<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-location-map",
  title: "위치와 지도 - GPS, Google Maps",
  date: "2025-12-13",
  summary: "안드로이드에서 GPS 위치를 가져오고 Google Maps를 활용하는 방법을 학습합니다. FusedLocationProviderClient, 지오코딩, 마커, 폴리라인까지 다룹니다.",
  category: "Technology/Android",
  tags: ["android", "location", "gps", "googlemap", "fusedlocation"],
  content: [
    "## 안드로이드 위치 서비스 개요",
    "",
    "안드로이드에서 위치 정보를 활용하는 앱은 매우 많습니다. 내비게이션, 배달 앱, 날씨 앱 등 다양한 분야에서 위치 기반 서비스(LBS)를 제공합니다.",
    "",
    "```mermaid",
    "graph TB",
    "    A[위치 서비스] --> B[위치 가져오기]",
    "    A --> C[지도 표시]",
    "    A --> D[지오코딩]",
    "    B --> B1[LocationManager<br>기본 API]",
    "    B --> B2[FusedLocationProvider<br>Google Play 서비스]",
    "    C --> C1[Google Maps SDK]",
    "    C --> C2[마커/폴리라인]",
    "    D --> D1[주소 → 좌표]",
    "    D --> D2[좌표 → 주소]",
    "```",
    "",
    "## 위치 권한 설정",
    "",
    "위치 정보에 접근하려면 반드시 적절한 권한을 선언하고, 런타임에 사용자에게 권한을 요청해야 합니다.",
    "",
    "### AndroidManifest.xml 권한 선언",
    "",
    "```xml",
    "<!-- 대략적 위치 (Wi-Fi, 기지국 기반, 약 100m 정확도) -->",
    "<uses-permission android:name=\"android.permission.ACCESS_COARSE_LOCATION\" />",
    "",
    "<!-- 정밀 위치 (GPS 기반, 약 1-10m 정확도) -->",
    "<uses-permission android:name=\"android.permission.ACCESS_FINE_LOCATION\" />",
    "",
    "<!-- 백그라운드 위치 (Android 10+, 별도 요청 필요) -->",
    "<uses-permission android:name=\"android.permission.ACCESS_BACKGROUND_LOCATION\" />",
    "```",
    "",
    "### 위치 권한 비교",
    "",
    "| 권한 | 정확도 | 소스 | API 레벨 |",
    "|------|--------|------|----------|",
    "| ACCESS_COARSE_LOCATION | ~100m | Wi-Fi, 기지국 | 1 |",
    "| ACCESS_FINE_LOCATION | ~1-10m | GPS | 1 |",
    "| ACCESS_BACKGROUND_LOCATION | - | 백그라운드 접근 허용 | 29 (Android 10) |",
    "",
    "### 런타임 권한 요청",
    "",
    "```java",
    "private final ActivityResultLauncher<String[]> locationPermissionLauncher =",
    "    registerForActivityResult(",
    "        new ActivityResultContracts.RequestMultiplePermissions(),",
    "        result -> {",
    "            Boolean fineLocation = result.getOrDefault(",
    "                Manifest.permission.ACCESS_FINE_LOCATION, false);",
    "            Boolean coarseLocation = result.getOrDefault(",
    "                Manifest.permission.ACCESS_COARSE_LOCATION, false);",
    "",
    "            if (fineLocation != null && fineLocation) {",
    "                Log.d(\"Location\", \"정밀 위치 권한 허용\");",
    "                getCurrentLocation();",
    "            } else if (coarseLocation != null && coarseLocation) {",
    "                Log.d(\"Location\", \"대략적 위치 권한만 허용\");",
    "                getCurrentLocation();",
    "            } else {",
    "                Log.d(\"Location\", \"위치 권한 거부됨\");",
    "            }",
    "        }",
    "    );",
    "",
    "private void requestLocationPermission() {",
    "    locationPermissionLauncher.launch(new String[]{",
    "        Manifest.permission.ACCESS_FINE_LOCATION,",
    "        Manifest.permission.ACCESS_COARSE_LOCATION",
    "    });",
    "}",
    "```",
    "",
    "## LocationManager vs FusedLocationProviderClient",
    "",
    "| 비교 항목 | LocationManager | FusedLocationProviderClient |",
    "|-----------|----------------|---------------------------|",
    "| 제공자 | 안드로이드 프레임워크 | Google Play 서비스 |",
    "| 사용 편의성 | 복잡함 (Provider 직접 관리) | 간편함 (자동 최적화) |",
    "| 배터리 효율 | 직접 최적화 필요 | 자동 배터리 최적화 |",
    "| 정확도 | Provider별 상이 | GPS+Wi-Fi+센서 융합 |",
    "| 의존성 | 없음 | Google Play 서비스 필요 |",
    "| 권장 여부 | 레거시 | **권장** |",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[FusedLocationProviderClient] --> B[GPS]",
    "    A --> C[Wi-Fi]",
    "    A --> D[기지국]",
    "    A --> E[센서]",
    "    B --> F[최적의 위치 결과]",
    "    C --> F",
    "    D --> F",
    "    E --> F",
    "```",
    "",
    "## FusedLocationProviderClient 사용",
    "",
    "### build.gradle 의존성 추가",
    "",
    "```groovy",
    "implementation 'com.google.android.gms:play-services-location:21.0.1'",
    "```",
    "",
    "### 마지막 위치 가져오기 (getLastLocation)",
    "",
    "```java",
    "private FusedLocationProviderClient fusedLocationClient;",
    "",
    "@Override",
    "protected void onCreate(Bundle savedInstanceState) {",
    "    super.onCreate(savedInstanceState);",
    "    setContentView(R.layout.activity_main);",
    "",
    "    fusedLocationClient = LocationServices.getFusedLocationProviderClient(this);",
    "",
    "    if (checkPermission()) {",
    "        getLastLocation();",
    "    } else {",
    "        requestLocationPermission();",
    "    }",
    "}",
    "",
    "private void getLastLocation() {",
    "    if (ActivityCompat.checkSelfPermission(this,",
    "            Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {",
    "        return;",
    "    }",
    "",
    "    fusedLocationClient.getLastLocation()",
    "        .addOnSuccessListener(this, location -> {",
    "            if (location != null) {",
    "                double lat = location.getLatitude();",
    "                double lng = location.getLongitude();",
    "                Log.d(\"Location\", \"위도: \" + lat + \", 경도: \" + lng);",
    "            } else {",
    "                Log.d(\"Location\", \"마지막 위치 없음. 위치 업데이트 요청 필요.\");",
    "            }",
    "        })",
    "        .addOnFailureListener(e -> {",
    "            Log.e(\"Location\", \"위치 가져오기 실패\", e);",
    "        });",
    "}",
    "```",
    "",
    "### 위치 업데이트 수신 (requestLocationUpdates)",
    "",
    "실시간 위치 추적이 필요한 경우 주기적으로 위치 업데이트를 받을 수 있습니다.",
    "",
    "```java",
    "private LocationCallback locationCallback;",
    "",
    "private void startLocationUpdates() {",
    "    LocationRequest locationRequest = new LocationRequest.Builder(",
    "        Priority.PRIORITY_HIGH_ACCURACY, 5000)  // 5초 간격",
    "        .setMinUpdateIntervalMillis(2000)        // 최소 2초 간격",
    "        .setMinUpdateDistanceMeters(10)           // 최소 10m 이동 시",
    "        .build();",
    "",
    "    locationCallback = new LocationCallback() {",
    "        @Override",
    "        public void onLocationResult(LocationResult locationResult) {",
    "            if (locationResult == null) return;",
    "",
    "            for (Location location : locationResult.getLocations()) {",
    "                double lat = location.getLatitude();",
    "                double lng = location.getLongitude();",
    "                float accuracy = location.getAccuracy();",
    "                Log.d(\"Location\", String.format(",
    "                    \"위도: %.6f, 경도: %.6f, 정확도: %.1fm\", lat, lng, accuracy));",
    "            }",
    "        }",
    "    };",
    "",
    "    if (ActivityCompat.checkSelfPermission(this,",
    "            Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {",
    "        fusedLocationClient.requestLocationUpdates(",
    "            locationRequest, locationCallback, Looper.getMainLooper());",
    "    }",
    "}",
    "",
    "private void stopLocationUpdates() {",
    "    if (locationCallback != null) {",
    "        fusedLocationClient.removeLocationUpdates(locationCallback);",
    "    }",
    "}",
    "",
    "@Override",
    "protected void onPause() {",
    "    super.onPause();",
    "    stopLocationUpdates();",
    "}",
    "```",
    "",
    "## Google Maps SDK 설정",
    "",
    "### 1단계: API 키 발급",
    "",
    "Google Cloud Console에서 Maps SDK for Android API 키를 발급받습니다.",
    "",
    "### 2단계: build.gradle 설정",
    "",
    "```groovy",
    "// 프로젝트 수준 build.gradle",
    "buildscript {",
    "    dependencies {",
    "        classpath 'com.google.gms:google-services:4.4.0'",
    "    }",
    "}",
    "",
    "// 앱 수준 build.gradle",
    "implementation 'com.google.android.gms:play-services-maps:18.2.0'",
    "```",
    "",
    "### 3단계: AndroidManifest.xml에 API 키 등록",
    "",
    "```xml",
    "<application>",
    "    <meta-data",
    "        android:name=\"com.google.android.geo.API_KEY\"",
    "        android:value=\"YOUR_API_KEY_HERE\" />",
    "</application>",
    "```",
    "",
    "## 지도 표시 - SupportMapFragment",
    "",
    "### 레이아웃",
    "",
    "```xml",
    "<fragment",
    "    android:id=\"@+id/mapFragment\"",
    "    android:name=\"com.google.android.gms.maps.SupportMapFragment\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"match_parent\" />",
    "```",
    "",
    "### GoogleMap 객체 사용",
    "",
    "```java",
    "public class MapActivity extends AppCompatActivity implements OnMapReadyCallback {",
    "    private GoogleMap googleMap;",
    "",
    "    @Override",
    "    protected void onCreate(Bundle savedInstanceState) {",
    "        super.onCreate(savedInstanceState);",
    "        setContentView(R.layout.activity_map);",
    "",
    "        SupportMapFragment mapFragment = (SupportMapFragment)",
    "            getSupportFragmentManager().findFragmentById(R.id.mapFragment);",
    "        if (mapFragment != null) {",
    "            mapFragment.getMapAsync(this);",
    "        }",
    "    }",
    "",
    "    @Override",
    "    public void onMapReady(@NonNull GoogleMap map) {",
    "        this.googleMap = map;",
    "",
    "        // 서울시청 좌표",
    "        LatLng seoul = new LatLng(37.5666, 126.9784);",
    "",
    "        // 마커 추가",
    "        googleMap.addMarker(new MarkerOptions()",
    "            .position(seoul)",
    "            .title(\"서울시청\")",
    "            .snippet(\"서울특별시 중구 세종대로 110\")",
    "            .icon(BitmapDescriptorFactory.defaultMarker(",
    "                BitmapDescriptorFactory.HUE_BLUE)));",
    "",
    "        // 카메라 이동",
    "        googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(seoul, 15));",
    "",
    "        // 지도 타입 설정",
    "        googleMap.setMapType(GoogleMap.MAP_TYPE_NORMAL);",
    "",
    "        // UI 설정",
    "        googleMap.getUiSettings().setZoomControlsEnabled(true);",
    "        googleMap.getUiSettings().setCompassEnabled(true);",
    "    }",
    "}",
    "```",
    "",
    "### 지도 타입",
    "",
    "| 타입 | 설명 |",
    "|------|------|",
    "| MAP_TYPE_NORMAL | 기본 도로 지도 |",
    "| MAP_TYPE_SATELLITE | 위성 사진 |",
    "| MAP_TYPE_HYBRID | 위성 + 도로 |",
    "| MAP_TYPE_TERRAIN | 지형도 |",
    "| MAP_TYPE_NONE | 빈 지도 |",
    "",
    "## 카메라 이동",
    "",
    "```java",
    "LatLng target = new LatLng(37.5666, 126.9784);",
    "",
    "// 즉시 이동",
    "googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(target, 15));",
    "",
    "// 애니메이션 이동 (부드럽게)",
    "googleMap.animateCamera(",
    "    CameraUpdateFactory.newLatLngZoom(target, 15),",
    "    2000,  // 2초간 애니메이션",
    "    new GoogleMap.CancelableCallback() {",
    "        @Override",
    "        public void onFinish() {",
    "            Log.d(\"Map\", \"카메라 이동 완료\");",
    "        }",
    "",
    "        @Override",
    "        public void onCancel() {",
    "            Log.d(\"Map\", \"카메라 이동 취소\");",
    "        }",
    "    }",
    ");",
    "",
    "// 줌 레벨: 1(세계) ~ 21(건물 수준)",
    "// 줌 인/아웃",
    "googleMap.animateCamera(CameraUpdateFactory.zoomIn());",
    "googleMap.animateCamera(CameraUpdateFactory.zoomOut());",
    "```",
    "",
    "## 지오코딩 (Geocoder)",
    "",
    "Geocoder를 사용하면 주소와 좌표를 상호 변환할 수 있습니다.",
    "",
    "```mermaid",
    "graph LR",
    "    A[주소 문자열] -->|지오코딩| B[위도/경도]",
    "    B -->|역 지오코딩| A",
    "```",
    "",
    "```java",
    "Geocoder geocoder = new Geocoder(this, Locale.KOREA);",
    "",
    "// 주소 → 좌표 (지오코딩)",
    "try {",
    "    List<Address> addresses = geocoder.getFromLocationName(",
    "        \"서울특별시 강남구 역삼동\", 5);",
    "    if (addresses != null && !addresses.isEmpty()) {",
    "        Address address = addresses.get(0);",
    "        double lat = address.getLatitude();",
    "        double lng = address.getLongitude();",
    "        Log.d(\"Geocoder\", \"좌표: \" + lat + \", \" + lng);",
    "    }",
    "} catch (IOException e) {",
    "    e.printStackTrace();",
    "}",
    "",
    "// 좌표 → 주소 (역 지오코딩)",
    "try {",
    "    List<Address> addresses = geocoder.getFromLocation(37.5666, 126.9784, 1);",
    "    if (addresses != null && !addresses.isEmpty()) {",
    "        Address address = addresses.get(0);",
    "        String fullAddress = address.getAddressLine(0);",
    "        Log.d(\"Geocoder\", \"주소: \" + fullAddress);",
    "    }",
    "} catch (IOException e) {",
    "    e.printStackTrace();",
    "}",
    "```",
    "",
    "## 폴리라인/원 그리기",
    "",
    "### 경로를 폴리라인으로 표시",
    "",
    "```java",
    "// 여러 지점을 연결하는 폴리라인",
    "PolylineOptions polylineOptions = new PolylineOptions()",
    "    .add(new LatLng(37.5666, 126.9784))   // 서울시청",
    "    .add(new LatLng(37.5512, 126.9882))   // 남산",
    "    .add(new LatLng(37.5326, 127.0246))   // 강남",
    "    .width(10)       // 선 두께",
    "    .color(Color.BLUE) // 선 색상",
    "    .geodesic(true);   // 측지선",
    "",
    "Polyline polyline = googleMap.addPolyline(polylineOptions);",
    "",
    "// 원 그리기",
    "CircleOptions circleOptions = new CircleOptions()",
    "    .center(new LatLng(37.5666, 126.9784))",
    "    .radius(500)           // 반지름 500m",
    "    .strokeColor(Color.RED)",
    "    .strokeWidth(3)",
    "    .fillColor(0x220000FF); // 반투명 파랑",
    "",
    "Circle circle = googleMap.addCircle(circleOptions);",
    "```",
    "",
    "## 현재 위치 표시",
    "",
    "```java",
    "@Override",
    "public void onMapReady(@NonNull GoogleMap map) {",
    "    this.googleMap = map;",
    "",
    "    if (ActivityCompat.checkSelfPermission(this,",
    "            Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {",
    "        googleMap.setMyLocationEnabled(true);",
    "        googleMap.getUiSettings().setMyLocationButtonEnabled(true);",
    "",
    "        fusedLocationClient.getLastLocation()",
    "            .addOnSuccessListener(location -> {",
    "                if (location != null) {",
    "                    LatLng myPos = new LatLng(",
    "                        location.getLatitude(),",
    "                        location.getLongitude());",
    "                    googleMap.animateCamera(",
    "                        CameraUpdateFactory.newLatLngZoom(myPos, 16));",
    "                }",
    "            });",
    "    }",
    "}",
    "```",
    "",
    "## 위치 기반 서비스 주의사항",
    "",
    "| 주의사항 | 설명 |",
    "|----------|------|",
    "| 배터리 소모 | GPS는 배터리를 많이 소모. 적절한 간격과 정확도 설정 |",
    "| 백그라운드 제한 | Android 8.0+에서 백그라운드 위치 접근 제한 |",
    "| Android 10+ | ACCESS_BACKGROUND_LOCATION 별도 요청 필요 |",
    "| Android 12+ | 대략적/정밀 위치 중 선택 가능 |",
    "| 실내 정확도 | GPS 신호 약한 실내에서 정확도 떨어짐 |",
    "| 개인정보 | 위치 데이터 수집 시 개인정보 처리방침 필요 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A{위치 사용<br>시나리오?} -->|앱 사용 중만| B[포그라운드만<br>FINE/COARSE]",
    "    A -->|항상 추적| C[백그라운드 필요<br>BACKGROUND_LOCATION]",
    "    B --> D[LocationRequest<br>적절한 간격 설정]",
    "    C --> E[Foreground Service<br>+ 지속 알림 필수]",
    "    D --> F[onPause에서<br>업데이트 중단]",
    "    E --> G[배터리 최적화<br>간격 늘리기]",
    "```",
    "",
    "## 정리",
    "",
    "위치와 지도 기능은 안드로이드 앱에서 매우 강력한 기능입니다. FusedLocationProviderClient를 사용하면 GPS, Wi-Fi, 기지국 신호를 융합하여 최적의 위치를 얻을 수 있으며, Google Maps SDK를 통해 풍부한 지도 기능을 구현할 수 있습니다. 항상 권한 관리, 배터리 소모, 백그라운드 제한을 고려하여 개발해야 합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
