<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-navigation",
  title: "화면 탐색 - ActionBar, Drawer, Tab, ViewPager",
  date: "2025-12-24",
  summary: "ActionBar, Toolbar, NavigationDrawer, TabLayout, ViewPager2, BottomNavigationView 등 Android 화면 탐색 컴포넌트를 총정리합니다.",
  category: "Technology/Android",
  tags: ["android", "actionbar", "toolbar", "drawer", "tablayout", "viewpager"],
  content: [
    "## ActionBar와 Toolbar",
    "",
    "ActionBar는 앱 상단에 표시되는 기본 탐색 바로, 앱 제목, 메뉴, 네비게이션 아이콘 등을 포함합니다. Toolbar는 ActionBar를 대체하는 더 유연한 위젯입니다.",
    "",
    "### ActionBar vs Toolbar 비교",
    "",
    "| 항목 | ActionBar | Toolbar |",
    "| --- | --- | --- |",
    "| 도입 시기 | API 11 (Android 3.0) | API 21 (Android 5.0) |",
    "| 커스터마이징 | 제한적 | 높은 자유도 |",
    "| 위치 | 화면 상단 고정 | 레이아웃 내 자유 배치 |",
    "| Material Design | 부분 지원 | 완전 지원 |",
    "| 권장 여부 | 비권장 | 권장 |",
    "",
    "```mermaid",
    "graph TD",
    "    A[앱 바 구현 방법] --> B[ActionBar<br/>기본 제공]",
    "    A --> C[Toolbar<br/>커스터마이징 가능]",
    "    C --> D[setSupportActionBar로<br/>ActionBar 역할 수행]",
    "    C --> E[독립적 위젯으로<br/>자유롭게 배치]",
    "    style A fill:#4CAF50,color:#fff",
    "    style C fill:#2196F3,color:#fff",
    "```",
    "",
    "### Toolbar 설정하기",
    "",
    "먼저 테마에서 기본 ActionBar를 비활성화합니다.",
    "",
    "```xml",
    "<!-- res/values/themes.xml -->",
    "<style name=\"Theme.MyApp\" parent=\"Theme.MaterialComponents.Light.NoActionBar\">",
    "    <item name=\"colorPrimary\">@color/purple_500</item>",
    "    <item name=\"colorPrimaryVariant\">@color/purple_700</item>",
    "</style>",
    "```",
    "",
    "레이아웃에 Toolbar를 추가합니다.",
    "",
    "```xml",
    "<androidx.appcompat.widget.Toolbar",
    "    android:id=\"@+id/toolbar\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"?attr/actionBarSize\"",
    "    android:background=\"?attr/colorPrimary\"",
    "    android:theme=\"@style/ThemeOverlay.AppCompat.Dark.ActionBar\"",
    "    app:popupTheme=\"@style/ThemeOverlay.AppCompat.Light\"",
    "    app:title=\"내 앱\" />",
    "```",
    "",
    "Activity에서 Toolbar를 ActionBar로 설정합니다.",
    "",
    "```java",
    "Toolbar toolbar = findViewById(R.id.toolbar);",
    "setSupportActionBar(toolbar);",
    "",
    "// 뒤로 가기 버튼 표시",
    "getSupportActionBar().setDisplayHomeAsUpEnabled(true);",
    "getSupportActionBar().setHomeAsUpIndicator(R.drawable.ic_menu);",
    "```",
    "",
    "## 옵션 메뉴 (Options Menu)",
    "",
    "### 메뉴 XML 정의",
    "",
    "```xml",
    "<!-- res/menu/menu_main.xml -->",
    "<menu xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    xmlns:app=\"http://schemas.android.com/apk/res-auto\">",
    "",
    "    <item",
    "        android:id=\"@+id/action_search\"",
    "        android:icon=\"@drawable/ic_search\"",
    "        android:title=\"검색\"",
    "        app:showAsAction=\"ifRoom\" />",
    "",
    "    <item",
    "        android:id=\"@+id/action_settings\"",
    "        android:title=\"설정\"",
    "        app:showAsAction=\"never\" />",
    "",
    "    <item",
    "        android:id=\"@+id/action_about\"",
    "        android:title=\"정보\"",
    "        app:showAsAction=\"never\" />",
    "</menu>",
    "```",
    "",
    "### showAsAction 속성",
    "",
    "| 값 | 설명 |",
    "| --- | --- |",
    "| `always` | 항상 ActionBar에 표시 |",
    "| `ifRoom` | 공간이 있으면 표시, 없으면 오버플로우 메뉴 |",
    "| `never` | 항상 오버플로우 메뉴에 표시 |",
    "| `withText` | 아이콘과 함께 텍스트도 표시 |",
    "| `collapseActionView` | 접힌 상태에서 확장 가능한 액션 뷰 |",
    "",
    "### 메뉴 생성 및 이벤트 처리",
    "",
    "```java",
    "@Override",
    "public boolean onCreateOptionsMenu(Menu menu) {",
    "    getMenuInflater().inflate(R.menu.menu_main, menu);",
    "    return true;",
    "}",
    "",
    "@Override",
    "public boolean onOptionsItemSelected(@NonNull MenuItem item) {",
    "    int id = item.getItemId();",
    "    if (id == R.id.action_search) {",
    "        openSearch();",
    "        return true;",
    "    } else if (id == R.id.action_settings) {",
    "        openSettings();",
    "        return true;",
    "    } else if (id == android.R.id.home) {",
    "        onBackPressed();",
    "        return true;",
    "    }",
    "    return super.onOptionsItemSelected(item);",
    "}",
    "```",
    "",
    "## NavigationDrawer",
    "",
    "NavigationDrawer는 화면 측면에서 슬라이드되어 나오는 탐색 패널입니다. `DrawerLayout`과 `NavigationView`를 조합하여 구현합니다.",
    "",
    "```mermaid",
    "graph LR",
    "    A[DrawerLayout] --> B[NavigationView<br/>왼쪽 서랍 메뉴]",
    "    A --> C[메인 콘텐츠<br/>FrameLayout]",
    "    B --> D[headerLayout<br/>상단 헤더]",
    "    B --> E[menu<br/>메뉴 항목들]",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "    style C fill:#FF9800,color:#fff",
    "```",
    "",
    "### 레이아웃 구성",
    "",
    "```xml",
    "<androidx.drawerlayout.widget.DrawerLayout",
    "    xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    xmlns:app=\"http://schemas.android.com/apk/res-auto\"",
    "    android:id=\"@+id/drawer_layout\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"match_parent\">",
    "",
    "    <!-- 메인 콘텐츠 -->",
    "    <FrameLayout",
    "        android:id=\"@+id/content_frame\"",
    "        android:layout_width=\"match_parent\"",
    "        android:layout_height=\"match_parent\" />",
    "",
    "    <!-- 네비게이션 드로어 -->",
    "    <com.google.android.material.navigation.NavigationView",
    "        android:id=\"@+id/nav_view\"",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"match_parent\"",
    "        android:layout_gravity=\"start\"",
    "        app:headerLayout=\"@layout/nav_header\"",
    "        app:menu=\"@menu/nav_menu\" />",
    "</androidx.drawerlayout.widget.DrawerLayout>",
    "```",
    "",
    "### 헤더 레이아웃",
    "",
    "```xml",
    "<!-- res/layout/nav_header.xml -->",
    "<LinearLayout xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"180dp\"",
    "    android:background=\"@color/purple_500\"",
    "    android:gravity=\"bottom\"",
    "    android:orientation=\"vertical\"",
    "    android:padding=\"16dp\">",
    "",
    "    <ImageView",
    "        android:layout_width=\"64dp\"",
    "        android:layout_height=\"64dp\"",
    "        android:src=\"@drawable/ic_profile\" />",
    "",
    "    <TextView",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"wrap_content\"",
    "        android:text=\"사용자 이름\"",
    "        android:textColor=\"@android:color/white\"",
    "        android:textSize=\"18sp\" />",
    "</LinearLayout>",
    "```",
    "",
    "### 네비게이션 메뉴",
    "",
    "```xml",
    "<!-- res/menu/nav_menu.xml -->",
    "<menu xmlns:android=\"http://schemas.android.com/apk/res/android\">",
    "    <group android:checkableBehavior=\"single\">",
    "        <item android:id=\"@+id/nav_home\"",
    "            android:icon=\"@drawable/ic_home\"",
    "            android:title=\"홈\" />",
    "        <item android:id=\"@+id/nav_gallery\"",
    "            android:icon=\"@drawable/ic_gallery\"",
    "            android:title=\"갤러리\" />",
    "        <item android:id=\"@+id/nav_settings\"",
    "            android:icon=\"@drawable/ic_settings\"",
    "            android:title=\"설정\" />",
    "    </group>",
    "</menu>",
    "```",
    "",
    "### Activity에서 Drawer 연결",
    "",
    "```java",
    "DrawerLayout drawerLayout = findViewById(R.id.drawer_layout);",
    "NavigationView navView = findViewById(R.id.nav_view);",
    "Toolbar toolbar = findViewById(R.id.toolbar);",
    "",
    "ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(",
    "    this, drawerLayout, toolbar,",
    "    R.string.nav_open, R.string.nav_close);",
    "drawerLayout.addDrawerListener(toggle);",
    "toggle.syncState();",
    "",
    "navView.setNavigationItemSelectedListener(item -> {",
    "    int id = item.getItemId();",
    "    if (id == R.id.nav_home) {",
    "        loadFragment(new HomeFragment());",
    "    } else if (id == R.id.nav_gallery) {",
    "        loadFragment(new GalleryFragment());",
    "    } else if (id == R.id.nav_settings) {",
    "        loadFragment(new SettingsFragment());",
    "    }",
    "    drawerLayout.closeDrawer(GravityCompat.START);",
    "    return true;",
    "});",
    "```",
    "",
    "## TabLayout + ViewPager2",
    "",
    "TabLayout과 ViewPager2를 조합하면 스와이프 가능한 탭 화면을 만들 수 있습니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[TabLayout] -->|TabLayoutMediator| B[ViewPager2]",
    "    B --> C[FragmentStateAdapter]",
    "    C --> D[Fragment 0<br/>홈]",
    "    C --> E[Fragment 1<br/>검색]",
    "    C --> F[Fragment 2<br/>알림]",
    "    style A fill:#FF9800,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "    style C fill:#4CAF50,color:#fff",
    "```",
    "",
    "### 레이아웃",
    "",
    "```xml",
    "<LinearLayout",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"match_parent\"",
    "    android:orientation=\"vertical\">",
    "",
    "    <com.google.android.material.tabs.TabLayout",
    "        android:id=\"@+id/tab_layout\"",
    "        android:layout_width=\"match_parent\"",
    "        android:layout_height=\"wrap_content\"",
    "        app:tabMode=\"fixed\"",
    "        app:tabGravity=\"fill\" />",
    "",
    "    <androidx.viewpager2.widget.ViewPager2",
    "        android:id=\"@+id/view_pager\"",
    "        android:layout_width=\"match_parent\"",
    "        android:layout_height=\"0dp\"",
    "        android:layout_weight=\"1\" />",
    "</LinearLayout>",
    "```",
    "",
    "### FragmentStateAdapter 구현",
    "",
    "```java",
    "public class MainPagerAdapter extends FragmentStateAdapter {",
    "",
    "    private final String[] tabTitles = {\"홈\", \"검색\", \"알림\"};",
    "",
    "    public MainPagerAdapter(@NonNull FragmentActivity fa) {",
    "        super(fa);",
    "    }",
    "",
    "    @NonNull",
    "    @Override",
    "    public Fragment createFragment(int position) {",
    "        switch (position) {",
    "            case 0: return new HomeFragment();",
    "            case 1: return new SearchFragment();",
    "            case 2: return new NotificationFragment();",
    "            default: return new HomeFragment();",
    "        }",
    "    }",
    "",
    "    @Override",
    "    public int getItemCount() {",
    "        return tabTitles.length;",
    "    }",
    "",
    "    public String getTabTitle(int position) {",
    "        return tabTitles[position];",
    "    }",
    "}",
    "```",
    "",
    "### TabLayout과 ViewPager2 연결",
    "",
    "```java",
    "ViewPager2 viewPager = findViewById(R.id.view_pager);",
    "TabLayout tabLayout = findViewById(R.id.tab_layout);",
    "MainPagerAdapter adapter = new MainPagerAdapter(this);",
    "viewPager.setAdapter(adapter);",
    "",
    "new TabLayoutMediator(tabLayout, viewPager, (tab, position) -> {",
    "    tab.setText(adapter.getTabTitle(position));",
    "    // 아이콘 설정도 가능",
    "    switch (position) {",
    "        case 0: tab.setIcon(R.drawable.ic_home); break;",
    "        case 1: tab.setIcon(R.drawable.ic_search); break;",
    "        case 2: tab.setIcon(R.drawable.ic_notification); break;",
    "    }",
    "}).attach();",
    "```",
    "",
    "### TabLayout 스타일 속성",
    "",
    "| 속성 | 설명 |",
    "| --- | --- |",
    "| `tabMode` | `fixed`(고정), `scrollable`(스크롤 가능) |",
    "| `tabGravity` | `fill`(균등 분배), `center`(가운데 정렬) |",
    "| `tabIndicatorColor` | 선택 인디케이터 색상 |",
    "| `tabIndicatorHeight` | 인디케이터 높이 |",
    "| `tabSelectedTextColor` | 선택된 탭 텍스트 색상 |",
    "| `tabTextColor` | 기본 탭 텍스트 색상 |",
    "",
    "## BottomNavigationView",
    "",
    "하단 탐색 바는 주요 화면 간 전환에 사용되는 Material Design 컴포넌트입니다.",
    "",
    "```xml",
    "<com.google.android.material.bottomnavigation.BottomNavigationView",
    "    android:id=\"@+id/bottom_nav\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:layout_gravity=\"bottom\"",
    "    app:menu=\"@menu/bottom_nav_menu\" />",
    "```",
    "",
    "```xml",
    "<!-- res/menu/bottom_nav_menu.xml -->",
    "<menu xmlns:android=\"http://schemas.android.com/apk/res/android\">",
    "    <item android:id=\"@+id/nav_home\"",
    "        android:icon=\"@drawable/ic_home\"",
    "        android:title=\"홈\" />",
    "    <item android:id=\"@+id/nav_search\"",
    "        android:icon=\"@drawable/ic_search\"",
    "        android:title=\"검색\" />",
    "    <item android:id=\"@+id/nav_profile\"",
    "        android:icon=\"@drawable/ic_person\"",
    "        android:title=\"프로필\" />",
    "</menu>",
    "```",
    "",
    "```java",
    "BottomNavigationView bottomNav = findViewById(R.id.bottom_nav);",
    "bottomNav.setOnItemSelectedListener(item -> {",
    "    Fragment selectedFragment = null;",
    "    int id = item.getItemId();",
    "    if (id == R.id.nav_home) {",
    "        selectedFragment = new HomeFragment();",
    "    } else if (id == R.id.nav_search) {",
    "        selectedFragment = new SearchFragment();",
    "    } else if (id == R.id.nav_profile) {",
    "        selectedFragment = new ProfileFragment();",
    "    }",
    "    if (selectedFragment != null) {",
    "        getSupportFragmentManager().beginTransaction()",
    "            .replace(R.id.fragment_container, selectedFragment)",
    "            .commit();",
    "    }",
    "    return true;",
    "});",
    "```",
    "",
    "## SearchView",
    "",
    "ActionBar에 검색 기능을 추가할 수 있습니다.",
    "",
    "```xml",
    "<item",
    "    android:id=\"@+id/action_search\"",
    "    android:icon=\"@drawable/ic_search\"",
    "    android:title=\"검색\"",
    "    app:showAsAction=\"ifRoom|collapseActionView\"",
    "    app:actionViewClass=\"androidx.appcompat.widget.SearchView\" />",
    "```",
    "",
    "```java",
    "@Override",
    "public boolean onCreateOptionsMenu(Menu menu) {",
    "    getMenuInflater().inflate(R.menu.menu_search, menu);",
    "    MenuItem searchItem = menu.findItem(R.id.action_search);",
    "    SearchView searchView = (SearchView) searchItem.getActionView();",
    "",
    "    searchView.setQueryHint(\"검색어를 입력하세요\");",
    "    searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {",
    "        @Override",
    "        public boolean onQueryTextSubmit(String query) {",
    "            performSearch(query);",
    "            return true;",
    "        }",
    "",
    "        @Override",
    "        public boolean onQueryTextChange(String newText) {",
    "            filterList(newText);",
    "            return true;",
    "        }",
    "    });",
    "    return true;",
    "}",
    "```",
    "",
    "## CoordinatorLayout과 AppBarLayout",
    "",
    "스크롤 시 앱 바가 접히거나 확장되는 동작을 구현합니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[CoordinatorLayout] --> B[AppBarLayout]",
    "    A --> C[스크롤 콘텐츠<br/>RecyclerView / NestedScrollView]",
    "    B --> D[Toolbar]",
    "    B --> E[CollapsingToolbarLayout]",
    "    E --> F[이미지 / 확장 콘텐츠]",
    "    E --> D",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "    style E fill:#FF9800,color:#fff",
    "```",
    "",
    "### CollapsingToolbarLayout",
    "",
    "```xml",
    "<androidx.coordinatorlayout.widget.CoordinatorLayout",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"match_parent\">",
    "",
    "    <com.google.android.material.appbar.AppBarLayout",
    "        android:layout_width=\"match_parent\"",
    "        android:layout_height=\"250dp\"",
    "        android:theme=\"@style/ThemeOverlay.AppCompat.Dark.ActionBar\">",
    "",
    "        <com.google.android.material.appbar.CollapsingToolbarLayout",
    "            android:layout_width=\"match_parent\"",
    "            android:layout_height=\"match_parent\"",
    "            app:layout_scrollFlags=\"scroll|exitUntilCollapsed\"",
    "            app:contentScrim=\"?attr/colorPrimary\"",
    "            app:title=\"상세 화면\">",
    "",
    "            <ImageView",
    "                android:layout_width=\"match_parent\"",
    "                android:layout_height=\"match_parent\"",
    "                android:scaleType=\"centerCrop\"",
    "                android:src=\"@drawable/header_image\"",
    "                app:layout_collapseMode=\"parallax\" />",
    "",
    "            <androidx.appcompat.widget.Toolbar",
    "                android:id=\"@+id/toolbar\"",
    "                android:layout_width=\"match_parent\"",
    "                android:layout_height=\"?attr/actionBarSize\"",
    "                app:layout_collapseMode=\"pin\" />",
    "        </com.google.android.material.appbar.CollapsingToolbarLayout>",
    "    </com.google.android.material.appbar.AppBarLayout>",
    "",
    "    <androidx.core.widget.NestedScrollView",
    "        android:layout_width=\"match_parent\"",
    "        android:layout_height=\"match_parent\"",
    "        app:layout_behavior=\"@string/appbar_scrolling_view_behavior\">",
    "",
    "        <!-- 콘텐츠 -->",
    "    </androidx.core.widget.NestedScrollView>",
    "</androidx.coordinatorlayout.widget.CoordinatorLayout>",
    "```",
    "",
    "### scrollFlags 옵션",
    "",
    "| 플래그 | 동작 |",
    "| --- | --- |",
    "| `scroll` | 스크롤에 반응 (필수) |",
    "| `enterAlways` | 아래로 스크롤 시 즉시 나타남 |",
    "| `enterAlwaysCollapsed` | 최소 높이로 먼저 나타남 |",
    "| `exitUntilCollapsed` | 최소 높이까지만 접힘 |",
    "| `snap` | 중간 상태 없이 완전히 접히거나 펼쳐짐 |",
    "",
    "## 탐색 컴포넌트 선택 가이드",
    "",
    "```mermaid",
    "graph TD",
    "    A{화면 전환 목적?} -->|주요 섹션 3~5개| B[BottomNavigationView]",
    "    A -->|관련 카테고리 전환| C[TabLayout + ViewPager2]",
    "    A -->|다양한 메뉴 항목| D[NavigationDrawer]",
    "    A -->|설정/보조 기능| E[옵션 메뉴]",
    "    style A fill:#9C27B0,color:#fff",
    "    style B fill:#4CAF50,color:#fff",
    "    style C fill:#2196F3,color:#fff",
    "    style D fill:#FF9800,color:#fff",
    "    style E fill:#607D8B,color:#fff",
    "```",
    "",
    "## 정리",
    "",
    "Android는 다양한 탐색 컴포넌트를 제공합니다. Toolbar로 상단 앱 바를 커스터마이징하고, NavigationDrawer로 풍부한 탐색 메뉴를 제공하며, TabLayout과 ViewPager2로 스와이프 탭 화면을 구현할 수 있습니다. BottomNavigationView는 주요 섹션 간 빠른 전환을 위한 하단 바를 제공합니다. CoordinatorLayout과 AppBarLayout을 활용하면 스크롤에 반응하는 세련된 앱 바 동작을 구현할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
