<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-overview",
  title: "Android 앱 개발 입문 - 프로젝트 구조와 핵심 개념",
  date: "2025-12-30",
  summary: "Android 앱 개발을 처음 시작하는 분들을 위한 입문 가이드입니다. 프로젝트 구조, Activity, XML 레이아웃, Gradle 빌드 시스템, 4대 컴포넌트 등 핵심 개념을 정리합니다.",
  category: "Technology/Android",
  tags: ["android", "java", "app", "mobile", "개발입문"],
  content: [
    "## Android란 무엇인가",
    "",
    "Android는 Google이 개발한 **모바일 운영체제**로, Linux 커널을 기반으로 합니다. 전 세계 스마트폰의 약 70% 이상이 Android를 사용하고 있으며, 스마트폰뿐 아니라 태블릿, TV, 웨어러블 기기 등 다양한 플랫폼에서 동작합니다.",
    "",
    "Android 앱은 주로 **Java** 또는 **Kotlin**으로 개발하며, 공식 IDE인 **Android Studio**를 사용합니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[Android 플랫폼 구조] --> B[Applications]",
    "    A --> C[Application Framework]",
    "    A --> D[Libraries & Android Runtime]",
    "    A --> E[Linux Kernel]",
    "    B --> B1[전화, 메시지, 브라우저 등]",
    "    C --> C1[Activity Manager]",
    "    C --> C2[Content Providers]",
    "    C --> C3[Resource Manager]",
    "    D --> D1[SQLite, OpenGL, WebKit]",
    "    D --> D2[ART / Dalvik VM]",
    "    E --> E1[디바이스 드라이버]",
    "    E --> E2[메모리/프로세스 관리]",
    "```",
    "",
    "---",
    "",
    "## Android Studio 프로젝트 구조",
    "",
    "Android Studio에서 새 프로젝트를 생성하면 다음과 같은 디렉토리 구조가 만들어집니다.",
    "",
    "```",
    "MyApplication/",
    "├── app/",
    "│   ├── src/",
    "│   │   ├── main/",
    "│   │   │   ├── java/com/example/myapp/   ← Java/Kotlin 소스 코드",
    "│   │   │   ├── res/                       ← 리소스 파일",
    "│   │   │   │   ├── layout/                ← XML 레이아웃",
    "│   │   │   │   ├── values/                ← 문자열, 색상, 스타일",
    "│   │   │   │   ├── drawable/              ← 이미지, 도형",
    "│   │   │   │   └── mipmap/                ← 앱 아이콘",
    "│   │   │   └── AndroidManifest.xml        ← 앱 설정 파일",
    "│   │   ├── test/                          ← 단위 테스트",
    "│   │   └── androidTest/                   ← 계측 테스트",
    "│   └── build.gradle                       ← 모듈 수준 빌드 설정",
    "├── gradle/",
    "├── build.gradle                           ← 프로젝트 수준 빌드 설정",
    "└── settings.gradle",
    "```",
    "",
    "| 디렉토리/파일 | 역할 |",
    "| --- | --- |",
    "| `app/src/main/java/` | 앱의 Java/Kotlin 소스 코드가 위치하는 곳 |",
    "| `app/src/main/res/layout/` | 화면 UI를 정의하는 XML 레이아웃 파일 |",
    "| `app/src/main/res/values/` | 문자열(strings.xml), 색상(colors.xml), 스타일(styles.xml) |",
    "| `AndroidManifest.xml` | 앱의 구성 요소, 권한, 메타데이터 선언 |",
    "| `build.gradle (Module)` | 의존성, SDK 버전, 빌드 타입 설정 |",
    "",
    "---",
    "",
    "## Activity란",
    "",
    "**Activity**는 Android 앱에서 **하나의 화면**을 나타내는 핵심 컴포넌트입니다. 사용자가 앱을 실행하면 가장 먼저 보이는 화면이 **MainActivity**입니다.",
    "",
    "```java",
    "package com.example.myapp;",
    "",
    "import android.os.Bundle;",
    "import androidx.appcompat.app.AppCompatActivity;",
    "",
    "public class MainActivity extends AppCompatActivity {",
    "",
    "    @Override",
    "    protected void onCreate(Bundle savedInstanceState) {",
    "        super.onCreate(savedInstanceState);",
    "        // res/layout/activity_main.xml 레이아웃을 이 Activity에 연결",
    "        setContentView(R.layout.activity_main);",
    "    }",
    "}",
    "```",
    "",
    "- `AppCompatActivity`를 상속하여 하위 호환성을 확보합니다.",
    "- `onCreate()`는 Activity가 생성될 때 호출되는 콜백 메서드입니다.",
    "- `setContentView()`로 화면에 표시할 XML 레이아웃을 지정합니다.",
    "",
    "---",
    "",
    "## XML 레이아웃 기초",
    "",
    "Android에서 UI는 **XML 파일**로 정의합니다. `res/layout/` 폴더에 위치하며, Java/Kotlin 코드에서 `R.layout.파일명`으로 참조합니다.",
    "",
    "```xml",
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
    "<LinearLayout",
    "    xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"match_parent\"",
    "    android:orientation=\"vertical\"",
    "    android:gravity=\"center\">",
    "",
    "    <TextView",
    "        android:id=\"@+id/tvHello\"",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"wrap_content\"",
    "        android:text=\"Hello, Android!\"",
    "        android:textSize=\"24sp\"",
    "        android:textColor=\"#333333\" />",
    "",
    "    <Button",
    "        android:id=\"@+id/btnClick\"",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"wrap_content\"",
    "        android:text=\"클릭하세요\"",
    "        android:layout_marginTop=\"16dp\" />",
    "",
    "</LinearLayout>",
    "```",
    "",
    "- `android:id=\"@+id/이름\"` : 코드에서 뷰를 참조하기 위한 고유 ID",
    "- `android:layout_width` / `layout_height` : 뷰의 크기 지정",
    "- `match_parent` : 부모 크기에 맞춤 / `wrap_content` : 내용 크기에 맞춤",
    "",
    "---",
    "",
    "## 첫 Hello World 앱 만들기",
    "",
    "### 1단계: 프로젝트 생성",
    "",
    "Android Studio에서 **File → New → New Project → Empty Activity**를 선택합니다.",
    "",
    "### 2단계: activity_main.xml 작성",
    "",
    "```xml",
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
    "<LinearLayout",
    "    xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"match_parent\"",
    "    android:orientation=\"vertical\"",
    "    android:gravity=\"center\">",
    "",
    "    <TextView",
    "        android:id=\"@+id/tvGreeting\"",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"wrap_content\"",
    "        android:text=\"안녕하세요!\"",
    "        android:textSize=\"30sp\" />",
    "",
    "    <Button",
    "        android:id=\"@+id/btnGreet\"",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"wrap_content\"",
    "        android:text=\"인사하기\"",
    "        android:layout_marginTop=\"20dp\" />",
    "",
    "</LinearLayout>",
    "```",
    "",
    "### 3단계: MainActivity.java 작성",
    "",
    "```java",
    "package com.example.helloworld;",
    "",
    "import android.os.Bundle;",
    "import android.widget.Button;",
    "import android.widget.TextView;",
    "import androidx.appcompat.app.AppCompatActivity;",
    "",
    "public class MainActivity extends AppCompatActivity {",
    "",
    "    @Override",
    "    protected void onCreate(Bundle savedInstanceState) {",
    "        super.onCreate(savedInstanceState);",
    "        setContentView(R.layout.activity_main);",
    "",
    "        TextView tvGreeting = findViewById(R.id.tvGreeting);",
    "        Button btnGreet = findViewById(R.id.btnGreet);",
    "",
    "        btnGreet.setOnClickListener(v -> {",
    "            tvGreeting.setText(\"Hello, Android World!\");",
    "        });",
    "    }",
    "}",
    "```",
    "",
    "### 4단계: 실행",
    "",
    "에뮬레이터 또는 실제 기기에서 실행하면 버튼을 누를 때 텍스트가 변경되는 것을 확인할 수 있습니다.",
    "",
    "---",
    "",
    "## R 클래스",
    "",
    "R 클래스는 Android 빌드 시스템이 **자동으로 생성**하는 클래스입니다. `res/` 폴더 내 모든 리소스에 대한 **정수형 ID**를 제공합니다.",
    "",
    "```java",
    "// R 클래스를 통해 리소스에 접근하는 예시",
    "setContentView(R.layout.activity_main);       // 레이아웃",
    "TextView tv = findViewById(R.id.tvGreeting);   // 뷰 ID",
    "String appName = getString(R.string.app_name); // 문자열 리소스",
    "int color = getColor(R.color.primary);          // 색상 리소스",
    "```",
    "",
    "| R 클래스 하위 | 대응 리소스 폴더 | 예시 |",
    "| --- | --- | --- |",
    "| `R.layout` | `res/layout/` | `R.layout.activity_main` |",
    "| `R.id` | XML의 `@+id` | `R.id.tvGreeting` |",
    "| `R.string` | `res/values/strings.xml` | `R.string.app_name` |",
    "| `R.drawable` | `res/drawable/` | `R.drawable.ic_launcher` |",
    "| `R.color` | `res/values/colors.xml` | `R.color.primary` |",
    "| `R.mipmap` | `res/mipmap/` | `R.mipmap.ic_launcher` |",
    "",
    "> **주의**: R 클래스는 빌드 시 자동 생성되므로 직접 수정하면 안 됩니다.",
    "",
    "---",
    "",
    "## Gradle 빌드 시스템",
    "",
    "Android Studio는 **Gradle**을 빌드 시스템으로 사용합니다. 프로젝트에는 두 가지 수준의 `build.gradle` 파일이 있습니다.",
    "",
    "### 프로젝트 수준 build.gradle",
    "",
    "```groovy",
    "// build.gradle (Project)",
    "buildscript {",
    "    repositories {",
    "        google()",
    "        mavenCentral()",
    "    }",
    "    dependencies {",
    "        classpath 'com.android.tools.build:gradle:8.1.0'",
    "    }",
    "}",
    "```",
    "",
    "### 모듈 수준 build.gradle (app)",
    "",
    "```groovy",
    "// build.gradle (Module: app)",
    "plugins {",
    "    id 'com.android.application'",
    "}",
    "",
    "android {",
    "    namespace 'com.example.myapp'",
    "    compileSdk 34",
    "",
    "    defaultConfig {",
    "        applicationId \"com.example.myapp\"",
    "        minSdk 24",
    "        targetSdk 34",
    "        versionCode 1",
    "        versionName \"1.0\"",
    "    }",
    "",
    "    buildTypes {",
    "        release {",
    "            minifyEnabled false",
    "            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'",
    "        }",
    "    }",
    "}",
    "",
    "dependencies {",
    "    implementation 'androidx.appcompat:appcompat:1.6.1'",
    "    implementation 'com.google.android.material:material:1.9.0'",
    "    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'",
    "}",
    "```",
    "",
    "| 속성 | 설명 |",
    "| --- | --- |",
    "| `compileSdk` | 컴파일 시 사용하는 SDK 버전 |",
    "| `minSdk` | 앱이 지원하는 최소 SDK 버전 |",
    "| `targetSdk` | 앱이 대상으로 하는 SDK 버전 |",
    "| `applicationId` | 앱의 고유 식별자 (패키지명) |",
    "| `versionCode` | 내부 버전 번호 (정수) |",
    "| `versionName` | 사용자에게 보이는 버전 이름 |",
    "",
    "---",
    "",
    "## AVD(에뮬레이터)와 실제 기기 실행",
    "",
    "### AVD (Android Virtual Device)",
    "",
    "Android Studio에 내장된 에뮬레이터로, 실제 기기 없이도 앱을 테스트할 수 있습니다.",
    "",
    "1. **Tools → Device Manager → Create Device**",
    "2. 원하는 디바이스(Pixel 6 등) 선택",
    "3. 시스템 이미지(API Level) 다운로드 및 선택",
    "4. AVD 생성 후 실행 버튼(▶) 클릭",
    "",
    "### 실제 기기 연결",
    "",
    "1. 스마트폰에서 **설정 → 개발자 옵션 → USB 디버깅** 활성화",
    "2. USB 케이블로 PC에 연결",
    "3. Android Studio에서 기기가 인식되면 실행 버튼 클릭",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[코드 작성] --> B[빌드 Gradle]",
    "    B --> C{실행 환경 선택}",
    "    C -->|에뮬레이터| D[AVD 실행]",
    "    C -->|실제 기기| E[USB 디버깅 연결]",
    "    D --> F[앱 설치 및 실행]",
    "    E --> F",
    "```",
    "",
    "---",
    "",
    "## Android 앱의 4대 컴포넌트",
    "",
    "Android 앱은 **4가지 핵심 컴포넌트**로 구성됩니다. 각 컴포넌트는 고유한 역할을 가지며, AndroidManifest.xml에 등록해야 합니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[Android 4대 컴포넌트] --> B[Activity]",
    "    A --> C[Service]",
    "    A --> D[BroadcastReceiver]",
    "    A --> E[ContentProvider]",
    "    B --> B1[사용자에게 보이는 화면 UI]",
    "    C --> C1[백그라운드 작업 수행]",
    "    D --> D1[시스템/앱 이벤트 수신]",
    "    E --> E1[앱 간 데이터 공유]",
    "```",
    "",
    "### Activity",
    "",
    "사용자와 상호작용하는 **화면(UI)**를 담당합니다. 앱에서 가장 많이 사용하는 컴포넌트입니다.",
    "",
    "```java",
    "// AndroidManifest.xml에 등록",
    "<activity android:name=\".MainActivity\">",
    "    <intent-filter>",
    "        <action android:name=\"android.intent.action.MAIN\" />",
    "        <category android:name=\"android.intent.category.LAUNCHER\" />",
    "    </intent-filter>",
    "</activity>",
    "```",
    "",
    "### Service",
    "",
    "사용자 인터페이스 없이 **백그라운드에서 작업**을 수행합니다. 음악 재생, 파일 다운로드 등에 사용됩니다.",
    "",
    "```java",
    "public class MusicService extends Service {",
    "    @Override",
    "    public int onStartCommand(Intent intent, int flags, int startId) {",
    "        // 백그라운드 음악 재생 로직",
    "        return START_STICKY;",
    "    }",
    "",
    "    @Override",
    "    public IBinder onBind(Intent intent) {",
    "        return null;",
    "    }",
    "}",
    "```",
    "",
    "### BroadcastReceiver",
    "",
    "시스템 또는 앱에서 발생하는 **브로드캐스트 메시지**를 수신합니다. 예를 들어 배터리 부족, 네트워크 변경 등의 이벤트를 감지합니다.",
    "",
    "```java",
    "public class NetworkReceiver extends BroadcastReceiver {",
    "    @Override",
    "    public void onReceive(Context context, Intent intent) {",
    "        if (ConnectivityManager.CONNECTIVITY_ACTION.equals(intent.getAction())) {",
    "            // 네트워크 상태 변경 처리",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### ContentProvider",
    "",
    "앱 간 **데이터를 공유**하기 위한 인터페이스입니다. 연락처, 갤러리 등의 데이터에 접근할 때 사용됩니다.",
    "",
    "```java",
    "// ContentProvider를 통해 연락처 조회",
    "Cursor cursor = getContentResolver().query(",
    "    ContactsContract.Contacts.CONTENT_URI,",
    "    null, null, null, null",
    ");",
    "```",
    "",
    "| 컴포넌트 | 역할 | Manifest 등록 | 활성화 방법 |",
    "| --- | --- | --- | --- |",
    "| Activity | 화면 UI 제공 | 필수 | Intent |",
    "| Service | 백그라운드 작업 | 필수 | startService / bindService |",
    "| BroadcastReceiver | 이벤트 수신 | 선택(동적 등록 가능) | sendBroadcast |",
    "| ContentProvider | 데이터 공유 | 필수 | ContentResolver |",
    "",
    "---",
    "",
    "## SDK 버전과 API 레벨",
    "",
    "Android SDK 버전은 **API 레벨**이라는 정수 값으로 구분됩니다. 각 Android 버전에는 고유한 API 레벨이 할당됩니다.",
    "",
    "| Android 버전 | API 레벨 | 코드명 | 주요 특징 |",
    "| --- | --- | --- | --- |",
    "| Android 14 | 34 | Upside Down Cake | 사진 선택기, 잠금 화면 커스텀 |",
    "| Android 13 | 33 | Tiramisu | 알림 권한, 테마 아이콘 |",
    "| Android 12 | 31-32 | Snow Cone | Material You, 스플래시 화면 API |",
    "| Android 11 | 30 | Red Velvet Cake | 범위 지정 저장소 강제 |",
    "| Android 10 | 29 | Quince Tart | 다크 모드, 제스처 네비게이션 |",
    "| Android 9 | 28 | Pie | 노치 지원, 적응형 배터리 |",
    "| Android 8 | 26-27 | Oreo | 알림 채널, PIP 모드 |",
    "",
    "### SDK 버전 설정 가이드",
    "",
    "```mermaid",
    "graph LR",
    "    A[minSdk] -->|지원하는 최소 버전| B[targetSdk]",
    "    B -->|최적화 대상 버전| C[compileSdk]",
    "    C -->|컴파일에 사용하는 최신 버전| D[최신 SDK]",
    "    style A fill:#ff6b6b,color:#fff",
    "    style B fill:#ffd93d,color:#333",
    "    style C fill:#6bcf7f,color:#fff",
    "```",
    "",
    "- **minSdk**: 앱을 설치할 수 있는 최소 Android 버전. 낮을수록 더 많은 기기를 지원하지만 최신 API를 사용할 수 없습니다.",
    "- **targetSdk**: 앱이 최적화된 대상 버전. Google Play에서는 최신 targetSdk를 요구합니다.",
    "- **compileSdk**: 빌드 시 사용하는 SDK 버전. 항상 최신 버전을 권장합니다.",
    "",
    "---",
    "",
    "## AndroidManifest.xml 살펴보기",
    "",
    "AndroidManifest.xml은 앱의 **모든 구성 정보**를 담고 있는 중요한 파일입니다.",
    "",
    "```xml",
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
    "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    package=\"com.example.myapp\">",
    "",
    "    <!-- 권한 선언 -->",
    "    <uses-permission android:name=\"android.permission.INTERNET\" />",
    "",
    "    <application",
    "        android:allowBackup=\"true\"",
    "        android:icon=\"@mipmap/ic_launcher\"",
    "        android:label=\"@string/app_name\"",
    "        android:theme=\"@style/Theme.MyApp\">",
    "",
    "        <!-- 메인 Activity -->",
    "        <activity",
    "            android:name=\".MainActivity\"",
    "            android:exported=\"true\">",
    "            <intent-filter>",
    "                <action android:name=\"android.intent.action.MAIN\" />",
    "                <category android:name=\"android.intent.category.LAUNCHER\" />",
    "            </intent-filter>",
    "        </activity>",
    "",
    "        <!-- 다른 Activity -->",
    "        <activity android:name=\".SecondActivity\" />",
    "",
    "    </application>",
    "</manifest>",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "이 글에서는 Android 앱 개발의 기초 개념을 살펴보았습니다.",
    "",
    "```mermaid",
    "mindmap",
    "  root((Android 입문))",
    "    프로젝트 구조",
    "      java 소스",
    "      res 리소스",
    "      AndroidManifest",
    "    핵심 개념",
    "      Activity",
    "      XML 레이아웃",
    "      R 클래스",
    "    빌드 & 실행",
    "      Gradle",
    "      AVD 에뮬레이터",
    "      USB 디버깅",
    "    4대 컴포넌트",
    "      Activity",
    "      Service",
    "      BroadcastReceiver",
    "      ContentProvider",
    "```",
    "",
    "다음 글에서는 **Android 레이아웃 시스템**을 자세히 다루겠습니다. LinearLayout부터 ConstraintLayout까지, 화면 구성의 핵심을 정리합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
