<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-lifecycle",
  title: "Activity 생명주기(Lifecycle) 완전 이해",
  date: "2025-12-26",
  summary: "Android Activity의 생명주기 7개 콜백을 상세히 정리합니다. 상태 다이어그램, 화면 회전 대응, onSaveInstanceState, ViewModel, Fragment 생명주기와의 관계까지 다룹니다.",
  category: "Technology/Android",
  tags: ["android", "lifecycle", "activity", "oncreate", "onresume", "savedinstancestate"],
  content: [
    "## 생명주기(Lifecycle)란",
    "",
    "Android Activity는 생성부터 소멸까지 여러 **상태(State)**를 거칩니다. 각 상태 전환 시 시스템이 특정 **콜백 메서드**를 호출하며, 개발자는 이 콜백에서 적절한 처리를 수행합니다.",
    "",
    "생명주기를 올바르게 이해하고 처리하지 않으면 다음과 같은 문제가 발생합니다:",
    "",
    "- 화면 회전 시 데이터 손실",
    "- 메모리 누수 (리소스 미해제)",
    "- 앱 비정상 종료 (크래시)",
    "- 백그라운드에서 불필요한 리소스 소비",
    "",
    "---",
    "",
    "## 7개 생명주기 콜백",
    "",
    "Activity의 생명주기는 **7개의 콜백 메서드**로 구성됩니다.",
    "",
    "```mermaid",
    "stateDiagram-v2",
    "    [*] --> onCreate",
    "    onCreate --> onStart",
    "    onStart --> onResume",
    "    onResume --> onPause : 부분적으로 가려짐",
    "    onPause --> onResume : 다시 포커스",
    "    onPause --> onStop : 완전히 안 보임",
    "    onStop --> onRestart : 다시 보임",
    "    onRestart --> onStart",
    "    onStop --> onDestroy : 종료",
    "    onDestroy --> [*]",
    "```",
    "",
    "| 콜백 | 호출 시점 | 주요 작업 |",
    "| --- | --- | --- |",
    "| `onCreate()` | Activity 최초 생성 시 | 레이아웃 설정, 변수 초기화, 뷰 바인딩 |",
    "| `onStart()` | 화면에 보이기 시작할 때 | UI 관련 리소스 등록 |",
    "| `onResume()` | 사용자와 상호작용 가능할 때 | 카메라, 센서 시작, 애니메이션 시작 |",
    "| `onPause()` | 다른 Activity에 의해 일부 가려질 때 | 경량 리소스 해제, 데이터 임시 저장 |",
    "| `onStop()` | 화면에서 완전히 사라질 때 | 무거운 리소스 해제, DB 저장 |",
    "| `onDestroy()` | Activity 종료 또는 Configuration Change 시 | 모든 리소스 정리 |",
    "| `onRestart()` | onStop 후 다시 보일 때 | onStart 전 준비 작업 |",
    "",
    "---",
    "",
    "## 각 콜백 상세 설명",
    "",
    "### onCreate()",
    "",
    "Activity가 **처음 생성**될 때 단 한 번 호출됩니다. 전체 생명주기에서 가장 먼저 실행되며, **필수 초기화**를 수행합니다.",
    "",
    "```java",
    "@Override",
    "protected void onCreate(Bundle savedInstanceState) {",
    "    super.onCreate(savedInstanceState);",
    "    setContentView(R.layout.activity_main);",
    "",
    "    // 뷰 참조",
    "    TextView tvTitle = findViewById(R.id.tvTitle);",
    "    Button btnClick = findViewById(R.id.btnClick);",
    "",
    "    // 이벤트 리스너 등록",
    "    btnClick.setOnClickListener(v -> {",
    "        tvTitle.setText(\"클릭됨!\");",
    "    });",
    "",
    "    // 저장된 상태 복원",
    "    if (savedInstanceState != null) {",
    "        String savedText = savedInstanceState.getString(\"text_key\");",
    "        tvTitle.setText(savedText);",
    "    }",
    "}",
    "```",
    "",
    "- `setContentView()`: XML 레이아웃을 화면에 연결",
    "- `findViewById()`: XML에서 정의한 뷰를 코드에서 참조",
    "- `savedInstanceState`: 이전에 저장된 상태를 복원 (화면 회전 등)",
    "",
    "### onStart()",
    "",
    "Activity가 **사용자에게 보이기 시작**하는 시점입니다. 아직 상호작용은 불가능합니다.",
    "",
    "```java",
    "@Override",
    "protected void onStart() {",
    "    super.onStart();",
    "    // BroadcastReceiver 등록",
    "    // 위치 업데이트 시작",
    "    // UI 업데이트 준비",
    "}",
    "```",
    "",
    "### onResume()",
    "",
    "Activity가 **포그라운드에서 사용자와 상호작용** 가능한 상태입니다. 앱의 \"활성\" 상태입니다.",
    "",
    "```java",
    "@Override",
    "protected void onResume() {",
    "    super.onResume();",
    "    // 카메라 프리뷰 시작",
    "    // 센서 리스너 등록",
    "    // 애니메이션 재개",
    "    // 타이머 시작",
    "}",
    "```",
    "",
    "### onPause()",
    "",
    "다른 Activity가 포그라운드로 오면서 **현재 Activity가 부분적으로 가려질 때** 호출됩니다. 빠르게 실행되어야 하며, 무거운 작업은 여기서 하면 안 됩니다.",
    "",
    "```java",
    "@Override",
    "protected void onPause() {",
    "    super.onPause();",
    "    // 카메라 프리뷰 중지",
    "    // 센서 리스너 해제",
    "    // 애니메이션 일시 정지",
    "}",
    "```",
    "",
    "### onStop()",
    "",
    "Activity가 **화면에서 완전히 사라질 때** 호출됩니다. 홈 버튼, 다른 앱 전환 등에서 발생합니다.",
    "",
    "```java",
    "@Override",
    "protected void onStop() {",
    "    super.onStop();",
    "    // 데이터베이스에 데이터 저장",
    "    // 네트워크 연결 해제",
    "    // 무거운 리소스 해제",
    "}",
    "```",
    "",
    "### onRestart()",
    "",
    "`onStop()` 이후 Activity가 **다시 보일 때** 호출됩니다. `onStart()` 이전에 실행됩니다.",
    "",
    "```java",
    "@Override",
    "protected void onRestart() {",
    "    super.onRestart();",
    "    // 데이터 새로고침",
    "    // UI 업데이트",
    "}",
    "```",
    "",
    "### onDestroy()",
    "",
    "Activity가 **완전히 종료**될 때 호출됩니다. `finish()` 호출이나 Configuration Change(화면 회전 등)에 의해 발생합니다.",
    "",
    "```java",
    "@Override",
    "protected void onDestroy() {",
    "    super.onDestroy();",
    "    // 모든 리소스 정리",
    "    // 스레드 종료",
    "    // 핸들러 메시지 제거",
    "}",
    "```",
    "",
    "---",
    "",
    "## 생명주기 시나리오별 흐름",
    "",
    "### 시나리오 1: 앱 처음 실행",
    "",
    "```",
    "onCreate → onStart → onResume",
    "```",
    "",
    "### 시나리오 2: 홈 버튼 누름 (백그라운드)",
    "",
    "```",
    "onPause → onStop",
    "```",
    "",
    "### 시나리오 3: 백그라운드에서 복귀",
    "",
    "```",
    "onRestart → onStart → onResume",
    "```",
    "",
    "### 시나리오 4: 뒤로가기 버튼으로 종료",
    "",
    "```",
    "onPause → onStop → onDestroy",
    "```",
    "",
    "### 시나리오 5: 다이얼로그로 부분적 가려짐",
    "",
    "```",
    "onPause (다이얼로그 표시) → onResume (다이얼로그 닫힘)",
    "```",
    "",
    "### 시나리오 6: A에서 B로 화면 전환",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant A as Activity A",
    "    participant System as Android 시스템",
    "    participant B as Activity B",
    "    A->>System: startActivity(B)",
    "    System->>A: onPause()",
    "    System->>B: onCreate()",
    "    System->>B: onStart()",
    "    System->>B: onResume()",
    "    System->>A: onStop()",
    "```",
    "",
    "> **중요**: A의 `onPause()`가 완료된 후에야 B가 시작됩니다. 따라서 onPause()에서 무거운 작업을 하면 화면 전환이 느려집니다.",
    "",
    "---",
    "",
    "## 화면 회전 시 생명주기",
    "",
    "화면이 회전하면 Activity가 **파괴 후 재생성**됩니다. 이것을 **Configuration Change**라고 합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant Activity as Activity",
    "    participant System as Android 시스템",
    "    Note over Activity: 세로 모드",
    "    Activity->>System: 화면 회전 감지",
    "    System->>Activity: onPause()",
    "    System->>Activity: onStop()",
    "    System->>Activity: onSaveInstanceState()",
    "    System->>Activity: onDestroy()",
    "    Note over Activity: Activity 파괴됨",
    "    System->>Activity: onCreate(savedInstanceState)",
    "    System->>Activity: onStart()",
    "    System->>Activity: onRestoreInstanceState()",
    "    System->>Activity: onResume()",
    "    Note over Activity: 가로 모드로 재생성",
    "```",
    "",
    "### Configuration Change의 종류",
    "",
    "| 변경 사항 | 설명 |",
    "| --- | --- |",
    "| 화면 회전 | `orientation` 변경 |",
    "| 화면 크기 | `screenSize` 변경 (멀티 윈도우) |",
    "| 언어 변경 | `locale` 변경 |",
    "| 폰트 크기 | `fontScale` 변경 |",
    "| 다크 모드 | `uiMode` 변경 |",
    "",
    "---",
    "",
    "## onSaveInstanceState / onRestoreInstanceState",
    "",
    "화면 회전 등으로 Activity가 재생성될 때 **데이터를 보존**하기 위해 사용합니다.",
    "",
    "### 데이터 저장",
    "",
    "```java",
    "@Override",
    "protected void onSaveInstanceState(Bundle outState) {",
    "    super.onSaveInstanceState(outState);",
    "",
    "    // 현재 상태 저장",
    "    outState.putString(\"user_input\", etInput.getText().toString());",
    "    outState.putInt(\"counter\", counter);",
    "    outState.putBoolean(\"is_logged_in\", isLoggedIn);",
    "    outState.putStringArrayList(\"item_list\", itemList);",
    "}",
    "```",
    "",
    "### 데이터 복원 (방법 1: onCreate에서)",
    "",
    "```java",
    "@Override",
    "protected void onCreate(Bundle savedInstanceState) {",
    "    super.onCreate(savedInstanceState);",
    "    setContentView(R.layout.activity_main);",
    "",
    "    if (savedInstanceState != null) {",
    "        String savedInput = savedInstanceState.getString(\"user_input\");",
    "        counter = savedInstanceState.getInt(\"counter\");",
    "        isLoggedIn = savedInstanceState.getBoolean(\"is_logged_in\");",
    "        itemList = savedInstanceState.getStringArrayList(\"item_list\");",
    "",
    "        etInput.setText(savedInput);",
    "        tvCounter.setText(String.valueOf(counter));",
    "    }",
    "}",
    "```",
    "",
    "### 데이터 복원 (방법 2: onRestoreInstanceState에서)",
    "",
    "```java",
    "@Override",
    "protected void onRestoreInstanceState(Bundle savedInstanceState) {",
    "    super.onRestoreInstanceState(savedInstanceState);",
    "",
    "    // savedInstanceState가 null이 아닌 경우에만 호출됨",
    "    counter = savedInstanceState.getInt(\"counter\");",
    "    tvCounter.setText(String.valueOf(counter));",
    "}",
    "```",
    "",
    "| 복원 위치 | 특징 |",
    "| --- | --- |",
    "| `onCreate()` | null 체크 필요, 초기화와 함께 처리 |",
    "| `onRestoreInstanceState()` | null 체크 불필요 (항상 non-null), onStart() 이후 호출 |",
    "",
    "---",
    "",
    "## ViewModel로 데이터 유지",
    "",
    "**ViewModel**은 Configuration Change(화면 회전 등)에서도 데이터를 유지하는 **AAC(Android Architecture Components)** 구성요소입니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[Activity 생성] --> B[ViewModel 생성]",
    "    B --> C[화면 회전 - Activity 재생성]",
    "    C --> D[ViewModel 유지됨!]",
    "    D --> E[Activity 종료 finish]",
    "    E --> F[ViewModel 소멸]",
    "```",
    "",
    "### ViewModel 구현",
    "",
    "```java",
    "// 1. ViewModel 클래스 생성",
    "public class MainViewModel extends ViewModel {",
    "    private int counter = 0;",
    "    private MutableLiveData<String> userName = new MutableLiveData<>();",
    "",
    "    public int getCounter() { return counter; }",
    "    public void incrementCounter() { counter++; }",
    "",
    "    public LiveData<String> getUserName() { return userName; }",
    "    public void setUserName(String name) { userName.setValue(name); }",
    "",
    "    @Override",
    "    protected void onCleared() {",
    "        super.onCleared();",
    "        // ViewModel이 소멸될 때 정리 작업",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "// 2. Activity에서 ViewModel 사용",
    "public class MainActivity extends AppCompatActivity {",
    "",
    "    private MainViewModel viewModel;",
    "",
    "    @Override",
    "    protected void onCreate(Bundle savedInstanceState) {",
    "        super.onCreate(savedInstanceState);",
    "        setContentView(R.layout.activity_main);",
    "",
    "        // ViewModel 획득 (화면 회전 시에도 동일한 인스턴스)",
    "        viewModel = new ViewModelProvider(this).get(MainViewModel.class);",
    "",
    "        TextView tvCounter = findViewById(R.id.tvCounter);",
    "        Button btnCount = findViewById(R.id.btnCount);",
    "",
    "        // 현재 값 표시",
    "        tvCounter.setText(String.valueOf(viewModel.getCounter()));",
    "",
    "        btnCount.setOnClickListener(v -> {",
    "            viewModel.incrementCounter();",
    "            tvCounter.setText(String.valueOf(viewModel.getCounter()));",
    "        });",
    "",
    "        // LiveData 관찰",
    "        viewModel.getUserName().observe(this, name -> {",
    "            tvName.setText(name);",
    "        });",
    "    }",
    "}",
    "```",
    "",
    "### onSaveInstanceState vs ViewModel 비교",
    "",
    "| 특성 | onSaveInstanceState | ViewModel |",
    "| --- | --- | --- |",
    "| 데이터 크기 | 소량 (Bundle 직렬화) | 제한 없음 (메모리) |",
    "| 프로세스 종료 후 복원 | 가능 | 불가능 |",
    "| Configuration Change 대응 | 수동 저장/복원 | 자동 유지 |",
    "| 데이터 타입 | 기본 타입, Parcelable | 모든 객체 |",
    "| 비동기 작업 | 부적합 | 적합 |",
    "| 사용 사례 | UI 상태 (스크롤 위치 등) | 비즈니스 데이터 |",
    "",
    "> **권장**: ViewModel과 onSaveInstanceState를 함께 사용합니다. ViewModel로 데이터를 유지하고, 프로세스 종료에 대비하여 onSaveInstanceState로 핵심 상태를 저장합니다.",
    "",
    "---",
    "",
    "## 로그로 생명주기 확인하기 (실습)",
    "",
    "실제로 각 콜백이 언제 호출되는지 **Log**를 찍어서 확인해봅시다.",
    "",
    "```java",
    "import android.util.Log;",
    "",
    "public class MainActivity extends AppCompatActivity {",
    "",
    "    private static final String TAG = \"LifecycleTest\";",
    "",
    "    @Override",
    "    protected void onCreate(Bundle savedInstanceState) {",
    "        super.onCreate(savedInstanceState);",
    "        setContentView(R.layout.activity_main);",
    "        Log.d(TAG, \">>> onCreate 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onStart() {",
    "        super.onStart();",
    "        Log.d(TAG, \">>> onStart 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onResume() {",
    "        super.onResume();",
    "        Log.d(TAG, \">>> onResume 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onPause() {",
    "        super.onPause();",
    "        Log.d(TAG, \">>> onPause 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onStop() {",
    "        super.onStop();",
    "        Log.d(TAG, \">>> onStop 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onRestart() {",
    "        super.onRestart();",
    "        Log.d(TAG, \">>> onRestart 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onDestroy() {",
    "        super.onDestroy();",
    "        Log.d(TAG, \">>> onDestroy 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onSaveInstanceState(Bundle outState) {",
    "        super.onSaveInstanceState(outState);",
    "        Log.d(TAG, \">>> onSaveInstanceState 호출됨\");",
    "    }",
    "",
    "    @Override",
    "    protected void onRestoreInstanceState(Bundle savedInstanceState) {",
    "        super.onRestoreInstanceState(savedInstanceState);",
    "        Log.d(TAG, \">>> onRestoreInstanceState 호출됨\");",
    "    }",
    "}",
    "```",
    "",
    "### Logcat에서 확인",
    "",
    "Android Studio에서 **Logcat** 창을 열고, 필터에 `LifecycleTest`를 입력하면 생명주기 콜백 호출 순서를 확인할 수 있습니다.",
    "",
    "```",
    "// 앱 실행 시",
    "D/LifecycleTest: >>> onCreate 호출됨",
    "D/LifecycleTest: >>> onStart 호출됨",
    "D/LifecycleTest: >>> onResume 호출됨",
    "",
    "// 홈 버튼 누를 때",
    "D/LifecycleTest: >>> onPause 호출됨",
    "D/LifecycleTest: >>> onStop 호출됨",
    "",
    "// 앱으로 복귀할 때",
    "D/LifecycleTest: >>> onRestart 호출됨",
    "D/LifecycleTest: >>> onStart 호출됨",
    "D/LifecycleTest: >>> onResume 호출됨",
    "",
    "// 화면 회전 시",
    "D/LifecycleTest: >>> onPause 호출됨",
    "D/LifecycleTest: >>> onStop 호출됨",
    "D/LifecycleTest: >>> onSaveInstanceState 호출됨",
    "D/LifecycleTest: >>> onDestroy 호출됨",
    "D/LifecycleTest: >>> onCreate 호출됨",
    "D/LifecycleTest: >>> onStart 호출됨",
    "D/LifecycleTest: >>> onRestoreInstanceState 호출됨",
    "D/LifecycleTest: >>> onResume 호출됨",
    "```",
    "",
    "---",
    "",
    "## Fragment 생명주기와의 관계",
    "",
    "Fragment는 Activity 안에서 동작하는 **독립적인 UI 모듈**입니다. Fragment도 자체 생명주기를 가지며, 호스트 Activity의 생명주기에 영향을 받습니다.",
    "",
    "```mermaid",
    "graph TD",
    "    subgraph Activity 생명주기",
    "        A1[onCreate] --> A2[onStart] --> A3[onResume]",
    "        A3 --> A4[onPause] --> A5[onStop] --> A6[onDestroy]",
    "    end",
    "    subgraph Fragment 생명주기",
    "        F1[onAttach] --> F2[onCreate] --> F3[onCreateView]",
    "        F3 --> F4[onViewCreated] --> F5[onStart] --> F6[onResume]",
    "        F6 --> F7[onPause] --> F8[onStop] --> F9[onDestroyView]",
    "        F9 --> F10[onDestroy] --> F11[onDetach]",
    "    end",
    "    A1 -.-> F1",
    "    A2 -.-> F5",
    "    A3 -.-> F6",
    "    A4 -.-> F7",
    "    A5 -.-> F8",
    "    A6 -.-> F10",
    "```",
    "",
    "### Fragment 추가 콜백",
    "",
    "| 콜백 | 설명 |",
    "| --- | --- |",
    "| `onAttach()` | Fragment가 Activity에 연결될 때 |",
    "| `onCreateView()` | Fragment의 UI(View)를 생성할 때 |",
    "| `onViewCreated()` | View 생성 완료 후 (뷰 초기화에 적합) |",
    "| `onDestroyView()` | Fragment의 View가 파괴될 때 |",
    "| `onDetach()` | Fragment가 Activity에서 분리될 때 |",
    "",
    "```java",
    "public class MyFragment extends Fragment {",
    "",
    "    @Override",
    "    public void onAttach(@NonNull Context context) {",
    "        super.onAttach(context);",
    "        Log.d(\"Fragment\", \"onAttach\");",
    "    }",
    "",
    "    @Nullable",
    "    @Override",
    "    public View onCreateView(@NonNull LayoutInflater inflater,",
    "            @Nullable ViewGroup container,",
    "            @Nullable Bundle savedInstanceState) {",
    "        return inflater.inflate(R.layout.fragment_my, container, false);",
    "    }",
    "",
    "    @Override",
    "    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {",
    "        super.onViewCreated(view, savedInstanceState);",
    "        // 뷰 초기화는 여기서",
    "        TextView tv = view.findViewById(R.id.tvFragment);",
    "        tv.setText(\"Fragment 내용\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 생명주기 베스트 프랙티스",
    "",
    "| 작업 | 시작 콜백 | 중지 콜백 |",
    "| --- | --- | --- |",
    "| 레이아웃 설정 | `onCreate` | - |",
    "| BroadcastReceiver 등록 | `onStart` | `onStop` |",
    "| 카메라/센서 | `onResume` | `onPause` |",
    "| 데이터베이스 저장 | - | `onStop` |",
    "| 리소스 해제 | - | `onDestroy` |",
    "| 애니메이션 | `onResume` | `onPause` |",
    "",
    "### 주의사항",
    "",
    "1. **onPause()에서 무거운 작업 금지**: 다음 Activity 전환이 지연됨",
    "2. **super 호출 필수**: 모든 콜백에서 `super.onXxx()` 먼저 호출",
    "3. **onCreate()에서 null 체크**: savedInstanceState가 null일 수 있음 (최초 실행 시)",
    "4. **finish() 후 return**: finish() 호출 후에도 코드가 계속 실행됨에 주의",
    "",
    "---",
    "",
    "## 정리",
    "",
    "```mermaid",
    "mindmap",
    "  root((Activity Lifecycle))",
    "    7개 콜백",
    "      onCreate",
    "      onStart",
    "      onResume",
    "      onPause",
    "      onStop",
    "      onRestart",
    "      onDestroy",
    "    상태 보존",
    "      onSaveInstanceState",
    "      onRestoreInstanceState",
    "      ViewModel",
    "    Configuration Change",
    "      화면 회전",
    "      언어 변경",
    "      다크 모드",
    "    Fragment",
    "      onAttach",
    "      onCreateView",
    "      onViewCreated",
    "      onDestroyView",
    "      onDetach",
    "```",
    "",
    "Activity 생명주기는 Android 개발의 **가장 기본이자 핵심**입니다. 각 콜백의 호출 시점과 역할을 정확히 이해하고, 적절한 위치에서 리소스를 초기화하고 해제하는 것이 안정적인 앱 개발의 첫걸음입니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
