<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-animation",
  title: "애니메이션과 WebView",
  date: "2025-12-21",
  summary: "Tween/Property Animation, ViewPropertyAnimator, Transition Framework, RecyclerView 아이템 애니메이션, Lottie, WebView 설정과 JavaScript 통신까지 총정리합니다.",
  category: "Technology/Android",
  tags: ["android", "animation", "tween", "property", "webview", "lottie"],
  content: [
    "## Android 애니메이션 체계 개요",
    "",
    "Android는 여러 종류의 애니메이션 API를 제공합니다. 각각의 특성과 적합한 사용 사례가 다릅니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[Android 애니메이션] --> B[Tween Animation<br/>View Animation]",
    "    A --> C[Property Animation]",
    "    A --> D[Transition Framework]",
    "    B --> B1[AlphaAnimation]",
    "    B --> B2[ScaleAnimation]",
    "    B --> B3[TranslateAnimation]",
    "    B --> B4[RotateAnimation]",
    "    C --> C1[ObjectAnimator]",
    "    C --> C2[ValueAnimator]",
    "    C --> C3[ViewPropertyAnimator]",
    "    D --> D1[화면 전환]",
    "    D --> D2[레이아웃 변경]",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "    style C fill:#FF9800,color:#fff",
    "    style D fill:#9C27B0,color:#fff",
    "```",
    "",
    "### 애니메이션 API 비교",
    "",
    "| 종류 | 대상 | 실제 속성 변경 | API Level |",
    "| --- | --- | --- | --- |",
    "| Tween Animation | View만 | 아니오 (시각적 변환만) | API 1 |",
    "| Property Animation | 모든 객체 | 예 | API 11 |",
    "| ViewPropertyAnimator | View만 | 예 | API 12 |",
    "| Transition Framework | ViewGroup | 예 | API 19 |",
    "",
    "## Tween Animation (View Animation)",
    "",
    "Tween Animation은 View의 시각적 변환만 수행합니다. 실제 속성(위치, 크기 등)은 변경되지 않으므로 클릭 영역이 이동하지 않는 한계가 있습니다.",
    "",
    "### AlphaAnimation (투명도)",
    "",
    "```java",
    "// 코드로 생성",
    "AlphaAnimation fadeIn = new AlphaAnimation(0f, 1f);",
    "fadeIn.setDuration(1000);",
    "fadeIn.setFillAfter(true);",
    "view.startAnimation(fadeIn);",
    "",
    "AlphaAnimation fadeOut = new AlphaAnimation(1f, 0f);",
    "fadeOut.setDuration(1000);",
    "fadeOut.setFillAfter(true);",
    "view.startAnimation(fadeOut);",
    "```",
    "",
    "### ScaleAnimation (크기)",
    "",
    "```java",
    "ScaleAnimation scaleUp = new ScaleAnimation(",
    "    1f, 1.5f,",
    "    1f, 1.5f,",
    "    Animation.RELATIVE_TO_SELF, 0.5f,",
    "    Animation.RELATIVE_TO_SELF, 0.5f);",
    "scaleUp.setDuration(500);",
    "scaleUp.setFillAfter(true);",
    "view.startAnimation(scaleUp);",
    "```",
    "",
    "### TranslateAnimation (이동)",
    "",
    "```java",
    "TranslateAnimation slide = new TranslateAnimation(",
    "    Animation.RELATIVE_TO_SELF, 0f,",
    "    Animation.RELATIVE_TO_SELF, 1f,",
    "    Animation.RELATIVE_TO_SELF, 0f,",
    "    Animation.RELATIVE_TO_SELF, 0f);",
    "slide.setDuration(800);",
    "slide.setFillAfter(true);",
    "view.startAnimation(slide);",
    "```",
    "",
    "### RotateAnimation (회전)",
    "",
    "```java",
    "RotateAnimation rotate = new RotateAnimation(",
    "    0f, 360f,",
    "    Animation.RELATIVE_TO_SELF, 0.5f,",
    "    Animation.RELATIVE_TO_SELF, 0.5f);",
    "rotate.setDuration(1000);",
    "rotate.setRepeatCount(Animation.INFINITE);",
    "rotate.setInterpolator(new LinearInterpolator());",
    "view.startAnimation(rotate);",
    "```",
    "",
    "### AnimationSet (조합)",
    "",
    "```java",
    "AnimationSet animSet = new AnimationSet(true);",
    "animSet.setInterpolator(new AccelerateDecelerateInterpolator());",
    "",
    "AlphaAnimation alpha = new AlphaAnimation(0f, 1f);",
    "alpha.setDuration(500);",
    "animSet.addAnimation(alpha);",
    "",
    "ScaleAnimation scale = new ScaleAnimation(",
    "    0.5f, 1f, 0.5f, 1f,",
    "    Animation.RELATIVE_TO_SELF, 0.5f,",
    "    Animation.RELATIVE_TO_SELF, 0.5f);",
    "scale.setDuration(500);",
    "animSet.addAnimation(scale);",
    "",
    "view.startAnimation(animSet);",
    "```",
    "",
    "### XML 애니메이션 리소스",
    "",
    "`res/anim/` 폴더에 XML로 애니메이션을 정의할 수 있습니다.",
    "",
    "```xml",
    "<!-- res/anim/fade_in_scale.xml -->",
    "<set xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    android:interpolator=\"@android:anim/accelerate_decelerate_interpolator\">",
    "",
    "    <alpha",
    "        android:fromAlpha=\"0.0\"",
    "        android:toAlpha=\"1.0\"",
    "        android:duration=\"500\" />",
    "",
    "    <scale",
    "        android:fromXScale=\"0.8\"",
    "        android:toXScale=\"1.0\"",
    "        android:fromYScale=\"0.8\"",
    "        android:toYScale=\"1.0\"",
    "        android:pivotX=\"50%\"",
    "        android:pivotY=\"50%\"",
    "        android:duration=\"500\" />",
    "</set>",
    "```",
    "",
    "```java",
    "Animation anim = AnimationUtils.loadAnimation(this, R.anim.fade_in_scale);",
    "view.startAnimation(anim);",
    "```",
    "",
    "## Property Animation",
    "",
    "Property Animation은 객체의 실제 속성을 변경하므로 Tween Animation의 한계를 극복합니다.",
    "",
    "### ObjectAnimator",
    "",
    "```java",
    "// 투명도 변경",
    "ObjectAnimator fadeAnim = ObjectAnimator.ofFloat(view, \"alpha\", 0f, 1f);",
    "fadeAnim.setDuration(1000);",
    "fadeAnim.start();",
    "",
    "// X축 이동",
    "ObjectAnimator moveX = ObjectAnimator.ofFloat(view, \"translationX\", 0f, 300f);",
    "moveX.setDuration(800);",
    "moveX.start();",
    "",
    "// 회전",
    "ObjectAnimator rotateAnim = ObjectAnimator.ofFloat(view, \"rotation\", 0f, 360f);",
    "rotateAnim.setDuration(1000);",
    "rotateAnim.setRepeatCount(ValueAnimator.INFINITE);",
    "rotateAnim.setInterpolator(new LinearInterpolator());",
    "rotateAnim.start();",
    "",
    "// 배경색 변경",
    "ObjectAnimator colorAnim = ObjectAnimator.ofArgb(",
    "    view, \"backgroundColor\",",
    "    Color.RED, Color.BLUE);",
    "colorAnim.setDuration(1500);",
    "colorAnim.setRepeatMode(ValueAnimator.REVERSE);",
    "colorAnim.setRepeatCount(ValueAnimator.INFINITE);",
    "colorAnim.start();",
    "```",
    "",
    "### ValueAnimator",
    "",
    "값의 변화를 콜백으로 받아 자유롭게 활용할 수 있습니다.",
    "",
    "```java",
    "ValueAnimator animator = ValueAnimator.ofFloat(0f, 1f);",
    "animator.setDuration(2000);",
    "animator.addUpdateListener(animation -> {",
    "    float value = (float) animation.getAnimatedValue();",
    "    view.setAlpha(value);",
    "    view.setScaleX(value);",
    "    view.setScaleY(value);",
    "});",
    "animator.start();",
    "",
    "// 정수 값 애니메이션 (카운트업 효과)",
    "ValueAnimator countUp = ValueAnimator.ofInt(0, 1000);",
    "countUp.setDuration(3000);",
    "countUp.addUpdateListener(animation -> {",
    "    int value = (int) animation.getAnimatedValue();",
    "    textView.setText(String.valueOf(value));",
    "});",
    "countUp.start();",
    "```",
    "",
    "### AnimatorSet (순차/동시 실행)",
    "",
    "```java",
    "ObjectAnimator moveX = ObjectAnimator.ofFloat(view, \"translationX\", 0f, 200f);",
    "ObjectAnimator moveY = ObjectAnimator.ofFloat(view, \"translationY\", 0f, 200f);",
    "ObjectAnimator fade = ObjectAnimator.ofFloat(view, \"alpha\", 1f, 0.3f);",
    "",
    "AnimatorSet set = new AnimatorSet();",
    "",
    "// 동시 실행",
    "set.playTogether(moveX, moveY);",
    "",
    "// 순차 실행",
    "// set.playSequentially(moveX, moveY, fade);",
    "",
    "// 커스텀 순서",
    "// set.play(moveX).with(moveY).before(fade);",
    "",
    "set.setDuration(1000);",
    "set.start();",
    "```",
    "",
    "### Interpolator 종류",
    "",
    "| Interpolator | 동작 |",
    "| --- | --- |",
    "| `LinearInterpolator` | 일정 속도 |",
    "| `AccelerateInterpolator` | 점점 빨라짐 |",
    "| `DecelerateInterpolator` | 점점 느려짐 |",
    "| `AccelerateDecelerateInterpolator` | 빨라졌다 느려짐 |",
    "| `BounceInterpolator` | 바운스 효과 |",
    "| `OvershootInterpolator` | 목표를 넘었다 돌아옴 |",
    "| `AnticipateInterpolator` | 뒤로 갔다 앞으로 |",
    "| `AnticipateOvershootInterpolator` | 뒤로 + 오버슈트 |",
    "",
    "## ViewPropertyAnimator",
    "",
    "View의 속성 애니메이션을 간편하게 체이닝으로 작성할 수 있습니다.",
    "",
    "```java",
    "// 간단한 페이드 인",
    "view.animate()",
    "    .alpha(1f)",
    "    .setDuration(500)",
    "    .start();",
    "",
    "// 복합 애니메이션",
    "view.animate()",
    "    .translationX(200f)",
    "    .translationY(100f)",
    "    .scaleX(1.5f)",
    "    .scaleY(1.5f)",
    "    .alpha(0.5f)",
    "    .rotation(45f)",
    "    .setDuration(1000)",
    "    .setInterpolator(new OvershootInterpolator())",
    "    .setStartDelay(200)",
    "    .withStartAction(() -> {",
    "        // 애니메이션 시작 시",
    "    })",
    "    .withEndAction(() -> {",
    "        // 애니메이션 종료 시",
    "    })",
    "    .start();",
    "```",
    "",
    "```mermaid",
    "graph LR",
    "    A[ViewPropertyAnimator] --> B[alpha]",
    "    A --> C[translationX/Y]",
    "    A --> D[scaleX/Y]",
    "    A --> E[rotation]",
    "    A --> F[setDuration]",
    "    A --> G[setInterpolator]",
    "    A --> H[withEndAction]",
    "    style A fill:#FF9800,color:#fff",
    "```",
    "",
    "## Transition Framework",
    "",
    "레이아웃 변경 시 자동으로 애니메이션을 적용하는 프레임워크입니다.",
    "",
    "```java",
    "// Scene 전환",
    "ViewGroup sceneRoot = findViewById(R.id.scene_root);",
    "Scene scene1 = Scene.getSceneForLayout(sceneRoot, R.layout.scene_1, this);",
    "Scene scene2 = Scene.getSceneForLayout(sceneRoot, R.layout.scene_2, this);",
    "",
    "Transition transition = new ChangeBounds();",
    "transition.setDuration(500);",
    "",
    "TransitionManager.go(scene2, transition);",
    "```",
    "",
    "### 지연된 전환 (Delayed Transition)",
    "",
    "```java",
    "// 레이아웃 변경 전에 호출",
    "TransitionManager.beginDelayedTransition(",
    "    container, new AutoTransition());",
    "",
    "// 이후 레이아웃 변경 → 자동 애니메이션",
    "if (detailView.getVisibility() == View.GONE) {",
    "    detailView.setVisibility(View.VISIBLE);",
    "} else {",
    "    detailView.setVisibility(View.GONE);",
    "}",
    "```",
    "",
    "## LayoutTransition",
    "",
    "ViewGroup에 자식 View가 추가/제거될 때 자동 애니메이션을 적용합니다.",
    "",
    "```xml",
    "<LinearLayout",
    "    android:id=\"@+id/container\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:animateLayoutChanges=\"true\"",
    "    android:orientation=\"vertical\" />",
    "```",
    "",
    "```java",
    "LinearLayout container = findViewById(R.id.container);",
    "LayoutTransition lt = container.getLayoutTransition();",
    "lt.enableTransitionType(LayoutTransition.CHANGING);",
    "lt.setDuration(300);",
    "```",
    "",
    "## RecyclerView 아이템 애니메이션",
    "",
    "### 기본 아이템 애니메이터",
    "",
    "RecyclerView는 기본적으로 `DefaultItemAnimator`를 사용합니다.",
    "",
    "```java",
    "recyclerView.setItemAnimator(new DefaultItemAnimator());",
    "```",
    "",
    "### XML로 아이템 진입 애니메이션",
    "",
    "```xml",
    "<!-- res/anim/item_fall_down.xml -->",
    "<set xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    android:duration=\"500\">",
    "",
    "    <translate",
    "        android:fromYDelta=\"-20%\"",
    "        android:toYDelta=\"0\"",
    "        android:interpolator=\"@android:anim/decelerate_interpolator\" />",
    "",
    "    <alpha",
    "        android:fromAlpha=\"0\"",
    "        android:toAlpha=\"1\"",
    "        android:interpolator=\"@android:anim/decelerate_interpolator\" />",
    "</set>",
    "```",
    "",
    "```xml",
    "<!-- res/anim/layout_animation_fall_down.xml -->",
    "<layoutAnimation xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    android:animation=\"@anim/item_fall_down\"",
    "    android:delay=\"15%\"",
    "    android:animationOrder=\"normal\" />",
    "```",
    "",
    "```java",
    "LayoutAnimationController controller = AnimationUtils.loadLayoutAnimation(",
    "    this, R.anim.layout_animation_fall_down);",
    "recyclerView.setLayoutAnimation(controller);",
    "```",
    "",
    "## Lottie 라이브러리",
    "",
    "Lottie는 After Effects 애니메이션을 JSON으로 내보내어 Android에서 재생할 수 있는 라이브러리입니다.",
    "",
    "### 의존성 추가",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'com.airbnb.android:lottie:6.3.0'",
    "}",
    "```",
    "",
    "### XML에서 사용",
    "",
    "```xml",
    "<com.airbnb.lottie.LottieAnimationView",
    "    android:id=\"@+id/lottie_view\"",
    "    android:layout_width=\"200dp\"",
    "    android:layout_height=\"200dp\"",
    "    app:lottie_rawRes=\"@raw/loading_animation\"",
    "    app:lottie_autoPlay=\"true\"",
    "    app:lottie_loop=\"true\" />",
    "```",
    "",
    "### 코드에서 제어",
    "",
    "```java",
    "LottieAnimationView lottieView = findViewById(R.id.lottie_view);",
    "",
    "// JSON 파일로부터 로드",
    "lottieView.setAnimation(R.raw.success_animation);",
    "lottieView.playAnimation();",
    "",
    "// URL에서 로드",
    "lottieView.setAnimationFromUrl(\"https://example.com/animation.json\");",
    "",
    "// 진행률 제어",
    "lottieView.setProgress(0.5f);",
    "",
    "// 반복 설정",
    "lottieView.setRepeatCount(LottieDrawable.INFINITE);",
    "",
    "// 리스너",
    "lottieView.addAnimatorListener(new AnimatorListenerAdapter() {",
    "    @Override",
    "    public void onAnimationEnd(Animator animation) {",
    "        // 애니메이션 완료 시",
    "    }",
    "});",
    "```",
    "",
    "## WebView",
    "",
    "WebView는 앱 내에서 웹 페이지를 표시하는 위젯입니다. 하이브리드 앱이나 웹 콘텐츠 표시에 사용됩니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[WebView] --> B[WebSettings<br/>JavaScript, 확대/축소 등]",
    "    A --> C[WebViewClient<br/>페이지 로딩 이벤트]",
    "    A --> D[WebChromeClient<br/>UI 관련 이벤트]",
    "    A --> E[JavaScriptInterface<br/>앱-웹 통신]",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "    style C fill:#FF9800,color:#fff",
    "    style D fill:#9C27B0,color:#fff",
    "    style E fill:#f44336,color:#fff",
    "```",
    "",
    "### 기본 설정",
    "",
    "```xml",
    "<WebView",
    "    android:id=\"@+id/web_view\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"match_parent\" />",
    "```",
    "",
    "```java",
    "WebView webView = findViewById(R.id.web_view);",
    "WebSettings settings = webView.getSettings();",
    "",
    "settings.setJavaScriptEnabled(true);",
    "settings.setDomStorageEnabled(true);",
    "settings.setBuiltInZoomControls(true);",
    "settings.setDisplayZoomControls(false);",
    "settings.setLoadWithOverviewMode(true);",
    "settings.setUseWideViewPort(true);",
    "",
    "webView.loadUrl(\"https://www.example.com\");",
    "```",
    "",
    "### WebSettings 주요 옵션",
    "",
    "| 메서드 | 설명 |",
    "| --- | --- |",
    "| `setJavaScriptEnabled()` | JavaScript 실행 허용 |",
    "| `setDomStorageEnabled()` | DOM Storage API 허용 |",
    "| `setBuiltInZoomControls()` | 확대/축소 컨트롤 |",
    "| `setCacheMode()` | 캐시 모드 설정 |",
    "| `setUserAgentString()` | User-Agent 설정 |",
    "| `setMixedContentMode()` | HTTP/HTTPS 혼합 콘텐츠 |",
    "",
    "### WebViewClient - 페이지 로딩 제어",
    "",
    "```java",
    "webView.setWebViewClient(new WebViewClient() {",
    "",
    "    @Override",
    "    public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {",
    "        String url = request.getUrl().toString();",
    "        if (url.startsWith(\"https://www.example.com\")) {",
    "            return false;",
    "        }",
    "        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));",
    "        startActivity(intent);",
    "        return true;",
    "    }",
    "",
    "    @Override",
    "    public void onPageStarted(WebView view, String url, Bitmap favicon) {",
    "        super.onPageStarted(view, url, favicon);",
    "        progressBar.setVisibility(View.VISIBLE);",
    "    }",
    "",
    "    @Override",
    "    public void onPageFinished(WebView view, String url) {",
    "        super.onPageFinished(view, url);",
    "        progressBar.setVisibility(View.GONE);",
    "    }",
    "",
    "    @Override",
    "    public void onReceivedError(WebView view, WebResourceRequest request,",
    "                                WebResourceError error) {",
    "        super.onReceivedError(view, request, error);",
    "        view.loadData(\"<h2>페이지를 로드할 수 없습니다</h2>\",",
    "            \"text/html\", \"utf-8\");",
    "    }",
    "});",
    "```",
    "",
    "### WebChromeClient - UI 이벤트",
    "",
    "```java",
    "webView.setWebChromeClient(new WebChromeClient() {",
    "",
    "    @Override",
    "    public void onProgressChanged(WebView view, int newProgress) {",
    "        progressBar.setProgress(newProgress);",
    "    }",
    "",
    "    @Override",
    "    public void onReceivedTitle(WebView view, String title) {",
    "        getSupportActionBar().setTitle(title);",
    "    }",
    "",
    "    @Override",
    "    public boolean onJsAlert(WebView view, String url,",
    "                             String message, JsResult result) {",
    "        new AlertDialog.Builder(MainActivity.this)",
    "            .setMessage(message)",
    "            .setPositiveButton(\"확인\", (d, w) -> result.confirm())",
    "            .setCancelable(false)",
    "            .show();",
    "        return true;",
    "    }",
    "});",
    "```",
    "",
    "### JavaScript 인터페이스 - 앱과 웹 통신",
    "",
    "Android 앱에서 JavaScript 함수를 호출하거나, 웹에서 앱의 메서드를 호출할 수 있습니다.",
    "",
    "```java",
    "public class WebAppInterface {",
    "    private Context context;",
    "",
    "    WebAppInterface(Context context) {",
    "        this.context = context;",
    "    }",
    "",
    "    @JavascriptInterface",
    "    public void showToast(String message) {",
    "        Toast.makeText(context, message, Toast.LENGTH_SHORT).show();",
    "    }",
    "",
    "    @JavascriptInterface",
    "    public String getDeviceInfo() {",
    "        return Build.MODEL + \" (\" + Build.VERSION.RELEASE + \")\";",
    "    }",
    "",
    "    @JavascriptInterface",
    "    public void openNativeScreen(String screenName) {",
    "        if (\"settings\".equals(screenName)) {",
    "            Intent intent = new Intent(context, SettingsActivity.class);",
    "            context.startActivity(intent);",
    "        }",
    "    }",
    "}",
    "",
    "// 인터페이스 등록",
    "webView.addJavascriptInterface(",
    "    new WebAppInterface(this), \"AndroidApp\");",
    "```",
    "",
    "### 웹에서 앱 메서드 호출 (JavaScript)",
    "",
    "```javascript",
    "// 웹 페이지의 JavaScript에서",
    "AndroidApp.showToast('안녕하세요!');",
    "",
    "var deviceInfo = AndroidApp.getDeviceInfo();",
    "document.getElementById('info').innerText = deviceInfo;",
    "",
    "AndroidApp.openNativeScreen('settings');",
    "```",
    "",
    "### 앱에서 JavaScript 함수 호출",
    "",
    "```java",
    "// JavaScript 실행",
    "webView.evaluateJavascript(",
    "    \"javascript:updateContent('새로운 데이터')\",",
    "    value -> {",
    "        // JavaScript 함수의 반환값",
    "        Log.d(\"WebView\", \"결과: \" + value);",
    "    }",
    ");",
    "```",
    "",
    "### WebView 뒤로 가기 처리",
    "",
    "```java",
    "@Override",
    "public void onBackPressed() {",
    "    if (webView.canGoBack()) {",
    "        webView.goBack();",
    "    } else {",
    "        super.onBackPressed();",
    "    }",
    "}",
    "```",
    "",
    "## 애니메이션과 WebView 활용 비교",
    "",
    "```mermaid",
    "graph TD",
    "    A{목적?} -->|시각적 효과| B[Tween Animation]",
    "    A -->|속성 변경 필요| C[Property Animation]",
    "    A -->|간단한 View 애니메이션| D[ViewPropertyAnimator]",
    "    A -->|레이아웃 변경 애니메이션| E[Transition Framework]",
    "    A -->|복잡한 애니메이션| F[Lottie]",
    "    A -->|웹 콘텐츠 표시| G[WebView]",
    "    style A fill:#4CAF50,color:#fff",
    "    style C fill:#2196F3,color:#fff",
    "    style D fill:#FF9800,color:#fff",
    "    style F fill:#9C27B0,color:#fff",
    "    style G fill:#f44336,color:#fff",
    "```",
    "",
    "## 정리",
    "",
    "Android 애니메이션은 Tween Animation에서 Property Animation으로 발전해왔습니다. ViewPropertyAnimator는 간결한 API로 View 애니메이션을 쉽게 구현할 수 있고, Transition Framework는 레이아웃 변경을 자동으로 애니메이션합니다. 복잡한 애니메이션은 Lottie 라이브러리를 활용하면 디자이너와의 협업이 수월해집니다. WebView는 앱 내에서 웹 콘텐츠를 표시하고, JavaScript 인터페이스를 통해 네이티브 앱과 웹 간 양방향 통신이 가능합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
