<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-network",
  title: "네트워크 통신 - HTTP, Volley, Socket",
  date: "2025-12-19",
  summary: "Android에서 네트워크 통신을 구현하는 방법을 HttpURLConnection부터 Volley, Retrofit, Socket까지 실전 예제와 함께 정리합니다.",
  category: "Technology/Android",
  tags: ["android", "network", "http", "volley", "retrofit", "socket"],
  content: [
    "## 인터넷 권한(INTERNET Permission)",
    "",
    "Android에서 네트워크 통신을 하려면 반드시 **AndroidManifest.xml**에 인터넷 권한을 선언해야 합니다.",
    "",
    "```xml",
    "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    package=\"com.example.networkapp\">",
    "",
    "    <uses-permission android:name=\"android.permission.INTERNET\" />",
    "    <uses-permission android:name=\"android.permission.ACCESS_NETWORK_STATE\" />",
    "",
    "    <application",
    "        ... >",
    "    </application>",
    "</manifest>",
    "```",
    "",
    "| 권한 | 타입 | 설명 |",
    "| --- | --- | --- |",
    "| INTERNET | 일반 권한 | 네트워크 소켓 열기 |",
    "| ACCESS_NETWORK_STATE | 일반 권한 | 네트워크 연결 상태 확인 |",
    "| ACCESS_WIFI_STATE | 일반 권한 | Wi-Fi 연결 정보 확인 |",
    "",
    "일반 권한이므로 별도의 런타임 권한 요청 없이 매니페스트 선언만으로 사용 가능합니다.",
    "",
    "## HttpURLConnection 사용법",
    "",
    "Java 표준 라이브러리에 포함된 `HttpURLConnection`으로 HTTP 요청을 보낼 수 있습니다.",
    "",
    "### GET 요청",
    "",
    "```java",
    "public String httpGet(String urlString) throws IOException {",
    "    URL url = new URL(urlString);",
    "    HttpURLConnection conn = (HttpURLConnection) url.openConnection();",
    "",
    "    try {",
    "        conn.setRequestMethod(\"GET\");",
    "        conn.setConnectTimeout(5000);",
    "        conn.setReadTimeout(5000);",
    "        conn.setRequestProperty(\"Accept\", \"application/json\");",
    "",
    "        int responseCode = conn.getResponseCode();",
    "        if (responseCode == HttpURLConnection.HTTP_OK) {",
    "            BufferedReader reader = new BufferedReader(",
    "                new InputStreamReader(conn.getInputStream(), \"UTF-8\"));",
    "            StringBuilder sb = new StringBuilder();",
    "            String line;",
    "            while ((line = reader.readLine()) != null) {",
    "                sb.append(line).append(\"\\n\");",
    "            }",
    "            reader.close();",
    "            return sb.toString();",
    "        } else {",
    "            return \"Error: \" + responseCode;",
    "        }",
    "    } finally {",
    "        conn.disconnect();",
    "    }",
    "}",
    "```",
    "",
    "### POST 요청",
    "",
    "```java",
    "public String httpPost(String urlString, String jsonBody) throws IOException {",
    "    URL url = new URL(urlString);",
    "    HttpURLConnection conn = (HttpURLConnection) url.openConnection();",
    "",
    "    try {",
    "        conn.setRequestMethod(\"POST\");",
    "        conn.setDoOutput(true);",
    "        conn.setConnectTimeout(5000);",
    "        conn.setRequestProperty(\"Content-Type\", \"application/json\");",
    "        conn.setRequestProperty(\"Accept\", \"application/json\");",
    "",
    "        OutputStream os = conn.getOutputStream();",
    "        os.write(jsonBody.getBytes(\"UTF-8\"));",
    "        os.flush();",
    "        os.close();",
    "",
    "        int responseCode = conn.getResponseCode();",
    "        BufferedReader reader = new BufferedReader(",
    "            new InputStreamReader(",
    "                responseCode >= 400 ? conn.getErrorStream() : conn.getInputStream(),",
    "                \"UTF-8\"));",
    "",
    "        StringBuilder sb = new StringBuilder();",
    "        String line;",
    "        while ((line = reader.readLine()) != null) {",
    "            sb.append(line);",
    "        }",
    "        reader.close();",
    "        return sb.toString();",
    "    } finally {",
    "        conn.disconnect();",
    "    }",
    "}",
    "```",
    "",
    "### HTTP 요청 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant App as Android 앱",
    "    participant Conn as HttpURLConnection",
    "    participant Server as 서버",
    "",
    "    App->>Conn: URL 생성 및 연결 설정",
    "    Conn->>Server: HTTP 요청 전송",
    "    Server-->>Conn: HTTP 응답 반환",
    "    Conn-->>App: InputStream으로 응답 읽기",
    "    App->>App: 응답 데이터 파싱",
    "```",
    "",
    "## JSON 파싱(JSONObject, JSONArray)",
    "",
    "Android에는 `org.json` 패키지가 내장되어 있어 JSON 파싱이 가능합니다.",
    "",
    "### JSONObject 파싱",
    "",
    "```java",
    "// JSON 문자열: {\"name\": \"홍길동\", \"age\": 25, \"email\": \"hong@example.com\"}",
    "String jsonString = response;",
    "",
    "try {",
    "    JSONObject jsonObject = new JSONObject(jsonString);",
    "    String name = jsonObject.getString(\"name\");",
    "    int age = jsonObject.getInt(\"age\");",
    "    String email = jsonObject.getString(\"email\");",
    "",
    "    Log.d(\"JSON\", name + \", \" + age + \", \" + email);",
    "} catch (JSONException e) {",
    "    e.printStackTrace();",
    "}",
    "```",
    "",
    "### JSONArray 파싱",
    "",
    "```java",
    "// JSON 배열: [{\"id\": 1, \"title\": \"제목1\"}, {\"id\": 2, \"title\": \"제목2\"}]",
    "try {",
    "    JSONArray jsonArray = new JSONArray(jsonString);",
    "    List<String> titles = new ArrayList<>();",
    "",
    "    for (int i = 0; i < jsonArray.length(); i++) {",
    "        JSONObject item = jsonArray.getJSONObject(i);",
    "        int id = item.getInt(\"id\");",
    "        String title = item.getString(\"title\");",
    "        titles.add(title);",
    "    }",
    "} catch (JSONException e) {",
    "    e.printStackTrace();",
    "}",
    "```",
    "",
    "### JSON 생성",
    "",
    "```java",
    "try {",
    "    JSONObject user = new JSONObject();",
    "    user.put(\"name\", \"김철수\");",
    "    user.put(\"age\", 30);",
    "",
    "    JSONArray hobbies = new JSONArray();",
    "    hobbies.put(\"축구\");",
    "    hobbies.put(\"독서\");",
    "    user.put(\"hobbies\", hobbies);",
    "",
    "    String jsonOutput = user.toString();",
    "    // {\"name\":\"김철수\",\"age\":30,\"hobbies\":[\"축구\",\"독서\"]}",
    "} catch (JSONException e) {",
    "    e.printStackTrace();",
    "}",
    "```",
    "",
    "## Volley 라이브러리",
    "",
    "Volley는 Google에서 제공하는 Android용 HTTP 라이브러리로, 비동기 요청과 캐싱을 쉽게 처리할 수 있습니다.",
    "",
    "### Gradle 의존성 추가",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'com.android.volley:volley:1.2.1'",
    "}",
    "```",
    "",
    "### RequestQueue 생성",
    "",
    "```java",
    "// 싱글턴 패턴 권장",
    "public class VolleySingleton {",
    "    private static VolleySingleton instance;",
    "    private RequestQueue requestQueue;",
    "    private static Context ctx;",
    "",
    "    private VolleySingleton(Context context) {",
    "        ctx = context.getApplicationContext();",
    "        requestQueue = Volley.newRequestQueue(ctx);",
    "    }",
    "",
    "    public static synchronized VolleySingleton getInstance(Context context) {",
    "        if (instance == null) {",
    "            instance = new VolleySingleton(context);",
    "        }",
    "        return instance;",
    "    }",
    "",
    "    public RequestQueue getRequestQueue() {",
    "        return requestQueue;",
    "    }",
    "",
    "    public <T> void addToRequestQueue(Request<T> req) {",
    "        getRequestQueue().add(req);",
    "    }",
    "}",
    "```",
    "",
    "### StringRequest",
    "",
    "```java",
    "String url = \"https://api.example.com/data\";",
    "",
    "StringRequest stringRequest = new StringRequest(",
    "    Request.Method.GET,",
    "    url,",
    "    response -> {",
    "        // 성공 콜백 (메인 스레드에서 실행됨)",
    "        textView.setText(response);",
    "    },",
    "    error -> {",
    "        // 에러 콜백",
    "        textView.setText(\"Error: \" + error.getMessage());",
    "    }",
    ");",
    "",
    "VolleySingleton.getInstance(this).addToRequestQueue(stringRequest);",
    "```",
    "",
    "### JsonObjectRequest",
    "",
    "```java",
    "String url = \"https://api.example.com/user\";",
    "",
    "JsonObjectRequest jsonRequest = new JsonObjectRequest(",
    "    Request.Method.GET,",
    "    url,",
    "    null, // POST body (GET이면 null)",
    "    response -> {",
    "        try {",
    "            String name = response.getString(\"name\");",
    "            int age = response.getInt(\"age\");",
    "            textView.setText(name + \" (\" + age + \"세)\");",
    "        } catch (JSONException e) {",
    "            e.printStackTrace();",
    "        }",
    "    },",
    "    error -> {",
    "        Log.e(\"Volley\", \"Error: \" + error.getMessage());",
    "    }",
    ");",
    "",
    "VolleySingleton.getInstance(this).addToRequestQueue(jsonRequest);",
    "```",
    "",
    "### ImageRequest",
    "",
    "```java",
    "String imageUrl = \"https://example.com/image.png\";",
    "",
    "ImageRequest imageRequest = new ImageRequest(",
    "    imageUrl,",
    "    bitmap -> {",
    "        imageView.setImageBitmap(bitmap);",
    "    },",
    "    0, 0, // maxWidth, maxHeight (0 = 원본 크기)",
    "    ImageView.ScaleType.CENTER_CROP,",
    "    Bitmap.Config.ARGB_8888,",
    "    error -> {",
    "        imageView.setImageResource(R.drawable.ic_error);",
    "    }",
    ");",
    "",
    "VolleySingleton.getInstance(this).addToRequestQueue(imageRequest);",
    "```",
    "",
    "### Volley 요청 흐름",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[Request 생성] --> B[RequestQueue에 추가]",
    "    B --> C{캐시 확인}",
    "    C -->|캐시 있음| D[CacheDispatcher]",
    "    C -->|캐시 없음| E[NetworkDispatcher]",
    "    D --> F[캐시 응답 반환]",
    "    E --> G[네트워크 요청 실행]",
    "    G --> H[응답 수신]",
    "    H --> I[캐시 저장]",
    "    I --> J[메인 스레드에서 콜백 실행]",
    "    F --> J",
    "```",
    "",
    "### Volley POST 요청 (커스텀 Body)",
    "",
    "```java",
    "String url = \"https://api.example.com/login\";",
    "",
    "StringRequest postRequest = new StringRequest(",
    "    Request.Method.POST,",
    "    url,",
    "    response -> {",
    "        Log.d(\"Volley\", \"Response: \" + response);",
    "    },",
    "    error -> {",
    "        Log.e(\"Volley\", \"Error: \" + error.getMessage());",
    "    }",
    ") {",
    "    @Override",
    "    protected Map<String, String> getParams() {",
    "        Map<String, String> params = new HashMap<>();",
    "        params.put(\"username\", \"user123\");",
    "        params.put(\"password\", \"pass456\");",
    "        return params;",
    "    }",
    "",
    "    @Override",
    "    public Map<String, String> getHeaders() {",
    "        Map<String, String> headers = new HashMap<>();",
    "        headers.put(\"Content-Type\", \"application/x-www-form-urlencoded\");",
    "        return headers;",
    "    }",
    "};",
    "",
    "VolleySingleton.getInstance(this).addToRequestQueue(postRequest);",
    "```",
    "",
    "## Retrofit 간단 소개",
    "",
    "Retrofit은 Square에서 만든 REST API 클라이언트 라이브러리입니다. 인터페이스와 어노테이션 기반으로 HTTP API를 정의합니다.",
    "",
    "### Gradle 의존성",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'com.squareup.retrofit2:retrofit:2.9.0'",
    "    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'",
    "}",
    "```",
    "",
    "### API 인터페이스 정의",
    "",
    "```java",
    "public interface ApiService {",
    "",
    "    @GET(\"users/{id}\")",
    "    Call<User> getUser(@Path(\"id\") int userId);",
    "",
    "    @GET(\"users\")",
    "    Call<List<User>> getUsers(@Query(\"page\") int page);",
    "",
    "    @POST(\"users\")",
    "    Call<User> createUser(@Body User user);",
    "",
    "    @PUT(\"users/{id}\")",
    "    Call<User> updateUser(@Path(\"id\") int id, @Body User user);",
    "",
    "    @DELETE(\"users/{id}\")",
    "    Call<Void> deleteUser(@Path(\"id\") int id);",
    "}",
    "```",
    "",
    "### Retrofit 인스턴스 생성 및 사용",
    "",
    "```java",
    "Retrofit retrofit = new Retrofit.Builder()",
    "    .baseUrl(\"https://api.example.com/\")",
    "    .addConverterFactory(GsonConverterFactory.create())",
    "    .build();",
    "",
    "ApiService apiService = retrofit.create(ApiService.class);",
    "",
    "apiService.getUser(1).enqueue(new Callback<User>() {",
    "    @Override",
    "    public void onResponse(Call<User> call, Response<User> response) {",
    "        if (response.isSuccessful()) {",
    "            User user = response.body();",
    "            textView.setText(user.getName());",
    "        }",
    "    }",
    "",
    "    @Override",
    "    public void onFailure(Call<User> call, Throwable t) {",
    "        Log.e(\"Retrofit\", \"Failed: \" + t.getMessage());",
    "    }",
    "});",
    "```",
    "",
    "## OkHttp 인터셉터",
    "",
    "OkHttp의 인터셉터를 사용하면 모든 요청/응답을 가로채서 처리할 수 있습니다.",
    "",
    "```java",
    "OkHttpClient client = new OkHttpClient.Builder()",
    "    .addInterceptor(chain -> {",
    "        Request original = chain.request();",
    "        Request request = original.newBuilder()",
    "            .header(\"Authorization\", \"Bearer \" + token)",
    "            .header(\"Accept\", \"application/json\")",
    "            .method(original.method(), original.body())",
    "            .build();",
    "        return chain.proceed(request);",
    "    })",
    "    .addInterceptor(new HttpLoggingInterceptor()",
    "        .setLevel(HttpLoggingInterceptor.Level.BODY))",
    "    .connectTimeout(30, TimeUnit.SECONDS)",
    "    .readTimeout(30, TimeUnit.SECONDS)",
    "    .build();",
    "",
    "Retrofit retrofit = new Retrofit.Builder()",
    "    .baseUrl(\"https://api.example.com/\")",
    "    .client(client)",
    "    .addConverterFactory(GsonConverterFactory.create())",
    "    .build();",
    "```",
    "",
    "## Socket 통신(TCP)",
    "",
    "실시간 양방향 통신이 필요한 경우 Socket을 사용합니다.",
    "",
    "### TCP 클라이언트",
    "",
    "```java",
    "public class TcpClient {",
    "",
    "    private Socket socket;",
    "    private PrintWriter writer;",
    "    private BufferedReader reader;",
    "",
    "    public void connect(String host, int port) {",
    "        new Thread(() -> {",
    "            try {",
    "                socket = new Socket(host, port);",
    "                writer = new PrintWriter(",
    "                    new OutputStreamWriter(socket.getOutputStream(), \"UTF-8\"), true);",
    "                reader = new BufferedReader(",
    "                    new InputStreamReader(socket.getInputStream(), \"UTF-8\"));",
    "",
    "                String message;",
    "                while ((message = reader.readLine()) != null) {",
    "                    final String msg = message;",
    "                    runOnUiThread(() -> {",
    "                        appendMessage(\"서버: \" + msg);",
    "                    });",
    "                }",
    "            } catch (IOException e) {",
    "                e.printStackTrace();",
    "            }",
    "        }).start();",
    "    }",
    "",
    "    public void sendMessage(String message) {",
    "        new Thread(() -> {",
    "            if (writer != null) {",
    "                writer.println(message);",
    "            }",
    "        }).start();",
    "    }",
    "",
    "    public void disconnect() {",
    "        try {",
    "            if (socket != null) socket.close();",
    "        } catch (IOException e) {",
    "            e.printStackTrace();",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "## 네트워크 상태 확인(ConnectivityManager)",
    "",
    "네트워크 요청 전에 연결 상태를 확인하는 것이 좋습니다.",
    "",
    "```java",
    "public boolean isNetworkAvailable(Context context) {",
    "    ConnectivityManager cm = (ConnectivityManager)",
    "        context.getSystemService(Context.CONNECTIVITY_SERVICE);",
    "",
    "    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {",
    "        Network network = cm.getActiveNetwork();",
    "        if (network == null) return false;",
    "",
    "        NetworkCapabilities capabilities = cm.getNetworkCapabilities(network);",
    "        return capabilities != null &&",
    "            (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) ||",
    "             capabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) ||",
    "             capabilities.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET));",
    "    } else {",
    "        NetworkInfo networkInfo = cm.getActiveNetworkInfo();",
    "        return networkInfo != null && networkInfo.isConnected();",
    "    }",
    "}",
    "```",
    "",
    "### 네트워크 변경 감지",
    "",
    "```java",
    "ConnectivityManager cm = (ConnectivityManager)",
    "    getSystemService(Context.CONNECTIVITY_SERVICE);",
    "",
    "NetworkRequest request = new NetworkRequest.Builder()",
    "    .addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)",
    "    .build();",
    "",
    "cm.registerNetworkCallback(request, new ConnectivityManager.NetworkCallback() {",
    "    @Override",
    "    public void onAvailable(@NonNull Network network) {",
    "        Log.d(\"Network\", \"네트워크 연결됨\");",
    "    }",
    "",
    "    @Override",
    "    public void onLost(@NonNull Network network) {",
    "        Log.d(\"Network\", \"네트워크 연결 끊김\");",
    "    }",
    "});",
    "```",
    "",
    "## 네트워크 라이브러리 비교",
    "",
    "| 특성 | HttpURLConnection | Volley | Retrofit | OkHttp |",
    "| --- | --- | --- | --- | --- |",
    "| 난이도 | 낮음 | 보통 | 보통 | 보통 |",
    "| 캐싱 | 수동 | 자동 | OkHttp 위임 | 자동 |",
    "| 이미지 로딩 | 없음 | 지원 | 없음 | 없음 |",
    "| JSON 파싱 | 수동 | 수동 | Gson/Moshi 자동 | 수동 |",
    "| 코드량 | 많음 | 보통 | 적음 | 보통 |",
    "| 인터셉터 | 없음 | 없음 | OkHttp 위임 | 지원 |",
    "| 권장 여부 | 학습용 | 간단한 요청 | ✅ REST API | HTTP 기반 |",
    "",
    "최신 Android 개발에서는 **Retrofit + OkHttp + Gson(또는 Moshi)** 조합이 가장 널리 사용됩니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
