<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-content-provider",
  title: "ContentProvider - 데이터 공유",
  date: "2025-12-15",
  summary: "ContentProvider를 활용하여 앱 간 데이터를 안전하게 공유하는 방법을 학습합니다. Content URI, ContentResolver, 커스텀 Provider 구현까지 상세히 다룹니다.",
  category: "Technology/Android",
  tags: ["android", "contentprovider", "contentresolver", "cursor", "uri"],
  content: [
    "## ContentProvider란?",
    "",
    "ContentProvider는 안드로이드의 4대 컴포넌트 중 하나로, **앱 간 데이터를 안전하게 공유**하기 위한 표준 인터페이스입니다. 다른 앱의 데이터에 직접 접근하는 것은 보안상 불가능하지만, ContentProvider를 통해 구조화된 방식으로 데이터를 제공하고 소비할 수 있습니다.",
    "",
    "```mermaid",
    "graph LR",
    "    A[앱 A<br>ContentResolver] -->|Content URI| B[ContentProvider]",
    "    B --> C[SQLite DB]",
    "    B --> D[파일 시스템]",
    "    B --> E[네트워크]",
    "    F[앱 B<br>ContentResolver] -->|Content URI| B",
    "    G[앱 C<br>ContentResolver] -->|Content URI| B",
    "```",
    "",
    "### ContentProvider의 주요 특징",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| 데이터 추상화 | 내부 저장 방식에 관계없이 일관된 인터페이스 제공 |",
    "| 프로세스 간 통신 | IPC(Inter-Process Communication)를 통해 다른 앱과 데이터 교환 |",
    "| 권한 관리 | 읽기/쓰기 권한을 세밀하게 제어 가능 |",
    "| URI 기반 접근 | Content URI를 통해 데이터를 식별하고 접근 |",
    "| CRUD 지원 | query, insert, update, delete 메서드 제공 |",
    "",
    "## Content URI 구조",
    "",
    "ContentProvider에 접근하기 위해 **Content URI**를 사용합니다. URI는 다음과 같은 구조를 가집니다:",
    "",
    "```",
    "content://com.example.myapp.provider/users/5",
    "  ───┬──   ────────────┬────────────  ──┬── ┬",
    "  scheme         authority              path id",
    "```",
    "",
    "| 구성 요소 | 설명 | 예시 |",
    "|-----------|------|------|",
    "| scheme | 항상 `content://` 사용 | `content://` |",
    "| authority | Provider를 고유하게 식별하는 문자열 | `com.example.myapp.provider` |",
    "| path | 데이터 유형(테이블)을 지정 | `/users` |",
    "| id | 특정 레코드를 지정 (선택사항) | `/5` |",
    "",
    "```java",
    "// URI 예시",
    "Uri allUsersUri = Uri.parse(\"content://com.example.myapp.provider/users\");",
    "Uri singleUserUri = Uri.parse(\"content://com.example.myapp.provider/users/5\");",
    "",
    "// ContentUris 유틸리티 사용",
    "Uri userUri = ContentUris.withAppendedId(",
    "    Uri.parse(\"content://com.example.myapp.provider/users\"), 5);",
    "long userId = ContentUris.parseId(userUri); // 5",
    "```",
    "",
    "## ContentResolver 사용법",
    "",
    "ContentProvider에 접근하려면 **ContentResolver**를 사용합니다. Activity나 Context에서 `getContentResolver()`로 얻을 수 있습니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant App as 클라이언트 앱",
    "    participant CR as ContentResolver",
    "    participant CP as ContentProvider",
    "    participant DB as 데이터 저장소",
    "    App->>CR: query(uri, ...)",
    "    CR->>CP: query(uri, ...)",
    "    CP->>DB: SQL SELECT",
    "    DB-->>CP: 결과",
    "    CP-->>CR: Cursor",
    "    CR-->>App: Cursor",
    "```",
    "",
    "### query - 데이터 조회",
    "",
    "```java",
    "ContentResolver resolver = getContentResolver();",
    "",
    "// SQL의 SELECT에 해당",
    "Cursor cursor = resolver.query(",
    "    uri,           // Content URI (FROM 테이블)",
    "    projection,    // 반환할 컬럼 배열 (SELECT 컬럼)",
    "    selection,     // WHERE 절 조건 (WHERE ...)",
    "    selectionArgs, // WHERE 절의 ? 치환 값",
    "    sortOrder      // 정렬 순서 (ORDER BY ...)",
    ");",
    "",
    "// 예시: 모든 사용자 조회",
    "String[] projection = {\"_id\", \"name\", \"email\"};",
    "String selection = \"age > ?\";",
    "String[] selectionArgs = {\"18\"};",
    "String sortOrder = \"name ASC\";",
    "",
    "Cursor cursor = resolver.query(",
    "    Uri.parse(\"content://com.example.provider/users\"),",
    "    projection,",
    "    selection,",
    "    selectionArgs,",
    "    sortOrder",
    ");",
    "```",
    "",
    "### insert - 데이터 삽입",
    "",
    "```java",
    "ContentValues values = new ContentValues();",
    "values.put(\"name\", \"홍길동\");",
    "values.put(\"email\", \"hong@example.com\");",
    "values.put(\"age\", 25);",
    "",
    "Uri newUri = resolver.insert(",
    "    Uri.parse(\"content://com.example.provider/users\"),",
    "    values",
    ");",
    "// newUri = content://com.example.provider/users/1",
    "```",
    "",
    "### update - 데이터 수정",
    "",
    "```java",
    "ContentValues values = new ContentValues();",
    "values.put(\"email\", \"new_email@example.com\");",
    "",
    "int rowsUpdated = resolver.update(",
    "    Uri.parse(\"content://com.example.provider/users\"),",
    "    values,",
    "    \"name = ?\",",
    "    new String[]{\"홍길동\"}",
    ");",
    "```",
    "",
    "### delete - 데이터 삭제",
    "",
    "```java",
    "int rowsDeleted = resolver.delete(",
    "    Uri.parse(\"content://com.example.provider/users\"),",
    "    \"age < ?\",",
    "    new String[]{\"18\"}",
    ");",
    "```",
    "",
    "## Cursor로 결과 읽기",
    "",
    "query() 메서드는 **Cursor** 객체를 반환합니다. Cursor는 결과 집합(ResultSet)을 순회하며 데이터를 읽는 인터페이스입니다.",
    "",
    "```java",
    "Cursor cursor = resolver.query(uri, projection, null, null, null);",
    "",
    "if (cursor != null) {",
    "    try {",
    "        // 컬럼 인덱스 미리 확보",
    "        int idIndex = cursor.getColumnIndexOrThrow(\"_id\");",
    "        int nameIndex = cursor.getColumnIndexOrThrow(\"name\");",
    "        int emailIndex = cursor.getColumnIndexOrThrow(\"email\");",
    "",
    "        while (cursor.moveToNext()) {",
    "            long id = cursor.getLong(idIndex);",
    "            String name = cursor.getString(nameIndex);",
    "            String email = cursor.getString(emailIndex);",
    "",
    "            Log.d(\"User\", \"ID: \" + id + \", 이름: \" + name + \", 이메일: \" + email);",
    "        }",
    "    } finally {",
    "        cursor.close(); // 반드시 닫아야 메모리 누수 방지",
    "    }",
    "}",
    "```",
    "",
    "### Cursor 주요 메서드",
    "",
    "| 메서드 | 설명 |",
    "|--------|------|",
    "| `moveToFirst()` | 첫 번째 행으로 이동 |",
    "| `moveToNext()` | 다음 행으로 이동 (없으면 false) |",
    "| `moveToLast()` | 마지막 행으로 이동 |",
    "| `moveToPrevious()` | 이전 행으로 이동 |",
    "| `getCount()` | 전체 행 개수 반환 |",
    "| `getColumnIndex(name)` | 컬럼 이름으로 인덱스 반환 |",
    "| `getString(index)` | 문자열 값 읽기 |",
    "| `getInt(index)` | 정수 값 읽기 |",
    "| `getLong(index)` | Long 값 읽기 |",
    "| `close()` | 커서 닫기 (필수) |",
    "",
    "## 연락처(ContactsContract) 읽기 예제",
    "",
    "안드로이드 기본 연락처 앱은 ContentProvider를 통해 데이터를 제공합니다.",
    "",
    "### AndroidManifest.xml 권한 추가",
    "",
    "```xml",
    "<uses-permission android:name=\"android.permission.READ_CONTACTS\" />",
    "```",
    "",
    "### 연락처 이름과 전화번호 읽기",
    "",
    "```java",
    "private void readContacts() {",
    "    ContentResolver resolver = getContentResolver();",
    "",
    "    Cursor cursor = resolver.query(",
    "        ContactsContract.Contacts.CONTENT_URI,",
    "        null, null, null,",
    "        ContactsContract.Contacts.DISPLAY_NAME + \" ASC\"",
    "    );",
    "",
    "    if (cursor == null) return;",
    "",
    "    try {",
    "        while (cursor.moveToNext()) {",
    "            String id = cursor.getString(",
    "                cursor.getColumnIndexOrThrow(ContactsContract.Contacts._ID));",
    "            String name = cursor.getString(",
    "                cursor.getColumnIndexOrThrow(ContactsContract.Contacts.DISPLAY_NAME));",
    "            int hasPhone = cursor.getInt(",
    "                cursor.getColumnIndexOrThrow(ContactsContract.Contacts.HAS_PHONE_NUMBER));",
    "",
    "            if (hasPhone > 0) {",
    "                Cursor phoneCursor = resolver.query(",
    "                    ContactsContract.CommonDataKinds.Phone.CONTENT_URI,",
    "                    null,",
    "                    ContactsContract.CommonDataKinds.Phone.CONTACT_ID + \" = ?\",",
    "                    new String[]{id},",
    "                    null",
    "                );",
    "",
    "                if (phoneCursor != null) {",
    "                    while (phoneCursor.moveToNext()) {",
    "                        String phone = phoneCursor.getString(",
    "                            phoneCursor.getColumnIndexOrThrow(",
    "                                ContactsContract.CommonDataKinds.Phone.NUMBER));",
    "                        Log.d(\"Contact\", name + \": \" + phone);",
    "                    }",
    "                    phoneCursor.close();",
    "                }",
    "            }",
    "        }",
    "    } finally {",
    "        cursor.close();",
    "    }",
    "}",
    "```",
    "",
    "## 갤러리(MediaStore) 이미지 불러오기",
    "",
    "MediaStore를 사용하면 기기에 저장된 미디어 파일에 접근할 수 있습니다.",
    "",
    "```java",
    "private void loadGalleryImages() {",
    "    String[] projection = {",
    "        MediaStore.Images.Media._ID,",
    "        MediaStore.Images.Media.DISPLAY_NAME,",
    "        MediaStore.Images.Media.DATE_ADDED,",
    "        MediaStore.Images.Media.SIZE",
    "    };",
    "",
    "    String sortOrder = MediaStore.Images.Media.DATE_ADDED + \" DESC\";",
    "",
    "    Cursor cursor = getContentResolver().query(",
    "        MediaStore.Images.Media.EXTERNAL_CONTENT_URI,",
    "        projection,",
    "        null, null,",
    "        sortOrder",
    "    );",
    "",
    "    if (cursor == null) return;",
    "",
    "    try {",
    "        int idCol = cursor.getColumnIndexOrThrow(MediaStore.Images.Media._ID);",
    "        int nameCol = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DISPLAY_NAME);",
    "",
    "        while (cursor.moveToNext()) {",
    "            long id = cursor.getLong(idCol);",
    "            String name = cursor.getString(nameCol);",
    "",
    "            // 이미지 URI 생성",
    "            Uri contentUri = ContentUris.withAppendedId(",
    "                MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id);",
    "",
    "            Log.d(\"Gallery\", \"이미지: \" + name + \", URI: \" + contentUri);",
    "        }",
    "    } finally {",
    "        cursor.close();",
    "    }",
    "}",
    "```",
    "",
    "## 커스텀 ContentProvider 만들기",
    "",
    "직접 ContentProvider를 구현하여 다른 앱에 데이터를 제공할 수 있습니다.",
    "",
    "```mermaid",
    "classDiagram",
    "    class ContentProvider {",
    "        +onCreate() boolean",
    "        +query() Cursor",
    "        +insert() Uri",
    "        +update() int",
    "        +delete() int",
    "        +getType() String",
    "    }",
    "    class MyContentProvider {",
    "        -SQLiteOpenHelper dbHelper",
    "        -UriMatcher uriMatcher",
    "        +onCreate() boolean",
    "        +query() Cursor",
    "        +insert() Uri",
    "        +update() int",
    "        +delete() int",
    "        +getType() String",
    "    }",
    "    ContentProvider <|-- MyContentProvider",
    "```",
    "",
    "### UriMatcher 설정",
    "",
    "UriMatcher는 들어온 URI를 분석하여 어떤 데이터에 접근할지 결정합니다.",
    "",
    "```java",
    "public class BookProvider extends ContentProvider {",
    "",
    "    public static final String AUTHORITY = \"com.example.myapp.bookprovider\";",
    "    public static final Uri CONTENT_URI =",
    "        Uri.parse(\"content://\" + AUTHORITY + \"/books\");",
    "",
    "    private static final int BOOKS = 1;      // 전체 목록",
    "    private static final int BOOK_ID = 2;     // 개별 항목",
    "",
    "    private static final UriMatcher uriMatcher = new UriMatcher(UriMatcher.NO_MATCH);",
    "",
    "    static {",
    "        uriMatcher.addURI(AUTHORITY, \"books\", BOOKS);",
    "        uriMatcher.addURI(AUTHORITY, \"books/#\", BOOK_ID);",
    "    }",
    "",
    "    private BookDatabaseHelper dbHelper;",
    "",
    "    @Override",
    "    public boolean onCreate() {",
    "        dbHelper = new BookDatabaseHelper(getContext());",
    "        return true;",
    "    }",
    "",
    "    @Override",
    "    public Cursor query(Uri uri, String[] projection,",
    "                        String selection, String[] selectionArgs, String sortOrder) {",
    "        SQLiteDatabase db = dbHelper.getReadableDatabase();",
    "        Cursor cursor;",
    "",
    "        switch (uriMatcher.match(uri)) {",
    "            case BOOKS:",
    "                cursor = db.query(\"books\", projection,",
    "                    selection, selectionArgs, null, null, sortOrder);",
    "                break;",
    "            case BOOK_ID:",
    "                String id = uri.getLastPathSegment();",
    "                cursor = db.query(\"books\", projection,",
    "                    \"_id = ?\", new String[]{id}, null, null, sortOrder);",
    "                break;",
    "            default:",
    "                throw new IllegalArgumentException(\"알 수 없는 URI: \" + uri);",
    "        }",
    "",
    "        cursor.setNotificationUri(getContext().getContentResolver(), uri);",
    "        return cursor;",
    "    }",
    "",
    "    @Override",
    "    public Uri insert(Uri uri, ContentValues values) {",
    "        if (uriMatcher.match(uri) != BOOKS) {",
    "            throw new IllegalArgumentException(\"잘못된 URI: \" + uri);",
    "        }",
    "",
    "        SQLiteDatabase db = dbHelper.getWritableDatabase();",
    "        long id = db.insert(\"books\", null, values);",
    "",
    "        if (id == -1) {",
    "            throw new SQLException(\"삽입 실패: \" + uri);",
    "        }",
    "",
    "        getContext().getContentResolver().notifyChange(uri, null);",
    "        return ContentUris.withAppendedId(CONTENT_URI, id);",
    "    }",
    "",
    "    @Override",
    "    public int update(Uri uri, ContentValues values,",
    "                      String selection, String[] selectionArgs) {",
    "        SQLiteDatabase db = dbHelper.getWritableDatabase();",
    "        int rowsUpdated;",
    "",
    "        switch (uriMatcher.match(uri)) {",
    "            case BOOKS:",
    "                rowsUpdated = db.update(\"books\", values, selection, selectionArgs);",
    "                break;",
    "            case BOOK_ID:",
    "                String id = uri.getLastPathSegment();",
    "                rowsUpdated = db.update(\"books\", values,",
    "                    \"_id = ?\", new String[]{id});",
    "                break;",
    "            default:",
    "                throw new IllegalArgumentException(\"알 수 없는 URI: \" + uri);",
    "        }",
    "",
    "        if (rowsUpdated > 0) {",
    "            getContext().getContentResolver().notifyChange(uri, null);",
    "        }",
    "        return rowsUpdated;",
    "    }",
    "",
    "    @Override",
    "    public int delete(Uri uri, String selection, String[] selectionArgs) {",
    "        SQLiteDatabase db = dbHelper.getWritableDatabase();",
    "        int rowsDeleted;",
    "",
    "        switch (uriMatcher.match(uri)) {",
    "            case BOOKS:",
    "                rowsDeleted = db.delete(\"books\", selection, selectionArgs);",
    "                break;",
    "            case BOOK_ID:",
    "                String id = uri.getLastPathSegment();",
    "                rowsDeleted = db.delete(\"books\", \"_id = ?\", new String[]{id});",
    "                break;",
    "            default:",
    "                throw new IllegalArgumentException(\"알 수 없는 URI: \" + uri);",
    "        }",
    "",
    "        if (rowsDeleted > 0) {",
    "            getContext().getContentResolver().notifyChange(uri, null);",
    "        }",
    "        return rowsDeleted;",
    "    }",
    "",
    "    @Override",
    "    public String getType(Uri uri) {",
    "        switch (uriMatcher.match(uri)) {",
    "            case BOOKS:",
    "                return \"vnd.android.cursor.dir/vnd.\" + AUTHORITY + \".books\";",
    "            case BOOK_ID:",
    "                return \"vnd.android.cursor.item/vnd.\" + AUTHORITY + \".books\";",
    "            default:",
    "                throw new IllegalArgumentException(\"알 수 없는 URI: \" + uri);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "## AndroidManifest에 Provider 등록",
    "",
    "커스텀 ContentProvider는 반드시 AndroidManifest.xml에 등록해야 합니다.",
    "",
    "```xml",
    "<application>",
    "    <provider",
    "        android:name=\".BookProvider\"",
    "        android:authorities=\"com.example.myapp.bookprovider\"",
    "        android:exported=\"true\"",
    "        android:readPermission=\"com.example.myapp.READ_BOOKS\"",
    "        android:writePermission=\"com.example.myapp.WRITE_BOOKS\" />",
    "</application>",
    "```",
    "",
    "### 주요 속성 설명",
    "",
    "| 속성 | 설명 |",
    "|------|------|",
    "| `android:name` | Provider 클래스 이름 |",
    "| `android:authorities` | 고유 authority 문자열 |",
    "| `android:exported` | 다른 앱에서 접근 가능 여부 |",
    "| `android:readPermission` | 읽기 접근에 필요한 권한 |",
    "| `android:writePermission` | 쓰기 접근에 필요한 권한 |",
    "| `android:grantUriPermissions` | 임시 URI 권한 부여 가능 여부 |",
    "",
    "## ContentProvider vs 직접 DB 접근 비교",
    "",
    "| 비교 항목 | ContentProvider | 직접 DB 접근 |",
    "|-----------|----------------|-------------|",
    "| 앱 간 공유 | 가능 (IPC 지원) | 불가능 (같은 앱만) |",
    "| 접근 방식 | Content URI | 직접 SQLiteDatabase 참조 |",
    "| 보안 | 권한 기반 세밀한 제어 | 앱 내부 샌드박스에 의존 |",
    "| 추상화 | 저장 방식 숨김 (DB, 파일, 네트워크) | DB 구조 노출 |",
    "| CursorLoader | 지원 (UI 자동 갱신) | 별도 구현 필요 |",
    "| 성능 | IPC 오버헤드 있음 | 직접 접근으로 빠름 |",
    "| 복잡도 | 구현 코드 많음 | 상대적으로 간단 |",
    "| 사용 시기 | 다른 앱에 데이터 제공 시 | 앱 내부 전용 데이터 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A{다른 앱에<br>데이터 제공?} -->|Yes| B[ContentProvider 사용]",
    "    A -->|No| C{동기화/CursorLoader<br>필요?}",
    "    C -->|Yes| B",
    "    C -->|No| D[직접 DB 접근<br>Room 추천]",
    "```",
    "",
    "## ContentObserver - 데이터 변경 감지",
    "",
    "ContentObserver를 등록하면 ContentProvider의 데이터가 변경될 때 알림을 받을 수 있습니다.",
    "",
    "```java",
    "ContentObserver observer = new ContentObserver(new Handler(Looper.getMainLooper())) {",
    "    @Override",
    "    public void onChange(boolean selfChange, Uri uri) {",
    "        super.onChange(selfChange, uri);",
    "        Log.d(\"Observer\", \"데이터 변경 감지: \" + uri);",
    "        // UI 갱신 로직",
    "    }",
    "};",
    "",
    "// 옵저버 등록",
    "getContentResolver().registerContentObserver(",
    "    BookProvider.CONTENT_URI,",
    "    true,  // 하위 URI 변경도 감지",
    "    observer",
    ");",
    "",
    "// 해제 (onDestroy에서)",
    "getContentResolver().unregisterContentObserver(observer);",
    "```",
    "",
    "## 배치 작업 (Batch Operations)",
    "",
    "여러 작업을 한 번에 수행하려면 `ContentProviderOperation`을 사용합니다.",
    "",
    "```java",
    "ArrayList<ContentProviderOperation> ops = new ArrayList<>();",
    "",
    "ops.add(ContentProviderOperation.newInsert(BookProvider.CONTENT_URI)",
    "    .withValue(\"title\", \"안드로이드 프로그래밍\")",
    "    .withValue(\"author\", \"김개발\")",
    "    .build());",
    "",
    "ops.add(ContentProviderOperation.newInsert(BookProvider.CONTENT_URI)",
    "    .withValue(\"title\", \"코틀린 인 액션\")",
    "    .withValue(\"author\", \"드미트리\")",
    "    .build());",
    "",
    "ops.add(ContentProviderOperation.newUpdate(BookProvider.CONTENT_URI)",
    "    .withSelection(\"author = ?\", new String[]{\"이저자\"})",
    "    .withValue(\"author\", \"새저자\")",
    "    .build());",
    "",
    "try {",
    "    ContentProviderResult[] results =",
    "        getContentResolver().applyBatch(BookProvider.AUTHORITY, ops);",
    "    Log.d(\"Batch\", \"배치 작업 완료: \" + results.length + \"건\");",
    "} catch (Exception e) {",
    "    Log.e(\"Batch\", \"배치 작업 실패\", e);",
    "}",
    "```",
    "",
    "## 정리",
    "",
    "ContentProvider는 안드로이드에서 앱 간 데이터 공유의 핵심입니다. 연락처, 갤러리, 캘린더 등 시스템 앱들이 모두 ContentProvider를 통해 데이터를 제공하고 있으며, 직접 커스텀 Provider를 구현하여 다른 앱에 데이터를 안전하게 제공할 수도 있습니다. Content URI 구조, ContentResolver의 CRUD 메서드, Cursor 활용, UriMatcher 패턴을 잘 이해하면 ContentProvider를 효과적으로 활용할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
