<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "android-ui-components",
  title: "Android UI 컴포넌트 - Toast, Dialog, Event 처리",
  date: "2025-12-28",
  summary: "Android에서 자주 사용하는 UI 위젯과 사용자 인터랙션 처리 방법을 정리합니다. Toast, Snackbar, AlertDialog, 이벤트 리스너, Drawable 등을 다룹니다.",
  category: "Technology/Android",
  tags: ["android", "ui", "toast", "dialog", "event", "widget"],
  content: [
    "## 기본 UI 위젯 (View)",
    "",
    "Android에서는 다양한 UI 컴포넌트(위젯)를 제공합니다. 모든 위젯은 `View` 클래스를 상속받으며, XML 레이아웃에서 선언하고 Java/Kotlin 코드에서 제어합니다.",
    "",
    "```mermaid",
    "graph TD",
    "    A[View] --> B[TextView]",
    "    A --> C[EditText]",
    "    A --> D[Button]",
    "    A --> E[ImageView]",
    "    A --> F[CompoundButton]",
    "    F --> F1[CheckBox]",
    "    F --> F2[RadioButton]",
    "    F --> F3[Switch]",
    "    A --> G[ProgressBar]",
    "    A --> H[SeekBar]",
    "    A --> I[Spinner]",
    "```",
    "",
    "---",
    "",
    "## TextView",
    "",
    "텍스트를 화면에 표시하는 가장 기본적인 위젯입니다.",
    "",
    "```xml",
    "<TextView",
    "    android:id=\"@+id/tvMessage\"",
    "    android:layout_width=\"wrap_content\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:text=\"안녕하세요\"",
    "    android:textSize=\"18sp\"",
    "    android:textColor=\"#333333\"",
    "    android:textStyle=\"bold\"",
    "    android:maxLines=\"2\"",
    "    android:ellipsize=\"end\" />",
    "```",
    "",
    "| 속성 | 설명 |",
    "| --- | --- |",
    "| `android:text` | 표시할 텍스트 |",
    "| `android:textSize` | 텍스트 크기 (sp 단위 권장) |",
    "| `android:textColor` | 텍스트 색상 |",
    "| `android:textStyle` | bold, italic, normal |",
    "| `android:maxLines` | 최대 줄 수 |",
    "| `android:ellipsize` | 텍스트 넘칠 때 ... 처리 (start, middle, end) |",
    "",
    "---",
    "",
    "## EditText",
    "",
    "사용자로부터 텍스트 입력을 받는 위젯입니다.",
    "",
    "```xml",
    "<EditText",
    "    android:id=\"@+id/etName\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:hint=\"이름을 입력하세요\"",
    "    android:inputType=\"textPersonName\"",
    "    android:maxLength=\"20\" />",
    "",
    "<EditText",
    "    android:id=\"@+id/etPassword\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:hint=\"비밀번호\"",
    "    android:inputType=\"textPassword\" />",
    "",
    "<EditText",
    "    android:id=\"@+id/etEmail\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:hint=\"이메일\"",
    "    android:inputType=\"textEmailAddress\" />",
    "```",
    "",
    "### inputType 종류",
    "",
    "| inputType | 설명 |",
    "| --- | --- |",
    "| `text` | 일반 텍스트 |",
    "| `textPassword` | 비밀번호 (마스킹) |",
    "| `textEmailAddress` | 이메일 (@ 키보드) |",
    "| `number` | 숫자 키패드 |",
    "| `phone` | 전화번호 키패드 |",
    "| `textMultiLine` | 여러 줄 입력 |",
    "",
    "### 코드에서 값 가져오기",
    "",
    "```java",
    "EditText etName = findViewById(R.id.etName);",
    "String name = etName.getText().toString();",
    "```",
    "",
    "---",
    "",
    "## Button",
    "",
    "사용자가 클릭할 수 있는 버튼입니다.",
    "",
    "```xml",
    "<Button",
    "    android:id=\"@+id/btnSubmit\"",
    "    android:layout_width=\"wrap_content\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:text=\"제출\"",
    "    android:backgroundTint=\"#2196F3\"",
    "    android:textColor=\"#FFFFFF\" />",
    "```",
    "",
    "```java",
    "Button btnSubmit = findViewById(R.id.btnSubmit);",
    "btnSubmit.setOnClickListener(v -> {",
    "    // 버튼 클릭 시 실행할 코드",
    "});",
    "```",
    "",
    "---",
    "",
    "## ImageView",
    "",
    "이미지를 표시하는 위젯입니다.",
    "",
    "```xml",
    "<ImageView",
    "    android:id=\"@+id/ivPhoto\"",
    "    android:layout_width=\"200dp\"",
    "    android:layout_height=\"200dp\"",
    "    android:src=\"@drawable/sample_image\"",
    "    android:scaleType=\"centerCrop\"",
    "    android:contentDescription=\"샘플 이미지\" />",
    "```",
    "",
    "| scaleType | 설명 |",
    "| --- | --- |",
    "| `centerCrop` | 비율 유지, 뷰를 꽉 채움 (잘릴 수 있음) |",
    "| `centerInside` | 비율 유지, 뷰 안에 들어가도록 축소 |",
    "| `fitCenter` | 비율 유지, 뷰 중앙에 맞춤 (기본값) |",
    "| `fitXY` | 비율 무시, 뷰 크기에 맞춤 |",
    "",
    "---",
    "",
    "## CheckBox, RadioButton, Switch",
    "",
    "### CheckBox",
    "",
    "```xml",
    "<CheckBox",
    "    android:id=\"@+id/cbAgree\"",
    "    android:layout_width=\"wrap_content\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:text=\"이용약관에 동의합니다\" />",
    "```",
    "",
    "```java",
    "CheckBox cbAgree = findViewById(R.id.cbAgree);",
    "cbAgree.setOnCheckedChangeListener((buttonView, isChecked) -> {",
    "    if (isChecked) {",
    "        // 체크됨",
    "    } else {",
    "        // 체크 해제됨",
    "    }",
    "});",
    "```",
    "",
    "### RadioButton & RadioGroup",
    "",
    "```xml",
    "<RadioGroup",
    "    android:id=\"@+id/rgGender\"",
    "    android:layout_width=\"wrap_content\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:orientation=\"horizontal\">",
    "",
    "    <RadioButton",
    "        android:id=\"@+id/rbMale\"",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"wrap_content\"",
    "        android:text=\"남성\" />",
    "",
    "    <RadioButton",
    "        android:id=\"@+id/rbFemale\"",
    "        android:layout_width=\"wrap_content\"",
    "        android:layout_height=\"wrap_content\"",
    "        android:text=\"여성\" />",
    "",
    "</RadioGroup>",
    "```",
    "",
    "### Switch",
    "",
    "```xml",
    "<Switch",
    "    android:id=\"@+id/swNotification\"",
    "    android:layout_width=\"wrap_content\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:text=\"알림 받기\" />",
    "```",
    "",
    "---",
    "",
    "## ProgressBar와 SeekBar",
    "",
    "### ProgressBar",
    "",
    "```xml",
    "<!-- 원형 로딩 (기본) -->",
    "<ProgressBar",
    "    android:id=\"@+id/pbLoading\"",
    "    android:layout_width=\"wrap_content\"",
    "    android:layout_height=\"wrap_content\" />",
    "",
    "<!-- 수평 진행 바 -->",
    "<ProgressBar",
    "    android:id=\"@+id/pbDownload\"",
    "    style=\"@android:style/Widget.ProgressBar.Horizontal\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:max=\"100\"",
    "    android:progress=\"45\" />",
    "```",
    "",
    "### SeekBar",
    "",
    "```xml",
    "<SeekBar",
    "    android:id=\"@+id/sbVolume\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\"",
    "    android:max=\"100\"",
    "    android:progress=\"50\" />",
    "```",
    "",
    "```java",
    "SeekBar sbVolume = findViewById(R.id.sbVolume);",
    "sbVolume.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {",
    "    @Override",
    "    public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {",
    "        // progress 값 변경 시",
    "    }",
    "",
    "    @Override",
    "    public void onStartTrackingTouch(SeekBar seekBar) { }",
    "",
    "    @Override",
    "    public void onStopTrackingTouch(SeekBar seekBar) { }",
    "});",
    "```",
    "",
    "---",
    "",
    "## Spinner (드롭다운 선택)",
    "",
    "```xml",
    "<Spinner",
    "    android:id=\"@+id/spCity\"",
    "    android:layout_width=\"match_parent\"",
    "    android:layout_height=\"wrap_content\" />",
    "```",
    "",
    "```java",
    "Spinner spCity = findViewById(R.id.spCity);",
    "String[] cities = {\"서울\", \"부산\", \"대구\", \"인천\", \"광주\"};",
    "ArrayAdapter<String> adapter = new ArrayAdapter<>(",
    "    this, android.R.layout.simple_spinner_item, cities);",
    "adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);",
    "spCity.setAdapter(adapter);",
    "",
    "spCity.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {",
    "    @Override",
    "    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {",
    "        String selected = cities[position];",
    "    }",
    "",
    "    @Override",
    "    public void onNothingSelected(AdapterView<?> parent) { }",
    "});",
    "```",
    "",
    "---",
    "",
    "## Toast 메시지",
    "",
    "**Toast**는 화면 하단에 잠시 나타났다 사라지는 짧은 알림 메시지입니다.",
    "",
    "```java",
    "// 짧은 시간 표시",
    "Toast.makeText(this, \"저장되었습니다\", Toast.LENGTH_SHORT).show();",
    "",
    "// 긴 시간 표시",
    "Toast.makeText(this, \"업로드가 완료되었습니다\", Toast.LENGTH_LONG).show();",
    "```",
    "",
    "| 상수 | 지속 시간 |",
    "| --- | --- |",
    "| `Toast.LENGTH_SHORT` | 약 2초 |",
    "| `Toast.LENGTH_LONG` | 약 3.5초 |",
    "",
    "> **참고**: Android 11(API 30)부터 백그라운드에서의 커스텀 Toast는 제한됩니다.",
    "",
    "---",
    "",
    "## Snackbar",
    "",
    "**Snackbar**는 Toast보다 기능이 풍부한 알림으로, **액션 버튼**을 포함할 수 있습니다. Material Design 라이브러리에 포함되어 있습니다.",
    "",
    "```java",
    "// 기본 Snackbar",
    "Snackbar.make(view, \"항목이 삭제되었습니다\", Snackbar.LENGTH_LONG).show();",
    "",
    "// 액션 버튼 포함",
    "Snackbar.make(view, \"항목이 삭제되었습니다\", Snackbar.LENGTH_LONG)",
    "    .setAction(\"실행 취소\", v -> {",
    "        // 삭제 취소 로직",
    "    })",
    "    .show();",
    "```",
    "",
    "| 비교 | Toast | Snackbar |",
    "| --- | --- | --- |",
    "| 위치 | 화면 하단 | 화면 하단 |",
    "| 액션 버튼 | 없음 | 가능 |",
    "| 스와이프 해제 | 불가 | 가능 |",
    "| 커스텀 뷰 | 제한적 | 가능 |",
    "| 의존성 | 기본 제공 | Material 라이브러리 필요 |",
    "",
    "---",
    "",
    "## AlertDialog",
    "",
    "**AlertDialog**는 사용자에게 확인, 선택, 입력을 요청하는 팝업 대화상자입니다.",
    "",
    "### 기본 AlertDialog",
    "",
    "```java",
    "new AlertDialog.Builder(this)",
    "    .setTitle(\"확인\")",
    "    .setMessage(\"정말로 삭제하시겠습니까?\")",
    "    .setPositiveButton(\"삭제\", (dialog, which) -> {",
    "        // 삭제 로직",
    "    })",
    "    .setNegativeButton(\"취소\", (dialog, which) -> {",
    "        dialog.dismiss();",
    "    })",
    "    .show();",
    "```",
    "",
    "### 리스트 AlertDialog",
    "",
    "```java",
    "String[] items = {\"빨강\", \"초록\", \"파랑\"};",
    "",
    "new AlertDialog.Builder(this)",
    "    .setTitle(\"색상 선택\")",
    "    .setItems(items, (dialog, which) -> {",
    "        String selected = items[which];",
    "        Toast.makeText(this, selected + \" 선택됨\", Toast.LENGTH_SHORT).show();",
    "    })",
    "    .show();",
    "```",
    "",
    "### 커스텀 레이아웃 AlertDialog",
    "",
    "```java",
    "View dialogView = getLayoutInflater().inflate(R.layout.dialog_custom, null);",
    "EditText etInput = dialogView.findViewById(R.id.etDialogInput);",
    "",
    "new AlertDialog.Builder(this)",
    "    .setTitle(\"이름 입력\")",
    "    .setView(dialogView)",
    "    .setPositiveButton(\"확인\", (dialog, which) -> {",
    "        String input = etInput.getText().toString();",
    "    })",
    "    .setNegativeButton(\"취소\", null)",
    "    .show();",
    "```",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[AlertDialog 유형] --> B[기본 메시지]",
    "    A --> C[리스트 선택]",
    "    A --> D[단일 선택 Radio]",
    "    A --> E[다중 선택 CheckBox]",
    "    A --> F[커스텀 레이아웃]",
    "    B --> B1[setMessage]",
    "    C --> C1[setItems]",
    "    D --> D1[setSingleChoiceItems]",
    "    E --> E1[setMultiChoiceItems]",
    "    F --> F1[setView]",
    "```",
    "",
    "---",
    "",
    "## DatePickerDialog / TimePickerDialog",
    "",
    "### DatePickerDialog",
    "",
    "```java",
    "Calendar calendar = Calendar.getInstance();",
    "int year = calendar.get(Calendar.YEAR);",
    "int month = calendar.get(Calendar.MONTH);",
    "int day = calendar.get(Calendar.DAY_OF_MONTH);",
    "",
    "DatePickerDialog dateDialog = new DatePickerDialog(",
    "    this,",
    "    (view, selectedYear, selectedMonth, selectedDay) -> {",
    "        String date = selectedYear + \"-\" + (selectedMonth + 1) + \"-\" + selectedDay;",
    "        tvDate.setText(date);",
    "    },",
    "    year, month, day",
    ");",
    "dateDialog.show();",
    "```",
    "",
    "### TimePickerDialog",
    "",
    "```java",
    "int hour = calendar.get(Calendar.HOUR_OF_DAY);",
    "int minute = calendar.get(Calendar.MINUTE);",
    "",
    "TimePickerDialog timeDialog = new TimePickerDialog(",
    "    this,",
    "    (view, selectedHour, selectedMinute) -> {",
    "        String time = selectedHour + \":\" + String.format(\"%02d\", selectedMinute);",
    "        tvTime.setText(time);",
    "    },",
    "    hour, minute, true",
    ");",
    "timeDialog.show();",
    "```",
    "",
    "---",
    "",
    "## 이벤트 처리",
    "",
    "Android에서 사용자 인터랙션은 **이벤트 리스너(Listener)**를 통해 처리합니다.",
    "",
    "### OnClickListener",
    "",
    "가장 기본적인 클릭 이벤트 처리입니다.",
    "",
    "```java",
    "// 방법 1: 람다식 (Java 8+)",
    "btnSubmit.setOnClickListener(v -> {",
    "    Toast.makeText(this, \"클릭됨\", Toast.LENGTH_SHORT).show();",
    "});",
    "",
    "// 방법 2: 익명 클래스",
    "btnSubmit.setOnClickListener(new View.OnClickListener() {",
    "    @Override",
    "    public void onClick(View v) {",
    "        Toast.makeText(MainActivity.this, \"클릭됨\", Toast.LENGTH_SHORT).show();",
    "    }",
    "});",
    "",
    "// 방법 3: Activity에서 인터페이스 구현",
    "public class MainActivity extends AppCompatActivity implements View.OnClickListener {",
    "    @Override",
    "    public void onClick(View v) {",
    "        if (v.getId() == R.id.btnSubmit) {",
    "            // 처리",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### OnLongClickListener",
    "",
    "뷰를 길게 누르면 발생하는 이벤트입니다.",
    "",
    "```java",
    "btnSubmit.setOnLongClickListener(v -> {",
    "    Toast.makeText(this, \"길게 클릭됨\", Toast.LENGTH_SHORT).show();",
    "    return true; // true: 이벤트 소비, false: 클릭 이벤트도 발생",
    "});",
    "```",
    "",
    "### OnTouchListener",
    "",
    "터치 이벤트를 세밀하게 처리할 수 있습니다.",
    "",
    "```java",
    "imageView.setOnTouchListener((v, event) -> {",
    "    switch (event.getAction()) {",
    "        case MotionEvent.ACTION_DOWN:",
    "            // 터치 시작",
    "            break;",
    "        case MotionEvent.ACTION_MOVE:",
    "            float x = event.getX();",
    "            float y = event.getY();",
    "            // 터치 이동 중",
    "            break;",
    "        case MotionEvent.ACTION_UP:",
    "            // 터치 종료",
    "            break;",
    "    }",
    "    return true;",
    "});",
    "```",
    "",
    "### 이벤트 처리 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant User as 사용자",
    "    participant View as 뷰(Button)",
    "    participant Listener as 이벤트 리스너",
    "    participant Handler as 핸들러 코드",
    "    User->>View: 터치/클릭",
    "    View->>Listener: 이벤트 전달",
    "    Listener->>Handler: 콜백 메서드 호출",
    "    Handler->>View: UI 업데이트",
    "```",
    "",
    "---",
    "",
    "## Drawable 리소스",
    "",
    "**Drawable**은 화면에 그릴 수 있는 그래픽 리소스입니다. `res/drawable/` 폴더에 XML로 정의합니다.",
    "",
    "### Shape Drawable",
    "",
    "```xml",
    "<!-- res/drawable/rounded_background.xml -->",
    "<shape xmlns:android=\"http://schemas.android.com/apk/res/android\"",
    "    android:shape=\"rectangle\">",
    "    <solid android:color=\"#2196F3\" />",
    "    <corners android:radius=\"12dp\" />",
    "    <stroke",
    "        android:width=\"2dp\"",
    "        android:color=\"#1976D2\" />",
    "    <padding android:all=\"8dp\" />",
    "</shape>",
    "```",
    "",
    "### Selector Drawable (상태별 스타일)",
    "",
    "```xml",
    "<!-- res/drawable/button_selector.xml -->",
    "<selector xmlns:android=\"http://schemas.android.com/apk/res/android\">",
    "    <item android:state_pressed=\"true\">",
    "        <shape android:shape=\"rectangle\">",
    "            <solid android:color=\"#1976D2\" />",
    "            <corners android:radius=\"8dp\" />",
    "        </shape>",
    "    </item>",
    "    <item>",
    "        <shape android:shape=\"rectangle\">",
    "            <solid android:color=\"#2196F3\" />",
    "            <corners android:radius=\"8dp\" />",
    "        </shape>",
    "    </item>",
    "</selector>",
    "```",
    "",
    "### Layer-list Drawable",
    "",
    "```xml",
    "<!-- res/drawable/layered_background.xml -->",
    "<layer-list xmlns:android=\"http://schemas.android.com/apk/res/android\">",
    "    <item>",
    "        <shape android:shape=\"rectangle\">",
    "            <solid android:color=\"#CCCCCC\" />",
    "        </shape>",
    "    </item>",
    "    <item android:left=\"2dp\" android:top=\"2dp\"",
    "          android:right=\"0dp\" android:bottom=\"0dp\">",
    "        <shape android:shape=\"rectangle\">",
    "            <solid android:color=\"#FFFFFF\" />",
    "        </shape>",
    "    </item>",
    "</layer-list>",
    "```",
    "",
    "---",
    "",
    "## 화면 회전 대응",
    "",
    "화면이 회전하면 Activity가 **파괴 후 재생성**됩니다. 이때 데이터가 손실될 수 있으므로 대비가 필요합니다.",
    "",
    "### 방법 1: onSaveInstanceState",
    "",
    "```java",
    "@Override",
    "protected void onSaveInstanceState(Bundle outState) {",
    "    super.onSaveInstanceState(outState);",
    "    outState.putString(\"userInput\", etInput.getText().toString());",
    "    outState.putInt(\"counter\", counter);",
    "}",
    "",
    "@Override",
    "protected void onCreate(Bundle savedInstanceState) {",
    "    super.onCreate(savedInstanceState);",
    "    setContentView(R.layout.activity_main);",
    "",
    "    if (savedInstanceState != null) {",
    "        String saved = savedInstanceState.getString(\"userInput\");",
    "        counter = savedInstanceState.getInt(\"counter\");",
    "        etInput.setText(saved);",
    "    }",
    "}",
    "```",
    "",
    "### 방법 2: ViewModel 사용 (권장)",
    "",
    "```java",
    "public class MainViewModel extends ViewModel {",
    "    private int counter = 0;",
    "",
    "    public int getCounter() { return counter; }",
    "    public void increment() { counter++; }",
    "}",
    "",
    "// Activity에서 사용",
    "MainViewModel viewModel = new ViewModelProvider(this).get(MainViewModel.class);",
    "viewModel.increment();",
    "int count = viewModel.getCounter();",
    "```",
    "",
    "### 방법 3: 회전 방지 (권장하지 않음)",
    "",
    "```xml",
    "<!-- AndroidManifest.xml -->",
    "<activity",
    "    android:name=\".MainActivity\"",
    "    android:configChanges=\"orientation|screenSize\"",
    "    android:screenOrientation=\"portrait\" />",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "```mermaid",
    "mindmap",
    "  root((UI 컴포넌트))",
    "    입력 위젯",
    "      TextView",
    "      EditText",
    "      Button",
    "      CheckBox/Radio/Switch",
    "    알림",
    "      Toast",
    "      Snackbar",
    "    다이얼로그",
    "      AlertDialog",
    "      DatePickerDialog",
    "      TimePickerDialog",
    "    이벤트",
    "      OnClickListener",
    "      OnLongClickListener",
    "      OnTouchListener",
    "    그래픽",
    "      Shape Drawable",
    "      Selector",
    "      Layer-list",
    "```",
    "",
    "다음 글에서는 **Activity와 Intent**를 다룹니다. 화면 전환과 데이터 전달의 핵심을 정리합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
