<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "artificial-neural-network",
  title: "인공 신경망(Artificial Neural Network, ANN)",
  date: "2026-02-17",
  summary: "인공 신경망은 뉴런을 모사한 유닛들이 연결된 구조입니다. 퍼셉트론, Dense 층, 활성화 함수, 케라스 Sequential까지 정리합니다.",
  category: "Technology/AI",
  tags: ["ai", "deep-learning", "neural-network", "keras", "tensorflow"],
  content: [
    "## 인공 신경망이란?",
    "**인공 신경망(ANN)**은 생물의 뇌를 모사해 **여러 뉴런(유닛)**이 연결된 구조입니다. 입력에 가중치를 곱하고 합한 뒤 **활성화 함수**를 거쳐 출력으로 넘깁니다.",
    "",
    "| 구성 요소 | 설명 |",
    "|----------|------|",
    "| 입력층 | 원본 데이터가 들어오는 층 |",
    "| 은닉층 | 중간에서 특징을 학습하는 층 |",
    "| 출력층 | 최종 예측을 내보내는 층 |",
    "| 가중치 | 입력과 곱해지는 학습 가능한 파라미터 |",
    "| 활성화 함수 | 비선형을 부여해 표현력 확보 |",
    "",
    "---",
    "## 퍼셉트론",
    "가장 단순한 형태의 인공 신경망으로, 입력 → 가중합 → 활성화 → 출력의 구조를 가집니다.",
    "",
    "z = w₁x₁ + w₂x₂ + ... + b  (가중합 + 편향)",
    "y = activation(z)",
    "",
    "---",
    "## Dense(완전 연결) 층",
    "**Dense**는 이전 층의 **모든 유닛**과 연결된 층입니다. 입력 차원 → 출력 차원으로 변환합니다.",
    "",
    "```python",
    "from tensorflow import keras",
    "",
    "# 784개 입력 → 10개 출력 (다중 분류)",
    "dense = keras.layers.Dense(10, activation='softmax', input_shape=(784,))",
    "model = keras.Sequential([dense])",
    "",
    "model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics='accuracy')",
    "model.fit(train_scaled, train_target, epochs=5)",
    "```",
    "",
    "---",
    "## 활성화 함수",
    "| 함수 | 용도 | 특징 |",
    "|------|------|------|",
    "| sigmoid | 이진 분류 출력 | 0~1, 기울기 소실 가능 |",
    "| softmax | 다중 분류 출력 | 확률 합 1 |",
    "| relu | 은닉층 | max(0,x), 기울기 소실 완화 |",
    "",
    "---",
    "## 패션 MNIST 예시",
    "28×28 패션 이미지를 10개 클래스로 분류하는 예제입니다.",
    "",
    "```python",
    "(train_input, train_target), (test_input, test_target) = keras.datasets.fashion_mnist.load_data()",
    "",
    "train_scaled = train_input / 255.0",
    "train_scaled = train_scaled.reshape(-1, 28*28)",
    "",
    "model = keras.Sequential([",
    "    keras.layers.Dense(10, activation='softmax', input_shape=(784,))",
    "])",
    "model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics='accuracy')",
    "model.fit(train_scaled, train_target, epochs=5)",
    "```",
    "",
    "---",
    "## 정리",
    "| 용어 | 요약 |",
    "|------|------|",
    "| 인공 신경망 | 뉴런 모사, 가중치·활성화로 학습 |",
    "| Dense | 완전 연결층 |",
    "| softmax | 다중 분류 출력용 활성화 |",
    "| Sequential | 케라스 순차 모델 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
