<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "container-os-reality",
  title: "컨테이너에서 돌아가는 OS의 실체",
  date: "2026-02-11",
  summary: "컨테이너 안의 Alpine/Ubuntu는 전체 OS가 아니라 rootfs입니다. 커널은 호스트와 공유합니다.",
  category: "Technology/Docker",
  tags: ["docker","container","os","rootfs","kernel"],
  content: [
    "## 한 줄 요약",
    "컨테이너 안의 Alpine/Ubuntu는 **OS 전체가 아니라 rootfs(파일 시스템)**이며, 커널은 호스트와 공유합니다.",
    "",
    "---",
    "",
    "## OS의 구조를 먼저 이해하자",
    "",
    "운영체제(OS)는 크게 두 부분으로 나뉩니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "  U[\"사용자 공간<br>(셸, 유틸리티, 라이브러리, 패키지 매니저, 설정 파일)\"]",
    "  K[\"커널 Kernel<br>(프로세스, 메모리, 파일시스템, 네트워크, 디바이스 관리)\"]",
    "  U --- K",
    "```",
    "",
    "| 구분 | 역할 | 예시 |",
    "|------|------|------|",
    "| **커널** | 하드웨어와 소통, 프로세스·메모리·파일 관리 | Linux kernel 6.x |",
    "| **사용자 공간 (rootfs)** | 셸, 명령어, 라이브러리, 패키지 매니저 등 | bash, apt, apk, glibc |",
    "",
    "> **핵심**: 우리가 \"Ubuntu\"라고 부르는 것은 **커널 + 사용자 공간**의 조합입니다. 컨테이너에서는 이 중 **사용자 공간(rootfs)만** 가져옵니다.",
    "",
    "---",
    "",
    "## 컨테이너의 OS는 rootfs다",
    "",
    "### rootfs란?",
    "",
    "rootfs(Root File System)는 `/` 디렉터리 아래의 전체 파일 트리입니다.",
    "",
    "```",
    "rootfs (/)",
    "├── bin/      ← ls, cat, sh 등 기본 명령어",
    "├── etc/      ← 설정 파일 (apt, apk 등)",
    "├── lib/      ← 공유 라이브러리 (glibc, musl 등)",
    "├── usr/      ← 사용자 프로그램, 라이브러리",
    "├── var/      ← 로그, 캐시",
    "├── tmp/      ← 임시 파일",
    "└── sbin/     ← 시스템 관리 명령어",
    "```",
    "",
    "### 컨테이너에서 일어나는 일",
    "",
    "```mermaid",
    "flowchart TD",
    "  subgraph Host[\"호스트 머신 (Linux)\"]",
    "    K[\"Linux Kernel<br>(프로세스, 메모리, 파일시스템, 네트워크)\"]",
    "    CA[\"컨테이너A<br>Alpine rootfs<br>apk, musl\"]",
    "    CB[\"컨테이너B<br>Ubuntu rootfs<br>apt, glibc\"]",
    "    HP[\"호스트 프로세스\"]",
    "  end",
    "  CA ---|커널 공유| K",
    "  CB ---|커널 공유| K",
    "  HP --- K",
    "```",
    "",
    "| 항목 | VM | 컨테이너 |",
    "|------|-----|---------|",
    "| 커널 | 각 VM마다 별도 커널 | **호스트 커널 공유** |",
    "| OS 이미지 | 전체 OS (수 GB) | rootfs만 (수 MB~수백 MB) |",
    "| 부팅 | Guest OS 부팅 필요 | 프로세스 실행만 (1초 이내) |",
    "| 격리 수준 | 하드웨어 수준 격리 | 커널 namespace + cgroup |",
    "",
    "---",
    "",
    "## 직접 확인해보기",
    "",
    "### 1. 컨테이너에서 커널 버전 확인",
    "```bash",
    "# 호스트에서 커널 확인",
    "uname -r",
    "# 출력: 5.15.0-91-generic",
    "",
    "# Alpine 컨테이너에서 커널 확인",
    "docker run --rm alpine uname -r",
    "# 출력: 5.15.0-91-generic  ← 호스트와 동일!",
    "",
    "# Ubuntu 컨테이너에서 커널 확인",
    "docker run --rm ubuntu uname -r",
    "# 출력: 5.15.0-91-generic  ← 역시 호스트와 동일!",
    "```",
    "",
    "> 컨테이너마다 다른 커널이 있는 게 아닙니다. 모두 **호스트의 동일한 커널**을 사용합니다.",
    "",
    "### 2. rootfs의 차이 확인",
    "```bash",
    "# Alpine - musl libc 기반, apk 패키지 매니저",
    "docker run --rm alpine cat /etc/os-release",
    "# NAME=\"Alpine Linux\"",
    "",
    "docker run --rm alpine ls /lib/",
    "# ld-musl-x86_64.so.1  ← musl 라이브러리",
    "",
    "# Ubuntu - glibc 기반, apt 패키지 매니저",
    "docker run --rm ubuntu cat /etc/os-release",
    "# NAME=\"Ubuntu\"",
    "",
    "docker run --rm ubuntu ls /lib/x86_64-linux-gnu/",
    "# libc.so.6  ← glibc 라이브러리",
    "```",
    "",
    "### 3. 이미지 크기 비교",
    "```bash",
    "docker images --format '{{.Repository}}:{{.Tag}}  {{.Size}}'",
    "```",
    "",
    "| 이미지 | 크기 | 포함된 것 |",
    "|--------|------|----------|",
    "| `alpine:latest` | ~7 MB | musl, busybox, apk |",
    "| `ubuntu:latest` | ~78 MB | glibc, apt, coreutils |",
    "| `debian:latest` | ~139 MB | glibc, apt, 더 많은 유틸 |",
    "| `centos:latest` | ~231 MB | glibc, yum/dnf |",
    "",
    "> 전체 OS라면 수 GB인데, 컨테이너 이미지는 수 MB~수백 MB입니다. 커널이 빠져 있기 때문입니다.",
    "",
    "---",
    "",
    "## 커널 공유가 가능한 이유: namespace와 cgroup",
    "",
    "하나의 커널을 여러 컨테이너가 공유하면서도 격리가 되는 이유는 Linux의 두 가지 기능 덕분입니다.",
    "",
    "### namespace (격리)",
    "",
    "| namespace | 격리하는 것 | 효과 |",
    "|-----------|-----------|------|",
    "| **PID** | 프로세스 ID | 컨테이너마다 PID 1부터 시작 |",
    "| **NET** | 네트워크 | 컨테이너마다 별도 IP, 포트 |",
    "| **MNT** | 파일시스템 마운트 | 컨테이너마다 독립된 / 경로 |",
    "| **UTS** | 호스트명 | 컨테이너마다 별도 hostname |",
    "| **IPC** | 프로세스 간 통신 | 컨테이너 간 IPC 격리 |",
    "| **USER** | 사용자 ID | 컨테이너 내부 root ≠ 호스트 root |",
    "",
    "```",
    "하나의 Linux 커널",
    "├── PID namespace A  →  컨테이너 A는 PID 1, 2, 3 ...",
    "├── PID namespace B  →  컨테이너 B도 PID 1, 2, 3 ...",
    "└── 호스트           →  전체 PID를 볼 수 있음",
    "```",
    "",
    "### cgroup (자원 제한)",
    "",
    "| 자원 | 제한 예시 |",
    "|------|----------|",
    "| CPU | 최대 2코어만 사용 |",
    "| 메모리 | 최대 512MB만 사용 |",
    "| I/O | 디스크 읽기/쓰기 속도 제한 |",
    "| 네트워크 | 대역폭 제한 |",
    "",
    "```bash",
    "# 메모리 256MB, CPU 1코어로 제한된 컨테이너 실행",
    "docker run --rm -m 256m --cpus 1 alpine sh",
    "```",
    "",
    "> namespace로 **보이는 것을 격리**하고, cgroup으로 **쓸 수 있는 양을 제한**합니다.",
    "",
    "---",
    "",
    "## 베이스 이미지별 차이점",
    "",
    "같은 커널을 쓰지만, rootfs가 다르면 사용 경험이 달라집니다.",
    "",
    "| 항목 | Alpine | Ubuntu | Debian |",
    "|------|--------|--------|--------|",
    "| C 라이브러리 | musl | glibc | glibc |",
    "| 패키지 매니저 | apk | apt | apt |",
    "| 셸 | ash (busybox) | bash | bash |",
    "| 기본 유틸 | busybox (경량) | coreutils (풍부) | coreutils |",
    "| 이미지 크기 | ~7 MB | ~78 MB | ~139 MB |",
    "| 장점 | 초경량, 보안 | 호환성, 풍부한 패키지 | 안정성 |",
    "| 단점 | 일부 바이너리 비호환 | 큰 이미지 | 큰 이미지 |",
    "",
    "### musl vs glibc 주의사항",
    "",
    "Alpine은 musl libc를 쓰기 때문에 glibc 기반으로 컴파일된 바이너리가 동작하지 않을 수 있습니다.",
    "",
    "```bash",
    "# glibc용 바이너리를 Alpine에서 실행하면",
    "docker run --rm alpine ./my-glibc-app",
    "# Error: /lib/x86_64-linux-gnu/libc.so.6: No such file or directory",
    "",
    "# 해결 1: Alpine에서 glibc 호환 패키지 설치",
    "apk add gcompat",
    "",
    "# 해결 2: 처음부터 Alpine(musl) 환경에서 빌드",
    "# 해결 3: glibc 기반 이미지(Ubuntu/Debian) 사용",
    "```",
    "",
    "---",
    "",
    "## Dockerfile에서 FROM의 의미",
    "",
    "`FROM`은 **어떤 rootfs 위에서 시작할 것인가**를 결정합니다.",
    "",
    "```dockerfile",
    "# Alpine rootfs + Node.js",
    "FROM node:20-alpine",
    "",
    "# Ubuntu rootfs + Python",
    "FROM python:3.12-slim",
    "",
    "# 아무 rootfs도 없이 시작 (바이너리만 넣을 때)",
    "FROM scratch",
    "```",
    "",
    "| FROM 이미지 | 실제로 가져오는 것 |",
    "|-------------|-------------------|",
    "| `alpine` | musl + busybox + apk (rootfs) |",
    "| `ubuntu` | glibc + bash + apt + coreutils (rootfs) |",
    "| `node:20-alpine` | Alpine rootfs + Node.js 바이너리 |",
    "| `scratch` | 완전히 빈 rootfs (정적 바이너리용) |",
    "",
    "### scratch 이미지",
    "",
    "Go처럼 정적 바이너리를 만드는 언어는 rootfs조차 필요 없습니다.",
    "",
    "```dockerfile",
    "# 빌드 스테이지",
    "FROM golang:1.22 AS builder",
    "WORKDIR /app",
    "COPY . .",
    "RUN CGO_ENABLED=0 go build -o server .",
    "",
    "# 실행 스테이지 - rootfs 없이 바이너리만",
    "FROM scratch",
    "COPY --from=builder /app/server /server",
    "ENTRYPOINT [\"/server\"]",
    "```",
    "",
    "> `scratch`로 만든 이미지는 수 MB로, 셸도 없고 `ls`, `cat`도 없습니다. 순수 바이너리만 존재합니다.",
    "",
    "---",
    "",
    "## 자주 하는 오해 정리",
    "",
    "| 오해 | 사실 |",
    "|------|------|",
    "| \"Alpine 컨테이너에는 Alpine OS가 들어있다\" | Alpine의 rootfs(파일+도구)만 있고, 커널은 호스트 것 |",
    "| \"컨테이너마다 커널이 따로 있다\" | 모든 컨테이너는 호스트 커널 하나를 공유 |",
    "| \"Docker는 가상머신이다\" | VM이 아니라 격리된 프로세스 (커널 공유) |",
    "| \"컨테이너 안에서 커널 업데이트 가능\" | 불가능, 커널은 호스트에서만 관리 |",
    "| \"Ubuntu 컨테이너는 Ubuntu에서만 실행\" | 아무 Linux 호스트에서나 실행 가능 (커널 호환만 되면) |",
    "| \"Windows 컨테이너를 Linux에서 돌릴 수 있다\" | 불가, Windows 컨테이너는 Windows 커널 필요 |",
    "",
    "---",
    "",
    "## Docker Desktop에서는 어떻게 될까?",
    "",
    "macOS나 Windows에서 Docker를 사용하면 Linux 커널이 없는데 어떻게 Linux 컨테이너를 실행할까요?",
    "",
    "```mermaid",
    "flowchart TD",
    "  subgraph Desktop[\"macOS / Windows\"]",
    "    subgraph DD[\"Docker Desktop\"]",
    "      subgraph VM[\"경량 Linux VM\"]",
    "        K[\"Linux Kernel\"]",
    "        CA[\"컨테이너A (Alpine)\"]",
    "        CB[\"컨테이너B (Ubuntu)\"]",
    "        CA --- K",
    "        CB --- K",
    "      end",
    "    end",
    "  end",
    "```",
    "",
    "> Docker Desktop은 내부적으로 **경량 Linux VM**을 자동 생성하고, 그 안에서 Linux 커널을 실행합니다. 사용자는 이를 의식하지 않아도 됩니다.",
    "",
    "---",
    "",
    "## 전체 정리",
    "",
    "```",
    "OS = 커널 + 사용자 공간(rootfs)",
    "",
    "VM:       각 VM이 독립된 커널 + rootfs를 가짐",
    "컨테이너: 호스트 커널 공유 + 독립된 rootfs만 가짐",
    "```",
    "",
    "| 핵심 개념 | 설명 |",
    "|-----------|------|",
    "| rootfs | 컨테이너가 가진 것, / 아래 파일 트리 전체 |",
    "| 커널 공유 | 모든 컨테이너는 호스트 Linux 커널을 공유 |",
    "| namespace | 프로세스·네트워크·파일시스템 등을 격리 |",
    "| cgroup | CPU·메모리 등 자원 사용량을 제한 |",
    "| FROM | Dockerfile에서 rootfs를 선택하는 명령 |",
    "| scratch | 빈 rootfs, 정적 바이너리 전용 |",
    "",
    "### 요약",
    "컨테이너 안의 \"OS\"는 전체 운영체제가 아니라 **rootfs(파일 시스템 + 유틸리티)**입니다. 커널은 호스트와 공유하며, Linux의 namespace와 cgroup으로 격리와 자원 제한을 구현합니다. Alpine/Ubuntu 같은 베이스 이미지는 rootfs의 종류(C 라이브러리, 패키지 매니저, 기본 도구)를 결정할 뿐이며, `FROM scratch`처럼 rootfs 없이 바이너리만 넣는 것도 가능합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
