<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "container-image-relationship",
  title: "컨테이너와 이미지의 관계",
  date: "2026-02-11",
  summary: "이미지는 읽기 전용 템플릿, 컨테이너는 그 이미지로부터 생성된 실행 인스턴스입니다.",
  category: "Technology/Docker",
  tags: ["docker","container","image","relationship","layers"],
  content: [
    "## 한 줄 요약",
    "이미지는 **읽기 전용 템플릿(설계도)**, 컨테이너는 그 이미지로부터 만들어진 **실행 인스턴스(실체)**입니다. 하나의 이미지로 여러 컨테이너를 만들 수 있습니다.",
    "",
    "---",
    "",
    "## 비유로 이해하기",
    "",
    "| 비유 | 이미지 | 컨테이너 |",
    "|------|--------|---------|",
    "| 프로그래밍 | 클래스 (설계도) | 인스턴스 (객체) |",
    "| 요리 | 레시피 | 실제 요리된 음식 |",
    "| 공장 | 금형 (틀) | 금형으로 찍어낸 제품 |",
    "| 음악 | 악보 | 실제 연주 |",
    "",
    "```mermaid",
    "flowchart LR",
    "  A[\"이미지 (node:20-alpine)\"] -->|docker run| B[\"컨테이너 A (실행 중)\"]",
    "  A -->|docker run| C[\"컨테이너 B (실행 중)\"]",
    "  A -->|docker run| D[\"컨테이너 C (중지됨)\"]",
    "```",
    "",
    "---",
    "",
    "## 이미지와 컨테이너의 차이",
    "",
    "| 구분 | 이미지 | 컨테이너 |",
    "|------|--------|---------|",
    "| 상태 | 정적 (읽기 전용) | 동적 (실행 중 / 중지) |",
    "| 변경 | 불변 (immutable) | 쓰기 가능 (writable layer) |",
    "| 저장 | 디스크에 레이어로 저장 | 메모리 + 쓰기 레이어 |",
    "| 생성 | `docker build` 또는 `docker pull` | `docker run` 또는 `docker create` |",
    "| 삭제 | `docker rmi` | `docker rm` |",
    "| 공유 | Docker Hub에 push 가능 | 공유 불가 (이미지로 변환 후 가능) |",
    "",
    "---",
    "",
    "## 레이어 구조 (핵심!)",
    "",
    "이미지와 컨테이너의 관계를 정확히 이해하려면 **레이어 구조**를 알아야 합니다.",
    "",
    "### 이미지 레이어 (읽기 전용)",
    "",
    "```mermaid",
    "flowchart TD",
    "  subgraph Image[\"이미지 레이어 (모두 읽기 전용 Read-Only)\"]",
    "    L4[\"Layer 4: COPY . .  ← 앱 코드\"]",
    "    L3[\"Layer 3: RUN npm install  ← node_modules\"]",
    "    L2[\"Layer 2: FROM node:20  ← Node.js 런타임\"]",
    "    L1[\"Layer 1: alpine  ← 기본 OS (rootfs)\"]",
    "    L4 --- L3 --- L2 --- L1",
    "  end",
    "```",
    "",
    "### 컨테이너 = 이미지 레이어 + 쓰기 레이어",
    "",
    "```mermaid",
    "flowchart TD",
    "  W[\"Writable Layer (R/W)<br>로그, 임시 파일, 변경사항<br>(컨테이너 삭제 시 사라짐)\"]",
    "  subgraph ImageLayers[\"이미지 레이어 (읽기 전용, 공유됨)\"]",
    "    L4[\"Layer 4: COPY . .\"] --- L3[\"Layer 3: RUN npm install\"] --- L2[\"Layer 2: FROM node:20\"] --- L1[\"Layer 1: alpine\"]",
    "  end",
    "  W --- L4",
    "```",
    "",
    "> 컨테이너 안에서 파일을 수정하면 **쓰기 레이어(Writable Layer)**에 기록됩니다. 원본 이미지는 변경되지 않습니다. 이 방식을 **Copy-on-Write (CoW)**라고 합니다.",
    "",
    "### 여러 컨테이너가 이미지 레이어 공유",
    "",
    "```mermaid",
    "flowchart TD",
    "  subgraph CA[\"컨테이너 A\"]",
    "    WA[\"Writable Layer A\"]",
    "  end",
    "  subgraph CB[\"컨테이너 B\"]",
    "    WB[\"Writable Layer B\"]",
    "  end",
    "  subgraph CC[\"컨테이너 C\"]",
    "    WC[\"Writable Layer C\"]",
    "  end",
    "  subgraph Shared[\"이미지 레이어 (공유, 읽기 전용)\"]",
    "    L[\"Layer 4 → Layer 3 → Layer 2 → Layer 1\"]",
    "  end",
    "  WA --- L",
    "  WB --- L",
    "  WC --- L",
    "```",
    "",
    "> 같은 이미지로 100개 컨테이너를 만들어도, 이미지 레이어는 **1벌만 디스크에 존재**합니다. 각 컨테이너는 쓰기 레이어만 추가로 갖습니다.",
    "",
    "---",
    "",
    "## 직접 확인해보기",
    "",
    "### 이미지 레이어 확인",
    "```bash",
    "# 이미지의 레이어 히스토리 확인",
    "docker history node:20-alpine",
    "",
    "# 출력 예시:",
    "# IMAGE        CREATED      CREATED BY                         SIZE",
    "# abc123       2 days ago   CMD [\"node\"]                       0B",
    "# def456       2 days ago   ENTRYPOINT [\"docker-entrypoint.…   0B",
    "# ghi789       2 days ago   COPY ...                           4.5MB",
    "# jkl012       3 days ago   RUN apk add ...                    2.1MB",
    "# mno345       5 days ago   /bin/sh -c #(nop) ADD file:...     7.8MB",
    "```",
    "",
    "### 컨테이너 쓰기 레이어 확인",
    "```bash",
    "# 컨테이너 실행",
    "docker run -d --name test nginx",
    "",
    "# 컨테이너 안에서 파일 생성",
    "docker exec test sh -c 'echo hello > /tmp/test.txt'",
    "",
    "# 컨테이너의 변경사항 확인 (diff)",
    "docker diff test",
    "# 출력:",
    "# C /tmp",
    "# A /tmp/test.txt",
    "# C = Changed, A = Added, D = Deleted",
    "",
    "# 컨테이너 삭제하면 쓰기 레이어도 사라짐",
    "docker rm -f test",
    "```",
    "",
    "---",
    "",
    "## 컨테이너 → 이미지 (docker commit)",
    "",
    "컨테이너의 현재 상태를 새 이미지로 저장할 수 있습니다.",
    "",
    "```bash",
    "# 컨테이너 실행 + 패키지 설치",
    "docker run -it --name my-ubuntu ubuntu bash",
    "apt update && apt install -y curl vim",
    "exit",
    "",
    "# 컨테이너를 이미지로 저장",
    "docker commit my-ubuntu my-custom-ubuntu:v1",
    "",
    "# 새 이미지 확인",
    "docker images | grep my-custom-ubuntu",
    "# my-custom-ubuntu  v1  abc123  10 seconds ago  150MB",
    "",
    "# 새 이미지로 컨테이너 실행 → curl, vim이 이미 설치됨",
    "docker run -it my-custom-ubuntu:v1 bash",
    "which curl   # /usr/bin/curl ✅",
    "```",
    "",
    "> 하지만 `docker commit`보다는 **Dockerfile로 이미지를 빌드**하는 것이 권장됩니다. Dockerfile은 재현 가능하고 버전 관리가 가능하기 때문입니다.",
    "",
    "---",
    "",
    "## 데이터 영속성: 볼륨(Volume)",
    "",
    "컨테이너의 쓰기 레이어는 컨테이너 삭제 시 사라집니다. 데이터를 유지하려면 **볼륨**을 사용합니다.",
    "",
    "```bash",
    "# 볼륨 마운트 (-v 호스트경로:컨테이너경로)",
    "docker run -d -v /my/data:/var/lib/mysql mysql",
    "",
    "# 이름 있는 볼륨 사용",
    "docker run -d -v db-data:/var/lib/mysql mysql",
    "",
    "# 볼륨 목록 확인",
    "docker volume ls",
    "```",
    "",
    "```mermaid",
    "flowchart TD",
    "  subgraph NoVol[\"볼륨 없이\"]",
    "    NW[\"Writable Layer<br>삭제 시 소멸\"] --- NI[\"이미지 레이어\"]",
    "  end",
    "  subgraph WithVol[\"볼륨 사용\"]",
    "    VW[\"Writable Layer\"] --- VI[\"이미지 레이어\"]",
    "    VI -->|마운트| VH[\"호스트 디스크<br>영구 보존\"]",
    "  end",
    "```",
    "",
    "---",
    "",
    "## 전체 정리",
    "",
    "| 항목 | 이미지 | 컨테이너 |",
    "|------|--------|---------|",
    "| 본질 | 읽기 전용 레이어의 집합 | 이미지 + 쓰기 레이어 |",
    "| 생성 | `docker build` / `docker pull` | `docker run` |",
    "| 관계 | 1개 이미지 → N개 컨테이너 | 각 컨테이너는 1개 이미지 기반 |",
    "| 변경 | 불변 (새 이미지로만 변경) | 쓰기 레이어에 변경 저장 |",
    "| 삭제 | `docker rmi` | `docker rm` |",
    "| 공유 | Docker Hub로 push/pull | 공유 불가 (commit 후 이미지로) |",
    "| 데이터 | 빌드 시 고정 | 쓰기 레이어 (삭제 시 소멸), 볼륨 사용 권장 |",
    "",
    "### 요약",
    "이미지는 **읽기 전용 레이어의 집합**이고, 컨테이너는 그 위에 **쓰기 레이어를 추가한 실행 인스턴스**입니다. 같은 이미지에서 여러 컨테이너를 만들 수 있고(1:N), 이미지 레이어는 컨테이너 간 공유되어 디스크를 절약합니다. 컨테이너 데이터를 영구 보존하려면 볼륨을 사용합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
