<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-lambda-linq-async",
  title: "C# 람다, LINQ, 비동기 프로그래밍",
  date: "2026-02-25",
  summary: "람다 식, Func/Action, LINQ 쿼리(where/orderby/group/join), Thread, Task, async/await 등 C#의 고급 기능을 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","lambda","linq","async","await","task","thread","func","action"],
  content: [
    "## 한 줄 요약",
    "C#은 **람다 식**으로 간결한 함수를 정의하고, **LINQ**로 데이터를 SQL처럼 조회하며, **async/await**로 비동기 프로그래밍을 직관적으로 처리합니다.",
    "",
    "---",
    "",
    "## 람다 식 (Lambda Expression)",
    "",
    "### 식 람다 (Expression Lambda)",
    "```csharp",
    "delegate int Calculate(int a, int b);",
    "",
    "Calculate calc = (a, b) => a + b;",
    "Console.WriteLine(calc(3, 4)); // 7",
    "```",
    "",
    "### 문 람다 (Statement Lambda)",
    "```csharp",
    "delegate string Concatenate(string[] args);",
    "",
    "Concatenate concat = (arr) =>",
    "{",
    "    string result = \"\";",
    "    foreach (string s in arr)",
    "        result += s;",
    "    return result;",
    "};",
    "",
    "Console.WriteLine(concat(new[] { \"Hello\", \" \", \"World\" }));",
    "// Hello World",
    "```",
    "",
    "---",
    "",
    "## Func<T> / Action<T>",
    "",
    "별도의 delegate 선언 없이 사용하는 **내장 델리게이트 타입**입니다.",
    "",
    "### Func<T> (반환값 있음)",
    "```csharp",
    "// 매개변수 없이 int 반환",
    "Func<int> func1 = () => 10;",
    "Console.WriteLine(func1()); // 10",
    "",
    "// int → int",
    "Func<int, int> func2 = (x) => x * 2;",
    "Console.WriteLine(func2(4)); // 8",
    "",
    "// double, double → double",
    "Func<double, double, double> func3 = (x, y) => x / y;",
    "Console.WriteLine(func3(22, 7)); // 3.142857...",
    "```",
    "",
    "### Action<T> (반환값 없음)",
    "```csharp",
    "// 매개변수 없음",
    "Action act1 = () => Console.WriteLine(\"Action()\");",
    "act1();",
    "",
    "// int 매개변수",
    "int result = 0;",
    "Action<int> act2 = (x) => result = x * x;",
    "act2(3);",
    "Console.WriteLine(result); // 9",
    "",
    "// double, double 매개변수",
    "Action<double, double> act3 = (x, y) =>",
    "{",
    "    double pi = x / y;",
    "    Console.WriteLine($\"PI ≈ {pi}\");",
    "};",
    "act3(22.0, 7.0); // PI ≈ 3.142857...",
    "```",
    "",
    "---",
    "",
    "## LINQ (Language Integrated Query)",
    "",
    "데이터를 **SQL과 유사한 문법**으로 조회합니다.",
    "",
    "### 기본 쿼리 (from/where/orderby/select)",
    "",
    "```csharp",
    "class Profile",
    "{",
    "    public string Name { get; set; }",
    "    public int Height { get; set; }",
    "}",
    "",
    "Profile[] arr = {",
    "    new Profile { Name=\"정우성\", Height=186 },",
    "    new Profile { Name=\"김태희\", Height=158 },",
    "    new Profile { Name=\"고현정\", Height=172 },",
    "    new Profile { Name=\"이문세\", Height=178 },",
    "    new Profile { Name=\"하하\",   Height=171 }",
    "};",
    "",
    "var profiles = from p in arr",
    "               where p.Height < 175",
    "               orderby p.Height",
    "               select new",
    "               {",
    "                   Name = p.Name,",
    "                   InchHeight = p.Height * 0.393",
    "               };",
    "",
    "foreach (var p in profiles)",
    "    Console.WriteLine($\"{p.Name}, {p.InchHeight:F1}inch\");",
    "// 김태희, 62.1inch",
    "// 하하, 67.2inch",
    "// 고현정, 67.6inch",
    "```",
    "",
    "### group by",
    "",
    "```csharp",
    "var grouped = from p in arr",
    "              orderby p.Height",
    "              group p by p.Height < 175 into g",
    "              select new { GroupKey = g.Key, Profiles = g };",
    "",
    "foreach (var group in grouped)",
    "{",
    "    Console.WriteLine($\"- 175cm 미만? : {group.GroupKey}\");",
    "    foreach (var p in group.Profiles)",
    "        Console.WriteLine($\"    {p.Name}, {p.Height}\");",
    "}",
    "```",
    "",
    "### join (조인)",
    "",
    "```csharp",
    "class Product",
    "{",
    "    public string Title { get; set; }",
    "    public string Star { get; set; }",
    "}",
    "",
    "Product[] products = {",
    "    new Product { Title=\"비트\", Star=\"정우성\" },",
    "    new Product { Title=\"CF 다수\", Star=\"김태희\" },",
    "    new Product { Title=\"아이리스\", Star=\"김태희\" },",
    "    new Product { Title=\"모래시계\", Star=\"고현정\" },",
    "    new Product { Title=\"Solo 예찬\", Star=\"이문세\" }",
    "};",
    "",
    "// 내부 조인",
    "var innerJoin = from p in arr",
    "                join prod in products on p.Name equals prod.Star",
    "                select new { p.Name, prod.Title, p.Height };",
    "",
    "foreach (var item in innerJoin)",
    "    Console.WriteLine($\"이름:{item.Name}, 작품:{item.Title}, 키:{item.Height}cm\");",
    "",
    "// 외부 조인 (into ... DefaultIfEmpty)",
    "var outerJoin = from p in arr",
    "                join prod in products on p.Name equals prod.Star into ps",
    "                from sub in ps.DefaultIfEmpty(new Product { Title=\"없음\" })",
    "                select new { p.Name, sub.Title, p.Height };",
    "",
    "foreach (var item in outerJoin)",
    "    Console.WriteLine($\"이름:{item.Name}, 작품:{item.Title}\");",
    "```",
    "",
    "### LINQ 메서드 구문",
    "```csharp",
    "// 쿼리 구문과 동일한 결과",
    "var result = arr",
    "    .Where(p => p.Height < 175)",
    "    .OrderBy(p => p.Height)",
    "    .Select(p => new { p.Name, Inch = p.Height * 0.393 });",
    "",
    "// 집계 함수",
    "int min = arr.Min(p => p.Height);    // 158",
    "int max = arr.Max(p => p.Height);    // 186",
    "double avg = arr.Average(p => p.Height); // 173.0",
    "int count = arr.Count(p => p.Height > 170); // 3",
    "```",
    "",
    "---",
    "",
    "## 스레드 (Thread)",
    "",
    "```csharp",
    "using System.Threading;",
    "",
    "static void DoSomething()",
    "{",
    "    for (int i = 0; i < 5; i++)",
    "    {",
    "        Console.WriteLine($\"DoSomething : {i}\");",
    "        Thread.Sleep(10);",
    "    }",
    "}",
    "",
    "Thread t1 = new Thread(new ThreadStart(DoSomething));",
    "t1.Start();",
    "",
    "for (int i = 0; i < 5; i++)",
    "{",
    "    Console.WriteLine($\"Main : {i}\");",
    "    Thread.Sleep(10);",
    "}",
    "",
    "t1.Join(); // 스레드 종료 대기",
    "Console.WriteLine(\"Finished\");",
    "```",
    "",
    "> `DoSomething`과 `Main`의 출력이 **교차**되며 나타납니다.",
    "",
    "---",
    "",
    "## Task (작업)",
    "",
    "Thread보다 가벼운 **비동기 작업 단위**입니다.",
    "",
    "```csharp",
    "using System.Threading.Tasks;",
    "",
    "// Task.Run으로 실행",
    "Task t1 = Task.Run(() =>",
    "{",
    "    Console.WriteLine(\"Task 실행 중\");",
    "    Thread.Sleep(1000);",
    "});",
    "",
    "t1.Wait(); // 완료 대기",
    "",
    "// 반환값이 있는 Task",
    "Task<List<int>> myTask = Task.Run(() =>",
    "{",
    "    Thread.Sleep(500);",
    "    return new List<int> { 3, 4, 5 };",
    "});",
    "",
    "myTask.Wait();",
    "List<int> list = myTask.Result; // 결과 가져오기",
    "```",
    "",
    "---",
    "",
    "## async / await",
    "",
    "비동기 코드를 **동기 코드처럼** 읽을 수 있게 합니다.",
    "",
    "```csharp",
    "async static Task MyMethodAsync(int count)",
    "{",
    "    Console.WriteLine(\"C\");",
    "    Console.WriteLine(\"D\");",
    "",
    "    await Task.Run(async () =>",
    "    {",
    "        for (int i = 1; i <= count; i++)",
    "        {",
    "            Console.WriteLine($\"{i}/{count} ...\");",
    "            await Task.Delay(100);",
    "        }",
    "    });",
    "",
    "    Console.WriteLine(\"G\");",
    "    Console.WriteLine(\"H\");",
    "}",
    "",
    "static void Caller()",
    "{",
    "    Console.WriteLine(\"A\");",
    "    Console.WriteLine(\"B\");",
    "",
    "    MyMethodAsync(3); // 비동기 호출 (await 없이)",
    "",
    "    Console.WriteLine(\"E\");",
    "    Console.WriteLine(\"F\");",
    "}",
    "",
    "// 실행 결과 (순서가 섞일 수 있음):",
    "// A → B → C → D → E → F → 1/3 → 2/3 → 3/3 → G → H",
    "```",
    "",
    "### async/await 핵심 규칙",
    "",
    "| 규칙 | 설명 |",
    "|------|------|",
    "| `async` | 메서드에 붙여 비동기 메서드로 선언 |",
    "| `await` | `Task`를 기다리며, 제어를 호출자에게 반환 |",
    "| 반환 타입 | `Task` (반환값 없음), `Task<T>` (반환값 있음), `void` (이벤트 핸들러) |",
    "| 명명 규칙 | 메서드 이름 끝에 `Async` 접미사 권장 |",
    "",
    "### 실용 예제 - 비동기 HTTP 요청",
    "```csharp",
    "using System.Net.Http;",
    "",
    "async static Task<string> FetchDataAsync(string url)",
    "{",
    "    using HttpClient client = new HttpClient();",
    "    string result = await client.GetStringAsync(url);",
    "    return result;",
    "}",
    "",
    "string html = await FetchDataAsync(\"https://example.com\");",
    "Console.WriteLine(html.Length);",
    "```",
    "",
    "---",
    "",
    "### Thread vs Task vs async/await 비교",
    "",
    "| 구분 | Thread | Task | async/await |",
    "|------|--------|------|-------------|",
    "| 수준 | OS 스레드 | 스레드풀 기반 | Task 위의 문법 설탕 |",
    "| 오버헤드 | 높음 | 낮음 | 낮음 |",
    "| 반환값 | 없음 | `Task<T>` | `Task<T>` |",
    "| 예외 처리 | 복잡 | `Wait()`에서 | `try/catch`로 자연스럽게 |",
    "| 권장 | 저수준 제어 | 병렬 작업 | I/O 바운드 비동기 |",
    "",
    "---",
    "",
    "### 요약",
    "람다 식과 `Func<T>`/`Action<T>`로 간결한 함수형 프로그래밍을 하고, LINQ로 데이터를 선언적으로 조회합니다. `Thread`는 저수준 병렬 처리, `Task`는 가벼운 비동기 작업, `async`/`await`는 비동기 코드의 가독성을 높여줍니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
