<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-exception-delegate-event",
  title: "C# 예외 처리와 델리게이트",
  date: "2026-02-25",
  summary: "try/catch/finally, 사용자 정의 예외, 예외 필터링, 델리게이트, 델리게이트 체인, 익명 메서드, 이벤트를 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","exception","delegate","event","try-catch","anonymous-method","callback"],
  content: [
    "## 한 줄 요약",
    "C#은 **구조적 예외 처리**(try/catch/finally/when)와 **델리게이트·이벤트** 기반의 콜백·옵저버 패턴을 언어 수준에서 지원합니다.",
    "",
    "---",
    "",
    "## try / catch / finally",
    "",
    "```csharp",
    "int[] arr = { 1, 2, 3 };",
    "",
    "try",
    "{",
    "    for (int i = 0; i < 5; i++)",
    "    {",
    "        Console.WriteLine(arr[i]);",
    "    }",
    "}",
    "catch (IndexOutOfRangeException e)",
    "{",
    "    Console.WriteLine($\"예외가 발생했습니다 : {e.Message}\");",
    "}",
    "finally",
    "{",
    "    Console.WriteLine(\"항상 실행됩니다\");",
    "}",
    "```",
    "",
    "### 여러 catch 블록",
    "```csharp",
    "try",
    "{",
    "    // 코드",
    "}",
    "catch (FormatException e)",
    "{",
    "    Console.WriteLine(\"형식 오류\");",
    "}",
    "catch (OverflowException e)",
    "{",
    "    Console.WriteLine(\"범위 초과\");",
    "}",
    "catch (Exception e) // 모든 예외의 기본 클래스",
    "{",
    "    Console.WriteLine($\"기타 오류: {e.Message}\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## throw (예외 던지기)",
    "",
    "```csharp",
    "static void CheckAge(int age)",
    "{",
    "    if (age < 0)",
    "        throw new ArgumentException(\"나이는 0 이상이어야 합니다.\");",
    "    Console.WriteLine($\"나이: {age}\");",
    "}",
    "",
    "try",
    "{",
    "    CheckAge(-1);",
    "}",
    "catch (ArgumentException e)",
    "{",
    "    Console.WriteLine(e.Message);",
    "}",
    "```",
    "",
    "---",
    "",
    "## 사용자 정의 예외",
    "",
    "`Exception`을 상속하여 도메인에 맞는 예외를 만듭니다.",
    "",
    "```csharp",
    "class InvalidArgumentException : Exception",
    "{",
    "    public InvalidArgumentException() { }",
    "    public InvalidArgumentException(string message) : base(message) { }",
    "",
    "    public object Argument { get; set; }",
    "    public string Range { get; set; }",
    "}",
    "",
    "static uint MergeARGB(uint alpha, uint red, uint green, uint blue)",
    "{",
    "    uint[] args = new uint[] { alpha, red, green, blue };",
    "",
    "    foreach (uint arg in args)",
    "    {",
    "        if (arg > 255)",
    "            throw new InvalidArgumentException()",
    "            {",
    "                Argument = arg,",
    "                Range = \"0~255\"",
    "            };",
    "    }",
    "",
    "    return (alpha << 24 & 0xFF000000) |",
    "           (red   << 16 & 0x00FF0000) |",
    "           (green << 8  & 0x0000FF00) |",
    "           (blue        & 0x000000FF);",
    "}",
    "",
    "try",
    "{",
    "    Console.WriteLine(\"0x{0:X}\", MergeARGB(255, 111, 111, 111));",
    "    Console.WriteLine(\"0x{0:X}\", MergeARGB(0, 255, 255, 300)); // 예외!",
    "}",
    "catch (InvalidArgumentException e)",
    "{",
    "    Console.WriteLine(e.Message);",
    "    Console.WriteLine($\"Argument:{e.Argument}, Range:{e.Range}\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## 예외 필터링 (when)",
    "",
    "C# 6.0+에서 `catch` 절에 **조건**을 추가할 수 있습니다.",
    "",
    "```csharp",
    "class FilterableException : Exception",
    "{",
    "    public int ErrorNo { get; set; }",
    "}",
    "",
    "try",
    "{",
    "    int num = Int32.Parse(Console.ReadLine());",
    "    if (num < 0 || num > 10)",
    "        throw new FilterableException() { ErrorNo = num };",
    "}",
    "catch (FilterableException e) when (e.ErrorNo < 0)",
    "{",
    "    Console.WriteLine(\"Negative input is not allowed.\");",
    "}",
    "catch (FilterableException e) when (e.ErrorNo > 10)",
    "{",
    "    Console.WriteLine(\"Too big number is not allowed.\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## 델리게이트 (Delegate)",
    "",
    "**메서드를 변수처럼** 다루는 타입입니다. 콜백 패턴의 기반입니다.",
    "",
    "```csharp",
    "delegate int MyDelegate(int a, int b);",
    "",
    "class Calculator",
    "{",
    "    public int Plus(int a, int b) => a + b;",
    "    public static int Minus(int a, int b) => a - b;",
    "}",
    "",
    "Calculator calc = new Calculator();",
    "",
    "MyDelegate callback = new MyDelegate(calc.Plus);",
    "Console.WriteLine(callback(3, 4)); // 7",
    "",
    "callback = new MyDelegate(Calculator.Minus);",
    "Console.WriteLine(callback(7, 5)); // 2",
    "```",
    "",
    "---",
    "",
    "## 델리게이트 체인",
    "",
    "하나의 델리게이트에 **여러 메서드를 연결**할 수 있습니다.",
    "",
    "```csharp",
    "delegate void Notify(string message);",
    "",
    "class Notifier",
    "{",
    "    public Notify EventOccured;",
    "}",
    "",
    "class EventListener",
    "{",
    "    private string name;",
    "    public EventListener(string name) { this.name = name; }",
    "",
    "    public void SomethingHappened(string message)",
    "    {",
    "        Console.WriteLine($\"{name}.SomethingHappened : {message}\");",
    "    }",
    "}",
    "",
    "Notifier notifier = new Notifier();",
    "EventListener l1 = new EventListener(\"Listener1\");",
    "EventListener l2 = new EventListener(\"Listener2\");",
    "EventListener l3 = new EventListener(\"Listener3\");",
    "",
    "// += 로 추가",
    "notifier.EventOccured += l1.SomethingHappened;",
    "notifier.EventOccured += l2.SomethingHappened;",
    "notifier.EventOccured += l3.SomethingHappened;",
    "notifier.EventOccured(\"You've got mail.\");",
    "// Listener1, Listener2, Listener3 모두 호출",
    "",
    "// -= 로 제거",
    "notifier.EventOccured -= l2.SomethingHappened;",
    "notifier.EventOccured(\"Download complete.\");",
    "// Listener1, Listener3만 호출",
    "```",
    "",
    "---",
    "",
    "## 익명 메서드",
    "",
    "이름 없이 **인라인으로 델리게이트 구현**을 작성합니다.",
    "",
    "```csharp",
    "delegate int Compare(int a, int b);",
    "",
    "static void BubbleSort(int[] data, Compare comparer)",
    "{",
    "    for (int i = 0; i < data.Length - 1; i++)",
    "        for (int j = 0; j < data.Length - (i + 1); j++)",
    "            if (comparer(data[j], data[j + 1]) > 0)",
    "                (data[j], data[j + 1]) = (data[j + 1], data[j]);",
    "}",
    "",
    "int[] array = { 3, 7, 4, 2, 10 };",
    "",
    "// 오름차순 (익명 메서드 사용)",
    "BubbleSort(array, delegate(int a, int b)",
    "{",
    "    if (a > b) return 1;",
    "    else if (a == b) return 0;",
    "    else return -1;",
    "});",
    "",
    "// 결과: 2 3 4 7 10",
    "```",
    "",
    "---",
    "",
    "## 이벤트 (event)",
    "",
    "델리게이트에 `event` 키워드를 추가하면, **클래스 외부에서 직접 호출할 수 없고** `+=`/`-=`로만 구독/해제가 가능합니다.",
    "",
    "```csharp",
    "class MyTimer",
    "{",
    "    public delegate void Tick(DateTime now);",
    "    public event Tick Ticked; // event 키워드 추가",
    "    private int interval;",
    "",
    "    public MyTimer(int interval)",
    "    {",
    "        this.interval = interval;",
    "    }",
    "",
    "    public void Start()",
    "    {",
    "        DateTime before = DateTime.Now;",
    "        while (true)",
    "        {",
    "            DateTime current = DateTime.Now;",
    "            if (before.AddSeconds(interval) < current)",
    "            {",
    "                Ticked(current); // 클래스 내부에서만 호출 가능",
    "                before = current;",
    "            }",
    "        }",
    "    }",
    "}",
    "",
    "static void TimeElapsed(DateTime current)",
    "{",
    "    Console.WriteLine($\"Time Elapsed : {current.ToLongTimeString()}\");",
    "}",
    "",
    "MyTimer timer = new MyTimer(5);",
    "timer.Ticked += new MyTimer.Tick(TimeElapsed); // 구독",
    "timer.Start();",
    "```",
    "",
    "### delegate vs event",
    "",
    "| 구분 | delegate | event |",
    "|------|----------|-------|",
    "| 외부 호출 | 가능 | 불가 (선언 클래스 내부만) |",
    "| `=` 할당 | 가능 | 불가 (`+=`/`-=`만) |",
    "| 용도 | 콜백 | 옵저버 패턴 (게시/구독) |",
    "",
    "---",
    "",
    "### 요약",
    "C#의 예외 처리는 `try`/`catch`/`finally`와 `when` 필터로 세밀하게 제어하고, 사용자 정의 예외로 도메인 특화 오류를 처리합니다. 델리게이트는 메서드를 일급 객체처럼 다루며, 체인·익명 메서드·이벤트로 유연한 콜백과 이벤트 구동 프로그래밍을 지원합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
