<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-network",
  title: "C# 네트워크 프로그래밍",
  date: "2026-02-25",
  summary: "TCP 소켓, TcpListener/TcpClient, NetworkStream, Echo 서버/클라이언트, 커스텀 프로토콜 기반 파일 업로드 프로젝트를 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","network","tcp","socket","tcplistener","tcpclient","file-upload","protocol"],
  content: [
    "## 한 줄 요약",
    "C#은 `System.Net.Sockets`의 `TcpListener`/`TcpClient`로 TCP 서버·클라이언트를 구현하고, `NetworkStream`으로 데이터를 주고받습니다.",
    "",
    "---",
    "",
    "## TCP 통신 구조",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph Server[\"TcpListener (서버)\"]",
    "        S1[\"AcceptClient\"] --> S2[\"NetworkStream\\nRead/Write\"]",
    "    end",
    "    subgraph Client[\"TcpClient (클라이언트)\"]",
    "        C1[\"Connect\"] --> C2[\"NetworkStream\\nRead/Write\"]",
    "    end",
    "    Client -->|\"접속요청\"| Server",
    "    S2 <-->|\"데이터\"| C2",
    "```",
    "",
    "---",
    "",
    "## Echo 서버",
    "",
    "클라이언트가 보낸 메시지를 그대로 되돌려보내는 서버입니다.",
    "",
    "```csharp",
    "using System;",
    "using System.Net;",
    "using System.Net.Sockets;",
    "using System.Text;",
    "",
    "class EchoServer",
    "{",
    "    static void Main(string[] args)",
    "    {",
    "        string bindIp = args[0];",
    "        const int bindPort = 5425;",
    "        TcpListener server = null;",
    "",
    "        try",
    "        {",
    "            IPEndPoint localAddress =",
    "                new IPEndPoint(IPAddress.Parse(bindIp), bindPort);",
    "",
    "            server = new TcpListener(localAddress);",
    "            server.Start();",
    "            Console.WriteLine(\"메아리 서버 시작...\");",
    "",
    "            while (true)",
    "            {",
    "                // 클라이언트 접속 대기",
    "                TcpClient client = server.AcceptTcpClient();",
    "                Console.WriteLine($\"클라이언트 접속 : {client.Client.RemoteEndPoint}\");",
    "",
    "                NetworkStream stream = client.GetStream();",
    "",
    "                int length;",
    "                byte[] bytes = new byte[256];",
    "",
    "                // 데이터 수신 → 그대로 송신",
    "                while ((length = stream.Read(bytes, 0, bytes.Length)) != 0)",
    "                {",
    "                    string data = Encoding.Default.GetString(bytes, 0, length);",
    "                    Console.WriteLine($\"수신: {data}\");",
    "",
    "                    byte[] msg = Encoding.Default.GetBytes(data);",
    "                    stream.Write(msg, 0, msg.Length);",
    "                    Console.WriteLine($\"송신: {data}\");",
    "                }",
    "",
    "                stream.Close();",
    "                client.Close();",
    "            }",
    "        }",
    "        catch (SocketException e)",
    "        {",
    "            Console.WriteLine(e);",
    "        }",
    "        finally",
    "        {",
    "            server.Stop();",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### 핵심 흐름",
    "1. `TcpListener`로 IP/포트에 바인딩",
    "2. `Start()`로 리스닝 시작",
    "3. `AcceptTcpClient()`로 클라이언트 접속 대기 (블로킹)",
    "4. `GetStream()`으로 `NetworkStream` 획득",
    "5. `Read()`/`Write()`로 데이터 송수신",
    "",
    "---",
    "",
    "## Echo 클라이언트",
    "",
    "```csharp",
    "using System;",
    "using System.Net;",
    "using System.Net.Sockets;",
    "using System.Text;",
    "",
    "class EchoClient",
    "{",
    "    static void Main(string[] args)",
    "    {",
    "        string bindIp = args[0];",
    "        int bindPort = Convert.ToInt32(args[1]);",
    "        string serverIp = args[2];",
    "        const int serverPort = 5425;",
    "        string message = args[3];",
    "",
    "        try",
    "        {",
    "            IPEndPoint clientAddress =",
    "                new IPEndPoint(IPAddress.Parse(bindIp), bindPort);",
    "            IPEndPoint serverAddress =",
    "                new IPEndPoint(IPAddress.Parse(serverIp), serverPort);",
    "",
    "            TcpClient client = new TcpClient(clientAddress);",
    "            client.Connect(serverAddress);",
    "",
    "            // 메시지 송신",
    "            byte[] data = Encoding.Default.GetBytes(message);",
    "            NetworkStream stream = client.GetStream();",
    "            stream.Write(data, 0, data.Length);",
    "            Console.WriteLine($\"송신: {message}\");",
    "",
    "            // 응답 수신",
    "            data = new byte[256];",
    "            int bytes = stream.Read(data, 0, data.Length);",
    "            string responseData = Encoding.Default.GetString(data, 0, bytes);",
    "            Console.WriteLine($\"수신: {responseData}\");",
    "",
    "            stream.Close();",
    "            client.Close();",
    "        }",
    "        catch (SocketException e)",
    "        {",
    "            Console.WriteLine(e);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### 실행 예시",
    "```",
    "# 서버 실행",
    "> EchoServer.exe 127.0.0.1",
    "메아리 서버 시작...",
    "",
    "# 클라이언트 실행 (다른 터미널)",
    "> EchoClient.exe 127.0.0.1 5426 127.0.0.1 \"Hello, Server!\"",
    "송신: Hello, Server!",
    "수신: Hello, Server!",
    "```",
    "",
    "---",
    "",
    "## 커스텀 프로토콜 - 파일 업로드",
    "",
    "실제 네트워크 프로그래밍에서는 **메시지 프로토콜**을 직접 설계합니다.",
    "",
    "### 프로토콜 구조",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph Message",
    "        direction LR",
    "        subgraph Header[\"Header (16바이트)\"]",
    "            direction TB",
    "            H1[\"MSGID (4바이트)\"]",
    "            H2[\"MSGTYPE (4바이트)\"]",
    "            H3[\"BODYLEN (4바이트)\"]",
    "            H4[\"FRAGMENTED (1바이트)\"]",
    "            H5[\"LASTMSG (1바이트)\"]",
    "            H6[\"SEQ (2바이트)\"]",
    "        end",
    "        subgraph Body[\"Body (가변)\"]",
    "            direction TB",
    "            B1[\"BodyRequest\"]",
    "            B2[\"BodyResponse\"]",
    "            B3[\"BodyData\"]",
    "            B4[\"BodyResult\"]",
    "        end",
    "    end",
    "```",
    "",
    "### 메시지 타입",
    "",
    "| 상수 | 값 | 설명 |",
    "|------|-----|------|",
    "| `REQ_FILE_SEND` | 0x01 | 파일 전송 요청 |",
    "| `REP_FILE_SEND` | 0x02 | 파일 전송 응답 (수락/거부) |",
    "| `FILE_SEND_DATA` | 0x03 | 파일 데이터 전송 |",
    "| `FILE_SEND_RES` | 0x04 | 전송 결과 (성공/실패) |",
    "",
    "### Header 클래스",
    "",
    "```csharp",
    "public class Header : ISerializable",
    "{",
    "    public uint MSGID { get; set; }",
    "    public uint MSGTYPE { get; set; }",
    "    public uint BODYLEN { get; set; }",
    "    public byte FRAGMENTED { get; set; }",
    "    public byte LASTMSG { get; set; }",
    "    public ushort SEQ { get; set; }",
    "",
    "    public Header(byte[] bytes)",
    "    {",
    "        MSGID = BitConverter.ToUInt32(bytes, 0);",
    "        MSGTYPE = BitConverter.ToUInt32(bytes, 4);",
    "        BODYLEN = BitConverter.ToUInt32(bytes, 8);",
    "        FRAGMENTED = bytes[12];",
    "        LASTMSG = bytes[13];",
    "        SEQ = BitConverter.ToUInt16(bytes, 14);",
    "    }",
    "",
    "    public byte[] GetBytes()",
    "    {",
    "        byte[] bytes = new byte[16];",
    "        Array.Copy(BitConverter.GetBytes(MSGID), 0, bytes, 0, 4);",
    "        Array.Copy(BitConverter.GetBytes(MSGTYPE), 0, bytes, 4, 4);",
    "        Array.Copy(BitConverter.GetBytes(BODYLEN), 0, bytes, 8, 4);",
    "        bytes[12] = FRAGMENTED;",
    "        bytes[13] = LASTMSG;",
    "        Array.Copy(BitConverter.GetBytes(SEQ), 0, bytes, 14, 2);",
    "        return bytes;",
    "    }",
    "",
    "    public int GetSize() => 16;",
    "}",
    "```",
    "",
    "### Message 클래스",
    "",
    "```csharp",
    "public interface ISerializable",
    "{",
    "    byte[] GetBytes();",
    "    int GetSize();",
    "}",
    "",
    "public class Message : ISerializable",
    "{",
    "    public Header Header { get; set; }",
    "    public ISerializable Body { get; set; }",
    "",
    "    public byte[] GetBytes()",
    "    {",
    "        byte[] bytes = new byte[GetSize()];",
    "        Header.GetBytes().CopyTo(bytes, 0);",
    "        Body.GetBytes().CopyTo(bytes, Header.GetSize());",
    "        return bytes;",
    "    }",
    "",
    "    public int GetSize() => Header.GetSize() + Body.GetSize();",
    "}",
    "```",
    "",
    "### MessageUtil (송수신 유틸)",
    "",
    "```csharp",
    "public class MessageUtil",
    "{",
    "    public static void Send(Stream writer, Message msg)",
    "    {",
    "        writer.Write(msg.GetBytes(), 0, msg.GetSize());",
    "    }",
    "",
    "    public static Message Receive(Stream reader)",
    "    {",
    "        // 1. 헤더(16바이트) 수신",
    "        byte[] hBuffer = new byte[16];",
    "        int totalRecv = 0, sizeToRead = 16;",
    "        while (sizeToRead > 0)",
    "        {",
    "            byte[] buffer = new byte[sizeToRead];",
    "            int recv = reader.Read(buffer, 0, sizeToRead);",
    "            if (recv == 0) return null;",
    "            buffer.CopyTo(hBuffer, totalRecv);",
    "            totalRecv += recv;",
    "            sizeToRead -= recv;",
    "        }",
    "        Header header = new Header(hBuffer);",
    "",
    "        // 2. 바디(BODYLEN 바이트) 수신",
    "        byte[] bBuffer = new byte[header.BODYLEN];",
    "        totalRecv = 0;",
    "        sizeToRead = (int)header.BODYLEN;",
    "        while (sizeToRead > 0)",
    "        {",
    "            byte[] buffer = new byte[sizeToRead];",
    "            int recv = reader.Read(buffer, 0, sizeToRead);",
    "            if (recv == 0) return null;",
    "            buffer.CopyTo(bBuffer, totalRecv);",
    "            totalRecv += recv;",
    "            sizeToRead -= recv;",
    "        }",
    "",
    "        // 3. MSGTYPE에 따라 Body 파싱",
    "        ISerializable body = header.MSGTYPE switch",
    "        {",
    "            CONSTANTS.REQ_FILE_SEND  => new BodyRequest(bBuffer),",
    "            CONSTANTS.REP_FILE_SEND  => new BodyResponse(bBuffer),",
    "            CONSTANTS.FILE_SEND_DATA => new BodyData(bBuffer),",
    "            CONSTANTS.FILE_SEND_RES  => new BodyResult(bBuffer),",
    "            _ => throw new Exception($\"Unknown MSGTYPE: {header.MSGTYPE}\")",
    "        };",
    "",
    "        return new Message() { Header = header, Body = body };",
    "    }",
    "}",
    "```",
    "",
    "### 파일 전송 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트(FileSender)",
    "    participant S as 서버(FileReceiver)",
    "    C->>S: REQ_FILE_SEND (파일명, 크기)",
    "    S->>C: REP_FILE_SEND (수락/거부)",
    "    C->>S: FILE_SEND_DATA",
    "    C->>S: FILE_SEND_DATA",
    "    C->>S: FILE_SEND_DATA (LAST)",
    "    Note over C,S: 4KB 청크 단위로 반복 전송",
    "    S->>C: FILE_SEND_RES (성공/실패)",
    "```",
    "",
    "### FileSender (클라이언트) 핵심 코드",
    "",
    "```csharp",
    "const int CHUNK_SIZE = 4096;",
    "",
    "// 1. 파일 전송 요청",
    "Message reqMsg = new Message();",
    "reqMsg.Body = new BodyRequest()",
    "{",
    "    FILESIZE = new FileInfo(filepath).Length,",
    "    FILENAME = Encoding.Default.GetBytes(filepath)",
    "};",
    "reqMsg.Header = new Header()",
    "{",
    "    MSGID = msgId++,",
    "    MSGTYPE = CONSTANTS.REQ_FILE_SEND,",
    "    BODYLEN = (uint)reqMsg.Body.GetSize(),",
    "    FRAGMENTED = CONSTANTS.NOT_FRAGMENTED,",
    "    LASTMSG = CONSTANTS.LASTMSG,",
    "    SEQ = 0",
    "};",
    "",
    "TcpClient client = new TcpClient(clientAddress);",
    "client.Connect(serverAddress);",
    "NetworkStream stream = client.GetStream();",
    "MessageUtil.Send(stream, reqMsg);",
    "",
    "// 2. 응답 확인",
    "Message rspMsg = MessageUtil.Receive(stream);",
    "if (((BodyResponse)rspMsg.Body).RESPONSE == CONSTANTS.DENIED)",
    "{",
    "    Console.WriteLine(\"서버에서 파일 전송을 거부했습니다.\");",
    "    return;",
    "}",
    "",
    "// 3. 파일 데이터를 4KB 청크 단위로 전송",
    "using (Stream fileStream = new FileStream(filepath, FileMode.Open))",
    "{",
    "    byte[] rbytes = new byte[CHUNK_SIZE];",
    "    int totalRead = 0;",
    "    ushort msgSeq = 0;",
    "",
    "    while (totalRead < fileStream.Length)",
    "    {",
    "        int read = fileStream.Read(rbytes, 0, CHUNK_SIZE);",
    "        totalRead += read;",
    "",
    "        byte[] sendBytes = new byte[read];",
    "        Array.Copy(rbytes, 0, sendBytes, 0, read);",
    "",
    "        Message fileMsg = new Message();",
    "        fileMsg.Body = new BodyData(sendBytes);",
    "        fileMsg.Header = new Header()",
    "        {",
    "            MSGID = msgId,",
    "            MSGTYPE = CONSTANTS.FILE_SEND_DATA,",
    "            BODYLEN = (uint)fileMsg.Body.GetSize(),",
    "            FRAGMENTED = CONSTANTS.FRAGMENTED,",
    "            LASTMSG = (totalRead < fileStream.Length)",
    "                ? CONSTANTS.NOT_LASTMSG : CONSTANTS.LASTMSG,",
    "            SEQ = msgSeq++",
    "        };",
    "",
    "        MessageUtil.Send(stream, fileMsg);",
    "    }",
    "",
    "    // 4. 결과 수신",
    "    Message rstMsg = MessageUtil.Receive(stream);",
    "    BodyResult result = (BodyResult)rstMsg.Body;",
    "    Console.WriteLine($\"파일 전송 성공 : {result.RESULT == CONSTANTS.SUCCESS}\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## 주요 클래스 정리",
    "",
    "| 클래스 | 네임스페이스 | 역할 |",
    "|--------|-------------|------|",
    "| `TcpListener` | `System.Net.Sockets` | TCP 서버 리스너 |",
    "| `TcpClient` | `System.Net.Sockets` | TCP 클라이언트 |",
    "| `NetworkStream` | `System.Net.Sockets` | 소켓 기반 스트림 |",
    "| `IPEndPoint` | `System.Net` | IP + 포트 조합 |",
    "| `IPAddress` | `System.Net` | IP 주소 표현 |",
    "| `Encoding` | `System.Text` | 문자열 ↔ 바이트 변환 |",
    "",
    "---",
    "",
    "### 요약",
    "C# 네트워크 프로그래밍의 기본은 `TcpListener`(서버)와 `TcpClient`(클라이언트)로 TCP 연결을 맺고, `NetworkStream`으로 데이터를 주고받는 것입니다. 실전에서는 Header + Body 구조의 커스텀 프로토콜을 설계하여 메시지 타입 구분, 분할 전송(Fragmentation), 시퀀스 번호 관리 등을 구현합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
