<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-lambda-linq-async",
  title: "C# 람다, LINQ, 비동기 프로그래밍",
  date: "2026-02-25",
  summary: "람다 식, Func/Action, LINQ 쿼리(where/orderby/group/join), Thread, Task, async/await 등 C#의 고급 기능을 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","lambda","linq","async","await","task","thread","func","action"],
  content: [
    "## 한 줄 요약",
    "C#은 **람다 식**으로 간결한 함수를 정의하고, **LINQ**로 데이터를 SQL처럼 조회하며, **async/await**로 비동기 프로그래밍을 직관적으로 처리합니다.",
    "",
    "---",
    "",
    "## 람다 식 (Lambda Expression)",
    "",
    "### 식 람다 (Expression Lambda)",
    "```csharp",
    "delegate int Calculate(int a, int b);",
    "",
    "Calculate calc = (a, b) => a + b;",
    "Console.WriteLine(calc(3, 4)); // 7",
    "```",
    "",
    "### 문 람다 (Statement Lambda)",
    "```csharp",
    "delegate string Concatenate(string[] args);",
    "",
    "Concatenate concat = (arr) =>",
    "{",
    "    string result = \"\";",
    "    foreach (string s in arr)",
    "        result += s;",
    "    return result;",
    "};",
    "",
    "Console.WriteLine(concat(new[] { \"Hello\", \" \", \"World\" }));",
    "// Hello World",
    "```",
    "",
    "---",
    "",
    "## 람다 식 vs 익명 메서드 vs 로컬 함수 비교",
    "",
    "| 구분 | 람다 식 | 익명 메서드 | 로컬 함수 |",
    "|------|--------|-----------|----------|",
    "| 구문 | `(x) => x * 2` | `delegate(int x) { return x * 2; }` | `int Double(int x) => x * 2;` |",
    "| 도입 버전 | C# 3.0 | C# 2.0 | C# 7.0 |",
    "| 재사용 | 변수에 할당 | 변수에 할당 | 선언 메서드 내에서만 |",
    "| 재귀 호출 | 불편 (변수 선언 필요) | 불편 | 자연스러움 |",
    "| 제네릭 지원 | X | X | O |",
    "| yield/await | 불가 (식 람다) | 불가 | 가능 |",
    "| 캡처 최적화 | 힙 할당 발생 가능 | 힙 할당 발생 가능 | `static` 로컬 함수로 회피 가능 |",
    "",
    "```csharp",
    "// 람다 식",
    "Func<int, int> lambdaDouble = x => x * 2;",
    "",
    "// 익명 메서드",
    "Func<int, int> anonDouble = delegate(int x) { return x * 2; };",
    "",
    "// 로컬 함수",
    "int LocalDouble(int x) => x * 2;",
    "",
    "// static 로컬 함수 (C# 8.0+) - 외부 변수 캡처 금지",
    "static int StaticDouble(int x) => x * 2;",
    "```",
    "",
    "---",
    "",
    "## 클로저 (Closure)",
    "",
    "람다 식이 **외부 변수를 캡처**하면 클로저가 됩니다. 캡처된 변수는 람다의 수명 동안 유지됩니다.",
    "",
    "```csharp",
    "int multiplier = 3;",
    "Func<int, int> multiply = x => x * multiplier;",
    "",
    "Console.WriteLine(multiply(5)); // 15",
    "multiplier = 10;",
    "Console.WriteLine(multiply(5)); // 50 (캡처된 변수의 현재 값 사용!)",
    "```",
    "",
    "### 클로저 주의사항: 반복문에서의 캡처",
    "",
    "```csharp",
    "// 주의: 반복 변수 캡처 문제",
    "var actions = new List<Action>();",
    "for (int i = 0; i < 5; i++)",
    "{",
    "    actions.Add(() => Console.Write(i + \" \"));",
    "}",
    "foreach (var act in actions) act();",
    "// 출력: 5 5 5 5 5 (모두 같은 변수 i를 참조!)",
    "",
    "// 해결: 지역 변수로 복사",
    "var actions2 = new List<Action>();",
    "for (int i = 0; i < 5; i++)",
    "{",
    "    int captured = i;",
    "    actions2.Add(() => Console.Write(captured + \" \"));",
    "}",
    "foreach (var act in actions2) act();",
    "// 출력: 0 1 2 3 4",
    "```",
    "",
    "> **참고**: `foreach`에서는 각 반복마다 새 변수가 생성되므로 이 문제가 발생하지 않습니다.",
    "",
    "---",
    "",
    "## `Expression<Func<T>>` (표현식 트리)",
    "",
    "람다를 **코드가 아닌 데이터 구조**로 표현합니다. Entity Framework 등에서 LINQ 쿼리를 SQL로 변환할 때 사용됩니다.",
    "",
    "```csharp",
    "using System.Linq.Expressions;",
    "",
    "// 일반 람다 - 컴파일되어 실행 가능한 코드",
    "Func<int, bool> func = x => x > 5;",
    "",
    "// 표현식 트리 - 분석 가능한 데이터 구조",
    "Expression<Func<int, bool>> expr = x => x > 5;",
    "",
    "// 표현식 트리 분석",
    "Console.WriteLine(expr.Body);       // (x > 5)",
    "Console.WriteLine(expr.Parameters[0]); // x",
    "",
    "// 표현식 트리를 컴파일하여 실행",
    "Func<int, bool> compiled = expr.Compile();",
    "Console.WriteLine(compiled(10)); // True",
    "```",
    "",
    "> Entity Framework에서 `Where(x => x.Age > 20)`을 SQL의 `WHERE Age > 20`으로 변환할 수 있는 것은 표현식 트리 덕분입니다.",
    "",
    "---",
    "",
    "## `Func<T>` / `Action<T>`",
    "",
    "별도의 delegate 선언 없이 사용하는 **내장 델리게이트 타입**입니다.",
    "",
    "### `Func<T>` (반환값 있음)",
    "```csharp",
    "// 매개변수 없이 int 반환",
    "Func<int> func1 = () => 10;",
    "Console.WriteLine(func1()); // 10",
    "",
    "// int → int",
    "Func<int, int> func2 = (x) => x * 2;",
    "Console.WriteLine(func2(4)); // 8",
    "",
    "// double, double → double",
    "Func<double, double, double> func3 = (x, y) => x / y;",
    "Console.WriteLine(func3(22, 7)); // 3.142857...",
    "```",
    "",
    "### `Action<T>` (반환값 없음)",
    "```csharp",
    "// 매개변수 없음",
    "Action act1 = () => Console.WriteLine(\"Action()\");",
    "act1();",
    "",
    "// int 매개변수",
    "int result = 0;",
    "Action<int> act2 = (x) => result = x * x;",
    "act2(3);",
    "Console.WriteLine(result); // 9",
    "",
    "// double, double 매개변수",
    "Action<double, double> act3 = (x, y) =>",
    "{",
    "    double pi = x / y;",
    "    Console.WriteLine($\"PI ≈ {pi}\");",
    "};",
    "act3(22.0, 7.0); // PI ≈ 3.142857...",
    "```",
    "",
    "---",
    "",
    "## LINQ (Language Integrated Query)",
    "",
    "데이터를 **SQL과 유사한 문법**으로 조회합니다.",
    "",
    "### 기본 쿼리 (from/where/orderby/select)",
    "",
    "```csharp",
    "class Profile",
    "{",
    "    public string Name { get; set; }",
    "    public int Height { get; set; }",
    "}",
    "",
    "Profile[] arr = {",
    "    new Profile { Name=\"정우성\", Height=186 },",
    "    new Profile { Name=\"김태희\", Height=158 },",
    "    new Profile { Name=\"고현정\", Height=172 },",
    "    new Profile { Name=\"이문세\", Height=178 },",
    "    new Profile { Name=\"하하\",   Height=171 }",
    "};",
    "",
    "var profiles = from p in arr",
    "               where p.Height < 175",
    "               orderby p.Height",
    "               select new",
    "               {",
    "                   Name = p.Name,",
    "                   InchHeight = p.Height * 0.393",
    "               };",
    "",
    "foreach (var p in profiles)",
    "    Console.WriteLine($\"{p.Name}, {p.InchHeight:F1}inch\");",
    "// 김태희, 62.1inch",
    "// 하하, 67.2inch",
    "// 고현정, 67.6inch",
    "```",
    "",
    "### group by",
    "",
    "```csharp",
    "var grouped = from p in arr",
    "              orderby p.Height",
    "              group p by p.Height < 175 into g",
    "              select new { GroupKey = g.Key, Profiles = g };",
    "",
    "foreach (var group in grouped)",
    "{",
    "    Console.WriteLine($\"- 175cm 미만? : {group.GroupKey}\");",
    "    foreach (var p in group.Profiles)",
    "        Console.WriteLine($\"    {p.Name}, {p.Height}\");",
    "}",
    "```",
    "",
    "### join (조인)",
    "",
    "```csharp",
    "class Product",
    "{",
    "    public string Title { get; set; }",
    "    public string Star { get; set; }",
    "}",
    "",
    "Product[] products = {",
    "    new Product { Title=\"비트\", Star=\"정우성\" },",
    "    new Product { Title=\"CF 다수\", Star=\"김태희\" },",
    "    new Product { Title=\"아이리스\", Star=\"김태희\" },",
    "    new Product { Title=\"모래시계\", Star=\"고현정\" },",
    "    new Product { Title=\"Solo 예찬\", Star=\"이문세\" }",
    "};",
    "",
    "// 내부 조인",
    "var innerJoin = from p in arr",
    "                join prod in products on p.Name equals prod.Star",
    "                select new { p.Name, prod.Title, p.Height };",
    "",
    "foreach (var item in innerJoin)",
    "    Console.WriteLine($\"이름:{item.Name}, 작품:{item.Title}, 키:{item.Height}cm\");",
    "",
    "// 외부 조인 (into ... DefaultIfEmpty)",
    "var outerJoin = from p in arr",
    "                join prod in products on p.Name equals prod.Star into ps",
    "                from sub in ps.DefaultIfEmpty(new Product { Title=\"없음\" })",
    "                select new { p.Name, sub.Title, p.Height };",
    "",
    "foreach (var item in outerJoin)",
    "    Console.WriteLine($\"이름:{item.Name}, 작품:{item.Title}\");",
    "```",
    "",
    "---",
    "",
    "## LINQ 쿼리 구문 vs 메서드 구문 비교",
    "",
    "| 기능 | 쿼리 구문 | 메서드 구문 |",
    "|------|----------|-----------|",
    "| 필터링 | `where p.Height < 175` | `.Where(p => p.Height < 175)` |",
    "| 정렬 | `orderby p.Height` | `.OrderBy(p => p.Height)` |",
    "| 내림차순 | `orderby p.Height descending` | `.OrderByDescending(p => p.Height)` |",
    "| 프로젝션 | `select new { p.Name }` | `.Select(p => new { p.Name })` |",
    "| 그룹화 | `group p by p.Age into g` | `.GroupBy(p => p.Age)` |",
    "| 조인 | `join ... on ... equals ...` | `.Join(...)` |",
    "| let 변수 | `let inch = p.Height * 0.393` | `.Select(p => new { p, inch = ... })` |",
    "",
    "```csharp",
    "// 쿼리 구문과 동일한 결과 (메서드 구문)",
    "var result = arr",
    "    .Where(p => p.Height < 175)",
    "    .OrderBy(p => p.Height)",
    "    .Select(p => new { p.Name, Inch = p.Height * 0.393 });",
    "```",
    "",
    "> **Tip**: 단순 필터/정렬은 메서드 구문이 간결하고, 복잡한 조인/그룹화는 쿼리 구문이 읽기 쉽습니다.",
    "",
    "---",
    "",
    "## LINQ 메서드 구문 실전 예제",
    "",
    "아래 예제들은 모두 다음 데이터 클래스를 사용합니다.",
    "",
    "```csharp",
    "record Product(string Name, string Category, int Price, int Stock);",
    "record Order(int Id, string Customer, string Product, int Qty, DateTime Date);",
    "",
    "List<Product> products = new()",
    "{",
    "    new(\"노트북\",    \"전자기기\", 1500000, 30),",
    "    new(\"마우스\",    \"전자기기\",   35000, 200),",
    "    new(\"키보드\",    \"전자기기\",  120000, 80),",
    "    new(\"모니터\",    \"전자기기\",  350000, 50),",
    "    new(\"셔츠\",      \"의류\",      45000, 150),",
    "    new(\"청바지\",    \"의류\",      65000, 100),",
    "    new(\"운동화\",    \"의류\",      89000, 70),",
    "    new(\"텀블러\",    \"생활용품\",   25000, 300),",
    "    new(\"에어팟\",    \"전자기기\",  250000, 60),",
    "    new(\"백팩\",      \"잡화\",      55000, 90)",
    "};",
    "",
    "List<Order> orders = new()",
    "{",
    "    new(1, \"홍길동\", \"노트북\", 1, new DateTime(2026,1,5)),",
    "    new(2, \"김철수\", \"마우스\", 3, new DateTime(2026,1,8)),",
    "    new(3, \"이영희\", \"셔츠\",   2, new DateTime(2026,1,10)),",
    "    new(4, \"홍길동\", \"키보드\", 1, new DateTime(2026,1,12)),",
    "    new(5, \"박민수\", \"청바지\", 1, new DateTime(2026,1,15)),",
    "    new(6, \"김철수\", \"텀블러\", 2, new DateTime(2026,2,1)),",
    "    new(7, \"이영희\", \"에어팟\", 1, new DateTime(2026,2,3)),",
    "    new(8, \"홍길동\", \"운동화\", 1, new DateTime(2026,2,10)),",
    "};",
    "```",
    "",
    "### Where - 필터링",
    "",
    "```csharp",
    "// 10만원 이상 상품",
    "var expensive = products.Where(p => p.Price >= 100000);",
    "// 노트북, 키보드, 모니터, 에어팟",
    "",
    "// 여러 조건 결합",
    "var cheapElectronics = products",
    "    .Where(p => p.Category == \"전자기기\" && p.Price < 200000);",
    "// 마우스, 키보드",
    "",
    "// 인덱스 활용 오버로드",
    "var evenIndex = products.Where((p, index) => index % 2 == 0);",
    "// 인덱스 0, 2, 4, 6, 8 위치의 상품",
    "```",
    "",
    "### Select - 변환 (프로젝션)",
    "",
    "```csharp",
    "// 이름만 추출",
    "var names = products.Select(p => p.Name);",
    "// [\"노트북\", \"마우스\", \"키보드\", ...]",
    "",
    "// 익명 타입으로 변환",
    "var summary = products.Select(p => new",
    "{",
    "    p.Name,",
    "    PriceWon = $\"{p.Price:N0}원\",",
    "    TotalValue = p.Price * p.Stock",
    "});",
    "// { Name=\"노트북\", PriceWon=\"1,500,000원\", TotalValue=45000000 }, ...",
    "",
    "// 인덱스 활용",
    "var numbered = products.Select((p, i) => $\"{i + 1}. {p.Name}\");",
    "// [\"1. 노트북\", \"2. 마우스\", ...]",
    "```",
    "",
    "### OrderBy / ThenBy - 정렬",
    "",
    "```csharp",
    "// 가격 오름차순",
    "var byPrice = products.OrderBy(p => p.Price);",
    "",
    "// 가격 내림차순",
    "var byPriceDesc = products.OrderByDescending(p => p.Price);",
    "",
    "// 다중 조건 정렬: 카테고리 오름차순 → 가격 내림차순",
    "var multiSort = products",
    "    .OrderBy(p => p.Category)",
    "    .ThenByDescending(p => p.Price);",
    "// 생활용품(텀블러) → 의류(운동화→청바지→셔츠) → 잡화(백팩) → 전자기기(노트북→모니터→...)",
    "```",
    "",
    "### GroupBy - 그룹화",
    "",
    "```csharp",
    "// 카테고리별 그룹화",
    "var groups = products.GroupBy(p => p.Category);",
    "",
    "foreach (var group in groups)",
    "{",
    "    Console.WriteLine($\"[{group.Key}] ({group.Count()}개)\");",
    "    foreach (var p in group)",
    "        Console.WriteLine($\"  {p.Name} - {p.Price:N0}원\");",
    "}",
    "// [전자기기] (5개)",
    "//   노트북 - 1,500,000원",
    "//   마우스 - 35,000원 ...",
    "",
    "// 그룹별 집계",
    "var categoryStats = products",
    "    .GroupBy(p => p.Category)",
    "    .Select(g => new",
    "    {",
    "        Category = g.Key,",
    "        Count = g.Count(),",
    "        AvgPrice = g.Average(p => p.Price),",
    "        MaxPrice = g.Max(p => p.Price),",
    "        TotalStock = g.Sum(p => p.Stock)",
    "    })",
    "    .OrderByDescending(x => x.AvgPrice);",
    "",
    "// { Category=\"전자기기\", Count=5, AvgPrice=451000, MaxPrice=1500000, TotalStock=420 }",
    "// { Category=\"의류\", Count=3, AvgPrice=66333, ... }",
    "// ...",
    "```",
    "",
    "### SelectMany - 평탄화",
    "",
    "```csharp",
    "// 중첩 배열 평탄화",
    "string[][] nested = { new[] {\"a\",\"b\"}, new[] {\"c\",\"d\"}, new[] {\"e\"} };",
    "var flat = nested.SelectMany(x => x); // [\"a\",\"b\",\"c\",\"d\",\"e\"]",
    "",
    "// 문자열을 문자 단위로 평탄화",
    "string[] words = { \"Hello\", \"World\" };",
    "var chars = words.SelectMany(w => w.ToCharArray());",
    "// ['H','e','l','l','o','W','o','r','l','d']",
    "",
    "// 고객별 주문을 하나로 펼치기",
    "var customerProducts = orders",
    "    .GroupBy(o => o.Customer)",
    "    .SelectMany(g => g.Select(o => new { Customer = g.Key, o.Product }));",
    "// { Customer=\"홍길동\", Product=\"노트북\" }, { Customer=\"홍길동\", Product=\"키보드\" }, ...",
    "```",
    "",
    "### Join - 조인",
    "",
    "```csharp",
    "// 주문에 상품 가격 정보 조인",
    "var orderDetails = orders.Join(",
    "    products,",
    "    o => o.Product,    // 외부 키",
    "    p => p.Name,       // 내부 키",
    "    (o, p) => new      // 결과 생성",
    "    {",
    "        o.Id,",
    "        o.Customer,",
    "        o.Product,",
    "        o.Qty,",
    "        p.Price,",
    "        Total = o.Qty * p.Price",
    "    }",
    ");",
    "",
    "foreach (var d in orderDetails)",
    "    Console.WriteLine($\"주문#{d.Id} {d.Customer}: {d.Product} x{d.Qty} = {d.Total:N0}원\");",
    "// 주문#1 홍길동: 노트북 x1 = 1,500,000원",
    "// 주문#2 김철수: 마우스 x3 = 105,000원 ...",
    "",
    "// GroupJoin - 1:N 관계 (왼쪽 기준)",
    "var productOrders = products.GroupJoin(",
    "    orders,",
    "    p => p.Name,",
    "    o => o.Product,",
    "    (p, orderGroup) => new",
    "    {",
    "        p.Name,",
    "        OrderCount = orderGroup.Count(),",
    "        TotalQty = orderGroup.Sum(o => o.Qty)",
    "    }",
    ");",
    "// { Name=\"노트북\", OrderCount=1, TotalQty=1 }",
    "// { Name=\"텀블러\", OrderCount=1, TotalQty=2 }",
    "// { Name=\"백팩\", OrderCount=0, TotalQty=0 }  ← 주문 없어도 포함",
    "```",
    "",
    "### Aggregate - 누적 연산",
    "",
    "```csharp",
    "int[] numbers = { 1, 2, 3, 4, 5 };",
    "",
    "// 합계",
    "int sum = numbers.Aggregate((acc, x) => acc + x); // 15",
    "",
    "// 시드값 + 누적 + 결과 변환",
    "string csv = numbers.Aggregate(",
    "    new StringBuilder(),",
    "    (sb, n) => sb.Length == 0 ? sb.Append(n) : sb.Append(\",\").Append(n),",
    "    sb => sb.ToString()",
    "); // \"1,2,3,4,5\"",
    "",
    "// 가장 긴 상품명",
    "string longest = products",
    "    .Select(p => p.Name)",
    "    .Aggregate((a, b) => a.Length >= b.Length ? a : b);",
    "// \"에어팟\" 또는 같은 길이의 다른 이름",
    "```",
    "",
    "### Take / Skip / Chunk - 페이지네이션",
    "",
    "```csharp",
    "// 상위 3개",
    "var top3 = products.OrderByDescending(p => p.Price).Take(3);",
    "// 노트북, 모니터, 에어팟",
    "",
    "// 2페이지 (페이지 크기 3)",
    "int page = 2, pageSize = 3;",
    "var page2 = products.Skip((page - 1) * pageSize).Take(pageSize);",
    "// 모니터, 셔츠, 청바지",
    "",
    "// TakeLast / SkipLast",
    "var last2 = products.TakeLast(2);  // 에어팟, 백팩",
    "var skipLast2 = products.SkipLast(2); // 노트북 ~ 운동화",
    "",
    "// TakeWhile / SkipWhile (조건이 true인 동안)",
    "int[] sorted = { 1, 2, 3, 5, 8, 13, 21 };",
    "var under10 = sorted.TakeWhile(n => n < 10); // [1, 2, 3, 5, 8]",
    "var from10 = sorted.SkipWhile(n => n < 10);  // [13, 21]",
    "",
    "// Chunk (C# 10+) - 일정 크기로 분할",
    "var chunks = products.Chunk(3);",
    "// [[노트북,마우스,키보드], [모니터,셔츠,청바지], [운동화,텀블러,에어팟], [백팩]]",
    "```",
    "",
    "### Zip - 두 시퀀스 결합",
    "",
    "```csharp",
    "string[] labels = { \"1위\", \"2위\", \"3위\" };",
    "var topProducts = products.OrderByDescending(p => p.Price).Take(3);",
    "",
    "var ranking = labels.Zip(topProducts, (label, p) => $\"{label}: {p.Name} ({p.Price:N0}원)\");",
    "// \"1위: 노트북 (1,500,000원)\", \"2위: 모니터 (350,000원)\", \"3위: 에어팟 (250,000원)\"",
    "",
    "// C# 10+: 3개 시퀀스 Zip",
    "int[] ids = { 1, 2, 3 };",
    "string[] names2 = { \"Alice\", \"Bob\", \"Charlie\" };",
    "int[] scores = { 90, 85, 95 };",
    "var triples = ids.Zip(names2, scores); // (1,\"Alice\",90), (2,\"Bob\",85), ...",
    "```",
    "",
    "### Any / All / Contains - 조건 검사",
    "",
    "```csharp",
    "// 10만원 이상 상품이 존재하는지",
    "bool hasExpensive = products.Any(p => p.Price >= 100000); // True",
    "",
    "// 모든 상품 재고가 0 이상인지",
    "bool allInStock = products.All(p => p.Stock > 0); // True",
    "",
    "// 특정 카테고리 존재 여부",
    "var categories = products.Select(p => p.Category).Distinct();",
    "bool hasFood = categories.Contains(\"식품\"); // False",
    "",
    "// 빈 시퀀스 체크",
    "bool noLuxury = !products.Any(p => p.Price >= 2000000); // True",
    "```",
    "",
    "### 집계 메서드 - Min, Max, Sum, Average, Count",
    "",
    "```csharp",
    "// 기본 집계",
    "int minPrice = products.Min(p => p.Price);        // 25,000",
    "int maxPrice = products.Max(p => p.Price);        // 1,500,000",
    "int totalStock = products.Sum(p => p.Stock);      // 1,130",
    "double avgPrice = products.Average(p => p.Price); // 253,400",
    "int count = products.Count(p => p.Category == \"전자기기\"); // 5",
    "",
    "// MinBy / MaxBy (C# 10+) - 해당 조건의 요소 자체를 반환",
    "Product cheapest = products.MinBy(p => p.Price);  // 텀블러(25,000원)",
    "Product priciest = products.MaxBy(p => p.Price);  // 노트북(1,500,000원)",
    "",
    "// 총 재고 가치",
    "long totalValue = products.Sum(p => (long)p.Price * p.Stock);",
    "Console.WriteLine($\"총 재고 가치: {totalValue:N0}원\"); // 132,900,000원",
    "```",
    "",
    "### Distinct / DistinctBy / Union / Intersect / Except - 집합 연산",
    "",
    "```csharp",
    "// 카테고리 중복 제거",
    "var categories2 = products.Select(p => p.Category).Distinct();",
    "// [\"전자기기\", \"의류\", \"생활용품\", \"잡화\"]",
    "",
    "// DistinctBy (C# 10+) - 특정 키 기준 중복 제거",
    "var onePerCategory = products.DistinctBy(p => p.Category);",
    "// 카테고리별 첫 번째 상품만: 노트북, 셔츠, 텀블러, 백팩",
    "",
    "// 집합 연산",
    "int[] setA = { 1, 2, 3, 4, 5 };",
    "int[] setB = { 3, 4, 5, 6, 7 };",
    "",
    "var union = setA.Union(setB);         // [1,2,3,4,5,6,7]",
    "var intersect = setA.Intersect(setB); // [3,4,5]",
    "var except = setA.Except(setB);       // [1,2]",
    "```",
    "",
    "### ToDictionary / ToLookup - 컬렉션 변환",
    "",
    "```csharp",
    "// ToDictionary: 키-값 딕셔너리 (키 중복 불가)",
    "Dictionary<string, int> priceMap = products",
    "    .ToDictionary(p => p.Name, p => p.Price);",
    "Console.WriteLine(priceMap[\"노트북\"]); // 1500000",
    "",
    "// ToLookup: 키-그룹 (키 중복 가능, GroupBy의 즉시 실행 버전)",
    "var lookup = products.ToLookup(p => p.Category);",
    "foreach (var p in lookup[\"의류\"])",
    "    Console.WriteLine(p.Name); // 셔츠, 청바지, 운동화",
    "",
    "// ToHashSet",
    "HashSet<string> categorySet = products",
    "    .Select(p => p.Category)",
    "    .ToHashSet();",
    "```",
    "",
    "### 실전 복합 예제",
    "",
    "```csharp",
    "// 1. 고객별 총 주문 금액 (조인 + 그룹 + 집계)",
    "var customerTotal = orders",
    "    .Join(products, o => o.Product, p => p.Name,",
    "          (o, p) => new { o.Customer, Total = o.Qty * p.Price })",
    "    .GroupBy(x => x.Customer)",
    "    .Select(g => new",
    "    {",
    "        Customer = g.Key,",
    "        OrderCount = g.Count(),",
    "        TotalSpent = g.Sum(x => x.Total)",
    "    })",
    "    .OrderByDescending(x => x.TotalSpent);",
    "",
    "foreach (var c in customerTotal)",
    "    Console.WriteLine($\"{c.Customer}: {c.OrderCount}건, {c.TotalSpent:N0}원\");",
    "// 홍길동: 3건, 1,709,000원",
    "// 이영희: 2건, 340,000원",
    "// 김철수: 2건, 155,000원",
    "// 박민수: 1건, 65,000원",
    "",
    "// 2. 월별 매출 요약",
    "var monthlySales = orders",
    "    .Join(products, o => o.Product, p => p.Name,",
    "          (o, p) => new { Month = o.Date.ToString(\"yyyy-MM\"), Revenue = o.Qty * p.Price })",
    "    .GroupBy(x => x.Month)",
    "    .Select(g => new",
    "    {",
    "        Month = g.Key,",
    "        Revenue = g.Sum(x => x.Revenue),",
    "        Orders = g.Count()",
    "    })",
    "    .OrderBy(x => x.Month);",
    "// { Month=\"2026-01\", Revenue=1,805,000원, Orders=5 }",
    "// { Month=\"2026-02\", Revenue=389,000원, Orders=3 }",
    "",
    "// 3. 재고 부족 상품 알림 (재고 100 미만 + 가격 높은 순)",
    "var lowStock = products",
    "    .Where(p => p.Stock < 100)",
    "    .OrderBy(p => p.Stock)",
    "    .Select(p => $\"⚠ {p.Name}: 재고 {p.Stock}개 (단가 {p.Price:N0}원)\");",
    "",
    "// 4. 카테고리별 가격 구간 분석",
    "var priceAnalysis = products",
    "    .GroupBy(p => p.Category)",
    "    .Select(g => new",
    "    {",
    "        Category = g.Key,",
    "        Cheapest = g.MinBy(p => p.Price)?.Name,",
    "        Priciest = g.MaxBy(p => p.Price)?.Name,",
    "        PriceRange = $\"{g.Min(p => p.Price):N0} ~ {g.Max(p => p.Price):N0}원\"",
    "    });",
    "// { Category=\"전자기기\", Cheapest=\"마우스\", Priciest=\"노트북\", PriceRange=\"35,000 ~ 1,500,000원\" }",
    "```",
    "",
    "### LINQ 메서드 한눈에 보기",
    "",
    "| 분류 | 메서드 | 설명 |",
    "|------|--------|------|",
    "| **필터링** | `Where` | 조건에 맞는 요소 |",
    "| **프로젝션** | `Select`, `SelectMany` | 변환, 평탄화 |",
    "| **정렬** | `OrderBy`, `ThenBy`, `Reverse` | 오름/내림차순 |",
    "| **그룹화** | `GroupBy`, `ToLookup` | 키별 그룹 |",
    "| **조인** | `Join`, `GroupJoin` | 두 시퀀스 결합 |",
    "| **집합** | `Distinct`, `Union`, `Intersect`, `Except` | 집합 연산 |",
    "| **페이징** | `Take`, `Skip`, `Chunk` | 개수 제한/건너뛰기 |",
    "| **집계** | `Count`, `Sum`, `Min`, `Max`, `Average` | 숫자 집계 |",
    "| **누적** | `Aggregate` | 사용자 정의 누적 |",
    "| **검사** | `Any`, `All`, `Contains` | 조건 충족 여부 |",
    "| **요소** | `First`, `Last`, `Single`, `ElementAt` | 단일 요소 |",
    "| **변환** | `ToList`, `ToArray`, `ToDictionary`, `ToHashSet` | 컬렉션 변환 |",
    "| **결합** | `Zip`, `Concat`, `Append`, `Prepend` | 시퀀스 합치기 |",
    "| **기타** | `DefaultIfEmpty`, `OfType`, `Cast` | 기본값, 타입 필터 |",
    "",
    "---",
    "",
    "## LINQ 심화",
    "",
    "### let 절 (쿼리 내 변수)",
    "```csharp",
    "var result = from p in arr",
    "             let bmi = p.Weight / (p.Height / 100.0 * p.Height / 100.0)",
    "             where bmi > 25",
    "             select new { p.Name, BMI = bmi };",
    "```",
    "",
    "---",
    "",
    "## LINQ 지연 실행 vs 즉시 실행",
    "",
    "LINQ 쿼리는 기본적으로 **지연 실행(Deferred Execution)**됩니다. 결과를 열거할 때(foreach, ToList 등) 비로소 실행됩니다.",
    "",
    "```csharp",
    "List<int> source = new() { 1, 2, 3, 4, 5 };",
    "",
    "// 지연 실행 - 쿼리 정의 시점에는 실행되지 않음",
    "var query = source.Where(x => x > 2);",
    "",
    "source.Add(6); // 원본에 추가",
    "",
    "foreach (int n in query)",
    "    Console.Write($\"{n} \"); // 3 4 5 6 (6도 포함!)",
    "```",
    "",
    "| 구분 | 지연 실행 | 즉시 실행 |",
    "|------|---------|---------|",
    "| 실행 시점 | 열거 시 | 호출 시 즉시 |",
    "| 대표 메서드 | Where, Select, OrderBy, Take, Skip | ToList, ToArray, ToDictionary, Count, First, Sum |",
    "| 원본 변경 반영 | O | X (스냅샷) |",
    "| 여러 번 열거 | 매번 재실행 | 한 번만 실행 |",
    "",
    "```csharp",
    "// 즉시 실행 - ToList()로 결과를 메모리에 고정",
    "var cached = source.Where(x => x > 2).ToList();",
    "source.Add(7);",
    "// cached에는 7이 포함되지 않음",
    "```",
    "",
    "---",
    "",
    "## LINQ to Objects vs LINQ to Entities",
    "",
    "| 구분 | LINQ to Objects | LINQ to Entities |",
    "|------|----------------|-----------------|",
    "| 데이터 소스 | 메모리 내 컬렉션 | 데이터베이스 (EF Core) |",
    "| 실행 위치 | 애플리케이션 | DB 서버 (SQL 변환) |",
    "| 사용 타입 | `IEnumerable<T>` | `IQueryable<T>` |",
    "| 람다 처리 | 직접 실행 | 표현식 트리 → SQL 변환 |",
    "| 성능 | 전체 로드 후 필터링 | DB에서 필터링 후 전송 |",
    "",
    "```csharp",
    "// LINQ to Objects",
    "List<User> users = GetAllUsers();",
    "var result = users.Where(u => u.Age > 20); // 메모리에서 필터",
    "",
    "// LINQ to Entities (EF Core)",
    "var result = dbContext.Users.Where(u => u.Age > 20);",
    "// SQL: SELECT * FROM Users WHERE Age > 20",
    "```",
    "",
    "---",
    "",
    "## 스레드 (Thread)",
    "",
    "```csharp",
    "using System.Threading;",
    "",
    "static void DoSomething()",
    "{",
    "    for (int i = 0; i < 5; i++)",
    "    {",
    "        Console.WriteLine($\"DoSomething : {i}\");",
    "        Thread.Sleep(10);",
    "    }",
    "}",
    "",
    "Thread t1 = new Thread(new ThreadStart(DoSomething));",
    "t1.Start();",
    "",
    "for (int i = 0; i < 5; i++)",
    "{",
    "    Console.WriteLine($\"Main : {i}\");",
    "    Thread.Sleep(10);",
    "}",
    "",
    "t1.Join(); // 스레드 종료 대기",
    "Console.WriteLine(\"Finished\");",
    "```",
    "",
    "> `DoSomething`과 `Main`의 출력이 **교차**되며 나타납니다.",
    "",
    "---",
    "",
    "## 스레드 동기화",
    "",
    "여러 스레드가 공유 자원에 접근할 때 **동기화**가 필요합니다.",
    "",
    "```csharp",
    "// lock - 가장 기본적인 동기화",
    "class Counter",
    "{",
    "    private int count = 0;",
    "    private readonly object lockObj = new();",
    "",
    "    public void Increment()",
    "    {",
    "        lock (lockObj)",
    "        {",
    "            count++;",
    "        }",
    "    }",
    "",
    "    public int Count => count;",
    "}",
    "```",
    "",
    "| 동기화 도구 | 범위 | 특징 |",
    "|-----------|------|------|",
    "| `lock` | 프로세스 내 | 가장 간단, Monitor 기반 |",
    "| `Monitor` | 프로세스 내 | Wait/Pulse로 세밀 제어 |",
    "| `Mutex` | 프로세스 간 | 시스템 수준, 느림 |",
    "| `Semaphore` | 프로세스 간 | 동시 접근 수 제한 |",
    "| `SemaphoreSlim` | 프로세스 내 | 경량 Semaphore, async 지원 |",
    "",
    "---",
    "",
    "## ThreadPool 개념",
    "",
    "스레드를 매번 생성/소멸하는 대신, **미리 만들어 둔 스레드 풀**에서 재사용합니다.",
    "",
    "```csharp",
    "// 스레드 풀에 작업 추가",
    "ThreadPool.QueueUserWorkItem(state =>",
    "{",
    "    Console.WriteLine($\"ThreadPool 작업 실행: {Thread.CurrentThread.ManagedThreadId}\");",
    "});",
    "",
    "// Task.Run()은 내부적으로 ThreadPool을 사용",
    "Task.Run(() => Console.WriteLine(\"Task도 ThreadPool 사용\"));",
    "```",
    "",
    "> `Task`는 `ThreadPool` 위에 구축된 더 높은 수준의 추상화입니다. 직접 `ThreadPool`을 사용하기보다는 `Task`를 사용하세요.",
    "",
    "---",
    "",
    "## Task (작업)",
    "",
    "Thread보다 가벼운 **비동기 작업 단위**입니다.",
    "",
    "```csharp",
    "using System.Threading.Tasks;",
    "",
    "// Task.Run으로 실행",
    "Task t1 = Task.Run(() =>",
    "{",
    "    Console.WriteLine(\"Task 실행 중\");",
    "    Thread.Sleep(1000);",
    "});",
    "",
    "t1.Wait(); // 완료 대기",
    "",
    "// 반환값이 있는 Task",
    "Task<List<int>> myTask = Task.Run(() =>",
    "{",
    "    Thread.Sleep(500);",
    "    return new List<int> { 3, 4, 5 };",
    "});",
    "",
    "myTask.Wait();",
    "List<int> list = myTask.Result; // 결과 가져오기",
    "```",
    "",
    "### Task 심화: WhenAll, WhenAny, ContinueWith",
    "",
    "```csharp",
    "// Task.WhenAll - 모든 Task 완료 대기",
    "Task<int> task1 = Task.Run(() => { Thread.Sleep(1000); return 1; });",
    "Task<int> task2 = Task.Run(() => { Thread.Sleep(2000); return 2; });",
    "Task<int> task3 = Task.Run(() => { Thread.Sleep(500);  return 3; });",
    "",
    "int[] results = await Task.WhenAll(task1, task2, task3);",
    "// results: [1, 2, 3] (총 2초 소요 - 병렬 실행)",
    "",
    "// Task.WhenAny - 가장 먼저 완료되는 Task 대기",
    "Task<int> fastest = await Task.WhenAny(task1, task2, task3);",
    "Console.WriteLine(await fastest); // 3 (500ms로 가장 빠름)",
    "",
    "// ContinueWith - 작업 완료 후 후속 작업",
    "Task.Run(() => 42)",
    "    .ContinueWith(prev => Console.WriteLine($\"결과: {prev.Result}\"));",
    "```",
    "",
    "---",
    "",
    "## async / await",
    "",
    "비동기 코드를 **동기 코드처럼** 읽을 수 있게 합니다.",
    "",
    "```csharp",
    "async static Task MyMethodAsync(int count)",
    "{",
    "    Console.WriteLine(\"C\");",
    "    Console.WriteLine(\"D\");",
    "",
    "    await Task.Run(async () =>",
    "    {",
    "        for (int i = 1; i <= count; i++)",
    "        {",
    "            Console.WriteLine($\"{i}/{count} ...\");",
    "            await Task.Delay(100);",
    "        }",
    "    });",
    "",
    "    Console.WriteLine(\"G\");",
    "    Console.WriteLine(\"H\");",
    "}",
    "",
    "static void Caller()",
    "{",
    "    Console.WriteLine(\"A\");",
    "    Console.WriteLine(\"B\");",
    "",
    "    MyMethodAsync(3); // 비동기 호출 (await 없이)",
    "",
    "    Console.WriteLine(\"E\");",
    "    Console.WriteLine(\"F\");",
    "}",
    "",
    "// 실행 결과 (순서가 섞일 수 있음):",
    "// A → B → C → D → E → F → 1/3 → 2/3 → 3/3 → G → H",
    "```",
    "",
    "### async/await 핵심 규칙",
    "",
    "| 규칙 | 설명 |",
    "|------|------|",
    "| `async` | 메서드에 붙여 비동기 메서드로 선언 |",
    "| `await` | `Task`를 기다리며, 제어를 호출자에게 반환 |",
    "| 반환 타입 | `Task` (반환값 없음), `Task<T>` (반환값 있음), `void` (이벤트 핸들러) |",
    "| 명명 규칙 | 메서드 이름 끝에 `Async` 접미사 권장 |",
    "",
    "---",
    "",
    "## async/await 내부 동작 원리",
    "",
    "컴파일러는 `async` 메서드를 **상태 머신(State Machine)**으로 변환합니다.",
    "",
    "```mermaid",
    "stateDiagram-v2",
    "    [*] --> State0 : 메서드 호출",
    "    State0 --> AwaitPoint1 : await 도달",
    "    AwaitPoint1 --> State1 : Task 완료 시 재개",
    "    State1 --> AwaitPoint2 : 다음 await 도달",
    "    AwaitPoint2 --> State2 : Task 완료 시 재개",
    "    State2 --> [*] : 메서드 완료",
    "",
    "    note right of AwaitPoint1 : 호출자에게 제어 반환\<br>(스레드 차단 없음)",
    "    note right of AwaitPoint2 : SynchronizationContext에\<br>따라 스레드 전환 가능",
    "```",
    "",
    "1. `async` 메서드 호출 → 상태 머신 생성",
    "2. `await`에 도달하면 Task가 완료되었는지 확인",
    "3. 미완료 시 → 현재 상태 저장, 호출자에게 제어 반환",
    "4. Task 완료 시 → 저장된 상태에서 이어서 실행",
    "",
    "---",
    "",
    "## async void를 피해야 하는 이유",
    "",
    "```csharp",
    "// 나쁜 예: async void - 예외를 잡을 수 없음!",
    "async void DangerousMethod()",
    "{",
    "    await Task.Delay(100);",
    "    throw new Exception(\"이 예외는 try/catch로 잡을 수 없습니다!\");",
    "}",
    "",
    "// 좋은 예: async Task",
    "async Task SafeMethod()",
    "{",
    "    await Task.Delay(100);",
    "    throw new Exception(\"이 예외는 잡을 수 있습니다.\");",
    "}",
    "",
    "try",
    "{",
    "    await SafeMethod(); // 정상적으로 예외 포착",
    "}",
    "catch (Exception ex)",
    "{",
    "    Console.WriteLine(ex.Message);",
    "}",
    "```",
    "",
    "| `async Task` | `async void` |",
    "|-------------|-------------|",
    "| 예외를 `await`에서 포착 가능 | 예외가 SynchronizationContext로 전파 → 앱 크래시 |",
    "| 완료 여부 추적 가능 | 완료 여부 알 수 없음 |",
    "| 테스트 가능 | 테스트 어려움 |",
    "| **권장** | 이벤트 핸들러에서만 사용 |",
    "",
    "---",
    "",
    "## ConfigureAwait(false)",
    "",
    "```csharp",
    "// UI 앱에서 await 후 원래 스레드(UI 스레드)로 돌아옴",
    "await SomeAsync(); // SynchronizationContext 사용",
    "",
    "// 라이브러리 코드에서는 원래 스레드로 돌아올 필요 없음",
    "await SomeAsync().ConfigureAwait(false); // 아무 스레드에서 계속",
    "```",
    "",
    "| 상황 | ConfigureAwait |",
    "|------|---------------|",
    "| UI 앱 (WPF, WinForms) | 기본값 (true) — UI 스레드 복귀 필요 |",
    "| 라이브러리 코드 | `ConfigureAwait(false)` — 데드락 방지, 성능 향상 |",
    "| ASP.NET Core | 불필요 (SynchronizationContext 없음) |",
    "",
    "---",
    "",
    "## CancellationToken으로 작업 취소",
    "",
    "```csharp",
    "async Task DownloadAsync(string url, CancellationToken token)",
    "{",
    "    using HttpClient client = new();",
    "",
    "    for (int i = 0; i < 10; i++)",
    "    {",
    "        token.ThrowIfCancellationRequested();",
    "        Console.WriteLine($\"다운로드 중... {(i + 1) * 10}%\");",
    "        await Task.Delay(500, token);",
    "    }",
    "",
    "    Console.WriteLine(\"다운로드 완료!\");",
    "}",
    "",
    "var cts = new CancellationTokenSource();",
    "",
    "// 3초 후 자동 취소",
    "cts.CancelAfter(TimeSpan.FromSeconds(3));",
    "",
    "try",
    "{",
    "    await DownloadAsync(\"https://example.com/file\", cts.Token);",
    "}",
    "catch (OperationCanceledException)",
    "{",
    "    Console.WriteLine(\"작업이 취소되었습니다.\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## 비동기 스트림 (IAsyncEnumerable, C# 8.0+)",
    "",
    "비동기적으로 데이터를 **하나씩** 생산하고 소비합니다.",
    "",
    "```csharp",
    "// 비동기 시퀀스 생산",
    "async IAsyncEnumerable<int> GenerateNumbersAsync()",
    "{",
    "    for (int i = 1; i <= 10; i++)",
    "    {",
    "        await Task.Delay(200); // 비동기 대기",
    "        yield return i;",
    "    }",
    "}",
    "",
    "// 비동기 시퀀스 소비",
    "await foreach (int number in GenerateNumbersAsync())",
    "{",
    "    Console.WriteLine($\"받은 값: {number}\");",
    "}",
    "",
    "// CancellationToken과 함께 사용",
    "async IAsyncEnumerable<string> ReadLinesAsync(",
    "    string path,",
    "    [EnumeratorCancellation] CancellationToken token = default)",
    "{",
    "    using var reader = new StreamReader(path);",
    "    while (!reader.EndOfStream)",
    "    {",
    "        token.ThrowIfCancellationRequested();",
    "        yield return await reader.ReadLineAsync();",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Parallel.ForEach / PLINQ 병렬 처리",
    "",
    "```csharp",
    "// Parallel.ForEach - CPU 바운드 작업 병렬화",
    "var items = Enumerable.Range(1, 100).ToList();",
    "",
    "Parallel.ForEach(items, item =>",
    "{",
    "    Console.WriteLine($\"처리 중: {item}, 스레드: {Thread.CurrentThread.ManagedThreadId}\");",
    "    Thread.Sleep(100); // CPU 작업 시뮬레이션",
    "});",
    "",
    "// PLINQ - LINQ 쿼리 병렬화",
    "var result = items",
    "    .AsParallel()",
    "    .WithDegreeOfParallelism(4)",
    "    .Where(x => x % 2 == 0)",
    "    .Select(x => x * x)",
    "    .ToList();",
    "```",
    "",
    "> **주의**: I/O 바운드 작업에는 `async/await`를, CPU 바운드 작업에는 `Parallel`/PLINQ를 사용하세요.",
    "",
    "---",
    "",
    "## 동기 vs 비동기 실행 흐름 비교",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant Main as Main 스레드",
    "    participant IO as I/O 작업",
    "",
    "    Note over Main, IO: 동기 실행",
    "    Main->>IO: 파일 읽기 요청",
    "    Note over Main: 스레드 차단 (대기)",
    "    IO-->>Main: 결과 반환",
    "    Main->>IO: API 호출",
    "    Note over Main: 스레드 차단 (대기)",
    "    IO-->>Main: 결과 반환",
    "    Note over Main: 총 소요: 작업1 + 작업2",
    "",
    "    Note over Main, IO: 비동기 실행",
    "    Main->>IO: await 파일 읽기",
    "    Note over Main: 스레드 해제 (다른 작업 가능)",
    "    Main->>IO: await API 호출 (동시 시작)",
    "    IO-->>Main: 파일 읽기 완료",
    "    IO-->>Main: API 호출 완료",
    "    Note over Main: 총 소요: max(작업1, 작업2)",
    "```",
    "",
    "---",
    "",
    "## 실전 예제: 비동기 파일 읽기",
    "",
    "```csharp",
    "async Task<string> ReadFileAsync(string path)",
    "{",
    "    using StreamReader reader = new(path);",
    "    return await reader.ReadToEndAsync();",
    "}",
    "",
    "string content = await ReadFileAsync(\"data.txt\");",
    "Console.WriteLine($\"파일 크기: {content.Length}자\");",
    "```",
    "",
    "## 실전 예제: 여러 API 동시 호출",
    "",
    "```csharp",
    "async Task<string> FetchAsync(HttpClient client, string url)",
    "{",
    "    var response = await client.GetAsync(url);",
    "    return await response.Content.ReadAsStringAsync();",
    "}",
    "",
    "using HttpClient client = new();",
    "",
    "// 순차 호출: 총 3초 (1초씩 3개)",
    "string r1 = await FetchAsync(client, \"https://api.example.com/users\");",
    "string r2 = await FetchAsync(client, \"https://api.example.com/posts\");",
    "string r3 = await FetchAsync(client, \"https://api.example.com/comments\");",
    "",
    "// 병렬 호출: 총 1초 (동시 실행)",
    "var tasks = new[]",
    "{",
    "    FetchAsync(client, \"https://api.example.com/users\"),",
    "    FetchAsync(client, \"https://api.example.com/posts\"),",
    "    FetchAsync(client, \"https://api.example.com/comments\")",
    "};",
    "",
    "string[] results = await Task.WhenAll(tasks);",
    "Console.WriteLine($\"사용자: {results[0].Length}자\");",
    "Console.WriteLine($\"게시글: {results[1].Length}자\");",
    "Console.WriteLine($\"댓글: {results[2].Length}자\");",
    "```",
    "",
    "---",
    "",
    "### Thread vs Task vs async/await 비교",
    "",
    "| 구분 | Thread | Task | async/await |",
    "|------|--------|------|-------------|",
    "| 수준 | OS 스레드 | 스레드풀 기반 | Task 위의 문법 설탕 |",
    "| 오버헤드 | 높음 | 낮음 | 낮음 |",
    "| 반환값 | 없음 | `Task<T>` | `Task<T>` |",
    "| 예외 처리 | 복잡 | `Wait()`에서 | `try/catch`로 자연스럽게 |",
    "| 취소 지원 | 수동 구현 | CancellationToken | CancellationToken |",
    "| 권장 | 저수준 제어 | CPU 바운드 병렬 작업 | I/O 바운드 비동기 |",
    "",
    "---",
    "",
    "### 요약",
    "람다 식과 `Func<T>`/`Action<T>`로 간결한 함수형 프로그래밍을 하고, 클로저의 캡처 원리를 이해하세요. LINQ로 데이터를 선언적으로 조회하며, 지연 실행과 즉시 실행의 차이를 파악해야 합니다. `Thread`는 저수준 병렬 처리, `Task`는 가벼운 비동기 작업, `async`/`await`는 비동기 코드의 가독성을 높여줍니다. `CancellationToken`으로 취소를 지원하고, `IAsyncEnumerable`로 비동기 스트림을 처리하세요."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
