<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-network",
  title: "C# 네트워크 프로그래밍",
  date: "2026-02-25",
  summary: "TCP 소켓, TcpListener/TcpClient, NetworkStream, Echo 서버/클라이언트, 커스텀 프로토콜 기반 파일 업로드 프로젝트를 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","network","tcp","socket","tcplistener","tcpclient","file-upload","protocol"],
  content: [
    "## 한 줄 요약",
    "C#은 `System.Net.Sockets`의 `TcpListener`/`TcpClient`로 TCP 서버·클라이언트를 구현하고, `NetworkStream`으로 데이터를 주고받습니다.",
    "",
    "---",
    "",
    "## 네트워크 기초",
    "",
    "```mermaid",
    "flowchart TB",
    "    subgraph OSI[\"OSI 7계층\"]",
    "        direction TB",
    "        L7[\"7. 응용 계층\<br>HTTP, FTP, SMTP\"]",
    "        L6[\"6. 표현 계층\<br>SSL/TLS, 암호화\"]",
    "        L5[\"5. 세션 계층\<br>연결 관리\"]",
    "        L4[\"4. 전송 계층\<br>TCP, UDP\"]",
    "        L3[\"3. 네트워크 계층\<br>IP, ICMP\"]",
    "        L2[\"2. 데이터링크 계층\<br>Ethernet, MAC\"]",
    "        L1[\"1. 물리 계층\<br>케이블, 전기 신호\"]",
    "    end",
    "    subgraph TCPIP[\"TCP/IP 4계층\"]",
    "        direction TB",
    "        T4[\"응용 계층\<br>HTTP, FTP\"]",
    "        T3[\"전송 계층\<br>TCP, UDP\"]",
    "        T2[\"인터넷 계층\<br>IP\"]",
    "        T1[\"네트워크 접근 계층\<br>Ethernet\"]",
    "    end",
    "    L7 -.-> T4",
    "    L4 -.-> T3",
    "    L3 -.-> T2",
    "    L1 -.-> T1",
    "```",
    "",
    "> C# 네트워크 프로그래밍은 주로 **전송 계층(TCP/UDP)** 과 **응용 계층(HTTP)** 을 다룹니다.",
    "",
    "---",
    "",
    "## TCP vs UDP 비교",
    "",
    "| 비교 항목 | TCP | UDP |",
    "|----------|-----|-----|",
    "| 연결 방식 | 연결 지향 (3-way handshake) | 비연결 |",
    "| 신뢰성 | 보장 (재전송, 순서 보장) | 보장 안 됨 |",
    "| 순서 보장 | O | X |",
    "| 속도 | 상대적으로 느림 | 빠름 |",
    "| 오버헤드 | 큼 (헤더 20바이트) | 작음 (헤더 8바이트) |",
    "| 흐름/혼잡 제어 | O | X |",
    "| 사용 사례 | 웹, 이메일, 파일 전송, SSH | 스트리밍, DNS, 게임, VoIP |",
    "| C# 클래스 | `TcpListener`/`TcpClient` | `UdpClient` |",
    "",
    "---",
    "",
    "## TCP 통신 구조",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph Server[\"TcpListener (서버)\"]",
    "        S1[\"AcceptClient\"] --> S2[\"NetworkStream\<br>Read/Write\"]",
    "    end",
    "    subgraph Client[\"TcpClient (클라이언트)\"]",
    "        C1[\"Connect\"] --> C2[\"NetworkStream\<br>Read/Write\"]",
    "    end",
    "    Client -->|\"접속요청\"| Server",
    "    S2 <-->|\"데이터\"| C2",
    "```",
    "",
    "---",
    "",
    "## Echo 서버",
    "",
    "클라이언트가 보낸 메시지를 그대로 되돌려보내는 서버입니다.",
    "",
    "```csharp",
    "using System;",
    "using System.Net;",
    "using System.Net.Sockets;",
    "using System.Text;",
    "",
    "class EchoServer",
    "{",
    "    static void Main(string[] args)",
    "    {",
    "        string bindIp = args[0];",
    "        const int bindPort = 5425;",
    "        TcpListener server = null;",
    "",
    "        try",
    "        {",
    "            IPEndPoint localAddress =",
    "                new IPEndPoint(IPAddress.Parse(bindIp), bindPort);",
    "",
    "            server = new TcpListener(localAddress);",
    "            server.Start();",
    "            Console.WriteLine(\"메아리 서버 시작...\");",
    "",
    "            while (true)",
    "            {",
    "                // 클라이언트 접속 대기",
    "                TcpClient client = server.AcceptTcpClient();",
    "                Console.WriteLine($\"클라이언트 접속 : {client.Client.RemoteEndPoint}\");",
    "",
    "                NetworkStream stream = client.GetStream();",
    "",
    "                int length;",
    "                byte[] bytes = new byte[256];",
    "",
    "                // 데이터 수신 → 그대로 송신",
    "                while ((length = stream.Read(bytes, 0, bytes.Length)) != 0)",
    "                {",
    "                    string data = Encoding.Default.GetString(bytes, 0, length);",
    "                    Console.WriteLine($\"수신: {data}\");",
    "",
    "                    byte[] msg = Encoding.Default.GetBytes(data);",
    "                    stream.Write(msg, 0, msg.Length);",
    "                    Console.WriteLine($\"송신: {data}\");",
    "                }",
    "",
    "                stream.Close();",
    "                client.Close();",
    "            }",
    "        }",
    "        catch (SocketException e)",
    "        {",
    "            Console.WriteLine(e);",
    "        }",
    "        finally",
    "        {",
    "            server.Stop();",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### 핵심 흐름",
    "1. `TcpListener`로 IP/포트에 바인딩",
    "2. `Start()`로 리스닝 시작",
    "3. `AcceptTcpClient()`로 클라이언트 접속 대기 (블로킹)",
    "4. `GetStream()`으로 `NetworkStream` 획득",
    "5. `Read()`/`Write()`로 데이터 송수신",
    "",
    "---",
    "",
    "## Echo 클라이언트",
    "",
    "```csharp",
    "using System;",
    "using System.Net;",
    "using System.Net.Sockets;",
    "using System.Text;",
    "",
    "class EchoClient",
    "{",
    "    static void Main(string[] args)",
    "    {",
    "        string bindIp = args[0];",
    "        int bindPort = Convert.ToInt32(args[1]);",
    "        string serverIp = args[2];",
    "        const int serverPort = 5425;",
    "        string message = args[3];",
    "",
    "        try",
    "        {",
    "            IPEndPoint clientAddress =",
    "                new IPEndPoint(IPAddress.Parse(bindIp), bindPort);",
    "            IPEndPoint serverAddress =",
    "                new IPEndPoint(IPAddress.Parse(serverIp), serverPort);",
    "",
    "            TcpClient client = new TcpClient(clientAddress);",
    "            client.Connect(serverAddress);",
    "",
    "            // 메시지 송신",
    "            byte[] data = Encoding.Default.GetBytes(message);",
    "            NetworkStream stream = client.GetStream();",
    "            stream.Write(data, 0, data.Length);",
    "            Console.WriteLine($\"송신: {message}\");",
    "",
    "            // 응답 수신",
    "            data = new byte[256];",
    "            int bytes = stream.Read(data, 0, data.Length);",
    "            string responseData = Encoding.Default.GetString(data, 0, bytes);",
    "            Console.WriteLine($\"수신: {responseData}\");",
    "",
    "            stream.Close();",
    "            client.Close();",
    "        }",
    "        catch (SocketException e)",
    "        {",
    "            Console.WriteLine(e);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 비동기 TCP 서버 (async/await)",
    "",
    "```csharp",
    "using System;",
    "using System.Collections.Generic;",
    "using System.Net;",
    "using System.Net.Sockets;",
    "using System.Text;",
    "using System.Threading.Tasks;",
    "",
    "class AsyncEchoServer",
    "{",
    "    private static List<TcpClient> _clients = new();",
    "",
    "    static async Task Main(string[] args)",
    "    {",
    "        var listener = new TcpListener(IPAddress.Any, 5425);",
    "        listener.Start();",
    "        Console.WriteLine(\"비동기 서버 시작 (포트: 5425)\");",
    "",
    "        while (true)",
    "        {",
    "            TcpClient client = await listener.AcceptTcpClientAsync();",
    "            Console.WriteLine($\"클라이언트 접속: {client.Client.RemoteEndPoint}\");",
    "            _clients.Add(client);",
    "",
    "            // 각 클라이언트를 별도 Task로 처리 (비블로킹)",
    "            _ = HandleClientAsync(client);",
    "        }",
    "    }",
    "",
    "    static async Task HandleClientAsync(TcpClient client)",
    "    {",
    "        NetworkStream stream = client.GetStream();",
    "        byte[] buffer = new byte[4096];",
    "",
    "        try",
    "        {",
    "            int bytesRead;",
    "            while ((bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length)) > 0)",
    "            {",
    "                string message = Encoding.UTF8.GetString(buffer, 0, bytesRead);",
    "                Console.WriteLine($\"[{client.Client.RemoteEndPoint}] {message}\");",
    "",
    "                // Echo 응답",
    "                byte[] response = Encoding.UTF8.GetBytes($\"Echo: {message}\");",
    "                await stream.WriteAsync(response, 0, response.Length);",
    "            }",
    "        }",
    "        catch (Exception ex)",
    "        {",
    "            Console.WriteLine($\"클라이언트 에러: {ex.Message}\");",
    "        }",
    "        finally",
    "        {",
    "            _clients.Remove(client);",
    "            client.Close();",
    "            Console.WriteLine(\"클라이언트 연결 종료\");",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "> **핵심**: `AcceptTcpClientAsync()`와 `ReadAsync()`를 사용하면 스레드를 블로킹하지 않고 여러 클라이언트를 동시에 처리할 수 있습니다.",
    "",
    "---",
    "",
    "## UDP 소켓 (UdpClient)",
    "",
    "```csharp",
    "// UDP 서버",
    "class UdpEchoServer",
    "{",
    "    static async Task Main()",
    "    {",
    "        using var server = new UdpClient(5426);",
    "        Console.WriteLine(\"UDP 서버 시작 (포트: 5426)\");",
    "",
    "        while (true)",
    "        {",
    "            UdpReceiveResult result = await server.ReceiveAsync();",
    "            string message = Encoding.UTF8.GetString(result.Buffer);",
    "            Console.WriteLine($\"수신 [{result.RemoteEndPoint}]: {message}\");",
    "",
    "            // Echo 응답",
    "            byte[] response = Encoding.UTF8.GetBytes($\"Echo: {message}\");",
    "            await server.SendAsync(response, response.Length, result.RemoteEndPoint);",
    "        }",
    "    }",
    "}",
    "",
    "// UDP 클라이언트",
    "class UdpEchoClient",
    "{",
    "    static async Task Main()",
    "    {",
    "        using var client = new UdpClient();",
    "        var serverEndpoint = new IPEndPoint(IPAddress.Loopback, 5426);",
    "",
    "        string message = \"Hello, UDP!\";",
    "        byte[] data = Encoding.UTF8.GetBytes(message);",
    "        await client.SendAsync(data, data.Length, serverEndpoint);",
    "        Console.WriteLine($\"송신: {message}\");",
    "",
    "        UdpReceiveResult result = await client.ReceiveAsync();",
    "        string response = Encoding.UTF8.GetString(result.Buffer);",
    "        Console.WriteLine($\"수신: {response}\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## HttpClient 사용법 상세",
    "",
    "```csharp",
    "using System.Net.Http;",
    "using System.Net.Http.Headers;",
    "using System.Text;",
    "using System.Text.Json;",
    "",
    "// HttpClient 싱글톤 (또는 IHttpClientFactory 사용)",
    "static readonly HttpClient _httpClient = new HttpClient",
    "{",
    "    BaseAddress = new Uri(\"https://api.example.com\"),",
    "    Timeout = TimeSpan.FromSeconds(30)",
    "};",
    "",
    "// GET 요청",
    "async Task<string> GetAsync(string endpoint)",
    "{",
    "    HttpResponseMessage response = await _httpClient.GetAsync(endpoint);",
    "    response.EnsureSuccessStatusCode();",
    "    return await response.Content.ReadAsStringAsync();",
    "}",
    "",
    "// POST (JSON 전송)",
    "async Task<T> PostJsonAsync<T>(string endpoint, object data)",
    "{",
    "    string json = JsonSerializer.Serialize(data);",
    "    var content = new StringContent(json, Encoding.UTF8, \"application/json\");",
    "",
    "    HttpResponseMessage response = await _httpClient.PostAsync(endpoint, content);",
    "    response.EnsureSuccessStatusCode();",
    "",
    "    string responseJson = await response.Content.ReadAsStringAsync();",
    "    return JsonSerializer.Deserialize<T>(responseJson);",
    "}",
    "",
    "// PUT 요청",
    "async Task PutAsync(string endpoint, object data)",
    "{",
    "    string json = JsonSerializer.Serialize(data);",
    "    var content = new StringContent(json, Encoding.UTF8, \"application/json\");",
    "    HttpResponseMessage response = await _httpClient.PutAsync(endpoint, content);",
    "    response.EnsureSuccessStatusCode();",
    "}",
    "",
    "// DELETE 요청",
    "async Task DeleteAsync(string endpoint)",
    "{",
    "    HttpResponseMessage response = await _httpClient.DeleteAsync(endpoint);",
    "    response.EnsureSuccessStatusCode();",
    "}",
    "",
    "// 커스텀 헤더 설정",
    "async Task GetWithHeadersAsync()",
    "{",
    "    var request = new HttpRequestMessage(HttpMethod.Get, \"/api/data\");",
    "    request.Headers.Add(\"X-Api-Key\", \"my-api-key\");",
    "    request.Headers.Authorization =",
    "        new AuthenticationHeaderValue(\"Bearer\", \"my-token\");",
    "",
    "    HttpResponseMessage response = await _httpClient.SendAsync(request);",
    "    string result = await response.Content.ReadAsStringAsync();",
    "}",
    "```",
    "",
    "### HttpClient Best Practices",
    "",
    "| 규칙 | 이유 |",
    "|------|------|",
    "| HttpClient를 **재사용** | 매번 생성하면 소켓 고갈 (TIME_WAIT) |",
    "| `IHttpClientFactory` 사용 | DNS 갱신, 커넥션 풀 관리 |",
    "| Timeout 설정 | 무한 대기 방지 |",
    "| `EnsureSuccessStatusCode()` 호출 | 4xx/5xx 응답 시 예외 발생 |",
    "| `CancellationToken` 전달 | 요청 취소 지원 |",
    "| `using` 불필요 (싱글톤) | HttpClient는 Dispose 시 커넥션 풀 파괴 |",
    "",
    "```csharp",
    "// ❌ 잘못된 사용: 매번 생성",
    "for (int i = 0; i < 100; i++)",
    "{",
    "    using var client = new HttpClient(); // 소켓 고갈!",
    "    await client.GetAsync(\"https://api.example.com\");",
    "}",
    "",
    "// ✅ 올바른 사용: 싱글톤 재사용",
    "static readonly HttpClient _client = new HttpClient();",
    "",
    "// ✅ 가장 좋은 방법: IHttpClientFactory (ASP.NET Core)",
    "// services.AddHttpClient<MyService>(client =>",
    "// {",
    "//     client.BaseAddress = new Uri(\"https://api.example.com\");",
    "//     client.Timeout = TimeSpan.FromSeconds(30);",
    "// });",
    "```",
    "",
    "---",
    "",
    "## DNS 조회",
    "",
    "```csharp",
    "using System.Net;",
    "",
    "// 호스트 이름으로 IP 주소 조회",
    "IPHostEntry hostEntry = Dns.GetHostEntry(\"www.google.com\");",
    "Console.WriteLine($\"호스트 이름: {hostEntry.HostName}\");",
    "foreach (IPAddress ip in hostEntry.AddressList)",
    "    Console.WriteLine($\"  IP: {ip} ({ip.AddressFamily})\");",
    "",
    "// IP 주소만 조회",
    "IPAddress[] addresses = Dns.GetHostAddresses(\"www.naver.com\");",
    "foreach (var addr in addresses)",
    "    Console.WriteLine($\"  {addr}\");",
    "",
    "// 비동기 DNS 조회",
    "IPHostEntry entry = await Dns.GetHostEntryAsync(\"github.com\");",
    "",
    "// 로컬 호스트 이름/IP",
    "string hostName = Dns.GetHostName();",
    "Console.WriteLine($\"내 호스트 이름: {hostName}\");",
    "IPAddress[] localIps = Dns.GetHostAddresses(hostName);",
    "foreach (var ip in localIps)",
    "    Console.WriteLine($\"  내 IP: {ip}\");",
    "```",
    "",
    "---",
    "",
    "## IP 주소 다루기",
    "",
    "```csharp",
    "using System.Net;",
    "",
    "// IPAddress 생성",
    "IPAddress ip1 = IPAddress.Parse(\"192.168.1.100\");",
    "IPAddress ip2 = IPAddress.Loopback;        // 127.0.0.1",
    "IPAddress ip3 = IPAddress.Any;             // 0.0.0.0",
    "IPAddress ip4 = IPAddress.IPv6Loopback;    // ::1",
    "",
    "// TryParse (안전한 파싱)",
    "if (IPAddress.TryParse(\"192.168.1.1\", out IPAddress parsed))",
    "    Console.WriteLine($\"유효한 IP: {parsed}\");",
    "",
    "// IPEndPoint (IP + 포트)",
    "IPEndPoint endpoint = new IPEndPoint(IPAddress.Parse(\"127.0.0.1\"), 8080);",
    "Console.WriteLine($\"주소: {endpoint.Address}, 포트: {endpoint.Port}\");",
    "",
    "// 바이트 배열 ↔ IPAddress",
    "byte[] ipBytes = ip1.GetAddressBytes();",
    "IPAddress fromBytes = new IPAddress(ipBytes);",
    "```",
    "",
    "---",
    "",
    "## 네트워크 보안 기초 (SSL/TLS)",
    "",
    "```csharp",
    "using System.Net.Security;",
    "using System.Security.Cryptography.X509Certificates;",
    "",
    "// SSL/TLS 클라이언트",
    "async Task SecureClientAsync(string host, int port)",
    "{",
    "    using var client = new TcpClient();",
    "    await client.ConnectAsync(host, port);",
    "",
    "    using var sslStream = new SslStream(",
    "        client.GetStream(),",
    "        leaveInnerStreamOpen: false,",
    "        (sender, cert, chain, errors) =>",
    "        {",
    "            // 인증서 검증 콜백",
    "            if (errors == SslPolicyErrors.None) return true;",
    "            Console.WriteLine($\"인증서 오류: {errors}\");",
    "            return false;",
    "        });",
    "",
    "    await sslStream.AuthenticateAsClientAsync(host);",
    "",
    "    Console.WriteLine($\"암호화: {sslStream.IsEncrypted}\");",
    "    Console.WriteLine($\"프로토콜: {sslStream.SslProtocol}\");",
    "    Console.WriteLine($\"서버 인증서: {sslStream.RemoteCertificate?.Subject}\");",
    "",
    "    // 암호화된 데이터 송수신",
    "    byte[] message = Encoding.UTF8.GetBytes(\"GET / HTTP/1.1\\r\<br>Host: \" + host + \"\\r\<br>\\r\<br>\");",
    "    await sslStream.WriteAsync(message);",
    "",
    "    byte[] buffer = new byte[4096];",
    "    int bytesRead = await sslStream.ReadAsync(buffer);",
    "    Console.WriteLine(Encoding.UTF8.GetString(buffer, 0, bytesRead));",
    "}",
    "```",
    "",
    "---",
    "",
    "## WebSocket 간단 소개",
    "",
    "```csharp",
    "using System.Net.WebSockets;",
    "",
    "async Task WebSocketClientAsync()",
    "{",
    "    using var ws = new ClientWebSocket();",
    "    await ws.ConnectAsync(new Uri(\"ws://localhost:5000/ws\"), CancellationToken.None);",
    "    Console.WriteLine(\"WebSocket 연결됨\");",
    "",
    "    // 메시지 전송",
    "    string message = \"Hello, WebSocket!\";",
    "    byte[] sendBytes = Encoding.UTF8.GetBytes(message);",
    "    await ws.SendAsync(sendBytes, WebSocketMessageType.Text,",
    "        endOfMessage: true, CancellationToken.None);",
    "",
    "    // 메시지 수신",
    "    byte[] buffer = new byte[4096];",
    "    var result = await ws.ReceiveAsync(buffer, CancellationToken.None);",
    "    string received = Encoding.UTF8.GetString(buffer, 0, result.Count);",
    "    Console.WriteLine($\"수신: {received}\");",
    "",
    "    // 연결 종료",
    "    await ws.CloseAsync(WebSocketCloseStatus.NormalClosure,",
    "        \"종료\", CancellationToken.None);",
    "}",
    "```",
    "",
    "---",
    "",
    "## 커스텀 프로토콜 - 파일 업로드",
    "",
    "실제 네트워크 프로그래밍에서는 **메시지 프로토콜**을 직접 설계합니다.",
    "",
    "### 프로토콜 구조",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph Message",
    "        direction LR",
    "        subgraph Header[\"Header (16바이트)\"]",
    "            direction TB",
    "            H1[\"MSGID (4바이트)\"]",
    "            H2[\"MSGTYPE (4바이트)\"]",
    "            H3[\"BODYLEN (4바이트)\"]",
    "            H4[\"FRAGMENTED (1바이트)\"]",
    "            H5[\"LASTMSG (1바이트)\"]",
    "            H6[\"SEQ (2바이트)\"]",
    "        end",
    "        subgraph Body[\"Body (가변)\"]",
    "            direction TB",
    "            B1[\"BodyRequest\"]",
    "            B2[\"BodyResponse\"]",
    "            B3[\"BodyData\"]",
    "            B4[\"BodyResult\"]",
    "        end",
    "    end",
    "```",
    "",
    "### 커스텀 프로토콜 설계 시 고려사항",
    "",
    "| 고려사항 | 설명 |",
    "|----------|------|",
    "| **메시지 경계** | TCP는 스트림이므로 메시지 구분 방법 필요 (길이 접두사, 구분자) |",
    "| **엔디안** | 바이트 순서 통일 (네트워크: Big Endian, x86: Little Endian) |",
    "| **헤더 설계** | 고정 크기 헤더 + 가변 크기 바디 패턴 권장 |",
    "| **버전 관리** | 프로토콜 버전 필드로 하위 호환성 확보 |",
    "| **에러 처리** | 에러 코드 정의, 타임아웃, 재전송 정책 |",
    "| **보안** | 인증, 암호화 (TLS) |",
    "| **페이로드 포맷** | 바이너리 vs JSON vs Protobuf |",
    "",
    "### 메시지 타입",
    "",
    "| 상수 | 값 | 설명 |",
    "|------|-----|------|",
    "| `REQ_FILE_SEND` | 0x01 | 파일 전송 요청 |",
    "| `REP_FILE_SEND` | 0x02 | 파일 전송 응답 (수락/거부) |",
    "| `FILE_SEND_DATA` | 0x03 | 파일 데이터 전송 |",
    "| `FILE_SEND_RES` | 0x04 | 전송 결과 (성공/실패) |",
    "",
    "### Header 클래스",
    "",
    "```csharp",
    "public class Header : ISerializable",
    "{",
    "    public uint MSGID { get; set; }",
    "    public uint MSGTYPE { get; set; }",
    "    public uint BODYLEN { get; set; }",
    "    public byte FRAGMENTED { get; set; }",
    "    public byte LASTMSG { get; set; }",
    "    public ushort SEQ { get; set; }",
    "",
    "    public Header(byte[] bytes)",
    "    {",
    "        MSGID = BitConverter.ToUInt32(bytes, 0);",
    "        MSGTYPE = BitConverter.ToUInt32(bytes, 4);",
    "        BODYLEN = BitConverter.ToUInt32(bytes, 8);",
    "        FRAGMENTED = bytes[12];",
    "        LASTMSG = bytes[13];",
    "        SEQ = BitConverter.ToUInt16(bytes, 14);",
    "    }",
    "",
    "    public byte[] GetBytes()",
    "    {",
    "        byte[] bytes = new byte[16];",
    "        Array.Copy(BitConverter.GetBytes(MSGID), 0, bytes, 0, 4);",
    "        Array.Copy(BitConverter.GetBytes(MSGTYPE), 0, bytes, 4, 4);",
    "        Array.Copy(BitConverter.GetBytes(BODYLEN), 0, bytes, 8, 4);",
    "        bytes[12] = FRAGMENTED;",
    "        bytes[13] = LASTMSG;",
    "        Array.Copy(BitConverter.GetBytes(SEQ), 0, bytes, 14, 2);",
    "        return bytes;",
    "    }",
    "",
    "    public int GetSize() => 16;",
    "}",
    "```",
    "",
    "### Message 클래스",
    "",
    "```csharp",
    "public interface ISerializable",
    "{",
    "    byte[] GetBytes();",
    "    int GetSize();",
    "}",
    "",
    "public class Message : ISerializable",
    "{",
    "    public Header Header { get; set; }",
    "    public ISerializable Body { get; set; }",
    "",
    "    public byte[] GetBytes()",
    "    {",
    "        byte[] bytes = new byte[GetSize()];",
    "        Header.GetBytes().CopyTo(bytes, 0);",
    "        Body.GetBytes().CopyTo(bytes, Header.GetSize());",
    "        return bytes;",
    "    }",
    "",
    "    public int GetSize() => Header.GetSize() + Body.GetSize();",
    "}",
    "```",
    "",
    "### MessageUtil (송수신 유틸)",
    "",
    "```csharp",
    "public class MessageUtil",
    "{",
    "    public static void Send(Stream writer, Message msg)",
    "    {",
    "        writer.Write(msg.GetBytes(), 0, msg.GetSize());",
    "    }",
    "",
    "    public static Message Receive(Stream reader)",
    "    {",
    "        // 1. 헤더(16바이트) 수신",
    "        byte[] hBuffer = new byte[16];",
    "        int totalRecv = 0, sizeToRead = 16;",
    "        while (sizeToRead > 0)",
    "        {",
    "            byte[] buffer = new byte[sizeToRead];",
    "            int recv = reader.Read(buffer, 0, sizeToRead);",
    "            if (recv == 0) return null;",
    "            buffer.CopyTo(hBuffer, totalRecv);",
    "            totalRecv += recv;",
    "            sizeToRead -= recv;",
    "        }",
    "        Header header = new Header(hBuffer);",
    "",
    "        // 2. 바디(BODYLEN 바이트) 수신",
    "        byte[] bBuffer = new byte[header.BODYLEN];",
    "        totalRecv = 0;",
    "        sizeToRead = (int)header.BODYLEN;",
    "        while (sizeToRead > 0)",
    "        {",
    "            byte[] buffer = new byte[sizeToRead];",
    "            int recv = reader.Read(buffer, 0, sizeToRead);",
    "            if (recv == 0) return null;",
    "            buffer.CopyTo(bBuffer, totalRecv);",
    "            totalRecv += recv;",
    "            sizeToRead -= recv;",
    "        }",
    "",
    "        // 3. MSGTYPE에 따라 Body 파싱",
    "        ISerializable body = header.MSGTYPE switch",
    "        {",
    "            CONSTANTS.REQ_FILE_SEND  => new BodyRequest(bBuffer),",
    "            CONSTANTS.REP_FILE_SEND  => new BodyResponse(bBuffer),",
    "            CONSTANTS.FILE_SEND_DATA => new BodyData(bBuffer),",
    "            CONSTANTS.FILE_SEND_RES  => new BodyResult(bBuffer),",
    "            _ => throw new Exception($\"Unknown MSGTYPE: {header.MSGTYPE}\")",
    "        };",
    "",
    "        return new Message() { Header = header, Body = body };",
    "    }",
    "}",
    "```",
    "",
    "### 파일 전송 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트(FileSender)",
    "    participant S as 서버(FileReceiver)",
    "    C->>S: REQ_FILE_SEND (파일명, 크기)",
    "    S->>C: REP_FILE_SEND (수락/거부)",
    "    C->>S: FILE_SEND_DATA",
    "    C->>S: FILE_SEND_DATA",
    "    C->>S: FILE_SEND_DATA (LAST)",
    "    Note over C,S: 4KB 청크 단위로 반복 전송",
    "    S->>C: FILE_SEND_RES (성공/실패)",
    "```",
    "",
    "### FileSender (클라이언트) 핵심 코드",
    "",
    "```csharp",
    "const int CHUNK_SIZE = 4096;",
    "",
    "// 1. 파일 전송 요청",
    "Message reqMsg = new Message();",
    "reqMsg.Body = new BodyRequest()",
    "{",
    "    FILESIZE = new FileInfo(filepath).Length,",
    "    FILENAME = Encoding.Default.GetBytes(filepath)",
    "};",
    "reqMsg.Header = new Header()",
    "{",
    "    MSGID = msgId++,",
    "    MSGTYPE = CONSTANTS.REQ_FILE_SEND,",
    "    BODYLEN = (uint)reqMsg.Body.GetSize(),",
    "    FRAGMENTED = CONSTANTS.NOT_FRAGMENTED,",
    "    LASTMSG = CONSTANTS.LASTMSG,",
    "    SEQ = 0",
    "};",
    "",
    "TcpClient client = new TcpClient(clientAddress);",
    "client.Connect(serverAddress);",
    "NetworkStream stream = client.GetStream();",
    "MessageUtil.Send(stream, reqMsg);",
    "",
    "// 2. 응답 확인",
    "Message rspMsg = MessageUtil.Receive(stream);",
    "if (((BodyResponse)rspMsg.Body).RESPONSE == CONSTANTS.DENIED)",
    "{",
    "    Console.WriteLine(\"서버에서 파일 전송을 거부했습니다.\");",
    "    return;",
    "}",
    "",
    "// 3. 파일 데이터를 4KB 청크 단위로 전송",
    "using (Stream fileStream = new FileStream(filepath, FileMode.Open))",
    "{",
    "    byte[] rbytes = new byte[CHUNK_SIZE];",
    "    int totalRead = 0;",
    "    ushort msgSeq = 0;",
    "",
    "    while (totalRead < fileStream.Length)",
    "    {",
    "        int read = fileStream.Read(rbytes, 0, CHUNK_SIZE);",
    "        totalRead += read;",
    "",
    "        byte[] sendBytes = new byte[read];",
    "        Array.Copy(rbytes, 0, sendBytes, 0, read);",
    "",
    "        Message fileMsg = new Message();",
    "        fileMsg.Body = new BodyData(sendBytes);",
    "        fileMsg.Header = new Header()",
    "        {",
    "            MSGID = msgId,",
    "            MSGTYPE = CONSTANTS.FILE_SEND_DATA,",
    "            BODYLEN = (uint)fileMsg.Body.GetSize(),",
    "            FRAGMENTED = CONSTANTS.FRAGMENTED,",
    "            LASTMSG = (totalRead < fileStream.Length)",
    "                ? CONSTANTS.NOT_LASTMSG : CONSTANTS.LASTMSG,",
    "            SEQ = msgSeq++",
    "        };",
    "",
    "        MessageUtil.Send(stream, fileMsg);",
    "    }",
    "",
    "    // 4. 결과 수신",
    "    Message rstMsg = MessageUtil.Receive(stream);",
    "    BodyResult result = (BodyResult)rstMsg.Body;",
    "    Console.WriteLine($\"파일 전송 성공 : {result.RESULT == CONSTANTS.SUCCESS}\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## 실전 예제: 멀티 클라이언트 채팅 서버 (비동기)",
    "",
    "```csharp",
    "using System;",
    "using System.Collections.Concurrent;",
    "using System.Net;",
    "using System.Net.Sockets;",
    "using System.Text;",
    "using System.Threading.Tasks;",
    "",
    "class ChatServer",
    "{",
    "    private static ConcurrentDictionary<string, TcpClient> _clients = new();",
    "",
    "    static async Task Main()",
    "    {",
    "        var listener = new TcpListener(IPAddress.Any, 9000);",
    "        listener.Start();",
    "        Console.WriteLine(\"채팅 서버 시작 (포트: 9000)\");",
    "",
    "        while (true)",
    "        {",
    "            TcpClient client = await listener.AcceptTcpClientAsync();",
    "            _ = HandleClientAsync(client);",
    "        }",
    "    }",
    "",
    "    static async Task HandleClientAsync(TcpClient client)",
    "    {",
    "        string clientId = client.Client.RemoteEndPoint.ToString();",
    "        _clients.TryAdd(clientId, client);",
    "        await BroadcastAsync($\"[서버] {clientId} 입장\");",
    "",
    "        NetworkStream stream = client.GetStream();",
    "        byte[] buffer = new byte[4096];",
    "",
    "        try",
    "        {",
    "            int bytesRead;",
    "            while ((bytesRead = await stream.ReadAsync(buffer)) > 0)",
    "            {",
    "                string message = Encoding.UTF8.GetString(buffer, 0, bytesRead);",
    "                Console.WriteLine($\"[{clientId}] {message}\");",
    "                await BroadcastAsync($\"[{clientId}] {message}\", clientId);",
    "            }",
    "        }",
    "        catch (Exception) { }",
    "        finally",
    "        {",
    "            _clients.TryRemove(clientId, out _);",
    "            client.Close();",
    "            await BroadcastAsync($\"[서버] {clientId} 퇴장\");",
    "        }",
    "    }",
    "",
    "    static async Task BroadcastAsync(string message, string excludeId = null)",
    "    {",
    "        byte[] data = Encoding.UTF8.GetBytes(message);",
    "        foreach (var (id, client) in _clients)",
    "        {",
    "            if (id == excludeId) continue;",
    "            try",
    "            {",
    "                await client.GetStream().WriteAsync(data);",
    "            }",
    "            catch",
    "            {",
    "                _clients.TryRemove(id, out _);",
    "            }",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 실전 예제: REST API 클라이언트",
    "",
    "```csharp",
    "using System.Net.Http;",
    "using System.Text;",
    "using System.Text.Json;",
    "",
    "class ApiClient",
    "{",
    "    private readonly HttpClient _client;",
    "    private readonly JsonSerializerOptions _jsonOptions = new()",
    "    {",
    "        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,",
    "        PropertyNameCaseInsensitive = true",
    "    };",
    "",
    "    public ApiClient(string baseUrl)",
    "    {",
    "        _client = new HttpClient { BaseAddress = new Uri(baseUrl) };",
    "    }",
    "",
    "    public async Task<List<User>> GetUsersAsync()",
    "    {",
    "        var response = await _client.GetAsync(\"/api/users\");",
    "        response.EnsureSuccessStatusCode();",
    "        string json = await response.Content.ReadAsStringAsync();",
    "        return JsonSerializer.Deserialize<List<User>>(json, _jsonOptions);",
    "    }",
    "",
    "    public async Task<User> CreateUserAsync(User user)",
    "    {",
    "        string json = JsonSerializer.Serialize(user, _jsonOptions);",
    "        var content = new StringContent(json, Encoding.UTF8, \"application/json\");",
    "        var response = await _client.PostAsync(\"/api/users\", content);",
    "        response.EnsureSuccessStatusCode();",
    "        string responseJson = await response.Content.ReadAsStringAsync();",
    "        return JsonSerializer.Deserialize<User>(responseJson, _jsonOptions);",
    "    }",
    "",
    "    public async Task DeleteUserAsync(int id)",
    "    {",
    "        var response = await _client.DeleteAsync($\"/api/users/{id}\");",
    "        response.EnsureSuccessStatusCode();",
    "    }",
    "}",
    "",
    "record User(int Id, string Name, string Email);",
    "",
    "// 사용 예",
    "var api = new ApiClient(\"https://jsonplaceholder.typicode.com\");",
    "var users = await api.GetUsersAsync();",
    "foreach (var user in users.Take(5))",
    "    Console.WriteLine($\"{user.Id}: {user.Name} ({user.Email})\");",
    "```",
    "",
    "---",
    "",
    "## 네트워크 디버깅 도구/팁",
    "",
    "| 도구/방법 | 용도 |",
    "|----------|------|",
    "| `netstat -an` | 열린 포트 및 연결 상태 확인 |",
    "| `telnet host port` | TCP 연결 테스트 |",
    "| Wireshark | 패킷 캡처 및 분석 |",
    "| Fiddler / Charles | HTTP(S) 트래픽 디버깅 |",
    "| Postman | REST API 테스트 |",
    "| `ping` / `tracert` | 네트워크 경로 및 지연 시간 확인 |",
    "| `nslookup` / `dig` | DNS 조회 테스트 |",
    "",
    "```csharp",
    "// 코드에서 네트워크 디버깅",
    "using System.Net.NetworkInformation;",
    "",
    "// Ping 테스트",
    "using var ping = new Ping();",
    "PingReply reply = await ping.SendPingAsync(\"google.com\", 3000);",
    "Console.WriteLine($\"상태: {reply.Status}\");",
    "Console.WriteLine($\"응답 시간: {reply.RoundtripTime}ms\");",
    "Console.WriteLine($\"TTL: {reply.Options?.Ttl}\");",
    "",
    "// 네트워크 인터페이스 정보",
    "foreach (var ni in NetworkInterface.GetAllNetworkInterfaces())",
    "{",
    "    if (ni.OperationalStatus == OperationalStatus.Up)",
    "    {",
    "        Console.WriteLine($\"{ni.Name}: {ni.NetworkInterfaceType}\");",
    "        var ipProps = ni.GetIPProperties();",
    "        foreach (var addr in ipProps.UnicastAddresses)",
    "            Console.WriteLine($\"  IP: {addr.Address}\");",
    "    }",
    "}",
    "```",
    "",
    "> **팁**: 소켓 프로그래밍에서 문제가 발생하면 먼저 `netstat`으로 포트 상태를 확인하고, Wireshark으로 실제 패킷을 확인하세요.",
    "",
    "---",
    "",
    "## 주요 클래스 정리",
    "",
    "| 클래스 | 네임스페이스 | 역할 |",
    "|--------|-------------|------|",
    "| `TcpListener` | `System.Net.Sockets` | TCP 서버 리스너 |",
    "| `TcpClient` | `System.Net.Sockets` | TCP 클라이언트 |",
    "| `UdpClient` | `System.Net.Sockets` | UDP 송수신 |",
    "| `NetworkStream` | `System.Net.Sockets` | 소켓 기반 스트림 |",
    "| `SslStream` | `System.Net.Security` | SSL/TLS 암호화 스트림 |",
    "| `HttpClient` | `System.Net.Http` | HTTP 요청/응답 |",
    "| `ClientWebSocket` | `System.Net.WebSockets` | WebSocket 클라이언트 |",
    "| `IPEndPoint` | `System.Net` | IP + 포트 조합 |",
    "| `IPAddress` | `System.Net` | IP 주소 표현 |",
    "| `Dns` | `System.Net` | DNS 조회 |",
    "| `Ping` | `System.Net.NetworkInformation` | ICMP Ping |",
    "| `Encoding` | `System.Text` | 문자열 ↔ 바이트 변환 |",
    "",
    "---",
    "",
    "### 요약",
    "C# 네트워크 프로그래밍의 기본은 `TcpListener`(서버)와 `TcpClient`(클라이언트)로 TCP 연결을 맺고, `NetworkStream`으로 데이터를 주고받는 것입니다. `async/await`를 활용하면 비블로킹으로 여러 클라이언트를 동시에 처리할 수 있습니다. UDP는 `UdpClient`로 비연결 통신을, `HttpClient`는 REST API 호출을, `SslStream`은 보안 통신을 구현합니다. 실전에서는 Header + Body 구조의 커스텀 프로토콜을 설계하여 메시지 타입 구분, 분할 전송(Fragmentation), 시퀀스 번호 관리 등을 구현하며, 네트워크 디버깅에는 `netstat`, Wireshark, Fiddler 등의 도구를 활용합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
