<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-reflection-attribute",
  title: "C# 리플렉션과 어트리뷰트",
  date: "2026-02-25",
  summary: "어트리뷰트(Obsolete, 사용자 정의), 리플렉션(Type, FieldInfo, MethodInfo), 동적 인스턴스 생성, 호출자 정보, Emit까지 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","reflection","attribute","type","emit","dynamic","metadata"],
  content: [
    "## 한 줄 요약",
    "C#의 **어트리뷰트**는 코드에 메타데이터를 부여하고, **리플렉션**은 런타임에 타입 정보를 조회·조작하여 동적 프로그래밍을 가능하게 합니다.",
    "",
    "---",
    "",
    "## 리플렉션 개념 흐름",
    "",
    "소스 코드가 컴파일되어 어셈블리(DLL/EXE)가 되면, **메타데이터**가 함께 저장됩니다. 리플렉션은 이 메타데이터를 런타임에 읽는 기술입니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"소스 코드\<br>(.cs 파일)\"] -->|\"컴파일\"| B[\"어셈블리\<br>(.dll / .exe)\"]",
    "    B --> C[\"IL 코드\"]",
    "    B --> D[\"메타데이터\<br>(타입, 멤버, 어트리뷰트)\"]",
    "    D -->|\"리플렉션으로 읽기\"| E[\"Type 객체\"]",
    "    E --> F[\"MethodInfo\"]",
    "    E --> G[\"PropertyInfo\"]",
    "    E --> H[\"FieldInfo\"]",
    "    E --> I[\"ConstructorInfo\"]",
    "    E --> J[\"Attribute 정보\"]",
    "```",
    "",
    "> 리플렉션은 **런타임에 타입 정보를 검사하고 조작**하는 강력한 메커니즘입니다. 프레임워크, DI 컨테이너, ORM, 직렬화 등 많은 곳에서 핵심적으로 사용됩니다.",
    "",
    "---",
    "",
    "## 어트리뷰트 (Attribute)",
    "",
    "코드 요소(클래스, 메서드 등)에 **메타데이터를 부착**하는 기능입니다. 어트리뷰트 자체는 동작을 변경하지 않지만, 리플렉션과 결합하면 강력한 선언적 프로그래밍이 가능합니다.",
    "",
    "### 내장 어트리뷰트 - [Obsolete]",
    "",
    "폐기된 코드에 경고를 표시합니다.",
    "",
    "```csharp",
    "class MyClass",
    "{",
    "    [Obsolete(\"OldMethod는 폐기되었습니다. NewMethod()를 이용하세요.\")]",
    "    public void OldMethod()",
    "    {",
    "        Console.WriteLine(\"I'm old\");",
    "    }",
    "",
    "    // 두 번째 매개변수를 true로 설정하면 컴파일 에러로 강제",
    "    [Obsolete(\"이 메서드는 완전히 제거되었습니다.\", true)]",
    "    public void RemovedMethod() { }",
    "",
    "    public void NewMethod()",
    "    {",
    "        Console.WriteLine(\"I'm new\");",
    "    }",
    "}",
    "",
    "MyClass obj = new MyClass();",
    "obj.OldMethod();  // 컴파일 시 경고 발생",
    "// obj.RemovedMethod(); // 컴파일 에러!",
    "obj.NewMethod();",
    "```",
    "",
    "---",
    "",
    "### 주요 내장 어트리뷰트 목록",
    "",
    "| 어트리뷰트 | 네임스페이스 | 설명 |",
    "|-----------|-------------|------|",
    "| `[Obsolete]` | `System` | 사용 중단된 코드 표시 |",
    "| `[Conditional]` | `System.Diagnostics` | 조건부 컴파일 (심볼 정의 시만 호출) |",
    "| `[CallerMemberName]` | `System.Runtime.CompilerServices` | 호출자 멤버 이름 |",
    "| `[CallerFilePath]` | `System.Runtime.CompilerServices` | 호출자 소스 파일 경로 |",
    "| `[CallerLineNumber]` | `System.Runtime.CompilerServices` | 호출자 줄 번호 |",
    "| `[Serializable]` | `System` | 직렬화 가능 표시 |",
    "| `[DllImport]` | `System.Runtime.InteropServices` | 네이티브 DLL 함수 호출 |",
    "| `[Flags]` | `System` | 비트 플래그 열거형 표시 |",
    "| `[AttributeUsage]` | `System` | 어트리뷰트 적용 대상/규칙 지정 |",
    "",
    "### [Conditional] 어트리뷰트",
    "",
    "```csharp",
    "using System.Diagnostics;",
    "",
    "class Logger",
    "{",
    "    [Conditional(\"DEBUG\")]",
    "    public static void DebugLog(string message)",
    "    {",
    "        Console.WriteLine($\"[DEBUG] {message}\");",
    "    }",
    "",
    "    [Conditional(\"TRACE\")]",
    "    public static void TraceLog(string message)",
    "    {",
    "        Console.WriteLine($\"[TRACE] {message}\");",
    "    }",
    "}",
    "",
    "// DEBUG 심볼이 정의된 경우에만 실제 호출",
    "// Release 빌드에서는 호출 코드 자체가 제거됨",
    "Logger.DebugLog(\"디버그 모드에서만 출력됩니다\");",
    "```",
    "",
    "### [DllImport] 어트리뷰트",
    "",
    "```csharp",
    "using System.Runtime.InteropServices;",
    "",
    "class NativeApi",
    "{",
    "    [DllImport(\"user32.dll\", CharSet = CharSet.Unicode)]",
    "    public static extern int MessageBox(",
    "        IntPtr hWnd, string text, string caption, uint type);",
    "}",
    "",
    "// Win32 API 직접 호출",
    "NativeApi.MessageBox(IntPtr.Zero, \"안녕하세요!\", \"C#에서 호출\", 0);",
    "```",
    "",
    "---",
    "",
    "### 사용자 정의 어트리뷰트",
    "",
    "`System.Attribute`를 상속하여 직접 어트리뷰트를 만들 수 있습니다.",
    "",
    "```csharp",
    "[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]",
    "class History : System.Attribute",
    "{",
    "    private string programmer;",
    "",
    "    public double Version { get; set; }",
    "    public string Changes { get; set; }",
    "",
    "    public History(string programmer)",
    "    {",
    "        this.programmer = programmer;",
    "        Version = 1.0;",
    "        Changes = \"First release\";",
    "    }",
    "",
    "    public string Programmer",
    "    {",
    "        get { return programmer; }",
    "    }",
    "}",
    "```",
    "",
    "### 어트리뷰트 적용 및 읽기",
    "",
    "```csharp",
    "[History(\"Sean\", Version = 0.1, Changes = \"2017-11-01 Created class stub\")]",
    "[History(\"Bob\",  Version = 0.2, Changes = \"2020-12-03 Added Func() Method\")]",
    "class MyClass",
    "{",
    "    public void Func()",
    "    {",
    "        Console.WriteLine(\"Func()\");",
    "    }",
    "}",
    "",
    "// 어트리뷰트 읽기",
    "Type type = typeof(MyClass);",
    "Attribute[] attributes = Attribute.GetCustomAttributes(type);",
    "",
    "foreach (Attribute a in attributes)",
    "{",
    "    History h = a as History;",
    "    if (h != null)",
    "        Console.WriteLine($\"Ver:{h.Version}, Programmer:{h.Programmer}, Changes:{h.Changes}\");",
    "}",
    "// Ver:0.1, Programmer:Sean, Changes:2017-11-01 Created class stub",
    "// Ver:0.2, Programmer:Bob,  Changes:2020-12-03 Added Func() Method",
    "```",
    "",
    "---",
    "",
    "### AttributeUsage 상세",
    "",
    "`[AttributeUsage]`는 사용자 정의 어트리뷰트의 적용 규칙을 제어합니다.",
    "",
    "| 속성 | 타입 | 설명 | 기본값 |",
    "|------|------|------|--------|",
    "| `ValidOn` | `AttributeTargets` | 적용 가능 대상 | `All` |",
    "| `AllowMultiple` | `bool` | 같은 요소에 여러 번 적용 가능 여부 | `false` |",
    "| `Inherited` | `bool` | 파생 클래스에 상속 여부 | `true` |",
    "",
    "### AttributeTargets 열거형",
    "",
    "| 값 | 대상 |",
    "|-----|------|",
    "| `Assembly` | 어셈블리 |",
    "| `Module` | 모듈 |",
    "| `Class` | 클래스 |",
    "| `Struct` | 구조체 |",
    "| `Enum` | 열거형 |",
    "| `Constructor` | 생성자 |",
    "| `Method` | 메서드 |",
    "| `Property` | 프로퍼티 |",
    "| `Field` | 필드 |",
    "| `Event` | 이벤트 |",
    "| `Interface` | 인터페이스 |",
    "| `Parameter` | 매개변수 |",
    "| `ReturnValue` | 반환값 |",
    "| `All` | 모든 요소 |",
    "",
    "```csharp",
    "// 메서드와 프로퍼티에만 적용 가능, 중복 적용 불가, 상속 안 됨",
    "[AttributeUsage(",
    "    AttributeTargets.Method | AttributeTargets.Property,",
    "    AllowMultiple = false,",
    "    Inherited = false)]",
    "class ValidateAttribute : Attribute",
    "{",
    "    public string Rule { get; }",
    "    public ValidateAttribute(string rule) => Rule = rule;",
    "}",
    "```",
    "",
    "---",
    "",
    "## 호출자 정보 어트리뷰트",
    "",
    "메서드를 호출한 **파일명, 줄 번호, 멤버 이름**을 자동으로 가져옵니다.",
    "",
    "```csharp",
    "using System.Runtime.CompilerServices;",
    "",
    "public static class Trace",
    "{",
    "    public static void WriteLine(string message,",
    "        [CallerFilePath] string file = \"\",",
    "        [CallerLineNumber] int line = 0,",
    "        [CallerMemberName] string member = \"\")",
    "    {",
    "        Console.WriteLine($\"{file}(Line:{line}) {member}: {message}\");",
    "    }",
    "}",
    "",
    "Trace.WriteLine(\"즐거운 프로그래밍!\");",
    "// MainApp.cs(Line:22) Main: 즐거운 프로그래밍!",
    "```",
    "",
    "| 어트리뷰트 | 제공 정보 |",
    "|------------|-----------|",
    "| `[CallerFilePath]` | 호출한 소스 파일 경로 |",
    "| `[CallerLineNumber]` | 호출한 줄 번호 |",
    "| `[CallerMemberName]` | 호출한 멤버(메서드/프로퍼티) 이름 |",
    "",
    "> **활용 팁**: INotifyPropertyChanged 구현에서 `[CallerMemberName]`을 사용하면 프로퍼티 이름을 하드코딩하지 않아도 됩니다.",
    "",
    "```csharp",
    "class ViewModel : INotifyPropertyChanged",
    "{",
    "    public event PropertyChangedEventHandler PropertyChanged;",
    "",
    "    protected void OnPropertyChanged([CallerMemberName] string name = \"\")",
    "    {",
    "        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));",
    "    }",
    "",
    "    private string _title;",
    "    public string Title",
    "    {",
    "        get => _title;",
    "        set",
    "        {",
    "            _title = value;",
    "            OnPropertyChanged(); // 자동으로 \"Title\"이 전달됨",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 커스텀 어트리뷰트 실전 예제",
    "",
    "### 유효성 검사 어트리뷰트",
    "",
    "```csharp",
    "[AttributeUsage(AttributeTargets.Property)]",
    "class RequiredAttribute : Attribute { }",
    "",
    "[AttributeUsage(AttributeTargets.Property)]",
    "class StringLengthAttribute : Attribute",
    "{",
    "    public int MinLength { get; }",
    "    public int MaxLength { get; }",
    "    public StringLengthAttribute(int min, int max)",
    "    {",
    "        MinLength = min;",
    "        MaxLength = max;",
    "    }",
    "}",
    "",
    "[AttributeUsage(AttributeTargets.Property)]",
    "class RangeAttribute : Attribute",
    "{",
    "    public int Min { get; }",
    "    public int Max { get; }",
    "    public RangeAttribute(int min, int max) { Min = min; Max = max; }",
    "}",
    "",
    "class User",
    "{",
    "    [Required]",
    "    [StringLength(2, 50)]",
    "    public string Name { get; set; }",
    "",
    "    [Required]",
    "    [Range(1, 150)]",
    "    public int Age { get; set; }",
    "",
    "    [StringLength(0, 200)]",
    "    public string Bio { get; set; }",
    "}",
    "",
    "// 리플렉션으로 유효성 검사 실행",
    "static List<string> Validate(object obj)",
    "{",
    "    var errors = new List<string>();",
    "    var properties = obj.GetType().GetProperties();",
    "",
    "    foreach (var prop in properties)",
    "    {",
    "        object value = prop.GetValue(obj);",
    "",
    "        if (prop.GetCustomAttribute<RequiredAttribute>() != null)",
    "        {",
    "            if (value == null || (value is string s && string.IsNullOrEmpty(s)))",
    "                errors.Add($\"{prop.Name}은(는) 필수 항목입니다.\");",
    "        }",
    "",
    "        var strLen = prop.GetCustomAttribute<StringLengthAttribute>();",
    "        if (strLen != null && value is string str)",
    "        {",
    "            if (str.Length < strLen.MinLength || str.Length > strLen.MaxLength)",
    "                errors.Add($\"{prop.Name}은(는) {strLen.MinLength}~{strLen.MaxLength}자여야 합니다.\");",
    "        }",
    "",
    "        var range = prop.GetCustomAttribute<RangeAttribute>();",
    "        if (range != null && value is int num)",
    "        {",
    "            if (num < range.Min || num > range.Max)",
    "                errors.Add($\"{prop.Name}은(는) {range.Min}~{range.Max} 범위여야 합니다.\");",
    "        }",
    "    }",
    "    return errors;",
    "}",
    "```",
    "",
    "### API 라우팅 어트리뷰트",
    "",
    "```csharp",
    "[AttributeUsage(AttributeTargets.Method)]",
    "class RouteAttribute : Attribute",
    "{",
    "    public string Method { get; }",
    "    public string Path { get; }",
    "    public RouteAttribute(string method, string path)",
    "    {",
    "        Method = method;",
    "        Path = path;",
    "    }",
    "}",
    "",
    "class ApiController",
    "{",
    "    [Route(\"GET\", \"/api/users\")]",
    "    public string GetUsers() => \"유저 목록 반환\";",
    "",
    "    [Route(\"GET\", \"/api/users/{id}\")]",
    "    public string GetUser(int id) => $\"유저 {id} 반환\";",
    "",
    "    [Route(\"POST\", \"/api/users\")]",
    "    public string CreateUser() => \"유저 생성\";",
    "",
    "    [Route(\"DELETE\", \"/api/users/{id}\")]",
    "    public string DeleteUser(int id) => $\"유저 {id} 삭제\";",
    "}",
    "",
    "// 리플렉션으로 라우트 테이블 자동 생성",
    "var controller = typeof(ApiController);",
    "foreach (var method in controller.GetMethods())",
    "{",
    "    var route = method.GetCustomAttribute<RouteAttribute>();",
    "    if (route != null)",
    "        Console.WriteLine($\"[{route.Method}] {route.Path} → {method.Name}()\");",
    "}",
    "// [GET] /api/users → GetUsers()",
    "// [GET] /api/users/{id} → GetUser()",
    "// [POST] /api/users → CreateUser()",
    "// [DELETE] /api/users/{id} → DeleteUser()",
    "```",
    "",
    "---",
    "",
    "## 리플렉션 (Reflection)",
    "",
    "**런타임에 타입 정보를 조회**하고 동적으로 조작하는 기능입니다.",
    "",
    "### Type 정보 얻기 (3가지 방법)",
    "",
    "```csharp",
    "// 방법 1: typeof 연산자 (컴파일 타임에 타입을 알 때)",
    "Type type1 = typeof(int);",
    "",
    "// 방법 2: GetType() 메서드 (인스턴스에서)",
    "int a = 0;",
    "Type type2 = a.GetType();",
    "",
    "// 방법 3: Type.GetType() (문자열로, 런타임에 타입 이름만 알 때)",
    "Type type3 = Type.GetType(\"System.Int32\");",
    "```",
    "",
    "### Type 클래스 주요 메서드/프로퍼티",
    "",
    "| 메서드/프로퍼티 | 반환 타입 | 설명 |",
    "|----------------|-----------|------|",
    "| `GetMethods()` | `MethodInfo[]` | 모든 public 메서드 |",
    "| `GetProperties()` | `PropertyInfo[]` | 모든 public 프로퍼티 |",
    "| `GetFields()` | `FieldInfo[]` | 모든 public 필드 |",
    "| `GetConstructors()` | `ConstructorInfo[]` | 모든 public 생성자 |",
    "| `GetInterfaces()` | `Type[]` | 구현 인터페이스 목록 |",
    "| `GetEvents()` | `EventInfo[]` | 모든 이벤트 |",
    "| `GetCustomAttributes()` | `object[]` | 어트리뷰트 목록 |",
    "| `GetMethod(name)` | `MethodInfo` | 이름으로 특정 메서드 |",
    "| `GetProperty(name)` | `PropertyInfo` | 이름으로 특정 프로퍼티 |",
    "| `BaseType` | `Type` | 부모 클래스 타입 |",
    "| `IsAbstract` | `bool` | 추상 클래스 여부 |",
    "| `IsInterface` | `bool` | 인터페이스 여부 |",
    "| `IsEnum` | `bool` | 열거형 여부 |",
    "| `IsValueType` | `bool` | 값 타입 여부 |",
    "| `FullName` | `string` | 네임스페이스 포함 전체 이름 |",
    "",
    "---",
    "",
    "### BindingFlags 상세",
    "",
    "`GetMethods()`, `GetFields()` 등에 `BindingFlags`를 전달하면 **조회 범위를 세밀하게 제어**할 수 있습니다.",
    "",
    "| BindingFlags | 설명 |",
    "|-------------|------|",
    "| `Public` | public 멤버 |",
    "| `NonPublic` | private, protected, internal 멤버 |",
    "| `Instance` | 인스턴스 멤버 |",
    "| `Static` | 정적 멤버 |",
    "| `DeclaredOnly` | 상속된 멤버 제외, 해당 타입에서 선언된 것만 |",
    "| `FlattenHierarchy` | 상속 계층의 정적 멤버 포함 |",
    "",
    "```csharp",
    "using System.Reflection;",
    "",
    "class Animal",
    "{",
    "    public string Name;",
    "    private int _age;",
    "    protected bool IsAlive;",
    "    public static int Count;",
    "}",
    "",
    "// public 인스턴스 필드만",
    "var publicFields = typeof(Animal).GetFields(",
    "    BindingFlags.Public | BindingFlags.Instance);",
    "// → Name",
    "",
    "// private 인스턴스 필드만",
    "var privateFields = typeof(Animal).GetFields(",
    "    BindingFlags.NonPublic | BindingFlags.Instance);",
    "// → _age, IsAlive",
    "",
    "// 모든 필드 (public + private + instance + static)",
    "var allFields = typeof(Animal).GetFields(",
    "    BindingFlags.Public | BindingFlags.NonPublic |",
    "    BindingFlags.Instance | BindingFlags.Static);",
    "// → Name, _age, IsAlive, Count",
    "```",
    "",
    "> **주의**: `BindingFlags`를 하나라도 지정하면 기본값이 무시됩니다. 예를 들어 `Public`만 지정하면 인스턴스/정적 구분이 없어 아무것도 나오지 않을 수 있습니다. 반드시 `Instance`나 `Static`도 함께 지정하세요.",
    "",
    "---",
    "",
    "### 인터페이스, 필드, 메서드, 프로퍼티 조회",
    "",
    "```csharp",
    "using System.Reflection;",
    "",
    "Type type = typeof(int);",
    "",
    "// 인터페이스 조회",
    "Type[] interfaces = type.GetInterfaces();",
    "foreach (Type i in interfaces)",
    "    Console.WriteLine($\"Interface: {i.Name}\");",
    "",
    "// 필드 조회 (private/public/static 포함)",
    "FieldInfo[] fields = type.GetFields(",
    "    BindingFlags.NonPublic |",
    "    BindingFlags.Public |",
    "    BindingFlags.Static |",
    "    BindingFlags.Instance);",
    "",
    "foreach (FieldInfo field in fields)",
    "{",
    "    string access = field.IsPublic ? \"public\" :",
    "                    field.IsPrivate ? \"private\" : \"protected\";",
    "    Console.WriteLine($\"Access:{access}, Type:{field.FieldType.Name}, Name:{field.Name}\");",
    "}",
    "",
    "// 메서드 조회",
    "MethodInfo[] methods = type.GetMethods();",
    "foreach (MethodInfo method in methods)",
    "{",
    "    ParameterInfo[] parameters = method.GetParameters();",
    "    string paramStr = string.Join(\", \", Array.ConvertAll(parameters, p => p.ParameterType.Name));",
    "    Console.WriteLine($\"Return:{method.ReturnType.Name}, Name:{method.Name}({paramStr})\");",
    "}",
    "",
    "// 프로퍼티 조회",
    "PropertyInfo[] properties = type.GetProperties();",
    "foreach (PropertyInfo prop in properties)",
    "    Console.WriteLine($\"Type:{prop.PropertyType.Name}, Name:{prop.Name}\");",
    "```",
    "",
    "---",
    "",
    "## 동적 인스턴스 생성 (Activator)",
    "",
    "리플렉션으로 **런타임에 객체를 생성**하고 메서드를 호출합니다.",
    "",
    "```csharp",
    "class Profile",
    "{",
    "    private string name;",
    "    private string phone;",
    "",
    "    public Profile() { name = \"\"; phone = \"\"; }",
    "    public Profile(string name, string phone)",
    "    {",
    "        this.name = name;",
    "        this.phone = phone;",
    "    }",
    "",
    "    public void Print()",
    "    {",
    "        Console.WriteLine($\"{name}, {phone}\");",
    "    }",
    "",
    "    public string Name { get; set; }",
    "    public string Phone { get; set; }",
    "}",
    "",
    "// 타입 정보 가져오기",
    "Type type = Type.GetType(\"DynamicInstance.Profile\");",
    "MethodInfo methodInfo = type.GetMethod(\"Print\");",
    "PropertyInfo nameProp = type.GetProperty(\"Name\");",
    "PropertyInfo phoneProp = type.GetProperty(\"Phone\");",
    "",
    "// 생성자 매개변수로 인스턴스 생성",
    "object profile = Activator.CreateInstance(type, \"박상현\", \"512-1234\");",
    "methodInfo.Invoke(profile, null); // 박상현, 512-1234",
    "",
    "// 기본 생성자 + 프로퍼티로 값 설정",
    "profile = Activator.CreateInstance(type);",
    "nameProp.SetValue(profile, \"박찬호\", null);",
    "phoneProp.SetValue(profile, \"997-5511\", null);",
    "",
    "Console.WriteLine($\"{nameProp.GetValue(profile)}, {phoneProp.GetValue(profile)}\");",
    "// 박찬호, 997-5511",
    "```",
    "",
    "### Activator.CreateInstance 심화",
    "",
    "```csharp",
    "// 제네릭 버전 (캐스팅 불필요)",
    "Profile p1 = Activator.CreateInstance<Profile>();",
    "",
    "// 생성자 매개변수 전달",
    "object p2 = Activator.CreateInstance(typeof(Profile), \"이름\", \"010-0000-0000\");",
    "",
    "// ConstructorInfo로 직접 호출",
    "ConstructorInfo ctor = typeof(Profile).GetConstructor(",
    "    new Type[] { typeof(string), typeof(string) });",
    "object p3 = ctor.Invoke(new object[] { \"홍길동\", \"010-1111-2222\" });",
    "",
    "// private 생성자도 호출 가능",
    "ConstructorInfo privateCtor = typeof(Singleton).GetConstructor(",
    "    BindingFlags.NonPublic | BindingFlags.Instance,",
    "    null, Type.EmptyTypes, null);",
    "object singleton = privateCtor.Invoke(null);",
    "```",
    "",
    "---",
    "",
    "## 동적 메서드 호출 (MethodInfo.Invoke)",
    "",
    "```csharp",
    "class Calculator",
    "{",
    "    public int Add(int a, int b) => a + b;",
    "    public int Multiply(int a, int b) => a * b;",
    "    private int Secret() => 42;",
    "    public static string Version() => \"1.0\";",
    "}",
    "",
    "Type calcType = typeof(Calculator);",
    "object calc = Activator.CreateInstance(calcType);",
    "",
    "// public 메서드 호출",
    "MethodInfo addMethod = calcType.GetMethod(\"Add\");",
    "object result = addMethod.Invoke(calc, new object[] { 3, 5 });",
    "Console.WriteLine(result); // 8",
    "",
    "// private 메서드 호출",
    "MethodInfo secretMethod = calcType.GetMethod(\"Secret\",",
    "    BindingFlags.NonPublic | BindingFlags.Instance);",
    "Console.WriteLine(secretMethod.Invoke(calc, null)); // 42",
    "",
    "// static 메서드 호출 (인스턴스 대신 null 전달)",
    "MethodInfo versionMethod = calcType.GetMethod(\"Version\");",
    "Console.WriteLine(versionMethod.Invoke(null, null)); // 1.0",
    "",
    "// 이름으로 동적 호출하는 유틸리티",
    "object DynamicCall(object obj, string methodName, params object[] args)",
    "{",
    "    MethodInfo method = obj.GetType().GetMethod(methodName);",
    "    return method?.Invoke(obj, args);",
    "}",
    "",
    "Console.WriteLine(DynamicCall(calc, \"Multiply\", 4, 7)); // 28",
    "```",
    "",
    "---",
    "",
    "## 동적 프로퍼티/필드 접근",
    "",
    "```csharp",
    "class Person",
    "{",
    "    public string Name { get; set; }",
    "    public int Age { get; set; }",
    "    private string _secret = \"비밀\";",
    "}",
    "",
    "Person person = new Person { Name = \"하루\", Age = 25 };",
    "Type personType = typeof(Person);",
    "",
    "// PropertyInfo로 프로퍼티 읽기/쓰기",
    "PropertyInfo nameProp = personType.GetProperty(\"Name\");",
    "Console.WriteLine(nameProp.GetValue(person));  // 하루",
    "nameProp.SetValue(person, \"새이름\");",
    "Console.WriteLine(person.Name);  // 새이름",
    "",
    "// FieldInfo로 private 필드 접근",
    "FieldInfo secretField = personType.GetField(\"_secret\",",
    "    BindingFlags.NonPublic | BindingFlags.Instance);",
    "Console.WriteLine(secretField.GetValue(person));  // 비밀",
    "secretField.SetValue(person, \"변경된 비밀\");",
    "Console.WriteLine(secretField.GetValue(person));  // 변경된 비밀",
    "",
    "// 모든 프로퍼티를 딕셔너리로 변환",
    "var dict = new Dictionary<string, object>();",
    "foreach (var prop in personType.GetProperties())",
    "    dict[prop.Name] = prop.GetValue(person);",
    "",
    "foreach (var kv in dict)",
    "    Console.WriteLine($\"{kv.Key}: {kv.Value}\");",
    "// Name: 새이름",
    "// Age: 25",
    "```",
    "",
    "---",
    "",
    "## 리플렉션으로 어트리뷰트 읽기",
    "",
    "```csharp",
    "// GetCustomAttributes - 모든 어트리뷰트 가져오기",
    "var attributes = typeof(MyClass).GetCustomAttributes(true);",
    "",
    "// 특정 어트리뷰트만 가져오기",
    "var histories = typeof(MyClass).GetCustomAttributes<History>();",
    "",
    "// 어트리뷰트 존재 여부 확인",
    "bool hasHistory = typeof(MyClass).IsDefined(typeof(History), true);",
    "",
    "// 메서드의 어트리뷰트 읽기",
    "MethodInfo method = typeof(ApiController).GetMethod(\"GetUsers\");",
    "RouteAttribute route = method.GetCustomAttribute<RouteAttribute>();",
    "if (route != null)",
    "    Console.WriteLine($\"{route.Method} {route.Path}\");",
    "",
    "// 프로퍼티의 모든 어트리뷰트 순회",
    "foreach (var prop in typeof(User).GetProperties())",
    "{",
    "    Console.Write($\"{prop.Name}: \");",
    "    foreach (var attr in prop.GetCustomAttributes())",
    "        Console.Write($\"[{attr.GetType().Name}] \");",
    "    Console.WriteLine();",
    "}",
    "// Name: [RequiredAttribute] [StringLengthAttribute]",
    "// Age: [RequiredAttribute] [RangeAttribute]",
    "// Bio: [StringLengthAttribute]",
    "```",
    "",
    "---",
    "",
    "## Emit (동적 코드 생성)",
    "",
    "리플렉션의 고급 기능으로, **런타임에 IL 코드를 생성**하여 메서드를 동적으로 만듭니다.",
    "",
    "```csharp",
    "using System.Reflection;",
    "using System.Reflection.Emit;",
    "",
    "// 동적 어셈블리 생성",
    "AssemblyBuilder newAssembly = AssemblyBuilder.DefineDynamicAssembly(",
    "    new AssemblyName(\"CalculatorAssembly\"), AssemblyBuilderAccess.Run);",
    "",
    "// 모듈과 타입 정의",
    "ModuleBuilder newModule = newAssembly.DefineDynamicModule(\"Calculator\");",
    "TypeBuilder newType = newModule.DefineType(\"Sum1To100\");",
    "",
    "// 메서드 정의",
    "MethodBuilder newMethod = newType.DefineMethod(",
    "    \"Calculate\",",
    "    MethodAttributes.Public,",
    "    typeof(int),   // 반환 타입",
    "    new Type[0]);  // 매개변수 없음",
    "",
    "// IL 코드 작성 (1부터 100까지 더하기)",
    "ILGenerator generator = newMethod.GetILGenerator();",
    "generator.Emit(OpCodes.Ldc_I4, 1);",
    "for (int i = 2; i <= 100; i++)",
    "{",
    "    generator.Emit(OpCodes.Ldc_I4, i);",
    "    generator.Emit(OpCodes.Add);",
    "}",
    "generator.Emit(OpCodes.Ret);",
    "",
    "// 타입 완성 후 실행",
    "newType.CreateType();",
    "object sum1To100 = Activator.CreateInstance(newType);",
    "MethodInfo Calculate = sum1To100.GetType().GetMethod(\"Calculate\");",
    "Console.WriteLine(Calculate.Invoke(sum1To100, null)); // 5050",
    "```",
    "",
    "> **Emit 사용 시나리오**: 고성능 직렬화 라이브러리, 프록시 패턴 구현, AOP(관점 지향 프로그래밍) 프레임워크 등에서 활용됩니다. 일반적인 애플리케이션 개발에서는 거의 사용하지 않습니다.",
    "",
    "---",
    "",
    "## Source Generator (리플렉션의 대안)",
    "",
    "**컴파일 타임에 코드를 자동 생성**하는 C# 9.0+의 기능입니다. 리플렉션의 런타임 비용 없이 유사한 효과를 얻을 수 있습니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"소스 코드\"] --> B[\"컴파일러\"]",
    "    C[\"Source Generator\"] --> B",
    "    B --> D[\"생성된 코드 포함된\<br>어셈블리\"]",
    "```",
    "",
    "| 비교 항목 | 리플렉션 | Source Generator |",
    "|----------|---------|-----------------|",
    "| 실행 시점 | 런타임 | 컴파일 타임 |",
    "| 성능 | 느림 (런타임 오버헤드) | 빠름 (일반 코드와 동일) |",
    "| AOT 호환 | 제한적 | 완전 호환 |",
    "| 디버깅 | 어려움 | 생성된 코드 확인 가능 |",
    "| 유연성 | 높음 (런타임 결정) | 컴파일 타임에 결정 |",
    "| 사용 예 | DI 컨테이너, ORM | System.Text.Json, Regex |",
    "",
    "```csharp",
    "// .NET 7+ System.Text.Json에서 Source Generator 활용",
    "[JsonSerializable(typeof(Person))]",
    "internal partial class AppJsonContext : JsonSerializerContext { }",
    "",
    "// 리플렉션 없이 직렬화 (AOT 호환, 고성능)",
    "string json = JsonSerializer.Serialize(person, AppJsonContext.Default.Person);",
    "```",
    "",
    "---",
    "",
    "## 리플렉션 성능 주의사항과 대안",
    "",
    "리플렉션은 강력하지만 **런타임 오버헤드**가 있습니다.",
    "",
    "| 방법 | 상대 속도 | 설명 |",
    "|------|----------|------|",
    "| 직접 호출 | 1x (기준) | `obj.Method()` |",
    "| 캐싱된 delegate | ~1.5x | `MethodInfo` → `Delegate` 변환 후 캐싱 |",
    "| Expression Tree | ~2x | 컴파일된 Expression 사용 |",
    "| 캐싱된 MethodInfo | ~5x | `MethodInfo`를 캐싱하여 재사용 |",
    "| 매번 GetMethod + Invoke | ~100x+ | 매 호출마다 리플렉션 |",
    "",
    "### 최적화 방법",
    "",
    "```csharp",
    "// ❌ 안 좋은 예: 매번 리플렉션",
    "for (int i = 0; i < 100000; i++)",
    "{",
    "    var method = obj.GetType().GetMethod(\"Calculate\");",
    "    method.Invoke(obj, new object[] { i });",
    "}",
    "",
    "// ✅ 좋은 예: MethodInfo 캐싱",
    "var cachedMethod = obj.GetType().GetMethod(\"Calculate\");",
    "for (int i = 0; i < 100000; i++)",
    "{",
    "    cachedMethod.Invoke(obj, new object[] { i });",
    "}",
    "",
    "// ✅ 더 좋은 예: Delegate로 변환",
    "var del = (Func<int, int>)Delegate.CreateDelegate(",
    "    typeof(Func<int, int>), obj, cachedMethod);",
    "for (int i = 0; i < 100000; i++)",
    "{",
    "    del(i); // 직접 호출과 거의 동일한 성능",
    "}",
    "```",
    "",
    "> **Best Practice**: 리플렉션은 초기화 단계에서 한 번 수행하고, 결과를 캐싱하여 이후에는 캐싱된 정보를 사용하세요.",
    "",
    "---",
    "",
    "## 실전 예제: 간단한 DI 컨테이너",
    "",
    "```csharp",
    "class SimpleContainer",
    "{",
    "    private Dictionary<Type, Type> _registrations = new();",
    "",
    "    public void Register<TInterface, TImplementation>()",
    "        where TImplementation : TInterface",
    "    {",
    "        _registrations[typeof(TInterface)] = typeof(TImplementation);",
    "    }",
    "",
    "    public T Resolve<T>() => (T)Resolve(typeof(T));",
    "",
    "    private object Resolve(Type type)",
    "    {",
    "        // 등록된 타입이면 구현 타입으로 교체",
    "        if (_registrations.TryGetValue(type, out Type implType))",
    "            type = implType;",
    "",
    "        // 생성자의 매개변수를 재귀적으로 해결",
    "        var ctor = type.GetConstructors().First();",
    "        var parameters = ctor.GetParameters()",
    "            .Select(p => Resolve(p.ParameterType))",
    "            .ToArray();",
    "",
    "        return Activator.CreateInstance(type, parameters);",
    "    }",
    "}",
    "",
    "// 사용 예",
    "interface ILogger { void Log(string msg); }",
    "class ConsoleLogger : ILogger",
    "{",
    "    public void Log(string msg) => Console.WriteLine(msg);",
    "}",
    "",
    "interface IUserService { void CreateUser(string name); }",
    "class UserService : IUserService",
    "{",
    "    private readonly ILogger _logger;",
    "    public UserService(ILogger logger) => _logger = logger;",
    "    public void CreateUser(string name) => _logger.Log($\"유저 생성: {name}\");",
    "}",
    "",
    "var container = new SimpleContainer();",
    "container.Register<ILogger, ConsoleLogger>();",
    "container.Register<IUserService, UserService>();",
    "",
    "var userService = container.Resolve<IUserService>();",
    "userService.CreateUser(\"하루\"); // 유저 생성: 하루",
    "```",
    "",
    "---",
    "",
    "## 실전 예제: 간단한 ORM 매핑",
    "",
    "```csharp",
    "[AttributeUsage(AttributeTargets.Class)]",
    "class TableAttribute : Attribute",
    "{",
    "    public string Name { get; }",
    "    public TableAttribute(string name) => Name = name;",
    "}",
    "",
    "[AttributeUsage(AttributeTargets.Property)]",
    "class ColumnAttribute : Attribute",
    "{",
    "    public string Name { get; }",
    "    public bool IsPrimaryKey { get; set; }",
    "    public ColumnAttribute(string name) => Name = name;",
    "}",
    "",
    "[Table(\"users\")]",
    "class UserEntity",
    "{",
    "    [Column(\"id\", IsPrimaryKey = true)]",
    "    public int Id { get; set; }",
    "",
    "    [Column(\"user_name\")]",
    "    public string Name { get; set; }",
    "",
    "    [Column(\"email_address\")]",
    "    public string Email { get; set; }",
    "}",
    "",
    "// 리플렉션으로 SQL INSERT 문 자동 생성",
    "static string GenerateInsertSql<T>(T entity)",
    "{",
    "    var type = typeof(T);",
    "    var table = type.GetCustomAttribute<TableAttribute>();",
    "    string tableName = table?.Name ?? type.Name;",
    "",
    "    var columns = new List<string>();",
    "    var values = new List<string>();",
    "",
    "    foreach (var prop in type.GetProperties())",
    "    {",
    "        var col = prop.GetCustomAttribute<ColumnAttribute>();",
    "        if (col == null || col.IsPrimaryKey) continue;",
    "",
    "        columns.Add(col.Name);",
    "        object val = prop.GetValue(entity);",
    "        values.Add(val is string ? $\"'{val}'\" : val.ToString());",
    "    }",
    "",
    "    return $\"INSERT INTO {tableName} ({string.Join(\", \", columns)}) \" +",
    "           $\"VALUES ({string.Join(\", \", values)})\";",
    "}",
    "",
    "var user = new UserEntity { Id = 1, Name = \"하루\", Email = \"haru@example.com\" };",
    "Console.WriteLine(GenerateInsertSql(user));",
    "// INSERT INTO users (user_name, email_address) VALUES ('하루', 'haru@example.com')",
    "```",
    "",
    "---",
    "",
    "### 리플렉션 활용 정리",
    "",
    "| 기능 | 클래스/메서드 | 설명 |",
    "|------|--------------|------|",
    "| 타입 정보 | `typeof()`, `GetType()` | 타입 메타데이터 조회 |",
    "| 필드 조회 | `GetFields()` | public/private 필드 목록 |",
    "| 메서드 조회 | `GetMethods()` | 메서드 이름, 반환 타입, 매개변수 |",
    "| 프로퍼티 조회 | `GetProperties()` | 프로퍼티 이름, 타입 |",
    "| 동적 생성 | `Activator.CreateInstance()` | 런타임 객체 생성 |",
    "| 동적 호출 | `MethodInfo.Invoke()` | 런타임 메서드 실행 |",
    "| 값 설정 | `PropertyInfo.SetValue()` | 런타임 프로퍼티 변경 |",
    "| 필드 접근 | `FieldInfo.GetValue/SetValue()` | 런타임 필드 읽기/쓰기 |",
    "| 어트리뷰트 | `GetCustomAttributes()` | 메타데이터 조회 |",
    "| 코드 생성 | `Emit` | IL 코드 동적 생성 |",
    "| 컴파일 타임 생성 | Source Generator | 리플렉션 없는 코드 생성 |",
    "",
    "---",
    "",
    "### 요약",
    "어트리뷰트는 코드에 메타데이터를 선언적으로 부착하고(`[Obsolete]`, `[Conditional]`, 사용자 정의), 리플렉션은 런타임에 `Type`, `FieldInfo`, `MethodInfo`, `PropertyInfo` 등으로 타입 정보를 조회·조작합니다. `Activator`로 동적 인스턴스를 생성하고, `MethodInfo.Invoke()`로 메서드를 동적 호출하며, `Emit`으로 IL 코드를 직접 생성할 수도 있습니다. 성능이 중요한 경우 리플렉션 결과를 캐싱하거나 Source Generator를 대안으로 고려하세요. DI 컨테이너, ORM, 유효성 검사 등 프레임워크 수준의 기능을 구현할 때 리플렉션과 어트리뷰트의 조합이 핵심적으로 활용됩니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
