<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-basics-types-operators",
  title: "C# 기초: 데이터 타입과 연산자",
  date: "2026-02-25",
  summary: "C# 프로그램 구조, 정수/실수/문자열/bool/enum/nullable 타입, 박싱/언박싱, 형변환, 문자열 보간, 산술/비교/논리/비트/null 병합 연산자를 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","dotnet","types","operators","string","enum","nullable","basics"],
  content: [
    "## 한 줄 요약",
    "C#은 **강력한 정적 타입 언어**로, 값 타입(int, float, struct)과 참조 타입(string, class, object)을 구분하며, Nullable(`?`)과 문자열 보간(`$\"\"`)을 지원합니다.",
    "",
    "---",
    "",
    "## .NET / CLR / C# 관계",
    "",
    "C#은 .NET 플랫폼 위에서 실행됩니다. 소스 코드는 중간 언어(IL)로 컴파일된 후, CLR이 실행 시점에 기계어로 변환합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"C# 소스 코드\<br>(.cs)\"] -->|Roslyn 컴파일러| B[\"IL 중간 언어\<br>(.dll / .exe)\"]",
    "    B -->|CLR 로드| C[\"JIT 컴파일러\"]",
    "    C -->|실행 시점 변환| D[\"네이티브 기계어\"]",
    "    D --> E[\"OS에서 실행\"]",
    "",
    "    style A fill:#9b59b6,color:#fff",
    "    style B fill:#3498db,color:#fff",
    "    style C fill:#e67e22,color:#fff",
    "    style D fill:#2ecc71,color:#fff",
    "    style E fill:#1abc9c,color:#fff",
    "```",
    "",
    "| 구성 요소 | 역할 |",
    "|-----------|------|",
    "| **C#** | 프로그래밍 언어 (문법, 키워드) |",
    "| **.NET SDK** | 컴파일러·라이브러리·도구 모음 |",
    "| **IL (Intermediate Language)** | 플랫폼 독립적인 중간 코드 |",
    "| **CLR (Common Language Runtime)** | IL을 실행하는 런타임 (GC, 타입 안전성, JIT 등) |",
    "| **BCL (Base Class Library)** | System.*, Collections, IO 등 기본 라이브러리 |",
    "",
    "> **핵심 포인트:** C#, F#, VB.NET 등 여러 언어가 같은 IL로 컴파일되므로, .NET 위에서 서로 호환됩니다.",
    "",
    "---",
    "",
    "## 프로그램 구조",
    "",
    "```csharp",
    "using System;",
    "using static System.Console;",
    "",
    "namespace Hello",
    "{",
    "    class MainApp",
    "    {",
    "        static void Main(string[] args)",
    "        {",
    "            if (args.Length == 0)",
    "            {",
    "                Console.WriteLine(\"사용법 : Hello.exe <이름>\");",
    "                return;",
    "            }",
    "            WriteLine(\"Hello, {0}!\", args[0]);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "| 요소 | 설명 |",
    "|------|------|",
    "| `using System` | 네임스페이스 가져오기 |",
    "| `namespace` | 코드를 논리적으로 그룹화 |",
    "| `class` | 클래스 정의 |",
    "| `static void Main` | 프로그램 진입점 |",
    "| `string[] args` | 명령줄 인자 |",
    "",
    "> C# 9.0부터 **최상위 문(Top-level statements)**으로 `Main` 메서드 없이 바로 코드를 작성할 수 있습니다.",
    "",
    "```csharp",
    "// C# 9.0+ 최상위 문",
    "Console.WriteLine(\"Hello, World!\");",
    "```",
    "",
    "---",
    "",
    "## C# 타입 체계 전체 분류",
    "",
    "```mermaid",
    "graph TD",
    "    A[\"C# 타입\"] --> B[\"값 타입\<br>(Value Type)\"]",
    "    A --> C[\"참조 타입\<br>(Reference Type)\"]",
    "",
    "    B --> D[\"정수: byte, short,\<br>int, long + unsigned\"]",
    "    B --> E[\"실수: float,\<br>double, decimal\"]",
    "    B --> F[\"bool, char\"]",
    "    B --> G[\"struct\"]",
    "    B --> H[\"enum\"]",
    "",
    "    C --> I[\"string\"]",
    "    C --> J[\"class\"]",
    "    C --> K[\"interface\"]",
    "    C --> L[\"delegate\"]",
    "    C --> M[\"object\"]",
    "    C --> N[\"dynamic\"]",
    "    C --> O[\"배열 (T[])\"]",
    "",
    "    style A fill:#e74c3c,color:#fff",
    "    style B fill:#f39c12,color:#fff",
    "    style C fill:#3498db,color:#fff",
    "```",
    "",
    "---",
    "",
    "## 값 타입 vs 참조 타입",
    "",
    "```mermaid",
    "graph LR",
    "    subgraph 스택[\"스택 (Stack)\"]",
    "        direction TB",
    "        S1[\"int x = 42\"]",
    "        S2[\"참조 변수 obj\"]",
    "    end",
    "",
    "    subgraph 힙[\"힙 (Heap)\"]",
    "        direction TB",
    "        H1[\"new MyClass()\<br>실제 객체 데이터\"]",
    "    end",
    "",
    "    S2 -.->|참조| H1",
    "",
    "    style 스택 fill:#ffeaa7",
    "    style 힙 fill:#dfe6e9",
    "```",
    "",
    "| 구분 | 값 타입 (Value Type) | 참조 타입 (Reference Type) |",
    "|------|---------------------|--------------------------|",
    "| **저장 위치** | 스택(Stack) | 힙(Heap), 스택에 참조 저장 |",
    "| **대입 동작** | 값 복사 (독립적) | 참조 복사 (같은 객체 공유) |",
    "| **기본값** | 0, false 등 | null |",
    "| **예시** | int, float, bool, struct, enum | string, class, object, 배열 |",
    "| **상속** | System.ValueType | System.Object |",
    "| **GC 대상** | 아님 (스택 자동 해제) | GC가 수거 |",
    "",
    "```csharp",
    "// 값 타입: 값이 복사됨",
    "int a = 10;",
    "int b = a;",
    "b = 20;",
    "Console.WriteLine(a); // 10 (영향 없음)",
    "",
    "// 참조 타입: 같은 객체를 가리킴",
    "int[] arr1 = { 1, 2, 3 };",
    "int[] arr2 = arr1;",
    "arr2[0] = 99;",
    "Console.WriteLine(arr1[0]); // 99 (같은 배열 참조)",
    "```",
    "",
    "---",
    "",
    "## 정수 타입",
    "",
    "C#은 8가지 정수 타입을 제공하며, 각각 부호(signed/unsigned)와 크기가 다릅니다.",
    "",
    "```csharp",
    "sbyte a = -10;       // -128 ~ 127 (8비트)",
    "byte  b = 40;        // 0 ~ 255",
    "short  c = -30000;   // -32,768 ~ 32,767 (16비트)",
    "ushort d = 60000;    // 0 ~ 65,535",
    "int  e = -1000_0000; // -21억 ~ 21억 (32비트)",
    "uint f = 3_0000_0000;// 0 ~ 42억",
    "long g = -5000_0000_0000;  // 64비트",
    "ulong h = 200_0000_0000_0000_0000;",
    "",
    "Console.WriteLine($\"e={e}, f={f}\");",
    "Console.WriteLine($\"g={g}, h={h}\");",
    "```",
    "",
    "> `_`(언더스코어)는 자릿수 구분자로, 가독성을 위해 사용합니다.",
    "",
    "| 타입 | 크기 | 범위 | 주요 용도 |",
    "|------|------|------|-----------|",
    "| `byte` | 8비트 | 0 ~ 255 | 바이너리 데이터, 색상값(RGB) |",
    "| `sbyte` | 8비트 | -128 ~ 127 | 거의 사용하지 않음 |",
    "| `short` | 16비트 | -32,768 ~ 32,767 | 메모리 절약이 중요할 때 |",
    "| `ushort` | 16비트 | 0 ~ 65,535 | 포트 번호, 유니코드 등 |",
    "| `int` | 32비트 | ±21억 | **가장 일반적**, 기본 정수 타입 |",
    "| `uint` | 32비트 | 0 ~ 42억 | 음수 불필요 시 범위 확장 |",
    "| `long` | 64비트 | ±922경 | 타임스탬프, 파일 크기 |",
    "| `ulong` | 64비트 | 0 ~ 1844경 | 매우 큰 양수 값 |",
    "",
    "> **💡 Tip:** 특별한 이유가 없다면 **`int`를 기본으로** 사용하세요. 성능 최적화가 필요한 경우에만 더 작은 타입을 고려합니다.",
    "",
    "---",
    "",
    "## 실수 타입",
    "",
    "```csharp",
    "float  a = 3.14f;    // 32비트, 접미사 f 필수",
    "double b = 3.141592; // 64비트 (기본값)",
    "decimal c = 3.14m;   // 128비트, 금융 계산에 적합",
    "",
    "Console.WriteLine($\"float: {a}, double: {b}, decimal: {c}\");",
    "```",
    "",
    "| 타입 | 크기 | 정밀도 | 접미사 | 용도 |",
    "|------|------|--------|--------|------|",
    "| `float` | 32비트 | ~7자리 | `f` | 게임, 3D 그래픽 |",
    "| `double` | 64비트 | ~15자리 | 없음 (기본) | 과학 계산, 일반 용도 |",
    "| `decimal` | 128비트 | ~28자리 | `m` | **금융, 회계** 계산 |",
    "",
    "### float vs decimal 정밀도 차이 (금융 계산)",
    "",
    "```csharp",
    "// float/double은 이진 부동소수점 → 10진수 정밀도 손실",
    "double price = 0.1 + 0.2;",
    "Console.WriteLine(price);          // 0.30000000000000004",
    "Console.WriteLine(price == 0.3);   // False!",
    "",
    "// decimal은 10진 부동소수점 → 정확한 10진수 표현",
    "decimal dPrice = 0.1m + 0.2m;",
    "Console.WriteLine(dPrice);         // 0.3",
    "Console.WriteLine(dPrice == 0.3m); // True",
    "",
    "// 실무 예시: 세금 계산",
    "decimal subtotal = 19999.99m;",
    "decimal tax = subtotal * 0.1m;",
    "decimal total = subtotal + tax;",
    "Console.WriteLine($\"소계: {subtotal:C}, 세금: {tax:C}, 합계: {total:C}\");",
    "```",
    "",
    "> **⚠️ 주의:** 금융·회계 시스템에서는 반드시 `decimal`을 사용하세요. `float`/`double`의 미세한 오차가 누적되면 큰 차이가 발생할 수 있습니다.",
    "",
    "---",
    "",
    "## 문자와 문자열",
    "",
    "```csharp",
    "char c = 'A';",
    "string s1 = \"Hello, C#!\";",
    "",
    "// 문자열 보간 (String Interpolation)",
    "string name = \"haru\";",
    "int age = 25;",
    "Console.WriteLine($\"{name}은(는) {age}살입니다.\");",
    "",
    "// 문자열 포맷",
    "Console.WriteLine(\"이름: {0}, 나이: {1}\", name, age);",
    "",
    "// 문자열 메서드",
    "string str = \"Hello, World!\";",
    "Console.WriteLine(str.Length);              // 13",
    "Console.WriteLine(str.ToUpper());           // HELLO, WORLD!",
    "Console.WriteLine(str.ToLower());           // hello, world!",
    "Console.WriteLine(str.Substring(7));        // World!",
    "Console.WriteLine(str.Contains(\"World\"));   // True",
    "Console.WriteLine(str.Replace(\"World\", \"C#\")); // Hello, C#!",
    "Console.WriteLine(str.IndexOf(\"World\"));    // 7",
    "Console.WriteLine(str.Split(','));           // [\"Hello\", \" World!\"]",
    "```",
    "",
    "### Verbatim String (@) & Raw String Literal",
    "",
    "```csharp",
    "// 일반 문자열: 이스케이프 필요",
    "string path1 = \"C:\\\\Users\\\\haru\\\\Documents\";",
    "",
    "// Verbatim String (@): 이스케이프 불필요",
    "string path2 = @\"C:\\Users\\haru\\Documents\";",
    "",
    "// Verbatim + 보간 결합",
    "string user = \"haru\";",
    "string path3 = $@\"C:\\Users\\{user}\\Documents\";",
    "",
    "// Raw String Literal (C# 11+): 큰따옴표도 이스케이프 불필요",
    "string json = \"\"\"",
    "    {",
    "        \"name\": \"haru\",",
    "        \"age\": 25",
    "    }",
    "    \"\"\";",
    "```",
    "",
    "### string vs StringBuilder 성능",
    "",
    "`string`은 **불변(immutable)** 타입입니다. 문자열을 수정할 때마다 새 객체가 생성되므로, 반복적인 문자열 연결에는 `StringBuilder`가 훨씬 효율적입니다.",
    "",
    "```csharp",
    "using System.Text;",
    "using System.Diagnostics;",
    "",
    "// 나쁜 예: string 연결 (O(n²) 성능)",
    "string result = \"\";",
    "for (int i = 0; i < 10000; i++)",
    "    result += i.ToString(); // 매번 새 string 객체 생성",
    "",
    "// 좋은 예: StringBuilder (O(n) 성능)",
    "var sb = new StringBuilder();",
    "for (int i = 0; i < 10000; i++)",
    "    sb.Append(i);",
    "string result2 = sb.ToString();",
    "```",
    "",
    "| 방식 | 10,000회 연결 시 | 메모리 할당 |",
    "|------|-----------------|-------------|",
    "| `string +=` | ~수백 ms | ~50,000개 객체 |",
    "| `StringBuilder` | ~1 ms | 수 개 버퍼 |",
    "",
    "---",
    "",
    "## bool 타입",
    "",
    "```csharp",
    "bool isTrue = true;",
    "bool isFalse = false;",
    "Console.WriteLine(isTrue);  // True",
    "Console.WriteLine(isFalse); // False",
    "```",
    "",
    "---",
    "",
    "## enum (열거형)",
    "",
    "```csharp",
    "enum DialogResult",
    "{",
    "    YES,    // 0",
    "    NO,     // 1",
    "    CANCEL  // 2",
    "}",
    "",
    "enum Color : byte",
    "{",
    "    Red = 0,",
    "    Green = 1,",
    "    Blue = 2",
    "}",
    "",
    "DialogResult result = DialogResult.YES;",
    "Console.WriteLine(result);        // YES",
    "Console.WriteLine((int)result);   // 0",
    "```",
    "",
    "### [Flags] 어트리뷰트",
    "",
    "`[Flags]`를 사용하면 enum 값을 **비트 플래그**로 조합할 수 있습니다.",
    "",
    "```csharp",
    "[Flags]",
    "enum Permission",
    "{",
    "    None    = 0,      // 0000",
    "    Read    = 1,      // 0001",
    "    Write   = 1 << 1, // 0010",
    "    Execute = 1 << 2, // 0100",
    "    Delete  = 1 << 3, // 1000",
    "    All     = Read | Write | Execute | Delete // 1111",
    "}",
    "",
    "Permission userPerm = Permission.Read | Permission.Write;",
    "Console.WriteLine(userPerm);                          // Read, Write",
    "Console.WriteLine(userPerm.HasFlag(Permission.Read)); // True",
    "Console.WriteLine(userPerm.HasFlag(Permission.Delete)); // False",
    "",
    "// 권한 추가/제거",
    "userPerm |= Permission.Execute;  // Execute 추가",
    "userPerm &= ~Permission.Write;   // Write 제거",
    "Console.WriteLine(userPerm);     // Read, Execute",
    "```",
    "",
    "### enum 유틸리티 메서드",
    "",
    "```csharp",
    "// 문자열 → enum 변환",
    "Color color = Enum.Parse<Color>(\"Green\");",
    "Console.WriteLine(color); // Green",
    "",
    "// 안전한 변환 (실패 시 false 반환)",
    "if (Enum.TryParse<Color>(\"Yellow\", out Color parsed))",
    "    Console.WriteLine(parsed);",
    "else",
    "    Console.WriteLine(\"유효하지 않은 색상\"); // 출력",
    "",
    "// 모든 값 순회",
    "foreach (Color c in Enum.GetValues<Color>())",
    "    Console.WriteLine($\"{c} = {(int)c}\");",
    "",
    "// 이름 목록",
    "string[] names = Enum.GetNames<Color>();",
    "Console.WriteLine(string.Join(\", \", names)); // Red, Green, Blue",
    "```",
    "",
    "---",
    "",
    "## Nullable 타입",
    "",
    "값 타입에 `null`을 허용합니다.",
    "",
    "```csharp",
    "int? a = null;",
    "",
    "Console.WriteLine(a.HasValue); // False",
    "Console.WriteLine(a != null);  // False",
    "",
    "a = 3;",
    "",
    "Console.WriteLine(a.HasValue); // True",
    "Console.WriteLine(a.Value);    // 3",
    "```",
    "",
    "### Nullable Reference Type (C# 8.0+)",
    "",
    "C# 8.0부터 참조 타입에도 null 가능 여부를 명시할 수 있습니다. 프로젝트 설정에서 `<Nullable>enable</Nullable>`을 켜면 활성화됩니다.",
    "",
    "```csharp",
    "#nullable enable",
    "",
    "string name = \"haru\";     // non-nullable: null 할당 시 경고",
    "string? nickname = null;  // nullable: null 허용",
    "",
    "// 컴파일러 경고 발생",
    "// string s = null; // CS8600: null 리터럴을 non-nullable에 할당",
    "",
    "Console.WriteLine(nickname?.ToUpper()); // null이면 null 반환",
    "Console.WriteLine(nickname?.Length ?? 0); // null이면 0",
    "```",
    "",
    "### null 관련 패턴 모음",
    "",
    "```csharp",
    "string? text = GetTextOrNull();",
    "",
    "// ?. (null 조건부 연산자): null이면 호출하지 않음",
    "int? length = text?.Length;",
    "",
    "// ?? (null 병합 연산자): null이면 오른쪽 값 사용",
    "string result = text ?? \"기본값\";",
    "",
    "// ??= (null 병합 할당): null이면 값 할당",
    "text ??= \"기본값\";",
    "",
    "// is null / is not null (패턴 매칭으로 null 확인)",
    "if (text is null)",
    "    Console.WriteLine(\"null입니다\");",
    "",
    "if (text is not null)",
    "    Console.WriteLine($\"값: {text}\");",
    "",
    "// ! (null-forgiving 연산자): 컴파일러에게 null 아님을 보증",
    "string definitelyNotNull = text!;",
    "```",
    "",
    "> **Best Practice:** `== null` 대신 `is null`을 사용하세요. `==` 연산자는 오버로딩될 수 있지만, `is null`은 항상 참조 비교를 수행합니다.",
    "",
    "---",
    "",
    "## 박싱 / 언박싱",
    "",
    "값 타입 → 참조 타입(object)으로 변환하는 것이 **박싱**, 반대가 **언박싱**입니다.",
    "",
    "```csharp",
    "int a = 123;",
    "object obj = a;           // 박싱 (값 → 힙에 복사)",
    "int b = (int)obj;         // 언박싱 (힙 → 값)",
    "",
    "Console.WriteLine(b);     // 123",
    "```",
    "",
    "### 박싱/언박싱의 성능 문제",
    "",
    "```csharp",
    "// 나쁜 예: ArrayList는 object를 저장 → 매번 박싱/언박싱",
    "var list = new System.Collections.ArrayList();",
    "for (int i = 0; i < 100000; i++)",
    "    list.Add(i);  // int → object 박싱 발생!",
    "",
    "int sum = 0;",
    "foreach (object item in list)",
    "    sum += (int)item;  // object → int 언박싱 발생!",
    "",
    "// 좋은 예: 제네릭 List<T>는 박싱/언박싱 없음",
    "var genericList = new List<int>();",
    "for (int i = 0; i < 100000; i++)",
    "    genericList.Add(i);  // 박싱 없음!",
    "",
    "int sum2 = 0;",
    "foreach (int item in genericList)",
    "    sum2 += item;  // 언박싱 없음!",
    "```",
    "",
    "> **Best Practice:** `ArrayList`, `Hashtable` 등 비제네릭 컬렉션 대신 `List<T>`, `Dictionary<TKey, TValue>` 등 **제네릭 컬렉션**을 사용하여 박싱/언박싱을 방지하세요.",
    "",
    "---",
    "",
    "## 형변환",
    "",
    "```csharp",
    "// 암시적 변환 (작은 → 큰 타입)",
    "int num = 100;",
    "long bigNum = num;        // int → long 자동 변환",
    "float f = num;            // int → float 자동 변환",
    "",
    "// 명시적 변환 (캐스팅)",
    "double d = 3.14;",
    "int i = (int)d;           // 3 (소수점 버림)",
    "",
    "// 문자열 ↔ 숫자 변환",
    "string s = \"123\";",
    "int n = int.Parse(s);           // 문자열 → 정수",
    "int n2 = Convert.ToInt32(s);    // 문자열 → 정수",
    "string s2 = n.ToString();       // 정수 → 문자열",
    "```",
    "",
    "### is 패턴과 as 연산자",
    "",
    "```csharp",
    "object obj = \"Hello\";",
    "",
    "// is: 타입 검사 (bool 반환)",
    "if (obj is string str)",
    "{",
    "    Console.WriteLine($\"문자열: {str}, 길이: {str.Length}\");",
    "}",
    "",
    "// as: 타입 변환 시도 (실패 시 null, 참조 타입만 가능)",
    "string? result = obj as string;",
    "if (result != null)",
    "    Console.WriteLine(result);",
    "",
    "// is not 패턴 (C# 9.0+)",
    "if (obj is not int)",
    "    Console.WriteLine(\"정수가 아닙니다.\");",
    "```",
    "",
    "### Convert 클래스",
    "",
    "```csharp",
    "// Convert는 다양한 타입 간 변환을 제공합니다",
    "int a = Convert.ToInt32(\"42\");",
    "double b = Convert.ToDouble(\"3.14\");",
    "bool c = Convert.ToBoolean(1);      // True",
    "string d = Convert.ToString(255, 2); // \"11111111\" (2진수 문자열)",
    "string e = Convert.ToString(255, 16); // \"ff\" (16진수 문자열)",
    "",
    "// Convert vs Parse 차이: null 처리",
    "string? nullStr = null;",
    "// int.Parse(nullStr);            // ArgumentNullException!",
    "int safe = Convert.ToInt32(nullStr); // 0 (기본값 반환)",
    "```",
    "",
    "| 방법 | null 입력 | 잘못된 형식 | 용도 |",
    "|------|----------|------------|------|",
    "| `int.Parse()` | 예외 발생 | 예외 발생 | 확실한 변환 |",
    "| `int.TryParse()` | false 반환 | false 반환 | 안전한 변환 |",
    "| `Convert.ToInt32()` | 0 반환 | 예외 발생 | null 허용 변환 |",
    "",
    "---",
    "",
    "## 연산자",
    "",
    "### 산술 연산자",
    "```csharp",
    "int a = 10, b = 3;",
    "Console.WriteLine(a + b);  // 13",
    "Console.WriteLine(a - b);  // 7",
    "Console.WriteLine(a * b);  // 30",
    "Console.WriteLine(a / b);  // 3 (정수 나눗셈)",
    "Console.WriteLine(a % b);  // 1 (나머지)",
    "```",
    "",
    "### 증감 연산자",
    "```csharp",
    "int x = 5;",
    "Console.WriteLine(x++); // 5 (사용 후 증가)",
    "Console.WriteLine(++x); // 7 (증가 후 사용)",
    "Console.WriteLine(x--); // 7 (사용 후 감소)",
    "Console.WriteLine(--x); // 5 (감소 후 사용)",
    "```",
    "",
    "### 비교 / 논리 연산자",
    "```csharp",
    "bool result1 = (3 > 1) && (5 > 2);  // true (AND)",
    "bool result2 = (3 > 1) || (5 < 2);  // true (OR)",
    "bool result3 = !(3 > 1);            // false (NOT)",
    "```",
    "",
    "### 비트 연산자",
    "```csharp",
    "int a = 0b_1010;  // 10",
    "int b = 0b_1100;  // 12",
    "",
    "Console.WriteLine(a & b);   // 0b_1000 = 8  (AND)",
    "Console.WriteLine(a | b);   // 0b_1110 = 14 (OR)",
    "Console.WriteLine(a ^ b);   // 0b_0110 = 6  (XOR)",
    "Console.WriteLine(~a);      // 비트 반전",
    "Console.WriteLine(a << 1);  // 0b_10100 = 20 (왼쪽 시프트)",
    "Console.WriteLine(a >> 1);  // 0b_0101 = 5   (오른쪽 시프트)",
    "```",
    "",
    "### 비트 연산 실전 활용: 권한 관리",
    "",
    "```csharp",
    "[Flags]",
    "enum FileAccess",
    "{",
    "    None  = 0,",
    "    Read  = 1,     // 001",
    "    Write = 2,     // 010",
    "    Execute = 4    // 100",
    "}",
    "",
    "FileAccess perm = FileAccess.Read | FileAccess.Write; // 011",
    "",
    "// 특정 권한 확인 (AND)",
    "bool canRead = (perm & FileAccess.Read) != 0;   // true",
    "bool canExec = (perm & FileAccess.Execute) != 0; // false",
    "",
    "// 권한 추가 (OR)",
    "perm |= FileAccess.Execute;  // 111",
    "",
    "// 권한 제거 (AND + NOT)",
    "perm &= ~FileAccess.Write;   // 101",
    "",
    "// 권한 토글 (XOR)",
    "perm ^= FileAccess.Read;     // 100",
    "",
    "Console.WriteLine(perm);     // Execute",
    "```",
    "",
    "### 조건부 연산자 (삼항)",
    "```csharp",
    "int score = 85;",
    "string grade = (score >= 90) ? \"A\" : (score >= 80) ? \"B\" : \"C\";",
    "Console.WriteLine(grade); // B",
    "```",
    "",
    "### null 병합 연산자",
    "```csharp",
    "// ?? : null이면 오른쪽 값 사용",
    "string name = null;",
    "Console.WriteLine(name ?? \"이름 없음\"); // 이름 없음",
    "",
    "// ??= : null이면 값 할당",
    "name ??= \"기본값\";",
    "Console.WriteLine(name); // 기본값",
    "",
    "// ?. : null이면 호출하지 않음",
    "string str = null;",
    "Console.WriteLine(str?.Length); // (빈 출력, 예외 없음)",
    "```",
    "",
    "### 연산자 오버로딩",
    "",
    "사용자 정의 타입에서 연산자의 동작을 재정의할 수 있습니다.",
    "",
    "```csharp",
    "struct Vector2",
    "{",
    "    public float X, Y;",
    "",
    "    public Vector2(float x, float y) { X = x; Y = y; }",
    "",
    "    public static Vector2 operator +(Vector2 a, Vector2 b)",
    "        => new Vector2(a.X + b.X, a.Y + b.Y);",
    "",
    "    public static Vector2 operator -(Vector2 a, Vector2 b)",
    "        => new Vector2(a.X - b.X, a.Y - b.Y);",
    "",
    "    public static Vector2 operator *(Vector2 v, float scalar)",
    "        => new Vector2(v.X * scalar, v.Y * scalar);",
    "",
    "    public static bool operator ==(Vector2 a, Vector2 b)",
    "        => a.X == b.X && a.Y == b.Y;",
    "",
    "    public static bool operator !=(Vector2 a, Vector2 b)",
    "        => !(a == b);",
    "",
    "    public override string ToString() => $\"({X}, {Y})\";",
    "}",
    "",
    "var v1 = new Vector2(1, 2);",
    "var v2 = new Vector2(3, 4);",
    "Console.WriteLine(v1 + v2);     // (4, 6)",
    "Console.WriteLine(v1 * 3);      // (3, 6)",
    "Console.WriteLine(v1 == v2);    // False",
    "```",
    "",
    "> **주의:** `==`를 오버로딩하면 반드시 `!=`도 함께 오버로딩해야 하며, `Equals()`와 `GetHashCode()`도 재정의하는 것이 권장됩니다.",
    "",
    "---",
    "",
    "## var (암시적 타입)",
    "",
    "```csharp",
    "var i = 10;           // int로 추론",
    "var d = 3.14;         // double로 추론",
    "var s = \"hello\";      // string으로 추론",
    "var list = new List<int>(); // List<int>로 추론",
    "",
    "// var는 반드시 초기화와 함께 사용해야 합니다",
    "// var x; // 컴파일 에러!",
    "```",
    "",
    "---",
    "",
    "## Best Practices 정리",
    "",
    "| 상황 | 권장 사항 |",
    "|------|----------|",
    "| 일반 정수 | `int` 사용 |",
    "| 금융 계산 | 반드시 `decimal` |",
    "| 문자열 반복 연결 | `StringBuilder` 사용 |",
    "| 컬렉션 | 제네릭(`List<T>`) 사용으로 박싱 방지 |",
    "| null 검사 | `is null` 패턴 사용 |",
    "| 형변환 | 안전한 `TryParse` 또는 `is` 패턴 |",
    "| 비트 플래그 | `[Flags]` enum 활용 |",
    "| 경로·JSON 문자열 | Verbatim(@) 또는 Raw String 사용 |",
    "",
    "---",
    "",
    "### 요약",
    "C#은 정수(`int`, `long`), 실수(`float`, `double`, `decimal`), 문자열(`string`), 논리(`bool`), 열거형(`enum`), Nullable(`?`) 등 풍부한 데이터 타입을 제공합니다. `.NET` 플랫폼 위에서 값 타입과 참조 타입을 명확히 구분하며, `[Flags]` enum, Nullable Reference Type, 연산자 오버로딩 등 고급 기능도 지원합니다. 문자열 보간(`$\"\"`)과 `??`/`?.` 연산자로 null을 안전하게 처리하고, `StringBuilder`와 제네릭 컬렉션으로 성능을 최적화할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
