<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-class-oop",
  title: "C# 클래스와 객체지향",
  date: "2026-02-25",
  summary: "클래스, 생성자/소멸자, 상속, 오버라이딩, 추상 클래스, 인터페이스, 구조체, 튜플, 확장 메서드 등 C# 객체지향 프로그래밍의 핵심을 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","class","oop","inheritance","interface","abstract","struct","tuple"],
  content: [
    "## 한 줄 요약",
    "C#은 **클래스·상속·다형성·인터페이스** 기반의 완전한 객체지향 언어이며, `struct`, `record`, `튜플`, `확장 메서드`로 유연성을 더합니다.",
    "",
    "---",
    "",
    "## OOP 4대 원칙",
    "",
    "```mermaid",
    "graph TD",
    "    OOP[\"객체지향 프로그래밍\<br>(OOP)\"] --> E[\"캡슐화\<br>Encapsulation\"]",
    "    OOP --> I[\"상속\<br>Inheritance\"]",
    "    OOP --> P[\"다형성\<br>Polymorphism\"]",
    "    OOP --> A[\"추상화\<br>Abstraction\"]",
    "",
    "    E --> E1[\"접근 제한자로\<br>내부 상태 보호\"]",
    "    I --> I1[\"코드 재사용\<br>계층 구조\"]",
    "    P --> P1[\"같은 인터페이스,\<br>다른 동작\"]",
    "    A --> A1[\"복잡성 숨기고\<br>핵심만 노출\"]",
    "",
    "    style OOP fill:#e74c3c,color:#fff",
    "    style E fill:#3498db,color:#fff",
    "    style I fill:#2ecc71,color:#fff",
    "    style P fill:#f39c12,color:#fff",
    "    style A fill:#9b59b6,color:#fff",
    "```",
    "",
    "| 원칙 | 설명 | C# 구현 |",
    "|------|------|---------|",
    "| **캡슐화** | 데이터와 동작을 묶고, 외부 접근 제한 | `private`, 프로퍼티(get/set) |",
    "| **상속** | 기존 클래스를 확장하여 코드 재사용 | `: BaseClass` |",
    "| **다형성** | 같은 메서드 호출이 타입에 따라 다르게 동작 | `virtual`/`override`, 인터페이스 |",
    "| **추상화** | 구현 세부사항을 숨기고 핵심 기능만 노출 | `abstract class`, `interface` |",
    "",
    "---",
    "",
    "## 클래스 기본",
    "",
    "```csharp",
    "class Cat",
    "{",
    "    public string Name;",
    "    public string Color;",
    "",
    "    public void Meow()",
    "    {",
    "        Console.WriteLine($\"{Name} : 야옹\");",
    "    }",
    "}",
    "",
    "Cat kitty = new Cat();",
    "kitty.Name = \"키티\";",
    "kitty.Color = \"하얀색\";",
    "kitty.Meow(); // 키티 : 야옹",
    "```",
    "",
    "---",
    "",
    "## 생성자와 소멸자",
    "",
    "```csharp",
    "class Cat",
    "{",
    "    public string Name;",
    "    public string Color;",
    "",
    "    // 기본 생성자",
    "    public Cat()",
    "    {",
    "        Name = \"\";",
    "        Color = \"\";",
    "    }",
    "",
    "    // 매개변수가 있는 생성자",
    "    public Cat(string _Name, string _Color)",
    "    {",
    "        Name = _Name;",
    "        Color = _Color;",
    "    }",
    "",
    "    // 소멸자 (가비지 컬렉터에 의해 호출)",
    "    ~Cat()",
    "    {",
    "        Console.WriteLine($\"{Name} : 잘가\");",
    "    }",
    "",
    "    public void Meow()",
    "    {",
    "        Console.WriteLine($\"{Name} : 야옹\");",
    "    }",
    "}",
    "",
    "Cat kitty = new Cat(\"키티\", \"하얀색\");",
    "kitty.Meow(); // 키티 : 야옹",
    "```",
    "",
    "### 생성자 체이닝 (this, base)",
    "",
    "```csharp",
    "class MyClass",
    "{",
    "    int a, b, c;",
    "",
    "    public MyClass()",
    "    {",
    "        this.a = 5425;",
    "    }",
    "",
    "    public MyClass(int b) : this()",
    "    {",
    "        this.b = b;",
    "    }",
    "",
    "    public MyClass(int b, int c) : this(b)",
    "    {",
    "        this.c = c;",
    "    }",
    "}",
    "",
    "// new MyClass(1, 2) → MyClass() → MyClass(1) → MyClass(1, 2) 순서로 호출",
    "```",
    "",
    "### 정적 생성자 (static constructor)",
    "",
    "클래스가 처음 사용될 때 **한 번만** 호출됩니다. 정적 필드 초기화에 사용합니다.",
    "",
    "```csharp",
    "class Config",
    "{",
    "    public static string AppName { get; private set; }",
    "    public static DateTime StartTime { get; private set; }",
    "",
    "    static Config()",
    "    {",
    "        AppName = \"MyApp\";",
    "        StartTime = DateTime.Now;",
    "        Console.WriteLine(\"정적 생성자 호출됨 (1회만)\");",
    "    }",
    "}",
    "",
    "// Config 클래스에 처음 접근할 때 자동 호출",
    "Console.WriteLine(Config.AppName); // MyApp",
    "```",
    "",
    "> 정적 생성자는 접근 제한자를 가질 수 없고, 매개변수도 받을 수 없습니다.",
    "",
    "### IDisposable과 Dispose 패턴",
    "",
    "소멸자(Finalizer) 대신, **관리되지 않는 리소스**(파일, DB 연결 등)는 `IDisposable`을 구현하여 명시적으로 해제합니다.",
    "",
    "```csharp",
    "class DatabaseConnection : IDisposable",
    "{",
    "    private bool _disposed = false;",
    "",
    "    public DatabaseConnection()",
    "    {",
    "        Console.WriteLine(\"DB 연결 열림\");",
    "    }",
    "",
    "    public void Query(string sql)",
    "    {",
    "        if (_disposed) throw new ObjectDisposedException(nameof(DatabaseConnection));",
    "        Console.WriteLine($\"쿼리 실행: {sql}\");",
    "    }",
    "",
    "    public void Dispose()",
    "    {",
    "        if (!_disposed)",
    "        {",
    "            Console.WriteLine(\"DB 연결 닫힘\");",
    "            _disposed = true;",
    "        }",
    "    }",
    "}",
    "",
    "// using 문: 블록 종료 시 자동 Dispose 호출",
    "using (var db = new DatabaseConnection())",
    "{",
    "    db.Query(\"SELECT * FROM Users\");",
    "} // 여기서 자동으로 Dispose() 호출",
    "",
    "// using 선언 (C# 8.0+): 스코프 끝에서 자동 해제",
    "using var db2 = new DatabaseConnection();",
    "db2.Query(\"INSERT INTO Logs VALUES (...)\");",
    "// 메서드 종료 시 자동 Dispose",
    "```",
    "",
    "> **Best Practice:** 소멸자(`~`)보다 `IDisposable` 패턴을 사용하세요. 소멸자는 GC 타이밍에 의존하므로 리소스 해제 시점을 제어할 수 없습니다.",
    "",
    "---",
    "",
    "## 접근 제한자",
    "",
    "| 접근 제한자 | 같은 클래스 | 파생 클래스 | 같은 어셈블리 | 외부 |",
    "|-------------|:-----------:|:-----------:|:-------------:|:----:|",
    "| `public` | O | O | O | O |",
    "| `protected` | O | O | X | X |",
    "| `internal` | O | O | O | X |",
    "| `protected internal` | O | O | O | X |",
    "| `private protected` | O | O (같은 어셈블리) | X | X |",
    "| `private` | O | X | X | X |",
    "",
    "---",
    "",
    "## 상속",
    "",
    "```csharp",
    "class Base",
    "{",
    "    protected string Name;",
    "",
    "    public Base(string Name)",
    "    {",
    "        this.Name = Name;",
    "        Console.WriteLine($\"{this.Name}.Base()\");",
    "    }",
    "",
    "    ~Base()",
    "    {",
    "        Console.WriteLine($\"{this.Name}.~Base()\");",
    "    }",
    "",
    "    public void BaseMethod()",
    "    {",
    "        Console.WriteLine($\"{Name}.BaseMethod()\");",
    "    }",
    "}",
    "",
    "class Derived : Base",
    "{",
    "    public Derived(string Name) : base(Name)",
    "    {",
    "        Console.WriteLine($\"{this.Name}.Derived()\");",
    "    }",
    "",
    "    public void DerivedMethod()",
    "    {",
    "        Console.WriteLine($\"{Name}.DerivedMethod()\");",
    "    }",
    "}",
    "",
    "Derived b = new Derived(\"b\");",
    "b.BaseMethod();    // 부모 메서드 사용 가능",
    "b.DerivedMethod(); // 자식 메서드",
    "```",
    "",
    "### sealed 클래스와 메서드",
    "",
    "`sealed`는 더 이상의 상속이나 오버라이딩을 금지합니다.",
    "",
    "```csharp",
    "// sealed 클래스: 상속 불가",
    "sealed class FinalClass",
    "{",
    "    public void DoSomething() => Console.WriteLine(\"최종 클래스\");",
    "}",
    "",
    "// class CannotInherit : FinalClass { } // 컴파일 에러!",
    "",
    "// sealed 메서드: 더 이상 오버라이딩 불가",
    "class Animal",
    "{",
    "    public virtual void Speak() => Console.WriteLine(\"...\");",
    "}",
    "",
    "class Dog : Animal",
    "{",
    "    public sealed override void Speak() => Console.WriteLine(\"멍멍\");",
    "}",
    "",
    "class Puppy : Dog",
    "{",
    "    // public override void Speak() { } // 컴파일 에러! sealed",
    "}",
    "```",
    "",
    "> `sealed`는 JIT 컴파일러의 최적화(devirtualization)에도 도움이 됩니다.",
    "",
    "---",
    "",
    "## 다형성: virtual / override / new",
    "",
    "부모 클래스의 메서드를 자식이 **재정의**합니다.",
    "",
    "```csharp",
    "class ArmorSuite",
    "{",
    "    public virtual void Initialize()",
    "    {",
    "        Console.WriteLine(\"Armored\");",
    "    }",
    "}",
    "",
    "class IronMan : ArmorSuite",
    "{",
    "    public override void Initialize()",
    "    {",
    "        base.Initialize();",
    "        Console.WriteLine(\"Repulsor Rays Armed\");",
    "    }",
    "}",
    "",
    "class WarMachine : ArmorSuite",
    "{",
    "    public override void Initialize()",
    "    {",
    "        base.Initialize();",
    "        Console.WriteLine(\"Double-Barrel Cannons Armed\");",
    "        Console.WriteLine(\"Micro-Rocket Launcher Armed\");",
    "    }",
    "}",
    "",
    "ArmorSuite ironman = new IronMan();",
    "ironman.Initialize();",
    "// Armored",
    "// Repulsor Rays Armed",
    "```",
    "",
    "### override vs new (메서드 숨기기)",
    "",
    "```csharp",
    "class Parent",
    "{",
    "    public virtual void Hello() => Console.WriteLine(\"Parent.Hello\");",
    "}",
    "",
    "class ChildOverride : Parent",
    "{",
    "    public override void Hello() => Console.WriteLine(\"ChildOverride.Hello\");",
    "}",
    "",
    "class ChildNew : Parent",
    "{",
    "    public new void Hello() => Console.WriteLine(\"ChildNew.Hello\");",
    "}",
    "",
    "Parent a = new ChildOverride();",
    "Parent b = new ChildNew();",
    "",
    "a.Hello(); // ChildOverride.Hello (런타임 타입 기준 - 다형성)",
    "b.Hello(); // Parent.Hello (컴파일 타입 기준 - 숨기기!)",
    "",
    "// new를 사용하면 다형성이 깨지므로 주의 필요",
    "((ChildNew)b).Hello(); // ChildNew.Hello (직접 캐스팅 시)",
    "```",
    "",
    "| 키워드 | 동작 | 다형성 |",
    "|--------|------|--------|",
    "| `override` | 부모 메서드 재정의 | O (런타임 타입 기준) |",
    "| `new` | 부모 메서드 숨기기 | X (컴파일 타입 기준) |",
    "",
    "> **Best Practice:** 특별한 이유가 없다면 항상 `override`를 사용하세요. `new`는 다형성을 깨뜨려 예기치 않은 동작을 유발합니다.",
    "",
    "---",
    "",
    "## 업캐스팅 / 다운캐스팅",
    "",
    "```csharp",
    "class Animal { public virtual void Speak() => Console.WriteLine(\"...\"); }",
    "class Dog : Animal { public override void Speak() => Console.WriteLine(\"멍멍\"); }",
    "class Cat : Animal { public override void Speak() => Console.WriteLine(\"야옹\"); }",
    "",
    "// 업캐스팅: 자식 → 부모 (항상 안전, 암시적)",
    "Animal animal = new Dog();",
    "animal.Speak(); // 멍멍 (다형성)",
    "",
    "// 다운캐스팅: 부모 → 자식 (위험, 명시적)",
    "if (animal is Dog dog)",
    "{",
    "    Console.WriteLine(\"Dog로 변환 성공\");",
    "}",
    "",
    "// as 연산자: 실패 시 null 반환",
    "Cat? cat = animal as Cat;",
    "Console.WriteLine(cat == null); // True (Dog인데 Cat으로 변환 시도)",
    "",
    "// 잘못된 다운캐스팅 → InvalidCastException",
    "// Cat wrongCast = (Cat)animal; // 런타임 예외!",
    "```",
    "",
    "---",
    "",
    "## 추상 클래스 (abstract)",
    "",
    "인스턴스를 직접 생성할 수 없고, 반드시 상속 후 추상 메서드를 구현해야 합니다.",
    "",
    "```csharp",
    "abstract class AbstractBase",
    "{",
    "    protected void PrivateMethodA()",
    "    {",
    "        Console.WriteLine(\"AbstractBase.PrivateMethodA()\");",
    "    }",
    "",
    "    public void PublicMethodA()",
    "    {",
    "        Console.WriteLine(\"AbstractBase.PublicMethodA()\");",
    "    }",
    "",
    "    public abstract void AbstractMethodA();",
    "}",
    "",
    "class Derived : AbstractBase",
    "{",
    "    public override void AbstractMethodA()",
    "    {",
    "        Console.WriteLine(\"Derived.AbstractMethodA()\");",
    "        PrivateMethodA();",
    "    }",
    "}",
    "",
    "AbstractBase obj = new Derived();",
    "obj.AbstractMethodA();",
    "obj.PublicMethodA();",
    "```",
    "",
    "---",
    "",
    "## 인터페이스 (interface)",
    "",
    "클래스가 구현해야 할 **계약(contract)**을 정의합니다. 다중 상속이 가능합니다.",
    "",
    "```csharp",
    "interface ILogger",
    "{",
    "    void WriteLog(string message);",
    "}",
    "",
    "interface IFormattableLogger : ILogger",
    "{",
    "    void WriteLog(string format, params Object[] args);",
    "}",
    "",
    "class ConsoleLogger : IFormattableLogger",
    "{",
    "    public void WriteLog(string message)",
    "    {",
    "        Console.WriteLine($\"{DateTime.Now.ToLocalTime()}, {message}\");",
    "    }",
    "",
    "    public void WriteLog(string format, params Object[] args)",
    "    {",
    "        string message = String.Format(format, args);",
    "        Console.WriteLine($\"{DateTime.Now.ToLocalTime()}, {message}\");",
    "    }",
    "}",
    "",
    "IFormattableLogger logger = new ConsoleLogger();",
    "logger.WriteLog(\"The world is not flat.\");",
    "logger.WriteLog(\"{0} + {1} = {2}\", 1, 1, 2);",
    "```",
    "",
    "### 인터페이스 기본 구현 (C# 8.0+)",
    "",
    "```csharp",
    "interface ILogger",
    "{",
    "    void WriteLog(string message);",
    "",
    "    void WriteError(string error)",
    "    {",
    "        WriteLog($\"Error: {error}\");",
    "    }",
    "}",
    "```",
    "",
    "### 명시적 인터페이스 구현",
    "",
    "같은 이름의 메서드를 가진 여러 인터페이스를 구현할 때 사용합니다.",
    "",
    "```csharp",
    "interface IKorean { void Greet(); }",
    "interface IEnglish { void Greet(); }",
    "",
    "class Multilingual : IKorean, IEnglish",
    "{",
    "    void IKorean.Greet() => Console.WriteLine(\"안녕하세요\");",
    "    void IEnglish.Greet() => Console.WriteLine(\"Hello\");",
    "}",
    "",
    "var person = new Multilingual();",
    "// person.Greet(); // 컴파일 에러! 어떤 인터페이스인지 모호",
    "",
    "((IKorean)person).Greet();  // 안녕하세요",
    "((IEnglish)person).Greet(); // Hello",
    "```",
    "",
    "### 추상 클래스 vs 인터페이스 비교",
    "",
    "| 구분 | 추상 클래스 (abstract class) | 인터페이스 (interface) |",
    "|------|---------------------------|---------------------|",
    "| **다중 상속** | 불가 (1개만) | 가능 (여러 개) |",
    "| **필드** | 가질 수 있음 | 불가 (C# 8.0 이전) |",
    "| **생성자** | 가질 수 있음 | 불가 |",
    "| **기본 구현** | 가능 | C# 8.0+ 가능 (default) |",
    "| **접근 제한자** | 모두 사용 가능 | 기본 public |",
    "| **용도** | \"~이다\" (is-a) 관계 | \"~할 수 있다\" (can-do) 관계 |",
    "| **예시** | `Animal` → `Dog` | `IDisposable`, `IComparable` |",
    "",
    "---",
    "",
    "## 클래스 vs 구조체 상세 비교",
    "",
    "```csharp",
    "struct Point3D",
    "{",
    "    public int X;",
    "    public int Y;",
    "    public int Z;",
    "",
    "    public Point3D(int X, int Y, int Z)",
    "    {",
    "        this.X = X;",
    "        this.Y = Y;",
    "        this.Z = Z;",
    "    }",
    "",
    "    public override string ToString()",
    "    {",
    "        return $\"{X}, {Y}, {Z}\";",
    "    }",
    "}",
    "",
    "Point3D p1 = new Point3D(100, 200, 300);",
    "Point3D p2 = p1;    // 값 복사 (독립적)",
    "p2.Z = 400;",
    "",
    "Console.WriteLine(p1); // 100, 200, 300 (변경 없음)",
    "Console.WriteLine(p2); // 100, 200, 400",
    "```",
    "",
    "| 구분 | class | struct |",
    "|------|-------|--------|",
    "| **타입** | 참조 타입 (힙) | 값 타입 (스택) |",
    "| **복사** | 참조 복사 (같은 객체 공유) | 값 복사 (독립적 사본) |",
    "| **상속** | 가능 | 불가 (인터페이스 구현만 가능) |",
    "| **null** | 가능 | 불가 (`Nullable<T>`로 가능) |",
    "| **기본 생성자** | 자동 생성 | C# 10+ 사용자 정의 가능 |",
    "| **GC 부담** | 있음 (힙 할당) | 없음 (스택 할당) |",
    "| **용도** | 복잡한 객체, 상속 필요 시 | 가벼운 데이터 (좌표, 색상 등) |",
    "",
    "> **struct를 사용할 때:** 크기가 16바이트 이하이고, 불변(immutable)이며, 자주 박싱되지 않을 때 적합합니다.",
    "",
    "---",
    "",
    "## 튜플 (ValueTuple) 심화",
    "",
    "```csharp",
    "// 명명되지 않은 튜플",
    "var a = (\"슈퍼맨\", 9999);",
    "Console.WriteLine($\"{a.Item1}, {a.Item2}\");",
    "",
    "// 명명된 튜플",
    "var b = (Name: \"박상현\", Age: 17);",
    "Console.WriteLine($\"{b.Name}, {b.Age}\");",
    "",
    "// 분해 (Deconstruct)",
    "var (name, age) = b;",
    "Console.WriteLine($\"{name}, {age}\");",
    "",
    "// 메서드에서 여러 값 반환",
    "static (int min, int max) GetMinMax(int[] arr)",
    "{",
    "    return (arr.Min(), arr.Max());",
    "}",
    "",
    "var result = GetMinMax(new int[] {1, 5, 3, 9, 2});",
    "Console.WriteLine($\"Min: {result.min}, Max: {result.max}\");",
    "```",
    "",
    "### 사용자 정의 Deconstruct",
    "",
    "```csharp",
    "class Person",
    "{",
    "    public string Name { get; set; }",
    "    public int Age { get; set; }",
    "",
    "    public void Deconstruct(out string name, out int age)",
    "    {",
    "        name = Name;",
    "        age = Age;",
    "    }",
    "}",
    "",
    "var person = new Person { Name = \"하루\", Age = 25 };",
    "var (n, a) = person; // Deconstruct 호출",
    "Console.WriteLine($\"{n}, {a}\"); // 하루, 25",
    "```",
    "",
    "---",
    "",
    "## record 타입 (C# 9.0+)",
    "",
    "`record`는 **불변 데이터**를 위한 참조 타입으로, 값 기반 동등성과 간결한 문법을 제공합니다.",
    "",
    "```csharp",
    "// record 선언 (위치 매개변수 문법)",
    "record Person(string Name, int Age);",
    "",
    "var p1 = new Person(\"하루\", 25);",
    "var p2 = new Person(\"하루\", 25);",
    "",
    "// 값 기반 동등성 (class는 참조 비교)",
    "Console.WriteLine(p1 == p2);        // True (값이 같으므로)",
    "Console.WriteLine(p1.Equals(p2));   // True",
    "",
    "// with 식: 일부 값만 변경한 새 인스턴스 생성",
    "var p3 = p1 with { Age = 30 };",
    "Console.WriteLine(p3);              // Person { Name = 하루, Age = 30 }",
    "",
    "// 분해 가능",
    "var (name, age) = p1;",
    "Console.WriteLine($\"{name}, {age}\"); // 하루, 25",
    "",
    "// 자동 ToString",
    "Console.WriteLine(p1); // Person { Name = 하루, Age = 25 }",
    "```",
    "",
    "### record struct (C# 10+)",
    "",
    "```csharp",
    "// record struct: 값 타입 record (스택 할당)",
    "record struct Point(int X, int Y);",
    "",
    "// readonly record struct: 불변 값 타입",
    "readonly record struct ImmutablePoint(int X, int Y);",
    "",
    "var p = new Point(1, 2);",
    "var q = p with { X = 10 };",
    "Console.WriteLine(q); // Point { X = 10, Y = 2 }",
    "```",
    "",
    "| 타입 | 종류 | 동등성 | 불변성 | 상속 |",
    "|------|------|--------|--------|------|",
    "| `class` | 참조 타입 | 참조 비교 | 가변 | 가능 |",
    "| `record` | 참조 타입 | 값 비교 | 기본 불변 | record끼리 가능 |",
    "| `struct` | 값 타입 | 값 비교 | 가변 | 불가 |",
    "| `record struct` | 값 타입 | 값 비교 | 가변/불변 선택 | 불가 |",
    "",
    "---",
    "",
    "## 확장 메서드 (Extension Method)",
    "",
    "기존 타입에 **새 메서드를 추가**합니다. `this` 키워드로 대상 타입을 지정합니다.",
    "",
    "```csharp",
    "public static class IntegerExtension",
    "{",
    "    public static int Square(this int myInt)",
    "    {",
    "        return myInt * myInt;",
    "    }",
    "",
    "    public static int Power(this int myInt, int exponent)",
    "    {",
    "        int result = myInt;",
    "        for (int i = 1; i < exponent; i++)",
    "            result = result * myInt;",
    "        return result;",
    "    }",
    "}",
    "",
    "Console.WriteLine(3.Square());    // 9",
    "Console.WriteLine(3.Power(4));    // 81",
    "Console.WriteLine(2.Power(10));   // 1024",
    "```",
    "",
    "### 확장 메서드 체이닝과 LINQ",
    "",
    "LINQ는 확장 메서드의 대표적인 활용 사례입니다.",
    "",
    "```csharp",
    "public static class StringExtensions",
    "{",
    "    public static string Repeat(this string s, int count)",
    "        => string.Concat(Enumerable.Repeat(s, count));",
    "",
    "    public static string Reverse(this string s)",
    "        => new string(s.AsEnumerable().Reverse().ToArray());",
    "",
    "    public static bool IsNullOrEmpty(this string? s)",
    "        => string.IsNullOrEmpty(s);",
    "}",
    "",
    "// 체이닝",
    "string result = \"Hello\"",
    "    .Repeat(3)       // HelloHelloHello",
    "    .ToUpper()       // HELLOHELLOHELLO",
    "    .Substring(0, 5); // HELLO",
    "",
    "// LINQ도 확장 메서드의 체이닝",
    "var numbers = new[] { 5, 3, 8, 1, 9, 2 };",
    "var result2 = numbers",
    "    .Where(n => n > 3)",
    "    .OrderBy(n => n)",
    "    .Select(n => n * 10)",
    "    .ToList();",
    "// [50, 80, 90]",
    "```",
    "",
    "---",
    "",
    "## 클래스 계층 구조 예제",
    "",
    "```mermaid",
    "classDiagram",
    "    class Shape {",
    "        <<abstract>>",
    "        +string Name",
    "        +double Area()*",
    "        +string ToString()",
    "    }",
    "",
    "    class Circle {",
    "        +double Radius",
    "        +double Area()",
    "    }",
    "",
    "    class Rectangle {",
    "        +double Width",
    "        +double Height",
    "        +double Area()",
    "    }",
    "",
    "    class Square {",
    "        +Square(double side)",
    "    }",
    "",
    "    class IDrawable {",
    "        <<interface>>",
    "        +void Draw()",
    "    }",
    "",
    "    Shape <|-- Circle",
    "    Shape <|-- Rectangle",
    "    Rectangle <|-- Square",
    "    IDrawable <|.. Circle",
    "    IDrawable <|.. Rectangle",
    "```",
    "",
    "---",
    "",
    "## 실전 설계 예제: 도메인 모델링",
    "",
    "```csharp",
    "// 도메인 모델: 주문 시스템",
    "record Product(string Name, decimal Price);",
    "",
    "record OrderItem(Product Product, int Quantity)",
    "{",
    "    public decimal SubTotal => Product.Price * Quantity;",
    "}",
    "",
    "class Order",
    "{",
    "    private readonly List<OrderItem> _items = new();",
    "",
    "    public string OrderId { get; } = Guid.NewGuid().ToString(\"N\")[..8];",
    "    public DateTime CreatedAt { get; } = DateTime.Now;",
    "    public IReadOnlyList<OrderItem> Items => _items.AsReadOnly();",
    "    public decimal Total => _items.Sum(i => i.SubTotal);",
    "",
    "    public void AddItem(Product product, int quantity)",
    "    {",
    "        if (quantity <= 0)",
    "            throw new ArgumentException(\"수량은 1 이상이어야 합니다.\");",
    "        _items.Add(new OrderItem(product, quantity));",
    "    }",
    "",
    "    public override string ToString()",
    "        => $\"주문 #{OrderId} | 상품 {_items.Count}종 | 합계: {Total:N0}원\";",
    "}",
    "",
    "// 사용 예시",
    "var order = new Order();",
    "order.AddItem(new Product(\"키보드\", 89000m), 1);",
    "order.AddItem(new Product(\"마우스\", 45000m), 2);",
    "",
    "Console.WriteLine(order);",
    "foreach (var item in order.Items)",
    "    Console.WriteLine($\"  {item.Product.Name} x{item.Quantity} = {item.SubTotal:N0}원\");",
    "```",
    "",
    "---",
    "",
    "## Best Practices 정리",
    "",
    "| 상황 | 권장 사항 |",
    "|------|----------|",
    "| 작고 불변인 데이터 | `readonly record struct` |",
    "| 불변 도메인 모델 | `record` |",
    "| 리소스 관리 | `IDisposable` + `using` |",
    "| 상속 금지 | `sealed` 사용 |",
    "| 여러 계약 구현 | 인터페이스 (다중 구현 가능) |",
    "| is-a 관계 + 공유 구현 | 추상 클래스 |",
    "| 메서드 재정의 | `override` 사용 (`new` 지양) |",
    "| 타입 변환 | `is` 패턴 매칭 활용 |",
    "| 기존 타입 확장 | 확장 메서드 |",
    "",
    "---",
    "",
    "### 요약",
    "C#의 OOP는 `class`(참조 타입)와 `struct`(값 타입)를 기반으로, `virtual`/`override` 다형성, `abstract` 클래스, `interface` 다중 구현, `record` 불변 타입, `확장 메서드`, `튜플` 등을 활용하여 유연하고 안전한 코드를 작성할 수 있습니다. `sealed`로 상속을 제한하고, `IDisposable`로 리소스를 관리하며, `record`로 값 기반 동등성을 간편하게 구현하는 것이 현대 C#의 모범 사례입니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
