<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "csharp-file-io",
  title: "C# 파일 다루기",
  date: "2026-02-25",
  summary: "Stream, FileStream, StreamReader/Writer, BinaryReader/Writer, 디렉터리/파일 조작, using 선언, 직렬화까지 C# 파일 I/O를 정리합니다.",
  category: "Coding/C#",
  tags: ["csharp","file","stream","io","serialization","directory","binary","text"],
  content: [
    "## 한 줄 요약",
    "C#은 `Stream` 기반의 파일 I/O를 제공하며, 텍스트(`StreamReader`/`Writer`), 바이너리(`BinaryReader`/`Writer`), 직렬화(`Serialize`) 등 다양한 방식으로 파일을 다룹니다.",
    "",
    "---",
    "",
    "## Stream 계층 구조",
    "",
    "C#에서 모든 I/O는 **Stream(스트림)** 추상 클래스를 기반으로 합니다.",
    "",
    "```mermaid",
    "classDiagram",
    "    class Stream {",
    "        <<abstract>>",
    "        +Read(byte[], int, int) int",
    "        +Write(byte[], int, int) void",
    "        +Seek(long, SeekOrigin) long",
    "        +Flush() void",
    "        +Close() void",
    "        +Position : long",
    "        +Length : long",
    "        +CanRead : bool",
    "        +CanWrite : bool",
    "        +CanSeek : bool",
    "    }",
    "    Stream <|-- FileStream",
    "    Stream <|-- MemoryStream",
    "    Stream <|-- NetworkStream",
    "    Stream <|-- BufferedStream",
    "    Stream <|-- GZipStream",
    "    FileStream : +FileMode mode",
    "    FileStream : +FileAccess access",
    "    MemoryStream : +ToArray() byte[]",
    "    MemoryStream : +GetBuffer() byte[]",
    "    NetworkStream : +DataAvailable bool",
    "    BufferedStream : +int bufferSize",
    "```",
    "",
    "### Stream 핵심 개념",
    "",
    "| 개념 | 설명 |",
    "|------|------|",
    "| 바이트 스트림 | 데이터를 **바이트 단위**로 순차 처리하는 추상화 |",
    "| Position | 현재 읽기/쓰기 위치 |",
    "| Length | 스트림 전체 길이 |",
    "| Seek | 위치를 임의로 이동 (Random Access) |",
    "| Flush | 버퍼에 남은 데이터를 실제 대상에 기록 |",
    "| Dispose | 리소스 해제 (using과 함께 사용) |",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"프로그램\"] -->|\"쓰기 (Stream)\"| B[\"파일\"]",
    "    B -->|\"읽기 (Stream)\"| A",
    "```",
    "",
    "---",
    "",
    "## File 클래스 vs FileInfo 클래스",
    "",
    "| 비교 항목 | `File` (정적 클래스) | `FileInfo` (인스턴스 클래스) |",
    "|----------|---------------------|---------------------------|",
    "| 사용 방식 | `File.Exists(path)` | `new FileInfo(path).Exists` |",
    "| 보안 검사 | 매 호출마다 수행 | 생성 시 한 번만 수행 |",
    "| 적합한 경우 | 단일 작업 | 같은 파일에 여러 작업 |",
    "| 반환값 | 없거나 단순 타입 | `FileInfo` 객체 (체이닝 가능) |",
    "",
    "```csharp",
    "// File (정적 메서드) - 단일 작업에 편리",
    "bool exists = File.Exists(\"test.txt\");",
    "string text = File.ReadAllText(\"test.txt\");",
    "File.WriteAllText(\"test.txt\", \"Hello\");",
    "",
    "// FileInfo (인스턴스) - 여러 작업 시 효율적",
    "FileInfo fi = new FileInfo(\"test.txt\");",
    "if (fi.Exists)",
    "{",
    "    Console.WriteLine($\"이름: {fi.Name}\");",
    "    Console.WriteLine($\"크기: {fi.Length} bytes\");",
    "    Console.WriteLine($\"생성일: {fi.CreationTime}\");",
    "    Console.WriteLine($\"수정일: {fi.LastWriteTime}\");",
    "    Console.WriteLine($\"확장자: {fi.Extension}\");",
    "    Console.WriteLine($\"디렉터리: {fi.DirectoryName}\");",
    "    Console.WriteLine($\"속성: {fi.Attributes}\");",
    "    Console.WriteLine($\"읽기전용: {fi.IsReadOnly}\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## Directory / DirectoryInfo 클래스",
    "",
    "```csharp",
    "// Directory (정적) - 디렉터리 조작",
    "Directory.CreateDirectory(\"newDir\");",
    "Directory.Move(\"newDir\", \"renamedDir\");",
    "Directory.Delete(\"renamedDir\");",
    "bool exists = Directory.Exists(\"someDir\");",
    "",
    "string[] dirs = Directory.GetDirectories(\".\");",
    "string[] files = Directory.GetFiles(\".\", \"*.txt\");",
    "string[] allFiles = Directory.GetFiles(\".\", \"*.*\", SearchOption.AllDirectories);",
    "",
    "// DirectoryInfo (인스턴스) - 상세 정보",
    "DirectoryInfo di = new DirectoryInfo(\".\");",
    "Console.WriteLine($\"이름: {di.Name}\");",
    "Console.WriteLine($\"전체 경로: {di.FullName}\");",
    "Console.WriteLine($\"부모: {di.Parent?.Name}\");",
    "Console.WriteLine($\"생성일: {di.CreationTime}\");",
    "",
    "// 하위 파일/디렉터리 조회",
    "foreach (FileInfo file in di.GetFiles(\"*.cs\"))",
    "    Console.WriteLine($\"  {file.Name} ({file.Length} bytes)\");",
    "",
    "foreach (DirectoryInfo subDir in di.GetDirectories())",
    "    Console.WriteLine($\"  [DIR] {subDir.Name}\");",
    "```",
    "",
    "---",
    "",
    "## Path 클래스 활용",
    "",
    "파일 경로를 안전하게 조작하는 유틸리티 클래스입니다.",
    "",
    "```csharp",
    "string path = @\"C:\\Users\\haru\\Documents\\report.txt\";",
    "",
    "Console.WriteLine(Path.GetFileName(path));        // report.txt",
    "Console.WriteLine(Path.GetFileNameWithoutExtension(path)); // report",
    "Console.WriteLine(Path.GetExtension(path));       // .txt",
    "Console.WriteLine(Path.GetDirectoryName(path));   // C:\\Users\\haru\\Documents",
    "Console.WriteLine(Path.GetFullPath(\"test.txt\"));  // 절대 경로로 변환",
    "",
    "// 경로 결합 (OS별 구분자 자동 처리)",
    "string combined = Path.Combine(\"C:\\\\Users\", \"haru\", \"file.txt\");",
    "// C:\\Users\\haru\\file.txt",
    "",
    "// 임시 파일/폴더",
    "string tempFile = Path.GetTempFileName();    // 임시 파일 생성",
    "string tempPath = Path.GetTempPath();        // 임시 폴더 경로",
    "string randomName = Path.GetRandomFileName(); // 랜덤 파일명 생성",
    "",
    "// 확장자 변경",
    "string newPath = Path.ChangeExtension(path, \".csv\");",
    "// C:\\Users\\haru\\Documents\\report.csv",
    "```",
    "",
    "> **Best Practice**: 경로 결합 시 `+` 연산자 대신 반드시 `Path.Combine()`을 사용하세요. OS별 경로 구분자(`\\` vs `/`)를 자동으로 처리합니다.",
    "",
    "---",
    "",
    "## 파일 읽기/쓰기 편의 메서드 (File 클래스)",
    "",
    "```csharp",
    "// 전체 텍스트 읽기/쓰기",
    "File.WriteAllText(\"hello.txt\", \"Hello, C#!\");",
    "string content = File.ReadAllText(\"hello.txt\");",
    "",
    "// 줄 단위 읽기/쓰기",
    "File.WriteAllLines(\"names.txt\", new[] { \"Alice\", \"Bob\", \"Charlie\" });",
    "string[] lines = File.ReadAllLines(\"names.txt\");",
    "",
    "// 추가 쓰기",
    "File.AppendAllText(\"log.txt\", $\"[{DateTime.Now}] 로그 메시지\<br>\");",
    "",
    "// 바이트 단위 읽기/쓰기",
    "byte[] data = new byte[] { 0x48, 0x65, 0x6C, 0x6C, 0x6F };",
    "File.WriteAllBytes(\"binary.dat\", data);",
    "byte[] readData = File.ReadAllBytes(\"binary.dat\");",
    "",
    "// 파일 복사, 이동, 삭제",
    "File.Copy(\"source.txt\", \"dest.txt\", overwrite: true);",
    "File.Move(\"old.txt\", \"new.txt\");",
    "File.Delete(\"temp.txt\");",
    "```",
    "",
    "---",
    "",
    "## FileStream으로 바이트 읽고 쓰기",
    "",
    "```csharp",
    "using System.IO;",
    "",
    "long someValue = 0x123456789ABCDEF0;",
    "",
    "// 쓰기",
    "Stream outStream = new FileStream(\"a.dat\", FileMode.Create);",
    "byte[] wBytes = BitConverter.GetBytes(someValue);",
    "outStream.Write(wBytes, 0, wBytes.Length);",
    "outStream.Close();",
    "",
    "// 읽기",
    "Stream inStream = new FileStream(\"a.dat\", FileMode.Open);",
    "byte[] rBytes = new byte[8];",
    "",
    "int i = 0;",
    "while (inStream.Position < inStream.Length)",
    "    rBytes[i++] = (byte)inStream.ReadByte();",
    "",
    "long readValue = BitConverter.ToInt64(rBytes, 0);",
    "Console.WriteLine($\"0x{readValue:X16}\"); // 0x123456789ABCDEF0",
    "inStream.Close();",
    "```",
    "",
    "### FileMode, FileAccess, FileShare 상세",
    "",
    "**FileMode:**",
    "",
    "| FileMode | 파일 있을 때 | 파일 없을 때 |",
    "|----------|------------|------------|",
    "| `CreateNew` | 예외 발생 | 새로 생성 |",
    "| `Create` | 덮어쓰기 | 새로 생성 |",
    "| `Open` | 열기 | 예외 발생 |",
    "| `OpenOrCreate` | 열기 | 새로 생성 |",
    "| `Truncate` | 열고 내용 비움 | 예외 발생 |",
    "| `Append` | 끝에 추가 | 새로 생성 |",
    "",
    "**FileAccess:**",
    "",
    "| FileAccess | 설명 |",
    "|-----------|------|",
    "| `Read` | 읽기 전용 |",
    "| `Write` | 쓰기 전용 |",
    "| `ReadWrite` | 읽기 + 쓰기 |",
    "",
    "**FileShare:**",
    "",
    "| FileShare | 설명 |",
    "|-----------|------|",
    "| `None` | 다른 프로세스 접근 차단 |",
    "| `Read` | 다른 프로세스의 읽기 허용 |",
    "| `Write` | 다른 프로세스의 쓰기 허용 |",
    "| `ReadWrite` | 읽기/쓰기 모두 허용 |",
    "| `Delete` | 삭제 허용 |",
    "",
    "```csharp",
    "// 읽기 전용으로 열고, 다른 프로세스의 읽기도 허용",
    "using var fs = new FileStream(\"data.txt\",",
    "    FileMode.Open, FileAccess.Read, FileShare.Read);",
    "```",
    "",
    "---",
    "",
    "## Seek (랜덤 액세스)",
    "",
    "스트림 내의 **위치(Position)를 이동**하여 원하는 지점에 읽기/쓰기합니다.",
    "",
    "```csharp",
    "Stream stream = new FileStream(\"a.dat\", FileMode.Create);",
    "",
    "stream.WriteByte(0x01); // Position: 1",
    "stream.WriteByte(0x02); // Position: 2",
    "stream.WriteByte(0x03); // Position: 3",
    "",
    "stream.Seek(5, SeekOrigin.Current); // 현재 위치에서 5바이트 이동 → Position: 8",
    "",
    "stream.WriteByte(0x04); // Position: 9",
    "stream.Close();",
    "```",
    "",
    "| SeekOrigin | 기준 |",
    "|------------|------|",
    "| `Begin` | 스트림 시작점 |",
    "| `Current` | 현재 위치 |",
    "| `End` | 스트림 끝 |",
    "",
    "---",
    "",
    "## using 선언 vs using 문",
    "",
    "스트림은 반드시 닫아야 합니다. `using`을 사용하면 **자동으로 Dispose(Close)** 됩니다.",
    "",
    "```csharp",
    "// using 블록 (C# 전통 방식) - 블록 끝에서 Dispose",
    "using (Stream outStream = new FileStream(\"a.dat\", FileMode.Create))",
    "{",
    "    byte[] bytes = BitConverter.GetBytes(0x123456789ABCDEF0);",
    "    outStream.Write(bytes, 0, bytes.Length);",
    "} // 여기서 자동으로 Close/Dispose",
    "",
    "// using 선언 (C# 8.0+) - 스코프(메서드) 끝에서 Dispose",
    "using Stream inStream = new FileStream(\"a.dat\", FileMode.Open);",
    "byte[] rBytes = new byte[8];",
    "int i = 0;",
    "while (inStream.Position < inStream.Length)",
    "    rBytes[i++] = (byte)inStream.ReadByte();",
    "// 메서드 종료 시 자동 Dispose",
    "```",
    "",
    "| 비교 | using 블록 (전통) | using 선언 (C# 8.0+) |",
    "|------|------------------|---------------------|",
    "| 문법 | `using (var s = ...) { }` | `using var s = ...;` |",
    "| Dispose 시점 | 블록 끝 `}` | 선언된 스코프 끝 |",
    "| 중첩 | 깊어질 수 있음 | 깔끔한 플랫 구조 |",
    "| 범위 제어 | 정확한 범위 지정 가능 | 메서드 끝까지 유지 |",
    "",
    "> **Best Practice**: 리소스를 빨리 해제해야 하면 `using 블록`, 코드 간결성이 중요하면 `using 선언`을 사용하세요.",
    "",
    "---",
    "",
    "## 텍스트 파일 (StreamWriter / StreamReader)",
    "",
    "```csharp",
    "// 텍스트 쓰기",
    "using (StreamWriter sw = new StreamWriter(",
    "    new FileStream(\"a.txt\", FileMode.Create)))",
    "{",
    "    sw.WriteLine(int.MaxValue);",
    "    sw.WriteLine(\"Good morning!\");",
    "    sw.WriteLine(uint.MaxValue);",
    "    sw.WriteLine(\"안녕하세요!\");",
    "    sw.WriteLine(double.MaxValue);",
    "}",
    "",
    "// 텍스트 읽기",
    "using (StreamReader sr = new StreamReader(",
    "    new FileStream(\"a.txt\", FileMode.Open)))",
    "{",
    "    Console.WriteLine($\"File size : {sr.BaseStream.Length} bytes\");",
    "",
    "    while (!sr.EndOfStream)",
    "    {",
    "        Console.WriteLine(sr.ReadLine());",
    "    }",
    "}",
    "```",
    "",
    "### StreamReader/StreamWriter 인코딩 처리",
    "",
    "```csharp",
    "using System.Text;",
    "",
    "// UTF-8 (기본값)",
    "using var writer1 = new StreamWriter(\"utf8.txt\", false, Encoding.UTF8);",
    "writer1.WriteLine(\"한글 테스트\");",
    "",
    "// EUC-KR (레거시 한국어 인코딩)",
    "Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);",
    "Encoding eucKr = Encoding.GetEncoding(\"EUC-KR\");",
    "using var writer2 = new StreamWriter(\"euckr.txt\", false, eucKr);",
    "writer2.WriteLine(\"한글 테스트\");",
    "",
    "// BOM 없는 UTF-8",
    "using var writer3 = new StreamWriter(\"no-bom.txt\", false, new UTF8Encoding(false));",
    "writer3.WriteLine(\"BOM 없는 UTF-8\");",
    "",
    "// 인코딩 감지하여 읽기",
    "using var reader = new StreamReader(\"unknown.txt\", detectEncodingFromByteOrderMarks: true);",
    "string text = reader.ReadToEnd();",
    "Console.WriteLine($\"인코딩: {reader.CurrentEncoding.EncodingName}\");",
    "```",
    "",
    "| 인코딩 | 설명 | 사용 시기 |",
    "|--------|------|----------|",
    "| `UTF-8` | 유니코드 가변 길이 (1~4바이트) | 기본 권장, 웹 표준 |",
    "| `UTF-16` | 유니코드 고정 2바이트 | .NET 내부 문자열 |",
    "| `EUC-KR` | 한국어 레거시 인코딩 | 오래된 시스템 호환 |",
    "| `ASCII` | 영문/숫자만 (1바이트) | 영문 전용 데이터 |",
    "",
    "---",
    "",
    "## 바이너리 파일 (BinaryWriter / BinaryReader)",
    "",
    "타입별로 **정확한 바이트 크기**로 저장/읽기합니다.",
    "",
    "```csharp",
    "// 바이너리 쓰기",
    "using (BinaryWriter bw = new BinaryWriter(",
    "    new FileStream(\"a.dat\", FileMode.Create)))",
    "{",
    "    bw.Write(int.MaxValue);       // 4바이트",
    "    bw.Write(\"Good morning!\");    // 길이 + 문자열",
    "    bw.Write(uint.MaxValue);      // 4바이트",
    "    bw.Write(\"안녕하세요!\");       // 길이 + 문자열",
    "    bw.Write(double.MaxValue);    // 8바이트",
    "}",
    "",
    "// 바이너리 읽기 (쓴 순서대로 타입 맞춰서)",
    "using BinaryReader br = new BinaryReader(",
    "    new FileStream(\"a.dat\", FileMode.Open));",
    "",
    "Console.WriteLine($\"File size : {br.BaseStream.Length} bytes\");",
    "Console.WriteLine(br.ReadInt32());    // 2147483647",
    "Console.WriteLine(br.ReadString());   // Good morning!",
    "Console.WriteLine(br.ReadUInt32());   // 4294967295",
    "Console.WriteLine(br.ReadString());   // 안녕하세요!",
    "Console.WriteLine(br.ReadDouble());   // 1.7976931348623157E+308",
    "```",
    "",
    "### 텍스트 vs 바이너리",
    "",
    "| 구분 | 텍스트 파일 | 바이너리 파일 |",
    "|------|------------|--------------|",
    "| 저장 방식 | 사람이 읽을 수 있는 문자 | 원시 바이트 |",
    "| 파일 크기 | 상대적으로 큼 | 작고 효율적 |",
    "| 클래스 | `StreamWriter`/`Reader` | `BinaryWriter`/`Reader` |",
    "| 읽기 | `ReadLine()` | `ReadInt32()`, `ReadString()` 등 |",
    "",
    "---",
    "",
    "## 비동기 파일 I/O",
    "",
    "```csharp",
    "// 비동기 텍스트 읽기/쓰기 (File 클래스)",
    "await File.WriteAllTextAsync(\"async.txt\", \"비동기 파일 쓰기\");",
    "string content = await File.ReadAllTextAsync(\"async.txt\");",
    "",
    "string[] lines = await File.ReadAllLinesAsync(\"data.txt\");",
    "await File.WriteAllLinesAsync(\"output.txt\", lines);",
    "await File.AppendAllTextAsync(\"log.txt\", \"비동기 추가\<br>\");",
    "",
    "// 비동기 StreamReader/StreamWriter",
    "using var writer = new StreamWriter(\"stream-async.txt\");",
    "await writer.WriteLineAsync(\"비동기 줄 쓰기\");",
    "await writer.FlushAsync();",
    "",
    "using var reader = new StreamReader(\"stream-async.txt\");",
    "string line = await reader.ReadLineAsync();",
    "string all = await reader.ReadToEndAsync();",
    "",
    "// 비동기 FileStream",
    "using var fs = new FileStream(\"binary-async.dat\",",
    "    FileMode.Create, FileAccess.Write, FileShare.None,",
    "    bufferSize: 4096, useAsync: true);",
    "byte[] data = new byte[] { 1, 2, 3, 4, 5 };",
    "await fs.WriteAsync(data, 0, data.Length);",
    "```",
    "",
    "> **Best Practice**: UI 애플리케이션이나 서버에서 파일 I/O를 수행할 때는 비동기 메서드를 사용하여 스레드 블로킹을 방지하세요.",
    "",
    "---",
    "",
    "## MemoryStream 활용",
    "",
    "메모리 내에서 스트림 처리를 수행합니다. 파일을 거치지 않고 데이터를 스트림으로 다룰 때 유용합니다.",
    "",
    "```csharp",
    "// 메모리에 데이터 쓰기",
    "using var ms = new MemoryStream();",
    "using var writer = new StreamWriter(ms, leaveOpen: true);",
    "writer.WriteLine(\"메모리 스트림 테스트\");",
    "writer.WriteLine(\"파일 없이 스트림 처리\");",
    "writer.Flush();",
    "",
    "// 처음으로 되감기 후 읽기",
    "ms.Position = 0;",
    "using var reader = new StreamReader(ms);",
    "string result = reader.ReadToEnd();",
    "Console.WriteLine(result);",
    "",
    "// 바이트 배열로 변환",
    "byte[] bytes = ms.ToArray();",
    "Console.WriteLine($\"크기: {bytes.Length} bytes\");",
    "",
    "// 바이트 배열에서 MemoryStream 생성",
    "using var ms2 = new MemoryStream(bytes);",
    "using var reader2 = new StreamReader(ms2);",
    "Console.WriteLine(reader2.ReadToEnd());",
    "```",
    "",
    "---",
    "",
    "## 파일 감시 (FileSystemWatcher)",
    "",
    "```csharp",
    "using var watcher = new FileSystemWatcher(@\"C:\\WatchFolder\");",
    "",
    "watcher.NotifyFilter = NotifyFilters.LastWrite",
    "                     | NotifyFilters.FileName",
    "                     | NotifyFilters.DirectoryName;",
    "",
    "// 감시할 파일 필터",
    "watcher.Filter = \"*.txt\";",
    "watcher.IncludeSubdirectories = true;",
    "",
    "// 이벤트 핸들러 등록",
    "watcher.Created += (s, e) =>",
    "    Console.WriteLine($\"[생성] {e.FullPath}\");",
    "watcher.Changed += (s, e) =>",
    "    Console.WriteLine($\"[변경] {e.FullPath}\");",
    "watcher.Deleted += (s, e) =>",
    "    Console.WriteLine($\"[삭제] {e.FullPath}\");",
    "watcher.Renamed += (s, e) =>",
    "    Console.WriteLine($\"[이름변경] {e.OldFullPath} → {e.FullPath}\");",
    "watcher.Error += (s, e) =>",
    "    Console.WriteLine($\"[에러] {e.GetException().Message}\");",
    "",
    "// 감시 시작",
    "watcher.EnableRaisingEvents = true;",
    "Console.WriteLine(\"파일 감시 중... (Enter 키로 종료)\");",
    "Console.ReadLine();",
    "```",
    "",
    "> **주의**: `FileSystemWatcher`는 짧은 시간에 여러 이벤트를 발생시킬 수 있습니다. 디바운싱 처리가 필요할 수 있습니다.",
    "",
    "---",
    "",
    "## 직렬화 심화",
    "",
    "### JSON 직렬화 (System.Text.Json)",
    "",
    "```csharp",
    "using System.Text.Json;",
    "using System.Text.Json.Serialization;",
    "",
    "class Person",
    "{",
    "    public string Name { get; set; }",
    "    public int Age { get; set; }",
    "",
    "    [JsonIgnore]",
    "    public string Password { get; set; }",
    "",
    "    [JsonPropertyName(\"email_address\")]",
    "    public string Email { get; set; }",
    "}",
    "",
    "Person p = new Person { Name = \"하루\", Age = 25, Password = \"secret\", Email = \"haru@test.com\" };",
    "",
    "// 직렬화 옵션",
    "var options = new JsonSerializerOptions",
    "{",
    "    WriteIndented = true,              // 들여쓰기",
    "    PropertyNamingPolicy = JsonNamingPolicy.CamelCase, // camelCase",
    "    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull",
    "};",
    "",
    "// 직렬화",
    "string json = JsonSerializer.Serialize(p, options);",
    "File.WriteAllText(\"person.json\", json);",
    "Console.WriteLine(json);",
    "// {\"name\": \"하루\", \"age\": 25, \"email_address\": \"haru@test.com\"}",
    "",
    "// 역직렬화",
    "string readJson = File.ReadAllText(\"person.json\");",
    "Person p2 = JsonSerializer.Deserialize<Person>(readJson, options);",
    "Console.WriteLine($\"{p2.Name}, {p2.Age}\"); // 하루, 25",
    "",
    "// 비동기 직렬화/역직렬화",
    "using var writeStream = File.OpenWrite(\"person-async.json\");",
    "await JsonSerializer.SerializeAsync(writeStream, p, options);",
    "",
    "using var readStream = File.OpenRead(\"person-async.json\");",
    "Person p3 = await JsonSerializer.DeserializeAsync<Person>(readStream, options);",
    "```",
    "",
    "### 직렬화 방식 비교",
    "",
    "| 방식 | 장점 | 단점 | 권장 여부 |",
    "|------|------|------|----------|",
    "| `System.Text.Json` | 빠름, 내장, AOT 호환 | 복잡한 시나리오 제한적 | ✅ 권장 |",
    "| `Newtonsoft.Json` | 풍부한 기능, 유연함 | 외부 패키지, 약간 느림 | ✅ 복잡한 경우 |",
    "| XML 직렬화 | 표준화, 스키마 검증 | 장황함, 느림 | ⚠️ 레거시 |",
    "| `BinaryFormatter` | 간편 | 보안 취약, .NET 5+ 비권장 | ❌ 사용 금지 |",
    "",
    "---",
    "",
    "## CSV 파일 파싱 예제",
    "",
    "```csharp",
    "// CSV 쓰기",
    "var records = new List<(string Name, int Age, string City)>",
    "{",
    "    (\"하루\", 25, \"서울\"),",
    "    (\"민수\", 30, \"부산\"),",
    "    (\"지연\", 28, \"대전\")",
    "};",
    "",
    "using (var sw = new StreamWriter(\"data.csv\", false, Encoding.UTF8))",
    "{",
    "    sw.WriteLine(\"이름,나이,도시\");",
    "    foreach (var r in records)",
    "        sw.WriteLine($\"{r.Name},{r.Age},{r.City}\");",
    "}",
    "",
    "// CSV 읽기",
    "using (var sr = new StreamReader(\"data.csv\", Encoding.UTF8))",
    "{",
    "    string header = sr.ReadLine(); // 헤더 건너뛰기",
    "    while (!sr.EndOfStream)",
    "    {",
    "        string line = sr.ReadLine();",
    "        string[] parts = line.Split(',');",
    "        Console.WriteLine($\"이름: {parts[0]}, 나이: {parts[1]}, 도시: {parts[2]}\");",
    "    }",
    "}",
    "",
    "// LINQ로 CSV 파싱",
    "var parsed = File.ReadAllLines(\"data.csv\")",
    "    .Skip(1) // 헤더 건너뛰기",
    "    .Select(line => line.Split(','))",
    "    .Select(parts => new { Name = parts[0], Age = int.Parse(parts[1]), City = parts[2] })",
    "    .ToList();",
    "",
    "foreach (var p in parsed)",
    "    Console.WriteLine($\"{p.Name} ({p.Age}) - {p.City}\");",
    "```",
    "",
    "> **주의**: 값에 쉼표나 줄바꿈이 포함된 경우 `Split`만으로는 부족합니다. 프로덕션 코드에서는 `CsvHelper` 같은 라이브러리를 사용하세요.",
    "",
    "---",
    "",
    "## 대용량 파일 처리 패턴",
    "",
    "### 라인별 읽기 (메모리 효율적)",
    "",
    "```csharp",
    "// ❌ 안 좋은 예: 전체 파일을 메모리에 로드",
    "string[] allLines = File.ReadAllLines(\"huge-file.txt\"); // 메모리 부족 가능!",
    "",
    "// ✅ 좋은 예: 라인별 스트리밍 읽기",
    "using var reader = new StreamReader(\"huge-file.txt\");",
    "while (!reader.EndOfStream)",
    "{",
    "    string line = reader.ReadLine();",
    "    ProcessLine(line);",
    "}",
    "",
    "// ✅ 더 좋은 예: File.ReadLines (IEnumerable, 지연 평가)",
    "foreach (string line in File.ReadLines(\"huge-file.txt\"))",
    "{",
    "    ProcessLine(line);",
    "}",
    "",
    "// LINQ와 결합 (지연 평가로 메모리 효율적)",
    "var errorLines = File.ReadLines(\"server.log\")",
    "    .Where(line => line.Contains(\"ERROR\"))",
    "    .Take(100)",
    "    .ToList();",
    "```",
    "",
    "### 청크 처리",
    "",
    "```csharp",
    "const int CHUNK_SIZE = 8192; // 8KB",
    "",
    "using var source = new FileStream(\"large.bin\", FileMode.Open);",
    "using var dest = new FileStream(\"copy.bin\", FileMode.Create);",
    "",
    "byte[] buffer = new byte[CHUNK_SIZE];",
    "int bytesRead;",
    "long totalRead = 0;",
    "",
    "while ((bytesRead = source.Read(buffer, 0, CHUNK_SIZE)) > 0)",
    "{",
    "    dest.Write(buffer, 0, bytesRead);",
    "    totalRead += bytesRead;",
    "",
    "    double progress = (double)totalRead / source.Length * 100;",
    "    Console.Write($\"\\r복사 진행: {progress:F1}%\");",
    "}",
    "Console.WriteLine(\"\<br>복사 완료!\");",
    "```",
    "",
    "---",
    "",
    "## 실전 예제: 로그 파일 분석",
    "",
    "```csharp",
    "static void AnalyzeLogFile(string logPath)",
    "{",
    "    var stats = new Dictionary<string, int>",
    "    {",
    "        [\"INFO\"] = 0, [\"WARN\"] = 0, [\"ERROR\"] = 0, [\"FATAL\"] = 0",
    "    };",
    "",
    "    int totalLines = 0;",
    "",
    "    foreach (string line in File.ReadLines(logPath))",
    "    {",
    "        totalLines++;",
    "        foreach (var level in stats.Keys.ToList())",
    "        {",
    "            if (line.Contains($\"[{level}]\"))",
    "                stats[level]++;",
    "        }",
    "    }",
    "",
    "    Console.WriteLine($\"총 {totalLines}줄 분석 완료:\");",
    "    foreach (var kv in stats)",
    "        Console.WriteLine($\"  {kv.Key}: {kv.Value}건\");",
    "}",
    "```",
    "",
    "## 실전 예제: 설정 파일 읽기/쓰기",
    "",
    "```csharp",
    "class AppConfig",
    "{",
    "    public string ServerUrl { get; set; } = \"http://localhost:5000\";",
    "    public int MaxRetries { get; set; } = 3;",
    "    public bool EnableLogging { get; set; } = true;",
    "    public List<string> AllowedOrigins { get; set; } = new();",
    "}",
    "",
    "// 설정 저장",
    "static void SaveConfig(AppConfig config, string path)",
    "{",
    "    var options = new JsonSerializerOptions { WriteIndented = true };",
    "    string json = JsonSerializer.Serialize(config, options);",
    "    File.WriteAllText(path, json);",
    "}",
    "",
    "// 설정 로드 (파일 없으면 기본값 생성)",
    "static AppConfig LoadConfig(string path)",
    "{",
    "    if (!File.Exists(path))",
    "    {",
    "        var defaultConfig = new AppConfig();",
    "        SaveConfig(defaultConfig, path);",
    "        return defaultConfig;",
    "    }",
    "",
    "    string json = File.ReadAllText(path);",
    "    return JsonSerializer.Deserialize<AppConfig>(json);",
    "}",
    "",
    "// 사용",
    "var config = LoadConfig(\"appsettings.json\");",
    "config.MaxRetries = 5;",
    "config.AllowedOrigins.Add(\"https://example.com\");",
    "SaveConfig(config, \"appsettings.json\");",
    "```",
    "",
    "---",
    "",
    "### 파일 I/O 클래스 정리",
    "",
    "| 클래스 | 용도 |",
    "|--------|------|",
    "| `FileStream` | 바이트 단위 파일 읽기/쓰기 |",
    "| `StreamWriter` / `StreamReader` | 텍스트 파일 |",
    "| `BinaryWriter` / `BinaryReader` | 바이너리 파일 |",
    "| `MemoryStream` | 메모리 내 스트림 처리 |",
    "| `BufferedStream` | 버퍼링을 추가한 스트림 래퍼 |",
    "| `File` | 파일 생성/복사/이동/삭제/간편 읽기·쓰기 |",
    "| `FileInfo` | 파일 메타데이터 조회 |",
    "| `Directory` / `DirectoryInfo` | 디렉터리 조작/조회 |",
    "| `Path` | 경로 문자열 안전 조작 |",
    "| `FileSystemWatcher` | 파일/디렉터리 변경 감시 |",
    "| `JsonSerializer` | JSON 직렬화/역직렬화 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
