<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "docker-commands",
  title: "도커 명령어 완벽 정리",
  date: "2026-02-25",
  summary: "도커 CLI의 상위 커맨드(Management Command)와 하위 커맨드, 주요 옵션을 실전 예시와 함께 정리합니다.",
  category: "Technology/Docker",
  tags: ["docker","cli","commands","container","image","volume","network"],
  content: [
    "## 한 줄 요약",
    "도커 CLI는 `docker <상위 커맨드> <하위 커맨드> [옵션]` 구조이며, container, image, volume, network, compose, system 등의 상위 커맨드로 모든 리소스를 관리합니다.",
    "",
    "---",
    "",
    "## 도커 명령어 구조",
    "",
    "```",
    "docker [상위 커맨드] <하위 커맨드> [옵션] [인자]",
    "",
    "예시:",
    "docker  container   run      -d -p 80:80   nginx",
    "  │        │         │          │            │",
    "  │        │         │          │            └── 인자 (이미지명)",
    "  │        │         │          └── 옵션 (-d: 백그라운드, -p: 포트)",
    "  │        │         └── 하위 커맨드 (실행)",
    "  │        └── 상위 커맨드 (컨테이너 관리)",
    "  └── docker CLI",
    "```",
    "",
    "> 일부 명령은 상위 커맨드를 생략할 수 있습니다. `docker run`은 `docker container run`의 축약형입니다.",
    "",
    "---",
    "",
    "## 상위 커맨드 (Management Commands) 전체 목록",
    "",
    "| 상위 커맨드 | 관리 대상 | 설명 |",
    "|------------|----------|------|",
    "| `container` | 컨테이너 | 컨테이너 생성, 실행, 중지, 삭제 등 |",
    "| `image` | 이미지 | 이미지 빌드, 다운로드, 삭제 등 |",
    "| `volume` | 볼륨 | 데이터 영속성을 위한 볼륨 관리 |",
    "| `network` | 네트워크 | 컨테이너 간 네트워크 관리 |",
    "| `compose` | Compose | 멀티 컨테이너 앱 관리 |",
    "| `system` | 시스템 | 디스크, 정보, 이벤트 등 |",
    "| `buildx` | 빌드 | 멀티플랫폼 이미지 빌드 |",
    "| `builder` | 빌더 | 빌드 캐시, 빌더 인스턴스 관리 |",
    "| `plugin` | 플러그인 | 도커 플러그인 관리 |",
    "| `context` | 컨텍스트 | 원격 도커 호스트 연결 관리 |",
    "",
    "---",
    "",
    "## 1. docker container (컨테이너 관리)",
    "",
    "### 하위 커맨드 목록",
    "",
    "| 하위 커맨드 | 축약형 | 설명 |",
    "|-----------|--------|------|",
    "| `container run` | `run` | 이미지로 새 컨테이너 생성 + 실행 |",
    "| `container create` | `create` | 컨테이너 생성만 (실행 X) |",
    "| `container start` | `start` | 중지된 컨테이너 시작 |",
    "| `container stop` | `stop` | 실행 중인 컨테이너 중지 (SIGTERM) |",
    "| `container kill` | `kill` | 컨테이너 강제 종료 (SIGKILL) |",
    "| `container restart` | `restart` | 컨테이너 재시작 |",
    "| `container rm` | `rm` | 컨테이너 삭제 |",
    "| `container ls` | `ps` | 컨테이너 목록 |",
    "| `container logs` | `logs` | 컨테이너 로그 출력 |",
    "| `container exec` | `exec` | 실행 중인 컨테이너에 명령 실행 |",
    "| `container inspect` | `inspect` | 컨테이너 상세 정보 (JSON) |",
    "| `container cp` | `cp` | 호스트 ↔ 컨테이너 파일 복사 |",
    "| `container stats` | `stats` | 실시간 리소스 사용량 |",
    "| `container top` | `top` | 컨테이너 내 프로세스 목록 |",
    "| `container rename` | `rename` | 컨테이너 이름 변경 |",
    "| `container pause` | `pause` | 컨테이너 일시 정지 |",
    "| `container unpause` | `unpause` | 일시 정지 해제 |",
    "| `container wait` | `wait` | 컨테이너 종료 대기 + 종료 코드 반환 |",
    "| `container diff` | `diff` | 컨테이너 파일 변경사항 확인 |",
    "| `container port` | `port` | 포트 매핑 확인 |",
    "| `container attach` | `attach` | 컨테이너 표준 입출력에 연결 |",
    "| `container commit` | `commit` | 컨테이너를 이미지로 저장 |",
    "| `container export` | `export` | 컨테이너를 tar 아카이브로 내보내기 |",
    "| `container update` | `update` | 컨테이너 리소스 제한 변경 |",
    "| `container prune` | - | 중지된 모든 컨테이너 삭제 |",
    "",
    "### docker run 주요 옵션",
    "",
    "| 옵션 | 축약 | 설명 | 예시 |",
    "|------|------|------|------|",
    "| `--detach` | `-d` | 백그라운드 실행 | `docker run -d nginx` |",
    "| `--interactive` | `-i` | 표준 입력(stdin) 열기 | `docker run -i ubuntu` |",
    "| `--tty` | `-t` | 가상 터미널 할당 | `docker run -it ubuntu bash` |",
    "| `--name` | | 컨테이너 이름 지정 | `docker run --name my-app nginx` |",
    "| `--publish` | `-p` | 포트 매핑 (호스트:컨테이너) | `docker run -p 8080:80 nginx` |",
    "| `--publish-all` | `-P` | 모든 EXPOSE 포트를 랜덤 매핑 | `docker run -P nginx` |",
    "| `--volume` | `-v` | 볼륨/바인드 마운트 | `docker run -v data:/app nginx` |",
    "| `--mount` | | 상세 마운트 설정 | `docker run --mount type=bind,src=.,dst=/app nginx` |",
    "| `--env` | `-e` | 환경 변수 설정 | `docker run -e NODE_ENV=production node` |",
    "| `--env-file` | | 환경 변수 파일 로드 | `docker run --env-file .env node` |",
    "| `--rm` | | 종료 시 자동 삭제 | `docker run --rm alpine echo hi` |",
    "| `--network` | | 네트워크 연결 | `docker run --network my-net nginx` |",
    "| `--restart` | | 재시작 정책 | `docker run --restart always nginx` |",
    "| `--memory` | `-m` | 메모리 제한 | `docker run -m 512m nginx` |",
    "| `--cpus` | | CPU 제한 | `docker run --cpus 1.5 nginx` |",
    "| `--workdir` | `-w` | 작업 디렉터리 | `docker run -w /app node` |",
    "| `--entrypoint` | | ENTRYPOINT 덮어쓰기 | `docker run --entrypoint sh nginx` |",
    "| `--user` | `-u` | 실행 사용자 | `docker run -u 1000:1000 nginx` |",
    "| `--hostname` | `-h` | 호스트명 설정 | `docker run -h myhost nginx` |",
    "| `--link` | | 다른 컨테이너 연결 (레거시) | `docker run --link db:db app` |",
    "| `--platform` | | 플랫폼 지정 | `docker run --platform linux/arm64 nginx` |",
    "",
    "### 실전 예시",
    "",
    "```bash",
    "# 기본 실행",
    "docker run nginx",
    "",
    "# 백그라운드 + 이름 + 포트 + 자동 재시작",
    "docker run -d --name web -p 80:80 --restart always nginx",
    "",
    "# 인터랙티브 셸 + 종료 시 자동 삭제",
    "docker run -it --rm ubuntu bash",
    "",
    "# 환경변수 + 볼륨 + 메모리 제한",
    "docker run -d --name api \\",
    "  -e NODE_ENV=production \\",
    "  -e DB_HOST=db \\",
    "  -v $(pwd)/src:/app/src \\",
    "  -m 512m --cpus 1 \\",
    "  -p 3000:3000 \\",
    "  my-api:v1.0",
    "",
    "# MySQL 컨테이너 (볼륨 + 환경변수)",
    "docker run -d --name mysql \\",
    "  -e MYSQL_ROOT_PASSWORD=secret \\",
    "  -e MYSQL_DATABASE=mydb \\",
    "  -v mysql-data:/var/lib/mysql \\",
    "  -p 3306:3306 \\",
    "  mysql:8",
    "```",
    "",
    "### docker ps 옵션",
    "",
    "| 옵션 | 설명 | 예시 |",
    "|------|------|------|",
    "| (없음) | 실행 중인 컨테이너만 | `docker ps` |",
    "| `-a` / `--all` | 모든 컨테이너 (중지 포함) | `docker ps -a` |",
    "| `-q` / `--quiet` | ID만 출력 | `docker ps -q` |",
    "| `-f` / `--filter` | 필터링 | `docker ps -f status=exited` |",
    "| `--format` | 출력 형식 지정 | `docker ps --format '{{.Names}} {{.Status}}'` |",
    "| `-n` / `--last` | 최근 N개만 | `docker ps -n 5` |",
    "| `-s` / `--size` | 컨테이너 크기 표시 | `docker ps -s` |",
    "",
    "```bash",
    "# 모든 컨테이너 ID만 출력 (스크립팅에 유용)",
    "docker ps -aq",
    "",
    "# 종료된 컨테이너만 필터",
    "docker ps -f status=exited",
    "",
    "# 이름과 상태만 보기",
    "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'",
    "```",
    "",
    "### docker exec 옵션",
    "",
    "| 옵션 | 설명 | 예시 |",
    "|------|------|------|",
    "| `-i` | 표준 입력 열기 | `docker exec -i web cat` |",
    "| `-t` | 가상 터미널 할당 | `docker exec -it web bash` |",
    "| `-e` | 환경 변수 설정 | `docker exec -e VAR=val web env` |",
    "| `-w` | 작업 디렉터리 | `docker exec -w /app web ls` |",
    "| `-u` | 실행 사용자 | `docker exec -u root web apt update` |",
    "",
    "```bash",
    "# 컨테이너 안에 bash 셸 접속",
    "docker exec -it my-app bash",
    "",
    "# Alpine 컨테이너 (bash 없음, sh 사용)",
    "docker exec -it my-app sh",
    "",
    "# 컨테이너 안에서 명령 실행 (접속 없이)",
    "docker exec my-app cat /etc/os-release",
    "docker exec my-db mysql -u root -p -e 'SHOW DATABASES;'",
    "```",
    "",
    "### docker logs 옵션",
    "",
    "| 옵션 | 설명 | 예시 |",
    "|------|------|------|",
    "| `-f` / `--follow` | 실시간 로그 추적 | `docker logs -f web` |",
    "| `--tail` | 마지막 N줄만 | `docker logs --tail 100 web` |",
    "| `-t` / `--timestamps` | 타임스탬프 표시 | `docker logs -t web` |",
    "| `--since` | 특정 시간 이후 | `docker logs --since 1h web` |",
    "| `--until` | 특정 시간 이전 | `docker logs --until 2026-02-25T12:00:00 web` |",
    "",
    "```bash",
    "# 최근 50줄 + 실시간 추적",
    "docker logs --tail 50 -f my-app",
    "",
    "# 최근 30분간의 로그",
    "docker logs --since 30m my-app",
    "",
    "# 타임스탬프 포함",
    "docker logs -t my-app",
    "```",
    "",
    "### docker rm / stop / kill 옵션",
    "",
    "```bash",
    "# 컨테이너 중지 (10초 후 강제 종료)",
    "docker stop my-app",
    "docker stop -t 30 my-app     # 30초 대기 후 강제 종료",
    "",
    "# 컨테이너 강제 종료",
    "docker kill my-app",
    "",
    "# 컨테이너 삭제",
    "docker rm my-app",
    "docker rm -f my-app          # 실행 중이어도 강제 삭제",
    "docker rm -v my-app          # 연결된 익명 볼륨도 삭제",
    "",
    "# 모든 중지된 컨테이너 삭제",
    "docker container prune",
    "docker container prune -f    # 확인 없이 삭제",
    "",
    "# 모든 컨테이너 중지 + 삭제 (스크립팅)",
    "docker stop $(docker ps -q)",
    "docker rm $(docker ps -aq)",
    "```",
    "",
    "### docker cp (파일 복사)",
    "",
    "```bash",
    "# 호스트 → 컨테이너",
    "docker cp ./config.json my-app:/app/config.json",
    "",
    "# 컨테이너 → 호스트",
    "docker cp my-app:/app/logs ./backup-logs",
    "",
    "# 디렉터리 통째로 복사",
    "docker cp my-app:/app/data ./local-data",
    "```",
    "",
    "### docker stats (리소스 모니터링)",
    "",
    "```bash",
    "# 전체 컨테이너 실시간 모니터링",
    "docker stats",
    "",
    "# 특정 컨테이너만",
    "docker stats my-app my-db",
    "",
    "# 한 번만 출력 (스크립팅)",
    "docker stats --no-stream",
    "",
    "# 원하는 정보만 출력",
    "docker stats --format 'table {{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}'",
    "```",
    "",
    "---",
    "",
    "## 2. docker image (이미지 관리)",
    "",
    "### 하위 커맨드 목록",
    "",
    "| 하위 커맨드 | 축약형 | 설명 |",
    "|-----------|--------|------|",
    "| `image ls` | `images` | 로컬 이미지 목록 |",
    "| `image pull` | `pull` | 레지스트리에서 이미지 다운로드 |",
    "| `image push` | `push` | 레지스트리에 이미지 업로드 |",
    "| `image build` | `build` | Dockerfile로 이미지 빌드 |",
    "| `image rm` | `rmi` | 이미지 삭제 |",
    "| `image tag` | `tag` | 이미지에 태그 추가 |",
    "| `image inspect` | - | 이미지 상세 정보 (JSON) |",
    "| `image history` | `history` | 이미지 레이어 히스토리 |",
    "| `image save` | `save` | 이미지를 tar 파일로 저장 |",
    "| `image load` | `load` | tar 파일에서 이미지 복원 |",
    "| `image import` | `import` | tar 파일을 이미지로 가져오기 |",
    "| `image prune` | - | 사용하지 않는 이미지 삭제 |",
    "",
    "### docker build 주요 옵션",
    "",
    "| 옵션 | 축약 | 설명 | 예시 |",
    "|------|------|------|------|",
    "| `--tag` | `-t` | 이미지 이름:태그 | `docker build -t my-app:v1 .` |",
    "| `--file` | `-f` | Dockerfile 경로 지정 | `docker build -f prod.Dockerfile .` |",
    "| `--build-arg` | | 빌드 인자 전달 | `docker build --build-arg NODE_ENV=prod .` |",
    "| `--no-cache` | | 캐시 없이 빌드 | `docker build --no-cache -t app .` |",
    "| `--target` | | 멀티스테이지 빌드 대상 | `docker build --target builder .` |",
    "| `--platform` | | 빌드 플랫폼 | `docker build --platform linux/amd64 .` |",
    "| `--progress` | | 출력 형식 | `docker build --progress plain .` |",
    "| `--pull` | | 베이스 이미지 항상 최신 다운 | `docker build --pull -t app .` |",
    "",
    "### 실전 예시",
    "",
    "```bash",
    "# 기본 빌드",
    "docker build -t my-app .",
    "",
    "# 태그 여러 개",
    "docker build -t my-app:v1.0 -t my-app:latest .",
    "",
    "# 빌드 인자 전달 + 캐시 무시",
    "docker build --build-arg API_URL=https://api.example.com \\",
    "  --no-cache -t my-app:v2.0 .",
    "",
    "# 다른 Dockerfile 사용",
    "docker build -f Dockerfile.prod -t my-app:prod .",
    "",
    "# 이미지 다운로드",
    "docker pull nginx:1.25-alpine",
    "",
    "# 이미지 목록",
    "docker images",
    "docker images --format 'table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}'",
    "",
    "# 이미지 삭제",
    "docker rmi nginx:1.25-alpine",
    "docker rmi $(docker images -q)    # 모든 이미지 삭제",
    "",
    "# 이미지 태그 추가",
    "docker tag my-app:v1.0 myuser/my-app:v1.0",
    "docker tag my-app:v1.0 myuser/my-app:latest",
    "",
    "# Docker Hub에 push",
    "docker login",
    "docker push myuser/my-app:v1.0",
    "docker push myuser/my-app:latest",
    "",
    "# 이미지 레이어 확인",
    "docker history my-app:v1.0",
    "",
    "# 이미지를 파일로 저장/복원 (오프라인 배포)",
    "docker save -o my-app.tar my-app:v1.0",
    "docker load -i my-app.tar",
    "",
    "# 사용하지 않는 이미지 정리",
    "docker image prune        # 태그 없는 이미지(dangling)",
    "docker image prune -a     # 사용하지 않는 모든 이미지",
    "```",
    "",
    "---",
    "",
    "## 3. docker volume (볼륨 관리)",
    "",
    "### 하위 커맨드 목록",
    "",
    "| 하위 커맨드 | 설명 |",
    "|-----------|------|",
    "| `volume create` | 볼륨 생성 |",
    "| `volume ls` | 볼륨 목록 |",
    "| `volume inspect` | 볼륨 상세 정보 |",
    "| `volume rm` | 볼륨 삭제 |",
    "| `volume prune` | 사용하지 않는 볼륨 삭제 |",
    "",
    "### 실전 예시",
    "",
    "```bash",
    "# 볼륨 생성",
    "docker volume create my-data",
    "",
    "# 볼륨 목록",
    "docker volume ls",
    "",
    "# 볼륨 상세 정보 (마운트 경로 등)",
    "docker volume inspect my-data",
    "",
    "# 볼륨 사용 (이름 있는 볼륨)",
    "docker run -d -v my-data:/var/lib/mysql mysql:8",
    "",
    "# 바인드 마운트 (호스트 경로 직접 지정)",
    "docker run -d -v $(pwd)/src:/app/src my-app",
    "",
    "# 읽기 전용 마운트",
    "docker run -d -v $(pwd)/config:/app/config:ro my-app",
    "",
    "# 볼륨 삭제",
    "docker volume rm my-data",
    "",
    "# 사용하지 않는 볼륨 전부 삭제",
    "docker volume prune -f",
    "```",
    "",
    "### 마운트 타입 비교",
    "",
    "| 타입 | 옵션 | 특징 |",
    "|------|------|------|",
    "| **이름 있는 볼륨** | `-v my-vol:/app/data` | 도커가 관리, 이식성 좋음 |",
    "| **바인드 마운트** | `-v /host/path:/app/data` | 호스트 경로 직접 지정, 개발용 |",
    "| **tmpfs 마운트** | `--tmpfs /app/tmp` | 메모리에만 저장, 임시 데이터용 |",
    "",
    "---",
    "",
    "## 4. docker network (네트워크 관리)",
    "",
    "### 하위 커맨드 목록",
    "",
    "| 하위 커맨드 | 설명 |",
    "|-----------|------|",
    "| `network create` | 네트워크 생성 |",
    "| `network ls` | 네트워크 목록 |",
    "| `network inspect` | 네트워크 상세 정보 |",
    "| `network rm` | 네트워크 삭제 |",
    "| `network connect` | 컨테이너를 네트워크에 연결 |",
    "| `network disconnect` | 컨테이너를 네트워크에서 분리 |",
    "| `network prune` | 사용하지 않는 네트워크 삭제 |",
    "",
    "### 네트워크 드라이버",
    "",
    "| 드라이버 | 설명 |",
    "|---------|------|",
    "| `bridge` | 기본값, 같은 호스트의 컨테이너 간 통신 |",
    "| `host` | 호스트 네트워크 직접 사용 (포트 매핑 불필요) |",
    "| `none` | 네트워크 비활성화 |",
    "| `overlay` | 여러 호스트의 컨테이너 간 통신 (Swarm) |",
    "",
    "### 실전 예시",
    "",
    "```bash",
    "# 네트워크 생성",
    "docker network create my-net",
    "docker network create --driver bridge my-net",
    "",
    "# 네트워크 목록",
    "docker network ls",
    "",
    "# 네트워크에 연결된 컨테이너로 실행",
    "docker run -d --name api --network my-net my-api",
    "docker run -d --name db --network my-net mysql:8",
    "",
    "# 같은 네트워크 안에서는 컨테이너 이름으로 접근 가능",
    "# api 컨테이너에서: mysql -h db -u root -p",
    "",
    "# 실행 중인 컨테이너를 네트워크에 추가",
    "docker network connect my-net existing-container",
    "",
    "# 네트워크에서 분리",
    "docker network disconnect my-net existing-container",
    "",
    "# 네트워크 상세 정보 (연결된 컨테이너 확인)",
    "docker network inspect my-net",
    "",
    "# 호스트 네트워크 모드 (포트 매핑 없이 직접 사용)",
    "docker run -d --network host nginx",
    "",
    "# 사용하지 않는 네트워크 삭제",
    "docker network prune -f",
    "```",
    "",
    "---",
    "",
    "## 5. docker compose (멀티 컨테이너 관리)",
    "",
    "### 하위 커맨드 목록",
    "",
    "| 하위 커맨드 | 설명 |",
    "|-----------|------|",
    "| `compose up` | 서비스 생성 + 시작 |",
    "| `compose down` | 서비스 중지 + 삭제 |",
    "| `compose start` | 중지된 서비스 시작 |",
    "| `compose stop` | 서비스 중지 |",
    "| `compose restart` | 서비스 재시작 |",
    "| `compose ps` | 서비스 목록 |",
    "| `compose logs` | 서비스 로그 |",
    "| `compose exec` | 서비스 컨테이너에 명령 실행 |",
    "| `compose build` | 서비스 이미지 빌드 |",
    "| `compose pull` | 서비스 이미지 다운로드 |",
    "| `compose config` | Compose 파일 유효성 검사 |",
    "| `compose top` | 서비스 프로세스 목록 |",
    "| `compose images` | 서비스 이미지 목록 |",
    "| `compose run` | 일회성 명령 실행 |",
    "| `compose watch` | 파일 변경 감지 + 자동 동기화 |",
    "",
    "### docker compose up 주요 옵션",
    "",
    "| 옵션 | 설명 | 예시 |",
    "|------|------|------|",
    "| `-d` | 백그라운드 실행 | `docker compose up -d` |",
    "| `--build` | 이미지 강제 재빌드 | `docker compose up --build` |",
    "| `--force-recreate` | 컨테이너 강제 재생성 | `docker compose up --force-recreate` |",
    "| `--scale` | 서비스 인스턴스 수 | `docker compose up --scale api=3` |",
    "| `-f` | Compose 파일 지정 | `docker compose -f prod.yml up` |",
    "| `--remove-orphans` | 정의에 없는 컨테이너 삭제 | `docker compose up --remove-orphans` |",
    "",
    "### docker compose down 주요 옵션",
    "",
    "| 옵션 | 설명 | 예시 |",
    "|------|------|------|",
    "| `-v` / `--volumes` | 볼륨도 삭제 | `docker compose down -v` |",
    "| `--rmi all` | 이미지도 삭제 | `docker compose down --rmi all` |",
    "| `--remove-orphans` | 고아 컨테이너 삭제 | `docker compose down --remove-orphans` |",
    "",
    "### 실전 예시",
    "",
    "```bash",
    "# 서비스 시작 (백그라운드)",
    "docker compose up -d",
    "",
    "# 이미지 재빌드 + 시작",
    "docker compose up -d --build",
    "",
    "# 서비스 중지 + 삭제",
    "docker compose down",
    "",
    "# 볼륨까지 삭제 (데이터 초기화)",
    "docker compose down -v",
    "",
    "# 특정 서비스만 시작",
    "docker compose up -d api db",
    "",
    "# 서비스 로그 (실시간)",
    "docker compose logs -f",
    "docker compose logs -f api     # 특정 서비스만",
    "",
    "# 서비스 컨테이너에 접속",
    "docker compose exec api bash",
    "",
    "# 일회성 명령 실행",
    "docker compose run --rm api npm test",
    "",
    "# Compose 파일 유효성 검사",
    "docker compose config",
    "",
    "# 서비스 상태 확인",
    "docker compose ps",
    "```",
    "",
    "---",
    "",
    "## 6. docker system (시스템 관리)",
    "",
    "### 하위 커맨드 목록",
    "",
    "| 하위 커맨드 | 설명 |",
    "|-----------|------|",
    "| `system df` | 디스크 사용량 확인 |",
    "| `system prune` | 사용하지 않는 모든 리소스 삭제 |",
    "| `system info` | 도커 시스템 정보 |",
    "| `system events` | 실시간 이벤트 모니터링 |",
    "",
    "### 실전 예시",
    "",
    "```bash",
    "# 디스크 사용량 확인",
    "docker system df",
    "docker system df -v     # 상세 (각 이미지/컨테이너/볼륨별)",
    "",
    "# 출력 예시:",
    "# TYPE          TOTAL   ACTIVE   SIZE      RECLAIMABLE",
    "# Images        15      5        3.2GB     1.8GB (56%)",
    "# Containers    8       3        150MB     100MB (66%)",
    "# Volumes       5       3        500MB     200MB (40%)",
    "",
    "# 사용하지 않는 모든 리소스 정리",
    "docker system prune",
    "docker system prune -a          # 사용하지 않는 이미지도 포함",
    "docker system prune -a -f       # 확인 없이 강제",
    "docker system prune --volumes   # 볼륨도 포함",
    "",
    "# 도커 시스템 정보",
    "docker system info",
    "# = docker info",
    "",
    "# 실시간 이벤트 (컨테이너 생성/시작/중지 등)",
    "docker system events",
    "docker system events --filter type=container",
    "```",
    "",
    "---",
    "",
    "## 7. 기타 유용한 최상위 명령어",
    "",
    "| 명령어 | 설명 | 예시 |",
    "|--------|------|------|",
    "| `docker version` | 클라이언트/서버 버전 | `docker version` |",
    "| `docker info` | 시스템 정보 | `docker info` |",
    "| `docker login` | 레지스트리 로그인 | `docker login` |",
    "| `docker logout` | 레지스트리 로그아웃 | `docker logout` |",
    "| `docker search` | Docker Hub 이미지 검색 | `docker search nginx` |",
    "| `docker inspect` | 리소스 상세 정보 | `docker inspect my-app` |",
    "",
    "```bash",
    "# 버전 확인",
    "docker version",
    "docker --version",
    "",
    "# Docker Hub 이미지 검색",
    "docker search nginx --limit 5",
    "",
    "# 이미지/컨테이너/네트워크 상세 정보",
    "docker inspect my-app",
    "docker inspect --format '{{.State.Status}}' my-app",
    "docker inspect --format '{{.NetworkSettings.IPAddress}}' my-app",
    "```",
    "",
    "---",
    "",
    "## 자주 쓰는 명령어 조합 (스크립팅)",
    "",
    "```bash",
    "# 모든 컨테이너 중지",
    "docker stop $(docker ps -q)",
    "",
    "# 모든 컨테이너 삭제",
    "docker rm $(docker ps -aq)",
    "",
    "# 모든 이미지 삭제",
    "docker rmi $(docker images -q)",
    "",
    "# dangling 이미지만 삭제 (<none> 태그)",
    "docker rmi $(docker images -f dangling=true -q)",
    "",
    "# 특정 이미지 기반 컨테이너 모두 삭제",
    "docker rm $(docker ps -aq -f ancestor=nginx)",
    "",
    "# 전체 초기화 (주의!)",
    "docker system prune -a --volumes -f",
    "",
    "# 컨테이너 리소스 사용량 한 줄 요약",
    "docker stats --no-stream --format 'table {{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}'",
    "```",
    "",
    "---",
    "",
    "## 전체 명령어 요약표",
    "",
    "| 카테고리 | 주요 명령어 | 설명 |",
    "|---------|-----------|------|",
    "| **컨테이너** | `run`, `ps`, `stop`, `rm`, `exec`, `logs` | 컨테이너 생명 주기 관리 |",
    "| **이미지** | `build`, `pull`, `push`, `images`, `rmi`, `tag` | 이미지 빌드·배포 |",
    "| **볼륨** | `volume create`, `volume ls`, `volume rm` | 데이터 영속성 |",
    "| **네트워크** | `network create`, `network ls`, `network connect` | 컨테이너 간 통신 |",
    "| **Compose** | `compose up`, `compose down`, `compose logs` | 멀티 컨테이너 관리 |",
    "| **시스템** | `system df`, `system prune`, `info`, `version` | 시스템 관리·정리 |",
    "",
    "### 요약",
    "도커 CLI는 `docker <상위 커맨드> <하위 커맨드> [옵션]` 구조입니다. **container**(컨테이너), **image**(이미지), **volume**(볼륨), **network**(네트워크), **compose**(멀티 컨테이너), **system**(시스템)이 핵심 상위 커맨드이며, 각각 `create`, `ls`, `rm`, `inspect`, `prune` 등의 하위 커맨드를 가집니다. `docker run -d -p -v -e --name` 옵션 조합이 가장 자주 사용됩니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
