<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "docker-core-concepts",
  title: "도커 핵심 개념: 도커, 컨테이너, 도커 엔진, 이미지",
  date: "2026-02-11",
  summary: "도커(Docker)와 컨테이너, 도커 엔진, 이미지의 개념과 이들 간의 관계를 정리합니다.",
  category: "Technology/Docker",
  tags: ["docker","container","image","engine","devops"],
  content: [
    "## 한 줄 요약",
    "도커는 **이미지**라는 템플릿으로 **컨테이너**라는 격리된 실행 환경을 만들고, **도커 엔진**이 이 전체 과정을 관리합니다.",
    "",
    "---",
    "",
    "## 4가지 핵심 개념 관계도",
    "",
    "```mermaid",
    "flowchart LR",
    "  subgraph Docker[\"도커 Docker = 컨테이너 플랫폼 전체\"]",
    "    A[\"이미지 (읽기전용)\"] --> B[\"도커 엔진 (dockerd)\"] --> C[\"컨테이너 (실행중)\"]",
    "  end",
    "```",
    "",
    "---",
    "",
    "## 1. 도커(Docker)란?",
    "",
    "도커는 애플리케이션을 **컨테이너**라는 격리된 환경에서 실행하고 배포하기 위한 **오픈소스 플랫폼**입니다.",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 만든 곳 | Docker, Inc. (2013년 출시) |",
    "| 핵심 기능 | 앱을 컨테이너로 패키징, 실행, 배포 |",
    "| 비유 | 택배 상자 — 내용물이 뭐든 같은 규격으로 운반 |",
    "",
    "### 도커가 해결하는 문제",
    "",
    "```",
    "도커 없이:",
    "개발자 PC(Windows) → 서버(Linux) → 테스트 서버(다른 Linux)",
    "\"내 컴퓨터에서는 되는데...\" 😫",
    "",
    "도커 사용:",
    "이미지 하나 → 어디서든 동일하게 실행",
    "\"이미지만 있으면 어디서든 됩니다\" ✅",
    "```",
    "",
    "---",
    "",
    "## 2. 컨테이너(Container)란?",
    "",
    "컨테이너는 애플리케이션과 그 실행에 필요한 모든 것(코드, 라이브러리, 설정)을 담은 **격리된 실행 환경**입니다.",
    "",
    "### 컨테이너의 특징",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| 격리됨 | 다른 컨테이너, 호스트와 분리된 환경 |",
    "| 가벼움 | VM과 달리 OS 전체가 아닌 프로세스 수준 |",
    "| 빠름 | 1초 이내에 시작/중지 가능 |",
    "| 일회용 | 삭제 후 다시 만들어도 동일한 환경 |",
    "| 이식성 | 어디서든 동일하게 동작 |",
    "",
    "### 컨테이너 기본 명령어",
    "",
    "```bash",
    "# 컨테이너 생성 + 실행",
    "docker run nginx",
    "",
    "# 백그라운드 실행 (-d: detach)",
    "docker run -d --name my-nginx nginx",
    "",
    "# 실행 중인 컨테이너 목록",
    "docker ps",
    "",
    "# 모든 컨테이너 (중지 포함)",
    "docker ps -a",
    "",
    "# 컨테이너 중지 / 시작 / 재시작",
    "docker stop my-nginx",
    "docker start my-nginx",
    "docker restart my-nginx",
    "",
    "# 컨테이너 삭제",
    "docker rm my-nginx",
    "",
    "# 컨테이너 안으로 들어가기",
    "docker exec -it my-nginx bash",
    "",
    "# 컨테이너 로그 보기",
    "docker logs my-nginx",
    "docker logs -f my-nginx    # 실시간 추적",
    "```",
    "",
    "### 컨테이너 생명 주기",
    "",
    "```mermaid",
    "flowchart LR",
    "  A[\"이미지\"] -->|docker run| B[\"Created\"]",
    "  B -->|start| C[\"Running\"]",
    "  C -->|stop| D[\"Stopped\"]",
    "  D -->|rm| E[\"삭제\"]",
    "  D -->|restart| C",
    "```",
    "",
    "---",
    "",
    "## 3. 도커 이미지(Image)란?",
    "",
    "이미지는 컨테이너를 만들기 위한 **읽기 전용 템플릿**입니다. 애플리케이션 코드, 런타임, 라이브러리, 환경 변수, 설정 파일 등이 모두 포함됩니다.",
    "",
    "### 프로그래밍 비유",
    "",
    "| 프로그래밍 | 도커 |",
    "|-----------|------|",
    "| 클래스 (설계도) | 이미지 |",
    "| 인스턴스 (객체) | 컨테이너 |",
    "| new 키워드 | docker run |",
    "",
    "### 이미지 기본 명령어",
    "",
    "```bash",
    "# 이미지 다운로드",
    "docker pull nginx",
    "docker pull node:20-alpine",
    "",
    "# 로컬 이미지 목록",
    "docker images",
    "",
    "# 이미지 삭제",
    "docker rmi nginx",
    "",
    "# 이미지 검색",
    "docker search nginx",
    "",
    "# 이미지 상세 정보",
    "docker inspect nginx",
    "```",
    "",
    "### 이미지 태그",
    "",
    "이미지 이름은 `이름:태그` 형태입니다.",
    "",
    "```bash",
    "docker pull node          # node:latest와 동일",
    "docker pull node:20       # Node.js 20 버전",
    "docker pull node:20-alpine   # Node.js 20, Alpine 기반 (경량)",
    "docker pull node:20-slim     # Node.js 20, Debian Slim 기반",
    "```",
    "",
    "| 태그 패턴 | 의미 |",
    "|----------|------|",
    "| `latest` | 가장 최신 (기본값, 프로덕션 비권장) |",
    "| `20`, `3.12` | 특정 메이저 버전 |",
    "| `20.11.0` | 정확한 버전 |",
    "| `alpine` | Alpine Linux 기반 (경량, ~5MB) |",
    "| `slim` | 불필요한 패키지 제거 (중간 크기) |",
    "| `bullseye`, `bookworm` | Debian 코드네임 |",
    "",
    "### 이미지 레이어",
    "",
    "이미지는 여러 **레이어**로 구성되며, 각 레이어는 Dockerfile의 명령 하나에 대응합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "  L4[\"Layer 4: COPY . .  ← 내 앱 코드\"]",
    "  L3[\"Layer 3: RUN npm i  ← npm 패키지\"]",
    "  L2[\"Layer 2: node:20  ← Node.js 런타임\"]",
    "  L1[\"Layer 1: alpine  ← 기본 OS (rootfs)\"]",
    "  L4 --- L3 --- L2 --- L1",
    "```",
    "",
    "> 레이어는 **캐싱**됩니다. 변경되지 않은 레이어는 다시 다운로드하지 않아 빌드와 배포가 빨라집니다.",
    "",
    "---",
    "",
    "## 4. 도커 엔진(Docker Engine)이란?",
    "",
    "도커 엔진은 이미지를 가져와 컨테이너를 생성·실행·관리하는 **핵심 프로그램**입니다.",
    "",
    "### 도커 엔진 아키텍처",
    "",
    "```mermaid",
    "flowchart TD",
    "  A[\"사용자\"] -->|docker run nginx| B[\"Docker CLI (docker)<br>명령어 입력 도구\"]",
    "  B -->|REST API| C[\"Docker Daemon (dockerd)<br>핵심 서비스\"]",
    "  C --> D[\"containerd<br>컨테이너 런타임 관리\"]",
    "  D --> E[\"runc<br>실제 컨테이너 프로세스 생성\"]",
    "```",
    "",
    "### 각 구성요소 역할",
    "",
    "| 구성요소 | 역할 | 비유 |",
    "|----------|------|------|",
    "| **Docker CLI** | 사용자가 입력하는 명령어 도구 | 리모컨 |",
    "| **dockerd** (데몬) | 이미지 관리, 네트워크, 볼륨, API 처리 | 관제 센터 |",
    "| **containerd** | 컨테이너의 생명 주기 관리 (생성~삭제) | 공장 관리자 |",
    "| **runc** | Linux namespace/cgroup으로 컨테이너 프로세스 생성 | 실제 노동자 |",
    "",
    "### docker run 실행 흐름",
    "",
    "```",
    "1. docker run nginx",
    "2. Docker CLI → dockerd에 REST API 요청",
    "3. dockerd: 이미지가 로컬에 있나? 없으면 Docker Hub에서 pull",
    "4. dockerd → containerd에 컨테이너 생성 요청",
    "5. containerd → runc 실행",
    "6. runc: namespace + cgroup 생성 → 프로세스 실행",
    "7. 컨테이너 실행 완료!",
    "```",
    "",
    "---",
    "",
    "## Dockerfile로 이미지 만들기",
    "",
    "Dockerfile은 이미지를 만드는 **레시피(스크립트)**입니다.",
    "",
    "```dockerfile",
    "# 베이스 이미지 선택",
    "FROM node:20-alpine",
    "",
    "# 작업 디렉터리 설정",
    "WORKDIR /app",
    "",
    "# 의존성 파일 복사 + 설치",
    "COPY package*.json ./",
    "RUN npm install",
    "",
    "# 소스 코드 복사",
    "COPY . .",
    "",
    "# 포트 노출",
    "EXPOSE 3000",
    "",
    "# 실행 명령",
    "CMD [\"node\", \"server.js\"]",
    "```",
    "",
    "### 주요 Dockerfile 명령어",
    "",
    "| 명령어 | 역할 | 예시 |",
    "|--------|------|------|",
    "| `FROM` | 베이스 이미지 | `FROM node:20-alpine` |",
    "| `WORKDIR` | 작업 디렉터리 | `WORKDIR /app` |",
    "| `COPY` | 파일 복사 (호스트 → 이미지) | `COPY . .` |",
    "| `RUN` | 빌드 시 명령 실행 | `RUN npm install` |",
    "| `CMD` | 컨테이너 시작 시 기본 명령 | `CMD [\"node\", \"app.js\"]` |",
    "| `EXPOSE` | 포트 문서화 | `EXPOSE 3000` |",
    "| `ENV` | 환경 변수 | `ENV NODE_ENV=production` |",
    "| `ENTRYPOINT` | 고정 실행 명령 | `ENTRYPOINT [\"python\"]` |",
    "",
    "### 이미지 빌드 + 실행",
    "",
    "```bash",
    "# 이미지 빌드 (-t: 태그 이름)",
    "docker build -t my-app .",
    "",
    "# 빌드한 이미지로 컨테이너 실행",
    "docker run -d -p 3000:3000 my-app",
    "",
    "# http://localhost:3000 에서 확인",
    "```",
    "",
    "---",
    "",
    "## 4가지 개념 한눈에 정리",
    "",
    "| 개념 | 정의 | 비유 |",
    "|------|------|------|",
    "| **도커** | 컨테이너 기반 앱을 실행·배포하는 플랫폼 | 택배 시스템 전체 |",
    "| **이미지** | 컨테이너를 만들기 위한 읽기 전용 템플릿 | 설계도 / 레시피 |",
    "| **컨테이너** | 이미지로부터 생성된 격리된 실행 환경 | 실제 요리된 음식 |",
    "| **도커 엔진** | 이미지를 받아 컨테이너를 생성·관리하는 프로그램 | 요리사 |",
    "",
    "### 요약",
    "도커는 **이미지**(읽기 전용 템플릿)로 **컨테이너**(격리된 실행 환경)를 만드는 플랫폼이며, **도커 엔진**(dockerd → containerd → runc)이 이 전체 과정을 관리합니다. Dockerfile로 이미지를 정의하고, `docker build`로 빌드하고, `docker run`으로 컨테이너를 실행합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
