<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "git-fork-pullrequest",
  title: "GitHub Fork와 Pull Request 완벽 가이드",
  date: "2026-02-25",
  summary: "Fork와 Pull Request의 개념, 오픈소스 기여 흐름, Fork 동기화, PR 작성법과 코드 리뷰까지 실습과 함께 정리합니다.",
  category: "Technology/Git",
  tags: ["git","github","fork","pull-request","pr","open-source","code-review"],
  content: [
    "## 한 줄 요약",
    "**Fork**는 다른 사람의 저장소를 내 계정으로 복사하는 것이고, **Pull Request(PR)**는 내가 수정한 코드를 원본 저장소에 합쳐달라고 요청하는 것입니다.",
    "",
    "---",
    "",
    "## Fork와 Pull Request 전체 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant U as 원본 저장소 (upstream)",
    "    participant O as 내 저장소 (origin)",
    "    participant L as 내 PC (local)",
    "    U->>O: ① Fork",
    "    O->>L: ② Clone",
    "    L->>L: ③ 수정 + 커밋",
    "    L->>O: ④ Push",
    "    O->>U: ⑤ PR 생성",
    "    U->>U: ⑥ PR 리뷰 + 병합",
    "```",
    "",
    "| 단계 | 동작 | 명령/위치 |",
    "|------|------|----------|",
    "| ① Fork | 원본 → 내 계정으로 복사 | GitHub 웹 |",
    "| ② Clone | 내 저장소 → 내 PC | `git clone` |",
    "| ③ 수정 + 커밋 | 코드 수정, 브랜치 생성 | `git add`, `git commit` |",
    "| ④ Push | 내 PC → 내 저장소 | `git push` |",
    "| ⑤ PR 생성 | 내 저장소 → 원본에 요청 | GitHub 웹 |",
    "| ⑥ 병합 | 원본 관리자가 승인 후 merge | GitHub 웹 |",
    "",
    "---",
    "",
    "## Fork란?",
    "",
    "Fork는 **다른 사람의 GitHub 저장소를 내 계정으로 통째로 복사**하는 것입니다.",
    "",
    "```",
    "Clone vs Fork:",
    "",
    "Clone:  원본 저장소 → 내 PC (로컬 복사)",
    "Fork:   원본 저장소 → 내 GitHub 계정 (원격 복사)",
    "```",
    "",
    "| 구분 | Clone | Fork |",
    "|------|-------|------|",
    "| 복사 위치 | 내 PC (로컬) | 내 GitHub 계정 (원격) |",
    "| push 권한 | 원본에 권한 있어야 가능 | 내 Fork에는 자유롭게 push |",
    "| 용도 | 팀 프로젝트 (권한 있을 때) | 오픈소스 기여 (권한 없을 때) |",
    "| 원본과 연결 | origin = 원본 | origin = 내 Fork, upstream = 원본 |",
    "",
    "### Fork 하는 방법",
    "",
    "1. 기여하고 싶은 GitHub 저장소 페이지로 이동",
    "2. 오른쪽 상단 **Fork** 버튼 클릭",
    "3. Owner(내 계정) 확인 → **Create fork** 클릭",
    "4. 내 계정에 `내아이디/저장소명` 저장소가 생성됨",
    "",
    "> Fork한 저장소에는 \"forked from 원본아이디/저장소명\"이 표시됩니다.",
    "",
    "---",
    "",
    "## 실습: Fork부터 PR까지",
    "",
    "### 1단계: Fork + Clone",
    "",
    "```bash",
    "# Fork한 내 저장소를 로컬에 clone",
    "git clone https://github.com/내아이디/project.git",
    "cd project",
    "",
    "# 원본 저장소를 upstream으로 등록",
    "git remote add upstream https://github.com/원본아이디/project.git",
    "",
    "# remote 확인",
    "git remote -v",
    "# origin    https://github.com/내아이디/project.git (fetch)",
    "# origin    https://github.com/내아이디/project.git (push)",
    "# upstream  https://github.com/원본아이디/project.git (fetch)",
    "# upstream  https://github.com/원본아이디/project.git (push)",
    "```",
    "",
    "```",
    "remote 구조:",
    "",
    "upstream (원본)     origin (내 Fork)      local (내 PC)",
    "원본아이디/project   내아이디/project       ~/project",
    "```",
    "",
    "### 2단계: 브랜치 생성 + 작업",
    "",
    "```bash",
    "# 최신 코드 동기화",
    "git fetch upstream",
    "git merge upstream/main",
    "",
    "# 기능 브랜치 생성",
    "git switch -c fix/typo-in-readme",
    "",
    "# 코드 수정",
    "# ... 파일 수정 ...",
    "",
    "# 커밋",
    "git add .",
    "git commit -m \"fix: README 오타 수정\"",
    "```",
    "",
    "> **반드시 브랜치를 만들어서 작업하세요.** main에서 직접 수정하면 나중에 동기화가 복잡해집니다.",
    "",
    "### 3단계: Push (내 Fork에)",
    "",
    "```bash",
    "# 내 Fork(origin)에 브랜치 push",
    "git push origin fix/typo-in-readme",
    "```",
    "",
    "### 4단계: Pull Request 생성",
    "",
    "1. GitHub에서 **내 Fork 저장소** 페이지로 이동",
    "2. 상단에 **Compare & pull request** 버튼이 나타남 → 클릭",
    "3. PR 내용 작성:",
    "",
    "```",
    "┌─────────────────────────────────────────────┐",
    "│ base repository: 원본아이디/project          │",
    "│ base: main                                   │",
    "│              ←                               │",
    "│ head repository: 내아이디/project             │",
    "│ compare: fix/typo-in-readme                  │",
    "├─────────────────────────────────────────────┤",
    "│ Title: fix: README 오타 수정                  │",
    "├─────────────────────────────────────────────┤",
    "│ Description:                                 │",
    "│ ## 변경 내용                                  │",
    "│ - README.md의 오타를 수정했습니다              │",
    "│                                              │",
    "│ ## 관련 이슈                                  │",
    "│ - Closes #42                                 │",
    "└─────────────────────────────────────────────┘",
    "```",
    "",
    "4. **Create pull request** 클릭",
    "",
    "### 5단계: 코드 리뷰 + 병합",
    "",
    "```",
    "PR 생성 후 흐름:",
    "",
    "PR 생성 → 리뷰어 지정 → 코드 리뷰 → 수정 요청 → 재수정 → 승인 → Merge",
    "```",
    "",
    "- 원본 관리자가 코드를 리뷰합니다",
    "- 수정 요청이 오면 같은 브랜치에 추가 커밋 후 push하면 PR에 자동 반영됩니다",
    "- 승인되면 관리자가 **Merge** 버튼을 클릭합니다",
    "",
    "---",
    "",
    "## Fork 동기화 (원본 최신 코드 가져오기)",
    "",
    "원본 저장소가 업데이트되면 내 Fork에도 반영해야 합니다.",
    "",
    "```bash",
    "# 원본(upstream)의 최신 코드 가져오기",
    "git fetch upstream",
    "",
    "# main 브랜치로 이동",
    "git switch main",
    "",
    "# 원본의 main을 내 main에 병합",
    "git merge upstream/main",
    "",
    "# 내 Fork(origin)에도 반영",
    "git push origin main",
    "```",
    "",
    "동기화 흐름:",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"upstream/main<br>(원본 최신)\"] -->|fetch| B[\"local/main<br>(내 PC)\"]",
    "    B -->|push| C[\"origin/main<br>(내 Fork)\"]",
    "```",
    "",
    "### GitHub 웹에서 동기화",
    "",
    "Fork한 저장소 페이지에서 **Sync fork** → **Update branch** 버튼으로도 가능합니다.",
    "",
    "---",
    "",
    "## Pull Request 작성법",
    "",
    "### 좋은 PR 제목",
    "",
    "| 접두사 | 용도 | 예시 |",
    "|--------|------|------|",
    "| `feat:` | 새 기능 | `feat: 다크모드 추가` |",
    "| `fix:` | 버그 수정 | `fix: 로그인 시 비밀번호 검증 오류` |",
    "| `docs:` | 문서 수정 | `docs: README 설치 방법 업데이트` |",
    "| `style:` | 코드 스타일 | `style: 들여쓰기 정리` |",
    "| `refactor:` | 리팩토링 | `refactor: 인증 모듈 구조 개선` |",
    "| `test:` | 테스트 | `test: 로그인 유닛 테스트 추가` |",
    "| `chore:` | 빌드/설정 | `chore: ESLint 설정 업데이트` |",
    "",
    "### PR 본문 템플릿",
    "",
    "```markdown",
    "## 변경 내용",
    "- 어떤 변경을 했는지 구체적으로",
    "",
    "## 변경 이유",
    "- 왜 이 변경이 필요한지",
    "",
    "## 테스트 방법",
    "- 어떻게 테스트할 수 있는지",
    "",
    "## 스크린샷 (UI 변경 시)",
    "- 변경 전/후 스크린샷",
    "",
    "## 관련 이슈",
    "- Closes #이슈번호",
    "```",
    "",
    "> `Closes #42`를 본문에 넣으면 PR이 병합될 때 **이슈 #42가 자동으로 닫힙니다.**",
    "",
    "---",
    "",
    "## 코드 리뷰",
    "",
    "### 리뷰어 (코드를 검토하는 사람)",
    "",
    "PR의 **Files changed** 탭에서 변경된 코드를 줄 단위로 확인하고 댓글을 남깁니다.",
    "",
    "| 리뷰 결과 | 의미 |",
    "|-----------|------|",
    "| **Approve** | 승인 (병합 가능) |",
    "| **Request changes** | 수정 요청 (수정 후 다시 리뷰) |",
    "| **Comment** | 의견만 남김 (승인/거부 아님) |",
    "",
    "### 수정 요청 대응",
    "",
    "```bash",
    "# 리뷰어가 수정 요청을 하면",
    "# 같은 브랜치에서 수정 후 push하면 PR에 자동 반영",
    "",
    "# 코드 수정",
    "# ... 파일 수정 ...",
    "",
    "git add .",
    "git commit -m \"fix: 리뷰 반영 - 변수명 수정\"",
    "git push origin fix/typo-in-readme",
    "",
    "# PR 페이지에 새 커밋이 자동으로 추가됨",
    "```",
    "",
    "---",
    "",
    "## PR 병합 방식",
    "",
    "| 방식 | 설명 | 히스토리 |",
    "|------|------|---------|",
    "| **Merge commit** | 병합 커밋 생성 (기본값) | 브랜치 그래프 유지 |",
    "| **Squash and merge** | PR의 모든 커밋을 1개로 합침 | 깔끔한 히스토리 |",
    "| **Rebase and merge** | 커밋을 재배치 (일직선) | 가장 깔끔 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    subgraph mc[\"Merge commit\"]",
    "        direction LR",
    "        mcPR[\"A ← B ← C ← D\"] --> mcM[\"M (병합 커밋)\"]",
    "        mcMain[main] --> mcM",
    "    end",
    "    subgraph sq[\"Squash and merge\"]",
    "        direction LR",
    "        sqPR[\"A, B, C, D (PR 커밋들)\"] -->|squash| sqS[\"S (1개 커밋) → main\"]",
    "    end",
    "    subgraph rb[\"Rebase and merge\"]",
    "        direction LR",
    "        rbMain[main] --> rbA[\"A'\"] --> rbB[\"B'\"] --> rbC[\"C'\"] --> rbD[\"D'\"]",
    "    end",
    "```",
    "",
    "> 오픈소스 프로젝트는 보통 **Squash and merge**를 선호합니다. PR 하나가 커밋 하나가 되어 히스토리가 깔끔합니다.",
    "",
    "---",
    "",
    "## 오픈소스 기여 체크리스트",
    "",
    "오픈소스 프로젝트에 PR을 보내기 전 확인할 것:",
    "",
    "| 순서 | 확인 사항 |",
    "|------|----------|",
    "| 1 | **CONTRIBUTING.md** 읽기 (기여 가이드) |",
    "| 2 | **이슈(Issues)** 확인 (이미 누가 작업 중인지) |",
    "| 3 | **이슈 댓글**로 작업 의사 표시 (\"이 이슈 작업해도 될까요?\") |",
    "| 4 | Fork + Clone + upstream 등록 |",
    "| 5 | **기능 브랜치** 생성 (main에서 직접 작업 금지) |",
    "| 6 | 코드 스타일, 린트 규칙 따르기 |",
    "| 7 | 테스트가 있으면 **테스트 통과** 확인 |",
    "| 8 | 커밋 메시지 규칙 따르기 (Conventional Commits 등) |",
    "| 9 | PR 제목·본문 명확하게 작성 |",
    "| 10 | 리뷰어 피드백에 정중하게 대응 |",
    "",
    "---",
    "",
    "## GitHub CLI로 PR 관리",
    "",
    "```bash",
    "# PR 생성",
    "gh pr create --title \"fix: 오타 수정\" --body \"README 오타 수정\"",
    "",
    "# PR 목록 확인",
    "gh pr list",
    "",
    "# PR 상세 보기",
    "gh pr view 123",
    "",
    "# PR 체크아웃 (로컬에서 확인)",
    "gh pr checkout 123",
    "",
    "# PR 병합",
    "gh pr merge 123 --squash",
    "",
    "# PR 닫기",
    "gh pr close 123",
    "```",
    "",
    "---",
    "",
    "## Fork 없이 PR (팀 프로젝트)",
    "",
    "같은 저장소에 push 권한이 있으면 Fork 없이 브랜치로 PR을 만듭니다.",
    "",
    "```bash",
    "# 원본 저장소를 직접 clone",
    "git clone https://github.com/팀/project.git",
    "cd project",
    "",
    "# 기능 브랜치 생성",
    "git switch -c feature/login",
    "",
    "# 작업 + 커밋",
    "git add .",
    "git commit -m \"feat: 로그인 기능 추가\"",
    "",
    "# 브랜치 push",
    "git push -u origin feature/login",
    "",
    "# GitHub에서 PR 생성",
    "# feature/login → main",
    "```",
    "",
    "```",
    "Fork 방식 (오픈소스):          브랜치 방식 (팀):",
    "원본 ← PR ← 내 Fork          main ← PR ← feature 브랜치",
    "(push 권한 없음)              (push 권한 있음)",
    "```",
    "",
    "---",
    "",
    "## 자주 겪는 문제",
    "",
    "| 문제 | 원인 | 해결 |",
    "|------|------|------|",
    "| PR에 충돌 표시 | 원본 main이 변경됨 | Fork 동기화 후 충돌 해결 |",
    "| \"This branch is out of date\" | 원본이 업데이트됨 | `git fetch upstream` → `git merge` |",
    "| PR에 불필요한 커밋 포함 | main에서 직접 작업함 | 기능 브랜치에서 작업 |",
    "| Fork가 원본보다 뒤처짐 | 동기화 안 함 | Sync fork 또는 `git merge upstream/main` |",
    "",
    "### PR 충돌 해결",
    "",
    "```bash",
    "# 원본 최신 코드 가져오기",
    "git fetch upstream",
    "",
    "# 내 작업 브랜치에서 원본 main 병합",
    "git switch fix/typo-in-readme",
    "git merge upstream/main",
    "",
    "# 충돌 해결",
    "# ... 파일 수정 ...",
    "git add .",
    "git commit -m \"merge: upstream main 병합 + 충돌 해결\"",
    "",
    "# 내 Fork에 push (PR에 자동 반영)",
    "git push origin fix/typo-in-readme",
    "```",
    "",
    "---",
    "",
    "## 명령어 전체 정리",
    "",
    "| 명령어 | 설명 |",
    "|--------|------|",
    "| `git remote add upstream URL` | 원본 저장소 등록 |",
    "| `git fetch upstream` | 원본 최신 코드 가져오기 |",
    "| `git merge upstream/main` | 원본 코드를 내 main에 병합 |",
    "| `git push origin 브랜치` | 내 Fork에 push |",
    "| `gh pr create` | PR 생성 (GitHub CLI) |",
    "| `gh pr list` | PR 목록 |",
    "| `gh pr checkout 번호` | PR을 로컬에서 확인 |",
    "| `gh pr merge 번호` | PR 병합 |",
    "",
    "### 요약",
    "**Fork**는 다른 사람의 저장소를 내 계정으로 복사하는 것이고, **Pull Request**는 수정한 코드를 원본에 합쳐달라고 요청하는 것입니다. Fork → Clone → 브랜치 생성 → 작업 → Push → PR 생성이 오픈소스 기여의 표준 흐름입니다. `upstream`으로 원본을 등록하고 정기적으로 동기화하며, PR은 **Squash and merge**로 병합하면 히스토리가 깔끔합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
