<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "git-branch",
  title: "Git Branch 완벽 가이드",
  date: "2026-02-25",
  summary: "브랜치의 개념, 생성·전환·병합·삭제, 충돌 해결, 브랜치 전략까지 실습과 함께 정리합니다.",
  category: "Technology/Git",
  tags: ["git","branch","merge","rebase","conflict","gitflow"],
  content: [
    "## 한 줄 요약",
    "브랜치는 **커밋을 가리키는 포인터**입니다. 독립된 작업 공간을 만들어 기능 개발·버그 수정을 분리하고, 완료 후 병합(merge)합니다.",
    "",
    "---",
    "",
    "## 브랜치란?",
    "",
    "### 비유로 이해하기",
    "",
    "소설을 쓰고 있다고 상상해보세요:",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"원본 원고 (main)\"] --> B[\"해피엔딩 버전<br>(feature/happy-ending)\"]",
    "    A --> C[\"새드엔딩 버전<br>(feature/sad-ending)\"]",
    "    B -.- D[\"마음에 들면 원본에 반영<br>마음에 안 들면 버리기\"]",
    "    C -.- E[\"원본은 건드리지 않고 실험\"]",
    "```",
    "",
    "- 원본(main)은 그대로 유지",
    "- 각 버전(브랜치)에서 독립적으로 작업",
    "- 마음에 드는 버전을 원본에 합침(merge)",
    "",
    "### Git에서의 브랜치",
    "",
    "브랜치는 사실 **특정 커밋을 가리키는 포인터(화살표)**에 불과합니다.",
    "",
    "커밋 히스토리:",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[A] --> B[B] --> C[C] --> D[D]",
    "    HEAD([\"HEAD (현재 위치)\"]) -.-> main([\"main (브랜치 = 포인터)\"]) -.-> D",
    "```",
    "",
    "> 브랜치를 만드는 것은 **포인터 하나를 추가하는 것**이라 매우 가볍고 빠릅니다. 파일을 복사하는 것이 아닙니다.",
    "",
    "---",
    "",
    "## 브랜치 기본 명령어",
    "",
    "### 브랜치 목록 확인",
    "",
    "```bash",
    "# 로컬 브랜치 목록",
    "git branch",
    "# * main              ← * 표시가 현재 브랜치",
    "#   feature/login",
    "#   feature/signup",
    "",
    "# 원격 브랜치 포함 전체 목록",
    "git branch -a",
    "",
    "# 원격 브랜치만",
    "git branch -r",
    "",
    "# 각 브랜치의 마지막 커밋 함께 보기",
    "git branch -v",
    "# * main          abc1234 세 번째 커밋",
    "#   feature/login def5678 로그인 기능 추가",
    "```",
    "",
    "### 브랜치 생성",
    "",
    "```bash",
    "# 브랜치 생성 (이동하지 않음)",
    "git branch feature/login",
    "",
    "# 브랜치 생성 + 이동 (switch 방식, 권장)",
    "git switch -c feature/login",
    "",
    "# 브랜치 생성 + 이동 (checkout 방식)",
    "git checkout -b feature/login",
    "",
    "# 특정 커밋에서 브랜치 생성",
    "git branch hotfix/bug abc1234",
    "```",
    "",
    "git branch feature/login 실행 후:",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[A] --> B[B] --> C[C] --> D[D]",
    "    main([\"main\"]) -.-> D",
    "    feature([\"feature/login ← 새 포인터 추가됨\"]) -.-> D",
    "    HEAD([\"HEAD (아직 main에 있음)\"]) -.-> main",
    "```",
    "",
    "### 브랜치 전환 (이동)",
    "",
    "```bash",
    "# switch 방식 (권장)",
    "git switch feature/login",
    "git switch main",
    "git switch -               # 직전 브랜치로 이동",
    "",
    "# checkout 방식",
    "git checkout feature/login",
    "git checkout main",
    "```",
    "",
    "git switch feature/login 실행 후:",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[A] --> B[B] --> C[C] --> D[D]",
    "    main([\"main\"]) -.-> D",
    "    feature([\"feature/login\"]) -.-> D",
    "    HEAD([\"HEAD (이제 feature/login에 있음)\"]) -.-> feature",
    "```",
    "",
    "### 브랜치 이름 변경",
    "",
    "```bash",
    "# 현재 브랜치 이름 변경",
    "git branch -m 새이름",
    "",
    "# 특정 브랜치 이름 변경",
    "git branch -m 기존이름 새이름",
    "",
    "# 예시",
    "git branch -m feature/login feature/auth",
    "```",
    "",
    "### 브랜치 삭제",
    "",
    "```bash",
    "# 병합 완료된 브랜치 삭제",
    "git branch -d feature/login",
    "",
    "# 병합 안 된 브랜치 강제 삭제",
    "git branch -D feature/login",
    "",
    "# 원격 브랜치 삭제",
    "git push origin --delete feature/login",
    "```",
    "",
    "---",
    "",
    "## 실습: 브랜치 생성부터 병합까지",
    "",
    "### 준비",
    "",
    "```bash",
    "mkdir branch-practice",
    "cd branch-practice",
    "git init",
    "",
    "# 초기 파일 + 커밋",
    "echo \"메인 페이지\" > index.html",
    "git add .",
    "git commit -m \"초기 커밋: index.html\"",
    "",
    "git log --oneline",
    "# abc1234 초기 커밋: index.html",
    "```",
    "",
    "### 기능 브랜치에서 작업",
    "",
    "```bash",
    "# 로그인 기능 브랜치 생성 + 이동",
    "git switch -c feature/login",
    "",
    "# 로그인 파일 생성",
    "echo \"로그인 페이지\" > login.html",
    "git add .",
    "git commit -m \"로그인 페이지 추가\"",
    "",
    "# 로그인 기능 추가",
    "echo \"로그인 폼\" >> login.html",
    "git add .",
    "git commit -m \"로그인 폼 추가\"",
    "",
    "git log --oneline",
    "# def5678 로그인 폼 추가",
    "# ghi9012 로그인 페이지 추가",
    "# abc1234 초기 커밋: index.html",
    "```",
    "",
    "현재 상태:",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"abc1234\"] --> B[\"ghi9012\"] --> C[\"def5678\"]",
    "    main([\"main\"]) -.-> A",
    "    feature([\"feature/login\"]) -.-> C",
    "    HEAD([\"HEAD\"]) -.-> feature",
    "```",
    "",
    "### main으로 돌아가서 병합",
    "",
    "```bash",
    "# main으로 이동",
    "git switch main",
    "",
    "# login.html이 없는 것 확인 (main에는 아직 없음)",
    "ls",
    "# index.html",
    "",
    "# feature/login 브랜치를 main에 병합",
    "git merge feature/login",
    "",
    "# login.html이 생긴 것 확인",
    "ls",
    "# index.html  login.html",
    "",
    "git log --oneline",
    "# def5678 로그인 폼 추가",
    "# ghi9012 로그인 페이지 추가",
    "# abc1234 초기 커밋: index.html",
    "",
    "# 병합 완료된 브랜치 삭제",
    "git branch -d feature/login",
    "```",
    "",
    "---",
    "",
    "## 병합(Merge) 방식",
    "",
    "### 1. Fast-Forward 병합",
    "",
    "main에 새 커밋이 없으면, 브랜치 포인터만 앞으로 이동합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph before[\"병합 전\"]",
    "        direction LR",
    "        bA[A] --> bB[B] --> bC[\"C (main)\"] --> bD[D] --> bE[\"E (feature)\"]",
    "    end",
    "    subgraph after[\"병합 후 (Fast-Forward)\"]",
    "        direction LR",
    "        aA[A] --> aB[B] --> aC[C] --> aD[D] --> aE[\"E (main, feature)\"]",
    "    end",
    "```",
    "",
    "```bash",
    "git switch main",
    "git merge feature/login",
    "# Fast-forward 메시지가 나옴",
    "```",
    "",
    "### 2. 3-Way Merge (병합 커밋 생성)",
    "",
    "main에도 새 커밋이 있으면, **병합 커밋(merge commit)**이 생성됩니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph before[\"병합 전\"]",
    "        direction LR",
    "        bA[A] --> bB[B] --> bC[C] --> bF[\"F (main)\"]",
    "        bB --> bD[D] --> bE[\"E (feature)\"]",
    "    end",
    "    subgraph after[\"병합 후 (3-Way Merge)\"]",
    "        direction LR",
    "        aA[A] --> aB[B] --> aC[C] --> aF[F]",
    "        aB --> aD[D] --> aE[E]",
    "        aF --> aG[\"G (main) ← 병합 커밋\"]",
    "        aE --> aG",
    "    end",
    "```",
    "",
    "```bash",
    "git switch main",
    "git merge feature/login",
    "# Merge made by the 'ort' strategy. 메시지가 나옴",
    "# 자동으로 병합 커밋이 생성됨",
    "```",
    "",
    "---",
    "",
    "## 충돌(Conflict) 해결",
    "",
    "두 브랜치가 **같은 파일의 같은 부분**을 수정하면 충돌이 발생합니다.",
    "",
    "### 충돌 만들어보기",
    "",
    "```bash",
    "# 준비",
    "echo \"원본 내용\" > common.txt",
    "git add . && git commit -m \"common.txt 추가\"",
    "",
    "# feature 브랜치에서 수정",
    "git switch -c feature/update",
    "echo \"feature에서 수정\" > common.txt",
    "git add . && git commit -m \"feature: common.txt 수정\"",
    "",
    "# main에서도 같은 파일 수정",
    "git switch main",
    "echo \"main에서 수정\" > common.txt",
    "git add . && git commit -m \"main: common.txt 수정\"",
    "",
    "# 병합 시도 → 충돌 발생!",
    "git merge feature/update",
    "# CONFLICT (content): Merge conflict in common.txt",
    "# Automatic merge failed; fix conflicts and then commit the result.",
    "```",
    "",
    "### 충돌 파일 내용",
    "",
    "```",
    "<<<<<<< HEAD",
    "main에서 수정",
    "=======",
    "feature에서 수정",
    ">>>>>>> feature/update",
    "```",
    "",
    "| 표시 | 의미 |",
    "|------|------|",
    "| `<<<<<<< HEAD` | 현재 브랜치(main)의 내용 시작 |",
    "| `=======` | 구분선 |",
    "| `>>>>>>> feature/update` | 병합하려는 브랜치의 내용 끝 |",
    "",
    "### 충돌 해결 방법",
    "",
    "```bash",
    "# 1. 파일을 열어서 원하는 내용으로 수정",
    "#    (<<<, ===, >>> 표시를 모두 제거하고 원하는 내용만 남김)",
    "",
    "echo \"main과 feature 합친 내용\" > common.txt",
    "",
    "# 2. 수정한 파일을 스테이지에 추가",
    "git add common.txt",
    "",
    "# 3. 커밋 (충돌 해결 완료)",
    "git commit -m \"충돌 해결: common.txt 병합\"",
    "",
    "# 충돌 해결 완료!",
    "```",
    "",
    "### 충돌 시 유용한 명령어",
    "",
    "```bash",
    "# 충돌 상태 확인",
    "git status",
    "# both modified: common.txt",
    "",
    "# 병합 취소 (충돌 전으로 돌아가기)",
    "git merge --abort",
    "",
    "# 충돌 파일에서 어느 쪽을 선택할지",
    "git checkout --ours common.txt     # 현재 브랜치(main) 내용 선택",
    "git checkout --theirs common.txt   # 상대 브랜치(feature) 내용 선택",
    "```",
    "",
    "---",
    "",
    "## Rebase",
    "",
    "Merge 대신 **Rebase**로 히스토리를 깔끔하게 만들 수 있습니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph m[\"Merge (병합 커밋 생성)\"]",
    "        direction LR",
    "        mA[A] --> mB[B] --> mC[C] --> mF[F]",
    "        mB --> mD[D] --> mE[\"E (feature)\"]",
    "        mF --> mG[\"G (main) ← 병합 커밋\"]",
    "        mE --> mG",
    "    end",
    "    subgraph r[\"Rebase (일직선 히스토리)\"]",
    "        direction LR",
    "        rA[A] --> rB[B] --> rC[C] --> rF[F] --> rD[\"D'\"] --> rE[\"E' (feature → main)\"]",
    "    end",
    "```",
    "",
    "```bash",
    "# feature 브랜치에서 rebase",
    "git switch feature/login",
    "git rebase main",
    "",
    "# main에서 fast-forward merge",
    "git switch main",
    "git merge feature/login",
    "```",
    "",
    "### Merge vs Rebase",
    "",
    "| 항목 | Merge | Rebase |",
    "|------|-------|--------|",
    "| 히스토리 | 분기 + 병합 커밋 (그래프) | 일직선 (깔끔) |",
    "| 기존 커밋 | 변경 없음 | 새 커밋으로 재생성 |",
    "| 안전성 | 안전 (기록 보존) | 공유 브랜치에서는 위험 |",
    "| 충돌 해결 | 한 번에 해결 | 커밋마다 해결할 수 있음 |",
    "",
    "> **규칙**: 이미 push한 브랜치(다른 사람과 공유 중)에서는 rebase하지 마세요. 로컬 브랜치에서만 사용하세요.",
    "",
    "---",
    "",
    "## 브랜치 전략",
    "",
    "### 1. GitHub Flow (간단)",
    "",
    "```mermaid",
    "flowchart TD",
    "    M[\"main (항상 배포 가능)\"]",
    "    FL[\"feature/login\"] -->|\"PR → merge\"| M",
    "    FS[\"feature/signup\"] -->|\"PR → merge\"| M",
    "```",
    "",
    "- `main`은 항상 배포 가능한 상태",
    "- 기능 개발은 **feature 브랜치**에서",
    "- 완료되면 **Pull Request(PR)**로 코드 리뷰 후 병합",
    "- 소규모 팀, 빠른 배포에 적합",
    "",
    "### 2. Git Flow (체계적)",
    "",
    "```mermaid",
    "flowchart TD",
    "    main[\"main (배포 버전)\"]",
    "    develop[\"develop (개발 통합)\"]",
    "    fa[\"feature/a\"] -->|merge| develop",
    "    fb[\"feature/b\"] -->|merge| develop",
    "    develop --> release[\"release/1.0\"]",
    "    release -->|merge| main",
    "    hotfix[\"hotfix/bug\"] -->|merge| main",
    "    hotfix -->|merge| develop",
    "```",
    "",
    "| 브랜치 | 역할 |",
    "|--------|------|",
    "| `main` | 배포된 안정 버전 |",
    "| `develop` | 개발 통합 브랜치 |",
    "| `feature/*` | 기능 개발 |",
    "| `release/*` | 배포 준비 |",
    "| `hotfix/*` | 긴급 버그 수정 |",
    "",
    "### 브랜치 이름 규칙",
    "",
    "| 접두사 | 용도 | 예시 |",
    "|--------|------|------|",
    "| `feature/` | 새 기능 | `feature/login`, `feature/cart` |",
    "| `bugfix/` | 버그 수정 | `bugfix/login-error` |",
    "| `hotfix/` | 긴급 수정 | `hotfix/security-patch` |",
    "| `release/` | 배포 준비 | `release/1.0.0` |",
    "| `refactor/` | 리팩토링 | `refactor/auth-module` |",
    "",
    "---",
    "",
    "## 원격 브랜치",
    "",
    "```bash",
    "# 로컬 브랜치를 원격에 push",
    "git push origin feature/login",
    "git push -u origin feature/login   # 추적 설정 (이후 git push만 하면 됨)",
    "",
    "# 원격 브랜치 가져오기",
    "git fetch origin",
    "git switch feature/login           # 원격에만 있으면 자동 추적",
    "",
    "# 원격 브랜치 삭제",
    "git push origin --delete feature/login",
    "",
    "# 삭제된 원격 브랜치 로컬 정리",
    "git fetch --prune",
    "",
    "# 원격 브랜치 목록",
    "git branch -r",
    "```",
    "",
    "---",
    "",
    "## git log로 브랜치 시각화",
    "",
    "```bash",
    "# 브랜치 그래프 보기",
    "git log --oneline --graph --all",
    "",
    "# 출력 예시:",
    "# *   abc1234 (HEAD -> main) Merge feature/login",
    "# |\\",
    "# | * def5678 (feature/login) 로그인 폼 추가",
    "# | * ghi9012 로그인 페이지 추가",
    "# |/",
    "# * jkl3456 초기 커밋",
    "",
    "# 간단한 별칭(alias) 등록",
    "git config --global alias.lg \"log --oneline --graph --all\"",
    "",
    "# 이후 간단하게 사용",
    "git lg",
    "```",
    "",
    "---",
    "",
    "## 브랜치 명령어 전체 정리",
    "",
    "| 명령어 | 설명 |",
    "|--------|------|",
    "| `git branch` | 브랜치 목록 |",
    "| `git branch 이름` | 브랜치 생성 |",
    "| `git branch -d 이름` | 브랜치 삭제 (병합 완료 시) |",
    "| `git branch -D 이름` | 브랜치 강제 삭제 |",
    "| `git branch -m 새이름` | 브랜치 이름 변경 |",
    "| `git branch -v` | 브랜치 + 마지막 커밋 |",
    "| `git branch -a` | 로컬 + 원격 브랜치 |",
    "| `git switch 이름` | 브랜치 전환 |",
    "| `git switch -c 이름` | 브랜치 생성 + 전환 |",
    "| `git switch -` | 직전 브랜치로 이동 |",
    "| `git merge 이름` | 현재 브랜치에 병합 |",
    "| `git merge --abort` | 병합 취소 |",
    "| `git rebase 이름` | 현재 브랜치를 재배치 |",
    "| `git push origin 이름` | 원격에 브랜치 push |",
    "| `git push origin --delete 이름` | 원격 브랜치 삭제 |",
    "",
    "### 요약",
    "브랜치는 **커밋을 가리키는 가벼운 포인터**입니다. `git switch -c`로 생성+이동, 독립적으로 작업한 뒤, `git merge`로 병합합니다. 같은 파일을 동시에 수정하면 **충돌**이 발생하며, 직접 파일을 수정하고 `git add` + `git commit`으로 해결합니다. 소규모 팀은 **GitHub Flow**, 체계적인 프로젝트는 **Git Flow** 전략을 사용합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
