<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "git-file-states",
  title: "Git으로 관리하는 파일의 4가지 상태",
  date: "2026-02-25",
  summary: "Untracked, Staged, Unmodified, Modified — Git이 파일을 관리하는 4가지 상태를 명령어 실습과 함께 이해합니다.",
  category: "Technology/Git",
  tags: ["git","file-states","untracked","staged","modified","status","add","commit"],
  content: [
    "## 한 줄 요약",
    "Git 파일은 **Untracked**(추적 안 됨) → **Staged**(스테이지) → **Unmodified**(커밋 완료) → **Modified**(수정됨) 4가지 상태를 순환하며, `git add`와 `git commit`으로 상태를 전환합니다.",
    "",
    "---",
    "",
    "## 4가지 상태 전체 흐름",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Untracked<br>(추적 안 됨)\"] -->|git add| B[\"Staged<br>(스테이지)\"]",
    "    B -->|git commit| C[\"Unmodified<br>(커밋 완료)\"]",
    "    C -->|파일 수정| D[\"Modified<br>(수정됨)\"]",
    "    D -->|git add| B",
    "    C -->|git rm| A",
    "```",
    "",
    "| 상태 | 영어 | 의미 | git status 표시 |",
    "|------|------|------|----------------|",
    "| **Untracked** | 추적 안 됨 | Git이 모르는 새 파일 | 빨간색 `Untracked files` |",
    "| **Staged** | 스테이지 | 다음 커밋에 포함될 파일 | 초록색 `Changes to be committed` |",
    "| **Unmodified** | 수정 안 됨 | 커밋 완료, 변경 없음 | 표시 안 됨 (깨끗한 상태) |",
    "| **Modified** | 수정됨 | 커밋 후 내용이 변경됨 | 빨간색 `Changes not staged` |",
    "",
    "---",
    "",
    "## 실습 준비",
    "",
    "```bash",
    "# 빈 폴더 생성 + Git 초기화",
    "mkdir git-state-practice",
    "cd git-state-practice",
    "git init",
    "",
    "# 현재 상태 확인",
    "git status",
    "```",
    "",
    "출력:",
    "```",
    "On branch master",
    "No commits yet",
    "nothing to commit (create/copy files and use \"git add\" to track)",
    "```",
    "",
    "> 아직 파일이 없으므로 \"nothing to commit\"이라고 나옵니다.",
    "",
    "---",
    "",
    "## 1단계: Untracked (추적 안 됨)",
    "",
    "Git 저장소에 새 파일을 만들면, Git은 이 파일의 존재를 **모릅니다**.",
    "",
    "```bash",
    "# 새 파일 생성",
    "echo \"hello git\" > hello.txt",
    "",
    "# 상태 확인",
    "git status",
    "```",
    "",
    "출력:",
    "```",
    "On branch master",
    "No commits yet",
    "Untracked files:",
    "  (use \"git add <file>...\" to include in what will be committed)",
    "        hello.txt",
    "",
    "nothing added to commit but untracked files present",
    "```",
    "",
    "```",
    "hello.txt의 상태: ❌ Untracked (추적 안 됨)",
    "",
    "Git:  \"hello.txt? 처음 보는 파일인데, 추적할까요?\"",
    "```",
    "",
    "**Untracked 파일의 특징:**",
    "- Git이 **존재조차 모르는** 파일",
    "- `git add` 하기 전까지 Git의 관리 대상이 아님",
    "- 커밋에 포함되지 않음",
    "- `.gitignore`에 등록하면 영원히 무시 가능",
    "",
    "---",
    "",
    "## 2단계: Staged (스테이지 / 인덱스)",
    "",
    "`git add`로 파일을 **스테이지 영역(Staging Area)**에 올립니다.",
    "",
    "```bash",
    "# 파일을 스테이지에 추가",
    "git add hello.txt",
    "",
    "# 상태 확인",
    "git status",
    "```",
    "",
    "출력:",
    "```",
    "On branch master",
    "No commits yet",
    "Changes to be committed:",
    "  (use \"git rm --cached <file>...\" to unstage)",
    "        new file:   hello.txt",
    "```",
    "",
    "```",
    "hello.txt의 상태: ✅ Staged (스테이지)",
    "",
    "Git:  \"hello.txt를 다음 커밋에 포함시킬 준비 완료!\"",
    "```",
    "",
    "**Staged 파일의 특징:**",
    "- **다음 커밋에 포함될** 파일",
    "- 스테이지 영역(Staging Area)에 스냅샷이 저장됨",
    "- `git commit` 하면 이 스냅샷이 저장소에 기록됨",
    "- `git restore --staged`로 스테이지에서 내릴 수 있음",
    "",
    "### 스테이지에서 내리기 (Staged → Untracked)",
    "",
    "```bash",
    "# 스테이지에서 내리기 (파일은 그대로, 추적만 해제)",
    "git rm --cached hello.txt",
    "git status",
    "# → 다시 Untracked 상태",
    "",
    "# 다시 스테이지에 올리기",
    "git add hello.txt",
    "```",
    "",
    "---",
    "",
    "## 3단계: Unmodified (수정 안 됨 / 커밋 완료)",
    "",
    "`git commit`으로 커밋하면 파일은 **Unmodified** 상태가 됩니다.",
    "",
    "```bash",
    "# 커밋",
    "git commit -m \"첫 번째 커밋: hello.txt 추가\"",
    "",
    "# 상태 확인",
    "git status",
    "```",
    "",
    "출력:",
    "```",
    "On branch master",
    "nothing to commit, working tree clean",
    "```",
    "",
    "```",
    "hello.txt의 상태: 📦 Unmodified (수정 안 됨)",
    "",
    "Git:  \"hello.txt는 마지막 커밋과 동일합니다. 변경 없음!\"",
    "```",
    "",
    "**Unmodified 파일의 특징:**",
    "- 마지막 커밋과 **내용이 완전히 동일**한 파일",
    "- `git status`에 **표시되지 않음** (깨끗한 상태)",
    "- 파일을 수정하면 Modified로 전환",
    "- `git rm`으로 삭제하면 삭제 이력이 Staged로 올라감",
    "",
    "### 커밋 로그 확인",
    "",
    "```bash",
    "git log --oneline",
    "# abc1234 첫 번째 커밋: hello.txt 추가",
    "```",
    "",
    "---",
    "",
    "## 4단계: Modified (수정됨)",
    "",
    "Unmodified 파일을 수정하면 **Modified** 상태가 됩니다.",
    "",
    "```bash",
    "# 파일 내용 수정",
    "echo \"hello git world\" > hello.txt",
    "",
    "# 상태 확인",
    "git status",
    "```",
    "",
    "출력:",
    "```",
    "On branch master",
    "Changes not staged for commit:",
    "  (use \"git add <file>...\" to update what will be committed)",
    "  (use \"git restore <file>...\" to discard changes in working directory)",
    "        modified:   hello.txt",
    "",
    "no changes added to commit",
    "```",
    "",
    "```",
    "hello.txt의 상태: ✏️ Modified (수정됨)",
    "",
    "Git:  \"hello.txt가 마지막 커밋과 달라졌습니다!\"",
    "```",
    "",
    "**Modified 파일의 특징:**",
    "- 마지막 커밋과 **내용이 달라진** 파일",
    "- 아직 스테이지에 올라가지 않은 상태",
    "- `git add`로 다시 Staged 상태로 전환",
    "- `git restore`로 수정 취소 가능 (마지막 커밋 상태로 되돌림)",
    "",
    "### 변경 내용 확인",
    "",
    "```bash",
    "# 워킹 디렉터리 vs 마지막 커밋 비교",
    "git diff",
    "",
    "# 출력 예시:",
    "# -hello git",
    "# +hello git world",
    "```",
    "",
    "### Modified → Staged → Unmodified (다시 커밋)",
    "",
    "```bash",
    "# 수정한 파일을 스테이지에 추가",
    "git add hello.txt",
    "git status",
    "# → Changes to be committed: modified: hello.txt (Staged)",
    "",
    "# 커밋",
    "git commit -m \"두 번째 커밋: hello.txt 내용 수정\"",
    "git status",
    "# → nothing to commit, working tree clean (Unmodified)",
    "```",
    "",
    "---",
    "",
    "## 전체 실습: 여러 파일로 4가지 상태 동시 확인",
    "",
    "```bash",
    "# 새 파일 2개 생성",
    "echo \"file a\" > a.txt",
    "echo \"file b\" > b.txt",
    "",
    "git status",
    "# a.txt → Untracked",
    "# b.txt → Untracked",
    "",
    "# a.txt만 스테이지에 추가",
    "git add a.txt",
    "",
    "git status",
    "# a.txt → Staged (new file)",
    "# b.txt → Untracked",
    "",
    "# 커밋 (a.txt만 포함됨)",
    "git commit -m \"a.txt 추가\"",
    "",
    "git status",
    "# a.txt → Unmodified (표시 안 됨)",
    "# b.txt → Untracked",
    "",
    "# a.txt 수정",
    "echo \"file a updated\" > a.txt",
    "",
    "git status",
    "# a.txt → Modified",
    "# b.txt → Untracked",
    "",
    "# b.txt도 스테이지에 추가",
    "git add a.txt b.txt",
    "",
    "git status",
    "# a.txt → Staged (modified)",
    "# b.txt → Staged (new file)",
    "",
    "# 커밋",
    "git commit -m \"a.txt 수정 + b.txt 추가\"",
    "",
    "git status",
    "# nothing to commit, working tree clean",
    "# a.txt → Unmodified",
    "# b.txt → Unmodified",
    "```",
    "",
    "---",
    "",
    "## 3가지 영역 이해하기",
    "",
    "Git에는 파일이 거치는 **3가지 영역**이 있습니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    WD[\"Working Directory<br>실제 파일이 있는 곳<br>(Untracked / Modified)\"] -->|git add| SA[\"Staging Area (Index)<br>다음 커밋에 포함될 파일<br>(Staged)\"]",
    "    SA -->|git commit| R[\"Repository (.git)<br>커밋된 스냅샷이 영구 저장된 곳<br>(Unmodified)\"]",
    "    SA -->|git restore| WD",
    "```",
    "",
    "| 영역 | 설명 | 위치 |",
    "|------|------|------|",
    "| **Working Directory** | 실제 파일이 있는 폴더 | 프로젝트 폴더 |",
    "| **Staging Area (Index)** | 다음 커밋에 포함될 파일 목록 | `.git/index` |",
    "| **Repository** | 커밋된 스냅샷이 저장된 곳 | `.git/objects/` |",
    "",
    "---",
    "",
    "## 상태 전환 명령어 정리",
    "",
    "| 전환 | 명령어 | 설명 |",
    "|------|--------|------|",
    "| Untracked → Staged | `git add 파일` | 새 파일을 스테이지에 추가 |",
    "| Modified → Staged | `git add 파일` | 수정된 파일을 스테이지에 추가 |",
    "| Staged → Unmodified | `git commit` | 스테이지의 파일을 커밋 |",
    "| Unmodified → Modified | 파일 수정 (에디터) | 커밋된 파일의 내용을 변경 |",
    "| Staged → Untracked | `git rm --cached 파일` | 추적 해제 (파일은 유지) |",
    "| Staged → Modified | `git restore --staged 파일` | 스테이지에서 내리기 |",
    "| Modified → Unmodified | `git restore 파일` | 수정 취소 (마지막 커밋으로) |",
    "| Unmodified → Untracked | `git rm 파일` | 파일 삭제 + 추적 해제 |",
    "",
    "---",
    "",
    "## git add 다양한 사용법",
    "",
    "```bash",
    "# 특정 파일 추가",
    "git add hello.txt",
    "",
    "# 여러 파일 추가",
    "git add a.txt b.txt c.txt",
    "",
    "# 현재 디렉터리의 모든 변경 추가",
    "git add .",
    "",
    "# 모든 변경 추가 (삭제 포함)",
    "git add -A",
    "",
    "# 특정 확장자만 추가",
    "git add *.js",
    "",
    "# 특정 폴더의 파일만 추가",
    "git add src/",
    "```",
    "",
    "---",
    "",
    "## git diff로 상태별 변경 확인",
    "",
    "```bash",
    "# Modified 파일의 변경 내용 (워킹 디렉터리 vs 스테이지)",
    "git diff",
    "",
    "# Staged 파일의 변경 내용 (스테이지 vs 마지막 커밋)",
    "git diff --staged",
    "# 또는",
    "git diff --cached",
    "",
    "# 워킹 디렉터리 vs 마지막 커밋 (전체 비교)",
    "git diff HEAD",
    "```",
    "",
    "### 실습",
    "",
    "```bash",
    "echo \"line 1\" > test.txt",
    "git add test.txt",
    "git commit -m \"test.txt 생성\"",
    "",
    "# 파일 수정",
    "echo \"line 2\" >> test.txt",
    "",
    "# Modified 상태의 변경 확인",
    "git diff",
    "# +line 2",
    "",
    "# 스테이지에 올린 후",
    "git add test.txt",
    "",
    "git diff",
    "# (출력 없음 — Modified 변경이 없으니까)",
    "",
    "git diff --staged",
    "# +line 2  (스테이지 vs 마지막 커밋)",
    "```",
    "",
    "---",
    "",
    "## .gitignore (영원히 Untracked로 유지)",
    "",
    "특정 파일을 Git이 절대 추적하지 않도록 `.gitignore`에 등록합니다.",
    "",
    "```bash",
    "# .gitignore 파일 생성",
    "echo \"node_modules/\" > .gitignore",
    "echo \".env\" >> .gitignore",
    "echo \"*.log\" >> .gitignore",
    "",
    "git status",
    "# node_modules/, .env, *.log 파일은 Untracked에도 표시되지 않음",
    "```",
    "",
    "| 패턴 | 의미 |",
    "|------|------|",
    "| `node_modules/` | node_modules 폴더 전체 무시 |",
    "| `.env` | .env 파일 무시 |",
    "| `*.log` | 모든 .log 파일 무시 |",
    "| `dist/` | dist 폴더 무시 |",
    "| `!important.log` | important.log는 예외 (추적) |",
    "",
    "---",
    "",
    "## 상태 확인 명령어 모음",
    "",
    "```bash",
    "# 기본 상태 확인",
    "git status",
    "",
    "# 간단한 형태 (-s: short)",
    "git status -s",
    "# 출력 예시:",
    "#  M hello.txt      ← Modified (빨간 M: unstaged)",
    "# M  hello.txt      ← Staged (초록 M: staged)",
    "# MM hello.txt      ← Staged + 추가 수정됨",
    "# A  new.txt        ← Staged (새 파일)",
    "# ?? unknown.txt    ← Untracked",
    "# D  deleted.txt    ← 삭제됨",
    "",
    "# 커밋 히스토리",
    "git log --oneline",
    "",
    "# 변경 내용 확인",
    "git diff              # Modified 확인",
    "git diff --staged     # Staged 확인",
    "```",
    "",
    "### git status -s 기호 정리",
    "",
    "| 기호 | 위치 | 의미 |",
    "|------|------|------|",
    "| `??` | | Untracked (새 파일, 추적 안 됨) |",
    "| `A` | 왼쪽 (초록) | Staged (새 파일 추가) |",
    "| `M` | 왼쪽 (초록) | Staged (수정된 파일) |",
    "| `M` | 오른쪽 (빨강) | Modified (수정됨, unstaged) |",
    "| `D` | 왼쪽 | Staged (삭제됨) |",
    "| `D` | 오른쪽 | 삭제됨 (unstaged) |",
    "| `MM` | 양쪽 | Staged 후 추가 수정됨 |",
    "",
    "---",
    "",
    "## 전체 순환 한눈에 보기",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Untracked\"] -->|git add| B[\"Staged\"]",
    "    B -->|git commit| C[\"Unmodified\"]",
    "    C -->|파일 수정| D[\"Modified\"]",
    "    D -->|git rm| A",
    "    D -->|git add| B",
    "```",
    "",
    "### 요약",
    "Git 파일은 **Untracked**(새 파일) → **Staged**(`git add`) → **Unmodified**(`git commit`) → **Modified**(파일 수정) 4가지 상태를 순환합니다. `git status`로 현재 상태를 확인하고, `git diff`로 변경 내용을 비교하며, `git add`와 `git commit`으로 상태를 전환합니다. Working Directory, Staging Area, Repository 3가지 영역을 이해하면 Git의 동작 원리가 명확해집니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
