<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "java-array",
  title: "Java 배열 (Array)",
  date: "2026-02-17",
  summary: "Java 배열의 선언, 생성, 초기화부터 다차원 배열, Arrays 유틸리티, 메모리 구조, 실전 예제까지 상세히 정리합니다.",
  category: "Coding/Java",
  tags: ["java", "배열", "array", "basics"],
  content: [
    "## 배열이란?",
    "",
    "배열(Array)은 **같은 타입의 데이터를 연속된 메모리 공간에 저장**하는 자료구조입니다. 한 번 생성하면 크기를 변경할 수 없는 **고정 길이** 특성을 가집니다.",
    "",
    "- 같은 타입의 값만 저장 가능 (int 배열에는 int만, String 배열에는 String만)",
    "- 인덱스(index)를 통해 각 요소에 빠르게 접근 가능 → **O(1) 시간 복잡도**",
    "- 선언 시 크기가 고정되며, 이후 크기 변경 불가",
    "",
    "```mermaid",
    "graph LR",
    "    A[\"int[] scores\"] --> B[\"scores[0] = 95\"]",
    "    A --> C[\"scores[1] = 71\"]",
    "    A --> D[\"scores[2] = 84\"]",
    "    A --> E[\"scores[3] = 93\"]",
    "    A --> F[\"scores[4] = 87\"]",
    "    style A fill:#4CAF50,color:#fff",
    "```",
    "",
    "---",
    "",
    "## 배열 선언과 생성",
    "",
    "배열을 사용하려면 **선언**과 **생성** 두 단계를 거칩니다.",
    "",
    "### 선언 방법",
    "",
    "```java",
    "// 방법 1: 타입[] 변수명 (권장)",
    "int[] scores;",
    "String[] names;",
    "",
    "// 방법 2: 타입 변수명[] (C 스타일, 비권장)",
    "int scores[];",
    "String names[];",
    "```",
    "",
    "### 생성 방법 (new 키워드)",
    "",
    "```java",
    "// 크기를 지정하여 생성",
    "int[] scores = new int[5];       // 정수 5개짜리 배열 (기본값 0)",
    "double[] avg = new double[3];    // 실수 3개짜리 배열 (기본값 0.0)",
    "String[] names = new String[4];  // 문자열 4개짜리 배열 (기본값 null)",
    "boolean[] flags = new boolean[2]; // 논리 2개짜리 배열 (기본값 false)",
    "```",
    "",
    "> **타입별 기본값**: `int` → 0, `double` → 0.0, `boolean` → false, `char` → '\\u0000', 참조 타입 → null",
    "",
    "---",
    "",
    "## 배열 초기화",
    "",
    "### 직접 초기화 (인덱스 지정)",
    "",
    "```java",
    "int[] scores = new int[3];",
    "scores[0] = 95;",
    "scores[1] = 80;",
    "scores[2] = 71;",
    "```",
    "",
    "### 중괄호 초기화 (선언과 동시에)",
    "",
    "```java",
    "// 선언과 동시에 초기화 — new 생략 가능",
    "int[] scores = { 95, 80, 71 };",
    "String[] fruits = { \"사과\", \"바나나\", \"포도\" };",
    "",
    "// 주의: 선언 후 별도 줄에서는 new 필요",
    "int[] arr;",
    "arr = new int[] { 10, 20, 30 };  // OK",
    "// arr = { 10, 20, 30 };         // 컴파일 에러!",
    "```",
    "",
    "---",
    "",
    "## 배열 인덱스와 length",
    "",
    "배열의 인덱스는 **0부터** 시작하고, 마지막 인덱스는 **length - 1**입니다.",
    "",
    "```java",
    "int[] arr = { 10, 20, 30, 40, 50 };",
    "",
    "System.out.println(arr[0]);          // 10 (첫 번째 요소)",
    "System.out.println(arr[arr.length - 1]); // 50 (마지막 요소)",
    "System.out.println(arr.length);      // 5 (배열 크기)",
    "```",
    "",
    "### ArrayIndexOutOfBoundsException",
    "",
    "유효하지 않은 인덱스에 접근하면 **런타임 예외**가 발생합니다.",
    "",
    "```java",
    "int[] arr = new int[3]; // 인덱스: 0, 1, 2",
    "",
    "arr[3] = 10;  // ArrayIndexOutOfBoundsException 발생!",
    "arr[-1] = 5;  // ArrayIndexOutOfBoundsException 발생!",
    "```",
    "",
    "> **💡 팁**: 배열 접근 전에 항상 인덱스 범위를 확인하는 습관을 들이세요.",
    "",
    "---",
    "",
    "## 배열 순회",
    "",
    "### for 문",
    "",
    "```java",
    "int[] scores = { 95, 80, 71, 93, 87 };",
    "",
    "for (int i = 0; i < scores.length; i++) {",
    "    System.out.println(\"scores[\" + i + \"] = \" + scores[i]);",
    "}",
    "```",
    "",
    "### 향상된 for 문 (for-each)",
    "",
    "인덱스가 필요 없을 때 간결하게 사용할 수 있습니다.",
    "",
    "```java",
    "int[] scores = { 95, 80, 71, 93, 87 };",
    "",
    "for (int score : scores) {",
    "    System.out.println(score);",
    "}",
    "```",
    "",
    "| 방식 | 장점 | 단점 |",
    "|------|------|------|",
    "| for 문 | 인덱스 사용 가능, 요소 수정 가능 | 코드가 길어짐 |",
    "| for-each | 간결, 읽기 쉬움 | 인덱스 접근 불가, 요소 수정 불가 |",
    "",
    "---",
    "",
    "## 다차원 배열",
    "",
    "### 2차원 배열 선언과 초기화",
    "",
    "```java",
    "// 방법 1: 크기 지정",
    "int[][] matrix = new int[3][4]; // 3행 4열",
    "",
    "// 방법 2: 중괄호 초기화",
    "int[][] matrix = {",
    "    { 1, 2, 3 },",
    "    { 4, 5, 6 },",
    "    { 7, 8, 9 }",
    "};",
    "```",
    "",
    "### 2차원 배열 순회",
    "",
    "```java",
    "int[][] matrix = {",
    "    { 1, 2, 3 },",
    "    { 4, 5, 6 },",
    "    { 7, 8, 9 }",
    "};",
    "",
    "for (int i = 0; i < matrix.length; i++) {",
    "    for (int j = 0; j < matrix[i].length; j++) {",
    "        System.out.print(matrix[i][j] + \" \");",
    "    }",
    "    System.out.println();",
    "}",
    "```",
    "",
    "### 가변 길이 배열 (Jagged Array)",
    "",
    "행마다 열 개수가 다를 수 있습니다.",
    "",
    "```java",
    "int[][] jagged = new int[3][];",
    "jagged[0] = new int[] { 1, 2 };",
    "jagged[1] = new int[] { 3, 4, 5 };",
    "jagged[2] = new int[] { 6 };",
    "",
    "// 또는 중괄호로",
    "int[][] jagged2 = {",
    "    { 1, 2 },",
    "    { 3, 4, 5 },",
    "    { 6 }",
    "};",
    "```",
    "",
    "```mermaid",
    "graph TD",
    "    A[\"int[][] jagged\"] --> B[\"jagged[0] → [1, 2]\"]",
    "    A --> C[\"jagged[1] → [3, 4, 5]\"]",
    "    A --> D[\"jagged[2] → [6]\"]",
    "    style A fill:#2196F3,color:#fff",
    "```",
    "",
    "---",
    "",
    "## 배열 복사",
    "",
    "배열은 참조 타입이므로 `=`로 복사하면 **같은 배열을 가리킵니다**. 실제 복사를 하려면 별도의 방법이 필요합니다.",
    "",
    "### System.arraycopy()",
    "",
    "```java",
    "int[] src = { 1, 2, 3, 4, 5 };",
    "int[] dest = new int[5];",
    "",
    "// arraycopy(원본, 원본시작, 대상, 대상시작, 길이)",
    "System.arraycopy(src, 0, dest, 0, src.length);",
    "```",
    "",
    "### Arrays.copyOf()",
    "",
    "```java",
    "import java.util.Arrays;",
    "",
    "int[] original = { 1, 2, 3 };",
    "int[] copy = Arrays.copyOf(original, original.length);",
    "",
    "// 길이를 늘리면 나머지는 기본값(0)으로 채워짐",
    "int[] expanded = Arrays.copyOf(original, 5); // [1, 2, 3, 0, 0]",
    "",
    "// 범위 복사",
    "int[] partial = Arrays.copyOfRange(original, 1, 3); // [2, 3]",
    "```",
    "",
    "### clone()",
    "",
    "```java",
    "int[] original = { 10, 20, 30 };",
    "int[] cloned = original.clone();",
    "```",
    "",
    "> **⚠️ 주의**: 위 방법들은 모두 **얕은 복사(Shallow Copy)**입니다. 참조 타입 배열은 내부 객체까지 복사되지 않습니다.",
    "",
    "---",
    "",
    "## Arrays 유틸리티 클래스",
    "",
    "`java.util.Arrays` 클래스는 배열 조작에 유용한 정적 메서드들을 제공합니다.",
    "",
    "```java",
    "import java.util.Arrays;",
    "",
    "int[] arr = { 5, 2, 8, 1, 9, 3 };",
    "",
    "// 정렬",
    "Arrays.sort(arr);",
    "System.out.println(Arrays.toString(arr)); // [1, 2, 3, 5, 8, 9]",
    "",
    "// 이진 탐색 (정렬된 배열에서만 사용)",
    "int idx = Arrays.binarySearch(arr, 5); // 3",
    "",
    "// 채우기",
    "int[] filled = new int[5];",
    "Arrays.fill(filled, 7);",
    "System.out.println(Arrays.toString(filled)); // [7, 7, 7, 7, 7]",
    "",
    "// 비교",
    "int[] a = { 1, 2, 3 };",
    "int[] b = { 1, 2, 3 };",
    "System.out.println(Arrays.equals(a, b)); // true",
    "",
    "// 스트림 변환 (Java 8+)",
    "int sum = Arrays.stream(arr).sum();",
    "System.out.println(\"합계: \" + sum);",
    "```",
    "",
    "| 메서드 | 설명 |",
    "|--------|------|",
    "| `sort(arr)` | 오름차순 정렬 |",
    "| `binarySearch(arr, key)` | 이진 탐색 (정렬 필수) |",
    "| `fill(arr, val)` | 모든 요소를 val로 채움 |",
    "| `toString(arr)` | 배열 내용을 문자열로 변환 |",
    "| `equals(a, b)` | 두 배열의 내용 비교 |",
    "| `copyOf(arr, len)` | 새 배열로 복사 |",
    "| `stream(arr)` | 스트림으로 변환 |",
    "",
    "---",
    "",
    "## 메모리 구조",
    "",
    "배열의 **참조 변수는 스택(Stack)** 에, **실제 배열 데이터는 힙(Heap)** 에 저장됩니다.",
    "",
    "```mermaid",
    "graph LR",
    "    subgraph Stack",
    "        A[\"scores (참조)\"]",
    "    end",
    "    subgraph Heap",
    "        B[\"[95, 80, 71, 93, 87]\"]",
    "    end",
    "    A -->|참조| B",
    "    style A fill:#FF9800,color:#fff",
    "    style B fill:#4CAF50,color:#fff",
    "```",
    "",
    "```java",
    "int[] a = { 1, 2, 3 };",
    "int[] b = a;  // 같은 배열을 가리킴 (참조 복사)",
    "",
    "b[0] = 99;",
    "System.out.println(a[0]); // 99 — a와 b는 같은 배열!",
    "```",
    "",
    "> `=`은 참조를 복사하므로, 독립적인 복사본이 필요하면 `Arrays.copyOf()` 등을 사용해야 합니다.",
    "",
    "---",
    "",
    "## 배열 vs ArrayList 비교",
    "",
    "| 특성 | 배열 (Array) | ArrayList |",
    "|------|-------------|-----------|",
    "| 크기 | 고정 (생성 시 결정) | 가변 (자동 확장) |",
    "| 타입 | 기본형 + 참조형 | 참조형만 (래퍼 클래스 필요) |",
    "| 성능 | 빠름 (연속 메모리) | 약간 느림 (내부 배열 복사) |",
    "| 편의성 | 낮음 (직접 관리) | 높음 (add, remove 등) |",
    "| 길이 확인 | `.length` (필드) | `.size()` (메서드) |",
    "| 다차원 | 지원 | 리스트 안의 리스트로 구현 |",
    "",
    "```java",
    "import java.util.ArrayList;",
    "",
    "// ArrayList 사용 예",
    "ArrayList<Integer> list = new ArrayList<>();",
    "list.add(95);",
    "list.add(80);",
    "list.remove(0);",
    "System.out.println(list.size()); // 1",
    "```",
    "",
    "---",
    "",
    "## 실전 예제",
    "",
    "### 최대값 / 최소값 찾기",
    "",
    "```java",
    "int[] scores = { 78, 95, 63, 84, 91, 72 };",
    "int max = scores[0];",
    "int min = scores[0];",
    "",
    "for (int i = 1; i < scores.length; i++) {",
    "    if (scores[i] > max) max = scores[i];",
    "    if (scores[i] < min) min = scores[i];",
    "}",
    "",
    "System.out.println(\"최대값: \" + max); // 95",
    "System.out.println(\"최소값: \" + min); // 63",
    "```",
    "",
    "### 배열 뒤집기",
    "",
    "```java",
    "int[] arr = { 1, 2, 3, 4, 5 };",
    "",
    "for (int i = 0; i < arr.length / 2; i++) {",
    "    int temp = arr[i];",
    "    arr[i] = arr[arr.length - 1 - i];",
    "    arr[arr.length - 1 - i] = temp;",
    "}",
    "",
    "System.out.println(Arrays.toString(arr)); // [5, 4, 3, 2, 1]",
    "```",
    "",
    "### 빈도수 카운팅",
    "",
    "```java",
    "int[] data = { 1, 3, 2, 3, 1, 2, 3, 1, 2, 1 };",
    "int[] count = new int[4]; // 0~3 범위",
    "",
    "for (int val : data) {",
    "    count[val]++;",
    "}",
    "",
    "for (int i = 0; i < count.length; i++) {",
    "    System.out.println(i + \"의 등장 횟수: \" + count[i]);",
    "}",
    "// 0의 등장 횟수: 0",
    "// 1의 등장 횟수: 4",
    "// 2의 등장 횟수: 3",
    "// 3의 등장 횟수: 3",
    "```",
    "",
    "### 배열을 메서드 인자로 전달",
    "",
    "```java",
    "public static double average(int[] arr) {",
    "    int sum = 0;",
    "    for (int val : arr) {",
    "        sum += val;",
    "    }",
    "    return (double) sum / arr.length;",
    "}",
    "",
    "public static void main(String[] args) {",
    "    int[] scores = { 90, 85, 78, 92 };",
    "    System.out.println(\"평균: \" + average(scores));",
    "}",
    "```",
    "",
    "---",
    "",
    "## 주의사항 정리",
    "",
    "- 배열 크기는 **0 이상의 정수**여야 하며, 음수 크기는 `NegativeArraySizeException` 발생",
    "- `new int[0]`은 유효 — 길이 0인 빈 배열 (null과 다름)",
    "- 배열 변수에 `null`을 할당하면 참조가 끊기며, GC 대상이 됨",
    "- 다차원 배열에서 `matrix.length`는 행 수, `matrix[i].length`는 해당 행의 열 수",
    "- `Arrays.toString()`은 1차원 배열용, 다차원은 `Arrays.deepToString()` 사용",
    "",
    "```java",
    "int[][] matrix = { { 1, 2 }, { 3, 4 } };",
    "System.out.println(Arrays.toString(matrix));     // [[I@..., [I@...]",
    "System.out.println(Arrays.deepToString(matrix));  // [[1, 2], [3, 4]]",
    "```"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
