<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "java-class-object",
  title: "Java 클래스와 객체",
  date: "2026-02-17",
  summary: "Java의 객체 지향 프로그래밍 핵심인 클래스 정의, 생성자, 필드, 메서드, 접근 제어자, static, final, 불변 객체까지 상세히 정리합니다.",
  category: "Coding/Java",
  tags: ["java", "클래스", "객체", "생성자", "basics"],
  content: [
    "## 객체 지향 프로그래밍(OOP)이란?",
    "",
    "객체 지향 프로그래밍(Object-Oriented Programming)은 프로그램을 **객체(Object)** 들의 상호작용으로 구성하는 패러다임입니다. Java는 대표적인 OOP 언어입니다.",
    "",
    "### OOP의 4가지 핵심 원칙",
    "",
    "| 원칙 | 설명 |",
    "|------|------|",
    "| **캡슐화** (Encapsulation) | 데이터와 메서드를 하나로 묶고, 외부 접근을 제한 |",
    "| **상속** (Inheritance) | 기존 클래스를 확장하여 재사용 |",
    "| **다형성** (Polymorphism) | 같은 타입이지만 다른 동작 수행 |",
    "| **추상화** (Abstraction) | 핵심만 노출, 세부 구현을 숨김 |",
    "",
    "```mermaid",
    "graph TD",
    "    OOP[\"객체 지향 프로그래밍\"]",
    "    OOP --> A[\"캡슐화\"]",
    "    OOP --> B[\"상속\"]",
    "    OOP --> C[\"다형성\"]",
    "    OOP --> D[\"추상화\"]",
    "    A --> A1[\"private 필드 + public getter/setter\"]",
    "    B --> B1[\"extends로 부모 기능 물려받기\"]",
    "    C --> C1[\"오버라이딩, 인터페이스\"]",
    "    D --> D1[\"추상 클래스, 인터페이스\"]",
    "    style OOP fill:#4CAF50,color:#fff",
    "```",
    "",
    "---",
    "",
    "## 클래스와 객체의 관계",
    "",
    "- **클래스(Class)** = 설계도, 틀, 청사진",
    "- **객체(Object)** = 클래스로부터 생성된 실체(인스턴스)",
    "",
    "하나의 클래스로 여러 개의 객체를 생성할 수 있으며, 각 객체는 독립적인 데이터를 가집니다.",
    "",
    "```mermaid",
    "classDiagram",
    "    class Car {",
    "        -String brand",
    "        -int speed",
    "        +Car(String brand)",
    "        +accelerate() void",
    "        +brake() void",
    "        +getBrand() String",
    "    }",
    "    note for Car \"클래스 = 설계도\"",
    "```",
    "",
    "```java",
    "// 클래스 정의 (설계도)",
    "public class Car {",
    "    private String brand;",
    "    private int speed;",
    "",
    "    public Car(String brand) {",
    "        this.brand = brand;",
    "        this.speed = 0;",
    "    }",
    "",
    "    public void accelerate() {",
    "        speed += 10;",
    "    }",
    "}",
    "",
    "// 객체 생성 (실체 만들기)",
    "Car car1 = new Car(\"현대\");  // 객체 1",
    "Car car2 = new Car(\"기아\");  // 객체 2 — 서로 독립적",
    "```",
    "",
    "---",
    "",
    "## 클래스 구성 요소",
    "",
    "클래스는 크게 **필드(Field)**, **생성자(Constructor)**, **메서드(Method)** 세 가지로 구성됩니다.",
    "",
    "```java",
    "public class Student {",
    "    // ① 필드 (데이터 저장)",
    "    private String name;",
    "    private int age;",
    "    private static int studentCount = 0;",
    "",
    "    // ② 생성자 (객체 초기화)",
    "    public Student(String name, int age) {",
    "        this.name = name;",
    "        this.age = age;",
    "        studentCount++;",
    "    }",
    "",
    "    // ③ 메서드 (동작 정의)",
    "    public void introduce() {",
    "        System.out.println(name + \" (\" + age + \"세)\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 필드 (Field)",
    "",
    "### 인스턴스 변수 vs 클래스 변수",
    "",
    "| 구분 | 인스턴스 변수 | 클래스 변수 (static) |",
    "|------|-------------|-------------------|",
    "| 선언 | `private int age;` | `private static int count;` |",
    "| 메모리 | 객체마다 별도 | 클래스당 하나 (모든 객체 공유) |",
    "| 접근 | 객체를 통해 | 클래스명으로 직접 접근 가능 |",
    "| 생성 시점 | 객체 생성 시 | 클래스 로딩 시 |",
    "",
    "```java",
    "public class Player {",
    "    private String name;             // 인스턴스 변수",
    "    private static int totalPlayers; // 클래스 변수 (모든 객체 공유)",
    "",
    "    public Player(String name) {",
    "        this.name = name;",
    "        totalPlayers++;",
    "    }",
    "",
    "    public static int getTotalPlayers() {",
    "        return totalPlayers;",
    "    }",
    "}",
    "",
    "Player p1 = new Player(\"홍길동\");",
    "Player p2 = new Player(\"김철수\");",
    "System.out.println(Player.getTotalPlayers()); // 2",
    "```",
    "",
    "---",
    "",
    "## 생성자 (Constructor)",
    "",
    "생성자는 **객체 생성 시 호출**되며, 필드를 초기화하는 역할을 합니다. 이름은 클래스 이름과 동일하고 리턴 타입이 없습니다.",
    "",
    "### 기본 생성자",
    "",
    "생성자를 하나도 정의하지 않으면, 컴파일러가 **기본 생성자**를 자동 생성합니다.",
    "",
    "```java",
    "public class Dog {",
    "    // 생성자 없음 → 컴파일러가 자동 생성:",
    "    // public Dog() { }",
    "}",
    "",
    "Dog dog = new Dog(); // 기본 생성자 호출",
    "```",
    "",
    "> **⚠️ 주의**: 매개변수가 있는 생성자를 하나라도 정의하면 기본 생성자는 자동 생성되지 않습니다.",
    "",
    "### 매개변수 생성자",
    "",
    "```java",
    "public class Person {",
    "    private String name;",
    "    private int age;",
    "",
    "    public Person(String name, int age) {",
    "        this.name = name;",
    "        this.age = age;",
    "    }",
    "}",
    "```",
    "",
    "### 생성자 오버로딩",
    "",
    "매개변수의 타입, 개수, 순서가 다르면 여러 생성자를 정의할 수 있습니다.",
    "",
    "```java",
    "public class Book {",
    "    private String title;",
    "    private String author;",
    "    private int price;",
    "",
    "    public Book() {",
    "        this(\"제목 없음\", \"작자 미상\", 0);",
    "    }",
    "",
    "    public Book(String title) {",
    "        this(title, \"작자 미상\", 0);",
    "    }",
    "",
    "    public Book(String title, String author, int price) {",
    "        this.title = title;",
    "        this.author = author;",
    "        this.price = price;",
    "    }",
    "}",
    "```",
    "",
    "### this() — 다른 생성자 호출",
    "",
    "`this()`를 사용해 같은 클래스의 다른 생성자를 호출할 수 있습니다. **반드시 생성자의 첫 줄**에 위치해야 합니다.",
    "",
    "---",
    "",
    "## 메서드 (Method)",
    "",
    "### 메서드 선언",
    "",
    "```java",
    "접근제어자 리턴타입 메서드명(매개변수) {",
    "    // 실행 코드",
    "    return 값; // void면 생략 가능",
    "}",
    "```",
    "",
    "### 메서드 오버로딩 (Overloading)",
    "",
    "같은 이름이지만 **매개변수가 다른** 메서드를 여러 개 정의할 수 있습니다.",
    "",
    "```java",
    "public class Calculator {",
    "    public int add(int a, int b) {",
    "        return a + b;",
    "    }",
    "",
    "    public double add(double a, double b) {",
    "        return a + b;",
    "    }",
    "",
    "    public int add(int a, int b, int c) {",
    "        return a + b + c;",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## this 키워드",
    "",
    "`this`는 현재 객체 자신을 가리키는 참조입니다.",
    "",
    "```java",
    "public class Account {",
    "    private String owner;",
    "    private int balance;",
    "",
    "    public Account(String owner, int balance) {",
    "        this.owner = owner;      // this.필드 = 매개변수",
    "        this.balance = balance;",
    "    }",
    "",
    "    public Account deposit(int amount) {",
    "        this.balance += amount;",
    "        return this; // 메서드 체이닝을 위한 this 반환",
    "    }",
    "}",
    "",
    "// 메서드 체이닝",
    "Account acc = new Account(\"홍길동\", 0);",
    "acc.deposit(1000).deposit(2000).deposit(3000);",
    "```",
    "",
    "---",
    "",
    "## 접근 제어자",
    "",
    "| 제어자 | 같은 클래스 | 같은 패키지 | 하위 클래스 | 모든 곳 |",
    "|--------|:---------:|:---------:|:---------:|:------:|",
    "| `public` | ✅ | ✅ | ✅ | ✅ |",
    "| `protected` | ✅ | ✅ | ✅ | ❌ |",
    "| `(default)` | ✅ | ✅ | ❌ | ❌ |",
    "| `private` | ✅ | ❌ | ❌ | ❌ |",
    "",
    "> **원칙**: 필드는 `private`, 메서드는 필요한 만큼만 공개 — **정보 은닉(Information Hiding)**",
    "",
    "---",
    "",
    "## Getter / Setter 패턴",
    "",
    "`private` 필드에 대한 읽기/쓰기를 메서드로 제어합니다.",
    "",
    "```java",
    "public class Member {",
    "    private String name;",
    "    private int age;",
    "",
    "    public String getName() {",
    "        return name;",
    "    }",
    "",
    "    public void setName(String name) {",
    "        this.name = name;",
    "    }",
    "",
    "    public int getAge() {",
    "        return age;",
    "    }",
    "",
    "    public void setAge(int age) {",
    "        if (age < 0) {",
    "            throw new IllegalArgumentException(\"나이는 0 이상이어야 합니다.\");",
    "        }",
    "        this.age = age;",
    "    }",
    "}",
    "```",
    "",
    "> setter에서 **유효성 검사**를 수행할 수 있다는 것이 캡슐화의 핵심 장점입니다.",
    "",
    "---",
    "",
    "## static 키워드",
    "",
    "`static`은 **클래스 소속**임을 나타냅니다. 객체 생성 없이 사용 가능합니다.",
    "",
    "### static 필드",
    "",
    "```java",
    "public class Config {",
    "    public static final String APP_NAME = \"MyApp\";",
    "    public static int instanceCount = 0;",
    "}",
    "",
    "System.out.println(Config.APP_NAME); // 객체 생성 없이 접근",
    "```",
    "",
    "### static 메서드",
    "",
    "```java",
    "public class MathUtils {",
    "    public static int max(int a, int b) {",
    "        return (a > b) ? a : b;",
    "    }",
    "}",
    "",
    "int result = MathUtils.max(10, 20); // 객체 생성 없이 호출",
    "```",
    "",
    "> **⚠️ 주의**: static 메서드에서는 인스턴스 필드/메서드에 직접 접근할 수 없습니다. (`this` 사용 불가)",
    "",
    "### static 초기화 블록",
    "",
    "```java",
    "public class Database {",
    "    private static String url;",
    "",
    "    static {",
    "        url = \"jdbc:mysql://localhost:3306/mydb\";",
    "        System.out.println(\"DB 설정 로딩 완료\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## final 키워드",
    "",
    "| 대상 | 의미 |",
    "|------|------|",
    "| `final` 변수 | 한 번 할당 후 변경 불가 (상수) |",
    "| `final` 메서드 | 자식 클래스에서 오버라이딩 불가 |",
    "| `final` 클래스 | 상속 불가 (예: String, Integer) |",
    "",
    "```java",
    "public class Circle {",
    "    public static final double PI = 3.14159265358979;",
    "    private final double radius;",
    "",
    "    public Circle(double radius) {",
    "        this.radius = radius; // final은 생성자에서 한 번 초기화 가능",
    "    }",
    "",
    "    public double getArea() {",
    "        return PI * radius * radius;",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 객체 생성 과정",
    "",
    "`new` 키워드로 객체를 생성할 때 내부적으로 일어나는 과정입니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant Code as 코드",
    "    participant JVM as JVM",
    "    participant Heap as 힙 메모리",
    "    Code->>JVM: new Car(\"현대\")",
    "    JVM->>Heap: 1. 힙에 메모리 할당",
    "    JVM->>Heap: 2. 필드를 기본값으로 초기화",
    "    JVM->>Heap: 3. 생성자 실행 (필드 값 설정)",
    "    JVM-->>Code: 4. 객체 참조(주소) 반환",
    "```",
    "",
    "1. **힙 메모리 할당**: 객체에 필요한 메모리 공간 확보",
    "2. **기본값 초기화**: 필드를 타입별 기본값(0, null, false 등)으로 설정",
    "3. **생성자 실행**: 개발자가 정의한 초기화 로직 수행",
    "4. **참조 반환**: 생성된 객체의 힙 주소를 스택 변수에 저장",
    "",
    "---",
    "",
    "## toString() / equals() / hashCode() 오버라이딩",
    "",
    "Object 클래스의 메서드를 재정의하여 객체를 의미 있게 사용합니다.",
    "",
    "```java",
    "public class Student {",
    "    private String name;",
    "    private int id;",
    "",
    "    public Student(String name, int id) {",
    "        this.name = name;",
    "        this.id = id;",
    "    }",
    "",
    "    @Override",
    "    public String toString() {",
    "        return \"Student{name='\" + name + \"', id=\" + id + \"}\";",
    "    }",
    "",
    "    @Override",
    "    public boolean equals(Object obj) {",
    "        if (this == obj) return true;",
    "        if (!(obj instanceof Student)) return false;",
    "        Student other = (Student) obj;",
    "        return this.id == other.id;",
    "    }",
    "",
    "    @Override",
    "    public int hashCode() {",
    "        return Integer.hashCode(id);",
    "    }",
    "}",
    "```",
    "",
    "> **equals를 오버라이드하면 hashCode도 반드시 오버라이드**해야 합니다. HashMap, HashSet 등에서 올바르게 동작하려면 두 메서드의 일관성이 필요합니다.",
    "",
    "---",
    "",
    "## 불변 객체 (Immutable Object)",
    "",
    "한 번 생성되면 **내부 상태를 변경할 수 없는** 객체입니다. 대표적으로 `String`, `Integer` 등이 있습니다.",
    "",
    "### 불변 객체 만드는 규칙",
    "",
    "1. 모든 필드를 `private final`로 선언",
    "2. setter를 제공하지 않음",
    "3. 가변 참조 필드는 방어적 복사 (defensive copy) 수행",
    "",
    "```java",
    "public final class Money {",
    "    private final int amount;",
    "    private final String currency;",
    "",
    "    public Money(int amount, String currency) {",
    "        this.amount = amount;",
    "        this.currency = currency;",
    "    }",
    "",
    "    public int getAmount() {",
    "        return amount;",
    "    }",
    "",
    "    public String getCurrency() {",
    "        return currency;",
    "    }",
    "",
    "    public Money add(Money other) {",
    "        if (!this.currency.equals(other.currency)) {",
    "            throw new IllegalArgumentException(\"통화가 다릅니다.\");",
    "        }",
    "        return new Money(this.amount + other.amount, this.currency);",
    "    }",
    "}",
    "```",
    "",
    "| 특성 | 가변 객체 | 불변 객체 |",
    "|------|----------|----------|",
    "| 상태 변경 | 가능 (setter) | 불가 (새 객체 반환) |",
    "| 스레드 안전 | 별도 동기화 필요 | 기본적으로 안전 |",
    "| 디버깅 | 상태 추적 어려움 | 예측 가능 |",
    "| 성능 | 수정 시 유리 | 매번 새 객체 생성 비용 |",
    "",
    "---",
    "",
    "## 주의사항 정리",
    "",
    "- 클래스 이름은 **대문자**로 시작 (PascalCase): `Student`, `BankAccount`",
    "- 한 `.java` 파일에 `public class`는 **하나만** 가능하고, 파일 이름과 동일해야 함",
    "- 객체를 더 이상 참조하지 않으면 **GC(Garbage Collector)** 가 자동으로 메모리 회수",
    "- `==`는 참조(주소) 비교, `equals()`는 내용 비교 — equals를 오버라이딩해야 내용 비교 가능",
    "- static 메서드에서 인스턴스 멤버에 접근하면 **컴파일 에러**"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
