<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "java-basic-structure",
  title: "Java 기본 구조 (package, class, main)",
  date: "2026-02-17",
  summary: "Java 프로그래밍 언어의 핵심 구조인 패키지, 클래스, main 메서드를 상세히 알아보고, 컴파일 과정부터 코딩 컨벤션까지 실무에 필요한 기본기를 정리합니다.",
  category: "Coding/Java",
  tags: ["java", "패키지", "main", "기본구조", "basics"],
  content: [
    "## Java 프로그래밍 언어 소개",
    "",
    "Java는 1995년 Sun Microsystems(현재 Oracle)의 제임스 고슬링이 개발한 객체지향 프로그래밍 언어입니다.",
    "**\"Write Once, Run Anywhere\"**(한 번 작성하면 어디서든 실행)라는 철학을 가지고 있으며,",
    "JVM(Java Virtual Machine) 위에서 실행되기 때문에 운영체제에 독립적입니다.",
    "",
    "### Java의 주요 특징",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| 객체지향 | 모든 것이 클래스와 객체로 구성됩니다 |",
    "| 플랫폼 독립적 | JVM 위에서 실행되어 OS에 상관없이 동작합니다 |",
    "| 강타입(Strongly Typed) | 모든 변수의 타입을 명시적으로 선언해야 합니다 |",
    "| 자동 메모리 관리 | Garbage Collector가 사용하지 않는 메모리를 자동 해제합니다 |",
    "| 멀티스레드 지원 | 내장된 스레드 API로 병렬 처리가 가능합니다 |",
    "| 풍부한 표준 라이브러리 | java.util, java.io 등 방대한 API를 제공합니다 |",
    "",
    "---",
    "",
    "## JDK, JRE, JVM의 관계",
    "",
    "Java 개발과 실행 환경은 세 가지 계층으로 구성됩니다.",
    "",
    "```mermaid",
    "graph TB",
    "    JDK[\"JDK (Java Development Kit)\"]",
    "    JRE[\"JRE (Java Runtime Environment)\"]",
    "    JVM[\"JVM (Java Virtual Machine)\"]",
    "    TOOLS[\"개발 도구: javac, jar, javadoc\"]",
    "    LIBS[\"표준 라이브러리: java.lang, java.util 등\"]",
    "    EXEC[\"클래스 로더 + 실행 엔진 + GC\"]",
    "",
    "    JDK --> JRE",
    "    JDK --> TOOLS",
    "    JRE --> JVM",
    "    JRE --> LIBS",
    "    JVM --> EXEC",
    "",
    "    style JDK fill:#4CAF50,color:#fff",
    "    style JRE fill:#2196F3,color:#fff",
    "    style JVM fill:#FF9800,color:#fff",
    "```",
    "",
    "| 구분 | 역할 | 포함 요소 |",
    "|------|------|----------|",
    "| **JDK** | Java 개발 + 실행 환경 | javac(컴파일러), jar, javadoc + JRE 전체 |",
    "| **JRE** | Java 실행 환경 | 표준 라이브러리 + JVM |",
    "| **JVM** | 바이트코드 실행 엔진 | 클래스 로더, 실행 엔진, GC |",
    "",
    "> **💡 팁**: 개발자는 JDK를 설치하고, 일반 사용자는 JRE만 있으면 Java 프로그램을 실행할 수 있습니다.",
    "> Java 11부터는 JRE가 별도로 제공되지 않고 JDK에 통합되었습니다.",
    "",
    "---",
    "",
    "## Java 소스코드 컴파일 과정",
    "",
    "Java 프로그램이 실행되기까지의 과정을 단계별로 살펴봅니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"HelloWorld.java\<br>(소스코드)\"] -->|javac 컴파일| B[\"HelloWorld.class\<br>(바이트코드)\"]",
    "    B -->|java 실행| C[\"JVM\"]",
    "    C -->|클래스 로딩| D[\"클래스 로더\"]",
    "    D -->|실행| E[\"실행 엔진\<br>(인터프리터 + JIT)\"]",
    "    E --> F[\"프로그램 실행 결과\"]",
    "```",
    "",
    "```java",
    "// 1단계: 소스 파일 작성 (HelloWorld.java)",
    "public class HelloWorld {",
    "    public static void main(String[] args) {",
    "        System.out.println(\"Hello, Java!\");",
    "    }",
    "}",
    "```",
    "",
    "```bash",
    "# 2단계: 컴파일 (소스코드 → 바이트코드)",
    "javac HelloWorld.java    # HelloWorld.class 생성",
    "",
    "# 3단계: 실행 (JVM이 바이트코드 해석·실행)",
    "java HelloWorld          # \"Hello, Java!\" 출력",
    "```",
    "",
    "> **⚠️ 주의**: `java` 명령 실행 시 `.class` 확장자를 붙이지 않습니다. `java HelloWorld.class`는 오류입니다.",
    "",
    "---",
    "",
    "## 프로젝트 구조",
    "",
    "일반적인 Java 프로젝트의 디렉토리 구조는 다음과 같습니다.",
    "",
    "```",
    "my-project/",
    "├── src/",
    "│   └── main/",
    "│       └── java/",
    "│           └── com/",
    "│               └── example/",
    "│                   └── app/",
    "│                       ├── Main.java",
    "│                       ├── model/",
    "│                       │   └── User.java",
    "│                       └── service/",
    "│                           └── UserService.java",
    "├── bin/          ← 컴파일된 .class 파일",
    "└── lib/          ← 외부 라이브러리 (.jar)",
    "```",
    "",
    "---",
    "",
    "## package 선언과 import",
    "",
    "### package란?",
    "",
    "패키지는 **관련된 클래스들을 그룹으로 묶는 폴더(디렉토리) 구조**입니다.",
    "클래스 이름의 충돌을 방지하고 코드를 체계적으로 관리할 수 있습니다.",
    "",
    "```java",
    "// 파일 최상단에 반드시 선언 (한 파일에 하나만)",
    "package com.example.app;",
    "",
    "public class Main {",
    "    // ...",
    "}",
    "```",
    "",
    "### 패키지 명명 규칙",
    "",
    "| 규칙 | 예시 | 설명 |",
    "|------|------|------|",
    "| 소문자만 사용 | `com.example.util` | 대문자 사용 금지 |",
    "| 역도메인 구조 | `com.company.project` | 도메인을 거꾸로 사용 |",
    "| 예약어 회피 | `com.example.my_class` | `int`, `class` 등 사용 불가 |",
    "| 의미 있는 이름 | `com.shop.order.service` | 기능·역할을 나타내도록 |",
    "",
    "### import 문",
    "",
    "다른 패키지의 클래스를 사용하려면 `import`가 필요합니다.",
    "",
    "```java",
    "package com.example.app;",
    "",
    "import java.util.Scanner;           // 특정 클래스 import",
    "import java.util.ArrayList;",
    "import java.time.*;                  // 패키지 전체 import (와일드카드)",
    "",
    "// java.lang 패키지는 자동 import (String, System, Math 등)",
    "",
    "public class Main {",
    "    public static void main(String[] args) {",
    "        Scanner sc = new Scanner(System.in);",
    "        ArrayList<String> list = new ArrayList<>();",
    "    }",
    "}",
    "```",
    "",
    "> **💡 팁**: `import java.util.*`처럼 와일드카드를 사용하면 편리하지만,",
    "> 어떤 클래스를 사용하는지 명확하지 않으므로 개별 import를 권장합니다.",
    "> IDE의 자동 import 기능(IntelliJ: Alt+Enter, Eclipse: Ctrl+Shift+O)을 활용하세요.",
    "",
    "---",
    "",
    "## class 구조 상세",
    "",
    "Java의 모든 코드는 클래스 안에 작성됩니다.",
    "",
    "```java",
    "package com.example.model;",
    "",
    "public class Student {",
    "",
    "    // 1. 필드 (멤버 변수)",
    "    private String name;",
    "    private int age;",
    "    private static int count = 0;  // 클래스(정적) 변수",
    "",
    "    // 2. 생성자",
    "    public Student(String name, int age) {",
    "        this.name = name;",
    "        this.age = age;",
    "        count++;",
    "    }",
    "",
    "    // 3. 메서드",
    "    public String getName() {",
    "        return name;",
    "    }",
    "",
    "    public void introduce() {",
    "        System.out.println(name + \"(\" + age + \"세)\");",
    "    }",
    "",
    "    // 4. 정적 메서드",
    "    public static int getCount() {",
    "        return count;",
    "    }",
    "}",
    "```",
    "",
    "### public class와 파일명의 관계",
    "",
    "- 하나의 `.java` 파일에는 **public class가 최대 1개**만 존재할 수 있습니다.",
    "- public class의 이름은 **파일명과 반드시 동일**해야 합니다.",
    "- public이 아닌 class는 같은 파일에 여러 개 작성 가능합니다.",
    "",
    "```java",
    "// 파일명: Student.java (반드시 public class 이름과 동일)",
    "public class Student {",
    "    // ...",
    "}",
    "",
    "class StudentHelper {   // public 아님 → 같은 파일에 작성 가능",
    "    // ...",
    "}",
    "```",
    "",
    "---",
    "",
    "## main 메서드 상세",
    "",
    "main 메서드는 Java 프로그램의 **진입점(Entry Point)**입니다.",
    "JVM이 프로그램을 시작할 때 가장 먼저 호출하는 메서드입니다.",
    "",
    "```java",
    "public static void main(String[] args) {",
    "    System.out.println(\"프로그램 시작!\");",
    "}",
    "```",
    "",
    "### 각 키워드의 의미",
    "",
    "| 키워드 | 의미 | 왜 필요한가? |",
    "|--------|------|-------------|",
    "| `public` | 접근 제한자 — 어디서든 접근 가능 | JVM이 외부에서 호출해야 하므로 |",
    "| `static` | 정적 메서드 — 객체 생성 없이 호출 | JVM이 인스턴스 없이 직접 호출하므로 |",
    "| `void` | 반환값 없음 | 프로그램 종료 시 반환할 값이 없으므로 |",
    "| `main` | 메서드 이름 (고정) | JVM이 이 이름을 약속된 진입점으로 인식 |",
    "| `String[] args` | 명령행 인자 배열 | 실행 시 외부에서 값을 전달받기 위해 |",
    "",
    "### 명령행 인자(args) 활용",
    "",
    "```java",
    "public class ArgsExample {",
    "    public static void main(String[] args) {",
    "        // 전달된 인자 개수 확인",
    "        System.out.println(\"인자 개수: \" + args.length);",
    "",
    "        // 모든 인자 출력",
    "        for (int i = 0; i < args.length; i++) {",
    "            System.out.println(\"args[\" + i + \"] = \" + args[i]);",
    "        }",
    "",
    "        // 활용 예: 계산기",
    "        if (args.length == 3) {",
    "            int a = Integer.parseInt(args[0]);",
    "            String op = args[1];",
    "            int b = Integer.parseInt(args[2]);",
    "",
    "            if (op.equals(\"+\")) {",
    "                System.out.println(\"결과: \" + (a + b));",
    "            }",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "```bash",
    "# 실행 시 인자 전달",
    "java ArgsExample 10 + 20",
    "# 출력: 결과: 30",
    "```",
    "",
    "---",
    "",
    "## System.out 출력 메서드들",
    "",
    "### println, print, printf 비교",
    "",
    "```java",
    "String name = \"홍길동\";",
    "int age = 25;",
    "double score = 95.5;",
    "",
    "// println — 출력 후 줄바꿈",
    "System.out.println(\"이름: \" + name);",
    "System.out.println(\"나이: \" + age);",
    "",
    "// print — 줄바꿈 없이 출력",
    "System.out.print(\"Hello \");",
    "System.out.print(\"World\");  // 같은 줄에 이어서 출력",
    "System.out.println();        // 줄바꿈만",
    "",
    "// printf — 형식 지정 출력",
    "System.out.printf(\"이름: %s, 나이: %d세%n\", name, age);",
    "System.out.printf(\"점수: %.1f점%n\", score);",
    "```",
    "",
    "### printf 주요 포맷 지정자",
    "",
    "| 지정자 | 설명 | 예시 | 결과 |",
    "|--------|------|------|------|",
    "| `%d` | 정수(10진수) | `printf(\"%d\", 42)` | `42` |",
    "| `%f` | 실수 | `printf(\"%.2f\", 3.14159)` | `3.14` |",
    "| `%s` | 문자열 | `printf(\"%s\", \"Java\")` | `Java` |",
    "| `%c` | 문자 1개 | `printf(\"%c\", 'A')` | `A` |",
    "| `%b` | boolean | `printf(\"%b\", true)` | `true` |",
    "| `%n` | 줄바꿈(OS 호환) | `printf(\"끝%n\")` | `끝\<br>` |",
    "| `%x` | 16진수 | `printf(\"%x\", 255)` | `ff` |",
    "| `%o` | 8진수 | `printf(\"%o\", 8)` | `10` |",
    "| `%10d` | 10자리 우측 정렬 | `printf(\"%10d\", 42)` | `        42` |",
    "| `%-10s` | 10자리 좌측 정렬 | `printf(\"%-10s!\", \"Hi\")` | `Hi        !` |",
    "",
    "---",
    "",
    "## Scanner로 입력 받기",
    "",
    "```java",
    "import java.util.Scanner;",
    "",
    "public class InputExample {",
    "    public static void main(String[] args) {",
    "        Scanner scanner = new Scanner(System.in);",
    "",
    "        System.out.print(\"이름 입력: \");",
    "        String name = scanner.nextLine();    // 한 줄 전체",
    "",
    "        System.out.print(\"나이 입력: \");",
    "        int age = scanner.nextInt();          // 정수",
    "",
    "        System.out.print(\"키 입력(cm): \");",
    "        double height = scanner.nextDouble(); // 실수",
    "",
    "        System.out.printf(\"%s님, %d세, %.1fcm%n\", name, age, height);",
    "",
    "        scanner.close();  // 자원 해제",
    "    }",
    "}",
    "```",
    "",
    "> **⚠️ 주의**: `nextInt()` 다음에 `nextLine()`을 호출하면 빈 문자열이 읽힙니다.",
    "> `nextInt()` 뒤에 `scanner.nextLine()`을 한 번 추가하여 남은 줄바꿈을 소비해야 합니다.",
    "",
    "---",
    "",
    "## 주석 (Comments)",
    "",
    "```java",
    "// 단일행 주석: 한 줄만 주석 처리",
    "",
    "/*",
    " * 다중행 주석:",
    " * 여러 줄에 걸쳐",
    " * 주석을 작성할 수 있습니다.",
    " */",
    "",
    "/**",
    " * Javadoc 주석: API 문서를 자동 생성합니다.",
    " * @param name 학생 이름",
    " * @param age  학생 나이",
    " * @return 생성된 Student 객체",
    " * @throws IllegalArgumentException 나이가 음수일 때",
    " */",
    "public static Student create(String name, int age) {",
    "    if (age < 0) throw new IllegalArgumentException(\"나이는 0 이상\");",
    "    return new Student(name, age);",
    "}",
    "```",
    "",
    "| 주석 종류 | 문법 | 용도 |",
    "|----------|------|------|",
    "| 단일행 | `// 내용` | 간단한 설명 |",
    "| 다중행 | `/* 내용 */` | 여러 줄 설명, 코드 비활성화 |",
    "| Javadoc | `/** 내용 */` | API 문서 생성용 (javadoc 명령) |",
    "",
    "---",
    "",
    "## 코딩 컨벤션 (네이밍 규칙)",
    "",
    "Java 커뮤니티에서 널리 사용되는 네이밍 규칙입니다.",
    "",
    "| 대상 | 규칙 | 예시 |",
    "|------|------|------|",
    "| 패키지 | 모두 소문자 | `com.example.service` |",
    "| 클래스 / 인터페이스 | PascalCase (대문자 시작) | `StudentService`, `Runnable` |",
    "| 메서드 / 변수 | camelCase (소문자 시작) | `getName()`, `totalScore` |",
    "| 상수 (final) | UPPER_SNAKE_CASE | `MAX_SIZE`, `DEFAULT_NAME` |",
    "",
    "```java",
    "package com.school.service;          // 패키지: 소문자",
    "",
    "public class StudentManager {        // 클래스: PascalCase",
    "",
    "    private static final int MAX_STUDENTS = 100;  // 상수: UPPER_SNAKE",
    "",
    "    private String studentName;       // 변수: camelCase",
    "",
    "    public String getStudentName() {  // 메서드: camelCase",
    "        return studentName;",
    "    }",
    "}",
    "```",
    "",
    "### 추가 컨벤션",
    "",
    "- **중괄호 스타일**: 여는 중괄호 `{`는 선언문과 같은 줄에 작성합니다 (K&R 스타일).",
    "- **들여쓰기**: 4칸 스페이스 (또는 탭 1개)를 사용합니다.",
    "- **한 줄 길이**: 120자 이내를 권장합니다.",
    "- **빈 줄**: 메서드 사이, 논리적 블록 사이에 빈 줄을 넣어 가독성을 높입니다.",
    "",
    "---",
    "",
    "## 전체 구조 한눈에 보기",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"1. package 선언\"] --> B[\"2. import 문\"]",
    "    B --> C[\"3. class 선언\"]",
    "    C --> D[\"4. 필드(변수)\"]",
    "    C --> E[\"5. 생성자\"]",
    "    C --> F[\"6. 메서드\"]",
    "    F --> G[\"main 메서드\<br>(진입점)\"]",
    "```",
    "",
    "```java",
    "package com.example.app;               // 1. 패키지 선언",
    "",
    "import java.util.Scanner;              // 2. import",
    "",
    "public class MyApp {                   // 3. 클래스 선언",
    "",
    "    private static final String TITLE = \"My App\";  // 4. 필드",
    "",
    "    public MyApp() {                   // 5. 생성자",
    "        System.out.println(TITLE + \" 초기화\");",
    "    }",
    "",
    "    public void run() {               // 6. 일반 메서드",
    "        Scanner sc = new Scanner(System.in);",
    "        System.out.print(\"입력: \");",
    "        String input = sc.nextLine();",
    "        System.out.println(\"입력값: \" + input);",
    "        sc.close();",
    "    }",
    "",
    "    public static void main(String[] args) {  // main 진입점",
    "        MyApp app = new MyApp();",
    "        app.run();",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 요약",
    "",
    "| 항목 | 핵심 내용 |",
    "|------|----------|",
    "| Java 실행 구조 | `.java` → (javac) → `.class` → (JVM) → 실행 |",
    "| JDK vs JRE vs JVM | JDK ⊃ JRE ⊃ JVM (개발 ⊃ 실행 ⊃ 엔진) |",
    "| package | 클래스를 폴더로 분류, 파일 첫 줄에 선언 |",
    "| import | 다른 패키지의 클래스를 사용하기 위해 선언 |",
    "| class | 모든 Java 코드의 기본 단위, 파일명 = public 클래스명 |",
    "| main 메서드 | `public static void main(String[] args)` — 프로그램 진입점 |",
    "| 출력 | `println`(줄바꿈), `print`(줄바꿈 없음), `printf`(포맷 지정) |",
    "| 입력 | `Scanner` 클래스로 키보드 입력 처리 |",
    "| 네이밍 | 클래스=PascalCase, 변수/메서드=camelCase, 상수=UPPER_SNAKE |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
