<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "java-interface",
  title: "Java 인터페이스 (interface)",
  date: "2026-02-17",
  summary: "Java 인터페이스의 선언, implements, default/static/private 메서드, 다중 구현, 추상 클래스와 비교, 함수형 인터페이스, 전략 패턴까지 상세히 정리합니다.",
  category: "Coding/Java",
  tags: ["java", "인터페이스", "interface", "implements", "basics"],
  content: [
    "## 인터페이스란?",
    "",
    "인터페이스(Interface)는 **구현 클래스가 반드시 따라야 할 규약(계약)** 을 정의하는 것입니다. \"무엇을 할 수 있는가\"를 명시하되, \"어떻게 하는가\"는 구현 클래스에 맡깁니다.",
    "",
    "- 추상 메서드의 집합으로, 구현 강제",
    "- 다중 구현 가능 (`implements A, B`)",
    "- 서로 관련 없는 클래스에 공통 기능을 부여",
    "",
    "```mermaid",
    "classDiagram",
    "    class Flyable {",
    "        <<interface>>",
    "        +fly() void",
    "    }",
    "    class Swimmable {",
    "        <<interface>>",
    "        +swim() void",
    "    }",
    "    class Duck {",
    "        +fly() void",
    "        +swim() void",
    "        +quack() void",
    "    }",
    "    Flyable <|.. Duck : implements",
    "    Swimmable <|.. Duck : implements",
    "```",
    "",
    "---",
    "",
    "## interface 선언",
    "",
    "```java",
    "public interface Soundable {",
    "    // 상수 (자동으로 public static final)",
    "    int MAX_VOLUME = 100;",
    "",
    "    // 추상 메서드 (자동으로 public abstract)",
    "    String sound();",
    "",
    "    // default 메서드 (Java 8+)",
    "    default void info() {",
    "        System.out.println(\"소리를 낼 수 있는 객체입니다.\");",
    "    }",
    "",
    "    // static 메서드 (Java 8+)",
    "    static void description() {",
    "        System.out.println(\"Soundable 인터페이스\");",
    "    }",
    "}",
    "```",
    "",
    "> 인터페이스의 모든 메서드는 기본적으로 `public`이므로, 구현 시 반드시 `public`으로 선언해야 합니다.",
    "",
    "---",
    "",
    "## implements 키워드",
    "",
    "클래스가 인터페이스를 구현할 때 `implements`를 사용합니다. **모든 추상 메서드를 반드시 구현**해야 합니다.",
    "",
    "```java",
    "public class Dog implements Soundable {",
    "    @Override",
    "    public String sound() {",
    "        return \"멍멍\";",
    "    }",
    "}",
    "",
    "public class Cat implements Soundable {",
    "    @Override",
    "    public String sound() {",
    "        return \"야옹\";",
    "    }",
    "}",
    "",
    "public class Horn implements Soundable {",
    "    @Override",
    "    public String sound() {",
    "        return \"빵빵\";",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 추상 메서드 (abstract)",
    "",
    "인터페이스의 메서드는 기본적으로 `public abstract`입니다. 본문(body)이 없으며, 구현 클래스가 반드시 오버라이딩해야 합니다.",
    "",
    "```java",
    "public interface Drawable {",
    "    void draw();          // public abstract 생략 가능",
    "    void resize(int size); // public abstract 생략 가능",
    "}",
    "",
    "public class Circle implements Drawable {",
    "    @Override",
    "    public void draw() {",
    "        System.out.println(\"원을 그립니다.\");",
    "    }",
    "",
    "    @Override",
    "    public void resize(int size) {",
    "        System.out.println(\"크기를 \" + size + \"로 조절합니다.\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## default 메서드 (Java 8+)",
    "",
    "`default` 메서드는 인터페이스에 **구현이 포함된 메서드**입니다. 기존 인터페이스에 새 기능을 추가하면서도 하위 호환성을 유지할 수 있습니다.",
    "",
    "```java",
    "public interface Loggable {",
    "    void log(String message);",
    "",
    "    default void logInfo(String message) {",
    "        log(\"[INFO] \" + message);",
    "    }",
    "",
    "    default void logError(String message) {",
    "        log(\"[ERROR] \" + message);",
    "    }",
    "}",
    "",
    "public class ConsoleLogger implements Loggable {",
    "    @Override",
    "    public void log(String message) {",
    "        System.out.println(message);",
    "    }",
    "    // logInfo(), logError()는 구현하지 않아도 default 사용 가능",
    "}",
    "```",
    "",
    "```java",
    "ConsoleLogger logger = new ConsoleLogger();",
    "logger.logInfo(\"서버 시작\");   // [INFO] 서버 시작",
    "logger.logError(\"연결 실패\");  // [ERROR] 연결 실패",
    "```",
    "",
    "> default 메서드도 필요하면 구현 클래스에서 **오버라이딩 가능**합니다.",
    "",
    "---",
    "",
    "## static 메서드 (Java 8+)",
    "",
    "인터페이스에 정의된 `static` 메서드는 **인터페이스 이름으로 직접 호출**합니다. 구현 클래스에서 오버라이딩할 수 없습니다.",
    "",
    "```java",
    "public interface StringUtils {",
    "    static boolean isEmpty(String str) {",
    "        return str == null || str.trim().isEmpty();",
    "    }",
    "",
    "    static String capitalize(String str) {",
    "        if (isEmpty(str)) return str;",
    "        return str.substring(0, 1).toUpperCase() + str.substring(1);",
    "    }",
    "}",
    "",
    "// 사용",
    "StringUtils.isEmpty(\"\");          // true",
    "StringUtils.capitalize(\"hello\");  // \"Hello\"",
    "```",
    "",
    "---",
    "",
    "## private 메서드 (Java 9+)",
    "",
    "인터페이스 내부에서만 사용하는 **공통 로직을 추출**할 때 사용합니다. default 메서드 간 코드 중복을 제거합니다.",
    "",
    "```java",
    "public interface Validator {",
    "    default boolean validateName(String name) {",
    "        return isNotEmpty(name) && name.length() >= 2;",
    "    }",
    "",
    "    default boolean validateEmail(String email) {",
    "        return isNotEmpty(email) && email.contains(\"@\");",
    "    }",
    "",
    "    // private 메서드 — 외부에서 접근 불가",
    "    private boolean isNotEmpty(String str) {",
    "        return str != null && !str.trim().isEmpty();",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 상수 (public static final)",
    "",
    "인터페이스에 선언된 변수는 자동으로 `public static final`이 됩니다. 즉, 상수만 선언 가능합니다.",
    "",
    "```java",
    "public interface GameConstants {",
    "    int MAX_PLAYERS = 4;        // public static final 자동 적용",
    "    int DEFAULT_LIVES = 3;",
    "    String GAME_TITLE = \"MyGame\";",
    "}",
    "",
    "// 사용",
    "System.out.println(GameConstants.MAX_PLAYERS); // 4",
    "```",
    "",
    "---",
    "",
    "## 다중 구현",
    "",
    "클래스는 **여러 인터페이스를 동시에 구현**할 수 있습니다. 이것이 Java에서 다중 상속 문제를 해결하는 방법입니다.",
    "",
    "```java",
    "public interface Flyable {",
    "    void fly();",
    "}",
    "",
    "public interface Swimmable {",
    "    void swim();",
    "}",
    "",
    "public class Duck implements Flyable, Swimmable {",
    "    @Override",
    "    public void fly() {",
    "        System.out.println(\"오리가 날아갑니다.\");",
    "    }",
    "",
    "    @Override",
    "    public void swim() {",
    "        System.out.println(\"오리가 헤엄칩니다.\");",
    "    }",
    "}",
    "```",
    "",
    "> **💡 팁**: 두 인터페이스에 동일한 시그니처의 default 메서드가 있으면, 구현 클래스에서 반드시 오버라이딩해야 합니다.",
    "",
    "---",
    "",
    "## 인터페이스 상속 (extends)",
    "",
    "인터페이스끼리는 `extends`로 상속할 수 있으며, **다중 상속도 가능**합니다.",
    "",
    "```java",
    "public interface Readable {",
    "    void read();",
    "}",
    "",
    "public interface Writable {",
    "    void write();",
    "}",
    "",
    "// 인터페이스 다중 상속",
    "public interface ReadWritable extends Readable, Writable {",
    "    void flush();",
    "}",
    "",
    "// 구현 클래스는 3개의 메서드를 모두 구현",
    "public class FileHandler implements ReadWritable {",
    "    @Override",
    "    public void read() { System.out.println(\"파일 읽기\"); }",
    "",
    "    @Override",
    "    public void write() { System.out.println(\"파일 쓰기\"); }",
    "",
    "    @Override",
    "    public void flush() { System.out.println(\"버퍼 비우기\"); }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 인터페이스 vs 추상 클래스",
    "",
    "| 특성 | 인터페이스 | 추상 클래스 |",
    "|------|----------|-----------|",
    "| 키워드 | `interface` | `abstract class` |",
    "| 다중 상속/구현 | 다중 구현 가능 | 단일 상속만 |",
    "| 생성자 | 없음 | 있음 |",
    "| 필드 | 상수만 (`public static final`) | 인스턴스 변수 가능 |",
    "| 메서드 | abstract, default, static, private | abstract + 일반 메서드 |",
    "| 접근 제어자 | `public`만 (abstract) | 모든 접근 제어자 |",
    "| 용도 | \"할 수 있는 것\" (능력) | \"~이다\" (공통 속성) |",
    "| 예시 | Comparable, Serializable | AbstractList, HttpServlet |",
    "",
    "### 언제 무엇을 사용할까?",
    "",
    "- **인터페이스**: 관련 없는 클래스들에 공통 기능을 부여할 때",
    "- **추상 클래스**: 관련 있는 클래스들이 공통 코드를 공유할 때",
    "",
    "---",
    "",
    "## 다형성과 인터페이스",
    "",
    "인터페이스 타입으로 구현 객체를 참조하면, **구현이 바뀌어도 호출 코드를 변경하지 않아도** 됩니다.",
    "",
    "```java",
    "public interface MessageSender {",
    "    void send(String message);",
    "}",
    "",
    "public class EmailSender implements MessageSender {",
    "    @Override",
    "    public void send(String message) {",
    "        System.out.println(\"이메일 전송: \" + message);",
    "    }",
    "}",
    "",
    "public class SmsSender implements MessageSender {",
    "    @Override",
    "    public void send(String message) {",
    "        System.out.println(\"SMS 전송: \" + message);",
    "    }",
    "}",
    "",
    "// 호출 코드 — 구현에 의존하지 않음",
    "public class NotificationService {",
    "    private MessageSender sender;",
    "",
    "    public NotificationService(MessageSender sender) {",
    "        this.sender = sender;",
    "    }",
    "",
    "    public void notify(String msg) {",
    "        sender.send(msg);",
    "    }",
    "}",
    "",
    "// 사용",
    "NotificationService svc1 = new NotificationService(new EmailSender());",
    "svc1.notify(\"안녕하세요\"); // 이메일 전송: 안녕하세요",
    "",
    "NotificationService svc2 = new NotificationService(new SmsSender());",
    "svc2.notify(\"안녕하세요\"); // SMS 전송: 안녕하세요",
    "```",
    "",
    "---",
    "",
    "## 함수형 인터페이스 (@FunctionalInterface)",
    "",
    "**추상 메서드가 딱 하나**인 인터페이스입니다. 람다 표현식의 타겟 타입으로 사용됩니다.",
    "",
    "```java",
    "@FunctionalInterface",
    "public interface Calculator {",
    "    int calculate(int a, int b);",
    "}",
    "```",
    "",
    "> `@FunctionalInterface`는 선택 사항이지만, 실수로 추상 메서드를 2개 이상 선언하면 컴파일 에러를 발생시켜줍니다.",
    "",
    "### 람다 표현식과의 관계",
    "",
    "함수형 인터페이스는 **람다 표현식**으로 간결하게 구현할 수 있습니다.",
    "",
    "```java",
    "// 익명 클래스 (기존 방식)",
    "Calculator add = new Calculator() {",
    "    @Override",
    "    public int calculate(int a, int b) {",
    "        return a + b;",
    "    }",
    "};",
    "",
    "// 람다 표현식 (Java 8+)",
    "Calculator addLambda = (a, b) -> a + b;",
    "Calculator subtract = (a, b) -> a - b;",
    "Calculator multiply = (a, b) -> a * b;",
    "",
    "System.out.println(addLambda.calculate(10, 5));  // 15",
    "System.out.println(subtract.calculate(10, 5));   // 5",
    "System.out.println(multiply.calculate(10, 5));   // 50",
    "```",
    "",
    "### Java 표준 함수형 인터페이스",
    "",
    "| 인터페이스 | 추상 메서드 | 용도 |",
    "|----------|-----------|------|",
    "| `Function<T, R>` | `R apply(T t)` | 변환 (입력 → 출력) |",
    "| `Consumer<T>` | `void accept(T t)` | 소비 (입력만) |",
    "| `Supplier<T>` | `T get()` | 공급 (출력만) |",
    "| `Predicate<T>` | `boolean test(T t)` | 판별 (조건 검사) |",
    "",
    "---",
    "",
    "## Comparable / Comparator 예제",
    "",
    "### Comparable — 자연 순서 정의",
    "",
    "```java",
    "import java.util.List;",
    "import java.util.ArrayList;",
    "import java.util.Collections;",
    "",
    "public class Student implements Comparable<Student> {",
    "    private String name;",
    "    private int score;",
    "",
    "    public Student(String name, int score) {",
    "        this.name = name;",
    "        this.score = score;",
    "    }",
    "",
    "    @Override",
    "    public int compareTo(Student other) {",
    "        return Integer.compare(this.score, other.score); // 점수 오름차순",
    "    }",
    "",
    "    @Override",
    "    public String toString() {",
    "        return name + \"(\" + score + \")\";",
    "    }",
    "}",
    "",
    "List<Student> students = new ArrayList<>(List.of(",
    "    new Student(\"김철수\", 85),",
    "    new Student(\"이영희\", 92),",
    "    new Student(\"박민수\", 78)",
    "));",
    "Collections.sort(students);",
    "System.out.println(students); // [박민수(78), 김철수(85), 이영희(92)]",
    "```",
    "",
    "### Comparator — 사용자 정의 순서",
    "",
    "```java",
    "// 이름 기준 정렬 (Comparator)",
    "students.sort(Comparator.comparing(Student::getName));",
    "",
    "// 점수 내림차순",
    "students.sort(Comparator.comparing(Student::getScore).reversed());",
    "",
    "// 람다 사용",
    "students.sort((s1, s2) -> s2.getScore() - s1.getScore());",
    "```",
    "",
    "---",
    "",
    "## 전략 패턴 (Strategy Pattern) 소개",
    "",
    "인터페이스를 활용한 대표적인 디자인 패턴입니다. **알고리즘을 캡슐화**하여 런타임에 교체할 수 있게 합니다.",
    "",
    "```mermaid",
    "classDiagram",
    "    class PaymentStrategy {",
    "        <<interface>>",
    "        +pay(int amount) void",
    "    }",
    "    class CreditCardPayment {",
    "        -String cardNumber",
    "        +pay(int amount) void",
    "    }",
    "    class BankTransferPayment {",
    "        -String bankAccount",
    "        +pay(int amount) void",
    "    }",
    "    class ShoppingCart {",
    "        -PaymentStrategy strategy",
    "        +checkout(int amount) void",
    "    }",
    "    PaymentStrategy <|.. CreditCardPayment",
    "    PaymentStrategy <|.. BankTransferPayment",
    "    ShoppingCart --> PaymentStrategy",
    "```",
    "",
    "```java",
    "public interface PaymentStrategy {",
    "    void pay(int amount);",
    "}",
    "",
    "public class CreditCardPayment implements PaymentStrategy {",
    "    private String cardNumber;",
    "",
    "    public CreditCardPayment(String cardNumber) {",
    "        this.cardNumber = cardNumber;",
    "    }",
    "",
    "    @Override",
    "    public void pay(int amount) {",
    "        System.out.println(amount + \"원을 신용카드(\" + cardNumber + \")로 결제\");",
    "    }",
    "}",
    "",
    "public class BankTransferPayment implements PaymentStrategy {",
    "    private String bankAccount;",
    "",
    "    public BankTransferPayment(String bankAccount) {",
    "        this.bankAccount = bankAccount;",
    "    }",
    "",
    "    @Override",
    "    public void pay(int amount) {",
    "        System.out.println(amount + \"원을 계좌이체(\" + bankAccount + \")로 결제\");",
    "    }",
    "}",
    "",
    "public class ShoppingCart {",
    "    private PaymentStrategy strategy;",
    "",
    "    public void setPaymentStrategy(PaymentStrategy strategy) {",
    "        this.strategy = strategy;",
    "    }",
    "",
    "    public void checkout(int amount) {",
    "        strategy.pay(amount);",
    "    }",
    "}",
    "",
    "// 사용",
    "ShoppingCart cart = new ShoppingCart();",
    "",
    "cart.setPaymentStrategy(new CreditCardPayment(\"1234-5678\"));",
    "cart.checkout(50000); // 50000원을 신용카드(1234-5678)로 결제",
    "",
    "cart.setPaymentStrategy(new BankTransferPayment(\"110-123-456\"));",
    "cart.checkout(30000); // 30000원을 계좌이체(110-123-456)로 결제",
    "```",
    "",
    "---",
    "",
    "## 주의사항 정리",
    "",
    "- 인터페이스는 **직접 인스턴스화할 수 없음** (`new Soundable()` 불가)",
    "- 인터페이스의 모든 추상 메서드를 구현하지 않으면, 해당 클래스도 `abstract`로 선언해야 함",
    "- default 메서드 충돌 시 구현 클래스에서 **반드시 오버라이딩** 필요",
    "- Java 8 이전에는 인터페이스에 abstract 메서드와 상수만 가능했음",
    "- 인터페이스는 `Serializable`, `Cloneable`처럼 **마커 인터페이스**(메서드 없는 인터페이스)로도 사용됨",
    "- 의존성을 인터페이스에 두면 **느슨한 결합(Loose Coupling)** 이 가능해져 테스트와 유지보수에 유리"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
