<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "java-conditionals",
  title: "Java 조건문 (if, switch)",
  date: "2026-02-17",
  summary: "Java의 if, else if, else, switch-case 조건문은 물론 삼항 연산자, switch 표현식(Java 14+), 패턴 매칭까지 조건 분기의 모든 것을 정리합니다.",
  category: "Coding/Java",
  tags: ["java", "조건문", "if", "switch", "basics"],
  content: [
    "## 조건문이란",
    "",
    "조건문은 **주어진 조건의 참/거짓에 따라 실행 흐름을 분기**하는 제어문입니다.",
    "프로그램이 상황에 맞는 동작을 수행하도록 만드는 핵심 구조입니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"시작\"] --> B{\"조건 판단\"}",
    "    B -->|true| C[\"블록 A 실행\"]",
    "    B -->|false| D[\"블록 B 실행\"]",
    "    C --> E[\"계속\"]",
    "    D --> E",
    "```",
    "",
    "---",
    "",
    "## 비교 연산자",
    "",
    "조건문에서 조건을 작성할 때 사용하는 연산자입니다. 결과는 항상 `boolean`(true/false)입니다.",
    "",
    "| 연산자 | 의미 | 예시 | 결과 |",
    "|--------|------|------|------|",
    "| `==` | 같다 | `5 == 5` | true |",
    "| `!=` | 같지 않다 | `5 != 3` | true |",
    "| `>` | 크다 | `5 > 3` | true |",
    "| `<` | 작다 | `5 < 3` | false |",
    "| `>=` | 크거나 같다 | `5 >= 5` | true |",
    "| `<=` | 작거나 같다 | `3 <= 5` | true |",
    "",
    "---",
    "",
    "## 논리 연산자",
    "",
    "여러 조건을 **결합**할 때 사용합니다.",
    "",
    "| 연산자 | 의미 | 설명 |",
    "|--------|------|------|",
    "| `&&` | AND (그리고) | 둘 다 true일 때만 true |",
    "| `\\|\\|` | OR (또는) | 둘 중 하나라도 true이면 true |",
    "| `!` | NOT (부정) | true → false, false → true |",
    "",
    "```java",
    "int age = 25;",
    "boolean hasLicense = true;",
    "",
    "// AND: 두 조건 모두 만족",
    "if (age >= 18 && hasLicense) {",
    "    System.out.println(\"운전 가능\");",
    "}",
    "",
    "// OR: 하나라도 만족",
    "if (age < 13 || age >= 65) {",
    "    System.out.println(\"할인 대상\");",
    "}",
    "",
    "// NOT: 조건 반전",
    "if (!hasLicense) {",
    "    System.out.println(\"면허가 없습니다\");",
    "}",
    "```",
    "",
    "> **💡 팁**: `&&`와 `||`는 **단축 평가(Short-circuit Evaluation)**를 수행합니다.",
    "> `&&`에서 앞 조건이 false이면 뒤 조건은 평가하지 않고, `||`에서 앞 조건이 true이면 뒤 조건을 평가하지 않습니다.",
    "",
    "---",
    "",
    "## if문",
    "",
    "### 기본 if문",
    "",
    "```java",
    "int score = 85;",
    "",
    "if (score >= 60) {",
    "    System.out.println(\"합격입니다!\");",
    "}",
    "```",
    "",
    "### if-else문",
    "",
    "```java",
    "int score = 45;",
    "",
    "if (score >= 60) {",
    "    System.out.println(\"합격\");",
    "} else {",
    "    System.out.println(\"불합격\");",
    "}",
    "```",
    "",
    "### if-else if-else문",
    "",
    "```java",
    "int score = 85;",
    "String grade;",
    "",
    "if (score >= 90) {",
    "    grade = \"A\";",
    "} else if (score >= 80) {",
    "    grade = \"B\";",
    "} else if (score >= 70) {",
    "    grade = \"C\";",
    "} else if (score >= 60) {",
    "    grade = \"D\";",
    "} else {",
    "    grade = \"F\";",
    "}",
    "",
    "System.out.println(\"등급: \" + grade);  // 등급: B",
    "```",
    "",
    "### 중첩 if문",
    "",
    "```java",
    "int score = 95;",
    "boolean isExtraCredit = true;",
    "",
    "if (score >= 90) {",
    "    if (isExtraCredit) {",
    "        System.out.println(\"A+ (가산점 포함)\");",
    "    } else {",
    "        System.out.println(\"A\");",
    "    }",
    "} else {",
    "    System.out.println(\"A 미만\");",
    "}",
    "```",
    "",
    "> **💡 팁**: 중첩이 깊어지면 코드 가독성이 떨어집니다.",
    "> 가능하면 조건을 결합하거나 메서드로 분리하여 중첩을 줄이세요.",
    "",
    "---",
    "",
    "## 삼항 연산자 (?:)",
    "",
    "간단한 if-else를 **한 줄**로 표현할 수 있습니다.",
    "",
    "```java",
    "// 문법: 조건 ? 참일때_값 : 거짓일때_값",
    "",
    "int score = 75;",
    "String result = (score >= 60) ? \"합격\" : \"불합격\";",
    "System.out.println(result);  // 합격",
    "",
    "// 활용 예시",
    "int a = 10, b = 20;",
    "int max = (a > b) ? a : b;   // 큰 값 선택",
    "",
    "int age = 17;",
    "String category = (age >= 18) ? \"성인\" : \"미성년자\";",
    "",
    "// 중첩 삼항 (가독성 주의!)",
    "String grade = (score >= 90) ? \"A\" :",
    "               (score >= 80) ? \"B\" :",
    "               (score >= 70) ? \"C\" : \"F\";",
    "```",
    "",
    "> **⚠️ 주의**: 삼항 연산자를 중첩하면 읽기 어려워집니다.",
    "> 복잡한 조건은 if-else if를 사용하세요.",
    "",
    "---",
    "",
    "## switch문",
    "",
    "### 기본 문법",
    "",
    "하나의 변수 값에 따라 여러 경우로 분기합니다.",
    "",
    "```java",
    "int day = 3;",
    "String dayName;",
    "",
    "switch (day) {",
    "    case 1:",
    "        dayName = \"월요일\";",
    "        break;",
    "    case 2:",
    "        dayName = \"화요일\";",
    "        break;",
    "    case 3:",
    "        dayName = \"수요일\";",
    "        break;",
    "    case 4:",
    "        dayName = \"목요일\";",
    "        break;",
    "    case 5:",
    "        dayName = \"금요일\";",
    "        break;",
    "    case 6:",
    "        dayName = \"토요일\";",
    "        break;",
    "    case 7:",
    "        dayName = \"일요일\";",
    "        break;",
    "    default:",
    "        dayName = \"잘못된 값\";",
    "        break;",
    "}",
    "",
    "System.out.println(dayName);  // 수요일",
    "```",
    "",
    "### break의 역할과 fall-through",
    "",
    "`break`를 생략하면 다음 case로 계속 실행됩니다 (**fall-through**).",
    "의도적으로 사용할 수도 있지만, 보통은 버그의 원인이 됩니다.",
    "",
    "```java",
    "int month = 8;",
    "String season;",
    "",
    "// fall-through를 의도적으로 활용한 예",
    "switch (month) {",
    "    case 3: case 4: case 5:",
    "        season = \"봄\";",
    "        break;",
    "    case 6: case 7: case 8:",
    "        season = \"여름\";",
    "        break;",
    "    case 9: case 10: case 11:",
    "        season = \"가을\";",
    "        break;",
    "    case 12: case 1: case 2:",
    "        season = \"겨울\";",
    "        break;",
    "    default:",
    "        season = \"알 수 없음\";",
    "}",
    "",
    "System.out.println(season);  // 여름",
    "```",
    "",
    "### switch에서 사용 가능한 타입",
    "",
    "| 타입 | Java 버전 | 예시 |",
    "|------|----------|------|",
    "| `byte`, `short`, `int` | 1.0+ | `switch (number)` |",
    "| `char` | 1.0+ | `switch (grade)` |",
    "| `String` | 7+ | `switch (command)` |",
    "| `enum` | 5+ | `switch (direction)` |",
    "",
    "```java",
    "// String switch 예시",
    "String command = \"start\";",
    "",
    "switch (command) {",
    "    case \"start\":",
    "        System.out.println(\"시작합니다\");",
    "        break;",
    "    case \"stop\":",
    "        System.out.println(\"중지합니다\");",
    "        break;",
    "    case \"pause\":",
    "        System.out.println(\"일시정지\");",
    "        break;",
    "    default:",
    "        System.out.println(\"알 수 없는 명령\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## switch 표현식 (Java 14+)",
    "",
    "Java 14부터 **화살표 구문(->)**으로 switch를 간결하게 작성할 수 있습니다.",
    "`break`가 필요 없고, 값을 반환할 수 있습니다.",
    "",
    "```java",
    "int day = 3;",
    "",
    "// 화살표 구문: break 불필요, fall-through 없음",
    "String dayName = switch (day) {",
    "    case 1 -> \"월요일\";",
    "    case 2 -> \"화요일\";",
    "    case 3 -> \"수요일\";",
    "    case 4 -> \"목요일\";",
    "    case 5 -> \"금요일\";",
    "    case 6 -> \"토요일\";",
    "    case 7 -> \"일요일\";",
    "    default -> \"잘못된 값\";",
    "};",
    "",
    "System.out.println(dayName);  // 수요일",
    "```",
    "",
    "### 여러 case 묶기 & yield",
    "",
    "```java",
    "int month = 8;",
    "",
    "// 여러 case를 쉼표로 묶기",
    "String season = switch (month) {",
    "    case 3, 4, 5 -> \"봄\";",
    "    case 6, 7, 8 -> \"여름\";",
    "    case 9, 10, 11 -> \"가을\";",
    "    case 12, 1, 2 -> \"겨울\";",
    "    default -> \"알 수 없음\";",
    "};",
    "",
    "// 블록이 필요할 때: yield로 값 반환",
    "String description = switch (month) {",
    "    case 6, 7, 8 -> {",
    "        String msg = \"더운 \" + season;",
    "        yield msg + \" 시즌입니다\";",
    "    }",
    "    default -> season + \" 시즌입니다\";",
    "};",
    "```",
    "",
    "> **💡 팁**: 화살표 구문에서 여러 줄이 필요하면 중괄호 `{}`를 쓰고 `yield`로 값을 반환합니다.",
    "> `return`이 아닌 `yield`임에 주의하세요.",
    "",
    "---",
    "",
    "## if vs switch 선택 가이드",
    "",
    "| 상황 | 추천 | 이유 |",
    "|------|------|------|",
    "| 범위 조건 (`score >= 90`) | **if** | switch는 정확한 값 매칭만 가능 |",
    "| 정확한 값 매칭 (`day == 3`) | **switch** | 가독성이 좋고 성능도 유리 |",
    "| 조건이 2~3개 | **if** | 간단한 분기에 적합 |",
    "| 조건이 4개 이상 | **switch** | 구조화된 분기 표현에 유리 |",
    "| 복합 조건 (`a > 0 && b < 10`) | **if** | switch는 단일 값 비교만 가능 |",
    "| enum 분기 | **switch** | enum과 switch는 궁합이 좋음 |",
    "",
    "---",
    "",
    "## 조건문에서 String 비교",
    "",
    "```java",
    "String input = \"yes\";",
    "",
    "// ❌ 잘못된 비교 (== 는 참조 비교)",
    "if (input == \"yes\") {  // 동작할 수도 있지만 보장되지 않음",
    "    System.out.println(\"참\");",
    "}",
    "",
    "// ✅ 올바른 비교 (equals로 내용 비교)",
    "if (input.equals(\"yes\")) {",
    "    System.out.println(\"참\");",
    "}",
    "",
    "// ✅ NullPointerException 방지 (상수를 앞에)",
    "if (\"yes\".equals(input)) {",
    "    System.out.println(\"참 (null-safe)\");",
    "}",
    "",
    "// ✅ 대소문자 무시 비교",
    "if (input.equalsIgnoreCase(\"YES\")) {",
    "    System.out.println(\"대소문자 무시 비교\");",
    "}",
    "```",
    "",
    "---",
    "",
    "## instanceof 연산자",
    "",
    "객체가 **특정 타입의 인스턴스인지** 확인합니다.",
    "",
    "```java",
    "Object obj = \"Hello\";",
    "",
    "if (obj instanceof String) {",
    "    String str = (String) obj;  // 형변환 후 사용",
    "    System.out.println(str.length());  // 5",
    "}",
    "",
    "if (obj instanceof Integer) {",
    "    System.out.println(\"정수\");  // 실행 안 됨",
    "}",
    "```",
    "",
    "---",
    "",
    "## 패턴 매칭 (Java 16+)",
    "",
    "instanceof와 형변환을 **한 번에** 처리할 수 있습니다.",
    "",
    "```java",
    "Object obj = \"Hello, Java!\";",
    "",
    "// Java 16 이전: instanceof + 캐스팅 분리",
    "if (obj instanceof String) {",
    "    String str = (String) obj;",
    "    System.out.println(str.toUpperCase());",
    "}",
    "",
    "// Java 16+: 패턴 매칭으로 간결하게",
    "if (obj instanceof String str) {",
    "    System.out.println(str.toUpperCase());  // 바로 사용 가능",
    "}",
    "",
    "// 조건 결합도 가능",
    "if (obj instanceof String str && str.length() > 5) {",
    "    System.out.println(\"긴 문자열: \" + str);",
    "}",
    "```",
    "",
    "---",
    "",
    "## 실전 예제: 성적 판별 프로그램",
    "",
    "```java",
    "import java.util.Scanner;",
    "",
    "public class GradeChecker {",
    "    public static void main(String[] args) {",
    "        Scanner sc = new Scanner(System.in);",
    "",
    "        System.out.print(\"점수 입력 (0~100): \");",
    "        int score = sc.nextInt();",
    "",
    "        if (score < 0 || score > 100) {",
    "            System.out.println(\"올바른 점수를 입력하세요!\");",
    "            return;",
    "        }",
    "",
    "        String grade = switch (score / 10) {",
    "            case 10, 9 -> \"A\";",
    "            case 8 -> \"B\";",
    "            case 7 -> \"C\";",
    "            case 6 -> \"D\";",
    "            default -> \"F\";",
    "        };",
    "",
    "        String passOrFail = (score >= 60) ? \"합격\" : \"불합격\";",
    "",
    "        System.out.printf(\"점수: %d → 등급: %s (%s)%n\",",
    "            score, grade, passOrFail);",
    "",
    "        sc.close();",
    "    }",
    "}",
    "```",
    "",
    "## 실전 예제: 간단한 계산기",
    "",
    "```java",
    "import java.util.Scanner;",
    "",
    "public class Calculator {",
    "    public static void main(String[] args) {",
    "        Scanner sc = new Scanner(System.in);",
    "",
    "        System.out.print(\"첫 번째 수: \");",
    "        double a = sc.nextDouble();",
    "",
    "        System.out.print(\"연산자 (+, -, *, /): \");",
    "        String op = sc.next();",
    "",
    "        System.out.print(\"두 번째 수: \");",
    "        double b = sc.nextDouble();",
    "",
    "        double result = switch (op) {",
    "            case \"+\" -> a + b;",
    "            case \"-\" -> a - b;",
    "            case \"*\" -> a * b;",
    "            case \"/\" -> {",
    "                if (b == 0) {",
    "                    System.out.println(\"0으로 나눌 수 없습니다!\");",
    "                    yield 0.0;",
    "                }",
    "                yield a / b;",
    "            }",
    "            default -> {",
    "                System.out.println(\"지원하지 않는 연산자입니다.\");",
    "                yield 0.0;",
    "            }",
    "        };",
    "",
    "        System.out.printf(\"%.2f %s %.2f = %.2f%n\", a, op, b, result);",
    "        sc.close();",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 요약",
    "",
    "| 항목 | 핵심 내용 |",
    "|------|----------|",
    "| if문 | 범위 조건, 복합 조건 등 유연한 분기에 적합 |",
    "| switch문 | 정확한 값 매칭, 여러 경우 분기 시 가독성 우수 |",
    "| 삼항 연산자 | 간단한 if-else를 한 줄로 → `조건 ? A : B` |",
    "| switch 표현식 (14+) | 화살표 `->`, break 불필요, `yield`로 값 반환 |",
    "| 문자열 비교 | 반드시 `equals()` 사용, `==` 사용 금지 |",
    "| instanceof | 타입 확인 연산자, Java 16+에서 패턴 매칭 지원 |",
    "| 비교·논리 연산자 | `==`, `!=`, `>`, `<`, `&&`, `\\|\\|`, `!` |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
