<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "js-array-methods",
  title: "배열의 내장 함수 (Array Methods)",
  date: "2026-02-25",
  summary: "자바스크립트/타입스크립트 배열의 핵심 내장 함수를 정리합니다. forEach, map, filter, reduce, find, some, every, sort, splice, slice, concat, flat, includes 등 실무에서 자주 쓰는 메서드를 JS/TS 예제와 함께 설명합니다.",
  category: "Coding/JavaScript",
  tags: ["javascript","typescript","array","map","filter","reduce","sort","method","basics"],
  content: [
    "## 한 줄 요약",
    "배열 내장 함수의 핵심은 **순회**(forEach), **변환**(map), **필터링**(filter), **축소**(reduce), **검색**(find/includes), **정렬**(sort)이며, 이 6가지만 익히면 대부분의 배열 작업을 처리할 수 있습니다.",
    "",
    "---",
    "",
    "## 분류 요약",
    "",
    "| 분류 | 메서드 | 원본 변경 |",
    "|------|--------|----------|",
    "| 순회 | `forEach` | ❌ |",
    "| 변환 | `map` | ❌ (새 배열 반환) |",
    "| 필터링 | `filter` | ❌ (새 배열 반환) |",
    "| 축소 | `reduce`, `reduceRight` | ❌ |",
    "| 검색 | `find`, `findIndex`, `indexOf`, `includes` | ❌ |",
    "| 판별 | `some`, `every` | ❌ |",
    "| 정렬 | `sort`, `reverse` | ✅ |",
    "| 추가/제거 | `push`, `pop`, `shift`, `unshift`, `splice` | ✅ |",
    "| 결합/분리 | `concat`, `slice`, `join`, `flat`, `flatMap` | ❌ (새 배열 반환) |",
    "| 채우기 | `fill`, `Array.from`, `Array.of` | - |",
    "",
    "---",
    "",
    "## 1. forEach - 순회",
    "",
    "배열의 각 요소에 대해 콜백 함수를 실행합니다. **반환값이 없습니다**(undefined).",
    "",
    "```javascript",
    "// JavaScript",
    "const fruits = ['apple', 'banana', 'cherry'];",
    "",
    "fruits.forEach((item, index) => {",
    "    console.log(`${index}: ${item}`);",
    "});",
    "// 0: apple",
    "// 1: banana",
    "// 2: cherry",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const fruits: string[] = ['apple', 'banana', 'cherry'];",
    "",
    "fruits.forEach((item: string, index: number) => {",
    "    console.log(`${index}: ${item}`);",
    "});",
    "```",
    "",
    "> `forEach`는 `break`를 사용할 수 없습니다. 중간에 멈춰야 하면 `for...of`나 `some`을 사용하세요.",
    "",
    "---",
    "",
    "## 2. map - 변환",
    "",
    "각 요소를 변환한 **새 배열**을 반환합니다. 원본은 변경되지 않습니다.",
    "",
    "```javascript",
    "// JavaScript",
    "const numbers = [1, 2, 3, 4, 5];",
    "",
    "const doubled = numbers.map(num => num * 2);",
    "console.log(doubled); // [2, 4, 6, 8, 10]",
    "",
    "const users = [",
    "    { name: 'haru', age: 25 },",
    "    { name: 'kim', age: 30 }",
    "];",
    "const names = users.map(user => user.name);",
    "console.log(names); // ['haru', 'kim']",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const numbers: number[] = [1, 2, 3, 4, 5];",
    "const doubled: number[] = numbers.map((num: number): number => num * 2);",
    "",
    "interface User {",
    "    name: string;",
    "    age: number;",
    "}",
    "",
    "const users: User[] = [",
    "    { name: 'haru', age: 25 },",
    "    { name: 'kim', age: 30 }",
    "];",
    "const names: string[] = users.map((user: User): string => user.name);",
    "```",
    "",
    "---",
    "",
    "## 3. filter - 필터링",
    "",
    "조건을 만족하는 요소만 모은 **새 배열**을 반환합니다.",
    "",
    "```javascript",
    "// JavaScript",
    "const numbers = [1, 2, 3, 4, 5, 6, 7, 8];",
    "",
    "const evens = numbers.filter(num => num % 2 === 0);",
    "console.log(evens); // [2, 4, 6, 8]",
    "",
    "const users = [",
    "    { name: 'haru', age: 25, active: true },",
    "    { name: 'kim', age: 17, active: false },",
    "    { name: 'lee', age: 30, active: true }",
    "];",
    "const activeAdults = users.filter(u => u.active && u.age >= 18);",
    "// [{ name: 'haru', ... }, { name: 'lee', ... }]",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const numbers: number[] = [1, 2, 3, 4, 5, 6, 7, 8];",
    "const evens: number[] = numbers.filter((num: number): boolean => num % 2 === 0);",
    "",
    "interface User {",
    "    name: string;",
    "    age: number;",
    "    active: boolean;",
    "}",
    "",
    "const users: User[] = [",
    "    { name: 'haru', age: 25, active: true },",
    "    { name: 'kim', age: 17, active: false },",
    "    { name: 'lee', age: 30, active: true }",
    "];",
    "const activeAdults: User[] = users.filter(",
    "    (u: User): boolean => u.active && u.age >= 18",
    ");",
    "```",
    "",
    "---",
    "",
    "## 4. reduce - 축소",
    "",
    "배열을 **하나의 값**으로 축소합니다. 가장 강력하고 범용적인 메서드입니다.",
    "",
    "```",
    "reduce((누적값, 현재값, 인덱스, 배열) => 다음 누적값, 초기값)",
    "```",
    "",
    "```javascript",
    "// JavaScript",
    "",
    "// 합계",
    "const sum = [1, 2, 3, 4, 5].reduce((acc, cur) => acc + cur, 0);",
    "console.log(sum); // 15",
    "",
    "// 최대값",
    "const max = [3, 1, 4, 1, 5, 9].reduce((a, b) => Math.max(a, b));",
    "console.log(max); // 9",
    "",
    "// 그룹화",
    "const items = ['apple', 'banana', 'apple', 'cherry', 'banana', 'apple'];",
    "const count = items.reduce((acc, item) => {",
    "    acc[item] = (acc[item] || 0) + 1;",
    "    return acc;",
    "}, {});",
    "console.log(count); // { apple: 3, banana: 2, cherry: 1 }",
    "",
    "// 배열 평탄화",
    "const nested = [[1, 2], [3, 4], [5, 6]];",
    "const flat = nested.reduce((acc, cur) => acc.concat(cur), []);",
    "console.log(flat); // [1, 2, 3, 4, 5, 6]",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const sum: number = [1, 2, 3, 4, 5].reduce(",
    "    (acc: number, cur: number): number => acc + cur, 0",
    ");",
    "",
    "// 그룹화",
    "const items: string[] = ['apple', 'banana', 'apple', 'cherry'];",
    "const count: Record<string, number> = items.reduce(",
    "    (acc: Record<string, number>, item: string) => {",
    "        acc[item] = (acc[item] || 0) + 1;",
    "        return acc;",
    "    }, {}",
    ");",
    "",
    "// 배열 평탄화",
    "const nested: number[][] = [[1, 2], [3, 4], [5, 6]];",
    "const flat: number[] = nested.reduce<number[]>(",
    "    (acc, cur) => acc.concat(cur), []",
    ");",
    "```",
    "",
    "---",
    "",
    "## 5. find / findIndex - 검색",
    "",
    "### find",
    "조건을 만족하는 **첫 번째 요소**를 반환합니다. 없으면 `undefined`.",
    "",
    "```javascript",
    "// JavaScript",
    "const users = [",
    "    { id: 1, name: 'haru' },",
    "    { id: 2, name: 'kim' },",
    "    { id: 3, name: 'lee' }",
    "];",
    "",
    "const found = users.find(u => u.id === 2);",
    "console.log(found); // { id: 2, name: 'kim' }",
    "",
    "const notFound = users.find(u => u.id === 99);",
    "console.log(notFound); // undefined",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "interface User { id: number; name: string; }",
    "",
    "const users: User[] = [",
    "    { id: 1, name: 'haru' },",
    "    { id: 2, name: 'kim' }",
    "];",
    "",
    "const found: User | undefined = users.find((u: User) => u.id === 2);",
    "",
    "// undefined 처리 필요",
    "if (found) {",
    "    console.log(found.name); // 'kim'",
    "}",
    "```",
    "",
    "### findIndex",
    "조건을 만족하는 **첫 번째 인덱스**를 반환합니다. 없으면 `-1`.",
    "",
    "```javascript",
    "// JavaScript",
    "const users = [",
    "    { id: 1, name: 'haru' },",
    "    { id: 2, name: 'kim' },",
    "    { id: 3, name: 'lee' }",
    "];",
    "",
    "const index = users.findIndex(u => u.name === 'kim');",
    "console.log(index); // 1",
    "",
    "const notFound = users.findIndex(u => u.name === 'park');",
    "console.log(notFound); // -1",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "interface User { id: number; name: string; }",
    "",
    "const users: User[] = [",
    "    { id: 1, name: 'haru' },",
    "    { id: 2, name: 'kim' },",
    "    { id: 3, name: 'lee' }",
    "];",
    "",
    "const index: number = users.findIndex((u: User): boolean => u.name === 'kim');",
    "console.log(index); // 1",
    "```",
    "",
    "---",
    "",
    "## 6. some / every - 판별",
    "",
    "### some",
    "**하나라도** 조건을 만족하면 `true`.",
    "",
    "```javascript",
    "// JavaScript",
    "const numbers = [1, 3, 5, 7, 8];",
    "const hasEven = numbers.some(n => n % 2 === 0);",
    "console.log(hasEven); // true (8이 짝수)",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const numbers: number[] = [1, 3, 5, 7, 8];",
    "const hasEven: boolean = numbers.some((n: number): boolean => n % 2 === 0);",
    "```",
    "",
    "### every",
    "**모든 요소**가 조건을 만족하면 `true`.",
    "",
    "```javascript",
    "// JavaScript",
    "const allPositive = [1, 2, 3].every(n => n > 0);",
    "console.log(allPositive); // true",
    "",
    "const allEven = [2, 4, 5].every(n => n % 2 === 0);",
    "console.log(allEven); // false",
    "",
    "// 실전: 폼 검증",
    "const fields = ['이름', '이메일', '비밀번호'];",
    "const allFilled = fields.every(f => f.length > 0);",
    "console.log(allFilled); // true",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const allPositive: boolean = [1, 2, 3].every((n: number): boolean => n > 0);",
    "",
    "interface FormField {",
    "    name: string;",
    "    value: string;",
    "    required: boolean;",
    "}",
    "",
    "const fields: FormField[] = [",
    "    { name: 'email', value: 'test@test.com', required: true },",
    "    { name: 'password', value: '1234', required: true },",
    "];",
    "",
    "const isValid: boolean = fields.every(",
    "    (f: FormField): boolean => !f.required || f.value.length > 0",
    ");",
    "```",
    "",
    "---",
    "",
    "## 7. sort - 정렬",
    "",
    "**원본 배열을 변경**합니다. 비교 함수 없이 호출하면 **문자열 유니코드 순**으로 정렬합니다.",
    "",
    "```javascript",
    "// JavaScript",
    "",
    "// ⚠️ 주의: 기본 정렬은 문자열 비교",
    "console.log([10, 9, 80, 1].sort()); // [1, 10, 80, 9] (문자열 비교!)",
    "",
    "// 숫자 오름차순",
    "const asc = [10, 9, 80, 1].sort((a, b) => a - b);",
    "console.log(asc); // [1, 9, 10, 80]",
    "",
    "// 숫자 내림차순",
    "const desc = [10, 9, 80, 1].sort((a, b) => b - a);",
    "console.log(desc); // [80, 10, 9, 1]",
    "",
    "// 문자열 정렬",
    "const words = ['banana', 'apple', 'cherry'];",
    "words.sort(); // ['apple', 'banana', 'cherry']",
    "",
    "// 객체 배열 정렬",
    "const users = [",
    "    { name: 'kim', age: 30 },",
    "    { name: 'haru', age: 25 },",
    "    { name: 'lee', age: 28 }",
    "];",
    "users.sort((a, b) => a.age - b.age);",
    "// age 오름차순: haru(25), lee(28), kim(30)",
    "",
    "// 문자열 프로퍼티 정렬",
    "users.sort((a, b) => a.name.localeCompare(b.name));",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "interface User { name: string; age: number; }",
    "",
    "const users: User[] = [",
    "    { name: 'kim', age: 30 },",
    "    { name: 'haru', age: 25 }",
    "];",
    "",
    "// 원본 변경 방지: 복사 후 정렬",
    "const sorted: User[] = [...users].sort(",
    "    (a: User, b: User): number => a.age - b.age",
    ");",
    "```",
    "",
    "| 비교 함수 반환값 | 정렬 순서 |",
    "|----------------|----------|",
    "| 음수 | a가 앞 |",
    "| 0 | 순서 유지 |",
    "| 양수 | b가 앞 |",
    "",
    "---",
    "",
    "## 8. splice - 추가/제거/교체",
    "",
    "**원본 배열을 변경**하며, 제거된 요소들을 반환합니다.",
    "",
    "```",
    "splice(시작인덱스, 제거개수, ...추가할요소)",
    "```",
    "",
    "```javascript",
    "// JavaScript",
    "const arr = ['a', 'b', 'c', 'd', 'e'];",
    "",
    "// 제거",
    "const removed = arr.splice(1, 2);",
    "console.log(arr);     // ['a', 'd', 'e']",
    "console.log(removed); // ['b', 'c']",
    "",
    "// 추가 (제거 0개)",
    "arr.splice(1, 0, 'x', 'y');",
    "console.log(arr); // ['a', 'x', 'y', 'd', 'e']",
    "",
    "// 교체",
    "arr.splice(0, 1, 'z');",
    "console.log(arr); // ['z', 'x', 'y', 'd', 'e']",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const arr: string[] = ['a', 'b', 'c', 'd', 'e'];",
    "const removed: string[] = arr.splice(1, 2);",
    "arr.splice(1, 0, 'x', 'y');",
    "```",
    "",
    "---",
    "",
    "## 9. slice - 부분 복사",
    "",
    "원본을 **변경하지 않고** 부분 배열을 반환합니다.",
    "",
    "```javascript",
    "// JavaScript",
    "const arr = [0, 1, 2, 3, 4, 5];",
    "",
    "console.log(arr.slice(1, 4));  // [1, 2, 3]  (시작 포함, 끝 미포함)",
    "console.log(arr.slice(2));     // [2, 3, 4, 5] (끝까지)",
    "console.log(arr.slice(-2));    // [4, 5] (뒤에서 2개)",
    "console.log(arr.slice());      // [0, 1, 2, 3, 4, 5] (얕은 복사)",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const arr: number[] = [0, 1, 2, 3, 4, 5];",
    "const partial: number[] = arr.slice(1, 4); // [1, 2, 3]",
    "const copy: number[] = arr.slice();        // 얕은 복사",
    "```",
    "",
    "| 비교 | splice | slice |",
    "|------|--------|-------|",
    "| 원본 변경 | ✅ | ❌ |",
    "| 반환값 | 제거된 요소 | 부분 복사 배열 |",
    "| 추가/삭제 | 가능 | 불가 (읽기만) |",
    "",
    "---",
    "",
    "## 10. concat / spread - 배열 합치기",
    "",
    "```javascript",
    "// JavaScript",
    "const a = [1, 2];",
    "const b = [3, 4];",
    "const c = [5, 6];",
    "",
    "// concat",
    "const merged1 = a.concat(b, c);",
    "console.log(merged1); // [1, 2, 3, 4, 5, 6]",
    "",
    "// spread 연산자 (더 많이 사용)",
    "const merged2 = [...a, ...b, ...c];",
    "console.log(merged2); // [1, 2, 3, 4, 5, 6]",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const a: number[] = [1, 2];",
    "const b: number[] = [3, 4];",
    "const merged: number[] = [...a, ...b]; // [1, 2, 3, 4]",
    "```",
    "",
    "---",
    "",
    "## 11. flat / flatMap - 평탄화",
    "",
    "```javascript",
    "// JavaScript",
    "const nested = [1, [2, 3], [4, [5, 6]]];",
    "",
    "console.log(nested.flat());    // [1, 2, 3, 4, [5, 6]] (1단계)",
    "console.log(nested.flat(2));   // [1, 2, 3, 4, 5, 6]   (2단계)",
    "console.log(nested.flat(Infinity)); // 모든 중첩 제거",
    "",
    "// flatMap = map + flat(1단계)",
    "const sentences = ['hello world', 'foo bar'];",
    "const words = sentences.flatMap(s => s.split(' '));",
    "console.log(words); // ['hello', 'world', 'foo', 'bar']",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const nested: (number | number[])[] = [1, [2, 3], [4, 5]];",
    "const flat: number[] = nested.flat() as number[];",
    "",
    "const sentences: string[] = ['hello world', 'foo bar'];",
    "const words: string[] = sentences.flatMap((s: string): string[] => s.split(' '));",
    "```",
    "",
    "---",
    "",
    "## 12. includes / indexOf - 존재 확인",
    "",
    "```javascript",
    "// JavaScript",
    "const fruits = ['apple', 'banana', 'cherry'];",
    "",
    "// includes: boolean 반환",
    "console.log(fruits.includes('banana'));  // true",
    "console.log(fruits.includes('grape'));   // false",
    "",
    "// indexOf: 인덱스 반환 (없으면 -1)",
    "console.log(fruits.indexOf('cherry'));   // 2",
    "console.log(fruits.indexOf('grape'));    // -1",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const fruits: string[] = ['apple', 'banana', 'cherry'];",
    "const hasBanana: boolean = fruits.includes('banana');",
    "const cherryIdx: number = fruits.indexOf('cherry');",
    "```",
    "",
    "---",
    "",
    "## 13. push / pop / shift / unshift",
    "",
    "**원본 배열을 변경**합니다.",
    "",
    "```javascript",
    "// JavaScript",
    "const arr = [1, 2, 3];",
    "",
    "arr.push(4);        // 끝에 추가 → [1, 2, 3, 4]",
    "arr.pop();          // 끝에서 제거 → [1, 2, 3]  반환값: 4",
    "arr.unshift(0);     // 앞에 추가 → [0, 1, 2, 3]",
    "arr.shift();        // 앞에서 제거 → [1, 2, 3]  반환값: 0",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const arr: number[] = [1, 2, 3];",
    "arr.push(4);               // number 반환 (새 길이)",
    "const last: number | undefined = arr.pop();  // number | undefined",
    "```",
    "",
    "| 메서드 | 위치 | 동작 | 반환값 |",
    "|--------|------|------|--------|",
    "| push | 끝 | 추가 | 새 길이 |",
    "| pop | 끝 | 제거 | 제거된 요소 |",
    "| unshift | 앞 | 추가 | 새 길이 |",
    "| shift | 앞 | 제거 | 제거된 요소 |",
    "",
    "---",
    "",
    "## 14. join - 문자열 변환",
    "",
    "```javascript",
    "// JavaScript",
    "const arr = ['Hello', 'World', '!'];",
    "console.log(arr.join(' '));   // 'Hello World !'",
    "console.log(arr.join('-'));   // 'Hello-World-!'",
    "console.log(arr.join(''));    // 'HelloWorld!'",
    "console.log(arr.join());     // 'Hello,World,!'  (기본: 쉼표)",
    "",
    "// 실전: 경로 생성",
    "const pathParts = ['users', 'haru', 'profile'];",
    "console.log(pathParts.join('/')); // 'users/haru/profile'",
    "",
    "// 실전: CSV 행 생성",
    "const row = ['haru', 25, 'admin'];",
    "console.log(row.join(',')); // 'haru,25,admin'",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const arr: string[] = ['Hello', 'World', '!'];",
    "const sentence: string = arr.join(' '); // 'Hello World !'",
    "",
    "const pathParts: string[] = ['users', 'haru', 'profile'];",
    "const path: string = pathParts.join('/'); // 'users/haru/profile'",
    "",
    "// 숫자 배열도 문자열로 결합",
    "const nums: number[] = [1, 2, 3];",
    "const result: string = nums.join(' + '); // '1 + 2 + 3'",
    "```",
    "",
    "---",
    "",
    "## 15. fill - 채우기",
    "",
    "```javascript",
    "// JavaScript",
    "const arr = [1, 2, 3, 4, 5];",
    "arr.fill(0);           // [0, 0, 0, 0, 0]",
    "arr.fill(9, 1, 3);     // [0, 9, 9, 0, 0]  (인덱스 1~2)",
    "",
    "// 초기화에 유용",
    "const zeros = new Array(5).fill(0); // [0, 0, 0, 0, 0]",
    "const trues = new Array(3).fill(true); // [true, true, true]",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const arr: number[] = [1, 2, 3, 4, 5];",
    "arr.fill(0);                // [0, 0, 0, 0, 0]",
    "arr.fill(9, 1, 3);          // [0, 9, 9, 0, 0]",
    "",
    "const zeros: number[] = new Array<number>(5).fill(0);",
    "const flags: boolean[] = new Array<boolean>(3).fill(false);",
    "```",
    "",
    "---",
    "",
    "## 16. Array.from / Array.of - 생성",
    "",
    "```javascript",
    "// Array.from: 유사 배열/이터러블 → 배열",
    "Array.from('hello');           // ['h', 'e', 'l', 'l', 'o']",
    "Array.from({ length: 5 }, (_, i) => i);  // [0, 1, 2, 3, 4]",
    "Array.from({ length: 5 }, (_, i) => i * 2); // [0, 2, 4, 6, 8]",
    "",
    "// Array.of: 인자들로 배열 생성",
    "Array.of(1, 2, 3);    // [1, 2, 3]",
    "Array.of(5);           // [5]  (new Array(5)와 다름!)",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const nums: number[] = Array.from({ length: 5 }, (_, i: number): number => i);",
    "const items: number[] = Array.of(1, 2, 3);",
    "```",
    "",
    "---",
    "",
    "## 17. reverse - 뒤집기",
    "",
    "**원본 배열을 변경**합니다.",
    "",
    "```javascript",
    "// JavaScript",
    "const arr = [1, 2, 3, 4, 5];",
    "arr.reverse();",
    "console.log(arr); // [5, 4, 3, 2, 1] (원본 변경!)",
    "",
    "// 원본 유지하며 뒤집기",
    "const reversed = [...arr].reverse();",
    "",
    "// 문자열 뒤집기 활용",
    "const str = 'hello';",
    "const reversedStr = str.split('').reverse().join('');",
    "console.log(reversedStr); // 'olleh'",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const arr: number[] = [1, 2, 3, 4, 5];",
    "arr.reverse(); // [5, 4, 3, 2, 1] (원본 변경!)",
    "",
    "// 원본 유지하며 뒤집기",
    "const reversed: number[] = [...arr].reverse();",
    "",
    "// 문자열 뒤집기",
    "const str: string = 'hello';",
    "const reversedStr: string = str.split('').reverse().join('');",
    "console.log(reversedStr); // 'olleh'",
    "```",
    "",
    "---",
    "",
    "## 18. 구조 분해 할당과 배열",
    "",
    "```javascript",
    "// JavaScript",
    "const [first, second, ...rest] = [1, 2, 3, 4, 5];",
    "console.log(first);  // 1",
    "console.log(second); // 2",
    "console.log(rest);   // [3, 4, 5]",
    "",
    "// 값 교환",
    "let a = 1, b = 2;",
    "[a, b] = [b, a];",
    "console.log(a, b); // 2, 1",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "const [first, second, ...rest]: number[] = [1, 2, 3, 4, 5];",
    "// first: number, second: number, rest: number[]",
    "",
    "const [name, age]: [string, number] = ['haru', 25]; // 튜플",
    "```",
    "",
    "---",
    "",
    "## 메서드 체이닝 (실전 활용)",
    "",
    "여러 메서드를 연결하여 한 번에 처리합니다.",
    "",
    "```javascript",
    "// JavaScript",
    "const products = [",
    "    { name: 'Phone', price: 800, inStock: true },",
    "    { name: 'Laptop', price: 1200, inStock: false },",
    "    { name: 'Tablet', price: 500, inStock: true },",
    "    { name: 'Watch', price: 300, inStock: true },",
    "    { name: 'Earbuds', price: 150, inStock: true }",
    "];",
    "",
    "// 재고 있는 상품 중 500원 이하 → 가격순 정렬 → 이름만 추출",
    "const result = products",
    "    .filter(p => p.inStock)",
    "    .filter(p => p.price <= 500)",
    "    .sort((a, b) => a.price - b.price)",
    "    .map(p => p.name);",
    "",
    "console.log(result); // ['Earbuds', 'Watch', 'Tablet']",
    "```",
    "",
    "```typescript",
    "// TypeScript",
    "interface Product {",
    "    name: string;",
    "    price: number;",
    "    inStock: boolean;",
    "}",
    "",
    "const products: Product[] = [",
    "    { name: 'Phone', price: 800, inStock: true },",
    "    { name: 'Laptop', price: 1200, inStock: false },",
    "    { name: 'Tablet', price: 500, inStock: true },",
    "    { name: 'Watch', price: 300, inStock: true },",
    "    { name: 'Earbuds', price: 150, inStock: true }",
    "];",
    "",
    "const result: string[] = products",
    "    .filter((p: Product): boolean => p.inStock && p.price <= 500)",
    "    .sort((a: Product, b: Product): number => a.price - b.price)",
    "    .map((p: Product): string => p.name);",
    "```",
    "",
    "---",
    "",
    "## 자주 쓰는 패턴 정리",
    "",
    "| 목적 | 코드 |",
    "|------|------|",
    "| 배열 합계 | `arr.reduce((a, b) => a + b, 0)` |",
    "| 배열 최대값 | `Math.max(...arr)` |",
    "| 배열 최소값 | `Math.min(...arr)` |",
    "| 중복 제거 | `[...new Set(arr)]` |",
    "| 배열 얕은 복사 | `[...arr]` 또는 `arr.slice()` |",
    "| 배열 뒤집기 (원본 유지) | `[...arr].reverse()` |",
    "| 빈 요소 제거 | `arr.filter(Boolean)` |",
    "| 객체 배열에서 특정 값 추출 | `arr.map(item => item.key)` |",
    "| 조건에 맞는 첫 요소 | `arr.find(item => 조건)` |",
    "| 특정 길이 배열 생성 | `Array.from({ length: n }, (_, i) => i)` |",
    "",
    "---",
    "### 요약",
    "배열 내장 함수의 핵심은 **변환(`map`)**, **필터링(`filter`)**, **축소(`reduce`)**이며, 이 세 가지로 대부분의 데이터 가공이 가능합니다. `sort`는 원본을 변경하므로 `[...arr].sort()`로 복사 후 사용하고, `splice`(원본 변경) vs `slice`(복사)의 차이를 기억하세요. TypeScript에서는 배열 타입(`number[]`), 반환 타입, 콜백 타입을 명시하면 더 안전한 코드를 작성할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
