<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "js-data-types-operators",
  title: "자바스크립트 데이터 타입과 연산자",
  date: "2026-02-24",
  summary: "자바스크립트의 기본 타입(숫자, 문자열, 불린, null, undefined)과 참조 타입(객체, 배열)의 차이, 프로토타입 개념, 그리고 연산자(+, ==, ===, !!)를 소스 코드 예제와 함께 정리합니다.",
  category: "Coding/JavaScript",
  tags: ["javascript","data-type","object","array","operator","prototype","basics"],
  content: [
    "## 한 줄 요약",
    "자바스크립트의 데이터 타입은 **기본 타입**(숫자·문자열·불린·null·undefined)과 **참조 타입**(객체·배열)으로 나뉘며, 기본 타입은 값이 복사되고 참조 타입은 참조(주소)가 복사됩니다.",
    "",
    "---",
    "",
    "## 설치 및 실행 환경",
    "",
    "자바스크립트는 **브라우저**와 **Node.js** 두 가지 환경에서 실행할 수 있습니다.",
    "",
    "### 브라우저에서 실행",
    "HTML 파일에 `<script>` 태그로 포함하거나, 크롬 개발자 도구(F12) → Console 탭에서 바로 실행할 수 있습니다.",
    "",
    "```html",
    "<!DOCTYPE html>",
    "<html>",
    "<body>",
    "  <script src=\"app.js\"></" + "script>",
    "</body>",
    "</html>",
    "```",
    "",
    "### Node.js 설치 및 실행",
    "```bash",
    "# Node.js 설치 확인",
    "node --version",
    "npm --version",
    "```",
    "",
    "Node.js가 없다면 [https://nodejs.org](https://nodejs.org)에서 LTS 버전을 설치합니다.",
    "",
    "```bash",
    "# JS 파일 실행",
    "node app.js",
    "",
    "# REPL 모드 (대화형 실행)",
    "node",
    "> console.log('Hello')",
    "Hello",
    "> 1 + 2",
    "3",
    "> .exit",
    "```",
    "",
    "### 프로젝트 초기화",
    "```bash",
    "# 프로젝트 폴더 생성",
    "mkdir my-project && cd my-project",
    "",
    "# package.json 생성",
    "npm init -y",
    "",
    "# 패키지 설치 예시",
    "npm install lodash           # 의존성 설치",
    "npm install --save-dev jest   # 개발 의존성 설치",
    "```",
    "",
    "### 주요 개발 도구",
    "",
    "| 도구 | 설명 |",
    "|------|------|",
    "| VS Code | 가장 많이 사용하는 코드 에디터 |",
    "| Node.js | 브라우저 밖에서 JS 실행 |",
    "| npm / yarn | 패키지 매니저 |",
    "| Chrome DevTools | 브라우저 내 디버깅 도구 (F12) |",
    "| ESLint | 코드 스타일·오류 검사 도구 |",
    "| Prettier | 코드 자동 포맷팅 |",
    "",
    "---",
    "",
    "## 1. 기본 타입 (Primitive Type)",
    "",
    "### typeof로 타입 확인",
    "```javascript",
    "var intNum = 10;",
    "var floatNum = 0.1;",
    "var singleQuoteStr = 'single quote string';",
    "var dobuleQuoteStr = \"double quote string\";",
    "var bool = true;",
    "var emptyVar;        // undefined",
    "var nullVar = null;",
    "",
    "console.log(",
    "    typeof intNum,       // number",
    "    typeof floatNum,     // number",
    "    typeof singleQuoteStr, // string",
    "    typeof dobuleQuoteStr, // string",
    "    typeof bool,         // boolean",
    "    typeof nullVar,      // object (주의!)",
    "    typeof emptyVar      // undefined",
    ");",
    "```",
    "",
    "자바스크립트는 **정수와 실수 구분 없이** 모두 `number` 타입입니다.",
    "",
    "```javascript",
    "var num = 5 / 2;",
    "console.log(num);            // 2.5 (정수 나눗셈이 아님)",
    "console.log(Math.floor(num)); // 2",
    "```",
    "",
    "### 문자열의 불변성",
    "문자열은 한 번 생성되면 개별 문자를 변경할 수 없습니다.",
    "",
    "```javascript",
    "var str = 'test';",
    "console.log(str[0], str[1], str[2], str[3]); // t e s t",
    "",
    "str[0] = 'T';",
    "console.log(str); // test (변경되지 않음)",
    "```",
    "",
    "### null 타입 주의",
    "`typeof null`은 `object`를 반환합니다. null 체크 시 `===`를 사용해야 합니다.",
    "",
    "```javascript",
    "var nullVar = null;",
    "console.log(typeof nullVar === null); // false (typeof는 'object' 반환)",
    "console.log(nullVar === null);        // true",
    "```",
    "",
    "---",
    "",
    "## 2. 객체 (Object)",
    "",
    "### 객체 생성 방법",
    "",
    "```javascript",
    "// 1) Object() 생성자",
    "var foo = new Object();",
    "foo.name = 'foo';",
    "foo.age = 30;",
    "",
    "// 2) 객체 리터럴 (권장)",
    "var foo = {",
    "    name: 'foo',",
    "    age: 30,",
    "    gender: 'male'",
    "};",
    "```",
    "",
    "### 프로퍼티 접근: 점(.) vs 대괄호([])",
    "```javascript",
    "var foo = { name: 'foo', major: 'computer science' };",
    "",
    "// 읽기",
    "console.log(foo.name);       // foo",
    "console.log(foo['name']);     // foo",
    "console.log(foo.nickname);   // undefined",
    "",
    "// 갱신",
    "foo.major = 'electronics engineering';",
    "",
    "// 동적 생성",
    "foo.age = 30;",
    "",
    "// 대괄호 표기법이 필수인 경우 (특수문자 포함 키)",
    "foo['full-name'] = 'foo bar';",
    "console.log(foo['full-name']); // foo bar",
    "console.log(foo.full-name);    // NaN (foo.full - name으로 해석됨)",
    "```",
    "",
    "### for...in으로 프로퍼티 순회",
    "```javascript",
    "var foo = { name: 'foo', age: 30, major: 'computer science' };",
    "",
    "for (var prop in foo) {",
    "    console.log(prop, foo[prop]);",
    "}",
    "// name foo",
    "// age 30",
    "// major computer science",
    "```",
    "",
    "### 객체의 참조",
    "객체를 변수에 할당하면 **값이 아니라 참조(주소)가 복사**됩니다.",
    "",
    "```javascript",
    "var objA = { val: 40 };",
    "var objB = objA;      // 같은 객체를 가리킴",
    "",
    "objB.val = 50;",
    "console.log(objA.val); // 50 (objA도 변경됨)",
    "```",
    "",
    "### 동등(==) 비교와 참조",
    "```javascript",
    "var a = 100;",
    "var b = 100;",
    "var objA = { value: 100 };",
    "var objB = { value: 100 };",
    "var objC = objB;",
    "",
    "console.log(a == b);       // true (값 비교)",
    "console.log(objA == objB); // false (다른 참조)",
    "console.log(objB == objC); // true (같은 참조)",
    "```",
    "",
    "### 함수 호출 시 전달 방식",
    "기본 타입은 **값 복사(call by value)**, 참조 타입은 **참조 전달(call by reference)**입니다.",
    "",
    "```javascript",
    "var a = 100;",
    "var objA = { value: 100 };",
    "",
    "function changeArg(num, obj) {",
    "    num = 200;       // 원본에 영향 없음",
    "    obj.value = 200; // 원본이 변경됨",
    "}",
    "",
    "changeArg(a, objA);",
    "console.log(a);          // 100 (변경 안 됨)",
    "console.log(objA.value); // 200 (변경됨)",
    "```",
    "",
    "---",
    "",
    "## 3. 배열 (Array)",
    "",
    "### 배열 생성과 동적 추가",
    "```javascript",
    "var colorArr = ['orange', 'yellow', 'blue', 'green', 'red'];",
    "console.log(colorArr[0]); // orange",
    "",
    "// 빈 배열에 동적 추가",
    "var emptyArr = [];",
    "emptyArr[0] = 100;",
    "emptyArr[3] = 'eight';",
    "emptyArr[7] = true;",
    "console.log(emptyArr);        // [100, undefined × 2, 'eight', undefined × 3, true]",
    "console.log(emptyArr.length); // 8",
    "```",
    "",
    "### length 프로퍼티",
    "`length`는 배열의 가장 큰 인덱스 + 1입니다. 직접 변경하면 배열이 잘리거나 확장됩니다.",
    "",
    "```javascript",
    "var arr = [0, 1, 2];",
    "arr.length = 5;       // 확장 (빈 슬롯 추가)",
    "arr.length = 2;       // 잘림",
    "console.log(arr);     // [0, 1]",
    "console.log(arr[2]);  // undefined",
    "```",
    "",
    "### 배열 vs 객체",
    "```javascript",
    "var colorsArray = ['orange', 'yellow', 'green'];",
    "var colorsObj = { '0': 'orange', '1': 'yellow', '2': 'green' };",
    "",
    "console.log(typeof colorsArray); // object",
    "console.log(typeof colorsObj);   // object",
    "",
    "console.log(colorsArray.length); // 3",
    "console.log(colorsObj.length);   // undefined",
    "",
    "colorsArray.push('red'); // OK",
    "// colorsObj.push('red'); // TypeError! (push 메서드 없음)",
    "```",
    "",
    "배열과 객체는 `typeof`가 모두 `object`이지만, 배열은 `Array.prototype`을 상속받아 `push`, `splice` 등의 메서드를 사용할 수 있습니다.",
    "",
    "### delete vs splice",
    "```javascript",
    "var arr = ['zero', 'one', 'two', 'three'];",
    "",
    "// delete: 빈 자리가 남음",
    "delete arr[2];",
    "console.log(arr);        // ['zero', 'one', undefined, 'three']",
    "console.log(arr.length); // 4",
    "",
    "// splice: 완전히 제거",
    "var arr2 = ['zero', 'one', 'two', 'three'];",
    "arr2.splice(2, 1);",
    "console.log(arr2);        // ['zero', 'one', 'three']",
    "console.log(arr2.length); // 3",
    "```",
    "",
    "### 유사 배열 객체에서 배열 메서드 빌려쓰기",
    "```javascript",
    "var obj = { name: 'foo', length: 1 };",
    "",
    "// obj.push('baz'); // TypeError!",
    "Array.prototype.push.apply(obj, ['baz']);",
    "console.log(obj); // { '1': 'baz', name: 'foo', length: 2 }",
    "```",
    "",
    "---",
    "",
    "## 4. 기본 타입의 래퍼 객체",
    "기본 타입도 메서드를 호출할 수 있습니다. 임시로 래퍼 객체가 생성됩니다.",
    "",
    "```javascript",
    "var num = 0.5;",
    "console.log(num.toExponential(1)); // '5.0e-1'",
    "",
    "console.log('test'.charAt(2));     // 's'",
    "```",
    "",
    "---",
    "",
    "## 5. 연산자",
    "",
    "### + 연산자 (덧셈 vs 문자열 연결)",
    "```javascript",
    "console.log(1 + 2);          // 3",
    "console.log('my ' + 'str');  // 'my str'",
    "console.log(1 + 'string');   // '1string' (숫자 → 문자열)",
    "console.log('string' + 2);   // 'string2'",
    "```",
    "",
    "### == vs === (동등 vs 일치)",
    "```javascript",
    "console.log(1 == '1');  // true (타입 변환 후 비교)",
    "console.log(1 === '1'); // false (타입까지 비교)",
    "```",
    "",
    "**`===`(일치 연산자)를 사용하는 것이 권장됩니다.**",
    "",
    "### !! 연산자 (불린 변환)",
    "```javascript",
    "console.log(!!0);          // false",
    "console.log(!!1);          // true",
    "console.log(!!'string');   // true",
    "console.log(!!'');         // false",
    "console.log(!!null);       // false",
    "console.log(!!undefined);  // false",
    "console.log(!!{});         // true",
    "console.log(!![1,2,3]);    // true",
    "```",
    "",
    "| Falsy 값 | Truthy 값 |",
    "|----------|-----------|",
    "| `0`, `-0` | 0이 아닌 모든 숫자 |",
    "| `''` (빈 문자열) | 비어있지 않은 문자열 |",
    "| `null` | 모든 객체 `{}` |",
    "| `undefined` | 모든 배열 `[]` |",
    "| `NaN` | 함수 |",
    "",
    "---",
    "### 요약",
    "자바스크립트 데이터 타입의 핵심은 **기본 타입은 값이 복사**되고 **참조 타입은 참조가 복사**된다는 것입니다. 배열은 `typeof`가 `object`이지만 `Array.prototype`을 상속받아 `push`, `splice` 등의 메서드를 사용할 수 있으며, `===`(일치 연산자)와 `!!`(불린 변환)를 적극 활용하는 것이 좋습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
