<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "js-execution-context-closure",
  title: "실행 컨텍스트, 스코프, 클로저",
  date: "2026-02-24",
  summary: "자바스크립트의 실행 컨텍스트(Execution Context), 스코프 체인, 렉시컬 스코프, 그리고 클로저(Closure)의 원리와 다양한 활용 패턴(캡슐화, 비동기, 루프 문제 해결)을 소스 코드와 함께 정리합니다.",
  category: "Coding/JavaScript",
  tags: ["javascript","execution-context","scope","closure","lexical-scope","iife","basics"],
  content: [
    "## 한 줄 요약",
    "**실행 컨텍스트**는 코드가 실행되는 환경이고, **스코프 체인**은 변수를 찾는 경로이며, **클로저**는 외부 함수가 종료된 뒤에도 내부 함수가 외부 변수에 접근할 수 있는 메커니즘입니다.",
    "",
    "---",
    "",
    "## 1. 실행 컨텍스트 (Execution Context)",
    "",
    "자바스크립트 코드가 실행될 때, 엔진은 **실행 컨텍스트**를 생성하고 스택에 쌓습니다.",
    "",
    "```javascript",
    "console.log('This is global context');",
    "",
    "function ExContext1() {",
    "    console.log('This is ExContext1');",
    "}",
    "",
    "function ExContext2() {",
    "    ExContext1();",
    "    console.log('This is ExContext2');",
    "}",
    "",
    "ExContext2();",
    "```",
    "",
    "```",
    "실행 컨텍스트 스택 변화:",
    "",
    "1. [전역 컨텍스트]             → 'This is global context'",
    "2. [전역] → [ExContext2]       → ExContext2 진입",
    "3. [전역] → [ExContext2] → [ExContext1] → 'This is ExContext1'",
    "4. [전역] → [ExContext2]       → ExContext1 종료, 'This is ExContext2'",
    "5. [전역]                      → ExContext2 종료",
    "```",
    "",
    "### 실행 컨텍스트의 구성",
    "```javascript",
    "function execute(param1, param2) {",
    "    var a = 1, b = 2;",
    "    function func() {",
    "        return a + b;",
    "    }",
    "    return param1 + param2 + func();",
    "}",
    "execute(3, 4); // 10",
    "```",
    "",
    "| 구성 요소 | 내용 |",
    "|-----------|------|",
    "| 변수 객체 (Variable Object) | `param1`, `param2`, `a`, `b`, `func` |",
    "| 스코프 체인 | 현재 컨텍스트의 변수 객체 → 상위 컨텍스트 → ... → 전역 |",
    "| this | 호출 방식에 따라 결정 |",
    "",
    "---",
    "",
    "## 2. 스코프 체인 (Scope Chain)",
    "",
    "변수를 참조할 때, 현재 스코프에서 찾고 없으면 **상위 스코프로 올라가며 검색**합니다.",
    "",
    "```javascript",
    "var var1 = 1;",
    "var var2 = 2;",
    "",
    "function func() {",
    "    var var1 = 10;",
    "    var var2 = 20;",
    "    console.log(var1); // 10 (지역 변수 우선)",
    "    console.log(var2); // 20",
    "}",
    "",
    "func();",
    "console.log(var1); // 1 (전역 변수)",
    "console.log(var2); // 2",
    "```",
    "",
    "---",
    "",
    "## 3. 렉시컬 스코프 (Lexical Scope)",
    "",
    "자바스크립트는 함수가 **선언된 위치**에서 스코프가 결정됩니다 (동적 스코프가 아닙니다).",
    "",
    "```javascript",
    "var value = 'value1';",
    "",
    "function printValue() {",
    "    return value;",
    "}",
    "",
    "function printFunc(func) {",
    "    var value = 'value2';",
    "    console.log(func()); // 'value1' (선언 위치의 value)",
    "}",
    "",
    "printFunc(printValue);",
    "```",
    "",
    "`printValue`는 전역에서 선언되었으므로, `printFunc` 내부의 `value`가 아니라 **전역의 `value`**를 참조합니다.",
    "",
    "---",
    "",
    "## 4. 클로저 (Closure)",
    "",
    "클로저란, 함수가 자신이 **선언된 환경의 변수**에 접근할 수 있는 것을 말합니다. 외부 함수가 종료되어도 유지됩니다.",
    "",
    "### 기본 클로저",
    "```javascript",
    "function outerFunc() {",
    "    var x = 10;",
    "    var innerFunc = function () { console.log(x); };",
    "    return innerFunc;",
    "}",
    "",
    "var inner = outerFunc();",
    "inner(); // 10 (outerFunc가 종료되었지만 x에 접근 가능)",
    "```",
    "",
    "### 인자와 지역 변수 캡처",
    "```javascript",
    "function outerFunc(arg1, arg2) {",
    "    var local = 8;",
    "    function innerFunc(innerArg) {",
    "        console.log((arg1 + arg2) / (innerArg + local));",
    "    }",
    "    return innerFunc;",
    "}",
    "",
    "var exam1 = outerFunc(2, 4);",
    "exam1(2); // (2 + 4) / (2 + 8) = 0.6",
    "```",
    "",
    "---",
    "",
    "## 5. 클로저 활용 패턴",
    "",
    "### 패턴 1: 캡슐화 (IIFE + 클로저)",
    "",
    "전역 변수 오염을 방지하며 내부 데이터를 숨깁니다.",
    "",
    "```javascript",
    "// Before: 전역에 노출된 배열",
    "var buffAr = ['I am ', '', '. I live in ', '', \". I'm \", '', ' years old.'];",
    "",
    "function getCompletedStr(name, city, age) {",
    "    buffAr[1] = name;",
    "    buffAr[3] = city;",
    "    buffAr[5] = age;",
    "    return buffAr.join('');",
    "}",
    "```",
    "",
    "```javascript",
    "// After: IIFE + 클로저로 캡슐화",
    "var getCompletedStr = (function () {",
    "    var buffAr = ['I am ', '', '. I live in ', '', \". I'm \", '', ' years old.'];",
    "",
    "    return function (name, city, age) {",
    "        buffAr[1] = name;",
    "        buffAr[3] = city;",
    "        buffAr[5] = age;",
    "        return buffAr.join('');",
    "    };",
    "})();",
    "",
    "console.log(getCompletedStr('zzoon', 'seoul', 16));",
    "// 'I am zzoon. I live in seoul. I'm 16 years old.'",
    "```",
    "",
    "### 패턴 2: 상태 유지",
    "",
    "클로저는 호출할 때마다 상태를 기억합니다.",
    "",
    "```javascript",
    "function outerFunc(argNum) {",
    "    var num = argNum;",
    "    return function (x) {",
    "        num += x;",
    "        console.log('num: ' + num);",
    "    };",
    "}",
    "",
    "var exam = outerFunc(40);",
    "exam(5);   // num: 45",
    "exam(-10); // num: 35 (이전 상태 유지)",
    "```",
    "",
    "### 패턴 3: 여러 메서드가 같은 변수 공유",
    "```javascript",
    "function func() {",
    "    var x = 1;",
    "    return {",
    "        func1: function () { console.log(++x); },",
    "        func2: function () { console.log(-x); }",
    "    };",
    "}",
    "",
    "var exam = func();",
    "exam.func1(); // 2",
    "exam.func2(); // -2",
    "```",
    "",
    "### 패턴 4: 비동기와 클로저 (setTimeout)",
    "```javascript",
    "function callLater(obj, a, b) {",
    "    return function () {",
    "        obj['sum'] = a + b;",
    "        console.log(obj['sum']);",
    "    };",
    "}",
    "",
    "var sumObj = { sum: 0 };",
    "var func = callLater(sumObj, 1, 2);",
    "setTimeout(func, 500); // 0.5초 후 3 출력",
    "```",
    "",
    "---",
    "",
    "## 6. 클로저와 루프 문제",
    "",
    "가장 흔한 클로저 실수입니다.",
    "",
    "### 문제: 모두 같은 값 출력",
    "```javascript",
    "function countSeconds(howMany) {",
    "    for (var i = 1; i <= howMany; i++) {",
    "        setTimeout(function () {",
    "            console.log(i); // 모두 4 출력!",
    "        }, i * 1000);",
    "    }",
    "}",
    "countSeconds(3); // 4, 4, 4",
    "```",
    "",
    "루프가 끝난 후 `setTimeout`의 콜백이 실행될 때 `i`는 이미 4가 되어 있습니다.",
    "",
    "### 해결: IIFE로 현재 값 캡처",
    "```javascript",
    "function countSeconds(howMany) {",
    "    for (var i = 1; i <= howMany; i++) {",
    "        (function (currentI) {",
    "            setTimeout(function () {",
    "                console.log(currentI);",
    "            }, currentI * 1000);",
    "        })(i); // 현재 i를 즉시 전달",
    "    }",
    "}",
    "countSeconds(3); // 1, 2, 3",
    "```",
    "",
    "---",
    "### 요약",
    "**실행 컨텍스트**는 코드 실행 시 생성되어 스택에 쌓이고, **스코프 체인**을 따라 변수를 검색합니다. **렉시컬 스코프** 덕분에 함수는 선언 위치의 변수를 기억하며, 이것이 **클로저**의 핵심입니다. 클로저는 캡슐화, 상태 유지, 비동기 처리에 널리 활용되지만, 루프 내 클로저 사용 시 IIFE로 값을 캡처해야 하는 점에 주의해야 합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
