<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "js-execution-context-closure",
  title: "실행 컨텍스트, 스코프, 클로저",
  date: "2026-03-08",
  summary: "자바스크립트의 실행 컨텍스트(Execution Context), 스코프 체인, 렉시컬 스코프, 그리고 클로저(Closure)의 원리와 다양한 활용 패턴(캡슐화, 비동기, 루프 문제 해결)을 소스 코드와 함께 정리합니다.",
  category: "Coding/JavaScript",
  tags: ["javascript","execution-context","scope","closure","lexical-scope","iife","basics"],
  content: [
    "## 한 줄 요약",
    "**실행 컨텍스트**는 코드가 실행되는 환경이고, **스코프 체인**은 변수를 찾는 경로이며, **클로저**는 외부 함수가 종료된 뒤에도 내부 함수가 외부 변수에 접근할 수 있는 메커니즘입니다.",
    "",
    "---",
    "",
    "## 1. 실행 컨텍스트 (Execution Context)",
    "",
    "### 실행 컨텍스트란?",
    "자바스크립트 엔진이 코드를 실행할 때, **\"이 코드가 어떤 환경에서 실행되는가\"**에 대한 정보를 담는 객체입니다. 쉽게 말해 **코드가 실행되기 위해 필요한 모든 정보(변수, 함수, this, 상위 스코프 등)를 모아놓은 환경**입니다.",
    "",
    "코드를 실행하려면 다음과 같은 정보가 필요합니다:",
    "- 여기서 쓸 수 있는 변수/함수는 무엇인가?",
    "- `this`는 무엇을 가리키는가?",
    "- 상위 스코프는 어디인가?",
    "",
    "이 정보들을 하나로 묶은 것이 실행 컨텍스트입니다.",
    "",
    "### 실행 컨텍스트의 3가지 종류",
    "| 종류 | 생성 시점 | 설명 |",
    "|------|----------|------|",
    "| **전역 실행 컨텍스트** | 스크립트가 처음 로드될 때 | 전역 코드를 위한 컨텍스트. 프로그램당 1개만 존재 |",
    "| **함수 실행 컨텍스트** | 함수가 **호출**될 때마다 | 각 함수 호출마다 새로 생성 |",
    "| **eval 실행 컨텍스트** | eval() 호출 시 | 거의 사용하지 않음 (보안 문제) |",
    "",
    "> **핵심**: 함수를 \"선언\"할 때가 아니라 **\"호출\"할 때** 실행 컨텍스트가 만들어집니다.",
    "",
    "### 실행 컨텍스트 스택 (Call Stack)",
    "실행 컨텍스트는 **스택(Stack)** 구조로 관리됩니다. 스택은 \"마지막에 들어온 것이 먼저 나가는\" 구조(LIFO)입니다.",
    "",
    "```javascript",
    "console.log('전역 코드 실행');",
    "",
    "function first() {",
    "    console.log('first 함수 실행');",
    "    second();",
    "    console.log('first 함수 끝');",
    "}",
    "",
    "function second() {",
    "    console.log('second 함수 실행');",
    "}",
    "",
    "first();",
    "console.log('전역 코드 끝');",
    "```",
    "",
    "```",
    "스택 변화 과정:",
    "",
    "① [전역]                         → '전역 코드 실행'",
    "② [전역] → [first]               → 'first 함수 실행'",
    "③ [전역] → [first] → [second]    → 'second 함수 실행'",
    "④ [전역] → [first]               → second 종료, 스택에서 제거",
    "                                   'first 함수 끝'",
    "⑤ [전역]                         → first 종료, 스택에서 제거",
    "                                   '전역 코드 끝'",
    "⑥ (비어있음)                      → 프로그램 종료",
    "```",
    "",
    "스택의 **맨 위에 있는 컨텍스트가 현재 실행 중인 코드**입니다. 함수가 끝나면 해당 컨텍스트가 스택에서 빠지고(pop), 아래에 있던 컨텍스트가 다시 실행을 이어갑니다.",
    "",
    "### 실행 컨텍스트의 구성 요소",
    "",
    "실행 컨텍스트가 생성되면 내부에 3가지가 만들어집니다:",
    "",
    "```",
    "실행 컨텍스트 = {",
    "    1. 변수 환경 (Variable Environment)",
    "       → var 변수, 함수 선언을 저장",
    "",
    "    2. 렉시컬 환경 (Lexical Environment)",
    "       → let, const 변수, 블록 스코프 관리",
    "       → 스코프 체인(외부 환경 참조)도 여기에 포함",
    "",
    "    3. this 바인딩",
    "       → 이 코드에서 this가 가리키는 대상",
    "}",
    "```",
    "",
    "```javascript",
    "function execute(param1, param2) {",
    "    var a = 1, b = 2;",
    "    function inner() {",
    "        return a + b;",
    "    }",
    "    return param1 + param2 + inner();",
    "}",
    "execute(3, 4); // 10",
    "```",
    "",
    "| 구성 요소 | 내용 |",
    "|-----------|------|",
    "| **변수 환경** | `param1: 3`, `param2: 4`, `a: 1`, `b: 2`, `inner: function` |",
    "| **스코프 체인** | 현재 컨텍스트의 변수 → 전역 컨텍스트의 변수 |",
    "| **this** | 일반 함수 호출이므로 `window` (strict 모드에서는 `undefined`) |",
    "",
    "### 생성 단계 vs 실행 단계",
    "",
    "실행 컨텍스트는 **2단계**로 처리됩니다:",
    "",
    "**1단계: 생성(Creation Phase)** — 코드를 실행하기 전에 환경을 세팅",
    "- `var` 변수 선언을 먼저 등록하고 `undefined`로 초기화 (**호이스팅**)",
    "- 함수 선언문을 통째로 등록 (함수 호이스팅)",
    "- `let`/`const`는 등록만 하고 초기화하지 않음 (TDZ)",
    "- 스코프 체인 설정",
    "- `this` 결정",
    "",
    "**2단계: 실행(Execution Phase)** — 코드를 한 줄씩 실행",
    "- 변수에 실제 값을 할당",
    "- 함수를 호출",
    "- 표현식을 평가",
    "",
    "```javascript",
    "console.log(x);    // undefined (var는 호이스팅되어 undefined로 초기화)",
    "console.log(y);    // ReferenceError! (let은 TDZ에 걸림)",
    "console.log(greet); // function greet() {...} (함수 선언문은 통째로 호이스팅)",
    "",
    "var x = 10;",
    "let y = 20;",
    "function greet() { return 'hello'; }",
    "```",
    "",
    "```",
    "생성 단계에서 메모리 상태:",
    "┌──────────────────────────┐",
    "│ x     → undefined       │  var: 선언 + undefined 초기화",
    "│ y     → 초기화 안 됨(TDZ) │  let: 선언만, 접근 시 에러",
    "│ greet → function {...}  │  함수 선언문: 통째로 등록",
    "└──────────────────────────┘",
    "",
    "실행 단계에서:",
    "│ x     → 10              │  값 할당",
    "│ y     → 20              │  값 할당 (TDZ 해제)",
    "```",
    "",
    "> **TDZ(Temporal Dead Zone)**: `let`/`const`로 선언한 변수가 선언문에 도달하기 전까지 접근할 수 없는 구간입니다. 호이스팅은 되지만, 초기화 전에 접근하면 `ReferenceError`가 발생합니다.",
    "",
    "---",
    "",
    "## 2. 스코프 (Scope)",
    "",
    "### 스코프란?",
    "스코프는 **변수에 접근할 수 있는 범위**입니다. \"이 변수를 여기서 쓸 수 있는가?\"를 결정합니다.",
    "",
    "### 스코프의 종류",
    "",
    "| 스코프 | 설명 | 예시 |",
    "|--------|------|------|",
    "| **전역 스코프** | 어디서든 접근 가능 | 함수 밖에서 선언한 변수 |",
    "| **함수 스코프** | 함수 내부에서만 접근 가능 | `var`로 선언한 변수 |",
    "| **블록 스코프** | `{}` 블록 내부에서만 접근 가능 | `let`/`const`로 선언한 변수 |",
    "",
    "```javascript",
    "var globalVar = '전역';        // 전역 스코프",
    "",
    "function myFunc() {",
    "    var funcVar = '함수';      // 함수 스코프 (myFunc 안에서만)",
    "",
    "    if (true) {",
    "        var varInBlock = 'var'; // var는 함수 스코프 → if 밖에서도 접근 가능!",
    "        let letInBlock = 'let'; // let은 블록 스코프 → if 안에서만",
    "        const constInBlock = 'const'; // const도 블록 스코프",
    "    }",
    "",
    "    console.log(varInBlock);   // 'var' (접근 가능!)",
    "    // console.log(letInBlock);  // ReferenceError (블록 밖)",
    "    // console.log(constInBlock); // ReferenceError (블록 밖)",
    "}",
    "",
    "myFunc();",
    "// console.log(funcVar); // ReferenceError (함수 밖)",
    "```",
    "",
    "> **`var`의 함정**: `var`는 블록(`if`, `for`)을 무시하고 함수 스코프를 따릅니다. 이것이 `var` 대신 `let`/`const`를 쓰는 핵심 이유입니다.",
    "",
    "### 스코프 체인 (Scope Chain)",
    "",
    "변수를 참조할 때, 자바스크립트 엔진은 **현재 스코프에서 먼저 찾고, 없으면 상위 스코프로 올라가며 검색**합니다. 이 검색 경로를 **스코프 체인**이라고 합니다.",
    "",
    "```javascript",
    "var x = '전역 x';",
    "",
    "function outer() {",
    "    var y = 'outer의 y';",
    "",
    "    function inner() {",
    "        var z = 'inner의 z';",
    "        console.log(z); // 'inner의 z' → inner에서 찾음",
    "        console.log(y); // 'outer의 y' → inner에 없어서 outer에서 찾음",
    "        console.log(x); // '전역 x'   → inner, outer에 없어서 전역에서 찾음",
    "    }",
    "",
    "    inner();",
    "}",
    "",
    "outer();",
    "```",
    "",
    "```",
    "스코프 체인 (inner 기준):",
    "",
    "inner 스코프  →  outer 스코프  →  전역 스코프",
    "  { z }            { y }           { x }",
    "",
    "변수 z → inner에서 찾음 ✓",
    "변수 y → inner에 없음 → outer에서 찾음 ✓",
    "변수 x → inner에 없음 → outer에 없음 → 전역에서 찾음 ✓",
    "```",
    "",
    "**중요한 점**: 스코프 체인은 **안에서 밖으로만** 검색합니다. 밖에서 안으로는 불가능합니다.",
    "",
    "```javascript",
    "function outer() {",
    "    function inner() {",
    "        var secret = '비밀';",
    "    }",
    "    // console.log(secret); // ReferenceError! 바깥에서 안쪽 변수 접근 불가",
    "}",
    "```",
    "",
    "### 같은 이름의 변수가 여러 스코프에 있으면? (변수 섀도잉)",
    "",
    "```javascript",
    "var value = 1;",
    "",
    "function func() {",
    "    var value = 10;          // 전역 value를 '가림(shadow)'",
    "    console.log(value);      // 10 (가장 가까운 스코프의 변수 우선)",
    "}",
    "",
    "func();",
    "console.log(value);          // 1 (전역 변수는 그대로)",
    "```",
    "",
    "스코프 체인에서 **가장 가까운 스코프의 변수가 우선**합니다. 안쪽 스코프의 `value`가 바깥쪽의 `value`를 가리는 것을 **변수 섀도잉(Variable Shadowing)**이라고 합니다.",
    "",
    "---",
    "",
    "## 3. 렉시컬 스코프 (Lexical Scope / 정적 스코프)",
    "",
    "### 렉시컬 스코프란?",
    "함수의 스코프가 **어디서 호출했느냐**가 아니라 **어디서 선언(작성)했느냐**에 따라 결정되는 방식입니다.",
    "",
    "자바스크립트는 **렉시컬 스코프(정적 스코프)**를 사용합니다. 이는 코드를 작성하는 시점에 스코프가 이미 확정된다는 의미입니다.",
    "",
    "### 왜 중요한가?",
    "```javascript",
    "var value = '전역';",
    "",
    "function printValue() {",
    "    console.log(value);",
    "}",
    "",
    "function wrapper() {",
    "    var value = 'wrapper 내부';",
    "    printValue();              // 무엇이 출력될까?",
    "}",
    "",
    "wrapper(); // '전역'",
    "```",
    "",
    "- **동적 스코프**였다면: `printValue`가 `wrapper` 안에서 **호출**되었으므로 `'wrapper 내부'` 출력",
    "- **렉시컬 스코프**이므로: `printValue`가 **전역에서 선언**되었으므로 `'전역'` 출력",
    "",
    "```",
    "printValue는 전역에서 '선언'됨:",
    "",
    "전역 스코프 ← printValue의 상위 스코프는 '선언 위치'인 전역",
    "  { value: '전역', printValue, wrapper }",
    "",
    "wrapper 스코프",
    "  { value: 'wrapper 내부' }",
    "  → printValue()를 호출하지만,",
    "    printValue의 스코프 체인에 wrapper는 포함되지 않음",
    "```",
    "",
    "### 렉시컬 스코프와 클로저의 관계",
    "렉시컬 스코프 덕분에 함수는 **자신이 선언된 환경을 기억**합니다. 이것이 바로 클로저의 기반입니다.",
    "",
    "```javascript",
    "function makeGreeter(greeting) {",
    "    // greeting은 makeGreeter의 스코프에 존재",
    "    return function (name) {",
    "        // 이 함수는 makeGreeter 안에서 '선언'됨",
    "        // → 렉시컬 스코프에 의해 greeting에 접근 가능",
    "        console.log(greeting + ', ' + name + '!');",
    "    };",
    "}",
    "",
    "var helloGreeter = makeGreeter('Hello');",
    "var hiGreeter = makeGreeter('Hi');",
    "",
    "helloGreeter('Kim'); // 'Hello, Kim!'",
    "hiGreeter('Lee');    // 'Hi, Lee!'",
    "```",
    "",
    "---",
    "",
    "## 4. 클로저 (Closure)",
    "",
    "### 클로저란?",
    "클로저는 **함수와 그 함수가 선언된 렉시컬 환경의 조합**입니다.",
    "",
    "쉽게 말하면: **외부 함수가 종료된 후에도, 내부 함수가 외부 함수의 변수에 접근할 수 있는 현상**입니다.",
    "",
    "### 왜 가능한가?",
    "일반적으로 함수가 끝나면 그 안의 지역 변수는 메모리에서 사라집니다. 하지만 **내부 함수가 외부 함수의 변수를 참조하고 있으면**, 자바스크립트 엔진은 그 변수를 메모리에서 제거하지 않습니다 (가비지 컬렉터가 수거하지 않음).",
    "",
    "```javascript",
    "function outerFunc() {",
    "    var x = 10;                          // outerFunc의 지역 변수",
    "    var innerFunc = function () {",
    "        console.log(x);                  // 외부 변수 x를 참조",
    "    };",
    "    return innerFunc;                    // 내부 함수를 반환",
    "}",
    "",
    "var inner = outerFunc();",
    "// outerFunc()는 이미 실행이 끝남",
    "// 보통이라면 x는 사라져야 하지만...",
    "",
    "inner(); // 10 → x가 아직 살아있다!",
    "```",
    "",
    "```",
    "메모리에서 일어나는 일:",
    "",
    "1. outerFunc() 호출",
    "   → 실행 컨텍스트 생성, x = 10, innerFunc 생성",
    "   → innerFunc는 자신의 렉시컬 환경(x가 있는 환경)을 기억",
    "",
    "2. outerFunc() 종료",
    "   → 실행 컨텍스트는 스택에서 제거",
    "   → 하지만 innerFunc가 x를 참조하고 있으므로 x는 메모리에 유지",
    "",
    "3. inner() 호출",
    "   → innerFunc 실행, 스코프 체인을 통해 x를 찾음 → 10",
    "```",
    "",
    "### 클로저가 아닌 경우",
    "```javascript",
    "function notClosure() {",
    "    var x = 10;",
    "    console.log(x);  // 10",
    "}",
    "notClosure();",
    "// x는 함수 종료 후 사라짐 → 클로저 아님 (내부 함수가 없음)",
    "```",
    "",
    "```javascript",
    "function outerFunc() {",
    "    var x = 10;",
    "    function innerFunc() {",
    "        console.log(x);",
    "    }",
    "    innerFunc(); // 여기서 바로 호출하고 끝남",
    "}",
    "outerFunc();",
    "// innerFunc가 외부로 나가지 않음 → 일반적인 스코프 체인 참조일 뿐",
    "// (엄밀히는 클로저이지만, 실무에서 '클로저'라고 부르는 건 주로 외부로 반환되는 경우)",
    "```",
    "",
    "### 인자와 지역 변수 캡처",
    "클로저는 외부 함수의 **매개변수와 지역 변수 모두**를 기억합니다.",
    "```javascript",
    "function outerFunc(arg1, arg2) {",
    "    var local = 8;",
    "    function innerFunc(innerArg) {",
    "        console.log((arg1 + arg2) / (innerArg + local));",
    "    }",
    "    return innerFunc;",
    "}",
    "",
    "var exam1 = outerFunc(2, 4);",
    "exam1(2); // (2 + 4) / (2 + 8) = 0.6",
    "```",
    "",
    "`innerFunc`가 기억하는 것: `arg1 = 2`, `arg2 = 4`, `local = 8` 모두.",
    "",
    "### 클로저는 \"값\"이 아니라 \"변수 자체\"를 기억한다",
    "이 점이 매우 중요합니다.",
    "```javascript",
    "function counter() {",
    "    var count = 0;",
    "    return function () {",
    "        count++;            // count의 '현재 값'이 아니라 count '변수'를 참조",
    "        console.log(count);",
    "    };",
    "}",
    "",
    "var increment = counter();",
    "increment(); // 1",
    "increment(); // 2",
    "increment(); // 3",
    "// count = 0의 '값'을 복사한 게 아니라,",
    "// count '변수'를 참조하므로 매번 바뀐 값이 반영됨",
    "```",
    "",
    "---",
    "",
    "## 5. 클로저 활용 패턴",
    "",
    "### 패턴 1: 캡슐화 (정보 은닉)",
    "",
    "외부에서 직접 접근할 수 없는 **private 변수**를 만듭니다. 자바스크립트에는 `private` 키워드가 없었기 때문에 클로저로 구현했습니다.",
    "",
    "```javascript",
    "// 문제: 전역에 노출되어 누구든 변경 가능",
    "var count = 0;",
    "function increment() { count++; }",
    "function getCount() { return count; }",
    "count = -100; // 외부에서 직접 변경 가능!",
    "```",
    "",
    "```javascript",
    "// 해결: 클로저로 캡슐화",
    "function createCounter() {",
    "    var count = 0; // 외부에서 접근 불가능한 private 변수",
    "",
    "    return {",
    "        increment: function () { count++; },",
    "        decrement: function () { count--; },",
    "        getCount: function () { return count; }",
    "    };",
    "}",
    "",
    "var counter = createCounter();",
    "counter.increment();",
    "counter.increment();",
    "counter.increment();",
    "console.log(counter.getCount()); // 3",
    "// counter.count → undefined (직접 접근 불가!)",
    "```",
    "",
    "### 패턴 2: IIFE + 클로저",
    "",
    "**IIFE(Immediately Invoked Function Expression)**는 선언과 동시에 실행되는 함수입니다. 클로저와 함께 사용하면 전역 오염 없이 모듈을 만들 수 있습니다.",
    "",
    "```javascript",
    "var getCompletedStr = (function () {",
    "    // 이 변수는 IIFE 안에 갇혀 외부에서 접근 불가",
    "    var buffAr = ['I am ', '', '. I live in ', '', \". I'm \", '', ' years old.'];",
    "",
    "    return function (name, city, age) {",
    "        buffAr[1] = name;",
    "        buffAr[3] = city;",
    "        buffAr[5] = age;",
    "        return buffAr.join('');",
    "    };",
    "})(); // ← 즉시 실행!",
    "",
    "console.log(getCompletedStr('Kim', 'Seoul', 25));",
    "// 'I am Kim. I live in Seoul. I'm 25 years old.'",
    "// buffAr에 직접 접근 불가능",
    "```",
    "",
    "### 패턴 3: 상태 유지",
    "",
    "클로저는 호출할 때마다 이전 상태를 기억합니다.",
    "",
    "```javascript",
    "function accumulator(initial) {",
    "    var total = initial;",
    "    return function (amount) {",
    "        total += amount;",
    "        console.log('총합: ' + total);",
    "        return total;",
    "    };",
    "}",
    "",
    "var account = accumulator(1000);",
    "account(500);   // 총합: 1500",
    "account(-200);  // 총합: 1300",
    "account(100);   // 총합: 1400",
    "",
    "// 새로 만들면 독립적인 상태",
    "var account2 = accumulator(0);",
    "account2(50);   // 총합: 50 (account와 별개)",
    "```",
    "",
    "### 패턴 4: 여러 메서드가 같은 변수 공유",
    "```javascript",
    "function createPlayer(name) {",
    "    var hp = 100;",
    "",
    "    return {",
    "        attack: function () { console.log(name + ' 공격! (HP: ' + hp + ')'); },",
    "        damage: function (amount) {",
    "            hp -= amount;",
    "            console.log(name + '이(가) ' + amount + ' 피해! (HP: ' + hp + ')');",
    "        },",
    "        heal: function (amount) {",
    "            hp += amount;",
    "            console.log(name + '이(가) ' + amount + ' 회복! (HP: ' + hp + ')');",
    "        },",
    "        getHP: function () { return hp; }",
    "    };",
    "}",
    "",
    "var player = createPlayer('전사');",
    "player.attack();    // '전사 공격! (HP: 100)'",
    "player.damage(30);  // '전사이(가) 30 피해! (HP: 70)'",
    "player.heal(10);    // '전사이(가) 10 회복! (HP: 80)'",
    "// player.hp → undefined (직접 접근 불가)",
    "```",
    "",
    "`attack`, `damage`, `heal` 세 함수가 **같은 `hp` 변수를 공유**하면서도, 외부에서는 `hp`에 직접 접근할 수 없습니다.",
    "",
    "### 패턴 5: 비동기와 클로저 (setTimeout)",
    "```javascript",
    "function callLater(obj, a, b) {",
    "    return function () {",
    "        obj['sum'] = a + b;",
    "        console.log(obj['sum']);",
    "    };",
    "}",
    "",
    "var sumObj = { sum: 0 };",
    "var func = callLater(sumObj, 1, 2);",
    "setTimeout(func, 500); // 0.5초 후 3 출력",
    "// 0.5초가 지난 후에도 a=1, b=2를 기억하고 있음",
    "```",
    "",
    "---",
    "",
    "## 6. 클로저와 루프 문제",
    "",
    "클로저에서 **가장 흔하고 중요한 실수**입니다.",
    "",
    "### 문제: 모두 같은 값 출력",
    "```javascript",
    "function countSeconds(howMany) {",
    "    for (var i = 1; i <= howMany; i++) {",
    "        setTimeout(function () {",
    "            console.log(i);",
    "        }, i * 1000);",
    "    }",
    "}",
    "countSeconds(3);",
    "// 기대: 1초 후 1, 2초 후 2, 3초 후 3",
    "// 실제: 1초 후 4, 2초 후 4, 3초 후 4",
    "```",
    "",
    "**왜 이런 일이 생기나?**",
    "",
    "1. `var i`는 **함수 스코프**이므로, `countSeconds` 함수 전체에서 하나의 `i`를 공유",
    "2. `setTimeout`의 콜백 함수 3개가 모두 **같은 `i` 변수를 참조** (값을 복사하는 게 아님!)",
    "3. `for` 루프는 금방 끝남 (setTimeout보다 훨씬 빠름)",
    "4. 루프가 끝난 시점에 `i`는 이미 `4` (i=4일 때 조건 `i <= 3`이 false라서 종료)",
    "5. 1~3초 후 콜백이 실행될 때 `i`를 보면 → 전부 `4`",
    "",
    "```",
    "시간순서:",
    "0ms   → for 루프 시작: i=1, setTimeout 등록 (1초 후)",
    "0ms   → i=2, setTimeout 등록 (2초 후)",
    "0ms   → i=3, setTimeout 등록 (3초 후)",
    "0ms   → i=4, 조건 false → 루프 종료",
    "1000ms → 콜백 실행, i 확인 → 4",
    "2000ms → 콜백 실행, i 확인 → 4",
    "3000ms → 콜백 실행, i 확인 → 4",
    "```",
    "",
    "### 해결 1: IIFE로 현재 값 캡처",
    "```javascript",
    "function countSeconds(howMany) {",
    "    for (var i = 1; i <= howMany; i++) {",
    "        (function (currentI) {",
    "            // currentI는 IIFE의 매개변수 → 각 반복마다 새로운 스코프 생성",
    "            setTimeout(function () {",
    "                console.log(currentI);",
    "            }, currentI * 1000);",
    "        })(i); // 현재 i 값을 인자로 전달",
    "    }",
    "}",
    "countSeconds(3); // 1, 2, 3 ✓",
    "```",
    "",
    "IIFE가 호출될 때마다 **새로운 스코프가 만들어지고**, `currentI`에 그 시점의 `i` 값이 복사됩니다. 각 콜백은 서로 다른 `currentI`를 참조합니다.",
    "",
    "### 해결 2: let 사용 (ES6, 가장 간단)",
    "```javascript",
    "function countSeconds(howMany) {",
    "    for (let i = 1; i <= howMany; i++) {",
    "        setTimeout(function () {",
    "            console.log(i);",
    "        }, i * 1000);",
    "    }",
    "}",
    "countSeconds(3); // 1, 2, 3 ✓",
    "```",
    "",
    "`let`은 **블록 스코프**이므로 `for` 루프의 **각 반복마다 새로운 `i`가 생성**됩니다. 결과적으로 각 콜백이 서로 다른 `i`를 참조하게 됩니다.",
    "",
    "```",
    "var i의 경우:                    let i의 경우:",
    "┌─────────────────┐            반복 1: ┌─── let i = 1 ───┐ ← 콜백1이 참조",
    "│ var i            │            반복 2: ┌─── let i = 2 ───┐ ← 콜백2가 참조",
    "│ 모든 콜백이 참조  │            반복 3: ┌─── let i = 3 ───┐ ← 콜백3이 참조",
    "└─────────────────┘",
    "```",
    "",
    "> 실무에서는 `var` 대신 `let`을 쓰면 이 문제가 자연스럽게 해결됩니다.",
    "",
    "---",
    "",
    "## 7. 클로저 사용 시 주의사항",
    "",
    "### 메모리 누수",
    "클로저가 참조하는 변수는 가비지 컬렉터가 수거하지 못합니다. 불필요한 클로저를 계속 유지하면 **메모리 누수**가 발생할 수 있습니다.",
    "",
    "```javascript",
    "function heavyProcess() {",
    "    var bigData = new Array(1000000).fill('data'); // 큰 데이터",
    "    return function () {",
    "        console.log(bigData.length); // bigData를 참조 → 메모리에 유지",
    "    };",
    "}",
    "",
    "var process = heavyProcess();",
    "// process가 존재하는 한 bigData는 메모리에서 해제되지 않음",
    "// 더 이상 필요 없으면:",
    "process = null; // 참조 제거 → 가비지 컬렉터가 수거 가능",
    "```",
    "",
    "### 성능",
    "클로저를 남용하면 불필요한 스코프 체인 탐색이 발생합니다. 단순한 작업에는 클로저 없이 일반 함수를 사용하는 것이 좋습니다.",
    "",
    "---",
    "",
    "## 8. 전체 흐름 정리",
    "",
    "```",
    "1. 코드 실행 → 실행 컨텍스트 생성 → 콜 스택에 push",
    "",
    "2. 실행 컨텍스트 안에는:",
    "   - 변수 환경 (var 변수, 함수 선언)",
    "   - 렉시컬 환경 (let/const, 스코프 체인)",
    "   - this 바인딩",
    "",
    "3. 변수를 찾을 때 → 스코프 체인을 따라 현재 → 상위 → 전역 순서로 검색",
    "",
    "4. 스코프는 '선언 위치'로 결정 (렉시컬 스코프)",
    "   → 호출 위치는 상관없음",
    "",
    "5. 내부 함수가 외부 변수를 참조 + 외부로 반환 = 클로저",
    "   → 외부 함수가 종료되어도 변수 유지",
    "",
    "6. 클로저 활용: 캡슐화, 상태 유지, 비동기 처리",
    "   → 주의: 메모리 관리, 루프 문제",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "| 개념 | 핵심 |",
    "|------|------|",
    "| **실행 컨텍스트** | 코드 실행에 필요한 환경 정보. 함수 호출 시 생성되어 콜 스택에 쌓임 |",
    "| **호이스팅** | 생성 단계에서 var/함수 선언이 먼저 등록됨. let/const는 TDZ |",
    "| **스코프** | 변수에 접근 가능한 범위. var=함수 스코프, let/const=블록 스코프 |",
    "| **스코프 체인** | 변수를 현재 → 상위 → 전역 순서로 검색하는 경로 |",
    "| **렉시컬 스코프** | 스코프는 함수가 \"선언된 위치\"에서 결정 (호출 위치 X) |",
    "| **클로저** | 내부 함수가 외부 함수의 변수를 기억하는 현상. 값이 아니라 변수 자체를 참조 |",
    "| **루프 문제** | var + 클로저는 같은 변수를 공유 → let 또는 IIFE로 해결 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
