<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "js-functions",
  title: "자바스크립트 함수",
  date: "2026-02-24",
  summary: "자바스크립트 함수의 정의 방식(선언문, 표현식, Function 생성자), 일급 객체 특성, 호이스팅, this 바인딩(메서드/함수/생성자/apply·call), 클로저, arguments 객체, 프로토타입 체이닝까지 소스 코드와 함께 정리합니다.",
  category: "Coding/JavaScript",
  tags: ["javascript","function","this","closure","prototype","hoisting","apply","call","basics"],
  content: [
    "## 한 줄 요약",
    "자바스크립트 함수는 **일급 객체**로서 변수에 할당·인자로 전달·리턴값으로 사용할 수 있으며, 호출 방식에 따라 `this`가 다르게 바인딩됩니다.",
    "",
    "---",
    "",
    "## 1. 함수 정의 방식",
    "",
    "### 함수 선언문 (Function Declaration)",
    "```javascript",
    "function add(x, y) {",
    "    return x + y;",
    "}",
    "console.log(add(3, 4)); // 7",
    "```",
    "",
    "### 함수 표현식 (Function Expression)",
    "```javascript",
    "var add = function (x, y) {",
    "    return x + y;",
    "};",
    "",
    "var plus = add;",
    "console.log(add(3, 4));  // 7",
    "console.log(plus(5, 6)); // 11",
    "```",
    "",
    "### 기명 함수 표현식",
    "함수 이름은 **함수 내부에서만** 유효합니다. 재귀 호출에 활용됩니다.",
    "",
    "```javascript",
    "var factorialVar = function factorial(n) {",
    "    if (n <= 1) return 1;",
    "    return n * factorial(n - 1); // 내부에서 이름 사용 가능",
    "};",
    "",
    "console.log(factorialVar(3)); // 6",
    "// console.log(factorial(3)); // ReferenceError!",
    "```",
    "",
    "### 화살표 함수 (Arrow Function) - ES6+",
    "",
    "화살표 함수(`=>`)는 ES6에서 도입된 **간결한 함수 표현식**입니다.",
    "",
    "```javascript",
    "// 기본 형태",
    "const add = (x, y) => {",
    "    return x + y;",
    "};",
    "",
    "// 본문이 한 줄이면 중괄호와 return 생략",
    "const add2 = (x, y) => x + y;",
    "",
    "// 매개변수가 1개면 괄호 생략 가능",
    "const double = x => x * 2;",
    "",
    "// 매개변수가 없으면 빈 괄호 필수",
    "const greet = () => 'Hello!';",
    "",
    "console.log(add(3, 4));    // 7",
    "console.log(double(5));    // 10",
    "console.log(greet());      // 'Hello!'",
    "```",
    "",
    "#### 객체 리터럴 반환",
    "객체를 바로 반환할 때는 **소괄호로 감싸야** 합니다.",
    "",
    "```javascript",
    "// ❌ 중괄호를 함수 본문으로 해석",
    "const getUser1 = () => { name: 'haru', age: 25 }; // undefined 반환",
    "",
    "// ✅ 소괄호로 감싸서 객체 반환",
    "const getUser2 = () => ({ name: 'haru', age: 25 });",
    "console.log(getUser2()); // { name: 'haru', age: 25 }",
    "```",
    "",
    "#### 화살표 함수의 this",
    "",
    "화살표 함수는 **자체 `this`를 갖지 않습니다**. 선언 시점의 상위 스코프 `this`를 그대로 사용합니다 (렉시컬 this).",
    "",
    "```javascript",
    "// 일반 함수: this가 호출 시점에 결정",
    "var obj1 = {",
    "    value: 100,",
    "    getValue: function () {",
    "        // 내부 함수에서 this가 전역을 가리킴",
    "        setTimeout(function () {",
    "            console.log(this.value); // undefined (this = 전역)",
    "        }, 100);",
    "    }",
    "};",
    "",
    "// 화살표 함수: this가 선언 시점의 상위 스코프 (obj2)",
    "var obj2 = {",
    "    value: 100,",
    "    getValue: function () {",
    "        // 화살표 함수는 상위 스코프의 this를 사용",
    "        setTimeout(() => {",
    "            console.log(this.value); // 100 (this = obj2)",
    "        }, 100);",
    "    }",
    "};",
    "",
    "obj1.getValue(); // undefined",
    "obj2.getValue(); // 100",
    "```",
    "",
    "**that 패턴 vs 화살표 함수 비교:**",
    "",
    "```javascript",
    "var myObject = {",
    "    value: 1,",
    "    // ES5: that 패턴으로 this 보존",
    "    incES5: function () {",
    "        var that = this;",
    "        var inner = function () {",
    "            that.value += 1;",
    "            console.log('ES5:', that.value);",
    "        };",
    "        inner();",
    "    },",
    "    // ES6: 화살표 함수로 자연스럽게 this 보존",
    "    incES6: function () {",
    "        var inner = () => {",
    "            this.value += 1;",
    "            console.log('ES6:', this.value);",
    "        };",
    "        inner();",
    "    }",
    "};",
    "",
    "myObject.incES5(); // ES5: 2",
    "myObject.incES6(); // ES6: 3",
    "```",
    "",
    "#### 화살표 함수를 쓰면 안 되는 경우",
    "",
    "| 상황 | 이유 |",
    "|------|------|",
    "| 객체의 메서드 | `this`가 객체를 가리키지 않음 |",
    "| `prototype` 메서드 | `this`가 인스턴스를 가리키지 않음 |",
    "| 생성자 함수 | `new`로 호출 불가 (TypeError) |",
    "| `arguments` 사용 | 자체 `arguments` 객체가 없음 |",
    "",
    "```javascript",
    "// ❌ 객체 메서드에 화살표 함수 사용",
    "const person = {",
    "    name: 'haru',",
    "    sayName: () => {",
    "        console.log(this.name); // undefined (this = 전역)",
    "    }",
    "};",
    "person.sayName(); // undefined",
    "",
    "// ✅ 일반 함수 사용",
    "const person2 = {",
    "    name: 'haru',",
    "    sayName: function () {",
    "        console.log(this.name); // 'haru'",
    "    },",
    "    // 또는 ES6 단축 메서드",
    "    sayHello() {",
    "        console.log(`Hello, ${this.name}`);",
    "    }",
    "};",
    "person2.sayName();  // 'haru'",
    "person2.sayHello(); // 'Hello, haru'",
    "```",
    "",
    "#### 콜백에서의 화살표 함수 활용",
    "```javascript",
    "const numbers = [1, 2, 3, 4, 5];",
    "",
    "// map",
    "const doubled = numbers.map(n => n * 2);",
    "console.log(doubled); // [2, 4, 6, 8, 10]",
    "",
    "// filter",
    "const evens = numbers.filter(n => n % 2 === 0);",
    "console.log(evens); // [2, 4]",
    "",
    "// reduce",
    "const sum = numbers.reduce((acc, cur) => acc + cur, 0);",
    "console.log(sum); // 15",
    "",
    "// sort",
    "const sorted = [...numbers].sort((a, b) => b - a);",
    "console.log(sorted); // [5, 4, 3, 2, 1]",
    "",
    "// 체이닝",
    "const result = numbers",
    "    .filter(n => n >= 3)",
    "    .map(n => n * 10)",
    "    .reduce((acc, cur) => acc + cur, 0);",
    "console.log(result); // 120 (30 + 40 + 50)",
    "```",
    "",
    "#### 함수 정의 방식 비교",
    "",
    "| 비교 | 함수 선언문 | 함수 표현식 | 화살표 함수 |",
    "|------|-----------|------------|------------|",
    "| 문법 | `function f() {}` | `var f = function() {}` | `const f = () => {}` |",
    "| 호이스팅 | ✅ | ❌ | ❌ |",
    "| `this` | 호출 시 결정 | 호출 시 결정 | 선언 시 상위 스코프 고정 |",
    "| `arguments` | ✅ | ✅ | ❌ (없음) |",
    "| `new` 사용 | ✅ | ✅ | ❌ (생성자 불가) |",
    "| 용도 | 일반 함수, 생성자 | 콜백, 변수 할당 | 콜백, 간결한 표현 |",
    "",
    "### Function() 생성자",
    "```javascript",
    "var add = new Function('x', 'y', 'return x + y');",
    "console.log(add(3, 4)); // 7",
    "```",
    "",
    "---",
    "",
    "## 2. 호이스팅 (Hoisting)",
    "",
    "**함수 선언문**은 코드 최상단으로 끌어올려져 선언 전에도 호출할 수 있습니다.",
    "",
    "```javascript",
    "// 함수 선언문 → 호이스팅됨",
    "console.log(add(2, 3)); // 5 (정상 동작)",
    "",
    "function add(x, y) {",
    "    return x + y;",
    "}",
    "```",
    "",
    "**함수 표현식**은 호이스팅되지 않아 선언 전 호출 시 에러가 발생합니다.",
    "",
    "```javascript",
    "// 함수 표현식 → 호이스팅 안 됨",
    "// add(2, 3); // TypeError: add is not a function",
    "",
    "var add = function (x, y) {",
    "    return x + y;",
    "};",
    "",
    "add(3, 4); // 7 (정상)",
    "```",
    "",
    "---",
    "",
    "## 3. 일급 객체 (First-class Object)",
    "",
    "자바스크립트의 함수는 일급 객체로서 다음이 가능합니다.",
    "",
    "### 변수/프로퍼티에 할당",
    "```javascript",
    "var bar = function () { return 100; };",
    "console.log(bar()); // 100",
    "",
    "var obj = {};",
    "obj.baz = function () { return 200; };",
    "console.log(obj.baz()); // 200",
    "```",
    "",
    "### 함수를 인자로 전달 (콜백)",
    "```javascript",
    "var foo = function (func) {",
    "    func();",
    "};",
    "",
    "foo(function () {",
    "    console.log('Function can be used as the argument.');",
    "});",
    "```",
    "",
    "### 함수를 리턴값으로 사용",
    "```javascript",
    "var foo = function () {",
    "    return function () {",
    "        console.log('this function is the return value.');",
    "    };",
    "};",
    "",
    "var bar = foo();",
    "bar(); // 'this function is the return value.'",
    "```",
    "",
    "### 함수에 프로퍼티 추가",
    "함수도 객체이므로 프로퍼티를 동적으로 추가할 수 있습니다.",
    "",
    "```javascript",
    "function add(x, y) { return x + y; }",
    "add.result = add(3, 2);",
    "add.status = 'OK';",
    "console.log(add.result); // 5",
    "console.log(add.status); // 'OK'",
    "```",
    "",
    "### 함수의 length 프로퍼티",
    "`length`는 함수가 기대하는 **매개변수의 개수**입니다.",
    "",
    "```javascript",
    "function func0() {}",
    "function func1(x) { return x; }",
    "function func2(x, y) { return x + y; }",
    "",
    "console.log(func0.length); // 0",
    "console.log(func1.length); // 1",
    "console.log(func2.length); // 2",
    "```",
    "",
    "---",
    "",
    "## 4. 즉시 실행 함수 (IIFE)",
    "",
    "선언과 동시에 실행되며, 변수 스코프를 오염시키지 않습니다.",
    "",
    "```javascript",
    "(function (name) {",
    "    console.log('This is the immediate function --> ' + name);",
    "})('foo');",
    "```",
    "",
    "---",
    "",
    "## 5. 내부 함수와 클로저",
    "",
    "### 내부 함수",
    "내부 함수는 부모 함수의 변수에 접근할 수 있지만, 외부에서는 호출할 수 없습니다.",
    "",
    "```javascript",
    "function parent() {",
    "    var a = 100;",
    "    var b = 200;",
    "",
    "    function child() {",
    "        var b = 300;",
    "        console.log(a); // 100 (부모 변수 접근)",
    "        console.log(b); // 300 (자신의 변수 우선)",
    "    }",
    "    child();",
    "}",
    "parent();",
    "// child(); // ReferenceError! (외부 호출 불가)",
    "```",
    "",
    "### 클로저 (Closure)",
    "내부 함수를 리턴하면, 외부 함수가 종료된 뒤에도 부모 변수에 접근할 수 있습니다.",
    "",
    "```javascript",
    "function parent() {",
    "    var a = 100;",
    "    var child = function () {",
    "        console.log(a);",
    "    };",
    "    return child;",
    "}",
    "",
    "var inner = parent();",
    "inner(); // 100 (parent가 종료되었지만 a에 접근 가능)",
    "```",
    "",
    "---",
    "",
    "## 6. arguments 객체",
    "",
    "함수 호출 시 전달된 모든 인자를 담는 유사 배열 객체입니다.",
    "",
    "```javascript",
    "function add(a, b) {",
    "    console.dir(arguments); // { '0': 1, '1': 2, '2': 3 }",
    "    return a + b;",
    "}",
    "",
    "console.log(add(1));       // NaN (b가 undefined)",
    "console.log(add(1, 2));    // 3",
    "console.log(add(1, 2, 3)); // 3 (세 번째 인자 무시)",
    "```",
    "",
    "### arguments를 진짜 배열로 변환",
    "```javascript",
    "function myFunction() {",
    "    var args = Array.prototype.slice.apply(arguments);",
    "    console.dir(args); // 진짜 배열",
    "}",
    "myFunction(1, 2, 3);",
    "```",
    "",
    "---",
    "",
    "## 7. this 바인딩",
    "",
    "함수 호출 방식에 따라 `this`가 가리키는 대상이 달라집니다.",
    "",
    "### 메서드 호출 → this = 해당 객체",
    "```javascript",
    "var myObject = {",
    "    name: 'foo',",
    "    sayName: function () {",
    "        console.log(this.name);",
    "    }",
    "};",
    "",
    "var otherObject = { name: 'bar' };",
    "otherObject.sayName = myObject.sayName;",
    "",
    "myObject.sayName();    // 'foo'",
    "otherObject.sayName(); // 'bar'",
    "```",
    "",
    "### 일반 함수 호출 → this = 전역 객체",
    "```javascript",
    "var test = 'This is test';",
    "",
    "var sayFoo = function () {",
    "    console.log(this.test); // 전역 객체의 test",
    "};",
    "",
    "sayFoo(); // 'This is test'",
    "```",
    "",
    "### 내부 함수의 this 문제와 해결 (that 패턴)",
    "```javascript",
    "var myObject = {",
    "    value: 1,",
    "    func1: function () {",
    "        var that = this; // this를 that에 저장",
    "",
    "        this.value += 1;",
    "        console.log('func1: ' + this.value); // 2",
    "",
    "        var func2 = function () {",
    "            that.value += 1;",
    "            console.log('func2: ' + that.value); // 3",
    "        };",
    "        func2();",
    "    }",
    "};",
    "myObject.func1();",
    "```",
    "",
    "### 생성자 함수 호출 → this = 새로 생성된 객체",
    "```javascript",
    "var Person = function (name) {",
    "    this.name = name;",
    "};",
    "",
    "var foo = new Person('foo');",
    "console.log(foo.name); // 'foo'",
    "```",
    "",
    "### new 없이 호출하면?",
    "`new` 없이 생성자 함수를 호출하면 `this`가 전역 객체를 가리킵니다.",
    "",
    "```javascript",
    "function Person(name, age, gender) {",
    "    this.name = name;",
    "    this.age = age;",
    "}",
    "",
    "var qux = Person('qux', 20, 'man');",
    "console.log(qux);         // undefined (리턴값 없음)",
    "console.log(window.name); // 'qux' (전역 오염!)",
    "```",
    "",
    "### apply() / call()로 명시적 this 바인딩",
    "```javascript",
    "function Person(name, age, gender) {",
    "    this.name = name;",
    "    this.age = age;",
    "    this.gender = gender;",
    "}",
    "",
    "var foo = {};",
    "Person.apply(foo, ['foo', 30, 'man']);",
    "console.dir(foo); // { name: 'foo', age: 30, gender: 'man' }",
    "```",
    "",
    "| 메서드 | 인자 전달 방식 |",
    "|--------|---------------|",
    "| `apply(thisArg, [argsArray])` | 배열로 전달 |",
    "| `call(thisArg, arg1, arg2, ...)` | 개별 인자로 전달 |",
    "",
    "---",
    "",
    "## 8. 함수 리턴",
    "",
    "### 리턴문이 없으면 undefined",
    "```javascript",
    "var noReturnFunc = function () {",
    "    console.log('no return');",
    "};",
    "console.log(noReturnFunc()); // undefined",
    "```",
    "",
    "### 생성자 함수에서의 리턴",
    "```javascript",
    "// 객체를 반환하면 → 해당 객체가 리턴",
    "function Person(name) {",
    "    this.name = name;",
    "    return { name: 'bar', age: 20 }; // 이 객체가 리턴됨",
    "}",
    "var foo = new Person('foo');",
    "console.log(foo.name); // 'bar'",
    "",
    "// 기본 타입을 반환하면 → 무시되고 this 리턴",
    "function Person2(name) {",
    "    this.name = name;",
    "    return 100; // 무시됨",
    "}",
    "var bar = new Person2('bar');",
    "console.log(bar.name); // 'bar' (this가 리턴됨)",
    "```",
    "",
    "---",
    "",
    "## 9. 프로토타입 체이닝",
    "",
    "객체에서 프로퍼티를 찾을 때, 자신에게 없으면 **프로토타입 체인**을 따라 상위로 검색합니다.",
    "",
    "### 프로토타입 메서드 동적 추가",
    "```javascript",
    "function Person(name) {",
    "    this.name = name;",
    "}",
    "",
    "var foo = new Person('foo');",
    "",
    "Person.prototype.sayHello = function () {",
    "    console.log('Hello');",
    "};",
    "",
    "foo.sayHello(); // 'Hello' (이미 생성된 객체도 접근 가능)",
    "```",
    "",
    "### 프로토타입 프로퍼티 읽기 vs 쓰기",
    "```javascript",
    "function Person(name) { this.name = name; }",
    "Person.prototype.country = 'Korea';",
    "",
    "var foo = new Person('foo');",
    "var bar = new Person('bar');",
    "",
    "console.log(foo.country); // 'Korea' (프로토타입에서 읽기)",
    "console.log(bar.country); // 'Korea'",
    "",
    "foo.country = 'USA'; // foo 인스턴스에 직접 추가 (프로토타입 수정 아님)",
    "console.log(foo.country); // 'USA'",
    "console.log(bar.country); // 'Korea' (영향 없음)",
    "```",
    "",
    "### 내장 프로토타입 확장",
    "```javascript",
    "String.prototype.testMethod = function () {",
    "    console.log('This is String.prototype.testMethod()');",
    "};",
    "",
    "var str = 'this is test';",
    "str.testMethod(); // 동작함",
    "```",
    "",
    "---",
    "### 요약",
    "자바스크립트 함수의 핵심은 **일급 객체**(변수 할당·인자·리턴), **호이스팅**(선언문 vs 표현식), **this 바인딩**(메서드·함수·생성자·apply/call), **클로저**(내부 함수가 외부 변수 유지), **프로토타입 체이닝**(프로퍼티 검색 경로)입니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
