<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "js-functional-programming",
  title: "자바스크립트 함수형 프로그래밍",
  date: "2026-02-24",
  summary: "자바스크립트에서 함수형 프로그래밍을 구현하는 기법을 정리합니다. 고차 함수, reduce 추상화, 메모이제이션, 커링(Currying), bind, 래퍼 패턴, 그리고 each/map/reduce 직접 구현까지 소스 코드와 함께 설명합니다.",
  category: "Coding/JavaScript",
  tags: ["javascript","functional-programming","higher-order","memoization","currying","reduce","map","bind","basics"],
  content: [
    "## 한 줄 요약",
    "함수형 프로그래밍의 핵심은 **함수를 값으로 다루는 것**이며, 이를 통해 **고차 함수**, **메모이제이션**, **커링**, **map/reduce** 같은 강력한 추상화가 가능합니다.",
    "",
    "---",
    "",
    "## 1. 고차 함수 (Higher-order Function)",
    "",
    "함수를 인자로 받거나 함수를 반환하는 함수를 고차 함수라고 합니다.",
    "",
    "```javascript",
    "var get_encrypted = function (func) {",
    "    var str = 'zzoon';",
    "    return function () {",
    "        return func.call(this, str);",
    "    };",
    "};",
    "",
    "var f1 = function (input) { return 1; };",
    "var f2 = function (input) { return 2; };",
    "",
    "console.log(get_encrypted(f1)()); // 1",
    "console.log(get_encrypted(f2)()); // 2",
    "```",
    "",
    "암호화 함수를 **인자로 교체**할 수 있어, 알고리즘을 유연하게 바꿀 수 있습니다.",
    "",
    "---",
    "",
    "## 2. reduce 패턴 (배열 축소 추상화)",
    "",
    "### 구체적 함수에서 출발",
    "```javascript",
    "// 합계",
    "function sum(arr) {",
    "    var i = 0, sum = 0;",
    "    for (; i < arr.length; i++) sum += arr[i];",
    "    return sum;",
    "}",
    "",
    "// 곱셈",
    "function multiply(arr) {",
    "    var i = 0, result = 1;",
    "    for (; i < arr.length; i++) result *= arr[i];",
    "    return result;",
    "}",
    "",
    "var arr = [1, 2, 3, 4];",
    "console.log(sum(arr));      // 10",
    "console.log(multiply(arr)); // 24",
    "```",
    "",
    "### 범용 reduce로 추상화",
    "반복 로직은 같고 **연산만 다르므로** 함수를 인자로 받는 `reduce`로 통합할 수 있습니다.",
    "",
    "```javascript",
    "function reduce(func, arr, memo) {",
    "    var len = arr.length, i = 0, accum = memo;",
    "    for (; i < len; i++) {",
    "        accum = func(accum, arr[i]);",
    "    }",
    "    return accum;",
    "}",
    "",
    "var arr = [1, 2, 3, 4];",
    "",
    "var sum = function (x, y) { return x + y; };",
    "var multiply = function (x, y) { return x * y; };",
    "",
    "console.log(reduce(sum, arr, 0));      // 10",
    "console.log(reduce(multiply, arr, 1)); // 24",
    "```",
    "",
    "---",
    "",
    "## 3. 메모이제이션 (Memoization)",
    "",
    "이미 계산한 결과를 **캐시에 저장**해 중복 계산을 방지합니다.",
    "",
    "### 팩토리얼: 반복문 → 재귀 → 메모이제이션",
    "",
    "```javascript",
    "// 1) 반복문",
    "function factLoop(num) {",
    "    var val = 1;",
    "    for (var i = 2; i <= num; i++) val *= i;",
    "    return val;",
    "}",
    "",
    "// 2) 재귀",
    "function factRecur(num) {",
    "    if (num == 0) return 1;",
    "    return num * factRecur(num - 1);",
    "}",
    "",
    "// 3) 메모이제이션 + 클로저",
    "var fact = (function () {",
    "    var cache = { '0': 1 };",
    "    var func = function (n) {",
    "        if (typeof cache[n] === 'number') {",
    "            return cache[n];",
    "        }",
    "        return (cache[n] = n * func(n - 1));",
    "    };",
    "    return func;",
    "})();",
    "",
    "console.log(fact(10)); // 3628800",
    "console.log(fact(20)); // 두 번째 호출 시 캐시 활용",
    "```",
    "",
    "### 피보나치: 메모이제이션",
    "```javascript",
    "var fibo = (function () {",
    "    var cache = { '0': 0, '1': 1 };",
    "    var func = function (n) {",
    "        if (typeof cache[n] === 'number') return cache[n];",
    "        return (cache[n] = func(n - 1) + func(n - 2));",
    "    };",
    "    return func;",
    "})();",
    "",
    "console.log(fibo(10)); // 55",
    "```",
    "",
    "### 범용 cacher 함수",
    "팩토리얼과 피보나치의 메모이제이션 패턴을 하나의 함수로 통합합니다.",
    "",
    "```javascript",
    "var cacher = function (cache, func) {",
    "    var calculate = function (n) {",
    "        if (typeof cache[n] === 'number') return cache[n];",
    "        return (cache[n] = func(calculate, n));",
    "    };",
    "    return calculate;",
    "};",
    "",
    "var fact = cacher({ '0': 1 }, function (func, n) {",
    "    return n * func(n - 1);",
    "});",
    "",
    "var fibo = cacher({ '0': 0, '1': 1 }, function (func, n) {",
    "    return func(n - 1) + func(n - 2);",
    "});",
    "",
    "console.log(fact(10)); // 3628800",
    "console.log(fibo(10)); // 55",
    "```",
    "",
    "---",
    "",
    "## 4. 커링 (Currying)",
    "",
    "인자를 **미리 고정**하여 새로운 함수를 만드는 기법입니다.",
    "",
    "### 기본 Curry",
    "```javascript",
    "function Calculate(a, b, c) {",
    "    return a * b + c;",
    "}",
    "",
    "function Curry(func) {",
    "    var args = Array.prototype.slice.call(arguments, 1);",
    "    return function () {",
    "        return func.apply(null, args.concat(",
    "            Array.prototype.slice.call(arguments)",
    "        ));",
    "    };",
    "}",
    "",
    "var new_func1 = Curry(Calculate, 1);",
    "console.log(new_func1(2, 3)); // 1*2+3 = 5",
    "",
    "var new_func2 = Curry(Calculate, 1, 3);",
    "console.log(new_func2(3));    // 1*3+3 = 6",
    "```",
    "",
    "### Curry2: undefined 자리 채우기",
    "```javascript",
    "function Curry2(func) {",
    "    var args = Array.prototype.slice.call(arguments, 1);",
    "    return function () {",
    "        var arg_idx = 0;",
    "        for (var i = 0; i < args.length && arg_idx < arguments.length; i++)",
    "            if (args[i] === undefined)",
    "                args[i] = arguments[arg_idx++];",
    "        return func.apply(null, args);",
    "    };",
    "}",
    "",
    "var new_func = Curry2(Calculate, 1, undefined, 4);",
    "console.log(new_func(3)); // 1*3+4 = 7",
    "```",
    "",
    "---",
    "",
    "## 5. bind와 래퍼 패턴",
    "",
    "### bind",
    "`bind`는 `this`와 일부 인자를 고정한 새 함수를 반환합니다.",
    "",
    "```javascript",
    "var print_all = function (arg) {",
    "    for (var i in this) console.log(i + ' : ' + this[i]);",
    "    for (var i in arguments) console.log(i + ' : ' + arguments[i]);",
    "};",
    "",
    "var myobj = { name: 'zzoon' };",
    "",
    "var myfunc = print_all.bind(myobj);",
    "myfunc(); // name : zzoon",
    "",
    "var myfunc1 = print_all.bind(myobj, 'iamhjoo', 'others');",
    "myfunc1('insidejs');",
    "```",
    "",
    "### 래퍼(Wrapper) 패턴",
    "기존 함수를 감싸서 **기능을 확장**합니다.",
    "",
    "```javascript",
    "function wrap(object, method, wrapper) {",
    "    var fn = object[method];",
    "    return object[method] = function () {",
    "        return wrapper.apply(this, [fn].concat(",
    "            Array.prototype.slice.call(arguments)",
    "        ));",
    "    };",
    "}",
    "",
    "Function.prototype.original = function (value) {",
    "    this.value = value;",
    "    console.log('value : ' + this.value);",
    "};",
    "",
    "wrap(Function.prototype, 'original', function (orig_func, value) {",
    "    this.value = 20;",
    "    orig_func(value);",
    "    console.log('wrapper value : ' + this.value);",
    "});",
    "```",
    "",
    "---",
    "",
    "## 6. each / map / reduce 직접 구현",
    "",
    "### each (반복 추상화)",
    "```javascript",
    "function each(obj, fn, args) {",
    "    if (obj.length == undefined)",
    "        for (var i in obj)",
    "            fn.apply(obj[i], args || [i, obj[i]]);",
    "    else",
    "        for (var i = 0; i < obj.length; i++)",
    "            fn.apply(obj[i], args || [i, obj[i]]);",
    "    return obj;",
    "}",
    "",
    "each([1, 2, 3], function (idx, num) {",
    "    console.log(idx + ': ' + num);",
    "});",
    "",
    "each({ name: 'zzoon', age: 30 }, function (idx, value) {",
    "    console.log(idx + ': ' + value);",
    "});",
    "```",
    "",
    "### Array.prototype.map 구현",
    "```javascript",
    "Array.prototype.map = function (callback) {",
    "    var obj = this;",
    "    var A = new Array(obj.length);",
    "",
    "    for (var i = 0; i < obj.length; i++) {",
    "        A[i] = callback.call(null, obj[i]);",
    "    }",
    "    return A;",
    "};",
    "",
    "var arr = [1, 2, 3];",
    "var new_arr = arr.map(function (value) {",
    "    return value * value;",
    "});",
    "console.log(new_arr); // [1, 4, 9]",
    "```",
    "",
    "### Array.prototype.reduce 구현",
    "```javascript",
    "Array.prototype.reduce = function (callback) {",
    "    var obj = this;",
    "    var accumulated_value = 0;",
    "",
    "    for (var i = 0; i < obj.length; i++) {",
    "        accumulated_value = callback.call(null, accumulated_value, obj[i]);",
    "    }",
    "    return accumulated_value;",
    "};",
    "",
    "var arr = [1, 2, 3];",
    "var result = arr.reduce(function (a, b) {",
    "    return a + b * b;",
    "});",
    "console.log(result); // 14 (0 + 1 + 4 + 9)",
    "```",
    "",
    "---",
    "",
    "## 학습 흐름 정리",
    "",
    "```",
    "구체적 함수 (sum, multiply)",
    "    ↓ 추상화",
    "고차 함수 (reduce, each)",
    "    ↓ 성능 최적화",
    "메모이제이션 (cache + closure)",
    "    ↓ 범용화",
    "cacher 패턴",
    "    ↓ 함수 조합",
    "커링, bind, 래퍼",
    "    ↓ 실전",
    "map, reduce 직접 구현",
    "```",
    "",
    "---",
    "### 요약",
    "자바스크립트 함수형 프로그래밍의 핵심은 **구체적 로직을 고차 함수로 추상화**하고, **메모이제이션으로 성능을 최적화**하며, **커링/bind로 함수를 재사용**하는 것입니다. `each`, `map`, `reduce`와 같은 함수형 유틸리티의 내부 구현을 이해하면 라이브러리 활용 능력도 높아집니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
