<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "k-means-clustering",
  title: "K-평균 군집화(K-Means Clustering)",
  date: "2026-02-17",
  summary: "K-평균은 정답 레이블 없이 데이터를 K개의 군집으로 나누는 비지도 학습 알고리즘입니다. 중심 갱신, inertia, 사이킷런 KMeans까지 정리합니다.",
  category: "Technology/AI",
  tags: ["ai", "machine-learning", "k-means", "clustering", "unsupervised-learning"],
  content: [
    "## K-평균 군집화란?",
    "**K-평균(K-Means)**은 **정답 레이블 없이** 데이터를 **K개의 군집**으로 나누는 **비지도 학습** 알고리즘입니다. 각 군집은 **중심(centroid)**을 갖고, 각 샘플은 가장 가까운 중심에 할당됩니다.",
    "",
    "| 장점 | 단점 |",
    "|------|------|",
    "| 구현이 간단하고 빠름 | K를 미리 정해야 함 |",
    "| 대용량 데이터에 적용 가능 | 구형(球形) 군집에 적합 |",
    "| 해석이 비교적 쉬움 | 이상치에 민감 |",
    "",
    "---",
    "## 알고리즘 동작",
    "1. K개의 중심을 **무작위**로 초기화",
    "2. 각 샘플을 **가장 가까운 중심**에 할당",
    "3. 각 군집의 **평균**을 새 중심으로 갱신",
    "4. 2~3을 **수렴**할 때까지 반복",
    "",
    "---",
    "## 기본 사용법",
    "```python",
    "from sklearn.cluster import KMeans",
    "import numpy as np",
    "",
    "# 2차원 데이터 예시",
    "data = np.array([[1, 2], [1.5, 1.8], [5, 8], [8, 8], [1, 0.6], [9, 11]])",
    "",
    "kmeans = KMeans(n_clusters=2, random_state=42)",
    "kmeans.fit(data)",
    "",
    "# 각 샘플의 군집 레이블 (0 또는 1)",
    "print(kmeans.labels_)",
    "",
    "# 군집 중심 좌표",
    "print(kmeans.cluster_centers_)",
    "",
    "# inertia: 각 샘플-중심 거리 제곱의 합 (작을수록 응집 좋음)",
    "print(kmeans.inertia_)",
    "```",
    "",
    "---",
    "## K 선택하기",
    "K를 미리 알아야 하므로, **엘보우 방법**으로 inertia-K 그래프를 보고 꺾이는 지점을 K로 선택합니다.",
    "",
    "```python",
    "inertias = []",
    "for k in range(2, 10):",
    "    km = KMeans(n_clusters=k, random_state=42)",
    "    km.fit(data)",
    "    inertias.append(km.inertia_)",
    "",
    "import matplotlib.pyplot as plt",
    "plt.plot(range(2, 10), inertias, marker='o')",
    "plt.xlabel('K')",
    "plt.ylabel('inertia')",
    "plt.show()",
    "```",
    "",
    "---",
    "## predict vs fit_predict",
    "- **fit**: 훈련 데이터로 중심 학습",
    "- **predict**: 새 데이터를 기존 중심에 할당 (가장 가까운 군집 번호 반환)",
    "",
    "```python",
    "new_points = np.array([[0, 0], [10, 10]])",
    "print(kmeans.predict(new_points))  # [0, 1] 등",
    "```",
    "",
    "---",
    "## 정리",
    "| 용어 | 요약 |",
    "|------|------|",
    "| K-평균 | K개 중심으로 군집 나누는 비지도 학습 |",
    "| centroid | 군집 중심 (평균 좌표) |",
    "| inertia | 군집 내 응집도 (작을수록 좋음) |",
    "| n_clusters | 군집 개수 K |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
