<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "k-nearest-neighbors-algorithm",
  title: "K-최근접 이웃 알고리즘(K-Nearest Neighbors, KNN)",
  date: "2026-02-16",
  summary: "K-최근접 이웃 알고리즘은 가장 가까운 K개의 이웃을 찾아 다수결로 분류하는 지도 학습 알고리즘입니다. 특성, 입력·타깃, 훈련, 모델, 정확도, 사이킷런 KNeighborsClassifier까지 정리합니다.",
  category: "Technology/AI",
  tags: ["ai", "machine-learning", "knn", "scikit-learn", "supervised-learning"],
  content: [
    "## K-최근접 이웃 알고리즘이란?",
    "K-최근접 이웃(K-Nearest Neighbors, KNN)은 **가장 가까운 K개의 샘플**을 찾아 그들의 **다수결**로 예측하는 지도 학습 알고리즘입니다.",
    "",
    "예: 새 물고기(길이 30cm, 무게 600g)가 도미인지 빙어인지 예측할 때,",
    "- 가장 가까운 5개 이웃 중 4개가 도미, 1개가 빙어 → **도미**로 분류",
    "",
    "| 장점 | 단점 |",
    "|------|------|",
    "| 직관적이고 이해하기 쉬움 | 예측 시 모든 훈련 데이터와 거리 계산 필요 → 느림 |",
    "| 데이터 분포를 가정하지 않음 | 특성 스케일에 민감 (정규화 필요) |",
    "| 분류·회귀 모두 사용 가능 | 고차원에서 성능 저하 |",
    "",
    "---",
    "## 산점도(Scatter Plot)",
    "**산점도**는 두 변수를 x축, y축에 두고 점으로 나타내는 그래프입니다. 데이터 분포를 시각적으로 파악할 때 사용합니다.",
    "",
    "예: 물고기 분류에서 x축=길이, y축=무게로 점을 찍으면 도미와 빙어가 서로 다른 영역에 모여 있는 것을 볼 수 있습니다.",
    "",
    "```python",
    "import matplotlib.pyplot as plt",
    "plt.scatter(bream_length, bream_weight)   # 도미",
    "plt.scatter(smelt_length, smelt_weight)   # 빙어",
    "plt.xlabel('length')",
    "plt.ylabel('weight')",
    "plt.show()",
    "```",
    "",
    "---",
    "## 맷플롯립(Matplotlib)",
    "**Matplotlib**은 Python에서 그래프·차트를 그리는 대표 라이브러리입니다.",
    "",
    "| 함수 | 설명 |",
    "|------|------|",
    "| `plt.scatter(x, y)` | 산점도 그리기 |",
    "| `plt.xlabel()` / `plt.ylabel()` | 축 레이블 |",
    "| `plt.show()` | 그래프 표시 |",
    "",
    "```python",
    "import matplotlib.pyplot as plt",
    "plt.scatter([1,2,3], [4,5,6])",
    "plt.show()",
    "```",
    "",
    "---",
    "## 특성(Feature)",
    "**특성(Feature)**은 모델에 입력하는 **각 변수**입니다. 예측에 사용하는 정보 단위입니다.",
    "",
    "| 예시 | 특성 |",
    "|------|------|",
    "| 물고기 분류 | 길이, 무게 (2개 특성) |",
    "| 집값 예측 | 면적, 층수, 연식, ... |",
    "| 스팸 분류 | 단어 빈도, 제목 길이, ... |",
    "",
    "특성이 많을수록 고차원이 되고, KNN은 거리 계산에 모든 특성을 사용합니다.",
    "",
    "---",
    "## 지도 학습 데이터 - 입력(Input)",
    "**입력**은 모델에게 넣어주는 **특성 데이터**입니다. 예측의 근거가 됩니다.",
    "",
    "```python",
    "# fish_data: [길이, 무게] 쌍 49개",
    "fish_data = [[25.4, 242.0], [26.3, 290.0], ...]",
    "```",
    "",
    "- 각 행 = 하나의 샘플(예: 한 마리 물고기)",
    "- 각 열 = 하나의 특성(예: 길이, 무게)",
    "",
    "---",
    "## 지도 학습 정답 - 타깃(Target)",
    "**타깃(Target)**은 각 입력에 대한 **정답 레이블**입니다. 지도 학습에서 모델이 학습할 '답'입니다.",
    "",
    "```python",
    "# fish_target: 1=도미, 0=빙어",
    "fish_target = [1, 1, 1, ..., 0, 0, 0]  # 35개 1, 14개 0",
    "```",
    "",
    "| 학습 종류 | 타깃 | 예시 |",
    "|----------|------|------|",
    "| 분류 | 카테고리(0, 1, 2, ...) | 도미/빙어, 스팸/정상 |",
    "| 회귀 | 연속값 | 집값, 온도 |",
    "",
    "---",
    "## 훈련 세트와 테스트 세트",
    "데이터를 **훈련 세트**와 **테스트 세트**로 나누는 이유는, 모델이 **보지 못한 데이터**에서 얼마나 잘 예측하는지 평가하기 위함입니다.",
    "",
    "### 훈련 세트(Training Set)",
    "- **모델이 학습할 때 사용하는 데이터**",
    "- `fit(train_input, train_target)`에 전달",
    "- 모델이 이 데이터로부터 규칙(패턴)을 학습함",
    "",
    "### 테스트 세트(Test Set)",
    "- **모델이 한 번도 보지 못한 데이터**",
    "- `score(test_input, test_target)`로 정확도 평가",
    "- 훈련에 사용하지 않았기 때문에, **실제 성능**을 더 잘 반영함",
    "",
    "### 왜 나누는가?",
    "| 훈련 데이터로만 평가할 때 | 테스트 세트로 평가할 때 |",
    "|--------------------------|--------------------------|",
    "| 모델이 '외운' 데이터에 과적합돼도 잘 맞춤 | 보지 못한 데이터 → 일반화 능력 확인 |",
    "| 과적합 여부를 알 수 없음 | 과적합되면 테스트 정확도가 떨어짐 |",
    "",
    "### 분할 비율",
    "흔히 **훈련 70~80% : 테스트 20~30%** 정도로 나눕니다. 사이킷런의 `train_test_split`을 사용하면 됩니다.",
    "",
    "```python",
    "from sklearn.model_selection import train_test_split",
    "train_input, test_input, train_target, test_target = train_test_split(",
    "    fish_data, fish_target, test_size=0.2, random_state=42",
    ")",
    "```",
    "",
    "주의: **순서대로** 나누면 (앞 35개=도미, 뒤 14개=빙어) 테스트에 빙어만 들어가 편향됩니다. **무작위로 섞어서** 나눠야 합니다.",
    "",
    "---",
    "## 훈련(Training)",
    "**훈련(Learning)**은 모델이 **데이터로부터 규칙을 학습**하는 과정입니다.",
    "",
    "KNN의 경우:",
    "- 별도의 '학습' 단계가 거의 없음",
    "- `fit()` 호출 시 **훈련 데이터를 그대로 저장**해 둠",
    "- 예측 시 저장된 데이터와의 거리를 계산해 이웃을 찾음",
    "",
    "```python",
    "kn.fit(fish_data, fish_target)  # 훈련 데이터 저장",
    "```",
    "",
    "---",
    "## 모델(Model)",
    "**모델**은 머신러닝 알고리즘이 **구체화된 프로그램**입니다. 훈련된 상태로 예측·분류를 수행합니다.",
    "",
    "- `KNeighborsClassifier`: KNN 분류 모델",
    "- `fit()`: 훈련 데이터로 '학습'",
    "- `predict()`: 새 데이터의 예측값 반환",
    "- `score()`: 정확도 계산",
    "",
    "```python",
    "kn = KNeighborsClassifier()      # 모델 생성",
    "kn.fit(fish_data, fish_target)   # 훈련",
    "kn.predict([[30, 600]])          # 예측 → [1] (도미)",
    "```",
    "",
    "---",
    "## 정확도(Accuracy)",
    "**정확도**는 모델이 **맞게 예측한 비율**입니다.",
    "",
    "정확도 = (맞춘 개수) / (전체 개수)",
    "",
    "```python",
    "kn.score(fish_data, fish_target)  # 훈련 데이터에 대한 정확도",
    "# 테스트 데이터로 평가할 때가 더 신뢰할 수 있음",
    "```",
    "",
    "주의: 훈련 데이터로만 정확도를 보면 **과적합** 여부를 알 수 없습니다. 보통 훈련 세트와 **테스트 세트**를 나누어 평가합니다.",
    "",
    "---",
    "## 사이킷런(Scikit-learn)",
    "**Scikit-learn**은 Python의 대표적인 **머신러닝 라이브러리**입니다.",
    "",
    "| 기능 | 설명 |",
    "|------|------|",
    "| 분류 | KNN, SVM, 결정 트리, 랜덤 포레스트 등 |",
    "| 회귀 | 선형 회귀, 릿지, 라쏘 등 |",
    "| 전처리 | 스케일링, 인코딩 등 |",
    "| 모델 선택 | 교차 검증, 그리드 서치 |",
    "",
    "```python",
    "pip install scikit-learn",
    "```",
    "",
    "---",
    "## KNeighborsClassifier",
    "**KNeighborsClassifier**는 사이킷런에서 KNN **분류**를 위한 클래스입니다.",
    "",
    "### 기본 사용법",
    "```python",
    "from sklearn.neighbors import KNeighborsClassifier",
    "",
    "kn = KNeighborsClassifier()",
    "kn = KNeighborsClassifier(n_neighbors=5)  # k=5 (기본값)",
    "",
    "kn.fit(train_input, train_target)           # 훈련",
    "kn.predict([[30, 600]])                      # 예측",
    "kn.score(test_input, test_target)            # 정확도",
    "```",
    "",
    "### 주요 파라미터",
    "| 파라미터 | 설명 | 기본값 |",
    "|----------|------|--------|",
    "| `n_neighbors` | 이웃 개수 k | 5 |",
    "| `weights` | 이웃 가중치 (uniform, distance 등) | uniform |",
    "| `metric` | 거리 척도 (euclidean, manhattan 등) | euclidean |",
    "",
    "---",
    "## 정리",
    "| 용어 | 한 줄 요약 |",
    "|------|------------|",
    "| K-최근접 이웃 | 가장 가까운 K개 이웃의 다수결로 예측 |",
    "| 산점도 | x-y 좌표에 점으로 데이터 분포 표시 |",
    "| 맷플롯립 | Python 그래프 라이브러리 |",
    "| 특성 | 입력 변수(예: 길이, 무게) |",
    "| 입력 | 모델에 넣는 데이터 (X) |",
    "| 타깃 | 정답 레이블 (y) |",
    "| 훈련 | 데이터로 규칙 학습 (fit) |",
    "| 모델 | 학습된 예측기 |",
    "| 정확도 | 맞춘 비율 (score) |",
    "| 훈련 세트 | 모델이 학습할 때 사용하는 데이터 |",
    "| 테스트 세트 | 평가용, 한 번도 보지 못한 데이터 |",
    "| 사이킷런 | Python 머신러닝 라이브러리 |",
    "| KNeighborsClassifier | KNN 분류 클래스 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
