<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "kotlin-generics-arrays",
  title: "Kotlin 제네릭과 배열 - 타입 파라미터, 변성, 배열 활용",
  date: "2026-03-03",
  summary: "Kotlin의 제네릭 클래스/함수, 공변성(out)/반공변성(in), reified, 배열 생성과 조작을 정리합니다.",
  category: "Coding/Kotlin",
  tags: ["kotlin", "제네릭", "배열", "공변성", "reified", "array"],
  content: [
    "## 제네릭 (Generics)",
    "타입을 매개변수화하여 다양한 타입에서 재사용 가능한 코드를 작성합니다.",
    "",
    "### 제네릭 클래스",
    "```kotlin",
    "class Box<T>(t: T) { var name = t }",
    "",
    "val box1: Box<Int> = Box(1)",
    "val box2: Box<String> = Box(\"Hello\")",
    "println(box1.name)  // 1",
    "println(box2.name)  // Hello",
    "```",
    "",
    "### 제네릭 함수",
    "```kotlin",
    "fun <T> findIndex(arr: Array<T>, target: T): Int {",
    "    for (i in arr.indices) { if (arr[i] == target) return i }",
    "    return -1",
    "}",
    "```",
    "",
    "### 타입 제한 (Upper Bound)",
    "```kotlin",
    "fun <T : Number> addNumbers(a: T, b: T): Double {",
    "    return a.toDouble() + b.toDouble()",
    "}",
    "```",
    "",
    "## 변성 (Variance)",
    "### 공변성 (Covariance) - out",
    "`out` 키워드를 사용하면 하위 타입 관계가 유지됩니다. **읽기 전용**(생산자)으로 제한됩니다.",
    "",
    "```kotlin",
    "class Box<out T>(val value: T)",
    "val intBox: Box<Int> = Box(10)",
    "val anyBox: Box<Any> = intBox  // 가능! (공변)",
    "```",
    "",
    "### 반공변성 (Contravariance) - in",
    "`in` 키워드를 사용하면 상위 타입 관계가 유지됩니다. **쓰기 전용**(소비자)으로 제한됩니다.",
    "",
    "```kotlin",
    "class Box<in T>(val size: Int) {",
    "    fun consume(item: T) { }",
    "}",
    "val nothings: Box<Nothing> = Box<Int>(20)",
    "```",
    "",
    "### 변성 요약",
    "| 변성 | 키워드 | 관계 | 역할 |",
    "|------|--------|------|------|",
    "| 무변성 | 없음 | 관계 없음 | 읽기/쓰기 |",
    "| 공변성 | `out` | `Int` → `Any` | 생산자 (읽기만) |",
    "| 반공변성 | `in` | `Any` → `Int` | 소비자 (쓰기만) |",
    "",
    "## reified 타입 파라미터",
    "```kotlin",
    "inline fun <reified T> checkType(value: Any) {",
    "    if (value is T) println(\"Type matches: ${T::class.simpleName}\")",
    "    else println(\"Type does not match\")",
    "}",
    "",
    "checkType<String>(\"Hello\")  // Type matches: String",
    "checkType<Int>(\"Hello\")     // Type does not match",
    "```",
    "",
    "## 배열 (Array)",
    "### 배열 생성",
    "```kotlin",
    "val intArr = intArrayOf(1, 2, 3, 4, 5)",
    "val strArr = arrayOf(\"Hello\", \"World\")",
    "val squares = Array(5) { i -> i * i }  // [0, 1, 4, 9, 16]",
    "```",
    "",
    "### 배열 접근",
    "```kotlin",
    "val arr = intArrayOf(1, 2, 3, 4, 5)",
    "println(arr[2])        // 3",
    "arr[0] = 8             // 세터",
    "println(arr.size)      // 5",
    "println(arr.sum())     // 합계",
    "println(4 in arr)      // true",
    "```",
    "",
    "### 배열 순회",
    "```kotlin",
    "val arr = arrayOf(\"a\", \"b\", \"c\")",
    "for (i in arr.indices) println(\"arr[$i] = ${arr[i]}\")",
    "for ((i, v) in arr.withIndex()) println(\"$i: $v\")",
    "arr.forEach { println(it) }",
    "```",
    "",
    "### 배열 정렬과 변환",
    "```kotlin",
    "val arr = arrayOf(5, 3, 1, 4, 2)",
    "arr.sort()",
    "val filtered = arr.filter { it > 3 }",
    "val mapped = arr.map { it * 2 }",
    "```",
    "",
    "## 문자열 처리",
    "```kotlin",
    "val str = \"Hello, Kotlin!\"",
    "println(str.length)                // 14",
    "println(str.uppercase())           // HELLO, KOTLIN!",
    "println(str.substring(7))          // Kotlin!",
    "println(str.split(\", \"))           // [Hello, Kotlin!]",
    "println(str.contains(\"Kotlin\"))    // true",
    "```",
    "",
    "---",
    "### 요약",
    "- 제네릭: `<T>`로 타입 매개변수화, `T : Number`로 상한 제한",
    "- 변성: `out`(공변, 생산자), `in`(반공변, 소비자), `*`(스타 프로젝션)",
    "- `reified`: 인라인 함수에서 런타임 타입 접근",
    "- 배열: `arrayOf()`, `intArrayOf()`, 인덱스/get/set/contains 접근"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
