<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "kotlin-basics",
  title: "Kotlin 기본 문법 - 변수, 타입, Null 안전성",
  date: "2026-03-03",
  summary: "Kotlin의 변수 선언(val/var), 기본 타입, Null 안전성, 연산자까지 핵심 기초를 정리합니다.",
  category: "Coding/Kotlin",
  tags: ["kotlin", "변수", "타입", "null", "연산자", "basics"],
  content: [
    "## Kotlin이란?",
    "Kotlin은 JetBrains에서 개발한 JVM 기반 프로그래밍 언어입니다. 2017년 Google이 Android 공식 언어로 채택하면서 큰 인기를 얻었습니다.",
    "",
    "- **간결한 문법**: 세미콜론 불필요, 타입 추론 지원",
    "- **Null 안전성**: 컴파일 타임에 NullPointerException 방지",
    "- **Java 상호운용**: 기존 Java 코드와 100% 호환",
    "- **함수형 프로그래밍**: 고차 함수, 람다식 지원",
    "",
    "## 변수 선언: val vs var",
    "`val`은 읽기 전용(불변), `var`은 변경 가능(가변)입니다.",
    "",
    "```kotlin",
    "val number = 10          // Int로 추론, 재할당 불가",
    "var language = \"Korean\"  // String으로 추론, 재할당 가능",
    "val secondNumber: Int = 20 // 타입 명시적 지정",
    "",
    "language = \"English\"     // var이므로 재할당 가능",
    "// number = 20            // 오류! val은 재할당 불가",
    "```",
    "",
    "| 키워드 | 의미 | Java 대응 |",
    "|--------|------|-----------|",
    "| val | 불변 (읽기 전용) | final 변수 |",
    "| var | 가변 (읽기/쓰기) | 일반 변수 |",
    "",
    "## 기본 타입",
    "Kotlin은 모든 것이 **객체**입니다. 기본 타입도 내부적으로 객체처럼 동작합니다.",
    "",
    "```kotlin",
    "val a: Int = 5         // 정수",
    "val b: Double = 3.14   // 실수",
    "val c: Boolean = true  // 논리",
    "val d: Char = 'A'      // 문자",
    "val e: String = \"Hello\" // 문자열",
    "val f: Long = 100L     // Long 타입",
    "```",
    "",
    "### 타입 추론",
    "Kotlin은 컴파일러가 타입을 자동으로 추론합니다.",
    "",
    "```kotlin",
    "val a = 5       // Int로 추론",
    "val b = 3       // Int로 추론",
    "val c: Int = a + b  // 명시적 Int 선언",
    "// val d: Short = a + b  // 오류! Int + Int = Int, Short에 할당 불가",
    "```",
    "",
    "### 문자열 템플릿",
    "문자열 안에서 `$변수명` 또는 `${표현식}`으로 값을 삽입할 수 있습니다.",
    "",
    "```kotlin",
    "val name = \"Kotlin\"",
    "println(\"Hello, $name!\")           // Hello, Kotlin!",
    "println(\"길이: ${name.length}\")     // 길이: 6",
    "```",
    "",
    "### 문자열 비교",
    "```kotlin",
    "var str1: String = \"Hello\"",
    "var str3 = \"Hello\"",
    "",
    "println(str1 == str3)   // true  (값 비교)",
    "println(str1 === str3)  // true  (참조 비교, String Pool)",
    "```",
    "",
    "## Null 안전성",
    "Kotlin의 가장 강력한 기능 중 하나입니다. 기본적으로 모든 변수는 **null을 허용하지 않습니다**.",
    "",
    "### Nullable 타입 (`?`)",
    "```kotlin",
    "var str1: String = \"Hello\"",
    "// str1 = null  // 오류! 기본적으로 null 불허",
    "",
    "var str2: String? = \"Hello\"  // ?를 붙이면 null 허용",
    "str2 = null                   // 가능",
    "```",
    "",
    "### 안전 호출 연산자 (`?.`)",
    "null일 수 있는 객체의 메서드를 안전하게 호출합니다. null이면 null을 반환합니다.",
    "",
    "```kotlin",
    "var str: String? = \"Hello Kotlin\"",
    "str = null",
    "println(str?.length)  // null (NPE 발생하지 않음)",
    "```",
    "",
    "### 엘비스 연산자 (`?:`)",
    "null인 경우 대체 값을 제공합니다.",
    "",
    "```kotlin",
    "var str: String? = null",
    "println(str?.length ?: -1)  // -1 (null이면 -1 반환)",
    "```",
    "",
    "### 비-null 단정 연산자 (`!!`)",
    "null이 아님을 강제로 단정합니다. null이면 **NPE가 발생**하므로 주의해야 합니다.",
    "",
    "```kotlin",
    "var str: String? = null",
    "// println(str!!.length)  // NPE 발생!",
    "```",
    "",
    "### Null 검사 요약",
    "| 연산자 | 설명 | 예시 |",
    "|--------|------|------|",
    "| `?.` | 안전 호출 (null이면 null 반환) | `str?.length` |",
    "| `?:` | 엘비스 (null이면 대체 값) | `str?.length ?: 0` |",
    "| `!!` | 비-null 단정 (NPE 위험) | `str!!.length` |",
    "",
    "## 타입 검사와 캐스팅",
    "```kotlin",
    "val x: Any = 256",
    "",
    "if (x is Int) {",
    "    println(\"Int: $x\")  // 스마트 캐스트로 자동 변환",
    "}",
    "",
    "// as를 이용한 명시적 캐스팅",
    "val y: String = x as? String ?: \"Not a String\"",
    "```",
    "",
    "## 비트 연산자",
    "Kotlin은 비트 연산에 **중위 함수**를 사용합니다.",
    "",
    "```kotlin",
    "val x = 4",
    "println(x shl 2)   // 16 (왼쪽 시프트)",
    "println(x shr 1)   // 2  (오른쪽 시프트)",
    "println(x.inv())   // -5 (비트 반전)",
    "",
    "val a = 0b1010     // 10",
    "val b = 0b1100     // 12",
    "println(a and b)   // 8  (0b1000)",
    "println(a or b)    // 14 (0b1110)",
    "println(a xor b)   // 6  (0b0110)",
    "```",
    "",
    "| 연산자 | 설명 |",
    "|--------|------|",
    "| `shl` | 왼쪽 시프트 |",
    "| `shr` | 오른쪽 시프트 |",
    "| `ushr` | 부호 없는 오른쪽 시프트 |",
    "| `and` | 비트 AND |",
    "| `or` | 비트 OR |",
    "| `xor` | 비트 XOR |",
    "| `inv()` | 비트 반전 |",
    "",
    "---",
    "### 요약",
    "- `val` = 불변, `var` = 가변",
    "- Kotlin은 타입 추론을 지원하며, 모든 것이 객체",
    "- `?` 타입으로 null 허용, `?.` `?:` `!!`로 안전하게 처리",
    "- 문자열 템플릿 `${}` 으로 편리한 문자열 조합",
    "- 비트 연산은 `shl`, `shr`, `and`, `or`, `xor` 중위 함수 사용"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
