<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "kotlin-abstract-interface",
  title: "Kotlin 추상 클래스, 인터페이스, 특수 클래스",
  date: "2026-03-03",
  summary: "Kotlin의 추상 클래스, 인터페이스, data class, enum class, sealed class, 연산자 오버로딩을 정리합니다.",
  category: "Coding/Kotlin",
  tags: ["kotlin", "추상클래스", "인터페이스", "sealed", "enum", "data"],
  content: [
    "## 추상 클래스 (abstract class)",
    "하나 이상의 추상 멤버를 포함하며, 인스턴스를 직접 생성할 수 없습니다.",
    "",
    "```kotlin",
    "abstract class Vehicle(val name: String, val color: String, val weight: Double) {",
    "    abstract var maxSpeed: Double",
    "    var year = \"2018\"",
    "    abstract fun start()",
    "    abstract fun stop()",
    "    fun displaySpecs() {",
    "        println(\"Name: $name, Color: $color, Max Speed: $maxSpeed\")",
    "    }",
    "}",
    "",
    "class Car(name: String, color: String, weight: Double, override var maxSpeed: Double)",
    "    : Vehicle(name, color, weight) {",
    "    override fun start() = println(\"Car Started\")",
    "    override fun stop() = println(\"Car Stopped\")",
    "}",
    "```",
    "",
    "## 인터페이스 (interface)",
    "추상 메서드와 기본 구현을 모두 가질 수 있습니다. **다중 구현**이 가능합니다.",
    "",
    "```kotlin",
    "interface Pet {",
    "    var category: String",
    "    val msgTags: String",
    "        get() = \"I'm your lovely pet!\"",
    "    fun feeding()",
    "    fun patting() { println(\"Keep patting!\") }",
    "}",
    "",
    "class Cat(override var category: String) : Pet {",
    "    override fun feeding() = println(\"Feed the cat a tuna can!\")",
    "}",
    "```",
    "",
    "### 추상 클래스 vs 인터페이스",
    "| 구분 | 추상 클래스 | 인터페이스 |",
    "|------|-------------|------------|",
    "| 상속 | 단일 상속 | 다중 구현 |",
    "| 생성자 | 있음 | 없음 |",
    "| 상태(필드) | 가능 | 불가 |",
    "| 기본 구현 | 가능 | 가능 |",
    "",
    "## data class",
    "`equals()`, `hashCode()`, `toString()`, `copy()`, `componentN()` 메서드를 자동 생성합니다.",
    "",
    "```kotlin",
    "data class Customer(var name: String, var email: String)",
    "",
    "val cus1 = Customer(\"Sean\", \"sean@mail.com\")",
    "val cus2 = Customer(\"Sean\", \"sean@mail.com\")",
    "",
    "println(cus1 == cus2)  // true",
    "println(cus1)          // Customer(name=Sean, email=sean@mail.com)",
    "",
    "val cus3 = cus1.copy(name = \"Alice\")",
    "",
    "// 구조 분해",
    "val (name, email) = cus1",
    "```",
    "",
    "## enum class",
    "```kotlin",
    "interface Score { fun getScore(): Int }",
    "",
    "enum class MemberType(var prio: String) : Score {",
    "    NORMAL(\"Third\") { override fun getScore() = 100 },",
    "    SILVER(\"Second\") { override fun getScore() = 500 },",
    "    GOLD(\"First\") { override fun getScore() = 1500 }",
    "}",
    "",
    "println(MemberType.NORMAL.getScore())  // 100",
    "println(MemberType.SILVER.prio)        // Second",
    "```",
    "",
    "## sealed class",
    "제한된 클래스 계층을 정의합니다. `when`과 함께 사용하면 `else`가 불필요합니다.",
    "",
    "```kotlin",
    "sealed class Result {",
    "    open class Success(val message: String) : Result()",
    "    class Error(val code: Int, val message: String) : Result()",
    "}",
    "",
    "class Status : Result()",
    "",
    "fun eval(result: Result): String = when (result) {",
    "    is Status -> \"in progress\"",
    "    is Result.Success -> result.message",
    "    is Result.Error -> result.message",
    "}",
    "```",
    "",
    "## 연산자 오버로딩",
    "```kotlin",
    "data class Point(val x: Int, val y: Int) {",
    "    operator fun plus(other: Point) = Point(x + other.x, y + other.y)",
    "}",
    "",
    "val p1 = Point(3, 5)",
    "val p2 = Point(1, 2)",
    "println(p1 + p2)  // Point(x=4, y=7)",
    "```",
    "",
    "| 연산자 | 함수명 |",
    "|--------|--------|",
    "| `+` | `plus` |",
    "| `-` | `minus` |",
    "| `*` | `times` |",
    "| `/` | `div` |",
    "| `==` | `equals` |",
    "| `[]` | `get`, `set` |",
    "| `()` | `invoke` |",
    "",
    "---",
    "### 요약",
    "- 추상 클래스: 단일 상속, 생성자/상태 보유 가능",
    "- 인터페이스: 다중 구현, 기본 구현 가능",
    "- `data class`: equals, hashCode, toString, copy, 구조 분해 자동 생성",
    "- `enum class`: 열거형 상수",
    "- `sealed class`: 제한된 계층 구조, `when`에서 else 불필요",
    "- `operator` 키워드로 연산자 오버로딩"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
