<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "kotlin-functions",
  title: "Kotlin 함수 - 고차 함수, 람다, 확장 함수",
  date: "2026-03-03",
  summary: "Kotlin 함수의 기본 선언부터 고차 함수, 람다식, 확장 함수, 인라인 함수, 꼬리 재귀까지 정리합니다.",
  category: "Coding/Kotlin",
  tags: ["kotlin", "함수", "람다", "고차함수", "확장함수", "인라인"],
  content: [
    "## 함수 기본 선언",
    "Kotlin 함수는 `fun` 키워드로 선언합니다.",
    "",
    "```kotlin",
    "fun max(a: Int, b: Int): Int {",
    "    return if (a > b) a else b",
    "}",
    "",
    "// 단일 표현식 함수 (반환 타입 추론)",
    "fun max(a: Int, b: Int) = if (a > b) a else b",
    "```",
    "",
    "### 기본값 매개변수",
    "매개변수에 기본값을 지정할 수 있습니다.",
    "",
    "```kotlin",
    "fun add(name: String, email: String = \"default\") {",
    "    println(\"${name}님의 이메일은 ${email}입니다.\")",
    "}",
    "",
    "add(\"홍길동\")                    // 홍길동님의 이메일은 default입니다.",
    "add(\"둘리\", \"dooly@example.kr\") // 둘리님의 이메일은 dooly@example.kr입니다.",
    "```",
    "",
    "### 가변 인자 (vararg)",
    "```kotlin",
    "fun printAll(vararg messages: String) {",
    "    for (m in messages) println(m)",
    "}",
    "",
    "printAll(\"Hello\", \"World\", \"Kotlin\")",
    "```",
    "",
    "### 명명된 인자 (Named Arguments)",
    "```kotlin",
    "fun defaultArgs(x: Int = 100, y: Int = 200) {",
    "    println(x + y)",
    "}",
    "",
    "defaultArgs()            // 300",
    "defaultArgs(200)         // 400",
    "defaultArgs(y = 50)      // 150 (x는 기본값 사용)",
    "```",
    "",
    "## 고차 함수 (Higher-Order Function)",
    "함수를 매개변수로 받거나 반환하는 함수입니다.",
    "",
    "```kotlin",
    "fun highOrder(sum: (Int, Int) -> Int, a: Int, b: Int): Int {",
    "    return sum(a, b)",
    "}",
    "",
    "val result = highOrder({ x, y -> x + y }, 10, 20)",
    "println(result)  // 30",
    "```",
    "",
    "### 람다식",
    "람다식은 `{매개변수 -> 본문}` 형태로 작성합니다.",
    "",
    "```kotlin",
    "// 기본 람다식",
    "val sum = { x: Int, y: Int -> x + y }",
    "println(sum(3, 5))  // 8",
    "",
    "// 매개변수가 1개면 it으로 접근",
    "val square: (Int) -> Int = { it * it }",
    "println(square(4))  // 16",
    "```",
    "",
    "### Call by Value vs Call by Name",
    "```kotlin",
    "// Call by Value: 람다식이 즉시 실행되어 값이 전달",
    "fun callByValue(b: Boolean): Boolean {",
    "    println(\"callByValue\")",
    "    return b",
    "}",
    "",
    "// Call by Name: 람다식 자체가 전달되어 필요할 때 실행",
    "fun callByName(b: () -> Boolean): Boolean {",
    "    println(\"callByName\")",
    "    return b()",
    "}",
    "```",
    "",
    "### 함수 참조 (::)",
    "```kotlin",
    "fun sum(a: Int, b: Int) = a + b",
    "",
    "val ref: (Int, Int) -> Int = ::sum",
    "println(ref(1, 2))  // 3",
    "```",
    "",
    "## 확장 함수 (Extension Function)",
    "기존 클래스에 새로운 함수를 추가할 수 있습니다. 클래스 수정 없이 기능을 확장합니다.",
    "",
    "```kotlin",
    "fun String.getLongString(target: String): String =",
    "    if (this.length > target.length) this else target",
    "",
    "val source = \"Hello World!\"",
    "val target = \"Kotlin\"",
    "println(source.getLongString(target))  // Hello World!",
    "```",
    "",
    "### 중위 함수 (Infix Function)",
    "```kotlin",
    "infix fun Int.multiply(x: Int): Int = this * x",
    "",
    "println(3 multiply 5)  // 15",
    "println(3.multiply(5)) // 15 (일반 호출도 가능)",
    "```",
    "",
    "## 인라인 함수 (Inline Function)",
    "고차 함수 호출 시 발생하는 오버헤드를 줄입니다. 함수 본문이 호출 지점에 복사됩니다.",
    "",
    "```kotlin",
    "inline fun shortFunc(a: Int, out: (Int) -> Unit) {",
    "    println(\"Before calling out()\")",
    "    out(a)",
    "    println(\"After calling out()\")",
    "}",
    "",
    "shortFunc(3) { println(\"First call: $it\") }",
    "// Before calling out()",
    "// First call: 3",
    "// After calling out()",
    "```",
    "",
    "### noinline과 crossinline",
    "| 키워드 | 설명 |",
    "|--------|------|",
    "| `inline` | 함수 본문과 람다를 호출 지점에 인라인 |",
    "| `noinline` | 특정 람다 매개변수를 인라인하지 않음 |",
    "| `crossinline` | 비지역 반환을 금지하면서 인라인 |",
    "",
    "## 꼬리 재귀 함수 (tailrec)",
    "스택 오버플로우 없이 재귀를 수행합니다. 컴파일러가 반복문으로 최적화합니다.",
    "",
    "```kotlin",
    "tailrec fun factorial(n: Int, run: Int = 1): Long {",
    "    return if (n == 1) run.toLong() else factorial(n - 1, run * n)",
    "}",
    "",
    "println(factorial(5))  // 120",
    "```",
    "",
    "### 일반 재귀 vs 꼬리 재귀",
    "```kotlin",
    "// 일반 재귀 (스택 누적)",
    "fun normalFactorial(n: Int): Long {",
    "    return if (n == 1) 1L else n * normalFactorial(n - 1)",
    "}",
    "",
    "// 꼬리 재귀 (스택 최적화, tailrec)",
    "tailrec fun tailFactorial(n: Int, acc: Int = 1): Long {",
    "    return if (n == 1) acc.toLong() else tailFactorial(n - 1, acc * n)",
    "}",
    "```",
    "",
    "## 지역 함수와 변수 범위",
    "함수 안에 함수를 정의할 수 있습니다.",
    "",
    "```kotlin",
    "fun outerFunc() {",
    "    val outerVar = 10",
    "",
    "    fun innerFunc() {",
    "        val innerVar = 20",
    "        println(outerVar + innerVar)  // 외부 변수 접근 가능",
    "    }",
    "",
    "    innerFunc()",
    "}",
    "```",
    "",
    "## 익명 함수 (Anonymous Function)",
    "```kotlin",
    "val greet = fun(name: String): String {",
    "    return \"Hello, $name!\"",
    "}",
    "",
    "println(greet(\"Kotlin\"))  // Hello, Kotlin!",
    "```",
    "",
    "---",
    "### 요약",
    "- `fun`으로 선언, 단일 표현식은 `=`으로 간결하게",
    "- 기본값 매개변수, 명명된 인자, vararg 지원",
    "- 고차 함수: 함수를 매개변수/반환값으로 사용",
    "- 람다식: `{ x, y -> x + y }`, 단일 매개변수는 `it`",
    "- 확장 함수로 기존 클래스에 기능 추가",
    "- `inline`으로 고차 함수 오버헤드 제거",
    "- `tailrec`으로 꼬리 재귀 최적화"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
