<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "kotlin-scope-io",
  title: "Kotlin 스코프 함수와 파일 I/O - let, apply, run, with, also",
  date: "2026-03-03",
  summary: "Kotlin의 5가지 스코프 함수(let, run, with, apply, also), DSL 빌더, 파일 읽기/쓰기를 정리합니다.",
  category: "Coding/Kotlin",
  tags: ["kotlin", "스코프함수", "let", "apply", "run", "파일IO"],
  content: [
    "## 스코프 함수란?",
    "객체의 컨텍스트 안에서 코드 블록을 실행하는 함수입니다.",
    "",
    "## let",
    "**컨텍스트 객체**: `it` | **반환값**: 람다 결과",
    "",
    "```kotlin",
    "val score: Int? = 32",
    "score?.let { println(\"Score: $it\") }",
    "",
    "val str = score.let { it.toString() }",
    "",
    "var a = 1",
    "a = a.let { it + 2 }.let { val i = it + 2; i }",
    "println(a)  // 5",
    "```",
    "",
    "## run",
    "**컨텍스트 객체**: `this` | **반환값**: 람다 결과",
    "",
    "```kotlin",
    "data class User(var name: String, var skills: String)",
    "val user = User(\"Kildong\", \"default\")",
    "val result = user.run {",
    "    skills = \"Kotlin\"",
    "    \"Updated: $name\"",
    "}",
    "println(result)  // Updated: Kildong",
    "```",
    "",
    "## with",
    "**컨텍스트 객체**: `this` | **반환값**: 람다 결과 (확장 함수 아님)",
    "",
    "```kotlin",
    "data class User(val name: String, var skills: String, var email: String? = null)",
    "val user = User(\"Kildong\", \"default\")",
    "val result = with(user) {",
    "    skills = \"Kotlin\"",
    "    email = \"kildong@example.com\"",
    "    \"Success\"",
    "}",
    "```",
    "",
    "## apply",
    "**컨텍스트 객체**: `this` | **반환값**: 객체 자체",
    "",
    "```kotlin",
    "data class Person(var name: String, var skills: String)",
    "val person = Person(\"Kildong\", \"Kotlin\").apply {",
    "    name = \"Sean\"",
    "    skills = \"Java\"",
    "}",
    "println(person)  // Person(name=Sean, skills=Java)",
    "```",
    "",
    "## also",
    "**컨텍스트 객체**: `it` | **반환값**: 객체 자체",
    "",
    "```kotlin",
    "val numbers = mutableListOf(1, 2, 3)",
    "numbers.also { println(\"원본: $it\") }.add(4)",
    "",
    "val result = \"Hello\"",
    "    .also { println(\"Step 1: $it\") }",
    "    .uppercase()",
    "    .also { println(\"Step 2: $it\") }",
    "```",
    "",
    "## 스코프 함수 비교",
    "| 함수 | 객체 참조 | 반환값 | 주요 용도 |",
    "|------|----------|--------|----------|",
    "| `let` | `it` | 람다 결과 | null 검사, 변환 |",
    "| `run` | `this` | 람다 결과 | 초기화 + 결과 계산 |",
    "| `with` | `this` | 람다 결과 | 객체 멤버 일괄 접근 |",
    "| `apply` | `this` | 객체 자체 | 객체 설정 |",
    "| `also` | `it` | 객체 자체 | 부수 효과, 디버깅 |",
    "",
    "## use (자동 리소스 해제)",
    "```kotlin",
    "import java.io.File",
    "val text = File(\"data.txt\").inputStream().bufferedReader().use { it.readText() }",
    "```",
    "",
    "## DSL 빌더",
    "```kotlin",
    "class Person { var name = \"\"; var age = 0; var email = \"\" }",
    "",
    "fun person(block: Person.() -> Unit): Person {",
    "    val p = Person(); p.block(); return p",
    "}",
    "",
    "val me = person {",
    "    name = \"Kim\"",
    "    age = 25",
    "    email = \"kim@example.com\"",
    "}",
    "```",
    "",
    "## 파일 I/O",
    "### 파일 읽기",
    "```kotlin",
    "import java.io.File",
    "",
    "val text = File(path).readText()",
    "val lines = File(path).readLines()",
    "val buffered = File(path).bufferedReader().use { it.readText() }",
    "",
    "val lineList = mutableListOf<String>()",
    "File(path).useLines { lines -> lines.forEach { lineList.add(it) } }",
    "```",
    "",
    "### 파일 쓰기",
    "```kotlin",
    "File(path).writeText(\"Hello Kotlin\")",
    "File(path).appendText(\"\\nNew Line\")",
    "",
    "File(path).printWriter().use { out ->",
    "    out.println(\"First Line\")",
    "    out.println(\"Second Line\")",
    "}",
    "```",
    "",
    "### 콘솔 입출력",
    "```kotlin",
    "print(\"이름 입력: \")",
    "val name = readLine()!!",
    "val number = readLine()!!.toInt()",
    "```",
    "",
    "---",
    "### 요약",
    "- 5가지 스코프 함수: `let`(it/결과), `run`(this/결과), `with`(this/결과), `apply`(this/객체), `also`(it/객체)",
    "- `use`: Closeable 자동 해제",
    "- DSL 빌더: 수신 객체 람다(`T.() -> Unit`)로 선언적 코드 작성",
    "- 파일 I/O: `readText()`, `readLines()`, `writeText()`, `appendText()`"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
