<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-package-management",
  title: "리눅스 패키지 관리 - RPM, YUM/DNF, APT, 소스 컴파일 총정리",
  date: "2026-03-06",
  summary: "리눅스 패키지 관리의 모든 것을 정리합니다. RPM 설치·질의, YUM/DNF 저장소 관리, EPEL 확장 저장소, dpkg/APT(Debian 계열), 소스 컴파일 설치(configure→make→make install), 패키지 검증까지 실전 예제와 함께 설명합니다.",
  category: "Technology/Linux",
  tags: ["linux","rpm","yum","dnf","apt","dpkg","epel","package","compile","make"],
  content: [
    "## 한 줄 요약",
    "리눅스에서 소프트웨어를 설치·관리하는 방법은 크게 **패키지 매니저(RPM/YUM/APT)**와 **소스 컴파일** 두 가지입니다.",
    "",
    "---",
    "",
    "## 1. 패키지란?",
    "",
    "패키지는 소프트웨어의 **실행 파일, 설정 파일, 라이브러리, 문서 등을 하나로 묶은 설치 파일**입니다.",
    "",
    "| 배포판 계열 | 패키지 형식 | 저수준 도구 | 고수준 도구 |",
    "|------------|-----------|-----------|-----------|",
    "| **Red Hat** (CentOS, RHEL, Fedora, Rocky) | `.rpm` | `rpm` | `yum` / `dnf` |",
    "| **Debian** (Ubuntu, Debian, Mint) | `.deb` | `dpkg` | `apt-get` / `apt` |",
    "",
    "### 저수준 vs 고수준 도구",
    "| 구분 | 저수준 (rpm, dpkg) | 고수준 (yum, apt) |",
    "|------|-------------------|-------------------|",
    "| 의존성 해결 | **수동** (직접 설치) | **자동** |",
    "| 저장소 | 사용 안 함 (파일 직접 지정) | 저장소에서 자동 다운로드 |",
    "| 용도 | 개별 패키지 설치/질의 | 일반적인 설치/업데이트 |",
    "",
    "---",
    "",
    "## 2. RPM (Red Hat Package Manager)",
    "",
    "Red Hat 계열에서 사용하는 **저수준 패키지 관리** 도구입니다.",
    "",
    "### RPM 파일 이름 구조",
    "```",
    "httpd-2.4.6-97.el7.centos.x86_64.rpm",
    "│     │          │        │",
    "│     │          │        └ 아키텍처 (x86_64, i686, noarch)",
    "│     │          └ 배포판 (el7=RHEL 7, el8=RHEL 8)",
    "│     └ 버전-릴리스",
    "└ 패키지 이름",
    "```",
    "",
    "### 설치·업그레이드·삭제",
    "```bash",
    "rpm -ivh package.rpm           # 설치 (i:install, v:verbose, h:hash 진행률)",
    "rpm -Uvh package.rpm           # 업그레이드 (없으면 설치, U:upgrade)",
    "rpm -Fvh package.rpm           # 이미 설치된 경우만 업그레이드 (F:freshen)",
    "rpm -e package                 # 삭제 (e:erase, 패키지 이름만)",
    "rpm -e --nodeps package        # 의존성 무시하고 삭제 (비권장)",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `-i` | Install (설치) |",
    "| `-U` | Upgrade (업그레이드, 없으면 설치) |",
    "| `-F` | Freshen (이미 설치된 경우만 업그레이드) |",
    "| `-e` | Erase (삭제) |",
    "| `-v` | Verbose (상세 출력) |",
    "| `-h` | Hash (진행률 `#` 표시) |",
    "| `--nodeps` | 의존성 검사 무시 |",
    "| `--force` | 강제 설치 (덮어쓰기) |",
    "",
    "### 질의 (Query) - 시험 빈출!",
    "```bash",
    "# 설치된 패키지 질의",
    "rpm -qa                        # 설치된 전체 패키지 목록",
    "rpm -qa | grep httpd           # 특정 패키지 검색",
    "rpm -qi httpd                  # 패키지 상세 정보 (i:info)",
    "rpm -ql httpd                  # 패키지가 설치한 파일 목록 (l:list)",
    "rpm -qf /usr/bin/vim           # 파일이 속한 패키지 확인 (f:file)",
    "rpm -qc httpd                  # 설정 파일 목록 (c:config)",
    "rpm -qd httpd                  # 문서 파일 목록 (d:doc)",
    "rpm -qR httpd                  # 의존성 목록 (R:requires)",
    "",
    "# 미설치 RPM 파일 질의 (-p 추가)",
    "rpm -qip package.rpm           # 미설치 RPM 파일 정보",
    "rpm -qlp package.rpm           # 미설치 RPM 포함 파일 목록",
    "```",
    "",
    "### RPM 질의 옵션 정리",
    "| 옵션 | 의미 | 설명 |",
    "|------|------|------|",
    "| `-q` | Query | 질의 모드 |",
    "| `-a` | All | 설치된 모든 패키지 |",
    "| `-i` | Info | 패키지 상세 정보 |",
    "| `-l` | List | 설치된 파일 목록 |",
    "| `-f` | File | 파일이 속한 패키지 |",
    "| `-c` | Config | 설정 파일 목록 |",
    "| `-d` | Doc | 문서 파일 목록 |",
    "| `-R` | Requires | 의존성 목록 |",
    "| `-p` | Package file | 미설치 RPM 파일 대상 |",
    "",
    "### RPM 검증",
    "```bash",
    "rpm -V httpd                   # 설치 후 변경된 파일 검증",
    "rpm -Va                        # 모든 패키지 검증",
    "rpm --checksig package.rpm     # RPM 파일 서명 확인",
    "```",
    "",
    "검증 결과 코드:",
    "| 코드 | 의미 |",
    "|------|------|",
    "| `S` | 파일 크기 변경 |",
    "| `M` | 퍼미션 변경 |",
    "| `5` | MD5 체크섬 변경 (내용 변경) |",
    "| `T` | 수정 시간 변경 |",
    "| `U` | 소유자 변경 |",
    "| `G` | 그룹 변경 |",
    "",
    "---",
    "",
    "## 3. YUM / DNF (Red Hat 계열 고수준 도구)",
    "",
    "**의존성을 자동으로 해결**하며, 인터넷 **저장소(Repository)**에서 패키지를 다운로드·설치합니다.",
    "",
    "- **YUM**: CentOS 7, RHEL 7 이하",
    "- **DNF**: CentOS 8+, RHEL 8+, Fedora (YUM의 후속, 명령어 형식 동일)",
    "",
    "### 기본 사용법",
    "```bash",
    "# 설치",
    "yum install httpd              # 패키지 설치 (의존성 자동 해결)",
    "yum install httpd -y           # 확인 없이 설치",
    "",
    "# 업데이트",
    "yum update httpd               # 특정 패키지 업데이트",
    "yum update                     # 시스템 전체 업데이트",
    "yum check-update               # 업데이트 가능 패키지 확인",
    "",
    "# 삭제",
    "yum remove httpd               # 패키지 삭제",
    "",
    "# 검색·정보",
    "yum search keyword             # 패키지 검색",
    "yum info httpd                 # 패키지 정보",
    "yum list installed             # 설치된 패키지 목록",
    "yum list available             # 설치 가능한 패키지 목록",
    "",
    "# 그룹",
    "yum grouplist                  # 패키지 그룹 목록",
    "yum groupinstall 'Development Tools'  # 그룹 설치",
    "yum groupremove 'Development Tools'   # 그룹 삭제",
    "",
    "# 기타",
    "yum provides /usr/bin/vim      # 파일을 제공하는 패키지 검색",
    "yum history                    # 설치/삭제 이력 확인",
    "yum clean all                  # 캐시 삭제",
    "yum repolist                   # 활성화된 저장소 목록",
    "```",
    "",
    "### YUM 저장소 설정",
    "저장소 설정 파일은 `/etc/yum.repos.d/` 디렉터리에 `.repo` 파일로 관리됩니다.",
    "",
    "```ini",
    "# /etc/yum.repos.d/CentOS-Base.repo 예시",
    "[base]",
    "name=CentOS-$releasever - Base",
    "baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/",
    "gpgcheck=1",
    "gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7",
    "enabled=1",
    "```",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| `[base]` | 저장소 ID |",
    "| `name` | 저장소 이름 |",
    "| `baseurl` | 패키지 저장소 URL |",
    "| `gpgcheck` | GPG 서명 검증 여부 (1=예, 0=아니오) |",
    "| `gpgkey` | GPG 키 파일 경로 |",
    "| `enabled` | 저장소 활성화 여부 (1=활성, 0=비활성) |",
    "",
    "### EPEL 저장소 (확장 패키지 저장소)",
    "**EPEL(Extra Packages for Enterprise Linux)**은 CentOS/RHEL에서 기본 제공하지 않는 추가 패키지를 설치할 수 있는 확장 저장소입니다.",
    "",
    "```bash",
    "# EPEL 저장소 설치 (시험 빈출!)",
    "yum install epel-release",
    "",
    "# 설치 후 저장소 설정 파일이 추가됨",
    "ls /etc/yum.repos.d/epel*",
    "",
    "# EPEL 저장소의 패키지 설치 가능",
    "yum --enablerepo=epel install nginx",
    "```",
    "",
    "`epel-release` 패키지는 EPEL 저장소의 **GPG 키와 저장소 설정 파일**을 설치합니다. 이후부터 EPEL에 포함된 패키지를 `yum install`로 설치할 수 있습니다.",
    "",
    "### DNF (YUM 후속)",
    "```bash",
    "# DNF는 YUM과 명령어가 거의 동일",
    "dnf install httpd",
    "dnf update",
    "dnf remove httpd",
    "dnf search keyword",
    "dnf info httpd",
    "dnf list installed",
    "dnf repolist",
    "dnf clean all",
    "",
    "# DNF 추가 기능",
    "dnf module list                # 모듈 스트림 목록 (AppStream)",
    "dnf module install nodejs:16   # 특정 버전 스트림 설치",
    "dnf autoremove                 # 불필요한 의존 패키지 제거",
    "```",
    "",
    "---",
    "",
    "## 4. dpkg (Debian 계열 저수준 도구)",
    "",
    "```bash",
    "# 설치·삭제",
    "dpkg -i package.deb            # 설치 (i:install)",
    "dpkg -r package                # 삭제 (설정 파일 유지)",
    "dpkg -P package                # 완전 삭제 (설정 파일 포함, P:purge)",
    "",
    "# 질의",
    "dpkg -l                        # 설치된 패키지 목록",
    "dpkg -l | grep nginx           # 특정 패키지 검색",
    "dpkg -L package                # 패키지가 설치한 파일 목록",
    "dpkg -S /usr/bin/vim           # 파일이 속한 패키지 확인",
    "dpkg -s package                # 패키지 상태·정보",
    "dpkg -c package.deb            # 미설치 deb 파일 내용 확인",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `-i` | Install (설치) |",
    "| `-r` | Remove (삭제, 설정 유지) |",
    "| `-P` | Purge (완전 삭제) |",
    "| `-l` | List (설치된 패키지 목록) |",
    "| `-L` | List files (패키지의 파일 목록) |",
    "| `-S` | Search (파일이 속한 패키지) |",
    "| `-s` | Status (패키지 정보) |",
    "",
    "---",
    "",
    "## 5. APT (Debian 계열 고수준 도구)",
    "",
    "`apt-get` / `apt-cache`를 통합한 `apt` 명령어를 주로 사용합니다.",
    "",
    "```bash",
    "# 저장소 목록 갱신 (설치 전 필수!)",
    "apt update                     # = apt-get update",
    "",
    "# 설치",
    "apt install nginx              # = apt-get install nginx",
    "apt install nginx -y           # 확인 없이 설치",
    "",
    "# 업그레이드",
    "apt upgrade                    # 설치된 패키지 업그레이드",
    "apt full-upgrade               # 의존성 변경 포함 업그레이드",
    "apt dist-upgrade               # 배포판 업그레이드",
    "",
    "# 삭제",
    "apt remove nginx               # 삭제 (설정 파일 유지)",
    "apt purge nginx                # 완전 삭제 (설정 포함)",
    "apt autoremove                 # 불필요한 의존 패키지 삭제",
    "",
    "# 검색·정보",
    "apt search keyword             # = apt-cache search keyword",
    "apt show nginx                 # = apt-cache show nginx",
    "apt list --installed           # 설치된 패키지 목록",
    "apt list --upgradable          # 업그레이드 가능 패키지",
    "```",
    "",
    "### APT 저장소 설정",
    "```bash",
    "# 저장소 목록 파일",
    "cat /etc/apt/sources.list",
    "ls /etc/apt/sources.list.d/",
    "",
    "# PPA 저장소 추가 (Ubuntu)",
    "add-apt-repository ppa:user/repo",
    "apt update",
    "```",
    "",
    "### apt-get vs apt",
    "| apt-get / apt-cache | apt | 설명 |",
    "|---------------------|-----|------|",
    "| `apt-get install` | `apt install` | 패키지 설치 |",
    "| `apt-get remove` | `apt remove` | 패키지 삭제 |",
    "| `apt-get update` | `apt update` | 저장소 갱신 |",
    "| `apt-get upgrade` | `apt upgrade` | 업그레이드 |",
    "| `apt-cache search` | `apt search` | 패키지 검색 |",
    "| `apt-cache show` | `apt show` | 패키지 정보 |",
    "",
    "`apt`는 `apt-get`/`apt-cache`의 통합 버전으로, 진행률 표시 등 사용자 친화적 기능이 추가되었습니다.",
    "",
    "---",
    "",
    "## 6. 소스 컴파일 설치",
    "",
    "패키지 매니저에 없는 소프트웨어나, 특정 옵션을 지정하여 설치할 때 소스 코드를 직접 컴파일합니다.",
    "",
    "### 설치 흐름",
    "```bash",
    "# 1. 소스 코드 다운로드 및 압축 해제",
    "wget https://example.com/package-1.0.tar.gz",
    "tar xvfz package-1.0.tar.gz",
    "cd package-1.0",
    "",
    "# 2. 환경 설정 (Makefile 생성)",
    "./configure",
    "./configure --prefix=/usr/local/package    # 설치 경로 지정",
    "",
    "# 3. 컴파일",
    "make",
    "",
    "# 4. 설치",
    "make install",
    "",
    "# (선택) 설치 파일 정리",
    "make clean",
    "```",
    "",
    "### 각 단계 설명",
    "| 단계 | 명령어 | 설명 |",
    "|------|--------|------|",
    "| 1 | `tar xvfz` | 소스 코드 압축 해제 |",
    "| 2 | `./configure` | 시스템 환경 확인, Makefile 생성 |",
    "| 3 | `make` | 소스 코드 컴파일 (바이너리 생성) |",
    "| 4 | `make install` | 컴파일된 파일을 시스템에 설치 |",
    "| - | `make clean` | 컴파일 중간 파일 삭제 |",
    "",
    "### configure 주요 옵션",
    "```bash",
    "./configure --prefix=/usr/local/nginx      # 설치 경로",
    "./configure --with-http_ssl_module          # 추가 모듈 포함",
    "./configure --without-debug                 # 디버그 제외",
    "./configure --help                          # 사용 가능한 옵션 확인",
    "```",
    "",
    "### 컴파일 전 필수 패키지",
    "소스 컴파일에 필요한 개발 도구를 먼저 설치해야 합니다.",
    "",
    "```bash",
    "# CentOS/RHEL",
    "yum groupinstall 'Development Tools'",
    "yum install gcc gcc-c++ make",
    "",
    "# Ubuntu/Debian",
    "apt install build-essential",
    "```",
    "",
    "---",
    "",
    "## 7. Red Hat vs Debian 계열 비교",
    "",
    "| 항목 | Red Hat 계열 | Debian 계열 |",
    "|------|-------------|-------------|",
    "| 패키지 형식 | `.rpm` | `.deb` |",
    "| 저수준 도구 | `rpm` | `dpkg` |",
    "| 고수준 도구 | `yum` / `dnf` | `apt-get` / `apt` |",
    "| 저장소 설정 | `/etc/yum.repos.d/*.repo` | `/etc/apt/sources.list` |",
    "| 전체 설치 | `rpm -ivh` | `dpkg -i` |",
    "| 전체 목록 | `rpm -qa` | `dpkg -l` |",
    "| 파일 → 패키지 | `rpm -qf /path` | `dpkg -S /path` |",
    "| 패키지 검색 | `yum search` | `apt search` |",
    "| 의존성 설치 | `yum install` | `apt install` |",
    "| 업데이트 | `yum update` | `apt update && apt upgrade` |",
    "| 삭제 | `yum remove` | `apt remove` / `apt purge` |",
    "| 확장 저장소 | EPEL (`epel-release`) | PPA (`add-apt-repository`) |",
    "",
    "---",
    "",
    "## 8. 패키지 관리 실전 예제",
    "",
    "### 웹 서버(Apache) 설치",
    "```bash",
    "# CentOS/RHEL",
    "yum install httpd -y",
    "systemctl start httpd",
    "systemctl enable httpd",
    "",
    "# Ubuntu/Debian",
    "apt update",
    "apt install apache2 -y",
    "systemctl start apache2",
    "systemctl enable apache2",
    "```",
    "",
    "### 설치된 패키지 확인",
    "```bash",
    "# CentOS/RHEL",
    "rpm -qa | grep httpd",
    "rpm -qi httpd",
    "rpm -ql httpd | head",
    "",
    "# Ubuntu/Debian",
    "dpkg -l | grep apache",
    "dpkg -L apache2 | head",
    "```",
    "",
    "### 특정 파일이 어느 패키지에 속하는지",
    "```bash",
    "# CentOS/RHEL",
    "rpm -qf /usr/sbin/httpd",
    "",
    "# Ubuntu/Debian",
    "dpkg -S /usr/sbin/apache2",
    "```",
    "",
    "### 불필요한 패키지 정리",
    "```bash",
    "# CentOS/RHEL",
    "yum autoremove",
    "yum clean all",
    "",
    "# Ubuntu/Debian",
    "apt autoremove",
    "apt clean",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "- **RPM**: Red Hat 계열 저수준 도구, `-ivh`(설치), `-Uvh`(업그레이드), `-e`(삭제), `-qa`(전체 목록), `-qi`(정보), `-ql`(파일 목록), `-qf`(파일→패키지)",
    "- **YUM/DNF**: 고수준 도구, 의존성 자동 해결, `install`/`update`/`remove`/`search`/`info`",
    "- **EPEL**: `yum install epel-release`로 확장 저장소 추가",
    "- **dpkg**: Debian 계열 저수준 도구, `-i`(설치), `-r`(삭제), `-l`(목록), `-L`(파일), `-S`(검색)",
    "- **APT**: Debian 계열 고수준 도구, `update`(저장소 갱신) → `install`/`upgrade`/`remove`",
    "- **소스 컴파일**: `tar` → `./configure` → `make` → `make install`",
    "- **Red Hat vs Debian**: rpm/yum vs dpkg/apt, .repo vs sources.list"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
