<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-process-management",
  title: "리눅스 프로세스 관리",
  date: "2026-03-07",
  summary: "리눅스 프로세스의 개념, 상태, ps·top·kill 명령어, 시그널, 포그라운드/백그라운드 실행, 데몬, 우선순위(nice/renice), 작업 스케줄링(cron/at)까지 프로세스 관리의 핵심을 정리합니다.",
  category: "Technology/Linux",
  tags: ["linux","process","ps","top","kill","signal","daemon","cron","nice","nohup"],
  content: [
    "## 한 줄 요약",
    "프로세스는 **실행 중인 프로그램**이며, 리눅스에서 `ps`, `top`, `kill` 등의 명령어로 조회·관리합니다.",
    "",
    "---",
    "",
    "## 1. 프로세스란?",
    "",
    "**프로그램**은 디스크에 저장된 실행 파일이고, **프로세스**는 그 프로그램이 메모리에 로드되어 실행 중인 상태입니다.",
    "",
    "| 구분 | 프로그램 | 프로세스 |",
    "|------|---------|---------|",
    "| 상태 | 디스크에 저장 (정적) | 메모리에서 실행 중 (동적) |",
    "| 예시 | `/usr/bin/vim` 파일 | vim으로 파일 편집 중인 상태 |",
    "| 식별 | 파일 경로 | **PID** (Process ID) |",
    "",
    "### 프로세스의 주요 속성",
    "| 속성 | 설명 |",
    "|------|------|",
    "| **PID** | 프로세스 고유 번호 |",
    "| **PPID** | 부모 프로세스 ID |",
    "| **UID** | 프로세스를 실행한 사용자 ID |",
    "| **상태** | Running, Sleeping, Stopped, Zombie 등 |",
    "| **우선순위** | nice 값 (-20 ~ 19) |",
    "",
    "### 프로세스 계층 구조",
    "리눅스의 모든 프로세스는 **부모-자식 관계**의 트리 구조를 형성합니다.",
    "",
    "```",
    "systemd (PID 1)",
    "├── sshd",
    "│   └── bash",
    "│       └── vim",
    "├── httpd",
    "│   ├── httpd (worker)",
    "│   └── httpd (worker)",
    "├── crond",
    "└── rsyslogd",
    "```",
    "",
    "- **PID 1**: `systemd` (또는 `init`) — 모든 프로세스의 최상위 부모",
    "- 부모 프로세스가 종료되면 자식 프로세스는 `systemd`가 인수",
    "",
    "---",
    "",
    "## 2. 프로세스 상태",
    "",
    "| 상태 | 코드 | 설명 |",
    "|------|------|------|",
    "| **Running** | R | 실행 중이거나 실행 대기 |",
    "| **Sleeping** | S | 이벤트 대기 (인터럽트 가능) |",
    "| **Sleeping** | D | I/O 대기 (인터럽트 불가) |",
    "| **Stopped** | T | 중지됨 (Ctrl+Z 또는 SIGSTOP) |",
    "| **Zombie** | Z | 종료되었지만 부모가 아직 회수하지 않은 상태 |",
    "",
    "```",
    "생성 → Ready(실행 대기) → Running(실행 중) → Terminated(종료)",
    "                ↑              ↓",
    "                └── Sleeping(대기) / Stopped(중지)",
    "```",
    "",
    "### 좀비 프로세스",
    "자식 프로세스가 종료되었지만 부모가 `wait()`를 호출하지 않아 프로세스 테이블에 남아 있는 상태입니다. 좀비가 쌓이면 PID가 고갈될 수 있습니다.",
    "",
    "```bash",
    "# 좀비 프로세스 확인",
    "ps aux | grep Z",
    "```",
    "",
    "---",
    "",
    "## 3. 프로세스 조회 명령어",
    "",
    "### ps (Process Status)",
    "```bash",
    "ps                     # 현재 터미널의 프로세스",
    "ps -e                  # 모든 프로세스",
    "ps -f                  # 풀 포맷 (PPID, UID 포함)",
    "ps -ef                 # 모든 프로세스 풀 포맷 (가장 많이 사용)",
    "ps aux                 # BSD 스타일 (CPU, MEM 사용률 포함)",
    "ps -ef | grep httpd    # 특정 프로세스 검색",
    "ps -u haru             # 특정 사용자의 프로세스",
    "ps -p 1234             # 특정 PID 조회",
    "```",
    "",
    "### ps -ef 출력 필드",
    "```",
    "UID   PID  PPID  C STIME TTY     TIME     CMD",
    "root    1     0  0 10:00 ?       00:00:02 /usr/lib/systemd/systemd",
    "haru 1234  1100  0 10:05 pts/0   00:00:00 bash",
    "```",
    "",
    "| 필드 | 설명 |",
    "|------|------|",
    "| UID | 프로세스 소유자 |",
    "| PID | 프로세스 ID |",
    "| PPID | 부모 프로세스 ID |",
    "| C | CPU 사용률 |",
    "| STIME | 시작 시간 |",
    "| TTY | 터미널 (? = 터미널 없음, 데몬) |",
    "| TIME | 누적 CPU 시간 |",
    "| CMD | 실행 명령어 |",
    "",
    "### ps aux 출력 필드",
    "```",
    "USER  PID %CPU %MEM   VSZ   RSS TTY  STAT START TIME COMMAND",
    "root    1  0.0  0.1 16940  4500 ?    Ss   10:00 0:02 /usr/lib/systemd/systemd",
    "```",
    "",
    "| 필드 | 설명 |",
    "|------|------|",
    "| %CPU | CPU 사용률 |",
    "| %MEM | 메모리 사용률 |",
    "| VSZ | 가상 메모리 크기 |",
    "| RSS | 실제 메모리 사용량 |",
    "| STAT | 프로세스 상태 (R, S, D, T, Z 등) |",
    "",
    "### top (실시간 모니터링)",
    "프로세스를 **실시간으로** 모니터링합니다.",
    "",
    "```bash",
    "top                    # 실시간 프로세스 목록",
    "top -d 3               # 3초 간격으로 갱신",
    "top -u haru            # 특정 사용자 프로세스만",
    "top -p 1234            # 특정 PID만 모니터링",
    "```",
    "",
    "### top 실행 중 단축키",
    "| 키 | 기능 |",
    "|----|------|",
    "| `P` | **CPU 사용률** 순 정렬 |",
    "| `M` | **메모리 사용률** 순 정렬 |",
    "| `T` | 누적 시간 순 정렬 |",
    "| `k` | 프로세스 kill (PID 입력) |",
    "| `r` | renice (우선순위 변경) |",
    "| `1` | CPU 코어별 사용률 표시 |",
    "| `q` | 종료 |",
    "",
    "### pstree (프로세스 트리)",
    "```bash",
    "pstree                 # 프로세스 트리 구조",
    "pstree -p              # PID 포함",
    "pstree -u haru         # 특정 사용자 기준",
    "```",
    "",
    "### 기타 조회 명령어",
    "```bash",
    "pgrep httpd            # 이름으로 PID 검색",
    "pgrep -u haru          # 사용자의 프로세스 PID",
    "pidof nginx            # 이름으로 PID 조회",
    "uptime                 # 시스템 가동 시간, 로드 평균",
    "free -h                # 메모리 사용량",
    "```",
    "",
    "---",
    "",
    "## 4. 프로세스 종료 (kill)",
    "",
    "### kill 명령어",
    "```bash",
    "kill PID               # SIGTERM (15) 전송 - 정상 종료 요청",
    "kill -9 PID            # SIGKILL (9) - 강제 종료",
    "kill -1 PID            # SIGHUP (1) - 재시작",
    "kill -15 PID           # SIGTERM (15) - 정상 종료 (기본값)",
    "kill -l                # 사용 가능한 시그널 목록",
    "```",
    "",
    "### killall / pkill",
    "```bash",
    "killall httpd          # 이름으로 모든 해당 프로세스 종료",
    "killall -9 httpd       # 강제 종료",
    "pkill -u haru          # 사용자의 모든 프로세스 종료",
    "pkill -f \"python app\"  # 명령어 전체 문자열로 검색 후 종료",
    "```",
    "",
    "### 주요 시그널",
    "| 번호 | 이름 | 설명 | 기본 동작 |",
    "|------|------|------|-----------|",
    "| 1 | **SIGHUP** | Hangup (재시작) | 종료 |",
    "| 2 | **SIGINT** | Interrupt (Ctrl+C) | 종료 |",
    "| 9 | **SIGKILL** | 강제 종료 (**무시 불가**) | 종료 |",
    "| 15 | **SIGTERM** | 정상 종료 요청 (기본값) | 종료 |",
    "| 18 | **SIGCONT** | 중지된 프로세스 재개 | 계속 |",
    "| 19 | **SIGSTOP** | 프로세스 일시 중지 (**무시 불가**) | 중지 |",
    "| 20 | **SIGTSTP** | 터미널 중지 (Ctrl+Z) | 중지 |",
    "",
    "**SIGKILL(9)**과 **SIGSTOP(19)**은 프로세스가 가로챌 수 없는 시그널입니다. 나머지는 프로세스가 핸들러를 등록하여 처리할 수 있습니다.",
    "",
    "---",
    "",
    "## 5. 포그라운드 / 백그라운드",
    "",
    "| 구분 | 설명 |",
    "|------|------|",
    "| **포그라운드(FG)** | 터미널을 점유하고 실행. 다른 명령 입력 불가 |",
    "| **백그라운드(BG)** | 터미널을 점유하지 않고 뒤에서 실행 |",
    "",
    "```bash",
    "# 백그라운드 실행",
    "command &              # 명령어 뒤에 &",
    "sleep 100 &            # 예시",
    "",
    "# 작업 목록 확인",
    "jobs                   # 현재 셸의 작업 목록",
    "jobs -l                # PID 포함",
    "",
    "# 전환",
    "Ctrl+Z                 # 포그라운드 → 중지(Stopped)",
    "bg %1                  # 중지된 작업 1번을 백그라운드로 재개",
    "fg %1                  # 작업 1번을 포그라운드로 가져옴",
    "",
    "# 실행 흐름 예시",
    "sleep 300              # 포그라운드 실행 (터미널 점유)",
    "  Ctrl+Z               # 중지 [1]+ Stopped",
    "  bg %1                # 백그라운드로 전환 [1]+ Running",
    "  fg %1                # 다시 포그라운드로",
    "```",
    "",
    "### nohup (터미널 종료 후에도 실행 유지)",
    "터미널(SSH 세션)을 닫아도 프로세스가 종료되지 않게 합니다.",
    "",
    "```bash",
    "nohup command &                      # 기본 사용",
    "nohup ./server.sh &                  # 서버 스크립트 실행",
    "nohup command > output.log 2>&1 &    # 출력을 파일로 리다이렉션",
    "```",
    "",
    "nohup은 **SIGHUP 시그널을 무시**하도록 설정합니다. 터미널이 닫힐 때 SIGHUP이 전송되는데, 이를 무시하여 프로세스가 계속 실행됩니다.",
    "",
    "---",
    "",
    "## 6. 데몬 (Daemon)",
    "",
    "**데몬**은 백그라운드에서 지속적으로 실행되는 서비스 프로세스입니다. 터미널 없이 동작하며, 보통 시스템 부팅 시 자동으로 시작됩니다.",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| 이름 | 보통 `d`로 끝남 (httpd, sshd, crond 등) |",
    "| 터미널 | 없음 (TTY가 `?`) |",
    "| 시작 | systemd에 의해 관리 |",
    "| 실행 | 백그라운드 상주 |",
    "",
    "### systemctl (데몬 관리)",
    "```bash",
    "systemctl start httpd       # 서비스 시작",
    "systemctl stop httpd        # 서비스 중지",
    "systemctl restart httpd     # 재시작",
    "systemctl reload httpd      # 설정 다시 읽기 (중단 없이)",
    "systemctl status httpd      # 상태 확인",
    "systemctl enable httpd      # 부팅 시 자동 시작",
    "systemctl disable httpd     # 자동 시작 해제",
    "systemctl is-active httpd   # 실행 중인지 확인",
    "systemctl is-enabled httpd  # 자동 시작 설정 여부",
    "systemctl list-unit-files --type=service  # 모든 서비스 목록",
    "```",
    "",
    "---",
    "",
    "## 7. 우선순위 (nice / renice)",
    "",
    "리눅스 프로세스에는 **nice 값**이라는 우선순위가 있습니다.",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| 범위 | **-20** (최고 우선) ~ **19** (최저 우선) |",
    "| 기본값 | 0 |",
    "| 권한 | 낮추기(숫자 올리기): 일반 사용자 / 높이기(숫자 내리기): **root만** |",
    "",
    "```bash",
    "# nice: 새 프로세스를 특정 우선순위로 실행",
    "nice -n 10 command          # 우선순위 낮춰서(10) 실행",
    "nice -n -5 command          # 우선순위 높여서(-5) 실행 (root만)",
    "nice command                # 기본 nice 값 10으로 실행",
    "",
    "# renice: 실행 중인 프로세스 우선순위 변경",
    "renice 5 -p 1234            # PID 1234의 우선순위를 5로 변경",
    "renice -5 -p 1234           # PID 1234의 우선순위를 -5로 (root만)",
    "renice 10 -u haru           # 사용자 haru의 모든 프로세스를 10으로",
    "",
    "# 현재 nice 값 확인",
    "ps -eo pid,ni,comm          # nice 값(NI) 포함 출력",
    "top                         # NI 컬럼에서 확인",
    "```",
    "",
    "---",
    "",
    "## 8. 작업 스케줄링",
    "",
    "### crontab (주기적 반복 실행)",
    "```bash",
    "crontab -e               # 편집 (현재 사용자)",
    "crontab -l               # 목록 조회",
    "crontab -r               # 전체 삭제",
    "crontab -u haru -l       # 특정 사용자 조회 (root)",
    "```",
    "",
    "### cron 필드 형식",
    "```",
    "분  시  일  월  요일  명령어",
    "┬   ┬   ┬   ┬   ┬",
    "│   │   │   │   └─ 요일 (0-7, 0과 7은 일요일)",
    "│   │   │   └───── 월 (1-12)",
    "│   │   └───────── 일 (1-31)",
    "│   └───────────── 시 (0-23)",
    "└─────────────────  분 (0-59)",
    "```",
    "",
    "### crontab 예제",
    "```bash",
    "# 매일 새벽 3시에 백업",
    "0 3 * * * /root/backup.sh",
    "",
    "# 매주 월요일 오전 6시 30분",
    "30 6 * * 1 /usr/local/bin/weekly.sh",
    "",
    "# 5분마다 실행",
    "*/5 * * * * /root/check.sh",
    "",
    "# 월~금 오전 9시~오후 6시 매시 실행",
    "0 9-18 * * 1-5 /root/work.sh",
    "",
    "# 매월 1일, 15일 자정",
    "0 0 1,15 * * /root/monthly.sh",
    "",
    "# 매일 오후 11시에 7일 이상 된 임시파일 삭제",
    "0 23 * * * /usr/bin/find /tmp -mtime +7 -delete",
    "```",
    "",
    "### cron 접근 제어",
    "| 파일 | 설명 |",
    "|------|------|",
    "| `/etc/cron.allow` | 목록에 있는 사용자만 사용 가능 |",
    "| `/etc/cron.deny` | 목록에 있는 사용자만 사용 불가 |",
    "",
    "- 두 파일 모두 없으면: **root만** 사용 가능",
    "- `cron.allow`가 있으면: 해당 파일 사용자만 허용",
    "- `cron.allow` 없고 `cron.deny`만 있으면: deny에 없는 사용자 허용",
    "",
    "### at (1회성 예약 실행)",
    "```bash",
    "at 3:00 AM tomorrow         # 내일 새벽 3시에 실행",
    "at> /root/backup.sh",
    "at> Ctrl+D                  # 입력 완료",
    "",
    "at now + 30 minutes         # 30분 후 실행",
    "at 10:00 PM                 # 오늘 오후 10시",
    "",
    "atq                         # 예약된 작업 목록",
    "atrm 1                      # 작업 번호 1 삭제",
    "```",
    "",
    "| 비교 | cron | at |",
    "|------|------|-----|",
    "| 실행 횟수 | 반복 | 1회 |",
    "| 관리 명령 | crontab -e/-l/-r | at / atq / atrm |",
    "| 접근 제어 | cron.allow / cron.deny | at.allow / at.deny |",
    "",
    "---",
    "",
    "## 9. 유용한 프로세스 관련 명령어",
    "",
    "```bash",
    "# 프로세스 실행 시간 측정",
    "time command",
    "",
    "# 특정 프로세스의 시스템 콜 추적",
    "strace -p PID",
    "",
    "# 프로세스가 열고 있는 파일 확인",
    "lsof -p PID",
    "",
    "# 특정 포트를 사용 중인 프로세스",
    "lsof -i :80",
    "ss -tlnp | grep :80",
    "",
    "# 프로세스 메모리 맵",
    "pmap PID",
    "",
    "# /proc에서 프로세스 정보 직접 확인",
    "cat /proc/PID/status       # 프로세스 상태 정보",
    "cat /proc/PID/cmdline      # 실행 명령어",
    "ls -l /proc/PID/fd/        # 열려 있는 파일 디스크립터",
    "```",
    "",
    "---",
    "### 요약",
    "- **프로세스**: 실행 중인 프로그램, PID로 식별",
    "- **조회**: `ps -ef` (전체), `ps aux` (CPU/MEM 포함), `top` (실시간), `pstree` (트리)",
    "- **종료**: `kill PID` (SIGTERM), `kill -9 PID` (SIGKILL 강제), `killall`/`pkill` (이름)",
    "- **시그널**: SIGHUP(1), SIGINT(2), SIGKILL(9), SIGTERM(15), SIGSTOP(19)",
    "- **포그라운드/백그라운드**: `&`, `jobs`, `fg`, `bg`, `Ctrl+Z`",
    "- **nohup**: 터미널 종료 후에도 실행 유지",
    "- **데몬**: 백그라운드 서비스 프로세스, `systemctl`로 관리",
    "- **우선순위**: `nice` (실행 시 설정), `renice` (실행 중 변경), -20(최고)~19(최저)",
    "- **스케줄링**: `cron` (반복), `at` (1회)"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
