<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-shell-script",
  title: "리눅스 셸 스크립트 - 기초부터 실전까지",
  date: "2026-03-01",
  summary: "셸 스크립트의 기본 구조, 변수, 조건문(if/case), 반복문(for/while), 함수, 매개변수 처리, 문자열·배열 조작, 파일 테스트, 정규표현식, 실전 예제까지 Bash 셸 스크립트를 정리합니다.",
  category: "Technology/Linux",
  tags: ["linux","shell","bash","script","if","for","while","function","variable","awk","sed"],
  content: [
    "## 한 줄 요약",
    "셸 스크립트는 리눅스 명령어들을 **파일에 모아 자동으로 실행**하는 프로그램입니다.",
    "",
    "---",
    "",
    "## 1. 셸 스크립트란?",
    "",
    "셸(Shell)은 사용자의 명령을 해석하여 커널에 전달하는 **명령어 해석기**입니다. 셸 스크립트는 이 셸 명령어들을 파일에 작성하여 **일괄 실행**하는 프로그램입니다.",
    "",
    "### 셸 종류",
    "| 셸 | 경로 | 설명 |",
    "|------|------|------|",
    "| **Bash** | `/bin/bash` | 리눅스 기본 셸, 가장 많이 사용 |",
    "| Bourne Shell | `/bin/sh` | 최초의 유닉스 셸 |",
    "| C Shell | `/bin/csh` | C 언어 문법과 유사 |",
    "| Korn Shell | `/bin/ksh` | Bourne + C Shell 장점 결합 |",
    "| Z Shell | `/bin/zsh` | 고급 자동완성, 플러그인 |",
    "",
    "```bash",
    "echo $SHELL              # 현재 사용 중인 셸",
    "cat /etc/shells          # 사용 가능한 셸 목록",
    "chsh -s /bin/zsh         # 기본 셸 변경",
    "```",
    "",
    "### 첫 번째 스크립트",
    "```bash",
    "#!/bin/bash",
    "echo \"Hello, Shell Script!\"",
    "```",
    "",
    "```bash",
    "# 실행 방법",
    "chmod +x hello.sh        # 실행 권한 부여",
    "./hello.sh               # 방법 1: 직접 실행",
    "bash hello.sh            # 방법 2: bash로 실행 (권한 불필요)",
    "```",
    "",
    "첫 줄의 `#!/bin/bash`는 **셔뱅(Shebang)**이라고 하며, 이 스크립트를 어떤 셸로 실행할지 지정합니다.",
    "",
    "---",
    "",
    "## 2. 변수",
    "",
    "### 변수 선언과 사용",
    "```bash",
    "#!/bin/bash",
    "",
    "# 변수 선언 (= 앞뒤에 공백 없음!)",
    "NAME=\"haru\"",
    "AGE=25",
    "TODAY=$(date +%Y-%m-%d)        # 명령어 결과를 변수에 저장",
    "FILES=`ls /home`               # 백틱도 가능 ($(...)을 권장)",
    "",
    "# 변수 사용 ($변수명)",
    "echo \"이름: $NAME\"",
    "echo \"나이: ${AGE}세\"           # 중괄호로 명확하게",
    "echo \"오늘: $TODAY\"",
    "```",
    "",
    "**주의**: `NAME = \"haru\"`처럼 `=` 앞뒤에 공백을 넣으면 에러가 발생합니다.",
    "",
    "### 변수 종류",
    "| 종류 | 설명 | 예시 |",
    "|------|------|------|",
    "| 지역 변수 | 현재 셸에서만 유효 | `NAME=\"haru\"` |",
    "| 환경 변수 | 자식 프로세스에도 전달 | `export NAME=\"haru\"` |",
    "| 특수 변수 | 셸이 자동으로 설정 | `$0`, `$1`, `$?`, `$$` 등 |",
    "",
    "### 주요 환경 변수",
    "```bash",
    "echo $HOME               # 홈 디렉터리",
    "echo $USER               # 현재 사용자",
    "echo $PATH               # 명령어 검색 경로",
    "echo $PWD                # 현재 작업 디렉터리",
    "echo $SHELL              # 현재 셸",
    "echo $HOSTNAME           # 호스트명",
    "echo $LANG               # 언어 설정",
    "echo $RANDOM             # 랜덤 숫자 (0~32767)",
    "```",
    "",
    "### 특수 변수 (매개변수)",
    "| 변수 | 설명 |",
    "|------|------|",
    "| `$0` | 스크립트 파일명 |",
    "| `$1`, `$2`, ... | 첫 번째, 두 번째 인자 |",
    "| `$#` | 인자 개수 |",
    "| `$@` | 모든 인자 (개별 문자열) |",
    "| `$*` | 모든 인자 (하나의 문자열) |",
    "| `$?` | 이전 명령어의 종료 상태 (0=성공) |",
    "| `$$` | 현재 프로세스 PID |",
    "| `$!` | 마지막 백그라운드 프로세스 PID |",
    "",
    "```bash",
    "#!/bin/bash",
    "echo \"스크립트: $0\"",
    "echo \"인자 수: $#\"",
    "echo \"첫 번째 인자: $1\"",
    "echo \"두 번째 인자: $2\"",
    "echo \"모든 인자: $@\"",
    "",
    "# 실행: ./script.sh hello world",
    "# 스크립트: ./script.sh",
    "# 인자 수: 2",
    "# 첫 번째 인자: hello",
    "# 두 번째 인자: world",
    "# 모든 인자: hello world",
    "```",
    "",
    "### 읽기 전용 변수 / 변수 삭제",
    "```bash",
    "readonly PI=3.14         # 읽기 전용 (변경 불가)",
    "unset NAME               # 변수 삭제 (readonly는 삭제 불가)",
    "```",
    "",
    "---",
    "",
    "## 3. 입력 받기 (read)",
    "",
    "```bash",
    "#!/bin/bash",
    "echo -n \"이름을 입력하세요: \"",
    "read NAME",
    "echo \"안녕하세요, ${NAME}님!\"",
    "",
    "# 여러 변수 동시 입력",
    "echo -n \"이름과 나이: \"",
    "read NAME AGE",
    "echo \"${NAME}, ${AGE}세\"",
    "",
    "# -p: 프롬프트와 함께",
    "read -p \"계속할까요? (y/n): \" ANSWER",
    "",
    "# -s: 입력 숨기기 (비밀번호)",
    "read -sp \"비밀번호: \" PASSWORD",
    "echo",
    "",
    "# -t: 타임아웃 (5초)",
    "read -t 5 -p \"5초 안에 입력: \" INPUT",
    "```",
    "",
    "---",
    "",
    "## 4. 산술 연산",
    "",
    "```bash",
    "#!/bin/bash",
    "",
    "# 방법 1: $(( )) - 권장",
    "A=10",
    "B=3",
    "echo $((A + B))          # 13",
    "echo $((A - B))          # 7",
    "echo $((A * B))          # 30",
    "echo $((A / B))          # 3 (정수 나눗셈)",
    "echo $((A % B))          # 1 (나머지)",
    "echo $((A ** 2))         # 100 (거듭제곱)",
    "",
    "# 방법 2: expr (공백 필수, * 앞에 \\)",
    "expr $A + $B             # 13",
    "expr $A \\* $B            # 30",
    "",
    "# 방법 3: let",
    "let RESULT=A+B",
    "echo $RESULT             # 13",
    "",
    "# 방법 4: bc (소수점 계산 가능)",
    "echo \"10 / 3\" | bc -l    # 3.33333333...",
    "echo \"scale=2; 10/3\" | bc # 3.33",
    "```",
    "",
    "---",
    "",
    "## 5. 조건문",
    "",
    "### if 문",
    "```bash",
    "#!/bin/bash",
    "",
    "if [ $1 -gt 100 ]; then",
    "    echo \"100보다 큽니다\"",
    "elif [ $1 -gt 50 ]; then",
    "    echo \"50보다 큽니다\"",
    "else",
    "    echo \"50 이하입니다\"",
    "fi",
    "```",
    "",
    "### 비교 연산자",
    "",
    "**숫자 비교** (`[ ]` 안에서 사용)",
    "| 연산자 | 의미 | 예시 |",
    "|--------|------|------|",
    "| `-eq` | 같다 (equal) | `[ $A -eq $B ]` |",
    "| `-ne` | 다르다 (not equal) | `[ $A -ne $B ]` |",
    "| `-gt` | 크다 (greater than) | `[ $A -gt $B ]` |",
    "| `-ge` | 크거나 같다 | `[ $A -ge $B ]` |",
    "| `-lt` | 작다 (less than) | `[ $A -lt $B ]` |",
    "| `-le` | 작거나 같다 | `[ $A -le $B ]` |",
    "",
    "**문자열 비교**",
    "| 연산자 | 의미 | 예시 |",
    "|--------|------|------|",
    "| `=` | 같다 | `[ \"$A\" = \"$B\" ]` |",
    "| `!=` | 다르다 | `[ \"$A\" != \"$B\" ]` |",
    "| `-z` | 빈 문자열 | `[ -z \"$A\" ]` |",
    "| `-n` | 비어있지 않음 | `[ -n \"$A\" ]` |",
    "",
    "**파일 테스트**",
    "| 연산자 | 의미 |",
    "|--------|------|",
    "| `-e` | 파일/디렉터리 존재 |",
    "| `-f` | 일반 파일 존재 |",
    "| `-d` | 디렉터리 존재 |",
    "| `-r` | 읽기 권한 있음 |",
    "| `-w` | 쓰기 권한 있음 |",
    "| `-x` | 실행 권한 있음 |",
    "| `-s` | 파일 크기가 0이 아님 |",
    "| `-L` | 심볼릭 링크 |",
    "",
    "```bash",
    "#!/bin/bash",
    "",
    "FILE=\"/etc/passwd\"",
    "",
    "if [ -f \"$FILE\" ]; then",
    "    echo \"$FILE 은 일반 파일입니다\"",
    "fi",
    "",
    "if [ -d \"/home\" ]; then",
    "    echo \"/home 은 디렉터리입니다\"",
    "fi",
    "",
    "if [ -r \"$FILE\" ] && [ -w \"$FILE\" ]; then",
    "    echo \"읽기/쓰기 가능\"",
    "fi",
    "```",
    "",
    "### 논리 연산자",
    "```bash",
    "# [ ] 안에서",
    "[ $A -gt 0 -a $A -lt 100 ]     # AND (-a)",
    "[ $A -gt 0 -o $B -gt 0 ]       # OR (-o)",
    "[ ! -f file.txt ]              # NOT (!)",
    "",
    "# [[ ]] 안에서 (Bash 확장, 권장)",
    "[[ $A -gt 0 && $A -lt 100 ]]   # AND (&&)",
    "[[ $A -gt 0 || $B -gt 0 ]]     # OR (||)",
    "```",
    "",
    "### case 문",
    "```bash",
    "#!/bin/bash",
    "",
    "echo -n \"과일을 입력하세요: \"",
    "read FRUIT",
    "",
    "case $FRUIT in",
    "    apple|사과)",
    "        echo \"사과입니다\"",
    "        ;;",
    "    banana|바나나)",
    "        echo \"바나나입니다\"",
    "        ;;",
    "    *)",
    "        echo \"알 수 없는 과일: $FRUIT\"",
    "        ;;",
    "esac",
    "```",
    "",
    "---",
    "",
    "## 6. 반복문",
    "",
    "### for 문",
    "```bash",
    "#!/bin/bash",
    "",
    "# 목록 순회",
    "for NAME in Alice Bob Charlie; do",
    "    echo \"Hello, $NAME\"",
    "done",
    "",
    "# 범위 (1부터 5까지)",
    "for i in {1..5}; do",
    "    echo \"번호: $i\"",
    "done",
    "",
    "# 범위 + 증가값 (1, 3, 5, 7, 9)",
    "for i in {1..10..2}; do",
    "    echo $i",
    "done",
    "",
    "# C 스타일",
    "for ((i=0; i<5; i++)); do",
    "    echo \"index: $i\"",
    "done",
    "",
    "# 파일 순회",
    "for FILE in /etc/*.conf; do",
    "    echo \"설정 파일: $FILE\"",
    "done",
    "",
    "# 명령어 결과 순회",
    "for USER in $(cat /etc/passwd | cut -d: -f1); do",
    "    echo \"사용자: $USER\"",
    "done",
    "```",
    "",
    "### while 문",
    "```bash",
    "#!/bin/bash",
    "",
    "# 기본 while",
    "COUNT=1",
    "while [ $COUNT -le 5 ]; do",
    "    echo \"Count: $COUNT\"",
    "    COUNT=$((COUNT + 1))",
    "done",
    "",
    "# 파일을 한 줄씩 읽기",
    "while IFS= read -r LINE; do",
    "    echo \"줄: $LINE\"",
    "done < /etc/hostname",
    "",
    "# 무한 루프",
    "while true; do",
    "    echo \"실행 중... (Ctrl+C로 종료)\"",
    "    sleep 1",
    "done",
    "```",
    "",
    "### until 문 (조건이 참이 될 때까지)",
    "```bash",
    "COUNT=1",
    "until [ $COUNT -gt 5 ]; do",
    "    echo \"Count: $COUNT\"",
    "    COUNT=$((COUNT + 1))",
    "done",
    "```",
    "",
    "### break / continue",
    "```bash",
    "for i in {1..10}; do",
    "    if [ $i -eq 5 ]; then",
    "        break              # 반복문 종료",
    "    fi",
    "    if [ $((i % 2)) -eq 0 ]; then",
    "        continue           # 현재 반복 건너뛰기",
    "    fi",
    "    echo $i                # 1, 3 출력",
    "done",
    "```",
    "",
    "---",
    "",
    "## 7. 함수",
    "",
    "```bash",
    "#!/bin/bash",
    "",
    "# 함수 정의 (function 키워드 생략 가능)",
    "greet() {",
    "    echo \"안녕하세요, $1님! ($2세)\"",
    "}",
    "",
    "# 함수 호출",
    "greet \"haru\" 25",
    "# 안녕하세요, haru님! (25세)",
    "",
    "# 반환값 (return은 0~255 정수만, 문자열은 echo)",
    "add() {",
    "    echo $(($1 + $2))     # 결과를 echo로 출력",
    "}",
    "",
    "RESULT=$(add 10 20)       # 명령 치환으로 결과 받기",
    "echo \"합계: $RESULT\"     # 합계: 30",
    "",
    "# 종료 상태 확인",
    "check_file() {",
    "    if [ -f \"$1\" ]; then",
    "        return 0           # 성공",
    "    else",
    "        return 1           # 실패",
    "    fi",
    "}",
    "",
    "check_file \"/etc/passwd\"",
    "if [ $? -eq 0 ]; then",
    "    echo \"파일이 존재합니다\"",
    "fi",
    "```",
    "",
    "### 지역 변수 (local)",
    "```bash",
    "my_func() {",
    "    local LOCAL_VAR=\"함수 안에서만\"",
    "    GLOBAL_VAR=\"함수 밖에서도\"",
    "}",
    "",
    "my_func",
    "echo $LOCAL_VAR           # (출력 없음 - 함수 내부에서만 유효)",
    "echo $GLOBAL_VAR          # 함수 밖에서도",
    "```",
    "",
    "---",
    "",
    "## 8. 문자열 처리",
    "",
    "```bash",
    "STR=\"Hello, World!\"",
    "",
    "# 길이",
    "echo ${#STR}               # 13",
    "",
    "# 부분 문자열 (위치, 길이)",
    "echo ${STR:0:5}            # Hello",
    "echo ${STR:7}              # World!",
    "",
    "# 치환",
    "echo ${STR/World/Bash}     # Hello, Bash! (첫 번째만)",
    "echo ${STR//l/L}           # HeLLo, WorLd! (모두 치환)",
    "",
    "# 삭제 (패턴)",
    "FILE=\"/home/haru/document.tar.gz\"",
    "echo ${FILE##*/}           # document.tar.gz (경로 제거 = basename)",
    "echo ${FILE%/*}            # /home/haru (파일명 제거 = dirname)",
    "echo ${FILE%%.*}           # /home/haru/document (첫 . 이후 모두 제거)",
    "echo ${FILE#*.}            # tar.gz (첫 . 이전 제거)",
    "",
    "# 기본값 설정",
    "echo ${UNSET_VAR:-default} # 변수가 없으면 default 사용",
    "echo ${UNSET_VAR:=default} # 변수가 없으면 default로 할당까지",
    "```",
    "",
    "### 패턴 삭제 요약",
    "| 문법 | 설명 |",
    "|------|------|",
    "| `${변수#패턴}` | 앞에서부터 최소 일치 삭제 |",
    "| `${변수##패턴}` | 앞에서부터 최대 일치 삭제 |",
    "| `${변수%패턴}` | 뒤에서부터 최소 일치 삭제 |",
    "| `${변수%%패턴}` | 뒤에서부터 최대 일치 삭제 |",
    "",
    "---",
    "",
    "## 9. 배열",
    "",
    "```bash",
    "#!/bin/bash",
    "",
    "# 배열 선언",
    "FRUITS=(\"apple\" \"banana\" \"cherry\" \"date\")",
    "",
    "# 접근",
    "echo ${FRUITS[0]}          # apple (첫 번째)",
    "echo ${FRUITS[2]}          # cherry",
    "echo ${FRUITS[@]}          # 전체 출력",
    "echo ${FRUITS[*]}          # 전체 출력",
    "",
    "# 길이",
    "echo ${#FRUITS[@]}         # 4 (요소 개수)",
    "echo ${#FRUITS[0]}         # 5 (apple의 글자 수)",
    "",
    "# 추가·변경·삭제",
    "FRUITS+=(\"elderberry\")     # 끝에 추가",
    "FRUITS[1]=\"blueberry\"      # 변경",
    "unset FRUITS[3]            # 삭제",
    "",
    "# 순회",
    "for FRUIT in \"${FRUITS[@]}\"; do",
    "    echo \"과일: $FRUIT\"",
    "done",
    "",
    "# 슬라이싱",
    "echo ${FRUITS[@]:1:2}      # 인덱스 1부터 2개",
    "```",
    "",
    "---",
    "",
    "## 10. 유용한 텍스트 처리 명령어",
    "",
    "### cut (컬럼 추출)",
    "```bash",
    "# /etc/passwd에서 사용자명(1번째 필드)만 추출",
    "cut -d: -f1 /etc/passwd",
    "",
    "# 여러 필드",
    "cut -d: -f1,3,6 /etc/passwd   # 사용자명, UID, 홈",
    "",
    "# 문자 위치로 추출",
    "echo \"Hello World\" | cut -c1-5  # Hello",
    "```",
    "",
    "### awk (패턴 처리)",
    "```bash",
    "# 특정 필드 출력 (기본 구분자: 공백)",
    "ps aux | awk '{print $1, $2, $11}'   # USER, PID, COMMAND",
    "",
    "# 구분자 지정",
    "awk -F: '{print $1, $3}' /etc/passwd # 사용자명, UID",
    "",
    "# 조건 필터",
    "awk -F: '$3 >= 1000 {print $1}' /etc/passwd  # UID 1000 이상",
    "",
    "# 계산",
    "df -h | awk 'NR>1 {print $1, $5}'    # 파일시스템별 사용률",
    "```",
    "",
    "### sed (스트림 편집기)",
    "```bash",
    "# 문자열 치환 (첫 번째만)",
    "sed 's/old/new/' file.txt",
    "",
    "# 전체 치환 (g = global)",
    "sed 's/old/new/g' file.txt",
    "",
    "# 파일 직접 수정 (-i)",
    "sed -i 's/old/new/g' file.txt",
    "",
    "# 특정 줄 삭제",
    "sed '3d' file.txt             # 3번째 줄 삭제",
    "sed '/pattern/d' file.txt     # 패턴이 있는 줄 삭제",
    "",
    "# 특정 줄 출력 (-n + p)",
    "sed -n '5,10p' file.txt       # 5~10번째 줄 출력",
    "```",
    "",
    "### sort / uniq / wc",
    "```bash",
    "sort file.txt                  # 정렬",
    "sort -r file.txt               # 역순 정렬",
    "sort -n file.txt               # 숫자 기준 정렬",
    "sort -k2 file.txt              # 2번째 필드 기준 정렬",
    "sort -t: -k3 -n /etc/passwd    # : 구분자, 3번째 필드, 숫자 정렬",
    "",
    "sort file.txt | uniq           # 중복 제거 (정렬 먼저!)",
    "sort file.txt | uniq -c        # 중복 횟수 표시",
    "",
    "wc -l file.txt                 # 줄 수",
    "wc -w file.txt                 # 단어 수",
    "wc -c file.txt                 # 바이트 수",
    "```",
    "",
    "### xargs (파이프 결과를 인자로 전달)",
    "```bash",
    "# 검색된 파일 삭제",
    "find /tmp -name \"*.log\" | xargs rm",
    "",
    "# 검색된 파일에서 문자열 검색",
    "find . -name \"*.sh\" | xargs grep \"error\"",
    "```",
    "",
    "---",
    "",
    "## 11. 리다이렉션과 파이프",
    "",
    "```bash",
    "# 표준 출력 리다이렉션",
    "echo \"hello\" > file.txt         # 덮어쓰기",
    "echo \"world\" >> file.txt        # 추가(append)",
    "",
    "# 표준 에러 리다이렉션",
    "command 2> error.log             # 에러만 파일로",
    "command > all.log 2>&1           # 출력 + 에러 모두 파일로",
    "command &> all.log               # 위와 동일 (Bash 단축)",
    "",
    "# 표준 입력 리다이렉션",
    "sort < data.txt                  # 파일을 입력으로",
    "",
    "# Here Document (여러 줄 입력)",
    "cat << EOF",
    "첫 번째 줄",
    "두 번째 줄",
    "변수도 사용 가능: $HOME",
    "EOF",
    "",
    "# 파이프 (|)",
    "ps -ef | grep httpd | grep -v grep | wc -l",
    "cat access.log | sort | uniq -c | sort -rn | head -10",
    "```",
    "",
    "---",
    "",
    "## 12. 실전 스크립트 예제",
    "",
    "### 자동 백업 스크립트",
    "```bash",
    "#!/bin/bash",
    "",
    "BACKUP_DIR=\"/backup\"",
    "SOURCE_DIR=\"/home\"",
    "DATE=$(date +%Y%m%d_%H%M%S)",
    "FILENAME=\"home_backup_${DATE}.tar.gz\"",
    "",
    "mkdir -p $BACKUP_DIR",
    "tar -czf ${BACKUP_DIR}/${FILENAME} $SOURCE_DIR",
    "",
    "if [ $? -eq 0 ]; then",
    "    echo \"[성공] ${FILENAME} 백업 완료\"",
    "else",
    "    echo \"[실패] 백업에 문제가 발생했습니다\" >&2",
    "    exit 1",
    "fi",
    "",
    "# 7일 이상 된 백업 삭제",
    "find $BACKUP_DIR -name \"home_backup_*.tar.gz\" -mtime +7 -delete",
    "echo \"오래된 백업 정리 완료\"",
    "```",
    "",
    "### 서버 상태 점검 스크립트",
    "```bash",
    "#!/bin/bash",
    "",
    "echo \"===== 서버 상태 점검 =====\"",
    "echo \"날짜: $(date)\"",
    "echo \"\"",
    "",
    "echo \"[1] 시스템 가동 시간\"",
    "uptime",
    "echo \"\"",
    "",
    "echo \"[2] 디스크 사용량\"",
    "df -h | awk '$5+0 > 80 {print \"⚠ \" $0}'",
    "df -h | awk '$5+0 <= 80 {print \"  \" $0}'",
    "echo \"\"",
    "",
    "echo \"[3] 메모리 사용량\"",
    "free -h",
    "echo \"\"",
    "",
    "echo \"[4] CPU 상위 5개 프로세스\"",
    "ps aux --sort=-%cpu | head -6",
    "echo \"\"",
    "",
    "echo \"[5] 로그인 사용자\"",
    "who",
    "```",
    "",
    "### 로그 모니터링 (에러 감지)",
    "```bash",
    "#!/bin/bash",
    "",
    "LOG_FILE=\"/var/log/messages\"",
    "KEYWORD=\"error\"",
    "MAIL_TO=\"admin@example.com\"",
    "",
    "COUNT=$(grep -ic \"$KEYWORD\" $LOG_FILE)",
    "",
    "if [ $COUNT -gt 0 ]; then",
    "    echo \"[경고] ${LOG_FILE}에서 ${KEYWORD} ${COUNT}건 발견\" | \\",
    "        mail -s \"로그 경고\" $MAIL_TO",
    "fi",
    "```",
    "",
    "---",
    "",
    "## 13. 디버깅",
    "",
    "```bash",
    "# 스크립트 전체 디버깅",
    "bash -x script.sh             # 실행되는 명령을 출력",
    "",
    "# 스크립트 내부에서 설정",
    "set -x                        # 디버깅 시작",
    "set +x                        # 디버깅 종료",
    "",
    "# 에러 발생 시 즉시 종료",
    "set -e",
    "",
    "# 미정의 변수 사용 시 에러",
    "set -u",
    "",
    "# 파이프 중간 에러 감지",
    "set -o pipefail",
    "",
    "# 실전에서 스크립트 상단에 권장하는 조합",
    "#!/bin/bash",
    "set -euo pipefail",
    "```",
    "",
    "---",
    "### 요약",
    "- **셔뱅**: `#!/bin/bash` — 실행할 셸 지정",
    "- **변수**: `=` 앞뒤 공백 없음, `$변수` 또는 `${변수}`로 사용",
    "- **특수 변수**: `$0`(스크립트명), `$1`(인자), `$#`(인자 수), `$?`(종료 상태)",
    "- **조건문**: `if [ 조건 ]; then ... elif ... else ... fi`",
    "- **비교**: 숫자(`-eq`, `-gt`), 문자열(`=`, `!=`), 파일(`-f`, `-d`, `-r`)",
    "- **반복문**: `for ... in ... do ... done`, `while [ 조건 ]; do ... done`",
    "- **함수**: `func() { ... }`, 인자는 `$1`, `$2`, 반환은 `echo` + 명령 치환",
    "- **텍스트 처리**: `cut`, `awk`, `sed`, `sort`, `uniq`, `xargs`",
    "- **디버깅**: `set -euxo pipefail` 또는 `bash -x`"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
