<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-disk-management",
  title: "리눅스 디스크 관리 - 파티션, 마운트, LVM, RAID 총정리",
  date: "2026-03-05",
  summary: "리눅스 디스크 관리의 모든 것을 정리합니다. fdisk 파티션, mkfs 포맷, mount/fstab 마운트, df/du 용량 확인, LVM(PV→VG→LV) 생성·확장·축소·스냅샷, RAID 0/1/5/6/10 구성과 mdadm 명령어, 용량 계산까지 실전 예제와 함께 설명합니다.",
  category: "Technology/Linux",
  tags: ["linux","disk","partition","mount","fstab","lvm","raid","mdadm","fdisk","mkfs"],
  content: [
    "## 한 줄 요약",
    "리눅스 디스크 관리는 **파티션 → 포맷 → 마운트**가 기본이며, **LVM**으로 유연하게, **RAID**로 안정적으로 관리합니다.",
    "",
    "---",
    "",
    "## 1. 디스크·파티션 기본",
    "",
    "### 디스크 장치 이름 규칙",
    "| 장치 | 설명 |",
    "|------|------|",
    "| `/dev/sda` | 첫 번째 SCSI/SATA 디스크 |",
    "| `/dev/sdb` | 두 번째 디스크 |",
    "| `/dev/sda1` | 첫 번째 디스크의 첫 번째 파티션 |",
    "| `/dev/sda2` | 첫 번째 디스크의 두 번째 파티션 |",
    "| `/dev/nvme0n1` | NVMe SSD |",
    "| `/dev/nvme0n1p1` | NVMe SSD의 첫 번째 파티션 |",
    "| `/dev/vda` | 가상화 환경(VirtIO) 디스크 |",
    "",
    "### MBR vs GPT",
    "| 항목 | MBR | GPT |",
    "|------|-----|-----|",
    "| 최대 디스크 크기 | **2TB** | 사실상 무한 (9.4ZB) |",
    "| 최대 파티션 수 | 주 파티션 4개 (확장+논리 사용 시 더 가능) | **128개** |",
    "| 부팅 방식 | BIOS | **UEFI** |",
    "| 복구 | 복구 어려움 | 백업 테이블 존재 |",
    "",
    "### 파티션 관리 (fdisk)",
    "```bash",
    "# 디스크·파티션 목록 확인",
    "fdisk -l",
    "fdisk -l /dev/sdb              # 특정 디스크만",
    "",
    "# 파티션 관리 (대화형)",
    "fdisk /dev/sdb",
    "  # n: 새 파티션 생성",
    "  # d: 파티션 삭제",
    "  # p: 파티션 테이블 출력",
    "  # t: 파티션 타입 변경 (83=Linux, 82=Swap, 8e=LVM, fd=RAID)",
    "  # w: 변경사항 저장 후 종료",
    "  # q: 저장 없이 종료",
    "",
    "# GPT 파티션 관리",
    "gdisk /dev/sdb                 # GPT용 fdisk",
    "parted /dev/sdb                # 범용 파티션 도구",
    "```",
    "",
    "### 파티션 타입 코드 (시험 빈출!)",
    "| 코드 | 타입 | 설명 |",
    "|------|------|------|",
    "| `83` | Linux | 일반 리눅스 파티션 |",
    "| `82` | Linux swap | 스왑 파티션 |",
    "| `8e` | Linux LVM | LVM용 파티션 |",
    "| `fd` | Linux RAID autodetect | RAID용 파티션 |",
    "",
    "---",
    "",
    "## 2. 파일시스템 생성 (포맷)",
    "",
    "파티션을 만든 후 **파일시스템을 생성(포맷)**해야 사용할 수 있습니다.",
    "",
    "```bash",
    "mkfs -t ext4 /dev/sdb1         # ext4 파일시스템 생성",
    "mkfs.ext4 /dev/sdb1            # 동일 (축약형)",
    "mkfs.xfs /dev/sdb1             # XFS 파일시스템 생성",
    "mkfs.vfat /dev/sdb1            # FAT32 파일시스템",
    "",
    "mkswap /dev/sdb2               # 스왑 영역 생성",
    "swapon /dev/sdb2               # 스왑 활성화",
    "swapoff /dev/sdb2              # 스왑 비활성화",
    "```",
    "",
    "### 파일시스템 검사·복구",
    "```bash",
    "fsck /dev/sdb1                 # 일반 파일시스템 검사",
    "e2fsck -f /dev/sdb1            # ext2/3/4 강제 검사",
    "xfs_repair /dev/sdb1           # XFS 복구",
    "```",
    "",
    "**주의**: `fsck`는 반드시 **언마운트 상태**에서 실행해야 합니다.",
    "",
    "---",
    "",
    "## 3. 블록 장치 확인",
    "",
    "```bash",
    "# 블록 장치 트리 구조 확인",
    "lsblk",
    "lsblk -f                       # 파일시스템, UUID, 마운트 포인트 포함",
    "",
    "# 블록 장치 UUID, 타입 확인",
    "blkid",
    "blkid /dev/sdb1",
    "```",
    "",
    "```",
    "# lsblk 출력 예시",
    "NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT",
    "sda      8:0    0   50G  0 disk",
    "├─sda1   8:1    0    1G  0 part /boot",
    "└─sda2   8:2    0   49G  0 part",
    "  ├─vg-root 253:0 0   30G  0 lvm  /",
    "  └─vg-home 253:1 0   19G  0 lvm  /home",
    "sdb      8:16   0  100G  0 disk",
    "```",
    "",
    "---",
    "",
    "## 4. 마운트 (mount / umount)",
    "",
    "파일시스템을 **디렉터리 트리에 연결**하는 것이 마운트입니다.",
    "",
    "```bash",
    "# 수동 마운트",
    "mount /dev/sdb1 /mnt/data",
    "mount -t ext4 /dev/sdb1 /mnt/data      # 파일시스템 타입 지정",
    "mount -o ro /dev/sdb1 /mnt/data         # 읽기 전용 마운트",
    "mount -o remount,rw /mnt/data           # 읽기-쓰기로 재마운트",
    "",
    "# 언마운트",
    "umount /mnt/data",
    "umount /dev/sdb1               # 장치명으로도 가능",
    "",
    "# 현재 마운트 목록",
    "mount",
    "mount | grep sdb",
    "```",
    "",
    "### 마운트 옵션",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `defaults` | rw, suid, dev, exec, auto, nouser, async |",
    "| `ro` / `rw` | 읽기 전용 / 읽기-쓰기 |",
    "| `noexec` | 실행 파일 실행 금지 |",
    "| `nosuid` | SetUID/SetGID 무시 |",
    "| `noatime` | 접근 시간 기록 안 함 (성능 향상) |",
    "| `auto` / `noauto` | 부팅 시 자동 마운트 여부 |",
    "| `user` / `nouser` | 일반 사용자 마운트 허용 여부 |",
    "",
    "### /etc/fstab (부팅 시 자동 마운트)",
    "```",
    "/dev/sdb1  /mnt/data  ext4  defaults  0  2",
    "│          │          │     │         │  └ fsck 검사 순서 (0:안함, 1:루트, 2:기타)",
    "│          │          │     │         └ dump 백업 (0:안함, 1:함)",
    "│          │          │     └ 마운트 옵션",
    "│          │          └ 파일시스템 타입",
    "│          └ 마운트 포인트",
    "└ 장치명 또는 UUID",
    "```",
    "",
    "```bash",
    "# UUID로 지정 (장치명보다 안정적)",
    "UUID=a1b2c3d4-5678-90ab-cdef-1234567890ab  /mnt/data  ext4  defaults  0  2",
    "",
    "# fstab 수정 후 테스트 (재부팅 없이)",
    "mount -a                       # fstab의 모든 항목 마운트",
    "```",
    "",
    "---",
    "",
    "## 5. 디스크 용량 확인",
    "",
    "```bash",
    "# 파일시스템별 사용량",
    "df -h                          # 사람이 읽기 쉬운 단위",
    "df -T                          # 파일시스템 타입 포함",
    "df -i                          # inode 사용량",
    "",
    "# 디렉터리/파일 크기",
    "du -sh /home                   # 특정 디렉터리 크기",
    "du -sh *                       # 현재 디렉터리 항목별 크기",
    "du -h --max-depth=1 /var       # 1단계까지만 표시",
    "```",
    "",
    "### df vs du",
    "| 명령 | 설명 |",
    "|------|------|",
    "| `df` | **파일시스템** 단위 사용량 (마운트된 전체) |",
    "| `du` | **디렉터리/파일** 단위 사용량 (실제 크기) |",
    "",
    "---",
    "",
    "## 6. LVM (Logical Volume Manager)",
    "",
    "물리 디스크를 논리적으로 묶어 **유연하게 파티션 크기를 조절**할 수 있는 디스크 관리 기술입니다.",
    "",
    "### 왜 LVM이 필요한가?",
    "",
    "| 상황 | 일반 파티션 | LVM |",
    "|------|-----------|-----|",
    "| 파티션이 꽉 찼을 때 | 재파티셔닝 필요 (매우 어려움) | 명령어로 확장 |",
    "| 디스크를 추가해서 확장 | 새 마운트포인트 필요 | 기존 볼륨에 추가 후 확장 |",
    "| 디스크 교체 시 이동 | 백업 → 재설치 → 복원 | `pvmove`로 온라인 이동 |",
    "| 스냅샷 백업 | 별도 도구 필요 | 기본 지원 |",
    "",
    "### LVM 구조 (시험 빈출!)",
    "```",
    "물리 디스크 → PV(물리볼륨) → VG(볼륨그룹) → LV(논리볼륨) → 파일시스템",
    "",
    "┌──────────────────────────────────────┐",
    "│         VG (Volume Group)            │",
    "│  ┌─────────┐  ┌─────────┐           │",
    "│  │ LV: data │  │ LV: log │  (여유)   │",
    "│  └─────────┘  └─────────┘           │",
    "├──────────┬──────────┬────────────────┤",
    "│ PV: sdb1 │ PV: sdc1 │   PV: sdd1    │",
    "└──────────┴──────────┴────────────────┘",
    "```",
    "",
    "### LVM 용어",
    "| 용어 | 설명 | 비유 |",
    "|------|------|------|",
    "| **PV** (Physical Volume) | 물리 볼륨. 실제 파티션이나 디스크 | 재료 (밀가루 봉지) |",
    "| **VG** (Volume Group) | 볼륨 그룹. PV를 하나로 묶은 저장소 풀 | 반죽통 (재료를 합친 것) |",
    "| **LV** (Logical Volume) | 논리 볼륨. VG에서 할당받은 가상 파티션 | 빵 (원하는 크기로 자름) |",
    "| **PE** (Physical Extent) | PV를 구성하는 최소 블록 단위 (기본 4MB) | - |",
    "| **LE** (Logical Extent) | LV를 구성하는 최소 블록 단위 (PE와 1:1 매핑) | - |",
    "",
    "LV 위에 파일시스템(ext4, xfs 등)을 만들고 마운트하면 일반 파티션처럼 사용합니다.",
    "",
    "### LVM 주요 명령어",
    "```bash",
    "# ── PV (물리볼륨) 관리 ──",
    "pvcreate /dev/sdb1              # PV 생성",
    "pvdisplay                       # PV 상세 정보",
    "pvs                             # PV 요약 목록",
    "pvremove /dev/sdb1              # PV 제거",
    "",
    "# ── VG (볼륨그룹) 관리 ──",
    "vgcreate myvg /dev/sdb1 /dev/sdc1   # VG 생성 (PV 여러개 묶기)",
    "vgdisplay myvg                  # VG 상세 정보",
    "vgs                             # VG 요약 목록",
    "vgextend myvg /dev/sdd1         # VG에 PV 추가 (확장)",
    "vgreduce myvg /dev/sdd1         # VG에서 PV 제거 (축소)",
    "vgremove myvg                   # VG 삭제",
    "",
    "# ── LV (논리볼륨) 관리 ──",
    "lvcreate -L 10G -n mylv myvg    # LV 생성 (크기 10GB)",
    "lvcreate -l 100%FREE -n mylv myvg  # VG 남은 공간 전부 사용",
    "lvdisplay /dev/myvg/mylv        # LV 상세 정보",
    "lvs                             # LV 요약 목록",
    "lvremove /dev/myvg/mylv         # LV 삭제",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `-L 10G` | 크기 지정 (G, M, T) |",
    "| `-l 100%FREE` | 남은 공간의 비율로 지정 |",
    "| `-n mylv` | 논리 볼륨 이름 |",
    "",
    "### LVM 생성 전체 흐름",
    "```bash",
    "# 1. 파티션 생성 (타입: 8e = Linux LVM)",
    "fdisk /dev/sdb                  # → n(새 파티션) → t(타입 변경) → 8e → w(저장)",
    "",
    "# 2. PV 생성",
    "pvcreate /dev/sdb1",
    "",
    "# 3. VG 생성",
    "vgcreate myvg /dev/sdb1",
    "",
    "# 4. LV 생성",
    "lvcreate -L 10G -n mylv myvg",
    "",
    "# 5. 파일시스템 생성 (포맷)",
    "mkfs.ext4 /dev/myvg/mylv",
    "",
    "# 6. 마운트",
    "mkdir /mnt/data",
    "mount /dev/myvg/mylv /mnt/data",
    "",
    "# 7. 영구 마운트 (/etc/fstab에 등록)",
    "/dev/myvg/mylv  /mnt/data  ext4  defaults  0  2",
    "```",
    "",
    "LV의 경로는 `/dev/VG이름/LV이름` 형식입니다.",
    "",
    "### LV 크기 확장",
    "LVM의 가장 큰 장점은 **운영 중에도 볼륨 크기를 변경**할 수 있다는 것입니다.",
    "",
    "```bash",
    "# LV 5GB 추가 확장",
    "lvextend -L +5G /dev/myvg/mylv",
    "",
    "# LV를 총 20GB로 확장",
    "lvextend -L 20G /dev/myvg/mylv",
    "",
    "# VG 남은 공간 전부 사용",
    "lvextend -l +100%FREE /dev/myvg/mylv",
    "",
    "# 파일시스템도 함께 확장 (-r 옵션, 가장 편리)",
    "lvextend -L +5G -r /dev/myvg/mylv",
    "",
    "# 수동으로 파일시스템 확장",
    "resize2fs /dev/myvg/mylv              # ext4 파일시스템 확장",
    "xfs_growfs /mnt/data                  # xfs 파일시스템 확장",
    "```",
    "",
    "ext4와 xfs 모두 **온라인(마운트 상태) 확장**이 가능합니다.",
    "",
    "### LV 크기 축소",
    "```bash",
    "# ext4: 언마운트 후 축소 (xfs는 축소 불가!)",
    "umount /mnt/data                      # 언마운트 필수",
    "e2fsck -f /dev/myvg/mylv              # 파일시스템 검사",
    "resize2fs /dev/myvg/mylv 5G           # 파일시스템 먼저 축소",
    "lvreduce -L 5G /dev/myvg/mylv         # LV 축소",
    "mount /dev/myvg/mylv /mnt/data        # 다시 마운트",
    "",
    "# -r 옵션으로 한 번에 (파일시스템 + LV 동시 축소)",
    "umount /mnt/data",
    "lvreduce -L 5G -r /dev/myvg/mylv",
    "mount /dev/myvg/mylv /mnt/data",
    "```",
    "",
    "**주의**: 축소는 데이터 손실 위험이 있으므로 반드시 **백업 후** 진행합니다.",
    "",
    "### VG에 디스크 추가",
    "서버 용량이 부족할 때, 새 디스크를 추가해서 기존 볼륨을 확장할 수 있습니다.",
    "",
    "```bash",
    "# 새 디스크를 PV로 초기화",
    "pvcreate /dev/sdd",
    "",
    "# 기존 VG에 추가",
    "vgextend myvg /dev/sdd",
    "",
    "# 이제 VG 전체 용량이 늘어남 → LV를 확장 가능",
    "lvextend -l +100%FREE -r /dev/myvg/mylv",
    "```",
    "",
    "이것이 일반 파티션으로는 불가능한, LVM의 핵심 장점입니다.",
    "",
    "### LVM 스냅샷",
    "특정 시점의 LV 상태를 **복사 없이 보존**합니다 (COW: Copy-On-Write 방식).",
    "",
    "```bash",
    "# 스냅샷 생성",
    "lvcreate -s -L 2G -n mysnap /dev/myvg/mylv",
    "  # -s: snapshot  -L: 스냅샷 크기  -n: 이름",
    "",
    "# 스냅샷 마운트 (읽기 전용 확인)",
    "mount -o ro /dev/myvg/mysnap /mnt/snap",
    "",
    "# 스냅샷으로 복원",
    "lvconvert --merge /dev/myvg/mysnap",
    "",
    "# 스냅샷 삭제",
    "lvremove /dev/myvg/mysnap",
    "```",
    "",
    "| 용도 | 설명 |",
    "|------|------|",
    "| 백업 전 상태 보존 | 업데이트/변경 전 스냅샷 → 문제 시 롤백 |",
    "| 일관된 백업 | 스냅샷을 마운트해서 백업하면 변경 중인 파일 영향 없음 |",
    "| 테스트 | 설정 변경 테스트 후 문제 시 복원 |",
    "",
    "### LVM 확인 명령어",
    "```bash",
    "pvs          # PV 간략 목록",
    "pvdisplay    # PV 상세 정보",
    "",
    "vgs          # VG 간략 목록",
    "vgdisplay    # VG 상세 정보",
    "",
    "lvs          # LV 간략 목록",
    "lvdisplay    # LV 상세 정보",
    "```",
    "",
    "### LVM vs 일반 파티션",
    "| 기준 | 일반 파티션 | LVM |",
    "|------|-----------|-----|",
    "| 크기 변경 | 매우 어려움 (재파티셔닝) | 명령어로 확장/축소 |",
    "| 여러 디스크를 하나로 | 불가 | VG로 묶기 가능 |",
    "| 디스크 추가 후 확장 | 새 마운트포인트 필요 | 기존 LV에 공간 추가 |",
    "| 스냅샷 | 별도 도구 필요 | 기본 지원 |",
    "| 온라인 확장 | 제한적 | 마운트 상태에서 확장 가능 |",
    "| 복잡도 | 단순 | PV/VG/LV 개념 학습 필요 |",
    "| 성능 | 약간 유리 | 미세한 오버헤드 (실무에서 무시 가능) |",
    "",
    "### LVM 주의사항",
    "- **/boot은 LVM 밖에 두기**: GRUB이 LVM 위의 /boot을 인식하지 못할 수 있음",
    "- **축소는 신중하게**: 데이터 손실 위험, xfs는 축소 불가",
    "- **스냅샷 공간 관리**: 변경이 많으면 스냅샷 공간이 가득 찰 수 있음",
    "- **복구 시 LVM 인식**: Live USB 복구 시 `vgchange -ay`로 VG 활성화 필요",
    "",
    "---",
    "",
    "## 7. RAID (Redundant Array of Independent Disks)",
    "",
    "여러 디스크를 묶어 **성능 향상** 또는 **데이터 안정성**을 높이는 기술입니다.",
    "",
    "**주의**: RAID는 **백업이 아닙니다**. 실수로 파일을 삭제하면 RAID에서도 삭제됩니다. RAID는 디스크 **하드웨어 고장**에 대한 보호입니다.",
    "",
    "### 핵심 용어",
    "| 용어 | 설명 |",
    "|------|------|",
    "| **스트라이핑** (Striping) | 데이터를 여러 디스크에 나눠 저장 → 읽기/쓰기 속도 향상 |",
    "| **미러링** (Mirroring) | 같은 데이터를 2개 이상의 디스크에 동일하게 복사 |",
    "| **패리티** (Parity) | 오류 복구용 데이터. 디스크 하나가 고장나면 패리티로 복원 가능 |",
    "| **핫 스페어** (Hot Spare) | 예비 디스크. 고장 발생 시 자동으로 교체되어 리빌드 |",
    "| **리빌드** (Rebuild) | 고장난 디스크를 교체한 뒤 데이터를 다시 복구하는 과정 |",
    "",
    "### RAID 레벨 비교 (시험 빈출!)",
    "",
    "#### RAID 0 (스트라이핑)",
    "```",
    "디스크1: [A1][A3][A5]",
    "디스크2: [A2][A4][A6]",
    "```",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 구조 | 데이터를 디스크에 번갈아 저장 (스트라이핑) |",
    "| 최소 디스크 | 2개 |",
    "| 사용 가능 용량 | 전체 합계 (100%) |",
    "| 내결함성 | **없음** — 1개만 고장나도 전체 데이터 손실 |",
    "| 용도 | 임시 데이터, 캐시 등 속도가 중요하고 손실이 괜찮은 경우 |",
    "",
    "#### RAID 1 (미러링)",
    "```",
    "디스크1: [A1][A2][A3]",
    "디스크2: [A1][A2][A3]  ← 동일한 복사본",
    "```",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 구조 | 같은 데이터를 2개 디스크에 동일하게 저장 |",
    "| 최소 디스크 | 2개 |",
    "| 사용 가능 용량 | 절반 (50%) |",
    "| 내결함성 | 1개 고장 허용 |",
    "| 용도 | OS 디스크, 중요 데이터, 소규모 서버 |",
    "",
    "#### RAID 5 (스트라이핑 + 분산 패리티)",
    "```",
    "디스크1: [A1][B2][C_P]",
    "디스크2: [A2][B_P][C1]",
    "디스크3: [A_P][B1][C2]",
    "         (_P = 패리티)",
    "```",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 구조 | 데이터 + 패리티를 모든 디스크에 분산 저장 |",
    "| 최소 디스크 | 3개 |",
    "| 사용 가능 용량 | (N-1) × 디스크 크기 |",
    "| 내결함성 | 1개 고장 허용 |",
    "| 용도 | 범용 서버, NAS, 용량과 안정성의 균형 |",
    "",
    "#### RAID 6 (스트라이핑 + 이중 패리티)",
    "```",
    "디스크1: [A1][B_P][C_Q][D2]",
    "디스크2: [A_P][B1][C2][D_Q]",
    "디스크3: [A_Q][B2][C_P][D1]",
    "디스크4: [A2][B_Q][C1][D_P]",
    "         (_P, _Q = 패리티 2개)",
    "```",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 구조 | RAID 5와 유사하지만 패리티를 2개 저장 |",
    "| 최소 디스크 | 4개 |",
    "| 사용 가능 용량 | (N-2) × 디스크 크기 |",
    "| 내결함성 | **2개** 동시 고장 허용 |",
    "| 용도 | 대용량 스토리지, 리빌드 시간이 긴 대형 디스크 환경 |",
    "",
    "#### RAID 10 (1+0, 미러 + 스트라이프)",
    "```",
    "          RAID 0 (스트라이프)",
    "         /              \\\\",
    "   RAID 1 (미러)    RAID 1 (미러)",
    "   디스크1  디스크2  디스크3  디스크4",
    "   [A1]    [A1]    [A2]    [A2]",
    "   [A3]    [A3]    [A4]    [A4]",
    "```",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 구조 | 미러링(RAID 1)한 쌍을 스트라이핑(RAID 0)으로 묶음 |",
    "| 최소 디스크 | 4개 |",
    "| 사용 가능 용량 | 절반 (50%) |",
    "| 내결함성 | 각 미러 쌍에서 1개씩 고장 허용 |",
    "| 용도 | 데이터베이스 서버, 고성능 + 고안정성이 모두 필요한 환경 |",
    "",
    "### RAID 한눈에 비교",
    "| 레벨 | 최소 디스크 | 사용 용량 | 내결함성 | 읽기 | 쓰기 | 용도 |",
    "|------|-----------|----------|---------|------|------|------|",
    "| RAID 0 | 2 | 100% | 없음 | 매우 빠름 | 매우 빠름 | 속도 우선 |",
    "| RAID 1 | 2 | 50% | 1개 | 빠름 | 보통 | OS, 중요 데이터 |",
    "| RAID 5 | 3 | (N-1)/N | 1개 | 빠름 | 보통 | 범용 서버, NAS |",
    "| RAID 6 | 4 | (N-2)/N | 2개 | 빠름 | 느림 | 대용량 스토리지 |",
    "| RAID 10 | 4 | 50% | 쌍당 1개 | 매우 빠름 | 빠름 | DB, 고성능 서버 |",
    "",
    "### 소프트웨어 RAID (mdadm)",
    "리눅스에서는 **mdadm**으로 소프트웨어 RAID를 구성합니다.",
    "",
    "```bash",
    "# RAID 생성",
    "mdadm --create /dev/md0 --level=5 --raid-devices=3 /dev/sdb1 /dev/sdc1 /dev/sdd1",
    "",
    "# 파일시스템 생성 + 마운트",
    "mkfs.ext4 /dev/md0",
    "mount /dev/md0 /mnt/raid",
    "",
    "# RAID 상태 확인",
    "mdadm --detail /dev/md0",
    "cat /proc/mdstat",
    "",
    "# RAID 중지·제거",
    "mdadm --stop /dev/md0",
    "mdadm --remove /dev/md0",
    "",
    "# 설정 저장 (재부팅 후에도 유지)",
    "mdadm --detail --scan >> /etc/mdadm.conf",
    "```",
    "",
    "### /proc/mdstat 읽기",
    "```",
    "md0 : active raid5 sdd1[2] sdc1[1] sdb1[0]",
    "      209408 blocks super 1.2 level 5, 512k chunk, algorithm 2 [3/3] [UUU]",
    "```",
    "- `[UUU]`: 3개 디스크 모두 정상 (U=Up)",
    "- `[UU_]`: 하나가 고장/분리됨",
    "",
    "### 디스크 교체 (고장 시)",
    "```bash",
    "# 고장난 디스크 표시·제거",
    "mdadm --manage /dev/md0 --fail /dev/sdb1",
    "mdadm --manage /dev/md0 --remove /dev/sdb1",
    "",
    "# 새 디스크 추가 → 자동 리빌드 시작",
    "mdadm --manage /dev/md0 --add /dev/sde1",
    "",
    "# 리빌드 진행 상황 확인",
    "cat /proc/mdstat",
    "```",
    "",
    "### 스페어 디스크 (Spare Disk)",
    "RAID 구성에서 **예비로 대기하는 디스크**입니다. 평소에는 사용되지 않다가, 디스크 장애 시 **자동으로 교체되어 리빌드(복구)**를 시작합니다.",
    "",
    "```",
    "[정상] 디스크1 + 디스크2 + 디스크3 (RAID 5) + 스페어(대기)",
    "  ↓ 디스크2 고장!",
    "[복구] 디스크1 + 스페어(리빌드) + 디스크3",
    "```",
    "",
    "- **Hot Spare**: 시스템 가동 중 자동으로 장애 디스크 대체",
    "- RAID 0은 복구 기능이 없으므로 스페어 디스크 사용 불가",
    "- RAID 1, 5, 6, 10 등 미러링·패리티가 있는 RAID에서 사용",
    "",
    "```bash",
    "# RAID 생성 시 스페어 포함",
    "mdadm --create /dev/md0 --level=5 --raid-devices=3 --spare-devices=1 \\\\",
    "  /dev/sdb1 /dev/sdc1 /dev/sdd1 /dev/sde1",
    "",
    "# 기존 RAID에 스페어 추가",
    "mdadm /dev/md0 --add /dev/sde1",
    "```",
    "",
    "### 하드웨어 RAID vs 소프트웨어 RAID",
    "| 구분 | 하드웨어 RAID | 소프트웨어 RAID |",
    "|------|-------------|----------------|",
    "| 구현 | 전용 RAID 컨트롤러 카드 | OS가 처리 (mdadm 등) |",
    "| 비용 | 비쌈 (컨트롤러 구매) | 무료 (OS 기능) |",
    "| CPU 부하 | 없음 (컨트롤러가 처리) | 있음 (현대 CPU에선 미미) |",
    "| 부팅 | 컨트롤러 BIOS에서 관리 | OS 부팅 후 활성화 |",
    "| 이식성 | 같은 컨트롤러 필요 | 어떤 리눅스에서든 인식 |",
    "| 배터리 백업 | BBU 가능 | 없음 |",
    "",
    "클라우드·가상화 환경에서는 소프트웨어 RAID(mdadm)가 더 일반적입니다.",
    "",
    "### RAID 용량 계산 (시험 빈출!)",
    "스페어 디스크를 **먼저 제외**한 후, RAID 레벨별 공식을 적용합니다.",
    "",
    "| RAID | 용량 공식 | 설명 | 최소 디스크 |",
    "|------|-----------|------|------------|",
    "| RAID 0 | N × 디스크 용량 | 전부 사용 (스트라이핑) | 2개 |",
    "| RAID 1 | **N / 2 × 디스크 용량** | 2개씩 쌍으로 미러링 (짝수 필요) | 2개 |",
    "| RAID 5 | **(N - 1) × 디스크 용량** | 패리티 1개분 차감 | 3개 |",
    "| RAID 6 | (N - 2) × 디스크 용량 | 패리티 2개분 차감 | 4개 |",
    "| RAID 10 | N / 2 × 디스크 용량 | 미러링 + 스트라이핑 (짝수 필요) | 4개 |",
    "",
    "**예제 1**: 10GB 디스크 8개, 스페어 1개, **RAID-5** 구성 시 사용 가능한 용량은?",
    "```",
    "전체 8개 디스크 (각 10GB)",
    "  - 스페어 디스크 1개 제외 → RAID 구성 디스크: 7개",
    "  - RAID-5 공식: (N-1) × 디스크 용량",
    "  = (7-1) × 10GB = 60GB  ← 정답",
    "```",
    "",
    "RAID-5의 패리티는 특정 디스크 하나에 몰리지 않고 **모든 디스크에 분산 저장**되지만, 전체 패리티 총량이 디스크 1개분이므로 계산 시 1개를 빼면 됩니다.",
    "",
    "**예제 2**: 10GB 디스크 8개, 스페어 1개, **RAID-1** 구성 시 사용 가능한 용량은?",
    "```",
    "전체 8개 디스크 (각 10GB)",
    "  - 스페어 디스크 1개 제외 → 7개",
    "  - RAID-1은 짝수 필요 (2개씩 쌍) → 6개 사용 (1개 추가 스페어)",
    "  - RAID-1 공식: N / 2 × 디스크 용량",
    "  = 6 / 2 × 10GB = 30GB  ← 정답",
    "```",
    "",
    "### RAID 주의사항",
    "- **RAID는 백업이 아니다**: 디스크 고장 보호이지, 파일 삭제·랜섬웨어 보호가 아님. 별도 백업 필수",
    "- **같은 용량의 디스크 사용**: 가장 작은 디스크 용량에 맞춰짐",
    "- **리빌드 시간**: 대용량 디스크(4TB+)는 수 시간~수십 시간 소요. 이 시간 동안 추가 고장 위험",
    "- **모니터링 필수**: 디스크 고장을 빨리 발견해야 교체 가능. mdadm 알림 설정 권장",
    "",
    "---",
    "",
    "## 8. RAID + LVM 조합",
    "",
    "실무에서는 RAID와 LVM을 함께 사용하는 경우가 많습니다.",
    "",
    "```",
    "물리 디스크 → RAID (mdadm) → LVM (PV → VG → LV) → 파일시스템 → 마운트",
    "```",
    "",
    "| 계층 | 역할 |",
    "|------|------|",
    "| RAID | 디스크 고장 보호 + 성능 |",
    "| LVM | 볼륨 크기 유연한 관리 |",
    "",
    "```bash",
    "# RAID 배열을 LVM의 PV로 사용",
    "pvcreate /dev/md0",
    "vgcreate vg_raid /dev/md0",
    "lvcreate -L 50G -n lv_data vg_raid",
    "mkfs.ext4 /dev/vg_raid/lv_data",
    "mount /dev/vg_raid/lv_data /mnt/data",
    "```",
    "",
    "RAID가 안정성을, LVM이 유연성을 담당하는 조합입니다.",
    "",
    "---",
    "",
    "## 9. 실전 예시: 서버 디스크 구성",
    "",
    "### LVM 서버 구성",
    "```bash",
    "pvcreate /dev/sdb /dev/sdc",
    "vgcreate vg_server /dev/sdb /dev/sdc",
    "",
    "lvcreate -L 30G -n lv_root vg_server",
    "lvcreate -L 50G -n lv_home vg_server",
    "lvcreate -L 20G -n lv_var vg_server",
    "lvcreate -L 4G  -n lv_swap vg_server",
    "",
    "mkfs.ext4 /dev/vg_server/lv_root",
    "mkfs.ext4 /dev/vg_server/lv_home",
    "mkfs.ext4 /dev/vg_server/lv_var",
    "mkswap /dev/vg_server/lv_swap",
    "```",
    "",
    "나중에 /home이 부족하면 `lvextend -L +20G -r /dev/vg_server/lv_home` 한 줄로 확장합니다.",
    "",
    "### 전체 흐름 요약",
    "```",
    "1. fdisk로 파티션 생성 (타입 설정: 83, 8e, fd)",
    "     ↓",
    "2-A. 일반 사용: mkfs → mount → fstab",
    "2-B. LVM: pvcreate → vgcreate → lvcreate → mkfs → mount → fstab",
    "2-C. RAID: mdadm --create → mkfs → mount → fstab",
    "2-D. RAID+LVM: mdadm → pvcreate(md0) → vgcreate → lvcreate → mkfs → mount",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "- **파티션**: `fdisk`(MBR) / `gdisk`(GPT)로 생성, 타입 코드(83, 82, 8e, fd) 지정",
    "- **포맷**: `mkfs.ext4` / `mkfs.xfs`로 파일시스템 생성",
    "- **마운트**: `mount`(수동), `/etc/fstab`(영구), `mount -a`(테스트)",
    "- **용량**: `df -h`(파일시스템), `du -sh`(디렉터리)",
    "- **LVM**: PV → VG → LV 3단계, `lvextend -r`(확장), `lvreduce -r`(축소), `lvcreate -s`(스냅샷)",
    "- **RAID**: 0(스트라이핑), 1(미러링), 5(패리티 1개), 6(패리티 2개), 10(미러+스트라이프)",
    "- **mdadm**: `--create`(생성), `--detail`(상태), `--fail/--remove/--add`(교체)",
    "- **용량 계산**: 스페어 먼저 제외 → RAID 0: N, RAID 1: N/2, RAID 5: N-1, RAID 6: N-2",
    "- **RAID+LVM**: RAID(안정성) + LVM(유연성) 조합이 실무 표준"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
