<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-network-management",
  title: "리눅스 네트워크 관리 - 설정, 명령어, 서비스 포트 총정리",
  date: "2026-03-03",
  summary: "리눅스 네트워크의 핵심을 정리합니다. IP 설정(ifconfig/ip), 호스트네임, DNS, 라우팅, 네트워크 진단(ping/traceroute/netstat/ss), 파일 전송(scp/sftp/ftp), 주요 서비스 포트, 방화벽(firewalld/iptables)까지 실전 예제와 함께 설명합니다.",
  category: "Technology/Linux",
  tags: ["linux","network","ifconfig","ip","ping","netstat","ss","firewall","dns","port"],
  content: [
    "## 한 줄 요약",
    "리눅스 네트워크 관리는 **IP 설정 → DNS 설정 → 라우팅 → 진단 → 방화벽** 순서로 이해하면 됩니다.",
    "",
    "---",
    "",
    "## 1. 네트워크 기본 개념",
    "",
    "### IP 주소",
    "네트워크에서 장치를 식별하는 고유 주소입니다.",
    "",
    "| 구분 | IPv4 | IPv6 |",
    "|------|------|------|",
    "| 형식 | 32비트 (4옥텟) | 128비트 (8그룹) |",
    "| 표기 | `192.168.1.100` | `2001:0db8::1` |",
    "| 주소 수 | 약 43억 개 | 사실상 무한 |",
    "",
    "### IP 주소 클래스",
    "| 클래스 | 범위 | 기본 서브넷 마스크 | 용도 |",
    "|--------|------|-------------------|------|",
    "| A | 1.0.0.0 ~ 126.255.255.255 | 255.0.0.0 (/8) | 대규모 네트워크 |",
    "| B | 128.0.0.0 ~ 191.255.255.255 | 255.255.0.0 (/16) | 중규모 네트워크 |",
    "| C | 192.0.0.0 ~ 223.255.255.255 | 255.255.255.0 (/24) | 소규모 네트워크 |",
    "| D | 224.0.0.0 ~ 239.255.255.255 | - | 멀티캐스트 |",
    "| E | 240.0.0.0 ~ 255.255.255.255 | - | 예약(실험용) |",
    "",
    "### 사설 IP 주소 (Private IP)",
    "| 클래스 | 범위 |",
    "|--------|------|",
    "| A | 10.0.0.0 ~ 10.255.255.255 |",
    "| B | 172.16.0.0 ~ 172.31.255.255 |",
    "| C | 192.168.0.0 ~ 192.168.255.255 |",
    "",
    "### 서브넷 마스크와 게이트웨이",
    "- **서브넷 마스크**: 네트워크 부분과 호스트 부분을 구분 (예: `255.255.255.0`)",
    "- **게이트웨이**: 외부 네트워크로 나가는 출입구 (예: `192.168.1.1`)",
    "- **브로드캐스트**: 네트워크 내 모든 호스트에 전달 (예: `192.168.1.255`)",
    "",
    "### MAC 주소",
    "네트워크 인터페이스 카드(NIC)에 할당된 **물리적 주소** (48비트)입니다.",
    "```",
    "형식: AA:BB:CC:DD:EE:FF",
    "앞 3바이트: 제조사 식별 (OUI)",
    "뒤 3바이트: 장치 고유 번호",
    "```",
    "",
    "---",
    "",
    "## 2. 네트워크 인터페이스 설정",
    "",
    "### ifconfig (전통 방식)",
    "```bash",
    "# 모든 인터페이스 정보 확인",
    "ifconfig",
    "",
    "# 특정 인터페이스 확인",
    "ifconfig eth0",
    "",
    "# IP 주소 설정",
    "ifconfig eth0 192.168.1.100 netmask 255.255.255.0",
    "",
    "# 인터페이스 활성화/비활성화",
    "ifconfig eth0 up",
    "ifconfig eth0 down",
    "",
    "# 출력 주요 항목",
    "# inet: IPv4 주소",
    "# inet6: IPv6 주소",
    "# ether: MAC 주소",
    "# RX/TX: 수신/송신 패킷 통계",
    "# MTU: 최대 전송 단위",
    "```",
    "",
    "### ip 명령어 (현대 방식, iproute2)",
    "`ifconfig`를 대체하는 최신 명령어입니다.",
    "",
    "```bash",
    "# IP 주소 확인",
    "ip addr show                  # = ip a",
    "ip addr show eth0             # 특정 인터페이스",
    "",
    "# IP 주소 추가/삭제",
    "ip addr add 192.168.1.100/24 dev eth0",
    "ip addr del 192.168.1.100/24 dev eth0",
    "",
    "# 인터페이스 활성화/비활성화",
    "ip link set eth0 up",
    "ip link set eth0 down",
    "",
    "# 링크 상태 확인",
    "ip link show                  # = ip l",
    "",
    "# 라우팅 테이블 확인",
    "ip route show                 # = ip r",
    "",
    "# 기본 게이트웨이 추가/삭제",
    "ip route add default via 192.168.1.1",
    "ip route del default via 192.168.1.1",
    "```",
    "",
    "### ifconfig vs ip 비교",
    "| 항목 | ifconfig | ip |",
    "|------|----------|-----|",
    "| 패키지 | net-tools | iproute2 |",
    "| 최신 여부 | 구식 (deprecated) | **현재 표준** |",
    "| IP 확인 | `ifconfig` | `ip addr show` |",
    "| 활성화 | `ifconfig eth0 up` | `ip link set eth0 up` |",
    "| IP 설정 | `ifconfig eth0 IP` | `ip addr add IP dev eth0` |",
    "| 라우팅 | `route` | `ip route` |",
    "",
    "### 인터페이스 이름 규칙",
    "| 이름 | 설명 |",
    "|------|------|",
    "| `eth0`, `eth1` | 전통적 이더넷 |",
    "| `ens33`, `enp0s3` | 예측 가능한 이름 (systemd) |",
    "| `lo` | 루프백 (127.0.0.1) |",
    "| `wlan0`, `wlp2s0` | 무선 LAN |",
    "| `virbr0` | 가상 브릿지 (KVM) |",
    "",
    "---",
    "",
    "## 3. 네트워크 설정 파일",
    "",
    "### /etc/sysconfig/network-scripts/ (CentOS/RHEL)",
    "```bash",
    "# 인터페이스 설정 파일",
    "cat /etc/sysconfig/network-scripts/ifcfg-eth0",
    "```",
    "",
    "```",
    "TYPE=Ethernet",
    "BOOTPROTO=static              # static | dhcp | none",
    "NAME=eth0",
    "DEVICE=eth0",
    "ONBOOT=yes                    # 부팅 시 자동 활성화",
    "IPADDR=192.168.1.100",
    "NETMASK=255.255.255.0",
    "GATEWAY=192.168.1.1",
    "DNS1=8.8.8.8",
    "DNS2=8.8.4.4",
    "```",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| `BOOTPROTO` | IP 할당 방식 (static/dhcp/none) |",
    "| `ONBOOT` | 부팅 시 자동 활성화 여부 (yes/no) |",
    "| `IPADDR` | IP 주소 |",
    "| `NETMASK` | 서브넷 마스크 |",
    "| `GATEWAY` | 기본 게이트웨이 |",
    "| `DNS1`, `DNS2` | DNS 서버 |",
    "",
    "```bash",
    "# 네트워크 재시작",
    "systemctl restart network     # CentOS 7",
    "systemctl restart NetworkManager  # CentOS 8+",
    "nmcli connection reload       # NetworkManager 사용 시",
    "```",
    "",
    "### /etc/netplan/ (Ubuntu 18.04+)",
    "```yaml",
    "# /etc/netplan/01-config.yaml",
    "network:",
    "  version: 2",
    "  ethernets:",
    "    enp0s3:",
    "      dhcp4: false",
    "      addresses:",
    "        - 192.168.1.100/24",
    "      gateway4: 192.168.1.1",
    "      nameservers:",
    "        addresses: [8.8.8.8, 8.8.4.4]",
    "```",
    "",
    "```bash",
    "sudo netplan apply            # 설정 적용",
    "```",
    "",
    "---",
    "",
    "## 4. 호스트네임 관리",
    "",
    "```bash",
    "# 호스트네임 확인",
    "hostname",
    "hostnamectl",
    "",
    "# 호스트네임 변경 (영구)",
    "hostnamectl set-hostname myserver",
    "",
    "# 호스트네임 관련 파일",
    "cat /etc/hostname             # 호스트네임 저장 파일",
    "cat /etc/hosts                # 호스트네임 ↔ IP 매핑",
    "```",
    "",
    "### /etc/hosts",
    "DNS보다 **먼저** 참조되는 로컬 호스트 매핑 파일입니다.",
    "",
    "```",
    "127.0.0.1       localhost",
    "192.168.1.100   myserver myserver.example.com",
    "192.168.1.200   dbserver",
    "```",
    "",
    "---",
    "",
    "## 5. DNS 설정",
    "",
    "### /etc/resolv.conf",
    "DNS 서버를 지정하는 파일입니다.",
    "",
    "```",
    "nameserver 8.8.8.8",
    "nameserver 8.8.4.4",
    "search example.com",
    "```",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| `nameserver` | DNS 서버 주소 (최대 3개) |",
    "| `search` | 짧은 호스트명 입력 시 자동 붙는 도메인 |",
    "| `domain` | 기본 도메인 이름 |",
    "",
    "### 이름 해석 순서: /etc/nsswitch.conf",
    "```",
    "hosts: files dns myhostname",
    "```",
    "1. `files` → `/etc/hosts` 먼저 확인",
    "2. `dns` → `/etc/resolv.conf`의 DNS 서버 조회",
    "",
    "### DNS 조회 명령어",
    "```bash",
    "# nslookup - 대화형 DNS 조회",
    "nslookup google.com",
    "nslookup google.com 8.8.8.8   # 특정 DNS 서버 지정",
    "",
    "# dig - 상세한 DNS 조회",
    "dig google.com",
    "dig google.com A               # A 레코드 조회",
    "dig google.com MX              # 메일 서버 조회",
    "dig @8.8.8.8 google.com        # 특정 DNS 서버 사용",
    "dig +short google.com          # 간략 출력",
    "",
    "# host - 간단한 DNS 조회",
    "host google.com",
    "host 8.8.8.8                   # 역방향 조회",
    "```",
    "",
    "---",
    "",
    "## 6. 라우팅 (Routing)",
    "",
    "### 라우팅 테이블 확인",
    "```bash",
    "# 라우팅 테이블 확인",
    "route -n                       # 전통 방식",
    "ip route show                  # 현대 방식",
    "netstat -rn                    # netstat으로 확인",
    "```",
    "",
    "### route 명령어",
    "```bash",
    "# 기본 게이트웨이 추가",
    "route add default gw 192.168.1.1",
    "",
    "# 기본 게이트웨이 삭제",
    "route del default gw 192.168.1.1",
    "",
    "# 특정 네트워크 대역 라우팅 추가",
    "route add -net 10.0.0.0/8 gw 192.168.1.254",
    "",
    "# 특정 호스트 라우팅 추가",
    "route add -host 10.0.0.5 gw 192.168.1.254",
    "```",
    "",
    "### ip route 명령어",
    "```bash",
    "# 기본 게이트웨이 추가",
    "ip route add default via 192.168.1.1 dev eth0",
    "",
    "# 특정 네트워크 라우팅 추가",
    "ip route add 10.0.0.0/8 via 192.168.1.254",
    "",
    "# 라우팅 삭제",
    "ip route del 10.0.0.0/8",
    "```",
    "",
    "### ARP (Address Resolution Protocol)",
    "IP 주소 → MAC 주소 변환 프로토콜입니다.",
    "",
    "```bash",
    "arp -a                         # ARP 캐시 테이블 확인",
    "arp -d 192.168.1.1             # 특정 항목 삭제",
    "arp -s 192.168.1.50 AA:BB:CC:DD:EE:FF  # 정적 ARP 추가",
    "",
    "# ip 명령어 사용",
    "ip neigh show                  # ARP 테이블 확인",
    "ip neigh flush all             # ARP 캐시 전체 삭제",
    "```",
    "",
    "---",
    "",
    "## 7. 네트워크 진단 명령어",
    "",
    "### ping (연결 확인)",
    "ICMP 프로토콜로 대상 호스트와의 **연결 상태**를 확인합니다.",
    "",
    "```bash",
    "ping google.com                # Ctrl+C로 중지",
    "ping -c 5 google.com           # 5번만 전송",
    "ping -i 2 google.com           # 2초 간격으로 전송",
    "ping -s 1000 google.com        # 패킷 크기 지정 (바이트)",
    "ping -W 3 google.com           # 응답 대기 시간 3초",
    "```",
    "",
    "### traceroute / tracepath (경로 추적)",
    "목적지까지의 **네트워크 경로**(홉)를 추적합니다.",
    "",
    "```bash",
    "traceroute google.com",
    "traceroute -n google.com       # IP만 표시 (DNS 해석 안 함)",
    "",
    "tracepath google.com           # root 권한 불필요",
    "```",
    "",
    "### netstat (네트워크 상태 확인)",
    "```bash",
    "# 열린 포트와 연결 상태 확인",
    "netstat -tlnp                  # TCP 리스닝 포트 + 프로세스",
    "netstat -ulnp                  # UDP 리스닝 포트 + 프로세스",
    "netstat -an                    # 모든 연결 (숫자 표기)",
    "netstat -rn                    # 라우팅 테이블",
    "netstat -i                     # 인터페이스 통계",
    "netstat -s                     # 프로토콜별 통계",
    "```",
    "",
    "| 옵션 | 의미 |",
    "|------|------|",
    "| `-t` | TCP |",
    "| `-u` | UDP |",
    "| `-l` | LISTEN 상태만 |",
    "| `-n` | 숫자로 표시 (이름 해석 안 함) |",
    "| `-p` | 프로세스 이름/PID 표시 |",
    "| `-a` | 모든 연결 |",
    "| `-r` | 라우팅 테이블 |",
    "| `-i` | 인터페이스 통계 |",
    "",
    "### ss (Socket Statistics, netstat 대체)",
    "`netstat`보다 빠르고 상세한 **현대적 소켓 조회** 명령어입니다.",
    "",
    "```bash",
    "ss -tlnp                       # TCP 리스닝 포트 + 프로세스",
    "ss -ulnp                       # UDP 리스닝 포트",
    "ss -an                         # 모든 소켓",
    "ss -s                          # 소켓 요약 통계",
    "ss -o state established        # ESTABLISHED 상태 소켓",
    "ss -t dst 192.168.1.100        # 특정 목적지 연결",
    "```",
    "",
    "### netstat vs ss",
    "| 항목 | netstat | ss |",
    "|------|---------|-----|",
    "| 패키지 | net-tools | iproute2 |",
    "| 속도 | 느림 | **빠름** |",
    "| 최신 여부 | 구식 | **현재 표준** |",
    "| 옵션 | 동일한 주요 옵션 (-t, -u, -l, -n, -p) | 동일 |",
    "",
    "---",
    "",
    "## 8. 파일 전송",
    "",
    "### scp (Secure Copy)",
    "SSH를 통해 **암호화된 파일 전송**을 합니다.",
    "",
    "```bash",
    "# 로컬 → 원격",
    "scp file.txt user@192.168.1.200:/home/user/",
    "scp -r mydir/ user@192.168.1.200:/home/user/",
    "",
    "# 원격 → 로컬",
    "scp user@192.168.1.200:/home/user/file.txt ./",
    "scp -r user@192.168.1.200:/home/user/mydir/ ./",
    "",
    "# 포트 지정",
    "scp -P 2222 file.txt user@192.168.1.200:/home/user/",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `-r` | 디렉터리 재귀 복사 |",
    "| `-P 포트` | SSH 포트 지정 |",
    "| `-p` | 타임스탬프, 권한 유지 |",
    "| `-C` | 압축 전송 |",
    "",
    "### sftp (SSH File Transfer Protocol)",
    "SSH 기반의 **대화형** 파일 전송 프로토콜입니다.",
    "",
    "```bash",
    "sftp user@192.168.1.200",
    "",
    "# sftp 내부 명령어",
    "sftp> ls                       # 원격 파일 목록",
    "sftp> lls                      # 로컬 파일 목록",
    "sftp> cd /home/user            # 원격 디렉터리 이동",
    "sftp> lcd /tmp                 # 로컬 디렉터리 이동",
    "sftp> get file.txt             # 원격 → 로컬 다운로드",
    "sftp> put file.txt             # 로컬 → 원격 업로드",
    "sftp> mget *.log               # 여러 파일 다운로드",
    "sftp> mput *.conf              # 여러 파일 업로드",
    "sftp> bye                      # 종료",
    "```",
    "",
    "### ftp (File Transfer Protocol)",
    "**비암호화** 파일 전송 프로토콜입니다 (보안에 취약).",
    "",
    "```bash",
    "ftp 192.168.1.200",
    "",
    "ftp> ls                        # 파일 목록",
    "ftp> get file.txt              # 다운로드",
    "ftp> put file.txt              # 업로드",
    "ftp> mget *.log                # 여러 파일 다운로드",
    "ftp> binary                    # 바이너리 모드 전환",
    "ftp> ascii                     # ASCII 모드 전환",
    "ftp> bye                       # 종료",
    "```",
    "",
    "### scp vs sftp vs ftp",
    "| 항목 | scp | sftp | ftp |",
    "|------|-----|------|-----|",
    "| 암호화 | **O** (SSH) | **O** (SSH) | **X** |",
    "| 대화형 | X (명령줄) | **O** | **O** |",
    "| 포트 | 22 (SSH) | 22 (SSH) | 20 (데이터), 21 (제어) |",
    "| 권장 여부 | **권장** | **권장** | 비권장 |",
    "",
    "---",
    "",
    "## 9. 주요 서비스 포트 (시험 필수!)",
    "",
    "| 포트 | 프로토콜 | 서비스 |",
    "|------|----------|--------|",
    "| 20 | TCP | FTP (데이터 전송) |",
    "| 21 | TCP | FTP (제어) |",
    "| 22 | TCP | **SSH** (보안 원격 접속) |",
    "| 23 | TCP | Telnet (비암호화 원격 접속) |",
    "| 25 | TCP | **SMTP** (메일 전송) |",
    "| 53 | TCP/UDP | **DNS** (도메인 이름 해석) |",
    "| 67 | UDP | DHCP (서버) |",
    "| 68 | UDP | DHCP (클라이언트) |",
    "| 69 | UDP | TFTP (간이 파일 전송) |",
    "| 80 | TCP | **HTTP** (웹) |",
    "| 110 | TCP | **POP3** (메일 수신) |",
    "| 111 | TCP/UDP | RPC (portmapper) |",
    "| 123 | UDP | **NTP** (시간 동기화) |",
    "| 137-139 | TCP/UDP | NetBIOS (삼바/윈도우 공유) |",
    "| 143 | TCP | **IMAP** (메일 수신) |",
    "| 161 | UDP | SNMP (네트워크 관리) |",
    "| 443 | TCP | **HTTPS** (보안 웹) |",
    "| 465 | TCP | SMTPS (보안 메일 전송) |",
    "| 514 | UDP | Syslog (로그 전송) |",
    "| 587 | TCP | SMTP (메일 전송, 인증) |",
    "| 631 | TCP | **CUPS** (인쇄 서비스) |",
    "| 993 | TCP | IMAPS (보안 IMAP) |",
    "| 995 | TCP | POP3S (보안 POP3) |",
    "| 2049 | TCP/UDP | **NFS** (네트워크 파일 시스템) |",
    "| 3306 | TCP | **MySQL/MariaDB** |",
    "| 5432 | TCP | **PostgreSQL** |",
    "| 6379 | TCP | Redis |",
    "",
    "```bash",
    "# 잘 알려진 포트 목록 확인",
    "cat /etc/services",
    "grep ssh /etc/services",
    "grep http /etc/services",
    "```",
    "",
    "---",
    "",
    "## 10. 방화벽 (Firewall)",
    "",
    "### firewalld (CentOS 7+ / RHEL 7+)",
    "**zone** 기반의 동적 방화벽으로, `firewall-cmd`로 관리합니다.",
    "",
    "```bash",
    "# 상태 확인",
    "systemctl status firewalld",
    "firewall-cmd --state",
    "",
    "# 기본 zone 확인",
    "firewall-cmd --get-default-zone",
    "firewall-cmd --get-active-zones",
    "",
    "# 허용된 서비스/포트 확인",
    "firewall-cmd --list-all",
    "firewall-cmd --list-services",
    "firewall-cmd --list-ports",
    "",
    "# 서비스 허용 (영구)",
    "firewall-cmd --permanent --add-service=http",
    "firewall-cmd --permanent --add-service=https",
    "",
    "# 포트 허용 (영구)",
    "firewall-cmd --permanent --add-port=8080/tcp",
    "firewall-cmd --permanent --add-port=3306/tcp",
    "",
    "# 서비스/포트 차단 (영구)",
    "firewall-cmd --permanent --remove-service=ftp",
    "firewall-cmd --permanent --remove-port=8080/tcp",
    "",
    "# 설정 반영 (reload 필수!)",
    "firewall-cmd --reload",
    "```",
    "",
    "### 주요 zone",
    "| zone | 설명 |",
    "|------|------|",
    "| `public` | 기본 zone, 신뢰하지 않는 공용 네트워크 |",
    "| `trusted` | 모든 트래픽 허용 |",
    "| `home` | 홈 네트워크, 대부분 허용 |",
    "| `internal` | 내부 네트워크 |",
    "| `dmz` | DMZ 영역 |",
    "| `block` | 모든 수신 차단 (거부 응답) |",
    "| `drop` | 모든 수신 차단 (응답 없음) |",
    "",
    "### iptables (전통 방식)",
    "리눅스 커널의 **netfilter** 프레임워크를 사용하는 패킷 필터링 도구입니다.",
    "",
    "```bash",
    "# 현재 규칙 확인",
    "iptables -L                    # 전체 규칙 목록",
    "iptables -L -n -v              # 상세 + 숫자 표기",
    "iptables -L --line-numbers     # 규칙 번호 포함",
    "",
    "# 규칙 추가 (-A: Append)",
    "iptables -A INPUT -p tcp --dport 80 -j ACCEPT",
    "iptables -A INPUT -p tcp --dport 22 -j ACCEPT",
    "iptables -A INPUT -p tcp --dport 3306 -j DROP",
    "",
    "# 규칙 삽입 (-I: Insert, 맨 위에)",
    "iptables -I INPUT 1 -p tcp --dport 443 -j ACCEPT",
    "",
    "# 규칙 삭제 (-D: Delete)",
    "iptables -D INPUT -p tcp --dport 3306 -j DROP",
    "iptables -D INPUT 3             # 3번째 규칙 삭제",
    "",
    "# 모든 규칙 삭제",
    "iptables -F                    # Flush",
    "",
    "# 기본 정책 설정 (-P: Policy)",
    "iptables -P INPUT DROP         # 기본적으로 모든 입력 차단",
    "iptables -P OUTPUT ACCEPT      # 모든 출력 허용",
    "iptables -P FORWARD DROP       # 포워딩 차단",
    "",
    "# 규칙 저장/복원",
    "iptables-save > /etc/iptables.rules",
    "iptables-restore < /etc/iptables.rules",
    "service iptables save          # CentOS",
    "```",
    "",
    "### iptables 체인",
    "| 체인 | 설명 |",
    "|------|------|",
    "| `INPUT` | 서버로 **들어오는** 패킷 |",
    "| `OUTPUT` | 서버에서 **나가는** 패킷 |",
    "| `FORWARD` | 서버를 **통과하는** 패킷 (라우터 역할 시) |",
    "",
    "### iptables 타겟",
    "| 타겟 | 설명 |",
    "|------|------|",
    "| `ACCEPT` | 패킷 허용 |",
    "| `DROP` | 패킷 차단 (응답 없음) |",
    "| `REJECT` | 패킷 차단 (거부 응답 전송) |",
    "| `LOG` | 로그 기록 후 다음 규칙 진행 |",
    "",
    "---",
    "",
    "## 11. TCP Wrapper (접근 제어)",
    "",
    "서비스별로 **호스트 기반 접근 제어**를 하는 간단한 방화벽입니다.",
    "",
    "| 파일 | 설명 |",
    "|------|------|",
    "| `/etc/hosts.allow` | 접근을 **허용**할 호스트 |",
    "| `/etc/hosts.deny` | 접근을 **차단**할 호스트 |",
    "",
    "### 우선순위",
    "```",
    "1. hosts.allow 먼저 확인 → 일치하면 허용",
    "2. hosts.deny 확인 → 일치하면 차단",
    "3. 두 파일 모두 일치 없으면 → 허용",
    "```",
    "",
    "### 설정 형식",
    "```",
    "# 형식: 서비스 : 호스트",
    "",
    "# /etc/hosts.allow - SSH는 특정 IP만 허용",
    "sshd : 192.168.1.0/255.255.255.0",
    "sshd : 10.0.0.5",
    "",
    "# /etc/hosts.deny - SSH 나머지 전부 차단",
    "sshd : ALL",
    "",
    "# 모든 서비스에 대해 전부 차단 후 allow로 허용 (화이트리스트 방식)",
    "ALL : ALL                      # hosts.deny에 설정",
    "sshd : 192.168.1.0/24          # hosts.allow에 설정",
    "```",
    "",
    "---",
    "",
    "## 12. NetworkManager와 nmcli",
    "",
    "**NetworkManager**는 네트워크를 자동 관리하는 데몬이며, `nmcli`로 CLI 관리합니다.",
    "",
    "```bash",
    "# 상태 확인",
    "nmcli general status",
    "nmcli device status",
    "nmcli connection show",
    "",
    "# 연결 상세 확인",
    "nmcli connection show \"유선 연결 1\"",
    "",
    "# 고정 IP 설정",
    "nmcli connection modify eth0 ipv4.addresses 192.168.1.100/24",
    "nmcli connection modify eth0 ipv4.gateway 192.168.1.1",
    "nmcli connection modify eth0 ipv4.dns \"8.8.8.8 8.8.4.4\"",
    "nmcli connection modify eth0 ipv4.method manual",
    "",
    "# DHCP로 변경",
    "nmcli connection modify eth0 ipv4.method auto",
    "",
    "# 연결 활성화/비활성화",
    "nmcli connection up eth0",
    "nmcli connection down eth0",
    "",
    "# 새 연결 추가",
    "nmcli connection add type ethernet con-name mycon ifname eth0 ipv4.addresses 192.168.1.100/24 ipv4.gateway 192.168.1.1 ipv4.method manual",
    "```",
    "",
    "---",
    "",
    "## 13. 기타 네트워크 유틸리티",
    "",
    "```bash",
    "# wget - 파일 다운로드",
    "wget http://example.com/file.tar.gz",
    "wget -O output.html http://example.com",
    "wget -c http://example.com/bigfile.iso  # 이어받기",
    "",
    "# curl - HTTP 요청",
    "curl http://example.com",
    "curl -O http://example.com/file.tar.gz  # 파일 다운로드",
    "curl -I http://example.com              # 헤더만 확인",
    "curl -X POST -d 'data=value' http://example.com/api",
    "",
    "# nc (netcat) - 네트워크 연결 테스트",
    "nc -zv 192.168.1.100 22        # TCP 포트 스캔",
    "nc -zv 192.168.1.100 80-100    # 포트 범위 스캔",
    "nc -l 8080                     # 8080 포트에서 수신 대기",
    "",
    "# ethtool - NIC 정보 확인",
    "ethtool eth0                   # 인터페이스 상세 정보",
    "",
    "# mtr - ping + traceroute 통합",
    "mtr google.com",
    "",
    "# whois - 도메인 정보 조회",
    "whois google.com",
    "```",
    "",
    "---",
    "",
    "## 14. 네트워크 문제 해결 순서",
    "",
    "네트워크 장애 발생 시 아래 순서로 점검합니다.",
    "",
    "```",
    "1단계: 인터페이스 확인",
    "  → ip addr show / ifconfig",
    "  → IP가 할당되어 있는지, 인터페이스가 UP인지",
    "",
    "2단계: 로컬 연결 확인",
    "  → ping 127.0.0.1 (루프백)",
    "  → ping 자기 IP",
    "",
    "3단계: 게이트웨이 연결 확인",
    "  → ping 게이트웨이 IP",
    "  → ip route show (기본 경로 확인)",
    "",
    "4단계: 외부 연결 확인",
    "  → ping 8.8.8.8 (DNS IP 직접)",
    "  → 성공하면 네트워크 OK, DNS 문제 가능",
    "",
    "5단계: DNS 확인",
    "  → ping google.com",
    "  → cat /etc/resolv.conf",
    "  → nslookup google.com",
    "",
    "6단계: 포트/방화벽 확인",
    "  → ss -tlnp / netstat -tlnp",
    "  → firewall-cmd --list-all",
    "  → iptables -L -n",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "- **IP 설정**: `ifconfig`(구식) → `ip addr`(현대), 설정 파일로 영구 적용",
    "- **DNS**: `/etc/resolv.conf`(DNS 서버), `/etc/hosts`(로컬 매핑), `nslookup`/`dig`/`host`",
    "- **라우팅**: `route`(구식) → `ip route`(현대), `arp` → `ip neigh`",
    "- **진단**: `ping`(연결), `traceroute`(경로), `netstat`/`ss`(포트/소켓)",
    "- **파일 전송**: `scp`(단발), `sftp`(대화형), 둘 다 SSH 기반 암호화",
    "- **주요 포트**: SSH(22), HTTP(80), HTTPS(443), DNS(53), SMTP(25), FTP(20/21)",
    "- **방화벽**: `firewalld`(zone 기반) / `iptables`(체인+규칙), `--permanent` + `--reload`",
    "- **TCP Wrapper**: `hosts.allow` > `hosts.deny` 순서, 서비스별 접근 제어",
    "- **문제 해결**: 인터페이스 → 로컬 → 게이트웨이 → 외부 → DNS → 방화벽 순으로 점검"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
