<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-partition",
  title: "리눅스 파티션(Partition)이란?",
  date: "2026-03-11",
  summary: "파티션은 하나의 디스크를 논리적으로 나눈 영역입니다. MBR/GPT 파티션 테이블, 파일시스템(ext4, xfs), swap, 마운트, fdisk/lsblk 명령어까지 정리합니다.",
  category: "Technology/Linux",
  tags: ["linux","partition","filesystem","mount","disk","mbr","gpt","basics"],
  content: [
    "## 한 줄 요약",
    "**파티션(Partition)**은 하나의 물리 디스크를 **논리적으로 나눈 독립된 영역**입니다. 각 파티션에 파일시스템을 만들고 마운트하여 사용합니다.",
    "",
    "## 왜 파티션을 나눌까",
    "",
    "| 이유 | 설명 |",
    "|------|------|",
    "| OS와 데이터 분리 | 시스템을 재설치해도 데이터 파티션은 보존 |",
    "| 보안·격리 | /home, /var, /tmp를 분리하면 한 영역이 가득 차도 시스템 전체가 멈추지 않음 |",
    "| 멀티부팅 | 하나의 디스크에 여러 OS를 설치 가능 |",
    "| 성능 | swap 영역을 별도 파티션으로 두면 관리가 명확해짐 |",
    "| 백업·관리 | 파티션 단위로 백업·스냅샷이 가능 |",
    "",
    "## 디스크 → 파티션 → 파일시스템 → 마운트",
    "",
    "리눅스에서 디스크를 사용하는 전체 흐름입니다.",
    "",
    "```",
    "물리 디스크 (/dev/sda)",
    "  ├─ 파티션 1 (/dev/sda1) → 파일시스템(ext4) → 마운트(/boot)",
    "  ├─ 파티션 2 (/dev/sda2) → 파일시스템(ext4) → 마운트(/)",
    "  ├─ 파티션 3 (/dev/sda3) → 파일시스템(ext4) → 마운트(/home)",
    "  └─ 파티션 4 (/dev/sda4) → swap                → swap 영역",
    "```",
    "",
    "| 단계 | 설명 |",
    "|------|------|",
    "| 디스크 | 물리적 저장 장치 (/dev/sda, /dev/nvme0n1 등) |",
    "| 파티션 | 디스크를 논리적으로 나눈 영역 (/dev/sda1, /dev/sda2 등) |",
    "| 파일시스템 | 파티션 위에 만드는 데이터 구조 (ext4, xfs 등) |",
    "| 마운트 | 파일시스템을 디렉토리 트리의 특정 경로에 연결 |",
    "",
    "## 파티션 테이블: MBR vs GPT",
    "",
    "파티션 테이블은 디스크의 파티션 구조 정보를 저장하는 방식입니다.",
    "",
    "### MBR (Master Boot Record)",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 등장 | 1983년 (IBM PC) |",
    "| 최대 디스크 크기 | 2TB |",
    "| 최대 주 파티션 | 4개 (확장 파티션 사용 시 논리 파티션으로 더 나눌 수 있음) |",
    "| 부트로더 위치 | 디스크 첫 512바이트 |",
    "| 복구 | 파티션 테이블이 1개뿐이라 손상 시 복구 어려움 |",
    "",
    "### GPT (GUID Partition Table)",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 등장 | UEFI 표준과 함께 |",
    "| 최대 디스크 크기 | 약 9.4ZB (사실상 무제한) |",
    "| 최대 파티션 수 | 128개 (기본, 확장 불필요) |",
    "| 부트 방식 | UEFI 펌웨어 사용 |",
    "| 복구 | 파티션 테이블 백업이 디스크 끝에도 저장되어 복구 용이 |",
    "",
    "### MBR vs GPT 비교",
    "| 기준 | MBR | GPT |",
    "|------|-----|-----|",
    "| 디스크 2TB 초과 | 불가 | 가능 |",
    "| 파티션 수 | 주 4개 (논리 파티션으로 확장) | 128개 |",
    "| 부팅 방식 | BIOS (Legacy) | UEFI |",
    "| 안정성 | 낮음 (백업 없음) | 높음 (이중 저장) |",
    "| 현재 권장 | 레거시 환경 | 신규 설치 시 권장 |",
    "",
    "최근 대부분의 시스템은 **GPT + UEFI** 조합을 사용합니다.",
    "",
    "## MBR 파티션 종류",
    "",
    "MBR에서는 파티션이 3가지로 나뉩니다.",
    "",
    "| 종류 | 설명 |",
    "|------|------|",
    "| 주 파티션 (Primary) | 직접 파일시스템을 만들 수 있는 파티션. 최대 4개 |",
    "| 확장 파티션 (Extended) | 주 파티션 4개 제한을 넘기기 위한 컨테이너. 1개만 가능 |",
    "| 논리 파티션 (Logical) | 확장 파티션 안에 만드는 파티션. 번호가 5부터 시작 |",
    "",
    "```",
    "/dev/sda",
    "  ├─ sda1  (Primary)   → /boot",
    "  ├─ sda2  (Primary)   → /",
    "  ├─ sda3  (Extended)",
    "  │   ├─ sda5 (Logical) → /home",
    "  │   └─ sda6 (Logical) → swap",
    "  └─ sda4  (Primary)   → /var",
    "```",
    "",
    "GPT에서는 이런 구분이 없고, 모든 파티션이 동등합니다.",
    "",
    "## 파일시스템",
    "",
    "파티션을 만든 뒤, 그 위에 **파일시스템**을 생성해야 파일을 저장할 수 있습니다.",
    "",
    "### 리눅스에서 자주 쓰는 파일시스템",
    "| 파일시스템 | 특징 |",
    "|-----------|------|",
    "| ext4 | 리눅스 표준. 안정적이고 범용적. 대부분의 배포판 기본값 |",
    "| xfs | 대용량 파일·고성능에 강함. RHEL/CentOS 기본값 |",
    "| btrfs | 스냅샷, 압축, 서브볼륨 지원. 차세대 파일시스템 |",
    "| f2fs | 플래시 메모리(SSD/eMMC) 최적화 |",
    "| vfat (FAT32) | USB, EFI System Partition 등 호환용 |",
    "| swap | 메모리 부족 시 디스크를 가상 메모리로 사용하는 영역 |",
    "",
    "### 파일시스템 생성 명령어",
    "```bash",
    "mkfs.ext4 /dev/sda2",
    "mkfs.xfs /dev/sda3",
    "mkswap /dev/sda4",
    "```",
    "",
    "## Swap 파티션",
    "",
    "Swap은 **물리 메모리(RAM)가 부족할 때 디스크 일부를 가상 메모리로 사용하는 영역**입니다.",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| 역할 | RAM 부족 시 데이터를 디스크로 내보내고(swap out), 필요할 때 다시 불러옴(swap in) |",
    "| 크기 기준 (일반적) | RAM 크기와 비슷하거나 2배 (용도에 따라 다름) |",
    "| 파티션 vs 파일 | 별도 파티션으로 만들거나, 파일(swap file)로도 가능 |",
    "",
    "```bash",
    "# swap 파티션 생성 및 활성화",
    "mkswap /dev/sda4",
    "swapon /dev/sda4",
    "",
    "# swap 파일로 만들기",
    "fallocate -l 2G /swapfile",
    "chmod 600 /swapfile",
    "mkswap /swapfile",
    "swapon /swapfile",
    "```",
    "",
    "## 마운트(Mount)",
    "",
    "파일시스템을 디렉토리 트리의 특정 경로에 연결하는 것이 **마운트**입니다.",
    "",
    "```bash",
    "# 수동 마운트",
    "mount /dev/sda2 /mnt",
    "",
    "# 마운트 해제",
    "umount /mnt",
    "```",
    "",
    "### /etc/fstab (자동 마운트 설정)",
    "부팅 시 자동으로 마운트할 파티션을 `/etc/fstab`에 등록합니다.",
    "",
    "```",
    "# <장치>          <마운트포인트>  <파일시스템>  <옵션>     <dump> <pass>",
    "/dev/sda2         /              ext4         defaults   0      1",
    "/dev/sda1         /boot          ext4         defaults   0      2",
    "/dev/sda3         /home          ext4         defaults   0      2",
    "/dev/sda4         none           swap         sw         0      0",
    "```",
    "",
    "| 필드 | 설명 |",
    "|------|------|",
    "| 장치 | 파티션 경로 또는 UUID |",
    "| 마운트포인트 | 연결할 디렉토리 경로 |",
    "| 파일시스템 | ext4, xfs, swap 등 |",
    "| 옵션 | defaults, noatime, ro 등 |",
    "| dump | 백업 여부 (보통 0) |",
    "| pass | 부팅 시 fsck 검사 순서 (루트=1, 나머지=2, 검사 안 함=0) |",
    "",
    "## 디스크·파티션 확인 명령어",
    "",
    "### lsblk (블록 장치 목록)",
    "```bash",
    "lsblk",
    "```",
    "```",
    "NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT",
    "sda      8:0    0   100G  0 disk",
    "├─sda1   8:1    0   512M  0 part /boot",
    "├─sda2   8:2    0    50G  0 part /",
    "├─sda3   8:3    0    45G  0 part /home",
    "└─sda4   8:4    0   4.5G  0 part [SWAP]",
    "```",
    "",
    "### fdisk (MBR 파티션 관리)",
    "```bash",
    "sudo fdisk -l           # 파티션 목록 확인",
    "sudo fdisk /dev/sda     # 파티션 편집 (인터랙티브)",
    "```",
    "",
    "### gdisk (GPT 파티션 관리)",
    "```bash",
    "sudo gdisk -l /dev/sda  # GPT 파티션 목록 확인",
    "sudo gdisk /dev/sda     # GPT 파티션 편집",
    "```",
    "",
    "### parted (MBR/GPT 모두 지원)",
    "```bash",
    "sudo parted /dev/sda print",
    "```",
    "",
    "### df (마운트된 파티션 사용량)",
    "```bash",
    "df -h",
    "```",
    "```",
    "Filesystem      Size  Used Avail Use% Mounted on",
    "/dev/sda2        50G   12G   36G  25% /",
    "/dev/sda1       512M   80M  400M  17% /boot",
    "/dev/sda3        45G   20G   23G  47% /home",
    "```",
    "",
    "### blkid (UUID·파일시스템 타입 확인)",
    "```bash",
    "sudo blkid",
    "```",
    "```",
    "/dev/sda1: UUID=\"a1b2c3d4-...\" TYPE=\"ext4\"",
    "/dev/sda2: UUID=\"e5f6g7h8-...\" TYPE=\"ext4\"",
    "```",
    "",
    "fstab에서 장치 경로 대신 **UUID**를 쓰면 디스크 순서가 바뀌어도 안전합니다.",
    "",
    "## 실전: 파티션 나누기 예시",
    "",
    "### 서버 권장 파티션 구성",
    "| 파티션 | 마운트 | 크기 기준 | 이유 |",
    "|--------|--------|-----------|------|",
    "| /boot | /boot | 512MB~1GB | 커널·부트로더 |",
    "| / | / | 20~50GB | 시스템·패키지 |",
    "| /home | /home | 용도에 따라 | 사용자 데이터 분리 |",
    "| /var | /var | 10~50GB | 로그·DB·캐시 (가득 차도 시스템에 영향 최소화) |",
    "| swap | - | RAM×1~2 | 가상 메모리 |",
    "| /tmp | /tmp | 2~10GB | 임시 파일 격리 |",
    "",
    "### 데스크톱 간단 구성",
    "| 파티션 | 마운트 | 설명 |",
    "|--------|--------|------|",
    "| EFI System Partition | /boot/efi | UEFI 부팅용 (FAT32, 512MB) |",
    "| / | / | 시스템 전체 |",
    "| /home | /home | 사용자 데이터 (재설치 시 보존) |",
    "| swap | - | 가상 메모리 |",
    "",
    "## 주의사항",
    "",
    "### 1) 파티션 변경은 데이터 손실 위험",
    "이미 사용 중인 파티션의 크기를 변경하거나 삭제하면 데이터가 사라질 수 있습니다. 반드시 **백업 후** 작업합니다.",
    "",
    "### 2) 루트(/) 파티션은 반드시 필요",
    "리눅스는 최소한 하나의 루트(/) 파티션이 있어야 부팅됩니다.",
    "",
    "### 3) UEFI 부팅 시 ESP 필요",
    "GPT + UEFI 환경에서는 **EFI System Partition(ESP)**이 필요합니다. FAT32로 포맷하고, /boot/efi에 마운트합니다.",
    "",
    "### 4) UUID 사용 권장",
    "/etc/fstab에서 /dev/sda1 같은 장치 경로 대신 UUID를 사용하면, 디스크가 추가되거나 순서가 바뀌어도 문제없이 마운트됩니다.",
    "",
    "---",
    "### 요약",
    "파티션은 디스크를 논리적으로 나눈 영역이며, MBR(2TB 제한, 최대 4개 주 파티션)과 GPT(사실상 무제한, 128개 파티션)로 관리합니다. 파티션 위에 파일시스템(ext4, xfs 등)을 만들고 마운트하여 사용하며, lsblk·fdisk·df·blkid 명령어로 확인·관리합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
