<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-service-daemon",
  title: "리눅스 서비스·데몬 관리 - systemd, 런레벨, 부팅 과정 총정리",
  date: "2026-03-04",
  summary: "리눅스 서비스와 데몬의 개념, systemctl 명령어, Unit 파일 구조, 런레벨과 systemd 타겟, 부팅 과정(BIOS→GRUB→Kernel→systemd), xinetd, 시스템 종료·재부팅 명령어까지 실전 예제와 함께 정리합니다.",
  category: "Technology/Linux",
  tags: ["linux","systemd","daemon","service","systemctl","runlevel","boot","grub","xinetd","target"],
  content: [
    "## 한 줄 요약",
    "리눅스에서 백그라운드로 실행되는 프로그램을 **데몬(Daemon)**이라 하고, **systemctl**로 관리합니다.",
    "",
    "---",
    "",
    "## 1. 데몬(Daemon)이란?",
    "",
    "데몬은 사용자의 직접적인 조작 없이 **백그라운드에서 실행**되는 프로세스입니다.",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| 이름 규칙 | 보통 `d`로 끝남 (httpd, sshd, crond, mysqld) |",
    "| 실행 방식 | 부팅 시 자동 시작 또는 수동 시작 |",
    "| 부모 프로세스 | PID 1 (systemd 또는 init)의 자식 프로세스 |",
    "| 터미널 | 제어 터미널 없이 동작 |",
    "",
    "### 주요 데몬 목록",
    "| 데몬 | 서비스 | 설명 |",
    "|------|--------|------|",
    "| `httpd` / `apache2` | 웹 서버 | Apache HTTP Server |",
    "| `nginx` | 웹 서버 | Nginx |",
    "| `sshd` | 원격 접속 | SSH 서버 |",
    "| `crond` | 스케줄링 | cron 작업 예약 |",
    "| `mysqld` / `mariadbd` | 데이터베이스 | MySQL / MariaDB |",
    "| `named` | DNS | BIND DNS 서버 |",
    "| `postfix` | 메일 | 메일 전송 서버 (SMTP) |",
    "| `dovecot` | 메일 | 메일 수신 서버 (IMAP/POP3) |",
    "| `vsftpd` | 파일 전송 | FTP 서버 |",
    "| `smbd` / `nmbd` | 파일 공유 | Samba (Windows 공유) |",
    "| `nfs-server` | 파일 공유 | NFS 서버 |",
    "| `firewalld` | 방화벽 | 동적 방화벽 |",
    "| `NetworkManager` | 네트워크 | 네트워크 관리 |",
    "| `rsyslogd` | 로깅 | 시스템 로그 |",
    "| `cups` / `cupsd` | 인쇄 | 인쇄 서비스 |",
    "",
    "---",
    "",
    "## 2. init vs systemd",
    "",
    "### SysVinit (init)",
    "전통적인 초기화 시스템으로, `/etc/init.d/`에 있는 **쉘 스크립트**로 서비스를 관리합니다.",
    "",
    "```bash",
    "# SysVinit 방식 (구식)",
    "service httpd start",
    "service httpd stop",
    "service httpd restart",
    "service httpd status",
    "",
    "# 부팅 시 자동 시작 설정",
    "chkconfig httpd on",
    "chkconfig httpd off",
    "chkconfig --list",
    "```",
    "",
    "### systemd",
    "**PID 1**로 실행되는 현대적 초기화 시스템입니다. CentOS 7, Ubuntu 15.04 이후 기본 사용됩니다.",
    "",
    "| 항목 | SysVinit (init) | systemd |",
    "|------|-----------------|---------|",
    "| PID 1 | `/sbin/init` | `/usr/lib/systemd/systemd` |",
    "| 서비스 관리 | `service` 명령어 | **`systemctl`** 명령어 |",
    "| 부팅 설정 | `chkconfig` | `systemctl enable/disable` |",
    "| 설정 파일 | `/etc/init.d/` 쉘 스크립트 | **Unit 파일** (.service) |",
    "| 부팅 속도 | 순차 실행 (느림) | **병렬 실행** (빠름) |",
    "| 의존성 | 수동 관리 | 자동 의존성 해결 |",
    "| 로그 | 파일 기반 | **journalctl** (바이너리) |",
    "| 런레벨 | 0~6 (숫자) | **target** (이름) |",
    "",
    "---",
    "",
    "## 3. systemctl 명령어 (핵심!)",
    "",
    "### 서비스 제어",
    "```bash",
    "# 서비스 시작",
    "systemctl start httpd",
    "",
    "# 서비스 중지",
    "systemctl stop httpd",
    "",
    "# 서비스 재시작 (중지 후 시작)",
    "systemctl restart httpd",
    "",
    "# 서비스 리로드 (설정만 다시 읽기, 중단 없음)",
    "systemctl reload httpd",
    "",
    "# 리로드 가능하면 리로드, 불가능하면 재시작",
    "systemctl reload-or-restart httpd",
    "",
    "# 서비스 상태 확인",
    "systemctl status httpd",
    "```",
    "",
    "### 부팅 시 자동 시작",
    "```bash",
    "# 부팅 시 자동 시작 등록",
    "systemctl enable httpd",
    "",
    "# 부팅 시 자동 시작 해제",
    "systemctl disable httpd",
    "",
    "# enable + 즉시 start",
    "systemctl enable --now httpd",
    "",
    "# disable + 즉시 stop",
    "systemctl disable --now httpd",
    "",
    "# 자동 시작 등록 여부 확인",
    "systemctl is-enabled httpd",
    "```",
    "",
    "### 서비스 상태 조회",
    "```bash",
    "# 실행 중인지 확인",
    "systemctl is-active httpd",
    "",
    "# 실패 여부 확인",
    "systemctl is-failed httpd",
    "",
    "# 모든 서비스 목록",
    "systemctl list-units --type=service",
    "",
    "# 실행 중인 서비스만",
    "systemctl list-units --type=service --state=running",
    "",
    "# 실패한 서비스만",
    "systemctl list-units --type=service --state=failed",
    "",
    "# 모든 서비스 (비활성 포함)",
    "systemctl list-units --type=service --all",
    "",
    "# 부팅 시 활성화된 서비스 목록",
    "systemctl list-unit-files --type=service --state=enabled",
    "```",
    "",
    "### 서비스 마스킹",
    "마스킹하면 수동으로도 시작할 수 없게 **완전히 비활성화**합니다.",
    "",
    "```bash",
    "systemctl mask httpd           # 마스킹 (start 불가)",
    "systemctl unmask httpd         # 마스킹 해제",
    "```",
    "",
    "---",
    "",
    "## 4. Unit 파일",
    "",
    "systemd가 관리하는 모든 대상을 **Unit**이라 합니다.",
    "",
    "### Unit 유형",
    "| 유형 | 확장자 | 설명 |",
    "|------|--------|------|",
    "| Service | `.service` | 서비스 (데몬) |",
    "| Socket | `.socket` | 소켓 기반 활성화 |",
    "| Target | `.target` | Unit 그룹 (런레벨 대체) |",
    "| Mount | `.mount` | 파일 시스템 마운트 |",
    "| Timer | `.timer` | 타이머 (cron 대체) |",
    "| Device | `.device` | 장치 |",
    "| Path | `.path` | 파일/디렉터리 감시 |",
    "| Swap | `.swap` | 스왑 공간 |",
    "",
    "### Unit 파일 위치",
    "| 경로 | 용도 | 우선순위 |",
    "|------|------|----------|",
    "| `/usr/lib/systemd/system/` | 패키지 설치 시 기본 | 낮음 |",
    "| `/etc/systemd/system/` | 관리자 커스텀 설정 | **높음** |",
    "| `/run/systemd/system/` | 런타임 (재부팅 시 사라짐) | 중간 |",
    "",
    "### .service 파일 구조",
    "```ini",
    "# /etc/systemd/system/myapp.service",
    "[Unit]",
    "Description=My Application Service",
    "After=network.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    "User=myapp",
    "Group=myapp",
    "WorkingDirectory=/opt/myapp",
    "ExecStart=/opt/myapp/start.sh",
    "ExecStop=/opt/myapp/stop.sh",
    "ExecReload=/bin/kill -HUP $MAINPID",
    "Restart=on-failure",
    "RestartSec=5",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "```",
    "",
    "### [Unit] 섹션",
    "| 지시어 | 설명 |",
    "|--------|------|",
    "| `Description` | 서비스 설명 |",
    "| `After` | 이 Unit **이후**에 시작 (순서) |",
    "| `Before` | 이 Unit **이전**에 시작 (순서) |",
    "| `Requires` | 의존 Unit (실패 시 함께 중지) |",
    "| `Wants` | 의존 Unit (실패해도 계속 실행) |",
    "| `Conflicts` | 충돌 Unit (동시 실행 불가) |",
    "",
    "### [Service] 섹션",
    "| 지시어 | 설명 |",
    "|--------|------|",
    "| `Type` | 서비스 유형 (simple, forking, oneshot, notify, idle) |",
    "| `ExecStart` | 시작 명령어 |",
    "| `ExecStop` | 중지 명령어 |",
    "| `ExecReload` | 리로드 명령어 |",
    "| `Restart` | 재시작 조건 (no, on-failure, always, on-abnormal) |",
    "| `RestartSec` | 재시작 대기 시간 (초) |",
    "| `User` / `Group` | 실행 사용자/그룹 |",
    "| `WorkingDirectory` | 작업 디렉터리 |",
    "| `Environment` | 환경 변수 설정 |",
    "| `EnvironmentFile` | 환경 변수 파일 |",
    "",
    "### Type 유형",
    "| Type | 설명 |",
    "|------|------|",
    "| `simple` | 기본값, ExecStart 프로세스가 메인 프로세스 |",
    "| `forking` | 부모 프로세스가 fork 후 종료, 자식이 데몬 |",
    "| `oneshot` | 한 번 실행 후 종료 (ExecStart 완료까지 대기) |",
    "| `notify` | 시작 완료를 systemd에 알림 |",
    "| `idle` | 다른 작업 완료 후 실행 |",
    "",
    "### [Install] 섹션",
    "| 지시어 | 설명 |",
    "|--------|------|",
    "| `WantedBy` | enable 시 어떤 target에 연결할지 |",
    "| `RequiredBy` | 이 Unit이 필수인 target |",
    "| `Alias` | Unit의 별칭 |",
    "",
    "### Unit 파일 수정 후 반영",
    "```bash",
    "# Unit 파일 수정 후 반드시 실행",
    "systemctl daemon-reload",
    "",
    "# 서비스 재시작",
    "systemctl restart myapp",
    "",
    "# Unit 파일 내용 확인",
    "systemctl cat httpd",
    "",
    "# Unit 설정 확인 (기본값 포함)",
    "systemctl show httpd",
    "```",
    "",
    "---",
    "",
    "## 5. 런레벨과 systemd 타겟",
    "",
    "### 런레벨 (SysVinit)",
    "| 런레벨 | 설명 |",
    "|--------|------|",
    "| 0 | **시스템 종료** (halt) |",
    "| 1 (S) | **단일 사용자 모드** (복구 모드, 네트워크 없음) |",
    "| 2 | 다중 사용자 (NFS 없음, Debian은 GUI 포함) |",
    "| 3 | **다중 사용자 (텍스트 모드)** - 서버 기본 |",
    "| 4 | 미사용 (사용자 정의) |",
    "| 5 | **다중 사용자 (GUI 모드)** - 데스크톱 기본 |",
    "| 6 | **시스템 재부팅** (reboot) |",
    "",
    "### systemd 타겟",
    "| 런레벨 | systemd 타겟 | 설명 |",
    "|--------|-------------|------|",
    "| 0 | `poweroff.target` | 시스템 종료 |",
    "| 1 | `rescue.target` | 복구 모드 (단일 사용자) |",
    "| 2, 3, 4 | `multi-user.target` | 다중 사용자 (텍스트) |",
    "| 5 | `graphical.target` | GUI 모드 |",
    "| 6 | `reboot.target` | 재부팅 |",
    "| - | `emergency.target` | 긴급 모드 (최소 환경) |",
    "",
    "### 타겟 관련 명령어",
    "```bash",
    "# 현재 기본 타겟 확인",
    "systemctl get-default",
    "",
    "# 기본 타겟 변경",
    "systemctl set-default multi-user.target     # 텍스트 모드 부팅",
    "systemctl set-default graphical.target      # GUI 모드 부팅",
    "",
    "# 즉시 타겟 전환 (재부팅 없이)",
    "systemctl isolate multi-user.target",
    "systemctl isolate graphical.target",
    "systemctl isolate rescue.target",
    "",
    "# 현재 런레벨 확인 (호환)",
    "runlevel",
    "who -r",
    "```",
    "",
    "### rescue vs emergency",
    "| 항목 | rescue.target | emergency.target |",
    "|------|---------------|------------------|",
    "| 런레벨 | 1 (단일 사용자) | - |",
    "| 파일 시스템 | 마운트됨 (rw) | **루트만 읽기 전용 (ro)** |",
    "| 네트워크 | 없음 | 없음 |",
    "| 서비스 | 최소 서비스 실행 | **거의 없음** |",
    "| 용도 | 일반 복구 | 심각한 장애 복구 |",
    "",
    "---",
    "",
    "## 6. 부팅 과정 (Boot Process)",
    "",
    "```",
    "전원 ON",
    "  │",
    "  ▼",
    "① BIOS/UEFI",
    "  │  - POST(Power On Self Test): 하드웨어 점검",
    "  │  - 부팅 장치 탐색 (디스크, USB, 네트워크)",
    "  │",
    "  ▼",
    "② 부트 로더 (GRUB2)",
    "  │  - 커널 선택 메뉴 표시",
    "  │  - 커널 이미지와 initramfs를 메모리에 로드",
    "  │  - 설정: /boot/grub2/grub.cfg",
    "  │",
    "  ▼",
    "③ 커널 (Kernel)",
    "  │  - 하드웨어 초기화, 드라이버 로드",
    "  │  - initramfs에서 임시 루트 파일 시스템 마운트",
    "  │  - 실제 루트 파일 시스템으로 전환",
    "  │  - PID 1 프로세스 실행 (systemd)",
    "  │",
    "  ▼",
    "④ systemd (PID 1)",
    "  │  - default.target 읽기",
    "  │  - 의존성에 따라 서비스 병렬 시작",
    "  │  - 파일 시스템 마운트 (/etc/fstab)",
    "  │  - 네트워크, 로깅 등 서비스 시작",
    "  │",
    "  ▼",
    "⑤ 로그인 프롬프트 / Display Manager",
    "     - multi-user.target: 텍스트 로그인 (getty)",
    "     - graphical.target: GUI 로그인 (GDM, LightDM)",
    "```",
    "",
    "### BIOS vs UEFI",
    "| 항목 | BIOS | UEFI |",
    "|------|------|------|",
    "| 출시 | 1981년 | 2000년대~ |",
    "| 인터페이스 | 텍스트 기반 | GUI 지원 |",
    "| 디스크 지원 | MBR (최대 2TB) | **GPT** (2TB 초과) |",
    "| 부팅 속도 | 느림 | **빠름** |",
    "| 보안 부팅 | X | **Secure Boot** 지원 |",
    "",
    "### GRUB2 (GRand Unified Bootloader 2)",
    "```bash",
    "# GRUB 설정 파일",
    "cat /boot/grub2/grub.cfg           # 자동 생성 (직접 수정 X)",
    "cat /etc/default/grub              # 사용자 설정",
    "",
    "# /etc/default/grub 주요 항목",
    "GRUB_TIMEOUT=5                     # 메뉴 대기 시간 (초)",
    "GRUB_DEFAULT=0                     # 기본 부팅 항목 (0번째)",
    "GRUB_CMDLINE_LINUX=\"...\"           # 커널 부팅 파라미터",
    "",
    "# 설정 변경 후 grub.cfg 재생성",
    "grub2-mkconfig -o /boot/grub2/grub.cfg     # CentOS/RHEL",
    "update-grub                                 # Ubuntu/Debian",
    "```",
    "",
    "---",
    "",
    "## 7. 시스템 종료·재부팅",
    "",
    "```bash",
    "# 즉시 종료",
    "shutdown -h now",
    "poweroff",
    "halt",
    "init 0",
    "systemctl poweroff",
    "",
    "# 예약 종료",
    "shutdown -h +10                    # 10분 후 종료",
    "shutdown -h 22:00                  # 오후 10시에 종료",
    "",
    "# 종료 예약 취소",
    "shutdown -c",
    "",
    "# 즉시 재부팅",
    "shutdown -r now",
    "reboot",
    "init 6",
    "systemctl reboot",
    "",
    "# 모든 사용자에게 메시지 전송 후 종료",
    "shutdown -h +5 \"서버 점검을 위해 5분 후 종료됩니다\"",
    "```",
    "",
    "### shutdown 옵션",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `-h` | halt (종료) |",
    "| `-r` | reboot (재부팅) |",
    "| `-c` | cancel (예약 취소) |",
    "| `-k` | 종료하지 않고 경고 메시지만 전송 |",
    "| `now` | 즉시 |",
    "| `+분` | 지정 시간(분) 후 |",
    "| `HH:MM` | 특정 시각 |",
    "",
    "---",
    "",
    "## 8. journalctl (systemd 로그)",
    "",
    "systemd의 통합 로깅 시스템인 **journald**가 수집한 로그를 조회합니다.",
    "",
    "```bash",
    "# 전체 로그 확인",
    "journalctl",
    "",
    "# 최근 로그부터 (역순)",
    "journalctl -r",
    "",
    "# 실시간 로그 (tail -f와 유사)",
    "journalctl -f",
    "",
    "# 특정 서비스 로그",
    "journalctl -u httpd",
    "journalctl -u sshd --since today",
    "",
    "# 부팅별 로그",
    "journalctl -b                      # 현재 부팅",
    "journalctl -b -1                   # 이전 부팅",
    "journalctl --list-boots            # 부팅 목록",
    "",
    "# 시간 범위 지정",
    "journalctl --since \"2026-03-01\"",
    "journalctl --since \"2026-03-01\" --until \"2026-03-02\"",
    "journalctl --since \"1 hour ago\"",
    "",
    "# 우선순위(심각도)별 필터",
    "journalctl -p err                  # 에러 이상만",
    "journalctl -p warning              # 경고 이상만",
    "",
    "# 커널 메시지",
    "journalctl -k                      # = dmesg",
    "",
    "# 출력 줄 수 제한",
    "journalctl -n 50                   # 최근 50줄",
    "",
    "# 디스크 사용량 확인",
    "journalctl --disk-usage",
    "```",
    "",
    "### 로그 우선순위 (priority)",
    "| 번호 | 이름 | 설명 |",
    "|------|------|------|",
    "| 0 | emerg | 시스템 사용 불가 |",
    "| 1 | alert | 즉시 조치 필요 |",
    "| 2 | crit | 심각한 상태 |",
    "| 3 | **err** | 오류 |",
    "| 4 | **warning** | 경고 |",
    "| 5 | notice | 주의 |",
    "| 6 | **info** | 정보 |",
    "| 7 | debug | 디버그 |",
    "",
    "---",
    "",
    "## 9. xinetd (슈퍼 데몬)",
    "",
    "**xinetd**는 자주 사용하지 않는 서비스를 평소에는 꺼두었다가, **요청이 들어올 때만 실행**하는 관리 데몬입니다.",
    "",
    "### standalone vs xinetd 방식",
    "| 항목 | standalone | xinetd |",
    "|------|-----------|--------|",
    "| 실행 | 항상 메모리에 상주 | 요청 시에만 실행 |",
    "| 응답 속도 | **빠름** | 느림 (실행 시간 포함) |",
    "| 메모리 | 많이 사용 | **적게 사용** |",
    "| 예시 | httpd, sshd, mysqld | telnet, finger, tftp |",
    "| 적합 환경 | 빈번한 요청 서비스 | 드문 요청 서비스 |",
    "",
    "### xinetd 설정",
    "```bash",
    "# 메인 설정 파일",
    "cat /etc/xinetd.conf",
    "",
    "# 개별 서비스 설정 디렉터리",
    "ls /etc/xinetd.d/",
    "```",
    "",
    "```",
    "# /etc/xinetd.d/telnet 예시",
    "service telnet",
    "{",
    "    flags           = REUSE",
    "    socket_type     = stream",
    "    wait            = no",
    "    user            = root",
    "    server          = /usr/sbin/in.telnetd",
    "    log_on_failure  += USERID",
    "    disable         = no",
    "}",
    "```",
    "",
    "| 지시어 | 설명 |",
    "|--------|------|",
    "| `socket_type` | stream(TCP), dgram(UDP) |",
    "| `wait` | no(다중 연결 허용), yes(한 연결씩) |",
    "| `user` | 실행 사용자 |",
    "| `server` | 실행할 프로그램 경로 |",
    "| `disable` | yes(비활성), no(활성) |",
    "| `only_from` | 접속 허용 호스트 |",
    "| `no_access` | 접속 차단 호스트 |",
    "| `access_times` | 접속 허용 시간대 |",
    "",
    "---",
    "",
    "## 10. 커스텀 서비스 만들기",
    "",
    "직접 만든 프로그램을 systemd 서비스로 등록하는 방법입니다.",
    "",
    "### 1단계: 실행 스크립트 준비",
    "```bash",
    "# /opt/myapp/myapp.sh",
    "#!/bin/bash",
    "while true; do",
    "    echo \"$(date) - running\" >> /var/log/myapp.log",
    "    sleep 60",
    "done",
    "```",
    "",
    "```bash",
    "chmod +x /opt/myapp/myapp.sh",
    "```",
    "",
    "### 2단계: Unit 파일 작성",
    "```ini",
    "# /etc/systemd/system/myapp.service",
    "[Unit]",
    "Description=My Custom Application",
    "After=network.target",
    "",
    "[Service]",
    "Type=simple",
    "ExecStart=/opt/myapp/myapp.sh",
    "Restart=on-failure",
    "RestartSec=10",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "```",
    "",
    "### 3단계: 등록 및 실행",
    "```bash",
    "systemctl daemon-reload          # Unit 파일 인식",
    "systemctl start myapp            # 시작",
    "systemctl enable myapp           # 부팅 시 자동 시작",
    "systemctl status myapp           # 상태 확인",
    "journalctl -u myapp -f           # 로그 실시간 확인",
    "```",
    "",
    "---",
    "",
    "## 11. 모듈·커널 관련",
    "",
    "### 커널 정보",
    "```bash",
    "uname -r                         # 커널 버전",
    "uname -a                         # 전체 시스템 정보",
    "cat /proc/version                # 커널 버전 상세",
    "```",
    "",
    "### 커널 모듈 관리",
    "```bash",
    "# 로드된 모듈 목록",
    "lsmod",
    "",
    "# 모듈 정보 확인",
    "modinfo ext4",
    "modinfo e1000",
    "",
    "# 모듈 로드 (의존성 자동 해결)",
    "modprobe ext4",
    "modprobe -r ext4                 # 모듈 제거",
    "",
    "# 모듈 로드 (의존성 해결 안 함, 구식)",
    "insmod /lib/modules/.../ext4.ko",
    "rmmod ext4                       # 모듈 제거",
    "```",
    "",
    "### modprobe vs insmod",
    "| 항목 | modprobe | insmod |",
    "|------|---------|--------|",
    "| 의존성 | **자동 해결** | 수동 |",
    "| 경로 | 모듈 이름만 | 전체 경로 필요 |",
    "| 권장 | **권장** | 비권장 |",
    "",
    "---",
    "",
    "### 요약",
    "- **데몬**: 백그라운드 실행 프로세스, 보통 `d`로 끝남 (httpd, sshd, crond)",
    "- **systemctl**: `start`(시작), `stop`(중지), `restart`(재시작), `reload`(리로드), `enable`(자동시작), `disable`(해제), `status`(상태)",
    "- **Unit 파일**: `.service` 파일로 서비스 정의, `[Unit]` + `[Service]` + `[Install]` 섹션",
    "- **런레벨 → 타겟**: 0=poweroff, 1=rescue, 3=multi-user, 5=graphical, 6=reboot",
    "- **타겟 관리**: `get-default`(확인), `set-default`(변경), `isolate`(즉시 전환)",
    "- **부팅 과정**: BIOS/UEFI → GRUB2 → Kernel → systemd → 로그인",
    "- **journalctl**: systemd 통합 로그 조회, `-u`(서비스별), `-p`(우선순위별), `-f`(실시간)",
    "- **xinetd**: 요청 시에만 서비스 실행하는 슈퍼 데몬",
    "- **커널 모듈**: `lsmod`(목록), `modprobe`(로드/제거), `modinfo`(정보)"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
