<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-file-directory-commands",
  title: "리눅스 디렉터리 및 파일 명령어",
  date: "2026-03-09",
  summary: "리눅스에서 디렉터리와 파일을 다루는 핵심 명령어를 정리합니다. ls, cd, mkdir, cp, mv, rm, find, chmod, chown과 함께 압축(gzip/bzip2/xz), 아카이브(tar/cpio), 백업(dd/rsync) 명령어까지 예제와 함께 설명합니다.",
  category: "Technology/Linux",
  tags: ["linux","command","file","directory","ls","cp","mv","rm","chmod","tar","gzip","rsync","dd","backup"],
  content: [
    "## 한 줄 요약",
    "리눅스에서 디렉터리와 파일을 다루는 명령어는 **ls, cd, pwd, mkdir, rmdir, cp, mv, rm, touch, cat, head, tail, find, chmod, chown** 등이 있으며, 이들만 익혀도 대부분의 파일 작업이 가능합니다.",
    "",
    "## 경로 표기법",
    "",
    "명령어를 배우기 전에 경로 표기법을 먼저 정리합니다.",
    "",
    "| 표기 | 의미 | 예시 |",
    "|------|------|------|",
    "| `/` | 루트 디렉터리 (최상위) | `/etc/hosts` |",
    "| `~` | 현재 사용자의 홈 디렉터리 | `~/documents` = `/home/haru/documents` |",
    "| `.` | 현재 디렉터리 | `./script.sh` |",
    "| `..` | 상위(부모) 디렉터리 | `cd ..` |",
    "| `-` | 이전 디렉터리 (cd 전용) | `cd -` |",
    "",
    "| 종류 | 설명 | 예시 |",
    "|------|------|------|",
    "| 절대 경로 | /부터 시작하는 전체 경로 | `/home/haru/file.txt` |",
    "| 상대 경로 | 현재 위치 기준 경로 | `../documents/file.txt` |",
    "",
    "## 디렉터리 명령어",
    "",
    "### pwd (Print Working Directory)",
    "현재 위치(작업 디렉터리)를 출력합니다.",
    "",
    "```bash",
    "pwd",
    "# /home/haru",
    "```",
    "",
    "### cd (Change Directory)",
    "디렉터리를 이동합니다.",
    "",
    "```bash",
    "cd /etc              # 절대 경로로 이동",
    "cd documents         # 상대 경로로 이동",
    "cd ..                # 상위 디렉터리로 이동",
    "cd ~                 # 홈 디렉터리로 이동",
    "cd                   # 홈 디렉터리로 이동 (cd ~와 동일)",
    "cd -                 # 이전 디렉터리로 이동",
    "cd ../..             # 2단계 상위로 이동",
    "```",
    "",
    "### ls (List)",
    "디렉터리 내용을 나열합니다. 가장 자주 쓰는 명령어 중 하나입니다.",
    "",
    "```bash",
    "ls                   # 현재 디렉터리 내용",
    "ls /etc              # 특정 디렉터리 내용",
    "ls -l                # 상세 정보 (권한, 소유자, 크기, 날짜)",
    "ls -a                # 숨김 파일 포함 (.으로 시작하는 파일)",
    "ls -la               # 상세 + 숨김 파일",
    "ls -lh               # 상세 + 사람이 읽기 쉬운 크기 (K, M, G)",
    "ls -lt               # 상세 + 수정 시간 순 정렬",
    "ls -ltr              # 상세 + 수정 시간 역순 (오래된 것 먼저)",
    "ls -lS               # 상세 + 파일 크기 순 정렬",
    "ls -R                # 하위 디렉터리까지 재귀적으로 표시",
    "```",
    "",
    "### ls -l 출력 읽는 법",
    "```",
    "-rw-r--r-- 1 haru users  4096 Feb 24 10:00 file.txt",
    "drwxr-xr-x 2 haru users  4096 Feb 24 10:00 mydir/",
    "```",
    "",
    "| 필드 | 의미 |",
    "|------|------|",
    "| `-rw-r--r--` | 파일 타입 + 권한 (- 파일, d 디렉터리, l 심볼릭링크) |",
    "| `1` | 하드 링크 수 |",
    "| `haru` | 소유자 |",
    "| `users` | 소유 그룹 |",
    "| `4096` | 파일 크기 (바이트) |",
    "| `Feb 24 10:00` | 마지막 수정 시간 |",
    "| `file.txt` | 파일/디렉터리 이름 |",
    "",
    "### mkdir (Make Directory)",
    "디렉터리를 생성합니다.",
    "",
    "```bash",
    "mkdir mydir                  # 디렉터리 생성",
    "mkdir -p parent/child/grand  # 중간 경로가 없으면 함께 생성",
    "mkdir dir1 dir2 dir3         # 여러 개 동시 생성",
    "mkdir -m 755 mydir           # 권한을 지정하면서 생성",
    "```",
    "",
    "### rmdir (Remove Directory)",
    "**빈 디렉터리**만 삭제합니다.",
    "",
    "```bash",
    "rmdir mydir                  # 빈 디렉터리 삭제",
    "rmdir -p parent/child/grand  # 빈 중간 디렉터리까지 삭제",
    "```",
    "",
    "디렉터리 안에 파일이 있으면 `rm -r`을 사용합니다.",
    "",
    "## 파일 명령어",
    "",
    "### touch",
    "빈 파일을 생성하거나, 기존 파일의 수정 시간을 갱신합니다.",
    "",
    "```bash",
    "touch newfile.txt            # 빈 파일 생성",
    "touch file1.txt file2.txt    # 여러 파일 동시 생성",
    "touch existing.txt           # 이미 있으면 수정 시간만 갱신",
    "```",
    "",
    "### 절대경로 / 상대경로로 파일 생성",
    "",
    "```bash",
    "# 현재 위치 확인",
    "pwd",
    "# /home/haru",
    "",
    "# ── 절대경로로 생성 ──",
    "# 어디에 있든 /tmp 아래에 파일 생성",
    "touch /tmp/test.txt",
    "touch /home/haru/documents/memo.txt",
    "touch /var/log/myapp.log",
    "",
    "# ── 상대경로로 생성 ──",
    "# 현재 위치(/home/haru) 기준",
    "touch ./hello.txt            # 현재 디렉터리에 생성 (/home/haru/hello.txt)",
    "touch documents/note.txt     # 하위 디렉터리에 생성 (/home/haru/documents/note.txt)",
    "touch ../shared/data.txt     # 상위 → shared 디렉터리에 생성 (/home/shared/data.txt)",
    "```",
    "",
    "```",
    "예시: 현재 위치가 /home/haru일 때",
    "",
    "절대경로:  touch /tmp/test.txt           → /tmp/test.txt",
    "상대경로:  touch documents/note.txt      → /home/haru/documents/note.txt",
    "상대경로:  touch ./hello.txt             → /home/haru/hello.txt",
    "상대경로:  touch ../shared/data.txt      → /home/shared/data.txt",
    "```",
    "",
    "> **주의**: 경로에 있는 디렉터리가 존재하지 않으면 에러가 발생합니다. `touch /tmp/newdir/file.txt`을 실행하려면 `/tmp/newdir/` 디렉터리가 먼저 있어야 합니다. `mkdir -p /tmp/newdir && touch /tmp/newdir/file.txt`처럼 디렉터리를 먼저 만드세요.",
    "",
    "### cp (Copy)",
    "파일/디렉터리를 복사합니다.",
    "",
    "```bash",
    "cp file.txt copy.txt              # 파일 복사",
    "cp file.txt /tmp/                 # 다른 위치로 복사",
    "cp -r mydir/ mydir_backup/        # 디렉터리 복사 (-r: 재귀)",
    "cp -i file.txt copy.txt           # 덮어쓰기 전 확인",
    "cp -p file.txt copy.txt           # 권한·시간 등 속성 보존",
    "cp -a mydir/ backup/              # 아카이브 모드 (-r + 속성 보존 + 심볼릭링크 유지)",
    "cp file1.txt file2.txt /tmp/      # 여러 파일을 한 디렉터리로 복사",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -r | 디렉터리를 재귀적으로 복사 |",
    "| -i | 덮어쓰기 전 확인(interactive) |",
    "| -p | 소유자·권한·시간 보존 |",
    "| -a | 아카이브 모드 (-r -p + 심볼릭링크 유지) |",
    "| -v | 복사 과정 출력(verbose) |",
    "",
    "### mv (Move / Rename)",
    "파일/디렉터리를 이동하거나 이름을 변경합니다.",
    "",
    "```bash",
    "mv old.txt new.txt                # 이름 변경",
    "mv file.txt /tmp/                 # 파일 이동",
    "mv mydir/ /opt/mydir/             # 디렉터리 이동",
    "mv -i file.txt /tmp/file.txt      # 덮어쓰기 전 확인",
    "mv file1.txt file2.txt /tmp/      # 여러 파일 이동",
    "```",
    "",
    "### rm (Remove)",
    "파일/디렉터리를 삭제합니다. **삭제하면 복구가 매우 어렵습니다.**",
    "",
    "```bash",
    "rm file.txt                       # 파일 삭제",
    "rm -i file.txt                    # 삭제 전 확인",
    "rm -r mydir/                      # 디렉터리와 내용 전부 삭제",
    "rm -rf mydir/                     # 강제 삭제 (확인 없이)",
    "rm *.log                          # 와일드카드로 .log 파일 전부 삭제",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -r | 디렉터리 재귀 삭제 |",
    "| -f | 강제 삭제 (확인 없이, 에러 무시) |",
    "| -i | 삭제 전 확인 |",
    "",
    "**`rm -rf /`는 시스템 전체를 삭제합니다. 절대 실행하지 마세요.**",
    "",
    "## 파일 내용 확인",
    "",
    "### cat (Concatenate)",
    "파일 내용 전체를 출력합니다.",
    "",
    "```bash",
    "cat file.txt                      # 파일 내용 출력",
    "cat file1.txt file2.txt           # 여러 파일 연결해서 출력",
    "cat -n file.txt                   # 줄 번호 포함",
    "cat file.txt > new.txt            # 내용을 새 파일로 저장 (덮어쓰기)",
    "cat file.txt >> log.txt           # 내용을 기존 파일에 추가",
    "```",
    "",
    "### head / tail",
    "파일의 처음/끝 부분만 출력합니다.",
    "",
    "```bash",
    "head file.txt                     # 처음 10줄",
    "head -n 20 file.txt               # 처음 20줄",
    "tail file.txt                     # 마지막 10줄",
    "tail -n 20 file.txt               # 마지막 20줄",
    "tail -f /var/log/syslog           # 실시간 로그 모니터링 (파일이 추가될 때마다 출력)",
    "```",
    "",
    "`tail -f`는 서버 로그를 실시간으로 보는 데 매우 자주 사용됩니다.",
    "",
    "### less / more",
    "파일 내용을 페이지 단위로 탐색합니다.",
    "",
    "```bash",
    "less file.txt                     # 페이지 단위 탐색 (위아래 스크롤 가능)",
    "more file.txt                     # 페이지 단위 탐색 (아래로만)",
    "```",
    "",
    "| less 키 | 동작 |",
    "|---------|------|",
    "| Space | 다음 페이지 |",
    "| b | 이전 페이지 |",
    "| /검색어 | 앞으로 검색 |",
    "| ?검색어 | 뒤로 검색 |",
    "| n | 다음 검색 결과 |",
    "| q | 종료 |",
    "| g | 파일 처음으로 |",
    "| G | 파일 끝으로 |",
    "",
    "### wc (Word Count)",
    "파일의 줄 수, 단어 수, 바이트 수를 세어 줍니다.",
    "",
    "```bash",
    "wc file.txt                       # 줄 / 단어 / 바이트",
    "wc -l file.txt                    # 줄 수만",
    "wc -w file.txt                    # 단어 수만",
    "wc -c file.txt                    # 바이트 수만",
    "```",
    "",
    "## 파일 검색",
    "",
    "### find",
    "조건에 맞는 파일/디렉터리를 검색합니다.",
    "",
    "```bash",
    "find /home -name \"*.txt\"                 # 이름으로 검색",
    "find /home -iname \"*.txt\"                # 대소문자 무시",
    "find / -type f -name \"config\"            # 파일만 검색 (-type f)",
    "find / -type d -name \"log\"               # 디렉터리만 검색 (-type d)",
    "find /var -size +100M                    # 100MB 초과 파일",
    "find /home -mtime -7                     # 최근 7일 내 수정된 파일",
    "find /tmp -empty                         # 빈 파일/디렉터리",
    "find /home -name \"*.tmp\" -delete         # 찾아서 삭제",
    "find /home -name \"*.sh\" -exec chmod +x {} \\;  # 찾아서 명령 실행",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -name | 파일명 패턴 (대소문자 구분) |",
    "| -iname | 파일명 패턴 (대소문자 무시) |",
    "| -type f/d/l | 파일(f), 디렉터리(d), 심볼릭링크(l) |",
    "| -size +100M | 100MB 초과 |",
    "| -mtime -7 | 최근 7일 내 수정 |",
    "| -user haru | 소유자가 haru |",
    "| -perm 755 | 권한이 755 |",
    "| -exec 명령 {} \\; | 검색 결과마다 명령 실행 |",
    "",
    "### grep (파일 내용 검색)",
    "파일 안에서 특정 문자열을 검색합니다.",
    "",
    "```bash",
    "grep \"error\" /var/log/syslog             # 문자열 검색",
    "grep -i \"error\" file.txt                 # 대소문자 무시",
    "grep -r \"TODO\" /home/haru/project/       # 디렉터리 재귀 검색",
    "grep -n \"main\" app.py                    # 줄 번호 포함",
    "grep -c \"error\" file.txt                 # 일치 줄 수만 출력",
    "grep -v \"debug\" file.txt                 # 일치하지 않는 줄 출력",
    "grep -l \"error\" *.log                    # 일치하는 파일 이름만 출력",
    "```",
    "",
    "### locate",
    "미리 만들어 둔 데이터베이스(DB)에서 파일을 빠르게 검색합니다. `find`보다 훨씬 빠르지만, DB를 갱신해야 최신 파일이 반영됩니다.",
    "",
    "```bash",
    "locate config.txt                  # 파일명에 config.txt가 포함된 모든 경로",
    "locate -i readme                   # 대소문자 무시 검색",
    "locate -n 10 \"*.conf\"              # 결과를 10개만 출력",
    "locate -c \"*.log\"                  # 일치 개수만 출력",
    "sudo updatedb                      # DB 수동 갱신 (새 파일 반영)",
    "```",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| 원리 | `updatedb`가 만든 파일 경로 DB(`/var/lib/mlocate/mlocate.db`)를 검색 |",
    "| 장점 | 디스크를 실시간으로 탐색하지 않아 매우 빠름 |",
    "| 단점 | DB 갱신 전에 생긴 파일은 검색 안 됨 |",
    "| DB 갱신 | `sudo updatedb` (보통 cron으로 하루 1회 자동 실행) |",
    "| 설치 | `sudo apt install mlocate` (Ubuntu) / `sudo yum install mlocate` (CentOS) |",
    "",
    "> **find vs locate**: `find`는 디스크를 직접 탐색해 항상 최신이지만 느리고, `locate`는 DB 기반이라 빠르지만 최신 파일이 누락될 수 있습니다. 용도에 맞게 선택하세요.",
    "",
    "### which / whereis",
    "명령어의 위치를 찾습니다.",
    "",
    "```bash",
    "which python3          # 실행 파일 경로",
    "whereis python3        # 실행 파일 + 매뉴얼 + 소스 경로",
    "```",
    "",
    "## 권한 관련 명령어",
    "",
    "### chmod (Change Mode)",
    "파일/디렉터리의 권한을 변경합니다.",
    "",
    "```bash",
    "chmod 755 script.sh          # 숫자 방식 (rwxr-xr-x)",
    "chmod +x script.sh           # 실행 권한 추가",
    "chmod -w file.txt            # 쓰기 권한 제거",
    "chmod u+x script.sh          # 소유자에게 실행 권한 추가",
    "chmod go-w file.txt          # 그룹·기타에서 쓰기 제거",
    "chmod -R 755 mydir/          # 디렉터리 재귀 적용",
    "```",
    "",
    "### 권한 숫자 의미",
    "| 숫자 | 권한 | 의미 |",
    "|------|------|------|",
    "| 4 | r | 읽기 (read) |",
    "| 2 | w | 쓰기 (write) |",
    "| 1 | x | 실행 (execute) |",
    "",
    "세 자리 숫자는 순서대로 **소유자 / 그룹 / 기타**의 권한입니다.",
    "",
    "| 예시 | 소유자 | 그룹 | 기타 | 의미 |",
    "|------|--------|------|------|------|",
    "| 755 | rwx(7) | r-x(5) | r-x(5) | 소유자 모두, 나머지 읽기+실행 |",
    "| 644 | rw-(6) | r--(4) | r--(4) | 소유자 읽기+쓰기, 나머지 읽기만 |",
    "| 700 | rwx(7) | ---(0) | ---(0) | 소유자만 모든 권한 |",
    "| 600 | rw-(6) | ---(0) | ---(0) | 소유자만 읽기+쓰기 |",
    "",
    "### chown (Change Owner)",
    "파일/디렉터리의 소유자와 그룹을 변경합니다.",
    "",
    "```bash",
    "sudo chown haru file.txt              # 소유자 변경",
    "sudo chown haru:users file.txt        # 소유자 + 그룹 변경",
    "sudo chown :users file.txt            # 그룹만 변경",
    "sudo chown -R haru:users mydir/       # 디렉터리 재귀 적용",
    "```",
    "",
    "### chgrp (Change Group)",
    "파일/디렉터리의 그룹만 변경합니다.",
    "",
    "```bash",
    "sudo chgrp users file.txt",
    "sudo chgrp -R users mydir/",
    "```",
    "",
    "### umask (기본 권한 마스크)",
    "새 파일/디렉터리 생성 시 기본 권한을 결정합니다.",
    "",
    "```bash",
    "umask              # 현재 umask 값 확인 (보통 0022)",
    "umask 027          # umask 설정 변경",
    "```",
    "",
    "| 항목 | 기본 최대 권한 | umask 0022 적용 | 결과 |",
    "|------|---------------|-----------------|------|",
    "| 파일 | 666 | 666 - 022 | **644** (rw-r--r--) |",
    "| 디렉터리 | 777 | 777 - 022 | **755** (rwxr-xr-x) |",
    "",
    "### 특수 권한 (SetUID, SetGID, Sticky Bit)",
    "",
    "일반 권한(rwx) 외에 **3가지 특수 권한**이 있습니다.",
    "",
    "#### SetUID (4000)",
    "실행 파일에 설정하면, **파일 소유자의 권한**으로 실행됩니다.",
    "",
    "```bash",
    "chmod 4755 /usr/bin/passwd      # -rwsr-xr-x",
    "chmod u+s program               # SetUID 설정",
    "",
    "# 확인: 소유자 실행 권한 자리에 s 표시",
    "ls -l /usr/bin/passwd",
    "# -rwsr-xr-x 1 root root ... /usr/bin/passwd",
    "```",
    "",
    "일반 사용자가 `passwd` 명령으로 자신의 비밀번호를 변경할 수 있는 이유는, 이 파일에 SetUID가 설정되어 있어 **root 권한으로 실행**되기 때문입니다.",
    "",
    "#### SetGID (2000)",
    "- **파일**: 실행 시 **파일 그룹의 권한**으로 실행",
    "- **디렉터리**: 해당 디렉터리 안에서 생성되는 파일이 **디렉터리의 그룹을 상속**",
    "",
    "```bash",
    "chmod 2755 /project             # drwxr-sr-x",
    "chmod g+s /project              # SetGID 설정",
    "",
    "# 확인: 그룹 실행 권한 자리에 s 표시",
    "ls -ld /project",
    "# drwxr-sr-x 2 root devteam ... /project",
    "",
    "# /project 안에서 만든 파일은 자동으로 devteam 그룹 소유",
    "touch /project/newfile.txt",
    "ls -l /project/newfile.txt",
    "# -rw-r--r-- 1 haru devteam ... newfile.txt",
    "```",
    "",
    "팀 공유 디렉터리에서 모든 파일의 그룹을 통일할 때 유용합니다.",
    "",
    "#### Sticky Bit (1000)",
    "디렉터리에 설정하면, **파일 소유자만 해당 파일을 삭제**할 수 있습니다. 다른 사용자의 파일은 삭제 불가합니다.",
    "",
    "```bash",
    "chmod 1777 /tmp                 # drwxrwxrwt",
    "chmod +t /shared                # Sticky Bit 설정",
    "",
    "# 확인: 기타(Other) 실행 권한 자리에 t 표시",
    "ls -ld /tmp",
    "# drwxrwxrwt 10 root root ... /tmp",
    "```",
    "",
    "`/tmp` 디렉터리가 대표적인 예입니다. 모든 사용자가 파일을 생성할 수 있지만, 자기 파일만 삭제 가능합니다.",
    "",
    "#### 특수 권한 요약표",
    "| 특수 권한 | 숫자 | 표시 위치 | 용도 | 대표 예시 |",
    "|-----------|------|-----------|------|-----------|",
    "| **SetUID** | 4 | 소유자 x → `s` | 실행 시 파일 소유자 권한 | `/usr/bin/passwd` |",
    "| **SetGID** | 2 | 그룹 x → `s` | 실행 시 파일 그룹 권한 / 디렉터리 그룹 상속 | 공유 디렉터리 |",
    "| **Sticky Bit** | 1 | 기타 x → `t` | 소유자만 삭제 가능 | `/tmp` |",
    "",
    "```bash",
    "# 특수 권한 숫자 방식 (앞에 1자리 추가)",
    "chmod 4755 file     # SetUID + rwxr-xr-x  →  -rwsr-xr-x",
    "chmod 2755 dir      # SetGID + rwxr-xr-x  →  drwxr-sr-x",
    "chmod 1777 dir      # Sticky + rwxrwxrwx  →  drwxrwxrwt",
    "",
    "# 특수 권한 해제",
    "chmod 0755 file     # 특수 권한 제거",
    "chmod u-s file      # SetUID 제거",
    "chmod g-s dir       # SetGID 제거",
    "chmod -t dir        # Sticky Bit 제거",
    "",
    "# 특수 권한이 있는 파일 찾기",
    "find / -perm -4000 -type f     # SetUID 파일 찾기",
    "find / -perm -2000 -type d     # SetGID 디렉터리 찾기",
    "find / -perm -1000 -type d     # Sticky Bit 디렉터리 찾기",
    "```",
    "",
    "**보안 주의**: SetUID가 설정된 파일은 보안 위험이 될 수 있습니다. 불필요한 SetUID 파일이 있는지 주기적으로 `find / -perm -4000`으로 확인하는 것이 좋습니다.",
    "",
    "## 링크",
    "",
    "### ln (Link)",
    "```bash",
    "ln file.txt hardlink.txt              # 하드 링크",
    "ln -s /path/to/file symlink.txt       # 심볼릭(소프트) 링크",
    "ln -s /path/to/dir symdir             # 디렉터리 심볼릭 링크",
    "```",
    "",
    "| 종류 | 설명 |",
    "|------|------|",
    "| 하드 링크 | 같은 데이터를 가리키는 또 다른 이름. 원본 삭제해도 접근 가능 |",
    "| 심볼릭 링크 | 바로가기. 원본 경로를 가리킴. 원본 삭제 시 깨짐 |",
    "",
    "실무에서는 **심볼릭 링크(ln -s)**를 훨씬 많이 사용합니다.",
    "",
    "## 기타 유용한 명령어",
    "",
    "### file",
    "파일의 종류를 알려줍니다.",
    "",
    "```bash",
    "file image.png          # PNG image data, 1920x1080...",
    "file script.sh          # Bourne-Again shell script",
    "file /dev/sda           # block special",
    "```",
    "",
    "### stat",
    "파일의 상세 메타데이터를 출력합니다.",
    "",
    "```bash",
    "stat file.txt",
    "# 크기, 블록 수, 권한, 소유자, 접근/수정/변경 시간 등",
    "```",
    "",
    "### du (Disk Usage)",
    "디렉터리/파일의 디스크 사용량을 확인합니다.",
    "",
    "```bash",
    "du -sh mydir/           # 디렉터리 전체 크기 요약",
    "du -sh *                # 현재 디렉터리의 항목별 크기",
    "du -h --max-depth=1     # 1단계 하위까지만 표시",
    "```",
    "",
    "### tree",
    "디렉터리 구조를 트리 형태로 출력합니다.",
    "",
    "```bash",
    "tree                    # 현재 디렉터리 트리",
    "tree -L 2               # 2단계까지만 표시",
    "tree -d                 # 디렉터리만 표시",
    "```",
    "",
    "## 압축·아카이브·백업",
    "",
    "### 압축 명령어",
    "",
    "리눅스의 압축 명령어는 **파일 1개**를 압축합니다. 디렉터리를 압축하려면 `tar`로 먼저 묶어야 합니다.",
    "",
    "#### gzip / gunzip",
    "가장 널리 쓰이는 압축 도구입니다.",
    "",
    "```bash",
    "gzip file.txt                  # file.txt.gz 생성 (원본 삭제)",
    "gzip -d file.txt.gz            # 압축 해제 (= gunzip file.txt.gz)",
    "gzip -k file.txt               # 원본 유지하면서 압축",
    "gzip -r mydir/                 # 디렉터리 내 파일들 개별 압축",
    "gzip -l file.txt.gz            # 압축 정보 확인 (비율 등)",
    "gzip -1 file.txt               # 빠른 압축 (낮은 압축률)",
    "gzip -9 file.txt               # 최대 압축 (느림)",
    "",
    "zcat file.txt.gz               # 압축 해제 없이 내용 확인",
    "zgrep \"keyword\" file.txt.gz    # 압축 파일에서 검색",
    "```",
    "",
    "#### bzip2 / bunzip2",
    "gzip보다 **높은 압축률**, 대신 속도가 느립니다.",
    "",
    "```bash",
    "bzip2 file.txt                 # file.txt.bz2 생성 (원본 삭제)",
    "bzip2 -d file.txt.bz2          # 압축 해제 (= bunzip2 file.txt.bz2)",
    "bzip2 -k file.txt              # 원본 유지하면서 압축",
    "",
    "bzcat file.txt.bz2             # 압축 해제 없이 내용 확인",
    "```",
    "",
    "#### xz / unxz",
    "**가장 높은 압축률**, 가장 느립니다.",
    "",
    "```bash",
    "xz file.txt                    # file.txt.xz 생성 (원본 삭제)",
    "xz -d file.txt.xz              # 압축 해제 (= unxz file.txt.xz)",
    "xz -k file.txt                 # 원본 유지하면서 압축",
    "",
    "xzcat file.txt.xz              # 압축 해제 없이 내용 확인",
    "```",
    "",
    "#### 압축 도구 비교",
    "| 도구 | 확장자 | 압축률 | 속도 | 해제 명령 | 내용 보기 |",
    "|------|--------|--------|------|-----------|-----------|",
    "| `gzip` | `.gz` | 보통 | **빠름** | `gunzip` / `gzip -d` | `zcat` |",
    "| `bzip2` | `.bz2` | 높음 | 보통 | `bunzip2` / `bzip2 -d` | `bzcat` |",
    "| `xz` | `.xz` | **최고** | 느림 | `unxz` / `xz -d` | `xzcat` |",
    "",
    "공통 옵션: `-d`(해제), `-k`(원본 유지), `-v`(상세 출력)",
    "",
    "---",
    "",
    "### tar (아카이브 + 압축)",
    "",
    "`tar`는 여러 파일·디렉터리를 **하나로 묶는(아카이브)** 도구이며, 압축 옵션과 조합해서 사용합니다.",
    "",
    "#### 기본 사용법",
    "```bash",
    "# 묶기 + 압축",
    "tar cvf archive.tar dir/              # 묶기만 (압축 X)",
    "tar cvfz archive.tar.gz dir/          # gzip 압축",
    "tar cvfj archive.tar.bz2 dir/         # bzip2 압축",
    "tar cvfJ archive.tar.xz dir/          # xz 압축",
    "",
    "# 해제",
    "tar xvf archive.tar                   # 묶기 해제",
    "tar xvfz archive.tar.gz               # gzip 해제",
    "tar xvfj archive.tar.bz2              # bzip2 해제",
    "tar xvfJ archive.tar.xz               # xz 해제",
    "",
    "# 특정 경로에 해제",
    "tar xvfz archive.tar.gz -C /opt/      # /opt/ 아래에 해제",
    "",
    "# 내용 확인 (해제 없이 목록 보기)",
    "tar tvf archive.tar                   # 목록 보기",
    "tar tvfz archive.tar.gz               # gzip 아카이브 목록",
    "```",
    "",
    "#### tar 옵션 정리",
    "",
    "**동작 옵션 (셋 중 하나 필수 선택)**",
    "| 옵션 | 의미 | 설명 |",
    "|------|------|------|",
    "| `c` | **C**reate | 새 아카이브 생성 |",
    "| `x` | E**x**tract | 아카이브 해제 |",
    "| `t` | Lis**t** | 내용 확인만 (해제 X) |",
    "",
    "**압축 옵션 (확장자에 맞게 선택)**",
    "| 옵션 | 압축 방식 | 확장자 |",
    "|------|-----------|--------|",
    "| `z` | gzip | `.tar.gz` / `.tgz` |",
    "| `j` | bzip2 | `.tar.bz2` |",
    "| `J` | xz | `.tar.xz` |",
    "",
    "**주의: `j`(소문자) = bzip2, `J`(대문자) = xz → 시험에서 자주 혼동 유도!**",
    "",
    "**기타 옵션**",
    "| 옵션 | 의미 |",
    "|------|------|",
    "| `v` | Verbose (상세 출력) |",
    "| `f` | File (파일명 지정, 항상 마지막에 위치) |",
    "| `-C` | 해제할 경로 지정 |",
    "| `-p` | 권한 보존 |",
    "| `--exclude` | 특정 파일/디렉터리 제외 |",
    "",
    "#### tar 활용 예제",
    "```bash",
    "# 특정 파일 제외하고 압축",
    "tar cvfz backup.tar.gz --exclude='*.log' --exclude='.git' myproject/",
    "",
    "# 기존 아카이브에 파일 추가 (비압축 tar만 가능)",
    "tar rvf archive.tar newfile.txt",
    "",
    "# 특정 파일만 해제",
    "tar xvfz archive.tar.gz path/to/specific-file.txt",
    "",
    "# 증분 백업 (변경된 파일만)",
    "tar cvfz backup-$(date +%Y%m%d).tar.gz --newer='2026-03-01' /data/",
    "```",
    "",
    "#### 예제 문제",
    "`tar ( 괄호 ) php-8.2.7.tar.bz2`의 내용만 확인하려면?",
    "```bash",
    "# 내용 확인(t) + bzip2(j) + 상세(v) + 파일(f)",
    "tar jtvf php-8.2.7.tar.bz2",
    "```",
    "",
    "---",
    "",
    "### dd (디스크 복사)",
    "",
    "블록 단위로 **디스크나 파티션을 통째로 복사**하는 저수준 명령어입니다.",
    "",
    "```bash",
    "# 디스크 전체 이미지 백업",
    "dd if=/dev/sda of=/backup/disk.img bs=4M",
    "",
    "# 이미지에서 디스크 복원",
    "dd if=/backup/disk.img of=/dev/sda bs=4M",
    "",
    "# MBR (부트 섹터) 백업 (512바이트)",
    "dd if=/dev/sda of=/backup/mbr.bak bs=512 count=1",
    "",
    "# ISO를 USB에 기록",
    "dd if=linux.iso of=/dev/sdb bs=4M status=progress",
    "",
    "# 빈 파일 생성 (1GB)",
    "dd if=/dev/zero of=empty.img bs=1M count=1024",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `if` | Input File (입력 파일/장치) |",
    "| `of` | Output File (출력 파일/장치) |",
    "| `bs` | Block Size (블록 크기, 예: 4M) |",
    "| `count` | 복사할 블록 수 |",
    "| `status=progress` | 진행 상황 표시 |",
    "",
    "---",
    "",
    "### cpio (아카이브)",
    "",
    "표준 입력으로 파일 목록을 받아 아카이브를 생성합니다. 주로 `find`와 함께 사용합니다.",
    "",
    "```bash",
    "# 아카이브 생성 (-o: output)",
    "find /home -name \"*.txt\" | cpio -o > backup.cpio",
    "find /etc -type f | cpio -ov > etc_backup.cpio",
    "",
    "# 아카이브 복원 (-i: input, -d: 디렉터리 생성)",
    "cpio -id < backup.cpio",
    "cpio -idv < backup.cpio          # 상세 출력",
    "",
    "# 내용 목록 확인 (-t: list)",
    "cpio -t < backup.cpio",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `-o` | 아카이브 생성 (Copy-Out) |",
    "| `-i` | 아카이브 복원 (Copy-In) |",
    "| `-t` | 내용 목록 확인 |",
    "| `-d` | 필요한 디렉터리 자동 생성 |",
    "| `-v` | 상세 출력 |",
    "",
    "---",
    "",
    "### rsync (동기화 백업)",
    "",
    "파일·디렉터리를 **증분 동기화**하는 백업 도구입니다. 변경된 부분만 전송하므로 효율적입니다.",
    "",
    "```bash",
    "# 로컬 동기화",
    "rsync -avz /data/ /backup/data/",
    "",
    "# 원격 동기화 (SSH 기반)",
    "rsync -avz /data/ user@192.168.1.200:/backup/data/",
    "rsync -avz user@192.168.1.200:/data/ /backup/data/",
    "",
    "# 삭제된 파일도 동기화 (원본에 없으면 백업에서도 삭제)",
    "rsync -avz --delete /data/ /backup/data/",
    "",
    "# 특정 파일 제외",
    "rsync -avz --exclude='*.log' --exclude='.git' /data/ /backup/",
    "",
    "# 드라이런 (실제 실행 없이 미리보기)",
    "rsync -avzn /data/ /backup/data/",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `-a` | Archive (권한, 소유자, 타임스탬프 등 보존) |",
    "| `-v` | Verbose (상세 출력) |",
    "| `-z` | 전송 시 압축 |",
    "| `-r` | 재귀 (디렉터리 하위 포함) |",
    "| `-n` | 드라이런 (시뮬레이션) |",
    "| `--delete` | 원본에 없는 파일을 대상에서 삭제 |",
    "| `--exclude` | 제외 패턴 |",
    "| `-e ssh` | SSH 프로토콜 사용 (기본값) |",
    "",
    "---",
    "",
    "### 백업 도구 비교",
    "| 도구 | 용도 | 특징 |",
    "|------|------|------|",
    "| `tar` | 아카이브 + 압축 | 여러 파일/디렉터리를 하나로 묶음 |",
    "| `dd` | 디스크 이미지 복사 | 블록 단위 저수준 복사 (MBR, 파티션 전체) |",
    "| `cpio` | 아카이브 | find와 파이프로 연결, RPM 내부에서도 사용 |",
    "| `rsync` | 증분 동기화 | 변경분만 전송, 원격 백업에 최적 |",
    "",
    "## 자주 쓰는 조합 정리",
    "",
    "| 목적 | 명령어 |",
    "|------|--------|",
    "| 현재 위치 확인 | `pwd` |",
    "| 디렉터리 이동 | `cd /path` |",
    "| 파일 목록 (상세) | `ls -la` |",
    "| 디렉터리 생성 (중간 포함) | `mkdir -p a/b/c` |",
    "| 파일 복사 (속성 보존) | `cp -a src/ dest/` |",
    "| 디렉터리 통째로 삭제 | `rm -rf mydir/` |",
    "| 파일 내용 보기 | `cat file.txt` 또는 `less file.txt` |",
    "| 실시간 로그 보기 | `tail -f /var/log/syslog` |",
    "| 파일 찾기 (이름) | `find / -name \"*.conf\"` |",
    "| 파일 내용 검색 | `grep -r \"keyword\" /path/` |",
    "| 실행 권한 추가 | `chmod +x script.sh` |",
    "| 소유자 변경 | `sudo chown user:group file` |",
    "| 디렉터리 크기 확인 | `du -sh mydir/` |",
    "| gzip 압축 | `tar cvfz name.tar.gz dir/` |",
    "| bzip2 압축 | `tar cvfj name.tar.bz2 dir/` |",
    "| xz 압축 | `tar cvfJ name.tar.xz dir/` |",
    "| 압축 해제 | `tar xvfz name.tar.gz` |",
    "| 내용 확인 | `tar tvf name.tar` |",
    "| 디스크 이미지 백업 | `dd if=/dev/sda of=disk.img bs=4M` |",
    "| 증분 동기화 | `rsync -avz /data/ /backup/` |",
    "",
    "---",
    "### 요약",
    "리눅스 파일·디렉터리 명령어의 핵심은 ls(목록), cd(이동), mkdir(생성), cp(복사), mv(이동/이름변경), rm(삭제), cat/less(내용 보기), find/grep(검색), chmod/chown(권한)입니다. 압축은 gzip(빠름) → bzip2(높은 압축률) → xz(최고 압축률) 순이며, tar로 묶기+압축을 동시에 처리합니다. `j`(소문자)=bzip2, `J`(대문자)=xz를 혼동하지 않도록 주의하세요. 백업은 tar(아카이브), dd(디스크 이미지), cpio(find 연동), rsync(증분 동기화)를 용도에 맞게 사용합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
