<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-web-server",
  title: "리눅스 웹서버 관리 - Apache, Nginx 설치와 설정 총정리",
  date: "2026-02-26",
  summary: "리눅스 웹서버의 핵심인 Apache와 Nginx를 정리합니다. 설치, 기본 설정, 가상 호스트(Virtual Host), HTTPS/SSL, 리버스 프록시, 로드 밸런싱, 로그 관리, 성능 튜닝, 보안 설정까지 실전 예제와 함께 설명합니다.",
  category: "Technology/Linux",
  tags: ["linux","apache","nginx","httpd","web-server","virtual-host","ssl","reverse-proxy","load-balancer"],
  content: [
    "## 한 줄 요약",
    "**Apache**는 모듈 기반의 유연한 웹서버, **Nginx**는 이벤트 기반의 고성능 웹서버이며, 실무에서는 **Nginx(리버스 프록시) + 백엔드 앱** 조합이 가장 많이 사용됩니다.",
    "",
    "---",
    "",
    "## 1. 웹서버란?",
    "",
    "클라이언트(브라우저)의 **HTTP 요청을 받아 응답을 반환**하는 소프트웨어입니다.",
    "",
    "```",
    "브라우저 (클라이언트)",
    "    │",
    "    │  HTTP 요청: GET /index.html",
    "    ▼",
    "웹서버 (Apache / Nginx)",
    "    │",
    "    │  정적 파일이면 → 바로 응답",
    "    │  동적 요청이면 → 백엔드(WAS)에 전달",
    "    ▼",
    "백엔드 (Spring Boot, Node.js, Django 등)",
    "```",
    "",
    "### Apache vs Nginx 비교",
    "",
    "| 항목 | Apache (httpd) | Nginx |",
    "|------|---------------|-------|",
    "| 개발 | 1995년, Apache 재단 | 2004년, Igor Sysoev |",
    "| 아키텍처 | **프로세스/스레드** 기반 | **이벤트 루프** 기반 |",
    "| 동시 접속 | 접속마다 프로세스/스레드 생성 | 하나의 워커로 수천 연결 처리 |",
    "| 정적 파일 | 보통 | **빠름** |",
    "| 동적 처리 | **mod_php** 등 자체 모듈 | 외부 WAS에 전달 (프록시) |",
    "| 설정 방식 | `.htaccess` (디렉터리별 설정) | 중앙 설정 파일만 |",
    "| 리버스 프록시 | 가능 | **매우 강력** |",
    "| 메모리 사용 | 높음 (접속 수에 비례) | **낮음** |",
    "| 시장 점유율 | 레거시에 많음 | **현재 1위** |",
    "",
    "---",
    "",
    "## 2. Apache 웹서버",
    "",
    "### 설치",
    "```bash",
    "# CentOS/RHEL",
    "yum install httpd -y",
    "systemctl start httpd",
    "systemctl enable httpd",
    "",
    "# Ubuntu/Debian",
    "apt install apache2 -y",
    "systemctl start apache2",
    "systemctl enable apache2",
    "",
    "# 방화벽 허용",
    "firewall-cmd --permanent --add-service=http",
    "firewall-cmd --permanent --add-service=https",
    "firewall-cmd --reload",
    "# 또는",
    "ufw allow 'Apache Full'",
    "```",
    "",
    "### 디렉터리 구조",
    "",
    "**CentOS/RHEL**",
    "| 경로 | 설명 |",
    "|------|------|",
    "| `/etc/httpd/conf/httpd.conf` | **메인 설정 파일** |",
    "| `/etc/httpd/conf.d/` | 추가 설정 파일 (*.conf 자동 로드) |",
    "| `/var/www/html/` | **문서 루트** (웹 파일 위치) |",
    "| `/var/log/httpd/` | 로그 디렉터리 |",
    "| `/etc/httpd/modules/` | 모듈 디렉터리 |",
    "",
    "**Ubuntu/Debian**",
    "| 경로 | 설명 |",
    "|------|------|",
    "| `/etc/apache2/apache2.conf` | 메인 설정 파일 |",
    "| `/etc/apache2/sites-available/` | 가상 호스트 설정 |",
    "| `/etc/apache2/sites-enabled/` | 활성화된 가상 호스트 (심볼릭 링크) |",
    "| `/var/www/html/` | 문서 루트 |",
    "| `/var/log/apache2/` | 로그 디렉터리 |",
    "",
    "### 기본 설정 (httpd.conf)",
    "```apache",
    "# /etc/httpd/conf/httpd.conf 주요 항목",
    "",
    "ServerRoot \"/etc/httpd\"",
    "Listen 80                              # 수신 포트",
    "ServerAdmin admin@example.com          # 관리자 이메일",
    "ServerName www.example.com:80          # 서버 도메인",
    "DocumentRoot \"/var/www/html\"           # 문서 루트",
    "",
    "# 문서 루트 접근 설정",
    "<Directory \"/var/www/html\">",
    "    Options Indexes FollowSymLinks      # Indexes: 파일 목록 표시",
    "    AllowOverride All                   # .htaccess 허용",
    "    Require all granted                 # 모든 접근 허용",
    "</Directory>",
    "",
    "# 기본 문서",
    "DirectoryIndex index.html index.htm",
    "",
    "# 에러 로그",
    "ErrorLog \"logs/error_log\"",
    "",
    "# 접속 로그",
    "CustomLog \"logs/access_log\" combined",
    "```",
    "",
    "#### 주요 설정 항목",
    "| 지시어 | 설명 |",
    "|--------|------|",
    "| `Listen` | 수신할 포트 (기본 80) |",
    "| `ServerName` | 서버의 호스트명 |",
    "| `DocumentRoot` | 웹 파일이 위치하는 루트 경로 |",
    "| `DirectoryIndex` | 기본 문서 파일명 |",
    "| `Options Indexes` | 디렉터리 파일 목록 표시 (보안상 끄는 것 권장) |",
    "| `Options FollowSymLinks` | 심볼릭 링크 허용 |",
    "| `AllowOverride` | `.htaccess` 사용 여부 (None/All) |",
    "| `ErrorLog` | 에러 로그 경로 |",
    "| `CustomLog` | 접속 로그 경로 |",
    "",
    "### Apache 가상 호스트 (Virtual Host)",
    "하나의 서버에서 **여러 도메인(사이트)**을 운영할 때 사용합니다.",
    "",
    "```apache",
    "# /etc/httpd/conf.d/vhost.conf (CentOS)",
    "# 또는 /etc/apache2/sites-available/mysite.conf (Ubuntu)",
    "",
    "# 이름 기반 가상 호스트",
    "<VirtualHost *:80>",
    "    ServerName www.site-a.com",
    "    DocumentRoot /var/www/site-a",
    "    ErrorLog /var/log/httpd/site-a-error.log",
    "    CustomLog /var/log/httpd/site-a-access.log combined",
    "</VirtualHost>",
    "",
    "<VirtualHost *:80>",
    "    ServerName www.site-b.com",
    "    DocumentRoot /var/www/site-b",
    "    ErrorLog /var/log/httpd/site-b-error.log",
    "    CustomLog /var/log/httpd/site-b-access.log combined",
    "</VirtualHost>",
    "```",
    "",
    "```bash",
    "# Ubuntu에서 가상 호스트 활성화",
    "a2ensite mysite.conf",
    "a2dissite mysite.conf     # 비활성화",
    "systemctl reload apache2",
    "",
    "# 설정 문법 검사",
    "apachectl configtest",
    "# 또는",
    "httpd -t",
    "```",
    "",
    "### Apache 모듈 관리",
    "```bash",
    "# 설치된 모듈 확인",
    "httpd -M",
    "apache2ctl -M",
    "",
    "# Ubuntu에서 모듈 활성화/비활성화",
    "a2enmod rewrite           # mod_rewrite 활성화",
    "a2enmod ssl               # SSL 모듈 활성화",
    "a2enmod proxy             # 프록시 모듈",
    "a2dismod autoindex        # 모듈 비활성화",
    "systemctl restart apache2",
    "```",
    "",
    "#### 주요 모듈",
    "| 모듈 | 설명 |",
    "|------|------|",
    "| `mod_rewrite` | URL 재작성 (리다이렉트, 클린 URL) |",
    "| `mod_ssl` | HTTPS/SSL 지원 |",
    "| `mod_proxy` | 리버스 프록시 |",
    "| `mod_security` | 웹 방화벽 (WAF) |",
    "| `mod_headers` | HTTP 헤더 조작 |",
    "| `mod_php` | PHP 내장 처리 |",
    "",
    "### Apache .htaccess",
    "디렉터리별로 설정을 덮어쓸 수 있는 파일입니다. `AllowOverride All`이어야 동작합니다.",
    "",
    "```apache",
    "# /var/www/html/.htaccess 예시",
    "",
    "# HTTP → HTTPS 리다이렉트",
    "RewriteEngine On",
    "RewriteCond %{HTTPS} off",
    "RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]",
    "",
    "# 특정 IP 차단",
    "Deny from 192.168.1.100",
    "",
    "# 디렉터리 목록 표시 금지",
    "Options -Indexes",
    "```",
    "",
    "---",
    "",
    "## 3. Nginx 웹서버",
    "",
    "### 설치",
    "```bash",
    "# CentOS/RHEL (EPEL 필요)",
    "yum install epel-release -y",
    "yum install nginx -y",
    "systemctl start nginx",
    "systemctl enable nginx",
    "",
    "# Ubuntu/Debian",
    "apt install nginx -y",
    "systemctl start nginx",
    "systemctl enable nginx",
    "",
    "# 방화벽 허용",
    "firewall-cmd --permanent --add-service=http",
    "firewall-cmd --permanent --add-service=https",
    "firewall-cmd --reload",
    "# 또는",
    "ufw allow 'Nginx Full'",
    "```",
    "",
    "### 디렉터리 구조",
    "| 경로 | 설명 |",
    "|------|------|",
    "| `/etc/nginx/nginx.conf` | **메인 설정 파일** |",
    "| `/etc/nginx/conf.d/` | 추가 설정 (*.conf 자동 로드) |",
    "| `/etc/nginx/sites-available/` | 가상 호스트 설정 (Ubuntu) |",
    "| `/etc/nginx/sites-enabled/` | 활성화된 가상 호스트 (Ubuntu) |",
    "| `/usr/share/nginx/html/` | 기본 문서 루트 (CentOS) |",
    "| `/var/www/html/` | 기본 문서 루트 (Ubuntu) |",
    "| `/var/log/nginx/` | 로그 디렉터리 |",
    "",
    "### Nginx 설정 구조",
    "```",
    "nginx.conf",
    "├── 전역 (Global) 설정          ← worker_processes 등",
    "├── events { }                  ← 연결 처리 방식",
    "├── http { }                    ← HTTP 관련 전역 설정",
    "│   ├── server { }             ← 가상 호스트 (1개 사이트)",
    "│   │   ├── listen             ← 수신 포트",
    "│   │   ├── server_name        ← 도메인",
    "│   │   └── location { }      ← URL 경로별 설정",
    "│   └── server { }             ← 또 다른 사이트",
    "│",
    "└── include conf.d/*.conf      ← 추가 설정 파일 포함",
    "```",
    "",
    "### 기본 설정 (nginx.conf)",
    "```nginx",
    "# /etc/nginx/nginx.conf",
    "",
    "user nginx;                              # 실행 사용자",
    "worker_processes auto;                   # 워커 프로세스 수 (CPU 코어 수만큼)",
    "error_log /var/log/nginx/error.log;",
    "pid /run/nginx.pid;",
    "",
    "events {",
    "    worker_connections 1024;             # 워커당 최대 동시 연결 수",
    "}",
    "",
    "http {",
    "    include /etc/nginx/mime.types;",
    "    default_type application/octet-stream;",
    "",
    "    # 로그 형식",
    "    log_format main '$remote_addr - $remote_user [$time_local] \"$request\" '",
    "                    '$status $body_bytes_sent \"$http_referer\" '",
    "                    '\"$http_user_agent\"';",
    "",
    "    access_log /var/log/nginx/access.log main;",
    "",
    "    sendfile on;                         # 커널 레벨 파일 전송 (성능↑)",
    "    keepalive_timeout 65;                # Keep-Alive 유지 시간",
    "    gzip on;                             # 응답 압축",
    "",
    "    include /etc/nginx/conf.d/*.conf;    # 추가 설정 포함",
    "}",
    "```",
    "",
    "### Nginx 가상 호스트 (Server Block)",
    "```nginx",
    "# /etc/nginx/conf.d/site-a.conf",
    "",
    "server {",
    "    listen 80;",
    "    server_name www.site-a.com site-a.com;",
    "",
    "    root /var/www/site-a;                # 문서 루트",
    "    index index.html index.htm;",
    "",
    "    # 정적 파일 캐시 설정",
    "    location ~* \\.(jpg|jpeg|png|gif|css|js|ico)$ {",
    "        expires 30d;",
    "        add_header Cache-Control \"public, immutable\";",
    "    }",
    "",
    "    # 에러 페이지",
    "    error_page 404 /404.html;",
    "    error_page 500 502 503 504 /50x.html;",
    "",
    "    access_log /var/log/nginx/site-a-access.log;",
    "    error_log /var/log/nginx/site-a-error.log;",
    "}",
    "```",
    "",
    "```bash",
    "# 설정 문법 검사 (반드시!)",
    "nginx -t",
    "",
    "# 설정 리로드 (서비스 무중단)",
    "systemctl reload nginx",
    "",
    "# Ubuntu에서 가상 호스트 활성화",
    "ln -s /etc/nginx/sites-available/site-a.conf /etc/nginx/sites-enabled/",
    "nginx -t && systemctl reload nginx",
    "```",
    "",
    "### Nginx location 블록",
    "URL 경로에 따라 다른 처리를 할 때 사용합니다.",
    "",
    "```nginx",
    "server {",
    "    listen 80;",
    "    server_name example.com;",
    "",
    "    # 정확히 / 일 때",
    "    location = / {",
    "        return 200 'Welcome!';",
    "    }",
    "",
    "    # /images/로 시작하는 경로",
    "    location /images/ {",
    "        root /var/www;",
    "    }",
    "",
    "    # 정규표현식 매칭 (대소문자 구분)",
    "    location ~ \\.php$ {",
    "        fastcgi_pass 127.0.0.1:9000;",
    "    }",
    "",
    "    # 정규표현식 매칭 (대소문자 무시)",
    "    location ~* \\.(jpg|png|gif)$ {",
    "        expires 30d;",
    "    }",
    "}",
    "```",
    "",
    "#### location 매칭 우선순위",
    "| 우선순위 | 기호 | 의미 | 예시 |",
    "|---------|------|------|------|",
    "| 1 | `=` | 정확히 일치 | `location = /login` |",
    "| 2 | `^~` | 접두어 일치 (정규식 검사 안 함) | `location ^~ /static/` |",
    "| 3 | `~` | 정규표현식 (대소문자 구분) | `location ~ \\.php$` |",
    "| 4 | `~*` | 정규표현식 (대소문자 무시) | `location ~* \\.(jpg|png)$` |",
    "| 5 | 없음 | 접두어 일치 (가장 긴 것 우선) | `location /api/` |",
    "",
    "---",
    "",
    "## 4. 리버스 프록시",
    "",
    "Nginx가 클라이언트 요청을 받아 **백엔드 서버(WAS)에 전달**하는 구성입니다. 실무에서 가장 흔한 패턴입니다.",
    "",
    "```",
    "클라이언트 → Nginx (80/443) → 백엔드 앱 (3000, 8080 등)",
    "                │",
    "                ├→ Spring Boot  :8080",
    "                ├→ Node.js      :3000",
    "                └→ Django       :8000",
    "```",
    "",
    "### Nginx 리버스 프록시 설정",
    "```nginx",
    "# /etc/nginx/conf.d/app.conf",
    "",
    "server {",
    "    listen 80;",
    "    server_name api.example.com;",
    "",
    "    location / {",
    "        proxy_pass http://127.0.0.1:8080;          # 백엔드로 전달",
    "        proxy_set_header Host $host;                # 원래 호스트 전달",
    "        proxy_set_header X-Real-IP $remote_addr;    # 실제 클라이언트 IP",
    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "    }",
    "}",
    "```",
    "",
    "### Apache 리버스 프록시 설정",
    "```apache",
    "# mod_proxy 활성화 필요",
    "# a2enmod proxy proxy_http (Ubuntu)",
    "",
    "<VirtualHost *:80>",
    "    ServerName api.example.com",
    "",
    "    ProxyPreserveHost On",
    "    ProxyPass / http://127.0.0.1:8080/",
    "    ProxyPassReverse / http://127.0.0.1:8080/",
    "</VirtualHost>",
    "```",
    "",
    "---",
    "",
    "## 5. 로드 밸런싱",
    "",
    "여러 백엔드 서버에 트래픽을 **분산**합니다.",
    "",
    "```",
    "                    ┌→ 백엔드 서버 1 (:8080)",
    "클라이언트 → Nginx ─┼→ 백엔드 서버 2 (:8081)",
    "                    └→ 백엔드 서버 3 (:8082)",
    "```",
    "",
    "### Nginx 로드 밸런싱",
    "```nginx",
    "upstream backend {",
    "    # 기본: 라운드 로빈 (순서대로 분배)",
    "    server 192.168.1.10:8080;",
    "    server 192.168.1.11:8080;",
    "    server 192.168.1.12:8080;",
    "",
    "    # 가중치 (weight가 큰 서버에 더 많이 분배)",
    "    # server 192.168.1.10:8080 weight=3;",
    "    # server 192.168.1.11:8080 weight=1;",
    "",
    "    # least_conn: 연결 수가 가장 적은 서버에 분배",
    "    # least_conn;",
    "",
    "    # ip_hash: 같은 IP는 같은 서버로 (세션 유지)",
    "    # ip_hash;",
    "}",
    "",
    "server {",
    "    listen 80;",
    "    server_name www.example.com;",
    "",
    "    location / {",
    "        proxy_pass http://backend;",
    "        proxy_set_header Host $host;",
    "        proxy_set_header X-Real-IP $remote_addr;",
    "    }",
    "}",
    "```",
    "",
    "#### 로드 밸런싱 알고리즘",
    "| 알고리즘 | 설명 |",
    "|---------|------|",
    "| **Round Robin** (기본) | 순서대로 분배 |",
    "| **Least Connections** | 연결 수가 가장 적은 서버로 |",
    "| **IP Hash** | 같은 클라이언트 IP → 같은 서버 (세션 유지) |",
    "| **Weight** | 가중치에 따라 비율 분배 |",
    "",
    "---",
    "",
    "## 6. HTTPS / SSL 설정",
    "",
    "### Let's Encrypt 무료 SSL 인증서 (Certbot)",
    "```bash",
    "# Certbot 설치",
    "# CentOS",
    "yum install certbot python3-certbot-nginx -y",
    "# Ubuntu",
    "apt install certbot python3-certbot-nginx -y",
    "",
    "# Nginx용 SSL 인증서 자동 발급 + 설정",
    "certbot --nginx -d www.example.com -d example.com",
    "",
    "# Apache용",
    "certbot --apache -d www.example.com",
    "",
    "# 인증서 자동 갱신 테스트",
    "certbot renew --dry-run",
    "",
    "# 자동 갱신 cron (보통 certbot이 자동 등록)",
    "# 0 0,12 * * * certbot renew --quiet",
    "```",
    "",
    "### Nginx HTTPS 설정 (수동)",
    "```nginx",
    "server {",
    "    listen 80;",
    "    server_name www.example.com;",
    "    return 301 https://$host$request_uri;     # HTTP → HTTPS 리다이렉트",
    "}",
    "",
    "server {",
    "    listen 443 ssl;",
    "    server_name www.example.com;",
    "",
    "    ssl_certificate     /etc/letsencrypt/live/www.example.com/fullchain.pem;",
    "    ssl_certificate_key /etc/letsencrypt/live/www.example.com/privkey.pem;",
    "",
    "    ssl_protocols TLSv1.2 TLSv1.3;",
    "    ssl_ciphers HIGH:!aNULL:!MD5;",
    "",
    "    location / {",
    "        proxy_pass http://127.0.0.1:8080;",
    "        proxy_set_header Host $host;",
    "        proxy_set_header X-Real-IP $remote_addr;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "    }",
    "}",
    "```",
    "",
    "### Apache HTTPS 설정",
    "```apache",
    "<VirtualHost *:80>",
    "    ServerName www.example.com",
    "    Redirect permanent / https://www.example.com/",
    "</VirtualHost>",
    "",
    "<VirtualHost *:443>",
    "    ServerName www.example.com",
    "    DocumentRoot /var/www/html",
    "",
    "    SSLEngine on",
    "    SSLCertificateFile /etc/letsencrypt/live/www.example.com/fullchain.pem",
    "    SSLCertificateKeyFile /etc/letsencrypt/live/www.example.com/privkey.pem",
    "</VirtualHost>",
    "```",
    "",
    "---",
    "",
    "## 7. 로그 관리",
    "",
    "### Nginx 로그",
    "```bash",
    "# 접속 로그 (누가, 언제, 무엇을 요청했는지)",
    "tail -f /var/log/nginx/access.log",
    "",
    "# 에러 로그",
    "tail -f /var/log/nginx/error.log",
    "",
    "# 로그 형식 예시",
    "# 192.168.1.5 - - [03/Mar/2026:10:30:00 +0900] \"GET /api/users HTTP/1.1\" 200 1234",
    "#     │             │                              │                    │    │",
    "#   클라이언트IP    시간                          요청 내용            상태  크기",
    "```",
    "",
    "### Apache 로그",
    "```bash",
    "# CentOS",
    "tail -f /var/log/httpd/access_log",
    "tail -f /var/log/httpd/error_log",
    "",
    "# Ubuntu",
    "tail -f /var/log/apache2/access.log",
    "tail -f /var/log/apache2/error.log",
    "```",
    "",
    "### 로그 로테이션",
    "로그 파일이 무한히 커지지 않도록 `/etc/logrotate.d/`에서 관리합니다.",
    "",
    "```bash",
    "# /etc/logrotate.d/nginx (보통 자동 생성됨)",
    "/var/log/nginx/*.log {",
    "    daily",
    "    missingok",
    "    rotate 14            # 14일치 보관",
    "    compress",
    "    notifempty",
    "    create 0640 nginx adm",
    "    sharedscripts",
    "    postrotate",
    "        [ -f /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`",
    "    endscript",
    "}",
    "```",
    "",
    "---",
    "",
    "## 8. 보안 설정",
    "",
    "### Nginx 보안",
    "```nginx",
    "server {",
    "    # 서버 버전 정보 숨기기",
    "    server_tokens off;",
    "",
    "    # 보안 헤더",
    "    add_header X-Frame-Options \"SAMEORIGIN\" always;",
    "    add_header X-Content-Type-Options \"nosniff\" always;",
    "    add_header X-XSS-Protection \"1; mode=block\" always;",
    "",
    "    # 특정 IP만 허용 (관리자 페이지 등)",
    "    location /admin/ {",
    "        allow 192.168.1.0/24;",
    "        deny all;",
    "    }",
    "",
    "    # 숨김 파일 접근 차단",
    "    location ~ /\\. {",
    "        deny all;",
    "    }",
    "",
    "    # 요청 크기 제한 (업로드 제한)",
    "    client_max_body_size 10M;",
    "}",
    "```",
    "",
    "### Apache 보안",
    "```apache",
    "# 서버 정보 숨기기",
    "ServerTokens Prod",
    "ServerSignature Off",
    "",
    "# 디렉터리 목록 표시 금지",
    "<Directory /var/www/html>",
    "    Options -Indexes",
    "</Directory>",
    "",
    "# 특정 IP 차단",
    "<Directory /var/www/html/admin>",
    "    Require ip 192.168.1.0/24",
    "</Directory>",
    "```",
    "",
    "---",
    "",
    "## 9. 성능 튜닝",
    "",
    "### Nginx 성능 설정",
    "```nginx",
    "# 워커 설정",
    "worker_processes auto;                    # CPU 코어 수만큼",
    "worker_connections 4096;                  # 워커당 최대 연결",
    "",
    "# HTTP 설정",
    "http {",
    "    sendfile on;",
    "    tcp_nopush on;                        # sendfile과 함께 사용",
    "    tcp_nodelay on;",
    "",
    "    # Gzip 압축",
    "    gzip on;",
    "    gzip_types text/plain text/css application/json application/javascript;",
    "    gzip_min_length 1000;",
    "",
    "    # 정적 파일 캐시",
    "    open_file_cache max=1000 inactive=20s;",
    "    open_file_cache_valid 30s;",
    "",
    "    # Keep-Alive",
    "    keepalive_timeout 65;",
    "    keepalive_requests 100;",
    "}",
    "```",
    "",
    "### Apache MPM (Multi-Processing Module)",
    "Apache의 동시 접속 처리 방식입니다.",
    "",
    "| MPM | 방식 | 특징 |",
    "|-----|------|------|",
    "| **prefork** | 프로세스 1개 = 연결 1개 | 안정적, 메모리 많이 사용 (mod_php 필요 시) |",
    "| **worker** | 스레드 기반 | prefork보다 효율적 |",
    "| **event** | 이벤트 기반 | **가장 효율적** (Apache 2.4 기본) |",
    "",
    "```apache",
    "# /etc/httpd/conf.modules.d/00-mpm.conf",
    "# 사용할 MPM만 활성화",
    "LoadModule mpm_event_module modules/mod_mpm_event.so",
    "# LoadModule mpm_prefork_module modules/mod_mpm_prefork.so",
    "# LoadModule mpm_worker_module modules/mod_mpm_worker.so",
    "```",
    "",
    "---",
    "",
    "## 10. 실무에서의 웹서버 구성",
    "",
    "### 가장 흔한 구성: Nginx + 백엔드",
    "```",
    "인터넷 → Nginx (443) ─→ Spring Boot (:8080)",
    "              │",
    "              ├─→ 정적 파일 직접 서빙 (CSS, JS, 이미지)",
    "              ├─→ /api → 백엔드로 프록시",
    "              └─→ HTTPS 처리, 압축, 캐시",
    "```",
    "",
    "```nginx",
    "server {",
    "    listen 443 ssl;",
    "    server_name www.example.com;",
    "",
    "    ssl_certificate     /etc/letsencrypt/live/www.example.com/fullchain.pem;",
    "    ssl_certificate_key /etc/letsencrypt/live/www.example.com/privkey.pem;",
    "",
    "    # 프론트엔드 정적 파일",
    "    location / {",
    "        root /var/www/frontend/dist;",
    "        try_files $uri $uri/ /index.html;    # SPA 라우팅 지원",
    "    }",
    "",
    "    # API 요청 → 백엔드",
    "    location /api/ {",
    "        proxy_pass http://127.0.0.1:8080;",
    "        proxy_set_header Host $host;",
    "        proxy_set_header X-Real-IP $remote_addr;",
    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "    }",
    "}",
    "```",
    "",
    "### 웹서버 관리 명령어 정리",
    "| 작업 | Nginx | Apache (CentOS) | Apache (Ubuntu) |",
    "|------|-------|-----------------|-----------------|",
    "| 시작 | `systemctl start nginx` | `systemctl start httpd` | `systemctl start apache2` |",
    "| 중지 | `systemctl stop nginx` | `systemctl stop httpd` | `systemctl stop apache2` |",
    "| 재시작 | `systemctl restart nginx` | `systemctl restart httpd` | `systemctl restart apache2` |",
    "| 리로드 | `systemctl reload nginx` | `systemctl reload httpd` | `systemctl reload apache2` |",
    "| 설정 검사 | `nginx -t` | `httpd -t` | `apachectl configtest` |",
    "| 버전 확인 | `nginx -v` | `httpd -v` | `apache2 -v` |",
    "",
    "---",
    "",
    "### 요약",
    "- **Apache**: 모듈 기반, `.htaccess`로 디렉터리별 설정, `mod_php`로 PHP 내장 처리 가능",
    "- **Nginx**: 이벤트 기반 고성능, 적은 메모리로 높은 동시 접속 처리, 리버스 프록시·로드밸런싱에 강함",
    "- **가상 호스트**: 하나의 서버에서 여러 도메인 운영 (Apache: `<VirtualHost>`, Nginx: `server { }`)",
    "- **리버스 프록시**: `proxy_pass`(Nginx) / `ProxyPass`(Apache)로 백엔드에 요청 전달",
    "- **로드 밸런싱**: `upstream` 블록으로 여러 백엔드에 트래픽 분산 (Round Robin, Least Conn, IP Hash)",
    "- **HTTPS**: Let's Encrypt + Certbot으로 무료 SSL 발급, 자동 갱신",
    "- **보안**: 버전 숨기기, 보안 헤더, 디렉터리 목록 비활성화, 접근 제어",
    "- **실무 표준**: Nginx(리버스 프록시 + HTTPS + 정적 파일) + 백엔드 앱 조합"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
