<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-lvm",
  title: "LVM(Logical Volume Manager)이란?",
  date: "2026-02-24",
  summary: "LVM은 물리 디스크를 논리적으로 묶어 유연하게 파티션 크기를 조절할 수 있는 리눅스 디스크 관리 기술입니다. PV, VG, LV 개념과 확장·축소·스냅샷까지 정리합니다.",
  category: "Technology/Linux",
  tags: ["linux","lvm","disk","partition","volume","storage","basics"],
  content: [
    "## 한 줄 요약",
    "**LVM(Logical Volume Manager)**은 물리 디스크와 파티션 사이에 **논리적인 계층**을 추가해서, 파티션 크기를 자유롭게 늘리거나 줄이고, 여러 디스크를 하나로 묶을 수 있게 해주는 기술입니다.",
    "",
    "## 왜 LVM이 필요할까",
    "",
    "### 일반 파티션의 한계",
    "일반 파티션은 한번 크기를 정하면 변경이 어렵습니다.",
    "",
    "| 상황 | 일반 파티션 | LVM |",
    "|------|-----------|-----|",
    "| /home이 꽉 찼는데 /var에 여유 공간이 있음 | 옮기기 매우 어려움 | 간단한 명령어로 크기 조절 |",
    "| 디스크를 추가해서 기존 파티션을 확장하고 싶음 | 불가능 (새 마운트포인트 필요) | 기존 볼륨에 디스크 추가 후 확장 |",
    "| 디스크 교체 시 데이터 이동 | 백업 → 재설치 → 복원 | pvmove로 온라인 이동 |",
    "| 스냅샷을 찍어 백업하고 싶음 | 별도 도구 필요 | LV 스냅샷 기본 지원 |",
    "",
    "## LVM 구조: PV → VG → LV",
    "",
    "LVM은 3단계 구조로 디스크를 관리합니다.",
    "",
    "```",
    "물리 디스크/파티션",
    "  │",
    "  ▼",
    "┌─────────────────────────────────────┐",
    "│  PV (Physical Volume)               │  ← 물리 볼륨: 디스크/파티션을 LVM에 등록",
    "│  /dev/sda1, /dev/sdb1, /dev/sdc     │",
    "└─────────────┬───────────────────────┘",
    "              │",
    "              ▼",
    "┌─────────────────────────────────────┐",
    "│  VG (Volume Group)                  │  ← 볼륨 그룹: PV를 하나의 저장소 풀로 묶음",
    "│  예: vg_data                        │",
    "└─────────────┬───────────────────────┘",
    "              │",
    "              ▼",
    "┌────────┐ ┌────────┐ ┌────────┐",
    "│ LV     │ │ LV     │ │ LV     │     ← 논리 볼륨: 실제 사용하는 \"가상 파티션\"",
    "│ lv_root│ │lv_home │ │lv_var  │",
    "│  /     │ │ /home  │ │ /var   │",
    "└────────┘ └────────┘ └────────┘",
    "```",
    "",
    "### 각 계층 설명",
    "",
    "| 계층 | 이름 | 역할 | 비유 |",
    "|------|------|------|------|",
    "| PV | Physical Volume | 물리 디스크/파티션을 LVM에 등록 | 재료 (밀가루 봉지) |",
    "| VG | Volume Group | PV들을 하나의 큰 저장소 풀로 묶음 | 반죽통 (재료를 합친 것) |",
    "| LV | Logical Volume | VG에서 원하는 크기만큼 떼어낸 논리적 파티션 | 빵 (원하는 크기로 자름) |",
    "",
    "LV 위에 파일시스템(ext4, xfs 등)을 만들고 마운트하면 일반 파티션처럼 사용합니다.",
    "",
    "## 기본 사용법",
    "",
    "### 1) PV 생성 (Physical Volume)",
    "디스크/파티션을 LVM용으로 초기화합니다.",
    "",
    "```bash",
    "sudo pvcreate /dev/sdb",
    "sudo pvcreate /dev/sdc1",
    "```",
    "",
    "### 2) VG 생성 (Volume Group)",
    "PV를 묶어 볼륨 그룹을 만듭니다.",
    "",
    "```bash",
    "sudo vgcreate vg_data /dev/sdb /dev/sdc1",
    "```",
    "",
    "### 3) LV 생성 (Logical Volume)",
    "볼륨 그룹에서 원하는 크기만큼 논리 볼륨을 만듭니다.",
    "",
    "```bash",
    "sudo lvcreate -L 50G -n lv_home vg_data",
    "sudo lvcreate -L 20G -n lv_var vg_data",
    "sudo lvcreate -l 100%FREE -n lv_backup vg_data   # 남은 공간 전부 사용",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -L 50G | 크기 지정 (G, M, T) |",
    "| -l 100%FREE | 남은 공간의 비율로 지정 |",
    "| -n lv_home | 논리 볼륨 이름 |",
    "",
    "### 4) 파일시스템 생성 + 마운트",
    "```bash",
    "sudo mkfs.ext4 /dev/vg_data/lv_home",
    "sudo mkdir -p /home",
    "sudo mount /dev/vg_data/lv_home /home",
    "```",
    "",
    "LV의 경로는 `/dev/VG이름/LV이름` 형식입니다.",
    "",
    "### 5) /etc/fstab 등록 (자동 마운트)",
    "```",
    "/dev/vg_data/lv_home   /home   ext4   defaults   0   2",
    "/dev/vg_data/lv_var    /var    ext4   defaults   0   2",
    "```",
    "",
    "## LV 크기 조절",
    "",
    "LVM의 가장 큰 장점은 **운영 중에도 볼륨 크기를 변경**할 수 있다는 것입니다.",
    "",
    "### 확장 (늘리기)",
    "```bash",
    "# LV 크기를 10G 추가",
    "sudo lvextend -L +10G /dev/vg_data/lv_home",
    "",
    "# 파일시스템도 함께 확장 (-r 옵션)",
    "sudo lvextend -L +10G -r /dev/vg_data/lv_home",
    "",
    "# VG 남은 공간 전부 사용",
    "sudo lvextend -l +100%FREE -r /dev/vg_data/lv_home",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -L +10G | 10G만큼 추가 |",
    "| -L 80G | 총 80G로 설정 |",
    "| -l +100%FREE | 남은 공간 전부 추가 |",
    "| -r | 파일시스템도 자동으로 함께 확장 (resize2fs 불필요) |",
    "",
    "ext4는 온라인(마운트 상태) 확장이 가능합니다. xfs도 마찬가지입니다.",
    "",
    "### 축소 (줄이기)",
    "```bash",
    "# ext4: 언마운트 후 축소",
    "sudo umount /home",
    "sudo lvreduce -L 30G -r /dev/vg_data/lv_home",
    "sudo mount /dev/vg_data/lv_home /home",
    "```",
    "",
    "**주의**: 축소는 데이터 손실 위험이 있으므로 반드시 **백업 후** 진행합니다. xfs는 축소를 지원하지 않습니다.",
    "",
    "## VG에 디스크 추가",
    "",
    "서버 용량이 부족할 때, 새 디스크를 추가해서 기존 볼륨을 확장할 수 있습니다.",
    "",
    "```bash",
    "# 새 디스크를 PV로 초기화",
    "sudo pvcreate /dev/sdd",
    "",
    "# 기존 VG에 추가",
    "sudo vgextend vg_data /dev/sdd",
    "",
    "# 이제 VG 전체 용량이 늘어남 → LV를 확장 가능",
    "sudo lvextend -l +100%FREE -r /dev/vg_data/lv_home",
    "```",
    "",
    "이것이 일반 파티션으로는 불가능한, LVM의 핵심 장점입니다.",
    "",
    "## 스냅샷 (Snapshot)",
    "",
    "LVM 스냅샷은 특정 시점의 LV 상태를 **복사 없이 보존**합니다 (COW: Copy-On-Write 방식).",
    "",
    "```bash",
    "# 스냅샷 생성 (변경 데이터를 저장할 공간 5G 할당)",
    "sudo lvcreate -L 5G -s -n lv_home_snap /dev/vg_data/lv_home",
    "",
    "# 스냅샷 마운트해서 확인",
    "sudo mount -o ro /dev/vg_data/lv_home_snap /mnt/snapshot",
    "",
    "# 스냅샷으로 복원",
    "sudo lvconvert --merge /dev/vg_data/lv_home_snap",
    "",
    "# 스냅샷 삭제",
    "sudo lvremove /dev/vg_data/lv_home_snap",
    "```",
    "",
    "| 용도 | 설명 |",
    "|------|------|",
    "| 백업 전 상태 보존 | 업데이트/변경 전 스냅샷 → 문제 시 롤백 |",
    "| 일관된 백업 | 스냅샷을 마운트해서 백업하면 변경 중인 파일 영향 없음 |",
    "| 테스트 | 설정 변경 테스트 후 문제 시 복원 |",
    "",
    "## 확인 명령어",
    "",
    "### PV 확인",
    "```bash",
    "sudo pvs          # 간략 목록",
    "sudo pvdisplay    # 상세 정보",
    "```",
    "```",
    "  PV         VG      Fmt  Attr PSize   PFree",
    "  /dev/sdb   vg_data lvm2 a--  100.00g  30.00g",
    "  /dev/sdc1  vg_data lvm2 a--   50.00g   0",
    "```",
    "",
    "### VG 확인",
    "```bash",
    "sudo vgs          # 간략 목록",
    "sudo vgdisplay    # 상세 정보",
    "```",
    "```",
    "  VG      #PV #LV #SN Attr   VSize   VFree",
    "  vg_data   2   3   0 wz--n- 150.00g 30.00g",
    "```",
    "",
    "### LV 확인",
    "```bash",
    "sudo lvs          # 간략 목록",
    "sudo lvdisplay    # 상세 정보",
    "```",
    "```",
    "  LV        VG      Attr       LSize  Pool Origin Data%",
    "  lv_home   vg_data -wi-ao---- 50.00g",
    "  lv_var    vg_data -wi-ao---- 20.00g",
    "  lv_backup vg_data -wi-ao---- 50.00g",
    "```",
    "",
    "## 일반 파티션 vs LVM 비교",
    "",
    "| 기준 | 일반 파티션 | LVM |",
    "|------|-----------|-----|",
    "| 크기 변경 | 매우 어려움 | 명령어로 확장/축소 |",
    "| 여러 디스크를 하나로 | 불가 | VG로 묶기 가능 |",
    "| 스냅샷 | 별도 도구 | 기본 지원 |",
    "| 온라인 확장 | 제한적 | 마운트 상태에서 확장 가능 |",
    "| 디스크 추가 후 확장 | 새 마운트포인트 필요 | 기존 LV에 공간 추가 |",
    "| 복잡도 | 단순 | PV/VG/LV 개념 학습 필요 |",
    "| 성능 | 약간 유리 | 미세한 오버헤드 (실무에서 무시 가능) |",
    "",
    "## 실전 예시: 서버 구성",
    "",
    "```bash",
    "# 디스크 2개를 LVM으로 구성",
    "sudo pvcreate /dev/sdb /dev/sdc",
    "sudo vgcreate vg_server /dev/sdb /dev/sdc",
    "",
    "sudo lvcreate -L 30G -n lv_root vg_server",
    "sudo lvcreate -L 50G -n lv_home vg_server",
    "sudo lvcreate -L 20G -n lv_var vg_server",
    "sudo lvcreate -L 4G  -n lv_swap vg_server",
    "",
    "sudo mkfs.ext4 /dev/vg_server/lv_root",
    "sudo mkfs.ext4 /dev/vg_server/lv_home",
    "sudo mkfs.ext4 /dev/vg_server/lv_var",
    "sudo mkswap /dev/vg_server/lv_swap",
    "```",
    "",
    "나중에 /home이 부족하면 `lvextend -L +20G -r /dev/vg_server/lv_home` 한 줄로 확장합니다.",
    "",
    "## 주의사항",
    "",
    "### 1) /boot은 LVM 밖에 두기",
    "GRUB 부트로더가 /boot을 읽어야 하는데, 일부 환경에서 LVM 위의 /boot을 인식하지 못할 수 있습니다. /boot (또는 ESP)은 일반 파티션으로 두는 것이 안전합니다.",
    "",
    "### 2) 축소는 신중하게",
    "LV 축소 시 데이터 손실 위험이 있습니다. 반드시 백업 후 진행하고, xfs는 축소를 지원하지 않습니다.",
    "",
    "### 3) 스냅샷 공간 관리",
    "스냅샷은 원본 변경분을 저장하므로, 변경이 많으면 스냅샷 공간이 가득 찰 수 있습니다. 가득 차면 스냅샷이 무효화되므로 충분한 크기를 할당합니다.",
    "",
    "### 4) 복구 시 LVM 인식",
    "Live USB로 복구할 때 LVM 볼륨을 인식하려면 `sudo vgchange -ay` 명령으로 VG를 활성화해야 합니다.",
    "",
    "---",
    "### 요약",
    "LVM은 PV(물리 볼륨) → VG(볼륨 그룹) → LV(논리 볼륨) 3단계로 디스크를 관리하며, 볼륨 크기를 자유롭게 확장·축소하고, 여러 디스크를 하나로 묶고, 스냅샷을 찍을 수 있습니다. 서버 환경에서 디스크 관리의 유연성을 크게 높여줍니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
