<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "linux-user-management",
  title: "리눅스 사용자 생성 및 계정 관리 명령어",
  date: "2026-02-24",
  summary: "리눅스에서 사용자와 그룹을 생성·수정·삭제하는 핵심 명령어를 정리합니다. useradd, usermod, userdel, passwd, groupadd, su, sudo 등 계정 관리에 필요한 명령어를 예제와 함께 설명합니다.",
  category: "Technology/Linux",
  tags: ["linux","user","group","useradd","usermod","passwd","sudo","account","basics"],
  content: [
    "## 한 줄 요약",
    "리눅스 계정 관리의 핵심은 **useradd(생성)**, **usermod(수정)**, **userdel(삭제)**, **passwd(비밀번호)**, **groupadd(그룹 생성)**, **su/sudo(권한 전환)**이며, 관련 정보는 `/etc/passwd`, `/etc/shadow`, `/etc/group` 파일에 저장됩니다.",
    "",
    "## 사용자 관련 핵심 파일",
    "",
    "명령어를 배우기 전에, 사용자 정보가 저장되는 파일을 먼저 이해해야 합니다.",
    "",
    "### /etc/passwd",
    "모든 사용자 계정 정보가 저장됩니다. 누구나 읽을 수 있습니다.",
    "",
    "```",
    "haru:x:1000:1000:Haru Kim:/home/haru:/bin/bash",
    "```",
    "",
    "| 필드 | 값 | 의미 |",
    "|------|-----|------|",
    "| 1 | haru | 사용자 이름 |",
    "| 2 | x | 비밀번호 (x = /etc/shadow에 저장) |",
    "| 3 | 1000 | UID (사용자 ID) |",
    "| 4 | 1000 | GID (기본 그룹 ID) |",
    "| 5 | Haru Kim | 설명 (GECOS 필드) |",
    "| 6 | /home/haru | 홈 디렉터리 |",
    "| 7 | /bin/bash | 로그인 셸 |",
    "",
    "### /etc/shadow",
    "비밀번호 해시와 만료 정보가 저장됩니다. **root만 읽을 수 있습니다.**",
    "",
    "```",
    "haru:$6$abc...:19777:0:99999:7:::",
    "```",
    "",
    "| 필드 | 의미 |",
    "|------|------|",
    "| 1 | 사용자 이름 |",
    "| 2 | 암호화된 비밀번호 (! 또는 * = 로그인 불가) |",
    "| 3 | 마지막 비밀번호 변경일 (1970-01-01 기준 일수) |",
    "| 4 | 비밀번호 최소 사용 일수 |",
    "| 5 | 비밀번호 최대 사용 일수 |",
    "| 6 | 만료 경고 일수 |",
    "| 7 | 비활성 기간 |",
    "| 8 | 계정 만료일 |",
    "",
    "### /etc/group",
    "그룹 정보가 저장됩니다.",
    "",
    "```",
    "developers:x:1001:haru,kim",
    "```",
    "",
    "| 필드 | 의미 |",
    "|------|------|",
    "| 1 | 그룹 이름 |",
    "| 2 | 비밀번호 (보통 x) |",
    "| 3 | GID (그룹 ID) |",
    "| 4 | 그룹에 속한 사용자 목록 (쉼표 구분) |",
    "",
    "## 사용자 생성",
    "",
    "### useradd",
    "새 사용자를 생성합니다.",
    "",
    "```bash",
    "sudo useradd haru                         # 기본 사용자 생성",
    "sudo useradd -m haru                      # 홈 디렉터리도 함께 생성",
    "sudo useradd -m -s /bin/bash haru         # 홈 디렉터리 + 셸 지정",
    "sudo useradd -m -d /opt/haru haru         # 홈 디렉터리 경로 지정",
    "sudo useradd -m -G sudo,docker haru       # 추가 그룹 지정",
    "sudo useradd -m -u 1500 haru              # UID 지정",
    "sudo useradd -m -e 2026-12-31 haru        # 계정 만료일 지정",
    "sudo useradd -m -c \"Haru Kim\" haru        # 설명(코멘트) 지정",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -m | 홈 디렉터리 생성 (/home/사용자명) |",
    "| -d 경로 | 홈 디렉터리 경로 지정 |",
    "| -s 셸 | 로그인 셸 지정 (/bin/bash, /bin/zsh 등) |",
    "| -G 그룹 | 추가 그룹 지정 (쉼표로 여러 개) |",
    "| -g 그룹 | 기본(primary) 그룹 지정 |",
    "| -u UID | 사용자 ID 지정 |",
    "| -e 날짜 | 계정 만료일 (YYYY-MM-DD) |",
    "| -c 설명 | 사용자 설명 (GECOS) |",
    "| -r | 시스템 계정 생성 (UID가 낮은 범위) |",
    "",
    "### adduser (Debian/Ubuntu)",
    "Debian 계열에서 제공하는 **대화형** 사용자 생성 도구입니다. `useradd`보다 편리합니다.",
    "",
    "```bash",
    "sudo adduser haru",
    "# → 비밀번호, 이름, 전화번호 등을 대화형으로 입력",
    "# → 홈 디렉터리 자동 생성, 셸 자동 설정",
    "```",
    "",
    "| 비교 | useradd | adduser |",
    "|------|---------|---------|",
    "| 방식 | 옵션으로 직접 지정 | 대화형 (질문에 답변) |",
    "| 홈 디렉터리 | -m 옵션 필요 | 자동 생성 |",
    "| 비밀번호 | 별도로 passwd 실행 | 생성 중 설정 |",
    "| 사용 환경 | 모든 배포판 | Debian/Ubuntu 계열 |",
    "",
    "## 사용자 수정",
    "",
    "### usermod",
    "기존 사용자의 속성을 변경합니다.",
    "",
    "```bash",
    "sudo usermod -s /bin/zsh haru             # 셸 변경",
    "sudo usermod -d /new/home haru            # 홈 디렉터리 변경",
    "sudo usermod -d /new/home -m haru         # 홈 디렉터리 변경 + 파일 이동",
    "sudo usermod -aG docker haru              # 그룹 추가 (-a: 기존 유지하며 추가)",
    "sudo usermod -G sudo haru                 # 그룹 덮어쓰기 (기존 그룹 제거!)",
    "sudo usermod -L haru                      # 계정 잠금 (로그인 불가)",
    "sudo usermod -U haru                      # 계정 잠금 해제",
    "sudo usermod -l newname haru              # 사용자 이름 변경",
    "sudo usermod -e 2026-12-31 haru           # 계정 만료일 설정",
    "sudo usermod -c \"New Comment\" haru        # 설명 변경",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -s 셸 | 로그인 셸 변경 |",
    "| -d 경로 | 홈 디렉터리 변경 |",
    "| -m | 홈 디렉터리 변경 시 기존 파일도 이동 |",
    "| -aG 그룹 | 기존 그룹을 유지하면서 그룹 추가 |",
    "| -G 그룹 | 그룹 목록 덮어쓰기 (주의!) |",
    "| -L / -U | 계정 잠금 / 해제 |",
    "| -l 이름 | 사용자 이름 변경 |",
    "| -e 날짜 | 계정 만료일 |",
    "",
    "> **주의**: `-aG`와 `-G`는 다릅니다. `-aG docker`는 docker 그룹을 **추가**하지만, `-G docker`만 쓰면 기존 그룹이 모두 제거되고 docker만 남습니다. 그룹을 추가할 때는 반드시 **-aG**를 사용하세요.",
    "",
    "## 사용자 삭제",
    "",
    "### userdel",
    "사용자를 삭제합니다.",
    "",
    "```bash",
    "sudo userdel haru                         # 사용자 삭제 (홈 디렉터리 유지)",
    "sudo userdel -r haru                      # 사용자 + 홈 디렉터리 + 메일 삭제",
    "sudo userdel -f haru                      # 로그인 중이어도 강제 삭제",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -r | 홈 디렉터리와 메일함도 함께 삭제 |",
    "| -f | 강제 삭제 (로그인 중이어도) |",
    "",
    "## 비밀번호 관리",
    "",
    "### passwd",
    "사용자 비밀번호를 설정·변경합니다.",
    "",
    "```bash",
    "passwd                                    # 자신의 비밀번호 변경",
    "sudo passwd haru                          # 다른 사용자 비밀번호 변경 (root)",
    "sudo passwd -l haru                       # 계정 잠금",
    "sudo passwd -u haru                       # 계정 잠금 해제",
    "sudo passwd -d haru                       # 비밀번호 삭제 (빈 비밀번호)",
    "sudo passwd -e haru                       # 다음 로그인 시 비밀번호 변경 강제",
    "sudo passwd -S haru                       # 비밀번호 상태 확인",
    "```",
    "",
    "### chage (비밀번호 정책)",
    "비밀번호 만료 정책을 관리합니다.",
    "",
    "```bash",
    "sudo chage -l haru                        # 비밀번호 정책 확인",
    "sudo chage -M 90 haru                     # 최대 90일마다 변경 필요",
    "sudo chage -m 7 haru                      # 최소 7일 후에 변경 가능",
    "sudo chage -W 14 haru                     # 만료 14일 전 경고",
    "sudo chage -E 2026-12-31 haru             # 계정 만료일 설정",
    "sudo chage -d 0 haru                      # 다음 로그인 시 비밀번호 변경 강제",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| -l | 현재 정책 확인 |",
    "| -M 일수 | 비밀번호 최대 사용 기간 |",
    "| -m 일수 | 비밀번호 최소 사용 기간 |",
    "| -W 일수 | 만료 전 경고 기간 |",
    "| -E 날짜 | 계정 만료일 |",
    "| -d 0 | 비밀번호 즉시 만료 (변경 강제) |",
    "",
    "## 그룹 관리",
    "",
    "### groupadd",
    "새 그룹을 생성합니다.",
    "",
    "```bash",
    "sudo groupadd developers                  # 그룹 생성",
    "sudo groupadd -g 2000 developers          # GID 지정하여 생성",
    "```",
    "",
    "### groupmod",
    "기존 그룹을 수정합니다.",
    "",
    "```bash",
    "sudo groupmod -n newname oldname           # 그룹 이름 변경",
    "sudo groupmod -g 3000 developers           # GID 변경",
    "```",
    "",
    "### groupdel",
    "그룹을 삭제합니다.",
    "",
    "```bash",
    "sudo groupdel developers                   # 그룹 삭제",
    "```",
    "",
    "해당 그룹을 기본(primary) 그룹으로 사용하는 사용자가 있으면 삭제할 수 없습니다.",
    "",
    "### gpasswd",
    "그룹 멤버를 관리합니다.",
    "",
    "```bash",
    "sudo gpasswd -a haru developers            # 사용자를 그룹에 추가",
    "sudo gpasswd -d haru developers            # 사용자를 그룹에서 제거",
    "sudo gpasswd -A haru developers            # 그룹 관리자 지정",
    "```",
    "",
    "## 사용자 전환 및 권한",
    "",
    "### su (Switch User)",
    "다른 사용자로 전환합니다.",
    "",
    "```bash",
    "su haru                 # haru 사용자로 전환 (환경변수 유지)",
    "su - haru               # haru 사용자로 전환 (로그인 셸, 환경 초기화)",
    "su -                    # root로 전환 (로그인 셸)",
    "su -c \"whoami\" haru     # haru로 명령 1개만 실행 후 복귀",
    "exit                    # 원래 사용자로 돌아감",
    "```",
    "",
    "| 비교 | su haru | su - haru |",
    "|------|---------|-----------|",
    "| 환경변수 | 현재 사용자 것 유지 | haru의 환경으로 초기화 |",
    "| 작업 디렉터리 | 현재 위치 유지 | haru의 홈으로 이동 |",
    "| PATH | 현재 PATH 유지 | haru의 PATH 로드 |",
    "",
    "### sudo (Superuser Do)",
    "현재 사용자 상태에서 **root 권한**으로 명령을 실행합니다.",
    "",
    "```bash",
    "sudo apt update                            # root 권한으로 명령 실행",
    "sudo -u haru command                       # 특정 사용자 권한으로 실행",
    "sudo -i                                    # root 로그인 셸 진입",
    "sudo -s                                    # root 셸 진입 (환경 유지)",
    "sudo -l                                    # 현재 사용자의 sudo 권한 확인",
    "sudo !!                                    # 직전 명령을 sudo로 재실행",
    "```",
    "",
    "### /etc/sudoers 설정",
    "sudo 권한은 `/etc/sudoers` 파일로 관리하며, 반드시 **visudo** 명령으로 편집해야 합니다.",
    "",
    "```bash",
    "sudo visudo              # /etc/sudoers 안전하게 편집",
    "```",
    "",
    "```",
    "# 형식: 사용자  호스트=(실행할 사용자) 명령",
    "haru    ALL=(ALL:ALL) ALL              # haru에게 모든 sudo 권한",
    "haru    ALL=(ALL) NOPASSWD: ALL        # 비밀번호 없이 sudo",
    "%sudo   ALL=(ALL:ALL) ALL              # sudo 그룹 전체에 권한",
    "haru    ALL=(ALL) /usr/bin/apt         # apt 명령만 sudo 허용",
    "```",
    "",
    "| 필드 | 의미 |",
    "|------|------|",
    "| 사용자/% 그룹 | 권한을 부여할 대상 (%는 그룹) |",
    "| ALL=(ALL:ALL) | 모든 호스트에서, 모든 사용자:그룹으로 |",
    "| ALL | 모든 명령 실행 가능 |",
    "| NOPASSWD: | 비밀번호 입력 없이 실행 |",
    "",
    "> **visudo**를 사용하는 이유: 문법 오류가 있으면 저장을 막아줍니다. 직접 편집하다 문법이 깨지면 sudo 자체가 동작하지 않아 시스템을 복구하기 매우 어렵습니다.",
    "",
    "## 사용자 정보 확인",
    "",
    "### 현재 사용자 / 그룹 확인",
    "```bash",
    "whoami                                     # 현재 사용자 이름",
    "id                                         # UID, GID, 속한 그룹 전부",
    "id haru                                    # 특정 사용자 정보",
    "groups                                     # 현재 사용자의 그룹 목록",
    "groups haru                                # 특정 사용자의 그룹 목록",
    "```",
    "",
    "### 로그인/접속 관련",
    "```bash",
    "who                                        # 현재 로그인한 사용자 목록",
    "w                                          # 로그인 사용자 + 작업 정보",
    "last                                       # 최근 로그인 기록",
    "lastlog                                    # 모든 사용자의 마지막 로그인",
    "finger haru                                # 사용자 상세 정보 (설치 필요)",
    "```",
    "",
    "### 사용자 목록 확인",
    "```bash",
    "cat /etc/passwd                            # 전체 사용자 목록",
    "cat /etc/passwd | grep /bin/bash           # 실제 로그인 가능한 사용자",
    "getent passwd                              # 사용자 목록 (LDAP 등 포함)",
    "getent group                               # 그룹 목록",
    "```",
    "",
    "## UID/GID 규칙",
    "",
    "| UID 범위 | 용도 |",
    "|----------|------|",
    "| 0 | root (슈퍼유저) |",
    "| 1 ~ 999 | 시스템 계정 (서비스용) |",
    "| 1000 ~ | 일반 사용자 계정 |",
    "",
    "## 자주 쓰는 조합 정리",
    "",
    "| 목적 | 명령어 |",
    "|------|--------|",
    "| 사용자 생성 (추천) | `sudo useradd -m -s /bin/bash username` |",
    "| 비밀번호 설정 | `sudo passwd username` |",
    "| 그룹에 사용자 추가 | `sudo usermod -aG groupname username` |",
    "| 사용자 완전 삭제 | `sudo userdel -r username` |",
    "| sudo 권한 부여 | `sudo usermod -aG sudo username` |",
    "| 계정 잠금 | `sudo usermod -L username` |",
    "| 현재 사용자 확인 | `whoami` 또는 `id` |",
    "| 접속 중인 사용자 | `who` 또는 `w` |",
    "| 비밀번호 정책 확인 | `sudo chage -l username` |",
    "| sudo 편집 | `sudo visudo` |",
    "",
    "---",
    "### 요약",
    "리눅스 계정 관리의 핵심은 **useradd → passwd → usermod → userdel** 흐름입니다. 그룹은 **groupadd/gpasswd**로 관리하고, 권한 전환은 **su(사용자 전환)**와 **sudo(관리자 권한 실행)**를 사용합니다. 보안상 root 직접 로그인보다는 sudo를 통한 권한 상승이 권장됩니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
