<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "logistic-regression",
  title: "로지스틱 회귀(Logistic Regression)",
  date: "2026-02-17",
  summary: "로지스틱 회귀는 이진 분류를 위한 지도 학습 알고리즘입니다. 시그모이드 함수, 결정 경계, 확률 출력, 사이킷런 LogisticRegression까지 정리합니다.",
  category: "Technology/AI",
  tags: ["ai", "machine-learning", "logistic-regression", "classification", "scikit-learn"],
  content: [
    "## 로지스틱 회귀란?",
    "**로지스틱 회귀(Logistic Regression)**는 이름에 '회귀'가 있지만 **이진 분류**에 사용되는 지도 학습 알고리즘입니다. 선형 회귀와 달리 **시그모이드 함수**를 사용해 0~1 사이의 확률을 출력합니다.",
    "",
    "시그모이드: σ(z) = 1 / (1 + e^(-z))",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| 출력 | 클래스에 속할 **확률** (0~1) |",
    "| 결정 경계 | 직선(또는 평면)으로 영역 분리 |",
    "| 해석 | 특성별 기여도 파악 용이 |",
    "| 다중 클래스 | One-vs-Rest 등으로 확장 가능 |",
    "",
    "---",
    "## 기본 사용법",
    "사이킷런의 `LogisticRegression`으로 이진 분류를 수행합니다.",
    "",
    "```python",
    "from sklearn.linear_model import LogisticRegression",
    "",
    "lr = LogisticRegression()",
    "lr.fit(train_input, train_target)",
    "",
    "# 정확도",
    "print(lr.score(train_input, train_target))",
    "print(lr.score(test_input, test_target))",
    "",
    "# 예측 (0 또는 1)",
    "print(lr.predict(test_input[:5]))",
    "",
    "# 각 클래스에 속할 확률 (predict_proba)",
    "print(lr.predict_proba(test_input[:5]))",
    "```",
    "",
    "---",
    "## C 파라미터와 규제",
    "`C`는 **규제 강도의 역수**입니다. C가 크면 규제가 약해져 훈련 데이터에 더 맞추고, C가 작으면 규제가 강해져 일반화를 우선합니다.",
    "",
    "```python",
    "lr = LogisticRegression(C=20, max_iter=1000)",
    "lr.fit(train_input, train_target)",
    "print(lr.score(train_input, train_target))",
    "```",
    "",
    "`max_iter`: 수렴을 위한 최대 반복 횟수. 경고가 나오면 늘려줍니다.",
    "",
    "---",
    "## 결정 경계 시각화",
    "```python",
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "",
    "# 그리드 생성",
    "x_min, x_max = train_input[:, 0].min() - 1, train_input[:, 0].max() + 1",
    "y_min, y_max = train_input[:, 1].min() - 1, train_input[:, 1].max() + 1",
    "xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100),",
    "                     np.linspace(y_min, y_max, 100))",
    "",
    "Z = lr.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)",
    "plt.contourf(xx, yy, Z, alpha=0.3)",
    "plt.scatter(train_input[:, 0], train_input[:, 1], c=train_target)",
    "plt.xlabel('length')",
    "plt.ylabel('weight')",
    "plt.show()",
    "```",
    "",
    "---",
    "## 정리",
    "| 용어 | 요약 |",
    "|------|------|",
    "| 로지스틱 회귀 | 시그모이드로 확률 출력, 이진 분류 |",
    "| 시그모이드 | 0~1 확률로 변환 |",
    "| predict_proba | 클래스별 확률 반환 |",
    "| C | 규제 강도 역수 (클수록 규제 약함) |",
    "| max_iter | 최대 반복 횟수 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
