<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "neural-network-training",
  title: "신경망 모델 훈련",
  date: "2026-02-17",
  summary: "신경망 훈련의 핵심: 손실 함수, 옵티마이저, 손실 곡선, Early Stopping, Dropout, 콜백을 정리합니다.",
  category: "Technology/AI",
  tags: ["ai", "deep-learning", "training", "keras", "overfitting"],
  content: [
    "## 손실 함수(Loss)",
    "**손실 함수**는 예측과 정답의 차이를 수치화합니다. 이 값을 최소화하는 방향으로 가중치가 학습됩니다.",
    "",
    "| 문제 | 손실 함수 |",
    "|------|----------|",
    "| 다중 분류 | sparse_categorical_crossentropy |",
    "| 이진 분류 | binary_crossentropy |",
    "| 회귀 | mse (평균 제곱 오차) |",
    "",
    "---",
    "## 옵티마이저(Optimizer)",
    "**옵티마이저**는 손실을 줄이기 위해 가중치를 갱신하는 방식입니다.",
    "",
    "| 옵티마이저 | 특징 |",
    "|------------|------|",
    "| sgd | 기본 경사 하강법 |",
    "| adam | 적응적 학습률, 널리 사용 |",
    "| rmsprop | RNN·시계열에 자주 사용 |",
    "",
    "---",
    "## 손실 곡선",
    "훈련 과정에서 **loss**, **val_loss**를 기록하면 과적합 여부를 확인할 수 있습니다.",
    "",
    "- 훈련 loss는 줄고 검증 loss가 다시 올라가면 → **과적합**",
    "",
    "```python",
    "history = model.fit(train_scaled, train_target, epochs=20,",
    "                    validation_data=(val_scaled, val_target))",
    "",
    "import matplotlib.pyplot as plt",
    "plt.plot(history.history['loss'], label='train')",
    "plt.plot(history.history['val_loss'], label='val')",
    "plt.legend()",
    "plt.show()",
    "```",
    "",
    "---",
    "## Early Stopping",
    "검증 손실이 개선되지 않으면 **조기 종료**하여 과적합을 막습니다.",
    "",
    "```python",
    "model = keras.Sequential([...])",
    "model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics='accuracy')",
    "",
    "checkpoint_cb = keras.callbacks.ModelCheckpoint('best-model.h5', save_best_only=True)",
    "early_stopping_cb = keras.callbacks.EarlyStopping(patience=2, restore_best_weights=True)",
    "",
    "model.fit(train_scaled, train_target, epochs=20, validation_data=(val_scaled, val_target),",
    "          callbacks=[checkpoint_cb, early_stopping_cb])",
    "```",
    "",
    "---",
    "## Dropout",
    "훈련 시 **일부 뉴런을 무작위로 비활성화**해 과적합을 완화합니다.",
    "",
    "```python",
    "model.add(keras.layers.Dense(100, activation='relu'))",
    "model.add(keras.layers.Dropout(0.3))  # 30% 비활성화",
    "model.add(keras.layers.Dense(10, activation='softmax'))",
    "```",
    "",
    "---",
    "## 정리",
    "| 용어 | 요약 |",
    "|------|------|",
    "| 손실 함수 | 예측–정답 차이, 최소화 대상 |",
    "| adam | 널리 쓰이는 옵티마이저 |",
    "| Early Stopping | 검증 손실 기준 조기 종료 |",
    "| Dropout | 과적합 방지용 규제 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
