<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "nodejs-board-project",
  title: "Express + MongoDB + Handlebars 게시판 프로젝트",
  date: "2026-02-25",
  summary: "Express, MongoDB, Handlebars 템플릿 엔진을 활용한 실전 게시판 프로젝트입니다. 서비스 레이어 분리, 페이지네이션, 댓글 기능, 검색까지 구현합니다.",
  category: "Technology/Node.js",
  tags: ["nodejs","express","mongodb","handlebars","board","project","pagination"],
  content: [
    "## 한 줄 요약",
    "Express + MongoDB + Handlebars로 CRUD, 댓글, 검색, 페이지네이션을 갖춘 **게시판 웹 애플리케이션**을 만듭니다.",
    "",
    "---",
    "",
    "## 프로젝트 구조",
    "",
    "```",
    "board/",
    "├── app.js                          # 메인 서버",
    "├── configs/",
    "│   ├── mongodb-connection.js       # MongoDB 연결 설정",
    "│   └── handlebars-helpers.js       # 템플릿 헬퍼 함수",
    "├── services/",
    "│   └── post-service.js             # 게시글 비즈니스 로직",
    "├── utils/",
    "│   └── paginator.js                # 페이지네이션 유틸",
    "└── views/",
    "    ├── layouts/main.handlebars     # 레이아웃",
    "    ├── home.handlebars             # 목록 페이지",
    "    ├── detail.handlebars           # 상세 페이지",
    "    └── write.handlebars            # 작성 페이지",
    "```",
    "",
    "---",
    "",
    "## 1. 서버 설정 (app.js)",
    "",
    "```javascript",
    "const express = require('express');",
    "const handlebars = require('express-handlebars');",
    "const postService = require('./services/post-service');",
    "const mongodbConnection = require('./configs/mongodb-connection');",
    "",
    "const app = express();",
    "",
    "app.use(express.json());",
    "app.use(express.urlencoded({ extended: true }));",
    "",
    "// Handlebars 템플릿 엔진 설정",
    "app.engine(",
    "  'handlebars',",
    "  handlebars.create({",
    "    helpers: require('./configs/handlebars-helpers'),",
    "  }).engine",
    ");",
    "app.set('view engine', 'handlebars');",
    "app.set('views', __dirname + '/views');",
    "```",
    "",
    "---",
    "",
    "## 2. MongoDB 연결",
    "",
    "```javascript",
    "// configs/mongodb-connection.js",
    "const { MongoClient } = require('mongodb');",
    "",
    "const uri = 'mongodb+srv://user:pass@cluster0.example.mongodb.net/';",
    "",
    "module.exports = function (callback) {",
    "  return MongoClient.connect(uri, callback);",
    "};",
    "```",
    "",
    "---",
    "",
    "## 3. 서비스 레이어 (post-service.js)",
    "",
    "비즈니스 로직을 라우트에서 분리하여 관리합니다.",
    "",
    "```javascript",
    "const paginator = require('../utils/paginator');",
    "const { ObjectId } = require('mongodb');",
    "",
    "// 글 작성",
    "async function writePost(collection, post) {",
    "  post.hits = 0;",
    "  post.createdDt = new Date().toISOString();",
    "  return await collection.insertOne(post);",
    "}",
    "",
    "// 글 목록 (검색 + 페이지네이션)",
    "async function list(collection, page, search) {",
    "  const perPage = 10;",
    "  const query = { title: new RegExp(search, 'i') };",
    "  const cursor = collection",
    "    .find(query, { limit: perPage, skip: (page - 1) * perPage })",
    "    .sort({ createdDt: -1 });",
    "  const totalCount = await collection.count(query);",
    "  const posts = await cursor.toArray();",
    "  const paginatorObj = paginator({ totalCount, page, perPage });",
    "  return [posts, paginatorObj];",
    "}",
    "",
    "// 글 상세 (조회수 증가)",
    "const projectionOption = {",
    "  projection: {",
    "    password: 0,",
    "    'comments.password': 0,",
    "  },",
    "};",
    "",
    "async function getDetailPost(collection, id) {",
    "  return await collection.findOneAndUpdate(",
    "    { _id: ObjectId(id) },",
    "    { $inc: { hits: 1 } },",
    "    projectionOption",
    "  );",
    "}",
    "",
    "// 글 수정",
    "async function updatePost(collection, id, post) {",
    "  return await collection.updateOne(",
    "    { _id: ObjectId(id) },",
    "    { $set: { ...post } }",
    "  );",
    "}",
    "",
    "// 글 삭제 (비밀번호 확인)",
    "async function deletePost(collection, id, password) {",
    "  const result = await collection.deleteOne({",
    "    _id: ObjectId(id),",
    "    password: password,",
    "  });",
    "  return result.deletedCount === 1;",
    "}",
    "",
    "module.exports = {",
    "  list, writePost, getDetailPost,",
    "  getPostById, getPostByIdAndPassword,",
    "  updatePost, deletePost, getComments,",
    "};",
    "```",
    "",
    "### 주요 포인트",
    "",
    "| 기능 | 설명 |",
    "|------|------|",
    "| `projection` | 비밀번호 필드를 응답에서 제외 |",
    "| `$inc: { hits: 1 }` | 조회수 원자적 증가 |",
    "| `RegExp(search, 'i')` | 대소문자 무시 검색 |",
    "| `findOneAndUpdate` | 조회와 업데이트를 한 번에 |",
    "",
    "---",
    "",
    "## 4. 페이지네이션 (paginator.js)",
    "",
    "```javascript",
    "const lodash = require('lodash');",
    "const PAGE_LIST_SIZE = 10;",
    "",
    "module.exports = ({ totalCount, page, perPage = 10 }) => {",
    "  const totalPage = Math.ceil(totalCount / perPage);",
    "",
    "  let quotient = parseInt(page / PAGE_LIST_SIZE);",
    "  if (page % PAGE_LIST_SIZE === 0) {",
    "    quotient -= 1;",
    "  }",
    "  const startPage = quotient * PAGE_LIST_SIZE + 1;",
    "  const endPage = startPage + PAGE_LIST_SIZE - 1 < totalPage",
    "    ? startPage + PAGE_LIST_SIZE - 1",
    "    : totalPage;",
    "",
    "  return {",
    "    pageList: lodash.range(startPage, endPage + 1),",
    "    page,",
    "    prevPage: page - 1,",
    "    nextPage: page + 1,",
    "    startPage,",
    "    lastPage: totalPage,",
    "    hasPrev: page > 1,",
    "    hasNext: page < totalPage,",
    "    isFirstPage: page === 1,",
    "    isLastPage: page === totalPage,",
    "  };",
    "};",
    "```",
    "",
    "---",
    "",
    "## 5. 라우트 (app.js 핵심 라우트)",
    "",
    "```javascript",
    "// 목록 (검색 + 페이지네이션)",
    "app.get('/', async (req, res) => {",
    "  const page = parseInt(req.query.page) || 1;",
    "  const search = req.query.search || '';",
    "  try {",
    "    const [posts, paginator] = await postService.list(collection, page, search);",
    "    res.render('home', { title: '테스트 게시판', search, paginator, posts });",
    "  } catch (error) {",
    "    console.error(error);",
    "    res.render('home', { title: '테스트 게시판' });",
    "  }",
    "});",
    "",
    "// 글 작성",
    "app.post('/write', async (req, res) => {",
    "  const post = req.body;",
    "  const result = await postService.writePost(collection, post);",
    "  res.redirect(`/detail/${result.insertedId}`);",
    "});",
    "",
    "// 글 상세",
    "app.get('/detail/:id', async (req, res) => {",
    "  const result = await postService.getDetailPost(collection, req.params.id);",
    "  res.render('detail', {",
    "    title: '테스트 게시판',",
    "    post: result.value,",
    "  });",
    "});",
    "",
    "// 댓글 작성",
    "app.post('/write-comment', async (req, res) => {",
    "  const { id, name, password, comment } = req.body;",
    "  const post = await postService.getPostById(collection, id);",
    "",
    "  if (post.comments) {",
    "    post.comments.push({",
    "      idx: post.comments.length + 1,",
    "      name, password, comment,",
    "      createdDt: new Date().toISOString(),",
    "    });",
    "  } else {",
    "    post.comments = [{",
    "      idx: 1, name, password, comment,",
    "      createdDt: new Date().toISOString(),",
    "    }];",
    "  }",
    "",
    "  postService.updatePost(collection, id, post);",
    "  return res.redirect(`/detail/${id}`);",
    "});",
    "```",
    "",
    "---",
    "",
    "## 6. Handlebars 템플릿",
    "",
    "### 헬퍼 함수",
    "```javascript",
    "// configs/handlebars-helpers.js",
    "module.exports = {",
    "  lengthOfList: (list = []) => list.length,",
    "  eq: (val1, val2) => val1 === val2,",
    "  dateString: (isoString) => new Date(isoString).toLocaleDateString(),",
    "};",
    "```",
    "",
    "### 목록 페이지 (home.handlebars)",
    "```handlebars",
    "<table>",
    "  <thead>",
    "    <tr>",
    "      <th width=\"50%\">제목</th>",
    "      <th>작성자</th>",
    "      <th>조회수</th>",
    "      <th>등록일</th>",
    "    </tr>",
    "  </thead>",
    "  <tbody>",
    "    {{#each posts}}",
    "      <tr>",
    "        <td><a href=\"/detail/{{_id}}\">{{title}}</a></td>",
    "        <td align=\"center\">{{writer}}</td>",
    "        <td align=\"center\">{{hits}}</td>",
    "        <td align=\"center\">{{dateString createdDt}}</td>",
    "      </tr>",
    "    {{/each}}",
    "  </tbody>",
    "</table>",
    "",
    "<!-- 페이지네이션 -->",
    "{{#with paginator}}",
    "  <a href=\"/?page=1&search={{@root.search}}\">&lt;&lt;</a>",
    "  {{#if hasPrev}}",
    "    <a href=\"/?page={{prevPage}}&search={{@root.search}}\">&lt;</a>",
    "  {{/if}}",
    "  {{#each pageList}}",
    "    {{#if (eq . @root.paginator.page)}}",
    "      <a>{{.}}</a>",
    "    {{else}}",
    "      <a href=\"/?page={{.}}&search={{@root.search}}\">{{.}}</a>",
    "    {{/if}}",
    "  {{/each}}",
    "  {{#if hasNext}}",
    "    <a href=\"/?page={{nextPage}}&search={{@root.search}}\">&gt;</a>",
    "  {{/if}}",
    "  <a href=\"/?page={{lastPage}}&search={{@root.search}}\">&gt;&gt;</a>",
    "{{/with}}",
    "```",
    "",
    "---",
    "",
    "## 아키텍처 정리",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"클라이언트\"] <-->|\"HTTP\"| B[\"라우트 (app.js)\"]",
    "    B --> C[\"서비스 (post-service.js)\"]",
    "    C --> D[\"MongoDB (collection)\"]",
    "    B --> E[\"뷰 (Handlebars)\"]",
    "```",
    "",
    "| 레이어 | 역할 | 파일 |",
    "|--------|------|------|",
    "| 라우트 | HTTP 요청/응답 처리 | `app.js` |",
    "| 서비스 | 비즈니스 로직 | `post-service.js` |",
    "| 유틸 | 공통 기능 | `paginator.js` |",
    "| 설정 | DB 연결, 헬퍼 | `configs/` |",
    "| 뷰 | 화면 렌더링 | `views/` |",
    "",
    "---",
    "",
    "### 요약",
    "Express + MongoDB + Handlebars 조합으로 글 목록/상세/작성/수정/삭제, 댓글, 검색, 페이지네이션까지 갖춘 게시판을 구현했습니다. 서비스 레이어로 비즈니스 로직을 분리하고, `projection`으로 비밀번호를 숨기며, 헬퍼 함수로 템플릿을 깔끔하게 유지합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
