<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "nodejs-nestjs-auth",
  title: "NestJS 인증과 보안: Passport, Guard, 세션, OAuth",
  date: "2026-02-25",
  summary: "NestJS에서 Passport.js를 활용한 로컬 로그인, Google OAuth, 세션/쿠키 기반 인증, Guard를 이용한 라우트 보호, bcrypt 비밀번호 암호화를 정리합니다.",
  category: "Technology/Node.js",
  tags: ["nodejs","nestjs","passport","auth","guard","session","oauth","bcrypt"],
  content: [
    "## 한 줄 요약",
    "NestJS에서 **Passport.js** 전략 패턴으로 인증을 구현하고, **Guard**로 라우트를 보호하며, **bcrypt**로 비밀번호를 암호화합니다.",
    "",
    "---",
    "",
    "## 인증 구조 개요",
    "",
    "```",
    "[클라이언트] → [Guard] → [Strategy (Passport)] → [AuthService] → [UserService/DB]",
    "```",
    "",
    "| 구성 요소 | 역할 |",
    "|-----------|------|",
    "| Guard | 라우트 접근 제어 (인증 여부 확인) |",
    "| Strategy | 인증 전략 (Local, Google, JWT 등) |",
    "| AuthService | 인증 로직 (검증, 토큰 발급) |",
    "| UserService | 사용자 CRUD |",
    "",
    "### 설치",
    "```bash",
    "npm install @nestjs/passport passport passport-local",
    "npm install bcrypt express-session",
    "npm install -D @types/passport-local @types/bcrypt @types/express-session",
    "```",
    "",
    "---",
    "",
    "## 1. 회원가입 (bcrypt 암호화)",
    "",
    "```typescript",
    "// auth.service.ts",
    "import * as bcrypt from 'bcrypt';",
    "",
    "@Injectable()",
    "export class AuthService {",
    "  constructor(private userService: UserService) {}",
    "",
    "  async register(userDto: CreateUserDto) {",
    "    // 비밀번호 해시 (salt rounds: 10)",
    "    const encryptedPassword = bcrypt.hashSync(userDto.password, 10);",
    "",
    "    const user = await this.userService.createUser({",
    "      ...userDto,",
    "      password: encryptedPassword,",
    "    });",
    "",
    "    // 응답에서 비밀번호 제외",
    "    const { password, ...userInfo } = user;",
    "    return userInfo;",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 2. 로그인 검증 (Local Strategy)",
    "",
    "### AuthService 검증 메서드",
    "```typescript",
    "async validateUser(email: string, password: string) {",
    "  const user = await this.userService.getUser(email);",
    "",
    "  // 해시된 비밀번호와 비교",
    "  if (bcrypt.compareSync(password, user.password)) {",
    "    const { password, ...userInfo } = user;",
    "    return userInfo;",
    "  }",
    "  return null;",
    "}",
    "```",
    "",
    "### Local Strategy",
    "```typescript",
    "// local.strategy.ts",
    "import { PassportStrategy } from '@nestjs/passport';",
    "import { Strategy } from 'passport-local';",
    "",
    "@Injectable()",
    "export class LocalStrategy extends PassportStrategy(Strategy) {",
    "  constructor(private authService: AuthService) {",
    "    super({ usernameField: 'email' }); // 기본은 username, email로 변경",
    "  }",
    "",
    "  async validate(email: string, password: string): Promise<any> {",
    "    const user = await this.authService.validateUser(email, password);",
    "    if (!user) return null;",
    "    return user; // req.user에 저장됨",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 3. Guard (라우트 보호)",
    "",
    "### 로그인 Guard",
    "```typescript",
    "// auth.guard.ts",
    "import { AuthGuard } from '@nestjs/passport';",
    "",
    "@Injectable()",
    "export class LocalAuthGuard extends AuthGuard('local') {",
    "  async canActivate(context: any): Promise<boolean> {",
    "    const result = (await super.canActivate(context)) as boolean;",
    "    const request = context.switchToHttp().getRequest();",
    "    await super.logIn(request); // 세션에 저장",
    "    return result;",
    "  }",
    "}",
    "```",
    "",
    "### 인증 확인 Guard",
    "```typescript",
    "@Injectable()",
    "export class AuthenticatedGuard implements CanActivate {",
    "  canActivate(context: ExecutionContext): boolean {",
    "    const request = context.switchToHttp().getRequest();",
    "    return request.isAuthenticated(); // 세션 기반 인증 확인",
    "  }",
    "}",
    "```",
    "",
    "### Controller에서 Guard 사용",
    "```typescript",
    "@Controller('auth')",
    "export class AuthController {",
    "  @Post('register')",
    "  async register(@Body() userDto: CreateUserDto) {",
    "    return this.authService.register(userDto);",
    "  }",
    "",
    "  @UseGuards(LocalAuthGuard)  // 로그인 시 Local Strategy 실행",
    "  @Post('login')",
    "  login(@Request() req) {",
    "    return req.user;",
    "  }",
    "",
    "  @UseGuards(AuthenticatedGuard)  // 로그인된 사용자만 접근",
    "  @Get('profile')",
    "  getProfile(@Request() req) {",
    "    return req.user;",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 4. 세션 설정",
    "",
    "### main.ts",
    "```typescript",
    "import * as session from 'express-session';",
    "import * as passport from 'passport';",
    "",
    "async function bootstrap() {",
    "  const app = await NestFactory.create(AppModule);",
    "",
    "  app.use(",
    "    session({",
    "      secret: 'secret-key',",
    "      resave: false,",
    "      saveUninitialized: false,",
    "      cookie: { maxAge: 1000 * 60 * 30 }, // 30분",
    "    }),",
    "  );",
    "",
    "  app.use(passport.initialize());",
    "  app.use(passport.session());",
    "",
    "  await app.listen(3000);",
    "}",
    "```",
    "",
    "### Session Serializer",
    "```typescript",
    "// session.serializer.ts",
    "import { PassportSerializer } from '@nestjs/passport';",
    "",
    "@Injectable()",
    "export class SessionSerializer extends PassportSerializer {",
    "  constructor(private userService: UserService) {",
    "    super();",
    "  }",
    "",
    "  // 로그인 시: 세션에 저장할 데이터 결정",
    "  serializeUser(user: any, done: (err: Error, user: any) => void): any {",
    "    done(null, user.email); // email만 저장 (최소 정보)",
    "  }",
    "",
    "  // 요청마다: 세션에서 사용자 복원",
    "  async deserializeUser(payload: any, done: Function): Promise<any> {",
    "    const user = await this.userService.getUser(payload);",
    "    const { password, ...userInfo } = user;",
    "    done(null, userInfo);",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 5. Google OAuth 연동",
    "",
    "### 설치",
    "```bash",
    "npm install passport-google-oauth20",
    "npm install -D @types/passport-google-oauth20",
    "```",
    "",
    "### Google Strategy",
    "```typescript",
    "// google.strategy.ts",
    "import { Strategy, Profile } from 'passport-google-oauth20';",
    "",
    "@Injectable()",
    "export class GoogleStrategy extends PassportStrategy(Strategy) {",
    "  constructor(private userService: UserService) {",
    "    super({",
    "      clientID: process.env.GOOGLE_CLIENT_ID,",
    "      clientSecret: process.env.GOOGLE_CLIENT_SECRET,",
    "      callbackURL: 'http://localhost:3000/auth/google',",
    "      scope: ['email', 'profile'],",
    "    });",
    "  }",
    "",
    "  async validate(",
    "    accessToken: string,",
    "    refreshToken: string,",
    "    profile: Profile,",
    "  ) {",
    "    const { email, name, providerId } = extractProfile(profile);",
    "",
    "    // 기존 사용자면 조회, 없으면 생성",
    "    const user = await this.userService.findByEmailOrSave(",
    "      email,",
    "      name.familyName + name.givenName,",
    "      providerId,",
    "    );",
    "    return user;",
    "  }",
    "}",
    "```",
    "",
    "### Controller에 Google 로그인 추가",
    "```typescript",
    "@Get('google-login')",
    "@UseGuards(AuthGuard('google'))",
    "googleLogin() {",
    "  // Google 로그인 페이지로 리다이렉트",
    "}",
    "",
    "@Get('google')",
    "@UseGuards(AuthGuard('google'))",
    "googleCallback(@Request() req) {",
    "  return req.user; // 인증 성공 시 사용자 정보",
    "}",
    "```",
    "",
    "---",
    "",
    "## 인증 흐름 정리",
    "",
    "### 로컬 로그인 흐름",
    "```",
    "1. POST /auth/login (email, password)",
    "2. LocalAuthGuard → LocalStrategy.validate()",
    "3. AuthService.validateUser() → bcrypt.compareSync()",
    "4. 성공 → SessionSerializer.serializeUser() → 세션 저장",
    "5. 이후 요청마다 deserializeUser() → req.user 복원",
    "```",
    "",
    "### Google OAuth 흐름",
    "```",
    "1. GET /auth/google-login → Google 로그인 페이지",
    "2. 사용자 인증 → Google이 콜백 URL 호출",
    "3. GET /auth/google → GoogleStrategy.validate()",
    "4. findByEmailOrSave() → DB에 사용자 생성/조회",
    "5. 세션 저장",
    "```",
    "",
    "---",
    "",
    "## 보안 체크리스트",
    "",
    "| 항목 | 방법 |",
    "|------|------|",
    "| 비밀번호 저장 | `bcrypt.hashSync(pw, 10)` |",
    "| 비밀번호 비교 | `bcrypt.compareSync(pw, hash)` |",
    "| 세션 시크릿 | 환경 변수로 관리 |",
    "| 비밀번호 노출 방지 | 응답에서 `password` 필드 제거 |",
    "| 세션 만료 | `cookie.maxAge` 설정 |",
    "| DTO 검증 | `class-validator` 사용 |",
    "",
    "---",
    "",
    "### 요약",
    "NestJS에서는 Passport.js의 **Strategy 패턴**으로 다양한 인증 방식(Local, Google OAuth)을 구현하고, **Guard**로 라우트를 보호합니다. 세션 기반 인증에서는 **Serializer**로 세션 데이터를 관리하며, **bcrypt**로 비밀번호를 안전하게 저장합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
