<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "nodejs-express-mongodb",
  title: "Express.js와 MongoDB로 REST API 만들기",
  date: "2026-02-25",
  summary: "Express.js 기본 서버 구축, 미들웨어, RESTful API 설계, MongoDB 네이티브 드라이버와 Mongoose ODM으로 CRUD API를 구현하는 방법을 정리합니다.",
  category: "Technology/Node.js",
  tags: ["nodejs","express","mongodb","mongoose","rest-api","crud"],
  content: [
    "## 한 줄 요약",
    "**Express.js**는 Node.js의 대표적인 웹 프레임워크이며, **MongoDB**와 연동하여 빠르게 RESTful API를 구축할 수 있습니다.",
    "",
    "---",
    "",
    "## Express.js 기본 서버",
    "",
    "### 설치",
    "```bash",
    "npm init -y",
    "npm install express",
    "```",
    "",
    "### 기본 서버 구축",
    "```javascript",
    "const express = require('express');",
    "const app = express();",
    "const port = 3000;",
    "",
    "// 미들웨어 설정",
    "app.use(express.json());",
    "app.use(express.urlencoded({ extended: true }));",
    "",
    "// 메모리 기반 데이터 저장소",
    "let posts = [];",
    "",
    "// GET - 전체 조회",
    "app.get('/', (req, res) => {",
    "  res.json(posts);",
    "});",
    "",
    "// POST - 생성",
    "app.post('/posts', (req, res) => {",
    "  const { title, name, text } = req.body;",
    "  posts.push({",
    "    id: posts.length + 1,",
    "    title,",
    "    name,",
    "    text,",
    "    createdDt: Date(),",
    "  });",
    "  res.json({ title, name, text });",
    "});",
    "",
    "// DELETE - 삭제",
    "app.delete('/posts/:id', (req, res) => {",
    "  const id = req.params.id;",
    "  const filteredPosts = posts.filter((post) => post.id !== +id);",
    "  const isLengthChanged = posts.length !== filteredPosts.length;",
    "  posts = filteredPosts;",
    "",
    "  if (isLengthChanged) {",
    "    res.json('OK');",
    "    return;",
    "  }",
    "  res.json('NOT CHANGED');",
    "});",
    "",
    "app.listen(port, () => {",
    "  console.log(`Server running on http://localhost:${port}`);",
    "});",
    "```",
    "",
    "### 핵심 개념",
    "",
    "| 개념 | 설명 |",
    "|------|------|",
    "| `app.use()` | 미들웨어 등록 |",
    "| `express.json()` | JSON 요청 본문 파싱 |",
    "| `express.urlencoded()` | URL-encoded 폼 데이터 파싱 |",
    "| `req.body` | 요청 본문 데이터 |",
    "| `req.params` | URL 파라미터 (`:id` 등) |",
    "| `req.query` | 쿼리스트링 (`?page=1`) |",
    "| `res.json()` | JSON 응답 반환 |",
    "",
    "---",
    "",
    "## MongoDB 연동",
    "",
    "### 설치",
    "```bash",
    "npm install mongodb",
    "```",
    "",
    "### 1. 네이티브 드라이버: 연결",
    "```javascript",
    "const { MongoClient, ServerApiVersion } = require('mongodb');",
    "const uri = 'mongodb+srv://user:pass@cluster0.example.mongodb.net/?retryWrites=true&w=majority';",
    "",
    "const client = new MongoClient(uri, {",
    "  serverApi: {",
    "    version: ServerApiVersion.v1,",
    "    strict: true,",
    "    deprecationErrors: true,",
    "  },",
    "});",
    "",
    "async function run() {",
    "  try {",
    "    await client.connect();",
    "    const adminDB = await client.db('test').admin();",
    "    const listDatabases = await adminDB.listDatabases();",
    "    console.log(listDatabases);",
    "    return 'OK';",
    "  } finally {",
    "    await client.close();",
    "  }",
    "}",
    "",
    "run().catch(console.dir);",
    "```",
    "",
    "### 2. 네이티브 드라이버: CRUD",
    "```javascript",
    "const MongoClient = require('mongodb').MongoClient;",
    "const uri = 'mongodb+srv://user:pass@cluster0.example.mongodb.net/test';",
    "const client = new MongoClient(uri, { useNewUrlParser: true });",
    "",
    "async function main() {",
    "  try {",
    "    await client.connect();",
    "    console.log('MongoDB 접속 성공');",
    "",
    "    const collection = client.db('test').collection('person');",
    "",
    "    // CREATE",
    "    await collection.insertOne({ name: 'Andy', age: 30 });",
    "    console.log('문서 추가 완료');",
    "",
    "    // READ",
    "    const documents = await collection.find({ name: 'Andy' }).toArray();",
    "    console.log('찾은 문서', documents);",
    "",
    "    // UPDATE",
    "    await collection.updateOne(",
    "      { name: 'Andy' },",
    "      { $set: { age: 31 } }",
    "    );",
    "    console.log('문서 업데이트');",
    "",
    "    // DELETE",
    "    await collection.deleteOne({ name: 'Andy' });",
    "    console.log('문서 삭제');",
    "",
    "    await client.close();",
    "  } catch (err) {",
    "    console.error(err);",
    "  }",
    "}",
    "",
    "main();",
    "```",
    "",
    "---",
    "",
    "## Mongoose ODM",
    "",
    "Mongoose는 MongoDB를 위한 **ODM(Object Data Modeling)** 라이브러리로, 스키마 정의와 검증을 제공합니다.",
    "",
    "### 설치",
    "```bash",
    "npm install mongoose express",
    "```",
    "",
    "### 스키마 & 모델 정의",
    "```javascript",
    "// person-model.js",
    "const mongoose = require('mongoose');",
    "const Schema = mongoose.Schema;",
    "",
    "const personSchema = new Schema({",
    "  name: String,",
    "  age: Number,",
    "  email: { type: String, required: true },",
    "});",
    "",
    "module.exports = mongoose.model('Person', personSchema);",
    "```",
    "",
    "### Express + Mongoose CRUD API",
    "```javascript",
    "const express = require('express');",
    "const bodyParser = require('body-parser');",
    "const mongoose = require('mongoose');",
    "const Person = require('./person-model');",
    "",
    "mongoose.set('strictQuery', false);",
    "",
    "const app = express();",
    "app.use(bodyParser.json());",
    "",
    "app.listen(3000, async () => {",
    "  console.log('Server started');",
    "  const mongodbUri = 'mongodb+srv://user:pass@cluster0.example.mongodb.net/test';",
    "  mongoose",
    "    .connect(mongodbUri, { useNewUrlParser: true })",
    "    .then(console.log('Connected to MongoDB'));",
    "});",
    "",
    "// 전체 조회",
    "app.get('/person', async (req, res) => {",
    "  const person = await Person.find({});",
    "  res.send(person);",
    "});",
    "",
    "// 이메일로 조회",
    "app.get('/person/:email', async (req, res) => {",
    "  const person = await Person.findOne({ email: req.params.email });",
    "  res.send(person);",
    "});",
    "",
    "// 생성",
    "app.post('/person', async (req, res) => {",
    "  const person = new Person(req.body);",
    "  await person.save();",
    "  res.send(person);",
    "});",
    "",
    "// 수정",
    "app.put('/person/:email', async (req, res) => {",
    "  const person = await Person.findOneAndUpdate(",
    "    { email: req.params.email },",
    "    { $set: req.body },",
    "    { new: true }",
    "  );",
    "  res.send(person);",
    "});",
    "",
    "// 삭제",
    "app.delete('/person/:email', async (req, res) => {",
    "  await Person.deleteMany({ email: req.params.email });",
    "  res.send({ success: true });",
    "});",
    "```",
    "",
    "---",
    "",
    "## 네이티브 드라이버 vs Mongoose",
    "",
    "| 비교 | 네이티브 드라이버 | Mongoose |",
    "|------|------------------|----------|",
    "| 스키마 정의 | ❌ 없음 | ✅ 스키마/모델 필수 |",
    "| 데이터 검증 | 직접 구현 | ✅ 내장 검증 |",
    "| 학습 비용 | 낮음 | 보통 |",
    "| 유연성 | 높음 (MongoDB 직접 제어) | 보통 (추상화) |",
    "| 미들웨어 (훅) | ❌ | ✅ (`pre`, `post` 훅) |",
    "| 관계 처리 | 직접 구현 | `populate()` 지원 |",
    "| 추천 상황 | 간단한 스크립트, 성능 최적화 | 대부분의 웹 애플리케이션 |",
    "",
    "---",
    "",
    "## REST API 설계 규칙",
    "",
    "| HTTP 메서드 | 경로 | 동작 | 설명 |",
    "|-------------|------|------|------|",
    "| `GET` | `/users` | 목록 조회 | 전체 사용자 |",
    "| `GET` | `/users/:id` | 상세 조회 | 특정 사용자 |",
    "| `POST` | `/users` | 생성 | 새 사용자 |",
    "| `PUT` | `/users/:id` | 전체 수정 | 사용자 정보 교체 |",
    "| `PATCH` | `/users/:id` | 부분 수정 | 사용자 정보 일부 변경 |",
    "| `DELETE` | `/users/:id` | 삭제 | 사용자 삭제 |",
    "",
    "---",
    "",
    "### 요약",
    "Express.js는 `app.get/post/put/delete`로 라우팅하고, 미들웨어로 요청을 처리합니다. MongoDB는 네이티브 드라이버로 직접 다루거나, Mongoose ODM으로 스키마 기반의 CRUD API를 구현할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
