<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "nodejs-todo-app",
  title: "Node.js만으로 Todo App 만들기",
  date: "2026-02-25",
  summary: "Express 없이 Node.js 내장 http 모듈만으로 다양한 라우팅 패턴을 활용한 Todo App REST API를 구현합니다.",
  category: "Technology/Node.js",
  tags: ["nodejs","http","rest-api","routing","todo","crud","server"],
  content: [
    "## 한 줄 요약",
    "Node.js 내장 `http` 모듈만으로 **라우터, 미들웨어, CRUD, 검색, 필터링, 정적 파일 서빙**까지 갖춘 Todo App을 만들어봅니다.",
    "",
    "---",
    "",
    "## 기본 HTTP 서버 구조",
    "",
    "### 가장 단순한 서버",
    "```javascript",
    "const http = require('http');",
    "",
    "const server = http.createServer((req, res) => {",
    "  res.writeHead(200, { 'Content-Type': 'text/html' });",
    "  res.end('<h1>Hello World</h1>');",
    "});",
    "",
    "server.listen(3000, () => {",
    "  console.log('Server is running on port 3000');",
    "});",
    "```",
    "",
    "### 기본 라우팅",
    "```javascript",
    "const http = require('http');",
    "",
    "const server = http.createServer((req, res) => {",
    "  const { method, url } = req;",
    "",
    "  if (method === 'GET' && url === '/') {",
    "    res.writeHead(200, { 'Content-Type': 'text/html' });",
    "    res.end('<h1>Hello World</h1>');",
    "  } else if (method === 'GET' && url === '/hello') {",
    "    res.writeHead(200, { 'Content-Type': 'text/html' });",
    "    res.end('<h1>Hello World from GET /hello</h1>');",
    "  } else {",
    "    res.writeHead(404);",
    "    res.end('Not Found');",
    "  }",
    "});",
    "",
    "server.listen(3000, () => {",
    "  console.log('Server is running on port 3000');",
    "});",
    "```",
    "",
    "> `if/else` 분기가 많아지면 관리가 어려워집니다. 이를 개선해보겠습니다.",
    "",
    "---",
    "",
    "## 라우터 직접 만들기",
    "",
    "Express의 `app.get()`, `app.post()` 같은 라우터를 직접 구현합니다.",
    "",
    "```javascript",
    "class Router {",
    "  constructor() {",
    "    this.routes = [];",
    "  }",
    "",
    "  // 라우트 등록",
    "  addRoute(method, path, handler) {",
    "    this.routes.push({",
    "      method: method.toUpperCase(),",
    "      pattern: this._pathToRegex(path),",
    "      handler,",
    "    });",
    "  }",
    "",
    "  get(path, handler) { this.addRoute('GET', path, handler); }",
    "  post(path, handler) { this.addRoute('POST', path, handler); }",
    "  put(path, handler) { this.addRoute('PUT', path, handler); }",
    "  patch(path, handler) { this.addRoute('PATCH', path, handler); }",
    "  delete(path, handler) { this.addRoute('DELETE', path, handler); }",
    "",
    "  // URL 경로를 정규식으로 변환 (:id → 캡처 그룹)",
    "  _pathToRegex(path) {",
    "    const paramNames = [];",
    "    const regexStr = path.replace(/:([a-zA-Z]+)/g, (_, name) => {",
    "      paramNames.push(name);",
    "      return '([^/]+)';",
    "    });",
    "    return { regex: new RegExp(`^${regexStr}$`), paramNames };",
    "  }",
    "",
    "  // 요청에 맞는 라우트 찾기",
    "  resolve(method, url) {",
    "    const [pathname, queryString] = url.split('?');",
    "    for (const route of this.routes) {",
    "      if (route.method !== method) continue;",
    "      const match = pathname.match(route.pattern.regex);",
    "      if (match) {",
    "        const params = {};",
    "        route.pattern.paramNames.forEach((name, i) => {",
    "          params[name] = match[i + 1];",
    "        });",
    "        const query = Object.fromEntries(new URLSearchParams(queryString || ''));",
    "        return { handler: route.handler, params, query };",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "}",
    "```",
    "",
    "### 핵심 기능",
    "",
    "| 기능 | 설명 |",
    "|------|------|",
    "| `addRoute()` | 메서드 + 경로 + 핸들러 등록 |",
    "| `_pathToRegex()` | `/todos/:id` → 정규식 변환, 파라미터 이름 추출 |",
    "| `resolve()` | 요청 URL과 메서드에 매칭되는 핸들러 찾기 |",
    "| `query` 파싱 | `?done=true&keyword=공부` → `{ done: 'true', keyword: '공부' }` |",
    "",
    "---",
    "",
    "## 유틸리티 함수",
    "",
    "```javascript",
    "// 요청 본문 파싱",
    "function parseBody(req) {",
    "  return new Promise((resolve, reject) => {",
    "    let body = '';",
    "    req.on('data', (chunk) => { body += chunk; });",
    "    req.on('end', () => {",
    "      try {",
    "        resolve(body ? JSON.parse(body) : {});",
    "      } catch (e) {",
    "        reject(e);",
    "      }",
    "    });",
    "  });",
    "}",
    "",
    "// JSON 응답",
    "function sendJSON(res, statusCode, data) {",
    "  res.writeHead(statusCode, {",
    "    'Content-Type': 'application/json; charset=utf-8',",
    "    'Access-Control-Allow-Origin': '*',",
    "    'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS',",
    "    'Access-Control-Allow-Headers': 'Content-Type',",
    "  });",
    "  res.end(JSON.stringify(data));",
    "}",
    "",
    "// 에러 응답",
    "function sendError(res, statusCode, message) {",
    "  sendJSON(res, statusCode, { error: message });",
    "}",
    "",
    "// 현재 시간 문자열",
    "function now() {",
    "  return new Date().toISOString();",
    "}",
    "```",
    "",
    "---",
    "",
    "## Todo App 전체 코드",
    "",
    "```javascript",
    "const http = require('http');",
    "",
    "// ──────────── 데이터 저장소 ────────────",
    "let todos = [",
    "  { id: 1, title: 'Node.js 공부하기', done: false, priority: 'high', createdAt: now() },",
    "  { id: 2, title: '블로그 글 작성', done: true, priority: 'medium', createdAt: now() },",
    "  { id: 3, title: '운동하기', done: false, priority: 'low', createdAt: now() },",
    "];",
    "let nextId = 4;",
    "",
    "// ──────────── 라우터 설정 ────────────",
    "const router = new Router();",
    "",
    "// GET / - 서버 정보",
    "router.get('/', (req, res) => {",
    "  sendJSON(res, 200, {",
    "    name: 'Todo API',",
    "    version: '1.0.0',",
    "    endpoints: [",
    "      'GET    /todos',",
    "      'GET    /todos/:id',",
    "      'POST   /todos',",
    "      'PUT    /todos/:id',",
    "      'PATCH  /todos/:id',",
    "      'DELETE /todos/:id',",
    "      'DELETE /todos',",
    "      'GET    /todos/search?keyword=',",
    "      'GET    /todos/filter?done=&priority=',",
    "      'GET    /todos/stats',",
    "    ],",
    "  });",
    "});",
    "",
    "// GET /todos - 전체 목록 (정렬 지원)",
    "router.get('/todos', (req, res, params, query) => {",
    "  let result = [...todos];",
    "",
    "  // 정렬: ?sort=createdAt&order=desc",
    "  if (query.sort) {",
    "    const order = query.order === 'desc' ? -1 : 1;",
    "    result.sort((a, b) => {",
    "      if (a[query.sort] < b[query.sort]) return -1 * order;",
    "      if (a[query.sort] > b[query.sort]) return 1 * order;",
    "      return 0;",
    "    });",
    "  }",
    "",
    "  // 페이징: ?page=1&limit=10",
    "  if (query.page && query.limit) {",
    "    const page = parseInt(query.page);",
    "    const limit = parseInt(query.limit);",
    "    const start = (page - 1) * limit;",
    "    const paged = result.slice(start, start + limit);",
    "    return sendJSON(res, 200, {",
    "      data: paged,",
    "      total: result.length,",
    "      page, limit,",
    "      totalPages: Math.ceil(result.length / limit),",
    "    });",
    "  }",
    "",
    "  sendJSON(res, 200, result);",
    "});",
    "",
    "// GET /todos/stats - 통계",
    "router.get('/todos/stats', (req, res) => {",
    "  const total = todos.length;",
    "  const done = todos.filter((t) => t.done).length;",
    "  const undone = total - done;",
    "  const byPriority = {",
    "    high: todos.filter((t) => t.priority === 'high').length,",
    "    medium: todos.filter((t) => t.priority === 'medium').length,",
    "    low: todos.filter((t) => t.priority === 'low').length,",
    "  };",
    "  sendJSON(res, 200, { total, done, undone, byPriority });",
    "});",
    "",
    "// GET /todos/search?keyword= - 검색",
    "router.get('/todos/search', (req, res, params, query) => {",
    "  if (!query.keyword) {",
    "    return sendError(res, 400, 'keyword 파라미터가 필요합니다');",
    "  }",
    "  const keyword = query.keyword.toLowerCase();",
    "  const result = todos.filter((t) =>",
    "    t.title.toLowerCase().includes(keyword)",
    "  );",
    "  sendJSON(res, 200, { keyword: query.keyword, count: result.length, data: result });",
    "});",
    "",
    "// GET /todos/filter?done=true&priority=high - 필터링",
    "router.get('/todos/filter', (req, res, params, query) => {",
    "  let result = [...todos];",
    "  if (query.done !== undefined) {",
    "    result = result.filter((t) => t.done === (query.done === 'true'));",
    "  }",
    "  if (query.priority) {",
    "    result = result.filter((t) => t.priority === query.priority);",
    "  }",
    "  sendJSON(res, 200, result);",
    "});",
    "",
    "// GET /todos/:id - 단건 조회",
    "router.get('/todos/:id', (req, res, params) => {",
    "  const todo = todos.find((t) => t.id === parseInt(params.id));",
    "  if (!todo) return sendError(res, 404, '할 일을 찾을 수 없습니다');",
    "  sendJSON(res, 200, todo);",
    "});",
    "",
    "// POST /todos - 생성",
    "router.post('/todos', async (req, res) => {",
    "  const body = await parseBody(req);",
    "  if (!body.title || body.title.trim() === '') {",
    "    return sendError(res, 400, 'title은 필수입니다');",
    "  }",
    "  const newTodo = {",
    "    id: nextId++,",
    "    title: body.title.trim(),",
    "    done: false,",
    "    priority: body.priority || 'medium',",
    "    createdAt: now(),",
    "  };",
    "  todos.push(newTodo);",
    "  sendJSON(res, 201, newTodo);",
    "});",
    "",
    "// PUT /todos/:id - 전체 수정",
    "router.put('/todos/:id', async (req, res, params) => {",
    "  const todo = todos.find((t) => t.id === parseInt(params.id));",
    "  if (!todo) return sendError(res, 404, '할 일을 찾을 수 없습니다');",
    "  const body = await parseBody(req);",
    "  if (!body.title) return sendError(res, 400, 'title은 필수입니다');",
    "  todo.title = body.title;",
    "  todo.done = body.done ?? todo.done;",
    "  todo.priority = body.priority ?? todo.priority;",
    "  sendJSON(res, 200, todo);",
    "});",
    "",
    "// PATCH /todos/:id - 부분 수정",
    "router.patch('/todos/:id', async (req, res, params) => {",
    "  const todo = todos.find((t) => t.id === parseInt(params.id));",
    "  if (!todo) return sendError(res, 404, '할 일을 찾을 수 없습니다');",
    "  const body = await parseBody(req);",
    "  if (body.title !== undefined) todo.title = body.title;",
    "  if (body.done !== undefined) todo.done = body.done;",
    "  if (body.priority !== undefined) todo.priority = body.priority;",
    "  sendJSON(res, 200, todo);",
    "});",
    "",
    "// DELETE /todos/:id - 단건 삭제",
    "router.delete('/todos/:id', (req, res, params) => {",
    "  const index = todos.findIndex((t) => t.id === parseInt(params.id));",
    "  if (index === -1) return sendError(res, 404, '할 일을 찾을 수 없습니다');",
    "  const deleted = todos.splice(index, 1);",
    "  sendJSON(res, 200, { message: '삭제 완료', data: deleted[0] });",
    "});",
    "",
    "// DELETE /todos - 완료된 항목 일괄 삭제",
    "router.delete('/todos', (req, res) => {",
    "  const before = todos.length;",
    "  todos = todos.filter((t) => !t.done);",
    "  const deleted = before - todos.length;",
    "  sendJSON(res, 200, { message: `${deleted}건 삭제 완료`, remaining: todos.length });",
    "});",
    "",
    "// ──────────── 서버 시작 ────────────",
    "const server = http.createServer(async (req, res) => {",
    "  // CORS preflight",
    "  if (req.method === 'OPTIONS') {",
    "    res.writeHead(204, {",
    "      'Access-Control-Allow-Origin': '*',",
    "      'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS',",
    "      'Access-Control-Allow-Headers': 'Content-Type',",
    "    });",
    "    return res.end();",
    "  }",
    "",
    "  const result = router.resolve(req.method, req.url);",
    "  if (result) {",
    "    try {",
    "      await result.handler(req, res, result.params, result.query);",
    "    } catch (err) {",
    "      sendError(res, 500, err.message);",
    "    }",
    "  } else {",
    "    sendError(res, 404, `${req.method} ${req.url} 라우트를 찾을 수 없습니다`);",
    "  }",
    "});",
    "",
    "server.listen(3000, () => {",
    "  console.log('Todo API 서버: http://localhost:3000');",
    "});",
    "```",
    "",
    "---",
    "",
    "## API 테스트",
    "",
    "### 서버 정보",
    "```bash",
    "curl http://localhost:3000/",
    "```",
    "",
    "### CRUD",
    "```bash",
    "# 전체 조회",
    "curl http://localhost:3000/todos",
    "",
    "# 단건 조회",
    "curl http://localhost:3000/todos/1",
    "",
    "# 생성",
    "curl -X POST http://localhost:3000/todos \\",
    "  -H \"Content-Type: application/json\" \\",
    "  -d '{\"title\": \"TypeScript 배우기\", \"priority\": \"high\"}'",
    "",
    "# 전체 수정 (PUT)",
    "curl -X PUT http://localhost:3000/todos/1 \\",
    "  -H \"Content-Type: application/json\" \\",
    "  -d '{\"title\": \"Node.js 마스터\", \"done\": true, \"priority\": \"high\"}'",
    "",
    "# 부분 수정 (PATCH) - done만 변경",
    "curl -X PATCH http://localhost:3000/todos/3 \\",
    "  -H \"Content-Type: application/json\" \\",
    "  -d '{\"done\": true}'",
    "",
    "# 단건 삭제",
    "curl -X DELETE http://localhost:3000/todos/2",
    "",
    "# 완료된 항목 일괄 삭제",
    "curl -X DELETE http://localhost:3000/todos",
    "```",
    "",
    "### 검색 / 필터 / 정렬 / 페이징",
    "```bash",
    "# 키워드 검색",
    "curl \"http://localhost:3000/todos/search?keyword=공부\"",
    "",
    "# 필터링 (완료된 것만)",
    "curl \"http://localhost:3000/todos/filter?done=true\"",
    "",
    "# 필터링 (우선순위 high)",
    "curl \"http://localhost:3000/todos/filter?priority=high\"",
    "",
    "# 필터링 (미완료 + high)",
    "curl \"http://localhost:3000/todos/filter?done=false&priority=high\"",
    "",
    "# 정렬 (생성일 내림차순)",
    "curl \"http://localhost:3000/todos?sort=createdAt&order=desc\"",
    "",
    "# 페이징 (1페이지, 2개씩)",
    "curl \"http://localhost:3000/todos?page=1&limit=2\"",
    "",
    "# 통계",
    "curl http://localhost:3000/todos/stats",
    "```",
    "",
    "---",
    "",
    "## API 엔드포인트 정리",
    "",
    "| 메서드 | 경로 | 설명 |",
    "|--------|------|------|",
    "| `GET` | `/` | 서버 정보, API 목록 |",
    "| `GET` | `/todos` | 전체 목록 (정렬, 페이징 지원) |",
    "| `GET` | `/todos/stats` | 통계 (완료/미완료/우선순위별) |",
    "| `GET` | `/todos/search?keyword=` | 키워드 검색 |",
    "| `GET` | `/todos/filter?done=&priority=` | 조건 필터링 |",
    "| `GET` | `/todos/:id` | 단건 조회 |",
    "| `POST` | `/todos` | 생성 |",
    "| `PUT` | `/todos/:id` | 전체 수정 |",
    "| `PATCH` | `/todos/:id` | 부분 수정 |",
    "| `DELETE` | `/todos/:id` | 단건 삭제 |",
    "| `DELETE` | `/todos` | 완료 항목 일괄 삭제 |",
    "",
    "---",
    "",
    "## 라우팅 패턴 정리",
    "",
    "### 1. 정적 경로",
    "```",
    "GET /todos       → 정확히 일치하는 경로",
    "GET /todos/stats → /todos/:id보다 먼저 등록해야 함",
    "```",
    "",
    "### 2. 동적 파라미터 (`:param`)",
    "```",
    "GET    /todos/:id → params.id로 접근",
    "DELETE /todos/:id → 같은 패턴, 다른 메서드",
    "```",
    "",
    "### 3. 쿼리 스트링 (`?key=value`)",
    "```",
    "GET /todos?sort=createdAt&order=desc  → query.sort, query.order",
    "GET /todos?page=1&limit=10           → query.page, query.limit",
    "GET /todos/search?keyword=공부        → query.keyword",
    "GET /todos/filter?done=true           → query.done",
    "```",
    "",
    "### 4. 같은 경로, 다른 메서드",
    "```",
    "GET    /todos → 목록 조회",
    "POST   /todos → 새로 생성",
    "DELETE /todos → 일괄 삭제",
    "```",
    "",
    "### 5. PUT vs PATCH",
    "```",
    "PUT   /todos/:id → 전체 필드 교체 (title 필수)",
    "PATCH /todos/:id → 일부 필드만 수정 (보낸 것만 변경)",
    "```",
    "",
    "---",
    "",
    "## 라우트 등록 순서의 중요성",
    "",
    "```javascript",
    "// /todos/stats가 /todos/:id보다 먼저 등록되어야 합니다!",
    "router.get('/todos/stats', statsHandler);   // 먼저!",
    "router.get('/todos/search', searchHandler); // 먼저!",
    "router.get('/todos/filter', filterHandler); // 먼저!",
    "router.get('/todos/:id', getByIdHandler);   // 나중에!",
    "```",
    "",
    "> `/todos/stats`를 `/todos/:id` 뒤에 등록하면, `stats`가 `:id` 파라미터로 매칭되어 의도대로 동작하지 않습니다.",
    "",
    "---",
    "",
    "### Node.js 내장 HTTP vs Express 비교",
    "",
    "| 구분 | Node.js 내장 http | Express |",
    "|------|-------------------|---------|",
    "| 라우팅 | 직접 구현 (`if/else` 또는 Router 클래스) | `app.get()`, `app.post()` |",
    "| 파라미터 | 정규식으로 직접 파싱 | `req.params.id` 자동 |",
    "| 쿼리 스트링 | `URLSearchParams`로 직접 파싱 | `req.query` 자동 |",
    "| 요청 본문 | `req.on('data')` 수동 수집 | `express.json()` 미들웨어 |",
    "| 미들웨어 | 직접 구현 | `app.use()` 체인 |",
    "| CORS | 헤더 직접 설정 | `cors` 패키지 |",
    "| 장점 | HTTP 동작 원리 이해, 의존성 제로 | 생산성, 풍부한 생태계 |",
    "",
    "---",
    "",
    "### 요약",
    "Node.js 내장 `http` 모듈만으로도 라우터 클래스를 구현하여 동적 파라미터(`:id`), 쿼리 스트링, 정렬, 페이징, 검색, 필터링까지 갖춘 REST API를 만들 수 있습니다. 이 과정을 통해 Express가 내부적으로 해주는 작업(라우팅, 파라미터 파싱, 본문 파싱)을 직접 이해할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
