<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "nodejs-nestjs-fileupload-websocket",
  title: "NestJS 파일 업로드와 WebSocket 실시간 통신",
  date: "2026-02-25",
  summary: "NestJS에서 Multer로 파일 업로드를 처리하고, WebSocket과 Socket.io를 활용한 실시간 채팅(방, 네임스페이스, 브로드캐스트)을 구현하는 방법을 정리합니다.",
  category: "Technology/Node.js",
  tags: ["nodejs","nestjs","multer","websocket","socket.io","fileupload","realtime","chat"],
  content: [
    "## 한 줄 요약",
    "NestJS에서 **Multer**로 파일 업로드를, **WebSocket Gateway + Socket.io**로 실시간 채팅을 구현합니다.",
    "",
    "---",
    "",
    "# Part 1: 파일 업로드 (Multer)",
    "",
    "## 설치",
    "```bash",
    "npm install @nestjs/platform-express",
    "npm install -D @types/multer",
    "npm install @nestjs/serve-static",
    "```",
    "",
    "## Multer 옵션 설정",
    "```typescript",
    "// multer.options.ts",
    "import { randomUUID } from 'crypto';",
    "import { diskStorage } from 'multer';",
    "import { extname, join } from 'path';",
    "",
    "export const multerOption = {",
    "  storage: diskStorage({",
    "    destination: join(__dirname, '..', 'uploads'),",
    "    filename: (req, file, cb) => {",
    "      // UUID로 고유한 파일명 생성 (충돌 방지)",
    "      cb(null, randomUUID() + extname(file.originalname));",
    "    },",
    "  }),",
    "};",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `diskStorage` | 디스크에 파일 저장 |",
    "| `destination` | 저장 경로 |",
    "| `filename` | 저장될 파일명 규칙 |",
    "| `randomUUID()` | 고유 파일명으로 충돌 방지 |",
    "| `extname()` | 원본 파일의 확장자 추출 |",
    "",
    "## Controller",
    "```typescript",
    "// app.controller.ts",
    "import { FileInterceptor } from '@nestjs/platform-express';",
    "import { multerOption } from './multer.options';",
    "",
    "@Controller()",
    "export class AppController {",
    "  @Post('file-upload')",
    "  @UseInterceptors(FileInterceptor('file', multerOption))",
    "  fileUpload(@UploadedFile() file: Express.Multer.File) {",
    "    console.log(file);",
    "    return `${file.originalname} File upload`;",
    "  }",
    "}",
    "```",
    "",
    "| 데코레이터 | 설명 |",
    "|------------|------|",
    "| `@UseInterceptors()` | 인터셉터 적용 |",
    "| `FileInterceptor('file')` | `file` 필드에서 파일 추출 |",
    "| `@UploadedFile()` | 업로드된 파일 정보 주입 |",
    "",
    "## HTML 업로드 폼",
    "```html",
    "<form action=\"file-upload\" method=\"post\" enctype=\"multipart/form-data\">",
    "  <input type=\"file\" name=\"file\" />",
    "  <input type=\"submit\" value=\"Upload\" />",
    "</form>",
    "```",
    "",
    "## 정적 파일 서빙",
    "```typescript",
    "// app.module.ts",
    "import { ServeStaticModule } from '@nestjs/serve-static';",
    "import { join } from 'path';",
    "",
    "@Module({",
    "  imports: [",
    "    ServeStaticModule.forRoot({",
    "      rootPath: join(__dirname, '..', 'uploads'),",
    "      serveRoot: '/uploads',",
    "    }),",
    "  ],",
    "})",
    "```",
    "",
    "업로드 후 `http://localhost:3000/uploads/파일명`으로 접근 가능합니다.",
    "",
    "---",
    "",
    "# Part 2: WebSocket 실시간 통신",
    "",
    "## WebSocket이란?",
    "",
    "| HTTP | WebSocket |",
    "|------|-----------|",
    "| 요청-응답 (단방향) | 양방향 통신 |",
    "| 매번 연결/해제 | 한번 연결 후 유지 |",
    "| 클라이언트가 요청해야 응답 | 서버도 먼저 데이터 전송 가능 |",
    "",
    "## 순수 WebSocket (ws 모듈)",
    "",
    "### 서버",
    "```javascript",
    "// server.js",
    "const WebSocket = require('ws');",
    "const server = new WebSocket.Server({ port: 3000 });",
    "",
    "server.on('connection', (ws) => {",
    "  ws.send('[서버 접속 완료]');",
    "",
    "  ws.on('message', (message) => {",
    "    ws.send(`서버로부터 응답: ${message}`);",
    "  });",
    "",
    "  ws.on('close', () => {",
    "    console.log('클라이언트 접속 해제');",
    "  });",
    "});",
    "```",
    "",
    "### 클라이언트",
    "```html",
    "<input type=\"text\" id=\"message\" />",
    "<button onclick=\"sendMessage()\">전송</button>",
    "<div id=\"chat\"></div>",
    "",
    "```",
    "",
    "```javascript",
    "const ws = new WebSocket('ws://localhost:3000');",
    "",
    "ws.onopen = () => console.log('연결됨');",
    "ws.onmessage = (event) => {",
    "  document.getElementById('chat').innerHTML += `<div>${event.data}</div>`;",
    "};",
    "",
    "function sendMessage() {",
    "  const msg = document.getElementById('message').value;",
    "  ws.send(msg);",
    "}",
    "```",
    "",
    "---",
    "",
    "## NestJS Gateway (Socket.io)",
    "",
    "### 설치",
    "```bash",
    "npm install @nestjs/websockets @nestjs/platform-socket.io socket.io",
    "```",
    "",
    "### 채팅 Gateway",
    "```typescript",
    "// app.gateway.ts",
    "import { WebSocketGateway, WebSocketServer,",
    "  SubscribeMessage, MessageBody } from '@nestjs/websockets';",
    "import { Server, Socket } from 'socket.io';",
    "",
    "@WebSocketGateway({ namespace: 'chat' })",
    "export class ChatGateway {",
    "  @WebSocketServer() server: Server;",
    "",
    "  @SubscribeMessage('message')",
    "  handleMessage(socket: Socket, data: any): void {",
    "    const { message, nickname } = data;",
    "    // broadcast: 보낸 사람 제외 전체에게 전송",
    "    socket.broadcast.emit('message', `${nickname}: ${message}`);",
    "  }",
    "}",
    "```",
    "",
    "### 방(Room) Gateway",
    "```typescript",
    "@WebSocketGateway({ namespace: 'room' })",
    "export class RoomGateway {",
    "  rooms: string[] = [];",
    "",
    "  constructor(private chatGateway: ChatGateway) {}",
    "",
    "  @WebSocketServer() server: Server;",
    "",
    "  @SubscribeMessage('createRoom')",
    "  handleMessage(@MessageBody() data) {",
    "    const { nickname, room } = data;",
    "",
    "    // 모든 채팅 사용자에게 알림",
    "    this.chatGateway.server.emit('notice', {",
    "      message: `${nickname}님이 ${room}방을 만들었습니다`,",
    "    });",
    "",
    "    this.rooms.push(room);",
    "    this.server.emit('rooms', this.rooms);",
    "  }",
    "",
    "  @SubscribeMessage('joinRoom')",
    "  handleJoinRoom(socket: Socket, data) {",
    "    const { nickname, room, toLeaveRoom } = data;",
    "    socket.leave(toLeaveRoom);  // 기존 방 나가기",
    "    socket.join(room);           // 새 방 참가",
    "  }",
    "",
    "  @SubscribeMessage('message')",
    "  handleMessageToRoom(socket: Socket, data) {",
    "    const { nickname, room, message } = data;",
    "    // 같은 방의 다른 사용자에게만 전송",
    "    socket.broadcast.to(room).emit('message', {",
    "      message: `${nickname}: ${message}`,",
    "    });",
    "  }",
    "}",
    "```",
    "",
    "### 클라이언트 (Socket.io)",
    "```javascript",
    "const socket = io('http://localhost:3000/chat');",
    "const roomSocket = io('http://localhost:3000/room');",
    "",
    "// 채팅 메시지 수신",
    "socket.on('message', (message) => {",
    "  document.querySelector('#chat').innerHTML += `<div>${message}</div>`;",
    "});",
    "",
    "// 방 목록 업데이트",
    "roomSocket.on('rooms', (data) => {",
    "  const lis = data.map(",
    "    (room) => `<li>${room} <button onclick=\"joinRoom('${room}')\">join</button></li>`",
    "  );",
    "  document.querySelector('#rooms').innerHTML = lis.join('');",
    "});",
    "",
    "// 알림 수신",
    "socket.on('notice', (data) => {",
    "  document.querySelector('#chat').innerHTML += `<div>[공지] ${data.message}</div>`;",
    "});",
    "```",
    "",
    "---",
    "",
    "## Socket.io 핵심 개념",
    "",
    "| 개념 | 설명 |",
    "|------|------|",
    "| **Namespace** | 기능별 통신 채널 분리 (`/chat`, `/room`) |",
    "| **Room** | 네임스페이스 내의 그룹 (방) |",
    "| `socket.emit()` | 자신에게만 전송 |",
    "| `socket.broadcast.emit()` | 자신 제외 전체에게 전송 |",
    "| `socket.to(room).emit()` | 특정 방에만 전송 |",
    "| `socket.join(room)` | 방 참가 |",
    "| `socket.leave(room)` | 방 나가기 |",
    "| `server.emit()` | 모든 클라이언트에게 전송 |",
    "",
    "### 메시지 전송 범위 비교",
    "```",
    "server.emit()                  → 모든 클라이언트",
    "socket.broadcast.emit()        → 나 제외 전체",
    "socket.broadcast.to(room).emit() → 해당 방의 다른 사람들",
    "socket.emit()                  → 나에게만",
    "```",
    "",
    "---",
    "",
    "## NestJS 데코레이터 정리",
    "",
    "| 데코레이터 | 설명 |",
    "|------------|------|",
    "| `@WebSocketGateway()` | WebSocket 게이트웨이 선언 |",
    "| `@WebSocketServer()` | Socket.io Server 인스턴스 주입 |",
    "| `@SubscribeMessage('event')` | 특정 이벤트 구독 |",
    "| `@MessageBody()` | 메시지 데이터 추출 |",
    "| `@UseInterceptors()` | 인터셉터 (파일 업로드 등) |",
    "| `@UploadedFile()` | 업로드된 파일 주입 |",
    "",
    "---",
    "",
    "### 요약",
    "NestJS에서 **Multer**로 파일 업로드(UUID 파일명, 정적 파일 서빙)를 처리하고, **WebSocket Gateway**로 실시간 통신(채팅, 방, 네임스페이스, 브로드캐스트)을 구현합니다. Socket.io의 `namespace`로 기능을 분리하고, `room`으로 그룹 채팅을 만들 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
