<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "oracle-plsql-basics",
  title: "PL/SQL 기초 - 변수, 제어문, RECORD, 컬렉션",
  date: "2026-03-03",
  summary: "PL/SQL 블록 구조, 변수 선언, %TYPE·%ROWTYPE, IF·CASE·LOOP 제어문, RECORD 타입, 컬렉션(INDEX BY 테이블), 커서 FOR 루프까지 Oracle PL/SQL의 기초를 정리합니다.",
  category: "Coding/Oracle",
  tags: ["oracle","plsql","variable","type","rowtype","record","collection","loop","if","case"],
  content: [
    "## 한 줄 요약",
    "PL/SQL은 SQL에 **변수·제어문·예외 처리**를 더한 Oracle의 절차적 확장 언어이며, RECORD와 컬렉션으로 복합 데이터를 다룹니다.",
    "",
    "---",
    "",
    "## PL/SQL이란?",
    "",
    "PL/SQL(Procedural Language/SQL)은 Oracle에서 SQL을 절차적으로 확장한 프로그래밍 언어입니다.",
    "SQL만으로는 조건 분기, 반복, 변수 사용 등이 어렵지만, PL/SQL을 사용하면 이 모든 것이 가능합니다.",
    "",
    "---",
    "",
    "## PL/SQL 블록 구조",
    "",
    "PL/SQL 프로그램은 **블록(Block)** 단위로 작성합니다.",
    "",
    "```sql",
    "DECLARE",
    "    -- 선언부: 변수, 상수, 커서 등을 선언",
    "BEGIN",
    "    -- 실행부: 실제 처리할 SQL문, 제어문 등",
    "EXCEPTION",
    "    -- 예외 처리부: 에러 발생 시 처리 (선택)",
    "END;",
    "/",
    "```",
    "",
    "- **DECLARE**: 변수나 상수를 선언하는 부분 (생략 가능)",
    "- **BEGIN ~ END**: 실제 로직이 실행되는 부분 (필수)",
    "- **EXCEPTION**: 에러를 처리하는 부분 (생략 가능)",
    "- 블록 끝에는 반드시 **`/`** 를 붙여 실행합니다.",
    "",
    "---",
    "",
    "## 출력 설정: SET SERVEROUTPUT ON",
    "",
    "PL/SQL에서 결과를 화면에 출력하려면 먼저 출력 설정을 켜야 합니다.",
    "",
    "```sql",
    "SET SERVEROUTPUT ON;",
    "```",
    "",
    "출력에는 `DBMS_OUTPUT.PUT_LINE` 프로시저를 사용합니다.",
    "",
    "```sql",
    "BEGIN",
    "    DBMS_OUTPUT.PUT_LINE('Hello PL/SQL!');",
    "END;",
    "/",
    "```",
    "",
    "실행 결과:",
    "",
    "```sql",
    "Hello PL/SQL!",
    "```",
    "",
    "---",
    "",
    "## 변수 선언과 대입",
    "",
    "### 기본 변수 선언",
    "",
    "```sql",
    "DECLARE",
    "    v_name VARCHAR2(20) := '홍길동';",
    "    v_age  NUMBER := 25;",
    "BEGIN",
    "    DBMS_OUTPUT.PUT_LINE('이름: ' || v_name);",
    "    DBMS_OUTPUT.PUT_LINE('나이: ' || v_age);",
    "END;",
    "/",
    "```",
    "",
    "- 변수명 뒤에 **데이터 타입**을 지정합니다.",
    "- `:=` 연산자로 값을 대입합니다.",
    "- `||`는 문자열 연결 연산자입니다.",
    "",
    "### 상수 선언 (CONSTANT)",
    "",
    "```sql",
    "DECLARE",
    "    c_tax_rate CONSTANT NUMBER := 0.1;",
    "BEGIN",
    "    DBMS_OUTPUT.PUT_LINE('세율: ' || c_tax_rate);",
    "    -- c_tax_rate := 0.2;  -- 에러! 상수는 값 변경 불가",
    "END;",
    "/",
    "```",
    "",
    "- `CONSTANT` 키워드를 붙이면 값을 변경할 수 없는 상수가 됩니다.",
    "",
    "### DEFAULT 키워드",
    "",
    "```sql",
    "DECLARE",
    "    v_country VARCHAR2(20) DEFAULT '대한민국';",
    "BEGIN",
    "    DBMS_OUTPUT.PUT_LINE('국가: ' || v_country);",
    "END;",
    "/",
    "```",
    "",
    "- `:=` 대신 `DEFAULT` 키워드로도 초기값을 지정할 수 있습니다.",
    "",
    "### NOT NULL 제약",
    "",
    "```sql",
    "DECLARE",
    "    v_score NUMBER NOT NULL := 0;",
    "BEGIN",
    "    v_score := 95;",
    "    DBMS_OUTPUT.PUT_LINE('점수: ' || v_score);",
    "END;",
    "/",
    "```",
    "",
    "- `NOT NULL`을 붙이면 반드시 초기값이 있어야 하며, NULL 대입 시 에러가 발생합니다.",
    "",
    "---",
    "",
    "## %TYPE: 컬럼 타입 참조",
    "",
    "테이블의 특정 컬럼과 같은 데이터 타입으로 변수를 선언할 수 있습니다.",
    "",
    "```sql",
    "DECLARE",
    "    v_empno EMP.EMPNO%TYPE;",
    "    v_ename EMP.ENAME%TYPE;",
    "BEGIN",
    "    SELECT EMPNO, ENAME",
    "      INTO v_empno, v_ename",
    "      FROM EMP",
    "     WHERE EMPNO = 7788;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('사번: ' || v_empno);",
    "    DBMS_OUTPUT.PUT_LINE('이름: ' || v_ename);",
    "END;",
    "/",
    "```",
    "",
    "- `테이블명.컬럼명%TYPE`으로 해당 컬럼의 데이터 타입을 그대로 가져옵니다.",
    "- 테이블 컬럼 타입이 변경되어도 PL/SQL 코드를 수정할 필요가 없어 **유지보수에 유리**합니다.",
    "",
    "---",
    "",
    "## %ROWTYPE: 행 전체 타입 참조",
    "",
    "테이블의 한 행(row) 전체를 담을 수 있는 변수를 선언합니다.",
    "",
    "```sql",
    "DECLARE",
    "    v_emp EMP%ROWTYPE;",
    "BEGIN",
    "    SELECT *",
    "      INTO v_emp",
    "      FROM EMP",
    "     WHERE EMPNO = 7788;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('사번: ' || v_emp.EMPNO);",
    "    DBMS_OUTPUT.PUT_LINE('이름: ' || v_emp.ENAME);",
    "    DBMS_OUTPUT.PUT_LINE('직책: ' || v_emp.JOB);",
    "    DBMS_OUTPUT.PUT_LINE('급여: ' || v_emp.SAL);",
    "END;",
    "/",
    "```",
    "",
    "- `테이블명%ROWTYPE`으로 선언하면 해당 테이블의 모든 컬럼을 포함하는 레코드 변수가 됩니다.",
    "- `변수명.컬럼명`으로 각 필드에 접근합니다.",
    "",
    "---",
    "",
    "## SELECT INTO 문",
    "",
    "PL/SQL에서 SELECT 결과를 변수에 담으려면 반드시 `INTO` 절을 사용해야 합니다.",
    "",
    "```sql",
    "DECLARE",
    "    v_sal  EMP.SAL%TYPE;",
    "    v_comm EMP.COMM%TYPE;",
    "BEGIN",
    "    SELECT SAL, COMM",
    "      INTO v_sal, v_comm",
    "      FROM EMP",
    "     WHERE EMPNO = 7844;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('급여: ' || v_sal || ', 커미션: ' || NVL(v_comm, 0));",
    "END;",
    "/",
    "```",
    "",
    "- SELECT 결과가 **정확히 1행**이어야 합니다.",
    "- 0행이면 `NO_DATA_FOUND`, 2행 이상이면 `TOO_MANY_ROWS` 예외가 발생합니다.",
    "",
    "---",
    "",
    "## IF-THEN-ELSIF-ELSE 조건문",
    "",
    "```sql",
    "DECLARE",
    "    v_score NUMBER := 85;",
    "    v_grade VARCHAR2(10);",
    "BEGIN",
    "    IF v_score >= 90 THEN",
    "        v_grade := 'A';",
    "    ELSIF v_score >= 80 THEN",
    "        v_grade := 'B';",
    "    ELSIF v_score >= 70 THEN",
    "        v_grade := 'C';",
    "    ELSIF v_score >= 60 THEN",
    "        v_grade := 'D';",
    "    ELSE",
    "        v_grade := 'F';",
    "    END IF;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('점수: ' || v_score || ', 학점: ' || v_grade);",
    "END;",
    "/",
    "```",
    "",
    "- `IF ~ THEN ~ ELSIF ~ ELSE ~ END IF;` 구조입니다.",
    "- 주의: `ELSEIF`가 아니라 **`ELSIF`** 입니다 (E 없음).",
    "",
    "### 중첩 IF 예제",
    "",
    "```sql",
    "DECLARE",
    "    v_empno EMP.EMPNO%TYPE := 7788;",
    "    v_ename EMP.ENAME%TYPE;",
    "    v_deptno EMP.DEPTNO%TYPE;",
    "    v_msg VARCHAR2(100);",
    "BEGIN",
    "    SELECT ENAME, DEPTNO",
    "      INTO v_ename, v_deptno",
    "      FROM EMP",
    "     WHERE EMPNO = v_empno;",
    "",
    "    IF v_deptno = 10 THEN",
    "        v_msg := 'ACCOUNTING 부서';",
    "    ELSIF v_deptno = 20 THEN",
    "        v_msg := 'RESEARCH 부서';",
    "    ELSIF v_deptno = 30 THEN",
    "        v_msg := 'SALES 부서';",
    "    ELSE",
    "        v_msg := '기타 부서';",
    "    END IF;",
    "",
    "    DBMS_OUTPUT.PUT_LINE(v_ename || '은(는) ' || v_msg || '입니다.');",
    "END;",
    "/",
    "```",
    "",
    "---",
    "",
    "## CASE 문",
    "",
    "### 단순 CASE",
    "",
    "```sql",
    "DECLARE",
    "    v_deptno EMP.DEPTNO%TYPE := 20;",
    "    v_dname VARCHAR2(20);",
    "BEGIN",
    "    v_dname := CASE v_deptno",
    "                  WHEN 10 THEN 'ACCOUNTING'",
    "                  WHEN 20 THEN 'RESEARCH'",
    "                  WHEN 30 THEN 'SALES'",
    "                  WHEN 40 THEN 'OPERATIONS'",
    "                  ELSE '미정'",
    "              END;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('부서명: ' || v_dname);",
    "END;",
    "/",
    "```",
    "",
    "### 검색 CASE",
    "",
    "```sql",
    "DECLARE",
    "    v_sal NUMBER := 3500;",
    "    v_grade VARCHAR2(20);",
    "BEGIN",
    "    v_grade := CASE",
    "                  WHEN v_sal >= 5000 THEN '임원급'",
    "                  WHEN v_sal >= 3000 THEN '관리자급'",
    "                  WHEN v_sal >= 2000 THEN '사원급'",
    "                  ELSE '인턴급'",
    "              END;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('급여: ' || v_sal || ', 등급: ' || v_grade);",
    "END;",
    "/",
    "```",
    "",
    "- 단순 CASE: 하나의 값을 여러 값과 비교",
    "- 검색 CASE: 각 WHEN에 조건식을 자유롭게 작성",
    "",
    "---",
    "",
    "## 반복문 (LOOP)",
    "",
    "### 기본 LOOP ~ EXIT WHEN",
    "",
    "```sql",
    "DECLARE",
    "    v_num NUMBER := 1;",
    "BEGIN",
    "    LOOP",
    "        DBMS_OUTPUT.PUT_LINE('v_num = ' || v_num);",
    "        v_num := v_num + 1;",
    "        EXIT WHEN v_num > 5;",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "실행 결과:",
    "",
    "```sql",
    "v_num = 1",
    "v_num = 2",
    "v_num = 3",
    "v_num = 4",
    "v_num = 5",
    "```",
    "",
    "- `LOOP ~ END LOOP` 사이를 반복하며, `EXIT WHEN 조건`이 참이 되면 빠져나옵니다.",
    "",
    "### WHILE LOOP",
    "",
    "```sql",
    "DECLARE",
    "    v_num NUMBER := 1;",
    "BEGIN",
    "    WHILE v_num <= 5 LOOP",
    "        DBMS_OUTPUT.PUT_LINE('v_num = ' || v_num);",
    "        v_num := v_num + 1;",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "- 조건이 참인 동안 반복합니다.",
    "- 조건이 처음부터 거짓이면 한 번도 실행되지 않습니다.",
    "",
    "### FOR LOOP",
    "",
    "```sql",
    "BEGIN",
    "    FOR i IN 1..10 LOOP",
    "        DBMS_OUTPUT.PUT_LINE('i = ' || i);",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "- `IN 시작값..끝값` 형태로 범위를 지정합니다.",
    "- 루프 변수 `i`는 자동으로 선언되며, 루프 밖에서는 사용할 수 없습니다.",
    "",
    "### FOR LOOP (REVERSE)",
    "",
    "```sql",
    "BEGIN",
    "    FOR i IN REVERSE 1..5 LOOP",
    "        DBMS_OUTPUT.PUT_LINE('i = ' || i);",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "- `REVERSE`를 붙이면 끝값에서 시작값 방향으로 역순 반복합니다.",
    "",
    "### CONTINUE와 CONTINUE WHEN",
    "",
    "```sql",
    "BEGIN",
    "    FOR i IN 1..10 LOOP",
    "        CONTINUE WHEN MOD(i, 2) = 0;",
    "        DBMS_OUTPUT.PUT_LINE('홀수: ' || i);",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "실행 결과:",
    "",
    "```sql",
    "홀수: 1",
    "홀수: 3",
    "홀수: 5",
    "홀수: 7",
    "홀수: 9",
    "```",
    "",
    "- `CONTINUE WHEN 조건`: 조건이 참이면 나머지 코드를 건너뛰고 다음 반복으로 넘어갑니다.",
    "- `CONTINUE`만 단독으로 사용할 수도 있습니다.",
    "",
    "### 구구단 예제 (중첩 FOR)",
    "",
    "```sql",
    "BEGIN",
    "    FOR i IN 2..9 LOOP",
    "        DBMS_OUTPUT.PUT_LINE('--- ' || i || '단 ---');",
    "        FOR j IN 1..9 LOOP",
    "            DBMS_OUTPUT.PUT_LINE(i || ' x ' || j || ' = ' || (i * j));",
    "        END LOOP;",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "---",
    "",
    "## RECORD 타입",
    "",
    "여러 개의 필드를 하나로 묶어서 사용자 정의 레코드를 만들 수 있습니다.",
    "",
    "### 기본 RECORD 선언",
    "",
    "```sql",
    "DECLARE",
    "    TYPE rec_emp IS RECORD (",
    "        v_empno EMP.EMPNO%TYPE,",
    "        v_ename EMP.ENAME%TYPE,",
    "        v_job   EMP.JOB%TYPE,",
    "        v_sal   EMP.SAL%TYPE",
    "    );",
    "    r_emp rec_emp;",
    "BEGIN",
    "    SELECT EMPNO, ENAME, JOB, SAL",
    "      INTO r_emp",
    "      FROM EMP",
    "     WHERE EMPNO = 7788;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('사번: ' || r_emp.v_empno);",
    "    DBMS_OUTPUT.PUT_LINE('이름: ' || r_emp.v_ename);",
    "    DBMS_OUTPUT.PUT_LINE('직책: ' || r_emp.v_job);",
    "    DBMS_OUTPUT.PUT_LINE('급여: ' || r_emp.v_sal);",
    "END;",
    "/",
    "```",
    "",
    "- `TYPE 레코드명 IS RECORD (필드 선언, ...)` 형태로 정의합니다.",
    "- 각 필드에 `레코드변수.필드명`으로 접근합니다.",
    "",
    "### RECORD에 직접 값 대입",
    "",
    "```sql",
    "DECLARE",
    "    TYPE rec_product IS RECORD (",
    "        name  VARCHAR2(50),",
    "        price NUMBER,",
    "        qty   NUMBER",
    "    );",
    "    r_prod rec_product;",
    "BEGIN",
    "    r_prod.name  := '노트북';",
    "    r_prod.price := 1500000;",
    "    r_prod.qty   := 10;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('상품: ' || r_prod.name);",
    "    DBMS_OUTPUT.PUT_LINE('가격: ' || r_prod.price);",
    "    DBMS_OUTPUT.PUT_LINE('수량: ' || r_prod.qty);",
    "END;",
    "/",
    "```",
    "",
    "### 중첩 RECORD",
    "",
    "```sql",
    "DECLARE",
    "    TYPE rec_addr IS RECORD (",
    "        city    VARCHAR2(30),",
    "        zipcode VARCHAR2(10)",
    "    );",
    "    TYPE rec_person IS RECORD (",
    "        name VARCHAR2(20),",
    "        age  NUMBER,",
    "        addr rec_addr",
    "    );",
    "    r_person rec_person;",
    "BEGIN",
    "    r_person.name      := '김철수';",
    "    r_person.age       := 30;",
    "    r_person.addr.city    := '서울';",
    "    r_person.addr.zipcode := '12345';",
    "",
    "    DBMS_OUTPUT.PUT_LINE(r_person.name || ', ' || r_person.age || '세');",
    "    DBMS_OUTPUT.PUT_LINE('주소: ' || r_person.addr.city || ' (' || r_person.addr.zipcode || ')');",
    "END;",
    "/",
    "```",
    "",
    "- RECORD 안에 다른 RECORD를 필드로 포함할 수 있습니다.",
    "",
    "---",
    "",
    "## INDEX BY 테이블 (연관 배열 / Associative Array)",
    "",
    "PL/SQL에서 배열과 유사한 자료구조입니다. 키-값 쌍으로 데이터를 저장합니다.",
    "",
    "### 기본 사용",
    "",
    "```sql",
    "DECLARE",
    "    TYPE tbl_name IS TABLE OF VARCHAR2(30)",
    "        INDEX BY PLS_INTEGER;",
    "    v_names tbl_name;",
    "BEGIN",
    "    v_names(1) := '홍길동';",
    "    v_names(2) := '김영희';",
    "    v_names(3) := '이철수';",
    "",
    "    FOR i IN 1..3 LOOP",
    "        DBMS_OUTPUT.PUT_LINE(i || ': ' || v_names(i));",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "- `TYPE 타입명 IS TABLE OF 데이터타입 INDEX BY PLS_INTEGER` 형태로 선언합니다.",
    "- 인덱스(키)를 통해 값에 접근합니다.",
    "",
    "### VARCHAR2 키 사용",
    "",
    "```sql",
    "DECLARE",
    "    TYPE tbl_dept IS TABLE OF VARCHAR2(30)",
    "        INDEX BY VARCHAR2(10);",
    "    v_dept tbl_dept;",
    "BEGIN",
    "    v_dept('D10') := 'ACCOUNTING';",
    "    v_dept('D20') := 'RESEARCH';",
    "    v_dept('D30') := 'SALES';",
    "",
    "    DBMS_OUTPUT.PUT_LINE('D10: ' || v_dept('D10'));",
    "    DBMS_OUTPUT.PUT_LINE('D20: ' || v_dept('D20'));",
    "    DBMS_OUTPUT.PUT_LINE('D30: ' || v_dept('D30'));",
    "END;",
    "/",
    "```",
    "",
    "- `INDEX BY VARCHAR2(n)`으로 문자열 키도 사용할 수 있습니다.",
    "",
    "### RECORD 타입을 값으로 사용",
    "",
    "```sql",
    "DECLARE",
    "    TYPE rec_emp IS RECORD (",
    "        empno EMP.EMPNO%TYPE,",
    "        ename EMP.ENAME%TYPE,",
    "        sal   EMP.SAL%TYPE",
    "    );",
    "    TYPE tbl_emp IS TABLE OF rec_emp",
    "        INDEX BY PLS_INTEGER;",
    "    v_emps tbl_emp;",
    "    v_idx  PLS_INTEGER := 0;",
    "BEGIN",
    "    FOR rec IN (SELECT EMPNO, ENAME, SAL FROM EMP WHERE DEPTNO = 20) LOOP",
    "        v_idx := v_idx + 1;",
    "        v_emps(v_idx).empno := rec.EMPNO;",
    "        v_emps(v_idx).ename := rec.ENAME;",
    "        v_emps(v_idx).sal   := rec.SAL;",
    "    END LOOP;",
    "",
    "    FOR i IN 1..v_idx LOOP",
    "        DBMS_OUTPUT.PUT_LINE(v_emps(i).empno || ' | ' || v_emps(i).ename || ' | ' || v_emps(i).sal);",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "- TABLE OF 뒤에 RECORD 타입을 지정하면, 각 원소가 레코드인 컬렉션을 만들 수 있습니다.",
    "",
    "### 컬렉션 메서드",
    "",
    "| 메서드 | 설명 |",
    "| --- | --- |",
    "| `COUNT` | 원소의 총 개수 |",
    "| `FIRST` | 첫 번째 인덱스 |",
    "| `LAST` | 마지막 인덱스 |",
    "| `NEXT(n)` | n 다음 인덱스 |",
    "| `PRIOR(n)` | n 이전 인덱스 |",
    "| `EXISTS(n)` | n 인덱스 존재 여부 |",
    "| `DELETE` | 전체 삭제 |",
    "| `DELETE(n)` | n 인덱스 삭제 |",
    "",
    "```sql",
    "DECLARE",
    "    TYPE tbl_num IS TABLE OF NUMBER",
    "        INDEX BY PLS_INTEGER;",
    "    v_nums tbl_num;",
    "    v_idx  PLS_INTEGER;",
    "BEGIN",
    "    v_nums(10) := 100;",
    "    v_nums(20) := 200;",
    "    v_nums(30) := 300;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('개수: ' || v_nums.COUNT);",
    "    DBMS_OUTPUT.PUT_LINE('FIRST: ' || v_nums.FIRST);",
    "    DBMS_OUTPUT.PUT_LINE('LAST: ' || v_nums.LAST);",
    "",
    "    v_idx := v_nums.FIRST;",
    "    WHILE v_idx IS NOT NULL LOOP",
    "        DBMS_OUTPUT.PUT_LINE('인덱스 ' || v_idx || ' => ' || v_nums(v_idx));",
    "        v_idx := v_nums.NEXT(v_idx);",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "- `FIRST`/`LAST`와 `NEXT`/`PRIOR`를 사용하면 비연속 인덱스도 순회할 수 있습니다.",
    "",
    "---",
    "",
    "## 커서 FOR 루프 (암시적 커서)",
    "",
    "SELECT 결과를 하나씩 순회하는 가장 간단한 방법입니다.",
    "",
    "```sql",
    "BEGIN",
    "    FOR rec IN (SELECT EMPNO, ENAME, SAL FROM EMP WHERE DEPTNO = 30) LOOP",
    "        DBMS_OUTPUT.PUT_LINE(rec.EMPNO || ' | ' || rec.ENAME || ' | ' || rec.SAL);",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "- `FOR 변수 IN (SELECT문) LOOP` 형태로 사용합니다.",
    "- 커서의 OPEN, FETCH, CLOSE를 자동으로 처리해 줍니다.",
    "- `rec`는 자동 선언되는 %ROWTYPE 레코드입니다.",
    "",
    "### 커서 FOR 루프 + 조건문",
    "",
    "```sql",
    "BEGIN",
    "    FOR rec IN (SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP) LOOP",
    "        IF rec.SAL >= 3000 THEN",
    "            DBMS_OUTPUT.PUT_LINE('[고급] ' || rec.ENAME || ': ' || rec.SAL);",
    "        ELSIF rec.SAL >= 2000 THEN",
    "            DBMS_OUTPUT.PUT_LINE('[중급] ' || rec.ENAME || ': ' || rec.SAL);",
    "        ELSE",
    "            DBMS_OUTPUT.PUT_LINE('[초급] ' || rec.ENAME || ': ' || rec.SAL);",
    "        END IF;",
    "    END LOOP;",
    "END;",
    "/",
    "```",
    "",
    "---",
    "",
    "## 실습: 종합 예제",
    "",
    "### EMP 테이블 데이터를 컬렉션에 담기",
    "",
    "```sql",
    "DECLARE",
    "    TYPE rec_emp IS RECORD (",
    "        empno  EMP.EMPNO%TYPE,",
    "        ename  EMP.ENAME%TYPE,",
    "        job    EMP.JOB%TYPE,",
    "        sal    EMP.SAL%TYPE,",
    "        deptno EMP.DEPTNO%TYPE",
    "    );",
    "    TYPE tbl_emp IS TABLE OF rec_emp INDEX BY PLS_INTEGER;",
    "    v_emps  tbl_emp;",
    "    v_idx   PLS_INTEGER := 0;",
    "    v_total NUMBER := 0;",
    "BEGIN",
    "    FOR rec IN (SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP ORDER BY SAL DESC) LOOP",
    "        v_idx := v_idx + 1;",
    "        v_emps(v_idx).empno  := rec.EMPNO;",
    "        v_emps(v_idx).ename  := rec.ENAME;",
    "        v_emps(v_idx).job    := rec.JOB;",
    "        v_emps(v_idx).sal    := rec.SAL;",
    "        v_emps(v_idx).deptno := rec.DEPTNO;",
    "        v_total := v_total + rec.SAL;",
    "    END LOOP;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('=== 사원 목록 (급여 내림차순) ===');",
    "    FOR i IN 1..v_emps.COUNT LOOP",
    "        DBMS_OUTPUT.PUT_LINE(",
    "            RPAD(v_emps(i).ename, 10) || ' | ' ||",
    "            RPAD(v_emps(i).job, 12) || ' | ' ||",
    "            TO_CHAR(v_emps(i).sal, '99,999')",
    "        );",
    "    END LOOP;",
    "",
    "    DBMS_OUTPUT.PUT_LINE('---');",
    "    DBMS_OUTPUT.PUT_LINE('총 인원: ' || v_emps.COUNT || '명');",
    "    DBMS_OUTPUT.PUT_LINE('급여 합계: ' || TO_CHAR(v_total, '999,999'));",
    "    DBMS_OUTPUT.PUT_LINE('급여 평균: ' || TO_CHAR(ROUND(v_total / v_emps.COUNT, 2), '99,999.99'));",
    "END;",
    "/",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "",
    "| 항목 | 설명 |",
    "| --- | --- |",
    "| 블록 구조 | `DECLARE` - `BEGIN` - `EXCEPTION` - `END` |",
    "| 변수 선언 | `변수명 타입 := 값;` |",
    "| 상수 | `CONSTANT` 키워드 사용 |",
    "| `%TYPE` | 컬럼 타입 참조 (`EMP.SAL%TYPE`) |",
    "| `%ROWTYPE` | 행 전체 타입 참조 (`EMP%ROWTYPE`) |",
    "| 조건문 | `IF-THEN-ELSIF-ELSE-END IF`, `CASE` |",
    "| 반복문 | `LOOP-EXIT WHEN`, `WHILE LOOP`, `FOR LOOP` |",
    "| RECORD | `TYPE ... IS RECORD (...)` - 사용자 정의 레코드 |",
    "| 컬렉션 | `TYPE ... IS TABLE OF ... INDEX BY` - 연관 배열 |",
    "| 커서 FOR | `FOR rec IN (SELECT ...) LOOP` - 자동 커서 처리 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
