<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "oracle-join",
  title: "Oracle JOIN - 테이블 결합",
  date: "2026-03-03",
  summary: "Equi Join, Non-equi Join, Self Join, Outer Join, Natural Join, Cross Join까지 Oracle SQL에서 여러 테이블을 결합하는 JOIN의 모든 방법을 예제와 함께 정리합니다.",
  category: "Coding/Oracle",
  tags: ["oracle","sql","join","inner-join","outer-join","self-join","natural-join","cross-join"],
  content: [
    "## 한 줄 요약",
    "**JOIN**은 두 개 이상의 테이블을 공통 컬럼 기준으로 결합하여 하나의 결과로 조회하는 SQL의 핵심 기능입니다.",
    "",
    "---",
    "",
    "## 참고",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| 실습 스키마 | SCOTT (EMP, DEPT, SALGRADE 테이블) |",
    "| DBMS | Oracle Database |",
    "",
    "### 실습 테이블 구조",
    "",
    "| 테이블 | 주요 컬럼 |",
    "|--------|-----------|",
    "| EMP | EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, **DEPTNO** |",
    "| DEPT | **DEPTNO**, DNAME, LOC |",
    "| SALGRADE | GRADE, LOSAL, HISAL |",
    "",
    "- EMP와 DEPT는 `DEPTNO` 컬럼으로 연결됩니다.",
    "- SALGRADE는 급여 등급 범위(LOSAL~HISAL)를 저장합니다.",
    "",
    "---",
    "",
    "## JOIN이 필요한 이유",
    "",
    "관계형 데이터베이스에서는 데이터를 여러 테이블로 나누어 저장합니다(정규화). 예를 들어 사원 정보(EMP)와 부서 정보(DEPT)가 분리되어 있으므로, 사원의 부서명을 함께 보려면 두 테이블을 **결합(JOIN)**해야 합니다.",
    "",
    "```sql",
    "-- JOIN 없이는 부서명을 알 수 없음",
    "SELECT ENAME, DEPTNO FROM EMP;     -- DEPTNO만 표시",
    "SELECT DEPTNO, DNAME FROM DEPT;    -- 부서명은 별도 테이블",
    "```",
    "",
    "---",
    "",
    "## Equi Join (등가 조인)",
    "",
    "가장 많이 사용하는 JOIN으로, 두 테이블의 **공통 컬럼 값이 같은** 행을 결합합니다.",
    "",
    "### Oracle 전통 문법 (WHERE)",
    "",
    "```sql",
    "SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,",
    "       D.DEPTNO, D.DNAME, D.LOC",
    "  FROM EMP E, DEPT D",
    " WHERE E.DEPTNO = D.DEPTNO;",
    "```",
    "",
    "| EMPNO | ENAME | JOB | SAL | DEPTNO | DNAME | LOC |",
    "|-------|-------|-----|-----|--------|-------|-----|",
    "| 7369 | SMITH | CLERK | 800 | 20 | RESEARCH | DALLAS |",
    "| 7499 | ALLEN | SALESMAN | 1600 | 30 | SALES | CHICAGO |",
    "| 7839 | KING | PRESIDENT | 5000 | 10 | ACCOUNTING | NEW YORK |",
    "",
    "- `E`, `D`는 테이블 별칭(alias)으로, 컬럼 이름이 겹칠 때 어느 테이블의 컬럼인지 구분합니다.",
    "- WHERE 절에 조인 조건과 일반 조건을 함께 쓸 수 있습니다.",
    "",
    "### ANSI 표준 문법 (JOIN ... ON)",
    "",
    "```sql",
    "SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,",
    "       D.DEPTNO, D.DNAME, D.LOC",
    "  FROM EMP E",
    "  JOIN DEPT D ON E.DEPTNO = D.DEPTNO;",
    "```",
    "",
    "### 추가 조건과 함께 사용",
    "",
    "```sql",
    "-- 부서 30이면서 급여 1500 이상인 사원과 부서 정보",
    "SELECT E.EMPNO, E.ENAME, E.SAL,",
    "       D.DNAME, D.LOC",
    "  FROM EMP E",
    "  JOIN DEPT D ON E.DEPTNO = D.DEPTNO",
    " WHERE E.DEPTNO = 30",
    "   AND E.SAL >= 1500;",
    "```",
    "",
    "---",
    "",
    "## Non-equi Join (비등가 조인)",
    "",
    "`=` 이외의 연산자(`BETWEEN`, `>`, `<` 등)를 사용하여 조인합니다. SALGRADE 테이블처럼 범위로 매칭할 때 사용합니다.",
    "",
    "```sql",
    "-- 사원의 급여 등급 조회",
    "SELECT E.ENAME, E.SAL,",
    "       S.GRADE, S.LOSAL, S.HISAL",
    "  FROM EMP E, SALGRADE S",
    " WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;",
    "```",
    "",
    "| ENAME | SAL | GRADE | LOSAL | HISAL |",
    "|-------|-----|-------|-------|-------|",
    "| SMITH | 800 | 1 | 700 | 1200 |",
    "| ALLEN | 1600 | 3 | 1401 | 2000 |",
    "| KING | 5000 | 5 | 3001 | 9999 |",
    "",
    "### ANSI 표준 문법",
    "",
    "```sql",
    "SELECT E.ENAME, E.SAL,",
    "       S.GRADE",
    "  FROM EMP E",
    "  JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;",
    "```",
    "",
    "---",
    "",
    "## Self Join (자기 조인)",
    "",
    "같은 테이블을 두 번 사용하여 조인합니다. **사원-관리자 관계**처럼 한 테이블 안에서 참조가 있을 때 사용합니다.",
    "",
    "EMP 테이블의 `MGR` 컬럼은 해당 사원의 관리자 사원번호(EMPNO)를 가리킵니다.",
    "",
    "```sql",
    "-- 사원과 그 관리자의 이름을 함께 조회",
    "SELECT E.EMPNO AS 사원번호,",
    "       E.ENAME AS 사원이름,",
    "       E.MGR AS 관리자번호,",
    "       M.ENAME AS 관리자이름",
    "  FROM EMP E, EMP M",
    " WHERE E.MGR = M.EMPNO;",
    "```",
    "",
    "| 사원번호 | 사원이름 | 관리자번호 | 관리자이름 |",
    "|----------|----------|------------|------------|",
    "| 7369 | SMITH | 7902 | FORD |",
    "| 7499 | ALLEN | 7698 | BLAKE |",
    "| 7566 | JONES | 7839 | KING |",
    "",
    "> **주의**: KING(사장)은 MGR이 NULL이므로 Equi Join 결과에 포함되지 않습니다. KING도 포함하려면 **Outer Join**을 사용해야 합니다.",
    "",
    "### ANSI 표준 문법",
    "",
    "```sql",
    "SELECT E.EMPNO, E.ENAME AS 사원,",
    "       M.ENAME AS 관리자",
    "  FROM EMP E",
    "  JOIN EMP M ON E.MGR = M.EMPNO;",
    "```",
    "",
    "---",
    "",
    "## Outer Join (외부 조인)",
    "",
    "Inner Join은 두 테이블에 모두 일치하는 데이터만 반환합니다. **Outer Join**은 한쪽 테이블에 일치하는 행이 없어도 NULL로 채워서 결과에 포함합니다.",
    "",
    "### LEFT OUTER JOIN",
    "",
    "**왼쪽 테이블의 모든 행**을 포함합니다. 오른쪽에 매칭되는 행이 없으면 NULL로 채웁니다.",
    "",
    "```sql",
    "-- 모든 사원 + 관리자 (KING도 포함)",
    "SELECT E.EMPNO, E.ENAME AS 사원,",
    "       M.ENAME AS 관리자",
    "  FROM EMP E",
    "  LEFT OUTER JOIN EMP M ON E.MGR = M.EMPNO;",
    "```",
    "",
    "| EMPNO | 사원 | 관리자 |",
    "|-------|------|--------|",
    "| 7369 | SMITH | FORD |",
    "| 7839 | KING | (null) |",
    "",
    "### RIGHT OUTER JOIN",
    "",
    "**오른쪽 테이블의 모든 행**을 포함합니다.",
    "",
    "```sql",
    "-- 모든 부서 + 해당 사원 (사원이 없는 부서도 포함)",
    "SELECT E.ENAME, D.DEPTNO, D.DNAME",
    "  FROM EMP E",
    " RIGHT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO",
    " ORDER BY D.DEPTNO;",
    "```",
    "",
    "| ENAME | DEPTNO | DNAME |",
    "|-------|--------|-------|",
    "| CLARK | 10 | ACCOUNTING |",
    "| KING | 10 | ACCOUNTING |",
    "| (null) | 40 | OPERATIONS |",
    "",
    "> 부서 40(OPERATIONS)에는 사원이 없지만 RIGHT JOIN이므로 결과에 포함됩니다.",
    "",
    "### FULL OUTER JOIN",
    "",
    "**양쪽 테이블의 모든 행**을 포함합니다.",
    "",
    "```sql",
    "SELECT E.ENAME, D.DEPTNO, D.DNAME",
    "  FROM EMP E",
    "  FULL OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;",
    "```",
    "",
    "---",
    "",
    "## Oracle (+) 문법",
    "",
    "Oracle 전통 문법에서 Outer Join은 `(+)` 기호를 사용합니다. **(+)는 데이터가 부족한 쪽에** 붙입니다.",
    "",
    "```sql",
    "-- LEFT OUTER JOIN: 오른쪽(M)이 부족하므로 M 쪽에 (+)",
    "SELECT E.ENAME AS 사원,",
    "       M.ENAME AS 관리자",
    "  FROM EMP E, EMP M",
    " WHERE E.MGR = M.EMPNO(+);",
    "```",
    "",
    "```sql",
    "-- RIGHT OUTER JOIN: 왼쪽(E)이 부족하므로 E 쪽에 (+)",
    "SELECT E.ENAME, D.DEPTNO, D.DNAME",
    "  FROM EMP E, DEPT D",
    " WHERE E.DEPTNO(+) = D.DEPTNO;",
    "```",
    "",
    "### (+) 문법의 제한사항",
    "",
    "| 제한 | 설명 |",
    "|------|------|",
    "| FULL OUTER JOIN 불가 | `(+)`로는 양쪽 모두에 붙일 수 없음 |",
    "| OR 조건 사용 불가 | `(+)` 조건에 OR을 쓸 수 없음 |",
    "| 서브쿼리 제한 | `(+)`와 서브쿼리를 함께 쓸 수 없음 |",
    "",
    "> **권장**: ANSI 표준 JOIN 문법(LEFT/RIGHT/FULL OUTER JOIN)을 사용하세요. 가독성이 좋고 제약이 적습니다.",
    "",
    "---",
    "",
    "## NATURAL JOIN",
    "",
    "두 테이블에서 **이름과 타입이 같은 컬럼**을 자동으로 찾아 조인합니다. 조인 조건을 직접 쓰지 않습니다.",
    "",
    "```sql",
    "SELECT EMPNO, ENAME, JOB, DEPTNO, DNAME, LOC",
    "  FROM EMP",
    "NATURAL JOIN DEPT;",
    "```",
    "",
    "- `DEPTNO`가 두 테이블 모두에 있으므로 자동으로 조인 조건이 됩니다.",
    "- NATURAL JOIN에서는 조인에 사용된 컬럼에 **테이블 별칭을 붙이면 안 됩니다**.",
    "",
    "```sql",
    "-- ❌ 잘못된 예: NATURAL JOIN에서 조인 컬럼에 별칭 사용",
    "SELECT E.EMPNO, E.ENAME, E.DEPTNO  -- E.DEPTNO → 에러",
    "  FROM EMP E",
    "NATURAL JOIN DEPT D;",
    "",
    "-- ✅ 올바른 예: 조인 컬럼은 별칭 없이",
    "SELECT EMPNO, ENAME, DEPTNO, DNAME",
    "  FROM EMP",
    "NATURAL JOIN DEPT;",
    "```",
    "",
    "> **주의**: 의도치 않은 컬럼이 조인 조건에 포함될 수 있으므로 `JOIN ... ON`이 더 안전합니다.",
    "",
    "---",
    "",
    "## JOIN ... USING",
    "",
    "조인에 사용할 **컬럼 이름을 명시적으로 지정**합니다. 두 테이블에서 이름이 같은 컬럼 중 원하는 것만 선택합니다.",
    "",
    "```sql",
    "SELECT EMPNO, ENAME, JOB, DEPTNO, DNAME, LOC",
    "  FROM EMP",
    "  JOIN DEPT USING (DEPTNO);",
    "```",
    "",
    "- USING에 지정한 컬럼(`DEPTNO`)은 테이블 별칭을 붙이면 안 됩니다.",
    "- NATURAL JOIN보다 명시적이어서 실수를 줄일 수 있습니다.",
    "",
    "---",
    "",
    "## JOIN ... ON",
    "",
    "가장 범용적이고 **명시적인 조인 방법**입니다. 조인 조건을 ON 절에 직접 작성합니다.",
    "",
    "```sql",
    "SELECT E.EMPNO, E.ENAME, E.SAL,",
    "       D.DNAME, D.LOC",
    "  FROM EMP E",
    "  JOIN DEPT D ON E.DEPTNO = D.DEPTNO;",
    "```",
    "",
    "### 3개 이상 테이블 조인",
    "",
    "```sql",
    "-- EMP + DEPT + SALGRADE 3개 테이블 조인",
    "SELECT E.EMPNO, E.ENAME, E.SAL,",
    "       D.DNAME,",
    "       S.GRADE",
    "  FROM EMP E",
    "  JOIN DEPT D ON E.DEPTNO = D.DEPTNO",
    "  JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;",
    "```",
    "",
    "| EMPNO | ENAME | SAL | DNAME | GRADE |",
    "|-------|-------|-----|-------|-------|",
    "| 7369 | SMITH | 800 | RESEARCH | 1 |",
    "| 7839 | KING | 5000 | ACCOUNTING | 5 |",
    "",
    "### 다중 테이블 + Outer Join 조합",
    "",
    "```sql",
    "-- 모든 사원의 부서명, 급여등급, 관리자 이름 (관리자 없어도 포함)",
    "SELECT E.EMPNO,",
    "       E.ENAME AS 사원,",
    "       D.DNAME AS 부서명,",
    "       S.GRADE AS 급여등급,",
    "       M.ENAME AS 관리자",
    "  FROM EMP E",
    "  JOIN DEPT D ON E.DEPTNO = D.DEPTNO",
    "  JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL",
    "  LEFT OUTER JOIN EMP M ON E.MGR = M.EMPNO",
    " ORDER BY E.EMPNO;",
    "```",
    "",
    "---",
    "",
    "## CROSS JOIN (교차 조인)",
    "",
    "두 테이블의 **모든 행 조합(카티션 곱)**을 반환합니다. 조인 조건이 없으므로 결과 행 수 = A행 × B행 입니다.",
    "",
    "```sql",
    "-- ANSI 표준",
    "SELECT E.ENAME, D.DNAME",
    "  FROM EMP E",
    " CROSS JOIN DEPT D;",
    "",
    "-- Oracle 전통 (WHERE 없이 나열)",
    "SELECT E.ENAME, D.DNAME",
    "  FROM EMP E, DEPT D;",
    "```",
    "",
    "- EMP가 14행, DEPT가 4행이면 결과는 14 × 4 = **56행**",
    "- 실무에서는 거의 사용하지 않지만, 테스트 데이터 생성이나 모든 조합 확인 시 활용합니다.",
    "",
    "> **주의**: WHERE 절에 조인 조건을 빠뜨리면 의도치 않게 CROSS JOIN이 되어 대량 데이터가 발생합니다.",
    "",
    "---",
    "",
    "## JOIN 방식 비교",
    "",
    "| 방식 | 문법 | 특징 |",
    "|------|------|------|",
    "| Oracle 전통 | `FROM A, B WHERE A.col = B.col` | 간결하지만 조인·필터 조건 혼합 |",
    "| ANSI JOIN ON | `FROM A JOIN B ON A.col = B.col` | 명시적·범용적 (권장) |",
    "| NATURAL JOIN | `FROM A NATURAL JOIN B` | 자동 매칭 (위험할 수 있음) |",
    "| JOIN USING | `FROM A JOIN B USING (col)` | 동일 이름 컬럼 명시 |",
    "| CROSS JOIN | `FROM A CROSS JOIN B` | 카티션 곱 (조건 없음) |",
    "",
    "---",
    "",
    "## 종합 예제",
    "",
    "```sql",
    "-- 예제 1: 각 부서별 사원 수, 최대/최소 급여, 급여 등급 범위",
    "SELECT D.DEPTNO, D.DNAME,",
    "       COUNT(E.EMPNO) AS 사원수,",
    "       MAX(E.SAL) AS 최대급여,",
    "       MIN(E.SAL) AS 최소급여",
    "  FROM DEPT D",
    "  LEFT OUTER JOIN EMP E ON D.DEPTNO = E.DEPTNO",
    " GROUP BY D.DEPTNO, D.DNAME",
    " ORDER BY D.DEPTNO;",
    "```",
    "",
    "```sql",
    "-- 예제 2: 급여가 자신의 관리자보다 높은 사원 찾기",
    "SELECT E.ENAME AS 사원,",
    "       E.SAL AS 사원급여,",
    "       M.ENAME AS 관리자,",
    "       M.SAL AS 관리자급여",
    "  FROM EMP E",
    "  JOIN EMP M ON E.MGR = M.EMPNO",
    " WHERE E.SAL > M.SAL;",
    "```",
    "",
    "```sql",
    "-- 예제 3: 부서별 사원 목록과 급여등급을 한 줄로 출력",
    "SELECT D.DNAME,",
    "       LISTAGG(E.ENAME || '(' || S.GRADE || '등급)', ', ')",
    "         WITHIN GROUP (ORDER BY E.SAL DESC) AS 사원목록",
    "  FROM EMP E",
    "  JOIN DEPT D ON E.DEPTNO = D.DEPTNO",
    "  JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL",
    " GROUP BY D.DNAME;",
    "```",
    "",
    "```sql",
    "-- 예제 4: 같은 부서 내 다른 사원의 급여와 비교",
    "SELECT E1.DEPTNO,",
    "       E1.ENAME AS 사원1,",
    "       E1.SAL AS 급여1,",
    "       E2.ENAME AS 사원2,",
    "       E2.SAL AS 급여2",
    "  FROM EMP E1",
    "  JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO",
    "                AND E1.EMPNO < E2.EMPNO",
    " ORDER BY E1.DEPTNO, E1.ENAME;",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "",
    "| JOIN 유형 | 설명 | 사용 시기 |",
    "|-----------|------|-----------|",
    "| Equi Join | `=`로 컬럼 값 매칭 | 가장 일반적인 조인 (FK 관계) |",
    "| Non-equi Join | `BETWEEN`, `>`, `<` 등 사용 | 범위 매칭 (급여 등급 등) |",
    "| Self Join | 같은 테이블 2번 사용 | 계층 관계 (사원-관리자) |",
    "| LEFT OUTER JOIN | 왼쪽 테이블 전체 포함 | 매칭 안 되는 행도 필요할 때 |",
    "| RIGHT OUTER JOIN | 오른쪽 테이블 전체 포함 | 매칭 안 되는 행도 필요할 때 |",
    "| FULL OUTER JOIN | 양쪽 모두 포함 | 양쪽 다 누락 없이 볼 때 |",
    "| NATURAL JOIN | 동일 컬럼명 자동 매칭 | 간단하지만 위험 (비권장) |",
    "| JOIN USING | 조인 컬럼 명시 | 컬럼명이 같을 때 간결하게 |",
    "| JOIN ON | 조건 직접 지정 | 가장 범용적 (권장) |",
    "| CROSS JOIN | 카티션 곱 | 모든 조합 필요 시 (드뭄) |",
    "| Oracle (+) | 전통 Outer Join 문법 | 레거시 코드 (ANSI 권장) |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
