<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "oracle-ddl",
  title: "Oracle DDL - 테이블 생성·수정·삭제",
  date: "2026-03-03",
  summary: "Oracle 데이터 타입, CREATE TABLE, ALTER TABLE(ADD·MODIFY·DROP COLUMN), RENAME, TRUNCATE, DROP TABLE까지 DDL(데이터 정의어)을 예제와 함께 정리합니다.",
  category: "Coding/Oracle",
  tags: ["oracle","sql","ddl","create","alter","drop","truncate","rename","data-type"],
  content: [
    "## 한 줄 요약",
    "**DDL(Data Definition Language)**은 테이블·뷰 등 데이터베이스 객체의 **구조를 생성·변경·삭제**하는 명령어이며, 실행 즉시 **자동 COMMIT**됩니다.",
    "",
    "---",
    "",
    "## DDL이란?",
    "",
    "DDL은 데이터베이스 **객체(테이블, 인덱스, 뷰 등)의 구조**를 정의하는 SQL 명령어입니다.",
    "",
    "| 명령어 | 기능 |",
    "|--------|------|",
    "| **CREATE** | 객체 생성 |",
    "| **ALTER** | 객체 구조 변경 |",
    "| **DROP** | 객체 삭제 |",
    "| **TRUNCATE** | 테이블 데이터 전체 삭제 (구조 유지) |",
    "| **RENAME** | 객체 이름 변경 |",
    "",
    "> **중요:** DDL은 실행 즉시 **자동 COMMIT**됩니다. ROLLBACK으로 되돌릴 수 없으므로 신중하게 사용해야 합니다.",
    "",
    "---",
    "",
    "## 1. Oracle 주요 데이터 타입",
    "",
    "테이블을 만들기 전에 컬럼에 사용할 수 있는 데이터 타입을 알아야 합니다.",
    "",
    "### 문자 타입",
    "",
    "| 타입 | 설명 | 최대 크기 |",
    "|------|------|-----------|",
    "| **VARCHAR2(n)** | 가변 길이 문자열 (실제 길이만큼 저장) | 4000 바이트 |",
    "| **CHAR(n)** | 고정 길이 문자열 (남는 공간은 공백 채움) | 2000 바이트 |",
    "| **CLOB** | 대용량 텍스트 | 최대 4GB |",
    "",
    "```sql",
    "-- VARCHAR2: 'ABC' 저장 시 3바이트만 사용",
    "-- CHAR(10): 'ABC' 저장 시 10바이트 사용 (나머지 공백)",
    "```",
    "",
    "> **실무 팁:** 대부분의 문자 컬럼은 **VARCHAR2**를 사용합니다. CHAR는 우편번호, 성별 코드처럼 길이가 고정된 경우에만 사용합니다.",
    "",
    "### 숫자 타입",
    "",
    "| 타입 | 설명 | 예시 |",
    "|------|------|------|",
    "| **NUMBER** | 정수·실수 모두 가능 | NUMBER |",
    "| **NUMBER(p)** | 전체 자릿수 p | NUMBER(5) → 최대 99999 |",
    "| **NUMBER(p, s)** | 전체 p자리, 소수점 s자리 | NUMBER(7,2) → 최대 99999.99 |",
    "",
    "```sql",
    "-- NUMBER(7,2): 전체 7자리 중 소수점 2자리",
    "-- 예: 12345.67 (정수 5자리 + 소수 2자리 = 7자리)",
    "```",
    "",
    "### 날짜 타입",
    "",
    "| 타입 | 설명 |",
    "|------|------|",
    "| **DATE** | 날짜 + 시간 (초 단위까지) |",
    "| **TIMESTAMP** | 날짜 + 시간 (밀리초 단위까지) |",
    "",
    "### 이진 데이터 타입",
    "",
    "| 타입 | 설명 | 최대 크기 |",
    "|------|------|-----------|",
    "| **BLOB** | 이진 대용량 데이터 (이미지, 동영상 등) | 최대 4GB |",
    "",
    "### 데이터 타입 선택 가이드",
    "",
    "| 용도 | 추천 타입 |",
    "|------|-----------|",
    "| 이름, 주소 등 가변 문자열 | VARCHAR2 |",
    "| 성별(M/F), 코드 등 고정 문자열 | CHAR |",
    "| 가격, 수량, 점수 등 숫자 | NUMBER |",
    "| 가입일, 생년월일 등 날짜 | DATE |",
    "| 긴 텍스트 (게시글 본문 등) | CLOB |",
    "| 파일, 이미지 | BLOB |",
    "",
    "---",
    "",
    "## 2. CREATE TABLE — 테이블 생성",
    "",
    "### 기본 문법",
    "",
    "```sql",
    "CREATE TABLE 테이블명 (",
    "    컬럼명1  데이터타입  [제약조건],",
    "    컬럼명2  데이터타입  [제약조건],",
    "    ...",
    ");",
    "```",
    "",
    "### 사원 정보 테이블 생성 예제",
    "",
    "```sql",
    "CREATE TABLE MEMBER (",
    "    MEMBER_ID    NUMBER(10)     NOT NULL,",
    "    NAME         VARCHAR2(50)   NOT NULL,",
    "    EMAIL        VARCHAR2(100),",
    "    PHONE        VARCHAR2(20),",
    "    JOIN_DATE    DATE           DEFAULT SYSDATE,",
    "    SALARY       NUMBER(10, 2),",
    "    DEPT_CODE    CHAR(2)",
    ");",
    "```",
    "",
    "### 테이블 이름 규칙",
    "",
    "| 규칙 | 설명 |",
    "|------|------|",
    "| 문자로 시작 | 숫자로 시작 불가 |",
    "| 30자 이내 | Oracle 12c 이전 기준 |",
    "| 영문, 숫자, _, $, # 사용 가능 | 특수문자 제한 |",
    "| 예약어 사용 불가 | SELECT, TABLE 등은 이름으로 사용 불가 |",
    "| 대소문자 구분 없음 | Oracle은 기본적으로 대문자로 저장 |",
    "",
    "### DEFAULT 값 설정",
    "",
    "```sql",
    "CREATE TABLE ORDERS (",
    "    ORDER_ID     NUMBER(10),",
    "    ORDER_DATE   DATE          DEFAULT SYSDATE,",
    "    STATUS       VARCHAR2(20)  DEFAULT 'PENDING',",
    "    QUANTITY     NUMBER(5)     DEFAULT 1",
    ");",
    "```",
    "",
    "INSERT 시 값을 지정하지 않으면 DEFAULT 값이 자동으로 들어갑니다.",
    "",
    "---",
    "",
    "## 3. CREATE TABLE AS SELECT — 테이블 복사",
    "",
    "기존 테이블의 구조와 데이터를 복사하여 새 테이블을 생성합니다.",
    "",
    "### 구조 + 데이터 모두 복사",
    "",
    "```sql",
    "CREATE TABLE EMP_BACKUP",
    "    AS SELECT * FROM EMP;",
    "```",
    "",
    "### 특정 컬럼만 복사",
    "",
    "```sql",
    "CREATE TABLE EMP_SAL",
    "    AS SELECT EMPNO, ENAME, SAL, DEPTNO",
    "         FROM EMP;",
    "```",
    "",
    "### 조건에 맞는 데이터만 복사",
    "",
    "```sql",
    "CREATE TABLE EMP_DEPT10",
    "    AS SELECT *",
    "         FROM EMP",
    "        WHERE DEPTNO = 10;",
    "```",
    "",
    "### 구조만 복사 (데이터 없이)",
    "",
    "```sql",
    "CREATE TABLE EMP_EMPTY",
    "    AS SELECT *",
    "         FROM EMP",
    "        WHERE 1 <> 1;",
    "```",
    "",
    "`WHERE 1 <> 1`은 항상 거짓이므로 **0건의 행**과 **컬럼 구조**만 복사됩니다.",
    "",
    "> **주의:** CREATE TABLE AS SELECT는 **NOT NULL 제약조건만** 복사됩니다. PRIMARY KEY, FOREIGN KEY 등은 복사되지 않습니다.",
    "",
    "---",
    "",
    "## 4. ALTER TABLE — 테이블 구조 변경",
    "",
    "### ADD — 컬럼 추가",
    "",
    "```sql",
    "ALTER TABLE EMP_BACKUP",
    "  ADD (HOBBY VARCHAR2(50));",
    "```",
    "",
    "새 컬럼은 테이블 **맨 뒤**에 추가되며, 기존 행의 해당 컬럼 값은 **NULL**입니다.",
    "",
    "### 여러 컬럼 동시 추가",
    "",
    "```sql",
    "ALTER TABLE EMP_BACKUP",
    "  ADD (HOBBY    VARCHAR2(50),",
    "       ADDRESS  VARCHAR2(200),",
    "       BONUS    NUMBER(10, 2));",
    "```",
    "",
    "### MODIFY — 컬럼 변경",
    "",
    "컬럼의 데이터 타입, 크기, DEFAULT 값을 변경합니다.",
    "",
    "```sql",
    "-- 컬럼 크기 변경",
    "ALTER TABLE EMP_BACKUP",
    "  MODIFY (HOBBY VARCHAR2(100));",
    "```",
    "",
    "```sql",
    "-- DEFAULT 값 추가",
    "ALTER TABLE EMP_BACKUP",
    "  MODIFY (HOBBY VARCHAR2(100) DEFAULT 'NONE');",
    "```",
    "",
    "### MODIFY 주의사항",
    "",
    "| 변경 | 가능 조건 |",
    "|------|-----------|",
    "| 크기 확대 | 항상 가능 |",
    "| 크기 축소 | 기존 데이터 중 최대 길이보다 크거나 같아야 가능 |",
    "| 타입 변경 | 컬럼이 비어 있을 때만 가능 (일부 호환 타입 제외) |",
    "| NOT NULL 추가 | 컬럼에 NULL 데이터가 없을 때만 가능 |",
    "",
    "### RENAME COLUMN — 컬럼 이름 변경",
    "",
    "```sql",
    "ALTER TABLE EMP_BACKUP",
    "  RENAME COLUMN HOBBY TO INTEREST;",
    "```",
    "",
    "### DROP COLUMN — 컬럼 삭제",
    "",
    "```sql",
    "ALTER TABLE EMP_BACKUP",
    "  DROP COLUMN INTEREST;",
    "```",
    "",
    "> **주의:** 컬럼 삭제는 **되돌릴 수 없습니다.** 데이터도 함께 삭제됩니다.",
    "",
    "### ALTER TABLE 명령 정리",
    "",
    "| 명령 | 문법 | 설명 |",
    "|------|------|------|",
    "| ADD | `ALTER TABLE t ADD (col type)` | 컬럼 추가 |",
    "| MODIFY | `ALTER TABLE t MODIFY (col type)` | 컬럼 속성 변경 |",
    "| RENAME COLUMN | `ALTER TABLE t RENAME COLUMN a TO b` | 컬럼 이름 변경 |",
    "| DROP COLUMN | `ALTER TABLE t DROP COLUMN col` | 컬럼 삭제 |",
    "",
    "---",
    "",
    "## 5. RENAME — 테이블 이름 변경",
    "",
    "```sql",
    "RENAME EMP_BACKUP TO EMP_ARCHIVE;",
    "```",
    "",
    "테이블 이름이 `EMP_BACKUP`에서 `EMP_ARCHIVE`로 변경됩니다. DDL이므로 **자동 COMMIT**됩니다.",
    "",
    "```sql",
    "-- 변경 확인",
    "SELECT TABLE_NAME",
    "  FROM USER_TABLES",
    " WHERE TABLE_NAME = 'EMP_ARCHIVE';",
    "```",
    "",
    "---",
    "",
    "## 6. TRUNCATE TABLE vs DELETE — 전체 삭제 비교",
    "",
    "### TRUNCATE",
    "",
    "```sql",
    "TRUNCATE TABLE EMP_ARCHIVE;",
    "```",
    "",
    "### DELETE",
    "",
    "```sql",
    "DELETE FROM EMP_ARCHIVE;",
    "```",
    "",
    "### 차이점 비교",
    "",
    "| 항목 | TRUNCATE | DELETE |",
    "|------|----------|--------|",
    "| 분류 | **DDL** | **DML** |",
    "| ROLLBACK | 불가능 (자동 COMMIT) | 가능 (COMMIT 전) |",
    "| 속도 | 빠름 | 느림 (행 단위 삭제) |",
    "| WHERE 조건 | 사용 불가 (전체만) | 사용 가능 |",
    "| 저장 공간 | 해제됨 | 해제 안 됨 |",
    "| 로그 기록 | 최소 | 행 단위 기록 |",
    "| 트리거 실행 | 안 됨 | 실행됨 |",
    "",
    "> **실무 팁:** 전체 데이터를 삭제하고 복구가 필요 없다면 **TRUNCATE**가 훨씬 빠릅니다. 하지만 되돌릴 수 없으므로 주의해야 합니다.",
    "",
    "---",
    "",
    "## 7. DROP TABLE — 테이블 삭제",
    "",
    "```sql",
    "DROP TABLE EMP_ARCHIVE;",
    "```",
    "",
    "테이블의 **구조와 데이터 모두** 삭제됩니다. DDL이므로 **자동 COMMIT**됩니다.",
    "",
    "### 휴지통 기능 (Oracle 10g 이상)",
    "",
    "Oracle은 DROP된 테이블을 **휴지통(Recycle Bin)**에 보관합니다.",
    "",
    "```sql",
    "-- 휴지통 확인",
    "SELECT * FROM RECYCLEBIN;",
    "```",
    "",
    "```sql",
    "-- 휴지통에서 복구",
    "FLASHBACK TABLE EMP_ARCHIVE TO BEFORE DROP;",
    "```",
    "",
    "```sql",
    "-- 휴지통 거치지 않고 완전 삭제",
    "DROP TABLE EMP_ARCHIVE PURGE;",
    "```",
    "",
    "```sql",
    "-- 휴지통 비우기",
    "PURGE RECYCLEBIN;",
    "```",
    "",
    "---",
    "",
    "## DDL 명령어 전체 정리",
    "",
    "| 명령어 | 문법 | 자동 COMMIT |",
    "|--------|------|-------------|",
    "| CREATE TABLE | `CREATE TABLE t (col type, ...)` | O |",
    "| CREATE TABLE AS SELECT | `CREATE TABLE t AS SELECT ...` | O |",
    "| ALTER TABLE ADD | `ALTER TABLE t ADD (col type)` | O |",
    "| ALTER TABLE MODIFY | `ALTER TABLE t MODIFY (col type)` | O |",
    "| ALTER TABLE RENAME COLUMN | `ALTER TABLE t RENAME COLUMN a TO b` | O |",
    "| ALTER TABLE DROP COLUMN | `ALTER TABLE t DROP COLUMN col` | O |",
    "| RENAME | `RENAME old TO new` | O |",
    "| TRUNCATE TABLE | `TRUNCATE TABLE t` | O |",
    "| DROP TABLE | `DROP TABLE t` | O |",
    "",
    "---",
    "",
    "## 실전 예제 — 테이블 생성부터 삭제까지",
    "",
    "```sql",
    "-- 1) 테이블 생성",
    "CREATE TABLE STUDENT (",
    "    STU_ID     NUMBER(5)      NOT NULL,",
    "    NAME       VARCHAR2(30)   NOT NULL,",
    "    MAJOR      VARCHAR2(50),",
    "    GRADE      NUMBER(1)      DEFAULT 1,",
    "    BIRTH      DATE,",
    "    EMAIL      VARCHAR2(100)",
    ");",
    "```",
    "",
    "```sql",
    "-- 2) 컬럼 추가",
    "ALTER TABLE STUDENT",
    "  ADD (PHONE VARCHAR2(20));",
    "```",
    "",
    "```sql",
    "-- 3) 컬럼 크기 변경",
    "ALTER TABLE STUDENT",
    "  MODIFY (MAJOR VARCHAR2(100));",
    "```",
    "",
    "```sql",
    "-- 4) 컬럼 이름 변경",
    "ALTER TABLE STUDENT",
    "  RENAME COLUMN BIRTH TO BIRTHDAY;",
    "```",
    "",
    "```sql",
    "-- 5) 불필요한 컬럼 삭제",
    "ALTER TABLE STUDENT",
    "  DROP COLUMN EMAIL;",
    "```",
    "",
    "```sql",
    "-- 6) 구조 확인",
    "DESC STUDENT;",
    "```",
    "",
    "```sql",
    "-- 7) 테이블 이름 변경",
    "RENAME STUDENT TO STUDENT_INFO;",
    "```",
    "",
    "```sql",
    "-- 8) 데이터 전체 삭제 (구조 유지)",
    "TRUNCATE TABLE STUDENT_INFO;",
    "```",
    "",
    "```sql",
    "-- 9) 테이블 완전 삭제",
    "DROP TABLE STUDENT_INFO PURGE;",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "",
    "| 개념 | 핵심 |",
    "|------|------|",
    "| DDL | 객체 구조를 정의하는 명령, 자동 COMMIT |",
    "| 데이터 타입 | VARCHAR2(가변문자), NUMBER(숫자), DATE(날짜), CLOB/BLOB(대용량) |",
    "| CREATE TABLE | 테이블 생성, 컬럼명·타입·제약조건 정의 |",
    "| CREATE TABLE AS SELECT | 기존 테이블 복사, WHERE 1<>1로 구조만 복사 |",
    "| ALTER TABLE | ADD(추가), MODIFY(변경), RENAME COLUMN(이름변경), DROP COLUMN(삭제) |",
    "| RENAME | 테이블 이름 변경 |",
    "| TRUNCATE | 전체 데이터 삭제, DDL이라 ROLLBACK 불가, DELETE보다 빠름 |",
    "| DROP TABLE | 테이블 자체 삭제, PURGE로 완전 삭제 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
