<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "python-modules",
  title: "Python 모듈 (import)",
  date: "2026-02-17",
  summary: "sys, random, datetime, time, os 등 자주 쓰는 표준 라이브러리 모듈을 정리합니다.",
  category: "Coding/Python",
  tags: ["python", "모듈", "import", "basics"],
  content: [
    "## 모듈이란?",
    "미리 작성된 코드를 `import`로 가져와 재사용하는 단위입니다. Python에는 표준 라이브러리가 풍부합니다.",
    "",
    "## sys",
    "시스템·인터프리터 관련 정보와 설정입니다.",
    "",
    "```python",
    "import sys",
    "print(sys.argv)       # 명령행 인자 리스트",
    "print(sys.version)    # Python 버전",
    "sys.exit()            # 프로그램 강제 종료",
    "```",
    "",
    "## random",
    "난수 생성입니다.",
    "",
    "```python",
    "import random",
    "print(random.random())                    # 0.0 ~ 1.0",
    "print(random.uniform(10, 20))             # 10 ~ 20 실수",
    "print(random.randrange(10))              # 0 ~ 9 정수",
    "print(random.choice([1, 2, 3, 4, 5]))     # 리스트에서 하나",
    "print(random.sample([1, 2, 3, 4, 5], k=2))  # 2개 뽑기",
    "lst = [1, 2, 3, 4, 5]",
    "random.shuffle(lst)   # 리스트 섞기 (in-place)",
    "```",
    "",
    "## datetime",
    "날짜와 시간 처리입니다.",
    "",
    "```python",
    "import datetime",
    "now = datetime.datetime.now()",
    "print(now.year, now.month, now.day)",
    "print(now.hour, now.minute, now.second)",
    "print(now.strftime(\"%Y.%m.%d %H:%M:%S\"))",
    "```",
    "",
    "## time",
    "시간 대기 등입니다.",
    "",
    "```python",
    "import time",
    "print(\"5초 후에...\")",
    "time.sleep(5)",
    "print(\"종료\")",
    "```",
    "",
    "## os",
    "운영체제·파일시스템 관련입니다.",
    "",
    "```python",
    "import os",
    "print(os.getcwd())        # 현재 작업 디렉터리",
    "print(os.listdir('.'))    # 디렉터리 내용",
    "os.mkdir(\"hello\")        # 폴더 생성",
    "os.rmdir(\"hello\")       # 빈 폴더 삭제",
    "os.rename(\"old.txt\", \"new.txt\")",
    "os.remove(\"file.txt\")   # 파일 삭제",
    "```",
    "",
    "---",
    "### 요약",
    "- `import 모듈이름`으로 가져오기",
    "- sys: 인자, 버전, exit",
    "- random: 난수, choice, shuffle",
    "- datetime: 현재 시각, strftime",
    "- os: 경로, 파일·폴더 조작"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
