<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "python-loops",
  title: "Python 반복문 (for, while)",
  date: "2026-02-17",
  summary: "for, while, range(), reversed(), enumerate(), break, continue, 리스트 컴프리헨션을 정리합니다.",
  category: "Coding/Python",
  tags: ["python", "반복문", "for", "while", "range", "basics"],
  content: [
    "## for - 시퀀스 순회",
    "리스트·문자열 등 시퀀스의 각 요소를 순서대로 꺼냅니다.",
    "",
    "```python",
    "array = [273, 32, 103, 57, 52]",
    "for element in array:",
    "    print(element)",
    "```",
    "",
    "## range() - 숫자 범위",
    "| 사용법 | 결과 |",
    "|--------|------|",
    "| range(5) | 0, 1, 2, 3, 4 |",
    "| range(5, 10) | 5, 6, 7, 8, 9 |",
    "| range(0, 10, 3) | 0, 3, 6, 9 |",
    "",
    "```python",
    "for i in range(5):",
    "    print(i)",
    "",
    "for i in range(5, 10):",
    "    print(i)",
    "",
    "for i in range(0, 10, 3):",
    "    print(i)",
    "```",
    "",
    "## 역순 반복",
    "```python",
    "for i in reversed(range(5)):",
    "    print(i)  # 4, 3, 2, 1, 0",
    "",
    "for i in reversed([1, 2, 3, 4, 5]):",
    "    print(i)",
    "```",
    "",
    "## enumerate() - 인덱스와 값",
    "```python",
    "example_list = [\"요소A\", \"요소B\", \"요소C\"]",
    "for i, value in enumerate(example_list):",
    "    print(f\"{i}번째 요소는 {value}\")",
    "```",
    "",
    "## while",
    "조건이 참인 동안 반복합니다.",
    "",
    "```python",
    "i = 0",
    "while i < 10:",
    "    print(f\"{i}번째 반복\")",
    "    i += 1",
    "```",
    "",
    "## break - 반복 중단",
    "```python",
    "while True:",
    "    text = input(\"> 종료하시겠습니까?(y): \")",
    "    if text in [\"y\", \"Y\"]:",
    "        print(\"반복을 종료합니다.\")",
    "        break",
    "```",
    "",
    "## continue - 다음 반복으로",
    "```python",
    "numbers = [5, 15, 6, 20, 7, 25]",
    "for number in numbers:",
    "    if number < 10:",
    "        continue",
    "    print(number)  # 15, 20, 25만 출력",
    "```",
    "",
    "## 리스트 컴프리헨션",
    "```python",
    "array = [\"사과\", \"자두\", \"초콜릿\", \"바나나\"]",
    "output = [fruit for fruit in array if fruit != \"초콜릿\"]",
    "",
    "output2 = [i * i for i in range(0, 10, 2)]  # [0, 4, 16, 36, 64]",
    "```",
    "",
    "---",
    "### 요약",
    "- `for x in seq`: 시퀀스 순회",
    "- `range(start, end, step)`: 숫자 범위",
    "- `break`: 반복 종료, `continue`: 다음 반복",
    "- `[x for x in seq if 조건]`: 리스트 컴프리헨션"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
