<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "python-exceptions",
  title: "Python 예외 처리 (try, except)",
  date: "2026-02-17",
  summary: "try, except, else, finally로 예외를 처리하는 방법과 특정 예외 잡기, with 문을 정리합니다.",
  category: "Coding/Python",
  tags: ["python", "예외처리", "try", "except", "basics"],
  content: [
    "## 왜 예외 처리가 필요한가",
    "사용자가 잘못된 입력을 하거나, 파일이 없거나, 인덱스가 범위를 벗어나면 **예외(Exception)**가 발생합니다. 처리하지 않으면 프로그램이 중단됩니다.",
    "",
    "## try except 기본",
    "```python",
    "try:",
    "    number = int(input(\"정수 입력> \"))",
    "    print(\"원의 반지름:\", number)",
    "    print(\"원의 둘레:\", 2 * 3.14 * number)",
    "except:",
    "    print(\"정수를 입력하지 않았습니다.\")",
    "```",
    "",
    "## try except else",
    "예외가 **나지 않았을 때** `else` 블록이 실행됩니다.",
    "",
    "```python",
    "try:",
    "    number = int(input(\"정수 입력> \"))",
    "except:",
    "    print(\"정수를 입력하지 않았습니다.\")",
    "else:",
    "    print(\"원의 반지름:\", number)",
    "    print(\"원의 둘레:\", 2 * 3.14 * number)",
    "```",
    "",
    "## try except finally",
    "예외 발생 여부와 관계없이 **항상** `finally` 블록이 실행됩니다. 파일 닫기 등 정리 작업에 씁니다.",
    "",
    "```python",
    "try:",
    "    number = int(input(\"정수 입력> \"))",
    "    print(\"원의 반지름:\", number)",
    "except:",
    "    print(\"오류 발생\")",
    "finally:",
    "    print(\"프로그램이 종료됩니다.\")",
    "```",
    "",
    "## 특정 예외만 잡기",
    "```python",
    "list_number = [52, 273, 32, 72, 100]",
    "try:",
    "    idx = int(input(\"정수 입력> \"))",
    "    print(list_number[idx])",
    "except ValueError:",
    "    print(\"정수를 입력해 주세요!\")",
    "except IndexError:",
    "    print(\"인덱스 범위를 벗어났어요!\")",
    "```",
    "",
    "## 예외 객체 받기",
    "```python",
    "try:",
    "    number = int(\"abc\")",
    "except Exception as e:",
    "    print(\"type:\", type(e))",
    "    print(\"exception:\", e)",
    "```",
    "",
    "## with와 함께 쓰기",
    "파일을 열 때는 `with`를 쓰면 예외가 나도 **자동으로 닫힙니다**.",
    "",
    "```python",
    "try:",
    "    with open(\"basic.txt\", \"r\") as file:",
    "        contents = file.read()",
    "    print(contents)",
    "except FileNotFoundError:",
    "    print(\"파일이 없습니다.\")",
    "```",
    "",
    "---",
    "### 요약",
    "- `try` / `except`로 예외 처리",
    "- `else`: 예외 없을 때 실행",
    "- `finally`: 항상 실행 (정리용)",
    "- `except ValueError`, `except IndexError` 등으로 특정 예외만 처리"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
