<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "react-performance",
  title: "React 성능 최적화 완벽 가이드",
  date: "2026-03-03",
  summary: "React.memo, useMemo, useCallback, 코드 스플리팅, 가상화(Virtualization), React Profiler, 리렌더링 방지 패턴 등 React 앱 성능 최적화 기법을 JavaScript·TypeScript 예제로 정리합니다.",
  category: "Technology/React",
  tags: ["react","performance","React.memo","useMemo","useCallback","virtualization","profiler","code-splitting","typescript"],
  content: [
    "## 한 줄 요약",
    "React 성능 최적화의 핵심은 **불필요한 리렌더링 방지**, **번들 크기 축소**, **대량 데이터 가상화**입니다.",
    "",
    "---",
    "",
    "## 리렌더링이 발생하는 경우",
    "",
    "| 원인 | 설명 |",
    "|------|------|",
    "| `setState` 호출 | 해당 컴포넌트와 모든 자식 리렌더링 |",
    "| 부모 리렌더링 | props가 바뀌지 않아도 자식 리렌더링 |",
    "| Context 값 변경 | 해당 Context를 구독하는 모든 컴포넌트 |",
    "| 커스텀 훅의 상태 변경 | 훅을 사용하는 컴포넌트 리렌더링 |",
    "",
    "---",
    "",
    "## 1. React.memo — 컴포넌트 메모이제이션",
    "",
    "props가 변하지 않으면 리렌더링을 건너뜁니다.",
    "",
    "**TypeScript**",
    "```tsx",
    "import { memo } from 'react';",
    "",
    "interface UserCardProps {",
    "  name: string;",
    "  email: string;",
    "}",
    "",
    "const UserCard = memo(function UserCard({ name, email }: UserCardProps): JSX.Element {",
    "  console.log('UserCard 렌더링');",
    "  return (",
    "    <div>",
    "      <h3>{name}</h3>",
    "      <p>{email}</p>",
    "    </div>",
    "  );",
    "});",
    "",
    "// 부모가 리렌더링되어도 name, email이 같으면 UserCard는 리렌더링 안 됨",
    "```",
    "",
    "### 커스텀 비교 함수",
    "",
    "```tsx",
    "const HeavyList = memo(",
    "  function HeavyList({ items }: { items: Item[] }) {",
    "    return <ul>{items.map((item) => <li key={item.id}>{item.name}</li>)}</ul>;",
    "  },",
    "  (prevProps, nextProps) => {",
    "    return prevProps.items.length === nextProps.items.length;",
    "  }",
    ");",
    "```",
    "",
    "### React.memo가 효과 없는 경우",
    "",
    "```tsx",
    "// ❌ 매번 새 객체/함수를 만들면 memo가 무력화됨",
    "function Parent() {",
    "  return (",
    "    <MemoChild",
    "      style={{ color: 'red' }}     // 매번 새 객체",
    "      onClick={() => doSomething()} // 매번 새 함수",
    "    />",
    "  );",
    "}",
    "",
    "// ✅ useMemo + useCallback으로 해결",
    "function Parent() {",
    "  const style = useMemo(() => ({ color: 'red' }), []);",
    "  const handleClick = useCallback(() => doSomething(), []);",
    "",
    "  return <MemoChild style={style} onClick={handleClick} />;",
    "}",
    "```",
    "",
    "---",
    "",
    "## 2. useMemo — 계산 결과 메모이제이션",
    "",
    "비용이 큰 계산을 캐싱합니다.",
    "",
    "```tsx",
    "import { useMemo, useState } from 'react';",
    "",
    "function ProductList({ products }: { products: Product[] }): JSX.Element {",
    "  const [filter, setFilter] = useState('');",
    "  const [sortBy, setSortBy] = useState<'name' | 'price'>('name');",
    "",
    "  const filteredAndSorted = useMemo(() => {",
    "    console.log('필터링 + 정렬 계산');",
    "    return products",
    "      .filter((p) => p.name.includes(filter))",
    "      .sort((a, b) => (sortBy === 'price' ? a.price - b.price : a.name.localeCompare(b.name)));",
    "  }, [products, filter, sortBy]);",
    "",
    "  return (",
    "    <div>",
    "      <input value={filter} onChange={(e) => setFilter(e.target.value)} />",
    "      <ul>",
    "        {filteredAndSorted.map((p) => <li key={p.id}>{p.name}: {p.price}원</li>)}",
    "      </ul>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 3. useCallback — 함수 참조 유지",
    "",
    "자식에게 전달하는 콜백 함수의 참조를 유지하여 불필요한 리렌더링을 방지합니다.",
    "",
    "```tsx",
    "import { useCallback, useState, memo } from 'react';",
    "",
    "const TodoItem = memo(function TodoItem({",
    "  todo,",
    "  onToggle,",
    "}: {",
    "  todo: Todo;",
    "  onToggle: (id: number) => void;",
    "}) {",
    "  console.log('TodoItem 렌더링:', todo.text);",
    "  return (",
    "    <li onClick={() => onToggle(todo.id)}>",
    "      {todo.done ? '✅' : '⬜'} {todo.text}",
    "    </li>",
    "  );",
    "});",
    "",
    "function TodoList(): JSX.Element {",
    "  const [todos, setTodos] = useState<Todo[]>([]);",
    "",
    "  const handleToggle = useCallback((id: number) => {",
    "    setTodos((prev) =>",
    "      prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t))",
    "    );",
    "  }, []);",
    "",
    "  return (",
    "    <ul>",
    "      {todos.map((todo) => (",
    "        <TodoItem key={todo.id} todo={todo} onToggle={handleToggle} />",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 4. 코드 스플리팅 (Code Splitting)",
    "",
    "`React.lazy`와 `Suspense`로 페이지/컴포넌트를 필요할 때만 로드합니다.",
    "",
    "```tsx",
    "import { lazy, Suspense } from 'react';",
    "",
    "const HeavyChart = lazy(() => import('./components/HeavyChart'));",
    "const AdminPanel = lazy(() => import('./pages/AdminPanel'));",
    "",
    "function App(): JSX.Element {",
    "  return (",
    "    <Suspense fallback={<p>로딩 중...</p>}>",
    "      <Routes>",
    "        <Route path='/admin' element={<AdminPanel />} />",
    "        <Route path='/chart' element={<HeavyChart />} />",
    "      </Routes>",
    "    </Suspense>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 5. 가상화 (Virtualization)",
    "",
    "수천 개의 리스트 아이템 중 **화면에 보이는 것만** 렌더링합니다.",
    "",
    "### 설치",
    "```bash",
    "npm install @tanstack/react-virtual",
    "```",
    "",
    "```tsx",
    "import { useVirtualizer } from '@tanstack/react-virtual';",
    "import { useRef } from 'react';",
    "",
    "function VirtualList({ items }: { items: string[] }): JSX.Element {",
    "  const parentRef = useRef<HTMLDivElement>(null);",
    "",
    "  const virtualizer = useVirtualizer({",
    "    count: items.length,",
    "    getScrollElement: () => parentRef.current,",
    "    estimateSize: () => 40,",
    "  });",
    "",
    "  return (",
    "    <div ref={parentRef} style={{ height: '400px', overflow: 'auto' }}>",
    "      <div style={{ height: `${virtualizer.getTotalSize()}px`, position: 'relative' }}>",
    "        {virtualizer.getVirtualItems().map((virtualItem) => (",
    "          <div",
    "            key={virtualItem.key}",
    "            style={{",
    "              position: 'absolute',",
    "              top: 0,",
    "              transform: `translateY(${virtualItem.start}px)`,",
    "              height: `${virtualItem.size}px`,",
    "              width: '100%',",
    "            }}",
    "          >",
    "            {items[virtualItem.index]}",
    "          </div>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "// 10,000개 아이템도 부드럽게 스크롤",
    "<VirtualList items={Array.from({ length: 10000 }, (_, i) => `아이템 ${i}`)} />",
    "```",
    "",
    "---",
    "",
    "## 6. React Profiler",
    "",
    "### DevTools Profiler",
    "React DevTools의 Profiler 탭에서 각 컴포넌트의 렌더링 시간과 횟수를 시각적으로 확인할 수 있습니다.",
    "",
    "### Profiler 컴포넌트",
    "",
    "```tsx",
    "import { Profiler, type ProfilerOnRenderCallback } from 'react';",
    "",
    "const onRender: ProfilerOnRenderCallback = (",
    "  id, phase, actualDuration, baseDuration, startTime, commitTime",
    ") => {",
    "  console.log(`${id} [${phase}] ${actualDuration.toFixed(1)}ms`);",
    "};",
    "",
    "function App(): JSX.Element {",
    "  return (",
    "    <Profiler id='App' onRender={onRender}>",
    "      <Dashboard />",
    "    </Profiler>",
    "  );",
    "}",
    "```",
    "",
    "| 파라미터 | 설명 |",
    "|----------|------|",
    "| `id` | Profiler 식별자 |",
    "| `phase` | `'mount'` 또는 `'update'` |",
    "| `actualDuration` | 실제 렌더링 시간 (ms) |",
    "| `baseDuration` | 메모이제이션 없이 렌더링했을 때의 시간 |",
    "",
    "---",
    "",
    "## 7. 상태 구조 최적화",
    "",
    "### 상태 분리",
    "",
    "```tsx",
    "// ❌ 하나의 큰 상태 — 하나만 바뀌어도 전체 리렌더링",
    "const [state, setState] = useState({",
    "  users: [], filter: '', page: 1, isModalOpen: false,",
    "});",
    "",
    "// ✅ 독립적인 상태 분리 — 각각 독립 리렌더링",
    "const [users, setUsers] = useState<User[]>([]);",
    "const [filter, setFilter] = useState('');",
    "const [page, setPage] = useState(1);",
    "const [isModalOpen, setIsModalOpen] = useState(false);",
    "```",
    "",
    "### Context 분리",
    "",
    "```tsx",
    "// ❌ 하나의 Context에 모든 것",
    "const AppContext = createContext({ theme: 'light', user: null, lang: 'ko' });",
    "",
    "// ✅ 관심사별 Context 분리",
    "const ThemeContext = createContext<Theme>('light');",
    "const UserContext = createContext<User | null>(null);",
    "const LangContext = createContext<string>('ko');",
    "```",
    "",
    "---",
    "",
    "## 최적화 체크리스트",
    "",
    "| 기법 | 효과 | 적용 시점 |",
    "|------|------|----------|",
    "| `React.memo` | 불필요한 리렌더링 방지 | 자식 props가 자주 바뀌지 않을 때 |",
    "| `useMemo` | 비싼 계산 캐싱 | 필터링/정렬 등 무거운 연산 |",
    "| `useCallback` | 콜백 참조 유지 | memo된 자식에 함수 전달 시 |",
    "| 코드 스플리팅 | 초기 로드 시간 감소 | 라우트별 페이지 분리 |",
    "| 가상화 | 대량 리스트 성능 | 100개 이상 아이템 |",
    "| 상태 분리 | 리렌더링 범위 축소 | 독립적인 상태가 합쳐져 있을 때 |",
    "| Context 분리 | Context 리렌더링 범위 축소 | 자주 바뀌는 값과 안 바뀌는 값 분리 |",
    "",
    "---",
    "",
    "### 요약",
    "React 성능 최적화는 **측정 먼저, 최적화 나중**이 원칙입니다. React DevTools Profiler로 병목을 찾고, `React.memo`/`useMemo`/`useCallback`으로 불필요한 리렌더링을 방지합니다. 대량 리스트는 **가상화**, 번들 크기는 **코드 스플리팅**으로 해결합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
