<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "react-events",
  title: "React 이벤트 처리 완벽 가이드",
  date: "2026-03-03",
  summary: "React의 합성 이벤트(SyntheticEvent) 시스템, 클릭·폼·키보드·마우스·드래그 이벤트 처리, 이벤트 위임, 커스텀 이벤트 핸들러 패턴을 JavaScript·TypeScript 예제로 정리합니다.",
  category: "Technology/React",
  tags: ["react","event","onClick","onChange","onSubmit","SyntheticEvent","typescript","form"],
  content: [
    "## 한 줄 요약",
    "React는 브라우저 네이티브 이벤트를 **SyntheticEvent**로 감싸 크로스 브라우저 호환성을 보장하며, **camelCase** 이름과 **JSX 콜백**으로 이벤트를 처리합니다.",
    "",
    "---",
    "",
    "## 공식 문서",
    "",
    "| 항목 | URL |",
    "|------|-----|",
    "| 이벤트 응답하기 | [react.dev/learn/responding-to-events](https://react.dev/learn/responding-to-events) |",
    "| SyntheticEvent 레퍼런스 | [react.dev/reference/react-dom/components/common](https://react.dev/reference/react-dom/components/common) |",
    "",
    "---",
    "",
    "## React 이벤트 vs HTML 이벤트",
    "",
    "| 구분 | HTML | React |",
    "|------|------|-------|",
    "| 이벤트 이름 | `onclick` (소문자) | `onClick` (camelCase) |",
    "| 핸들러 전달 | 문자열 `\"handleClick()\"` | 함수 `{handleClick}` |",
    "| 기본 동작 방지 | `return false` | `e.preventDefault()` |",
    "| 이벤트 객체 | 브라우저 `Event` | React `SyntheticEvent` |",
    "| 이벤트 위임 | 직접 구현 | React가 자동 처리 (root에 위임) |",
    "",
    "```jsx",
    "// HTML",
    "// <button onclick=\"handleClick()\">클릭</button>",
    "",
    "// React",
    "<button onClick={handleClick}>클릭</button>",
    "```",
    "",
    "---",
    "",
    "## SyntheticEvent (합성 이벤트)",
    "",
    "React는 브라우저의 네이티브 이벤트를 `SyntheticEvent`로 래핑합니다. 모든 브라우저에서 동일한 API를 제공합니다.",
    "",
    "### 주요 속성·메서드",
    "",
    "| 속성/메서드 | 설명 |",
    "|------------|------|",
    "| `e.target` | 이벤트가 발생한 실제 요소 |",
    "| `e.currentTarget` | 핸들러가 바인딩된 요소 |",
    "| `e.preventDefault()` | 기본 동작 방지 (폼 제출, 링크 이동 등) |",
    "| `e.stopPropagation()` | 이벤트 전파(버블링) 중단 |",
    "| `e.nativeEvent` | 원본 브라우저 네이티브 이벤트 |",
    "| `e.type` | 이벤트 타입 문자열 (`'click'`, `'change'` 등) |",
    "",
    "---",
    "",
    "## 이벤트 핸들러 작성 패턴",
    "",
    "### 1. 인라인 함수",
    "```jsx",
    "<button onClick={() => alert('클릭!')}>클릭</button>",
    "```",
    "",
    "### 2. 별도 함수 선언",
    "```jsx",
    "function App() {",
    "  const handleClick = () => {",
    "    alert('클릭!');",
    "  };",
    "",
    "  return <button onClick={handleClick}>클릭</button>;",
    "}",
    "```",
    "",
    "### 3. 파라미터 전달",
    "```jsx",
    "function App() {",
    "  const handleDelete = (id) => {",
    "    console.log(`${id}번 삭제`);",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <button onClick={() => handleDelete(1)}>삭제 1</button>",
    "      <button onClick={() => handleDelete(2)}>삭제 2</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "> `onClick={handleDelete(1)}`로 쓰면 **렌더링 시 즉시 실행**됩니다. 반드시 `() => handleDelete(1)` 형태로 감싸야 합니다.",
    "",
    "### TypeScript 핸들러 타이핑",
    "```tsx",
    "function App(): JSX.Element {",
    "  // 이벤트 객체를 받는 핸들러",
    "  const handleClick = (e: React.MouseEvent<HTMLButtonElement>): void => {",
    "    console.log('클릭 좌표:', e.clientX, e.clientY);",
    "  };",
    "",
    "  // 파라미터를 받는 핸들러",
    "  const handleDelete = (id: number): void => {",
    "    console.log(`${id}번 삭제`);",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <button onClick={handleClick}>클릭</button>",
    "      <button onClick={() => handleDelete(1)}>삭제</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 클릭 이벤트 (onClick)",
    "",
    "### 카운터 예제",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function Counter() {",
    "  const [count, setCount] = useState(0);",
    "",
    "  return (",
    "    <div>",
    "      <p>카운트: {count}</p>",
    "      <button onClick={() => setCount(count + 1)}>+1</button>",
    "      <button onClick={() => setCount(count - 1)}>-1</button>",
    "      <button onClick={() => setCount(0)}>초기화</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState } from 'react';",
    "",
    "function Counter(): JSX.Element {",
    "  const [count, setCount] = useState<number>(0);",
    "",
    "  const handleIncrement = (): void => setCount((prev) => prev + 1);",
    "  const handleDecrement = (): void => setCount((prev) => prev - 1);",
    "  const handleReset = (): void => setCount(0);",
    "",
    "  return (",
    "    <div>",
    "      <p>카운트: {count}</p>",
    "      <button onClick={handleIncrement}>+1</button>",
    "      <button onClick={handleDecrement}>-1</button>",
    "      <button onClick={handleReset}>초기화</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 더블클릭 (onDoubleClick)",
    "```jsx",
    "function App() {",
    "  return (",
    "    <div>",
    "      <button onClick={() => console.log('싱글 클릭')}>클릭</button>",
    "      <button onDoubleClick={() => console.log('더블 클릭')}>더블 클릭</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 폼 이벤트 (onChange, onSubmit)",
    "",
    "### 입력 폼",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function LoginForm() {",
    "  const [form, setForm] = useState({ email: '', password: '' });",
    "",
    "  const handleChange = (e) => {",
    "    const { name, value } = e.target;",
    "    setForm({ ...form, [name]: value });",
    "  };",
    "",
    "  const handleSubmit = (e) => {",
    "    e.preventDefault();",
    "    console.log('로그인:', form);",
    "  };",
    "",
    "  return (",
    "    <form onSubmit={handleSubmit}>",
    "      <input",
    "        name=\"email\"",
    "        type=\"email\"",
    "        value={form.email}",
    "        onChange={handleChange}",
    "        placeholder=\"이메일\"",
    "      />",
    "      <input",
    "        name=\"password\"",
    "        type=\"password\"",
    "        value={form.password}",
    "        onChange={handleChange}",
    "        placeholder=\"비밀번호\"",
    "      />",
    "      <button type=\"submit\">로그인</button>",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState, type FormEvent, type ChangeEvent } from 'react';",
    "",
    "interface FormData {",
    "  email: string;",
    "  password: string;",
    "}",
    "",
    "function LoginForm(): JSX.Element {",
    "  const [form, setForm] = useState<FormData>({ email: '', password: '' });",
    "",
    "  const handleChange = (e: ChangeEvent<HTMLInputElement>): void => {",
    "    const { name, value } = e.target;",
    "    setForm((prev) => ({ ...prev, [name]: value }));",
    "  };",
    "",
    "  const handleSubmit = (e: FormEvent<HTMLFormElement>): void => {",
    "    e.preventDefault();",
    "    console.log('로그인:', form);",
    "  };",
    "",
    "  return (",
    "    <form onSubmit={handleSubmit}>",
    "      <input name=\"email\" type=\"email\" value={form.email}",
    "        onChange={handleChange} placeholder=\"이메일\" />",
    "      <input name=\"password\" type=\"password\" value={form.password}",
    "        onChange={handleChange} placeholder=\"비밀번호\" />",
    "      <button type=\"submit\">로그인</button>",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "### 다양한 입력 타입",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function SurveyForm() {",
    "  const [data, setData] = useState({",
    "    name: '',",
    "    age: '',",
    "    gender: '',",
    "    agree: false,",
    "    color: 'red',",
    "    bio: '',",
    "  });",
    "",
    "  const handleChange = (e) => {",
    "    const { name, value, type, checked } = e.target;",
    "    setData({ ...data, [name]: type === 'checkbox' ? checked : value });",
    "  };",
    "",
    "  const handleSubmit = (e) => {",
    "    e.preventDefault();",
    "    console.log('설문 결과:', data);",
    "  };",
    "",
    "  return (",
    "    <form onSubmit={handleSubmit}>",
    "      {/* 텍스트 */}",
    "      <input name=\"name\" value={data.name} onChange={handleChange} placeholder=\"이름\" />",
    "",
    "      {/* 숫자 */}",
    "      <input name=\"age\" type=\"number\" value={data.age} onChange={handleChange} placeholder=\"나이\" />",
    "",
    "      {/* 라디오 */}",
    "      <label>",
    "        <input type=\"radio\" name=\"gender\" value=\"male\" checked={data.gender === 'male'} onChange={handleChange} />",
    "        남성",
    "      </label>",
    "      <label>",
    "        <input type=\"radio\" name=\"gender\" value=\"female\" checked={data.gender === 'female'} onChange={handleChange} />",
    "        여성",
    "      </label>",
    "",
    "      {/* 체크박스 */}",
    "      <label>",
    "        <input type=\"checkbox\" name=\"agree\" checked={data.agree} onChange={handleChange} />",
    "        동의합니다",
    "      </label>",
    "",
    "      {/* 셀렉트 */}",
    "      <select name=\"color\" value={data.color} onChange={handleChange}>",
    "        <option value=\"red\">빨강</option>",
    "        <option value=\"blue\">파랑</option>",
    "        <option value=\"green\">초록</option>",
    "      </select>",
    "",
    "      {/* 텍스트에리어 */}",
    "      <textarea name=\"bio\" value={data.bio} onChange={handleChange} placeholder=\"자기소개\" />",
    "",
    "      <button type=\"submit\">제출</button>",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState, type ChangeEvent, type FormEvent } from 'react';",
    "",
    "interface SurveyData {",
    "  name: string;",
    "  age: string;",
    "  gender: string;",
    "  agree: boolean;",
    "  color: string;",
    "  bio: string;",
    "}",
    "",
    "function SurveyForm(): JSX.Element {",
    "  const [data, setData] = useState<SurveyData>({",
    "    name: '', age: '', gender: '', agree: false, color: 'red', bio: '',",
    "  });",
    "",
    "  const handleChange = (",
    "    e: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>",
    "  ): void => {",
    "    const target = e.target;",
    "    const value = target instanceof HTMLInputElement && target.type === 'checkbox'",
    "      ? target.checked",
    "      : target.value;",
    "    setData((prev) => ({ ...prev, [target.name]: value }));",
    "  };",
    "",
    "  const handleSubmit = (e: FormEvent<HTMLFormElement>): void => {",
    "    e.preventDefault();",
    "    console.log('설문 결과:', data);",
    "  };",
    "",
    "  return (",
    "    <form onSubmit={handleSubmit}>",
    "      <input name=\"name\" value={data.name} onChange={handleChange} placeholder=\"이름\" />",
    "      <input name=\"age\" type=\"number\" value={data.age} onChange={handleChange} placeholder=\"나이\" />",
    "      <label>",
    "        <input type=\"radio\" name=\"gender\" value=\"male\"",
    "          checked={data.gender === 'male'} onChange={handleChange} /> 남성",
    "      </label>",
    "      <label>",
    "        <input type=\"radio\" name=\"gender\" value=\"female\"",
    "          checked={data.gender === 'female'} onChange={handleChange} /> 여성",
    "      </label>",
    "      <label>",
    "        <input type=\"checkbox\" name=\"agree\"",
    "          checked={data.agree} onChange={handleChange} /> 동의합니다",
    "      </label>",
    "      <select name=\"color\" value={data.color} onChange={handleChange}>",
    "        <option value=\"red\">빨강</option>",
    "        <option value=\"blue\">파랑</option>",
    "        <option value=\"green\">초록</option>",
    "      </select>",
    "      <textarea name=\"bio\" value={data.bio} onChange={handleChange} placeholder=\"자기소개\" />",
    "      <button type=\"submit\">제출</button>",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "### onFocus / onBlur",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function ValidatedInput() {",
    "  const [value, setValue] = useState('');",
    "  const [touched, setTouched] = useState(false);",
    "  const isValid = value.length >= 3;",
    "",
    "  return (",
    "    <div>",
    "      <input",
    "        value={value}",
    "        onChange={(e) => setValue(e.target.value)}",
    "        onFocus={() => console.log('포커스 진입')}",
    "        onBlur={() => setTouched(true)}",
    "        placeholder=\"3자 이상 입력\"",
    "        style={{ border: touched && !isValid ? '2px solid red' : '1px solid #ccc' }}",
    "      />",
    "      {touched && !isValid && <p style={{ color: 'red' }}>3자 이상 입력하세요.</p>}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 키보드 이벤트 (onKeyDown, onKeyUp)",
    "",
    "### JavaScript",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function KeyboardDemo() {",
    "  const [pressedKeys, setPressedKeys] = useState([]);",
    "  const [input, setInput] = useState('');",
    "",
    "  const handleKeyDown = (e) => {",
    "    // Enter로 제출",
    "    if (e.key === 'Enter') {",
    "      alert(`입력: ${input}`);",
    "      setInput('');",
    "      return;",
    "    }",
    "",
    "    // Escape로 초기화",
    "    if (e.key === 'Escape') {",
    "      setInput('');",
    "      return;",
    "    }",
    "",
    "    // 조합 키 (Ctrl+S)",
    "    if (e.ctrlKey && e.key === 's') {",
    "      e.preventDefault();",
    "      alert('저장!');",
    "      return;",
    "    }",
    "",
    "    setPressedKeys((prev) => [...prev.slice(-4), e.key]);",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <input",
    "        value={input}",
    "        onChange={(e) => setInput(e.target.value)}",
    "        onKeyDown={handleKeyDown}",
    "        placeholder=\"Enter: 제출, Esc: 초기화, Ctrl+S: 저장\"",
    "      />",
    "      <p>최근 키: {pressedKeys.join(' → ')}</p>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "import { useState, type KeyboardEvent } from 'react';",
    "",
    "function KeyboardDemo(): JSX.Element {",
    "  const [pressedKeys, setPressedKeys] = useState<string[]>([]);",
    "  const [input, setInput] = useState('');",
    "",
    "  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>): void => {",
    "    if (e.key === 'Enter') {",
    "      alert(`입력: ${input}`);",
    "      setInput('');",
    "      return;",
    "    }",
    "    if (e.key === 'Escape') {",
    "      setInput('');",
    "      return;",
    "    }",
    "    if (e.ctrlKey && e.key === 's') {",
    "      e.preventDefault();",
    "      alert('저장!');",
    "      return;",
    "    }",
    "    setPressedKeys((prev) => [...prev.slice(-4), e.key]);",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <input value={input} onChange={(e) => setInput(e.target.value)}",
    "        onKeyDown={handleKeyDown} placeholder=\"Enter: 제출, Esc: 초기화\" />",
    "      <p>최근 키: {pressedKeys.join(' → ')}</p>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 주요 키 속성",
    "",
    "| 속성 | 설명 | 예시 |",
    "|------|------|------|",
    "| `e.key` | 누른 키의 값 | `'Enter'`, `'a'`, `'Escape'`, `'ArrowUp'` |",
    "| `e.code` | 물리적 키 코드 | `'KeyA'`, `'Space'`, `'ShiftLeft'` |",
    "| `e.ctrlKey` | Ctrl 키 동시 누름 여부 | `true` / `false` |",
    "| `e.shiftKey` | Shift 키 동시 누름 여부 | `true` / `false` |",
    "| `e.altKey` | Alt 키 동시 누름 여부 | `true` / `false` |",
    "| `e.metaKey` | Meta(Cmd/Win) 키 여부 | `true` / `false` |",
    "| `e.repeat` | 키를 누르고 있는 중 | `true` / `false` |",
    "",
    "---",
    "",
    "## 마우스 이벤트",
    "",
    "### 이벤트 종류",
    "",
    "| 이벤트 | 발생 시점 |",
    "|--------|----------|",
    "| `onClick` | 클릭 |",
    "| `onDoubleClick` | 더블 클릭 |",
    "| `onMouseDown` / `onMouseUp` | 버튼 누름 / 뗌 |",
    "| `onMouseEnter` / `onMouseLeave` | 요소 진입 / 이탈 (버블링 없음) |",
    "| `onMouseOver` / `onMouseOut` | 요소 위 / 밖 (버블링 있음) |",
    "| `onMouseMove` | 요소 위에서 이동 |",
    "| `onContextMenu` | 우클릭 (컨텍스트 메뉴) |",
    "",
    "### 마우스 위치 추적",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function MouseTracker() {",
    "  const [pos, setPos] = useState({ x: 0, y: 0 });",
    "  const [isOver, setIsOver] = useState(false);",
    "",
    "  return (",
    "    <div",
    "      onMouseMove={(e) => setPos({ x: e.clientX, y: e.clientY })}",
    "      onMouseEnter={() => setIsOver(true)}",
    "      onMouseLeave={() => setIsOver(false)}",
    "      style={{",
    "        width: '100%', height: '200px',",
    "        background: isOver ? '#e8f4fd' : '#f5f5f5',",
    "        display: 'flex', alignItems: 'center', justifyContent: 'center',",
    "        border: '2px dashed #3498db', borderRadius: '8px',",
    "        cursor: 'crosshair',",
    "      }}",
    "    >",
    "      <p>{isOver ? `마우스 위치: (${pos.x}, ${pos.y})` : '마우스를 올려보세요'}</p>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState, type MouseEvent } from 'react';",
    "",
    "interface Position {",
    "  x: number;",
    "  y: number;",
    "}",
    "",
    "function MouseTracker(): JSX.Element {",
    "  const [pos, setPos] = useState<Position>({ x: 0, y: 0 });",
    "  const [isOver, setIsOver] = useState(false);",
    "",
    "  const handleMouseMove = (e: MouseEvent<HTMLDivElement>): void => {",
    "    setPos({ x: e.clientX, y: e.clientY });",
    "  };",
    "",
    "  return (",
    "    <div",
    "      onMouseMove={handleMouseMove}",
    "      onMouseEnter={() => setIsOver(true)}",
    "      onMouseLeave={() => setIsOver(false)}",
    "      style={{",
    "        width: '100%', height: '200px',",
    "        background: isOver ? '#e8f4fd' : '#f5f5f5',",
    "        display: 'flex', alignItems: 'center', justifyContent: 'center',",
    "        border: '2px dashed #3498db', borderRadius: '8px',",
    "        cursor: 'crosshair',",
    "      }}",
    "    >",
    "      <p>{isOver ? `마우스 위치: (${pos.x}, ${pos.y})` : '마우스를 올려보세요'}</p>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 우클릭 메뉴 커스텀",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function ContextMenuDemo() {",
    "  const [menu, setMenu] = useState({ visible: false, x: 0, y: 0 });",
    "",
    "  const handleContextMenu = (e) => {",
    "    e.preventDefault();",
    "    setMenu({ visible: true, x: e.clientX, y: e.clientY });",
    "  };",
    "",
    "  return (",
    "    <div",
    "      onContextMenu={handleContextMenu}",
    "      onClick={() => setMenu({ ...menu, visible: false })}",
    "      style={{ width: '100%', height: '200px', background: '#f0f0f0', position: 'relative' }}",
    "    >",
    "      <p>우클릭해 보세요</p>",
    "      {menu.visible && (",
    "        <div style={{",
    "          position: 'fixed', left: menu.x, top: menu.y,",
    "          background: 'white', boxShadow: '0 2px 8px rgba(0,0,0,0.2)',",
    "          borderRadius: '8px', padding: '8px 0', minWidth: '150px', zIndex: 1000,",
    "        }}>",
    "          <div style={{ padding: '8px 16px', cursor: 'pointer' }}>복사</div>",
    "          <div style={{ padding: '8px 16px', cursor: 'pointer' }}>붙여넣기</div>",
    "          <div style={{ padding: '8px 16px', cursor: 'pointer', color: 'red' }}>삭제</div>",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 드래그 & 드롭 이벤트",
    "",
    "| 이벤트 | 발생 시점 |",
    "|--------|----------|",
    "| `onDrag` | 드래그 중 |",
    "| `onDragStart` | 드래그 시작 |",
    "| `onDragEnd` | 드래그 종료 |",
    "| `onDragOver` | 드롭 영역 위에 있을 때 |",
    "| `onDragEnter` / `onDragLeave` | 드롭 영역 진입 / 이탈 |",
    "| `onDrop` | 드롭 시 |",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function DragDropDemo() {",
    "  const [items, setItems] = useState(['항목 A', '항목 B', '항목 C']);",
    "  const [dragIdx, setDragIdx] = useState(null);",
    "",
    "  const handleDragStart = (idx) => {",
    "    setDragIdx(idx);",
    "  };",
    "",
    "  const handleDrop = (dropIdx) => {",
    "    if (dragIdx === null) return;",
    "    const updated = [...items];",
    "    const [dragged] = updated.splice(dragIdx, 1);",
    "    updated.splice(dropIdx, 0, dragged);",
    "    setItems(updated);",
    "    setDragIdx(null);",
    "  };",
    "",
    "  return (",
    "    <ul style={{ listStyle: 'none', padding: 0 }}>",
    "      {items.map((item, idx) => (",
    "        <li",
    "          key={item}",
    "          draggable",
    "          onDragStart={() => handleDragStart(idx)}",
    "          onDragOver={(e) => e.preventDefault()}",
    "          onDrop={() => handleDrop(idx)}",
    "          style={{",
    "            padding: '12px 16px', margin: '4px 0',",
    "            background: dragIdx === idx ? '#d5f5e3' : '#f8f9fa',",
    "            border: '1px solid #ddd', borderRadius: '8px',",
    "            cursor: 'grab',",
    "          }}",
    "        >",
    "          ☰ {item}",
    "        </li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState, type DragEvent } from 'react';",
    "",
    "function DragDropDemo(): JSX.Element {",
    "  const [items, setItems] = useState<string[]>(['항목 A', '항목 B', '항목 C']);",
    "  const [dragIdx, setDragIdx] = useState<number | null>(null);",
    "",
    "  const handleDragStart = (idx: number): void => {",
    "    setDragIdx(idx);",
    "  };",
    "",
    "  const handleDrop = (dropIdx: number): void => {",
    "    if (dragIdx === null) return;",
    "    const updated = [...items];",
    "    const [dragged] = updated.splice(dragIdx, 1);",
    "    updated.splice(dropIdx, 0, dragged);",
    "    setItems(updated);",
    "    setDragIdx(null);",
    "  };",
    "",
    "  const handleDragOver = (e: DragEvent<HTMLLIElement>): void => {",
    "    e.preventDefault();",
    "  };",
    "",
    "  return (",
    "    <ul style={{ listStyle: 'none', padding: 0 }}>",
    "      {items.map((item, idx) => (",
    "        <li key={item} draggable",
    "          onDragStart={() => handleDragStart(idx)}",
    "          onDragOver={handleDragOver}",
    "          onDrop={() => handleDrop(idx)}",
    "          style={{",
    "            padding: '12px 16px', margin: '4px 0',",
    "            background: dragIdx === idx ? '#d5f5e3' : '#f8f9fa',",
    "            border: '1px solid #ddd', borderRadius: '8px', cursor: 'grab',",
    "          }}",
    "        >",
    "          ☰ {item}",
    "        </li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 스크롤·포커스·클립보드 이벤트",
    "",
    "| 이벤트 | 발생 시점 | TypeScript 타입 |",
    "|--------|----------|----------------|",
    "| `onScroll` | 스크롤 시 | `UIEvent<HTMLDivElement>` |",
    "| `onFocus` | 포커스 진입 | `FocusEvent<HTMLInputElement>` |",
    "| `onBlur` | 포커스 이탈 | `FocusEvent<HTMLInputElement>` |",
    "| `onCopy` | 복사 | `ClipboardEvent<HTMLDivElement>` |",
    "| `onPaste` | 붙여넣기 | `ClipboardEvent<HTMLInputElement>` |",
    "| `onCut` | 잘라내기 | `ClipboardEvent<HTMLInputElement>` |",
    "",
    "### 스크롤 위치 감지",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function ScrollTracker() {",
    "  const [scrollTop, setScrollTop] = useState(0);",
    "",
    "  return (",
    "    <div",
    "      onScroll={(e) => setScrollTop(e.currentTarget.scrollTop)}",
    "      style={{ height: '200px', overflow: 'auto', border: '1px solid #ddd' }}",
    "    >",
    "      <div style={{",
    "        position: 'sticky', top: 0, background: '#3498db',",
    "        color: 'white', padding: '8px',",
    "      }}>",
    "        스크롤: {Math.round(scrollTop)}px",
    "      </div>",
    "      <div style={{ height: '800px', padding: '16px' }}>",
    "        <p>스크롤해 보세요</p>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 이벤트 전파 (버블링 & 캡처링)",
    "",
    "### 이벤트 버블링",
    "",
    "이벤트는 **자식 → 부모** 순서로 전파(버블링)됩니다.",
    "",
    "```jsx",
    "function BubbleDemo() {",
    "  return (",
    "    <div onClick={() => console.log('div 클릭')}",
    "      style={{ padding: '20px', background: '#f0f0f0' }}>",
    "      <button onClick={() => console.log('button 클릭')}",
    "        style={{ padding: '10px' }}>",
    "        클릭하면?",
    "      </button>",
    "    </div>",
    "  );",
    "  // 버튼 클릭 시 출력:",
    "  // \"button 클릭\"",
    "  // \"div 클릭\" (버블링)",
    "}",
    "```",
    "",
    "### stopPropagation으로 전파 중단",
    "```jsx",
    "function StopPropDemo() {",
    "  return (",
    "    <div onClick={() => console.log('div 클릭')}",
    "      style={{ padding: '20px', background: '#f0f0f0' }}>",
    "      <button onClick={(e) => {",
    "        e.stopPropagation(); // 버블링 중단",
    "        console.log('button만 클릭');",
    "      }}>",
    "        버블링 중단",
    "      </button>",
    "    </div>",
    "  );",
    "  // 버튼 클릭 시 출력:",
    "  // \"button만 클릭\" (div는 출력 안 됨)",
    "}",
    "```",
    "",
    "### 캡처 단계 이벤트",
    "",
    "이벤트 이름에 `Capture`를 붙이면 **캡처 단계**(부모 → 자식)에서 처리합니다.",
    "",
    "```jsx",
    "function CaptureDemo() {",
    "  return (",
    "    <div onClickCapture={() => console.log('1. div 캡처')}>",
    "      <button onClick={() => console.log('2. button 클릭')}>",
    "        클릭",
    "      </button>",
    "    </div>",
    "  );",
    "  // 출력 순서:",
    "  // \"1. div 캡처\"   (캡처 단계, 위 → 아래)",
    "  // \"2. button 클릭\" (버블 단계)",
    "}",
    "```",
    "",
    "### 전파 흐름 정리",
    "",
    "| 단계 | 방향 | React 이벤트 | 설명 |",
    "|------|------|-------------|------|",
    "| 캡처 | 부모 → 자식 | `onClickCapture` | 최상위부터 타깃까지 |",
    "| 타깃 | 이벤트 발생 요소 | `onClick` | 실제 클릭된 요소 |",
    "| 버블 | 자식 → 부모 | `onClick` | 타깃에서 최상위까지 |",
    "",
    "---",
    "",
    "## 이벤트 핸들러를 Props로 전달",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function Button({ onClick, variant = 'primary', children }) {",
    "  const colors = {",
    "    primary: '#3498db',",
    "    danger: '#e74c3c',",
    "    success: '#2ecc71',",
    "  };",
    "",
    "  return (",
    "    <button onClick={onClick} style={{",
    "      background: colors[variant], color: 'white',",
    "      border: 'none', padding: '10px 20px',",
    "      borderRadius: '8px', cursor: 'pointer', margin: '4px',",
    "    }}>",
    "      {children}",
    "    </button>",
    "  );",
    "}",
    "",
    "function App() {",
    "  const [message, setMessage] = useState('');",
    "",
    "  return (",
    "    <div>",
    "      <Button onClick={() => setMessage('저장됨!')} variant=\"primary\">저장</Button>",
    "      <Button onClick={() => setMessage('삭제됨!')} variant=\"danger\">삭제</Button>",
    "      <Button onClick={() => setMessage('완료!')} variant=\"success\">완료</Button>",
    "      {message && <p>{message}</p>}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState, type ReactNode } from 'react';",
    "",
    "type Variant = 'primary' | 'danger' | 'success';",
    "",
    "interface ButtonProps {",
    "  onClick: () => void;",
    "  variant?: Variant;",
    "  children: ReactNode;",
    "}",
    "",
    "function Button({ onClick, variant = 'primary', children }: ButtonProps): JSX.Element {",
    "  const colors: Record<Variant, string> = {",
    "    primary: '#3498db',",
    "    danger: '#e74c3c',",
    "    success: '#2ecc71',",
    "  };",
    "",
    "  return (",
    "    <button onClick={onClick} style={{",
    "      background: colors[variant], color: 'white',",
    "      border: 'none', padding: '10px 20px',",
    "      borderRadius: '8px', cursor: 'pointer', margin: '4px',",
    "    }}>",
    "      {children}",
    "    </button>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## TypeScript 이벤트 타입 정리",
    "",
    "| 이벤트 | TypeScript 타입 | 사용 요소 |",
    "|--------|----------------|----------|",
    "| `onClick` | `MouseEvent<HTMLButtonElement>` | button, div 등 |",
    "| `onChange` | `ChangeEvent<HTMLInputElement>` | input, select, textarea |",
    "| `onSubmit` | `FormEvent<HTMLFormElement>` | form |",
    "| `onKeyDown` / `onKeyUp` | `KeyboardEvent<HTMLInputElement>` | input, div 등 |",
    "| `onMouseMove` | `MouseEvent<HTMLDivElement>` | div 등 |",
    "| `onFocus` / `onBlur` | `FocusEvent<HTMLInputElement>` | input 등 |",
    "| `onScroll` | `UIEvent<HTMLDivElement>` | div 등 |",
    "| `onDragStart` | `DragEvent<HTMLLIElement>` | li, div 등 |",
    "| `onDrop` | `DragEvent<HTMLLIElement>` | li, div 등 |",
    "| `onCopy` / `onPaste` | `ClipboardEvent<HTMLDivElement>` | div, input 등 |",
    "| `onContextMenu` | `MouseEvent<HTMLDivElement>` | div 등 |",
    "",
    "### 이벤트 타입 import 패턴",
    "```tsx",
    "// 방법 1: React 네임스페이스",
    "const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {};",
    "",
    "// 방법 2: named import (권장)",
    "import { type MouseEvent, type ChangeEvent, type FormEvent } from 'react';",
    "const handleClick = (e: MouseEvent<HTMLButtonElement>) => {};",
    "```",
    "",
    "---",
    "",
    "## 이벤트 전체 요약",
    "",
    "| 개념 | 핵심 |",
    "|------|------|",
    "| SyntheticEvent | 크로스 브라우저 호환 이벤트 래퍼 |",
    "| camelCase | `onClick`, `onChange`, `onKeyDown` |",
    "| preventDefault | 기본 동작 방지 (폼 제출, 링크 이동) |",
    "| stopPropagation | 이벤트 버블링 중단 |",
    "| 핸들러 전달 | `{handleClick}` (함수 참조, 호출 아님) |",
    "| 파라미터 | `() => handleDelete(id)` 형태로 감싸기 |",
    "| 버블링 | 자식 → 부모 전파 (기본) |",
    "| 캡처링 | `onClickCapture` 로 부모 → 자식 전파 |",
    "",
    "---",
    "",
    "### 요약",
    "React는 SyntheticEvent로 브라우저 이벤트를 래핑하여 일관된 API를 제공합니다. camelCase 이벤트 이름(`onClick`, `onChange`)에 함수 참조를 전달하고, `e.preventDefault()`로 기본 동작을, `e.stopPropagation()`으로 이벤트 전파를 제어합니다. TypeScript에서는 `MouseEvent<HTMLButtonElement>`, `ChangeEvent<HTMLInputElement>` 등으로 정확한 타이핑이 가능합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
