<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "react-props",
  title: "React Props 완벽 가이드",
  date: "2026-03-03",
  summary: "Props의 개념, 전달 방법, 구조 분해, 기본값, children, PropTypes, TypeScript 타이핑, 콜백 Props, 조건부 렌더링까지 React Props의 모든 것을 예제와 함께 정리합니다.",
  category: "Technology/React",
  tags: ["react","props","component","typescript","children","proptypes","callback","destructuring"],
  content: [
    "## 한 줄 요약",
    "**Props(Properties)**는 부모 컴포넌트가 자식 컴포넌트에 데이터를 전달하는 React의 핵심 메커니즘이며, **읽기 전용**입니다.",
    "",
    "---",
    "",
    "## 공식 문서",
    "",
    "| 항목 | URL |",
    "|------|-----|",
    "| Props 전달하기 | [react.dev/learn/passing-props-to-a-component](https://react.dev/learn/passing-props-to-a-component) |",
    "| 컴포넌트 간 데이터 공유 | [react.dev/learn/sharing-state-between-components](https://react.dev/learn/sharing-state-between-components) |",
    "",
    "---",
    "",
    "## Props란?",
    "",
    "Props는 컴포넌트에 전달되는 **입력값**입니다. HTML 속성처럼 JSX에 작성하면 자식 컴포넌트에서 객체로 받을 수 있습니다.",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| **부모 → 자식** | 데이터는 항상 위에서 아래로 흐름 (단방향 데이터 흐름) |",
    "| **읽기 전용** | 자식에서 props를 직접 수정하면 안 됨 |",
    "| **모든 타입 가능** | 문자열, 숫자, 배열, 객체, 함수, JSX 모두 전달 가능 |",
    "| **재사용성** | 같은 컴포넌트에 다른 props를 전달해 재사용 |",
    "",
    "---",
    "",
    "## 기본 Props 전달",
    "",
    "### JavaScript",
    "```jsx",
    "function Greeting({ name }) {",
    "  return <h1>안녕하세요, {name}님!</h1>;",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <div>",
    "      <Greeting name=\"하루\" />",
    "      <Greeting name=\"철수\" />",
    "      <Greeting name=\"영희\" />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "interface GreetingProps {",
    "  name: string;",
    "}",
    "",
    "function Greeting({ name }: GreetingProps) {",
    "  return <h1>안녕하세요, {name}님!</h1>;",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <div>",
    "      <Greeting name=\"하루\" />",
    "      <Greeting name=\"철수\" />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## Props 전달 방식",
    "",
    "### props 객체로 받기",
    "```jsx",
    "function UserCard(props) {",
    "  return (",
    "    <div>",
    "      <h3>{props.name}</h3>",
    "      <p>나이: {props.age}세</p>",
    "      <p>이메일: {props.email}</p>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 구조 분해 할당 (권장)",
    "```jsx",
    "function UserCard({ name, age, email }) {",
    "  return (",
    "    <div>",
    "      <h3>{name}</h3>",
    "      <p>나이: {age}세</p>",
    "      <p>이메일: {email}</p>",
    "    </div>",
    "  );",
    "}",
    "",
    "// 사용",
    "<UserCard name=\"하루\" age={25} email=\"haru@test.com\" />",
    "```",
    "",
    "> 구조 분해 할당을 사용하면 어떤 props를 받는지 한눈에 파악할 수 있어 **가독성**이 좋습니다.",
    "",
    "---",
    "",
    "## 다양한 타입의 Props",
    "",
    "### JavaScript",
    "```jsx",
    "function ProductCard({ name, price, tags, onSale, image, onClick }) {",
    "  return (",
    "    <div onClick={onClick} style={{ border: '1px solid #ddd', padding: '16px', borderRadius: '8px' }}>",
    "      <img src={image} alt={name} style={{ width: '100%', borderRadius: '8px' }} />",
    "      <h3>{name} {onSale && <span style={{ color: 'red' }}>SALE</span>}</h3>",
    "      <p style={{ fontSize: '20px', fontWeight: 'bold' }}>{price.toLocaleString()}원</p>",
    "      <div>",
    "        {tags.map((tag, i) => (",
    "          <span key={i} style={{",
    "            background: '#e0e0e0', padding: '2px 8px',",
    "            borderRadius: '4px', marginRight: '4px', fontSize: '12px'",
    "          }}>",
    "            #{tag}",
    "          </span>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <ProductCard",
    "      name=\"노트북\"",
    "      price={1500000}",
    "      tags={['전자기기', '할인', '인기']}",
    "      onSale={true}",
    "      image=\"https://via.placeholder.com/300\"",
    "      onClick={() => alert('상품 클릭!')}",
    "    />",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "interface ProductCardProps {",
    "  name: string;",
    "  price: number;",
    "  tags: string[];",
    "  onSale: boolean;",
    "  image: string;",
    "  onClick: () => void;",
    "}",
    "",
    "function ProductCard({ name, price, tags, onSale, image, onClick }: ProductCardProps) {",
    "  return (",
    "    <div onClick={onClick} style={{ border: '1px solid #ddd', padding: '16px', borderRadius: '8px' }}>",
    "      <img src={image} alt={name} style={{ width: '100%', borderRadius: '8px' }} />",
    "      <h3>{name} {onSale && <span style={{ color: 'red' }}>SALE</span>}</h3>",
    "      <p style={{ fontSize: '20px', fontWeight: 'bold' }}>{price.toLocaleString()}원</p>",
    "      <div>",
    "        {tags.map((tag, i) => (",
    "          <span key={i} style={{",
    "            background: '#e0e0e0', padding: '2px 8px',",
    "            borderRadius: '4px', marginRight: '4px', fontSize: '12px'",
    "          }}>",
    "            #{tag}",
    "          </span>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### Props 타입 정리",
    "",
    "| 타입 | JSX 전달 | TypeScript 타입 |",
    "|------|----------|-----------------|",
    "| 문자열 | `name=\"하루\"` | `name: string` |",
    "| 숫자 | `age={25}` | `age: number` |",
    "| 불리언 | `isActive={true}` 또는 `isActive` | `isActive: boolean` |",
    "| 배열 | `items={[1, 2, 3]}` | `items: number[]` |",
    "| 객체 | `user={{ name: '하루' }}` | `user: { name: string }` |",
    "| 함수 | `onClick={() => {}}` | `onClick: () => void` |",
    "| JSX | `icon={<Icon />}` | `icon: React.ReactNode` |",
    "",
    "---",
    "",
    "## 기본값 (Default Props)",
    "",
    "### 구조 분해 기본값 (권장)",
    "```jsx",
    "function Button({ text = '클릭', color = '#3498db', size = 'medium' }) {",
    "  const sizes = { small: '10px 16px', medium: '12px 24px', large: '16px 32px' };",
    "  return (",
    "    <button style={{",
    "      background: color,",
    "      color: 'white',",
    "      padding: sizes[size],",
    "      border: 'none',",
    "      borderRadius: '8px',",
    "      cursor: 'pointer',",
    "    }}>",
    "      {text}",
    "    </button>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <div>",
    "      <Button />                           {/* 기본값 사용 */}",
    "      <Button text=\"저장\" color=\"#2ecc71\" /> {/* 일부 덮어쓰기 */}",
    "      <Button text=\"삭제\" color=\"#e74c3c\" size=\"large\" />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript에서 기본값",
    "```tsx",
    "interface ButtonProps {",
    "  text?: string;      // optional",
    "  color?: string;",
    "  size?: 'small' | 'medium' | 'large';",
    "}",
    "",
    "function Button({ text = '클릭', color = '#3498db', size = 'medium' }: ButtonProps) {",
    "  const sizes: Record<string, string> = {",
    "    small: '10px 16px',",
    "    medium: '12px 24px',",
    "    large: '16px 32px',",
    "  };",
    "  return (",
    "    <button style={{",
    "      background: color,",
    "      color: 'white',",
    "      padding: sizes[size],",
    "      border: 'none',",
    "      borderRadius: '8px',",
    "      cursor: 'pointer',",
    "    }}>",
    "      {text}",
    "    </button>",
    "  );",
    "}",
    "```",
    "",
    "> `?`로 optional prop을 선언하고 구조 분해에서 기본값을 설정하는 것이 TypeScript에서의 표준 패턴입니다.",
    "",
    "---",
    "",
    "## children Props",
    "",
    "컴포넌트 태그 사이에 넣은 내용은 자동으로 `children` prop이 됩니다.",
    "",
    "### JavaScript",
    "```jsx",
    "function Card({ title, children }) {",
    "  return (",
    "    <div style={{",
    "      border: '2px solid #3498db',",
    "      borderRadius: '12px',",
    "      padding: '20px',",
    "      margin: '12px',",
    "    }}>",
    "      <h2 style={{ color: '#3498db', marginTop: 0 }}>{title}</h2>",
    "      <div>{children}</div>",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <div>",
    "      <Card title=\"공지사항\">",
    "        <p>서버 점검: 3월 5일 02:00~06:00</p>",
    "        <p>이용에 불편을 드려 죄송합니다.</p>",
    "      </Card>",
    "      <Card title=\"오늘의 할 일\">",
    "        <ul>",
    "          <li>React 공부</li>",
    "          <li>운동</li>",
    "        </ul>",
    "      </Card>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "import type { ReactNode } from 'react';",
    "",
    "interface CardProps {",
    "  title: string;",
    "  children: ReactNode;",
    "}",
    "",
    "function Card({ title, children }: CardProps) {",
    "  return (",
    "    <div style={{",
    "      border: '2px solid #3498db',",
    "      borderRadius: '12px',",
    "      padding: '20px',",
    "      margin: '12px',",
    "    }}>",
    "      <h2 style={{ color: '#3498db', marginTop: 0 }}>{title}</h2>",
    "      <div>{children}</div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### children 타입 종류",
    "",
    "| 타입 | 설명 | 예시 |",
    "|------|------|------|",
    "| `ReactNode` | 모든 렌더링 가능 타입 (가장 유연) | JSX, 문자열, 숫자, null |",
    "| `ReactElement` | JSX 요소만 허용 | `<div>`, `<Component />` |",
    "| `string` | 문자열만 허용 | `\"텍스트\"` |",
    "| `React.FC<Props>` | children을 자동 포함 (비권장) | — |",
    "",
    "---",
    "",
    "## React.FC 타입 심층 분석",
    "",
    "`React.FC`(또는 `React.FunctionComponent`)는 함수 컴포넌트의 **타입을 지정**하는 TypeScript 제네릭 타입입니다.",
    "",
    "### React.FC 기본 사용법",
    "",
    "```tsx",
    "import type { FC } from 'react';",
    "",
    "interface GreetingProps {",
    "  name: string;",
    "  age: number;",
    "}",
    "",
    "// React.FC를 사용하는 방식",
    "const Greeting: FC<GreetingProps> = ({ name, age }) => {",
    "  return (",
    "    <div>",
    "      <h1>안녕하세요, {name}님!</h1>",
    "      <p>나이: {age}세</p>",
    "    </div>",
    "  );",
    "};",
    "```",
    "",
    "### React.FC를 사용하지 않는 방식 (권장)",
    "",
    "```tsx",
    "interface GreetingProps {",
    "  name: string;",
    "  age: number;",
    "}",
    "",
    "// 함수 매개변수에 직접 타입 지정",
    "function Greeting({ name, age }: GreetingProps) {",
    "  return (",
    "    <div>",
    "      <h1>안녕하세요, {name}님!</h1>",
    "      <p>나이: {age}세</p>",
    "    </div>",
    "  );",
    "}",
    "",
    "// 화살표 함수도 동일",
    "const Greeting2 = ({ name, age }: GreetingProps) => {",
    "  return <p>{name}, {age}세</p>;",
    "};",
    "```",
    "",
    "### React.FC의 내부 구조",
    "",
    "React 18 이전의 `React.FC` 타입 정의를 단순화하면 다음과 같습니다.",
    "",
    "```tsx",
    "type FC<P = {}> = (props: P & { children?: ReactNode }) => ReactElement | null;",
    "```",
    "",
    "즉 `FC<Props>`는:",
    "- Props를 받아서 `ReactElement | null`을 반환하는 함수 타입",
    "- **React 18 이전**: `children`을 자동으로 포함 → 의도하지 않은 children 전달 가능",
    "- **React 18 이후**: `children` 자동 포함이 **제거됨** → 명시적으로 선언해야 함",
    "",
    "### React.FC를 사용할 때와 하지 않을 때",
    "",
    "| 비교 항목 | `React.FC<Props>` | 직접 타입 지정 |",
    "|-----------|-------------------|---------------|",
    "| 반환 타입 | 자동 추론 (`ReactElement \\| null`) | 자동 추론 (더 유연) |",
    "| children | React 18+에서는 명시 필요 | 항상 명시 필요 |",
    "| 제네릭 컴포넌트 | ❌ 사용 불가 | ✅ 가능 |",
    "| 기본값 (defaultProps) | 타입 추론 안 됨 | 정상 동작 |",
    "| 함수 선언식 | ❌ (화살표 함수만) | ✅ 둘 다 가능 |",
    "| 코드 간결성 | 약간 장황 | 간결 |",
    "",
    "### React.FC의 문제점 — 제네릭 컴포넌트",
    "",
    "제네릭 컴포넌트를 만들 때 `React.FC`는 사용할 수 없습니다.",
    "",
    "```tsx",
    "// ❌ FC로는 제네릭 컴포넌트를 만들 수 없음",
    "// const List: FC<ListProps<T>> = ... // T를 어디에 선언?",
    "",
    "// ✅ 직접 타입 지정하면 제네릭 가능",
    "interface ListProps<T> {",
    "  items: T[];",
    "  renderItem: (item: T) => ReactNode;",
    "}",
    "",
    "function List<T>({ items, renderItem }: ListProps<T>) {",
    "  return (",
    "    <ul>",
    "      {items.map((item, i) => (",
    "        <li key={i}>{renderItem(item)}</li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "",
    "// 사용 — T가 자동 추론됨",
    "function App() {",
    "  return (",
    "    <div>",
    "      <List",
    "        items={['React', 'Vue', 'Angular']}",
    "        renderItem={(item) => <strong>{item}</strong>}",
    "      />",
    "      <List",
    "        items={[1, 2, 3]}",
    "        renderItem={(n) => <span>{n * 10}</span>}",
    "      />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### React.FC의 문제점 — defaultProps 타입 추론",
    "",
    "```tsx",
    "// ❌ FC + defaultProps → 타입 추론 불일치",
    "interface ButtonProps {",
    "  text?: string;",
    "  color?: string;",
    "}",
    "",
    "const Button: FC<ButtonProps> = ({ text, color }) => {",
    "  // text와 color가 여전히 string | undefined로 추론됨",
    "  return <button style={{ color }}>{text}</button>;",
    "};",
    "Button.defaultProps = { text: '클릭', color: 'blue' };",
    "",
    "// ✅ 구조 분해 기본값이면 정확히 string으로 추론됨",
    "function Button2({ text = '클릭', color = 'blue' }: ButtonProps) {",
    "  // text: string, color: string (undefined 아님!)",
    "  return <button style={{ color }}>{text}</button>;",
    "}",
    "```",
    "",
    "### React.FC의 장점",
    "",
    "그럼에도 `React.FC`를 사용하는 이유가 있습니다.",
    "",
    "```tsx",
    "// 1. 반환 타입을 명시적으로 제한 — 실수 방지",
    "const Good: FC<Props> = ({ name }) => {",
    "  return <div>{name}</div>;  // ✅ ReactElement 반환",
    "};",
    "",
    "// FC 없이는 문자열, 숫자 등도 반환 가능 (의도하지 않을 수 있음)",
    "function MaybeWrong({ name }: Props) {",
    "  return name;  // string 반환 — 에러 아님, 하지만 의도한 건가?",
    "}",
    "",
    "// 2. displayName 타입 지원",
    "const MyComponent: FC<Props> = (props) => <div />;",
    "MyComponent.displayName = 'MyComponent';  // ✅ 타입 안전",
    "```",
    "",
    "### 결론 — 어떤 방식을 쓸까?",
    "",
    "```tsx",
    "// ✅ 권장: 직접 타입 지정 (React 공식 문서도 이 방식 사용)",
    "interface CardProps {",
    "  title: string;",
    "  children: ReactNode;",
    "}",
    "",
    "function Card({ title, children }: CardProps) {",
    "  return (",
    "    <div>",
    "      <h2>{title}</h2>",
    "      {children}",
    "    </div>",
    "  );",
    "}",
    "",
    "// ⚠️ FC도 사용 가능 — 팀 컨벤션에 따라 결정",
    "const Card2: FC<CardProps> = ({ title, children }) => {",
    "  return (",
    "    <div>",
    "      <h2>{title}</h2>",
    "      {children}",
    "    </div>",
    "  );",
    "};",
    "```",
    "",
    "| 상황 | 권장 방식 |",
    "|------|----------|",
    "| 일반 컴포넌트 | **직접 타입 지정** (간결, 유연) |",
    "| 제네릭 컴포넌트 | **직접 타입 지정** (FC 불가) |",
    "| 팀에서 FC 컨벤션 사용 시 | **FC 사용** (일관성) |",
    "| React 공식 문서 스타일 | **직접 타입 지정** |",
    "",
    "> React 공식 문서, Create React App 템플릿, Next.js 모두 **직접 타입 지정 방식**을 사용합니다. `React.FC`는 틀린 것이 아니라 **취향/컨벤션의 차이**입니다.",
    "",
    "---",
    "",
    "## 콜백 Props (자식 → 부모 통신)",
    "",
    "자식이 부모의 상태를 변경하려면 **콜백 함수를 props로** 전달합니다.",
    "",
    "### JavaScript",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function SearchBar({ value, onChange, onSearch }) {",
    "  return (",
    "    <div style={{ display: 'flex', gap: '8px' }}>",
    "      <input",
    "        value={value}",
    "        onChange={(e) => onChange(e.target.value)}",
    "        placeholder=\"검색어 입력\"",
    "        style={{ padding: '8px', borderRadius: '4px', border: '1px solid #ccc', flex: 1 }}",
    "      />",
    "      <button onClick={onSearch} style={{",
    "        padding: '8px 16px', background: '#3498db',",
    "        color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer'",
    "      }}>",
    "        검색",
    "      </button>",
    "    </div>",
    "  );",
    "}",
    "",
    "function SearchResult({ results }) {",
    "  if (results.length === 0) return <p>검색 결과가 없습니다.</p>;",
    "  return (",
    "    <ul>",
    "      {results.map((item, i) => <li key={i}>{item}</li>)}",
    "    </ul>",
    "  );",
    "}",
    "",
    "function App() {",
    "  const [query, setQuery] = useState('');",
    "  const [results, setResults] = useState([]);",
    "  const allItems = ['React', 'Vue', 'Angular', 'Svelte', 'Next.js', 'Nuxt.js'];",
    "",
    "  const handleSearch = () => {",
    "    const filtered = allItems.filter((item) =>",
    "      item.toLowerCase().includes(query.toLowerCase())",
    "    );",
    "    setResults(filtered);",
    "  };",
    "",
    "  return (",
    "    <div style={{ padding: '20px', maxWidth: '400px' }}>",
    "      <h2>프레임워크 검색</h2>",
    "      <SearchBar value={query} onChange={setQuery} onSearch={handleSearch} />",
    "      <SearchResult results={results} />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "import { useState } from 'react';",
    "",
    "interface SearchBarProps {",
    "  value: string;",
    "  onChange: (value: string) => void;",
    "  onSearch: () => void;",
    "}",
    "",
    "function SearchBar({ value, onChange, onSearch }: SearchBarProps) {",
    "  return (",
    "    <div style={{ display: 'flex', gap: '8px' }}>",
    "      <input",
    "        value={value}",
    "        onChange={(e) => onChange(e.target.value)}",
    "        placeholder=\"검색어 입력\"",
    "        style={{ padding: '8px', borderRadius: '4px', border: '1px solid #ccc', flex: 1 }}",
    "      />",
    "      <button onClick={onSearch} style={{",
    "        padding: '8px 16px', background: '#3498db',",
    "        color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer'",
    "      }}>",
    "        검색",
    "      </button>",
    "    </div>",
    "  );",
    "}",
    "",
    "interface SearchResultProps {",
    "  results: string[];",
    "}",
    "",
    "function SearchResult({ results }: SearchResultProps) {",
    "  if (results.length === 0) return <p>검색 결과가 없습니다.</p>;",
    "  return (",
    "    <ul>",
    "      {results.map((item, i) => <li key={i}>{item}</li>)}",
    "    </ul>",
    "  );",
    "}",
    "",
    "function App() {",
    "  const [query, setQuery] = useState('');",
    "  const [results, setResults] = useState<string[]>([]);",
    "  const allItems: string[] = ['React', 'Vue', 'Angular', 'Svelte', 'Next.js', 'Nuxt.js'];",
    "",
    "  const handleSearch = (): void => {",
    "    const filtered = allItems.filter((item) =>",
    "      item.toLowerCase().includes(query.toLowerCase())",
    "    );",
    "    setResults(filtered);",
    "  };",
    "",
    "  return (",
    "    <div style={{ padding: '20px', maxWidth: '400px' }}>",
    "      <h2>프레임워크 검색</h2>",
    "      <SearchBar value={query} onChange={setQuery} onSearch={handleSearch} />",
    "      <SearchResult results={results} />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "> 자식 → 부모 통신은 항상 **부모가 콜백 함수를 props로 내려주고**, 자식이 그 함수를 호출하는 패턴입니다.",
    "",
    "---",
    "",
    "## Props 스프레드 연산자",
    "",
    "객체의 모든 속성을 한 번에 props로 전달할 수 있습니다.",
    "",
    "### JavaScript",
    "```jsx",
    "function Profile({ name, age, email, role }) {",
    "  return (",
    "    <div>",
    "      <h3>{name} ({role})</h3>",
    "      <p>{age}세 · {email}</p>",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  const user = { name: '하루', age: 25, email: 'haru@test.com', role: '관리자' };",
    "",
    "  // 일일이 전달하는 대신",
    "  // <Profile name={user.name} age={user.age} email={user.email} role={user.role} />",
    "",
    "  // 스프레드로 한 번에 전달",
    "  return <Profile {...user} />;",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "interface ProfileProps {",
    "  name: string;",
    "  age: number;",
    "  email: string;",
    "  role: string;",
    "}",
    "",
    "function Profile({ name, age, email, role }: ProfileProps) {",
    "  return (",
    "    <div>",
    "      <h3>{name} ({role})</h3>",
    "      <p>{age}세 · {email}</p>",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  const user: ProfileProps = {",
    "    name: '하루', age: 25, email: 'haru@test.com', role: '관리자'",
    "  };",
    "  return <Profile {...user} />;",
    "}",
    "```",
    "",
    "> 스프레드는 편리하지만, 어떤 props가 전달되는지 명확하지 않을 수 있으므로 **의도적으로** 사용합니다.",
    "",
    "---",
    "",
    "## ...props (나머지 Props 패턴)",
    "",
    "구조 분해에서 **필요한 props만 꺼내고 나머지를 `...rest`로 모아서** 하위 요소에 전달하는 패턴입니다. 래퍼 컴포넌트나 UI 라이브러리 제작 시 핵심적으로 사용됩니다.",
    "",
    "### 기본 개념",
    "",
    "```tsx",
    "// ...rest는 name과 age를 제외한 '나머지 모든 props'를 객체로 모음",
    "function Greeting({ name, age, ...rest }) {",
    "  console.log(rest); // { email: 'haru@test.com', role: '관리자' }",
    "  return <p>{name}, {age}세</p>;",
    "}",
    "",
    "<Greeting name=\"하루\" age={25} email=\"haru@test.com\" role=\"관리자\" />",
    "```",
    "",
    "### 실전 패턴 1 — HTML 속성 전달 (래퍼 컴포넌트)",
    "",
    "커스텀 컴포넌트가 내부의 HTML 요소에 **모든 네이티브 속성**을 그대로 전달해야 할 때 사용합니다.",
    "",
    "#### JavaScript",
    "```jsx",
    "function Input({ label, error, ...rest }) {",
    "  return (",
    "    <div style={{ marginBottom: '16px' }}>",
    "      {label && <label style={{ display: 'block', marginBottom: '4px', fontWeight: 'bold' }}>{label}</label>}",
    "      <input",
    "        {...rest}",
    "        style={{",
    "          padding: '8px 12px',",
    "          border: `2px solid ${error ? '#e74c3c' : '#ddd'}`,",
    "          borderRadius: '6px',",
    "          width: '100%',",
    "          boxSizing: 'border-box',",
    "        }}",
    "      />",
    "      {error && <p style={{ color: '#e74c3c', fontSize: '12px', marginTop: '4px' }}>{error}</p>}",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <form>",
    "      {/* ...rest 덕분에 type, placeholder, onChange 등이 <input>에 그대로 전달됨 */}",
    "      <Input label=\"이메일\" type=\"email\" placeholder=\"이메일 입력\" required />",
    "      <Input label=\"비밀번호\" type=\"password\" placeholder=\"비밀번호\" minLength={8} />",
    "      <Input label=\"이름\" error=\"이름을 입력하세요\" />",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "#### TypeScript",
    "```tsx",
    "import type { ComponentPropsWithoutRef } from 'react';",
    "",
    "// ComponentPropsWithoutRef<'input'>은 <input>의 모든 HTML 속성 타입",
    "interface InputProps extends ComponentPropsWithoutRef<'input'> {",
    "  label?: string;",
    "  error?: string;",
    "}",
    "",
    "function Input({ label, error, ...rest }: InputProps) {",
    "  return (",
    "    <div style={{ marginBottom: '16px' }}>",
    "      {label && <label style={{ display: 'block', marginBottom: '4px', fontWeight: 'bold' }}>{label}</label>}",
    "      <input",
    "        {...rest}",
    "        style={{",
    "          padding: '8px 12px',",
    "          border: `2px solid ${error ? '#e74c3c' : '#ddd'}`,",
    "          borderRadius: '6px',",
    "          width: '100%',",
    "          boxSizing: 'border-box',",
    "        }}",
    "      />",
    "      {error && <p style={{ color: '#e74c3c', fontSize: '12px', marginTop: '4px' }}>{error}</p>}",
    "    </div>",
    "  );",
    "}",
    "",
    "// 사용 — type, placeholder, required, onChange 등 모든 input 속성 가능",
    "function App() {",
    "  return (",
    "    <form>",
    "      <Input label=\"이메일\" type=\"email\" placeholder=\"이메일 입력\" required />",
    "      <Input label=\"비밀번호\" type=\"password\" placeholder=\"비밀번호\" minLength={8} />",
    "      <Input label=\"이름\" error=\"이름을 입력하세요\" onChange={(e) => console.log(e.target.value)} />",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "> `ComponentPropsWithoutRef<'input'>`은 `<input>` 태그의 모든 HTML 속성(type, placeholder, onChange, className 등)을 타입으로 가져옵니다. `'button'`, `'div'`, `'a'` 등 다른 태그도 가능합니다.",
    "",
    "### 실전 패턴 2 — 버튼 래퍼",
    "",
    "```tsx",
    "import type { ComponentPropsWithoutRef, ReactNode } from 'react';",
    "",
    "interface ButtonProps extends ComponentPropsWithoutRef<'button'> {",
    "  variant?: 'primary' | 'danger' | 'ghost';",
    "  size?: 'sm' | 'md' | 'lg';",
    "  children: ReactNode;",
    "}",
    "",
    "function Button({ variant = 'primary', size = 'md', children, ...rest }: ButtonProps) {",
    "  const colors = { primary: '#3498db', danger: '#e74c3c', ghost: 'transparent' };",
    "  const paddings = { sm: '6px 12px', md: '10px 20px', lg: '14px 28px' };",
    "",
    "  return (",
    "    <button",
    "      {...rest}",
    "      style={{",
    "        background: colors[variant],",
    "        color: variant === 'ghost' ? '#333' : 'white',",
    "        padding: paddings[size],",
    "        border: variant === 'ghost' ? '1px solid #ddd' : 'none',",
    "        borderRadius: '8px',",
    "        cursor: 'pointer',",
    "        fontSize: '14px',",
    "        ...rest.style,",
    "      }}",
    "    >",
    "      {children}",
    "    </button>",
    "  );",
    "}",
    "",
    "// 사용 — onClick, disabled, type 등 모든 button 속성이 그대로 전달됨",
    "function App() {",
    "  return (",
    "    <div style={{ display: 'flex', gap: '8px' }}>",
    "      <Button onClick={() => alert('저장!')}>저장</Button>",
    "      <Button variant=\"danger\" onClick={() => confirm('삭제?')}>삭제</Button>",
    "      <Button variant=\"ghost\" size=\"sm\" disabled>비활성</Button>",
    "      <Button type=\"submit\" form=\"myForm\">제출</Button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 실전 패턴 3 — 컴포넌트 감싸기 (Props 포워딩)",
    "",
    "기존 컴포넌트를 감싸면서 일부 props만 추가/변경하고 나머지는 그대로 전달합니다.",
    "",
    "```tsx",
    "import type { ComponentPropsWithoutRef } from 'react';",
    "",
    "// 기존 Input 컴포넌트의 모든 props를 받되, icon만 추가",
    "interface IconInputProps extends ComponentPropsWithoutRef<'input'> {",
    "  icon: string;",
    "}",
    "",
    "function IconInput({ icon, ...rest }: IconInputProps) {",
    "  return (",
    "    <div style={{ position: 'relative' }}>",
    "      <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)' }}>",
    "        {icon}",
    "      </span>",
    "      <input {...rest} style={{ paddingLeft: '36px', padding: '8px 8px 8px 36px', ...rest.style }} />",
    "    </div>",
    "  );",
    "}",
    "",
    "// 사용",
    "<IconInput icon=\"🔍\" placeholder=\"검색...\" onChange={(e) => setQuery(e.target.value)} />",
    "<IconInput icon=\"📧\" type=\"email\" placeholder=\"이메일\" required />",
    "```",
    "",
    "### ...props 동작 원리 정리",
    "",
    "```tsx",
    "// 부모가 전달한 모든 props",
    "<Card title=\"제목\" className=\"my-card\" id=\"card-1\" onClick={fn} />",
    "",
    "// 자식에서 구조 분해",
    "function Card({ title, ...rest }) {",
    "  // title = \"제목\"",
    "  // rest  = { className: \"my-card\", id: \"card-1\", onClick: fn }",
    "",
    "  return (",
    "    <div {...rest}>       {/* className, id, onClick이 <div>에 전달됨 */}",
    "      <h2>{title}</h2>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "| 문법 | 위치 | 역할 |",
    "|------|------|------|",
    "| `{...obj}` | JSX에서 | 객체의 모든 속성을 **props로 펼쳐서 전달** |",
    "| `...rest` | 매개변수에서 | 명시하지 않은 **나머지 props를 모아서 수집** |",
    "| `{...rest}` | 자식 JSX에서 | 수집한 나머지를 **하위 요소에 그대로 전달** |",
    "",
    "### 자주 사용하는 HTML 속성 타입",
    "",
    "| 타입 | 대상 | 사용 예 |",
    "|------|------|---------|",
    "| `ComponentPropsWithoutRef<'input'>` | `<input>` 래퍼 | type, placeholder, onChange... |",
    "| `ComponentPropsWithoutRef<'button'>` | `<button>` 래퍼 | onClick, disabled, type... |",
    "| `ComponentPropsWithoutRef<'a'>` | `<a>` 래퍼 | href, target, rel... |",
    "| `ComponentPropsWithoutRef<'div'>` | `<div>` 래퍼 | className, id, style... |",
    "| `ComponentPropsWithRef<'input'>` | ref 포함 | ref 전달이 필요할 때 |",
    "",
    "> `...props` 패턴은 **재사용 가능한 UI 컴포넌트**를 만들 때 필수입니다. 커스텀 props만 정의하고 나머지 HTML 속성은 `...rest`로 그대로 전달하면, 사용하는 쪽에서 네이티브 속성을 자유롭게 쓸 수 있습니다.",
    "",
    "---",
    "",
    "## 조건부 렌더링과 Props",
    "",
    "### JavaScript",
    "```jsx",
    "function Alert({ type = 'info', message, onClose }) {",
    "  const colors = {",
    "    info: { bg: '#d1ecf1', text: '#0c5460', border: '#bee5eb' },",
    "    success: { bg: '#d4edda', text: '#155724', border: '#c3e6cb' },",
    "    warning: { bg: '#fff3cd', text: '#856404', border: '#ffeaa7' },",
    "    error: { bg: '#f8d7da', text: '#721c24', border: '#f5c6cb' },",
    "  };",
    "  const style = colors[type];",
    "",
    "  return (",
    "    <div style={{",
    "      background: style.bg, color: style.text,",
    "      border: `1px solid ${style.border}`,",
    "      padding: '12px 16px', borderRadius: '8px',",
    "      display: 'flex', justifyContent: 'space-between', alignItems: 'center',",
    "      margin: '8px 0',",
    "    }}>",
    "      <span>{message}</span>",
    "      {onClose && (",
    "        <button onClick={onClose} style={{",
    "          background: 'none', border: 'none',",
    "          color: style.text, cursor: 'pointer', fontSize: '18px'",
    "        }}>",
    "          ×",
    "        </button>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <div style={{ padding: '20px', maxWidth: '500px' }}>",
    "      <Alert type=\"success\" message=\"저장되었습니다!\" />",
    "      <Alert type=\"error\" message=\"오류가 발생했습니다.\" onClose={() => alert('닫기')} />",
    "      <Alert type=\"warning\" message=\"주의: 변경사항이 있습니다.\" />",
    "      <Alert message=\"일반 안내 메시지입니다.\" />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "type AlertType = 'info' | 'success' | 'warning' | 'error';",
    "",
    "interface AlertProps {",
    "  type?: AlertType;",
    "  message: string;",
    "  onClose?: () => void;",
    "}",
    "",
    "interface AlertStyle {",
    "  bg: string;",
    "  text: string;",
    "  border: string;",
    "}",
    "",
    "function Alert({ type = 'info', message, onClose }: AlertProps) {",
    "  const colors: Record<AlertType, AlertStyle> = {",
    "    info: { bg: '#d1ecf1', text: '#0c5460', border: '#bee5eb' },",
    "    success: { bg: '#d4edda', text: '#155724', border: '#c3e6cb' },",
    "    warning: { bg: '#fff3cd', text: '#856404', border: '#ffeaa7' },",
    "    error: { bg: '#f8d7da', text: '#721c24', border: '#f5c6cb' },",
    "  };",
    "  const style = colors[type];",
    "",
    "  return (",
    "    <div style={{",
    "      background: style.bg, color: style.text,",
    "      border: `1px solid ${style.border}`,",
    "      padding: '12px 16px', borderRadius: '8px',",
    "      display: 'flex', justifyContent: 'space-between', alignItems: 'center',",
    "      margin: '8px 0',",
    "    }}>",
    "      <span>{message}</span>",
    "      {onClose && (",
    "        <button onClick={onClose} style={{",
    "          background: 'none', border: 'none',",
    "          color: style.text, cursor: 'pointer', fontSize: '18px'",
    "        }}>",
    "          ×",
    "        </button>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 리스트 렌더링과 Props",
    "",
    "### JavaScript",
    "```jsx",
    "function UserTable({ users }) {",
    "  return (",
    "    <table style={{ width: '100%', borderCollapse: 'collapse' }}>",
    "      <thead>",
    "        <tr style={{ background: '#f8f9fa' }}>",
    "          <th style={{ padding: '12px', textAlign: 'left' }}>이름</th>",
    "          <th style={{ padding: '12px', textAlign: 'left' }}>이메일</th>",
    "          <th style={{ padding: '12px', textAlign: 'left' }}>역할</th>",
    "        </tr>",
    "      </thead>",
    "      <tbody>",
    "        {users.map((user) => (",
    "          <tr key={user.id} style={{ borderBottom: '1px solid #dee2e6' }}>",
    "            <td style={{ padding: '12px' }}>{user.name}</td>",
    "            <td style={{ padding: '12px' }}>{user.email}</td>",
    "            <td style={{ padding: '12px' }}>{user.role}</td>",
    "          </tr>",
    "        ))}",
    "      </tbody>",
    "    </table>",
    "  );",
    "}",
    "",
    "function App() {",
    "  const users = [",
    "    { id: 1, name: '하루', email: 'haru@test.com', role: '관리자' },",
    "    { id: 2, name: '철수', email: 'cs@test.com', role: '일반' },",
    "    { id: 3, name: '영희', email: 'yh@test.com', role: '일반' },",
    "  ];",
    "",
    "  return <UserTable users={users} />;",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "interface User {",
    "  id: number;",
    "  name: string;",
    "  email: string;",
    "  role: string;",
    "}",
    "",
    "interface UserTableProps {",
    "  users: User[];",
    "}",
    "",
    "function UserTable({ users }: UserTableProps) {",
    "  return (",
    "    <table style={{ width: '100%', borderCollapse: 'collapse' }}>",
    "      <thead>",
    "        <tr style={{ background: '#f8f9fa' }}>",
    "          <th style={{ padding: '12px', textAlign: 'left' }}>이름</th>",
    "          <th style={{ padding: '12px', textAlign: 'left' }}>이메일</th>",
    "          <th style={{ padding: '12px', textAlign: 'left' }}>역할</th>",
    "        </tr>",
    "      </thead>",
    "      <tbody>",
    "        {users.map((user) => (",
    "          <tr key={user.id} style={{ borderBottom: '1px solid #dee2e6' }}>",
    "            <td style={{ padding: '12px' }}>{user.name}</td>",
    "            <td style={{ padding: '12px' }}>{user.email}</td>",
    "            <td style={{ padding: '12px' }}>{user.role}</td>",
    "          </tr>",
    "        ))}",
    "      </tbody>",
    "    </table>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## Render Props 패턴",
    "",
    "함수를 props로 전달하여 **렌더링 로직을 외부에서 결정**하는 고급 패턴입니다.",
    "",
    "### JavaScript",
    "```jsx",
    "import { useState, useEffect } from 'react';",
    "",
    "function MouseTracker({ render }) {",
    "  const [position, setPosition] = useState({ x: 0, y: 0 });",
    "",
    "  useEffect(() => {",
    "    const handleMove = (e) => setPosition({ x: e.clientX, y: e.clientY });",
    "    window.addEventListener('mousemove', handleMove);",
    "    return () => window.removeEventListener('mousemove', handleMove);",
    "  }, []);",
    "",
    "  return render(position);",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <div>",
    "      <MouseTracker render={({ x, y }) => (",
    "        <p>마우스 위치: ({x}, {y})</p>",
    "      )} />",
    "      <MouseTracker render={({ x, y }) => (",
    "        <div style={{",
    "          position: 'fixed', left: x, top: y,",
    "          width: '20px', height: '20px',",
    "          background: 'red', borderRadius: '50%',",
    "          transform: 'translate(-50%, -50%)',",
    "          pointerEvents: 'none',",
    "        }} />",
    "      )} />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "import { useState, useEffect, type ReactNode } from 'react';",
    "",
    "interface Position {",
    "  x: number;",
    "  y: number;",
    "}",
    "",
    "interface MouseTrackerProps {",
    "  render: (position: Position) => ReactNode;",
    "}",
    "",
    "function MouseTracker({ render }: MouseTrackerProps) {",
    "  const [position, setPosition] = useState<Position>({ x: 0, y: 0 });",
    "",
    "  useEffect(() => {",
    "    const handleMove = (e: MouseEvent): void => {",
    "      setPosition({ x: e.clientX, y: e.clientY });",
    "    };",
    "    window.addEventListener('mousemove', handleMove);",
    "    return () => window.removeEventListener('mousemove', handleMove);",
    "  }, []);",
    "",
    "  return <>{render(position)}</>;",
    "}",
    "```",
    "",
    "> Render Props는 커스텀 Hook이 등장하기 전에 많이 쓰였습니다. 현재는 Hook으로 대체하는 경우가 많지만, 렌더링 제어가 필요한 라이브러리에서 여전히 사용됩니다.",
    "",
    "---",
    "",
    "## Props 검증 (PropTypes)",
    "",
    "JavaScript에서 런타임에 props 타입을 검증할 수 있습니다. TypeScript를 사용하면 컴파일 타임에 잡히므로 PropTypes가 불필요합니다.",
    "",
    "```jsx",
    "import PropTypes from 'prop-types';",
    "",
    "function UserCard({ name, age, email, role }) {",
    "  return (",
    "    <div>",
    "      <h3>{name}</h3>",
    "      <p>{age}세 · {email}</p>",
    "      <p>역할: {role}</p>",
    "    </div>",
    "  );",
    "}",
    "",
    "UserCard.propTypes = {",
    "  name: PropTypes.string.isRequired,",
    "  age: PropTypes.number.isRequired,",
    "  email: PropTypes.string.isRequired,",
    "  role: PropTypes.oneOf(['관리자', '일반', '게스트']),",
    "};",
    "",
    "UserCard.defaultProps = {",
    "  role: '일반',",
    "};",
    "```",
    "",
    "### PropTypes vs TypeScript",
    "",
    "| 구분 | PropTypes | TypeScript |",
    "|------|----------|------------|",
    "| 검증 시점 | **런타임** (개발 모드) | **컴파일 타임** |",
    "| 설치 | `npm install prop-types` | 빌드 도구에 포함 |",
    "| 에러 표시 | 브라우저 콘솔 경고 | IDE 빨간 밑줄 + 빌드 에러 |",
    "| 성능 | 프로덕션에서 제거됨 | 빌드 시 제거됨 (제로 런타임) |",
    "| 권장 | JS 프로젝트 | TS 프로젝트 (PropTypes 불필요) |",
    "",
    "---",
    "",
    "## 컴포넌트 합성 패턴",
    "",
    "Props와 children을 활용한 **합성(Composition)** 패턴입니다.",
    "",
    "### JavaScript",
    "```jsx",
    "function Layout({ header, sidebar, children, footer }) {",
    "  return (",
    "    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>",
    "      <header style={{ background: '#2c3e50', color: 'white', padding: '16px' }}>",
    "        {header}",
    "      </header>",
    "      <div style={{ display: 'flex', flex: 1 }}>",
    "        <aside style={{ width: '200px', background: '#ecf0f1', padding: '16px' }}>",
    "          {sidebar}",
    "        </aside>",
    "        <main style={{ flex: 1, padding: '16px' }}>",
    "          {children}",
    "        </main>",
    "      </div>",
    "      <footer style={{ background: '#2c3e50', color: 'white', padding: '16px', textAlign: 'center' }}>",
    "        {footer}",
    "      </footer>",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <Layout",
    "      header={<h1>My App</h1>}",
    "      sidebar={",
    "        <nav>",
    "          <ul>",
    "            <li>홈</li>",
    "            <li>소개</li>",
    "            <li>연락처</li>",
    "          </ul>",
    "        </nav>",
    "      }",
    "      footer={<p>© 2026 My App</p>}",
    "    >",
    "      <h2>메인 콘텐츠</h2>",
    "      <p>여기에 본문이 들어갑니다.</p>",
    "    </Layout>",
    "  );",
    "}",
    "```",
    "",
    "### TypeScript",
    "```tsx",
    "import type { ReactNode } from 'react';",
    "",
    "interface LayoutProps {",
    "  header: ReactNode;",
    "  sidebar: ReactNode;",
    "  children: ReactNode;",
    "  footer: ReactNode;",
    "}",
    "",
    "function Layout({ header, sidebar, children, footer }: LayoutProps) {",
    "  return (",
    "    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>",
    "      <header style={{ background: '#2c3e50', color: 'white', padding: '16px' }}>",
    "        {header}",
    "      </header>",
    "      <div style={{ display: 'flex', flex: 1 }}>",
    "        <aside style={{ width: '200px', background: '#ecf0f1', padding: '16px' }}>",
    "          {sidebar}",
    "        </aside>",
    "        <main style={{ flex: 1, padding: '16px' }}>",
    "          {children}",
    "        </main>",
    "      </div>",
    "      <footer style={{ background: '#2c3e50', color: 'white', padding: '16px', textAlign: 'center' }}>",
    "        {footer}",
    "      </footer>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## Props 전체 요약",
    "",
    "| 개념 | 핵심 |",
    "|------|------|",
    "| 기본 전달 | `<Comp name=\"하루\" />` → `{ name }` 로 받기 |",
    "| 기본값 | `{ name = '기본값' }` 구조 분해 기본값 |",
    "| children | 태그 사이의 내용, `ReactNode` 타입 |",
    "| 콜백 Props | 부모 함수를 자식에게 전달하여 역방향 통신 |",
    "| 스프레드 | `{...obj}`로 한 번에 전달 |",
    "| Render Props | 함수를 전달하여 렌더링 제어 |",
    "| PropTypes | JS 런타임 검증 (TS 사용 시 불필요) |",
    "| TypeScript | `interface Props { }` 로 컴파일 타임 검증 |",
    "",
    "---",
    "",
    "### 요약",
    "Props는 React에서 부모 → 자식으로 데이터를 전달하는 핵심 메커니즘입니다. 구조 분해 할당으로 받고, 기본값을 설정하며, children으로 JSX를 감싸고, 콜백 함수로 역방향 통신을 합니다. TypeScript에서는 interface로 Props 타입을 정의하여 컴파일 타임에 안전성을 확보합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
