<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "react-overview",
  title: "React 개요 및 프로젝트 시작하기",
  date: "2026-02-25",
  summary: "React란 무엇인지, 왜 사용하는지, 프로젝트 생성(Vite), JSX 문법, 컴포넌트, props, state, 이벤트 처리, 조건부/리스트 렌더링, useEffect까지 React의 핵심 기초를 정리합니다.",
  category: "Technology/React",
  tags: ["react","jsx","component","props","state","hooks","vite","basics"],
  content: [
    "## 한 줄 요약",
    "**React**는 Facebook이 만든 **컴포넌트 기반 UI 라이브러리**로, JSX 문법과 Virtual DOM을 사용하여 선언적이고 효율적인 UI를 구축합니다.",
    "",
    "---",
    "",
    "## React란?",
    "",
    "- UI를 만들기 위한 **JavaScript 라이브러리** (프레임워크가 아님)",
    "- **컴포넌트 단위**로 UI를 조립",
    "- **Virtual DOM**으로 변경된 부분만 효율적으로 업데이트",
    "- **단방향 데이터 흐름** (부모 → 자식)",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| 선언적 | \"어떻게\" 보여줄지가 아니라 \"무엇을\" 보여줄지 기술 |",
    "| 컴포넌트 기반 | 재사용 가능한 독립적 UI 조각 |",
    "| Virtual DOM | 실제 DOM 조작을 최소화하여 성능 최적화 |",
    "| 단방향 바인딩 | 데이터가 부모에서 자식으로만 흐름 (props) |",
    "| 생태계 | React Router, Redux, Next.js 등 풍부한 생태계 |",
    "",
    "---",
    "",
    "## 프로젝트 생성 (Vite)",
    "",
    "### 설치 및 실행",
    "```bash",
    "# React + TypeScript 프로젝트 생성",
    "npm create vite@latest my-app -- --template react-ts",
    "",
    "# 프로젝트 이동 & 의존성 설치",
    "cd my-app",
    "npm install",
    "",
    "# 개발 서버 실행",
    "npm run dev",
    "# → http://localhost:5173 에서 확인",
    "```",
    "",
    "### 프로젝트 구조",
    "```",
    "my-app/",
    "├── public/                 # 정적 파일",
    "│   └── vite.svg            # Vite 로고 (favicon)",
    "├── src/",
    "│   ├── assets/             # 정적 에셋 (이미지 등)",
    "│   │   └── react.svg       # React 로고",
    "│   ├── App.css             # App 컴포넌트 스타일",
    "│   ├── App.tsx             # 루트 컴포넌트",
    "│   ├── index.css           # 전역 스타일",
    "│   └── main.tsx            # 엔트리 포인트 (렌더링 시작)",
    "├── .gitignore              # Git 추적 제외 파일 목록",
    "├── eslint.config.js        # ESLint 설정 (Flat Config)",
    "├── index.html              # HTML 템플릿",
    "├── package.json            # 프로젝트 메타데이터 & 의존성",
    "├── README.md               # 프로젝트 설명",
    "├── tsconfig.json           # TypeScript 프로젝트 참조 (루트)",
    "├── tsconfig.app.json       # 앱 소스용 TypeScript 설정",
    "├── tsconfig.node.json      # Node 환경(vite.config 등) TypeScript 설정",
    "└── vite.config.ts          # Vite 번들러 설정",
    "```",
    "",
    "### public/ vs src/assets/ 차이",
    "",
    "| 위치 | 처리 방식 | 접근 방법 | 용도 |",
    "|------|-----------|-----------|------|",
    "| `public/` | 빌드 시 그대로 복사 (변환 없음) | 절대 경로 `\"/vite.svg\"` | favicon, robots.txt 등 |",
    "| `src/assets/` | Vite가 번들링 (해시 추가, 최적화) | `import`로 가져오기 | 로고, 아이콘, 이미지 등 |",
    "",
    "```tsx",
    "// public/ 파일: 절대 경로로 접근",
    "import viteLogo from '/vite.svg'",
    "",
    "// src/assets/ 파일: import로 접근 (빌드 시 해시 추가됨)",
    "import reactLogo from './assets/react.svg'",
    "```",
    "",
    "### 엔트리 포인트 (main.tsx)",
    "```tsx",
    "import { StrictMode } from 'react'",
    "import { createRoot } from 'react-dom/client'",
    "import './index.css'",
    "import App from './App.tsx'",
    "",
    "createRoot(document.getElementById('root')!).render(",
    "  <StrictMode>",
    "    <App />",
    "  </StrictMode>,",
    ")",
    "```",
    "",
    "| 함수 | 역할 |",
    "|------|------|",
    "| `createRoot()` | 루트 DOM 노드에 React 앱을 연결 |",
    "| `.render()` | 컴포넌트를 실제 화면에 렌더링 |",
    "| `<StrictMode>` | 개발 중 잠재적 문제를 경고 (2번 렌더링) |",
    "",
    "---",
    "",
    "## JSX (JavaScript XML)",
    "",
    "JSX는 JavaScript 안에서 **HTML처럼** UI를 작성하는 문법입니다. 실제로는 `React.createElement()`로 변환됩니다.",
    "",
    "```tsx",
    "// JSX",
    "const element = <h1 className=\"title\">Hello, React!</h1>;",
    "",
    "// 변환된 JavaScript",
    "const element = React.createElement('h1', { className: 'title' }, 'Hello, React!');",
    "```",
    "",
    "### JSX 규칙",
    "",
    "```tsx",
    "function App() {",
    "  const name = 'React';",
    "  const isLoggedIn = true;",
    "",
    "  return (",
    "    // 1. 최상위 요소는 하나만 (Fragment 사용 가능)",
    "    <>",
    "      {/* 2. JS 표현식은 중괄호 {} 안에 */}",
    "      <h1>Hello, {name}!</h1>",
    "",
    "      {/* 3. class → className, for → htmlFor */}",
    "      <div className=\"container\">",
    "",
    "        {/* 4. 스타일은 객체로 */}",
    "        <p style={{ color: 'red', fontSize: '16px' }}>styled text</p>",
    "",
    "        {/* 5. 닫는 태그 필수 */}",
    "        <img src=\"logo.png\" alt=\"logo\" />",
    "        <br />",
    "      </div>",
    "    </>",
    "  );",
    "}",
    "```",
    "",
    "| HTML | JSX |",
    "|------|-----|",
    "| `class` | `className` |",
    "| `for` | `htmlFor` |",
    "| `style=\"color: red\"` | `style={{ color: 'red' }}` |",
    "| `<br>` | `<br />` (자기 닫기 필수) |",
    "| `<!-- 주석 -->` | `{/* 주석 */}` |",
    "",
    "---",
    "",
    "## 컴포넌트 (Component)",
    "",
    "React의 핵심 단위입니다. **함수**로 작성하며, **JSX를 반환**합니다.",
    "",
    "### 함수형 컴포넌트",
    "```tsx",
    "// 컴포넌트 이름은 대문자로 시작",
    "function Greeting() {",
    "  return <h1>안녕하세요!</h1>;",
    "}",
    "",
    "// 화살표 함수",
    "const Greeting = () => {",
    "  return <h1>안녕하세요!</h1>;",
    "};",
    "",
    "// 사용",
    "function App() {",
    "  return (",
    "    <div>",
    "      <Greeting />",
    "      <Greeting />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## Props (속성 전달)",
    "",
    "부모 컴포넌트에서 자식 컴포넌트로 **데이터를 전달**합니다. props는 **읽기 전용**입니다.",
    "",
    "```tsx",
    "// TypeScript: props 타입 정의",
    "interface UserCardProps {",
    "  name: string;",
    "  age: number;",
    "  isActive?: boolean;  // 선택적 props",
    "}",
    "",
    "function UserCard({ name, age, isActive = true }: UserCardProps) {",
    "  return (",
    "    <div>",
    "      <h2>{name}</h2>",
    "      <p>나이: {age}</p>",
    "      <p>상태: {isActive ? '활성' : '비활성'}</p>",
    "    </div>",
    "  );",
    "}",
    "",
    "// 사용",
    "function App() {",
    "  return (",
    "    <div>",
    "      <UserCard name=\"haru\" age={25} />",
    "      <UserCard name=\"kim\" age={30} isActive={false} />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### children props",
    "```tsx",
    "interface CardProps {",
    "  title: string;",
    "  children: React.ReactNode;",
    "}",
    "",
    "function Card({ title, children }: CardProps) {",
    "  return (",
    "    <div className=\"card\">",
    "      <h2>{title}</h2>",
    "      <div>{children}</div>",
    "    </div>",
    "  );",
    "}",
    "",
    "// 사용",
    "<Card title=\"공지사항\">",
    "  <p>이것은 카드 안의 내용입니다.</p>",
    "  <button>확인</button>",
    "</Card>",
    "```",
    "",
    "---",
    "",
    "## State (상태 관리)",
    "",
    "컴포넌트 내부에서 **변경 가능한 데이터**를 관리합니다. state가 변경되면 컴포넌트가 **다시 렌더링**됩니다.",
    "",
    "### useState",
    "```tsx",
    "import { useState } from 'react';",
    "",
    "function Counter() {",
    "  // [상태값, 변경함수] = useState(초기값)",
    "  const [count, setCount] = useState<number>(0);",
    "",
    "  return (",
    "    <div>",
    "      <p>카운트: {count}</p>",
    "      <button onClick={() => setCount(count + 1)}>+1</button>",
    "      <button onClick={() => setCount(count - 1)}>-1</button>",
    "      <button onClick={() => setCount(0)}>초기화</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 여러 state 사용",
    "```tsx",
    "function Form() {",
    "  const [name, setName] = useState<string>('');",
    "  const [age, setAge] = useState<number>(0);",
    "  const [isAgreed, setIsAgreed] = useState<boolean>(false);",
    "",
    "  return (",
    "    <form>",
    "      <input",
    "        value={name}",
    "        onChange={(e) => setName(e.target.value)}",
    "        placeholder=\"이름\"",
    "      />",
    "      <input",
    "        type=\"number\"",
    "        value={age}",
    "        onChange={(e) => setAge(Number(e.target.value))}",
    "        placeholder=\"나이\"",
    "      />",
    "      <label>",
    "        <input",
    "          type=\"checkbox\"",
    "          checked={isAgreed}",
    "          onChange={(e) => setIsAgreed(e.target.checked)}",
    "        />",
    "        동의합니다",
    "      </label>",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "### 객체/배열 state",
    "```tsx",
    "interface Todo {",
    "  id: number;",
    "  text: string;",
    "  done: boolean;",
    "}",
    "",
    "function TodoApp() {",
    "  const [todos, setTodos] = useState<Todo[]>([]);",
    "  const [input, setInput] = useState('');",
    "",
    "  const addTodo = () => {",
    "    if (!input.trim()) return;",
    "    setTodos([...todos, { id: Date.now(), text: input, done: false }]);",
    "    setInput('');",
    "  };",
    "",
    "  const toggleTodo = (id: number) => {",
    "    setTodos(todos.map(todo =>",
    "      todo.id === id ? { ...todo, done: !todo.done } : todo",
    "    ));",
    "  };",
    "",
    "  const deleteTodo = (id: number) => {",
    "    setTodos(todos.filter(todo => todo.id !== id));",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <input value={input} onChange={e => setInput(e.target.value)} />",
    "      <button onClick={addTodo}>추가</button>",
    "      <ul>",
    "        {todos.map(todo => (",
    "          <li key={todo.id}>",
    "            <span",
    "              style={{ textDecoration: todo.done ? 'line-through' : 'none' }}",
    "              onClick={() => toggleTodo(todo.id)}",
    "            >",
    "              {todo.text}",
    "            </span>",
    "            <button onClick={() => deleteTodo(todo.id)}>삭제</button>",
    "          </li>",
    "        ))}",
    "      </ul>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "> **주의**: state는 직접 수정하면 안 됩니다. 항상 `set` 함수를 통해 **새로운 값/객체/배열**을 전달해야 합니다.",
    "",
    "---",
    "",
    "## 이벤트 처리",
    "",
    "```tsx",
    "function EventExample() {",
    "  // 클릭",
    "  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {",
    "    console.log('clicked!', e.target);",
    "  };",
    "",
    "  // 입력",
    "  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {",
    "    console.log(e.target.value);",
    "  };",
    "",
    "  // 폼 제출",
    "  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {",
    "    e.preventDefault(); // 새로고침 방지",
    "    console.log('submitted!');",
    "  };",
    "",
    "  return (",
    "    <form onSubmit={handleSubmit}>",
    "      <input onChange={handleChange} />",
    "      <button onClick={handleClick}>클릭</button>",
    "    </form>",
    "  );",
    "}",
    "```",
    "",
    "| HTML | React |",
    "|------|-------|",
    "| `onclick` | `onClick` (camelCase) |",
    "| `onchange` | `onChange` |",
    "| `onsubmit` | `onSubmit` |",
    "| `\"handleClick()\"` (문자열) | `{handleClick}` (함수 참조) |",
    "",
    "---",
    "",
    "## 조건부 렌더링",
    "",
    "```tsx",
    "function Greeting({ isLoggedIn }: { isLoggedIn: boolean }) {",
    "  // 1. if문",
    "  if (!isLoggedIn) {",
    "    return <p>로그인해 주세요.</p>;",
    "  }",
    "",
    "  return (",
    "    <div>",
    "      {/* 2. 삼항 연산자 */}",
    "      <p>{isLoggedIn ? '환영합니다!' : '로그인 필요'}</p>",
    "",
    "      {/* 3. && 연산자 (true일 때만 렌더링) */}",
    "      {isLoggedIn && <button>로그아웃</button>}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 리스트 렌더링",
    "",
    "배열을 `map`으로 변환하여 렌더링합니다. **`key`는 필수**입니다.",
    "",
    "```tsx",
    "interface User {",
    "  id: number;",
    "  name: string;",
    "}",
    "",
    "function UserList() {",
    "  const users: User[] = [",
    "    { id: 1, name: 'haru' },",
    "    { id: 2, name: 'kim' },",
    "    { id: 3, name: 'lee' }",
    "  ];",
    "",
    "  return (",
    "    <ul>",
    "      {users.map(user => (",
    "        <li key={user.id}>{user.name}</li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "| key 규칙 | 설명 |",
    "|----------|------|",
    "| 고유해야 함 | 형제 요소 사이에서 유일한 값 |",
    "| 안정적이어야 함 | 렌더링마다 바뀌지 않는 값 (id 추천) |",
    "| index 사용 지양 | 순서가 바뀔 수 있는 리스트에서는 버그 발생 가능 |",
    "",
    "---",
    "",
    "## useEffect (사이드 이펙트)",
    "",
    "데이터 가져오기, 타이머, DOM 조작 등 **렌더링 이외의 작업**을 수행합니다.",
    "",
    "```tsx",
    "import { useState, useEffect } from 'react';",
    "",
    "function Timer() {",
    "  const [seconds, setSeconds] = useState(0);",
    "",
    "  useEffect(() => {",
    "    // 마운트 시 타이머 시작",
    "    const interval = setInterval(() => {",
    "      setSeconds(prev => prev + 1);",
    "    }, 1000);",
    "",
    "    // 클린업 (언마운트 시 타이머 정리)",
    "    return () => clearInterval(interval);",
    "  }, []); // 빈 배열: 마운트 시 1번만 실행",
    "",
    "  return <p>경과 시간: {seconds}초</p>;",
    "}",
    "```",
    "",
    "### 의존성 배열",
    "",
    "| 형태 | 실행 시점 |",
    "|------|----------|",
    "| `useEffect(() => {}, [])` | 마운트 시 **1번만** 실행 |",
    "| `useEffect(() => {}, [count])` | `count`가 **변경될 때마다** 실행 |",
    "| `useEffect(() => {})` | **매 렌더링마다** 실행 (주의!) |",
    "",
    "### API 데이터 가져오기",
    "```tsx",
    "interface Post {",
    "  id: number;",
    "  title: string;",
    "}",
    "",
    "function PostList() {",
    "  const [posts, setPosts] = useState<Post[]>([]);",
    "  const [loading, setLoading] = useState(true);",
    "",
    "  useEffect(() => {",
    "    fetch('https://jsonplaceholder.typicode.com/posts?_limit=5')",
    "      .then(res => res.json())",
    "      .then((data: Post[]) => {",
    "        setPosts(data);",
    "        setLoading(false);",
    "      });",
    "  }, []);",
    "",
    "  if (loading) return <p>로딩 중...</p>;",
    "",
    "  return (",
    "    <ul>",
    "      {posts.map(post => (",
    "        <li key={post.id}>{post.title}</li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## Props vs State 비교",
    "",
    "| 비교 | Props | State |",
    "|------|-------|-------|",
    "| 데이터 소유 | 부모 컴포넌트 | 자기 자신 |",
    "| 변경 가능 | ❌ (읽기 전용) | ✅ (set 함수로 변경) |",
    "| 전달 방향 | 부모 → 자식 | 컴포넌트 내부 |",
    "| 변경 시 | 부모가 다시 렌더링 | 자신이 다시 렌더링 |",
    "",
    "---",
    "",
    "## TypeScript 설정 파일 구조",
    "",
    "Vite React-TS 템플릿은 TypeScript 설정을 **3개 파일**로 분리합니다.",
    "",
    "### tsconfig.json (루트)",
    "프로젝트 전체를 묶는 **참조(reference) 파일**입니다. 직접적인 컴파일 옵션은 없습니다.",
    "```json",
    "{",
    "  \"files\": [],",
    "  \"references\": [",
    "    { \"path\": \"./tsconfig.app.json\" },",
    "    { \"path\": \"./tsconfig.node.json\" }",
    "  ]",
    "}",
    "```",
    "",
    "### tsconfig.app.json (앱 소스용)",
    "**src/ 폴더의 React 코드**에 적용되는 설정입니다.",
    "```json",
    "{",
    "  \"compilerOptions\": {",
    "    \"target\": \"ES2022\",",
    "    \"lib\": [\"ES2022\", \"DOM\", \"DOM.Iterable\"],",
    "    \"module\": \"ESNext\",",
    "    \"types\": [\"vite/client\"],",
    "    \"skipLibCheck\": true,",
    "    \"moduleResolution\": \"bundler\",",
    "    \"allowImportingTsExtensions\": true,",
    "    \"verbatimModuleSyntax\": true,",
    "    \"noEmit\": true,",
    "    \"jsx\": \"react-jsx\",",
    "    \"strict\": true,",
    "    \"noUnusedLocals\": true,",
    "    \"noUnusedParameters\": true",
    "  },",
    "  \"include\": [\"src\"]",
    "}",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `types: [\"vite/client\"]` | `import.meta.env` 등 Vite 전용 타입 제공 (예전 `vite-env.d.ts` 역할) |",
    "| `jsx: \"react-jsx\"` | React 17+ 자동 JSX 변환 (`import React` 불필요) |",
    "| `moduleResolution: \"bundler\"` | Vite 같은 번들러 환경에 최적화된 모듈 해석 |",
    "| `verbatimModuleSyntax` | `import type`을 명시적으로 사용하도록 강제 |",
    "| `noEmit` | 타입 체크만 수행, JS 파일 생성은 Vite가 담당 |",
    "",
    "### tsconfig.node.json (Node 환경용)",
    "**vite.config.ts** 같은 Node 환경 파일에 적용됩니다.",
    "```json",
    "{",
    "  \"compilerOptions\": {",
    "    \"target\": \"ES2023\",",
    "    \"lib\": [\"ES2023\"],",
    "    \"module\": \"ESNext\",",
    "    \"types\": [\"node\"],",
    "    \"skipLibCheck\": true,",
    "    \"moduleResolution\": \"bundler\",",
    "    \"noEmit\": true,",
    "    \"strict\": true",
    "  },",
    "  \"include\": [\"vite.config.ts\"]",
    "}",
    "```",
    "",
    "> **왜 분리하나?** 브라우저용 코드(src/)와 Node용 코드(vite.config.ts)는 실행 환경이 다릅니다. DOM API는 브라우저에만 있고, Node API(`fs`, `path` 등)는 서버에만 있으므로, 각각에 맞는 타입과 설정을 적용하기 위해 분리합니다.",
    "",
    "---",
    "",
    "## ESLint 설정 (eslint.config.js)",
    "",
    "Vite 템플릿은 최신 **ESLint Flat Config** 방식을 사용합니다.",
    "",
    "```js",
    "import js from '@eslint/js'",
    "import globals from 'globals'",
    "import reactHooks from 'eslint-plugin-react-hooks'",
    "import reactRefresh from 'eslint-plugin-react-refresh'",
    "import tseslint from 'typescript-eslint'",
    "import { defineConfig, globalIgnores } from 'eslint/config'",
    "",
    "export default defineConfig([",
    "  globalIgnores(['dist']),",
    "  {",
    "    files: ['**/*.{ts,tsx}'],",
    "    extends: [",
    "      js.configs.recommended,",
    "      tseslint.configs.recommended,",
    "      reactHooks.configs.flat.recommended,",
    "      reactRefresh.configs.vite,",
    "    ],",
    "    languageOptions: {",
    "      ecmaVersion: 2020,",
    "      globals: globals.browser,",
    "    },",
    "  },",
    "])",
    "```",
    "",
    "| 플러그인 | 역할 |",
    "|----------|------|",
    "| `@eslint/js` | JavaScript 기본 규칙 |",
    "| `typescript-eslint` | TypeScript 전용 규칙 |",
    "| `eslint-plugin-react-hooks` | Hooks 규칙 (deps 배열 검사 등) |",
    "| `eslint-plugin-react-refresh` | HMR(핫 리로드) 호환성 검사 |",
    "",
    "---",
    "",
    "## 주요 npm 스크립트",
    "",
    "```bash",
    "npm run dev      # 개발 서버 (HMR 핫 리로드)",
    "npm run build    # TypeScript 타입 체크 + 프로덕션 빌드 (dist/ 생성)",
    "npm run lint     # ESLint 코드 검사",
    "npm run preview  # 빌드 결과 미리보기",
    "```",
    "",
    "### build 스크립트 상세",
    "```json",
    "\"build\": \"tsc -b && vite build\"",
    "```",
    "- `tsc -b`: TypeScript **프로젝트 참조 빌드** (tsconfig.json의 references 기반 타입 체크)",
    "- `vite build`: 실제 번들링 및 최적화 수행 (dist/ 폴더에 결과물 생성)",
    "",
    "---",
    "",
    "## 주요 의존성",
    "",
    "```json",
    "\"dependencies\": {",
    "  \"react\": \"^19.2.0\",",
    "  \"react-dom\": \"^19.2.0\"",
    "},",
    "\"devDependencies\": {",
    "  \"@vitejs/plugin-react\": \"...\",",
    "  \"typescript\": \"~5.9.3\",",
    "  \"vite\": \"^7.3.1\",",
    "  \"eslint\": \"...\",",
    "  \"eslint-plugin-react-hooks\": \"...\",",
    "  \"eslint-plugin-react-refresh\": \"...\",",
    "  \"typescript-eslint\": \"...\",",
    "  \"@types/react\": \"...\",",
    "  \"@types/react-dom\": \"...\"",
    "}",
    "```",
    "",
    "| 구분 | 설명 |",
    "|------|------|",
    "| `dependencies` | **런타임에 필요한** 패키지 (빌드 결과에 포함) |",
    "| `devDependencies` | **개발 시에만 필요한** 패키지 (빌드 도구, 타입, 린터 등) |",
    "",
    "---",
    "### 요약",
    "React는 **컴포넌트**(재사용 가능한 UI 조각) + **JSX**(JS 안의 HTML) + **Props**(부모→자식 데이터 전달) + **State**(컴포넌트 내부 변경 데이터) + **Hooks**(useState, useEffect)로 구성됩니다. Vite로 프로젝트를 생성하면 **TypeScript 설정 3분할**, **ESLint Flat Config**, **HMR** 등이 기본 포함되어 있어 바로 개발을 시작할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
