<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "react-design-patterns",
  title: "React 디자인 패턴: HOC, Render Props, Compound Component",
  date: "2026-03-03",
  summary: "React의 대표 디자인 패턴인 HOC(고차 컴포넌트), Render Props, Compound Component, Custom Hook 패턴, 컨테이너/프레젠테이션 패턴의 개념과 활용법을 TypeScript 예제로 정리합니다.",
  category: "Technology/React",
  tags: ["react","design-pattern","HOC","render-props","compound-component","custom-hook","typescript"],
  content: [
    "## 한 줄 요약",
    "React 디자인 패턴은 **로직 재사용**과 **관심사 분리**를 위한 컴포넌트 설계 기법이며, 현대 React에서는 **커스텀 훅**이 대부분의 패턴을 대체합니다.",
    "",
    "---",
    "",
    "## 패턴 한눈에 비교",
    "",
    "| 패턴 | 목적 | 현재 상태 |",
    "|------|------|----------|",
    "| **Custom Hook** | 로직 재사용 | ✅ 가장 권장 |",
    "| **Compound Component** | 유연한 UI 합성 | ✅ 활발히 사용 |",
    "| **컨테이너/프레젠테이션** | 로직-UI 분리 | ✅ 여전히 유용 |",
    "| **Render Props** | 로직 공유 + UI 위임 | ⚠️ 훅으로 대체 가능 |",
    "| **HOC** | 횡단 관심사 주입 | ⚠️ 훅으로 대체 가능 |",
    "",
    "---",
    "",
    "## 1. 커스텀 훅 패턴",
    "",
    "상태 로직을 함수로 추출하여 여러 컴포넌트에서 재사용합니다. 현재 가장 권장되는 패턴입니다.",
    "",
    "```tsx",
    "// hooks/useToggle.ts",
    "import { useState, useCallback } from 'react';",
    "",
    "interface UseToggleReturn {",
    "  isOpen: boolean;",
    "  toggle: () => void;",
    "  open: () => void;",
    "  close: () => void;",
    "}",
    "",
    "function useToggle(initial = false): UseToggleReturn {",
    "  const [isOpen, setIsOpen] = useState(initial);",
    "",
    "  const toggle = useCallback(() => setIsOpen((prev) => !prev), []);",
    "  const open = useCallback(() => setIsOpen(true), []);",
    "  const close = useCallback(() => setIsOpen(false), []);",
    "",
    "  return { isOpen, toggle, open, close };",
    "}",
    "",
    "// 사용 — 모달",
    "function ModalExample(): JSX.Element {",
    "  const { isOpen, open, close } = useToggle();",
    "",
    "  return (",
    "    <div>",
    "      <button onClick={open}>모달 열기</button>",
    "      {isOpen && (",
    "        <div className='modal'>",
    "          <p>모달 내용</p>",
    "          <button onClick={close}>닫기</button>",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "// 사용 — 드롭다운",
    "function DropdownExample(): JSX.Element {",
    "  const { isOpen, toggle } = useToggle();",
    "",
    "  return (",
    "    <div>",
    "      <button onClick={toggle}>메뉴 {isOpen ? '▲' : '▼'}</button>",
    "      {isOpen && <ul><li>옵션 1</li><li>옵션 2</li></ul>}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 2. Compound Component 패턴",
    "",
    "관련 컴포넌트를 하나의 그룹으로 묶어, 내부 상태를 **Context**로 공유합니다. HTML의 `<select>` + `<option>` 관계와 유사합니다.",
    "",
    "```tsx",
    "import { createContext, useContext, useState, type ReactNode } from 'react';",
    "",
    "// Context",
    "interface AccordionContextType {",
    "  openIndex: number | null;",
    "  toggle: (index: number) => void;",
    "}",
    "",
    "const AccordionContext = createContext<AccordionContextType | null>(null);",
    "",
    "function useAccordionContext(): AccordionContextType {",
    "  const ctx = useContext(AccordionContext);",
    "  if (!ctx) throw new Error('Accordion 하위에서만 사용 가능');",
    "  return ctx;",
    "}",
    "",
    "// 부모",
    "function Accordion({ children }: { children: ReactNode }): JSX.Element {",
    "  const [openIndex, setOpenIndex] = useState<number | null>(null);",
    "  const toggle = (index: number) => setOpenIndex((prev) => (prev === index ? null : index));",
    "",
    "  return (",
    "    <AccordionContext.Provider value={{ openIndex, toggle }}>",
    "      <div>{children}</div>",
    "    </AccordionContext.Provider>",
    "  );",
    "}",
    "",
    "// 자식",
    "function AccordionItem({ index, title, children }: {",
    "  index: number; title: string; children: ReactNode;",
    "}): JSX.Element {",
    "  const { openIndex, toggle } = useAccordionContext();",
    "  const isOpen = openIndex === index;",
    "",
    "  return (",
    "    <div>",
    "      <button onClick={() => toggle(index)}>",
    "        {title} {isOpen ? '▲' : '▼'}",
    "      </button>",
    "      {isOpen && <div style={{ padding: '8px' }}>{children}</div>}",
    "    </div>",
    "  );",
    "}",
    "",
    "// 정적 속성으로 연결",
    "Accordion.Item = AccordionItem;",
    "",
    "// 사용",
    "function App(): JSX.Element {",
    "  return (",
    "    <Accordion>",
    "      <Accordion.Item index={0} title='섹션 1'>내용 1</Accordion.Item>",
    "      <Accordion.Item index={1} title='섹션 2'>내용 2</Accordion.Item>",
    "      <Accordion.Item index={2} title='섹션 3'>내용 3</Accordion.Item>",
    "    </Accordion>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 3. 컨테이너 / 프레젠테이션 패턴",
    "",
    "**로직**(데이터 페칭, 상태)과 **UI**(렌더링)를 분리합니다.",
    "",
    "```tsx",
    "// 프레젠테이션 — 순수 UI (props만 받음)",
    "interface UserListViewProps {",
    "  users: User[];",
    "  loading: boolean;",
    "}",
    "",
    "function UserListView({ users, loading }: UserListViewProps): JSX.Element {",
    "  if (loading) return <p>로딩 중...</p>;",
    "  return (",
    "    <ul>",
    "      {users.map((u) => <li key={u.id}>{u.name}</li>)}",
    "    </ul>",
    "  );",
    "}",
    "",
    "// 컨테이너 — 로직 담당",
    "function UserListContainer(): JSX.Element {",
    "  const { data: users = [], isLoading } = useUsers();",
    "  return <UserListView users={users} loading={isLoading} />;",
    "}",
    "```",
    "",
    "---",
    "",
    "## 4. Render Props 패턴",
    "",
    "컴포넌트의 렌더링 로직을 **함수로 전달**합니다. 훅 등장 이전에 로직 재사용의 핵심이었습니다.",
    "",
    "```tsx",
    "interface MousePosition { x: number; y: number; }",
    "",
    "interface MouseTrackerProps {",
    "  children: (pos: MousePosition) => JSX.Element;",
    "}",
    "",
    "function MouseTracker({ children }: MouseTrackerProps): JSX.Element {",
    "  const [pos, setPos] = useState<MousePosition>({ x: 0, y: 0 });",
    "",
    "  return (",
    "    <div onMouseMove={(e) => setPos({ x: e.clientX, y: e.clientY })}>",
    "      {children(pos)}",
    "    </div>",
    "  );",
    "}",
    "",
    "// 사용",
    "<MouseTracker>",
    "  {({ x, y }) => <p>마우스 위치: ({x}, {y})</p>}",
    "</MouseTracker>",
    "```",
    "",
    "> **현대적 대안:** 커스텀 훅 `useMousePosition()`으로 대체하는 것이 더 깔끔합니다.",
    "",
    "---",
    "",
    "## 5. HOC (고차 컴포넌트)",
    "",
    "컴포넌트를 받아 기능이 추가된 새 컴포넌트를 반환하는 **함수**입니다.",
    "",
    "```tsx",
    "interface WithLoadingProps {",
    "  loading: boolean;",
    "}",
    "",
    "function withLoading<P extends object>(",
    "  WrappedComponent: React.ComponentType<P>",
    ") {",
    "  return function WithLoadingComponent(props: P & WithLoadingProps): JSX.Element {",
    "    if (props.loading) return <p>로딩 중...</p>;",
    "    return <WrappedComponent {...props} />;",
    "  };",
    "}",
    "",
    "// 사용",
    "const UserListWithLoading = withLoading(UserList);",
    "<UserListWithLoading loading={isLoading} users={users} />",
    "```",
    "",
    "> **현대적 대안:** 커스텀 훅이나 Suspense로 대체하는 것이 권장됩니다.",
    "",
    "---",
    "",
    "## 패턴 선택 가이드",
    "",
    "| 상황 | 추천 패턴 |",
    "|------|----------|",
    "| 상태 로직 재사용 | **커스텀 훅** |",
    "| 유연한 UI 합성 (탭, 아코디언) | **Compound Component** |",
    "| 데이터/로직과 UI 분리 | **컨테이너/프레젠테이션** |",
    "| 기존 컴포넌트에 기능 주입 | **HOC** (레거시) 또는 **커스텀 훅** |",
    "| 렌더링 방식을 외부에서 결정 | **Render Props** 또는 **children as function** |",
    "",
    "---",
    "",
    "### 요약",
    "현대 React에서는 **커스텀 훅**이 로직 재사용의 표준입니다. **Compound Component**는 유연한 UI 합성에 여전히 강력하며, **컨테이너/프레젠테이션**은 로직과 UI를 분리하는 기본 원칙입니다. HOC와 Render Props는 레거시 코드에서 볼 수 있으므로 개념은 알아두되, 새 코드에서는 훅을 우선 사용합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
