<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "react-daisyui",
  title: "React에서 daisyUI 사용하기",
  date: "2026-02-25",
  summary: "Tailwind CSS 기반 컴포넌트 라이브러리 daisyUI를 React 프로젝트에 설치하고 주요 컴포넌트와 테마 시스템을 활용하는 방법을 정리합니다.",
  category: "Technology/React",
  tags: ["react","daisyui","tailwindcss","ui","component","theme","css"],
  content: [
    "## 한 줄 요약",
    "**daisyUI**는 Tailwind CSS 위에 `btn`, `card`, `modal` 같은 시맨틱 클래스명을 추가해주는 플러그인으로, React에서 적은 코드로 빠르게 UI를 구축할 수 있습니다.",
    "",
    "---",
    "",
    "## daisyUI란?",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 공식 사이트 | [daisyui.com](https://daisyui.com/) |",
    "| 공식 문서 | [daisyui.com/docs/install](https://daisyui.com/docs/install/) |",
    "| 컴포넌트 목록 | [daisyui.com/components](https://daisyui.com/components/) |",
    "| 테마 생성기 | [daisyui.com/theme-generator](https://daisyui.com/theme-generator/) |",
    "| GitHub | [github.com/saadeghi/daisyui](https://github.com/saadeghi/daisyui) |",
    "| 분류 | Tailwind CSS 플러그인 (컴포넌트 라이브러리) |",
    "| 특징 | **순수 CSS**, JS 의존성 없음 |",
    "| 컴포넌트 | 65개 이상 |",
    "| 테마 | 35개 이상 내장 + 커스텀 테마 |",
    "| 프레임워크 | React, Vue, Svelte, Angular 등 모두 지원 |",
    "",
    "### Tailwind CSS만 쓸 때의 문제",
    "```jsx",
    "// Tailwind만 사용 → 클래스명이 매우 길어짐",
    "<button className=\"inline-block cursor-pointer rounded-sm bg-zinc-900 px-4 py-2.5",
    "  text-center text-sm font-semibold text-white shadow-[0_.2rem_0.3rem_-.25rem_black]",
    "  active:shadow-none transition duration-200 ease-in-out focus-visible:ring-2",
    "  focus-visible:ring-zinc-700 focus-visible:ring-offset-2 focus-visible:outline-none",
    "  active:translate-y-[1px]\">",
    "  Save",
    "</button>",
    "```",
    "",
    "### daisyUI를 쓰면",
    "```jsx",
    "// daisyUI → 시맨틱 클래스명으로 간결하게",
    "<button className=\"btn btn-primary\">Save</button>",
    "```",
    "",
    "> daisyUI는 **클래스명 88% 감소**, **HTML 크기 79% 감소** 효과가 있습니다.",
    "",
    "---",
    "",
    "## 설치 및 설정",
    "",
    "### 1. React + Vite 프로젝트 생성",
    "```bash",
    "npm create vite@latest my-app -- --template react",
    "cd my-app",
    "npm install",
    "```",
    "",
    "### 2. Tailwind CSS 설치 (v4)",
    "```bash",
    "npm install tailwindcss @tailwindcss/vite",
    "```",
    "",
    "`vite.config.js`에 플러그인 추가:",
    "```javascript",
    "import { defineConfig } from 'vite'",
    "import react from '@vitejs/plugin-react'",
    "import tailwindcss from '@tailwindcss/vite'",
    "",
    "export default defineConfig({",
    "  plugins: [react(), tailwindcss()],",
    "})",
    "```",
    "",
    "### 3. daisyUI 설치",
    "```bash",
    "npm i -D daisyui@latest",
    "```",
    "",
    "### 4. CSS 설정",
    "",
    "`src/index.css` (또는 `app.css`):",
    "```css",
    "@import \"tailwindcss\";",
    "@plugin \"daisyui\";",
    "```",
    "",
    "> 이것으로 설정 완료입니다. 별도의 JS 번들이 필요하지 않습니다.",
    "",
    "---",
    "",
    "## 주요 컴포넌트",
    "",
    "### 버튼 (Button)",
    "",
    "```jsx",
    "function ButtonExample() {",
    "  return (",
    "    <div className=\"flex flex-wrap gap-2\">",
    "      <button className=\"btn\">Default</button>",
    "      <button className=\"btn btn-primary\">Primary</button>",
    "      <button className=\"btn btn-secondary\">Secondary</button>",
    "      <button className=\"btn btn-accent\">Accent</button>",
    "      <button className=\"btn btn-success\">Success</button>",
    "      <button className=\"btn btn-warning\">Warning</button>",
    "      <button className=\"btn btn-error\">Error</button>",
    "      <button className=\"btn btn-outline btn-primary\">Outline</button>",
    "      <button className=\"btn btn-ghost\">Ghost</button>",
    "      <button className=\"btn btn-link\">Link</button>",
    "",
    "      {/* 크기 */}",
    "      <button className=\"btn btn-primary btn-lg\">Large</button>",
    "      <button className=\"btn btn-primary btn-sm\">Small</button>",
    "      <button className=\"btn btn-primary btn-xs\">Tiny</button>",
    "",
    "      {/* 로딩 */}",
    "      <button className=\"btn btn-primary\">",
    "        <span className=\"loading loading-spinner\"></span>",
    "        로딩 중",
    "      </button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "| 클래스 | 설명 |",
    "|--------|------|",
    "| `btn` | 기본 버튼 |",
    "| `btn-primary` | 주 색상 |",
    "| `btn-secondary` | 보조 색상 |",
    "| `btn-accent` | 강조 색상 |",
    "| `btn-outline` | 테두리만 |",
    "| `btn-ghost` | 배경 없음 |",
    "| `btn-lg` / `btn-sm` / `btn-xs` | 크기 |",
    "| `btn-wide` | 넓은 버튼 |",
    "| `btn-circle` | 원형 |",
    "| `btn-square` | 정사각형 |",
    "",
    "---",
    "",
    "### 카드 (Card)",
    "",
    "```jsx",
    "function CardExample() {",
    "  return (",
    "    <div className=\"card bg-base-100 w-80 shadow-xl\">",
    "      <figure>",
    "        <img src=\"https://via.placeholder.com/400x200\" alt=\"thumbnail\" />",
    "      </figure>",
    "      <div className=\"card-body\">",
    "        <h2 className=\"card-title\">",
    "          카드 제목",
    "          <div className=\"badge badge-secondary\">NEW</div>",
    "        </h2>",
    "        <p>카드 본문 내용이 여기에 들어갑니다.</p>",
    "        <div className=\"card-actions justify-end\">",
    "          <button className=\"btn btn-primary\">자세히 보기</button>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 네비게이션 바 (Navbar)",
    "",
    "```jsx",
    "function NavbarExample() {",
    "  return (",
    "    <div className=\"navbar bg-base-100 shadow-sm\">",
    "      <div className=\"flex-1\">",
    "        <a className=\"btn btn-ghost text-xl\">My App</a>",
    "      </div>",
    "      <div className=\"flex-none\">",
    "        <ul className=\"menu menu-horizontal px-1\">",
    "          <li><a>홈</a></li>",
    "          <li><a>소개</a></li>",
    "          <li>",
    "            <details>",
    "              <summary>더보기</summary>",
    "              <ul className=\"bg-base-100 rounded-t-none p-2\">",
    "                <li><a>설정</a></li>",
    "                <li><a>로그아웃</a></li>",
    "              </ul>",
    "            </details>",
    "          </li>",
    "        </ul>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 모달 (Modal)",
    "",
    "daisyUI의 모달은 순수 CSS로 동작합니다. React에서는 state로도 제어할 수 있습니다.",
    "",
    "```jsx",
    "import { useRef } from 'react';",
    "",
    "function ModalExample() {",
    "  const modalRef = useRef(null);",
    "",
    "  return (",
    "    <>",
    "      <button className=\"btn btn-primary\" onClick={() => modalRef.current.showModal()}>",
    "        모달 열기",
    "      </button>",
    "",
    "      <dialog ref={modalRef} className=\"modal\">",
    "        <div className=\"modal-box\">",
    "          <h3 className=\"font-bold text-lg\">알림</h3>",
    "          <p className=\"py-4\">모달 본문 내용입니다.</p>",
    "          <div className=\"modal-action\">",
    "            <form method=\"dialog\">",
    "              <button className=\"btn\">닫기</button>",
    "            </form>",
    "          </div>",
    "        </div>",
    "        <form method=\"dialog\" className=\"modal-backdrop\">",
    "          <button>close</button>",
    "        </form>",
    "      </dialog>",
    "    </>",
    "  );",
    "}",
    "```",
    "",
    "> `<dialog>` 요소의 `showModal()` 메서드를 사용합니다. JS 라이브러리 없이 동작합니다.",
    "",
    "---",
    "",
    "### 드롭다운 (Dropdown)",
    "",
    "```jsx",
    "function DropdownExample() {",
    "  return (",
    "    <div className=\"dropdown\">",
    "      <div tabIndex={0} role=\"button\" className=\"btn m-1\">",
    "        메뉴",
    "      </div>",
    "      <ul tabIndex={0} className=\"dropdown-content menu bg-base-100 rounded-box z-10 w-52 p-2 shadow\">",
    "        <li><a>프로필</a></li>",
    "        <li><a>설정</a></li>",
    "        <li><a>로그아웃</a></li>",
    "      </ul>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 폼 입력 (Input / Select / Checkbox / Toggle)",
    "",
    "```jsx",
    "function FormExample() {",
    "  return (",
    "    <div className=\"flex flex-col gap-4 w-80\">",
    "      {/* 텍스트 입력 */}",
    "      <label className=\"floating-label\">",
    "        <span>이메일</span>",
    "        <input type=\"email\" placeholder=\"이메일\" className=\"input input-bordered w-full\" />",
    "      </label>",
    "",
    "      {/* 셀렉트 */}",
    "      <select className=\"select select-bordered w-full\">",
    "        <option disabled selected>카테고리 선택</option>",
    "        <option>기술</option>",
    "        <option>디자인</option>",
    "        <option>비즈니스</option>",
    "      </select>",
    "",
    "      {/* 체크박스 */}",
    "      <label className=\"label cursor-pointer\">",
    "        <span className=\"label-text\">이용약관 동의</span>",
    "        <input type=\"checkbox\" className=\"checkbox checkbox-primary\" />",
    "      </label>",
    "",
    "      {/* 토글 */}",
    "      <label className=\"label cursor-pointer\">",
    "        <span className=\"label-text\">알림 수신</span>",
    "        <input type=\"checkbox\" className=\"toggle toggle-success\" defaultChecked />",
    "      </label>",
    "",
    "      {/* 텍스트영역 */}",
    "      <textarea className=\"textarea textarea-bordered\" placeholder=\"내용 입력\"></textarea>",
    "",
    "      <button className=\"btn btn-primary\">제출</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 테이블 (Table)",
    "",
    "```jsx",
    "function TableExample() {",
    "  const users = [",
    "    { id: 1, name: '김철수', email: 'kim@example.com', role: '관리자' },",
    "    { id: 2, name: '이영희', email: 'lee@example.com', role: '사용자' },",
    "    { id: 3, name: '박민수', email: 'park@example.com', role: '사용자' },",
    "  ];",
    "",
    "  return (",
    "    <div className=\"overflow-x-auto\">",
    "      <table className=\"table table-zebra\">",
    "        <thead>",
    "          <tr>",
    "            <th>#</th>",
    "            <th>이름</th>",
    "            <th>이메일</th>",
    "            <th>역할</th>",
    "          </tr>",
    "        </thead>",
    "        <tbody>",
    "          {users.map((user) => (",
    "            <tr key={user.id} className=\"hover\">",
    "              <td>{user.id}</td>",
    "              <td>{user.name}</td>",
    "              <td>{user.email}</td>",
    "              <td><div className=\"badge badge-ghost\">{user.role}</div></td>",
    "            </tr>",
    "          ))}",
    "        </tbody>",
    "      </table>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "| 클래스 | 설명 |",
    "|--------|------|",
    "| `table` | 기본 테이블 |",
    "| `table-zebra` | 줄무늬 배경 |",
    "| `hover` (`<tr>`) | 마우스 오버 하이라이트 |",
    "| `table-pin-rows` | 헤더 고정 |",
    "| `table-pin-cols` | 첫 열 고정 |",
    "",
    "---",
    "",
    "### 알림 (Alert)",
    "",
    "```jsx",
    "function AlertExample() {",
    "  return (",
    "    <div className=\"flex flex-col gap-3\">",
    "      <div role=\"alert\" className=\"alert alert-info\">",
    "        <span>정보: 새 업데이트가 있습니다.</span>",
    "      </div>",
    "      <div role=\"alert\" className=\"alert alert-success\">",
    "        <span>성공: 저장이 완료되었습니다.</span>",
    "      </div>",
    "      <div role=\"alert\" className=\"alert alert-warning\">",
    "        <span>경고: 데이터가 곧 만료됩니다.</span>",
    "      </div>",
    "      <div role=\"alert\" className=\"alert alert-error\">",
    "        <span>에러: 서버에 연결할 수 없습니다.</span>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 뱃지 (Badge)",
    "",
    "```jsx",
    "function BadgeExample() {",
    "  return (",
    "    <div className=\"flex gap-2\">",
    "      <div className=\"badge\">default</div>",
    "      <div className=\"badge badge-primary\">primary</div>",
    "      <div className=\"badge badge-secondary\">secondary</div>",
    "      <div className=\"badge badge-accent\">accent</div>",
    "      <div className=\"badge badge-outline\">outline</div>",
    "      <div className=\"badge badge-lg\">large</div>",
    "      <div className=\"badge badge-sm\">small</div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 토스트 (Toast)",
    "",
    "```jsx",
    "function ToastExample() {",
    "  return (",
    "    <div className=\"toast toast-end\">",
    "      <div className=\"alert alert-success\">",
    "        <span>저장이 완료되었습니다.</span>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "| 위치 클래스 | 설명 |",
    "|-------------|------|",
    "| `toast-start` | 왼쪽 |",
    "| `toast-center` | 가운데 |",
    "| `toast-end` | 오른쪽 |",
    "| `toast-top` | 상단 |",
    "| `toast-middle` | 중간 |",
    "| `toast-bottom` | 하단 (기본) |",
    "",
    "---",
    "",
    "### 탭 (Tab)",
    "",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function TabExample() {",
    "  const [tab, setTab] = useState('tab1');",
    "",
    "  return (",
    "    <div>",
    "      <div role=\"tablist\" className=\"tabs tabs-bordered\">",
    "        <a role=\"tab\" className={`tab ${tab === 'tab1' ? 'tab-active' : ''}`}",
    "           onClick={() => setTab('tab1')}>탭 1</a>",
    "        <a role=\"tab\" className={`tab ${tab === 'tab2' ? 'tab-active' : ''}`}",
    "           onClick={() => setTab('tab2')}>탭 2</a>",
    "        <a role=\"tab\" className={`tab ${tab === 'tab3' ? 'tab-active' : ''}`}",
    "           onClick={() => setTab('tab3')}>탭 3</a>",
    "      </div>",
    "      <div className=\"p-4\">",
    "        {tab === 'tab1' && <p>첫 번째 탭 내용</p>}",
    "        {tab === 'tab2' && <p>두 번째 탭 내용</p>}",
    "        {tab === 'tab3' && <p>세 번째 탭 내용</p>}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 로딩 (Loading)",
    "",
    "```jsx",
    "function LoadingExample() {",
    "  return (",
    "    <div className=\"flex gap-4\">",
    "      <span className=\"loading loading-spinner loading-lg\"></span>",
    "      <span className=\"loading loading-dots loading-lg\"></span>",
    "      <span className=\"loading loading-ring loading-lg\"></span>",
    "      <span className=\"loading loading-ball loading-lg\"></span>",
    "      <span className=\"loading loading-bars loading-lg\"></span>",
    "      <span className=\"loading loading-infinity loading-lg\"></span>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "### 서랍 레이아웃 (Drawer)",
    "",
    "```jsx",
    "function DrawerExample() {",
    "  return (",
    "    <div className=\"drawer\">",
    "      <input id=\"my-drawer\" type=\"checkbox\" className=\"drawer-toggle\" />",
    "      <div className=\"drawer-content\">",
    "        <label htmlFor=\"my-drawer\" className=\"btn btn-primary drawer-button\">",
    "          사이드바 열기",
    "        </label>",
    "      </div>",
    "      <div className=\"drawer-side\">",
    "        <label htmlFor=\"my-drawer\" className=\"drawer-overlay\"></label>",
    "        <ul className=\"menu bg-base-200 text-base-content min-h-full w-60 p-4\">",
    "          <li><a>메뉴 1</a></li>",
    "          <li><a>메뉴 2</a></li>",
    "          <li><a>메뉴 3</a></li>",
    "        </ul>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "> `drawer-toggle`로 체크박스 상태를 이용해 사이드바를 열고 닫습니다. JS 없이 동작합니다.",
    "",
    "---",
    "",
    "## 테마 시스템",
    "",
    "daisyUI의 가장 강력한 기능 중 하나는 **35개 이상의 내장 테마**입니다.",
    "",
    "### 테마 적용",
    "",
    "HTML의 `data-theme` 속성으로 테마를 전환합니다.",
    "",
    "```jsx",
    "// index.html 또는 최상위 컴포넌트",
    "<html data-theme=\"light\">",
    "  ...",
    "</html>",
    "```",
    "",
    "### React에서 동적 테마 전환",
    "",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function ThemeSwitcher() {",
    "  const themes = [",
    "    'light', 'dark', 'cupcake', 'bumblebee', 'emerald',",
    "    'corporate', 'synthwave', 'retro', 'cyberpunk', 'valentine',",
    "    'halloween', 'garden', 'forest', 'aqua', 'lofi',",
    "    'pastel', 'fantasy', 'wireframe', 'black', 'luxury',",
    "    'dracula', 'cmyk', 'autumn', 'business', 'acid',",
    "    'lemonade', 'night', 'coffee', 'winter', 'dim',",
    "    'nord', 'sunset', 'caramellatte', 'abyss', 'silk',",
    "  ];",
    "",
    "  const [theme, setTheme] = useState('light');",
    "",
    "  const changeTheme = (t) => {",
    "    setTheme(t);",
    "    document.documentElement.setAttribute('data-theme', t);",
    "  };",
    "",
    "  return (",
    "    <div className=\"flex flex-wrap gap-2\">",
    "      {themes.map((t) => (",
    "        <button",
    "          key={t}",
    "          className={`btn btn-sm ${theme === t ? 'btn-primary' : 'btn-ghost'}`}",
    "          onClick={() => changeTheme(t)}",
    "        >",
    "          {t}",
    "        </button>",
    "      ))}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### Theme Controller (daisyUI 내장)",
    "",
    "daisyUI가 제공하는 `theme-controller` 클래스로 더 간편하게 전환할 수 있습니다.",
    "",
    "```jsx",
    "function ThemeController() {",
    "  return (",
    "    <div className=\"flex gap-2\">",
    "      <input",
    "        type=\"radio\"",
    "        name=\"theme-buttons\"",
    "        className=\"btn theme-controller\"",
    "        aria-label=\"Light\"",
    "        value=\"light\"",
    "      />",
    "      <input",
    "        type=\"radio\"",
    "        name=\"theme-buttons\"",
    "        className=\"btn theme-controller\"",
    "        aria-label=\"Dark\"",
    "        value=\"dark\"",
    "      />",
    "      <input",
    "        type=\"radio\"",
    "        name=\"theme-buttons\"",
    "        className=\"btn theme-controller\"",
    "        aria-label=\"Cyberpunk\"",
    "        value=\"cyberpunk\"",
    "      />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 시맨틱 색상 체계",
    "",
    "daisyUI는 테마별로 자동 변경되는 시맨틱 색상을 제공합니다.",
    "",
    "| 색상 | 용도 | Tailwind 클래스 |",
    "|------|------|-----------------|",
    "| `primary` | 주 색상 | `bg-primary`, `text-primary` |",
    "| `secondary` | 보조 색상 | `bg-secondary`, `text-secondary` |",
    "| `accent` | 강조 색상 | `bg-accent`, `text-accent` |",
    "| `neutral` | 중립 색상 | `bg-neutral`, `text-neutral` |",
    "| `base-100/200/300` | 배경 색상 | `bg-base-100`, `bg-base-200` |",
    "| `info` | 정보 | `bg-info`, `text-info` |",
    "| `success` | 성공 | `bg-success`, `text-success` |",
    "| `warning` | 경고 | `bg-warning`, `text-warning` |",
    "| `error` | 에러 | `bg-error`, `text-error` |",
    "",
    "> 테마를 바꾸면 이 색상들이 자동으로 변경되어 별도 작업 없이 다크 모드 등을 지원합니다.",
    "",
    "---",
    "",
    "## 실전 예제: Todo App",
    "",
    "daisyUI 컴포넌트들을 조합한 Todo App 예제입니다.",
    "",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function TodoApp() {",
    "  const [todos, setTodos] = useState([",
    "    { id: 1, text: 'React 공부하기', done: false },",
    "    { id: 2, text: 'daisyUI 적용하기', done: true },",
    "  ]);",
    "  const [input, setInput] = useState('');",
    "",
    "  const addTodo = () => {",
    "    if (!input.trim()) return;",
    "    setTodos([...todos, { id: Date.now(), text: input, done: false }]);",
    "    setInput('');",
    "  };",
    "",
    "  const toggleTodo = (id) => {",
    "    setTodos(todos.map((t) =>",
    "      t.id === id ? { ...t, done: !t.done } : t",
    "    ));",
    "  };",
    "",
    "  const deleteTodo = (id) => {",
    "    setTodos(todos.filter((t) => t.id !== id));",
    "  };",
    "",
    "  const remaining = todos.filter((t) => !t.done).length;",
    "",
    "  return (",
    "    <div className=\"min-h-screen bg-base-200 flex items-start justify-center pt-16\">",
    "      <div className=\"card bg-base-100 shadow-xl w-full max-w-md\">",
    "        <div className=\"card-body\">",
    "          <h2 className=\"card-title\">",
    "            Todo List",
    "            <div className=\"badge badge-primary\">{remaining}개 남음</div>",
    "          </h2>",
    "",
    "          <div className=\"join w-full\">",
    "            <input",
    "              className=\"input input-bordered join-item w-full\"",
    "              placeholder=\"할 일 입력...\"",
    "              value={input}",
    "              onChange={(e) => setInput(e.target.value)}",
    "              onKeyDown={(e) => e.key === 'Enter' && addTodo()}",
    "            />",
    "            <button className=\"btn btn-primary join-item\" onClick={addTodo}>",
    "              추가",
    "            </button>",
    "          </div>",
    "",
    "          <ul className=\"mt-2\">",
    "            {todos.map((todo) => (",
    "              <li key={todo.id}",
    "                  className=\"flex items-center justify-between py-2 border-b border-base-300\">",
    "                <label className=\"flex items-center gap-3 cursor-pointer\">",
    "                  <input",
    "                    type=\"checkbox\"",
    "                    className=\"checkbox checkbox-primary checkbox-sm\"",
    "                    checked={todo.done}",
    "                    onChange={() => toggleTodo(todo.id)}",
    "                  />",
    "                  <span className={todo.done ? 'line-through opacity-50' : ''}>",
    "                    {todo.text}",
    "                  </span>",
    "                </label>",
    "                <button",
    "                  className=\"btn btn-ghost btn-xs text-error\"",
    "                  onClick={() => deleteTodo(todo.id)}",
    "                >",
    "                  삭제",
    "                </button>",
    "              </li>",
    "            ))}",
    "          </ul>",
    "",
    "          {todos.length === 0 && (",
    "            <div className=\"text-center py-8 opacity-50\">",
    "              할 일이 없습니다",
    "            </div>",
    "          )}",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "export default TodoApp;",
    "```",
    "",
    "---",
    "",
    "## 컴포넌트 전체 목록",
    "",
    "### Actions (동작)",
    "| 컴포넌트 | 클래스 | 용도 |",
    "|----------|--------|------|",
    "| Button | `btn` | 버튼 |",
    "| Dropdown | `dropdown` | 드롭다운 메뉴 |",
    "| Modal | `modal` | 팝업 대화상자 |",
    "| Swap | `swap` | 토글 전환 |",
    "| Theme Controller | `theme-controller` | 테마 전환 |",
    "",
    "### Data Display (데이터 표시)",
    "| 컴포넌트 | 클래스 | 용도 |",
    "|----------|--------|------|",
    "| Accordion | `collapse` | 접기/펼치기 |",
    "| Avatar | `avatar` | 프로필 이미지 |",
    "| Badge | `badge` | 작은 라벨 |",
    "| Card | `card` | 카드 레이아웃 |",
    "| Carousel | `carousel` | 이미지 슬라이더 |",
    "| Chat Bubble | `chat` | 채팅 말풍선 |",
    "| Table | `table` | 데이터 테이블 |",
    "| Timeline | `timeline` | 타임라인 |",
    "| Stat | `stat` | 통계 수치 |",
    "",
    "### Navigation (내비게이션)",
    "| 컴포넌트 | 클래스 | 용도 |",
    "|----------|--------|------|",
    "| Breadcrumbs | `breadcrumbs` | 경로 탐색 |",
    "| Dock | `dock` | 하단 네비게이션 |",
    "| Menu | `menu` | 메뉴 목록 |",
    "| Navbar | `navbar` | 상단 네비게이션 |",
    "| Pagination | `join` | 페이지 전환 |",
    "| Steps | `steps` | 단계 표시 |",
    "| Tab | `tabs` | 탭 전환 |",
    "",
    "### Feedback (피드백)",
    "| 컴포넌트 | 클래스 | 용도 |",
    "|----------|--------|------|",
    "| Alert | `alert` | 알림 메시지 |",
    "| Loading | `loading` | 로딩 애니메이션 |",
    "| Progress | `progress` | 진행률 바 |",
    "| Skeleton | `skeleton` | 로딩 뼈대 |",
    "| Toast | `toast` | 토스트 알림 |",
    "| Tooltip | `tooltip` | 툴팁 |",
    "",
    "### Data Input (입력)",
    "| 컴포넌트 | 클래스 | 용도 |",
    "|----------|--------|------|",
    "| Checkbox | `checkbox` | 체크박스 |",
    "| Input | `input` | 텍스트 입력 |",
    "| Radio | `radio` | 라디오 버튼 |",
    "| Range | `range` | 슬라이더 |",
    "| Rating | `rating` | 별점 |",
    "| Select | `select` | 드롭다운 선택 |",
    "| Textarea | `textarea` | 여러 줄 입력 |",
    "| Toggle | `toggle` | 토글 스위치 |",
    "| File Input | `file-input` | 파일 업로드 |",
    "",
    "---",
    "",
    "## daisyUI vs 다른 라이브러리",
    "",
    "| 구분 | daisyUI | Bootstrap | MUI | shadcn/ui |",
    "|------|---------|-----------|-----|-----------|",
    "| 기반 | Tailwind CSS | 자체 CSS | 자체 CSS-in-JS | Tailwind CSS |",
    "| JS 의존성 | 없음 (순수 CSS) | jQuery (일부) | React 전용 | React 전용 |",
    "| 번들 크기 | 매우 작음 | 보통 | 큼 | 작음 |",
    "| 테마 | 35개 내장 + 커스텀 | 제한적 | 커스텀 | 커스텀 |",
    "| 커스터마이징 | Tailwind 유틸리티 활용 | CSS 변수 | `sx` prop, styled | 소스 복사 후 수정 |",
    "| 학습 곡선 | 낮음 | 낮음 | 보통 | 보통 |",
    "| 프레임워크 | 모두 지원 | 모두 (react-bootstrap) | React만 | React만 |",
    "",
    "---",
    "",
    "### 요약",
    "daisyUI는 Tailwind CSS 프로젝트에 `npm i -D daisyui@latest` 하나로 설치되며, `btn`, `card`, `modal` 같은 시맨틱 클래스명으로 적은 코드로 빠르게 UI를 만들 수 있습니다. JS 의존성이 없어 가볍고, 35개 이상의 내장 테마로 `data-theme` 속성만 바꾸면 다크 모드를 포함한 다양한 테마를 적용할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
