<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "react-key-ref-children",
  title: "React 특수 속성: key, ref, children",
  date: "2026-03-03",
  summary: "React의 3가지 특수 속성인 key(리스트 렌더링 최적화), ref(DOM 직접 접근), children(컴포넌트 합성)의 개념과 활용법을 JavaScript·TypeScript 예제로 정리합니다.",
  category: "Technology/React",
  tags: ["react","key","ref","children","useRef","forwardRef","typescript","list-rendering"],
  content: [
    "## 한 줄 요약",
    "**key**는 리스트의 각 요소를 식별하고, **ref**는 DOM에 직접 접근하며, **children**은 컴포넌트 태그 사이의 내용을 전달하는 React의 특수 속성입니다.",
    "",
    "---",
    "",
    "## 공식 문서",
    "",
    "| 항목 | URL |",
    "|------|-----|",
    "| key로 리스트 렌더링 | [react.dev/learn/rendering-lists](https://react.dev/learn/rendering-lists) |",
    "| ref로 DOM 조작 | [react.dev/learn/manipulating-the-dom-with-refs](https://react.dev/learn/manipulating-the-dom-with-refs) |",
    "| children 전달 | [react.dev/learn/passing-props-to-a-component](https://react.dev/learn/passing-props-to-a-component) |",
    "",
    "---",
    "",
    "## 세 속성이 특별한 이유",
    "",
    "일반 props와 달리 `key`, `ref`, `children`은 React가 **내부적으로 특별하게 처리**합니다.",
    "",
    "| 속성 | 자식 컴포넌트에서 접근 | 용도 |",
    "|------|----------------------|------|",
    "| `key` | ❌ `props.key`로 접근 불가 | React가 리스트 요소를 식별·비교하는 데 사용 |",
    "| `ref` | ❌ `props.ref`로 접근 불가 (forwardRef 필요) | DOM 요소나 컴포넌트 인스턴스에 직접 접근 |",
    "| `children` | ✅ `props.children`으로 접근 | 태그 사이의 내용을 자식 컴포넌트에 전달 |",
    "",
    "---",
    "",
    "## 1. key - 리스트 렌더링의 핵심",
    "",
    "### key란?",
    "",
    "`key`는 React가 리스트의 각 요소를 **고유하게 식별**하기 위해 사용하는 특수 속성입니다. React는 key를 통해 어떤 항목이 추가·삭제·변경되었는지 판단하고 **최소한의 DOM 업데이트**만 수행합니다.",
    "",
    "### 기본 사용법",
    "",
    "**JavaScript**",
    "```jsx",
    "function FruitList() {",
    "  const fruits = ['사과', '바나나', '포도', '딸기'];",
    "",
    "  return (",
    "    <ul>",
    "      {fruits.map((fruit, index) => (",
    "        <li key={index}>{fruit}</li>  // index를 key로 사용 (비권장)",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "function FruitList(): JSX.Element {",
    "  const fruits: string[] = ['사과', '바나나', '포도', '딸기'];",
    "",
    "  return (",
    "    <ul>",
    "      {fruits.map((fruit, index) => (",
    "        <li key={index}>{fruit}</li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "### 올바른 key 사용법",
    "",
    "**JavaScript**",
    "```jsx",
    "function UserList() {",
    "  const users = [",
    "    { id: 1, name: '하루', role: '관리자' },",
    "    { id: 2, name: '철수', role: '일반' },",
    "    { id: 3, name: '영희', role: '일반' },",
    "  ];",
    "",
    "  return (",
    "    <ul>",
    "      {users.map((user) => (",
    "        <li key={user.id}>",
    "          {user.name} ({user.role})",
    "        </li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "interface User {",
    "  id: number;",
    "  name: string;",
    "  role: string;",
    "}",
    "",
    "function UserList(): JSX.Element {",
    "  const users: User[] = [",
    "    { id: 1, name: '하루', role: '관리자' },",
    "    { id: 2, name: '철수', role: '일반' },",
    "    { id: 3, name: '영희', role: '일반' },",
    "  ];",
    "",
    "  return (",
    "    <ul>",
    "      {users.map((user) => (",
    "        <li key={user.id}>",
    "          {user.name} ({user.role})",
    "        </li>",
    "      ))}",
    "    </ul>",
    "  );",
    "}",
    "```",
    "",
    "### key 규칙",
    "",
    "| 규칙 | 설명 |",
    "|------|------|",
    "| **고유해야 함** | 형제 요소 간에 중복되면 안 됨 |",
    "| **안정적이어야 함** | 렌더링마다 바뀌면 안 됨 (`Math.random()` ❌) |",
    "| **DB id 사용 권장** | `user.id`, `post.id` 같은 고유 식별자 |",
    "| **index는 최후의 수단** | 순서가 변경되지 않는 정적 리스트에서만 사용 |",
    "",
    "### index를 key로 쓰면 안 되는 이유",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function TodoApp() {",
    "  const [todos, setTodos] = useState([",
    "    { id: 1, text: 'React 공부' },",
    "    { id: 2, text: '운동하기' },",
    "    { id: 3, text: '독서' },",
    "  ]);",
    "",
    "  const addToFront = () => {",
    "    const newTodo = { id: Date.now(), text: `할 일 ${todos.length + 1}` };",
    "    setTodos([newTodo, ...todos]); // 앞에 추가",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <button onClick={addToFront}>맨 앞에 추가</button>",
    "      <h3>❌ index를 key로 사용 (입력값이 밀림)</h3>",
    "      {todos.map((todo, index) => (",
    "        <div key={index} style={{ display: 'flex', gap: '8px', margin: '4px 0' }}>",
    "          <span>{todo.text}</span>",
    "          <input placeholder=\"메모\" />",
    "        </div>",
    "      ))}",
    "",
    "      <h3>✅ id를 key로 사용 (입력값이 유지됨)</h3>",
    "      {todos.map((todo) => (",
    "        <div key={todo.id} style={{ display: 'flex', gap: '8px', margin: '4px 0' }}>",
    "          <span>{todo.text}</span>",
    "          <input placeholder=\"메모\" />",
    "        </div>",
    "      ))}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "> index를 key로 사용하면, 맨 앞에 항목을 추가할 때 React가 기존 항목과 새 항목을 **잘못 매칭**합니다. 결과적으로 input의 값이 엉뚱한 항목에 붙게 됩니다.",
    "",
    "### key를 이용한 컴포넌트 초기화",
    "",
    "key가 변경되면 React는 해당 컴포넌트를 **완전히 언마운트하고 새로 마운트**합니다. 이 특성을 활용하면 컴포넌트를 강제로 초기화할 수 있습니다.",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState } from 'react';",
    "",
    "function Timer({ label }) {",
    "  const [seconds, setSeconds] = useState(0);",
    "",
    "  useState(() => {",
    "    const id = setInterval(() => setSeconds((s) => s + 1), 1000);",
    "    return () => clearInterval(id);",
    "  });",
    "",
    "  return <p>{label}: {seconds}초</p>;",
    "}",
    "",
    "function App() {",
    "  const [timerId, setTimerId] = useState(0);",
    "",
    "  return (",
    "    <div>",
    "      {/* key가 바뀌면 Timer가 완전히 새로 생성됨 */}",
    "      <Timer key={timerId} label=\"타이머\" />",
    "      <button onClick={() => setTimerId((id) => id + 1)}>타이머 초기화</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState } from 'react';",
    "",
    "interface TimerProps {",
    "  label: string;",
    "}",
    "",
    "function Timer({ label }: TimerProps): JSX.Element {",
    "  const [seconds, setSeconds] = useState(0);",
    "",
    "  useState(() => {",
    "    const id = setInterval(() => setSeconds((s) => s + 1), 1000);",
    "    return () => clearInterval(id);",
    "  });",
    "",
    "  return <p>{label}: {seconds}초</p>;",
    "}",
    "",
    "function App(): JSX.Element {",
    "  const [timerId, setTimerId] = useState(0);",
    "",
    "  return (",
    "    <div>",
    "      <Timer key={timerId} label=\"타이머\" />",
    "      <button onClick={() => setTimerId((id) => id + 1)}>타이머 초기화</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### key에서 props.key 접근 불가",
    "",
    "```jsx",
    "function Item({ key, name }) {",
    "  // ⚠️ key는 undefined! React가 내부적으로 사용하고 props에 전달하지 않음",
    "  console.log(key); // undefined",
    "  return <li>{name}</li>;",
    "}",
    "",
    "// key 값이 필요하면 별도 prop으로 전달",
    "function Item({ id, name }) {",
    "  return <li data-id={id}>{name}</li>;",
    "}",
    "",
    "<Item key={user.id} id={user.id} name={user.name} />",
    "```",
    "",
    "---",
    "",
    "## 2. ref - DOM 직접 접근",
    "",
    "### ref란?",
    "",
    "`ref`는 React가 관리하는 **DOM 요소에 직접 접근**하거나, 리렌더링 없이 값을 유지할 때 사용하는 특수 속성입니다.",
    "",
    "### useRef로 DOM 접근",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useRef } from 'react';",
    "",
    "function TextInput() {",
    "  const inputRef = useRef(null);",
    "",
    "  const handleFocus = () => {",
    "    inputRef.current.focus();",
    "    inputRef.current.select();",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <input ref={inputRef} placeholder=\"여기에 입력\" />",
    "      <button onClick={handleFocus}>포커스 & 선택</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useRef } from 'react';",
    "",
    "function TextInput(): JSX.Element {",
    "  const inputRef = useRef<HTMLInputElement>(null);",
    "",
    "  const handleFocus = (): void => {",
    "    inputRef.current?.focus();",
    "    inputRef.current?.select();",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <input ref={inputRef} placeholder=\"여기에 입력\" />",
    "      <button onClick={handleFocus}>포커스 & 선택</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 다양한 DOM 요소 ref",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useRef } from 'react';",
    "",
    "function MultiRef(): JSX.Element {",
    "  const inputRef = useRef<HTMLInputElement>(null);",
    "  const divRef = useRef<HTMLDivElement>(null);",
    "  const buttonRef = useRef<HTMLButtonElement>(null);",
    "  const canvasRef = useRef<HTMLCanvasElement>(null);",
    "  const videoRef = useRef<HTMLVideoElement>(null);",
    "  const textareaRef = useRef<HTMLTextAreaElement>(null);",
    "",
    "  return (",
    "    <div>",
    "      <input ref={inputRef} />",
    "      <div ref={divRef}>컨테이너</div>",
    "      <button ref={buttonRef}>버튼</button>",
    "      <canvas ref={canvasRef} />",
    "      <video ref={videoRef} />",
    "      <textarea ref={textareaRef} />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 자주 사용하는 ref 타입",
    "",
    "| HTML 요소 | TypeScript 타입 |",
    "|-----------|----------------|",
    "| `<input>` | `HTMLInputElement` |",
    "| `<div>` | `HTMLDivElement` |",
    "| `<button>` | `HTMLButtonElement` |",
    "| `<canvas>` | `HTMLCanvasElement` |",
    "| `<video>` | `HTMLVideoElement` |",
    "| `<textarea>` | `HTMLTextAreaElement` |",
    "| `<form>` | `HTMLFormElement` |",
    "| `<img>` | `HTMLImageElement` |",
    "| `<a>` | `HTMLAnchorElement` |",
    "| `<select>` | `HTMLSelectElement` |",
    "",
    "### 스크롤 제어 예제",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useRef } from 'react';",
    "",
    "function ScrollBox() {",
    "  const topRef = useRef(null);",
    "  const bottomRef = useRef(null);",
    "",
    "  const scrollToTop = () => {",
    "    topRef.current.scrollIntoView({ behavior: 'smooth' });",
    "  };",
    "",
    "  const scrollToBottom = () => {",
    "    bottomRef.current.scrollIntoView({ behavior: 'smooth' });",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <div ref={topRef} />",
    "      <button onClick={scrollToBottom}>아래로 이동</button>",
    "      <div style={{ height: '150vh', background: 'linear-gradient(#e0e0e0, #9e9e9e)' }}>",
    "        <p>긴 콘텐츠 영역</p>",
    "      </div>",
    "      <button onClick={scrollToTop}>위로 이동</button>",
    "      <div ref={bottomRef} />",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### 값 저장용 ref (리렌더링 없이)",
    "",
    "`useRef`는 DOM 접근뿐 아니라 **리렌더링 없이 값을 유지**할 때도 사용합니다.",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState, useRef, useEffect } from 'react';",
    "",
    "function RenderCounter() {",
    "  const [count, setCount] = useState(0);",
    "  const renderCount = useRef(0);",
    "  const prevCount = useRef(0);",
    "",
    "  useEffect(() => {",
    "    renderCount.current += 1;",
    "    prevCount.current = count;",
    "  });",
    "",
    "  return (",
    "    <div>",
    "      <p>현재 값: {count}</p>",
    "      <p>이전 값: {prevCount.current}</p>",
    "      <p>렌더링 횟수: {renderCount.current}</p>",
    "      <button onClick={() => setCount(count + 1)}>+1</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState, useRef, useEffect } from 'react';",
    "",
    "function RenderCounter(): JSX.Element {",
    "  const [count, setCount] = useState(0);",
    "  const renderCount = useRef<number>(0);",
    "  const prevCount = useRef<number>(0);",
    "",
    "  useEffect(() => {",
    "    renderCount.current += 1;",
    "    prevCount.current = count;",
    "  });",
    "",
    "  return (",
    "    <div>",
    "      <p>현재 값: {count}</p>",
    "      <p>이전 값: {prevCount.current}</p>",
    "      <p>렌더링 횟수: {renderCount.current}</p>",
    "      <button onClick={() => setCount(count + 1)}>+1</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### useState vs useRef",
    "",
    "| 구분 | useState | useRef |",
    "|------|----------|--------|",
    "| 값 변경 시 | 리렌더링 **발생** | 리렌더링 **없음** |",
    "| 값 접근 | 직접 (`count`) | `.current` (`ref.current`) |",
    "| 주요 용도 | UI에 표시할 데이터 | DOM 참조, 타이머 ID, 이전 값 |",
    "| 초기화 시점 | 매 렌더링마다 유지 | 마운트~언마운트까지 유지 |",
    "",
    "### forwardRef - 자식 컴포넌트의 DOM 접근",
    "",
    "일반적으로 `ref`는 자식 컴포넌트에 props로 전달할 수 없습니다. `forwardRef`로 감싸면 부모가 자식의 DOM에 접근할 수 있습니다.",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useRef, forwardRef } from 'react';",
    "",
    "// forwardRef로 ref를 받을 수 있게 함",
    "const CustomInput = forwardRef(function CustomInput({ label, ...props }, ref) {",
    "  return (",
    "    <label>",
    "      {label}",
    "      <input ref={ref} {...props} style={{",
    "        padding: '8px', border: '2px solid #3498db',",
    "        borderRadius: '8px', marginLeft: '8px',",
    "      }} />",
    "    </label>",
    "  );",
    "});",
    "",
    "function App() {",
    "  const inputRef = useRef(null);",
    "",
    "  const handleClick = () => {",
    "    inputRef.current.focus();",
    "    inputRef.current.style.borderColor = '#e74c3c';",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <CustomInput ref={inputRef} label=\"이름\" placeholder=\"이름 입력\" />",
    "      <button onClick={handleClick}>포커스</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useRef, forwardRef, type ComponentPropsWithoutRef } from 'react';",
    "",
    "interface CustomInputProps extends ComponentPropsWithoutRef<'input'> {",
    "  label: string;",
    "}",
    "",
    "const CustomInput = forwardRef<HTMLInputElement, CustomInputProps>(",
    "  function CustomInput({ label, ...props }, ref) {",
    "    return (",
    "      <label>",
    "        {label}",
    "        <input ref={ref} {...props} style={{",
    "          padding: '8px', border: '2px solid #3498db',",
    "          borderRadius: '8px', marginLeft: '8px',",
    "        }} />",
    "      </label>",
    "    );",
    "  }",
    ");",
    "",
    "function App(): JSX.Element {",
    "  const inputRef = useRef<HTMLInputElement>(null);",
    "",
    "  const handleClick = (): void => {",
    "    inputRef.current?.focus();",
    "  };",
    "",
    "  return (",
    "    <div>",
    "      <CustomInput ref={inputRef} label=\"이름\" placeholder=\"이름 입력\" />",
    "      <button onClick={handleClick}>포커스</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### useImperativeHandle - 부모에 노출할 메서드 제한",
    "",
    "`forwardRef`와 함께 사용하면 부모에게 **특정 메서드만 노출**할 수 있습니다.",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useRef, forwardRef, useImperativeHandle, useState } from 'react';",
    "",
    "const FancyInput = forwardRef(function FancyInput(props, ref) {",
    "  const inputRef = useRef(null);",
    "  const [value, setValue] = useState('');",
    "",
    "  useImperativeHandle(ref, () => ({",
    "    focus: () => inputRef.current.focus(),",
    "    clear: () => setValue(''),",
    "    getValue: () => value,",
    "  }));",
    "",
    "  return (",
    "    <input",
    "      ref={inputRef}",
    "      value={value}",
    "      onChange={(e) => setValue(e.target.value)}",
    "      placeholder=\"입력\"",
    "    />",
    "  );",
    "});",
    "",
    "function App() {",
    "  const fancyRef = useRef(null);",
    "",
    "  return (",
    "    <div>",
    "      <FancyInput ref={fancyRef} />",
    "      <button onClick={() => fancyRef.current.focus()}>포커스</button>",
    "      <button onClick={() => fancyRef.current.clear()}>비우기</button>",
    "      <button onClick={() => alert(fancyRef.current.getValue())}>값 확인</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useRef, forwardRef, useImperativeHandle, useState } from 'react';",
    "",
    "interface FancyInputHandle {",
    "  focus: () => void;",
    "  clear: () => void;",
    "  getValue: () => string;",
    "}",
    "",
    "const FancyInput = forwardRef<FancyInputHandle>(function FancyInput(_props, ref) {",
    "  const inputRef = useRef<HTMLInputElement>(null);",
    "  const [value, setValue] = useState('');",
    "",
    "  useImperativeHandle(ref, () => ({",
    "    focus: () => inputRef.current?.focus(),",
    "    clear: () => setValue(''),",
    "    getValue: () => value,",
    "  }));",
    "",
    "  return (",
    "    <input",
    "      ref={inputRef}",
    "      value={value}",
    "      onChange={(e) => setValue(e.target.value)}",
    "      placeholder=\"입력\"",
    "    />",
    "  );",
    "});",
    "",
    "function App(): JSX.Element {",
    "  const fancyRef = useRef<FancyInputHandle>(null);",
    "",
    "  return (",
    "    <div>",
    "      <FancyInput ref={fancyRef} />",
    "      <button onClick={() => fancyRef.current?.focus()}>포커스</button>",
    "      <button onClick={() => fancyRef.current?.clear()}>비우기</button>",
    "      <button onClick={() => alert(fancyRef.current?.getValue())}>값 확인</button>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "> `useImperativeHandle`로 `focus`, `clear`, `getValue`만 노출하고 나머지 DOM API는 숨깁니다. 컴포넌트의 내부 구현을 캡슐화하는 데 유용합니다.",
    "",
    "### 콜백 ref",
    "",
    "ref 속성에 **함수를 전달**하면 DOM 노드가 마운트/언마운트될 때 호출됩니다.",
    "",
    "**JavaScript**",
    "```jsx",
    "import { useState, useCallback } from 'react';",
    "",
    "function MeasuredBox() {",
    "  const [height, setHeight] = useState(0);",
    "",
    "  const measuredRef = useCallback((node) => {",
    "    if (node !== null) {",
    "      setHeight(node.getBoundingClientRect().height);",
    "    }",
    "  }, []);",
    "",
    "  return (",
    "    <div>",
    "      <div ref={measuredRef} style={{ padding: '20px', background: '#f0f0f0' }}>",
    "        <p>이 박스의 높이가 측정됩니다.</p>",
    "        <p>Lorem ipsum dolor sit amet.</p>",
    "      </div>",
    "      <p>측정된 높이: {Math.round(height)}px</p>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { useState, useCallback } from 'react';",
    "",
    "function MeasuredBox(): JSX.Element {",
    "  const [height, setHeight] = useState(0);",
    "",
    "  const measuredRef = useCallback((node: HTMLDivElement | null) => {",
    "    if (node !== null) {",
    "      setHeight(node.getBoundingClientRect().height);",
    "    }",
    "  }, []);",
    "",
    "  return (",
    "    <div>",
    "      <div ref={measuredRef} style={{ padding: '20px', background: '#f0f0f0' }}>",
    "        <p>이 박스의 높이가 측정됩니다.</p>",
    "        <p>Lorem ipsum dolor sit amet.</p>",
    "      </div>",
    "      <p>측정된 높이: {Math.round(height)}px</p>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### ref 사용 시 주의사항",
    "",
    "| 주의사항 | 설명 |",
    "|---------|------|",
    "| 렌더링 중 접근 금지 | `ref.current`는 렌더링 중이 아닌 **이벤트 핸들러나 useEffect**에서 접근 |",
    "| null 체크 필수 (TS) | 초기값이 null이므로 `ref.current?.method()` 사용 |",
    "| DOM 조작 최소화 | React가 관리하는 DOM을 직접 변경하면 충돌 가능 |",
    "| 남용 금지 | 선언적으로 해결할 수 있으면 ref 대신 state와 props 사용 |",
    "",
    "---",
    "",
    "## 3. children - 컴포넌트 합성",
    "",
    "### children이란?",
    "",
    "`children`은 컴포넌트의 **여는 태그와 닫는 태그 사이에 넣은 내용**이 자동으로 전달되는 특수 prop입니다.",
    "",
    "### 기본 사용법",
    "",
    "**JavaScript**",
    "```jsx",
    "function Card({ title, children }) {",
    "  return (",
    "    <div style={{",
    "      border: '2px solid #3498db',",
    "      borderRadius: '12px',",
    "      overflow: 'hidden',",
    "      margin: '12px',",
    "    }}>",
    "      <div style={{ background: '#3498db', color: 'white', padding: '12px 16px' }}>",
    "        <h3 style={{ margin: 0 }}>{title}</h3>",
    "      </div>",
    "      <div style={{ padding: '16px' }}>",
    "        {children}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <div>",
    "      <Card title=\"공지사항\">",
    "        <p>서버 점검 안내</p>",
    "        <p>3월 5일 02:00~06:00</p>",
    "      </Card>",
    "      <Card title=\"오늘의 할 일\">",
    "        <ul>",
    "          <li>React 공부</li>",
    "          <li>운동</li>",
    "        </ul>",
    "      </Card>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import type { ReactNode } from 'react';",
    "",
    "interface CardProps {",
    "  title: string;",
    "  children: ReactNode;",
    "}",
    "",
    "function Card({ title, children }: CardProps): JSX.Element {",
    "  return (",
    "    <div style={{",
    "      border: '2px solid #3498db',",
    "      borderRadius: '12px',",
    "      overflow: 'hidden',",
    "      margin: '12px',",
    "    }}>",
    "      <div style={{ background: '#3498db', color: 'white', padding: '12px 16px' }}>",
    "        <h3 style={{ margin: 0 }}>{title}</h3>",
    "      </div>",
    "      <div style={{ padding: '16px' }}>",
    "        {children}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### children이 될 수 있는 것들",
    "",
    "| 종류 | 예시 |",
    "|------|------|",
    "| JSX 요소 | `<Card><p>텍스트</p></Card>` |",
    "| 문자열 | `<Card>안녕하세요</Card>` |",
    "| 숫자 | `<Card>{42}</Card>` |",
    "| 배열 | `<Card>{[<p key=\"1\">A</p>, <p key=\"2\">B</p>]}</Card>` |",
    "| 컴포넌트 | `<Card><UserProfile /></Card>` |",
    "| null / boolean | 렌더링되지 않음 (조건부 렌더링에 활용) |",
    "| Fragment | `<Card><>여러 요소</></Card>` |",
    "",
    "### children 타입 선택 가이드 (TypeScript)",
    "",
    "| 타입 | 허용 범위 | 사용 시점 |",
    "|------|----------|----------|",
    "| `ReactNode` | JSX, 문자열, 숫자, null, undefined, boolean | 가장 유연 (대부분의 경우) |",
    "| `ReactElement` | JSX 요소만 (`<div>`, `<Comp />`) | JSX만 받아야 할 때 |",
    "| `string` | 문자열만 | 텍스트만 받을 때 |",
    "| `never` | children 불허 | 자식 컴포넌트 없이 사용할 때 |",
    "",
    "### 레이아웃 합성 패턴",
    "",
    "children을 활용한 **슬롯 패턴**으로 유연한 레이아웃을 구성합니다.",
    "",
    "**JavaScript**",
    "```jsx",
    "function PageLayout({ header, sidebar, children, footer }) {",
    "  return (",
    "    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>",
    "      <header style={{ background: '#2c3e50', color: 'white', padding: '16px' }}>",
    "        {header}",
    "      </header>",
    "      <div style={{ display: 'flex', flex: 1 }}>",
    "        {sidebar && (",
    "          <aside style={{ width: '220px', background: '#ecf0f1', padding: '16px' }}>",
    "            {sidebar}",
    "          </aside>",
    "        )}",
    "        <main style={{ flex: 1, padding: '24px' }}>",
    "          {children}",
    "        </main>",
    "      </div>",
    "      {footer && (",
    "        <footer style={{ background: '#2c3e50', color: 'white', padding: '16px', textAlign: 'center' }}>",
    "          {footer}",
    "        </footer>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "function App() {",
    "  return (",
    "    <PageLayout",
    "      header={<h1>My App</h1>}",
    "      sidebar={",
    "        <nav>",
    "          <ul style={{ listStyle: 'none', padding: 0 }}>",
    "            <li>홈</li>",
    "            <li>소개</li>",
    "            <li>연락처</li>",
    "          </ul>",
    "        </nav>",
    "      }",
    "      footer={<p>© 2026 My App</p>}",
    "    >",
    "      <h2>메인 콘텐츠</h2>",
    "      <p>본문 내용이 여기에 들어갑니다.</p>",
    "    </PageLayout>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import type { ReactNode } from 'react';",
    "",
    "interface PageLayoutProps {",
    "  header: ReactNode;",
    "  sidebar?: ReactNode;",
    "  children: ReactNode;",
    "  footer?: ReactNode;",
    "}",
    "",
    "function PageLayout({ header, sidebar, children, footer }: PageLayoutProps): JSX.Element {",
    "  return (",
    "    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>",
    "      <header style={{ background: '#2c3e50', color: 'white', padding: '16px' }}>",
    "        {header}",
    "      </header>",
    "      <div style={{ display: 'flex', flex: 1 }}>",
    "        {sidebar && (",
    "          <aside style={{ width: '220px', background: '#ecf0f1', padding: '16px' }}>",
    "            {sidebar}",
    "          </aside>",
    "        )}",
    "        <main style={{ flex: 1, padding: '24px' }}>",
    "          {children}",
    "        </main>",
    "      </div>",
    "      {footer && (",
    "        <footer style={{ background: '#2c3e50', color: 'white', padding: '16px', textAlign: 'center' }}>",
    "          {footer}",
    "        </footer>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "### Compound Component 패턴",
    "",
    "children과 Context를 조합하면 **관련 컴포넌트를 하나의 API로 묶는** Compound Component 패턴을 만들 수 있습니다.",
    "",
    "**JavaScript**",
    "```jsx",
    "import { createContext, useContext, useState } from 'react';",
    "",
    "const AccordionContext = createContext(null);",
    "",
    "function Accordion({ children }) {",
    "  const [openIndex, setOpenIndex] = useState(null);",
    "  return (",
    "    <AccordionContext.Provider value={{ openIndex, setOpenIndex }}>",
    "      <div style={{ border: '1px solid #ddd', borderRadius: '8px', overflow: 'hidden' }}>",
    "        {children}",
    "      </div>",
    "    </AccordionContext.Provider>",
    "  );",
    "}",
    "",
    "function AccordionItem({ index, title, children }) {",
    "  const { openIndex, setOpenIndex } = useContext(AccordionContext);",
    "  const isOpen = openIndex === index;",
    "",
    "  return (",
    "    <div>",
    "      <button",
    "        onClick={() => setOpenIndex(isOpen ? null : index)}",
    "        style={{",
    "          width: '100%', padding: '12px 16px', textAlign: 'left',",
    "          background: isOpen ? '#3498db' : '#f8f9fa',",
    "          color: isOpen ? 'white' : '#333',",
    "          border: 'none', borderBottom: '1px solid #ddd',",
    "          cursor: 'pointer', fontSize: '16px',",
    "        }}",
    "      >",
    "        {isOpen ? '▼' : '▶'} {title}",
    "      </button>",
    "      {isOpen && (",
    "        <div style={{ padding: '16px', background: 'white' }}>",
    "          {children}",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "Accordion.Item = AccordionItem;",
    "",
    "// 사용",
    "function App() {",
    "  return (",
    "    <Accordion>",
    "      <Accordion.Item index={0} title=\"React란?\">",
    "        <p>UI를 만들기 위한 JavaScript 라이브러리입니다.</p>",
    "      </Accordion.Item>",
    "      <Accordion.Item index={1} title=\"Props란?\">",
    "        <p>부모에서 자식으로 데이터를 전달하는 메커니즘입니다.</p>",
    "      </Accordion.Item>",
    "      <Accordion.Item index={2} title=\"State란?\">",
    "        <p>컴포넌트 내부에서 관리하는 변경 가능한 데이터입니다.</p>",
    "      </Accordion.Item>",
    "    </Accordion>",
    "  );",
    "}",
    "```",
    "",
    "**TypeScript**",
    "```tsx",
    "import { createContext, useContext, useState, type ReactNode, type Dispatch, type SetStateAction } from 'react';",
    "",
    "interface AccordionContextType {",
    "  openIndex: number | null;",
    "  setOpenIndex: Dispatch<SetStateAction<number | null>>;",
    "}",
    "",
    "const AccordionContext = createContext<AccordionContextType | undefined>(undefined);",
    "",
    "function useAccordion(): AccordionContextType {",
    "  const context = useContext(AccordionContext);",
    "  if (!context) throw new Error('useAccordion must be used within Accordion');",
    "  return context;",
    "}",
    "",
    "interface AccordionProps {",
    "  children: ReactNode;",
    "}",
    "",
    "function Accordion({ children }: AccordionProps): JSX.Element {",
    "  const [openIndex, setOpenIndex] = useState<number | null>(null);",
    "  return (",
    "    <AccordionContext.Provider value={{ openIndex, setOpenIndex }}>",
    "      <div style={{ border: '1px solid #ddd', borderRadius: '8px', overflow: 'hidden' }}>",
    "        {children}",
    "      </div>",
    "    </AccordionContext.Provider>",
    "  );",
    "}",
    "",
    "interface AccordionItemProps {",
    "  index: number;",
    "  title: string;",
    "  children: ReactNode;",
    "}",
    "",
    "function AccordionItem({ index, title, children }: AccordionItemProps): JSX.Element {",
    "  const { openIndex, setOpenIndex } = useAccordion();",
    "  const isOpen = openIndex === index;",
    "",
    "  return (",
    "    <div>",
    "      <button",
    "        onClick={() => setOpenIndex(isOpen ? null : index)}",
    "        style={{",
    "          width: '100%', padding: '12px 16px', textAlign: 'left',",
    "          background: isOpen ? '#3498db' : '#f8f9fa',",
    "          color: isOpen ? 'white' : '#333',",
    "          border: 'none', borderBottom: '1px solid #ddd',",
    "          cursor: 'pointer', fontSize: '16px',",
    "        }}",
    "      >",
    "        {isOpen ? '▼' : '▶'} {title}",
    "      </button>",
    "      {isOpen && (",
    "        <div style={{ padding: '16px', background: 'white' }}>",
    "          {children}",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "```",
    "",
    "---",
    "",
    "## 세 속성 비교 요약",
    "",
    "| 속성 | 역할 | props 접근 | 주요 API |",
    "|------|------|-----------|----------|",
    "| `key` | 리스트 요소 식별 | ❌ 불가 | - (React 내부) |",
    "| `ref` | DOM/컴포넌트 참조 | ❌ 불가 (forwardRef 필요) | `useRef`, `forwardRef`, `useImperativeHandle` |",
    "| `children` | 태그 사이 내용 전달 | ✅ `props.children` | `React.Children`, `ReactNode` |",
    "",
    "---",
    "",
    "### 요약",
    "`key`는 리스트의 각 요소를 고유하게 식별하여 효율적인 DOM 업데이트를 가능하게 하고, `ref`는 `useRef`와 `forwardRef`를 통해 DOM에 직접 접근하거나 리렌더링 없이 값을 유지합니다. `children`은 컴포넌트 태그 사이의 내용을 전달하여 유연한 합성 패턴을 만듭니다. 이 세 속성은 일반 props와 달리 React가 내부적으로 특별하게 처리하며, 각각의 용도를 이해하면 더 효율적이고 유연한 컴포넌트를 설계할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
