<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-websocket",
  title: "Spring Boot WebSocket 완전 정리 - STOMP, 실시간 채팅 구현까지",
  date: "2026-02-05",
  summary: "WebSocket의 개념, HTTP와의 차이, STOMP 프로토콜, SockJS, Spring Boot 연동, @MessageMapping, 실시간 채팅 구현, 1:1 메시지, 인증 연동까지 실전 예제로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","websocket","stomp","sockjs","realtime","chat","backend"],
  content: [
    "## WebSocket이란?",
    "",
    "WebSocket은 **클라이언트와 서버 간 양방향 통신**을 가능하게 하는 프로토콜입니다. HTTP와 달리 한 번 연결을 맺으면 **연결을 유지한 채** 양쪽에서 자유롭게 데이터를 주고받을 수 있습니다.",
    "",
    "### HTTP vs WebSocket 통신 비교",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant S as 서버",
    "",
    "    Note over C,S: ❌ HTTP 방식 (매번 새 연결)",
    "    C->>S: HTTP 요청 1 (새 연결)",
    "    S-->>C: 응답 1 (연결 종료)",
    "    C->>S: HTTP 요청 2 (새 연결)",
    "    S-->>C: 응답 2 (연결 종료)",
    "    C->>S: HTTP 요청 3 (새 연결)",
    "    S-->>C: 응답 3 (연결 종료)",
    "    Note over C,S: 서버가 먼저 데이터를 보낼 수 없음",
    "```",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant S as 서버",
    "",
    "    Note over C,S: ✅ WebSocket 방식 (연결 유지)",
    "    C->>S: HTTP 업그레이드 요청",
    "    S-->>C: 101 Switching Protocols",
    "    Note over C,S: WebSocket 연결 수립 ✅",
    "    C->>S: 메시지 전송",
    "    S->>C: 서버 푸시 (자유롭게)",
    "    C->>S: 메시지 전송",
    "    S->>C: 실시간 알림",
    "    S->>C: 데이터 업데이트",
    "    Note over C,S: 양방향 자유 통신 유지",
    "```",
    "",
    "### HTTP 폴링 vs WebSocket",
    "",
    "실시간 데이터를 받기 위한 HTTP 기반 접근 방식과 WebSocket을 비교합니다.",
    "",
    "| 방식 | 동작 | 장점 | 단점 |",
    "|------|------|------|------|",
    "| **Polling** | 일정 주기로 서버에 요청 | 구현 간단 | 불필요한 요청 다수, 지연 발생 |",
    "| **Long Polling** | 서버가 이벤트 발생 시까지 응답 보류 | Polling보다 효율적 | 연결 재수립 오버헤드 |",
    "| **SSE** | 서버 → 클라이언트 단방향 스트림 | 가벼움, 자동 재연결 | 단방향만 가능 |",
    "| **WebSocket** | 양방향 상시 연결 | **가장 빠른 실시간 통신** | 구현 복잡, 상태 관리 필요 |",
    "",
    "### WebSocket 주요 사용 사례",
    "",
    "- **실시간 채팅** (카카오톡, 슬랙)",
    "- **주식/암호화폐 시세** 실시간 업데이트",
    "- **온라인 게임** 멀티플레이어 통신",
    "- **협업 도구** (Google Docs 동시 편집)",
    "- **IoT 장치** 실시간 모니터링",
    "- **알림 시스템** 실시간 푸시 알림",
    "",
    "---",
    "",
    "## 프로젝트 설정 (IntelliJ 실습)",
    "",
    "### 1단계: 인텔리제이에서 프로젝트 만들기",
    "",
    "1. IntelliJ IDEA → **New Project** → **Spring Initializr** 선택",
    "2. 아래와 같이 설정:",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | `springboot_websocket_example` |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "3. Dependencies 선택:",
    "   - **Lombok**",
    "   - **Spring Web**",
    "   - **WebSocket**",
    "",
    "4. **Create** 클릭 → 프로젝트 생성 완료",
    "",
    "### 2단계: build.gradle 전체 코드",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-websocket'",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "### 3단계: 소스 코드 작성",
    "",
    "#### DemoApplication.java",
    "",
    "`src/main/java/com/example/demo/DemoApplication.java`",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "#### WebSocketConfig.java",
    "",
    "`src/main/java/com/example/demo/WebSocketConfig.java` — STOMP 메시지 브로커와 엔드포인트를 설정합니다.",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.context.annotation.Configuration;",
    "import org.springframework.messaging.simp.config.MessageBrokerRegistry;",
    "import org.springframework.web.socket.config.annotation.EnableWebSocketMessageBroker;",
    "import org.springframework.web.socket.config.annotation.StompEndpointRegistry;",
    "import org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer;",
    "",
    "@Configuration",
    "@EnableWebSocketMessageBroker",
    "public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {",
    "",
    "    @Override",
    "    public void configureMessageBroker(MessageBrokerRegistry config) {",
    "        config.enableSimpleBroker(\"/topic\");",
    "        config.setApplicationDestinationPrefixes(\"/app\");",
    "    }",
    "",
    "    @Override",
    "    public void registerStompEndpoints(StompEndpointRegistry registry) {",
    "        registry.addEndpoint(\"/ws\").withSockJS();",
    "    }",
    "}",
    "```",
    "",
    "| 메서드 | 설명 |",
    "|--------|------|",
    "| `enableSimpleBroker(\"/topic\")` | 구독 경로 설정 — 서버가 클라이언트에게 메시지를 보내는 prefix |",
    "| `setApplicationDestinationPrefixes(\"/app\")` | 클라이언트가 서버로 보내는 메시지의 prefix |",
    "| `addEndpoint(\"/ws\").withSockJS()` | WebSocket 핸드셰이크 엔드포인트 + SockJS 폴백 |",
    "",
    "#### ChatMessage.java",
    "",
    "`src/main/java/com/example/demo/ChatMessage.java` — 채팅 메시지 DTO입니다.",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import lombok.AllArgsConstructor;",
    "import lombok.Getter;",
    "import lombok.NoArgsConstructor;",
    "import lombok.Setter;",
    "",
    "@Getter",
    "@Setter",
    "@NoArgsConstructor",
    "@AllArgsConstructor",
    "public class ChatMessage {",
    "    private String sender;",
    "    private String content;",
    "}",
    "```",
    "",
    "#### ChatController.java",
    "",
    "`src/main/java/com/example/demo/ChatController.java` — 클라이언트 메시지를 받아 구독자 전원에게 브로드캐스트합니다.",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.messaging.handler.annotation.MessageMapping;",
    "import org.springframework.messaging.handler.annotation.SendTo;",
    "import org.springframework.stereotype.Controller;",
    "",
    "@Controller",
    "public class ChatController {",
    "",
    "    @MessageMapping(\"/chat\")",
    "    @SendTo(\"/topic/messages\")",
    "    public ChatMessage send(ChatMessage message) {",
    "        return message;",
    "    }",
    "}",
    "```",
    "",
    "- `@MessageMapping(\"/chat\")` → 클라이언트가 `/app/chat`으로 보낸 메시지를 이 메서드가 처리",
    "- `@SendTo(\"/topic/messages\")` → 처리 결과를 `/topic/messages` 구독자 전원에게 전송",
    "",
    "#### index.html (채팅 UI)",
    "",
    "`src/main/resources/static/index.html` — SockJS + STOMP.js를 사용한 간단한 채팅 화면입니다.",
    "",
    "```html",
    "<!DOCTYPE html>",
    "<html lang=\"ko\">",
    "<head>",
    "    <meta charset=\"UTF-8\">",
    "    <title>WebSocket 채팅</title>",
    "    \x3Cscript src=\"https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js\">\x3C/script>",
    "    \x3Cscript src=\"https://cdn.jsdelivr.net/npm/stompjs@2.3.3/lib/stomp.min.js\">\x3C/script>",
    "    <style>",
    "        body { font-family: sans-serif; max-width: 600px; margin: 40px auto; }",
    "        #messages { border: 1px solid #ccc; height: 300px; overflow-y: auto; padding: 10px; margin-bottom: 10px; }",
    "        #messages div { margin: 4px 0; }",
    "        .input-area { display: flex; gap: 8px; }",
    "        .input-area input { flex: 1; padding: 8px; }",
    "        .input-area button { padding: 8px 16px; cursor: pointer; }",
    "    </style>",
    "</head>",
    "<body>",
    "    <h2>실시간 채팅</h2>",
    "    <div id=\"messages\"></div>",
    "    <div class=\"input-area\">",
    "        <input id=\"sender\" placeholder=\"이름\" style=\"width:100px;flex:none;\">",
    "        <input id=\"content\" placeholder=\"메시지 입력...\" onkeypress=\"if(event.key==='Enter') send()\">",
    "        <button onclick=\"send()\">전송</button>",
    "    </div>",
    "",
    "    \x3Cscript>",
    "        const sock = new SockJS('/ws');",
    "        const client = Stomp.over(sock);",
    "        client.debug = null;",
    "",
    "        client.connect({}, function() {",
    "            client.subscribe('/topic/messages', function(msg) {",
    "                const data = JSON.parse(msg.body);",
    "                const div = document.createElement('div');",
    "                div.textContent = data.sender + ': ' + data.content;",
    "                document.getElementById('messages').appendChild(div);",
    "                div.scrollIntoView();",
    "            });",
    "        });",
    "",
    "        function send() {",
    "            const sender = document.getElementById('sender').value;",
    "            const content = document.getElementById('content').value;",
    "            if (!sender || !content) return;",
    "            client.send('/app/chat', {}, JSON.stringify({ sender, content }));",
    "            document.getElementById('content').value = '';",
    "        }",
    "    \x3C/script>",
    "</body>",
    "</html>",
    "```",
    "",
    "### 4단계: 실행 및 테스트",
    "",
    "1. `DemoApplication.java`를 실행합니다 (**Run** 버튼 클릭)",
    "2. 브라우저 **탭 2개**에서 `http://localhost:8080` 접속",
    "3. 각 탭에서 이름을 입력하고 메시지를 전송",
    "4. **두 탭 모두에서 실시간으로 메시지가 표시**되면 성공!",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant T1 as 브라우저 탭 1",
    "    participant S as Spring Boot 서버",
    "    participant T2 as 브라우저 탭 2",
    "",
    "    T1->>S: CONNECT /ws (SockJS)",
    "    T2->>S: CONNECT /ws (SockJS)",
    "    T1->>S: SUBSCRIBE /topic/messages",
    "    T2->>S: SUBSCRIBE /topic/messages",
    "",
    "    T1->>S: SEND /app/chat {sender:'A', content:'안녕!'}",
    "    S->>T1: MESSAGE {sender:'A', content:'안녕!'}",
    "    S->>T2: MESSAGE {sender:'A', content:'안녕!'}",
    "",
    "    T2->>S: SEND /app/chat {sender:'B', content:'반가워!'}",
    "    S->>T1: MESSAGE {sender:'B', content:'반가워!'}",
    "    S->>T2: MESSAGE {sender:'B', content:'반가워!'}",
    "```",
    "",
    "> `spring-boot-starter-websocket`은 Spring WebSocket과 STOMP 관련 라이브러리를 모두 포함합니다.",
    "",
    "---",
    "",
    "## STOMP 프로토콜",
    "",
    "**STOMP**(Simple Text Oriented Messaging Protocol)는 WebSocket 위에서 동작하는 **텍스트 기반 메시지 프로토콜**입니다. WebSocket만으로는 메시지의 형식이나 라우팅 규칙이 없기 때문에, STOMP를 사용하면 **구조화된 메시지 전송**이 가능합니다.",
    "",
    "### STOMP 프레임 구조",
    "",
    "```text",
    "COMMAND",
    "header1:value1",
    "header2:value2",
    "",
    "Body^@",
    "```",
    "",
    "주요 COMMAND: `CONNECT`, `SUBSCRIBE`, `SEND`, `MESSAGE`, `DISCONNECT`",
    "",
    "### Pub/Sub 모델",
    "",
    "STOMP는 **발행/구독(Pub/Sub)** 패턴을 기반으로 동작합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    P1[발행자 A] -->|SEND /app/chat| B[메시지 브로커]",
    "    P2[발행자 B] -->|SEND /app/chat| B",
    "    B -->|MESSAGE /topic/room| S1[구독자 1]",
    "    B -->|MESSAGE /topic/room| S2[구독자 2]",
    "    B -->|MESSAGE /topic/room| S3[구독자 3]",
    "```",
    "",
    "### Destination 개념",
    "",
    "STOMP에서 메시지 경로(destination)는 용도에 따라 접두사(prefix)를 구분합니다.",
    "",
    "| Destination | 용도 | 설명 |",
    "|-------------|------|------|",
    "| `/app/...` | 애플리케이션 전송 | 클라이언트 → **서버 컨트롤러**로 전송 |",
    "| `/topic/...` | 브로드캐스트 구독 | **1:N** 구독 (채팅방, 공지 등) |",
    "| `/queue/...` | 개인 큐 구독 | **1:1** 메시지 (개인 알림 등) |",
    "| `/user/...` | 특정 사용자 전송 | 서버 → **특정 유저**에게 전송 |",
    "",
    "---",
    "",
    "## WebSocket 설정",
    "",
    "### WebSocketMessageBrokerConfigurer",
    "",
    "```java",
    "@Configuration",
    "@EnableWebSocketMessageBroker",
    "public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {",
    "",
    "    @Override",
    "    public void configureMessageBroker(MessageBrokerRegistry config) {",
    "        // 구독 경로 (서버 → 클라이언트)",
    "        config.enableSimpleBroker(\"/topic\", \"/queue\");",
    "",
    "        // 발행 경로 접두사 (클라이언트 → 서버)",
    "        config.setApplicationDestinationPrefixes(\"/app\");",
    "",
    "        // 특정 사용자 전송 시 접두사",
    "        config.setUserDestinationPrefix(\"/user\");",
    "    }",
    "",
    "    @Override",
    "    public void registerStompEndpoints(StompEndpointRegistry registry) {",
    "        registry.addEndpoint(\"/ws\")",
    "                .setAllowedOriginPatterns(\"*\")",
    "                .withSockJS(); // SockJS 폴백 지원",
    "    }",
    "}",
    "```",
    "",
    "### 설정 항목 설명",
    "",
    "| 메서드 | 설명 |",
    "|--------|------|",
    "| `enableSimpleBroker(\"/topic\", \"/queue\")` | 인메모리 브로커 활성화, 구독 경로 설정 |",
    "| `setApplicationDestinationPrefixes(\"/app\")` | 클라이언트가 서버로 보내는 메시지의 접두사 |",
    "| `setUserDestinationPrefix(\"/user\")` | 특정 사용자에게 보낼 때 사용하는 접두사 |",
    "| `addEndpoint(\"/ws\")` | WebSocket 핸드셰이크 엔드포인트 |",
    "| `withSockJS()` | WebSocket 미지원 브라우저를 위한 SockJS 폴백 |",
    "",
    "### SockJS란?",
    "",
    "SockJS는 **WebSocket을 지원하지 않는 환경**에서도 WebSocket과 유사한 통신을 가능하게 하는 JavaScript 라이브러리입니다. WebSocket 연결에 실패하면 자동으로 **폴링(Polling)** 또는 **스트리밍** 방식으로 폴백합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[SockJS 연결 시도] --> B{WebSocket 지원?}",
    "    B -->|Yes| C[WebSocket 사용]",
    "    B -->|No| D{XHR Streaming 지원?}",
    "    D -->|Yes| E[XHR Streaming]",
    "    D -->|No| F[XHR Polling 폴백]",
    "```",
    "",
    "---",
    "",
    "## 메시지 DTO",
    "",
    "클라이언트와 서버 간 주고받는 메시지를 담는 DTO를 정의합니다.",
    "",
    "```java",
    "public class ChatMessage {",
    "",
    "    public enum MessageType {",
    "        CHAT, JOIN, LEAVE",
    "    }",
    "",
    "    private MessageType type;",
    "    private String content;",
    "    private String sender;",
    "    private String roomId;",
    "",
    "    public ChatMessage() {}",
    "",
    "    public ChatMessage(MessageType type, String content, String sender) {",
    "        this.type = type;",
    "        this.content = content;",
    "        this.sender = sender;",
    "    }",
    "",
    "    // Getter & Setter",
    "    public MessageType getType() { return type; }",
    "    public void setType(MessageType type) { this.type = type; }",
    "    public String getContent() { return content; }",
    "    public void setContent(String content) { this.content = content; }",
    "    public String getSender() { return sender; }",
    "    public void setSender(String sender) { this.sender = sender; }",
    "    public String getRoomId() { return roomId; }",
    "    public void setRoomId(String roomId) { this.roomId = roomId; }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Controller - @MessageMapping",
    "",
    "### 기본 메시지 처리",
    "",
    "```java",
    "@Controller",
    "public class ChatController {",
    "",
    "    @MessageMapping(\"/chat.sendMessage\")",
    "    @SendTo(\"/topic/public\")",
    "    public ChatMessage sendMessage(ChatMessage chatMessage) {",
    "        return chatMessage;",
    "    }",
    "",
    "    @MessageMapping(\"/chat.addUser\")",
    "    @SendTo(\"/topic/public\")",
    "    public ChatMessage addUser(",
    "            ChatMessage chatMessage,",
    "            SimpMessageHeaderAccessor headerAccessor) {",
    "",
    "        headerAccessor.getSessionAttributes()",
    "                .put(\"username\", chatMessage.getSender());",
    "        return chatMessage;",
    "    }",
    "}",
    "```",
    "",
    "### 어노테이션 설명",
    "",
    "| 어노테이션 | 설명 |",
    "|-----------|------|",
    "| `@MessageMapping(\"/chat.sendMessage\")` | 클라이언트가 `/app/chat.sendMessage`로 보낸 메시지 처리 |",
    "| `@SendTo(\"/topic/public\")` | 처리 결과를 `/topic/public` 구독자 전원에게 브로드캐스트 |",
    "| `@DestinationVariable` | 경로 변수 추출 (예: `/app/chat/{roomId}`) |",
    "| `@Payload` | 메시지 본문 바인딩 |",
    "| `@Header` | STOMP 헤더 값 추출 |",
    "",
    "### @DestinationVariable 사용",
    "",
    "```java",
    "@MessageMapping(\"/chat/{roomId}\")",
    "@SendTo(\"/topic/room/{roomId}\")",
    "public ChatMessage sendToRoom(",
    "        @DestinationVariable String roomId,",
    "        ChatMessage message) {",
    "",
    "    message.setRoomId(roomId);",
    "    return message;",
    "}",
    "```",
    "",
    "---",
    "",
    "## 실전: 채팅방 구현",
    "",
    "### 전체 메시지 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant U1 as 사용자 A",
    "    participant S as Spring Boot 서버",
    "    participant B as 메시지 브로커",
    "    participant U2 as 사용자 B",
    "    participant U3 as 사용자 C",
    "",
    "    Note over U1,U3: 1. 연결 및 구독",
    "    U1->>S: CONNECT /ws (SockJS)",
    "    U2->>S: CONNECT /ws",
    "    U3->>S: CONNECT /ws",
    "    U1->>B: SUBSCRIBE /topic/room/1",
    "    U2->>B: SUBSCRIBE /topic/room/1",
    "    U3->>B: SUBSCRIBE /topic/room/1",
    "",
    "    Note over U1,U3: 2. 입장 알림",
    "    U1->>S: SEND /app/chat.addUser (JOIN)",
    "    S->>B: ChatMessage {type:JOIN, sender:'A'}",
    "    B->>U1: MESSAGE (A님이 입장했습니다)",
    "    B->>U2: MESSAGE (A님이 입장했습니다)",
    "    B->>U3: MESSAGE (A님이 입장했습니다)",
    "",
    "    Note over U1,U3: 3. 메시지 전송",
    "    U1->>S: SEND /app/chat.sendMessage",
    "    S->>B: ChatMessage {type:CHAT, content:'안녕!'}",
    "    B->>U1: MESSAGE",
    "    B->>U2: MESSAGE",
    "    B->>U3: MESSAGE",
    "```",
    "",
    "### SimpMessagingTemplate을 이용한 메시지 전송",
    "",
    "`@SendTo` 대신 `SimpMessagingTemplate`을 사용하면 **비즈니스 로직 내에서 유연하게** 메시지를 보낼 수 있습니다.",
    "",
    "```java",
    "@Controller",
    "@RequiredArgsConstructor",
    "public class ChatRoomController {",
    "",
    "    private final SimpMessagingTemplate messagingTemplate;",
    "",
    "    @MessageMapping(\"/chat/{roomId}\")",
    "    public void sendMessage(",
    "            @DestinationVariable String roomId,",
    "            ChatMessage message) {",
    "",
    "        message.setRoomId(roomId);",
    "",
    "        // 특정 채팅방에만 전송",
    "        messagingTemplate.convertAndSend(",
    "                \"/topic/room/\" + roomId, message);",
    "    }",
    "",
    "    @MessageMapping(\"/chat/{roomId}/join\")",
    "    public void joinRoom(",
    "            @DestinationVariable String roomId,",
    "            ChatMessage message,",
    "            SimpMessageHeaderAccessor headerAccessor) {",
    "",
    "        headerAccessor.getSessionAttributes()",
    "                .put(\"username\", message.getSender());",
    "        headerAccessor.getSessionAttributes()",
    "                .put(\"roomId\", roomId);",
    "",
    "        message.setType(ChatMessage.MessageType.JOIN);",
    "        message.setContent(message.getSender() + \"님이 입장했습니다.\");",
    "",
    "        messagingTemplate.convertAndSend(",
    "                \"/topic/room/\" + roomId, message);",
    "    }",
    "}",
    "```",
    "",
    "### 서비스에서 메시지 전송",
    "",
    "컨트롤러가 아닌 서비스 계층에서도 `SimpMessagingTemplate`을 주입받아 메시지를 보낼 수 있습니다.",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class NotificationService {",
    "",
    "    private final SimpMessagingTemplate messagingTemplate;",
    "",
    "    public void notifyRoom(String roomId, String content) {",
    "        ChatMessage notification = new ChatMessage(",
    "                ChatMessage.MessageType.CHAT,",
    "                content,",
    "                \"SYSTEM\"",
    "        );",
    "        messagingTemplate.convertAndSend(",
    "                \"/topic/room/\" + roomId, notification);",
    "    }",
    "",
    "    public void notifyAllRooms(String content) {",
    "        ChatMessage notification = new ChatMessage(",
    "                ChatMessage.MessageType.CHAT,",
    "                content,",
    "                \"SYSTEM\"",
    "        );",
    "        messagingTemplate.convertAndSend(",
    "                \"/topic/public\", notification);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 1:1 메시지",
    "",
    "특정 사용자에게만 메시지를 보내려면 `convertAndSendToUser()`를 사용합니다.",
    "",
    "### 동작 원리",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant A as 사용자 A",
    "    participant S as 서버",
    "    participant B as 브로커",
    "    participant Target as 사용자 B",
    "",
    "    A->>S: SEND /app/chat.private (to: userB)",
    "    S->>B: convertAndSendToUser(\"userB\", \"/queue/messages\", msg)",
    "    Note over B: /user/userB/queue/messages 로 라우팅",
    "    B->>Target: MESSAGE (1:1 메시지)",
    "    Note over A: 사용자 A에게는 전달되지 않음",
    "```",
    "",
    "### 구현 코드",
    "",
    "```java",
    "@Controller",
    "@RequiredArgsConstructor",
    "public class PrivateMessageController {",
    "",
    "    private final SimpMessagingTemplate messagingTemplate;",
    "",
    "    @MessageMapping(\"/chat.private\")",
    "    public void sendPrivateMessage(@Payload PrivateMessage message,",
    "                                   Principal principal) {",
    "",
    "        message.setSender(principal.getName());",
    "",
    "        // 수신자에게 전송",
    "        messagingTemplate.convertAndSendToUser(",
    "                message.getRecipient(),",
    "                \"/queue/messages\",",
    "                message",
    "        );",
    "",
    "        // 발신자에게도 전송 (본인 화면 갱신용)",
    "        messagingTemplate.convertAndSendToUser(",
    "                principal.getName(),",
    "                \"/queue/messages\",",
    "                message",
    "        );",
    "    }",
    "}",
    "```",
    "",
    "### 1:1 메시지 DTO",
    "",
    "```java",
    "public class PrivateMessage {",
    "",
    "    private String sender;",
    "    private String recipient;",
    "    private String content;",
    "    private LocalDateTime timestamp;",
    "",
    "    // Getter & Setter",
    "    public String getSender() { return sender; }",
    "    public void setSender(String sender) { this.sender = sender; }",
    "    public String getRecipient() { return recipient; }",
    "    public void setRecipient(String recipient) { this.recipient = recipient; }",
    "    public String getContent() { return content; }",
    "    public void setContent(String content) { this.content = content; }",
    "    public LocalDateTime getTimestamp() { return timestamp; }",
    "    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }",
    "}",
    "```",
    "",
    "### 클라이언트 구독 (수신 측)",
    "",
    "1:1 메시지를 받으려면 클라이언트에서 `/user/queue/messages`를 구독해야 합니다.",
    "",
    "```javascript",
    "stompClient.subscribe('/user/queue/messages', function(message) {",
    "    const msg = JSON.parse(message.body);",
    "    console.log('1:1 메시지:', msg);",
    "});",
    "```",
    "",
    "> **핵심**: `convertAndSendToUser(\"userB\", \"/queue/messages\", msg)` 호출 시, 내부적으로 `/user/userB/queue/messages`로 변환되어 해당 사용자의 세션에만 전달됩니다.",
    "",
    "---",
    "",
    "## 이벤트 리스너",
    "",
    "WebSocket 연결/해제 이벤트를 감지하여 **접속자 관리**, **입퇴장 알림** 등을 구현할 수 있습니다.",
    "",
    "### SessionConnectEvent & SessionDisconnectEvent",
    "",
    "```java",
    "@Component",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class WebSocketEventListener {",
    "",
    "    private final SimpMessagingTemplate messagingTemplate;",
    "    private final Set<String> connectedUsers = ConcurrentHashMap.newKeySet();",
    "",
    "    @EventListener",
    "    public void handleWebSocketConnectListener(",
    "            SessionConnectEvent event) {",
    "",
    "        StimpHeaderAccessor headerAccessor =",
    "                StompHeaderAccessor.wrap(event.getMessage());",
    "",
    "        String sessionId = headerAccessor.getSessionId();",
    "        log.info(\"새 WebSocket 연결: sessionId={}\", sessionId);",
    "    }",
    "",
    "    @EventListener",
    "    public void handleWebSocketDisconnectListener(",
    "            SessionDisconnectEvent event) {",
    "",
    "        StompHeaderAccessor headerAccessor =",
    "                StompHeaderAccessor.wrap(event.getMessage());",
    "",
    "        String username = (String) headerAccessor",
    "                .getSessionAttributes().get(\"username\");",
    "        String roomId = (String) headerAccessor",
    "                .getSessionAttributes().get(\"roomId\");",
    "",
    "        if (username != null) {",
    "            connectedUsers.remove(username);",
    "            log.info(\"사용자 연결 해제: {}\", username);",
    "",
    "            ChatMessage leaveMessage = new ChatMessage(",
    "                    ChatMessage.MessageType.LEAVE,",
    "                    username + \"님이 퇴장했습니다.\",",
    "                    username",
    "            );",
    "",
    "            if (roomId != null) {",
    "                messagingTemplate.convertAndSend(",
    "                        \"/topic/room/\" + roomId, leaveMessage);",
    "            } else {",
    "                messagingTemplate.convertAndSend(",
    "                        \"/topic/public\", leaveMessage);",
    "            }",
    "        }",
    "    }",
    "",
    "    @EventListener",
    "    public void handleSessionSubscribeEvent(",
    "            SessionSubscribeEvent event) {",
    "",
    "        StompHeaderAccessor headerAccessor =",
    "                StompHeaderAccessor.wrap(event.getMessage());",
    "",
    "        log.info(\"구독: destination={}\",",
    "                headerAccessor.getDestination());",
    "    }",
    "}",
    "```",
    "",
    "### 접속자 관리 서비스",
    "",
    "```java",
    "@Service",
    "@Slf4j",
    "public class OnlineUserService {",
    "",
    "    private final Set<String> onlineUsers =",
    "            ConcurrentHashMap.newKeySet();",
    "",
    "    public void addUser(String username) {",
    "        onlineUsers.add(username);",
    "        log.info(\"온라인: {} (총 {}명)\",",
    "                username, onlineUsers.size());",
    "    }",
    "",
    "    public void removeUser(String username) {",
    "        onlineUsers.remove(username);",
    "        log.info(\"오프라인: {} (총 {}명)\",",
    "                username, onlineUsers.size());",
    "    }",
    "",
    "    public Set<String> getOnlineUsers() {",
    "        return Collections.unmodifiableSet(onlineUsers);",
    "    }",
    "",
    "    public boolean isOnline(String username) {",
    "        return onlineUsers.contains(username);",
    "    }",
    "",
    "    public int getOnlineCount() {",
    "        return onlineUsers.size();",
    "    }",
    "}",
    "```",
    "",
    "### 이벤트 종류 정리",
    "",
    "| 이벤트 | 발생 시점 | 용도 |",
    "|--------|----------|------|",
    "| `SessionConnectEvent` | STOMP CONNECT 프레임 처리 시 | 연결 로깅, 인증 확인 |",
    "| `SessionConnectedEvent` | 연결 완전 수립 후 | 접속자 목록 추가 |",
    "| `SessionSubscribeEvent` | SUBSCRIBE 프레임 처리 시 | 구독 추적 |",
    "| `SessionUnsubscribeEvent` | UNSUBSCRIBE 프레임 처리 시 | 구독 해제 추적 |",
    "| `SessionDisconnectEvent` | 연결 종료 시 | 퇴장 알림, 접속자 제거 |",
    "",
    "---",
    "",
    "## 프론트엔드 연동 (JavaScript)",
    "",
    "### SockJS + STOMP.js 설정",
    "",
    "```html",
    "<!DOCTYPE html>",
    "<html>",
    "<head>",
    "    <title>WebSocket 채팅</title>",
    "    \x3Cscript src=\"https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js\">\x3C/script>",
    "    \x3Cscript src=\"https://cdn.jsdelivr.net/npm/stompjs@2.3.3/lib/stomp.min.js\">\x3C/script>",
    "</head>",
    "<body>",
    "    <div id=\"chat-page\">",
    "        <div id=\"message-area\"></div>",
    "        <input type=\"text\" id=\"message-input\" placeholder=\"메시지 입력...\">",
    "        <button onclick=\"sendMessage()\">전송</button>",
    "    </div>",
    "",
    "    \x3Cscript>",
    "        let stompClient = null;",
    "        const username = prompt('사용자 이름을 입력하세요:');",
    "",
    "        function connect() {",
    "            const socket = new SockJS('/ws');",
    "            stompClient = Stomp.over(socket);",
    "",
    "            stompClient.connect({}, function(frame) {",
    "                console.log('Connected: ' + frame);",
    "",
    "                // 공개 채팅 구독",
    "                stompClient.subscribe('/topic/public',",
    "                    function(message) {",
    "                        showMessage(JSON.parse(message.body));",
    "                    }",
    "                );",
    "",
    "                // 1:1 메시지 구독",
    "                stompClient.subscribe('/user/queue/messages',",
    "                    function(message) {",
    "                        showMessage(JSON.parse(message.body));",
    "                    }",
    "                );",
    "",
    "                // 입장 알림",
    "                stompClient.send('/app/chat.addUser', {},",
    "                    JSON.stringify({",
    "                        sender: username,",
    "                        type: 'JOIN'",
    "                    })",
    "                );",
    "            });",
    "",
    "            stompClient.onStompError = function(frame) {",
    "                console.error('STOMP 에러:', frame);",
    "            };",
    "        }",
    "",
    "        function sendMessage() {",
    "            const input = document.getElementById('message-input');",
    "            if (input.value && stompClient) {",
    "                stompClient.send('/app/chat.sendMessage', {},",
    "                    JSON.stringify({",
    "                        sender: username,",
    "                        content: input.value,",
    "                        type: 'CHAT'",
    "                    })",
    "                );",
    "                input.value = '';",
    "            }",
    "        }",
    "",
    "        function showMessage(message) {",
    "            const area = document.getElementById('message-area');",
    "            const div = document.createElement('div');",
    "",
    "            if (message.type === 'JOIN') {",
    "                div.textContent = message.sender + '님이 입장했습니다.';",
    "                div.style.color = 'green';",
    "            } else if (message.type === 'LEAVE') {",
    "                div.textContent = message.sender + '님이 퇴장했습니다.';",
    "                div.style.color = 'red';",
    "            } else {",
    "                div.textContent = message.sender + ': ' + message.content;",
    "            }",
    "",
    "            area.appendChild(div);",
    "            area.scrollTop = area.scrollHeight;",
    "        }",
    "",
    "        connect();",
    "    \x3C/script>",
    "</body>",
    "</html>",
    "```",
    "",
    "### 연결 상태 관리 & 재연결",
    "",
    "```javascript",
    "let reconnectAttempts = 0;",
    "const maxReconnectAttempts = 5;",
    "",
    "function connect() {",
    "    const socket = new SockJS('/ws');",
    "    stompClient = Stomp.over(socket);",
    "    stompClient.debug = null; // 디버그 로그 비활성화",
    "",
    "    stompClient.connect({}, onConnected, onError);",
    "}",
    "",
    "function onConnected(frame) {",
    "    reconnectAttempts = 0;",
    "    console.log('연결 성공');",
    "    // 구독 설정...",
    "}",
    "",
    "function onError(error) {",
    "    console.error('연결 실패:', error);",
    "",
    "    if (reconnectAttempts < maxReconnectAttempts) {",
    "        reconnectAttempts++;",
    "        const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), 30000);",
    "        console.log(reconnectAttempts + '번째 재연결 시도... (' + delay + 'ms 후)');",
    "        setTimeout(connect, delay);",
    "    } else {",
    "        console.error('최대 재연결 횟수 초과');",
    "    }",
    "}",
    "```",
    "",
    "> **Exponential Backoff**: 재연결 간격을 1초, 2초, 4초, 8초... 최대 30초까지 점진적으로 늘려 서버 부하를 줄입니다.",
    "",
    "---",
    "",
    "## Spring Security 연동",
    "",
    "### WebSocket 보안 설정",
    "",
    "WebSocket 핸드셰이크는 HTTP 요청이므로 기존 Spring Security 설정이 적용됩니다.",
    "",
    "```java",
    "@Configuration",
    "@EnableWebSecurity",
    "public class SecurityConfig {",
    "",
    "    @Bean",
    "    public SecurityFilterChain filterChain(",
    "            HttpSecurity http) throws Exception {",
    "",
    "        http",
    "            .authorizeHttpRequests(auth -> auth",
    "                .requestMatchers(\"/ws/**\").authenticated()",
    "                .anyRequest().permitAll()",
    "            )",
    "            .formLogin(Customizer.withDefaults());",
    "",
    "        return http.build();",
    "    }",
    "}",
    "```",
    "",
    "### ChannelInterceptor로 STOMP 메시지 인증",
    "",
    "STOMP 메시지 단위에서 인증/인가를 적용하려면 `ChannelInterceptor`를 사용합니다.",
    "",
    "```java",
    "@Component",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class StompChannelInterceptor implements ChannelInterceptor {",
    "",
    "    private final JwtTokenProvider jwtTokenProvider;",
    "",
    "    @Override",
    "    public Message<?> preSend(",
    "            Message<?> message, MessageChannel channel) {",
    "",
    "        StompHeaderAccessor accessor =",
    "                MessageHeaderAccessor.getAccessor(",
    "                        message, StompHeaderAccessor.class);",
    "",
    "        if (StompCommand.CONNECT.equals(accessor.getCommand())) {",
    "            String token = accessor.getFirstNativeHeader(\"Authorization\");",
    "",
    "            if (token != null && token.startsWith(\"Bearer \")) {",
    "                token = token.substring(7);",
    "",
    "                if (jwtTokenProvider.validateToken(token)) {",
    "                    Authentication auth =",
    "                            jwtTokenProvider.getAuthentication(token);",
    "                    accessor.setUser(auth);",
    "                    log.info(\"WebSocket 인증 성공: {}\",",
    "                            auth.getName());",
    "                } else {",
    "                    log.warn(\"유효하지 않은 JWT 토큰\");",
    "                    throw new MessageDeliveryException(",
    "                            \"인증 실패\");",
    "                }",
    "            }",
    "        }",
    "",
    "        if (StompCommand.SUBSCRIBE.equals(accessor.getCommand())) {",
    "            String destination = accessor.getDestination();",
    "            Principal user = accessor.getUser();",
    "",
    "            if (destination != null",
    "                    && destination.startsWith(\"/topic/admin\")",
    "                    && !isAdmin(user)) {",
    "                throw new MessageDeliveryException(",
    "                        \"관리자 전용 채널입니다.\");",
    "            }",
    "        }",
    "",
    "        return message;",
    "    }",
    "",
    "    private boolean isAdmin(Principal user) {",
    "        if (user instanceof Authentication auth) {",
    "            return auth.getAuthorities().stream()",
    "                    .anyMatch(a -> a.getAuthority()",
    "                            .equals(\"ROLE_ADMIN\"));",
    "        }",
    "        return false;",
    "    }",
    "}",
    "```",
    "",
    "### ChannelInterceptor 등록",
    "",
    "```java",
    "@Configuration",
    "@EnableWebSocketMessageBroker",
    "@RequiredArgsConstructor",
    "public class WebSocketConfig",
    "        implements WebSocketMessageBrokerConfigurer {",
    "",
    "    private final StompChannelInterceptor stompChannelInterceptor;",
    "",
    "    @Override",
    "    public void configureMessageBroker(MessageBrokerRegistry config) {",
    "        config.enableSimpleBroker(\"/topic\", \"/queue\");",
    "        config.setApplicationDestinationPrefixes(\"/app\");",
    "        config.setUserDestinationPrefix(\"/user\");",
    "    }",
    "",
    "    @Override",
    "    public void registerStompEndpoints(StompEndpointRegistry registry) {",
    "        registry.addEndpoint(\"/ws\")",
    "                .setAllowedOriginPatterns(\"*\")",
    "                .withSockJS();",
    "    }",
    "",
    "    @Override",
    "    public void configureClientInboundChannel(",
    "            ChannelRegistration registration) {",
    "        registration.interceptors(stompChannelInterceptor);",
    "    }",
    "}",
    "```",
    "",
    "### 프론트엔드에서 JWT 토큰 전송",
    "",
    "```javascript",
    "const socket = new SockJS('/ws');",
    "stompClient = Stomp.over(socket);",
    "",
    "stompClient.connect(",
    "    { 'Authorization': 'Bearer ' + jwtToken },",
    "    function(frame) {",
    "        console.log('인증된 WebSocket 연결 성공');",
    "    },",
    "    function(error) {",
    "        console.error('인증 실패:', error);",
    "    }",
    ");",
    "```",
    "",
    "---",
    "",
    "## 주의사항 및 운영 팁",
    "",
    "### 스케일 아웃 시 외부 브로커",
    "",
    "인메모리 SimpleBroker는 **단일 서버**에서만 동작합니다. 서버를 여러 대로 확장(스케일 아웃)하면 서버 간 메시지가 공유되지 않습니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    subgraph 문제[❌ 인메모리 브로커 - 메시지 격리]",
    "        C1[클라이언트 A] --> S1[서버 1 - SimpleBroker]",
    "        C2[클라이언트 B] --> S2[서버 2 - SimpleBroker]",
    "        S1 -.->|메시지 공유 안됨| S2",
    "    end",
    "",
    "    subgraph 해결[✅ 외부 브로커 - 메시지 공유]",
    "        C3[클라이언트 A] --> S3[서버 1]",
    "        C4[클라이언트 B] --> S4[서버 2]",
    "        S3 --> RB[RabbitMQ / Redis Pub/Sub]",
    "        S4 --> RB",
    "    end",
    "```",
    "",
    "**외부 브로커 설정 (RabbitMQ):**",
    "",
    "```java",
    "@Override",
    "public void configureMessageBroker(MessageBrokerRegistry config) {",
    "    config.enableStompBrokerRelay(\"/topic\", \"/queue\")",
    "            .setRelayHost(\"localhost\")",
    "            .setRelayPort(61613)",
    "            .setClientLogin(\"guest\")",
    "            .setClientPasscode(\"guest\");",
    "",
    "    config.setApplicationDestinationPrefixes(\"/app\");",
    "}",
    "```",
    "",
    "### 운영 시 주의사항",
    "",
    "| 항목 | 설명 | 권장 사항 |",
    "|------|------|----------|",
    "| **메시지 크기** | 대용량 메시지는 성능 저하 유발 | 메시지 최대 크기 제한 (64KB 이하) |",
    "| **연결 수 관리** | 동시 접속이 많으면 메모리 부족 | 최대 연결 수 설정, 비활성 연결 타임아웃 |",
    "| **하트비트** | 연결 상태 확인 | 서버/클라이언트 heartbeat 설정 (10초/10초) |",
    "| **에러 처리** | 클라이언트 연결 실패 대비 | Exponential Backoff 재연결 |",
    "| **로깅** | 운영 환경 디버깅 | STOMP 프레임 로그 레벨 조절 |",
    "| **CORS** | 다른 도메인에서 접속 | `setAllowedOriginPatterns` 설정 |",
    "| **인증** | 미인증 접근 차단 | ChannelInterceptor로 STOMP 레벨 인증 |",
    "| **스케일 아웃** | 다중 서버 메시지 공유 | RabbitMQ / Redis Pub/Sub 외부 브로커 |",
    "",
    "### WebSocket 관련 application.yml 설정",
    "",
    "```yaml",
    "server:",
    "  servlet:",
    "    session:",
    "      timeout: 30m",
    "",
    "spring:",
    "  websocket:",
    "    max-text-message-buffer-size: 65536",
    "    max-binary-message-buffer-size: 65536",
    "",
    "logging:",
    "  level:",
    "    org.springframework.web.socket: INFO",
    "    org.springframework.messaging: INFO",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 개념 | 핵심 내용 |",
    "|------|----------|",
    "| **WebSocket** | HTTP와 달리 양방향 상시 연결, 실시간 통신에 최적 |",
    "| **STOMP** | WebSocket 위의 메시지 프로토콜, Pub/Sub 구조 |",
    "| **SockJS** | WebSocket 미지원 환경 폴백 (Polling, Streaming) |",
    "| **@MessageMapping** | 클라이언트 → 서버 메시지 처리 (컨트롤러) |",
    "| **@SendTo** | 처리 결과를 특정 destination으로 브로드캐스트 |",
    "| **SimpMessagingTemplate** | 서비스 계층에서 유연한 메시지 전송 |",
    "| **convertAndSendToUser** | 특정 사용자에게 1:1 메시지 전송 |",
    "| **이벤트 리스너** | 연결/해제/구독 이벤트 감지, 접속자 관리 |",
    "| **ChannelInterceptor** | STOMP 메시지 단위 인증/인가 |",
    "| **외부 브로커** | 스케일 아웃 시 RabbitMQ 등 연동 필수 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
