<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-mybatis",
  title: "Spring Boot + MyBatis 완전 정리 - 개념부터 실전 CRUD, 동적 쿼리까지",
  date: "2026-02-14",
  summary: "MyBatis의 개념, JPA와의 차이, Spring Boot 연동 설정, XML/어노테이션 매핑, CRUD 실전 예제, 동적 SQL, ResultMap, 페이징, TypeHandler까지 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","mybatis","sql","mapper","xml","backend"],
  content: [
    "## MyBatis란?",
    "",
    "**MyBatis**는 SQL을 직접 작성하면서 Java 객체와 매핑해주는 **SQL Mapper 프레임워크**입니다. JPA(ORM)처럼 SQL을 자동 생성하지 않고, **개발자가 SQL을 완전히 제어**합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Java 코드\"] --> B[\"MyBatis\"]",
    "    B --> C[\"SQL (XML / 어노테이션)\"]",
    "    C --> D[(\"DB\")]",
    "    D --> C",
    "    C --> B",
    "    B -->|ResultMap| A",
    "```",
    "",
    "---",
    "",
    "## MyBatis vs JPA 비교",
    "",
    "| 비교 | MyBatis | JPA (Hibernate) |",
    "|------|---------|----------------|",
    "| 유형 | **SQL Mapper** | **ORM** |",
    "| SQL 작성 | **개발자가 직접 작성** | 자동 생성 (JPQL, Querydsl) |",
    "| 학습 곡선 | SQL 알면 쉬움 | 영속성 컨텍스트, 지연 로딩 이해 필요 |",
    "| 복잡한 쿼리 | **자유롭게 작성** | 네이티브 쿼리 필요 |",
    "| DB 종속성 | SQL이 DB에 종속될 수 있음 | DB 독립적 |",
    "| 변경 감지 | 없음 (직접 UPDATE) | **Dirty Checking** |",
    "| 캐시 | 1차 캐시 (세션 단위) | 1차 + 2차 캐시 |",
    "| 적합 | 복잡한 SQL, 레거시 DB, 통계/리포트 | 도메인 중심, 빠른 개발 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A{\"어떤 기술을 선택?\"} -->|SQL 제어가 중요| B[\"MyBatis\"]",
    "    A -->|빠른 개발, 도메인 중심| C[\"JPA\"]",
    "    A -->|복잡한 통계/리포트 쿼리| B",
    "    A -->|레거시 DB 스키마| B",
    "    A -->|표준 CRUD 위주| C",
    "```",
    "",
    "---",
    "",
    "## 인텔리제이에서 프로젝트 만들기",
    "",
    "### Spring Initializr로 프로젝트 생성",
    "",
    "1. IntelliJ IDEA → **New Project** → **Spring Initializr** 선택",
    "2. 프로젝트 설정:",
    "",
    "| 항목 | 값 |",
    "|------|------|",
    "| Name | `springboot_mybatis_example` |",
    "| Language | Java |",
    "| Type | **Gradle - Groovy** |",
    "| JDK | **21** |",
    "",
    "3. **Dependencies** 추가:",
    "   - **Developer Tools**: Lombok",
    "   - **Web**: Spring Web",
    "   - **SQL**: MyBatis Framework, H2 Database",
    "",
    "4. **Create** 클릭 → 프로젝트 생성 완료",
    "",
    "---",
    "",
    "### build.gradle (전체)",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '1.0-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'",
    "    implementation 'org.springframework.boot:spring-boot-starter-validation'",
    "    runtimeOnly 'com.h2database:h2'",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "test {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "---",
    "",
    "### application.yml",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb",
    "    driver-class-name: org.h2.Driver",
    "    username: sa",
    "    password:",
    "  h2:",
    "    console:",
    "      enabled: true",
    "      path: /h2-console",
    "  sql:",
    "    init:",
    "      mode: always",
    "",
    "mybatis:",
    "  mapper-locations: classpath:mapper/**/*.xml",
    "  type-aliases-package: com.example.springboot_mybatis_example.domain",
    "  configuration:",
    "    map-underscore-to-camel-case: true",
    "```",
    "",
    "> `map-underscore-to-camel-case: true`를 설정하면 DB의 `created_at` 컬럼이 Java의 `createdAt` 필드에 자동 매핑됩니다.",
    "",
    "---",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "src/main/",
    "├── java/com/example/springboot_mybatis_example/",
    "│   ├── domain/",
    "│   │   └── Member.java",
    "│   ├── mapper/",
    "│   │   └── MemberMapper.java",
    "│   ├── service/",
    "│   │   └── MemberService.java",
    "│   ├── controller/",
    "│   │   └── MemberController.java",
    "│   ├── dto/",
    "│   │   ├── MemberCreateRequest.java",
    "│   │   ├── MemberUpdateRequest.java",
    "│   │   └── MemberResponse.java",
    "│   └── SpringbootMybatisExampleApplication.java",
    "└── resources/",
    "    ├── mapper/",
    "    │   └── MemberMapper.xml",
    "    ├── schema.sql",
    "    ├── data.sql",
    "    └── application.yml",
    "```",
    "",
    "---",
    "",
    "### schema.sql",
    "",
    "```sql",
    "CREATE TABLE member (",
    "    id          BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "    name        VARCHAR(50)  NOT NULL,",
    "    email       VARCHAR(100) NOT NULL UNIQUE,",
    "    age         INT,",
    "    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
    "    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    ");",
    "```",
    "",
    "### data.sql",
    "",
    "```sql",
    "INSERT INTO member (name, email, age) VALUES ('홍길동', 'hong@example.com', 25);",
    "INSERT INTO member (name, email, age) VALUES ('김영희', 'kim@example.com', 30);",
    "INSERT INTO member (name, email, age) VALUES ('이철수', 'lee@example.com', 28);",
    "```",
    "",
    "---",
    "",
    "## 전체 코드",
    "",
    "### SpringbootMybatisExampleApplication.java",
    "",
    "```java",
    "package com.example.springboot_mybatis_example;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class SpringbootMybatisExampleApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(SpringbootMybatisExampleApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### Member.java (도메인)",
    "",
    "```java",
    "package com.example.springboot_mybatis_example.domain;",
    "",
    "import lombok.*;",
    "import java.time.LocalDateTime;",
    "",
    "@Getter @Setter",
    "@NoArgsConstructor @AllArgsConstructor @Builder",
    "public class Member {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private Integer age;",
    "    private LocalDateTime createdAt;",
    "    private LocalDateTime updatedAt;",
    "}",
    "```",
    "",
    "> MyBatis에서는 `@Entity` 같은 JPA 어노테이션이 필요 없습니다. **순수 POJO**입니다.",
    "",
    "### MemberMapper.java (어노테이션 CRUD + XML 동적 SQL)",
    "",
    "```java",
    "package com.example.springboot_mybatis_example.mapper;",
    "",
    "import com.example.springboot_mybatis_example.domain.Member;",
    "import org.apache.ibatis.annotations.*;",
    "",
    "import java.util.List;",
    "import java.util.Optional;",
    "",
    "@Mapper",
    "public interface MemberMapper {",
    "",
    "    @Select(\"SELECT * FROM member ORDER BY id DESC\")",
    "    List<Member> findAll();",
    "",
    "    @Select(\"SELECT * FROM member WHERE id = #{id}\")",
    "    Optional<Member> findById(@Param(\"id\") Long id);",
    "",
    "    @Select(\"SELECT * FROM member WHERE email = #{email}\")",
    "    Optional<Member> findByEmail(@Param(\"email\") String email);",
    "",
    "    @Insert(\"INSERT INTO member (name, email, age) \" +",
    "            \"VALUES (#{name}, #{email}, #{age})\")",
    "    @Options(useGeneratedKeys = true, keyProperty = \"id\")",
    "    void insert(Member member);",
    "",
    "    @Update(\"UPDATE member SET name=#{name}, email=#{email}, \" +",
    "            \"age=#{age}, updated_at=CURRENT_TIMESTAMP WHERE id=#{id}\")",
    "    int update(Member member);",
    "",
    "    @Delete(\"DELETE FROM member WHERE id = #{id}\")",
    "    int deleteById(@Param(\"id\") Long id);",
    "",
    "    // XML 동적 SQL 메서드",
    "    List<Member> findByCondition(@Param(\"name\") String name,",
    "                                 @Param(\"minAge\") Integer minAge);",
    "",
    "    int insertBatch(@Param(\"list\") List<Member> members);",
    "}",
    "```",
    "",
    "> 단순 CRUD는 **어노테이션**으로, 복잡한 동적 쿼리는 **XML**로 작성합니다. 하나의 Mapper에서 두 방식을 혼합할 수 있습니다.",
    "",
    "### MemberMapper.xml (동적 SQL - if, where, foreach)",
    "",
    "```xml",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<!DOCTYPE mapper PUBLIC \"-//mybatis.org//DTD Mapper 3.0//EN\"",
    "        \"http://mybatis.org/dtd/mybatis-3-mapper.dtd\">",
    "",
    "<mapper namespace=\"com.example.springboot_mybatis_example.mapper.MemberMapper\">",
    "",
    "    <!-- 동적 조건 검색: <if> + <where> -->",
    "    <select id=\"findByCondition\" resultType=\"Member\">",
    "        SELECT * FROM member",
    "        <where>",
    "            <if test=\"name != null and name != ''\">",
    "                AND name LIKE CONCAT('%', #{name}, '%')",
    "            </if>",
    "            <if test=\"minAge != null\">",
    "                AND age &gt;= #{minAge}",
    "            </if>",
    "        </where>",
    "        ORDER BY id DESC",
    "    </select>",
    "",
    "    <!-- 배치 INSERT: <foreach> -->",
    "    <insert id=\"insertBatch\" parameterType=\"list\">",
    "        INSERT INTO member (name, email, age)",
    "        VALUES",
    "        <foreach collection=\"list\" item=\"member\" separator=\",\">",
    "            (#{member.name}, #{member.email}, #{member.age})",
    "        </foreach>",
    "    </insert>",
    "",
    "</mapper>",
    "```",
    "",
    "### MemberCreateRequest.java (DTO)",
    "",
    "```java",
    "package com.example.springboot_mybatis_example.dto;",
    "",
    "import jakarta.validation.constraints.Email;",
    "import jakarta.validation.constraints.NotBlank;",
    "import lombok.*;",
    "",
    "@Getter @Setter",
    "@NoArgsConstructor @AllArgsConstructor",
    "public class MemberCreateRequest {",
    "",
    "    @NotBlank(message = \"이름은 필수입니다\")",
    "    private String name;",
    "",
    "    @NotBlank(message = \"이메일은 필수입니다\")",
    "    @Email(message = \"올바른 이메일 형식이 아닙니다\")",
    "    private String email;",
    "",
    "    private Integer age;",
    "}",
    "```",
    "",
    "### MemberUpdateRequest.java (DTO)",
    "",
    "```java",
    "package com.example.springboot_mybatis_example.dto;",
    "",
    "import jakarta.validation.constraints.Email;",
    "import jakarta.validation.constraints.NotBlank;",
    "import lombok.*;",
    "",
    "@Getter @Setter",
    "@NoArgsConstructor @AllArgsConstructor",
    "public class MemberUpdateRequest {",
    "",
    "    @NotBlank(message = \"이름은 필수입니다\")",
    "    private String name;",
    "",
    "    @NotBlank(message = \"이메일은 필수입니다\")",
    "    @Email(message = \"올바른 이메일 형식이 아닙니다\")",
    "    private String email;",
    "",
    "    private Integer age;",
    "}",
    "```",
    "",
    "### MemberResponse.java (DTO)",
    "",
    "```java",
    "package com.example.springboot_mybatis_example.dto;",
    "",
    "import com.example.springboot_mybatis_example.domain.Member;",
    "import lombok.Builder;",
    "import lombok.Getter;",
    "",
    "import java.time.LocalDateTime;",
    "",
    "@Getter @Builder",
    "public class MemberResponse {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private Integer age;",
    "    private LocalDateTime createdAt;",
    "",
    "    public static MemberResponse from(Member member) {",
    "        return MemberResponse.builder()",
    "                .id(member.getId())",
    "                .name(member.getName())",
    "                .email(member.getEmail())",
    "                .age(member.getAge())",
    "                .createdAt(member.getCreatedAt())",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "### MemberService.java",
    "",
    "```java",
    "package com.example.springboot_mybatis_example.service;",
    "",
    "import com.example.springboot_mybatis_example.domain.Member;",
    "import com.example.springboot_mybatis_example.dto.MemberCreateRequest;",
    "import com.example.springboot_mybatis_example.dto.MemberResponse;",
    "import com.example.springboot_mybatis_example.dto.MemberUpdateRequest;",
    "import com.example.springboot_mybatis_example.mapper.MemberMapper;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.stereotype.Service;",
    "import org.springframework.transaction.annotation.Transactional;",
    "",
    "import java.util.List;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "public class MemberService {",
    "",
    "    private final MemberMapper memberMapper;",
    "",
    "    public List<MemberResponse> findAll() {",
    "        return memberMapper.findAll().stream()",
    "                .map(MemberResponse::from)",
    "                .toList();",
    "    }",
    "",
    "    public MemberResponse findById(Long id) {",
    "        Member member = memberMapper.findById(id)",
    "                .orElseThrow(() -> new RuntimeException(\"회원을 찾을 수 없습니다: \" + id));",
    "        return MemberResponse.from(member);",
    "    }",
    "",
    "    @Transactional",
    "    public MemberResponse create(MemberCreateRequest request) {",
    "        memberMapper.findByEmail(request.getEmail())",
    "                .ifPresent(m -> {",
    "                    throw new RuntimeException(\"이미 존재하는 이메일: \" + request.getEmail());",
    "                });",
    "",
    "        Member member = Member.builder()",
    "                .name(request.getName())",
    "                .email(request.getEmail())",
    "                .age(request.getAge())",
    "                .build();",
    "",
    "        memberMapper.insert(member);",
    "        return MemberResponse.from(member);",
    "    }",
    "",
    "    @Transactional",
    "    public MemberResponse update(Long id, MemberUpdateRequest request) {",
    "        Member member = memberMapper.findById(id)",
    "                .orElseThrow(() -> new RuntimeException(\"회원을 찾을 수 없습니다\"));",
    "",
    "        member.setName(request.getName());",
    "        member.setEmail(request.getEmail());",
    "        member.setAge(request.getAge());",
    "",
    "        memberMapper.update(member);",
    "        return MemberResponse.from(member);",
    "    }",
    "",
    "    @Transactional",
    "    public void delete(Long id) {",
    "        int deleted = memberMapper.deleteById(id);",
    "        if (deleted == 0) {",
    "            throw new RuntimeException(\"삭제할 회원이 없습니다: \" + id);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### MemberController.java",
    "",
    "```java",
    "package com.example.springboot_mybatis_example.controller;",
    "",
    "import com.example.springboot_mybatis_example.dto.MemberCreateRequest;",
    "import com.example.springboot_mybatis_example.dto.MemberResponse;",
    "import com.example.springboot_mybatis_example.dto.MemberUpdateRequest;",
    "import com.example.springboot_mybatis_example.service.MemberService;",
    "import jakarta.validation.Valid;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "import java.util.List;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/members\")",
    "@RequiredArgsConstructor",
    "public class MemberController {",
    "",
    "    private final MemberService memberService;",
    "",
    "    @GetMapping",
    "    public List<MemberResponse> findAll() {",
    "        return memberService.findAll();",
    "    }",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public MemberResponse findById(@PathVariable Long id) {",
    "        return memberService.findById(id);",
    "    }",
    "",
    "    @PostMapping",
    "    public ResponseEntity<MemberResponse> create(@RequestBody @Valid MemberCreateRequest request) {",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(memberService.create(request));",
    "    }",
    "",
    "    @PutMapping(\"/{id}\")",
    "    public MemberResponse update(@PathVariable Long id,",
    "                                  @RequestBody @Valid MemberUpdateRequest request) {",
    "        return memberService.update(id, request);",
    "    }",
    "",
    "    @DeleteMapping(\"/{id}\")",
    "    public ResponseEntity<Void> delete(@PathVariable Long id) {",
    "        memberService.delete(id);",
    "        return ResponseEntity.noContent().build();",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Postman으로 테스트",
    "",
    "서버를 실행한 뒤 (`./gradlew bootRun` 또는 IntelliJ에서 Run) Postman으로 API를 테스트합니다.",
    "",
    "### 1. 전체 조회 (GET)",
    "",
    "```",
    "GET http://localhost:8080/api/members",
    "```",
    "",
    "`data.sql`로 미리 넣은 3건이 반환됩니다.",
    "",
    "```json",
    "[",
    "    { \"id\": 3, \"name\": \"이철수\", \"email\": \"lee@example.com\", \"age\": 28, \"createdAt\": \"...\" },",
    "    { \"id\": 2, \"name\": \"김영희\", \"email\": \"kim@example.com\", \"age\": 30, \"createdAt\": \"...\" },",
    "    { \"id\": 1, \"name\": \"홍길동\", \"email\": \"hong@example.com\", \"age\": 25, \"createdAt\": \"...\" }",
    "]",
    "```",
    "",
    "### 2. 단건 조회 (GET)",
    "",
    "```",
    "GET http://localhost:8080/api/members/1",
    "```",
    "",
    "### 3. 회원 등록 (POST)",
    "",
    "```",
    "POST http://localhost:8080/api/members",
    "Content-Type: application/json",
    "```",
    "",
    "```json",
    "{",
    "    \"name\": \"박지민\",",
    "    \"email\": \"park@example.com\",",
    "    \"age\": 22",
    "}",
    "```",
    "",
    "응답: `201 Created`",
    "",
    "### 4. 회원 수정 (PUT)",
    "",
    "```",
    "PUT http://localhost:8080/api/members/1",
    "Content-Type: application/json",
    "```",
    "",
    "```json",
    "{",
    "    \"name\": \"홍길동(수정)\",",
    "    \"email\": \"hong@example.com\",",
    "    \"age\": 26",
    "}",
    "```",
    "",
    "### 5. 회원 삭제 (DELETE)",
    "",
    "```",
    "DELETE http://localhost:8080/api/members/1",
    "```",
    "",
    "응답: `204 No Content`",
    "",
    "---",
    "",
    "# 4. 동적 SQL",
    "",
    "MyBatis의 가장 강력한 기능입니다. 조건에 따라 SQL을 동적으로 조합합니다.",
    "",
    "## `<if>` (조건부 절)",
    "",
    "```xml",
    "<select id=\"findByCondition\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    WHERE 1=1",
    "    <if test=\"name != null and name != ''\">",
    "        AND name LIKE CONCAT('%', #{name}, '%')",
    "    </if>",
    "    <if test=\"department != null\">",
    "        AND department = #{department}",
    "    </if>",
    "    <if test=\"minAge != null\">",
    "        AND age >= #{minAge}",
    "    </if>",
    "    ORDER BY id DESC",
    "</select>",
    "```",
    "",
    "## `<where>` (WHERE 자동 생성)",
    "",
    "`WHERE 1=1` 대신 `<where>` 태그를 사용하면 첫 번째 조건의 `AND`를 자동으로 제거합니다.",
    "",
    "```xml",
    "<select id=\"findByCondition\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    <where>",
    "        <if test=\"name != null and name != ''\">",
    "            AND name LIKE CONCAT('%', #{name}, '%')",
    "        </if>",
    "        <if test=\"department != null\">",
    "            AND department = #{department}",
    "        </if>",
    "        <if test=\"minAge != null\">",
    "            AND age >= #{minAge}",
    "        </if>",
    "    </where>",
    "    ORDER BY id DESC",
    "</select>",
    "```",
    "",
    "## `<choose>` / `<when>` / `<otherwise>` (switch-case)",
    "",
    "```xml",
    "<select id=\"findBySort\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    ORDER BY",
    "    <choose>",
    "        <when test=\"sortBy == 'name'\">name</when>",
    "        <when test=\"sortBy == 'age'\">age DESC</when>",
    "        <otherwise>id DESC</otherwise>",
    "    </choose>",
    "</select>",
    "```",
    "",
    "## `<set>` (동적 UPDATE)",
    "",
    "```xml",
    "<update id=\"updateSelective\" parameterType=\"User\">",
    "    UPDATE users",
    "    <set>",
    "        <if test=\"name != null\">name = #{name},</if>",
    "        <if test=\"email != null\">email = #{email},</if>",
    "        <if test=\"age != null\">age = #{age},</if>",
    "        <if test=\"department != null\">department = #{department},</if>",
    "        updated_at = CURRENT_TIMESTAMP,",
    "    </set>",
    "    WHERE id = #{id}",
    "</update>",
    "```",
    "",
    "> `<set>` 태그는 마지막 쉼표를 자동으로 제거합니다.",
    "",
    "## `<foreach>` (IN 절, 배치 INSERT)",
    "",
    "```xml",
    "<!-- IN 절 -->",
    "<select id=\"findByIds\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    WHERE id IN",
    "    <foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">",
    "        #{id}",
    "    </foreach>",
    "</select>",
    "",
    "<!-- 배치 INSERT -->",
    "<insert id=\"insertBatch\" parameterType=\"list\">",
    "    INSERT INTO users (name, email, age, department)",
    "    VALUES",
    "    <foreach collection=\"list\" item=\"user\" separator=\",\">",
    "        (#{user.name}, #{user.email}, #{user.age}, #{user.department})",
    "    </foreach>",
    "</insert>",
    "```",
    "",
    "### `<foreach>` 속성",
    "",
    "| 속성 | 설명 | 예시 |",
    "|------|------|------|",
    "| `collection` | 파라미터명 | `\"ids\"`, `\"list\"` |",
    "| `item` | 반복 변수명 | `\"id\"`, `\"user\"` |",
    "| `open` | 시작 문자 | `\"(\"` |",
    "| `close` | 종료 문자 | `\")\"` |",
    "| `separator` | 구분자 | `\",\"` |",
    "",
    "## `<sql>` / `<include>` (재사용 SQL 조각)",
    "",
    "```xml",
    "<sql id=\"userColumns\">",
    "    id, name, email, age, department, created_at, updated_at",
    "</sql>",
    "",
    "<select id=\"findAll\" resultType=\"User\">",
    "    SELECT <include refid=\"userColumns\" />",
    "    FROM users",
    "    ORDER BY id DESC",
    "</select>",
    "",
    "<select id=\"findById\" resultType=\"User\">",
    "    SELECT <include refid=\"userColumns\" />",
    "    FROM users",
    "    WHERE id = #{id}",
    "</select>",
    "```",
    "",
    "### 동적 SQL 태그 정리",
    "",
    "| 태그 | 역할 | 예시 |",
    "|------|------|------|",
    "| `<if>` | 조건부 포함 | `test=\"name != null\"` |",
    "| `<where>` | WHERE + 불필요한 AND/OR 제거 | `<where><if>...</if></where>` |",
    "| `<set>` | SET + 불필요한 쉼표 제거 | 동적 UPDATE |",
    "| `<choose>` | switch-case | `<when>`, `<otherwise>` |",
    "| `<foreach>` | 반복 (IN, 배치) | `collection`, `item`, `separator` |",
    "| `<sql>` / `<include>` | SQL 조각 재사용 | 공통 컬럼 목록 |",
    "| `<trim>` | prefix/suffix 커스텀 | WHERE/SET의 일반화 |",
    "",
    "---",
    "",
    "# 5. ResultMap (복잡한 매핑)",
    "",
    "컬럼명과 필드명이 다르거나 **연관 관계(1:1, 1:N)**를 매핑할 때 사용합니다.",
    "",
    "## 기본 ResultMap",
    "",
    "```xml",
    "<resultMap id=\"userResultMap\" type=\"User\">",
    "    <id property=\"id\" column=\"user_id\" />",
    "    <result property=\"name\" column=\"user_name\" />",
    "    <result property=\"email\" column=\"user_email\" />",
    "</resultMap>",
    "",
    "<select id=\"findAll\" resultMap=\"userResultMap\">",
    "    SELECT user_id, user_name, user_email FROM users",
    "</select>",
    "```",
    "",
    "## 1:1 관계 (association)",
    "",
    "```xml",
    "<resultMap id=\"userWithDeptMap\" type=\"User\">",
    "    <id property=\"id\" column=\"id\" />",
    "    <result property=\"name\" column=\"name\" />",
    "    <association property=\"department\" javaType=\"Department\">",
    "        <id property=\"id\" column=\"dept_id\" />",
    "        <result property=\"deptName\" column=\"dept_name\" />",
    "    </association>",
    "</resultMap>",
    "",
    "<select id=\"findUserWithDepartment\" resultMap=\"userWithDeptMap\">",
    "    SELECT u.id, u.name, d.id AS dept_id, d.dept_name",
    "    FROM users u",
    "    JOIN departments d ON u.department_id = d.id",
    "    WHERE u.id = #{id}",
    "</select>",
    "```",
    "",
    "## 1:N 관계 (collection)",
    "",
    "```xml",
    "<resultMap id=\"userWithOrdersMap\" type=\"User\">",
    "    <id property=\"id\" column=\"id\" />",
    "    <result property=\"name\" column=\"name\" />",
    "    <collection property=\"orders\" ofType=\"Order\">",
    "        <id property=\"id\" column=\"order_id\" />",
    "        <result property=\"productName\" column=\"product_name\" />",
    "        <result property=\"price\" column=\"price\" />",
    "    </collection>",
    "</resultMap>",
    "",
    "<select id=\"findUserWithOrders\" resultMap=\"userWithOrdersMap\">",
    "    SELECT u.id, u.name, o.id AS order_id, o.product_name, o.price",
    "    FROM users u",
    "    LEFT JOIN orders o ON u.id = o.user_id",
    "    WHERE u.id = #{id}",
    "</select>",
    "```",
    "",
    "---",
    "",
    "# 6. 페이징",
    "",
    "## 직접 SQL 페이징",
    "",
    "```xml",
    "<select id=\"findPaged\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    ORDER BY id DESC",
    "    LIMIT #{limit} OFFSET #{offset}",
    "</select>",
    "```",
    "",
    "```java",
    "@Mapper",
    "public interface UserMapper {",
    "    List<User> findPaged(@Param(\"limit\") int limit, @Param(\"offset\") int offset);",
    "}",
    "```",
    "",
    "```java",
    "// Service에서 사용",
    "public List<UserResponse> findPaged(int page, int size) {",
    "    int offset = page * size;",
    "    return userMapper.findPaged(size, offset).stream()",
    "            .map(UserResponse::from)",
    "            .toList();",
    "}",
    "```",
    "",
    "## PageHelper 플러그인",
    "",
    "```groovy",
    "implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:2.1.0'",
    "```",
    "",
    "```java",
    "public PageInfo<User> findPaged(int pageNum, int pageSize) {",
    "    PageHelper.startPage(pageNum, pageSize);",
    "    List<User> users = userMapper.findAll();",
    "    return new PageInfo<>(users);",
    "}",
    "```",
    "",
    "---",
    "",
    "# 7. TypeHandler (커스텀 타입 변환)",
    "",
    "Java 타입과 DB 타입 간 변환 규칙을 정의합니다.",
    "",
    "```java",
    "@MappedTypes(YesNo.class)",
    "public class YesNoTypeHandler extends BaseTypeHandler<Boolean> {",
    "",
    "    @Override",
    "    public void setNonNullParameter(PreparedStatement ps, int i,",
    "                                     Boolean parameter, JdbcType jdbcType) throws SQLException {",
    "        ps.setString(i, parameter ? \"Y\" : \"N\");",
    "    }",
    "",
    "    @Override",
    "    public Boolean getNullableResult(ResultSet rs, String columnName) throws SQLException {",
    "        return \"Y\".equals(rs.getString(columnName));",
    "    }",
    "",
    "    @Override",
    "    public Boolean getNullableResult(ResultSet rs, int columnIndex) throws SQLException {",
    "        return \"Y\".equals(rs.getString(columnIndex));",
    "    }",
    "",
    "    @Override",
    "    public Boolean getNullableResult(CallableStatement cs, int columnIndex) throws SQLException {",
    "        return \"Y\".equals(cs.getString(columnIndex));",
    "    }",
    "}",
    "```",
    "",
    "```yaml",
    "mybatis:",
    "  type-handlers-package: com.example.demo.typehandler",
    "```",
    "",
    "> DB에 `\"Y\"/\"N\"`으로 저장된 값을 Java의 `Boolean` `true`/`false`로 자동 변환합니다.",
    "",
    "---",
    "",
    "## MyBatis + JPA 함께 사용하기",
    "",
    "하나의 프로젝트에서 **JPA와 MyBatis를 동시에** 사용할 수 있습니다.",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'",
    "    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'",
    "}",
    "```",
    "",
    "```java",
    "// 단순 CRUD: JPA",
    "public interface UserRepository extends JpaRepository<User, Long> { }",
    "",
    "// 복잡한 통계 쿼리: MyBatis",
    "@Mapper",
    "public interface UserStatsMapper {",
    "    List<DepartmentStats> getDepartmentStats();",
    "    List<MonthlyReport> getMonthlyReport(@Param(\"year\") int year);",
    "}",
    "```",
    "",
    "| 용도 | 기술 |",
    "|------|------|",
    "| 단순 CRUD, 도메인 로직 | JPA |",
    "| 복잡한 조회, 통계, 리포트 | MyBatis |",
    "| 레거시 테이블 매핑 | MyBatis |",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "### 1. `#{}` vs `${}` 혼동 금지",
    "`#{}`은 PreparedStatement 바인딩 (안전), `${}`는 문자열 치환 (SQL Injection 위험). 사용자 입력값에는 반드시 `#{}`을 사용하세요.",
    "",
    "### 2. namespace와 메서드명 일치",
    "XML의 `namespace`는 Mapper 인터페이스의 풀 패키지 경로, `id`는 메서드명과 정확히 일치해야 합니다. 오타 시 `BindingException`이 발생합니다.",
    "",
    "### 3. resultType vs resultMap",
    "컬럼명과 필드명이 일치하면 `resultType`, 다르거나 연관 관계가 있으면 `resultMap`을 사용하세요.",
    "",
    "### 4. N+1 문제",
    "MyBatis에서도 `association`/`collection`의 `select` 속성(중첩 쿼리)을 사용하면 N+1 문제가 발생합니다. 가능하면 **JOIN을 사용한 resultMap**으로 해결하세요.",
    "",
    "### 5. @Transactional 적용",
    "MyBatis Mapper 자체는 트랜잭션을 관리하지 않습니다. Service 계층에 `@Transactional`을 적용해야 합니다.",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 구성 | 역할 |",
    "|------|------|",
    "| `@Mapper` 인터페이스 | SQL 매핑 메서드 정의 |",
    "| XML 매퍼 | SQL 작성 (동적 SQL 포함) |",
    "| `#{}` | PreparedStatement 바인딩 (안전) |",
    "| `<if>`, `<where>`, `<set>` | 동적 SQL 조건 생성 |",
    "| `<foreach>` | IN 절, 배치 INSERT |",
    "| `<sql>` / `<include>` | SQL 조각 재사용 |",
    "| `ResultMap` | 복잡한 매핑 (1:1, 1:N) |",
    "| `TypeHandler` | Java ↔ DB 타입 변환 |",
    "",
    "| 선택 기준 | 추천 |",
    "|----------|------|",
    "| SQL을 직접 제어하고 싶을 때 | **MyBatis** |",
    "| 복잡한 통계/리포트 쿼리 | **MyBatis** |",
    "| 레거시 DB 스키마 | **MyBatis** |",
    "| 빠른 CRUD 개발 | JPA |",
    "| 도메인 중심 설계 | JPA |",
    "| 둘 다 필요할 때 | **JPA + MyBatis 혼합** |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
