<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-mail",
  title: "Spring Boot 메일 발송 완전 정리 - JavaMailSender, 템플릿 이메일, 첨부파일까지",
  date: "2026-03-01",
  summary: "Spring Boot에서 이메일을 발송하는 방법을 정리합니다. JavaMailSender, SimpleMailMessage, MimeMessage, Thymeleaf 템플릿 이메일, 첨부파일, 비동기 발송까지 실전 예제로 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","mail","email","javamailsender","smtp","backend"],
  content: [
    "## 메일 발송 개요",
    "",
    "Spring Boot에서 이메일을 발송하려면 **SMTP**(Simple Mail Transfer Protocol) 서버를 통해 메일을 전달합니다. Spring Boot는 `spring-boot-starter-mail`을 통해 **JavaMailSender**를 제공하여 간편하게 메일을 발송할 수 있습니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Spring Boot<br/>애플리케이션\"] -->|\"JavaMailSender\"| B[\"SMTP 서버<br/>(Gmail, Naver 등)\"]",
    "    B -->|\"SMTP 프로토콜\"| C[\"수신자 메일 서버\"]",
    "    C --> D[\"수신자 메일함\"]",
    "",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "```",
    "",
    "### Spring Boot Mail 구조",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"spring-boot-starter-mail\"] --> B[\"JavaMailSender<br/>(인터페이스)\"]",
    "    B --> C[\"JavaMailSenderImpl<br/>(구현체)\"]",
    "    C --> D[\"Jakarta Mail API<br/>(javax.mail → jakarta.mail)\"]",
    "",
    "    B --> E[\"SimpleMailMessage<br/>(단순 텍스트)\"]",
    "    B --> F[\"MimeMessage<br/>(HTML, 첨부파일)\"]",
    "    F --> G[\"MimeMessageHelper<br/>(편의 클래스)\"]",
    "",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "```",
    "",
    "| 클래스 | 역할 | 용도 |",
    "|-------|------|------|",
    "| `JavaMailSender` | 메일 발송 인터페이스 | DI로 주입받아 사용 |",
    "| `SimpleMailMessage` | 단순 텍스트 메일 | 간단한 알림 메일 |",
    "| `MimeMessage` | HTML, 첨부파일 메일 | 복잡한 메일 |",
    "| `MimeMessageHelper` | MimeMessage 편의 클래스 | HTML/첨부파일 쉽게 설정 |",
    "",
    "---",
    "",
    "## 프로젝트 설정",
    "",
    "### 의존성 추가",
    "",
    "```groovy",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-mail'",
    "    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf' // 템플릿 메일 사용 시",
    "}",
    "```",
    "",
    "```xml",
    "<!-- pom.xml -->",
    "<dependency>",
    "    <groupId>org.springframework.boot</groupId>",
    "    <artifactId>spring-boot-starter-mail</artifactId>",
    "</dependency>",
    "<dependency>",
    "    <groupId>org.springframework.boot</groupId>",
    "    <artifactId>spring-boot-starter-thymeleaf</artifactId>",
    "</dependency>",
    "```",
    "",
    "### Gmail SMTP 설정 (application.yml)",
    "",
    "```yaml",
    "spring:",
    "  mail:",
    "    host: smtp.gmail.com",
    "    port: 587",
    "    username: your-email@gmail.com",
    "    password: your-app-password          # Gmail 앱 비밀번호 (계정 비밀번호 아님!)",
    "    properties:",
    "      mail:",
    "        smtp:",
    "          auth: true",
    "          starttls:",
    "            enable: true",
    "            required: true",
    "          connectiontimeout: 5000",
    "          timeout: 5000",
    "          writetimeout: 5000",
    "```",
    "",
    "### Gmail 앱 비밀번호 발급 방법",
    "",
    "1. Google 계정 → **보안** → **2단계 인증** 활성화",
    "2. **앱 비밀번호** 생성 (메일 > Windows 컴퓨터 선택)",
    "3. 생성된 16자리 비밀번호를 `spring.mail.password`에 입력",
    "",
    "> **주의**: 실제 Gmail 비밀번호가 아닌 **앱 비밀번호**를 사용해야 합니다. 앱 비밀번호는 `application.yml`에 직접 넣지 말고 **환경 변수**나 **Vault**로 관리하세요.",
    "",
    "---",
    "",
    "## 단순 텍스트 메일 (SimpleMailMessage)",
    "",
    "가장 간단한 메일 발송 방법입니다. HTML 없이 **텍스트만** 보낼 때 사용합니다.",
    "",
    "```java",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.mail.SimpleMailMessage;",
    "import org.springframework.mail.javamail.JavaMailSender;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "public class MailService {",
    "",
    "    private final JavaMailSender mailSender;",
    "",
    "    public void sendSimpleMail(String to, String subject, String text) {",
    "        SimpleMailMessage message = new SimpleMailMessage();",
    "        message.setFrom(\"noreply@example.com\");",
    "        message.setTo(to);",
    "        message.setSubject(subject);",
    "        message.setText(text);",
    "",
    "        mailSender.send(message);",
    "    }",
    "}",
    "```",
    "",
    "### 사용 예시",
    "",
    "```java",
    "@RestController",
    "@RequiredArgsConstructor",
    "@RequestMapping(\"/api/mail\")",
    "public class MailController {",
    "",
    "    private final MailService mailService;",
    "",
    "    @PostMapping(\"/simple\")",
    "    public ResponseEntity<String> sendSimple(@RequestBody MailRequest request) {",
    "        mailService.sendSimpleMail(",
    "            request.to(),",
    "            request.subject(),",
    "            request.text()",
    "        );",
    "        return ResponseEntity.ok(\"메일 발송 완료\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## HTML 메일 (MimeMessage)",
    "",
    "HTML 형식의 메일을 보내려면 **MimeMessage**와 **MimeMessageHelper**를 사용합니다.",
    "",
    "```java",
    "import jakarta.mail.MessagingException;",
    "import jakarta.mail.internet.MimeMessage;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.mail.javamail.JavaMailSender;",
    "import org.springframework.mail.javamail.MimeMessageHelper;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "public class MailService {",
    "",
    "    private final JavaMailSender mailSender;",
    "",
    "    public void sendHtmlMail(String to, String subject, String htmlContent)",
    "            throws MessagingException {",
    "",
    "        MimeMessage message = mailSender.createMimeMessage();",
    "        MimeMessageHelper helper = new MimeMessageHelper(message, true, \"UTF-8\");",
    "",
    "        helper.setFrom(\"noreply@example.com\");",
    "        helper.setTo(to);",
    "        helper.setSubject(subject);",
    "        helper.setText(htmlContent, true);  // true = HTML",
    "",
    "        mailSender.send(message);",
    "    }",
    "}",
    "```",
    "",
    "### HTML 메일 본문 예시",
    "",
    "```java",
    "String htmlContent = \"\"\"",
    "    <div style=\"max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;\">",
    "        <div style=\"background: #4CAF50; color: white; padding: 20px; text-align: center;\">",
    "            <h1>회원가입을 환영합니다!</h1>",
    "        </div>",
    "        <div style=\"padding: 20px;\">",
    "            <p>안녕하세요, <strong>%s</strong>님!</p>",
    "            <p>아래 버튼을 클릭하여 이메일 인증을 완료해주세요.</p>",
    "            <a href=\"%s\" style=\"display: inline-block; padding: 12px 24px;",
    "               background: #4CAF50; color: white; text-decoration: none;",
    "               border-radius: 4px;\">이메일 인증하기</a>",
    "        </div>",
    "    </div>",
    "    \"\"\".formatted(userName, verifyUrl);",
    "",
    "mailService.sendHtmlMail(email, \"이메일 인증\", htmlContent);",
    "```",
    "",
    "---",
    "",
    "## 첨부파일 메일",
    "",
    "### 일반 첨부파일",
    "",
    "```java",
    "import org.springframework.core.io.FileSystemResource;",
    "import java.io.File;",
    "",
    "public void sendMailWithAttachment(String to, String subject, String text,",
    "                                   String filePath) throws MessagingException {",
    "",
    "    MimeMessage message = mailSender.createMimeMessage();",
    "    MimeMessageHelper helper = new MimeMessageHelper(message, true, \"UTF-8\");",
    "",
    "    helper.setFrom(\"noreply@example.com\");",
    "    helper.setTo(to);",
    "    helper.setSubject(subject);",
    "    helper.setText(text, true);",
    "",
    "    FileSystemResource file = new FileSystemResource(new File(filePath));",
    "    helper.addAttachment(file.getFilename(), file);",
    "",
    "    mailSender.send(message);",
    "}",
    "```",
    "",
    "### 여러 파일 첨부",
    "",
    "```java",
    "public void sendMailWithAttachments(String to, String subject, String text,",
    "                                    List<String> filePaths) throws MessagingException {",
    "",
    "    MimeMessage message = mailSender.createMimeMessage();",
    "    MimeMessageHelper helper = new MimeMessageHelper(message, true, \"UTF-8\");",
    "",
    "    helper.setFrom(\"noreply@example.com\");",
    "    helper.setTo(to);",
    "    helper.setSubject(subject);",
    "    helper.setText(text, true);",
    "",
    "    for (String filePath : filePaths) {",
    "        FileSystemResource file = new FileSystemResource(new File(filePath));",
    "        helper.addAttachment(file.getFilename(), file);",
    "    }",
    "",
    "    mailSender.send(message);",
    "}",
    "```",
    "",
    "### 인라인 이미지 (본문 삽입 이미지)",
    "",
    "```java",
    "public void sendMailWithInlineImage(String to, String subject) throws MessagingException {",
    "",
    "    MimeMessage message = mailSender.createMimeMessage();",
    "    MimeMessageHelper helper = new MimeMessageHelper(message, true, \"UTF-8\");",
    "",
    "    helper.setFrom(\"noreply@example.com\");",
    "    helper.setTo(to);",
    "    helper.setSubject(subject);",
    "",
    "    String htmlContent = \"\"\"",
    "        <h1>로고 포함 메일</h1>",
    "        <img src=\"cid:logoImage\" width=\"200\" />",
    "        <p>본문에 이미지가 포함됩니다.</p>",
    "        \"\"\";",
    "    helper.setText(htmlContent, true);",
    "",
    "    FileSystemResource logo = new FileSystemResource(new File(\"src/main/resources/static/logo.png\"));",
    "    helper.addInline(\"logoImage\", logo);",
    "",
    "    mailSender.send(message);",
    "}",
    "```",
    "",
    "> `addAttachment()`는 첨부파일로, `addInline()`은 **본문 삽입 이미지**로 추가합니다. `cid:식별자`로 HTML에서 참조합니다.",
    "",
    "---",
    "",
    "## Thymeleaf 템플릿 메일",
    "",
    "복잡한 HTML 메일은 **Thymeleaf 템플릿 파일**로 관리하면 유지보수가 편합니다.",
    "",
    "### 템플릿 파일 작성",
    "",
    "`src/main/resources/templates/mail/welcome.html`",
    "",
    "```html",
    "<!DOCTYPE html>",
    "<html xmlns:th=\"http://www.thymeleaf.org\">",
    "<head>",
    "    <meta charset=\"UTF-8\">",
    "</head>",
    "<body>",
    "    <div style=\"max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;\">",
    "        <div style=\"background: #2196F3; color: white; padding: 20px; text-align: center;\">",
    "            <h1 th:text=\"${title}\">제목</h1>",
    "        </div>",
    "        <div style=\"padding: 20px;\">",
    "            <p>안녕하세요, <strong th:text=\"${userName}\">사용자</strong>님!</p>",
    "            <p th:text=\"${message}\">메시지</p>",
    "",
    "            <div th:if=\"${verifyUrl}\" style=\"text-align: center; margin: 30px 0;\">",
    "                <a th:href=\"${verifyUrl}\"",
    "                   style=\"display: inline-block; padding: 12px 24px;",
    "                          background: #2196F3; color: white; text-decoration: none;",
    "                          border-radius: 4px; font-size: 16px;\">",
    "                    이메일 인증하기",
    "                </a>",
    "            </div>",
    "",
    "            <div th:if=\"${code}\" style=\"text-align: center; margin: 30px 0;\">",
    "                <span style=\"font-size: 32px; font-weight: bold; letter-spacing: 8px;",
    "                             color: #2196F3; background: #f5f5f5; padding: 10px 20px;",
    "                             border-radius: 8px;\"",
    "                       th:text=\"${code}\">000000</span>",
    "            </div>",
    "        </div>",
    "        <div style=\"background: #f5f5f5; padding: 15px; text-align: center; color: #999;\">",
    "            <p>본 메일은 발신 전용입니다.</p>",
    "        </div>",
    "    </div>",
    "</body>",
    "</html>",
    "```",
    "",
    "### MailService에서 템플릿 사용",
    "",
    "```java",
    "import jakarta.mail.MessagingException;",
    "import jakarta.mail.internet.MimeMessage;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.mail.javamail.JavaMailSender;",
    "import org.springframework.mail.javamail.MimeMessageHelper;",
    "import org.springframework.stereotype.Service;",
    "import org.thymeleaf.TemplateEngine;",
    "import org.thymeleaf.context.Context;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "public class MailService {",
    "",
    "    private final JavaMailSender mailSender;",
    "    private final TemplateEngine templateEngine;",
    "",
    "    public void sendTemplateMail(String to, String subject,",
    "                                 String templateName, Map<String, Object> variables)",
    "            throws MessagingException {",
    "",
    "        Context context = new Context();",
    "        context.setVariables(variables);",
    "",
    "        String htmlContent = templateEngine.process(\"mail/\" + templateName, context);",
    "",
    "        MimeMessage message = mailSender.createMimeMessage();",
    "        MimeMessageHelper helper = new MimeMessageHelper(message, true, \"UTF-8\");",
    "",
    "        helper.setFrom(\"noreply@example.com\");",
    "        helper.setTo(to);",
    "        helper.setSubject(subject);",
    "        helper.setText(htmlContent, true);",
    "",
    "        mailSender.send(message);",
    "    }",
    "",
    "    public void sendWelcomeMail(String to, String userName, String verifyUrl)",
    "            throws MessagingException {",
    "",
    "        Map<String, Object> variables = Map.of(",
    "            \"title\", \"회원가입을 환영합니다!\",",
    "            \"userName\", userName,",
    "            \"message\", \"아래 버튼을 클릭하여 이메일 인증을 완료해주세요.\",",
    "            \"verifyUrl\", verifyUrl",
    "        );",
    "",
    "        sendTemplateMail(to, \"회원가입 인증 메일\", \"welcome\", variables);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 비동기 메일 발송",
    "",
    "메일 발송은 **SMTP 서버와의 네트워크 통신**이므로 시간이 걸립니다. **@Async**를 사용하면 메일 발송을 비동기로 처리하여 **응답 시간을 단축**할 수 있습니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant Ctrl as Controller",
    "    participant Svc as MailService",
    "    participant SMTP as SMTP 서버",
    "",
    "    Note over C,SMTP: 동기 방식 (느림)",
    "    C->>Ctrl: 회원가입 요청",
    "    Ctrl->>Svc: sendMail()",
    "    Svc->>SMTP: 메일 전송 (2~5초)",
    "    SMTP-->>Svc: 완료",
    "    Svc-->>Ctrl: 완료",
    "    Ctrl-->>C: 응답 (3~6초 소요)",
    "",
    "    Note over C,SMTP: 비동기 방식 (빠름)",
    "    C->>Ctrl: 회원가입 요청",
    "    Ctrl->>Svc: sendMailAsync()",
    "    Svc-->>Ctrl: 즉시 반환",
    "    Ctrl-->>C: 응답 (100ms)",
    "    Svc->>SMTP: 별도 스레드에서 메일 전송",
    "```",
    "",
    "### @Async 설정",
    "",
    "```java",
    "import org.springframework.context.annotation.Configuration;",
    "import org.springframework.scheduling.annotation.EnableAsync;",
    "import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;",
    "import org.springframework.context.annotation.Bean;",
    "import java.util.concurrent.Executor;",
    "",
    "@Configuration",
    "@EnableAsync",
    "public class AsyncConfig {",
    "",
    "    @Bean(name = \"mailExecutor\")",
    "    public Executor mailExecutor() {",
    "        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();",
    "        executor.setCorePoolSize(2);",
    "        executor.setMaxPoolSize(5);",
    "        executor.setQueueCapacity(100);",
    "        executor.setThreadNamePrefix(\"mail-\");",
    "        executor.initialize();",
    "        return executor;",
    "    }",
    "}",
    "```",
    "",
    "### 비동기 MailService",
    "",
    "```java",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.mail.javamail.JavaMailSender;",
    "import org.springframework.mail.javamail.MimeMessageHelper;",
    "import org.springframework.scheduling.annotation.Async;",
    "import org.springframework.stereotype.Service;",
    "",
    "import jakarta.mail.MessagingException;",
    "import jakarta.mail.internet.MimeMessage;",
    "import java.util.concurrent.CompletableFuture;",
    "",
    "@Slf4j",
    "@Service",
    "@RequiredArgsConstructor",
    "public class AsyncMailService {",
    "",
    "    private final JavaMailSender mailSender;",
    "",
    "    @Async(\"mailExecutor\")",
    "    public CompletableFuture<Boolean> sendMailAsync(String to, String subject,",
    "                                                    String htmlContent) {",
    "        try {",
    "            MimeMessage message = mailSender.createMimeMessage();",
    "            MimeMessageHelper helper = new MimeMessageHelper(message, true, \"UTF-8\");",
    "",
    "            helper.setFrom(\"noreply@example.com\");",
    "            helper.setTo(to);",
    "            helper.setSubject(subject);",
    "            helper.setText(htmlContent, true);",
    "",
    "            mailSender.send(message);",
    "            log.info(\"메일 발송 성공 - to: {}\", to);",
    "            return CompletableFuture.completedFuture(true);",
    "",
    "        } catch (MessagingException e) {",
    "            log.error(\"메일 발송 실패 - to: {}, error: {}\", to, e.getMessage(), e);",
    "            return CompletableFuture.completedFuture(false);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### 실패 시 재시도 (Spring Retry)",
    "",
    "```java",
    "import org.springframework.retry.annotation.Backoff;",
    "import org.springframework.retry.annotation.Retryable;",
    "",
    "@Retryable(",
    "    retryFor = MessagingException.class,",
    "    maxAttempts = 3,",
    "    backoff = @Backoff(delay = 2000, multiplier = 2)",
    ")",
    "@Async(\"mailExecutor\")",
    "public void sendMailWithRetry(String to, String subject, String content)",
    "        throws MessagingException {",
    "    // 실패 시 2초 → 4초 → 8초 간격으로 최대 3번 재시도",
    "    MimeMessage message = mailSender.createMimeMessage();",
    "    MimeMessageHelper helper = new MimeMessageHelper(message, true, \"UTF-8\");",
    "    helper.setTo(to);",
    "    helper.setSubject(subject);",
    "    helper.setText(content, true);",
    "    mailSender.send(message);",
    "}",
    "```",
    "",
    "---",
    "",
    "## 다양한 SMTP 설정",
    "",
    "### Gmail SMTP",
    "",
    "```yaml",
    "spring:",
    "  mail:",
    "    host: smtp.gmail.com",
    "    port: 587",
    "    username: your-email@gmail.com",
    "    password: your-app-password",
    "    properties:",
    "      mail.smtp.auth: true",
    "      mail.smtp.starttls.enable: true",
    "```",
    "",
    "### Naver SMTP",
    "",
    "```yaml",
    "spring:",
    "  mail:",
    "    host: smtp.naver.com",
    "    port: 465",
    "    username: your-email@naver.com",
    "    password: your-password",
    "    properties:",
    "      mail.smtp.auth: true",
    "      mail.smtp.ssl.enable: true",
    "      mail.smtp.ssl.trust: smtp.naver.com",
    "```",
    "",
    "### 사내 SMTP 서버",
    "",
    "```yaml",
    "spring:",
    "  mail:",
    "    host: mail.company.com",
    "    port: 25",
    "    username: service@company.com",
    "    password: password",
    "    properties:",
    "      mail.smtp.auth: true",
    "      mail.smtp.starttls.enable: false",
    "```",
    "",
    "| SMTP 서버 | 호스트 | 포트 | 보안 | 비고 |",
    "|----------|-------|------|------|------|",
    "| Gmail | smtp.gmail.com | 587 | STARTTLS | 앱 비밀번호 필요 |",
    "| Naver | smtp.naver.com | 465 | SSL | 일반 비밀번호 |",
    "| Daum | smtp.daum.net | 465 | SSL | - |",
    "| 사내 SMTP | mail.company.com | 25 | 없음/STARTTLS | 사내 설정 확인 |",
    "",
    "---",
    "",
    "## 실전 예제: 회원가입 인증 메일",
    "",
    "회원가입 시 **인증 코드를 메일로 발송**하고, 사용자가 코드를 입력하여 **이메일 인증을 완료**하는 전체 흐름입니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant U as 사용자",
    "    participant C as Controller",
    "    participant S as AuthService",
    "    participant M as MailService",
    "    participant R as Redis",
    "    participant SMTP as SMTP 서버",
    "",
    "    U->>C: POST /api/auth/signup",
    "    C->>S: signup(request)",
    "    S->>S: 인증 코드 생성 (6자리)",
    "    S->>R: 코드 저장 (key: email, TTL: 5분)",
    "    S->>M: sendVerificationMail(email, code)",
    "    M->>SMTP: 메일 발송",
    "    S-->>C: \"인증 메일이 발송되었습니다\"",
    "    C-->>U: 200 OK",
    "",
    "    U->>C: POST /api/auth/verify",
    "    C->>S: verifyEmail(email, code)",
    "    S->>R: 저장된 코드 조회",
    "    R-->>S: 저장된 코드",
    "    S->>S: 코드 비교",
    "    S->>S: 사용자 인증 상태 변경",
    "    S-->>C: \"인증 완료\"",
    "    C-->>U: 200 OK",
    "```",
    "",
    "### 인증 코드 생성 유틸리티",
    "",
    "```java",
    "import java.security.SecureRandom;",
    "",
    "public class VerificationCodeUtil {",
    "",
    "    private static final SecureRandom random = new SecureRandom();",
    "",
    "    public static String generateCode(int length) {",
    "        StringBuilder code = new StringBuilder();",
    "        for (int i = 0; i < length; i++) {",
    "            code.append(random.nextInt(10));",
    "        }",
    "        return code.toString();",
    "    }",
    "}",
    "```",
    "",
    "### AuthService 구현",
    "",
    "```java",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.data.redis.core.StringRedisTemplate;",
    "import org.springframework.stereotype.Service;",
    "",
    "import java.time.Duration;",
    "",
    "@Slf4j",
    "@Service",
    "@RequiredArgsConstructor",
    "public class AuthService {",
    "",
    "    private final UserRepository userRepository;",
    "    private final MailService mailService;",
    "    private final StringRedisTemplate redisTemplate;",
    "",
    "    private static final String VERIFY_PREFIX = \"email:verify:\";",
    "    private static final Duration CODE_TTL = Duration.ofMinutes(5);",
    "",
    "    public void sendVerificationMail(String email) {",
    "        String code = VerificationCodeUtil.generateCode(6);",
    "",
    "        redisTemplate.opsForValue()",
    "                .set(VERIFY_PREFIX + email, code, CODE_TTL);",
    "",
    "        try {",
    "            mailService.sendTemplateMail(",
    "                email,",
    "                \"이메일 인증 코드\",",
    "                \"welcome\",",
    "                Map.of(",
    "                    \"title\", \"이메일 인증\",",
    "                    \"userName\", email,",
    "                    \"message\", \"아래 인증 코드를 입력해주세요. (5분 이내)\",",
    "                    \"code\", code",
    "                )",
    "            );",
    "            log.info(\"인증 메일 발송 완료 - email: {}\", email);",
    "        } catch (Exception e) {",
    "            log.error(\"인증 메일 발송 실패 - email: {}\", email, e);",
    "            throw new MailSendException(\"메일 발송에 실패했습니다.\");",
    "        }",
    "    }",
    "",
    "    public void verifyEmail(String email, String code) {",
    "        String savedCode = redisTemplate.opsForValue()",
    "                .get(VERIFY_PREFIX + email);",
    "",
    "        if (savedCode == null) {",
    "            throw new VerificationException(\"인증 코드가 만료되었습니다.\");",
    "        }",
    "",
    "        if (!savedCode.equals(code)) {",
    "            throw new VerificationException(\"인증 코드가 일치하지 않습니다.\");",
    "        }",
    "",
    "        redisTemplate.delete(VERIFY_PREFIX + email);",
    "",
    "        User user = userRepository.findByEmail(email)",
    "                .orElseThrow(() -> new UserNotFoundException(email));",
    "        user.setEmailVerified(true);",
    "        userRepository.save(user);",
    "",
    "        log.info(\"이메일 인증 완료 - email: {}\", email);",
    "    }",
    "}",
    "```",
    "",
    "### AuthController",
    "",
    "```java",
    "@RestController",
    "@RequestMapping(\"/api/auth\")",
    "@RequiredArgsConstructor",
    "public class AuthController {",
    "",
    "    private final AuthService authService;",
    "",
    "    @PostMapping(\"/send-verification\")",
    "    public ResponseEntity<String> sendVerification(",
    "            @RequestBody @Valid EmailRequest request) {",
    "        authService.sendVerificationMail(request.email());",
    "        return ResponseEntity.ok(\"인증 메일이 발송되었습니다.\");",
    "    }",
    "",
    "    @PostMapping(\"/verify\")",
    "    public ResponseEntity<String> verifyEmail(",
    "            @RequestBody @Valid VerifyRequest request) {",
    "        authService.verifyEmail(request.email(), request.code());",
    "        return ResponseEntity.ok(\"이메일 인증이 완료되었습니다.\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "| 주의사항 | 설명 |",
    "|---------|------|",
    "| SMTP 비밀번호 관리 | `application.yml`에 직접 넣지 말고 **환경 변수** 또는 **Vault** 사용 |",
    "| Gmail 앱 비밀번호 | 실제 비밀번호가 아닌 **앱 비밀번호** 발급 필요 |",
    "| 대량 발송 주의 | Gmail은 하루 500건 제한, 대량 발송은 **SendGrid**, **AWS SES** 사용 |",
    "| 스팸 방지 | SPF, DKIM, DMARC 레코드 설정 권장 |",
    "| 비동기 필수 | 메일 발송은 느리므로 **@Async**로 비동기 처리 |",
    "| 예외 처리 | 메일 발송 실패 시 **재시도** 또는 **큐** 사용 |",
    "| HTML 이메일 호환성 | CSS는 인라인 스타일 사용 (외부 CSS 불가) |",
    "| 인증 코드 보안 | 인증 코드는 **Redis**에 TTL 설정, 시도 횟수 제한 |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| **의존성** | `spring-boot-starter-mail` |",
    "| **JavaMailSender** | 메일 발송 인터페이스 (DI로 주입) |",
    "| **SimpleMailMessage** | 단순 텍스트 메일 |",
    "| **MimeMessage** | HTML, 첨부파일 메일 |",
    "| **MimeMessageHelper** | MimeMessage 편의 클래스 |",
    "| **Thymeleaf 템플릿** | HTML 템플릿 파일로 메일 본문 관리 |",
    "| **@Async** | 비동기 메일 발송 (응답 시간 단축) |",
    "| **첨부파일** | `addAttachment()` / `addInline()` |",
    "| **SMTP 설정** | Gmail (587/TLS), Naver (465/SSL), 사내 (25) |",
    "| **대량 발송** | SendGrid, AWS SES, Mailgun 사용 권장 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
