<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-mybatis",
  title: "Spring Boot + MyBatis 완전 정리 - 개념부터 실전 CRUD, 동적 쿼리까지",
  date: "2026-02-14",
  summary: "MyBatis의 개념, JPA와의 차이, Spring Boot 연동 설정, XML/어노테이션 매핑, CRUD 실전 예제, 동적 SQL, ResultMap, 페이징, TypeHandler까지 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","mybatis","sql","mapper","xml","backend"],
  content: [
    "## MyBatis란?",
    "",
    "**MyBatis**는 SQL을 직접 작성하면서 Java 객체와 매핑해주는 **SQL Mapper 프레임워크**입니다. JPA(ORM)처럼 SQL을 자동 생성하지 않고, **개발자가 SQL을 완전히 제어**합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Java 코드\"] --> B[\"MyBatis\"]",
    "    B --> C[\"SQL (XML / 어노테이션)\"]",
    "    C --> D[(\"DB\")]",
    "    D --> C",
    "    C --> B",
    "    B -->|ResultMap| A",
    "```",
    "",
    "---",
    "",
    "## MyBatis vs JPA 비교",
    "",
    "| 비교 | MyBatis | JPA (Hibernate) |",
    "|------|---------|----------------|",
    "| 유형 | **SQL Mapper** | **ORM** |",
    "| SQL 작성 | **개발자가 직접 작성** | 자동 생성 (JPQL, Querydsl) |",
    "| 학습 곡선 | SQL 알면 쉬움 | 영속성 컨텍스트, 지연 로딩 이해 필요 |",
    "| 복잡한 쿼리 | **자유롭게 작성** | 네이티브 쿼리 필요 |",
    "| DB 종속성 | SQL이 DB에 종속될 수 있음 | DB 독립적 |",
    "| 변경 감지 | 없음 (직접 UPDATE) | **Dirty Checking** |",
    "| 캐시 | 1차 캐시 (세션 단위) | 1차 + 2차 캐시 |",
    "| 적합 | 복잡한 SQL, 레거시 DB, 통계/리포트 | 도메인 중심, 빠른 개발 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A{\"어떤 기술을 선택?\"} -->|SQL 제어가 중요| B[\"MyBatis\"]",
    "    A -->|빠른 개발, 도메인 중심| C[\"JPA\"]",
    "    A -->|복잡한 통계/리포트 쿼리| B",
    "    A -->|레거시 DB 스키마| B",
    "    A -->|표준 CRUD 위주| C",
    "```",
    "",
    "---",
    "",
    "## 프로젝트 설정",
    "",
    "### 의존성 (build.gradle)",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "",
    "    runtimeOnly 'com.h2database:h2'           // 개발용",
    "    // runtimeOnly 'com.mysql:mysql-connector-j'  // MySQL",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "}",
    "```",
    "",
    "### application.yml",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb",
    "    driver-class-name: org.h2.Driver",
    "    username: sa",
    "    password:",
    "",
    "mybatis:",
    "  mapper-locations: classpath:mapper/**/*.xml   # XML 매퍼 위치",
    "  type-aliases-package: com.example.demo.domain  # 패키지 별칭",
    "  configuration:",
    "    map-underscore-to-camel-case: true           # snake_case → camelCase 자동 변환",
    "    default-fetch-size: 100",
    "    default-statement-timeout: 30",
    "```",
    "",
    "> `map-underscore-to-camel-case: true`를 설정하면 DB의 `user_name` 컬럼이 Java의 `userName` 필드에 자동 매핑됩니다.",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "src/main/",
    "├── java/com/example/demo/",
    "│   ├── domain/",
    "│   │   └── User.java",
    "│   ├── mapper/",
    "│   │   └── UserMapper.java              // Mapper 인터페이스",
    "│   ├── service/",
    "│   │   └── UserService.java",
    "│   ├── controller/",
    "│   │   └── UserController.java",
    "│   ├── dto/",
    "│   │   ├── CreateUserRequest.java",
    "│   │   └── UserResponse.java",
    "│   └── DemoApplication.java",
    "└── resources/",
    "    ├── mapper/",
    "    │   └── UserMapper.xml                // SQL XML",
    "    ├── schema.sql                         // 테이블 생성",
    "    └── application.yml",
    "```",
    "",
    "### 테이블 생성 (schema.sql)",
    "",
    "```sql",
    "CREATE TABLE users (",
    "    id          BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "    name        VARCHAR(50)  NOT NULL,",
    "    email       VARCHAR(100) NOT NULL UNIQUE,",
    "    age         INT,",
    "    department  VARCHAR(50),",
    "    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
    "    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    ");",
    "```",
    "",
    "---",
    "",
    "## 도메인",
    "",
    "```java",
    "@Getter @Setter",
    "@NoArgsConstructor @AllArgsConstructor @Builder",
    "public class User {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private Integer age;",
    "    private String department;",
    "    private LocalDateTime createdAt;",
    "    private LocalDateTime updatedAt;",
    "}",
    "```",
    "",
    "> MyBatis에서는 `@Entity` 같은 JPA 어노테이션이 필요 없습니다. **순수 POJO**입니다.",
    "",
    "---",
    "",
    "# 1. Mapper 인터페이스 + XML 방식 (권장)",
    "",
    "## Mapper 인터페이스",
    "",
    "```java",
    "package com.example.demo.mapper;",
    "",
    "import com.example.demo.domain.User;",
    "import org.apache.ibatis.annotations.Mapper;",
    "import org.apache.ibatis.annotations.Param;",
    "",
    "import java.util.List;",
    "import java.util.Optional;",
    "",
    "@Mapper",
    "public interface UserMapper {",
    "",
    "    List<User> findAll();",
    "",
    "    Optional<User> findById(@Param(\"id\") Long id);",
    "",
    "    Optional<User> findByEmail(@Param(\"email\") String email);",
    "",
    "    void insert(User user);",
    "",
    "    int update(User user);",
    "",
    "    int deleteById(@Param(\"id\") Long id);",
    "",
    "    List<User> findByCondition(@Param(\"name\") String name,",
    "                               @Param(\"department\") String department,",
    "                               @Param(\"minAge\") Integer minAge);",
    "",
    "    int count();",
    "}",
    "```",
    "",
    "> `@Mapper`를 붙이면 Spring이 자동으로 구현체를 생성합니다.",
    "",
    "## XML 매퍼 (SQL 작성)",
    "",
    "```xml",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<!DOCTYPE mapper PUBLIC \"-//mybatis.org//DTD Mapper 3.0//EN\"",
    "        \"http://mybatis.org/dtd/mybatis-3-mapper.dtd\">",
    "",
    "<mapper namespace=\"com.example.demo.mapper.UserMapper\">",
    "",
    "    <!-- 전체 조회 -->",
    "    <select id=\"findAll\" resultType=\"User\">",
    "        SELECT id, name, email, age, department, created_at, updated_at",
    "        FROM users",
    "        ORDER BY id DESC",
    "    </select>",
    "",
    "    <!-- ID로 조회 -->",
    "    <select id=\"findById\" parameterType=\"long\" resultType=\"User\">",
    "        SELECT id, name, email, age, department, created_at, updated_at",
    "        FROM users",
    "        WHERE id = #{id}",
    "    </select>",
    "",
    "    <!-- 이메일로 조회 -->",
    "    <select id=\"findByEmail\" parameterType=\"string\" resultType=\"User\">",
    "        SELECT id, name, email, age, department, created_at, updated_at",
    "        FROM users",
    "        WHERE email = #{email}",
    "    </select>",
    "",
    "    <!-- 삽입 (Auto Generated Key) -->",
    "    <insert id=\"insert\" parameterType=\"User\" useGeneratedKeys=\"true\" keyProperty=\"id\">",
    "        INSERT INTO users (name, email, age, department)",
    "        VALUES (#{name}, #{email}, #{age}, #{department})",
    "    </insert>",
    "",
    "    <!-- 수정 -->",
    "    <update id=\"update\" parameterType=\"User\">",
    "        UPDATE users",
    "        SET name       = #{name},",
    "            email      = #{email},",
    "            age        = #{age},",
    "            department = #{department},",
    "            updated_at = CURRENT_TIMESTAMP",
    "        WHERE id = #{id}",
    "    </update>",
    "",
    "    <!-- 삭제 -->",
    "    <delete id=\"deleteById\" parameterType=\"long\">",
    "        DELETE FROM users WHERE id = #{id}",
    "    </delete>",
    "",
    "    <!-- 건수 조회 -->",
    "    <select id=\"count\" resultType=\"int\">",
    "        SELECT COUNT(*) FROM users",
    "    </select>",
    "",
    "</mapper>",
    "```",
    "",
    "### XML 매퍼 핵심 규칙",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| `namespace` | Mapper 인터페이스의 **풀 패키지 경로**와 일치 |",
    "| `id` | Mapper 인터페이스의 **메서드 이름**과 일치 |",
    "| `#{param}` | PreparedStatement 파라미터 (SQL Injection 방지) |",
    "| `${param}` | 문자열 치환 (SQL Injection 위험, 동적 테이블명 등에만 사용) |",
    "| `resultType` | 반환 객체 타입 (type-aliases-package 설정 시 클래스명만) |",
    "| `parameterType` | 파라미터 타입 |",
    "| `useGeneratedKeys` | INSERT 후 자동 생성된 키를 객체에 세팅 |",
    "",
    "> **`#{}` vs `${}`**: `#{}`은 PreparedStatement로 안전하게 바인딩됩니다. `${}`는 문자열 그대로 치환되어 SQL Injection 위험이 있으므로 동적 테이블명/컬럼명에만 제한적으로 사용하세요.",
    "",
    "---",
    "",
    "# 2. 어노테이션 방식 (간단한 쿼리)",
    "",
    "XML 없이 인터페이스에 직접 SQL을 작성할 수 있습니다. 간단한 쿼리에 적합합니다.",
    "",
    "```java",
    "@Mapper",
    "public interface UserMapper {",
    "",
    "    @Select(\"SELECT * FROM users WHERE id = #{id}\")",
    "    Optional<User> findById(@Param(\"id\") Long id);",
    "",
    "    @Select(\"SELECT * FROM users ORDER BY id DESC\")",
    "    List<User> findAll();",
    "",
    "    @Insert(\"INSERT INTO users (name, email, age, department) \" +",
    "            \"VALUES (#{name}, #{email}, #{age}, #{department})\")",
    "    @Options(useGeneratedKeys = true, keyProperty = \"id\")",
    "    void insert(User user);",
    "",
    "    @Update(\"UPDATE users SET name=#{name}, email=#{email}, \" +",
    "            \"age=#{age}, department=#{department} WHERE id=#{id}\")",
    "    int update(User user);",
    "",
    "    @Delete(\"DELETE FROM users WHERE id = #{id}\")",
    "    int deleteById(@Param(\"id\") Long id);",
    "}",
    "```",
    "",
    "### XML vs 어노테이션 비교",
    "",
    "| 비교 | XML 방식 | 어노테이션 방식 |",
    "|------|---------|--------------|",
    "| SQL 관리 | XML 파일에 분리 | Java 코드 안에 작성 |",
    "| 동적 SQL | `<if>`, `<foreach>` 등 강력한 지원 | `<script>` 태그로 제한적 |",
    "| 가독성 | 긴 SQL에 유리 | 짧은 SQL에 유리 |",
    "| 유지보수 | SQL 변경 시 XML만 수정 | 코드 재컴파일 필요 |",
    "| 추천 | **복잡한 쿼리, 실무** | 단순 CRUD, 프로토타입 |",
    "",
    "---",
    "",
    "# 3. Service & Controller",
    "",
    "## Service",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class UserService {",
    "",
    "    private final UserMapper userMapper;",
    "",
    "    public List<UserResponse> findAll() {",
    "        return userMapper.findAll().stream()",
    "                .map(UserResponse::from)",
    "                .toList();",
    "    }",
    "",
    "    public UserResponse findById(Long id) {",
    "        User user = userMapper.findById(id)",
    "                .orElseThrow(() -> new RuntimeException(\"사용자를 찾을 수 없습니다: \" + id));",
    "        return UserResponse.from(user);",
    "    }",
    "",
    "    @Transactional",
    "    public UserResponse create(CreateUserRequest request) {",
    "        userMapper.findByEmail(request.getEmail())",
    "                .ifPresent(u -> {",
    "                    throw new RuntimeException(\"이미 존재하는 이메일: \" + request.getEmail());",
    "                });",
    "",
    "        User user = User.builder()",
    "                .name(request.getName())",
    "                .email(request.getEmail())",
    "                .age(request.getAge())",
    "                .department(request.getDepartment())",
    "                .build();",
    "",
    "        userMapper.insert(user);  // user.getId()에 자동 생성된 ID가 세팅됨",
    "        return UserResponse.from(user);",
    "    }",
    "",
    "    @Transactional",
    "    public UserResponse update(Long id, CreateUserRequest request) {",
    "        User user = userMapper.findById(id)",
    "                .orElseThrow(() -> new RuntimeException(\"사용자를 찾을 수 없습니다\"));",
    "",
    "        user.setName(request.getName());",
    "        user.setEmail(request.getEmail());",
    "        user.setAge(request.getAge());",
    "        user.setDepartment(request.getDepartment());",
    "",
    "        userMapper.update(user);",
    "        return UserResponse.from(user);",
    "    }",
    "",
    "    @Transactional",
    "    public void delete(Long id) {",
    "        int deleted = userMapper.deleteById(id);",
    "        if (deleted == 0) {",
    "            throw new RuntimeException(\"삭제할 사용자가 없습니다: \" + id);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "## Controller",
    "",
    "```java",
    "@RestController",
    "@RequestMapping(\"/api/users\")",
    "@RequiredArgsConstructor",
    "public class UserController {",
    "",
    "    private final UserService userService;",
    "",
    "    @GetMapping",
    "    public List<UserResponse> findAll() {",
    "        return userService.findAll();",
    "    }",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public UserResponse findById(@PathVariable Long id) {",
    "        return userService.findById(id);",
    "    }",
    "",
    "    @PostMapping",
    "    public ResponseEntity<UserResponse> create(@RequestBody @Valid CreateUserRequest request) {",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(userService.create(request));",
    "    }",
    "",
    "    @PutMapping(\"/{id}\")",
    "    public UserResponse update(@PathVariable Long id,",
    "                               @RequestBody @Valid CreateUserRequest request) {",
    "        return userService.update(id, request);",
    "    }",
    "",
    "    @DeleteMapping(\"/{id}\")",
    "    public ResponseEntity<Void> delete(@PathVariable Long id) {",
    "        userService.delete(id);",
    "        return ResponseEntity.noContent().build();",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "# 4. 동적 SQL",
    "",
    "MyBatis의 가장 강력한 기능입니다. 조건에 따라 SQL을 동적으로 조합합니다.",
    "",
    "## `<if>` (조건부 절)",
    "",
    "```xml",
    "<select id=\"findByCondition\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    WHERE 1=1",
    "    <if test=\"name != null and name != ''\">",
    "        AND name LIKE CONCAT('%', #{name}, '%')",
    "    </if>",
    "    <if test=\"department != null\">",
    "        AND department = #{department}",
    "    </if>",
    "    <if test=\"minAge != null\">",
    "        AND age >= #{minAge}",
    "    </if>",
    "    ORDER BY id DESC",
    "</select>",
    "```",
    "",
    "## `<where>` (WHERE 자동 생성)",
    "",
    "`WHERE 1=1` 대신 `<where>` 태그를 사용하면 첫 번째 조건의 `AND`를 자동으로 제거합니다.",
    "",
    "```xml",
    "<select id=\"findByCondition\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    <where>",
    "        <if test=\"name != null and name != ''\">",
    "            AND name LIKE CONCAT('%', #{name}, '%')",
    "        </if>",
    "        <if test=\"department != null\">",
    "            AND department = #{department}",
    "        </if>",
    "        <if test=\"minAge != null\">",
    "            AND age >= #{minAge}",
    "        </if>",
    "    </where>",
    "    ORDER BY id DESC",
    "</select>",
    "```",
    "",
    "## `<choose>` / `<when>` / `<otherwise>` (switch-case)",
    "",
    "```xml",
    "<select id=\"findBySort\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    ORDER BY",
    "    <choose>",
    "        <when test=\"sortBy == 'name'\">name</when>",
    "        <when test=\"sortBy == 'age'\">age DESC</when>",
    "        <otherwise>id DESC</otherwise>",
    "    </choose>",
    "</select>",
    "```",
    "",
    "## `<set>` (동적 UPDATE)",
    "",
    "```xml",
    "<update id=\"updateSelective\" parameterType=\"User\">",
    "    UPDATE users",
    "    <set>",
    "        <if test=\"name != null\">name = #{name},</if>",
    "        <if test=\"email != null\">email = #{email},</if>",
    "        <if test=\"age != null\">age = #{age},</if>",
    "        <if test=\"department != null\">department = #{department},</if>",
    "        updated_at = CURRENT_TIMESTAMP,",
    "    </set>",
    "    WHERE id = #{id}",
    "</update>",
    "```",
    "",
    "> `<set>` 태그는 마지막 쉼표를 자동으로 제거합니다.",
    "",
    "## `<foreach>` (IN 절, 배치 INSERT)",
    "",
    "```xml",
    "<!-- IN 절 -->",
    "<select id=\"findByIds\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    WHERE id IN",
    "    <foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">",
    "        #{id}",
    "    </foreach>",
    "</select>",
    "",
    "<!-- 배치 INSERT -->",
    "<insert id=\"insertBatch\" parameterType=\"list\">",
    "    INSERT INTO users (name, email, age, department)",
    "    VALUES",
    "    <foreach collection=\"list\" item=\"user\" separator=\",\">",
    "        (#{user.name}, #{user.email}, #{user.age}, #{user.department})",
    "    </foreach>",
    "</insert>",
    "```",
    "",
    "### `<foreach>` 속성",
    "",
    "| 속성 | 설명 | 예시 |",
    "|------|------|------|",
    "| `collection` | 파라미터명 | `\"ids\"`, `\"list\"` |",
    "| `item` | 반복 변수명 | `\"id\"`, `\"user\"` |",
    "| `open` | 시작 문자 | `\"(\"` |",
    "| `close` | 종료 문자 | `\")\"` |",
    "| `separator` | 구분자 | `\",\"` |",
    "",
    "## `<sql>` / `<include>` (재사용 SQL 조각)",
    "",
    "```xml",
    "<sql id=\"userColumns\">",
    "    id, name, email, age, department, created_at, updated_at",
    "</sql>",
    "",
    "<select id=\"findAll\" resultType=\"User\">",
    "    SELECT <include refid=\"userColumns\" />",
    "    FROM users",
    "    ORDER BY id DESC",
    "</select>",
    "",
    "<select id=\"findById\" resultType=\"User\">",
    "    SELECT <include refid=\"userColumns\" />",
    "    FROM users",
    "    WHERE id = #{id}",
    "</select>",
    "```",
    "",
    "### 동적 SQL 태그 정리",
    "",
    "| 태그 | 역할 | 예시 |",
    "|------|------|------|",
    "| `<if>` | 조건부 포함 | `test=\"name != null\"` |",
    "| `<where>` | WHERE + 불필요한 AND/OR 제거 | `<where><if>...</if></where>` |",
    "| `<set>` | SET + 불필요한 쉼표 제거 | 동적 UPDATE |",
    "| `<choose>` | switch-case | `<when>`, `<otherwise>` |",
    "| `<foreach>` | 반복 (IN, 배치) | `collection`, `item`, `separator` |",
    "| `<sql>` / `<include>` | SQL 조각 재사용 | 공통 컬럼 목록 |",
    "| `<trim>` | prefix/suffix 커스텀 | WHERE/SET의 일반화 |",
    "",
    "---",
    "",
    "# 5. ResultMap (복잡한 매핑)",
    "",
    "컬럼명과 필드명이 다르거나 **연관 관계(1:1, 1:N)**를 매핑할 때 사용합니다.",
    "",
    "## 기본 ResultMap",
    "",
    "```xml",
    "<resultMap id=\"userResultMap\" type=\"User\">",
    "    <id property=\"id\" column=\"user_id\" />",
    "    <result property=\"name\" column=\"user_name\" />",
    "    <result property=\"email\" column=\"user_email\" />",
    "</resultMap>",
    "",
    "<select id=\"findAll\" resultMap=\"userResultMap\">",
    "    SELECT user_id, user_name, user_email FROM users",
    "</select>",
    "```",
    "",
    "## 1:1 관계 (association)",
    "",
    "```xml",
    "<resultMap id=\"userWithDeptMap\" type=\"User\">",
    "    <id property=\"id\" column=\"id\" />",
    "    <result property=\"name\" column=\"name\" />",
    "    <association property=\"department\" javaType=\"Department\">",
    "        <id property=\"id\" column=\"dept_id\" />",
    "        <result property=\"deptName\" column=\"dept_name\" />",
    "    </association>",
    "</resultMap>",
    "",
    "<select id=\"findUserWithDepartment\" resultMap=\"userWithDeptMap\">",
    "    SELECT u.id, u.name, d.id AS dept_id, d.dept_name",
    "    FROM users u",
    "    JOIN departments d ON u.department_id = d.id",
    "    WHERE u.id = #{id}",
    "</select>",
    "```",
    "",
    "## 1:N 관계 (collection)",
    "",
    "```xml",
    "<resultMap id=\"userWithOrdersMap\" type=\"User\">",
    "    <id property=\"id\" column=\"id\" />",
    "    <result property=\"name\" column=\"name\" />",
    "    <collection property=\"orders\" ofType=\"Order\">",
    "        <id property=\"id\" column=\"order_id\" />",
    "        <result property=\"productName\" column=\"product_name\" />",
    "        <result property=\"price\" column=\"price\" />",
    "    </collection>",
    "</resultMap>",
    "",
    "<select id=\"findUserWithOrders\" resultMap=\"userWithOrdersMap\">",
    "    SELECT u.id, u.name, o.id AS order_id, o.product_name, o.price",
    "    FROM users u",
    "    LEFT JOIN orders o ON u.id = o.user_id",
    "    WHERE u.id = #{id}",
    "</select>",
    "```",
    "",
    "---",
    "",
    "# 6. 페이징",
    "",
    "## 직접 SQL 페이징",
    "",
    "```xml",
    "<select id=\"findPaged\" resultType=\"User\">",
    "    SELECT * FROM users",
    "    ORDER BY id DESC",
    "    LIMIT #{limit} OFFSET #{offset}",
    "</select>",
    "```",
    "",
    "```java",
    "@Mapper",
    "public interface UserMapper {",
    "    List<User> findPaged(@Param(\"limit\") int limit, @Param(\"offset\") int offset);",
    "}",
    "```",
    "",
    "```java",
    "// Service에서 사용",
    "public List<UserResponse> findPaged(int page, int size) {",
    "    int offset = page * size;",
    "    return userMapper.findPaged(size, offset).stream()",
    "            .map(UserResponse::from)",
    "            .toList();",
    "}",
    "```",
    "",
    "## PageHelper 플러그인",
    "",
    "```groovy",
    "implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:2.1.0'",
    "```",
    "",
    "```java",
    "public PageInfo<User> findPaged(int pageNum, int pageSize) {",
    "    PageHelper.startPage(pageNum, pageSize);",
    "    List<User> users = userMapper.findAll();",
    "    return new PageInfo<>(users);",
    "}",
    "```",
    "",
    "---",
    "",
    "# 7. TypeHandler (커스텀 타입 변환)",
    "",
    "Java 타입과 DB 타입 간 변환 규칙을 정의합니다.",
    "",
    "```java",
    "@MappedTypes(YesNo.class)",
    "public class YesNoTypeHandler extends BaseTypeHandler<Boolean> {",
    "",
    "    @Override",
    "    public void setNonNullParameter(PreparedStatement ps, int i,",
    "                                     Boolean parameter, JdbcType jdbcType) throws SQLException {",
    "        ps.setString(i, parameter ? \"Y\" : \"N\");",
    "    }",
    "",
    "    @Override",
    "    public Boolean getNullableResult(ResultSet rs, String columnName) throws SQLException {",
    "        return \"Y\".equals(rs.getString(columnName));",
    "    }",
    "",
    "    @Override",
    "    public Boolean getNullableResult(ResultSet rs, int columnIndex) throws SQLException {",
    "        return \"Y\".equals(rs.getString(columnIndex));",
    "    }",
    "",
    "    @Override",
    "    public Boolean getNullableResult(CallableStatement cs, int columnIndex) throws SQLException {",
    "        return \"Y\".equals(cs.getString(columnIndex));",
    "    }",
    "}",
    "```",
    "",
    "```yaml",
    "mybatis:",
    "  type-handlers-package: com.example.demo.typehandler",
    "```",
    "",
    "> DB에 `\"Y\"/\"N\"`으로 저장된 값을 Java의 `Boolean` `true`/`false`로 자동 변환합니다.",
    "",
    "---",
    "",
    "## MyBatis + JPA 함께 사용하기",
    "",
    "하나의 프로젝트에서 **JPA와 MyBatis를 동시에** 사용할 수 있습니다.",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'",
    "    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'",
    "}",
    "```",
    "",
    "```java",
    "// 단순 CRUD: JPA",
    "public interface UserRepository extends JpaRepository<User, Long> { }",
    "",
    "// 복잡한 통계 쿼리: MyBatis",
    "@Mapper",
    "public interface UserStatsMapper {",
    "    List<DepartmentStats> getDepartmentStats();",
    "    List<MonthlyReport> getMonthlyReport(@Param(\"year\") int year);",
    "}",
    "```",
    "",
    "| 용도 | 기술 |",
    "|------|------|",
    "| 단순 CRUD, 도메인 로직 | JPA |",
    "| 복잡한 조회, 통계, 리포트 | MyBatis |",
    "| 레거시 테이블 매핑 | MyBatis |",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "### 1. `#{}` vs `${}` 혼동 금지",
    "`#{}`은 PreparedStatement 바인딩 (안전), `${}`는 문자열 치환 (SQL Injection 위험). 사용자 입력값에는 반드시 `#{}`을 사용하세요.",
    "",
    "### 2. namespace와 메서드명 일치",
    "XML의 `namespace`는 Mapper 인터페이스의 풀 패키지 경로, `id`는 메서드명과 정확히 일치해야 합니다. 오타 시 `BindingException`이 발생합니다.",
    "",
    "### 3. resultType vs resultMap",
    "컬럼명과 필드명이 일치하면 `resultType`, 다르거나 연관 관계가 있으면 `resultMap`을 사용하세요.",
    "",
    "### 4. N+1 문제",
    "MyBatis에서도 `association`/`collection`의 `select` 속성(중첩 쿼리)을 사용하면 N+1 문제가 발생합니다. 가능하면 **JOIN을 사용한 resultMap**으로 해결하세요.",
    "",
    "### 5. @Transactional 적용",
    "MyBatis Mapper 자체는 트랜잭션을 관리하지 않습니다. Service 계층에 `@Transactional`을 적용해야 합니다.",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 구성 | 역할 |",
    "|------|------|",
    "| `@Mapper` 인터페이스 | SQL 매핑 메서드 정의 |",
    "| XML 매퍼 | SQL 작성 (동적 SQL 포함) |",
    "| `#{}` | PreparedStatement 바인딩 (안전) |",
    "| `<if>`, `<where>`, `<set>` | 동적 SQL 조건 생성 |",
    "| `<foreach>` | IN 절, 배치 INSERT |",
    "| `<sql>` / `<include>` | SQL 조각 재사용 |",
    "| `ResultMap` | 복잡한 매핑 (1:1, 1:N) |",
    "| `TypeHandler` | Java ↔ DB 타입 변환 |",
    "",
    "| 선택 기준 | 추천 |",
    "|----------|------|",
    "| SQL을 직접 제어하고 싶을 때 | **MyBatis** |",
    "| 복잡한 통계/리포트 쿼리 | **MyBatis** |",
    "| 레거시 DB 스키마 | **MyBatis** |",
    "| 빠른 CRUD 개발 | JPA |",
    "| 도메인 중심 설계 | JPA |",
    "| 둘 다 필요할 때 | **JPA + MyBatis 혼합** |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
