<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-jpa-advanced",
  title: "Spring Data JPA 심화 - QueryDSL, N+1 해결, 페이징, Auditing, Projection까지",
  date: "2026-03-03",
  summary: "실무에서 반드시 마주치는 JPA 심화 주제를 정리합니다. N+1 문제와 해결법(Fetch Join, EntityGraph, BatchSize), QueryDSL 동적 쿼리, 페이징/정렬, Auditing(생성일/수정일 자동화), Projection, Specification, 벌크 연산, 성능 최적화까지 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot", "jpa", "querydsl", "n+1", "paging", "auditing", "projection", "backend"],
  content: [
    "## N+1 문제",
    "",
    "JPA에서 가장 빈번하게 발생하는 성능 문제입니다. 연관 엔티티를 조회할 때 **1번의 쿼리로 N개의 결과**를 가져온 후, 각 결과마다 **추가 쿼리 N번**이 발생하는 현상입니다.",
    "",
    "### 문제 상황",
    "",
    "```java",
    "@Entity",
    "public class Team {",
    "    @Id @GeneratedValue",
    "    private Long id;",
    "    private String name;",
    "",
    "    @OneToMany(mappedBy = \"team\")",
    "    private List<Member> members = new ArrayList<>();",
    "}",
    "",
    "@Entity",
    "public class Member {",
    "    @Id @GeneratedValue",
    "    private Long id;",
    "    private String name;",
    "",
    "    @ManyToOne(fetch = FetchType.LAZY)",
    "    @JoinColumn(name = \"team_id\")",
    "    private Team team;",
    "}",
    "```",
    "",
    "```java",
    "List<Team> teams = teamRepository.findAll();",
    "for (Team team : teams) {",
    "    // team.getMembers()를 호출할 때마다 추가 쿼리 발생!",
    "    System.out.println(team.getName() + \": \" + team.getMembers().size());",
    "}",
    "```",
    "",
    "```sql",
    "-- 1번: 팀 목록 조회",
    "SELECT * FROM team;",
    "",
    "-- N번: 각 팀의 멤버 조회 (팀이 5개면 5번 추가)",
    "SELECT * FROM member WHERE team_id = 1;",
    "SELECT * FROM member WHERE team_id = 2;",
    "SELECT * FROM member WHERE team_id = 3;",
    "SELECT * FROM member WHERE team_id = 4;",
    "SELECT * FROM member WHERE team_id = 5;",
    "-- 총 1 + 5 = 6번 쿼리!",
    "```",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"findAll() 호출\"] --> B[\"1번 쿼리: SELECT * FROM team\"]",
    "    B --> C[\"5개 팀 반환\"]",
    "    C --> D[\"team.getMembers() 접근\"]",
    "    D --> E[\"추가 쿼리 5번 발생!\"]",
    "    E --> F[\"총 1 + N = 6번 쿼리\"]",
    "    style F fill:#f44336,color:#fff",
    "```",
    "",
    "### 해결 1: Fetch Join (JPQL)",
    "",
    "```java",
    "public interface TeamRepository extends JpaRepository<Team, Long> {",
    "",
    "    @Query(\"SELECT DISTINCT t FROM Team t JOIN FETCH t.members\")",
    "    List<Team> findAllWithMembers();",
    "}",
    "```",
    "",
    "```sql",
    "-- 단 1번의 쿼리로 팀 + 멤버를 한 번에 조회",
    "SELECT DISTINCT t.*, m.*",
    "FROM team t",
    "INNER JOIN member m ON t.id = m.team_id;",
    "```",
    "",
    "> `DISTINCT`를 넣어야 1:N 관계에서 팀이 중복으로 나오는 것을 방지합니다.",
    "",
    "**주의사항:**",
    "- Fetch Join은 **페이징과 함께 사용할 수 없음** (컬렉션 Fetch Join 시 메모리에서 페이징)",
    "- **둘 이상의 컬렉션**은 Fetch Join 불가 (MultipleBagFetchException)",
    "",
    "### 해결 2: @EntityGraph",
    "",
    "```java",
    "public interface TeamRepository extends JpaRepository<Team, Long> {",
    "",
    "    @EntityGraph(attributePaths = {\"members\"})",
    "    @Query(\"SELECT t FROM Team t\")",
    "    List<Team> findAllWithMembers();",
    "",
    "    // 메서드 이름 쿼리에도 적용 가능",
    "    @EntityGraph(attributePaths = {\"members\"})",
    "    List<Team> findAll();",
    "}",
    "```",
    "",
    "> `@EntityGraph`는 LEFT OUTER JOIN으로 동작합니다. JPQL을 직접 작성하지 않아도 됩니다.",
    "",
    "### 해결 3: @BatchSize (가장 실용적)",
    "",
    "```java",
    "@Entity",
    "public class Team {",
    "    @Id @GeneratedValue",
    "    private Long id;",
    "    private String name;",
    "",
    "    @BatchSize(size = 100)",
    "    @OneToMany(mappedBy = \"team\")",
    "    private List<Member> members = new ArrayList<>();",
    "}",
    "```",
    "",
    "또는 글로벌 설정:",
    "",
    "```yaml",
    "# application.yml",
    "spring:",
    "  jpa:",
    "    properties:",
    "      hibernate:",
    "        default_batch_fetch_size: 100",
    "```",
    "",
    "```sql",
    "-- @BatchSize 적용 시: IN 절로 한 번에 조회",
    "SELECT * FROM team;",
    "SELECT * FROM member WHERE team_id IN (1, 2, 3, 4, 5);",
    "-- 총 2번 쿼리! (1 + 1)",
    "```",
    "",
    "> **실무 권장**: 글로벌 `default_batch_fetch_size: 100`을 설정하면 N+1 문제를 대부분 해결할 수 있습니다. 페이징도 정상 동작합니다.",
    "",
    "### N+1 해결 방법 비교",
    "",
    "| 방법 | 쿼리 수 | 페이징 | 다중 컬렉션 | 사용법 |",
    "|------|--------|--------|------------|--------|",
    "| Fetch Join | **1번** | X (컬렉션) | X | `JOIN FETCH` JPQL |",
    "| @EntityGraph | **1번** | X (컬렉션) | X | 어노테이션 |",
    "| **@BatchSize** | **1+1번** | **O** | **O** | 글로벌 설정 권장 |",
    "",
    "---",
    "",
    "## QueryDSL",
    "",
    "JPQL을 **타입 안전한 Java 코드**로 작성할 수 있게 해주는 라이브러리입니다. 복잡한 동적 쿼리를 안전하고 깔끔하게 작성할 수 있습니다.",
    "",
    "### 설정 (Spring Boot 3.x + Gradle)",
    "",
    "```groovy",
    "// build.gradle",
    "dependencies {",
    "    implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'",
    "    annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'",
    "    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'",
    "    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'",
    "}",
    "```",
    "",
    "> 빌드하면 `@Entity` 클래스마다 `QTeam`, `QMember` 같은 **Q클래스**가 자동 생성됩니다.",
    "",
    "### 기본 사용법",
    "",
    "```java",
    "@Repository",
    "@RequiredArgsConstructor",
    "public class MemberQueryRepository {",
    "",
    "    private final JPAQueryFactory queryFactory;",
    "",
    "    public List<Member> findByName(String name) {",
    "        QMember member = QMember.member;",
    "",
    "        return queryFactory",
    "                .selectFrom(member)",
    "                .where(member.name.eq(name))",
    "                .fetch();",
    "    }",
    "}",
    "```",
    "",
    "### JPAQueryFactory 빈 등록",
    "",
    "```java",
    "@Configuration",
    "public class QueryDslConfig {",
    "",
    "    @Bean",
    "    public JPAQueryFactory jpaQueryFactory(EntityManager em) {",
    "        return new JPAQueryFactory(em);",
    "    }",
    "}",
    "```",
    "",
    "### 동적 쿼리 (BooleanBuilder)",
    "",
    "```java",
    "public List<Member> searchMembers(String name, Integer minAge, String teamName) {",
    "    QMember member = QMember.member;",
    "    QTeam team = QTeam.team;",
    "",
    "    BooleanBuilder builder = new BooleanBuilder();",
    "",
    "    if (name != null) {",
    "        builder.and(member.name.contains(name));",
    "    }",
    "    if (minAge != null) {",
    "        builder.and(member.age.goe(minAge));",
    "    }",
    "    if (teamName != null) {",
    "        builder.and(team.name.eq(teamName));",
    "    }",
    "",
    "    return queryFactory",
    "            .selectFrom(member)",
    "            .leftJoin(member.team, team)",
    "            .where(builder)",
    "            .orderBy(member.name.asc())",
    "            .fetch();",
    "}",
    "```",
    "",
    "### 동적 쿼리 (BooleanExpression, 더 깔끔)",
    "",
    "```java",
    "public List<Member> searchMembers(String name, Integer minAge, String teamName) {",
    "    QMember member = QMember.member;",
    "",
    "    return queryFactory",
    "            .selectFrom(member)",
    "            .leftJoin(member.team, QTeam.team)",
    "            .where(",
    "                    nameContains(name),",
    "                    ageGoe(minAge),",
    "                    teamNameEq(teamName)",
    "            )",
    "            .orderBy(member.name.asc())",
    "            .fetch();",
    "}",
    "",
    "private BooleanExpression nameContains(String name) {",
    "    return name != null ? QMember.member.name.contains(name) : null;",
    "}",
    "",
    "private BooleanExpression ageGoe(Integer minAge) {",
    "    return minAge != null ? QMember.member.age.goe(minAge) : null;",
    "}",
    "",
    "private BooleanExpression teamNameEq(String teamName) {",
    "    return teamName != null ? QTeam.team.name.eq(teamName) : null;",
    "}",
    "```",
    "",
    "> `where()`에 `null`이 들어가면 해당 조건은 **무시**됩니다. `BooleanExpression` 방식이 조건을 재사용할 수 있어 더 깔끔합니다.",
    "",
    "### QueryDSL 페이징",
    "",
    "```java",
    "public Page<Member> searchMembersPage(String name, Pageable pageable) {",
    "    QMember member = QMember.member;",
    "",
    "    List<Member> content = queryFactory",
    "            .selectFrom(member)",
    "            .where(nameContains(name))",
    "            .orderBy(member.name.asc())",
    "            .offset(pageable.getOffset())",
    "            .limit(pageable.getPageSize())",
    "            .fetch();",
    "",
    "    JPAQuery<Long> countQuery = queryFactory",
    "            .select(member.count())",
    "            .from(member)",
    "            .where(nameContains(name));",
    "",
    "    return PageableExecutionUtils.getPage(content, pageable, countQuery::fetchOne);",
    "}",
    "```",
    "",
    "> `PageableExecutionUtils.getPage()`는 마지막 페이지이거나 전체 개수가 pageSize보다 적으면 count 쿼리를 생략하는 최적화를 제공합니다.",
    "",
    "### QueryDSL DTO 반환 (Projections)",
    "",
    "```java",
    "@Getter @AllArgsConstructor",
    "public class MemberDto {",
    "    private String name;",
    "    private int age;",
    "    private String teamName;",
    "}",
    "```",
    "",
    "```java",
    "public List<MemberDto> findMemberDtos() {",
    "    QMember member = QMember.member;",
    "    QTeam team = QTeam.team;",
    "",
    "    return queryFactory",
    "            .select(Projections.constructor(MemberDto.class,",
    "                    member.name,",
    "                    member.age,",
    "                    team.name))",
    "            .from(member)",
    "            .leftJoin(member.team, team)",
    "            .fetch();",
    "}",
    "```",
    "",
    "| Projections 방식 | 설명 |",
    "|-----------------|------|",
    "| `Projections.constructor()` | **생성자** 기반 (타입/순서 매칭) |",
    "| `Projections.bean()` | Setter 기반 |",
    "| `Projections.fields()` | 필드 직접 접근 |",
    "",
    "---",
    "",
    "## 페이징과 정렬",
    "",
    "### Spring Data JPA 기본 페이징",
    "",
    "```java",
    "public interface MemberRepository extends JpaRepository<Member, Long> {",
    "",
    "    Page<Member> findByNameContaining(String name, Pageable pageable);",
    "",
    "    Slice<Member> findByAge(int age, Pageable pageable);",
    "}",
    "```",
    "",
    "```java",
    "@GetMapping(\"/members\")",
    "public Page<MemberDto> getMembers(",
    "        @RequestParam(defaultValue = \"\") String name,",
    "        @RequestParam(defaultValue = \"0\") int page,",
    "        @RequestParam(defaultValue = \"20\") int size,",
    "        @RequestParam(defaultValue = \"name,asc\") String sort) {",
    "",
    "    Pageable pageable = PageRequest.of(page, size, Sort.by(\"name\").ascending());",
    "    Page<Member> result = memberRepository.findByNameContaining(name, pageable);",
    "",
    "    return result.map(m -> new MemberDto(m.getName(), m.getAge(), m.getTeam().getName()));",
    "}",
    "```",
    "",
    "### Page vs Slice",
    "",
    "| 구분 | `Page` | `Slice` |",
    "|------|--------|---------|",
    "| count 쿼리 | **실행함** (전체 개수 조회) | **실행 안 함** |",
    "| 전체 페이지 수 | 알 수 있음 (`getTotalPages()`) | 알 수 없음 |",
    "| 사용 사례 | 일반 게시판 (페이지 번호 표시) | 무한 스크롤 (더보기 버튼) |",
    "| 응답 데이터 | `totalElements`, `totalPages` 포함 | `hasNext()` 여부만 제공 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q{\"UI에 전체 페이지 수가\<br>필요한가?\"}",
    "    Q -->|\"예 (페이지 번호)\"| P[\"Page 사용\"]",
    "    Q -->|\"아니오 (무한 스크롤)\"| S[\"Slice 사용\<br>(count 쿼리 절약)\"]",
    "```",
    "",
    "### 커스텀 count 쿼리 최적화",
    "",
    "```java",
    "@Query(value = \"SELECT m FROM Member m LEFT JOIN m.team t WHERE m.name LIKE %:name%\",",
    "       countQuery = \"SELECT COUNT(m) FROM Member m WHERE m.name LIKE %:name%\")",
    "Page<Member> findByNameCustomCount(@Param(\"name\") String name, Pageable pageable);",
    "```",
    "",
    "> 본 쿼리에 복잡한 JOIN이 있을 때, count 쿼리에서는 JOIN을 제거하여 성능을 개선합니다.",
    "",
    "---",
    "",
    "## Auditing (생성일/수정일 자동화)",
    "",
    "엔티티의 `생성일`, `수정일`, `생성자`, `수정자`를 자동으로 관리합니다.",
    "",
    "### 설정",
    "",
    "```java",
    "@Configuration",
    "@EnableJpaAuditing",
    "public class JpaAuditingConfig {",
    "",
    "    @Bean",
    "    public AuditorAware<String> auditorAware() {",
    "        return () -> {",
    "            Authentication auth = SecurityContextHolder.getContext().getAuthentication();",
    "            if (auth == null || !auth.isAuthenticated()) {",
    "                return Optional.of(\"system\");",
    "            }",
    "            return Optional.of(auth.getName());",
    "        };",
    "    }",
    "}",
    "```",
    "",
    "### BaseEntity 작성",
    "",
    "```java",
    "@Getter",
    "@MappedSuperclass",
    "@EntityListeners(AuditingEntityListener.class)",
    "public abstract class BaseEntity {",
    "",
    "    @CreatedDate",
    "    @Column(updatable = false)",
    "    private LocalDateTime createdAt;",
    "",
    "    @LastModifiedDate",
    "    private LocalDateTime updatedAt;",
    "",
    "    @CreatedBy",
    "    @Column(updatable = false)",
    "    private String createdBy;",
    "",
    "    @LastModifiedBy",
    "    private String updatedBy;",
    "}",
    "```",
    "",
    "### 엔티티에 적용",
    "",
    "```java",
    "@Entity",
    "public class Product extends BaseEntity {",
    "    @Id @GeneratedValue",
    "    private Long id;",
    "    private String name;",
    "    private int price;",
    "}",
    "```",
    "",
    "```java",
    "Product product = new Product(\"노트북\", 1500000);",
    "productRepository.save(product);",
    "",
    "// createdAt: 2026-03-03T14:30:00",
    "// updatedAt: 2026-03-03T14:30:00",
    "// createdBy: \"admin\"",
    "// updatedBy: \"admin\"",
    "",
    "product.setPrice(1400000);",
    "productRepository.save(product);",
    "// updatedAt: 2026-03-03T15:00:00  ← 자동 갱신",
    "// updatedBy: \"admin\"               ← 자동 갱신",
    "```",
    "",
    "> `@CreatedDate`와 `@LastModifiedDate`는 실무에서 거의 모든 테이블에 적용합니다. BaseEntity로 만들어두면 편리합니다.",
    "",
    "---",
    "",
    "## Projection (필요한 컬럼만 조회)",
    "",
    "엔티티 전체가 아닌 **특정 필드만** 조회하여 성능을 최적화합니다.",
    "",
    "### 인터페이스 기반 Projection (Closed Projection)",
    "",
    "```java",
    "public interface MemberNameOnly {",
    "    String getName();",
    "    int getAge();",
    "}",
    "",
    "public interface MemberRepository extends JpaRepository<Member, Long> {",
    "    List<MemberNameOnly> findProjectedByTeamName(String teamName);",
    "}",
    "```",
    "",
    "```sql",
    "-- name, age만 SELECT (전체 컬럼 X)",
    "SELECT m.name, m.age FROM member m",
    "JOIN team t ON m.team_id = t.id",
    "WHERE t.name = ?",
    "```",
    "",
    "### 클래스 기반 Projection (DTO Projection)",
    "",
    "```java",
    "@Getter @AllArgsConstructor",
    "public class MemberSummary {",
    "    private String name;",
    "    private int age;",
    "}",
    "",
    "public interface MemberRepository extends JpaRepository<Member, Long> {",
    "    List<MemberSummary> findByTeamName(String teamName);",
    "}",
    "```",
    "",
    "### 동적 Projection (제네릭)",
    "",
    "```java",
    "public interface MemberRepository extends JpaRepository<Member, Long> {",
    "",
    "    <T> List<T> findByName(String name, Class<T> type);",
    "}",
    "```",
    "",
    "```java",
    "// 상황에 따라 다른 Projection 사용",
    "List<MemberNameOnly> names = memberRepository.findByName(\"홍길동\", MemberNameOnly.class);",
    "List<MemberSummary> summaries = memberRepository.findByName(\"홍길동\", MemberSummary.class);",
    "List<Member> entities = memberRepository.findByName(\"홍길동\", Member.class);",
    "```",
    "",
    "### JPQL DTO Projection (new 연산자)",
    "",
    "```java",
    "@Query(\"SELECT new com.example.dto.MemberSummary(m.name, m.age) \" +",
    "       \"FROM Member m WHERE m.team.name = :teamName\")",
    "List<MemberSummary> findSummaryByTeam(@Param(\"teamName\") String teamName);",
    "```",
    "",
    "---",
    "",
    "## Specification (동적 쿼리, QueryDSL 없이)",
    "",
    "Spring Data JPA가 제공하는 동적 쿼리 기능입니다. QueryDSL 없이 동적 조건을 추가할 수 있습니다.",
    "",
    "### Repository 설정",
    "",
    "```java",
    "public interface MemberRepository extends JpaRepository<Member, Long>,",
    "                                          JpaSpecificationExecutor<Member> {",
    "}",
    "```",
    "",
    "### Specification 정의",
    "",
    "```java",
    "public class MemberSpec {",
    "",
    "    public static Specification<Member> nameContains(String name) {",
    "        return (root, query, cb) ->",
    "                name == null ? null : cb.like(root.get(\"name\"), \"%\" + name + \"%\");",
    "    }",
    "",
    "    public static Specification<Member> ageGreaterThan(Integer age) {",
    "        return (root, query, cb) ->",
    "                age == null ? null : cb.greaterThanOrEqualTo(root.get(\"age\"), age);",
    "    }",
    "",
    "    public static Specification<Member> teamNameEquals(String teamName) {",
    "        return (root, query, cb) -> {",
    "            if (teamName == null) return null;",
    "            Join<Member, Team> team = root.join(\"team\", JoinType.LEFT);",
    "            return cb.equal(team.get(\"name\"), teamName);",
    "        };",
    "    }",
    "}",
    "```",
    "",
    "### 사용법",
    "",
    "```java",
    "@GetMapping(\"/members/search\")",
    "public Page<Member> search(",
    "        @RequestParam(required = false) String name,",
    "        @RequestParam(required = false) Integer minAge,",
    "        @RequestParam(required = false) String teamName,",
    "        Pageable pageable) {",
    "",
    "    Specification<Member> spec = Specification",
    "            .where(MemberSpec.nameContains(name))",
    "            .and(MemberSpec.ageGreaterThan(minAge))",
    "            .and(MemberSpec.teamNameEquals(teamName));",
    "",
    "    return memberRepository.findAll(spec, pageable);",
    "}",
    "```",
    "",
    "### Specification vs QueryDSL",
    "",
    "| 항목 | Specification | QueryDSL |",
    "|------|---------------|----------|",
    "| 추가 라이브러리 | 불필요 (Spring Data JPA 내장) | 필요 |",
    "| 타입 안전성 | 문자열 기반 (`root.get(\"name\")`) | **컴파일 타임 체크** |",
    "| 가독성 | 복잡하면 읽기 어려움 | **깔끔** |",
    "| 학습 난이도 | 낮음 | 중간 |",
    "| 추천 | 간단한 동적 쿼리 | **복잡한 동적 쿼리** |",
    "",
    "---",
    "",
    "## 벌크 연산",
    "",
    "대량의 데이터를 한 번에 수정/삭제할 때 사용합니다. 건 단위로 UPDATE하면 성능이 매우 나쁩니다.",
    "",
    "### JPQL 벌크 연산",
    "",
    "```java",
    "public interface MemberRepository extends JpaRepository<Member, Long> {",
    "",
    "    @Modifying(clearAutomatically = true)",
    "    @Query(\"UPDATE Member m SET m.age = m.age + 1 WHERE m.age >= :age\")",
    "    int bulkAgeUp(@Param(\"age\") int age);",
    "",
    "    @Modifying(clearAutomatically = true)",
    "    @Query(\"DELETE FROM Member m WHERE m.team.name = :teamName\")",
    "    int deleteByTeamName(@Param(\"teamName\") String teamName);",
    "}",
    "```",
    "",
    "> `@Modifying(clearAutomatically = true)`는 벌크 연산 후 **영속성 컨텍스트를 자동으로 초기화**합니다. 이를 생략하면 DB와 영속성 컨텍스트의 데이터가 불일치합니다.",
    "",
    "### QueryDSL 벌크 연산",
    "",
    "```java",
    "long count = queryFactory",
    "        .update(member)",
    "        .set(member.age, member.age.add(1))",
    "        .where(member.age.goe(20))",
    "        .execute();",
    "",
    "em.flush();",
    "em.clear();",
    "```",
    "",
    "---",
    "",
    "## 성능 최적화 팁",
    "",
    "### 1. 지연 로딩(LAZY) 기본 설정",
    "",
    "```java",
    "// 모든 연관관계를 LAZY로 설정 (기본 원칙)",
    "@ManyToOne(fetch = FetchType.LAZY)  // 기본이 EAGER이므로 반드시 LAZY로!",
    "@JoinColumn(name = \"team_id\")",
    "private Team team;",
    "",
    "@OneToMany(mappedBy = \"team\")  // 기본이 LAZY (그대로 두면 됨)",
    "private List<Member> members;",
    "```",
    "",
    "> `@ManyToOne`, `@OneToOne`은 기본값이 EAGER입니다. **반드시 LAZY로 변경**하세요.",
    "",
    "### 2. 읽기 전용 쿼리 최적화",
    "",
    "```java",
    "@Transactional(readOnly = true)",
    "public List<Member> findAllMembers() {",
    "    return memberRepository.findAll();",
    "}",
    "```",
    "",
    "- `readOnly = true`로 설정하면 **변경 감지(Dirty Checking)를 하지 않음** → 메모리 절약",
    "- **조회 전용** 메서드에는 항상 `readOnly = true`를 붙이세요",
    "",
    "### 3. DTO로 직접 조회",
    "",
    "```java",
    "// 엔티티 조회 → DTO 변환 (영속성 컨텍스트 관리 비용 발생)",
    "List<Member> members = memberRepository.findAll();",
    "List<MemberDto> dtos = members.stream().map(MemberDto::from).toList();",
    "",
    "// DTO 직접 조회 (영속성 컨텍스트 관리 X → 성능 좋음)",
    "List<MemberDto> dtos = memberRepository.findMemberDtos();",
    "```",
    "",
    "### 4. 쿼리 힌트",
    "",
    "```java",
    "@QueryHints(value = @QueryHint(name = \"org.hibernate.readOnly\", value = \"true\"))",
    "List<Member> findReadOnlyByName(String name);",
    "```",
    "",
    "### 성능 최적화 체크리스트",
    "",
    "| 항목 | 방법 |",
    "|------|------|",
    "| 연관관계 | 모든 `@ManyToOne`, `@OneToOne`을 **LAZY** 설정 |",
    "| N+1 문제 | `default_batch_fetch_size: 100` 글로벌 설정 |",
    "| 조회 전용 | `@Transactional(readOnly = true)` 적용 |",
    "| 대량 조회 | DTO Projection 또는 Slice 사용 |",
    "| 대량 수정 | 벌크 연산 + `clearAutomatically = true` |",
    "| 페이징 | count 쿼리 최적화 또는 Slice 사용 |",
    "| 쿼리 확인 | `spring.jpa.show-sql: true` + `format_sql: true` |",
    "",
    "---",
    "",
    "## 쿼리 로그 설정",
    "",
    "```yaml",
    "spring:",
    "  jpa:",
    "    show-sql: true",
    "    properties:",
    "      hibernate:",
    "        format_sql: true",
    "        use_sql_comments: true",
    "        default_batch_fetch_size: 100",
    "",
    "logging:",
    "  level:",
    "    org.hibernate.SQL: DEBUG",
    "    org.hibernate.orm.jdbc.bind: TRACE",
    "```",
    "",
    "> 운영 환경에서는 `show-sql: false`로 비활성화하고, 로거를 통해 관리하세요.",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 주제 | 핵심 내용 |",
    "|------|----------|",
    "| **N+1 문제** | `default_batch_fetch_size: 100` 글로벌 설정 (가장 실용적) |",
    "| **QueryDSL** | BooleanExpression으로 동적 쿼리, Projections로 DTO 반환 |",
    "| **페이징** | `Page` (번호 페이징), `Slice` (무한 스크롤), count 쿼리 최적화 |",
    "| **Auditing** | `BaseEntity` + `@CreatedDate`/`@LastModifiedDate` 자동 관리 |",
    "| **Projection** | 인터페이스/클래스/동적 Projection으로 필요한 컬럼만 조회 |",
    "| **Specification** | QueryDSL 없이 동적 쿼리 (간단한 경우 적합) |",
    "| **벌크 연산** | `@Modifying(clearAutomatically = true)` + JPQL/QueryDSL |",
    "| **성능 최적화** | LAZY 기본, readOnly, DTO 직접 조회, BatchSize |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
