<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-proxy",
  title: "Spring Boot 프록시(Proxy) 완전 정리 - 개념부터 동작 원리까지",
  date: "2026-03-03",
  summary: "프록시 패턴의 개념, JDK Dynamic Proxy와 CGLIB의 차이, Spring이 프록시를 사용하는 이유(@Transactional, AOP, @Async, @Cacheable 등), ProxyFactory, 프록시 디버깅까지 실전으로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot", "proxy", "aop", "cglib", "jdk-dynamic-proxy", "transactional", "java", "backend"],
  content: [
    "## 프록시(Proxy)란?",
    "",
    "**프록시(Proxy)**는 '대리인'이라는 뜻으로, 원래 객체를 대신하여 요청을 처리하는 **대리 객체**입니다. 클라이언트는 원본 객체를 직접 호출하는 것처럼 보이지만, 실제로는 프록시가 요청을 가로채 **부가 기능을 수행**한 후 원본에게 전달합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant Client as 클라이언트",
    "    participant Proxy as 프록시",
    "    participant Target as 실제 객체",
    "    Client->>Proxy: 메서드 호출",
    "    Note over Proxy: 부가 기능 실행 전",
    "    Proxy->>Target: 실제 메서드 호출",
    "    Target-->>Proxy: 결과 반환",
    "    Note over Proxy: 부가 기능 실행 후",
    "    Proxy-->>Client: 결과 반환",
    "```",
    "",
    "### 프록시 패턴의 핵심",
    "",
    "- 클라이언트는 **프록시인지 실제 객체인지 구분하지 못함** (같은 인터페이스/타입)",
    "- 원본 코드를 **수정하지 않고** 부가 기능을 추가할 수 있음",
    "- **개방-폐쇄 원칙(OCP)**과 **단일 책임 원칙(SRP)**을 지킬 수 있음",
    "",
    "### 프록시가 하는 일 (예시)",
    "",
    "| 부가 기능 | 설명 |",
    "|-----------|------|",
    "| 트랜잭션 관리 | 메서드 시작 시 트랜잭션 시작, 종료 시 커밋/롤백 |",
    "| 로깅 | 메서드 호출 전후로 로그 출력 |",
    "| 보안 검사 | 메서드 호출 전 권한 확인 |",
    "| 캐싱 | 결과를 캐시에 저장, 동일 요청 시 캐시 반환 |",
    "| 지연 로딩 | 실제로 필요할 때까지 객체 생성을 지연 |",
    "| 비동기 실행 | 별도 스레드에서 실행 |",
    "",
    "---",
    "",
    "## 프록시 패턴 직접 구현",
    "",
    "프록시 패턴을 이해하기 위해 직접 구현해봅니다.",
    "",
    "### 인터페이스 기반 프록시",
    "",
    "```java",
    "public interface OrderService {",
    "    void createOrder(String item);",
    "}",
    "",
    "public class OrderServiceImpl implements OrderService {",
    "    @Override",
    "    public void createOrder(String item) {",
    "        System.out.println(\"주문 생성: \" + item);",
    "    }",
    "}",
    "",
    "public class OrderServiceProxy implements OrderService {",
    "    private final OrderService target;",
    "",
    "    public OrderServiceProxy(OrderService target) {",
    "        this.target = target;",
    "    }",
    "",
    "    @Override",
    "    public void createOrder(String item) {",
    "        long start = System.currentTimeMillis();",
    "        System.out.println(\"[프록시] 트랜잭션 시작\");",
    "",
    "        target.createOrder(item);",
    "",
    "        System.out.println(\"[프록시] 트랜잭션 커밋\");",
    "        long end = System.currentTimeMillis();",
    "        System.out.println(\"[프록시] 실행 시간: \" + (end - start) + \"ms\");",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "OrderService service = new OrderServiceProxy(new OrderServiceImpl());",
    "service.createOrder(\"노트북\");",
    "// [프록시] 트랜잭션 시작",
    "// 주문 생성: 노트북",
    "// [프록시] 트랜잭션 커밋",
    "// [프록시] 실행 시간: 2ms",
    "```",
    "",
    "이 방식의 문제: 서비스마다 프록시 클래스를 **일일이 만들어야** 합니다. 메서드가 100개면 프록시도 100개의 메서드를 구현해야 합니다.",
    "",
    "---",
    "",
    "## JDK Dynamic Proxy",
    "",
    "Java가 기본 제공하는 동적 프록시로, **런타임에 프록시 객체를 자동 생성**합니다. 반드시 **인터페이스가 있어야** 합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"클라이언트\"] --> B[\"JDK Dynamic Proxy\"]",
    "    B --> C[\"InvocationHandler.invoke\"]",
    "    C --> D[\"실제 객체 메서드 호출\"]",
    "    style B fill:#4CAF50,color:#fff",
    "```",
    "",
    "### 동작 원리",
    "",
    "1. `Proxy.newProxyInstance()`로 프록시 객체 생성",
    "2. 프록시의 모든 메서드 호출이 `InvocationHandler.invoke()`로 전달",
    "3. `invoke()` 안에서 부가 로직 수행 후 실제 메서드 호출",
    "",
    "### 코드 예제",
    "",
    "```java",
    "import java.lang.reflect.InvocationHandler;",
    "import java.lang.reflect.Method;",
    "import java.lang.reflect.Proxy;",
    "",
    "public class LoggingHandler implements InvocationHandler {",
    "    private final Object target;",
    "",
    "    public LoggingHandler(Object target) {",
    "        this.target = target;",
    "    }",
    "",
    "    @Override",
    "    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {",
    "        System.out.println(\"[LOG] \" + method.getName() + \"() 호출\");",
    "        long start = System.currentTimeMillis();",
    "",
    "        Object result = method.invoke(target, args);",
    "",
    "        long end = System.currentTimeMillis();",
    "        System.out.println(\"[LOG] \" + method.getName() + \"() 완료 (\" + (end - start) + \"ms)\");",
    "        return result;",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "OrderService target = new OrderServiceImpl();",
    "",
    "OrderService proxy = (OrderService) Proxy.newProxyInstance(",
    "    target.getClass().getClassLoader(),",
    "    new Class[]{OrderService.class},",
    "    new LoggingHandler(target)",
    ");",
    "",
    "proxy.createOrder(\"키보드\");",
    "// [LOG] createOrder() 호출",
    "// 주문 생성: 키보드",
    "// [LOG] createOrder() 완료 (1ms)",
    "```",
    "",
    "### JDK Dynamic Proxy 특징",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 조건 | **인터페이스 필수** |",
    "| 생성 방식 | `Proxy.newProxyInstance()` |",
    "| 핵심 | `InvocationHandler.invoke()` |",
    "| 프록시 타입 | 인터페이스 타입으로만 캐스팅 가능 |",
    "| 성능 | 리플렉션 기반이므로 약간의 오버헤드 |",
    "",
    "---",
    "",
    "## CGLIB Proxy",
    "",
    "**CGLIB(Code Generation Library)**는 인터페이스 없이 **클래스를 상속**하여 프록시를 생성합니다. 바이트코드를 조작하여 대상 클래스의 **서브클래스**를 동적으로 만듭니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"클라이언트\"] --> B[\"CGLIB Proxy\<br>(Target을 상속)\"]",
    "    B --> C[\"MethodInterceptor.intercept\"]",
    "    C --> D[\"실제 객체 메서드 호출\"]",
    "    style B fill:#2196F3,color:#fff",
    "```",
    "",
    "### 동작 원리",
    "",
    "1. 대상 클래스를 **상속(extends)**하는 프록시 클래스를 바이트코드로 생성",
    "2. 메서드 호출을 `MethodInterceptor.intercept()`로 가로챔",
    "3. `MethodProxy.invokeSuper()`로 부모(원본) 메서드 호출",
    "",
    "### 코드 예제",
    "",
    "```java",
    "import org.springframework.cglib.proxy.Enhancer;",
    "import org.springframework.cglib.proxy.MethodInterceptor;",
    "import org.springframework.cglib.proxy.MethodProxy;",
    "",
    "public class PaymentService {",
    "    public void pay(int amount) {",
    "        System.out.println(\"결제: \" + amount + \"원\");",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "Enhancer enhancer = new Enhancer();",
    "enhancer.setSuperclass(PaymentService.class);",
    "enhancer.setCallback((MethodInterceptor) (obj, method, args, proxy) -> {",
    "    System.out.println(\"[CGLIB] \" + method.getName() + \"() 시작\");",
    "    Object result = proxy.invokeSuper(obj, args);",
    "    System.out.println(\"[CGLIB] \" + method.getName() + \"() 끝\");",
    "    return result;",
    "});",
    "",
    "PaymentService proxy = (PaymentService) enhancer.create();",
    "proxy.pay(50000);",
    "// [CGLIB] pay() 시작",
    "// 결제: 50000원",
    "// [CGLIB] pay() 끝",
    "```",
    "",
    "### CGLIB 특징",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 조건 | 인터페이스 **불필요**, `final` 클래스/메서드는 프록시 불가 |",
    "| 생성 방식 | `Enhancer` 클래스 |",
    "| 핵심 | `MethodInterceptor.intercept()` |",
    "| 프록시 타입 | 대상 클래스의 **서브클래스** (실제 클래스 타입으로 캐스팅 가능) |",
    "| 성능 | 바이트코드 생성으로 JDK Proxy보다 **빠름** |",
    "",
    "---",
    "",
    "## JDK Dynamic Proxy vs CGLIB 비교",
    "",
    "| 항목 | JDK Dynamic Proxy | CGLIB |",
    "|------|-------------------|-------|",
    "| 기반 | **인터페이스** | **클래스 상속** |",
    "| 인터페이스 필요 | 필수 | 불필요 |",
    "| final 클래스 | 가능 (인터페이스만 프록시) | **불가** (상속 불가) |",
    "| final 메서드 | 프록시됨 | **프록시 불가** (오버라이딩 불가) |",
    "| 프록시 타입 | 인터페이스 타입 | 대상 클래스 타입 |",
    "| 핵심 API | `InvocationHandler` | `MethodInterceptor` |",
    "| 메서드 호출 | `method.invoke()` (리플렉션) | `proxy.invokeSuper()` (바이트코드) |",
    "| 성능 | 상대적으로 느림 | **상대적으로 빠름** |",
    "| Java 기본 제공 | O | X (라이브러리 필요, Spring에 내장) |",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q{\"프록시 대상에\<br>인터페이스가 있는가?\"}",
    "    Q -->|\"있음\"| JDK[\"JDK Dynamic Proxy\<br>(인터페이스 기반)\"]",
    "    Q -->|\"없음\"| CGLIB[\"CGLIB Proxy\<br>(클래스 상속 기반)\"]",
    "    JDK --> R[\"InvocationHandler\"]",
    "    CGLIB --> S[\"MethodInterceptor\"]",
    "```",
    "",
    "---",
    "",
    "## Spring Boot에서의 프록시",
    "",
    "Spring은 **AOP, 트랜잭션, 캐싱, 비동기** 등 핵심 기능을 프록시로 구현합니다. 개발자가 직접 프록시를 만들 필요 없이, **어노테이션 하나**로 Spring이 자동으로 프록시를 생성합니다.",
    "",
    "### Spring의 프록시 전략",
    "",
    "Spring Boot 2.0부터 기본 프록시 방식이 **CGLIB**로 변경되었습니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Spring Boot 프록시 생성\"]",
    "    A --> B{\"proxyTargetClass 설정\"}",
    "    B -->|\"true (기본값)\"| C[\"CGLIB 프록시\"]",
    "    B -->|\"false\"| D{\"인터페이스 있음?\"}",
    "    D -->|\"있음\"| E[\"JDK Dynamic Proxy\"]",
    "    D -->|\"없음\"| C",
    "    style C fill:#2196F3,color:#fff",
    "    style E fill:#4CAF50,color:#fff",
    "```",
    "",
    "```yaml",
    "# application.yml - 프록시 방식 변경 (기본: true → CGLIB)",
    "spring:",
    "  aop:",
    "    proxy-target-class: true  # CGLIB (기본값)",
    "    # proxy-target-class: false  # 인터페이스가 있으면 JDK Proxy 사용",
    "```",
    "",
    "---",
    "",
    "## Spring에서 프록시가 사용되는 곳",
    "",
    "### 1. `@Transactional` - 트랜잭션 관리",
    "",
    "가장 대표적인 프록시 활용입니다. 메서드 실행 전 트랜잭션을 시작하고, 정상 완료 시 커밋, 예외 발생 시 롤백합니다.",
    "",
    "```java",
    "@Service",
    "public class OrderService {",
    "",
    "    @Transactional",
    "    public void createOrder(OrderRequest request) {",
    "        orderRepository.save(new Order(request));",
    "        paymentService.processPayment(request.getAmount());",
    "        stockService.decreaseStock(request.getItemId());",
    "    }",
    "}",
    "```",
    "",
    "실제 동작:",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as Controller",
    "    participant P as 프록시 (OrderService$$)",
    "    participant T as 실제 OrderService",
    "    participant TX as TransactionManager",
    "    C->>P: createOrder() 호출",
    "    P->>TX: 트랜잭션 시작",
    "    P->>T: createOrder() 실제 실행",
    "    T-->>P: 정상 완료",
    "    P->>TX: 트랜잭션 커밋",
    "    P-->>C: 결과 반환",
    "    Note over P,TX: 예외 발생 시 롤백",
    "```",
    "",
    "### 2. `@Aspect` / AOP - 관점 지향 프로그래밍",
    "",
    "로깅, 성능 측정, 권한 검사 등 **횡단 관심사**를 프록시로 처리합니다.",
    "",
    "```java",
    "@Aspect",
    "@Component",
    "public class PerformanceAspect {",
    "",
    "    @Around(\"@annotation(org.springframework.web.bind.annotation.GetMapping)\")",
    "    public Object measureTime(ProceedingJoinPoint joinPoint) throws Throwable {",
    "        long start = System.currentTimeMillis();",
    "        Object result = joinPoint.proceed();",
    "        long end = System.currentTimeMillis();",
    "        log.info(\"{} 실행 시간: {}ms\", joinPoint.getSignature().getName(), end - start);",
    "        return result;",
    "    }",
    "}",
    "```",
    "",
    "### 3. `@Async` - 비동기 실행",
    "",
    "메서드를 별도의 스레드에서 비동기로 실행합니다.",
    "",
    "```java",
    "@Service",
    "public class NotificationService {",
    "",
    "    @Async",
    "    public void sendEmail(String to, String content) {",
    "        // 별도 스레드에서 실행됨",
    "        emailSender.send(to, content);",
    "    }",
    "}",
    "```",
    "",
    "프록시가 메서드 호출을 가로채 `TaskExecutor`에 작업을 제출합니다.",
    "",
    "### 4. `@Cacheable` - 캐싱",
    "",
    "메서드의 결과를 캐시에 저장하고, 동일한 파라미터로 다시 호출하면 캐시된 값을 반환합니다.",
    "",
    "```java",
    "@Service",
    "public class ProductService {",
    "",
    "    @Cacheable(value = \"products\", key = \"#id\")",
    "    public Product getProduct(Long id) {",
    "        // 첫 호출: DB 조회 후 캐시에 저장",
    "        // 이후 호출: 캐시에서 바로 반환 (이 코드 실행 안 됨)",
    "        return productRepository.findById(id).orElseThrow();",
    "    }",
    "}",
    "```",
    "",
    "### 5. `@Retryable` - 자동 재시도",
    "",
    "```java",
    "@Service",
    "public class ExternalApiService {",
    "",
    "    @Retryable(maxAttempts = 3, backoff = @Backoff(delay = 1000))",
    "    public String callExternalApi() {",
    "        // 실패 시 프록시가 자동으로 최대 3회 재시도",
    "        return restTemplate.getForObject(\"https://api.example.com/data\", String.class);",
    "    }",
    "}",
    "```",
    "",
    "### 6. `@Lazy` - 지연 초기화",
    "",
    "```java",
    "@Service",
    "@Lazy",
    "public class HeavyService {",
    "    public HeavyService() {",
    "        // 실제로 사용될 때까지 생성자가 호출되지 않음",
    "        // Spring은 프록시 객체를 먼저 주입하고, 실제 호출 시 초기화",
    "        loadHeavyResources();",
    "    }",
    "}",
    "```",
    "",
    "### 프록시 사용 어노테이션 정리",
    "",
    "| 어노테이션 | 프록시가 하는 일 | Spring 모듈 |",
    "|-----------|----------------|------------|",
    "| `@Transactional` | 트랜잭션 시작/커밋/롤백 | Spring TX |",
    "| `@Aspect` | 횡단 관심사 처리 (AOP) | Spring AOP |",
    "| `@Async` | 별도 스레드에서 비동기 실행 | Spring Async |",
    "| `@Cacheable` | 결과 캐싱, 캐시 히트 시 메서드 건너뜀 | Spring Cache |",
    "| `@Retryable` | 실패 시 자동 재시도 | Spring Retry |",
    "| `@PreAuthorize` | 권한 검사 후 허용/거부 | Spring Security |",
    "| `@Validated` | 메서드 파라미터 유효성 검사 | Spring Validation |",
    "| `@Lazy` | 실제 사용 시점까지 생성 지연 | Spring Core |",
    "",
    "---",
    "",
    "## 프록시의 핵심 주의사항",
    "",
    "### 1. 내부 호출 문제 (Self-Invocation)",
    "",
    "**같은 클래스 내에서** 메서드를 호출하면 프록시를 거치지 않아 어노테이션이 동작하지 않습니다. 이것이 프록시의 **가장 흔한 함정**입니다.",
    "",
    "```java",
    "@Service",
    "public class OrderService {",
    "",
    "    public void processOrder(Long orderId) {",
    "        // 내부 호출 → 프록시를 거치지 않음!",
    "        // @Transactional이 적용되지 않음!",
    "        this.createOrder(orderId);",
    "    }",
    "",
    "    @Transactional",
    "    public void createOrder(Long orderId) {",
    "        // 직접 호출하면 트랜잭션이 동작함",
    "        // 위의 processOrder()에서 내부 호출하면 트랜잭션 미적용",
    "        orderRepository.save(new Order(orderId));",
    "    }",
    "}",
    "```",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph \"프록시 통과 O\"",
    "        A[\"외부\"] -->|\"proxy.createOrder()\"| B[\"프록시\"] --> C[\"실제 객체\"]",
    "    end",
    "    subgraph \"프록시 통과 X\"",
    "        D[\"processOrder\"] -->|\"this.createOrder()\"| E[\"실제 객체 직접 호출\"]",
    "    end",
    "```",
    "",
    "#### 해결 방법",
    "",
    "```java",
    "// 방법 1: 별도 클래스로 분리 (권장)",
    "@Service",
    "public class OrderProcessService {",
    "    private final OrderService orderService;",
    "",
    "    public void processOrder(Long orderId) {",
    "        orderService.createOrder(orderId); // 프록시를 통해 호출",
    "    }",
    "}",
    "",
    "// 방법 2: 자기 자신을 주입 받기",
    "@Service",
    "public class OrderService {",
    "    @Lazy",
    "    @Autowired",
    "    private OrderService self;",
    "",
    "    public void processOrder(Long orderId) {",
    "        self.createOrder(orderId); // 프록시를 통해 호출",
    "    }",
    "",
    "    @Transactional",
    "    public void createOrder(Long orderId) {",
    "        orderRepository.save(new Order(orderId));",
    "    }",
    "}",
    "```",
    "",
    "### 2. final 클래스/메서드 프록시 불가 (CGLIB)",
    "",
    "```java",
    "// CGLIB은 상속 기반이므로 final은 프록시 불가",
    "public final class FinalService { // 프록시 생성 실패!",
    "    public void doSomething() { }",
    "}",
    "",
    "public class SomeService {",
    "    public final void doSomething() { } // 이 메서드만 프록시 불가!",
    "}",
    "```",
    "",
    "### 3. private 메서드는 프록시 불가",
    "",
    "```java",
    "@Service",
    "public class UserService {",
    "",
    "    @Transactional",
    "    private void internalSave() {",
    "        // private 메서드에 @Transactional을 붙여도 동작하지 않음!",
    "        // Spring이 private 메서드를 프록시할 수 없음",
    "    }",
    "}",
    "```",
    "",
    "> `@Transactional`, `@Async`, `@Cacheable` 등은 **public 메서드**에만 적용하세요.",
    "",
    "### 주의사항 요약",
    "",
    "| 문제 | 원인 | 해결 |",
    "|------|------|------|",
    "| 내부 호출 시 어노테이션 미동작 | `this.method()`는 프록시 우회 | 별도 클래스로 분리 또는 self 주입 |",
    "| final 클래스/메서드 | CGLIB이 상속 불가 | final 제거 또는 인터페이스 기반 |",
    "| private 메서드 | 프록시가 접근 불가 | public으로 변경 |",
    "| 생성자 내 호출 | 프록시 초기화 전 호출 | `@PostConstruct` 또는 이벤트 사용 |",
    "",
    "---",
    "",
    "## 실습: IntelliJ에서 프록시 동작 확인 프로젝트 만들기",
    "",
    "이론만으로는 프록시가 와닿지 않을 수 있습니다. 직접 Spring Boot 프로젝트를 만들어서 **CGLIB 프록시**와 **AOP**가 실제로 어떻게 동작하는지 눈으로 확인해봅니다.",
    "",
    "### 1. IntelliJ 프로젝트 생성",
    "",
    "IntelliJ에서 **File → New → Project → Spring Initializr**를 선택하고 아래와 같이 설정합니다.",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| Name | `springboot_proxy_example` |",
    "| Language | Java |",
    "| Type | Gradle - Groovy |",
    "| JDK | 21 |",
    "| Packaging | Jar |",
    "",
    "**Dependencies** 단계에서 다음 3개를 추가합니다:",
    "",
    "- **Lombok** (Developer Tools)",
    "- **Spring Web** (Web)",
    "- **Spring AOP** (AOP 검색 → `spring-boot-starter-aop`)",
    "",
    "### 2. build.gradle",
    "",
    "프로젝트가 생성되면 `build.gradle`이 아래와 같은지 확인합니다.",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-aop'",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "핵심 의존성 3개:",
    "",
    "| 의존성 | 역할 |",
    "|--------|------|",
    "| `spring-boot-starter-web` | REST 컨트롤러, 내장 톰캣 |",
    "| `spring-boot-starter-aop` | `@Aspect`, `@Around` 등 AOP 지원 |",
    "| `lombok` | `@Slf4j`, `@RequiredArgsConstructor` 등 보일러플레이트 제거 |",
    "",
    "### 3. 코드 작성",
    "",
    "#### DemoApplication.java",
    "",
    "`src/main/java/com/example/springboot_proxy_example/DemoApplication.java`",
    "",
    "```java",
    "package com.example.springboot_proxy_example;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "#### OrderService.java",
    "",
    "`src/main/java/com/example/springboot_proxy_example/service/OrderService.java`",
    "",
    "```java",
    "package com.example.springboot_proxy_example.service;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.stereotype.Service;",
    "import org.springframework.transaction.annotation.Transactional;",
    "",
    "@Slf4j",
    "@Service",
    "public class OrderService {",
    "",
    "    @Transactional",
    "    public String createOrder(String item) {",
    "        log.info(\"주문 생성 로직 실행 - item: {}\", item);",
    "        try {",
    "            Thread.sleep(100);",
    "        } catch (InterruptedException e) {",
    "            Thread.currentThread().interrupt();",
    "        }",
    "        return \"주문 완료: \" + item;",
    "    }",
    "}",
    "```",
    "",
    "> `@Transactional`을 붙이면 Spring이 이 클래스를 **CGLIB 프록시**로 감쌉니다. DB 연결이 없어도 프록시 자체는 생성됩니다.",
    "",
    "#### LoggingAspect.java",
    "",
    "`src/main/java/com/example/springboot_proxy_example/aspect/LoggingAspect.java`",
    "",
    "```java",
    "package com.example.springboot_proxy_example.aspect;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.aspectj.lang.ProceedingJoinPoint;",
    "import org.aspectj.lang.annotation.Around;",
    "import org.aspectj.lang.annotation.Aspect;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Slf4j",
    "@Aspect",
    "@Component",
    "public class LoggingAspect {",
    "",
    "    @Around(\"execution(* com.example.springboot_proxy_example.service..*(..))\")",
    "    public Object logExecutionTime(ProceedingJoinPoint joinPoint) throws Throwable {",
    "        String methodName = joinPoint.getSignature().toShortString();",
    "        log.info(\"[AOP] >>> {} 시작\", methodName);",
    "",
    "        long start = System.currentTimeMillis();",
    "        Object result = joinPoint.proceed();",
    "        long elapsed = System.currentTimeMillis() - start;",
    "",
    "        log.info(\"[AOP] <<< {} 완료 ({}ms)\", methodName, elapsed);",
    "        return result;",
    "    }",
    "}",
    "```",
    "",
    "> `@Around`로 `service` 패키지의 **모든 메서드** 실행 전후에 실행 시간을 측정합니다. 이것이 AOP 프록시의 핵심입니다.",
    "",
    "#### ProxyCheckController.java",
    "",
    "`src/main/java/com/example/springboot_proxy_example/controller/ProxyCheckController.java`",
    "",
    "```java",
    "package com.example.springboot_proxy_example.controller;",
    "",
    "import com.example.springboot_proxy_example.service.OrderService;",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.aop.support.AopUtils;",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.RequestMapping;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "import java.util.Map;",
    "",
    "@Slf4j",
    "@RestController",
    "@RequestMapping(\"/api/proxy\")",
    "@RequiredArgsConstructor",
    "public class ProxyCheckController {",
    "",
    "    private final OrderService orderService;",
    "",
    "    @GetMapping(\"/check\")",
    "    public Map<String, Object> checkProxy() {",
    "        String className = orderService.getClass().getName();",
    "        boolean isProxy = AopUtils.isAopProxy(orderService);",
    "        boolean isCglib = AopUtils.isCglibProxy(orderService);",
    "",
    "        log.info(\"=== 프록시 확인 ===\");",
    "        log.info(\"클래스 이름: {}\", className);",
    "        log.info(\"AOP 프록시 여부: {}\", isProxy);",
    "        log.info(\"CGLIB 프록시 여부: {}\", isCglib);",
    "",
    "        String orderResult = orderService.createOrder(\"테스트 상품\");",
    "",
    "        return Map.of(",
    "            \"className\", className,",
    "            \"isAopProxy\", isProxy,",
    "            \"isCglibProxy\", isCglib,",
    "            \"orderResult\", orderResult",
    "        );",
    "    }",
    "}",
    "```",
    "",
    "> `orderService.getClass().getName()`으로 주입된 객체의 실제 클래스 이름을 확인합니다. 프록시라면 `$$SpringCGLIB$$`가 포함됩니다.",
    "",
    "#### application.yml",
    "",
    "`src/main/resources/application.yml`",
    "",
    "```yaml",
    "spring:",
    "  application:",
    "    name: springboot-proxy-example",
    "",
    "logging:",
    "  level:",
    "    com.example.springboot_proxy_example: DEBUG",
    "    org.springframework.aop: DEBUG",
    "```",
    "",
    "### 4. 실행 및 테스트",
    "",
    "애플리케이션을 실행(`DemoApplication` → Run)한 후, 브라우저 또는 터미널에서 호출합니다.",
    "",
    "```bash",
    "curl http://localhost:8080/api/proxy/check",
    "```",
    "",
    "#### 응답 (JSON)",
    "",
    "```json",
    "{",
    "  \"className\": \"com.example.springboot_proxy_example.service.OrderService$$SpringCGLIB$$0\",",
    "  \"isAopProxy\": true,",
    "  \"isCglibProxy\": true,",
    "  \"orderResult\": \"주문 완료: 테스트 상품\"",
    "}",
    "```",
    "",
    "#### 콘솔 로그",
    "",
    "```text",
    "=== 프록시 확인 ===",
    "클래스 이름: com.example.springboot_proxy_example.service.OrderService$$SpringCGLIB$$0",
    "AOP 프록시 여부: true",
    "CGLIB 프록시 여부: true",
    "[AOP] >>> OrderService.createOrder(..) 시작",
    "주문 생성 로직 실행 - item: 테스트 상품",
    "[AOP] <<< OrderService.createOrder(..) 완료 (105ms)",
    "```",
    "",
    "#### 확인 포인트",
    "",
    "| 확인 항목 | 기대 결과 |",
    "|-----------|-----------|",
    "| `className`에 `$$SpringCGLIB$$` 포함 | Spring이 CGLIB 프록시를 생성했음을 증명 |",
    "| `isAopProxy = true` | AOP 프록시로 감싸져 있음 |",
    "| `[AOP] >>>`, `[AOP] <<<` 로그 출력 | `@Around` Aspect가 메서드 전후에 동작 |",
    "| 실행 시간 `(xxxms)` 출력 | AOP가 실행 시간을 측정하고 있음 |",
    "",
    "> `OrderService`에 `@Transactional`만 붙였는데 **프록시가 자동 생성**된 것, `LoggingAspect`의 `@Around`가 **메서드 호출을 가로채** 시간을 측정하는 것 — 이것이 Spring 프록시의 핵심입니다.",
    "",
    "---",
    "",
    "## 프록시 확인하기 (디버깅)",
    "",
    "### 프록시 여부 확인",
    "",
    "```java",
    "@Service",
    "public class DebugService {",
    "",
    "    @Autowired",
    "    private OrderService orderService;",
    "",
    "    public void checkProxy() {",
    "        System.out.println(orderService.getClass().getName());",
    "        // com.example.service.OrderService$$SpringCGLIB$$0",
    "        // → $$SpringCGLIB$$ 가 포함되어 있으면 CGLIB 프록시",
    "",
    "        System.out.println(AopUtils.isAopProxy(orderService));    // true",
    "        System.out.println(AopUtils.isCglibProxy(orderService));  // true",
    "        System.out.println(AopUtils.isJdkDynamicProxy(orderService)); // false",
    "    }",
    "}",
    "```",
    "",
    "### 프록시 내부 열어보기",
    "",
    "```java",
    "import org.springframework.aop.framework.AopProxyUtils;",
    "import org.springframework.aop.support.AopUtils;",
    "",
    "// 프록시를 통해 실제 타겟 객체 가져오기",
    "Object target = AopProxyUtils.getSingletonTarget(orderService);",
    "System.out.println(target.getClass().getName());",
    "// com.example.service.OrderService  ← 원본 클래스",
    "",
    "// 적용된 Advisor(부가 기능) 목록 확인",
    "if (orderService instanceof Advised advised) {",
    "    for (Advisor advisor : advised.getAdvisors()) {",
    "        System.out.println(advisor.getAdvice().getClass().getName());",
    "    }",
    "}",
    "```",
    "",
    "### 로그로 프록시 확인",
    "",
    "```yaml",
    "# application.yml",
    "logging:",
    "  level:",
    "    org.springframework.aop: DEBUG",
    "    org.springframework.transaction: DEBUG",
    "```",
    "",
    "---",
    "",
    "## Spring ProxyFactory",
    "",
    "Spring은 `ProxyFactory`를 통해 JDK Dynamic Proxy와 CGLIB를 **통합 관리**합니다. 개발자가 프록시 방식을 신경 쓰지 않아도 됩니다.",
    "",
    "```java",
    "import org.aopalliance.intercept.MethodInterceptor;",
    "import org.springframework.aop.framework.ProxyFactory;",
    "",
    "OrderService target = new OrderServiceImpl();",
    "",
    "ProxyFactory proxyFactory = new ProxyFactory(target);",
    "proxyFactory.addAdvice((MethodInterceptor) invocation -> {",
    "    System.out.println(\"[ProxyFactory] Before: \" + invocation.getMethod().getName());",
    "    Object result = invocation.proceed();",
    "    System.out.println(\"[ProxyFactory] After: \" + invocation.getMethod().getName());",
    "    return result;",
    "});",
    "",
    "OrderService proxy = (OrderService) proxyFactory.getProxy();",
    "proxy.createOrder(\"마우스\");",
    "// [ProxyFactory] Before: createOrder",
    "// 주문 생성: 마우스",
    "// [ProxyFactory] After: createOrder",
    "```",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"ProxyFactory\"] --> B{\"인터페이스 여부 + 설정\"}",
    "    B -->|\"인터페이스 O\<br>& proxyTargetClass=false\"| C[\"JDK Dynamic Proxy 생성\"]",
    "    B -->|\"인터페이스 X\<br>또는 proxyTargetClass=true\"| D[\"CGLIB Proxy 생성\"]",
    "    C --> E[\"동일한 Advice/Advisor 적용\"]",
    "    D --> E",
    "```",
    "",
    "> Spring이 내부적으로 `ProxyFactory`를 사용하기 때문에, 개발자는 `@Transactional`, `@Aspect` 같은 어노테이션만 사용하면 됩니다.",
    "",
    "---",
    "",
    "## 프록시와 Bean 라이프사이클",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Bean 정의 로드\"] --> B[\"Bean 인스턴스 생성\"]",
    "    B --> C[\"의존성 주입\"]",
    "    C --> D[\"@PostConstruct 실행\"]",
    "    D --> E{\"프록시 필요?\"}",
    "    E -->|\"@Transactional, @Async 등\"| F[\"BeanPostProcessor가\<br>프록시로 감싸기\"]",
    "    E -->|\"아니오\"| G[\"원본 그대로 등록\"]",
    "    F --> H[\"프록시 객체를 Bean으로 등록\"]",
    "    G --> H",
    "    H --> I[\"사용 준비 완료\"]",
    "```",
    "",
    "- `AbstractAutoProxyCreator` (BeanPostProcessor)가 빈 생성 후 프록시가 필요한 빈을 자동으로 프록시로 감쌈",
    "- 다른 빈이 주입받는 것은 **프록시 객체**",
    "",
    "---",
    "",
    "## 정리",
    "",
    "- **프록시**는 원본 객체를 대신하여 부가 기능을 수행하는 대리 객체",
    "- **JDK Dynamic Proxy**: 인터페이스 기반, `InvocationHandler`, 리플렉션 사용",
    "- **CGLIB**: 클래스 상속 기반, `MethodInterceptor`, 바이트코드 생성, Spring Boot 기본값",
    "- Spring은 `@Transactional`, `@Async`, `@Cacheable`, `@Aspect` 등에서 프록시를 자동 생성",
    "- **내부 호출(self-invocation)**은 프록시를 우회하므로 주의 (별도 클래스 분리로 해결)",
    "- `final` 클래스/메서드, `private` 메서드는 프록시 불가",
    "- `AopUtils.isAopProxy()`로 프록시 여부를 확인할 수 있음",
    "- Spring Boot 2.0+부터 기본 프록시 방식은 **CGLIB**"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
