<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-redis",
  title: "Spring Boot + Redis 완전 정리 - 캐시, 세션, 분산 락, Pub/Sub까지",
  date: "2026-02-04",
  summary: "Redis의 개념, 자료구조(String, List, Set, Hash, Sorted Set), Spring Data Redis 연동, RedisTemplate, 캐시 저장소, 세션 관리, 분산 락, Pub/Sub까지 실전 예제로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","redis","cache","session","pubsub","distributed-lock","backend"],
  content: [
    "## Redis란?",
    "",
    "**Redis**(Remote Dictionary Server)는 **인메모리(In-Memory) 데이터 저장소**입니다. 모든 데이터를 메모리에 저장하기 때문에 **읽기/쓰기가 매우 빠르며**, 캐시, 세션 관리, 메시지 브로커, 분산 락 등 다양한 용도로 사용됩니다.",
    "",
    "### RDBMS vs Redis",
    "",
    "| 비교 | RDBMS (MySQL 등) | Redis |",
    "|------|-----------------|-------|",
    "| 저장 위치 | **디스크** | **메모리** (+ 디스크 영속화 옵션) |",
    "| 속도 | 밀리초 ~ 초 단위 | **마이크로초 단위** |",
    "| 데이터 구조 | 테이블 (행/열) | Key-Value (다양한 자료구조) |",
    "| 스키마 | 엄격한 스키마 | **스키마 없음** |",
    "| 트랜잭션 | ACID 완전 지원 | 제한적 트랜잭션 |",
    "| 용도 | 영구 데이터 저장 | **캐시, 세션, 실시간 처리** |",
    "| 확장 | 수직 확장 중심 | **수평 확장 (Cluster)** |",
    "",
    "### Redis 사용 사례",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[Redis 사용 사례] --> B[캐시]",
    "    A --> C[세션 저장소]",
    "    A --> D[분산 락]",
    "    A --> E[실시간 Pub/Sub]",
    "    A --> F[랭킹/리더보드]",
    "    A --> G[Rate Limiting]",
    "",
    "    B --> B1[DB 조회 결과 캐싱]",
    "    B --> B2[API 응답 캐싱]",
    "    C --> C1[다중 서버 세션 공유]",
    "    D --> D1[동시성 제어]",
    "    D --> D2[재고 차감]",
    "    E --> E1[실시간 알림]",
    "    E --> E2[채팅]",
    "    F --> F1[Sorted Set 활용]",
    "    G --> G1[API 호출 횟수 제한]",
    "```",
    "",
    "---",
    "",
    "## Redis 자료구조",
    "",
    "Redis는 단순한 Key-Value 저장소가 아닙니다. **5가지 핵심 자료구조**를 지원하며, 각각 최적화된 용도가 있습니다.",
    "",
    "### String",
    "",
    "가장 기본적인 자료구조로, **단일 값**을 저장합니다. 문자열뿐 아니라 숫자, JSON 문자열 등 어떤 값이든 저장 가능합니다.",
    "",
    "```text",
    "SET key value           # 값 저장",
    "GET key                 # 값 조회",
    "INCR counter            # 숫자 1 증가 (원자적)",
    "DECR counter            # 숫자 1 감소",
    "SETEX key 3600 value    # TTL 3600초 설정 후 저장",
    "MSET k1 v1 k2 v2       # 여러 키 동시 저장",
    "MGET k1 k2             # 여러 키 동시 조회",
    "```",
    "",
    "**사용 사례**: 캐시, 카운터, 세션 토큰, 임시 데이터",
    "",
    "### List",
    "",
    "**순서가 있는 문자열 컬렉션**입니다. 양쪽 끝에서 삽입/삭제가 가능합니다 (Deque 구조).",
    "",
    "```text",
    "LPUSH list value        # 왼쪽에 삽입",
    "RPUSH list value        # 오른쪽에 삽입",
    "LPOP list               # 왼쪽에서 꺼내기",
    "RPOP list               # 오른쪽에서 꺼내기",
    "LRANGE list 0 -1        # 전체 조회",
    "LLEN list               # 길이 조회",
    "```",
    "",
    "**사용 사례**: 메시지 큐, 최근 활동 로그, 타임라인",
    "",
    "### Set",
    "",
    "**중복 없는 문자열 컬렉션**입니다. 집합 연산(합집합, 교집합, 차집합)을 지원합니다.",
    "",
    "```text",
    "SADD set member         # 멤버 추가",
    "SREM set member         # 멤버 제거",
    "SMEMBERS set            # 전체 멤버 조회",
    "SISMEMBER set member    # 멤버 존재 여부 확인",
    "SINTER set1 set2        # 교집합",
    "SUNION set1 set2        # 합집합",
    "SCARD set               # 멤버 수",
    "```",
    "",
    "**사용 사례**: 태그, 좋아요 사용자 목록, 온라인 유저 관리",
    "",
    "### Hash",
    "",
    "**필드-값 쌍의 컬렉션**입니다. 하나의 키 아래 여러 필드를 저장할 수 있어 객체를 표현하기에 적합합니다.",
    "",
    "```text",
    "HSET user:1 name \"홍길동\"    # 필드 설정",
    "HSET user:1 age 25          # 필드 설정",
    "HGET user:1 name            # 특정 필드 조회",
    "HGETALL user:1              # 전체 필드 조회",
    "HDEL user:1 age             # 필드 삭제",
    "HINCRBY user:1 age 1        # 숫자 필드 증가",
    "HEXISTS user:1 name         # 필드 존재 여부",
    "```",
    "",
    "**사용 사례**: 사용자 프로필, 설정 값, 장바구니",
    "",
    "### Sorted Set (ZSet)",
    "",
    "Set과 유사하지만 각 멤버에 **score(점수)** 가 있어 **정렬된 상태**로 유지됩니다.",
    "",
    "```text",
    "ZADD ranking 100 \"player1\"    # 멤버 + 점수 추가",
    "ZADD ranking 200 \"player2\"",
    "ZRANGE ranking 0 -1 WITHSCORES  # 점수 오름차순 조회",
    "ZREVRANGE ranking 0 2           # 점수 내림차순 상위 3명",
    "ZRANK ranking \"player1\"         # 순위 조회 (0부터)",
    "ZSCORE ranking \"player1\"        # 점수 조회",
    "ZINCRBY ranking 50 \"player1\"    # 점수 증가",
    "```",
    "",
    "**사용 사례**: 랭킹/리더보드, 우선순위 큐, 시간순 정렬",
    "",
    "### 자료구조 비교 표",
    "",
    "| 자료구조 | 특징 | 대표 명령어 | 대표 사용 사례 |",
    "|---------|------|-----------|--------------|",
    "| **String** | 단일 값 | GET, SET, INCR | 캐시, 카운터 |",
    "| **List** | 순서 있는 컬렉션 | LPUSH, RPOP, LRANGE | 큐, 로그 |",
    "| **Set** | 중복 없는 컬렉션 | SADD, SMEMBERS, SINTER | 태그, 유니크 방문자 |",
    "| **Hash** | 필드-값 쌍 | HSET, HGET, HGETALL | 객체 저장 |",
    "| **Sorted Set** | 점수 기반 정렬 | ZADD, ZRANGE, ZRANK | 랭킹, 리더보드 |",
    "",
    "---",
    "",
    "## 프로젝트 설정",
    "",
    "### Docker로 Redis 실행",
    "",
    "```bash",
    "# Redis 컨테이너 실행",
    "docker run -d \\",
    "  --name redis \\",
    "  -p 6379:6379 \\",
    "  redis:7-alpine",
    "",
    "# 비밀번호 설정 시",
    "docker run -d \\",
    "  --name redis \\",
    "  -p 6379:6379 \\",
    "  redis:7-alpine \\",
    "  redis-server --requirepass mypassword",
    "",
    "# Redis CLI 접속 확인",
    "docker exec -it redis redis-cli",
    "127.0.0.1:6379> PING",
    "PONG",
    "```",
    "",
    "### 의존성 추가",
    "",
    "**Gradle (build.gradle)**",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-data-redis'",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "",
    "    // 분산 락 사용 시",
    "    implementation 'org.redisson:redisson-spring-boot-starter:3.27.0'",
    "",
    "    // 세션 관리 사용 시",
    "    implementation 'org.springframework.session:spring-session-data-redis'",
    "}",
    "```",
    "",
    "### application.yml 설정",
    "",
    "```yaml",
    "spring:",
    "  data:",
    "    redis:",
    "      host: localhost",
    "      port: 6379",
    "      password: mypassword   # 비밀번호 설정 시",
    "      timeout: 6000ms",
    "      lettuce:",
    "        pool:",
    "          max-active: 10     # 최대 커넥션 수",
    "          max-idle: 10       # 최대 유휴 커넥션",
    "          min-idle: 2        # 최소 유휴 커넥션",
    "          max-wait: -1ms     # 커넥션 대기 시간 (-1: 무제한)",
    "```",
    "",
    "### Lettuce vs Jedis",
    "",
    "Spring Boot는 기본적으로 **Lettuce**를 Redis 클라이언트로 사용합니다.",
    "",
    "| 비교 | Lettuce | Jedis |",
    "|------|---------|-------|",
    "| 비동기 지원 | ✅ 비동기/리액티브 지원 | ❌ 동기만 지원 |",
    "| 스레드 안전 | ✅ 단일 커넥션 공유 가능 | ❌ 커넥션 풀 필요 |",
    "| 성능 | 높음 (Netty 기반) | 보통 |",
    "| Spring Boot 기본 | ✅ 기본 클라이언트 | ❌ 별도 설정 필요 |",
    "| Cluster 지원 | ✅ | ✅ |",
    "",
    "> 특별한 이유가 없다면 **Lettuce**를 그대로 사용하는 것이 권장됩니다.",
    "",
    "---",
    "",
    "## RedisConfig 설정",
    "",
    "### RedisConnectionFactory & RedisTemplate",
    "",
    "```java",
    "@Configuration",
    "public class RedisConfig {",
    "",
    "    @Bean",
    "    public RedisConnectionFactory redisConnectionFactory() {",
    "        return new LettuceConnectionFactory();",
    "    }",
    "",
    "    @Bean",
    "    public RedisTemplate<String, Object> redisTemplate(",
    "            RedisConnectionFactory connectionFactory) {",
    "",
    "        RedisTemplate<String, Object> template = new RedisTemplate<>();",
    "        template.setConnectionFactory(connectionFactory);",
    "",
    "        // Key: String 직렬화",
    "        template.setKeySerializer(",
    "                new StringRedisSerializer());",
    "        template.setHashKeySerializer(",
    "                new StringRedisSerializer());",
    "",
    "        // Value: JSON 직렬화",
    "        Jackson2JsonRedisSerializer<Object> jsonSerializer =",
    "                new Jackson2JsonRedisSerializer<>(Object.class);",
    "",
    "        ObjectMapper objectMapper = new ObjectMapper();",
    "        objectMapper.activateDefaultTyping(",
    "                LaissezFaireSubTypeValidator.instance,",
    "                ObjectMapper.DefaultTyping.NON_FINAL);",
    "        jsonSerializer.setObjectMapper(objectMapper);",
    "",
    "        template.setValueSerializer(jsonSerializer);",
    "        template.setHashValueSerializer(jsonSerializer);",
    "",
    "        template.afterPropertiesSet();",
    "        return template;",
    "    }",
    "",
    "    @Bean",
    "    public StringRedisTemplate stringRedisTemplate(",
    "            RedisConnectionFactory connectionFactory) {",
    "        return new StringRedisTemplate(connectionFactory);",
    "    }",
    "}",
    "```",
    "",
    "### 직렬화 방식 비교",
    "",
    "| Serializer | 특징 | 사용 상황 |",
    "|-----------|------|----------|",
    "| `StringRedisSerializer` | 문자열 그대로 저장 | Key, 단순 문자열 값 |",
    "| `Jackson2JsonRedisSerializer` | JSON 형태로 저장 | 객체를 JSON으로 변환 |",
    "| `GenericJackson2JsonRedisSerializer` | 클래스 정보 포함 JSON | 타입 정보까지 저장 필요 시 |",
    "| `JdkSerializationRedisSerializer` | Java 직렬화 (기본값) | **비권장** (가독성 나쁨) |",
    "",
    "> 기본 `JdkSerializationRedisSerializer`를 사용하면 Redis에 **바이너리 데이터**로 저장되어 redis-cli에서 값을 읽기 어렵습니다. 반드시 `StringRedisSerializer` + `Jackson2JsonRedisSerializer` 조합으로 설정하세요.",
    "",
    "---",
    "",
    "## RedisTemplate 사용법",
    "",
    "### ValueOperations (String)",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RedisStringService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    public void setValue(String key, Object value) {",
    "        ValueOperations<String, Object> ops =",
    "                redisTemplate.opsForValue();",
    "        ops.set(key, value);",
    "    }",
    "",
    "    public void setValueWithTTL(String key, Object value,",
    "                                long timeout, TimeUnit unit) {",
    "        redisTemplate.opsForValue()",
    "                .set(key, value, timeout, unit);",
    "    }",
    "",
    "    public Object getValue(String key) {",
    "        return redisTemplate.opsForValue().get(key);",
    "    }",
    "",
    "    public void increment(String key) {",
    "        redisTemplate.opsForValue().increment(key);",
    "    }",
    "",
    "    public Boolean setIfAbsent(String key, Object value) {",
    "        return redisTemplate.opsForValue()",
    "                .setIfAbsent(key, value);",
    "    }",
    "",
    "    public void delete(String key) {",
    "        redisTemplate.delete(key);",
    "    }",
    "}",
    "```",
    "",
    "### ListOperations",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RedisListService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    public void addToList(String key, Object value) {",
    "        redisTemplate.opsForList().rightPush(key, value);",
    "    }",
    "",
    "    public List<Object> getList(String key) {",
    "        return redisTemplate.opsForList()",
    "                .range(key, 0, -1);",
    "    }",
    "",
    "    public Object popFromList(String key) {",
    "        return redisTemplate.opsForList().leftPop(key);",
    "    }",
    "",
    "    public Long getListSize(String key) {",
    "        return redisTemplate.opsForList().size(key);",
    "    }",
    "",
    "    public void trimList(String key, long start, long end) {",
    "        redisTemplate.opsForList().trim(key, start, end);",
    "    }",
    "}",
    "```",
    "",
    "### SetOperations",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RedisSetService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    public void addToSet(String key, Object... values) {",
    "        redisTemplate.opsForSet().add(key, values);",
    "    }",
    "",
    "    public Set<Object> getMembers(String key) {",
    "        return redisTemplate.opsForSet().members(key);",
    "    }",
    "",
    "    public Boolean isMember(String key, Object value) {",
    "        return redisTemplate.opsForSet()",
    "                .isMember(key, value);",
    "    }",
    "",
    "    public Long getSize(String key) {",
    "        return redisTemplate.opsForSet().size(key);",
    "    }",
    "",
    "    public Set<Object> intersect(String key1, String key2) {",
    "        return redisTemplate.opsForSet()",
    "                .intersect(key1, key2);",
    "    }",
    "",
    "    public void removeFromSet(String key, Object... values) {",
    "        redisTemplate.opsForSet().remove(key, values);",
    "    }",
    "}",
    "```",
    "",
    "### HashOperations",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RedisHashService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    public void putHash(String key, String field, Object value) {",
    "        redisTemplate.opsForHash().put(key, field, value);",
    "    }",
    "",
    "    public void putAllHash(String key, Map<String, Object> map) {",
    "        redisTemplate.opsForHash().putAll(key, map);",
    "    }",
    "",
    "    public Object getHashField(String key, String field) {",
    "        return redisTemplate.opsForHash().get(key, field);",
    "    }",
    "",
    "    public Map<Object, Object> getEntireHash(String key) {",
    "        return redisTemplate.opsForHash().entries(key);",
    "    }",
    "",
    "    public void deleteHashField(String key, String... fields) {",
    "        redisTemplate.opsForHash().delete(key, (Object[]) fields);",
    "    }",
    "",
    "    public Boolean hasField(String key, String field) {",
    "        return redisTemplate.opsForHash().hasKey(key, field);",
    "    }",
    "}",
    "```",
    "",
    "### ZSetOperations (Sorted Set)",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RedisZSetService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    public void addScore(String key, Object value, double score) {",
    "        redisTemplate.opsForZSet().add(key, value, score);",
    "    }",
    "",
    "    public Set<Object> getTopN(String key, int n) {",
    "        return redisTemplate.opsForZSet()",
    "                .reverseRange(key, 0, n - 1);",
    "    }",
    "",
    "    public Set<ZSetOperations.TypedTuple<Object>> getTopNWithScores(",
    "            String key, int n) {",
    "        return redisTemplate.opsForZSet()",
    "                .reverseRangeWithScores(key, 0, n - 1);",
    "    }",
    "",
    "    public Long getRank(String key, Object value) {",
    "        return redisTemplate.opsForZSet()",
    "                .reverseRank(key, value);",
    "    }",
    "",
    "    public Double getScore(String key, Object value) {",
    "        return redisTemplate.opsForZSet()",
    "                .score(key, value);",
    "    }",
    "",
    "    public Double incrementScore(String key, Object value,",
    "                                  double delta) {",
    "        return redisTemplate.opsForZSet()",
    "                .incrementScore(key, value, delta);",
    "    }",
    "}",
    "```",
    "",
    "### Operations 비교 표",
    "",
    "| Operations | Redis 자료구조 | 주요 메서드 |",
    "|-----------|--------------|-----------|",
    "| `opsForValue()` | String | set, get, increment, setIfAbsent |",
    "| `opsForList()` | List | leftPush, rightPush, leftPop, range |",
    "| `opsForSet()` | Set | add, members, isMember, intersect |",
    "| `opsForHash()` | Hash | put, get, entries, hasKey |",
    "| `opsForZSet()` | Sorted Set | add, reverseRange, rank, score |",
    "",
    "---",
    "",
    "## 캐시 저장소로 사용",
    "",
    "### RedisCacheManager 설정",
    "",
    "```java",
    "@Configuration",
    "@EnableCaching",
    "public class RedisCacheConfig {",
    "",
    "    @Bean",
    "    public RedisCacheManager cacheManager(",
    "            RedisConnectionFactory connectionFactory) {",
    "",
    "        RedisCacheConfiguration defaultConfig =",
    "                RedisCacheConfiguration.defaultCacheConfig()",
    "                        .entryTtl(Duration.ofMinutes(30))",
    "                        .serializeKeysWith(",
    "                                RedisSerializationContext",
    "                                        .SerializationPair",
    "                                        .fromSerializer(",
    "                                                new StringRedisSerializer()))",
    "                        .serializeValuesWith(",
    "                                RedisSerializationContext",
    "                                        .SerializationPair",
    "                                        .fromSerializer(",
    "                                                new GenericJackson2JsonRedisSerializer()))",
    "                        .disableCachingNullValues();",
    "",
    "        Map<String, RedisCacheConfiguration> cacheConfigs =",
    "                new HashMap<>();",
    "",
    "        cacheConfigs.put(\"users\",",
    "                defaultConfig.entryTtl(Duration.ofHours(1)));",
    "        cacheConfigs.put(\"products\",",
    "                defaultConfig.entryTtl(Duration.ofMinutes(10)));",
    "        cacheConfigs.put(\"hotData\",",
    "                defaultConfig.entryTtl(Duration.ofMinutes(5)));",
    "",
    "        return RedisCacheManager.builder(connectionFactory)",
    "                .cacheDefaults(defaultConfig)",
    "                .withInitialCacheConfigurations(cacheConfigs)",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "### @Cacheable / @CacheEvict / @CachePut 사용",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class UserService {",
    "",
    "    private final UserRepository userRepository;",
    "",
    "    @Cacheable(value = \"users\", key = \"#id\")",
    "    public UserDto findById(Long id) {",
    "        // 캐시에 데이터가 없을 때만 DB 조회",
    "        User user = userRepository.findById(id)",
    "                .orElseThrow(() -> new UserNotFoundException(id));",
    "        return UserDto.from(user);",
    "    }",
    "",
    "    @Cacheable(",
    "            value = \"users\",",
    "            key = \"#email\",",
    "            unless = \"#result == null\"",
    "    )",
    "    public UserDto findByEmail(String email) {",
    "        return userRepository.findByEmail(email)",
    "                .map(UserDto::from)",
    "                .orElse(null);",
    "    }",
    "",
    "    @CachePut(value = \"users\", key = \"#result.id\")",
    "    public UserDto updateUser(Long id, UserUpdateRequest request) {",
    "        User user = userRepository.findById(id)",
    "                .orElseThrow(() -> new UserNotFoundException(id));",
    "        user.update(request);",
    "        return UserDto.from(userRepository.save(user));",
    "    }",
    "",
    "    @CacheEvict(value = \"users\", key = \"#id\")",
    "    public void deleteUser(Long id) {",
    "        userRepository.deleteById(id);",
    "    }",
    "",
    "    @CacheEvict(value = \"users\", allEntries = true)",
    "    public void clearAllUserCache() {",
    "        // 해당 캐시의 모든 엔트리 삭제",
    "    }",
    "}",
    "```",
    "",
    "### 캐시 어노테이션 정리",
    "",
    "| 어노테이션 | 동작 | 옵션 |",
    "|-----------|------|------|",
    "| `@Cacheable` | 캐시에 데이터가 있으면 반환, 없으면 메서드 실행 후 캐시 저장 | value, key, condition, unless |",
    "| `@CachePut` | 항상 메서드 실행 후 결과를 캐시에 갱신 | value, key |",
    "| `@CacheEvict` | 캐시에서 데이터 삭제 | value, key, allEntries |",
    "| `@Caching` | 여러 캐시 어노테이션 조합 | cacheable, put, evict |",
    "",
    "### 캐시 동작 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant S as Spring Boot",
    "    participant R as Redis 캐시",
    "    participant DB as 데이터베이스",
    "",
    "    Note over C,DB: 첫 번째 요청 (Cache Miss)",
    "    C->>S: GET /users/1",
    "    S->>R: 캐시 조회 (key: users::1)",
    "    R-->>S: null (캐시 없음)",
    "    S->>DB: SELECT * FROM users WHERE id = 1",
    "    DB-->>S: User 데이터",
    "    S->>R: 캐시 저장 (key: users::1, TTL: 1h)",
    "    S-->>C: UserDto 반환",
    "",
    "    Note over C,DB: 두 번째 요청 (Cache Hit)",
    "    C->>S: GET /users/1",
    "    S->>R: 캐시 조회 (key: users::1)",
    "    R-->>S: User 데이터 ✅",
    "    Note over S,DB: DB 조회 생략!",
    "    S-->>C: UserDto 반환 ⚡",
    "```",
    "",
    "---",
    "",
    "## 세션 저장소",
    "",
    "### Spring Session + Redis 설정",
    "",
    "분산 환경에서 **여러 서버가 동일한 세션**을 공유하려면 세션을 Redis에 저장합니다.",
    "",
    "```groovy",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.session:spring-session-data-redis'",
    "}",
    "```",
    "",
    "```java",
    "@Configuration",
    "@EnableRedisHttpSession(maxInactiveIntervalInSeconds = 1800)",
    "public class SessionConfig {",
    "",
    "    @Bean",
    "    public CookieSerializer cookieSerializer() {",
    "        DefaultCookieSerializer serializer =",
    "                new DefaultCookieSerializer();",
    "        serializer.setCookieName(\"SESSION\");",
    "        serializer.setCookiePath(\"/\");",
    "        serializer.setDomainNamePattern(\"^.+?\\\\.(\\\\w+\\\\.[a-z]+)$\");",
    "        return serializer;",
    "    }",
    "}",
    "```",
    "",
    "```yaml",
    "# application.yml",
    "spring:",
    "  session:",
    "    store-type: redis",
    "    redis:",
    "      namespace: spring:session",
    "```",
    "",
    "### 분산 환경 세션 공유",
    "",
    "```mermaid",
    "flowchart LR",
    "    C[클라이언트] -->|SESSION 쿠키| LB[로드 밸런서]",
    "    LB --> S1[서버 1]",
    "    LB --> S2[서버 2]",
    "    LB --> S3[서버 3]",
    "    S1 --> R[Redis - 세션 저장소]",
    "    S2 --> R",
    "    S3 --> R",
    "```",
    "",
    "> 어떤 서버로 요청이 가더라도 **Redis에서 동일한 세션**을 읽기 때문에 Sticky Session 없이도 세션이 유지됩니다.",
    "",
    "### 세션 사용 예제",
    "",
    "```java",
    "@RestController",
    "@RequiredArgsConstructor",
    "public class SessionController {",
    "",
    "    @PostMapping(\"/login\")",
    "    public ResponseEntity<String> login(",
    "            @RequestBody LoginRequest request,",
    "            HttpSession session) {",
    "",
    "        // 인증 로직...",
    "        session.setAttribute(\"userId\", user.getId());",
    "        session.setAttribute(\"username\", user.getUsername());",
    "        session.setAttribute(\"role\", user.getRole());",
    "",
    "        return ResponseEntity.ok(\"로그인 성공\");",
    "    }",
    "",
    "    @GetMapping(\"/me\")",
    "    public ResponseEntity<Map<String, Object>> getMyInfo(",
    "            HttpSession session) {",
    "",
    "        Long userId = (Long) session.getAttribute(\"userId\");",
    "        if (userId == null) {",
    "            return ResponseEntity.status(401).build();",
    "        }",
    "",
    "        Map<String, Object> info = Map.of(",
    "                \"userId\", userId,",
    "                \"username\", session.getAttribute(\"username\"),",
    "                \"role\", session.getAttribute(\"role\")",
    "        );",
    "        return ResponseEntity.ok(info);",
    "    }",
    "",
    "    @PostMapping(\"/logout\")",
    "    public ResponseEntity<String> logout(HttpSession session) {",
    "        session.invalidate();",
    "        return ResponseEntity.ok(\"로그아웃 성공\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 분산 락 (Redisson)",
    "",
    "여러 서버에서 **동시에 같은 자원에 접근**할 때 데이터 정합성을 보장하기 위해 **분산 락(Distributed Lock)** 을 사용합니다.",
    "",
    "### Redisson 설정",
    "",
    "```java",
    "@Configuration",
    "public class RedissonConfig {",
    "",
    "    @Bean",
    "    public RedissonClient redissonClient() {",
    "        Config config = new Config();",
    "        config.useSingleServer()",
    "                .setAddress(\"redis://localhost:6379\")",
    "                .setPassword(\"mypassword\")",
    "                .setConnectionMinimumIdleSize(5)",
    "                .setConnectionPoolSize(10);",
    "",
    "        return Redisson.create(config);",
    "    }",
    "}",
    "```",
    "",
    "### 재고 차감 예제 (동시성 제어)",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class StockService {",
    "",
    "    private final RedissonClient redissonClient;",
    "    private final StockRepository stockRepository;",
    "",
    "    public void decreaseStock(Long productId, int quantity) {",
    "        String lockKey = \"lock:stock:\" + productId;",
    "        RLock lock = redissonClient.getLock(lockKey);",
    "",
    "        try {",
    "            boolean acquired = lock.tryLock(",
    "                    10,  // 락 획득 대기 시간",
    "                    5,   // 락 점유 시간 (자동 해제)",
    "                    TimeUnit.SECONDS",
    "            );",
    "",
    "            if (!acquired) {",
    "                throw new RuntimeException(",
    "                        \"락 획득 실패: \" + productId);",
    "            }",
    "",
    "            Stock stock = stockRepository.findById(productId)",
    "                    .orElseThrow();",
    "",
    "            if (stock.getQuantity() < quantity) {",
    "                throw new RuntimeException(\"재고 부족\");",
    "            }",
    "",
    "            stock.decrease(quantity);",
    "            stockRepository.save(stock);",
    "",
    "            log.info(\"재고 차감 완료: productId={}, 남은 수량={}\",",
    "                    productId, stock.getQuantity());",
    "",
    "        } catch (InterruptedException e) {",
    "            Thread.currentThread().interrupt();",
    "            throw new RuntimeException(",
    "                    \"락 대기 중 인터럽트\", e);",
    "        } finally {",
    "            if (lock.isHeldByCurrentThread()) {",
    "                lock.unlock();",
    "            }",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### 분산 락 동작 흐름",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant S1 as 서버 1",
    "    participant R as Redis",
    "    participant S2 as 서버 2",
    "",
    "    S1->>R: tryLock(\"lock:stock:1\")",
    "    R-->>S1: 락 획득 성공 ✅",
    "    S2->>R: tryLock(\"lock:stock:1\")",
    "    R-->>S2: 대기 중... ⏳",
    "",
    "    Note over S1: 재고 차감 처리",
    "    S1->>R: unlock(\"lock:stock:1\")",
    "    R-->>S2: 락 획득 성공 ✅",
    "    Note over S2: 재고 차감 처리",
    "    S2->>R: unlock(\"lock:stock:1\")",
    "```",
    "",
    "### AOP로 분산 락 공통 처리",
    "",
    "매번 try-catch-finally를 작성하지 않도록 AOP로 분산 락을 공통 처리할 수 있습니다.",
    "",
    "```java",
    "@Target(ElementType.METHOD)",
    "@Retention(RetentionPolicy.RUNTIME)",
    "public @interface DistributedLock {",
    "    String key();",
    "    long waitTime() default 10;",
    "    long leaseTime() default 5;",
    "    TimeUnit timeUnit() default TimeUnit.SECONDS;",
    "}",
    "```",
    "",
    "```java",
    "@Aspect",
    "@Component",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class DistributedLockAspect {",
    "",
    "    private final RedissonClient redissonClient;",
    "",
    "    @Around(\"@annotation(distributedLock)\")",
    "    public Object around(ProceedingJoinPoint joinPoint,",
    "                         DistributedLock distributedLock)",
    "            throws Throwable {",
    "",
    "        String lockKey = distributedLock.key();",
    "        RLock lock = redissonClient.getLock(lockKey);",
    "",
    "        try {",
    "            boolean acquired = lock.tryLock(",
    "                    distributedLock.waitTime(),",
    "                    distributedLock.leaseTime(),",
    "                    distributedLock.timeUnit()",
    "            );",
    "",
    "            if (!acquired) {",
    "                throw new RuntimeException(",
    "                        \"분산 락 획득 실패: \" + lockKey);",
    "            }",
    "",
    "            return joinPoint.proceed();",
    "",
    "        } catch (InterruptedException e) {",
    "            Thread.currentThread().interrupt();",
    "            throw new RuntimeException(e);",
    "        } finally {",
    "            if (lock.isHeldByCurrentThread()) {",
    "                lock.unlock();",
    "            }",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "// 사용 예",
    "@DistributedLock(key = \"'lock:stock:' + #productId\")",
    "public void decreaseStock(Long productId, int quantity) {",
    "    Stock stock = stockRepository.findById(productId)",
    "            .orElseThrow();",
    "    stock.decrease(quantity);",
    "    stockRepository.save(stock);",
    "}",
    "```",
    "",
    "---",
    "",
    "## Pub/Sub",
    "",
    "Redis Pub/Sub는 **발행자(Publisher)가 채널에 메시지를 보내면**, 해당 채널을 **구독(Subscribe)하는 모든 수신자**에게 메시지가 전달되는 구조입니다.",
    "",
    "### 구조 다이어그램",
    "",
    "```mermaid",
    "flowchart LR",
    "    P1[Publisher 1] -->|convertAndSend| CH[Redis Channel: notifications]",
    "    P2[Publisher 2] -->|convertAndSend| CH",
    "    CH -->|onMessage| L1[Listener - 서버 1]",
    "    CH -->|onMessage| L2[Listener - 서버 2]",
    "    CH -->|onMessage| L3[Listener - 서버 3]",
    "```",
    "",
    "### MessageListener 구현",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class NotificationListener implements MessageListener {",
    "",
    "    private final ObjectMapper objectMapper = new ObjectMapper();",
    "",
    "    @Override",
    "    public void onMessage(Message message, byte[] pattern) {",
    "        try {",
    "            String body = new String(message.getBody());",
    "            NotificationEvent event =",
    "                    objectMapper.readValue(body,",
    "                            NotificationEvent.class);",
    "",
    "            log.info(\"알림 수신: userId={}, message={}\",",
    "                    event.getUserId(), event.getMessage());",
    "",
    "            // 실시간 알림 처리 (SSE, WebSocket 등으로 전달)",
    "            processNotification(event);",
    "",
    "        } catch (Exception e) {",
    "            log.error(\"메시지 처리 실패\", e);",
    "        }",
    "    }",
    "",
    "    private void processNotification(NotificationEvent event) {",
    "        // 알림 처리 로직",
    "    }",
    "}",
    "```",
    "",
    "### RedisMessageListenerContainer 설정",
    "",
    "```java",
    "@Configuration",
    "public class RedisPubSubConfig {",
    "",
    "    @Bean",
    "    public RedisMessageListenerContainer redisMessageListenerContainer(",
    "            RedisConnectionFactory connectionFactory,",
    "            NotificationListener notificationListener) {",
    "",
    "        RedisMessageListenerContainer container =",
    "                new RedisMessageListenerContainer();",
    "        container.setConnectionFactory(connectionFactory);",
    "",
    "        container.addMessageListener(",
    "                notificationListener,",
    "                new ChannelTopic(\"notifications\")",
    "        );",
    "",
    "        container.addMessageListener(",
    "                notificationListener,",
    "                new PatternTopic(\"chat.*\")",
    "        );",
    "",
    "        return container;",
    "    }",
    "}",
    "```",
    "",
    "### 메시지 발행 서비스",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class NotificationPublisher {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "    private final ObjectMapper objectMapper;",
    "",
    "    public void sendNotification(Long userId, String message) {",
    "        NotificationEvent event = new NotificationEvent(",
    "                userId, message, LocalDateTime.now()",
    "        );",
    "",
    "        try {",
    "            String json = objectMapper.writeValueAsString(event);",
    "            redisTemplate.convertAndSend(",
    "                    \"notifications\", json);",
    "        } catch (JsonProcessingException e) {",
    "            throw new RuntimeException(",
    "                    \"알림 발행 실패\", e);",
    "        }",
    "    }",
    "",
    "    public void sendChatMessage(String roomId,",
    "                                 String message) {",
    "        redisTemplate.convertAndSend(",
    "                \"chat.\" + roomId, message);",
    "    }",
    "}",
    "```",
    "",
    "### 알림 이벤트 DTO",
    "",
    "```java",
    "@Getter",
    "@AllArgsConstructor",
    "@NoArgsConstructor",
    "public class NotificationEvent {",
    "    private Long userId;",
    "    private String message;",
    "    private LocalDateTime timestamp;",
    "}",
    "```",
    "",
    "---",
    "",
    "## TTL & 만료 처리",
    "",
    "### TTL 설정",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RedisTTLService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    public void setWithExpire(String key, Object value,",
    "                              long timeout, TimeUnit unit) {",
    "        redisTemplate.opsForValue()",
    "                .set(key, value, timeout, unit);",
    "    }",
    "",
    "    public void setExpire(String key,",
    "                          long timeout, TimeUnit unit) {",
    "        redisTemplate.expire(key, timeout, unit);",
    "    }",
    "",
    "    public Long getExpire(String key) {",
    "        return redisTemplate.getExpire(key, TimeUnit.SECONDS);",
    "    }",
    "",
    "    public Boolean persist(String key) {",
    "        return redisTemplate.persist(key);",
    "    }",
    "}",
    "```",
    "",
    "### KeyExpirationEventMessageListener (만료 이벤트 감지)",
    "",
    "Redis 키가 만료될 때 이벤트를 받으려면 **Keyspace Notification**을 활성화해야 합니다.",
    "",
    "```bash",
    "# Redis 설정 (redis.conf 또는 CLI)",
    "CONFIG SET notify-keyspace-events Ex",
    "```",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class RedisKeyExpiredListener",
    "        extends KeyExpirationEventMessageListener {",
    "",
    "    public RedisKeyExpiredListener(",
    "            RedisMessageListenerContainer listenerContainer) {",
    "        super(listenerContainer);",
    "    }",
    "",
    "    @Override",
    "    public void onMessage(Message message, byte[] pattern) {",
    "        String expiredKey = message.toString();",
    "        log.info(\"키 만료: {}\", expiredKey);",
    "",
    "        if (expiredKey.startsWith(\"session:\")) {",
    "            handleSessionExpired(expiredKey);",
    "        } else if (expiredKey.startsWith(\"reservation:\")) {",
    "            handleReservationExpired(expiredKey);",
    "        }",
    "    }",
    "",
    "    private void handleSessionExpired(String key) {",
    "        log.info(\"세션 만료 처리: {}\", key);",
    "    }",
    "",
    "    private void handleReservationExpired(String key) {",
    "        String reservationId = key.replace(\"reservation:\", \"\");",
    "        log.info(\"예약 만료 - 자동 취소: {}\", reservationId);",
    "    }",
    "}",
    "```",
    "",
    "### TTL 활용 예제",
    "",
    "| 사용 사례 | Key 패턴 | TTL | 만료 시 동작 |",
    "|----------|---------|-----|------------|",
    "| 이메일 인증 코드 | `verify:email:{email}` | 5분 | 인증 만료 |",
    "| 비밀번호 재설정 | `reset:token:{token}` | 30분 | 토큰 무효화 |",
    "| 임시 예약 | `reservation:{id}` | 15분 | 자동 취소 |",
    "| 로그인 실패 횟수 | `login:fail:{userId}` | 1시간 | 카운터 초기화 |",
    "| API Rate Limit | `rate:{ip}:{endpoint}` | 1분 | 호출 횟수 리셋 |",
    "",
    "---",
    "",
    "## 주의사항 및 운영 팁",
    "",
    "### 메모리 관리",
    "",
    "Redis는 메모리에 데이터를 저장하므로 **메모리 관리가 핵심**입니다.",
    "",
    "```yaml",
    "# Redis 설정 (redis.conf)",
    "maxmemory 256mb",
    "maxmemory-policy allkeys-lru",
    "```",
    "",
    "| 정책 | 설명 |",
    "|------|------|",
    "| `noeviction` | 메모리 초과 시 쓰기 거부 (기본값) |",
    "| `allkeys-lru` | **모든 키 중 LRU 방식으로 제거** (캐시 용도 권장) |",
    "| `volatile-lru` | TTL이 설정된 키 중 LRU 방식으로 제거 |",
    "| `allkeys-random` | 모든 키 중 랜덤 제거 |",
    "| `volatile-ttl` | TTL이 짧은 키부터 제거 |",
    "",
    "### Serialization 주의사항",
    "",
    "- **JdkSerializationRedisSerializer (기본값)** 는 클래스 변경 시 역직렬화 실패 위험이 있고, redis-cli에서 값을 확인할 수 없습니다",
    "- 반드시 `StringRedisSerializer` + `Jackson2JsonRedisSerializer` 조합을 사용하세요",
    "- `GenericJackson2JsonRedisSerializer`는 클래스 정보(@class)를 포함하므로 패키지 변경 시 역직렬화 실패에 유의하세요",
    "",
    "### 장애 대응",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class ResilientCacheService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "    private final UserRepository userRepository;",
    "",
    "    public UserDto findUser(Long id) {",
    "        try {",
    "            Object cached = redisTemplate.opsForValue()",
    "                    .get(\"user:\" + id);",
    "            if (cached != null) {",
    "                return (UserDto) cached;",
    "            }",
    "        } catch (Exception e) {",
    "            log.warn(\"Redis 조회 실패, DB 직접 조회: {}\",",
    "                    e.getMessage());",
    "        }",
    "",
    "        // Redis 장애 시에도 DB에서 조회하여 서비스 유지",
    "        User user = userRepository.findById(id).orElseThrow();",
    "        UserDto dto = UserDto.from(user);",
    "",
    "        try {",
    "            redisTemplate.opsForValue()",
    "                    .set(\"user:\" + id, dto,",
    "                            30, TimeUnit.MINUTES);",
    "        } catch (Exception e) {",
    "            log.warn(\"Redis 캐시 저장 실패: {}\",",
    "                    e.getMessage());",
    "        }",
    "",
    "        return dto;",
    "    }",
    "}",
    "```",
    "",
    "> Redis 장애 시 **서비스 전체가 중단되지 않도록** 반드시 try-catch로 감싸고, DB 폴백 로직을 구현하세요.",
    "",
    "### 운영 체크리스트",
    "",
    "| 항목 | 설명 | 권장 사항 |",
    "|------|------|----------|",
    "| **메모리** | 메모리 부족 시 데이터 유실 | maxmemory + eviction 정책 설정 |",
    "| **영속화** | 서버 재시작 시 데이터 유실 | RDB/AOF 영속화 설정 |",
    "| **Serialization** | 역직렬화 실패 위험 | Jackson2Json 사용 |",
    "| **TTL** | 만료 없는 키 메모리 점유 | 모든 캐시 키에 TTL 설정 |",
    "| **Connection Pool** | 커넥션 고갈 | Lettuce Pool 설정 |",
    "| **모니터링** | 장애 감지 | Redis INFO, 메모리 사용량 모니터링 |",
    "| **Cluster** | 단일 장애점 제거 | Redis Sentinel 또는 Cluster 구성 |",
    "| **장애 대응** | Redis 다운 시 서비스 중단 | DB 폴백, Circuit Breaker |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 개념 | 핵심 내용 |",
    "|------|----------|",
    "| **Redis** | In-Memory 데이터 저장소, 마이크로초 단위 읽기/쓰기 |",
    "| **자료구조** | String, List, Set, Hash, Sorted Set 5가지 |",
    "| **Lettuce** | Spring Boot 기본 Redis 클라이언트 (비동기, 스레드 안전) |",
    "| **RedisTemplate** | Operations 메서드로 각 자료구조 CRUD 처리 |",
    "| **캐시** | @Cacheable + RedisCacheManager로 DB 부하 감소 |",
    "| **세션** | spring-session-data-redis로 분산 환경 세션 공유 |",
    "| **분산 락** | Redisson RLock으로 동시성 제어 (재고 차감 등) |",
    "| **Pub/Sub** | 채널 기반 실시간 메시지 전달 |",
    "| **TTL** | 키 만료 설정 + KeyExpirationEvent로 후처리 |",
    "| **Serialization** | Jackson2Json 사용 권장 (JDK 직렬화 금지) |",
    "| **장애 대응** | Redis 다운 시 DB 폴백, try-catch 필수 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
