<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-features",
  title: "Spring Boot 고유 기능 완전 정리 - ConfigurationProperties, Profile, ConditionalOn, Actuator, Auto Configuration",
  date: "2026-02-25",
  summary: "@ConfigurationProperties로 타입 안전한 설정, @Profile로 환경 분리, @ConditionalOn*으로 조건부 빈 등록, Actuator로 모니터링, Auto Configuration 원리까지 Spring Boot만의 핵심 기능을 실전 예제로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","configurationproperties","profile","actuator","autoconfiguration","java","backend"],
  content: [
    "## 개요",
    "",
    "Spring Boot는 Spring Framework 위에 **개발 편의성**과 **운영 편의성**을 더한 프레임워크입니다. 이 글에서는 Spring Boot만의 고유 기능 5가지를 정리합니다.",
    "",
    "| 기능 | 역할 | 핵심 키워드 |",
    "|------|------|-------------|",
    "| **@ConfigurationProperties** | 설정 파일 → 객체 바인딩 | 타입 안전한 설정 |",
    "| **@Profile** | 환경별 설정 분리 | dev, prod, test |",
    "| **@ConditionalOn*** | 조건부 빈 등록 | 자동 설정의 핵심 |",
    "| **Actuator** | 모니터링/관리 | health, metrics, info |",
    "| **Auto Configuration** | 자동 설정 메커니즘 | 설정 없이 동작하는 원리 |",
    "",
    "---",
    "",
    "# 1. @ConfigurationProperties",
    "",
    "## 개념",
    "",
    "`@ConfigurationProperties`는 `application.yml`(또는 `.properties`)의 설정 값을 **Java 객체에 자동으로 바인딩**해주는 어노테이션입니다. `@Value`보다 **타입 안전**하고 **구조적**으로 설정을 관리할 수 있습니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"application.yml<br/>app.jwt.secret=...<br/>app.jwt.expiration=3600\"] -->|바인딩| B[\"JwtProperties.java<br/>secret = '...'<br/>expiration = 3600\"]",
    "    B --> C[\"Service에서 주입받아 사용\"]",
    "```",
    "",
    "## @Value vs @ConfigurationProperties",
    "",
    "```java",
    "// @Value 방식 (단순하지만 관리 어려움)",
    "@Value(\"${app.jwt.secret}\")",
    "private String secret;",
    "",
    "@Value(\"${app.jwt.expiration}\")",
    "private long expiration;",
    "",
    "@Value(\"${app.jwt.issuer}\")",
    "private String issuer;",
    "```",
    "",
    "```java",
    "// @ConfigurationProperties 방식 (구조적, 타입 안전)",
    "@Getter @Setter",
    "@ConfigurationProperties(prefix = \"app.jwt\")",
    "public class JwtProperties {",
    "    private String secret;",
    "    private long expiration;",
    "    private String issuer;",
    "}",
    "```",
    "",
    "| 비교 | `@Value` | `@ConfigurationProperties` |",
    "|------|---------|---------------------------|",
    "| 바인딩 | 필드 하나씩 | **객체 단위** |",
    "| 타입 안전 | 런타임 에러 | **시작 시 검증** |",
    "| IDE 지원 | 없음 | **자동 완성** (메타데이터) |",
    "| 중첩 객체 | 불편 | **자연스러운 중첩** |",
    "| Validation | 불가 | **@Validated 사용 가능** |",
    "| 추천 | 단순 값 1~2개 | **설정 그룹 관리 (권장)** |",
    "",
    "---",
    "",
    "## 실전 예제 1: JWT 설정",
    "",
    "### application.yml",
    "",
    "```yaml",
    "app:",
    "  jwt:",
    "    secret: bXktc2VjcmV0LWtleS1mb3Itand0LTI1Ni1iaXQ=",
    "    access-token-expiration: 1800000   # 30분",
    "    refresh-token-expiration: 604800000 # 7일",
    "    issuer: my-app",
    "```",
    "",
    "### JwtProperties.java",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import jakarta.validation.constraints.NotBlank;",
    "import jakarta.validation.constraints.Positive;",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "import org.springframework.boot.context.properties.ConfigurationProperties;",
    "import org.springframework.validation.annotation.Validated;",
    "",
    "@Getter @Setter",
    "@Validated",
    "@ConfigurationProperties(prefix = \"app.jwt\")",
    "public class JwtProperties {",
    "",
    "    @NotBlank(message = \"JWT secret은 필수입니다\")",
    "    private String secret;",
    "",
    "    @Positive",
    "    private long accessTokenExpiration = 1800000;",
    "",
    "    @Positive",
    "    private long refreshTokenExpiration = 604800000;",
    "",
    "    private String issuer = \"my-app\";",
    "}",
    "```",
    "",
    "> `@Validated`를 함께 사용하면 애플리케이션 **시작 시점**에 설정 값을 검증합니다. `secret`이 비어있으면 시작 자체가 실패합니다.",
    "",
    "### 활성화 방법",
    "",
    "```java",
    "// 방법 1: 메인 클래스에 @ConfigurationPropertiesScan (권장)",
    "@SpringBootApplication",
    "@ConfigurationPropertiesScan",
    "public class DemoApplication { ... }",
    "",
    "// 방법 2: @EnableConfigurationProperties로 명시적 등록",
    "@Configuration",
    "@EnableConfigurationProperties(JwtProperties.class)",
    "public class AppConfig { ... }",
    "",
    "// 방법 3: @Component 추가 (간단하지만 비추천)",
    "@Component",
    "@ConfigurationProperties(prefix = \"app.jwt\")",
    "public class JwtProperties { ... }",
    "```",
    "",
    "### Service에서 사용",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class JwtTokenProvider {",
    "",
    "    private final JwtProperties jwtProperties;",
    "",
    "    public String generateToken(String username) {",
    "        return Jwts.builder()",
    "                .subject(username)",
    "                .issuer(jwtProperties.getIssuer())",
    "                .expiration(new Date(",
    "                    System.currentTimeMillis() + jwtProperties.getAccessTokenExpiration()))",
    "                .signWith(getKey())",
    "                .compact();",
    "    }",
    "",
    "    private SecretKey getKey() {",
    "        return Keys.hmacShaKeyFor(",
    "                Decoders.BASE64.decode(jwtProperties.getSecret()));",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 실전 예제 2: 중첩 객체 + 리스트",
    "",
    "### application.yml",
    "",
    "```yaml",
    "app:",
    "  datasource:",
    "    primary:",
    "      url: jdbc:mysql://localhost:3306/main_db",
    "      username: admin",
    "      password: secret",
    "      pool:",
    "        max-size: 20",
    "        min-idle: 5",
    "    cors:",
    "      allowed-origins:",
    "        - http://localhost:3000",
    "        - https://myapp.com",
    "      allowed-methods:",
    "        - GET",
    "        - POST",
    "        - PUT",
    "        - DELETE",
    "      max-age: 3600",
    "```",
    "",
    "### 중첩 Properties 클래스",
    "",
    "```java",
    "@Getter @Setter",
    "@ConfigurationProperties(prefix = \"app.datasource\")",
    "public class DataSourceProperties {",
    "",
    "    private Primary primary = new Primary();",
    "    private Cors cors = new Cors();",
    "",
    "    @Getter @Setter",
    "    public static class Primary {",
    "        private String url;",
    "        private String username;",
    "        private String password;",
    "        private Pool pool = new Pool();",
    "    }",
    "",
    "    @Getter @Setter",
    "    public static class Pool {",
    "        private int maxSize = 10;",
    "        private int minIdle = 2;",
    "    }",
    "",
    "    @Getter @Setter",
    "    public static class Cors {",
    "        private List<String> allowedOrigins = new ArrayList<>();",
    "        private List<String> allowedMethods = new ArrayList<>();",
    "        private long maxAge = 3600;",
    "    }",
    "}",
    "```",
    "",
    "> YAML의 계층 구조가 그대로 Java 중첩 클래스로 매핑됩니다. `kebab-case`(`max-size`)는 자동으로 `camelCase`(`maxSize`)로 변환됩니다.",
    "",
    "---",
    "",
    "## 실전 예제 3: 불변 객체(Record) 바인딩",
    "",
    "Java 16+의 `record`와 `@ConstructorBinding`을 사용하면 **불변 설정 객체**를 만들 수 있습니다.",
    "",
    "```java",
    "@ConfigurationProperties(prefix = \"app.mail\")",
    "public record MailProperties(",
    "        @NotBlank String host,",
    "        int port,",
    "        @NotBlank String username,",
    "        @NotBlank String password,",
    "        boolean starttls",
    ") {",
    "    public MailProperties {",
    "        if (port <= 0) port = 587;",
    "    }",
    "}",
    "```",
    "",
    "```yaml",
    "app:",
    "  mail:",
    "    host: smtp.gmail.com",
    "    port: 587",
    "    username: user@gmail.com",
    "    password: ${MAIL_PASSWORD}",
    "    starttls: true",
    "```",
    "",
    "---",
    "",
    "# 2. @Profile",
    "",
    "## 개념",
    "",
    "`@Profile`은 **환경(Profile)에 따라** 다른 빈을 등록하거나 다른 설정을 적용하는 기능입니다. 개발(dev), 운영(prod), 테스트(test) 환경을 분리할 수 있습니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Spring Boot 시작\"] --> B{\"활성 Profile?\"}",
    "    B -->|dev| C[\"application-dev.yml<br/>H2 인메모리 DB<br/>DEBUG 로깅\"]",
    "    B -->|prod| D[\"application-prod.yml<br/>MySQL<br/>WARN 로깅\"]",
    "    B -->|test| E[\"application-test.yml<br/>테스트 DB<br/>테스트 설정\"]",
    "```",
    "",
    "## 환경별 설정 파일",
    "",
    "### application.yml (공통)",
    "",
    "```yaml",
    "spring:",
    "  application:",
    "    name: my-app",
    "  profiles:",
    "    active: dev  # 기본 활성 프로파일",
    "```",
    "",
    "### application-dev.yml (개발)",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:devdb",
    "    username: sa",
    "    password:",
    "    driver-class-name: org.h2.Driver",
    "  h2:",
    "    console:",
    "      enabled: true",
    "  jpa:",
    "    show-sql: true",
    "    hibernate:",
    "      ddl-auto: create-drop",
    "",
    "logging:",
    "  level:",
    "    com.example: DEBUG",
    "    org.hibernate.SQL: DEBUG",
    "",
    "server:",
    "  port: 8080",
    "```",
    "",
    "### application-prod.yml (운영)",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:mysql://${DB_HOST:localhost}:3306/proddb",
    "    username: ${DB_USERNAME}",
    "    password: ${DB_PASSWORD}",
    "    driver-class-name: com.mysql.cj.jdbc.Driver",
    "  jpa:",
    "    show-sql: false",
    "    hibernate:",
    "      ddl-auto: validate",
    "",
    "logging:",
    "  level:",
    "    com.example: WARN",
    "",
    "server:",
    "  port: ${SERVER_PORT:8080}",
    "```",
    "",
    "## Profile 활성화 방법",
    "",
    "```bash",
    "# 방법 1: application.yml에서 설정",
    "spring.profiles.active: dev",
    "",
    "# 방법 2: JVM 옵션",
    "java -jar app.jar -Dspring.profiles.active=prod",
    "",
    "# 방법 3: 환경 변수",
    "export SPRING_PROFILES_ACTIVE=prod",
    "",
    "# 방법 4: 프로그램 인자",
    "java -jar app.jar --spring.profiles.active=prod",
    "```",
    "",
    "## @Profile로 환경별 빈 등록",
    "",
    "```java",
    "// 개발 환경에서만 등록되는 빈",
    "@Configuration",
    "@Profile(\"dev\")",
    "public class DevConfig {",
    "",
    "    @Bean",
    "    public DataInitializer dataInitializer() {",
    "        return new DataInitializer(); // 테스트 데이터 자동 생성",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "// 운영 환경에서만 등록되는 빈",
    "@Configuration",
    "@Profile(\"prod\")",
    "public class ProdConfig {",
    "",
    "    @Bean",
    "    public CacheManager cacheManager() {",
    "        return new RedisCacheManager(...); // Redis 캐시",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "// 여러 프로파일 조합",
    "@Profile(\"dev | test\")       // dev 또는 test",
    "@Profile(\"!prod\")            // prod가 아닌 경우",
    "@Profile({\"dev\", \"staging\"}) // dev 또는 staging",
    "```",
    "",
    "## 인터페이스 + Profile 패턴",
    "",
    "```java",
    "public interface StorageService {",
    "    String store(MultipartFile file);",
    "}",
    "",
    "@Service",
    "@Profile(\"dev\")",
    "public class LocalStorageService implements StorageService {",
    "    @Override",
    "    public String store(MultipartFile file) {",
    "        // 로컬 파일 시스템에 저장",
    "        return \"/uploads/\" + file.getOriginalFilename();",
    "    }",
    "}",
    "",
    "@Service",
    "@Profile(\"prod\")",
    "public class S3StorageService implements StorageService {",
    "    @Override",
    "    public String store(MultipartFile file) {",
    "        // AWS S3에 저장",
    "        return \"https://s3.amazonaws.com/bucket/\" + file.getOriginalFilename();",
    "    }",
    "}",
    "```",
    "",
    "> 같은 인터페이스를 구현하되, Profile에 따라 다른 구현체가 주입됩니다. Controller/Service는 변경 없이 환경에 맞게 동작합니다.",
    "",
    "---",
    "",
    "# 3. @ConditionalOn* 어노테이션",
    "",
    "## 개념",
    "",
    "`@ConditionalOn*`은 **특정 조건이 충족될 때만 빈을 등록**하는 어노테이션입니다. Spring Boot의 **Auto Configuration**이 동작하는 핵심 메커니즘입니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"@Configuration 클래스\"] --> B{\"@ConditionalOn* 조건 체크\"}",
    "    B -->|조건 충족| C[\"빈 등록\"]",
    "    B -->|조건 미충족| D[\"빈 등록 안 함 (무시)\"]",
    "```",
    "",
    "## 주요 @ConditionalOn* 어노테이션",
    "",
    "| 어노테이션 | 조건 | 예시 |",
    "|------------|------|------|",
    "| `@ConditionalOnProperty` | **설정 값**이 특정 값일 때 | `app.cache.enabled=true` |",
    "| `@ConditionalOnClass` | **클래스**가 클래스패스에 있을 때 | Redis 라이브러리 존재 여부 |",
    "| `@ConditionalOnMissingClass` | 클래스가 없을 때 | |",
    "| `@ConditionalOnBean` | **빈**이 이미 등록되어 있을 때 | DataSource 빈 존재 여부 |",
    "| `@ConditionalOnMissingBean` | **빈**이 없을 때 | 사용자 정의 빈이 없으면 기본 빈 등록 |",
    "| `@ConditionalOnWebApplication` | 웹 애플리케이션일 때 | |",
    "| `@ConditionalOnExpression` | **SpEL 표현식**이 true일 때 | 복합 조건 |",
    "",
    "---",
    "",
    "## 실전 예제 1: @ConditionalOnProperty",
    "",
    "설정 값에 따라 기능을 켜고 끕니다.",
    "",
    "### application.yml",
    "",
    "```yaml",
    "app:",
    "  cache:",
    "    enabled: true",
    "    type: redis",
    "  notification:",
    "    email:",
    "      enabled: true",
    "    sms:",
    "      enabled: false",
    "```",
    "",
    "### 설정에 따른 빈 등록",
    "",
    "```java",
    "@Configuration",
    "public class CacheConfig {",
    "",
    "    @Bean",
    "    @ConditionalOnProperty(",
    "            name = \"app.cache.enabled\",",
    "            havingValue = \"true\",",
    "            matchIfMissing = false  // 설정이 없으면 등록 안 함",
    "    )",
    "    public CacheManager cacheManager() {",
    "        return new ConcurrentMapCacheManager(\"users\", \"products\");",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@Configuration",
    "public class NotificationConfig {",
    "",
    "    @Bean",
    "    @ConditionalOnProperty(name = \"app.notification.email.enabled\", havingValue = \"true\")",
    "    public EmailNotificationService emailNotificationService() {",
    "        return new EmailNotificationService();",
    "    }",
    "",
    "    @Bean",
    "    @ConditionalOnProperty(name = \"app.notification.sms.enabled\", havingValue = \"true\")",
    "    public SmsNotificationService smsNotificationService() {",
    "        return new SmsNotificationService();",
    "    }",
    "}",
    "```",
    "",
    "> `matchIfMissing = true`로 설정하면 프로퍼티가 아예 없을 때도 조건이 충족됩니다 (기본값은 false).",
    "",
    "## 실전 예제 2: @ConditionalOnClass",
    "",
    "특정 라이브러리가 클래스패스에 있을 때만 빈을 등록합니다.",
    "",
    "```java",
    "@Configuration",
    "public class CacheAutoConfig {",
    "",
    "    @Bean",
    "    @ConditionalOnClass(name = \"org.springframework.data.redis.core.RedisTemplate\")",
    "    public CacheManager redisCacheManager() {",
    "        // Redis 의존성이 있을 때만 Redis 캐시 사용",
    "        return new RedisCacheManager(...);",
    "    }",
    "",
    "    @Bean",
    "    @ConditionalOnMissingClass(\"org.springframework.data.redis.core.RedisTemplate\")",
    "    public CacheManager simpleCacheManager() {",
    "        // Redis가 없으면 인메모리 캐시 사용",
    "        return new ConcurrentMapCacheManager();",
    "    }",
    "}",
    "```",
    "",
    "## 실전 예제 3: @ConditionalOnMissingBean",
    "",
    "사용자가 직접 빈을 정의하지 않았을 때만 기본 빈을 제공합니다.",
    "",
    "```java",
    "@Configuration",
    "public class DefaultServiceConfig {",
    "",
    "    @Bean",
    "    @ConditionalOnMissingBean(PasswordEncoder.class)",
    "    public PasswordEncoder passwordEncoder() {",
    "        // 사용자가 PasswordEncoder를 직접 등록하지 않았으면",
    "        // 기본값으로 BCrypt 사용",
    "        return new BCryptPasswordEncoder();",
    "    }",
    "}",
    "```",
    "",
    "> Spring Boot의 Auto Configuration이 바로 이 패턴입니다. 사용자가 직접 빈을 등록하면 그것을 우선 사용하고, 없으면 기본값을 제공합니다.",
    "",
    "## 실전 예제 4: @ConditionalOnExpression",
    "",
    "복합 조건이 필요할 때 SpEL 표현식을 사용합니다.",
    "",
    "```java",
    "@Bean",
    "@ConditionalOnExpression(",
    "    \"${app.cache.enabled:false} and '${app.cache.type}'.equals('redis')\"",
    ")",
    "public CacheManager redisCacheManager() {",
    "    // cache가 enabled이고 type이 redis일 때만 등록",
    "    return new RedisCacheManager(...);",
    "}",
    "```",
    "",
    "---",
    "",
    "# 4. Spring Boot Actuator",
    "",
    "## 개념",
    "",
    "**Actuator**는 운영 중인 애플리케이션을 **모니터링하고 관리**할 수 있는 HTTP 엔드포인트를 제공합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"운영자/모니터링 시스템\"] -->|\"/actuator/health\"| B[\"Spring Boot<br/>Actuator\"]",
    "    B --> C[\"헬스 체크\"]",
    "    B --> D[\"메트릭\"]",
    "    B --> E[\"환경 정보\"]",
    "    B --> F[\"빈 목록\"]",
    "    B --> G[\"HTTP 요청 추적\"]",
    "```",
    "",
    "## 의존성",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-actuator'",
    "}",
    "```",
    "",
    "## application.yml 설정",
    "",
    "```yaml",
    "management:",
    "  endpoints:",
    "    web:",
    "      exposure:",
    "        include: health,info,metrics,env,beans,loggers,mappings",
    "        # include: \"*\"  # 전체 노출 (개발용)",
    "  endpoint:",
    "    health:",
    "      show-details: always  # 상세 헬스 정보",
    "    shutdown:",
    "      enabled: false        # 원격 종료 비활성화 (보안)",
    "  info:",
    "    env:",
    "      enabled: true",
    "",
    "info:",
    "  app:",
    "    name: My Application",
    "    version: 1.0.0",
    "    description: Spring Boot 예제 프로젝트",
    "```",
    "",
    "## 주요 엔드포인트",
    "",
    "| 엔드포인트 | 설명 | 예시 URL |",
    "|------------|------|----------|",
    "| `/actuator/health` | 애플리케이션 상태 (UP/DOWN) | DB, 디스크, 외부 서비스 상태 |",
    "| `/actuator/info` | 앱 정보 | 이름, 버전, 설명 |",
    "| `/actuator/metrics` | 메트릭 목록 | JVM, HTTP, 커스텀 메트릭 |",
    "| `/actuator/metrics/{name}` | 특정 메트릭 상세 | CPU, 메모리, 요청 수 |",
    "| `/actuator/env` | 환경 변수, 설정 값 | Profile, Properties |",
    "| `/actuator/beans` | 등록된 빈 목록 | 모든 Spring Bean |",
    "| `/actuator/mappings` | URL 매핑 정보 | Controller 엔드포인트 목록 |",
    "| `/actuator/loggers` | 로깅 레벨 조회/변경 | 런타임 로그 레벨 변경 |",
    "| `/actuator/shutdown` | 앱 종료 (위험!) | POST로 원격 종료 |",
    "",
    "---",
    "",
    "## 응답 예시",
    "",
    "### /actuator/health",
    "",
    "```json",
    "{",
    "  \"status\": \"UP\",",
    "  \"components\": {",
    "    \"db\": {",
    "      \"status\": \"UP\",",
    "      \"details\": {",
    "        \"database\": \"MySQL\",",
    "        \"validationQuery\": \"isValid()\"",
    "      }",
    "    },",
    "    \"diskSpace\": {",
    "      \"status\": \"UP\",",
    "      \"details\": {",
    "        \"total\": 499963174912,",
    "        \"free\": 258741207040,",
    "        \"threshold\": 10485760",
    "      }",
    "    },",
    "    \"ping\": {",
    "      \"status\": \"UP\"",
    "    }",
    "  }",
    "}",
    "```",
    "",
    "### /actuator/metrics/jvm.memory.used",
    "",
    "```json",
    "{",
    "  \"name\": \"jvm.memory.used\",",
    "  \"description\": \"The amount of used memory\",",
    "  \"baseUnit\": \"bytes\",",
    "  \"measurements\": [",
    "    { \"statistic\": \"VALUE\", \"value\": 157286400 }",
    "  ],",
    "  \"availableTags\": [",
    "    { \"tag\": \"area\", \"values\": [\"heap\", \"nonheap\"] }",
    "  ]",
    "}",
    "```",
    "",
    "---",
    "",
    "## 커스텀 Health Indicator",
    "",
    "외부 서비스(결제 API, 메시지 큐 등)의 상태를 헬스 체크에 추가할 수 있습니다.",
    "",
    "```java",
    "package com.example.demo.actuator;",
    "",
    "import org.springframework.boot.actuate.health.Health;",
    "import org.springframework.boot.actuate.health.HealthIndicator;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Component",
    "public class PaymentApiHealthIndicator implements HealthIndicator {",
    "",
    "    @Override",
    "    public Health health() {",
    "        try {",
    "            // 결제 API 헬스 체크 로직",
    "            boolean isUp = checkPaymentApi();",
    "",
    "            if (isUp) {",
    "                return Health.up()",
    "                        .withDetail(\"service\", \"Payment API\")",
    "                        .withDetail(\"url\", \"https://api.payment.com\")",
    "                        .build();",
    "            } else {",
    "                return Health.down()",
    "                        .withDetail(\"error\", \"결제 API 응답 없음\")",
    "                        .build();",
    "            }",
    "        } catch (Exception e) {",
    "            return Health.down(e).build();",
    "        }",
    "    }",
    "",
    "    private boolean checkPaymentApi() {",
    "        // 실제 헬스 체크 로직 (ping, 상태 조회 등)",
    "        return true;",
    "    }",
    "}",
    "```",
    "",
    "**응답:**",
    "",
    "```json",
    "{",
    "  \"status\": \"UP\",",
    "  \"components\": {",
    "    \"paymentApi\": {",
    "      \"status\": \"UP\",",
    "      \"details\": {",
    "        \"service\": \"Payment API\",",
    "        \"url\": \"https://api.payment.com\"",
    "      }",
    "    }",
    "  }",
    "}",
    "```",
    "",
    "## 커스텀 메트릭",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class OrderService {",
    "",
    "    private final MeterRegistry meterRegistry;",
    "    private final Counter orderCounter;",
    "",
    "    public OrderService(MeterRegistry meterRegistry) {",
    "        this.meterRegistry = meterRegistry;",
    "        this.orderCounter = Counter.builder(\"orders.created\")",
    "                .description(\"생성된 주문 수\")",
    "                .tag(\"type\", \"total\")",
    "                .register(meterRegistry);",
    "    }",
    "",
    "    public Order createOrder(CreateOrderRequest request) {",
    "        Order order = processOrder(request);",
    "        orderCounter.increment();",
    "        return order;",
    "    }",
    "}",
    "```",
    "",
    "```",
    "GET /actuator/metrics/orders.created",
    "→ {\"name\":\"orders.created\", \"measurements\":[{\"statistic\":\"COUNT\",\"value\":42.0}]}",
    "```",
    "",
    "## Actuator 보안",
    "",
    "운영 환경에서는 Actuator 엔드포인트에 대한 **접근 제어**가 필수입니다.",
    "",
    "```java",
    "@Bean",
    "public SecurityFilterChain actuatorSecurity(HttpSecurity http) throws Exception {",
    "    http.securityMatcher(\"/actuator/**\")",
    "        .authorizeHttpRequests(auth -> auth",
    "            .requestMatchers(\"/actuator/health\").permitAll()",
    "            .requestMatchers(\"/actuator/**\").hasRole(\"ADMIN\")",
    "        );",
    "    return http.build();",
    "}",
    "```",
    "",
    "```yaml",
    "# 또는 별도 포트로 분리 (외부 접근 차단)",
    "management:",
    "  server:",
    "    port: 9090  # Actuator를 별도 포트로",
    "```",
    "",
    "---",
    "",
    "# 5. Auto Configuration 원리",
    "",
    "## 개념",
    "",
    "**Auto Configuration**은 Spring Boot의 핵심 철학인 **\"설정보다 관습(Convention over Configuration)\"**을 구현하는 메커니즘입니다. 클래스패스의 라이브러리와 설정을 분석하여 **필요한 빈을 자동으로 등록**합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"spring-boot-starter-web 추가\"] --> B[\"클래스패스에<br/>Tomcat, Jackson, Spring MVC 존재\"]",
    "    B --> C[\"Auto Configuration 동작\"]",
    "    C --> D[\"DispatcherServlet 자동 등록\"]",
    "    C --> E[\"내장 Tomcat 자동 설정\"]",
    "    C --> F[\"Jackson ObjectMapper 자동 등록\"]",
    "    C --> G[\"에러 핸들링 자동 설정\"]",
    "```",
    "",
    "> `spring-boot-starter-web`을 추가하기만 하면 별도 설정 없이 웹 서버가 동작하는 이유가 바로 Auto Configuration입니다.",
    "",
    "## 동작 원리",
    "",
    "### @SpringBootApplication 분해",
    "",
    "```java",
    "@SpringBootApplication",
    "// ↓ 이 어노테이션은 3가지를 포함합니다",
    "",
    "@SpringBootConfiguration    // @Configuration과 동일",
    "@EnableAutoConfiguration    // ★ 자동 설정 활성화",
    "@ComponentScan              // 컴포넌트 스캔",
    "public class DemoApplication { ... }",
    "```",
    "",
    "### @EnableAutoConfiguration 동작 과정",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"@EnableAutoConfiguration\"] --> B[\"META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports 파일 로드\"]",
    "    B --> C[\"자동 설정 후보 클래스 목록 로드<br/>(수백 개)\"]",
    "    C --> D[\"각 클래스의 @ConditionalOn* 조건 평가\"]",
    "    D -->|조건 충족| E[\"빈 등록\"]",
    "    D -->|조건 미충족| F[\"무시\"]",
    "```",
    "",
    "### 실제 Auto Configuration 예시 (DataSource)",
    "",
    "Spring Boot의 `DataSourceAutoConfiguration` 내부를 단순화하면 다음과 같습니다.",
    "",
    "```java",
    "@AutoConfiguration",
    "@ConditionalOnClass(DataSource.class)    // DataSource 클래스가 있을 때만",
    "@EnableConfigurationProperties(DataSourceProperties.class)",
    "public class DataSourceAutoConfiguration {",
    "",
    "    @Bean",
    "    @ConditionalOnMissingBean  // 사용자가 직접 DataSource를 등록하지 않았을 때만",
    "    public DataSource dataSource(DataSourceProperties properties) {",
    "        return DataSourceBuilder.create()",
    "                .url(properties.getUrl())",
    "                .username(properties.getUsername())",
    "                .password(properties.getPassword())",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "### 핵심 패턴",
    "",
    "```",
    "1. @ConditionalOnClass    → 라이브러리가 있는지 확인",
    "2. @ConditionalOnMissingBean → 사용자가 직접 등록하지 않았는지 확인",
    "3. @ConfigurationProperties → 설정 값 바인딩",
    "4. 기본값으로 빈 등록       → 설정 없이도 동작",
    "```",
    "",
    "> 이 패턴 덕분에 \"starter만 추가하면 동작\"하는 Spring Boot의 마법이 가능합니다.",
    "",
    "---",
    "",
    "## 커스텀 Auto Configuration 만들기",
    "",
    "자체 라이브러리에 Auto Configuration을 추가하는 방법입니다.",
    "",
    "### 1단계: Properties 클래스",
    "",
    "```java",
    "@Getter @Setter",
    "@ConfigurationProperties(prefix = \"my.greeting\")",
    "public class GreetingProperties {",
    "    private boolean enabled = true;",
    "    private String prefix = \"Hello\";",
    "    private String suffix = \"!\";",
    "}",
    "```",
    "",
    "### 2단계: 서비스 클래스",
    "",
    "```java",
    "@RequiredArgsConstructor",
    "public class GreetingService {",
    "",
    "    private final GreetingProperties properties;",
    "",
    "    public String greet(String name) {",
    "        return properties.getPrefix() + \", \" + name + properties.getSuffix();",
    "    }",
    "}",
    "```",
    "",
    "### 3단계: Auto Configuration 클래스",
    "",
    "```java",
    "@AutoConfiguration",
    "@ConditionalOnProperty(",
    "        name = \"my.greeting.enabled\",",
    "        havingValue = \"true\",",
    "        matchIfMissing = true",
    ")",
    "@EnableConfigurationProperties(GreetingProperties.class)",
    "public class GreetingAutoConfiguration {",
    "",
    "    @Bean",
    "    @ConditionalOnMissingBean",
    "    public GreetingService greetingService(GreetingProperties properties) {",
    "        return new GreetingService(properties);",
    "    }",
    "}",
    "```",
    "",
    "### 4단계: imports 파일 등록",
    "",
    "```",
    "src/main/resources/",
    "└── META-INF/spring/",
    "    └── org.springframework.boot.autoconfigure.AutoConfiguration.imports",
    "```",
    "",
    "```",
    "com.example.greeting.GreetingAutoConfiguration",
    "```",
    "",
    "### 사용 결과",
    "",
    "```yaml",
    "# application.yml",
    "my:",
    "  greeting:",
    "    prefix: 안녕하세요",
    "    suffix: 님!",
    "```",
    "",
    "```java",
    "@RestController",
    "@RequiredArgsConstructor",
    "public class HelloController {",
    "",
    "    private final GreetingService greetingService;",
    "",
    "    @GetMapping(\"/hello\")",
    "    public String hello(@RequestParam String name) {",
    "        return greetingService.greet(name);",
    "        // → \"안녕하세요, 홍길동님!\"",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Auto Configuration 디버깅",
    "",
    "어떤 Auto Configuration이 적용/제외되었는지 확인하는 방법입니다.",
    "",
    "```yaml",
    "# application.yml",
    "debug: true  # Auto Configuration 리포트 출력",
    "```",
    "",
    "```bash",
    "# 또는 실행 시 옵션",
    "java -jar app.jar --debug",
    "```",
    "",
    "**콘솔 출력:**",
    "",
    "```",
    "============================",
    "CONDITIONS EVALUATION REPORT",
    "============================",
    "",
    "Positive matches:   (적용된 Auto Configuration)",
    "-----------------",
    "   DataSourceAutoConfiguration matched:",
    "      - @ConditionalOnClass found required classes 'javax.sql.DataSource'",
    "",
    "Negative matches:   (적용되지 않은 Auto Configuration)",
    "-----------------",
    "   RedisAutoConfiguration:",
    "      - @ConditionalOnClass did not find required class 'RedisConnectionFactory'",
    "```",
    "",
    "## 특정 Auto Configuration 제외",
    "",
    "```java",
    "@SpringBootApplication(",
    "    exclude = {",
    "        DataSourceAutoConfiguration.class,  // DB 자동 설정 제외",
    "        SecurityAutoConfiguration.class      // Security 자동 설정 제외",
    "    }",
    ")",
    "public class DemoApplication { ... }",
    "```",
    "",
    "---",
    "",
    "## 전체 흐름 정리",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Spring Boot 시작\"] --> B[\"@SpringBootApplication\"]",
    "    B --> C[\"@ComponentScan<br/>개발자 작성 코드 스캔\"]",
    "    B --> D[\"@EnableAutoConfiguration<br/>자동 설정 로드\"]",
    "    D --> E[\"AutoConfiguration.imports 파일<br/>자동 설정 후보 수백 개\"]",
    "    E --> F[\"@ConditionalOn* 조건 평가\"]",
    "    F --> G[\"@ConditionalOnClass<br/>라이브러리 존재?\"]",
    "    F --> H[\"@ConditionalOnMissingBean<br/>사용자 빈 없음?\"]",
    "    F --> I[\"@ConditionalOnProperty<br/>설정 값 일치?\"]",
    "    G --> J[\"조건 충족 → 빈 등록\"]",
    "    H --> J",
    "    I --> J",
    "    J --> K[\"@ConfigurationProperties<br/>설정 값 바인딩\"]",
    "    K --> L[\"애플리케이션 준비 완료\"]",
    "    C --> L",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 기능 | 역할 | 핵심 코드 |",
    "|------|------|-----------|",
    "| `@ConfigurationProperties` | 설정 → 객체 바인딩 | `prefix = \"app.jwt\"` + `@Validated` |",
    "| `@Profile` | 환경별 설정/빈 분리 | `@Profile(\"dev\")`, `application-dev.yml` |",
    "| `@ConditionalOnProperty` | 설정 값 조건부 빈 | `havingValue = \"true\"` |",
    "| `@ConditionalOnClass` | 클래스 존재 조건부 빈 | 라이브러리 유무에 따른 분기 |",
    "| `@ConditionalOnMissingBean` | 빈 미존재 조건부 빈 | 기본값 제공 패턴 |",
    "| Actuator `/health` | 헬스 체크 | `HealthIndicator` 구현 |",
    "| Actuator `/metrics` | 메트릭 | `MeterRegistry`, `Counter` |",
    "| Auto Configuration | 자동 빈 등록 | `@AutoConfiguration` + `@ConditionalOn*` |",
    "",
    "| 상황 | 추천 기능 |",
    "|------|----------|",
    "| 설정 값을 안전하게 관리 | `@ConfigurationProperties` + `@Validated` |",
    "| dev/prod 환경 분리 | `@Profile` + `application-{profile}.yml` |",
    "| 기능 ON/OFF | `@ConditionalOnProperty` |",
    "| 라이브러리 유무 대응 | `@ConditionalOnClass` + `@ConditionalOnMissingBean` |",
    "| 운영 모니터링 | Actuator `health`, `metrics`, `loggers` |",
    "| 자동 설정 동작 확인 | `debug: true` (Conditions Report) |",
    "| 자동 설정 제외 | `@SpringBootApplication(exclude = ...)` |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
