<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-application-properties",
  title: "Spring Boot application.yml vs application.properties 완전 정리",
  date: "2026-03-11",
  summary: "Spring Boot의 핵심 설정 파일인 application.properties와 application.yml의 문법, 차이점, 프로파일 분리, 환경 변수 바인딩, 자주 쓰는 설정 예제, 우선순위까지 실전 중심으로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","application.yml","application.properties","configuration","yaml","backend"],
  content: [
    "## 설정 파일이란?",
    "",
    "Spring Boot는 `src/main/resources/` 아래에 위치한 **설정 파일**을 통해 서버 포트, DB 연결, 로깅 수준 등 애플리케이션의 동작 방식을 결정합니다. 두 가지 형식을 지원합니다.",
    "",
    "| 형식 | 파일명 | 확장자 |",
    "|------|--------|--------|",
    "| Properties | `application.properties` | `.properties` |",
    "| YAML | `application.yml` | `.yml` 또는 `.yaml` |",
    "",
    "둘 다 **동일한 역할**을 하며, 프로젝트에서 하나만 선택해서 사용합니다.",
    "",
    "---",
    "",
    "## application.properties 문법",
    "",
    "**key=value** 형태로 한 줄에 하나의 설정을 작성합니다.",
    "",
    "```properties",
    "# 서버 설정",
    "server.port=8080",
    "server.servlet.context-path=/api",
    "",
    "# 데이터베이스 설정",
    "spring.datasource.url=jdbc:mysql://localhost:3306/mydb",
    "spring.datasource.username=root",
    "spring.datasource.password=1234",
    "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver",
    "",
    "# JPA 설정",
    "spring.jpa.hibernate.ddl-auto=update",
    "spring.jpa.show-sql=true",
    "spring.jpa.properties.hibernate.format_sql=true",
    "",
    "# 로깅 설정",
    "logging.level.root=INFO",
    "logging.level.com.example=DEBUG",
    "```",
    "",
    "### properties 문법 규칙",
    "",
    "| 규칙 | 예시 |",
    "|------|------|",
    "| `key=value` 형식 | `server.port=8080` |",
    "| 주석은 `#` | `# 이것은 주석` |",
    "| 계층은 `.`(점)으로 구분 | `spring.datasource.url=...` |",
    "| 리스트는 `[인덱스]` | `app.servers[0]=host1` |",
    "| 공백은 의미 없음 | `key = value` = `key=value` |",
    "",
    "---",
    "",
    "## application.yml 문법",
    "",
    "**들여쓰기(indent) 기반 계층 구조**로 작성합니다.",
    "",
    "```yaml",
    "# 서버 설정",
    "server:",
    "  port: 8080",
    "  servlet:",
    "    context-path: /api",
    "",
    "# 데이터베이스 설정",
    "spring:",
    "  datasource:",
    "    url: jdbc:mysql://localhost:3306/mydb",
    "    username: root",
    "    password: 1234",
    "    driver-class-name: com.mysql.cj.jdbc.Driver",
    "",
    "  # JPA 설정",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: update",
    "    show-sql: true",
    "    properties:",
    "      hibernate:",
    "        format_sql: true",
    "",
    "# 로깅 설정",
    "logging:",
    "  level:",
    "    root: INFO",
    "    com.example: DEBUG",
    "```",
    "",
    "### yml 문법 규칙",
    "",
    "| 규칙 | 설명 |",
    "|------|------|",
    "| 들여쓰기로 계층 표현 | **스페이스만 사용** (탭 불가!) |",
    "| `key: value` | 콜론 뒤에 **반드시 공백** 필요 |",
    "| 주석은 `#` | `# 이것은 주석` |",
    "| 리스트는 `-` | 아래 예시 참고 |",
    "| 들여쓰기 크기 | 보통 **2칸** (통일만 하면 됨) |",
    "",
    "### yml 리스트 표현",
    "",
    "```yaml",
    "# 방법 1: - 사용 (권장)",
    "app:",
    "  allowed-origins:",
    "    - http://localhost:3000",
    "    - https://example.com",
    "    - https://api.example.com",
    "",
    "# 방법 2: 인라인 (짧을 때)",
    "app:",
    "  allowed-origins: [http://localhost:3000, https://example.com]",
    "```",
    "",
    "---",
    "",
    "## properties vs yml 동일 설정 비교",
    "",
    "같은 설정을 두 형식으로 나란히 비교합니다.",
    "",
    "### 서버 + DB 설정",
    "",
    "```properties",
    "# application.properties",
    "server.port=8080",
    "spring.datasource.url=jdbc:mysql://localhost:3306/mydb",
    "spring.datasource.username=root",
    "spring.datasource.password=1234",
    "spring.jpa.hibernate.ddl-auto=update",
    "spring.jpa.show-sql=true",
    "```",
    "",
    "```yaml",
    "# application.yml",
    "server:",
    "  port: 8080",
    "",
    "spring:",
    "  datasource:",
    "    url: jdbc:mysql://localhost:3306/mydb",
    "    username: root",
    "    password: 1234",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: update",
    "    show-sql: true",
    "```",
    "",
    "### 리스트 설정",
    "",
    "```properties",
    "# application.properties",
    "app.cors.allowed-origins[0]=http://localhost:3000",
    "app.cors.allowed-origins[1]=https://example.com",
    "app.cors.allowed-methods[0]=GET",
    "app.cors.allowed-methods[1]=POST",
    "app.cors.allowed-methods[2]=PUT",
    "```",
    "",
    "```yaml",
    "# application.yml",
    "app:",
    "  cors:",
    "    allowed-origins:",
    "      - http://localhost:3000",
    "      - https://example.com",
    "    allowed-methods:",
    "      - GET",
    "      - POST",
    "      - PUT",
    "```",
    "",
    "> 리스트가 많을수록 yml이 훨씬 읽기 편합니다.",
    "",
    "### 중첩 구조 설정",
    "",
    "```properties",
    "# application.properties - 같은 prefix가 계속 반복됨",
    "spring.datasource.hikari.maximum-pool-size=20",
    "spring.datasource.hikari.minimum-idle=5",
    "spring.datasource.hikari.idle-timeout=300000",
    "spring.datasource.hikari.connection-timeout=20000",
    "spring.datasource.hikari.max-lifetime=1200000",
    "```",
    "",
    "```yaml",
    "# application.yml - 계층이 한눈에 보임",
    "spring:",
    "  datasource:",
    "    hikari:",
    "      maximum-pool-size: 20",
    "      minimum-idle: 5",
    "      idle-timeout: 300000",
    "      connection-timeout: 20000",
    "      max-lifetime: 1200000",
    "```",
    "",
    "---",
    "",
    "## properties vs yml 차이 정리",
    "",
    "| 비교 | `application.properties` | `application.yml` |",
    "|------|------------------------|--------------------|",
    "| 문법 | `key=value` (flat) | 들여쓰기 기반 (hierarchical) |",
    "| 가독성 | 설정 많으면 prefix 반복 | **계층 구조로 깔끔** |",
    "| 리스트 | `key[0]=val` (번거로움) | **`-` 문법 (직관적)** |",
    "| 중첩 구조 | `.`으로 이어 붙임 | **들여쓰기로 표현** |",
    "| 들여쓰기 | 상관 없음 | **스페이스만 허용** (탭 불가) |",
    "| 한 파일에 멀티 프로파일 | X | **O** (`---` 구분자) |",
    "| 오류 가능성 | 낮음 | 들여쓰기 실수 시 파싱 에러 |",
    "| 실무 사용 | 레거시, 간단한 프로젝트 | **대부분의 실무 프로젝트** |",
    "",
    "> 현재 실무와 공식 문서에서는 **yml 형식을 권장**합니다. 중첩이 깊고 설정이 많을수록 yml의 가독성 장점이 뚜렷합니다.",
    "",
    "---",
    "",
    "## 프로파일(Profile) 분리",
    "",
    "환경(dev, test, prod)별로 **다른 설정을 적용**합니다.",
    "",
    "### 파일 분리 방식 (properties & yml 공통)",
    "",
    "```",
    "src/main/resources/",
    "├── application.yml              # 공통 설정",
    "├── application-dev.yml          # 개발 환경",
    "├── application-test.yml         # 테스트 환경",
    "├── application-prod.yml         # 운영 환경",
    "└── application-local.yml        # 로컬 환경",
    "```",
    "",
    "```yaml",
    "# application.yml (공통)",
    "spring:",
    "  application:",
    "    name: my-service",
    "  profiles:",
    "    active: dev        # 기본 프로파일",
    "",
    "server:",
    "  servlet:",
    "    context-path: /api",
    "```",
    "",
    "```yaml",
    "# application-dev.yml",
    "server:",
    "  port: 8080",
    "",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:devdb",
    "    username: sa",
    "    password:",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: create-drop",
    "    show-sql: true",
    "",
    "logging:",
    "  level:",
    "    root: DEBUG",
    "```",
    "",
    "```yaml",
    "# application-prod.yml",
    "server:",
    "  port: 80",
    "",
    "spring:",
    "  datasource:",
    "    url: jdbc:mysql://prod-db:3306/myapp",
    "    username: ${DB_USERNAME}",
    "    password: ${DB_PASSWORD}",
    "    hikari:",
    "      maximum-pool-size: 20",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: validate",
    "    show-sql: false",
    "",
    "logging:",
    "  level:",
    "    root: INFO",
    "```",
    "",
    "### yml 멀티 프로파일 (한 파일에)",
    "",
    "yml만 지원하는 기능입니다. `---` 구분자로 같은 파일 안에 여러 프로파일을 작성할 수 있습니다.",
    "",
    "```yaml",
    "# application.yml - 한 파일에 모두 작성",
    "spring:",
    "  profiles:",
    "    active: dev",
    "",
    "server:",
    "  port: 8080",
    "",
    "---",
    "spring:",
    "  config:",
    "    activate:",
    "      on-profile: dev",
    "  datasource:",
    "    url: jdbc:h2:mem:devdb",
    "",
    "---",
    "spring:",
    "  config:",
    "    activate:",
    "      on-profile: prod",
    "  datasource:",
    "    url: jdbc:mysql://prod-db:3306/myapp",
    "```",
    "",
    "> 설정이 적으면 한 파일에 몰아도 되지만, 실무에서는 **파일 분리**가 더 일반적입니다.",
    "",
    "### 프로파일 활성화 방법",
    "",
    "| 방법 | 명령어 |",
    "|------|--------|",
    "| yml에 기본값 | `spring.profiles.active: dev` |",
    "| 실행 인자 | `java -jar app.jar --spring.profiles.active=prod` |",
    "| 환경 변수 | `SPRING_PROFILES_ACTIVE=prod` |",
    "| IntelliJ | Run Configuration → Active profiles: `dev` |",
    "| Gradle | `./gradlew bootRun --args='--spring.profiles.active=dev'` |",
    "",
    "---",
    "",
    "## 환경 변수와 플레이스홀더",
    "",
    "설정 파일에서 **환경 변수**나 **다른 설정값**을 참조할 수 있습니다.",
    "",
    "### ${} 플레이스홀더",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: ${DB_URL:jdbc:h2:mem:default}  # 환경변수 DB_URL, 없으면 기본값 사용",
    "    username: ${DB_USERNAME:sa}",
    "    password: ${DB_PASSWORD:}",
    "",
    "app:",
    "  name: my-service",
    "  greeting: \"Welcome to ${app.name}\"    # 다른 설정값 참조",
    "```",
    "",
    "| 문법 | 의미 |",
    "|------|------|",
    "| `${ENV_VAR}` | 환경 변수 값 (없으면 에러) |",
    "| `${ENV_VAR:default}` | 환경 변수 값 (없으면 기본값) |",
    "| `${app.name}` | 같은 설정 파일의 다른 키 참조 |",
    "",
    "### 환경 변수 → 설정 키 자동 매핑",
    "",
    "Spring Boot는 **Relaxed Binding**으로 환경 변수를 자동 매핑합니다.",
    "",
    "| 환경 변수 | 매핑되는 설정 키 |",
    "|----------|----------------|",
    "| `SERVER_PORT` | `server.port` |",
    "| `SPRING_DATASOURCE_URL` | `spring.datasource.url` |",
    "| `APP_JWT_SECRET` | `app.jwt.secret` |",
    "| `SPRING_PROFILES_ACTIVE` | `spring.profiles.active` |",
    "",
    "> 대문자 + 언더스코어(`_`)가 소문자 + 점(`.`)으로 변환됩니다. Docker/K8s 배포 시 환경 변수로 설정을 덮어쓸 수 있어 매우 유용합니다.",
    "",
    "---",
    "",
    "## 설정 우선순위 (높은 것이 낮은 것을 덮어씀)",
    "",
    "Spring Boot는 여러 곳에서 설정을 읽을 수 있으며, **우선순위가 높은 것이 적용**됩니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"1. 커맨드라인 인자<br/>--server.port=9090\"] --> B[\"2. 환경 변수<br/>SERVER_PORT=9090\"]",
    "    B --> C[\"3. application-{profile}.yml\"]",
    "    C --> D[\"4. application.yml\"]",
    "    D --> E[\"5. @PropertySource\"]",
    "    E --> F[\"6. 기본값 (Spring Boot 내장)\"]",
    "    style A fill:#ff6b6b,color:#fff",
    "    style F fill:#74b9ff,color:#fff",
    "```",
    "",
    "| 우선순위 | 설정 소스 | 예시 |",
    "|---------|----------|------|",
    "| 1 (최고) | 커맨드라인 인자 | `--server.port=9090` |",
    "| 2 | 환경 변수 | `SERVER_PORT=9090` |",
    "| 3 | `config/application.yml` (외부) | 실행 디렉토리의 `config/` 폴더 |",
    "| 4 | `application-{profile}.yml` | `application-prod.yml` |",
    "| 5 | `application.yml` | 기본 설정 |",
    "| 6 | `@PropertySource` | 코드에서 지정한 추가 파일 |",
    "| 7 (최저) | Spring Boot 기본값 | `server.port=8080` |",
    "",
    "```bash",
    "# 예시: yml에 port=8080이지만, 커맨드라인이 우선",
    "java -jar app.jar --server.port=9090",
    "# → 9090으로 실행됨",
    "```",
    "",
    "---",
    "",
    "## 자주 쓰는 설정 모음",
    "",
    "### 서버 설정",
    "",
    "```yaml",
    "server:",
    "  port: 8080                        # 서버 포트",
    "  servlet:",
    "    context-path: /api              # 컨텍스트 경로 (/api/users)",
    "    encoding:",
    "      charset: UTF-8",
    "      enabled: true",
    "      force: true",
    "  error:",
    "    include-message: always         # 에러 응답에 message 포함",
    "    include-binding-errors: always",
    "  shutdown: graceful                # Graceful Shutdown",
    "```",
    "",
    "### DataSource (DB 연결)",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8",
    "    username: root",
    "    password: 1234",
    "    driver-class-name: com.mysql.cj.jdbc.Driver",
    "    hikari:",
    "      maximum-pool-size: 10         # 최대 커넥션 수",
    "      minimum-idle: 5               # 최소 유휴 커넥션",
    "      idle-timeout: 300000          # 유휴 커넥션 만료 시간 (ms)",
    "      connection-timeout: 20000     # 커넥션 획득 대기 시간 (ms)",
    "      max-lifetime: 1800000         # 커넥션 최대 수명 (ms)",
    "```",
    "",
    "### JPA / Hibernate",
    "",
    "```yaml",
    "spring:",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: update              # 테이블 자동 생성/수정",
    "    show-sql: true                  # SQL 출력",
    "    properties:",
    "      hibernate:",
    "        format_sql: true            # SQL 포맷팅",
    "        default_batch_fetch_size: 100  # N+1 방지 배치",
    "    open-in-view: false             # OSIV 비활성화 (권장)",
    "    database-platform: org.hibernate.dialect.MySQLDialect",
    "```",
    "",
    "#### ddl-auto 옵션",
    "",
    "| 값 | 동작 | 사용 환경 |",
    "|-----|------|---------|",
    "| `none` | 아무것도 안 함 | **운영** |",
    "| `validate` | 엔티티-테이블 일치 검증만 | **운영** |",
    "| `update` | 변경분만 반영 (컬럼 추가 등) | 개발 |",
    "| `create` | 시작 시 테이블 DROP + CREATE | 개발 |",
    "| `create-drop` | 시작 시 CREATE, 종료 시 DROP | 테스트 |",
    "",
    "> **운영 환경에서는 절대 `create`, `create-drop`, `update`를 사용하면 안 됩니다.** 데이터가 삭제되거나 의도치 않은 스키마 변경이 발생합니다.",
    "",
    "### 로깅",
    "",
    "```yaml",
    "logging:",
    "  level:",
    "    root: INFO                      # 전체 기본 레벨",
    "    com.example: DEBUG              # 특정 패키지 레벨",
    "    org.hibernate.SQL: DEBUG        # Hibernate SQL 로그",
    "    org.hibernate.type.descriptor.sql: TRACE  # 바인딩 파라미터",
    "  file:",
    "    name: logs/app.log              # 로그 파일 경로",
    "  pattern:",
    "    console: \"%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n\"",
    "```",
    "",
    "### 파일 업로드",
    "",
    "```yaml",
    "spring:",
    "  servlet:",
    "    multipart:",
    "      enabled: true",
    "      max-file-size: 10MB           # 단일 파일 최대 크기",
    "      max-request-size: 30MB        # 전체 요청 최대 크기",
    "      file-size-threshold: 2KB      # 디스크 기록 임계값",
    "```",
    "",
    "### Jackson (JSON)",
    "",
    "```yaml",
    "spring:",
    "  jackson:",
    "    date-format: yyyy-MM-dd HH:mm:ss",
    "    time-zone: Asia/Seoul",
    "    serialization:",
    "      write-dates-as-timestamps: false  # ISO-8601 형식",
    "      indent-output: true               # 보기 좋게 포맷팅 (개발용)",
    "    deserialization:",
    "      fail-on-unknown-properties: false  # 알 수 없는 필드 무시",
    "    default-property-inclusion: non_null  # null 필드 제외",
    "```",
    "",
    "### Redis",
    "",
    "```yaml",
    "spring:",
    "  data:",
    "    redis:",
    "      host: localhost",
    "      port: 6379",
    "      password: redis1234",
    "      timeout: 5000ms",
    "```",
    "",
    "### Mail (SMTP)",
    "",
    "```yaml",
    "spring:",
    "  mail:",
    "    host: smtp.gmail.com",
    "    port: 587",
    "    username: ${MAIL_USERNAME}",
    "    password: ${MAIL_PASSWORD}",
    "    properties:",
    "      mail:",
    "        smtp:",
    "          auth: true",
    "          starttls:",
    "            enable: true",
    "```",
    "",
    "### 커스텀 설정 (앱 전용)",
    "",
    "```yaml",
    "app:",
    "  jwt:",
    "    secret: ${JWT_SECRET:myDefaultSecretKey123}",
    "    expiration: 3600         # 초 단위",
    "    refresh-expiration: 604800",
    "  cors:",
    "    allowed-origins:",
    "      - http://localhost:3000",
    "      - https://example.com",
    "  upload:",
    "    path: /data/uploads",
    "    allowed-types:",
    "      - image/jpeg",
    "      - image/png",
    "      - application/pdf",
    "```",
    "",
    "---",
    "",
    "## @Value로 설정값 읽기",
    "",
    "```java",
    "@RestController",
    "public class ConfigController {",
    "",
    "    @Value(\"${server.port}\")",
    "    private int port;",
    "",
    "    @Value(\"${app.jwt.secret}\")",
    "    private String jwtSecret;",
    "",
    "    @Value(\"${app.name:DefaultApp}\")  // 기본값 지정",
    "    private String appName;",
    "",
    "    @Value(\"${app.cors.allowed-origins}\")",
    "    private List<String> allowedOrigins;",
    "",
    "    @GetMapping(\"/config\")",
    "    public Map<String, Object> getConfig() {",
    "        return Map.of(",
    "                \"port\", port,",
    "                \"appName\", appName,",
    "                \"origins\", allowedOrigins);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## @ConfigurationProperties로 설정값 읽기 (권장)",
    "",
    "설정이 여러 개면 `@Value` 대신 **타입 안전한 객체 바인딩**을 사용합니다.",
    "",
    "```yaml",
    "# application.yml",
    "app:",
    "  jwt:",
    "    secret: mySecretKey",
    "    expiration: 3600",
    "    refresh-expiration: 604800",
    "```",
    "",
    "```java",
    "@ConfigurationProperties(prefix = \"app.jwt\")",
    "@Getter @Setter",
    "public class JwtProperties {",
    "    private String secret;",
    "    private long expiration;",
    "    private long refreshExpiration;  // kebab-case → camelCase 자동 변환",
    "}",
    "```",
    "",
    "```java",
    "@SpringBootApplication",
    "@EnableConfigurationProperties(JwtProperties.class)",
    "public class MyApplication { }",
    "```",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class JwtService {",
    "    private final JwtProperties jwtProperties;",
    "",
    "    public String createToken(String userId) {",
    "        return Jwts.builder()",
    "                .setSubject(userId)",
    "                .setExpiration(new Date(System.currentTimeMillis()",
    "                        + jwtProperties.getExpiration() * 1000))",
    "                .signWith(Keys.hmacShaKeyFor(",
    "                        jwtProperties.getSecret().getBytes()))",
    "                .compact();",
    "    }",
    "}",
    "```",
    "",
    "### @Value vs @ConfigurationProperties",
    "",
    "| 비교 | `@Value` | `@ConfigurationProperties` |",
    "|------|---------|---------------------------|",
    "| 바인딩 | 필드 하나씩 | **객체 단위** |",
    "| 타입 안전 | 문자열 키 (오타 위험) | **컴파일 시점 확인** |",
    "| Relaxed Binding | X | **O** (`kebab-case` → `camelCase`) |",
    "| Validation | X | **O** (`@Validated`) |",
    "| 적합 | 간단한 값 1~2개 | **구조화된 설정 그룹** |",
    "",
    "---",
    "",
    "## 실전 프로젝트 설정 예시",
    "",
    "실제 프로젝트에서 자주 사용하는 **전체 설정 파일 템플릿**입니다.",
    "",
    "```yaml",
    "# application.yml (공통)",
    "spring:",
    "  application:",
    "    name: my-service",
    "  profiles:",
    "    active: ${SPRING_PROFILES_ACTIVE:dev}",
    "",
    "  # Jackson",
    "  jackson:",
    "    date-format: yyyy-MM-dd HH:mm:ss",
    "    time-zone: Asia/Seoul",
    "    serialization:",
    "      write-dates-as-timestamps: false",
    "    default-property-inclusion: non_null",
    "",
    "  # 파일 업로드",
    "  servlet:",
    "    multipart:",
    "      max-file-size: 10MB",
    "      max-request-size: 30MB",
    "",
    "# 서버",
    "server:",
    "  servlet:",
    "    encoding:",
    "      charset: UTF-8",
    "      force: true",
    "  error:",
    "    include-message: always",
    "  shutdown: graceful",
    "",
    "# 커스텀 설정",
    "app:",
    "  jwt:",
    "    secret: ${JWT_SECRET:devSecretKey123456789012345678901234}",
    "    expiration: 3600",
    "    refresh-expiration: 604800",
    "  cors:",
    "    allowed-origins:",
    "      - http://localhost:3000",
    "```",
    "",
    "```yaml",
    "# application-dev.yml",
    "server:",
    "  port: 8080",
    "",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:devdb",
    "    username: sa",
    "    password:",
    "  h2:",
    "    console:",
    "      enabled: true            # H2 콘솔 활성화",
    "      path: /h2-console",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: create-drop",
    "    show-sql: true",
    "    properties:",
    "      hibernate:",
    "        format_sql: true",
    "",
    "logging:",
    "  level:",
    "    root: INFO",
    "    com.example: DEBUG",
    "    org.hibernate.SQL: DEBUG",
    "```",
    "",
    "```yaml",
    "# application-prod.yml",
    "server:",
    "  port: 80",
    "",
    "spring:",
    "  datasource:",
    "    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:myapp}?useSSL=true&serverTimezone=Asia/Seoul",
    "    username: ${DB_USERNAME}",
    "    password: ${DB_PASSWORD}",
    "    hikari:",
    "      maximum-pool-size: 20",
    "      minimum-idle: 5",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: validate       # 운영은 validate만!",
    "    show-sql: false",
    "    open-in-view: false",
    "",
    "logging:",
    "  level:",
    "    root: WARN",
    "    com.example: INFO",
    "  file:",
    "    name: /var/log/myapp/app.log",
    "```",
    "",
    "---",
    "",
    "## yml 작성 시 흔한 실수",
    "",
    "### 1. 탭 사용 (파싱 에러)",
    "",
    "```yaml",
    "# ❌ 탭 사용 → 에러!",
    "server:",
    "\\tport: 8080",
    "",
    "# ✅ 스페이스 사용",
    "server:",
    "  port: 8080",
    "```",
    "",
    "### 2. 콜론 뒤 공백 누락",
    "",
    "```yaml",
    "# ❌ 공백 없음 → 파싱 에러",
    "server:",
    "  port:8080",
    "",
    "# ✅ 콜론 뒤에 공백 필수",
    "server:",
    "  port: 8080",
    "```",
    "",
    "### 3. 들여쓰기 불일치",
    "",
    "```yaml",
    "# ❌ spring 아래 설정이 같은 레벨이 아님",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:test",
    "   username: sa               # 3칸 들여쓰기 (datasource 밖으로 인식)",
    "",
    "# ✅ 같은 레벨은 같은 들여쓰기",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:test",
    "    username: sa               # 4칸 들여쓰기 (datasource 안)",
    "```",
    "",
    "### 4. 특수문자 값은 따옴표로 감싸기",
    "",
    "```yaml",
    "# ❌ 특수문자가 YAML 문법으로 해석될 수 있음",
    "app:",
    "  password: p@ss:word!",
    "",
    "# ✅ 따옴표로 감싸기",
    "app:",
    "  password: \"p@ss:word!\"",
    "```",
    "",
    "---",
    "",
    "## 설정 확인 방법",
    "",
    "### Actuator로 확인",
    "",
    "```yaml",
    "# application.yml",
    "management:",
    "  endpoints:",
    "    web:",
    "      exposure:",
    "        include: env,configprops",
    "```",
    "",
    "| URL | 설명 |",
    "|-----|------|",
    "| `GET /actuator/env` | 전체 환경 변수 + 설정값 |",
    "| `GET /actuator/configprops` | `@ConfigurationProperties` 바인딩 결과 |",
    "",
    "### 로그로 확인",
    "",
    "```java",
    "@Slf4j",
    "@Component",
    "public class ConfigLogger implements ApplicationRunner {",
    "    @Value(\"${server.port}\")",
    "    private int port;",
    "",
    "    @Override",
    "    public void run(ApplicationArguments args) {",
    "        log.info(\"=== 서버 포트: {} ===\", port);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 결론 |",
    "|------|------|",
    "| 파일 형식 | **yml 권장** (가독성, 멀티 프로파일) |",
    "| 프로파일 | 환경별 파일 분리 (`application-{profile}.yml`) |",
    "| 민감 정보 | `${ENV_VAR}` 환경 변수로 주입 |",
    "| 설정 읽기 | 구조화된 설정은 `@ConfigurationProperties`, 단순 값은 `@Value` |",
    "| 운영 ddl-auto | `validate` 또는 `none` |",
    "| 우선순위 | 커맨드라인 > 환경 변수 > profile yml > application.yml |",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"프로젝트 생성\"] --> B[\"application.yml<br/>(공통 설정)\"]",
    "    B --> C[\"application-dev.yml<br/>(개발: H2, DEBUG)\"]",
    "    B --> D[\"application-prod.yml<br/>(운영: MySQL, INFO)\"]",
    "    B --> E[\"application-test.yml<br/>(테스트: H2, create-drop)\"]",
    "    C --> F[\"로컬에서 실행\"]",
    "    D --> G[\"서버에 배포<br/>환경 변수로 민감 정보 주입\"]",
    "```"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
