<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-libraries",
  title: "스프링부트 다양한 라이브러리 - Validation, ModelMapper, Gson 완전 정리",
  date: "2026-03-03",
  summary: "Spring Boot에서 자주 사용하는 라이브러리 3가지를 정리합니다. Bean Validation(입력 검증), ModelMapper(객체 변환), Gson(JSON 처리)의 개념, 설정, 실전 예제를 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","validation","modelmapper","gson","java","backend"],
  content: [
    "## 개요",
    "",
    "Spring Boot 프로젝트에서 자주 사용하는 실용 라이브러리 3가지를 정리합니다.",
    "",
    "| 라이브러리 | 역할 | 핵심 키워드 |",
    "|------------|------|-------------|",
    "| **Bean Validation** | 입력 데이터 검증 | `@NotBlank`, `@Email`, `@Valid` |",
    "| **ModelMapper** | 객체 간 필드 복사/변환 | Entity ↔ DTO 변환 |",
    "| **Gson** | JSON 직렬화/역직렬화 | Google JSON 라이브러리 |",
    "",
    "---",
    "",
    "## 인텔리제이에서 프로젝트 만들기",
    "",
    "### 1단계: 새 프로젝트 생성",
    "",
    "1. IntelliJ IDEA 실행 → **File → New → Project**",
    "2. 왼쪽 목록에서 **Spring Initializr** 선택",
    "3. 아래와 같이 설정:",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | springboot_libraries_example |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **Group** | com.example |",
    "| **Artifact** | demo |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "4. **Next** 클릭",
    "",
    "### 2단계: 의존성 선택",
    "",
    "| 카테고리 | 선택할 의존성 |",
    "|----------|-------------|",
    "| **Developer Tools** | Lombok |",
    "| **Web** | Spring Web |",
    "| **Validation** | Validation |",
    "",
    "> ModelMapper와 Gson은 build.gradle에서 직접 추가합니다.",
    "",
    "5. **Create** 클릭 → 프로젝트 생성 완료",
    "",
    "### 3단계: build.gradle 설정",
    "",
    "생성된 `build.gradle`을 아래 내용으로 교체합니다.",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '1.0-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-validation'",
    "    implementation 'org.modelmapper:modelmapper:3.2.0'",
    "    implementation 'com.google.code.gson:gson:2.11.0'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "test {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "| 의존성 | 역할 |",
    "|--------|------|",
    "| `spring-boot-starter-validation` | Bean Validation (`@NotBlank`, `@Email`, `@Valid` 등) |",
    "| `modelmapper` | 객체 간 필드 자동 복사 (Entity ↔ DTO) |",
    "| `gson` | Google JSON 라이브러리 (JSON ↔ Java 객체) |",
    "",
    "> build.gradle 수정 후 IntelliJ 우측 상단의 🐘 **코끼리 아이콘(Reload)** 을 클릭하거나, **Ctrl + Shift + O**로 Gradle을 동기화하세요.",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── DemoApplication.java",
    "├── config/",
    "│   └── AppConfig.java                 ← ModelMapper + Gson Bean 등록",
    "├── dto/",
    "│   ├── SignupRequest.java             ← Validation 어노테이션 적용",
    "│   └── UserResponse.java             ← 응답 DTO",
    "├── model/",
    "│   └── User.java                      ← Entity (메모리 저장용)",
    "├── service/",
    "│   └── UserService.java              ← ModelMapper 사용",
    "├── controller/",
    "│   ├── UserController.java           ← @Valid + ModelMapper",
    "│   └── GsonController.java           ← Gson 활용",
    "└── exception/",
    "    └── GlobalExceptionHandler.java    ← Validation 에러 처리",
    "```",
    "",
    "---",
    "",
    "## 실습 코드 (복사해서 바로 실행)",
    "",
    "### DemoApplication.java",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### AppConfig.java (ModelMapper + Gson Bean 등록)",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import com.google.gson.Gson;",
    "import com.google.gson.GsonBuilder;",
    "import org.modelmapper.ModelMapper;",
    "import org.modelmapper.convention.MatchingStrategies;",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "",
    "@Configuration",
    "public class AppConfig {",
    "",
    "    @Bean",
    "    public ModelMapper modelMapper() {",
    "        ModelMapper mapper = new ModelMapper();",
    "        mapper.getConfiguration()",
    "                .setMatchingStrategy(MatchingStrategies.STRICT)",
    "                .setFieldMatchingEnabled(true)",
    "                .setFieldAccessLevel(",
    "                        org.modelmapper.config.Configuration.AccessLevel.PRIVATE",
    "                );",
    "        return mapper;",
    "    }",
    "",
    "    @Bean",
    "    public Gson gson() {",
    "        return new GsonBuilder()",
    "                .setPrettyPrinting()",
    "                .setDateFormat(\"yyyy-MM-dd HH:mm:ss\")",
    "                .serializeNulls()",
    "                .create();",
    "    }",
    "}",
    "```",
    "",
    "### User.java (Entity / 모델)",
    "",
    "```java",
    "package com.example.demo.model;",
    "",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "",
    "import java.time.LocalDateTime;",
    "",
    "@Getter",
    "@Setter",
    "public class User {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private String password;",
    "    private String phone;",
    "    private int age;",
    "    private LocalDateTime createdAt;",
    "}",
    "```",
    "",
    "### SignupRequest.java (Bean Validation 적용 DTO)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import jakarta.validation.constraints.*;",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "import lombok.ToString;",
    "",
    "@Getter",
    "@Setter",
    "@ToString",
    "public class SignupRequest {",
    "",
    "    @NotBlank(message = \"이름은 필수입니다\")",
    "    @Size(min = 2, max = 20, message = \"이름은 2~20자여야 합니다\")",
    "    private String name;",
    "",
    "    @NotBlank(message = \"이메일은 필수입니다\")",
    "    @Email(message = \"올바른 이메일 형식이 아닙니다\")",
    "    private String email;",
    "",
    "    @NotBlank(message = \"비밀번호는 필수입니다\")",
    "    @Size(min = 8, message = \"비밀번호는 8자 이상이어야 합니다\")",
    "    private String password;",
    "",
    "    @NotBlank(message = \"전화번호는 필수입니다\")",
    "    @Pattern(",
    "        regexp = \"^010-\\\\d{4}-\\\\d{4}$\",",
    "        message = \"전화번호 형식: 010-1234-5678\"",
    "    )",
    "    private String phone;",
    "",
    "    @Min(value = 14, message = \"만 14세 이상만 가입 가능합니다\")",
    "    @Max(value = 150, message = \"나이는 150 이하여야 합니다\")",
    "    private int age;",
    "}",
    "```",
    "",
    "### UserResponse.java (응답 DTO - password 제외)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "",
    "@Getter",
    "@Setter",
    "public class UserResponse {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private String phone;",
    "    private int age;",
    "    private String createdAt;",
    "}",
    "```",
    "",
    "> `UserResponse`에는 `password`가 없습니다. ModelMapper가 자동으로 **같은 이름의 필드만 복사**하므로, password는 응답에 포함되지 않습니다.",
    "",
    "### UserService.java (ModelMapper 활용)",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import com.example.demo.dto.SignupRequest;",
    "import com.example.demo.dto.UserResponse;",
    "import com.example.demo.model.User;",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.modelmapper.ModelMapper;",
    "import org.springframework.stereotype.Service;",
    "",
    "import java.time.LocalDateTime;",
    "import java.time.format.DateTimeFormatter;",
    "import java.util.ArrayList;",
    "import java.util.List;",
    "import java.util.Map;",
    "import java.util.concurrent.ConcurrentHashMap;",
    "import java.util.concurrent.atomic.AtomicLong;",
    "",
    "@Slf4j",
    "@Service",
    "@RequiredArgsConstructor",
    "public class UserService {",
    "",
    "    private final ModelMapper modelMapper;",
    "    private final Map<Long, User> users = new ConcurrentHashMap<>();",
    "    private final AtomicLong idGenerator = new AtomicLong(1);",
    "",
    "    public UserResponse signup(SignupRequest request) {",
    "        // DTO → Entity 변환 (ModelMapper)",
    "        User user = modelMapper.map(request, User.class);",
    "        user.setId(idGenerator.getAndIncrement());",
    "        user.setCreatedAt(LocalDateTime.now());",
    "",
    "        users.put(user.getId(), user);",
    "        log.info(\"회원가입: {} ({})\", user.getName(), user.getEmail());",
    "",
    "        return toResponse(user);",
    "    }",
    "",
    "    public UserResponse getUser(Long id) {",
    "        User user = users.get(id);",
    "        if (user == null) {",
    "            throw new IllegalArgumentException(\"존재하지 않는 사용자: \" + id);",
    "        }",
    "        return toResponse(user);",
    "    }",
    "",
    "    public List<UserResponse> getAllUsers() {",
    "        return users.values().stream()",
    "                .map(this::toResponse)",
    "                .toList();",
    "    }",
    "",
    "    private UserResponse toResponse(User user) {",
    "        // Entity → DTO 변환 (ModelMapper)",
    "        UserResponse response = modelMapper.map(user, UserResponse.class);",
    "        if (user.getCreatedAt() != null) {",
    "            response.setCreatedAt(",
    "                    user.getCreatedAt().format(DateTimeFormatter.ofPattern(\"yyyy-MM-dd HH:mm:ss\"))",
    "            );",
    "        }",
    "        return response;",
    "    }",
    "}",
    "```",
    "",
    "> **ModelMapper 핵심 코드:** `modelMapper.map(source, TargetClass.class)` 한 줄로 필드명이 같은 필드를 자동 복사합니다. 수동으로 `setName(getName())`, `setEmail(getEmail())` 등을 반복할 필요가 없습니다.",
    "",
    "### UserController.java (@Valid + ModelMapper)",
    "",
    "```java",
    "package com.example.demo.controller;",
    "",
    "import com.example.demo.dto.SignupRequest;",
    "import com.example.demo.dto.UserResponse;",
    "import com.example.demo.service.UserService;",
    "import jakarta.validation.Valid;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "import java.util.List;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/users\")",
    "@RequiredArgsConstructor",
    "public class UserController {",
    "",
    "    private final UserService userService;",
    "",
    "    @PostMapping",
    "    public ResponseEntity<UserResponse> signup(",
    "            @Valid @RequestBody SignupRequest request) {",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(userService.signup(request));",
    "    }",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public UserResponse get(@PathVariable Long id) {",
    "        return userService.getUser(id);",
    "    }",
    "",
    "    @GetMapping",
    "    public List<UserResponse> getAll() {",
    "        return userService.getAllUsers();",
    "    }",
    "}",
    "```",
    "",
    "> `@Valid`를 `@RequestBody` 앞에 붙이면 Spring이 자동으로 `SignupRequest`의 검증 어노테이션을 실행합니다. 실패하면 `MethodArgumentNotValidException`이 발생합니다.",
    "",
    "### GsonController.java (Gson 활용)",
    "",
    "```java",
    "package com.example.demo.controller;",
    "",
    "import com.google.gson.Gson;",
    "import com.google.gson.reflect.TypeToken;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "import java.lang.reflect.Type;",
    "import java.util.LinkedHashMap;",
    "import java.util.List;",
    "import java.util.Map;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/gson\")",
    "@RequiredArgsConstructor",
    "public class GsonController {",
    "",
    "    private final Gson gson;",
    "",
    "    // 객체 → JSON 문자열 변환 확인",
    "    @GetMapping(\"/to-json\")",
    "    public String toJson() {",
    "        Map<String, Object> data = new LinkedHashMap<>();",
    "        data.put(\"name\", \"홍길동\");",
    "        data.put(\"age\", 28);",
    "        data.put(\"scores\", List.of(90, 85, 95));",
    "        data.put(\"address\", null);",
    "        return gson.toJson(data);",
    "    }",
    "",
    "    // JSON 문자열 → 객체 변환 확인",
    "    @PostMapping(\"/from-json\")",
    "    public Map<String, Object> fromJson(@RequestBody String jsonBody) {",
    "        Type mapType = new TypeToken<Map<String, Object>>(){}.getType();",
    "        Map<String, Object> parsed = gson.fromJson(jsonBody, mapType);",
    "",
    "        Map<String, Object> result = new LinkedHashMap<>();",
    "        result.put(\"원본JSON\", jsonBody.trim());",
    "        result.put(\"파싱결과\", parsed);",
    "        result.put(\"키목록\", parsed.keySet());",
    "        return result;",
    "    }",
    "}",
    "```",
    "",
    "### GlobalExceptionHandler.java (Validation 에러 처리)",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.MethodArgumentNotValidException;",
    "import org.springframework.web.bind.annotation.ExceptionHandler;",
    "import org.springframework.web.bind.annotation.RestControllerAdvice;",
    "",
    "import java.util.LinkedHashMap;",
    "import java.util.Map;",
    "",
    "@RestControllerAdvice",
    "public class GlobalExceptionHandler {",
    "",
    "    @ExceptionHandler(MethodArgumentNotValidException.class)",
    "    public ResponseEntity<Map<String, Object>> handleValidation(",
    "            MethodArgumentNotValidException ex) {",
    "",
    "        Map<String, String> errors = new LinkedHashMap<>();",
    "        ex.getBindingResult().getFieldErrors().forEach(error ->",
    "            errors.put(error.getField(), error.getDefaultMessage())",
    "        );",
    "",
    "        Map<String, Object> body = new LinkedHashMap<>();",
    "        body.put(\"code\", \"VALIDATION_ERROR\");",
    "        body.put(\"message\", \"입력값이 올바르지 않습니다\");",
    "        body.put(\"errors\", errors);",
    "",
    "        return ResponseEntity.badRequest().body(body);",
    "    }",
    "",
    "    @ExceptionHandler(IllegalArgumentException.class)",
    "    public ResponseEntity<Map<String, Object>> handleNotFound(",
    "            IllegalArgumentException ex) {",
    "",
    "        Map<String, Object> body = new LinkedHashMap<>();",
    "        body.put(\"code\", \"NOT_FOUND\");",
    "        body.put(\"message\", ex.getMessage());",
    "",
    "        return ResponseEntity.status(404).body(body);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 실행 및 포스트맨으로 테스트",
    "",
    "### 애플리케이션 실행",
    "",
    "IntelliJ에서 `DemoApplication.java`를 열고 **▶ Run** 버튼을 클릭합니다.",
    "",
    "```",
    "Started DemoApplication in 1.5 seconds",
    "```",
    "",
    "### 테스트 1: 회원가입 — Validation 실패 (빈 값 전송)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | POST |",
    "| **URL** | `http://localhost:8080/api/users` |",
    "| **Headers** | Content-Type: application/json |",
    "| **Body** | 아래 참고 |",
    "",
    "```json",
    "{",
    "    \"name\": \"\",",
    "    \"email\": \"bad-email\",",
    "    \"password\": \"123\",",
    "    \"phone\": \"010-1234\",",
    "    \"age\": 10",
    "}",
    "```",
    "",
    "**포스트맨 응답 (400 Bad Request):**",
    "",
    "```json",
    "{",
    "    \"code\": \"VALIDATION_ERROR\",",
    "    \"message\": \"입력값이 올바르지 않습니다\",",
    "    \"errors\": {",
    "        \"name\": \"이름은 필수입니다\",",
    "        \"email\": \"올바른 이메일 형식이 아닙니다\",",
    "        \"password\": \"비밀번호는 8자 이상이어야 합니다\",",
    "        \"phone\": \"전화번호 형식: 010-1234-5678\",",
    "        \"age\": \"만 14세 이상만 가입 가능합니다\"",
    "    }",
    "}",
    "```",
    "",
    "> **Bean Validation**이 `@NotBlank`, `@Email`, `@Size`, `@Pattern`, `@Min`을 모두 검사하여 필드별 에러 메시지를 반환합니다.",
    "",
    "### 테스트 2: 회원가입 — Validation 통과 (정상 데이터)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | POST |",
    "| **URL** | `http://localhost:8080/api/users` |",
    "| **Headers** | Content-Type: application/json |",
    "| **Body** | 아래 참고 |",
    "",
    "```json",
    "{",
    "    \"name\": \"홍길동\",",
    "    \"email\": \"hong@example.com\",",
    "    \"password\": \"mypassword123\",",
    "    \"phone\": \"010-1234-5678\",",
    "    \"age\": 25",
    "}",
    "```",
    "",
    "**포스트맨 응답 (201 Created):**",
    "",
    "```json",
    "{",
    "    \"id\": 1,",
    "    \"name\": \"홍길동\",",
    "    \"email\": \"hong@example.com\",",
    "    \"phone\": \"010-1234-5678\",",
    "    \"age\": 25,",
    "    \"createdAt\": \"2026-03-03 14:30:00\"",
    "}",
    "```",
    "",
    "> 응답에 `password`가 없습니다. **ModelMapper**가 `User` → `UserResponse`로 변환할 때, `UserResponse`에 `password` 필드가 없으므로 자동으로 제외됩니다.",
    "",
    "### 테스트 3: 사용자 조회 (GET)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/users/1` |",
    "",
    "**포스트맨 응답:**",
    "",
    "```json",
    "{",
    "    \"id\": 1,",
    "    \"name\": \"홍길동\",",
    "    \"email\": \"hong@example.com\",",
    "    \"phone\": \"010-1234-5678\",",
    "    \"age\": 25,",
    "    \"createdAt\": \"2026-03-03 14:30:00\"",
    "}",
    "```",
    "",
    "### 테스트 4: 전체 사용자 조회 (GET)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/users` |",
    "",
    "### 테스트 5: Gson — 객체 → JSON 변환 (GET)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/gson/to-json` |",
    "",
    "**포스트맨 응답:**",
    "",
    "```json",
    "{",
    "  \"name\": \"홍길동\",",
    "  \"age\": 28,",
    "  \"scores\": [90, 85, 95],",
    "  \"address\": null",
    "}",
    "```",
    "",
    "> `serializeNulls()`를 설정했으므로 null 필드(`address`)도 포함됩니다. `setPrettyPrinting()`으로 보기 좋게 포맷팅됩니다.",
    "",
    "### 테스트 6: Gson — JSON → 객체 변환 (POST)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | POST |",
    "| **URL** | `http://localhost:8080/api/gson/from-json` |",
    "| **Headers** | Content-Type: application/json |",
    "| **Body** | 아래 참고 |",
    "",
    "```json",
    "{",
    "    \"product\": \"노트북\",",
    "    \"price\": 1500000,",
    "    \"inStock\": true",
    "}",
    "```",
    "",
    "**포스트맨 응답:**",
    "",
    "```json",
    "{",
    "    \"원본JSON\": \"{\\\"product\\\": \\\"노트북\\\", \\\"price\\\": 1500000, \\\"inStock\\\": true}\",",
    "    \"파싱결과\": {",
    "        \"product\": \"노트북\",",
    "        \"price\": 1500000.0,",
    "        \"inStock\": true",
    "    },",
    "    \"키목록\": [\"product\", \"price\", \"inStock\"]",
    "}",
    "```",
    "",
    "### 포스트맨 테스트 요약",
    "",
    "| 테스트 | Method | URL | 확인할 라이브러리 | 결과 |",
    "|--------|--------|-----|------------------|------|",
    "| Validation 실패 | POST | `/api/users` | **Bean Validation** | 400 + 필드별 에러 |",
    "| Validation 성공 | POST | `/api/users` | **Validation + ModelMapper** | 201 (password 제외) |",
    "| 사용자 조회 | GET | `/api/users/1` | **ModelMapper** | Entity → DTO 변환 |",
    "| 전체 조회 | GET | `/api/users` | **ModelMapper** | List 변환 |",
    "| 객체→JSON | GET | `/api/gson/to-json` | **Gson** | toJson() |",
    "| JSON→객체 | POST | `/api/gson/from-json` | **Gson** | fromJson() |",
    "",
    "---",
    "",
    "# 1. Bean Validation 상세",
    "",
    "## 검증 어노테이션 총정리",
    "",
    "### 문자열 검증",
    "",
    "| 어노테이션 | 설명 | 예시 |",
    "|------------|------|------|",
    "| `@NotNull` | null 불가 (빈 문자열은 허용) | `@NotNull String name` |",
    "| `@NotEmpty` | null, 빈 문자열(`\"\"`) 불가 | `@NotEmpty String name` |",
    "| `@NotBlank` | null, 빈 문자열, 공백만(`\" \"`) 불가 | `@NotBlank String name` |",
    "| `@Size(min, max)` | 길이 범위 | `@Size(min=2, max=50)` |",
    "| `@Email` | 이메일 형식 | `@Email String email` |",
    "| `@Pattern(regexp)` | 정규표현식 매칭 | `@Pattern(regexp=\"^010-\\\\d{4}-\\\\d{4}$\")` |",
    "",
    "### 숫자 검증",
    "",
    "| 어노테이션 | 설명 | 예시 |",
    "|------------|------|------|",
    "| `@Min(value)` | 최솟값 | `@Min(0) int age` |",
    "| `@Max(value)` | 최댓값 | `@Max(150) int age` |",
    "| `@Positive` | 양수 | `@Positive int price` |",
    "| `@PositiveOrZero` | 0 또는 양수 | `@PositiveOrZero int stock` |",
    "| `@Digits(integer, fraction)` | 정수·소수 자릿수 제한 | `@Digits(integer=10, fraction=2)` |",
    "",
    "### 날짜 / 기타 검증",
    "",
    "| 어노테이션 | 설명 |",
    "|------------|------|",
    "| `@Past` | 과거 날짜만 |",
    "| `@Future` | 미래 날짜만 |",
    "| `@PastOrPresent` | 과거 또는 현재 |",
    "| `@FutureOrPresent` | 미래 또는 현재 |",
    "| `@AssertTrue` | true여야 함 (약관 동의 등) |",
    "",
    "---",
    "",
    "## 커스텀 검증 어노테이션 만들기",
    "",
    "기본 어노테이션으로 부족한 경우 **직접 검증 규칙**을 만들 수 있습니다.",
    "",
    "### 예제: 비속어 금지 어노테이션",
    "",
    "```java",
    "package com.example.demo.validation;",
    "",
    "import jakarta.validation.Constraint;",
    "import jakarta.validation.Payload;",
    "import java.lang.annotation.*;",
    "",
    "@Target({ElementType.FIELD})",
    "@Retention(RetentionPolicy.RUNTIME)",
    "@Constraint(validatedBy = NoProfanityValidator.class)",
    "public @interface NoProfanity {",
    "    String message() default \"부적절한 단어가 포함되어 있습니다\";",
    "    Class<?>[] groups() default {};",
    "    Class<? extends Payload>[] payload() default {};",
    "}",
    "```",
    "",
    "```java",
    "package com.example.demo.validation;",
    "",
    "import jakarta.validation.ConstraintValidator;",
    "import jakarta.validation.ConstraintValidatorContext;",
    "import java.util.Set;",
    "",
    "public class NoProfanityValidator",
    "        implements ConstraintValidator<NoProfanity, String> {",
    "",
    "    private static final Set<String> BLOCKED_WORDS = Set.of(\"바보\", \"멍청이\");",
    "",
    "    @Override",
    "    public boolean isValid(String value, ConstraintValidatorContext context) {",
    "        if (value == null) return true;",
    "        return BLOCKED_WORDS.stream()",
    "                .noneMatch(word -> value.contains(word));",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "// DTO에 적용",
    "@NotBlank",
    "@NoProfanity",
    "private String nickname;",
    "```",
    "",
    "---",
    "",
    "# 2. ModelMapper 상세",
    "",
    "## 매칭 전략",
    "",
    "| 전략 | 설명 | 추천 |",
    "|------|------|------|",
    "| `STANDARD` | 기본값. 소스와 대상 필드명을 지능적으로 매칭 | 일반적인 경우 |",
    "| `STRICT` | 필드명이 정확히 일치해야 매핑 | **권장** (예상치 못한 매핑 방지) |",
    "| `LOOSE` | 가장 느슨한 매칭. 토큰 순서 무시 | 비추천 |",
    "",
    "## 필드명이 다른 경우 (커스텀 매핑)",
    "",
    "```java",
    "// Entity",
    "public class Order {",
    "    private Long id;",
    "    private String productName;",
    "    private int totalPrice;",
    "}",
    "",
    "// DTO (필드명이 다름)",
    "public class OrderResponse {",
    "    private Long orderId;       // id → orderId",
    "    private String itemName;    // productName → itemName",
    "    private int price;          // totalPrice → price",
    "}",
    "```",
    "",
    "```java",
    "mapper.createTypeMap(Order.class, OrderResponse.class)",
    "        .addMapping(Order::getId, OrderResponse::setOrderId)",
    "        .addMapping(Order::getProductName, OrderResponse::setItemName)",
    "        .addMapping(Order::getTotalPrice, OrderResponse::setPrice);",
    "```",
    "",
    "## ModelMapper vs 수동 변환 vs MapStruct",
    "",
    "| 비교 | 수동 변환 | ModelMapper | MapStruct |",
    "|------|----------|-------------|-----------|",
    "| 설정 | 없음 | Bean 등록 | 인터페이스 정의 |",
    "| 성능 | 가장 빠름 | 런타임 리플렉션 (느림) | **컴파일타임 코드 생성 (빠름)** |",
    "| 타입 안전성 | O | X (런타임 에러) | O (컴파일 에러) |",
    "| 코드량 | 많음 | **적음** | 적음 |",
    "| 추천 | 필드 적을 때 | 빠른 프로토타이핑 | **실무 권장** |",
    "",
    "> 실무에서는 **성능과 타입 안전성**이 중요하므로 MapStruct를 더 많이 사용합니다. ModelMapper는 빠른 개발이나 프로토타이핑에 적합합니다.",
    "",
    "---",
    "",
    "# 3. Gson 상세",
    "",
    "## 기본 사용법",
    "",
    "```java",
    "Gson gson = new Gson();",
    "",
    "// 객체 → JSON",
    "String json = gson.toJson(myObject);",
    "",
    "// JSON → 객체",
    "MyClass obj = gson.fromJson(json, MyClass.class);",
    "",
    "// JSON → List (TypeToken 필요)",
    "Type listType = new TypeToken<List<MyClass>>(){}.getType();",
    "List<MyClass> list = gson.fromJson(json, listType);",
    "```",
    "",
    "## 필드 이름 변경 (@SerializedName)",
    "",
    "```java",
    "import com.google.gson.annotations.SerializedName;",
    "",
    "public class GithubUser {",
    "",
    "    @SerializedName(\"login\")",
    "    private String username;",
    "",
    "    @SerializedName(\"avatar_url\")",
    "    private String avatarUrl;",
    "",
    "    @SerializedName(\"public_repos\")",
    "    private int publicRepoCount;",
    "}",
    "```",
    "",
    "```java",
    "String json = \"{\\\"login\\\":\\\"haru1813\\\",\\\"avatar_url\\\":\\\"https://...\\\",\\\"public_repos\\\":42}\";",
    "GithubUser user = gson.fromJson(json, GithubUser.class);",
    "System.out.println(user.getUsername()); // haru1813",
    "```",
    "",
    "## 특정 필드 제외",
    "",
    "```java",
    "import com.google.gson.annotations.Expose;",
    "",
    "public class User {",
    "    @Expose private Long id;",
    "    @Expose private String name;",
    "    private String password;  // @Expose 없음 → JSON에서 제외",
    "}",
    "",
    "// @Expose 없는 필드 제외 설정",
    "Gson gson = new GsonBuilder()",
    "        .excludeFieldsWithoutExposeAnnotation()",
    "        .create();",
    "```",
    "",
    "또는 `transient` 키워드로 간단하게 제외:",
    "",
    "```java",
    "public class User {",
    "    private Long id;",
    "    private String name;",
    "    private transient String password;  // JSON 변환에서 제외",
    "}",
    "```",
    "",
    "## Gson vs Jackson 비교",
    "",
    "| 비교 | Gson | Jackson |",
    "|------|------|---------|",
    "| 개발사 | Google | FasterXML |",
    "| Spring Boot 기본 | X | **O** (자동 포함) |",
    "| API 스타일 | `toJson()` / `fromJson()` | `writeValueAsString()` / `readValue()` |",
    "| 성능 | 중간 | **빠름** (스트리밍 지원) |",
    "| 어노테이션 | `@SerializedName`, `@Expose` | `@JsonProperty`, `@JsonIgnore` |",
    "| 추천 | 외부 JSON 파싱, 단순 변환 | Spring Boot 기본, REST API |",
    "",
    "> Spring Boot의 REST API에서는 Jackson이 자동으로 동작합니다. Gson은 **외부 API 응답 파싱**, **파일에서 JSON 읽기**, **Jackson이 없는 환경**에서 주로 사용합니다.",
    "",
    "---",
    "",
    "## 3가지 라이브러리 활용 흐름",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"클라이언트 요청<br/>(JSON)\"] -->|@Valid| B[\"Bean Validation<br/>입력 검증\"]",
    "    B -->|통과| C[\"Controller\"]",
    "    C --> D[\"Service\"]",
    "    D -->|ModelMapper| E[\"DTO → Entity 변환\"]",
    "    E --> F[\"저장\"]",
    "    F --> G[\"Entity 조회\"]",
    "    G -->|ModelMapper| H[\"Entity → DTO 변환\"]",
    "    H --> I[\"응답 반환 (JSON)\"]",
    "    D -->|Gson| J[\"외부 API 호출<br/>JSON 파싱\"]",
    "    J --> D",
    "    B -->|실패| K[\"400 에러 응답\"]",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 라이브러리 | 역할 | 핵심 코드 |",
    "|------------|------|-----------|",
    "| **Bean Validation** | 입력 검증 | `@NotBlank`, `@Email`, `@Valid` + `@RestControllerAdvice` |",
    "| **ModelMapper** | 객체 변환 | `modelMapper.map(source, TargetClass.class)` |",
    "| **Gson** | JSON 처리 | `gson.toJson(obj)`, `gson.fromJson(json, Class)` |",
    "",
    "| 상황 | 추천 |",
    "|------|------|",
    "| API 입력 검증 | **Bean Validation** (Spring 표준) |",
    "| Entity ↔ DTO 변환 (빠른 개발) | **ModelMapper** |",
    "| Entity ↔ DTO 변환 (실무 성능) | MapStruct |",
    "| Spring Boot REST API의 JSON 변환 | Jackson (기본 내장) |",
    "| 외부 JSON 파싱, 단순 변환 | **Gson** |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
