<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-rest-api",
  title: "Spring Boot REST API 설계와 예제",
  date: "2026-02-11",
  summary: "RESTful API 설계 원칙, Spring Web MVC 컨트롤러, Bean Validation, Global 예외 처리까지 실전 예제로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","rest","api","validation","backend"],
  content: [
    "## REST API란?",
    "",
    "**REST(Representational State Transfer)**는 웹에서 클라이언트와 서버가 데이터를 주고받는 아키텍처 스타일입니다. **리소스(Resource)**를 URL로 식별하고, **HTTP 메서드**로 행위를 표현합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트 (브라우저/앱)",
    "    participant S as Spring Boot 서버",
    "    C->>S: GET /api/users (전체 조회)",
    "    S-->>C: 200 OK + [{ id, name, email }, ...]",
    "    C->>S: POST /api/users + { name, email } (생성)",
    "    S-->>C: 201 Created + { id, name, email }",
    "    C->>S: PUT /api/users/1 + { name, email } (수정)",
    "    S-->>C: 200 OK + { id, name, email }",
    "    C->>S: DELETE /api/users/1 (삭제)",
    "    S-->>C: 204 No Content",
    "```",
    "",
    "---",
    "",
    "## RESTful API 설계 원칙",
    "",
    "### URL 설계 규칙",
    "",
    "| 규칙 | 좋은 예 | 나쁜 예 |",
    "|------|---------|---------|",
    "| 명사 사용, 복수형 | `/api/users` | `/api/getUser` |",
    "| 소문자, 하이픈(-) 구분 | `/api/order-items` | `/api/OrderItems` |",
    "| 계층 관계 표현 | `/api/users/1/posts` | `/api/getUserPosts?id=1` |",
    "| 행위는 HTTP 메서드로 | `DELETE /api/users/1` | `POST /api/deleteUser` |",
    "| 필터·정렬은 쿼리 파라미터 | `/api/users?page=0&sort=name` | `/api/users/page/0` |",
    "",
    "### HTTP 메서드와 CRUD 매핑",
    "",
    "| HTTP 메서드 | CRUD | URL 예시 | 설명 | 멱등성 |",
    "|-------------|------|----------|------|--------|",
    "| `GET` | Read | `/api/users` | 전체 조회 | O |",
    "| `GET` | Read | `/api/users/1` | 단일 조회 | O |",
    "| `POST` | Create | `/api/users` | 생성 | X |",
    "| `PUT` | Update | `/api/users/1` | 전체 수정 | O |",
    "| `PATCH` | Update | `/api/users/1` | 부분 수정 | O |",
    "| `DELETE` | Delete | `/api/users/1` | 삭제 | O |",
    "",
    "> **멱등성(Idempotency)**: 같은 요청을 여러 번 보내도 결과가 동일한 성질. POST만 멱등하지 않습니다.",
    "",
    "### HTTP 상태 코드",
    "",
    "| 상태 코드 | 의미 | 사용 시점 |",
    "|-----------|------|-----------|",
    "| `200 OK` | 성공 | 조회·수정 성공 |",
    "| `201 Created` | 생성 성공 | POST로 리소스 생성 |",
    "| `204 No Content` | 성공 (본문 없음) | DELETE 성공 |",
    "| `400 Bad Request` | 잘못된 요청 | 유효성 검증 실패 |",
    "| `404 Not Found` | 리소스 없음 | 존재하지 않는 ID 조회 |",
    "| `409 Conflict` | 충돌 | 이메일 중복 등 |",
    "| `500 Internal Server Error` | 서버 오류 | 예기치 못한 에러 |",
    "",
    "---",
    "",
    "## 인텔리제이에서 프로젝트 만들기",
    "",
    "### 1단계: 새 프로젝트 생성",
    "",
    "1. IntelliJ IDEA 실행 → **File → New → Project**",
    "2. 왼쪽 목록에서 **Spring Initializr** 선택",
    "3. 아래와 같이 설정:",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | springboot_rest_api_example |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **Group** | com.example |",
    "| **Artifact** | demo |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "4. **Next** 클릭",
    "",
    "### 2단계: 의존성 선택",
    "",
    "| 카테고리 | 선택할 의존성 |",
    "|----------|-------------|",
    "| **Developer Tools** | Lombok |",
    "| **Web** | Spring Web |",
    "| **Validation** | Validation |",
    "",
    "5. **Create** 클릭 → 프로젝트 생성 완료",
    "",
    "### 3단계: build.gradle 설정",
    "",
    "생성된 `build.gradle`을 아래 내용으로 교체합니다.",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '1.0-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-validation'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "test {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "| 의존성 | 역할 |",
    "|--------|------|",
    "| `starter-web` | Spring MVC, 내장 Tomcat, Jackson(JSON 변환) |",
    "| `starter-validation` | Bean Validation (`@NotBlank`, `@Email` 등) |",
    "",
    "> build.gradle 수정 후 IntelliJ 우측 상단의 🐘 **코끼리 아이콘(Reload)** 을 클릭하거나, **Ctrl + Shift + O**로 Gradle을 동기화하세요.",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── DemoApplication.java",
    "├── controller/",
    "│   └── UserController.java",
    "├── dto/",
    "│   ├── CreateUserRequest.java",
    "│   ├── UpdateUserRequest.java",
    "│   ├── UserResponse.java",
    "│   └── ErrorResponse.java",
    "├── entity/",
    "│   └── User.java",
    "├── repository/",
    "│   └── UserRepository.java",
    "├── service/",
    "│   └── UserService.java",
    "└── exception/",
    "    ├── UserNotFoundException.java",
    "    ├── DuplicateEmailException.java",
    "    └── GlobalExceptionHandler.java",
    "```",
    "",
    "### DemoApplication.java",
    "",
    "`src/main/java/com/example/demo/DemoApplication.java`는 프로젝트 생성 시 자동으로 만들어집니다. 수정 없이 그대로 사용합니다.",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### 실행 방법",
    "",
    "아래의 모든 Java 파일을 프로젝트 구조대로 만든 뒤 `DemoApplication.java`를 실행하면 서버가 `http://localhost:8080`에서 시작됩니다.",
    "",
    "---",
    "",
    "## Entity",
    "",
    "```java",
    "package com.example.demo.entity;",
    "",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "import java.time.LocalDateTime;",
    "",
    "@Getter @Setter",
    "public class User {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private Integer age;",
    "    private LocalDateTime createdAt;",
    "    private LocalDateTime updatedAt;",
    "}",
    "```",
    "",
    "---",
    "",
    "## DTO (Data Transfer Object)",
    "",
    "Entity를 직접 노출하지 않고, **요청용 DTO**와 **응답용 DTO**를 분리합니다.",
    "",
    "### CreateUserRequest (생성용)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import jakarta.validation.constraints.*;",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "",
    "@Getter @Setter",
    "public class CreateUserRequest {",
    "",
    "    @NotBlank(message = \"이름은 필수입니다\")",
    "    @Size(min = 2, max = 50, message = \"이름은 2~50자여야 합니다\")",
    "    private String name;",
    "",
    "    @NotBlank(message = \"이메일은 필수입니다\")",
    "    @Email(message = \"올바른 이메일 형식이 아닙니다\")",
    "    private String email;",
    "",
    "    @Min(value = 0, message = \"나이는 0 이상이어야 합니다\")",
    "    @Max(value = 150, message = \"나이는 150 이하여야 합니다\")",
    "    private Integer age;",
    "}",
    "```",
    "",
    "### UpdateUserRequest (수정용)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import jakarta.validation.constraints.*;",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "",
    "@Getter @Setter",
    "public class UpdateUserRequest {",
    "",
    "    @Size(min = 2, max = 50, message = \"이름은 2~50자여야 합니다\")",
    "    private String name;",
    "",
    "    @Email(message = \"올바른 이메일 형식이 아닙니다\")",
    "    private String email;",
    "",
    "    @Min(value = 0, message = \"나이는 0 이상이어야 합니다\")",
    "    @Max(value = 150, message = \"나이는 150 이하여야 합니다\")",
    "    private Integer age;",
    "}",
    "```",
    "",
    "> 수정 DTO는 `@NotBlank` 없이 nullable로 두어 **부분 수정(PATCH 스타일)**이 가능하게 합니다.",
    "",
    "### UserResponse (응답용)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import com.example.demo.entity.User;",
    "import lombok.AllArgsConstructor;",
    "import lombok.Getter;",
    "",
    "@Getter",
    "@AllArgsConstructor",
    "public class UserResponse {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private Integer age;",
    "    private String createdAt;",
    "",
    "    public static UserResponse from(User user) {",
    "        return new UserResponse(",
    "            user.getId(),",
    "            user.getName(),",
    "            user.getEmail(),",
    "            user.getAge(),",
    "            user.getCreatedAt().toString()",
    "        );",
    "    }",
    "}",
    "```",
    "",
    "### ErrorResponse (에러 응답용)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import lombok.AllArgsConstructor;",
    "import lombok.Getter;",
    "",
    "@Getter",
    "@AllArgsConstructor",
    "public class ErrorResponse {",
    "    private String code;",
    "    private String message;",
    "    private Object details;",
    "",
    "    public ErrorResponse(String code, String message) {",
    "        this(code, message, null);",
    "    }",
    "}",
    "```",
    "",
    "### 왜 Entity와 DTO를 분리하는가?",
    "",
    "| 이유 | 설명 |",
    "|------|------|",
    "| 보안 | 민감 필드(password 등)가 API에 노출되는 것을 방지 |",
    "| 유연성 | API 응답 구조를 Entity 변경 없이 수정 가능 |",
    "| 검증 분리 | 생성·수정 시 다른 검증 규칙 적용 가능 |",
    "| 순환 참조 방지 | JPA Entity의 양방향 관계가 JSON으로 직렬화될 때 무한 루프 방지 |",
    "",
    "---",
    "",
    "## Repository (메모리 저장소)",
    "",
    "```java",
    "package com.example.demo.repository;",
    "",
    "import com.example.demo.entity.User;",
    "import org.springframework.stereotype.Repository;",
    "",
    "import java.util.*;",
    "import java.util.concurrent.ConcurrentHashMap;",
    "import java.util.concurrent.atomic.AtomicLong;",
    "import java.util.stream.Collectors;",
    "",
    "@Repository",
    "public class UserRepository {",
    "",
    "    private final Map<Long, User> store = new ConcurrentHashMap<>();",
    "    private final AtomicLong sequence = new AtomicLong(0);",
    "",
    "    public User save(User user) {",
    "        if (user.getId() == null) {",
    "            user.setId(sequence.incrementAndGet());",
    "        }",
    "        store.put(user.getId(), user);",
    "        return user;",
    "    }",
    "",
    "    public Optional<User> findById(Long id) {",
    "        return Optional.ofNullable(store.get(id));",
    "    }",
    "",
    "    public List<User> findAll() {",
    "        return new ArrayList<>(store.values());",
    "    }",
    "",
    "    public boolean existsByEmail(String email) {",
    "        return store.values().stream()",
    "                .anyMatch(u -> u.getEmail().equals(email));",
    "    }",
    "",
    "    public boolean existsByEmailAndIdNot(String email, Long id) {",
    "        return store.values().stream()",
    "                .anyMatch(u -> u.getEmail().equals(email) && !u.getId().equals(id));",
    "    }",
    "",
    "    public void deleteById(Long id) {",
    "        store.remove(id);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Service",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import com.example.demo.dto.CreateUserRequest;",
    "import com.example.demo.dto.UpdateUserRequest;",
    "import com.example.demo.dto.UserResponse;",
    "import com.example.demo.entity.User;",
    "import com.example.demo.exception.DuplicateEmailException;",
    "import com.example.demo.exception.UserNotFoundException;",
    "import com.example.demo.repository.UserRepository;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.stereotype.Service;",
    "",
    "import java.time.LocalDateTime;",
    "import java.util.List;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "public class UserService {",
    "",
    "    private final UserRepository userRepository;",
    "",
    "    public UserResponse create(CreateUserRequest req) {",
    "        if (userRepository.existsByEmail(req.getEmail())) {",
    "            throw new DuplicateEmailException(req.getEmail());",
    "        }",
    "",
    "        User user = new User();",
    "        user.setName(req.getName());",
    "        user.setEmail(req.getEmail());",
    "        user.setAge(req.getAge());",
    "        user.setCreatedAt(LocalDateTime.now());",
    "        user.setUpdatedAt(LocalDateTime.now());",
    "",
    "        return UserResponse.from(userRepository.save(user));",
    "    }",
    "",
    "    public UserResponse findById(Long id) {",
    "        User user = userRepository.findById(id)",
    "                .orElseThrow(() -> new UserNotFoundException(id));",
    "        return UserResponse.from(user);",
    "    }",
    "",
    "    public List<UserResponse> findAll() {",
    "        return userRepository.findAll().stream()",
    "                .map(UserResponse::from)",
    "                .toList();",
    "    }",
    "",
    "    public UserResponse update(Long id, UpdateUserRequest req) {",
    "        User user = userRepository.findById(id)",
    "                .orElseThrow(() -> new UserNotFoundException(id));",
    "",
    "        if (req.getEmail() != null",
    "                && userRepository.existsByEmailAndIdNot(req.getEmail(), id)) {",
    "            throw new DuplicateEmailException(req.getEmail());",
    "        }",
    "",
    "        if (req.getName() != null) user.setName(req.getName());",
    "        if (req.getEmail() != null) user.setEmail(req.getEmail());",
    "        if (req.getAge() != null) user.setAge(req.getAge());",
    "        user.setUpdatedAt(LocalDateTime.now());",
    "",
    "        return UserResponse.from(userRepository.save(user));",
    "    }",
    "",
    "    public void delete(Long id) {",
    "        userRepository.findById(id)",
    "                .orElseThrow(() -> new UserNotFoundException(id));",
    "        userRepository.deleteById(id);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Controller (REST API 핵심)",
    "",
    "```java",
    "package com.example.demo.controller;",
    "",
    "import com.example.demo.dto.CreateUserRequest;",
    "import com.example.demo.dto.UpdateUserRequest;",
    "import com.example.demo.dto.UserResponse;",
    "import com.example.demo.service.UserService;",
    "import jakarta.validation.Valid;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "import java.net.URI;",
    "import java.util.List;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/users\")",
    "@RequiredArgsConstructor",
    "public class UserController {",
    "",
    "    private final UserService userService;",
    "",
    "    // ──────────────────────────────────────────",
    "    // GET /api/users - 전체 조회",
    "    // ──────────────────────────────────────────",
    "    @GetMapping",
    "    public ResponseEntity<List<UserResponse>> list() {",
    "        return ResponseEntity.ok(userService.findAll());",
    "    }",
    "",
    "    // ──────────────────────────────────────────",
    "    // GET /api/users/{id} - 단일 조회",
    "    // ──────────────────────────────────────────",
    "    @GetMapping(\"/{id}\")",
    "    public ResponseEntity<UserResponse> get(@PathVariable Long id) {",
    "        return ResponseEntity.ok(userService.findById(id));",
    "    }",
    "",
    "    // ──────────────────────────────────────────",
    "    // POST /api/users - 생성",
    "    // ──────────────────────────────────────────",
    "    @PostMapping",
    "    public ResponseEntity<UserResponse> create(@Valid @RequestBody CreateUserRequest req) {",
    "        UserResponse created = userService.create(req);",
    "        return ResponseEntity",
    "                .created(URI.create(\"/api/users/\" + created.getId()))",
    "                .body(created);",
    "    }",
    "",
    "    // ──────────────────────────────────────────",
    "    // PUT /api/users/{id} - 수정",
    "    // ──────────────────────────────────────────",
    "    @PutMapping(\"/{id}\")",
    "    public ResponseEntity<UserResponse> update(",
    "            @PathVariable Long id,",
    "            @Valid @RequestBody UpdateUserRequest req) {",
    "        return ResponseEntity.ok(userService.update(id, req));",
    "    }",
    "",
    "    // ──────────────────────────────────────────",
    "    // DELETE /api/users/{id} - 삭제",
    "    // ──────────────────────────────────────────",
    "    @DeleteMapping(\"/{id}\")",
    "    public ResponseEntity<Void> delete(@PathVariable Long id) {",
    "        userService.delete(id);",
    "        return ResponseEntity.noContent().build();",
    "    }",
    "}",
    "```",
    "",
    "### Controller 어노테이션 정리",
    "",
    "| 어노테이션 | 역할 |",
    "|------------|------|",
    "| `@RestController` | `@Controller` + `@ResponseBody` (JSON 자동 변환) |",
    "| `@RequestMapping(\"/api/users\")` | 공통 URL prefix 지정 |",
    "| `@GetMapping` | HTTP GET 요청 매핑 |",
    "| `@PostMapping` | HTTP POST 요청 매핑 |",
    "| `@PutMapping(\"/{id}\")` | HTTP PUT 요청 매핑 + 경로 변수 |",
    "| `@DeleteMapping(\"/{id}\")` | HTTP DELETE 요청 매핑 |",
    "| `@PathVariable` | URL 경로에서 변수 추출 (`/users/1` → `id=1`) |",
    "| `@RequestBody` | 요청 본문(JSON) → Java 객체 변환 |",
    "| `@Valid` | Bean Validation 실행 |",
    "",
    "### ResponseEntity 사용 패턴",
    "",
    "| 패턴 | 코드 | 상태 코드 |",
    "|------|------|-----------|",
    "| 조회 성공 | `ResponseEntity.ok(body)` | 200 |",
    "| 생성 성공 | `ResponseEntity.created(uri).body(body)` | 201 + Location 헤더 |",
    "| 삭제 성공 | `ResponseEntity.noContent().build()` | 204 |",
    "| 에러 | `ResponseEntity.status(404).body(error)` | 404 등 |",
    "",
    "---",
    "",
    "## 커스텀 예외 클래스",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "public class UserNotFoundException extends RuntimeException {",
    "    public UserNotFoundException(Long id) {",
    "        super(\"사용자를 찾을 수 없습니다. ID: \" + id);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Global 예외 처리 (@RestControllerAdvice)",
    "",
    "모든 컨트롤러에서 발생하는 예외를 **한 곳에서** 처리하여 일관된 에러 응답을 만듭니다.",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "import com.example.demo.dto.ErrorResponse;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.MethodArgumentNotValidException;",
    "import org.springframework.web.bind.annotation.ExceptionHandler;",
    "import org.springframework.web.bind.annotation.RestControllerAdvice;",
    "",
    "import java.util.HashMap;",
    "import java.util.Map;",
    "",
    "@RestControllerAdvice",
    "public class GlobalExceptionHandler {",
    "",
    "    @ExceptionHandler(MethodArgumentNotValidException.class)",
    "    public ResponseEntity<ErrorResponse> handleValidation(",
    "            MethodArgumentNotValidException ex) {",
    "        Map<String, String> fieldErrors = new HashMap<>();",
    "        ex.getBindingResult().getFieldErrors().forEach(error ->",
    "            fieldErrors.put(error.getField(), error.getDefaultMessage())",
    "        );",
    "        return ResponseEntity.badRequest()",
    "                .body(new ErrorResponse(\"VALIDATION_ERROR\", \"입력값이 올바르지 않습니다\", fieldErrors));",
    "    }",
    "",
    "    @ExceptionHandler(UserNotFoundException.class)",
    "    public ResponseEntity<ErrorResponse> handleUserNotFound(",
    "            UserNotFoundException ex) {",
    "        return ResponseEntity.status(HttpStatus.NOT_FOUND)",
    "                .body(new ErrorResponse(\"USER_NOT_FOUND\", ex.getMessage()));",
    "    }",
    "}",
    "```",
    "",
    "> 📌 예외 처리의 전체 전략, ErrorCode Enum 패턴, 예외 계층 설계 등 상세한 내용은 '스프링부트 예외 처리 완전 정리' 글을 참고하세요.",
    "",
    "---",
    "",
    "## Bean Validation 어노테이션 정리",
    "",
    "| 어노테이션 | 대상 | 설명 |",
    "|------------|------|------|",
    "| `@NotBlank` | String | null, 빈 문자열, 공백만 있는 문자열 불가 |",
    "| `@NotNull` | 모든 타입 | null 불가 |",
    "| `@Size(min, max)` | String, Collection | 길이/크기 범위 |",
    "| `@Email` | String | 이메일 형식 |",
    "| `@Min(value)` | 숫자 | 최솟값 |",
    "",
    "> 📌 Bean Validation의 전체 어노테이션 목록과 커스텀 검증 어노테이션 작성법은 '스프링부트 다양한 라이브러리' 글을 참고하세요.",
    "",
    "---",
    "",
    "## API 요청·응답 예시 (전체 CRUD)",
    "",
    "### 1. 사용자 생성 (POST)",
    "",
    "**요청:**",
    "```",
    "POST /api/users",
    "Content-Type: application/json",
    "",
    "{",
    "  \"name\": \"홍길동\",",
    "  \"email\": \"hong@mail.com\",",
    "  \"age\": 28",
    "}",
    "```",
    "",
    "**응답 (201 Created):**",
    "```json",
    "{",
    "  \"id\": 1,",
    "  \"name\": \"홍길동\",",
    "  \"email\": \"hong@mail.com\",",
    "  \"age\": 28,",
    "  \"createdAt\": \"2026-03-01T10:00:00\"",
    "}",
    "```",
    "",
    "### 2. 전체 조회 (GET)",
    "",
    "**요청:**",
    "```",
    "GET /api/users",
    "```",
    "",
    "**응답 (200 OK):**",
    "```json",
    "[",
    "  {",
    "    \"id\": 1,",
    "    \"name\": \"홍길동\",",
    "    \"email\": \"hong@mail.com\",",
    "    \"age\": 28,",
    "    \"createdAt\": \"2026-03-01T10:00:00\"",
    "  },",
    "  {",
    "    \"id\": 2,",
    "    \"name\": \"김철수\",",
    "    \"email\": \"kim@mail.com\",",
    "    \"age\": 24,",
    "    \"createdAt\": \"2026-03-01T10:05:00\"",
    "  }",
    "]",
    "```",
    "",
    "### 3. 단일 조회 (GET)",
    "",
    "**요청:**",
    "```",
    "GET /api/users/1",
    "```",
    "",
    "**응답 (200 OK):**",
    "```json",
    "{",
    "  \"id\": 1,",
    "  \"name\": \"홍길동\",",
    "  \"email\": \"hong@mail.com\",",
    "  \"age\": 28,",
    "  \"createdAt\": \"2026-03-01T10:00:00\"",
    "}",
    "```",
    "",
    "### 4. 수정 (PUT)",
    "",
    "**요청:**",
    "```",
    "PUT /api/users/1",
    "Content-Type: application/json",
    "",
    "{",
    "  \"name\": \"홍길동(수정)\",",
    "  \"age\": 29",
    "}",
    "```",
    "",
    "**응답 (200 OK):**",
    "```json",
    "{",
    "  \"id\": 1,",
    "  \"name\": \"홍길동(수정)\",",
    "  \"email\": \"hong@mail.com\",",
    "  \"age\": 29,",
    "  \"createdAt\": \"2026-03-01T10:00:00\"",
    "}",
    "```",
    "",
    "### 5. 삭제 (DELETE)",
    "",
    "**요청:**",
    "```",
    "DELETE /api/users/1",
    "```",
    "",
    "**응답 (204 No Content):**",
    "```",
    "(본문 없음)",
    "```",
    "",
    "---",
    "",
    "## Postman으로 REST API 테스트하기",
    "",
    "**Postman**은 API를 쉽게 테스트할 수 있는 GUI 도구입니다. [https://www.postman.com](https://www.postman.com)에서 무료로 다운로드할 수 있습니다.",
    "",
    "### Postman 기본 화면 구성",
    "",
    "| 영역 | 설명 |",
    "|------|------|",
    "| HTTP 메서드 선택 | GET, POST, PUT, DELETE 등 선택 |",
    "| URL 입력 | `http://localhost:8080/api/users` 입력 |",
    "| Headers 탭 | 요청 헤더 설정 |",
    "| Body 탭 | 요청 본문(JSON) 입력 |",
    "| Send 버튼 | 요청 전송 |",
    "| 하단 응답 영역 | 상태 코드, 응답 본문, 응답 시간 확인 |",
    "",
    "### 테스트 1: 사용자 생성 (POST)",
    "",
    "| 항목 | 설정 |",
    "|------|------|",
    "| Method | `POST` |",
    "| URL | `http://localhost:8080/api/users` |",
    "| Headers | `Content-Type: application/json` |",
    "| Body | `raw` → `JSON` 선택 |",
    "",
    "**Body에 입력:**",
    "",
    "```json",
    "{",
    "  \"name\": \"홍길동\",",
    "  \"email\": \"hong@mail.com\",",
    "  \"age\": 28",
    "}",
    "```",
    "",
    "**Send 클릭 → 결과 확인:**",
    "- Status: `201 Created`",
    "- Body: `{ \"id\": 1, \"name\": \"홍길동\", ... }`",
    "- Headers: `Location: /api/users/1`",
    "",
    "### 테스트 2: 전체 조회 (GET)",
    "",
    "| 항목 | 설정 |",
    "|------|------|",
    "| Method | `GET` |",
    "| URL | `http://localhost:8080/api/users` |",
    "| Body | 없음 |",
    "",
    "**결과:** Status `200 OK` + 사용자 배열",
    "",
    "### 테스트 3: 단일 조회 (GET)",
    "",
    "| 항목 | 설정 |",
    "|------|------|",
    "| Method | `GET` |",
    "| URL | `http://localhost:8080/api/users/1` |",
    "",
    "**결과:** Status `200 OK` + 단일 사용자 객체",
    "",
    "### 테스트 4: 수정 (PUT)",
    "",
    "| 항목 | 설정 |",
    "|------|------|",
    "| Method | `PUT` |",
    "| URL | `http://localhost:8080/api/users/1` |",
    "| Headers | `Content-Type: application/json` |",
    "| Body | `raw` → `JSON` |",
    "",
    "```json",
    "{",
    "  \"name\": \"홍길동(수정)\",",
    "  \"age\": 29",
    "}",
    "```",
    "",
    "**결과:** Status `200 OK` + 수정된 사용자",
    "",
    "### 테스트 5: 삭제 (DELETE)",
    "",
    "| 항목 | 설정 |",
    "|------|------|",
    "| Method | `DELETE` |",
    "| URL | `http://localhost:8080/api/users/1` |",
    "",
    "**결과:** Status `204 No Content` (본문 없음)",
    "",
    "### 테스트 6: 유효성 검증 실패 테스트",
    "",
    "| 항목 | 설정 |",
    "|------|------|",
    "| Method | `POST` |",
    "| URL | `http://localhost:8080/api/users` |",
    "| Body | `raw` → `JSON` |",
    "",
    "```json",
    "{",
    "  \"name\": \"\",",
    "  \"email\": \"잘못된이메일\",",
    "  \"age\": -5",
    "}",
    "```",
    "",
    "**결과:** Status `400 Bad Request`",
    "",
    "```json",
    "{",
    "  \"code\": \"VALIDATION_ERROR\",",
    "  \"message\": \"입력값이 올바르지 않습니다\",",
    "  \"details\": {",
    "    \"name\": \"이름은 필수입니다\",",
    "    \"email\": \"올바른 이메일 형식이 아닙니다\",",
    "    \"age\": \"나이는 0 이상이어야 합니다\"",
    "  }",
    "}",
    "```",
    "",
    "### 테스트 7: 존재하지 않는 사용자 조회",
    "",
    "| 항목 | 설정 |",
    "|------|------|",
    "| Method | `GET` |",
    "| URL | `http://localhost:8080/api/users/999` |",
    "",
    "**결과:** Status `404 Not Found`",
    "",
    "```json",
    "{",
    "  \"code\": \"USER_NOT_FOUND\",",
    "  \"message\": \"사용자를 찾을 수 없습니다. ID: 999\"",
    "}",
    "```",
    "",
    "### Postman 활용 팁",
    "",
    "| 기능 | 설명 |",
    "|------|------|",
    "| **Collection** | 관련 API 요청을 폴더로 그룹화하여 저장 |",
    "| **Environment** | 환경별 변수 (dev: `localhost:8080`, prod: `api.example.com`) |",
    "| **Variables** | `{{baseUrl}}/api/users`처럼 변수로 URL 관리 |",
    "| **Tests 탭** | 응답을 자동 검증하는 스크립트 작성 |",
    "| **Export** | Collection을 JSON으로 내보내 팀원과 공유 |",
    "",
    "#### Environment Variable 설정 예시",
    "",
    "| Variable | Value |",
    "|----------|-------|",
    "| `baseUrl` | `http://localhost:8080` |",
    "",
    "**사용:** URL에 `{{baseUrl}}/api/users`로 입력하면 환경에 따라 자동 치환됩니다.",
    "",
    "#### Tests 탭 자동 검증 스크립트",
    "",
    "```javascript",
    "// 상태 코드 확인",
    "pm.test(\"Status is 200\", function () {",
    "    pm.response.to.have.status(200);",
    "});",
    "",
    "// 응답 구조 확인",
    "pm.test(\"Response has id\", function () {",
    "    var jsonData = pm.response.json();",
    "    pm.expect(jsonData).to.have.property(\"id\");",
    "});",
    "",
    "// 응답 시간 확인",
    "pm.test(\"Response time < 500ms\", function () {",
    "    pm.expect(pm.response.responseTime).to.be.below(500);",
    "});",
    "```",
    "",
    "---",
    "",
    "## REST API 설계 체크리스트",
    "",
    "| 항목 | 체크 |",
    "|------|------|",
    "| URL에 명사·복수형 사용 | `/api/users` (O), `/api/getUser` (X) |",
    "| HTTP 메서드로 행위 표현 | `DELETE /api/users/1` (O), `POST /api/deleteUser` (X) |",
    "| 적절한 상태 코드 반환 | 생성 → 201, 삭제 → 204, 에러 → 400/404/500 |",
    "| 요청 DTO에 Validation 적용 | `@Valid @RequestBody` |",
    "| 일관된 에러 응답 포맷 | `ErrorResponse(code, message, details)` |",
    "| Entity를 직접 반환하지 않음 | DTO로 변환 후 반환 |",
    "| 예외를 한 곳에서 처리 | `@RestControllerAdvice` |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| 핵심 구조 | Controller → Service → Repository |",
    "| 요청 처리 | `@RequestBody` + `@Valid` + DTO |",
    "| 응답 처리 | `ResponseEntity` + DTO 변환 |",
    "| 예외 처리 | 커스텀 예외 + `@RestControllerAdvice` |",
    "| 테스트 도구 | Postman (Collection, Environment, Tests) |",
    "",
    "**핵심 패턴:**",
    "",
    "| 패턴 | 코드 |",
    "|------|------|",
    "| 조회 | `@GetMapping` + `ResponseEntity.ok()` |",
    "| 생성 | `@PostMapping` + `@Valid @RequestBody` + `ResponseEntity.created()` |",
    "| 수정 | `@PutMapping` + `@PathVariable` + `@Valid @RequestBody` |",
    "| 삭제 | `@DeleteMapping` + `ResponseEntity.noContent()` |",
    "| 에러 | `@ExceptionHandler` + `ErrorResponse` |",
    "",
    "REST API는 **URL로 리소스를 식별**하고, **HTTP 메서드로 행위를 표현**하고, **상태 코드로 결과를 알려주는** 것이 핵심입니다. 이 원칙을 지키면 누가 봐도 이해하기 쉬운 API를 설계할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
