<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-filter",
  title: "Spring Boot Filter 완전 정리 - 개념부터 실전 예제까지",
  date: "2026-03-04",
  summary: "Servlet Filter의 개념, Interceptor와의 차이, Filter 등록 방법 3가지, 인코딩·CORS·로깅·보안 실전 예제, Filter Chain 실행 순서, OncePerRequestFilter까지 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","filter","servlet","cors","java","backend"],
  content: [
    "## Filter란?",
    "",
    "**Filter(필터)**는 HTTP 요청이 **DispatcherServlet에 도달하기 전**과 **응답이 클라이언트로 나가기 전**에 공통 처리를 수행하는 **Servlet API** 기능입니다.",
    "",
    "Interceptor보다 **더 바깥쪽**에서 동작하며, Spring에 종속되지 않는 Java EE(Jakarta EE) 표준 기술입니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[클라이언트] --> B[\"Filter 1\"]",
    "    B --> C[\"Filter 2\"]",
    "    C --> D[\"Filter 3\"]",
    "    D --> E[\"DispatcherServlet\"]",
    "    E --> F[\"Interceptor\"]",
    "    F --> G[\"Controller\"]",
    "    G --> F",
    "    F --> E",
    "    E --> D",
    "    D --> C",
    "    C --> B",
    "    B --> A",
    "    style B fill:#e67e22,color:#fff",
    "    style C fill:#e67e22,color:#fff",
    "    style D fill:#e67e22,color:#fff",
    "    style F fill:#3498db,color:#fff",
    "```",
    "",
    "> Filter는 요청이 들어올 때와 응답이 나갈 때 **양방향으로** 동작합니다. 여러 Filter가 체인처럼 연결됩니다.",
    "",
    "---",
    "",
    "## Filter vs Interceptor 핵심 차이",
    "",
    "| 비교 | Filter | Interceptor |",
    "|------|--------|-------------|",
    "| 표준 | Servlet API (Jakarta EE) | Spring MVC |",
    "| 동작 위치 | DispatcherServlet **밖** | DispatcherServlet **안** |",
    "| 적용 대상 | **모든 요청** (정적 리소스 포함) | Controller로 향하는 요청만 |",
    "| 인터페이스 | `jakarta.servlet.Filter` | `HandlerInterceptor` |",
    "| 요청/응답 조작 | `ServletRequest/Response` 교체 가능 | 읽기만 가능 |",
    "| Spring Bean 접근 | Spring Boot에서 가능 | 자유롭게 가능 |",
    "| 주요 용도 | 인코딩, CORS, 보안, 요청 래핑 | 로그인 체크, 로깅, 권한 |",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant F as Filter",
    "    participant DS as DispatcherServlet",
    "    participant I as Interceptor",
    "    participant CT as Controller",
    "    rect rgb(230, 126, 34)",
    "        Note over F: Filter 영역 (Servlet 레벨)",
    "        C->>F: HTTP 요청",
    "        F->>DS: doFilter() → chain.doFilter()",
    "    end",
    "    rect rgb(52, 152, 219)",
    "        Note over I: Interceptor 영역 (Spring MVC 레벨)",
    "        DS->>I: preHandle()",
    "        I->>CT: Controller 실행",
    "        CT-->>I: postHandle()",
    "    end",
    "    I-->>DS: 응답",
    "    DS-->>F: 응답",
    "    F-->>C: 최종 응답",
    "```",
    "",
    "### 언제 Filter를 쓸까?",
    "",
    "| 상황 | 추천 이유 |",
    "|------|-----------|",
    "| 문자 인코딩 설정 | 모든 요청에 공통 적용, Spring 이전에 처리 필요 |",
    "| CORS 헤더 설정 | 모든 응답에 헤더 추가 |",
    "| 요청/응답 본문 로깅 | `HttpServletRequest`를 래핑해야 함 |",
    "| XSS·SQL Injection 방지 | 파라미터를 필터링/치환 |",
    "| 압축/암호화 | 응답 스트림을 래핑 |",
    "| 인증 토큰 검증 (Spring Security) | Security Filter Chain |",
    "",
    "---",
    "",
    "## Filter 인터페이스",
    "",
    "```java",
    "public interface Filter {",
    "",
    "    // 필터 초기화 (서버 시작 시 1회)",
    "    default void init(FilterConfig filterConfig) throws ServletException {}",
    "",
    "    // 요청/응답 처리 (매 요청마다)",
    "    void doFilter(ServletRequest request,",
    "                  ServletResponse response,",
    "                  FilterChain chain) throws IOException, ServletException;",
    "",
    "    // 필터 소멸 (서버 종료 시 1회)",
    "    default void destroy() {}",
    "}",
    "```",
    "",
    "| 메서드 | 호출 시점 | 역할 |",
    "|--------|-----------|------|",
    "| `init()` | 서버 시작 시 1회 | 초기화 작업 |",
    "| `doFilter()` | 매 요청마다 | 핵심 로직 + `chain.doFilter()`로 다음 필터 호출 |",
    "| `destroy()` | 서버 종료 시 1회 | 리소스 정리 |",
    "",
    "### doFilter()의 핵심 구조",
    "",
    "```java",
    "@Override",
    "public void doFilter(ServletRequest request,",
    "                     ServletResponse response,",
    "                     FilterChain chain) throws IOException, ServletException {",
    "",
    "    // ① 요청 전 처리 (Controller 실행 전)",
    "    // ... 전처리 로직 ...",
    "",
    "    chain.doFilter(request, response);  // ② 다음 필터 또는 Servlet으로 전달",
    "",
    "    // ③ 응답 후 처리 (Controller 실행 후)",
    "    // ... 후처리 로직 ...",
    "}",
    "```",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"① 전처리 (요청 로깅, 인코딩 등)\"] --> B[\"② chain.doFilter()\"]",
    "    B --> C[\"다음 Filter → ... → Controller → 응답\"]",
    "    C --> D[\"③ 후처리 (응답 로깅, 헤더 추가 등)\"]",
    "```",
    "",
    "> **`chain.doFilter()`를 호출하지 않으면** 요청이 다음 단계로 전달되지 않아 Controller가 실행되지 않습니다. Interceptor의 `return false`와 비슷한 효과입니다.",
    "",
    "---",
    "",
    "## 인텔리제이에서 프로젝트 만들기",
    "",
    "### 1단계: 새 프로젝트 생성",
    "",
    "1. IntelliJ IDEA 실행 → **File → New → Project**",
    "2. 왼쪽 목록에서 **Spring Initializr** 선택",
    "3. 아래와 같이 설정:",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | springboot_filter_example |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **Group** | com.example |",
    "| **Artifact** | demo |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "4. **Next** 클릭",
    "",
    "### 2단계: 의존성 선택",
    "",
    "| 카테고리 | 선택할 의존성 |",
    "|----------|-------------|",
    "| **Developer Tools** | Lombok |",
    "| **Web** | Spring Web |",
    "",
    "5. **Create** 클릭 → 프로젝트 생성 완료",
    "",
    "### 3단계: build.gradle 설정",
    "",
    "생성된 `build.gradle`을 아래 내용으로 교체합니다.",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '1.0-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "test {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "> Filter는 `spring-boot-starter-web`에 이미 포함되어 있어 **별도 의존성이 필요 없습니다**.",
    "",
    "> build.gradle 수정 후 IntelliJ 우측 상단의 🐘 **코끼리 아이콘(Reload)** 을 클릭하거나, **Ctrl + Shift + O**로 Gradle을 동기화하세요.",
    "",
    "### 프로젝트 구조",
    "",
    "아래 구조대로 패키지와 파일을 만들면 됩니다.",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── DemoApplication.java",
    "├── config/",
    "│   └── FilterConfig.java                ← Filter 등록 (순서·URL 설정)",
    "├── filter/",
    "│   ├── RequestLoggingFilter.java        ← 요청/응답 로깅 + 실행 시간",
    "│   ├── CorsFilter.java                  ← CORS 헤더 처리",
    "│   └── AuthenticationFilter.java        ← 토큰 인증",
    "├── controller/",
    "│   └── ItemController.java",
    "├── service/",
    "│   └── ItemService.java",
    "└── dto/",
    "    └── ItemRequest.java",
    "```",
    "",
    "---",
    "",
    "## 실습 코드 (복사해서 바로 실행)",
    "",
    "아래 코드를 위 프로젝트 구조에 맞게 파일을 만들고 복사-붙여넣기 하세요.",
    "",
    "### DemoApplication.java (메인 클래스)",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### ItemRequest.java (DTO)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "import lombok.ToString;",
    "",
    "@Getter",
    "@Setter",
    "@ToString",
    "public class ItemRequest {",
    "    private String name;",
    "    private int price;",
    "}",
    "```",
    "",
    "### ItemService.java",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.stereotype.Service;",
    "",
    "import java.util.ArrayList;",
    "import java.util.LinkedHashMap;",
    "import java.util.List;",
    "import java.util.Map;",
    "import java.util.concurrent.ConcurrentHashMap;",
    "import java.util.concurrent.atomic.AtomicLong;",
    "",
    "@Slf4j",
    "@Service",
    "public class ItemService {",
    "",
    "    private final Map<Long, Map<String, Object>> items = new ConcurrentHashMap<>();",
    "    private final AtomicLong idGenerator = new AtomicLong(1);",
    "",
    "    public Map<String, Object> createItem(String name, int price) {",
    "        Long id = idGenerator.getAndIncrement();",
    "        Map<String, Object> item = new LinkedHashMap<>();",
    "        item.put(\"id\", id);",
    "        item.put(\"name\", name);",
    "        item.put(\"price\", price);",
    "        items.put(id, item);",
    "        log.info(\"상품 생성: {} ({}원)\", name, price);",
    "        return item;",
    "    }",
    "",
    "    public Map<String, Object> getItem(Long id) {",
    "        Map<String, Object> item = items.get(id);",
    "        if (item == null) {",
    "            throw new IllegalArgumentException(\"존재하지 않는 상품: \" + id);",
    "        }",
    "        return item;",
    "    }",
    "",
    "    public List<Map<String, Object>> getAllItems() {",
    "        return new ArrayList<>(items.values());",
    "    }",
    "",
    "    public void deleteItem(Long id) {",
    "        if (items.remove(id) == null) {",
    "            throw new IllegalArgumentException(\"존재하지 않는 상품: \" + id);",
    "        }",
    "        log.info(\"상품 삭제: {}\", id);",
    "    }",
    "}",
    "```",
    "",
    "### ItemController.java",
    "",
    "```java",
    "package com.example.demo.controller;",
    "",
    "import com.example.demo.dto.ItemRequest;",
    "import com.example.demo.service.ItemService;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "import java.util.List;",
    "import java.util.Map;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/items\")",
    "@RequiredArgsConstructor",
    "public class ItemController {",
    "",
    "    private final ItemService itemService;",
    "",
    "    @PostMapping",
    "    public ResponseEntity<Map<String, Object>> create(@RequestBody ItemRequest request) {",
    "        Map<String, Object> item = itemService.createItem(request.getName(), request.getPrice());",
    "        return ResponseEntity.status(HttpStatus.CREATED).body(item);",
    "    }",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public Map<String, Object> get(@PathVariable Long id) {",
    "        return itemService.getItem(id);",
    "    }",
    "",
    "    @GetMapping",
    "    public List<Map<String, Object>> getAll() {",
    "        return itemService.getAllItems();",
    "    }",
    "",
    "    @DeleteMapping(\"/{id}\")",
    "    public ResponseEntity<Void> delete(@PathVariable Long id) {",
    "        itemService.deleteItem(id);",
    "        return ResponseEntity.noContent().build();",
    "    }",
    "}",
    "```",
    "",
    "### RequestLoggingFilter.java (로깅 + 실행 시간)",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "",
    "import java.io.IOException;",
    "",
    "@Slf4j",
    "public class RequestLoggingFilter implements Filter {",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "",
    "        HttpServletRequest httpReq = (HttpServletRequest) request;",
    "        HttpServletResponse httpRes = (HttpServletResponse) response;",
    "",
    "        String method = httpReq.getMethod();",
    "        String uri = httpReq.getRequestURI();",
    "        String clientIp = httpReq.getRemoteAddr();",
    "        long start = System.currentTimeMillis();",
    "",
    "        log.info(\"[Filter 요청] {} {} | IP: {}\", method, uri, clientIp);",
    "",
    "        chain.doFilter(request, response);  // 다음 필터 또는 Controller로 전달",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        int status = httpRes.getStatus();",
    "        log.info(\"[Filter 응답] {} {} → {} ({}ms)\", method, uri, status, elapsed);",
    "    }",
    "}",
    "```",
    "",
    "> `chain.doFilter()` **앞**은 요청 전처리, **뒤**는 응답 후처리입니다. 실행 시간은 이 두 지점의 차이로 계산합니다.",
    "",
    "### CorsFilter.java (CORS 헤더)",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "",
    "import java.io.IOException;",
    "",
    "@Slf4j",
    "public class CorsFilter implements Filter {",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "",
    "        HttpServletRequest httpReq = (HttpServletRequest) request;",
    "        HttpServletResponse httpRes = (HttpServletResponse) response;",
    "",
    "        httpRes.setHeader(\"Access-Control-Allow-Origin\", \"*\");",
    "        httpRes.setHeader(\"Access-Control-Allow-Methods\", \"GET, POST, PUT, DELETE, OPTIONS\");",
    "        httpRes.setHeader(\"Access-Control-Allow-Headers\", \"Authorization, Content-Type\");",
    "        httpRes.setHeader(\"Access-Control-Max-Age\", \"3600\");",
    "",
    "        // OPTIONS preflight 요청은 바로 응답",
    "        if (\"OPTIONS\".equalsIgnoreCase(httpReq.getMethod())) {",
    "            log.info(\"[CORS] OPTIONS preflight 요청 처리\");",
    "            httpRes.setStatus(HttpServletResponse.SC_OK);",
    "            return;",
    "        }",
    "",
    "        chain.doFilter(request, response);",
    "    }",
    "}",
    "```",
    "",
    "| CORS 헤더 | 역할 |",
    "|-----------|------|",
    "| `Access-Control-Allow-Origin` | 허용할 출처 (`*` = 모든 출처) |",
    "| `Access-Control-Allow-Methods` | 허용할 HTTP 메서드 |",
    "| `Access-Control-Allow-Headers` | 허용할 요청 헤더 |",
    "| `Access-Control-Max-Age` | Preflight 결과 캐시 시간(초) |",
    "",
    "### AuthenticationFilter.java (토큰 인증)",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "",
    "import java.io.IOException;",
    "",
    "@Slf4j",
    "public class AuthenticationFilter implements Filter {",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "",
    "        HttpServletRequest httpReq = (HttpServletRequest) request;",
    "        HttpServletResponse httpRes = (HttpServletResponse) response;",
    "",
    "        // GET 요청은 인증 없이 통과 (조회는 누구나 가능)",
    "        if (\"GET\".equalsIgnoreCase(httpReq.getMethod())) {",
    "            chain.doFilter(request, response);",
    "            return;",
    "        }",
    "",
    "        // POST, PUT, DELETE 등은 토큰 필요",
    "        String authHeader = httpReq.getHeader(\"Authorization\");",
    "",
    "        if (authHeader == null || !authHeader.startsWith(\"Bearer \")) {",
    "            log.warn(\"[인증 실패] 토큰 없음: {} {}\", httpReq.getMethod(), httpReq.getRequestURI());",
    "            httpRes.setStatus(HttpServletResponse.SC_UNAUTHORIZED);",
    "            httpRes.setContentType(\"application/json;charset=UTF-8\");",
    "            httpRes.getWriter().write(",
    "                    \"{\\\"error\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"Authorization 헤더에 Bearer 토큰이 필요합니다\\\"}\"",
    "            );",
    "            return;  // chain.doFilter()를 호출하지 않아 요청 차단!",
    "        }",
    "",
    "        String token = authHeader.substring(7);",
    "",
    "        if (token.length() < 10) {",
    "            log.warn(\"[인증 실패] 유효하지 않은 토큰: {} {}\", httpReq.getMethod(), httpReq.getRequestURI());",
    "            httpRes.setStatus(HttpServletResponse.SC_FORBIDDEN);",
    "            httpRes.setContentType(\"application/json;charset=UTF-8\");",
    "            httpRes.getWriter().write(",
    "                    \"{\\\"error\\\":\\\"FORBIDDEN\\\",\\\"message\\\":\\\"유효하지 않은 토큰입니다\\\"}\"",
    "            );",
    "            return;",
    "        }",
    "",
    "        log.info(\"[인증 성공] {} {}\", httpReq.getMethod(), httpReq.getRequestURI());",
    "        chain.doFilter(request, response);",
    "    }",
    "}",
    "```",
    "",
    "**요청 차단 방법 비교:**",
    "",
    "| Interceptor | Filter |",
    "|-------------|--------|",
    "| `return false;` | `chain.doFilter()`를 **호출하지 않고 return** |",
    "",
    "### FilterConfig.java (Filter 등록 - FilterRegistrationBean)",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import com.example.demo.filter.AuthenticationFilter;",
    "import com.example.demo.filter.CorsFilter;",
    "import com.example.demo.filter.RequestLoggingFilter;",
    "import org.springframework.boot.web.servlet.FilterRegistrationBean;",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "",
    "@Configuration",
    "public class FilterConfig {",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<CorsFilter> corsFilter() {",
    "        FilterRegistrationBean<CorsFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new CorsFilter());",
    "        bean.addUrlPatterns(\"/*\");",
    "        bean.setOrder(1);",
    "        bean.setName(\"corsFilter\");",
    "        return bean;",
    "    }",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<RequestLoggingFilter> loggingFilter() {",
    "        FilterRegistrationBean<RequestLoggingFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new RequestLoggingFilter());",
    "        bean.addUrlPatterns(\"/*\");",
    "        bean.setOrder(2);",
    "        bean.setName(\"requestLoggingFilter\");",
    "        return bean;",
    "    }",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<AuthenticationFilter> authFilter() {",
    "        FilterRegistrationBean<AuthenticationFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new AuthenticationFilter());",
    "        bean.addUrlPatterns(\"/api/*\");",
    "        bean.setOrder(3);",
    "        bean.setName(\"authenticationFilter\");",
    "        return bean;",
    "    }",
    "}",
    "```",
    "",
    "| 메서드 | 역할 |",
    "|--------|------|",
    "| `setFilter(new Filter())` | 등록할 Filter 객체 |",
    "| `addUrlPatterns(\"/api/*\")` | 적용할 URL 패턴 |",
    "| `setOrder(n)` | 실행 순서 (작을수록 먼저) |",
    "| `setName(\"name\")` | Filter 이름 (로그에서 확인용) |",
    "",
    "---",
    "",
    "## Filter 등록 방법 비교 (3가지)",
    "",
    "위 예제에서는 **방법 2 (FilterRegistrationBean)**을 사용했습니다. 참고로 3가지 방법이 있습니다.",
    "",
    "### 방법 1: @Component (간단하지만 순서·URL 제어 어려움)",
    "",
    "```java",
    "import org.springframework.core.annotation.Order;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Component",
    "@Order(1)",
    "public class MyFilter implements Filter {",
    "    @Override",
    "    public void doFilter(ServletRequest request, ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "        chain.doFilter(request, response);",
    "    }",
    "}",
    "```",
    "",
    "### 방법 2: FilterRegistrationBean (권장)",
    "",
    "위 `FilterConfig.java`에서 사용한 방식입니다. **순서, URL 패턴, 이름**을 모두 설정할 수 있습니다.",
    "",
    "### 방법 3: @WebFilter + @ServletComponentScan",
    "",
    "```java",
    "import jakarta.servlet.annotation.WebFilter;",
    "",
    "@WebFilter(urlPatterns = \"/api/*\", filterName = \"myFilter\")",
    "public class MyFilter implements Filter { ... }",
    "```",
    "",
    "```java",
    "import org.springframework.boot.web.servlet.ServletComponentScan;",
    "",
    "@SpringBootApplication",
    "@ServletComponentScan",
    "public class DemoApplication { ... }",
    "```",
    "",
    "### 등록 방법 비교",
    "",
    "| 방법 | 순서 제어 | URL 패턴 | Spring Bean 주입 | 추천도 |",
    "|------|-----------|----------|------------------|--------|",
    "| `@Component` + `@Order` | `@Order` | 불가 (전체 적용) | O | 간단한 경우 |",
    "| **`FilterRegistrationBean`** | `setOrder()` | `addUrlPatterns()` | O | **권장** |",
    "| `@WebFilter` | 보장 안 됨 | `urlPatterns` | X | 비추천 |",
    "",
    "---",
    "",
    "## 실행 및 포스트맨으로 테스트",
    "",
    "### 애플리케이션 실행",
    "",
    "IntelliJ에서 `DemoApplication.java`를 열고 **▶ Run** 버튼을 클릭합니다. 콘솔에 아래가 나오면 성공입니다.",
    "",
    "```",
    "Started DemoApplication in 1.5 seconds",
    "```",
    "",
    "### 테스트 1: 전체 상품 조회 (GET - 인증 없이 통과)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/items` |",
    "",
    "**포스트맨 응답:**",
    "",
    "```json",
    "[]",
    "```",
    "",
    "**IntelliJ 콘솔 로그 (Filter 동작 확인):**",
    "",
    "```",
    "INFO  [Filter 요청] GET /api/items | IP: 127.0.0.1",
    "INFO  [인증 성공] GET /api/items",
    "INFO  [Filter 응답] GET /api/items → 200 (12ms)",
    "```",
    "",
    "> `CorsFilter(order=1)` → `RequestLoggingFilter(order=2)` → `AuthenticationFilter(order=3)` 순서로 Filter Chain이 실행됩니다. GET은 인증 없이 통과합니다.",
    "",
    "### 테스트 2: 상품 생성 (POST - 토큰 없이 → 차단)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | POST |",
    "| **URL** | `http://localhost:8080/api/items` |",
    "| **Headers** | Content-Type: application/json |",
    "| **Body (raw JSON)** | 아래 참고 |",
    "",
    "```json",
    "{",
    "    \"name\": \"노트북\",",
    "    \"price\": 1500000",
    "}",
    "```",
    "",
    "**포스트맨 응답 (401 Unauthorized):**",
    "",
    "```json",
    "{",
    "    \"error\": \"UNAUTHORIZED\",",
    "    \"message\": \"Authorization 헤더에 Bearer 토큰이 필요합니다\"",
    "}",
    "```",
    "",
    "**콘솔 로그:**",
    "",
    "```",
    "INFO  [Filter 요청] POST /api/items | IP: 127.0.0.1",
    "WARN  [인증 실패] 토큰 없음: POST /api/items",
    "INFO  [Filter 응답] POST /api/items → 401 (3ms)",
    "```",
    "",
    "> `AuthenticationFilter`가 `chain.doFilter()`를 호출하지 않고 `return`하여 **Controller가 실행되지 않았습니다**.",
    "",
    "### 테스트 3: 상품 생성 (POST - 토큰 포함 → 성공)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | POST |",
    "| **URL** | `http://localhost:8080/api/items` |",
    "| **Headers** | Content-Type: application/json |",
    "| **Headers** | Authorization: `Bearer my-secret-token-12345` |",
    "| **Body (raw JSON)** | 아래 참고 |",
    "",
    "포스트맨에서 **Headers** 탭에 `Authorization` 헤더를 추가하고, 값에 `Bearer my-secret-token-12345`를 입력합니다.",
    "",
    "```json",
    "{",
    "    \"name\": \"노트북\",",
    "    \"price\": 1500000",
    "}",
    "```",
    "",
    "**포스트맨 응답 (201 Created):**",
    "",
    "```json",
    "{",
    "    \"id\": 1,",
    "    \"name\": \"노트북\",",
    "    \"price\": 1500000",
    "}",
    "```",
    "",
    "**콘솔 로그:**",
    "",
    "```",
    "INFO  [Filter 요청] POST /api/items | IP: 127.0.0.1",
    "INFO  [인증 성공] POST /api/items",
    "INFO  상품 생성: 노트북 (1500000원)",
    "INFO  [Filter 응답] POST /api/items → 201 (15ms)",
    "```",
    "",
    "### 테스트 4: 특정 상품 조회 (GET)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/items/1` |",
    "",
    "**포스트맨 응답:**",
    "",
    "```json",
    "{",
    "    \"id\": 1,",
    "    \"name\": \"노트북\",",
    "    \"price\": 1500000",
    "}",
    "```",
    "",
    "### 테스트 5: 상품 삭제 (DELETE - 짧은 토큰 → 403)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | DELETE |",
    "| **URL** | `http://localhost:8080/api/items/1` |",
    "| **Headers** | Authorization: `Bearer short` |",
    "",
    "**포스트맨 응답 (403 Forbidden):**",
    "",
    "```json",
    "{",
    "    \"error\": \"FORBIDDEN\",",
    "    \"message\": \"유효하지 않은 토큰입니다\"",
    "}",
    "```",
    "",
    "### 테스트 6: 상품 삭제 (DELETE - 정상 토큰 → 성공)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | DELETE |",
    "| **URL** | `http://localhost:8080/api/items/1` |",
    "| **Headers** | Authorization: `Bearer my-secret-token-12345` |",
    "",
    "**포스트맨 응답 (204 No Content):** 본문 없음",
    "",
    "### 포스트맨 테스트 요약",
    "",
    "| 테스트 | Method | URL | Authorization | 결과 | 확인할 Filter |",
    "|--------|--------|-----|---------------|------|-------------|",
    "| 전체 조회 | GET | `/api/items` | 없음 | 200 | CORS, Logging (Auth 통과) |",
    "| 생성 (토큰 없음) | POST | `/api/items` | 없음 | **401** | CORS, Logging, **Auth 차단** |",
    "| 생성 (토큰 있음) | POST | `/api/items` | `Bearer my-secret-token-12345` | 201 | 3개 모두 통과 |",
    "| 개별 조회 | GET | `/api/items/1` | 없음 | 200 | CORS, Logging (Auth 통과) |",
    "| 삭제 (짧은 토큰) | DELETE | `/api/items/1` | `Bearer short` | **403** | CORS, Logging, **Auth 차단** |",
    "| 삭제 (정상 토큰) | DELETE | `/api/items/1` | `Bearer my-secret-token-12345` | 204 | 3개 모두 통과 |",
    "",
    "---",
    "",
    "## Filter Chain 실행 순서",
    "",
    "여러 Filter가 등록된 경우, `order` 값이 **작을수록 먼저** 실행됩니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant F1 as CorsFilter (order=1)",
    "    participant F2 as LoggingFilter (order=2)",
    "    participant F3 as AuthFilter (order=3)",
    "    participant S as DispatcherServlet → Controller",
    "    C->>F1: 요청",
    "    F1->>F2: chain.doFilter()",
    "    F2->>F3: chain.doFilter()",
    "    F3->>S: chain.doFilter()",
    "    S-->>F3: 응답",
    "    F3-->>F2: 응답",
    "    F2-->>F1: 응답",
    "    F1-->>C: 최종 응답",
    "```",
    "",
    "### 권장 순서",
    "",
    "| 순서 | Filter | 이유 |",
    "|------|--------|------|",
    "| 1 | CORS | 모든 응답에 CORS 헤더가 포함되어야 함 |",
    "| 2 | 로깅 | 요청 전체 흐름을 기록 |",
    "| 3 | 인증 | 보호된 리소스 접근 전 최종 검증 |",
    "",
    "---",
    "",
    "## OncePerRequestFilter (Spring 제공)",
    "",
    "Spring은 `jakarta.servlet.Filter` 대신 **`OncePerRequestFilter`** 추상 클래스를 제공합니다. 요청당 **1회만** 실행되는 것을 보장합니다.",
    "",
    "### 왜 필요한가?",
    "",
    "서블릿 스펙에서는 `forward`나 `include`로 내부 이동이 발생하면 같은 요청에서 Filter가 **여러 번** 호출될 수 있습니다. `OncePerRequestFilter`는 이를 방지합니다.",
    "",
    "### 예제: OncePerRequestFilter 기반 로깅",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.FilterChain;",
    "import jakarta.servlet.ServletException;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.web.filter.OncePerRequestFilter;",
    "",
    "import java.io.IOException;",
    "",
    "@Slf4j",
    "public class ApiLoggingFilter extends OncePerRequestFilter {",
    "",
    "    @Override",
    "    protected void doFilterInternal(HttpServletRequest request,",
    "                                    HttpServletResponse response,",
    "                                    FilterChain filterChain)",
    "            throws ServletException, IOException {",
    "",
    "        long start = System.currentTimeMillis();",
    "        log.info(\"[API] {} {} 시작\", request.getMethod(), request.getRequestURI());",
    "",
    "        filterChain.doFilter(request, response);",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        log.info(\"[API] {} {} → {} ({}ms)\",",
    "                request.getMethod(), request.getRequestURI(), response.getStatus(), elapsed);",
    "    }",
    "",
    "    @Override",
    "    protected boolean shouldNotFilter(HttpServletRequest request) {",
    "        String uri = request.getRequestURI();",
    "        return uri.startsWith(\"/css\")",
    "                || uri.startsWith(\"/js\")",
    "                || uri.startsWith(\"/images\");",
    "    }",
    "}",
    "```",
    "",
    "### Filter vs OncePerRequestFilter 비교",
    "",
    "| 비교 | `Filter` | `OncePerRequestFilter` |",
    "|------|----------|------------------------|",
    "| 패키지 | `jakarta.servlet` | `org.springframework.web.filter` |",
    "| 요청당 실행 | 여러 번 가능 (forward/include 시) | **1회 보장** |",
    "| 구현 메서드 | `doFilter()` | `doFilterInternal()` |",
    "| 제외 조건 | 직접 구현 | `shouldNotFilter()` 오버라이드 |",
    "| 파라미터 타입 | `ServletRequest` | **`HttpServletRequest`** (캐스팅 불필요) |",
    "",
    "> 실무에서는 대부분 **`OncePerRequestFilter`를 사용하는 것이 권장**됩니다.",
    "",
    "---",
    "",
    "## Spring Boot 내장 Filter",
    "",
    "Spring Boot는 자동으로 등록하는 기본 Filter들이 있습니다.",
    "",
    "| Filter | 역할 | 자동 등록 |",
    "|--------|------|-----------|",
    "| `CharacterEncodingFilter` | 요청/응답 인코딩 (UTF-8) | O (기본 활성화) |",
    "| `HiddenHttpMethodFilter` | HTML form에서 PUT/DELETE 사용 (`_method` 파라미터) | O |",
    "| `FormContentFilter` | PUT/PATCH의 `application/x-www-form-urlencoded` 파싱 | O |",
    "| `RequestContextFilter` | `RequestContextHolder`에 요청 정보 저장 | O |",
    "",
    "> Spring Boot는 `CharacterEncodingFilter`가 기본 등록되어 있으므로, 별도로 인코딩 Filter를 만들 필요가 없습니다.",
    "",
    "---",
    "",
    "## 전체 흐름 정리: Filter → Interceptor → AOP → Controller",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"클라이언트 요청\"] --> B[\"Filter Chain<br/>(CORS → 로깅 → 인증)\"]",
    "    B --> C[\"DispatcherServlet\"]",
    "    C --> D[\"Interceptor<br/>preHandle()\"]",
    "    D --> E[\"AOP<br/>@Before / @Around\"]",
    "    E --> F[\"Controller\"]",
    "    F --> G[\"Service\"]",
    "    G --> F",
    "    F --> E",
    "    E --> D",
    "    D --> H[\"Interceptor<br/>postHandle() → afterCompletion()\"]",
    "    H --> C",
    "    C --> B",
    "    B --> I[\"클라이언트 응답\"]",
    "    style B fill:#e67e22,color:#fff",
    "    style D fill:#3498db,color:#fff",
    "    style H fill:#3498db,color:#fff",
    "    style E fill:#27ae60,color:#fff",
    "```",
    "",
    "| 계층 | 기술 | 주요 용도 |",
    "|------|------|-----------|",
    "| **가장 바깥** | Filter | 인코딩, CORS, XSS, 요청 래핑 |",
    "| **중간** | Interceptor | 로그인 체크, API 로깅, 권한 |",
    "| **가장 안쪽** | AOP | 트랜잭션, 메서드 실행 시간, 캐싱 |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| Filter란 | DispatcherServlet 밖에서 동작하는 Servlet 레벨 공통 처리 기능 |",
    "| 인터페이스 | `jakarta.servlet.Filter` 또는 `OncePerRequestFilter` (권장) |",
    "| 등록 방법 | `FilterRegistrationBean` (권장) > `@Component` > `@WebFilter` |",
    "| 순서 제어 | `setOrder(n)` — 작을수록 먼저 실행 |",
    "| 요청 차단 | `chain.doFilter()`를 호출하지 않으면 다음 단계로 전달되지 않음 |",
    "",
    "**Filter 활용 패턴:**",
    "",
    "| 용도 | 핵심 코드 |",
    "|------|-----------|",
    "| 로깅 | `chain.doFilter()` 전후에 시간 측정·로그 출력 |",
    "| CORS | `response.setHeader(\"Access-Control-Allow-Origin\", \"*\")` |",
    "| 인증 | `Authorization` 헤더 확인 → 실패 시 `return` (chain 미호출) |",
    "| XSS 방지 | `HttpServletRequestWrapper`로 요청 객체 교체 |",
    "| 제외 조건 | `OncePerRequestFilter.shouldNotFilter()` 오버라이드 |",
    "",
    "실무에서는 **인코딩·CORS·XSS는 Filter**, **로그인 체크·API 로깅은 Interceptor**, **트랜잭션·서비스 로직은 AOP**로 역할을 분리하는 것이 일반적입니다. 세 기술의 동작 위치를 이해하면 어디에 어떤 로직을 넣어야 하는지 자연스럽게 판단할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
