<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-caching",
  title: "스프링부트 캐싱 완전 정리 - @Cacheable, @CacheEvict, @CachePut, Redis 연동까지",
  date: "2026-02-20",
  summary: "Spring Boot의 캐시 추상화를 정리합니다. @Cacheable로 조회 캐싱, @CacheEvict로 캐시 삭제, @CachePut으로 캐시 갱신, Spring Cache Abstraction 구조, 인메모리/Redis/EhCache 구현체 비교와 실전 예제를 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","cache","cacheable","redis","ehcache","java","backend"],
  content: [
    "## 캐싱이 필요한 이유",
    "",
    "**캐싱**은 자주 조회되지만 잘 변하지 않는 데이터를 **메모리에 저장**해두고, 같은 요청이 오면 **DB 조회 없이 즉시 반환**하는 기법입니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant S as Service",
    "    participant Cache as 캐시",
    "    participant DB as 데이터베이스",
    "",
    "    Note over C,DB: 첫 번째 요청 (캐시 MISS)",
    "    C->>S: getUser(1)",
    "    S->>Cache: 캐시에 있나?",
    "    Cache-->>S: 없음 (MISS)",
    "    S->>DB: SELECT * FROM users WHERE id=1",
    "    DB-->>S: User 데이터",
    "    S->>Cache: 결과 저장",
    "    S-->>C: User 응답 (100ms)",
    "",
    "    Note over C,DB: 두 번째 요청 (캐시 HIT)",
    "    C->>S: getUser(1)",
    "    S->>Cache: 캐시에 있나?",
    "    Cache-->>S: 있음 (HIT) ⚡",
    "    S-->>C: User 응답 (1ms)",
    "```",
    "",
    "| 비교 | 캐시 없음 | 캐시 있음 |",
    "|------|----------|----------|",
    "| 응답 시간 | 50~200ms (DB 조회) | **1~5ms** |",
    "| DB 부하 | 매 요청마다 쿼리 | 최초 1번만 |",
    "| 적합한 데이터 | - | 자주 조회, 변경 적은 데이터 |",
    "",
    "---",
    "",
    "## Spring Cache Abstraction",
    "",
    "Spring은 **캐시 추상화 계층**을 제공하여, 코드 변경 없이 다양한 캐시 구현체를 교체할 수 있습니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"@Cacheable, @CacheEvict, @CachePut\"] --> B[\"Spring Cache Abstraction<br/>(CacheManager 인터페이스)\"]",
    "    B --> C[\"ConcurrentMapCacheManager<br/>(기본, 인메모리)\"]",
    "    B --> D[\"RedisCacheManager<br/>(Redis)\"]",
    "    B --> E[\"EhCacheCacheManager<br/>(EhCache)\"]",
    "    B --> F[\"CaffeineCacheManager<br/>(Caffeine)\"]",
    "```",
    "",
    "> 어노테이션은 동일하게 사용하고, **CacheManager 구현체만 교체**하면 캐시 저장소가 바뀝니다.",
    "",
    "---",
    "",
    "## 프로젝트 설정",
    "",
    "### 의존성 (build.gradle)",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-cache'",
    "",
    "    // Redis 사용 시",
    "    // implementation 'org.springframework.boot:spring-boot-starter-data-redis'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "}",
    "```",
    "",
    "### @EnableCaching 활성화",
    "",
    "```java",
    "@SpringBootApplication",
    "@EnableCaching",
    "public class DemoApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "> `@EnableCaching`이 없으면 캐시 어노테이션이 동작하지 않습니다.",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── config/",
    "│   └── CacheConfig.java           // 캐시 설정",
    "├── domain/",
    "│   └── Product.java",
    "├── repository/",
    "│   └── ProductRepository.java",
    "├── service/",
    "│   └── ProductService.java        // 캐시 적용",
    "├── controller/",
    "│   └── ProductController.java",
    "└── DemoApplication.java",
    "```",
    "",
    "---",
    "",
    "# 1. @Cacheable (조회 결과 캐싱)",
    "",
    "## 개념",
    "",
    "메서드 실행 결과를 **캐시에 저장**합니다. 같은 파라미터로 재호출 시 메서드를 실행하지 않고 **캐시에서 바로 반환**합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"메서드 호출\"] --> B{\"캐시에 데이터 있음?\"}",
    "    B -->|HIT| C[\"캐시에서 즉시 반환<br/>(메서드 실행 안 함)\"]",
    "    B -->|MISS| D[\"메서드 실행\"]",
    "    D --> E[\"결과를 캐시에 저장\"]",
    "    E --> F[\"결과 반환\"]",
    "```",
    "",
    "## 기본 사용법",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class ProductService {",
    "",
    "    private final ProductRepository productRepository;",
    "",
    "    @Cacheable(value = \"products\", key = \"#id\")",
    "    public Product findById(Long id) {",
    "        log.info(\"DB 조회 실행: id={}\", id);",
    "        return productRepository.findById(id)",
    "                .orElseThrow(() -> new RuntimeException(\"상품 없음\"));",
    "    }",
    "}",
    "```",
    "",
    "**호출 결과:**",
    "",
    "```",
    "findById(1)  →  \"DB 조회 실행: id=1\"  (캐시 MISS → DB 조회 → 캐시 저장)",
    "findById(1)  →  (로그 없음, 캐시 HIT → 즉시 반환)",
    "findById(1)  →  (로그 없음, 캐시 HIT → 즉시 반환)",
    "findById(2)  →  \"DB 조회 실행: id=2\"  (다른 키 → 캐시 MISS)",
    "```",
    "",
    "## @Cacheable 속성",
    "",
    "| 속성 | 설명 | 예시 |",
    "|------|------|------|",
    "| `value` / `cacheNames` | 캐시 이름 | `\"products\"` |",
    "| `key` | 캐시 키 (SpEL) | `\"#id\"`, `\"#user.email\"` |",
    "| `condition` | 캐싱 조건 | `\"#id > 0\"` |",
    "| `unless` | 결과 기반 캐싱 제외 | `\"#result == null\"` |",
    "| `keyGenerator` | 커스텀 키 생성기 | Bean 이름 |",
    "| `cacheManager` | 사용할 CacheManager | Bean 이름 |",
    "",
    "## 다양한 키 설정 예제",
    "",
    "```java",
    "// 단일 파라미터",
    "@Cacheable(value = \"products\", key = \"#id\")",
    "public Product findById(Long id) { ... }",
    "",
    "// 복합 키",
    "@Cacheable(value = \"products\", key = \"#category + ':' + #page\")",
    "public List<Product> findByCategory(String category, int page) { ... }",
    "",
    "// 객체 필드",
    "@Cacheable(value = \"users\", key = \"#request.email\")",
    "public User findByEmail(SearchRequest request) { ... }",
    "",
    "// 조건부 캐싱 (id가 양수일 때만)",
    "@Cacheable(value = \"products\", key = \"#id\", condition = \"#id > 0\")",
    "public Product findById(Long id) { ... }",
    "",
    "// null 결과는 캐싱하지 않음",
    "@Cacheable(value = \"products\", key = \"#id\", unless = \"#result == null\")",
    "public Product findById(Long id) { ... }",
    "```",
    "",
    "---",
    "",
    "# 2. @CacheEvict (캐시 삭제)",
    "",
    "## 개념",
    "",
    "데이터가 **변경/삭제**되었을 때 관련 캐시를 제거합니다. 다음 조회 시 DB에서 최신 데이터를 가져옵니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"상품 수정 요청\"] --> B[\"DB 업데이트\"]",
    "    B --> C[\"@CacheEvict<br/>해당 캐시 삭제\"]",
    "    C --> D[\"다음 조회 시<br/>DB에서 최신 데이터\"]",
    "```",
    "",
    "## 사용법",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class ProductService {",
    "",
    "    private final ProductRepository productRepository;",
    "",
    "    @Cacheable(value = \"products\", key = \"#id\")",
    "    public Product findById(Long id) {",
    "        log.info(\"DB 조회: id={}\", id);",
    "        return productRepository.findById(id).orElseThrow();",
    "    }",
    "",
    "    // 특정 키의 캐시 삭제",
    "    @CacheEvict(value = \"products\", key = \"#id\")",
    "    public Product update(Long id, UpdateProductRequest request) {",
    "        log.info(\"상품 수정 + 캐시 삭제: id={}\", id);",
    "        Product product = productRepository.findById(id).orElseThrow();",
    "        product.setName(request.getName());",
    "        product.setPrice(request.getPrice());",
    "        return productRepository.save(product);",
    "    }",
    "",
    "    // 특정 키의 캐시 삭제",
    "    @CacheEvict(value = \"products\", key = \"#id\")",
    "    public void delete(Long id) {",
    "        log.info(\"상품 삭제 + 캐시 삭제: id={}\", id);",
    "        productRepository.deleteById(id);",
    "    }",
    "",
    "    // 해당 캐시의 모든 항목 삭제",
    "    @CacheEvict(value = \"products\", allEntries = true)",
    "    public Product create(CreateProductRequest request) {",
    "        log.info(\"상품 생성 + 전체 캐시 삭제\");",
    "        return productRepository.save(request.toEntity());",
    "    }",
    "}",
    "```",
    "",
    "## @CacheEvict 속성",
    "",
    "| 속성 | 설명 | 기본값 |",
    "|------|------|--------|",
    "| `value` | 캐시 이름 | - |",
    "| `key` | 삭제할 키 | 파라미터 기반 |",
    "| `allEntries` | 해당 캐시의 **모든 항목** 삭제 | `false` |",
    "| `beforeInvocation` | 메서드 실행 **전에** 삭제 | `false` |",
    "",
    "> `beforeInvocation = true`로 설정하면 메서드 실행 중 예외가 발생해도 캐시가 삭제됩니다.",
    "",
    "---",
    "",
    "# 3. @CachePut (캐시 갱신)",
    "",
    "## 개념",
    "",
    "`@CachePut`은 메서드를 **항상 실행**하고, 그 결과로 **캐시를 갱신**합니다. `@Cacheable`과 달리 캐시 HIT여도 메서드가 실행됩니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    subgraph \"@Cacheable\"",
    "        A1[\"호출\"] --> B1{\"캐시 HIT?\"}",
    "        B1 -->|예| C1[\"캐시 반환 (실행 안 함)\"]",
    "        B1 -->|아니오| D1[\"실행 → 캐시 저장\"]",
    "    end",
    "    subgraph \"@CachePut\"",
    "        A2[\"호출\"] --> B2[\"항상 실행\"]",
    "        B2 --> C2[\"결과로 캐시 갱신\"]",
    "    end",
    "```",
    "",
    "## 사용법",
    "",
    "```java",
    "// 수정 후 결과로 캐시를 즉시 갱신",
    "@CachePut(value = \"products\", key = \"#id\")",
    "public Product update(Long id, UpdateProductRequest request) {",
    "    Product product = productRepository.findById(id).orElseThrow();",
    "    product.setName(request.getName());",
    "    product.setPrice(request.getPrice());",
    "    return productRepository.save(product);",
    "    // 반환된 Product가 캐시에 저장됨",
    "}",
    "```",
    "",
    "## @CacheEvict vs @CachePut (수정 시)",
    "",
    "| 방식 | 동작 | 다음 조회 |",
    "|------|------|----------|",
    "| `@CacheEvict` | 캐시 삭제 | DB에서 조회 (캐시 MISS → 재캐싱) |",
    "| `@CachePut` | 캐시 **갱신** | 캐시에서 즉시 반환 (캐시 HIT) |",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    Note over A,B: @CacheEvict 방식",
    "    participant A as Service",
    "    participant B as Cache/DB",
    "    A->>B: update() → 캐시 삭제",
    "    A->>B: findById() → 캐시 MISS → DB 조회 → 재캐싱",
    "",
    "    Note over A,B: @CachePut 방식",
    "    A->>B: update() → DB 수정 + 캐시 갱신",
    "    A->>B: findById() → 캐시 HIT (DB 조회 불필요)",
    "```",
    "",
    "> 수정 직후 바로 조회가 많다면 `@CachePut`이 유리합니다. 단순 무효화면 `@CacheEvict`가 간편합니다.",
    "",
    "---",
    "",
    "# 4. 캐시 설정",
    "",
    "## 인메모리 캐시 (ConcurrentMapCache, 기본)",
    "",
    "별도 설정 없이 `@EnableCaching`만 추가하면 `ConcurrentMapCacheManager`가 기본 사용됩니다.",
    "",
    "```java",
    "@Configuration",
    "@EnableCaching",
    "public class CacheConfig {",
    "",
    "    @Bean",
    "    public CacheManager cacheManager() {",
    "        return new ConcurrentMapCacheManager(\"products\", \"users\", \"categories\");",
    "    }",
    "}",
    "```",
    "",
    "> 간단하지만 **TTL(만료 시간) 설정이 불가능**하고 **서버 재시작 시 초기화**됩니다. 개발/테스트용으로 적합합니다.",
    "",
    "---",
    "",
    "## Caffeine 캐시 (고성능 인메모리)",
    "",
    "**Caffeine**은 Java에서 가장 빠른 인메모리 캐시 라이브러리입니다. TTL, 최대 크기 설정이 가능합니다.",
    "",
    "### 의존성",
    "",
    "```groovy",
    "implementation 'com.github.ben-manes.caffeine:caffeine'",
    "```",
    "",
    "### 설정",
    "",
    "```java",
    "@Configuration",
    "@EnableCaching",
    "public class CacheConfig {",
    "",
    "    @Bean",
    "    public CacheManager cacheManager() {",
    "        CaffeineCacheManager manager = new CaffeineCacheManager();",
    "        manager.setCaffeine(Caffeine.newBuilder()",
    "                .maximumSize(500)                      // 최대 500개 항목",
    "                .expireAfterWrite(Duration.ofMinutes(10)) // 10분 후 만료",
    "                .recordStats());                        // 통계 기록",
    "        return manager;",
    "    }",
    "}",
    "```",
    "",
    "### 캐시별 다른 설정",
    "",
    "```java",
    "@Configuration",
    "@EnableCaching",
    "public class CacheConfig {",
    "",
    "    @Bean",
    "    public CacheManager cacheManager() {",
    "        SimpleCacheManager manager = new SimpleCacheManager();",
    "        manager.setCaches(List.of(",
    "                buildCache(\"products\", 500, 10),   // 500개, 10분",
    "                buildCache(\"users\", 200, 30),      // 200개, 30분",
    "                buildCache(\"categories\", 50, 60)   // 50개, 60분",
    "        ));",
    "        return manager;",
    "    }",
    "",
    "    private CaffeineCache buildCache(String name, int maxSize, int minutesTTL) {",
    "        return new CaffeineCache(name, Caffeine.newBuilder()",
    "                .maximumSize(maxSize)",
    "                .expireAfterWrite(Duration.ofMinutes(minutesTTL))",
    "                .build());",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Redis란?",
    "",
    "**Redis(Remote Dictionary Server)**는 **인메모리 데이터 저장소**입니다. 데이터를 디스크가 아닌 **메모리(RAM)**에 저장하기 때문에 읽기/쓰기 속도가 매우 빠릅니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph \"일반 DB\"",
    "        A1[\"요청\"] --> B1[\"디스크 읽기\"] --> C1[\"응답\<br>수~수십 ms\"]",
    "    end",
    "    subgraph \"Redis\"",
    "        A2[\"요청\"] --> B2[\"메모리 읽기\"] --> C2[\"응답\<br>sub-ms\"]",
    "    end",
    "```",
    "",
    "### Redis의 특징",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| **인메모리** | 데이터를 RAM에 저장, **초당 10만+ 명령** 처리 가능 |",
    "| **Key-Value 구조** | 모든 데이터를 `키:값` 쌍으로 저장 |",
    "| **다양한 자료구조** | String, List, Set, Hash, Sorted Set 등 지원 |",
    "| **영속성(Persistence)** | RDB 스냅샷, AOF 로그로 디스크에 백업 가능 |",
    "| **TTL(Time To Live)** | 키별 만료 시간 설정 → 자동 삭제 |",
    "| **Pub/Sub** | 메시지 발행/구독 지원 |",
    "| **싱글 스레드** | 단일 스레드로 동작, 원자적 연산 보장 |",
    "| **Replication** | Master-Replica 구조로 읽기 분산 가능 |",
    "",
    "### Redis가 주로 쓰이는 곳",
    "",
    "```mermaid",
    "flowchart TD",
    "    R[\"Redis\"] --> A[\"캐싱\<br>(DB 조회 결과 저장)\"]",
    "    R --> B[\"세션 저장소\<br>(로그인 세션 관리)\"]",
    "    R --> C[\"Rate Limiting\<br>(API 호출 횟수 제한)\"]",
    "    R --> D[\"랭킹/리더보드\<br>(Sorted Set 활용)\"]",
    "    R --> E[\"메시지 큐\<br>(Pub/Sub, Stream)\"]",
    "    R --> F[\"분산 락\<br>(동시성 제어)\"]",
    "```",
    "",
    "### Redis 자료구조",
    "",
    "| 자료구조 | 설명 | 사용 예시 | 명령어 예 |",
    "|----------|------|----------|----------|",
    "| **String** | 단순 문자열/숫자 | 캐시, 카운터 | `SET key value`, `GET key` |",
    "| **Hash** | 필드-값 쌍의 집합 | 객체 저장 (User 정보) | `HSET user:1 name \"홍길동\"` |",
    "| **List** | 순서가 있는 문자열 목록 | 최근 게시물, 큐 | `LPUSH list val`, `RPOP list` |",
    "| **Set** | 중복 없는 문자열 집합 | 태그, 고유 방문자 | `SADD set val`, `SMEMBERS set` |",
    "| **Sorted Set** | 점수(score)로 정렬된 Set | 랭킹, 리더보드 | `ZADD rank 100 \"user1\"` |",
    "| **Stream** | 로그/이벤트 스트림 | 메시지 큐, 이벤트 소싱 | `XADD stream * field val` |",
    "",
    "---",
    "",
    "## Docker Compose로 Redis 구성",
    "",
    "개발 환경에서 Redis를 가장 쉽게 실행하는 방법은 **Docker Compose**입니다.",
    "",
    "### 기본 구성",
    "",
    "프로젝트 루트에 `docker-compose.yml` 파일을 생성합니다.",
    "",
    "```yaml",
    "version: '3.8'",
    "",
    "services:",
    "  redis:",
    "    image: redis:7-alpine",
    "    container_name: my-redis",
    "    ports:",
    "      - \"6379:6379\"",
    "    volumes:",
    "      - redis-data:/data",
    "    restart: unless-stopped",
    "",
    "volumes:",
    "  redis-data:",
    "```",
    "",
    "```bash",
    "# Redis 시작",
    "docker compose up -d",
    "",
    "# 상태 확인",
    "docker compose ps",
    "",
    "# Redis CLI 접속",
    "docker exec -it my-redis redis-cli",
    "",
    "# 종료",
    "docker compose down",
    "```",
    "",
    "### 비밀번호 + 커스텀 설정",
    "",
    "운영 환경에서는 비밀번호와 메모리 제한 등을 설정합니다.",
    "",
    "```yaml",
    "version: '3.8'",
    "",
    "services:",
    "  redis:",
    "    image: redis:7-alpine",
    "    container_name: my-redis",
    "    ports:",
    "      - \"6379:6379\"",
    "    command: >",
    "      redis-server",
    "      --requirepass myredispassword",
    "      --maxmemory 256mb",
    "      --maxmemory-policy allkeys-lru",
    "      --appendonly yes",
    "    volumes:",
    "      - redis-data:/data",
    "    environment:",
    "      - TZ=Asia/Seoul",
    "    restart: unless-stopped",
    "    healthcheck:",
    "      test: [\"CMD\", \"redis-cli\", \"-a\", \"myredispassword\", \"ping\"]",
    "      interval: 10s",
    "      timeout: 5s",
    "      retries: 3",
    "",
    "volumes:",
    "  redis-data:",
    "```",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| `--requirepass` | 접속 비밀번호 설정 |",
    "| `--maxmemory 256mb` | 최대 메모리 사용량 제한 |",
    "| `--maxmemory-policy allkeys-lru` | 메모리 초과 시 가장 오래된 키 삭제 |",
    "| `--appendonly yes` | AOF 영속성 활성화 (데이터 복구 가능) |",
    "",
    "### Spring Boot + Redis 함께 구성",
    "",
    "Spring Boot 애플리케이션과 Redis를 하나의 Docker Compose로 관리할 수 있습니다.",
    "",
    "```yaml",
    "version: '3.8'",
    "",
    "services:",
    "  app:",
    "    build: .",
    "    container_name: my-spring-app",
    "    ports:",
    "      - \"8080:8080\"",
    "    environment:",
    "      - SPRING_DATA_REDIS_HOST=redis",
    "      - SPRING_DATA_REDIS_PORT=6379",
    "      - SPRING_DATA_REDIS_PASSWORD=myredispassword",
    "    depends_on:",
    "      redis:",
    "        condition: service_healthy",
    "    restart: unless-stopped",
    "",
    "  redis:",
    "    image: redis:7-alpine",
    "    container_name: my-redis",
    "    ports:",
    "      - \"6379:6379\"",
    "    command: >",
    "      redis-server",
    "      --requirepass myredispassword",
    "      --maxmemory 256mb",
    "      --maxmemory-policy allkeys-lru",
    "      --appendonly yes",
    "    volumes:",
    "      - redis-data:/data",
    "    restart: unless-stopped",
    "    healthcheck:",
    "      test: [\"CMD\", \"redis-cli\", \"-a\", \"myredispassword\", \"ping\"]",
    "      interval: 10s",
    "      timeout: 5s",
    "      retries: 3",
    "",
    "volumes:",
    "  redis-data:",
    "```",
    "",
    "> Docker Compose 내에서 서비스 간 통신은 **서비스 이름**이 호스트명이 됩니다. `redis`라는 서비스 이름이 곧 `SPRING_DATA_REDIS_HOST=redis`의 값입니다.",
    "",
    "### Dockerfile (Spring Boot)",
    "",
    "```dockerfile",
    "FROM eclipse-temurin:17-jre-alpine",
    "WORKDIR /app",
    "COPY build/libs/*.jar app.jar",
    "ENTRYPOINT [\"java\", \"-jar\", \"app.jar\"]",
    "```",
    "",
    "---",
    "",
    "## Spring Boot + Redis 연동 (단계별 설정)",
    "",
    "### Step 1. 의존성 추가",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-cache'",
    "    implementation 'org.springframework.boot:spring-boot-starter-data-redis'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "}",
    "```",
    "",
    "> `spring-boot-starter-data-redis`를 추가하면 **Lettuce**(Redis 클라이언트)가 자동으로 포함됩니다.",
    "",
    "### Step 2. application.yml 설정",
    "",
    "```yaml",
    "spring:",
    "  data:",
    "    redis:",
    "      host: localhost              # Docker Compose 내부에서는 서비스명(redis)",
    "      port: 6379",
    "      password: myredispassword    # 비밀번호 설정 시",
    "      timeout: 3000               # 연결 타임아웃 (ms)",
    "      lettuce:",
    "        pool:",
    "          max-active: 8            # 최대 커넥션 수",
    "          max-idle: 8              # 최대 유휴 커넥션",
    "          min-idle: 2              # 최소 유휴 커넥션",
    "          max-wait: -1             # 커넥션 대기 시간 (-1: 무제한)",
    "  cache:",
    "    type: redis",
    "    redis:",
    "      time-to-live: 600000        # 기본 TTL 10분 (밀리초)",
    "      cache-null-values: false    # null 캐싱 안 함",
    "      key-prefix: \"myapp::\"      # 키 접두사",
    "```",
    "",
    "### Step 3. Redis 설정 클래스",
    "",
    "```java",
    "@Configuration",
    "@EnableCaching",
    "public class RedisConfig {",
    "",
    "    @Bean",
    "    public RedisConnectionFactory redisConnectionFactory(",
    "            @Value(\"${spring.data.redis.host}\") String host,",
    "            @Value(\"${spring.data.redis.port}\") int port,",
    "            @Value(\"${spring.data.redis.password}\") String password) {",
    "",
    "        RedisStandaloneConfiguration config = new RedisStandaloneConfiguration();",
    "        config.setHostName(host);",
    "        config.setPort(port);",
    "        config.setPassword(password);",
    "",
    "        LettuceConnectionFactory factory = new LettuceConnectionFactory(config);",
    "        return factory;",
    "    }",
    "",
    "    @Bean",
    "    public RedisTemplate<String, Object> redisTemplate(",
    "            RedisConnectionFactory connectionFactory) {",
    "",
    "        RedisTemplate<String, Object> template = new RedisTemplate<>();",
    "        template.setConnectionFactory(connectionFactory);",
    "",
    "        // Key는 문자열",
    "        template.setKeySerializer(new StringRedisSerializer());",
    "        template.setHashKeySerializer(new StringRedisSerializer());",
    "",
    "        // Value는 JSON",
    "        GenericJackson2JsonRedisSerializer jsonSerializer =",
    "                new GenericJackson2JsonRedisSerializer();",
    "        template.setValueSerializer(jsonSerializer);",
    "        template.setHashValueSerializer(jsonSerializer);",
    "",
    "        return template;",
    "    }",
    "}",
    "```",
    "",
    "### Step 4. Redis CacheManager 설정",
    "",
    "```java",
    "@Configuration",
    "@EnableCaching",
    "public class RedisCacheConfig {",
    "",
    "    @Bean",
    "    public CacheManager cacheManager(RedisConnectionFactory connectionFactory) {",
    "",
    "        RedisCacheConfiguration defaultConfig = RedisCacheConfiguration",
    "                .defaultCacheConfig()",
    "                .entryTtl(Duration.ofMinutes(10))",
    "                .disableCachingNullValues()",
    "                .serializeKeysWith(",
    "                        RedisSerializationContext.SerializationPair",
    "                                .fromSerializer(new StringRedisSerializer()))",
    "                .serializeValuesWith(",
    "                        RedisSerializationContext.SerializationPair",
    "                                .fromSerializer(new GenericJackson2JsonRedisSerializer()));",
    "",
    "        // 캐시별 개별 TTL 설정",
    "        Map<String, RedisCacheConfiguration> cacheConfigs = Map.of(",
    "                \"products\", defaultConfig.entryTtl(Duration.ofMinutes(30)),",
    "                \"users\", defaultConfig.entryTtl(Duration.ofHours(1)),",
    "                \"categories\", defaultConfig.entryTtl(Duration.ofHours(6))",
    "        );",
    "",
    "        return RedisCacheManager.builder(connectionFactory)",
    "                .cacheDefaults(defaultConfig)",
    "                .withInitialCacheConfigurations(cacheConfigs)",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "### Step 5. 캐시 적용 (서비스 코드는 동일)",
    "",
    "캐시 어노테이션 코드는 **인메모리 캐시와 완전히 동일**합니다. CacheManager만 바꿔주면 저장소가 Redis로 변경됩니다.",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class ProductService {",
    "",
    "    private final ProductRepository productRepository;",
    "",
    "    @Cacheable(value = \"products\", key = \"#id\", unless = \"#result == null\")",
    "    public Product findById(Long id) {",
    "        log.info(\"[CACHE MISS] DB 조회: id={}\", id);",
    "        return productRepository.findById(id).orElse(null);",
    "    }",
    "",
    "    @CachePut(value = \"products\", key = \"#id\")",
    "    public Product update(Long id, UpdateProductRequest request) {",
    "        Product product = productRepository.findById(id).orElseThrow();",
    "        product.setName(request.getName());",
    "        return productRepository.save(product);",
    "    }",
    "",
    "    @CacheEvict(value = \"products\", key = \"#id\")",
    "    public void delete(Long id) {",
    "        productRepository.deleteById(id);",
    "    }",
    "}",
    "```",
    "",
    "### Redis에 저장되는 형태",
    "",
    "```",
    "KEY:   myapp::products::1",
    "VALUE: {\"@class\":\"com.example.demo.domain.Product\",\"id\":1,\"name\":\"노트북\",\"price\":1500000}",
    "TTL:   1800초 (30분)",
    "```",
    "",
    "### Redis CLI로 확인하기",
    "",
    "```bash",
    "# Redis CLI 접속",
    "docker exec -it my-redis redis-cli -a myredispassword",
    "",
    "# 저장된 모든 키 조회",
    "127.0.0.1:6379> KEYS *",
    "1) \"myapp::products::1\"",
    "2) \"myapp::products::2\"",
    "3) \"myapp::users::admin@example.com\"",
    "",
    "# 특정 키의 값 조회",
    "127.0.0.1:6379> GET \"myapp::products::1\"",
    "\"{\\\"@class\\\":\\\"com.example.demo.domain.Product\\\",\\\"id\\\":1,...}\"",
    "",
    "# 특정 키의 남은 TTL 확인 (초)",
    "127.0.0.1:6379> TTL \"myapp::products::1\"",
    "(integer) 1523",
    "",
    "# 특정 키 삭제",
    "127.0.0.1:6379> DEL \"myapp::products::1\"",
    "(integer) 1",
    "",
    "# 패턴으로 키 삭제 (products 캐시 전체)",
    "127.0.0.1:6379> KEYS \"myapp::products::*\"",
    "# 개별 DEL 또는 Lua script 사용",
    "",
    "# 모든 데이터 삭제",
    "127.0.0.1:6379> FLUSHDB",
    "OK",
    "```",
    "",
    "---",
    "",
    "## RedisTemplate 직접 사용하기",
    "",
    "`@Cacheable` 외에도 `RedisTemplate`을 직접 사용해 Redis를 활용할 수 있습니다.",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RedisService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    // String 저장/조회",
    "    public void setString(String key, String value, Duration ttl) {",
    "        redisTemplate.opsForValue().set(key, value, ttl);",
    "    }",
    "",
    "    public String getString(String key) {",
    "        return (String) redisTemplate.opsForValue().get(key);",
    "    }",
    "",
    "    // Hash 저장/조회 (객체의 필드별 저장)",
    "    public void setHash(String key, String field, Object value) {",
    "        redisTemplate.opsForHash().put(key, field, value);",
    "    }",
    "",
    "    public Object getHash(String key, String field) {",
    "        return redisTemplate.opsForHash().get(key, field);",
    "    }",
    "",
    "    // 키 삭제",
    "    public void delete(String key) {",
    "        redisTemplate.delete(key);",
    "    }",
    "",
    "    // TTL 확인",
    "    public Long getTtl(String key) {",
    "        return redisTemplate.getExpire(key);",
    "    }",
    "",
    "    // 키 존재 여부",
    "    public boolean hasKey(String key) {",
    "        return Boolean.TRUE.equals(redisTemplate.hasKey(key));",
    "    }",
    "}",
    "```",
    "",
    "### 실전 활용: API Rate Limiting",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class RateLimitService {",
    "",
    "    private final RedisTemplate<String, Object> redisTemplate;",
    "",
    "    public boolean isAllowed(String clientIp, int maxRequests, Duration window) {",
    "        String key = \"rate:\" + clientIp;",
    "        Long count = redisTemplate.opsForValue().increment(key);",
    "",
    "        if (count == 1) {",
    "            redisTemplate.expire(key, window);",
    "        }",
    "",
    "        return count <= maxRequests;",
    "    }",
    "}",
    "```",
    "",
    "### 실전 활용: 세션 저장소",
    "",
    "```groovy",
    "// build.gradle",
    "implementation 'org.springframework.session:spring-session-data-redis'",
    "```",
    "",
    "```yaml",
    "# application.yml",
    "spring:",
    "  session:",
    "    store-type: redis",
    "    timeout: 1800    # 세션 만료 30분",
    "```",
    "",
    "```java",
    "@Configuration",
    "@EnableRedisHttpSession(maxInactiveIntervalInSeconds = 1800)",
    "public class SessionConfig {",
    "}",
    "```",
    "",
    "> `@EnableRedisHttpSession`을 추가하면 HttpSession이 자동으로 Redis에 저장됩니다. 서버를 여러 대 운영해도 세션이 공유됩니다.",
    "",
    "---",
    "",
    "## Redis 연동 전체 흐름",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"docker compose up -d\"] --> B[\"Redis 컨테이너 실행\<br>(포트 6379)\"]",
    "    B --> C[\"Spring Boot 시작\"]",
    "    C --> D[\"RedisConnectionFactory\<br>(Lettuce 커넥션 풀)\"]",
    "    D --> E[\"RedisCacheManager 생성\"]",
    "    E --> F{\"요청 발생\"}",
    "    F -->|\"@Cacheable\"| G{\"Redis에\<br>캐시 있음?\"}",
    "    G -->|\"HIT\"| H[\"Redis에서 반환\<br>(sub-ms)\"]",
    "    G -->|\"MISS\"| I[\"DB 조회\"]",
    "    I --> J[\"결과를 Redis에 저장\<br>(TTL 설정)\"]",
    "    J --> K[\"결과 반환\"]",
    "    F -->|\"@CacheEvict\"| L[\"Redis에서\<br>해당 키 삭제\"]",
    "    F -->|\"@CachePut\"| M[\"Redis에\<br>새 값으로 갱신\"]",
    "```",
    "",
    "### 인메모리 vs Redis 캐시 선택 기준",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q1{\"서버가 여러 대인가?\"}",
    "    Q1 -->|\"예\"| R[\"Redis (분산 캐시)\"]",
    "    Q1 -->|\"아니오\"| Q2{\"서버 재시작 시\<br>캐시 유지 필요?\"}",
    "    Q2 -->|\"예\"| R",
    "    Q2 -->|\"아니오\"| Q3{\"운영 환경?\"}",
    "    Q3 -->|\"예\"| C[\"Caffeine 또는 Redis\"]",
    "    Q3 -->|\"아니오 (개발/테스트)\"| D[\"ConcurrentMap\"]",
    "```",
    "",
    "---",
    "",
    "## Redis 관리 도구 (GUI)",
    "",
    "Elasticsearch에 **Kibana**가 있듯이, Redis에도 데이터를 시각화하고 관리할 수 있는 웹 UI 도구가 있습니다.",
    "",
    "### RedisInsight (공식 추천)",
    "",
    "Redis Labs에서 공식으로 제공하는 **무료 GUI 도구**입니다.",
    "",
    "| 기능 | 설명 |",
    "|------|------|",
    "| 키 브라우저 | 키 검색, 필터링, CRUD (추가/수정/삭제) |",
    "| 자료구조 시각화 | String, Hash, List, Set, Sorted Set 별 뷰 |",
    "| 내장 CLI | 웹 브라우저에서 Redis 명령어 직접 실행 |",
    "| 슬로우 로그 | 느린 명령어 분석 |",
    "| 메모리 분석 | 키별 메모리 사용량 시각화 |",
    "| 실시간 모니터링 | 메모리, 커넥션 수, 초당 명령 수 대시보드 |",
    "",
    "#### Docker Compose에 RedisInsight 추가",
    "",
    "```yaml",
    "version: '3.8'",
    "",
    "services:",
    "  redis:",
    "    image: redis:7-alpine",
    "    container_name: my-redis",
    "    ports:",
    "      - \"6379:6379\"",
    "    command: redis-server --requirepass myredispassword --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes",
    "    volumes:",
    "      - redis-data:/data",
    "    restart: unless-stopped",
    "",
    "  redisinsight:",
    "    image: redis/redisinsight:latest",
    "    container_name: my-redisinsight",
    "    ports:",
    "      - \"5540:5540\"",
    "    depends_on:",
    "      - redis",
    "    restart: unless-stopped",
    "",
    "volumes:",
    "  redis-data:",
    "```",
    "",
    "```bash",
    "docker compose up -d",
    "```",
    "",
    "`http://localhost:5540` 접속 후 Redis 서버를 등록합니다:",
    "",
    "| 항목 | 값 |",
    "|------|---|",
    "| Host | `redis` (Docker 네트워크 내 서비스명) |",
    "| Port | `6379` |",
    "| Password | `myredispassword` |",
    "",
    "### Redis Commander (경량 대안)",
    "",
    "Node.js 기반의 가벼운 웹 UI입니다. 기능은 RedisInsight보다 적지만 설정이 간단합니다.",
    "",
    "```yaml",
    "  redis-commander:",
    "    image: rediscommander/redis-commander:latest",
    "    container_name: my-redis-commander",
    "    ports:",
    "      - \"8081:8081\"",
    "    environment:",
    "      - REDIS_HOSTS=local:redis:6379:0:myredispassword",
    "    depends_on:",
    "      - redis",
    "    restart: unless-stopped",
    "```",
    "",
    "`http://localhost:8081`에서 접속할 수 있습니다.",
    "",
    "### 도구 비교",
    "",
    "| 항목 | RedisInsight | Redis Commander |",
    "|------|-------------|----------------|",
    "| 제공 | **Redis 공식** | 커뮤니티 |",
    "| 기능 | 풍부 (모니터링, 메모리 분석, 슬로우 로그) | 기본 (키 조회/수정/삭제) |",
    "| UI | 깔끔하고 현대적 | 심플 |",
    "| 리소스 | 상대적으로 무거움 | 가벼움 |",
    "| 접속 포트 | `5540` | `8081` |",
    "| 추천 | **개발 + 운영** | 가볍게 확인용 |",
    "",
    "> 실무에서는 **RedisInsight**를 가장 많이 사용합니다. Kibana처럼 Redis의 전반적인 상태를 직관적으로 확인할 수 있습니다.",
    "",
    "---",
    "",
    "## 캐시 구현체 비교",
    "",
    "| 구현체 | 저장 위치 | TTL | 분산 | 성능 | 추천 |",
    "|--------|----------|-----|------|------|------|",
    "| `ConcurrentMap` | JVM 힙 메모리 | X | X | 빠름 | 개발/테스트 |",
    "| **Caffeine** | JVM 힙 메모리 | **O** | X | **매우 빠름** | **단일 서버 운영** |",
    "| **Redis** | 외부 서버 | **O** | **O** | 빠름 (네트워크) | **다중 서버 운영** |",
    "| EhCache | JVM 힙/디스크 | O | 제한적 | 빠름 | 레거시 |",
    "",
    "---",
    "",
    "## 실전 예제: 전체 CRUD 캐시 적용",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class ProductService {",
    "",
    "    private final ProductRepository productRepository;",
    "",
    "    // 조회: 캐시 있으면 캐시 반환, 없으면 DB 조회 후 캐시 저장",
    "    @Cacheable(value = \"products\", key = \"#id\", unless = \"#result == null\")",
    "    public Product findById(Long id) {",
    "        log.info(\"[CACHE MISS] DB 조회: id={}\", id);",
    "        return productRepository.findById(id).orElse(null);",
    "    }",
    "",
    "    // 목록 조회: 카테고리+페이지 조합 키로 캐싱",
    "    @Cacheable(value = \"productList\",",
    "               key = \"#category + ':page:' + #page\",",
    "               condition = \"#page <= 10\")",
    "    public List<Product> findByCategory(String category, int page) {",
    "        log.info(\"[CACHE MISS] 목록 조회: category={}, page={}\", category, page);",
    "        return productRepository.findByCategory(category, page);",
    "    }",
    "",
    "    // 생성: 목록 캐시 전체 삭제 (목록이 바뀌므로)",
    "    @CacheEvict(value = \"productList\", allEntries = true)",
    "    public Product create(CreateProductRequest request) {",
    "        log.info(\"상품 생성 → productList 캐시 전체 삭제\");",
    "        return productRepository.save(request.toEntity());",
    "    }",
    "",
    "    // 수정: 해당 상품 캐시 갱신 + 목록 캐시 삭제",
    "    @Caching(",
    "        put = @CachePut(value = \"products\", key = \"#id\"),",
    "        evict = @CacheEvict(value = \"productList\", allEntries = true)",
    "    )",
    "    public Product update(Long id, UpdateProductRequest request) {",
    "        log.info(\"상품 수정 → products 캐시 갱신 + productList 캐시 삭제\");",
    "        Product product = productRepository.findById(id).orElseThrow();",
    "        product.setName(request.getName());",
    "        product.setPrice(request.getPrice());",
    "        return productRepository.save(product);",
    "    }",
    "",
    "    // 삭제: 해당 상품 캐시 삭제 + 목록 캐시 삭제",
    "    @Caching(evict = {",
    "        @CacheEvict(value = \"products\", key = \"#id\"),",
    "        @CacheEvict(value = \"productList\", allEntries = true)",
    "    })",
    "    public void delete(Long id) {",
    "        log.info(\"상품 삭제 → products, productList 캐시 삭제\");",
    "        productRepository.deleteById(id);",
    "    }",
    "}",
    "```",
    "",
    "### @Caching (여러 캐시 작업 조합)",
    "",
    "하나의 메서드에서 **여러 캐시**를 동시에 처리할 때 사용합니다.",
    "",
    "```java",
    "@Caching(",
    "    cacheable = @Cacheable(...),",
    "    put = @CachePut(...),",
    "    evict = { @CacheEvict(...), @CacheEvict(...) }",
    ")",
    "```",
    "",
    "---",
    "",
    "## 캐시 동작 흐름 (CRUD)",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as Controller",
    "    participant S as Service",
    "    participant Cache as Cache",
    "    participant DB as DB",
    "",
    "    Note over C,DB: CREATE (캐시 삭제)",
    "    C->>S: create()",
    "    S->>DB: INSERT",
    "    S->>Cache: @CacheEvict (목록 캐시 삭제)",
    "",
    "    Note over C,DB: READ (캐시 조회)",
    "    C->>S: findById(1)",
    "    S->>Cache: 조회 (MISS)",
    "    S->>DB: SELECT",
    "    S->>Cache: 결과 저장",
    "    C->>S: findById(1)",
    "    S->>Cache: 조회 (HIT → 즉시 반환)",
    "",
    "    Note over C,DB: UPDATE (캐시 갱신)",
    "    C->>S: update(1)",
    "    S->>DB: UPDATE",
    "    S->>Cache: @CachePut (새 값으로 갱신)",
    "    S->>Cache: @CacheEvict (목록 캐시 삭제)",
    "",
    "    Note over C,DB: DELETE (캐시 삭제)",
    "    C->>S: delete(1)",
    "    S->>DB: DELETE",
    "    S->>Cache: @CacheEvict (해당 키 + 목록 삭제)",
    "```",
    "",
    "---",
    "",
    "## 캐시 키 커스텀 생성기",
    "",
    "기본 키 생성 방식이 적합하지 않을 때 직접 키 생성 로직을 정의할 수 있습니다.",
    "",
    "```java",
    "@Component",
    "public class CustomKeyGenerator implements KeyGenerator {",
    "",
    "    @Override",
    "    public Object generate(Object target, Method method, Object... params) {",
    "        return target.getClass().getSimpleName() + \":\"",
    "                + method.getName() + \":\"",
    "                + StringUtils.arrayToDelimitedString(params, \":\");",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@Cacheable(value = \"products\", keyGenerator = \"customKeyGenerator\")",
    "public Product findByCondition(String category, int minPrice) { ... }",
    "```",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "### 1. 같은 클래스 내부 호출 시 캐시 미동작",
    "",
    "`@Cacheable`은 Spring AOP 프록시 기반이므로 **같은 클래스 내부 호출**에서는 동작하지 않습니다.",
    "",
    "```java",
    "@Service",
    "public class ProductService {",
    "",
    "    // X: 내부 호출 → 캐시 무시",
    "    public ProductDetail getDetail(Long id) {",
    "        Product product = findById(id);  // 캐시 적용 안 됨!",
    "        return new ProductDetail(product);",
    "    }",
    "",
    "    @Cacheable(value = \"products\", key = \"#id\")",
    "    public Product findById(Long id) { ... }",
    "}",
    "```",
    "",
    "> 해결: 별도 Service로 분리하거나, `self-injection` 패턴을 사용합니다.",
    "",
    "### 2. 캐시 직렬화 (Redis)",
    "",
    "Redis에 객체를 저장하려면 **직렬화 가능**해야 합니다.",
    "",
    "```java",
    "// GenericJackson2JsonRedisSerializer 사용 시",
    "// → JSON으로 직렬화 (기본 생성자 필요)",
    "@Getter @Setter",
    "@NoArgsConstructor  // 필수!",
    "public class Product {",
    "    private Long id;",
    "    private String name;",
    "    private int price;",
    "}",
    "```",
    "",
    "### 3. 캐시 데이터 일관성",
    "",
    "캐시와 DB의 데이터가 불일치할 수 있습니다. TTL을 적절히 설정하고, 데이터 변경 시 반드시 캐시를 무효화하세요.",
    "",
    "### 4. 과도한 캐싱 주의",
    "",
    "```java",
    "// X: 자주 변하는 데이터를 캐싱 → 오래된 데이터 반환",
    "@Cacheable(\"realTimeStock\")",
    "public int getStockCount(Long productId) { ... }",
    "",
    "// O: 변경 빈도가 낮은 데이터를 캐싱",
    "@Cacheable(\"categories\")",
    "public List<Category> getAllCategories() { ... }",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 어노테이션 | 역할 | 메서드 실행 | 캐시 동작 |",
    "|------------|------|-----------|-----------|",
    "| `@Cacheable` | 조회 캐싱 | HIT 시 **실행 안 함** | 결과 저장 |",
    "| `@CacheEvict` | 캐시 삭제 | **항상 실행** | 캐시 제거 |",
    "| `@CachePut` | 캐시 갱신 | **항상 실행** | 결과로 갱신 |",
    "| `@Caching` | 여러 작업 조합 | **항상 실행** | 복합 처리 |",
    "",
    "| CRUD | 캐시 전략 |",
    "|------|----------|",
    "| **Create** | `@CacheEvict(allEntries=true)` 목록 캐시 삭제 |",
    "| **Read** | `@Cacheable` 조회 결과 캐싱 |",
    "| **Update** | `@CachePut` 갱신 또는 `@CacheEvict` 삭제 |",
    "| **Delete** | `@CacheEvict` 해당 키 + 목록 캐시 삭제 |",
    "",
    "| 구현체 | 적합한 경우 |",
    "|--------|-----------|",
    "| ConcurrentMap | 개발/테스트 (TTL 불가) |",
    "| **Caffeine** | 단일 서버 운영 (고성능 인메모리) |",
    "| **Redis** | 다중 서버 운영 (분산 캐시, 세션 공유) |",
    "",
    "| Redis 연동 단계 | 내용 |",
    "|----------------|------|",
    "| Docker Compose | `redis:7-alpine` 이미지로 컨테이너 실행 |",
    "| 의존성 | `spring-boot-starter-data-redis` 추가 |",
    "| application.yml | `host`, `port`, `password`, `lettuce.pool` 설정 |",
    "| RedisConfig | `RedisTemplate` 빈 등록 (직렬화 설정) |",
    "| RedisCacheConfig | `RedisCacheManager` 빈 등록 (TTL, 직렬화) |",
    "| 서비스 코드 | `@Cacheable` 등 어노테이션 그대로 사용 (변경 불필요) |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
