<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-async",
  title: "스프링부트 비동기 처리 완전 정리 - @Async, CompletableFuture, @Scheduled",
  date: "2026-02-22",
  summary: "Spring Boot에서 비동기 처리를 구현하는 방법을 정리합니다. @Async로 비동기 메서드 실행, CompletableFuture로 비동기 결과 조합, @Scheduled로 스케줄링까지 스레드 풀 설정과 실전 예제로 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","async","completablefuture","scheduled","thread","backend"],
  content: [
    "## 비동기 처리가 필요한 이유",
    "",
    "웹 애플리케이션에서 **시간이 오래 걸리는 작업**(이메일 발송, 외부 API 호출, 대용량 처리 등)을 동기적으로 실행하면 사용자는 **응답을 받을 때까지 대기**해야 합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant S as 서버",
    "",
    "    Note over C,S: 동기 처리 (문제)",
    "    C->>S: POST /api/orders",
    "    S->>S: 주문 저장 (50ms)",
    "    S->>S: 이메일 발송 (3000ms) ⏳",
    "    S->>S: 알림 전송 (2000ms) ⏳",
    "    S-->>C: 200 OK (총 5050ms 대기!)",
    "",
    "    Note over C,S: 비동기 처리 (해결)",
    "    C->>S: POST /api/orders",
    "    S->>S: 주문 저장 (50ms)",
    "    S-->>C: 200 OK (50ms 만에 응답!)",
    "    S->>S: 이메일 발송 (별도 스레드) 🔄",
    "    S->>S: 알림 전송 (별도 스레드) 🔄",
    "```",
    "",
    "---",
    "",
    "# 0. 인텔리제이 프로젝트 만들기 (실습 환경 구성)",
    "",
    "이론을 먼저 보기보다 **직접 프로젝트를 만들어서 실행**해보면 훨씬 빨리 이해됩니다. 아래 과정대로 따라하면 이 글의 모든 예제를 바로 돌려볼 수 있습니다.",
    "",
    "## Step 1: Spring Initializr로 프로젝트 생성",
    "",
    "IntelliJ IDEA에서 **File → New → Project** 를 선택합니다.",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | `springboot_async_example` |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **Group** | `com.example` |",
    "| **Artifact** | `springboot_async_example` |",
    "| **JDK** | 21 |",
    "| **Java** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "**Dependencies** (Spring Initializr 화면에서 추가):",
    "",
    "| 의존성 | 설명 |",
    "|--------|------|",
    "| **Spring Web** | REST API 구성 |",
    "| **Lombok** | 보일러플레이트 코드 제거 |",
    "",
    "> Spring Initializr에서 위 두 개만 추가하면 됩니다. @Async, @Scheduled는 `spring-boot-starter`에 이미 포함되어 있습니다.",
    "",
    "## Step 2: build.gradle 확인",
    "",
    "프로젝트가 생성되면 `build.gradle`이 아래처럼 구성되어 있는지 확인합니다.",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "## Step 3: 프로젝트 구조",
    "",
    "아래 패키지 구조로 파일들을 생성합니다.",
    "",
    "```",
    "src/main/java/com/example/springboot_async_example/",
    "├── SpringbootAsyncExampleApplication.java   ← @EnableAsync, @EnableScheduling",
    "├── config/",
    "│   └── AsyncConfig.java                     ← 스레드 풀 설정",
    "├── service/",
    "│   └── EmailService.java                    ← @Async 비동기 메서드",
    "├── controller/",
    "│   └── NotificationController.java          ← REST API (동기 vs 비동기 비교)",
    "└── scheduler/",
    "    └── ScheduledTask.java                   ← @Scheduled 예제",
    "",
    "src/main/resources/",
    "└── application.yml                          ← 서버/스케줄링 설정",
    "```",
    "",
    "## Step 4: 전체 코드 작성",
    "",
    "### 4-1. SpringbootAsyncExampleApplication.java (메인 클래스)",
    "",
    "```java",
    "package com.example.springboot_async_example;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "import org.springframework.scheduling.annotation.EnableAsync;",
    "import org.springframework.scheduling.annotation.EnableScheduling;",
    "",
    "@SpringBootApplication",
    "@EnableAsync",
    "@EnableScheduling",
    "public class SpringbootAsyncExampleApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(SpringbootAsyncExampleApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "> `@EnableAsync`와 `@EnableScheduling`을 메인 클래스에 함께 선언합니다. 이 두 어노테이션이 없으면 `@Async`와 `@Scheduled`가 동작하지 않습니다.",
    "",
    "### 4-2. AsyncConfig.java (스레드 풀 설정)",
    "",
    "```java",
    "package com.example.springboot_async_example.config;",
    "",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;",
    "",
    "import java.util.concurrent.Executor;",
    "import java.util.concurrent.ThreadPoolExecutor;",
    "",
    "@Configuration",
    "public class AsyncConfig {",
    "",
    "    @Bean(name = \"taskExecutor\")",
    "    public Executor taskExecutor() {",
    "        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();",
    "        executor.setCorePoolSize(5);",
    "        executor.setMaxPoolSize(10);",
    "        executor.setQueueCapacity(50);",
    "        executor.setThreadNamePrefix(\"Async-\");",
    "        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());",
    "        executor.initialize();",
    "        return executor;",
    "    }",
    "}",
    "```",
    "",
    "> 기본 `SimpleAsyncTaskExecutor`는 **매번 새 스레드를 생성**하여 위험합니다. 반드시 `ThreadPoolTaskExecutor`로 풀을 관리하세요.",
    "",
    "### 4-3. EmailService.java (@Async 비동기 서비스)",
    "",
    "```java",
    "package com.example.springboot_async_example.service;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.scheduling.annotation.Async;",
    "import org.springframework.stereotype.Service;",
    "",
    "import java.util.concurrent.CompletableFuture;",
    "",
    "@Slf4j",
    "@Service",
    "public class EmailService {",
    "",
    "    // fire-and-forget: 결과를 기다리지 않는 비동기 메서드",
    "    @Async(\"taskExecutor\")",
    "    public void sendEmail(String to) {",
    "        log.info(\"[{}] 이메일 발송 시작 → {}\",",
    "                Thread.currentThread().getName(), to);",
    "        try {",
    "            Thread.sleep(3000); // 3초 걸리는 작업 시뮬레이션",
    "        } catch (InterruptedException e) {",
    "            Thread.currentThread().interrupt();",
    "        }",
    "        log.info(\"[{}] 이메일 발송 완료 → {}\",",
    "                Thread.currentThread().getName(), to);",
    "    }",
    "",
    "    // 결과 반환: CompletableFuture로 비동기 결과를 받을 수 있음",
    "    @Async(\"taskExecutor\")",
    "    public CompletableFuture<String> sendEmailWithResult(String to) {",
    "        log.info(\"[{}] 이메일(결과반환) 발송 시작 → {}\",",
    "                Thread.currentThread().getName(), to);",
    "        try {",
    "            Thread.sleep(3000);",
    "        } catch (InterruptedException e) {",
    "            Thread.currentThread().interrupt();",
    "            return CompletableFuture.completedFuture(\"FAIL\");",
    "        }",
    "        log.info(\"[{}] 이메일(결과반환) 발송 완료 → {}\",",
    "                Thread.currentThread().getName(), to);",
    "        return CompletableFuture.completedFuture(\"SUCCESS: \" + to);",
    "    }",
    "}",
    "```",
    "",
    "> `sendEmail`은 void 반환(fire-and-forget), `sendEmailWithResult`는 `CompletableFuture<String>` 반환으로 두 가지 패턴을 모두 보여줍니다.",
    "",
    "### 4-4. NotificationController.java (동기 vs 비동기 비교 API)",
    "",
    "```java",
    "package com.example.springboot_async_example.controller;",
    "",
    "import com.example.springboot_async_example.service.EmailService;",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.annotation.PostMapping;",
    "import org.springframework.web.bind.annotation.RequestMapping;",
    "import org.springframework.web.bind.annotation.RequestParam;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "import java.util.Map;",
    "import java.util.concurrent.CompletableFuture;",
    "",
    "@Slf4j",
    "@RestController",
    "@RequestMapping(\"/api/notify\")",
    "@RequiredArgsConstructor",
    "public class NotificationController {",
    "",
    "    private final EmailService emailService;",
    "",
    "    // 동기 방식: 이메일 발송이 끝날 때까지 3초 대기 후 응답",
    "    @PostMapping(\"/sync\")",
    "    public ResponseEntity<Map<String, String>> sendSync(",
    "            @RequestParam String email) {",
    "",
    "        log.info(\"[{}] /sync 요청 수신\", Thread.currentThread().getName());",
    "        long start = System.currentTimeMillis();",
    "",
    "        // 동기 호출 (3초 블로킹)",
    "        try {",
    "            Thread.sleep(3000);",
    "        } catch (InterruptedException e) {",
    "            Thread.currentThread().interrupt();",
    "        }",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        log.info(\"[{}] /sync 응답 반환 ({}ms)\", Thread.currentThread().getName(), elapsed);",
    "",
    "        return ResponseEntity.ok(Map.of(",
    "                \"mode\", \"SYNC\",",
    "                \"email\", email,",
    "                \"elapsed\", elapsed + \"ms\"",
    "        ));",
    "    }",
    "",
    "    // 비동기 방식 (fire-and-forget): 즉시 응답, 이메일은 백그라운드 처리",
    "    @PostMapping(\"/async\")",
    "    public ResponseEntity<Map<String, String>> sendAsync(",
    "            @RequestParam String email) {",
    "",
    "        log.info(\"[{}] /async 요청 수신\", Thread.currentThread().getName());",
    "        long start = System.currentTimeMillis();",
    "",
    "        emailService.sendEmail(email); // 즉시 반환됨",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        log.info(\"[{}] /async 응답 반환 ({}ms)\", Thread.currentThread().getName(), elapsed);",
    "",
    "        return ResponseEntity.ok(Map.of(",
    "                \"mode\", \"ASYNC (fire-and-forget)\",",
    "                \"email\", email,",
    "                \"elapsed\", elapsed + \"ms\",",
    "                \"note\", \"이메일은 백그라운드에서 발송 중\"",
    "        ));",
    "    }",
    "",
    "    // 비동기 방식 (CompletableFuture): 비동기 실행 후 결과를 기다려서 응답",
    "    @PostMapping(\"/async-result\")",
    "    public ResponseEntity<Map<String, String>> sendAsyncWithResult(",
    "            @RequestParam String email) throws Exception {",
    "",
    "        log.info(\"[{}] /async-result 요청 수신\", Thread.currentThread().getName());",
    "        long start = System.currentTimeMillis();",
    "",
    "        CompletableFuture<String> future = emailService.sendEmailWithResult(email);",
    "        String result = future.get(); // 비동기 작업 완료까지 대기",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        log.info(\"[{}] /async-result 응답 반환 ({}ms)\", Thread.currentThread().getName(), elapsed);",
    "",
    "        return ResponseEntity.ok(Map.of(",
    "                \"mode\", \"ASYNC (CompletableFuture)\",",
    "                \"result\", result,",
    "                \"elapsed\", elapsed + \"ms\"",
    "        ));",
    "    }",
    "}",
    "```",
    "",
    "> 3개의 엔드포인트로 **동기 / 비동기(fire-and-forget) / 비동기(결과 대기)** 세 가지 패턴을 직접 비교할 수 있습니다.",
    "",
    "### 4-5. ScheduledTask.java (@Scheduled 스케줄링 예제)",
    "",
    "```java",
    "package com.example.springboot_async_example.scheduler;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.scheduling.annotation.Scheduled;",
    "import org.springframework.stereotype.Component;",
    "",
    "import java.time.LocalDateTime;",
    "",
    "@Slf4j",
    "@Component",
    "public class ScheduledTask {",
    "",
    "    // fixedRate: 이전 시작 시점 기준 10초마다 실행",
    "    @Scheduled(fixedRate = 10000)",
    "    public void fixedRateTask() {",
    "        log.info(\"[{}] [fixedRate] 실행: {}\",",
    "                Thread.currentThread().getName(),",
    "                LocalDateTime.now());",
    "    }",
    "",
    "    // cron: 매분 0초에 실행 (테스트용)",
    "    @Scheduled(cron = \"0 * * * * *\")",
    "    public void cronTask() {",
    "        log.info(\"[{}] [cron 매분] 실행: {}\",",
    "                Thread.currentThread().getName(),",
    "                LocalDateTime.now());",
    "    }",
    "}",
    "```",
    "",
    "> `fixedRate = 10000`은 10초마다 실행, `cron = \"0 * * * * *\"`은 매분 정각에 실행됩니다. 서버 시작 후 콘솔에서 로그가 찍히는 것을 확인하세요.",
    "",
    "### 4-6. application.yml",
    "",
    "```yaml",
    "server:",
    "  port: 8080",
    "",
    "spring:",
    "  application:",
    "    name: springboot-async-example",
    "  task:",
    "    scheduling:",
    "      pool:",
    "        size: 3",
    "      thread-name-prefix: Schedule-",
    "",
    "logging:",
    "  level:",
    "    com.example: DEBUG",
    "```",
    "",
    "> `spring.task.scheduling.pool.size`를 3으로 설정하여 여러 스케줄 작업이 동시에 실행될 수 있게 합니다.",
    "",
    "---",
    "",
    "## Step 5: Postman으로 테스트",
    "",
    "서버를 시작한 후 아래 3개 요청을 순서대로 보내봅니다.",
    "",
    "### 테스트 1: 동기 방식 (`POST /api/notify/sync`)",
    "",
    "```",
    "POST http://localhost:8080/api/notify/sync?email=test@example.com",
    "```",
    "",
    "**응답 (약 3초 후):**",
    "",
    "```json",
    "{",
    "    \"mode\": \"SYNC\",",
    "    \"email\": \"test@example.com\",",
    "    \"elapsed\": \"3005ms\"",
    "}",
    "```",
    "",
    "> 3초 동안 응답이 오지 않다가 한 번에 옵니다.",
    "",
    "### 테스트 2: 비동기 fire-and-forget (`POST /api/notify/async`)",
    "",
    "```",
    "POST http://localhost:8080/api/notify/async?email=test@example.com",
    "```",
    "",
    "**응답 (즉시!):**",
    "",
    "```json",
    "{",
    "    \"mode\": \"ASYNC (fire-and-forget)\",",
    "    \"email\": \"test@example.com\",",
    "    \"elapsed\": \"5ms\",",
    "    \"note\": \"이메일은 백그라운드에서 발송 중\"",
    "}",
    "```",
    "",
    "> 5ms 만에 응답이 돌아옵니다! 이메일은 백그라운드에서 처리됩니다.",
    "",
    "### 테스트 3: 비동기 + 결과 대기 (`POST /api/notify/async-result`)",
    "",
    "```",
    "POST http://localhost:8080/api/notify/async-result?email=test@example.com",
    "```",
    "",
    "**응답 (약 3초 후):**",
    "",
    "```json",
    "{",
    "    \"mode\": \"ASYNC (CompletableFuture)\",",
    "    \"result\": \"SUCCESS: test@example.com\",",
    "    \"elapsed\": \"3008ms\"",
    "}",
    "```",
    "",
    "> 비동기로 실행되지만 `future.get()`으로 결과를 기다리므로, 응답 시간은 동기와 비슷합니다. 하지만 **실행 스레드가 다릅니다**.",
    "",
    "### 콘솔 로그 확인 (핵심!)",
    "",
    "세 요청을 보낸 후 IntelliJ 콘솔을 확인하면:",
    "",
    "```",
    "// 동기",
    "[http-nio-8080-exec-1] NotificationController : [http-nio-8080-exec-1] /sync 요청 수신",
    "[http-nio-8080-exec-1] NotificationController : [http-nio-8080-exec-1] /sync 응답 반환 (3005ms)",
    "",
    "// 비동기 fire-and-forget",
    "[http-nio-8080-exec-2] NotificationController : [http-nio-8080-exec-2] /async 요청 수신",
    "[http-nio-8080-exec-2] NotificationController : [http-nio-8080-exec-2] /async 응답 반환 (5ms)     ← 즉시 응답!",
    "[Async-1]              EmailService           : [Async-1] 이메일 발송 시작 → test@example.com      ← 다른 스레드!",
    "[Async-1]              EmailService           : [Async-1] 이메일 발송 완료 → test@example.com      ← 3초 후",
    "",
    "// 비동기 + 결과 대기",
    "[http-nio-8080-exec-3] NotificationController : [http-nio-8080-exec-3] /async-result 요청 수신",
    "[Async-2]              EmailService           : [Async-2] 이메일(결과반환) 발송 시작 → test@example.com",
    "[Async-2]              EmailService           : [Async-2] 이메일(결과반환) 발송 완료 → test@example.com",
    "[http-nio-8080-exec-3] NotificationController : [http-nio-8080-exec-3] /async-result 응답 반환 (3008ms)",
    "```",
    "",
    "**핵심 포인트:**",
    "",
    "- **동기**: `http-nio-8080-exec-1` 스레드 하나에서 모든 것을 처리 → 3초 블로킹",
    "- **비동기(fire-and-forget)**: 컨트롤러는 `http-nio-8080-exec-2`에서 즉시 응답, 이메일은 `Async-1`에서 별도 처리",
    "- **비동기(결과 대기)**: 이메일은 `Async-2`에서 실행되지만, `future.get()`으로 결과를 기다림",
    "",
    "### @Scheduled 콘솔 로그",
    "",
    "서버가 실행 중이면 10초마다, 매분마다 아래 로그가 자동으로 찍힙니다:",
    "",
    "```",
    "[Schedule-1] ScheduledTask : [Schedule-1] [fixedRate] 실행: 2026-03-09T14:00:10.001",
    "[Schedule-1] ScheduledTask : [Schedule-1] [fixedRate] 실행: 2026-03-09T14:00:20.002",
    "[Schedule-2] ScheduledTask : [Schedule-2] [cron 매분] 실행: 2026-03-09T14:01:00.000",
    "[Schedule-1] ScheduledTask : [Schedule-1] [fixedRate] 실행: 2026-03-09T14:00:30.001",
    "```",
    "",
    "> 스레드 이름이 `Schedule-`로 시작하는 것은 `application.yml`에서 설정한 `thread-name-prefix` 때문입니다.",
    "",
    "---",
    "",
    "이제 프로젝트 환경이 준비되었습니다. 아래부터는 각 기능의 **동작 원리와 심화 내용**을 상세히 다룹니다.",
    "",
    "---",
    "",
    "# 1. @Async (비동기 메서드 실행)",
    "",
    "## 개념",
    "",
    "`@Async`는 메서드를 **별도의 스레드**에서 비동기적으로 실행하게 하는 어노테이션입니다. 호출자는 결과를 기다리지 않고 즉시 다음 코드를 실행합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Controller<br/>(메인 스레드)\"] -->|\"호출 즉시 반환\"| B[\"@Async 메서드<br/>(별도 스레드에서 실행)\"]",
    "    A --> C[\"응답 반환<br/>(대기 없음)\"]",
    "```",
    "",
    "## 설정",
    "",
    "### @EnableAsync 활성화",
    "",
    "```java",
    "@SpringBootApplication",
    "@EnableAsync",
    "public class DemoApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "> `@EnableAsync`가 없으면 `@Async`를 붙여도 동기적으로 실행됩니다.",
    "",
    "### 스레드 풀 설정 (권장)",
    "",
    "기본 스레드 풀(`SimpleAsyncTaskExecutor`)은 **매 요청마다 새 스레드를 생성**하여 위험합니다. 반드시 커스텀 스레드 풀을 설정하세요.",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "import org.springframework.scheduling.annotation.EnableAsync;",
    "import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;",
    "",
    "import java.util.concurrent.Executor;",
    "",
    "@Configuration",
    "@EnableAsync",
    "public class AsyncConfig {",
    "",
    "    @Bean(name = \"taskExecutor\")",
    "    public Executor taskExecutor() {",
    "        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();",
    "        executor.setCorePoolSize(5);       // 기본 스레드 수",
    "        executor.setMaxPoolSize(10);       // 최대 스레드 수",
    "        executor.setQueueCapacity(50);     // 대기 큐 크기",
    "        executor.setThreadNamePrefix(\"Async-\");",
    "        executor.setRejectedExecutionHandler(",
    "                new java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy());",
    "        executor.initialize();",
    "        return executor;",
    "    }",
    "",
    "    @Bean(name = \"emailExecutor\")",
    "    public Executor emailExecutor() {",
    "        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();",
    "        executor.setCorePoolSize(2);",
    "        executor.setMaxPoolSize(5);",
    "        executor.setQueueCapacity(100);",
    "        executor.setThreadNamePrefix(\"Email-\");",
    "        executor.initialize();",
    "        return executor;",
    "    }",
    "}",
    "```",
    "",
    "### 스레드 풀 설정 상세",
    "",
    "| 설정 | 설명 | 권장값 |",
    "|------|------|--------|",
    "| `corePoolSize` | 기본으로 유지되는 스레드 수 | CPU 코어 수 기반 |",
    "| `maxPoolSize` | 최대 스레드 수 | core의 1.5~2배 |",
    "| `queueCapacity` | 스레드가 모두 사용 중일 때 대기 큐 크기 | 작업 특성에 따라 |",
    "| `threadNamePrefix` | 스레드 이름 접두사 (로그 추적용) | 의미 있는 이름 |",
    "| `rejectedExecutionHandler` | 큐도 가득 찼을 때 정책 | CallerRunsPolicy |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"비동기 작업 요청\"] --> B{\"core 스레드<br/>여유 있음?\"}",
    "    B -->|예| C[\"core 스레드에서 실행\"]",
    "    B -->|아니오| D{\"큐에<br/>여유 있음?\"}",
    "    D -->|예| E[\"큐에 대기\"]",
    "    D -->|아니오| F{\"max 스레드<br/>여유 있음?\"}",
    "    F -->|예| G[\"추가 스레드 생성 후 실행\"]",
    "    F -->|아니오| H[\"RejectedExecutionHandler<br/>CallerRunsPolicy: 호출 스레드에서 실행\"]",
    "```",
    "",
    "---",
    "",
    "## 실전 예제 1: 이메일 발송 (fire-and-forget)",
    "",
    "결과를 기다리지 않는 **fire-and-forget** 패턴입니다.",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.scheduling.annotation.Async;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Slf4j",
    "@Service",
    "public class EmailService {",
    "",
    "    @Async(\"emailExecutor\")",
    "    public void sendWelcomeEmail(String to, String username) {",
    "        log.info(\"[{}] 이메일 발송 시작: {}\",",
    "                Thread.currentThread().getName(), to);",
    "",
    "        try {",
    "            // 이메일 발송 로직 (3초 소요 가정)",
    "            Thread.sleep(3000);",
    "            log.info(\"이메일 발송 완료: {}\", to);",
    "        } catch (InterruptedException e) {",
    "            Thread.currentThread().interrupt();",
    "            log.error(\"이메일 발송 실패: {}\", to, e);",
    "        }",
    "    }",
    "",
    "    @Async(\"emailExecutor\")",
    "    public void sendOrderConfirmation(String to, Long orderId) {",
    "        log.info(\"주문 확인 메일 발송: {} (주문: {})\", to, orderId);",
    "        // 이메일 발송 로직...",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@RestController",
    "@RequestMapping(\"/api/orders\")",
    "@RequiredArgsConstructor",
    "public class OrderController {",
    "",
    "    private final OrderService orderService;",
    "    private final EmailService emailService;",
    "",
    "    @PostMapping",
    "    public ResponseEntity<OrderResponse> createOrder(",
    "            @Valid @RequestBody CreateOrderRequest request) {",
    "",
    "        // 1. 주문 저장 (동기)",
    "        OrderResponse order = orderService.create(request);",
    "",
    "        // 2. 이메일 발송 (비동기 - 즉시 반환)",
    "        emailService.sendOrderConfirmation(request.getEmail(), order.getId());",
    "",
    "        // 3. 이메일 완료를 기다리지 않고 바로 응답",
    "        return ResponseEntity.status(HttpStatus.CREATED).body(order);",
    "    }",
    "}",
    "```",
    "",
    "**로그 출력:**",
    "",
    "```",
    "[http-nio-8080-exec-1] OrderController  : 주문 생성 완료: #1001",
    "[http-nio-8080-exec-1] OrderController  : 응답 반환 (50ms)",
    "[Email-1]               EmailService    : 주문 확인 메일 발송: hong@example.com (주문: 1001)",
    "[Email-1]               EmailService    : 이메일 발송 완료 (3초 후)",
    "```",
    "",
    "> 메인 스레드(`http-nio-..`)는 즉시 응답하고, 이메일은 `Email-1` 스레드에서 별도로 처리됩니다.",
    "",
    "---",
    "",
    "## 실전 예제 2: 비동기 + 결과 반환 (CompletableFuture)",
    "",
    "비동기 작업의 **결과를 받아야** 할 때는 `CompletableFuture`를 반환합니다.",
    "",
    "```java",
    "@Service",
    "@Slf4j",
    "public class ExternalApiService {",
    "",
    "    @Async(\"taskExecutor\")",
    "    public CompletableFuture<UserProfile> fetchUserProfile(String userId) {",
    "        log.info(\"[{}] 프로필 조회 시작\", Thread.currentThread().getName());",
    "        // 외부 API 호출 (2초 소요)",
    "        UserProfile profile = restTemplate.getForObject(",
    "                \"https://api.example.com/users/\" + userId, UserProfile.class);",
    "        return CompletableFuture.completedFuture(profile);",
    "    }",
    "",
    "    @Async(\"taskExecutor\")",
    "    public CompletableFuture<List<Order>> fetchOrderHistory(String userId) {",
    "        log.info(\"[{}] 주문 내역 조회 시작\", Thread.currentThread().getName());",
    "        // 외부 API 호출 (3초 소요)",
    "        List<Order> orders = restTemplate.getForObject(",
    "                \"https://api.example.com/orders?userId=\" + userId,",
    "                new ParameterizedTypeReference<>() {});",
    "        return CompletableFuture.completedFuture(orders);",
    "    }",
    "",
    "    @Async(\"taskExecutor\")",
    "    public CompletableFuture<Integer> fetchPoint(String userId) {",
    "        log.info(\"[{}] 포인트 조회 시작\", Thread.currentThread().getName());",
    "        // 외부 API 호출 (1초 소요)",
    "        Integer point = restTemplate.getForObject(",
    "                \"https://api.example.com/points/\" + userId, Integer.class);",
    "        return CompletableFuture.completedFuture(point);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "# 2. CompletableFuture (비동기 결과 조합)",
    "",
    "## 개념",
    "",
    "`CompletableFuture`는 Java 8에서 도입된 **비동기 작업의 결과**를 다루는 클래스입니다. 여러 비동기 작업을 **병렬 실행**하고, 결과를 **조합/변환/체이닝**할 수 있습니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"시작\"] --> B[\"프로필 조회\"]",
    "    A --> C[\"주문 내역 조회\"]",
    "    A --> D[\"포인트 조회\"]",
    "    B --> E[\"allOf - 모두 완료 대기\"]",
    "    C --> E",
    "    D --> E",
    "    E --> F[\"결과 조합하여 응답\"]",
    "```",
    "",
    "### 동기 vs 비동기 실행 시간 비교",
    "",
    "| 방식 | 프로필(2초) | 주문(3초) | 포인트(1초) | **총 시간** |",
    "|------|-----------|----------|-----------|------------|",
    "| 동기(순차) | → | → | → | **6초** |",
    "| 비동기(병렬) | ↓ | ↓ | ↓ | **3초** (가장 긴 작업 기준) |",
    "",
    "---",
    "",
    "## 실전 예제: 여러 API를 병렬 호출 후 조합",
    "",
    "```java",
    "@RestController",
    "@RequestMapping(\"/api/dashboard\")",
    "@RequiredArgsConstructor",
    "public class DashboardController {",
    "",
    "    private final ExternalApiService apiService;",
    "",
    "    @GetMapping(\"/{userId}\")",
    "    public ResponseEntity<DashboardResponse> getDashboard(",
    "            @PathVariable String userId) throws Exception {",
    "",
    "        long start = System.currentTimeMillis();",
    "",
    "        // 3개의 비동기 작업을 동시에 시작",
    "        CompletableFuture<UserProfile> profileFuture =",
    "                apiService.fetchUserProfile(userId);",
    "        CompletableFuture<List<Order>> ordersFuture =",
    "                apiService.fetchOrderHistory(userId);",
    "        CompletableFuture<Integer> pointFuture =",
    "                apiService.fetchPoint(userId);",
    "",
    "        // 모든 작업이 완료될 때까지 대기",
    "        CompletableFuture.allOf(profileFuture, ordersFuture, pointFuture).join();",
    "",
    "        // 결과 조합",
    "        DashboardResponse response = DashboardResponse.builder()",
    "                .profile(profileFuture.get())",
    "                .orders(ordersFuture.get())",
    "                .point(pointFuture.get())",
    "                .build();",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        log.info(\"대시보드 조회 완료: {}ms (동기였다면 6초)\", elapsed);",
    "",
    "        return ResponseEntity.ok(response);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## CompletableFuture 핵심 메서드",
    "",
    "### 생성",
    "",
    "```java",
    "// 즉시 완료된 Future",
    "CompletableFuture.completedFuture(\"결과\");",
    "",
    "// 별도 스레드에서 실행 (Executor 지정 가능)",
    "CompletableFuture.supplyAsync(() -> {",
    "    return fetchData();  // 값 반환",
    "});",
    "",
    "CompletableFuture.runAsync(() -> {",
    "    sendEmail();  // 반환값 없음",
    "});",
    "```",
    "",
    "### 변환 / 체이닝",
    "",
    "```java",
    "CompletableFuture<String> future = CompletableFuture",
    "        .supplyAsync(() -> getUserName(userId))",
    "        .thenApply(name -> name.toUpperCase())             // 결과 변환",
    "        .thenApply(name -> \"Hello, \" + name + \"!\");       // 추가 변환",
    "",
    "// 비동기 체이닝 (다음 작업도 비동기)",
    "CompletableFuture<OrderResponse> future = CompletableFuture",
    "        .supplyAsync(() -> getUser(userId))",
    "        .thenCompose(user -> getOrders(user.getId()));     // 비동기 체이닝",
    "```",
    "",
    "### 조합",
    "",
    "```java",
    "// 두 작업 결과를 조합",
    "CompletableFuture<String> combined = profileFuture",
    "        .thenCombine(pointFuture, (profile, point) ->",
    "                profile.getName() + \"님의 포인트: \" + point);",
    "",
    "// 모든 작업 완료 대기",
    "CompletableFuture.allOf(future1, future2, future3).join();",
    "",
    "// 가장 빨리 끝나는 작업의 결과 사용",
    "CompletableFuture.anyOf(future1, future2, future3);",
    "```",
    "",
    "### 에러 처리",
    "",
    "```java",
    "CompletableFuture<UserProfile> future = CompletableFuture",
    "        .supplyAsync(() -> fetchUserProfile(userId))",
    "        .exceptionally(ex -> {",
    "            log.error(\"프로필 조회 실패\", ex);",
    "            return UserProfile.defaultProfile(); // 기본값 반환",
    "        });",
    "",
    "// 성공/실패 모두 처리",
    "CompletableFuture<UserProfile> future = CompletableFuture",
    "        .supplyAsync(() -> fetchUserProfile(userId))",
    "        .handle((result, ex) -> {",
    "            if (ex != null) {",
    "                log.error(\"실패\", ex);",
    "                return UserProfile.defaultProfile();",
    "            }",
    "            return result;",
    "        });",
    "```",
    "",
    "### 타임아웃",
    "",
    "```java",
    "// Java 9+: 5초 내에 완료되지 않으면 기본값",
    "CompletableFuture<UserProfile> future = CompletableFuture",
    "        .supplyAsync(() -> fetchUserProfile(userId))",
    "        .completeOnTimeout(UserProfile.defaultProfile(), 5, TimeUnit.SECONDS);",
    "",
    "// Java 9+: 5초 내에 완료되지 않으면 예외",
    "CompletableFuture<UserProfile> future = CompletableFuture",
    "        .supplyAsync(() -> fetchUserProfile(userId))",
    "        .orTimeout(5, TimeUnit.SECONDS);",
    "```",
    "",
    "### 메서드 정리표",
    "",
    "| 메서드 | 역할 | 반환 |",
    "|--------|------|------|",
    "| `supplyAsync(Supplier)` | 비동기 실행 (값 반환) | `CompletableFuture<T>` |",
    "| `runAsync(Runnable)` | 비동기 실행 (반환 없음) | `CompletableFuture<Void>` |",
    "| `thenApply(Function)` | 결과 변환 | `CompletableFuture<U>` |",
    "| `thenCompose(Function)` | 비동기 체이닝 | `CompletableFuture<U>` |",
    "| `thenCombine(Future, BiFunction)` | 두 결과 조합 | `CompletableFuture<V>` |",
    "| `allOf(Future...)` | 모든 작업 완료 대기 | `CompletableFuture<Void>` |",
    "| `anyOf(Future...)` | 가장 빠른 작업 결과 | `CompletableFuture<Object>` |",
    "| `exceptionally(Function)` | 에러 시 기본값 | `CompletableFuture<T>` |",
    "| `handle(BiFunction)` | 성공/실패 모두 처리 | `CompletableFuture<U>` |",
    "| `completeOnTimeout(T, long, TimeUnit)` | 타임아웃 시 기본값 | `CompletableFuture<T>` |",
    "| `orTimeout(long, TimeUnit)` | 타임아웃 시 예외 | `CompletableFuture<T>` |",
    "| `join()` | 결과 대기 (unchecked 예외) | `T` |",
    "| `get()` | 결과 대기 (checked 예외) | `T` |",
    "",
    "---",
    "",
    "## @Async vs CompletableFuture.supplyAsync",
    "",
    "| 비교 | `@Async` | `CompletableFuture.supplyAsync()` |",
    "|------|---------|----------------------------------|",
    "| 스레드 관리 | Spring이 관리 (Bean 설정) | 직접 Executor 전달 |",
    "| 트랜잭션 | 별도 트랜잭션 | 호출자 트랜잭션 상속 불가 |",
    "| AOP | Spring 프록시 기반 | 일반 Java 코드 |",
    "| 유연성 | 단순 비동기 | **체이닝, 조합, 에러 처리** 유연 |",
    "| 추천 | Service 메서드 비동기 실행 | 복잡한 비동기 로직 조합 |",
    "",
    "---",
    "",
    "# 3. @Scheduled (스케줄링)",
    "",
    "## 개념",
    "",
    "`@Scheduled`는 메서드를 **정해진 시간/주기**에 자동으로 실행하는 어노테이션입니다. 배치 작업, 캐시 갱신, 상태 모니터링 등에 사용합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Spring Scheduler\"] -->|\"매 5분마다\"| B[\"캐시 갱신\"]",
    "    A -->|\"매일 자정\"| C[\"만료 데이터 삭제\"]",
    "    A -->|\"매 시간\"| D[\"외부 데이터 동기화\"]",
    "    A -->|\"매 30초\"| E[\"헬스 체크\"]",
    "```",
    "",
    "## 설정",
    "",
    "### @EnableScheduling 활성화",
    "",
    "```java",
    "@SpringBootApplication",
    "@EnableScheduling",
    "public class DemoApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### 스케줄링 스레드 풀 설정",
    "",
    "기본은 **단일 스레드**입니다. 여러 스케줄 작업이 있으면 스레드 풀을 설정하세요.",
    "",
    "```yaml",
    "spring:",
    "  task:",
    "    scheduling:",
    "      pool:",
    "        size: 5  # 스케줄링 스레드 수",
    "      thread-name-prefix: Scheduler-",
    "```",
    "",
    "또는 Java 설정으로:",
    "",
    "```java",
    "@Configuration",
    "@EnableScheduling",
    "public class SchedulerConfig implements SchedulingConfigurer {",
    "",
    "    @Override",
    "    public void configureTasks(ScheduledTaskRegistrar registrar) {",
    "        ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();",
    "        scheduler.setPoolSize(5);",
    "        scheduler.setThreadNamePrefix(\"Scheduler-\");",
    "        scheduler.setErrorHandler(t ->",
    "            log.error(\"스케줄 작업 에러\", t));",
    "        scheduler.initialize();",
    "        registrar.setTaskScheduler(scheduler);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 스케줄링 방법 3가지",
    "",
    "### fixedRate - 고정 간격 (시작 기준)",
    "",
    "이전 작업 **시작 시점**부터 지정 시간 후 다시 실행합니다.",
    "",
    "```java",
    "@Scheduled(fixedRate = 5000)  // 5초마다",
    "public void checkSystemStatus() {",
    "    log.info(\"시스템 상태 체크: {}\", LocalDateTime.now());",
    "}",
    "```",
    "",
    "```",
    "실행: 0초 → 5초 → 10초 → 15초 (작업 시간 무관)",
    "```",
    "",
    "### fixedDelay - 고정 간격 (종료 기준)",
    "",
    "이전 작업이 **끝난 후** 지정 시간 후 다시 실행합니다.",
    "",
    "```java",
    "@Scheduled(fixedDelay = 5000)  // 이전 종료 후 5초 대기",
    "public void syncExternalData() {",
    "    log.info(\"외부 데이터 동기화 시작\");",
    "    // 3초 소요되는 작업...",
    "    log.info(\"동기화 완료\");",
    "}",
    "```",
    "",
    "```",
    "실행: 0초 → (3초 작업) → 8초 → (3초 작업) → 16초",
    "```",
    "",
    "### cron - Cron 표현식",
    "",
    "특정 시간에 실행하는 가장 유연한 방법입니다.",
    "",
    "```java",
    "@Scheduled(cron = \"0 0 0 * * *\")  // 매일 자정",
    "public void dailyCleanup() {",
    "    log.info(\"일일 정리 작업 시작\");",
    "    expiredTokenService.deleteAll();",
    "    tempFileService.cleanup();",
    "}",
    "```",
    "",
    "### fixedRate vs fixedDelay",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    Note over A: fixedRate = 5000 (작업 3초)",
    "    participant A as fixedRate",
    "    A->>A: 작업 실행 (0~3초)",
    "    Note right of A: 5초 후 바로 시작",
    "    A->>A: 작업 실행 (5~8초)",
    "    Note right of A: 10초에 시작",
    "    A->>A: 작업 실행 (10~13초)",
    "",
    "    Note over B: fixedDelay = 5000 (작업 3초)",
    "    participant B as fixedDelay",
    "    B->>B: 작업 실행 (0~3초)",
    "    Note right of B: 종료 후 5초 대기",
    "    B->>B: 작업 실행 (8~11초)",
    "    Note right of B: 종료 후 5초 대기",
    "    B->>B: 작업 실행 (16~19초)",
    "```",
    "",
    "---",
    "",
    "## Cron 표현식",
    "",
    "```",
    "초  분  시  일  월  요일",
    " ┃   ┃   ┃   ┃   ┃   ┃",
    " 0   0   0   *   *   *    → 매일 자정",
    "```",
    "",
    "| 필드 | 범위 | 특수문자 |",
    "|------|------|----------|",
    "| 초 | 0-59 | `,` `-` `*` `/` |",
    "| 분 | 0-59 | `,` `-` `*` `/` |",
    "| 시 | 0-23 | `,` `-` `*` `/` |",
    "| 일 | 1-31 | `,` `-` `*` `/` `?` |",
    "| 월 | 1-12 | `,` `-` `*` `/` |",
    "| 요일 | 0-7 (0,7=일) | `,` `-` `*` `/` `?` |",
    "",
    "### 자주 사용하는 Cron 예시",
    "",
    "| 표현식 | 설명 |",
    "|--------|------|",
    "| `0 0 0 * * *` | 매일 자정 |",
    "| `0 0 9 * * MON-FRI` | 평일 오전 9시 |",
    "| `0 */30 * * * *` | 30분마다 |",
    "| `0 0 */2 * * *` | 2시간마다 |",
    "| `0 0 9,18 * * *` | 매일 9시, 18시 |",
    "| `0 0 0 1 * *` | 매월 1일 자정 |",
    "| `0 0 0 * * SUN` | 매주 일요일 자정 |",
    "| `0 0 0 1 1 *` | 매년 1월 1일 자정 |",
    "",
    "---",
    "",
    "## 실전 예제: 다양한 스케줄 작업",
    "",
    "```java",
    "package com.example.demo.scheduler;",
    "",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.scheduling.annotation.Scheduled;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Slf4j",
    "@Component",
    "@RequiredArgsConstructor",
    "public class ScheduledTasks {",
    "",
    "    private final TokenService tokenService;",
    "    private final CacheService cacheService;",
    "    private final ReportService reportService;",
    "",
    "    // 매일 자정: 만료된 토큰 삭제",
    "    @Scheduled(cron = \"0 0 0 * * *\")",
    "    public void deleteExpiredTokens() {",
    "        log.info(\"[스케줄] 만료 토큰 삭제 시작\");",
    "        int count = tokenService.deleteExpired();",
    "        log.info(\"[스케줄] 만료 토큰 {}개 삭제 완료\", count);",
    "    }",
    "",
    "    // 10분마다: 캐시 갱신",
    "    @Scheduled(fixedRate = 600000)",
    "    public void refreshCache() {",
    "        log.info(\"[스케줄] 캐시 갱신\");",
    "        cacheService.refresh();",
    "    }",
    "",
    "    // 평일 오전 9시: 일일 리포트 생성",
    "    @Scheduled(cron = \"0 0 9 * * MON-FRI\")",
    "    public void generateDailyReport() {",
    "        log.info(\"[스케줄] 일일 리포트 생성\");",
    "        reportService.generateDaily();",
    "    }",
    "",
    "    // 매월 1일 자정: 월간 리포트 생성",
    "    @Scheduled(cron = \"0 0 0 1 * *\")",
    "    public void generateMonthlyReport() {",
    "        log.info(\"[스케줄] 월간 리포트 생성\");",
    "        reportService.generateMonthly();",
    "    }",
    "",
    "    // 30초마다: 외부 서비스 헬스 체크 (이전 완료 후 30초)",
    "    @Scheduled(fixedDelay = 30000, initialDelay = 10000)",
    "    public void healthCheck() {",
    "        log.debug(\"[스케줄] 헬스 체크\");",
    "    }",
    "}",
    "```",
    "",
    "> `initialDelay`를 설정하면 애플리케이션 시작 후 **지정 시간만큼 대기**한 뒤 첫 실행합니다.",
    "",
    "---",
    "",
    "## 스케줄과 yml 연동",
    "",
    "Cron 표현식을 코드가 아닌 **설정 파일**에서 관리할 수 있습니다.",
    "",
    "```yaml",
    "app:",
    "  schedule:",
    "    cleanup-cron: \"0 0 0 * * *\"",
    "    cache-refresh-rate: 600000",
    "```",
    "",
    "```java",
    "@Scheduled(cron = \"${app.schedule.cleanup-cron}\")",
    "public void deleteExpiredTokens() { ... }",
    "",
    "@Scheduled(fixedRateString = \"${app.schedule.cache-refresh-rate}\")",
    "public void refreshCache() { ... }",
    "```",
    "",
    "> 이렇게 하면 환경별로(dev/prod) **다른 스케줄 주기**를 설정할 수 있습니다.",
    "",
    "---",
    "",
    "## @Async와 @Scheduled 함께 사용하기",
    "",
    "스케줄 작업이 오래 걸리면 다음 실행이 지연될 수 있습니다. `@Async`를 함께 사용하면 스케줄 스레드를 차단하지 않습니다.",
    "",
    "```java",
    "@Async",
    "@Scheduled(fixedRate = 60000)  // 1분마다",
    "public void heavyScheduledTask() {",
    "    // 오래 걸리는 작업을 비동기 스레드에서 실행",
    "    log.info(\"[{}] 무거운 작업 시작\", Thread.currentThread().getName());",
    "    processLargeData();",
    "}",
    "```",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "### 1. @Async는 같은 클래스 내부 호출 시 동작하지 않음",
    "",
    "Spring AOP 프록시 기반이므로, **같은 클래스** 내에서 호출하면 비동기가 적용되지 않습니다.",
    "",
    "```java",
    "@Service",
    "public class OrderService {",
    "",
    "    // X: 같은 클래스 내부 호출 → 동기 실행됨!",
    "    public void createOrder() {",
    "        sendEmail();  // @Async 무시됨",
    "    }",
    "",
    "    @Async",
    "    public void sendEmail() { ... }",
    "}",
    "```",
    "",
    "```java",
    "// O: 별도 클래스로 분리",
    "@Service",
    "public class OrderService {",
    "    private final EmailService emailService;  // 별도 Bean",
    "",
    "    public void createOrder() {",
    "        emailService.sendEmail();  // @Async 정상 동작",
    "    }",
    "}",
    "```",
    "",
    "### 2. @Async 예외 처리",
    "",
    "`void` 반환 비동기 메서드의 예외는 **호출자에게 전달되지 않습니다**. `AsyncUncaughtExceptionHandler`를 등록하세요.",
    "",
    "```java",
    "@Configuration",
    "@EnableAsync",
    "public class AsyncConfig implements AsyncConfigurer {",
    "",
    "    @Override",
    "    public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {",
    "        return (ex, method, params) -> {",
    "            log.error(\"비동기 예외 발생 [{}.{}]: {}\",",
    "                    method.getDeclaringClass().getSimpleName(),",
    "                    method.getName(), ex.getMessage(), ex);",
    "        };",
    "    }",
    "}",
    "```",
    "",
    "### 3. @Scheduled는 기본 단일 스레드",
    "",
    "```yaml",
    "# 반드시 스레드 풀 크기를 늘려야 여러 작업이 동시에 동작",
    "spring.task.scheduling.pool.size: 5",
    "```",
    "",
    "### 4. @Transactional과 @Async",
    "",
    "`@Async` 메서드는 **새로운 스레드**에서 실행되므로 호출자의 트랜잭션과 분리됩니다.",
    "",
    "```java",
    "@Transactional",
    "public void createOrder() {",
    "    orderRepository.save(order);",
    "    emailService.sendEmail();  // @Async → 별도 트랜잭션",
    "    // 여기서 예외 발생해도 이메일 발송은 롤백되지 않음",
    "}",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 기능 | 역할 | 핵심 코드 |",
    "|------|------|-----------|",
    "| `@EnableAsync` | 비동기 기능 활성화 | 메인 클래스 또는 설정 클래스 |",
    "| `@Async` | 메서드를 별도 스레드에서 실행 | `@Async(\"executorName\")` |",
    "| `ThreadPoolTaskExecutor` | 비동기 스레드 풀 설정 | core, max, queue 설정 |",
    "| `CompletableFuture` | 비동기 결과 처리/조합 | `supplyAsync`, `thenApply`, `allOf` |",
    "| `@EnableScheduling` | 스케줄링 활성화 | 메인 클래스 또는 설정 클래스 |",
    "| `@Scheduled` | 정기 실행 | `fixedRate`, `fixedDelay`, `cron` |",
    "",
    "| 상황 | 추천 |",
    "|------|------|",
    "| 결과 불필요, 빠른 응답 | `@Async` (void) - fire and forget |",
    "| 비동기 결과 필요 | `@Async` + `CompletableFuture` 반환 |",
    "| 여러 비동기 작업 병렬 조합 | `CompletableFuture.allOf()` |",
    "| 비동기 결과 변환/체이닝 | `thenApply`, `thenCompose` |",
    "| 비동기 에러 기본값 | `exceptionally`, `handle` |",
    "| 정기 실행 (고정 간격) | `@Scheduled(fixedRate)` |",
    "| 정기 실행 (완료 후 대기) | `@Scheduled(fixedDelay)` |",
    "| 특정 시간에 실행 | `@Scheduled(cron = \"...\")` |",
    "| Cron 외부 설정 | `cron = \"${app.schedule.cron}\"` |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
