<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-logging",
  title: "Spring Boot 로깅 완전 정리 - SLF4J, Logback, 로그 레벨부터 실전 설정까지",
  date: "2026-03-03",
  summary: "SLF4J와 Logback의 관계, 로그 레벨(TRACE~ERROR), logback-spring.xml 설정, 파일 로깅, 프로파일별 로그 설정, MDC, 비동기 로깅까지 실전 예제로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","logging","slf4j","logback","mdc","backend"],
  content: [
    "## 로깅(Logging)이란?",
    "",
    "**로깅**은 애플리케이션의 **동작 상태를 기록**하는 것입니다. 언제 어떤 요청이 들어왔는지, 어떤 에러가 발생했는지를 파일이나 콘솔에 남겨 **디버깅**과 **모니터링**에 활용합니다.",
    "",
    "### System.out.println vs Logger",
    "",
    "| 비교 항목 | System.out.println | Logger (SLF4J) |",
    "|----------|-------------------|---------------|",
    "| 로그 레벨 | ❌ 없음 | ✅ TRACE~ERROR 5단계 |",
    "| 출력 대상 | 콘솔만 | 콘솔, 파일, 외부 시스템 |",
    "| 성능 | 동기 I/O, 느림 | 비동기 가능, 최적화 |",
    "| 포맷 | 직접 작성 | 패턴으로 자동 포맷 |",
    "| 운영 환경 | ❌ 부적합 | ✅ 필수 |",
    "| 필터링 | ❌ 불가 | ✅ 레벨/패키지별 필터링 |",
    "",
    "---",
    "",
    "## SLF4J와 Logback의 관계",
    "",
    "Spring Boot는 **SLF4J**(Simple Logging Facade for Java)를 로깅 인터페이스로, **Logback**을 기본 구현체로 사용합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"애플리케이션 코드\"] --> B[\"SLF4J API<br/>(로깅 인터페이스)\"]",
    "    B --> C[\"Logback<br/>(기본 구현체)\"]",
    "    B --> D[\"Log4j2<br/>(대체 구현체)\"]",
    "    B --> E[\"JUL<br/>(java.util.logging)\"]",
    "",
    "    C --> F[\"콘솔 출력\"]",
    "    C --> G[\"파일 출력\"]",
    "    C --> H[\"외부 시스템<br/>(ELK, Sentry 등)\"]",
    "",
    "    style B fill:#4CAF50,color:#fff",
    "    style C fill:#2196F3,color:#fff",
    "```",
    "",
    "- **SLF4J**: 로깅의 **인터페이스** (추상화 계층). 코드에서는 SLF4J API만 사용",
    "- **Logback**: SLF4J의 **기본 구현체**. spring-boot-starter에 자동 포함",
    "- 구현체를 교체해도 **애플리케이션 코드 변경 불필요** (OCP 원칙)",
    "",
    "---",
    "",
    "## 로그 레벨 (Log Level)",
    "",
    "로그 레벨은 **심각도 순서**로 5단계가 있으며, 설정한 레벨 **이상**의 로그만 출력됩니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    T[\"TRACE\"] --> D[\"DEBUG\"] --> I[\"INFO\"] --> W[\"WARN\"] --> E[\"ERROR\"]",
    "    style T fill:#9E9E9E,color:#fff",
    "    style D fill:#2196F3,color:#fff",
    "    style I fill:#4CAF50,color:#fff",
    "    style W fill:#FF9800,color:#fff",
    "    style E fill:#F44336,color:#fff",
    "```",
    "",
    "| 레벨 | 설명 | 사용 시점 | 예시 |",
    "|------|------|---------|------|",
    "| **TRACE** | 가장 상세한 정보 | 변수 값 추적, 메서드 진입/종료 | `메서드 진입: findUser(id=1)` |",
    "| **DEBUG** | 디버깅용 정보 | 개발 중 흐름 확인 | `DB 쿼리 결과: 3건` |",
    "| **INFO** | 일반 운영 정보 | 정상 동작 확인 | `서버 시작 완료 (port: 8080)` |",
    "| **WARN** | 경고 (동작은 정상) | 잠재적 문제 | `캐시 만료, DB 직접 조회` |",
    "| **ERROR** | 에러 발생 | 즉시 대응 필요 | `DB 연결 실패: timeout` |",
    "",
    "> **예시**: 로그 레벨을 `INFO`로 설정하면 → INFO, WARN, ERROR만 출력 (TRACE, DEBUG는 무시)",
    "",
    "---",
    "",
    "## 기본 사용법",
    "",
    "### Lombok @Slf4j 사용",
    "",
    "```java",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "@Slf4j",
    "@RestController",
    "@RequestMapping(\"/api/users\")",
    "public class UserController {",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public UserResponse getUser(@PathVariable Long id) {",
    "        log.trace(\"getUser 메서드 진입 - id: {}\", id);",
    "        log.debug(\"사용자 조회 시작 - id: {}\", id);",
    "        log.info(\"사용자 조회 요청 - id: {}\", id);",
    "",
    "        try {",
    "            UserResponse user = userService.findById(id);",
    "            log.info(\"사용자 조회 성공 - id: {}, name: {}\", id, user.getName());",
    "            return user;",
    "        } catch (UserNotFoundException e) {",
    "            log.warn(\"사용자를 찾을 수 없음 - id: {}\", id);",
    "            throw e;",
    "        } catch (Exception e) {",
    "            log.error(\"사용자 조회 중 오류 발생 - id: {}\", id, e);",
    "            throw e;",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### Lombok 없이 사용",
    "",
    "```java",
    "import org.slf4j.Logger;",
    "import org.slf4j.LoggerFactory;",
    "",
    "public class UserService {",
    "    private static final Logger log = LoggerFactory.getLogger(UserService.class);",
    "",
    "    public User findById(Long id) {",
    "        log.info(\"사용자 조회 - id: {}\", id);",
    "        return userRepository.findById(id)",
    "                .orElseThrow(() -> {",
    "                    log.error(\"사용자 없음 - id: {}\", id);",
    "                    return new UserNotFoundException(id);",
    "                });",
    "    }",
    "}",
    "```",
    "",
    "### 파라미터 바인딩 `{}`",
    "",
    "```java",
    "// ✅ 좋은 방법 - {} 플레이스홀더 사용 (지연 평가)",
    "log.debug(\"사용자 조회 - id: {}, name: {}\", id, name);",
    "",
    "// ❌ 나쁜 방법 - 문자열 연결 (항상 문자열 생성)",
    "log.debug(\"사용자 조회 - id: \" + id + \", name: \" + name);",
    "",
    "// ✅ 예외는 마지막 인자로 전달 (스택트레이스 자동 출력)",
    "log.error(\"처리 실패 - id: {}\", id, exception);",
    "```",
    "",
    "> **핵심**: `{}`를 사용하면 해당 로그 레벨이 비활성화된 경우 **문자열 생성 비용이 발생하지 않습니다**.",
    "",
    "---",
    "",
    "## application.yml 로그 설정",
    "",
    "### 기본 설정",
    "",
    "```yaml",
    "logging:",
    "  level:",
    "    root: INFO                                    # 전체 기본 레벨",
    "    com.example.myapp: DEBUG                      # 내 패키지는 DEBUG",
    "    com.example.myapp.controller: TRACE           # 컨트롤러는 TRACE",
    "    org.springframework.web: DEBUG                # Spring Web DEBUG",
    "    org.hibernate.SQL: DEBUG                      # Hibernate SQL 쿼리 출력",
    "    org.hibernate.type.descriptor.sql: TRACE      # 바인딩 파라미터 출력",
    "```",
    "",
    "### 파일 로깅 설정",
    "",
    "```yaml",
    "logging:",
    "  file:",
    "    name: logs/application.log                    # 로그 파일 경로",
    "    max-size: 10MB                                # 파일 최대 크기",
    "    max-history: 30                               # 보관 일수",
    "    total-size-cap: 1GB                           # 전체 로그 용량 제한",
    "  pattern:",
    "    console: \"%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n\"",
    "    file: \"%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n\"",
    "```",
    "",
    "| 설정 항목 | 설명 | 기본값 |",
    "|----------|------|-------|",
    "| `logging.level.root` | 전체 로그 레벨 | INFO |",
    "| `logging.level.패키지명` | 특정 패키지 로그 레벨 | - |",
    "| `logging.file.name` | 로그 파일 경로 | - (콘솔만) |",
    "| `logging.file.max-size` | 파일 최대 크기 | 10MB |",
    "| `logging.file.max-history` | 보관 일수 | 7 |",
    "| `logging.pattern.console` | 콘솔 출력 패턴 | 기본 패턴 |",
    "| `logging.pattern.file` | 파일 출력 패턴 | 기본 패턴 |",
    "",
    "---",
    "",
    "## logback-spring.xml 상세 설정",
    "",
    "더 세밀한 설정이 필요하면 `src/main/resources/logback-spring.xml` 파일을 사용합니다.",
    "",
    "### 전체 구조",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"logback-spring.xml\"] --> B[\"Appender<br/>(어디에 출력할지)\"]",
    "    A --> C[\"Logger<br/>(어떤 패키지를 기록할지)\"]",
    "    A --> D[\"Root<br/>(기본 로그 설정)\"]",
    "",
    "    B --> E[\"ConsoleAppender<br/>(콘솔 출력)\"]",
    "    B --> F[\"RollingFileAppender<br/>(파일 출력 + 롤링)\"]",
    "    B --> G[\"AsyncAppender<br/>(비동기 출력)\"]",
    "",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "```",
    "",
    "### 실전 logback-spring.xml",
    "",
    "```xml",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<configuration>",
    "",
    "    <!-- 공통 변수 정의 -->",
    "    <property name=\"LOG_PATH\" value=\"./logs\" />",
    "    <property name=\"LOG_FILE_NAME\" value=\"application\" />",
    "    <property name=\"CONSOLE_PATTERN\"",
    "             value=\"%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n\" />",
    "    <property name=\"FILE_PATTERN\"",
    "             value=\"%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} [%X{traceId}] - %msg%n\" />",
    "",
    "    <!-- 콘솔 Appender -->",
    "    <appender name=\"CONSOLE\" class=\"ch.qos.logback.core.ConsoleAppender\">",
    "        <encoder>",
    "            <pattern>${CONSOLE_PATTERN}</pattern>",
    "        </encoder>",
    "    </appender>",
    "",
    "    <!-- 파일 Appender (날짜별 롤링) -->",
    "    <appender name=\"FILE\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">",
    "        <file>${LOG_PATH}/${LOG_FILE_NAME}.log</file>",
    "        <encoder>",
    "            <pattern>${FILE_PATTERN}</pattern>",
    "        </encoder>",
    "        <rollingPolicy class=\"ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy\">",
    "            <fileNamePattern>${LOG_PATH}/${LOG_FILE_NAME}.%d{yyyy-MM-dd}.%i.log</fileNamePattern>",
    "            <maxFileSize>10MB</maxFileSize>",
    "            <maxHistory>30</maxHistory>",
    "            <totalSizeCap>1GB</totalSizeCap>",
    "        </rollingPolicy>",
    "    </appender>",
    "",
    "    <!-- ERROR 전용 Appender -->",
    "    <appender name=\"ERROR_FILE\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">",
    "        <file>${LOG_PATH}/error.log</file>",
    "        <filter class=\"ch.qos.logback.classic.filter.LevelFilter\">",
    "            <level>ERROR</level>",
    "            <onMatch>ACCEPT</onMatch>",
    "            <onMismatch>DENY</onMismatch>",
    "        </filter>",
    "        <encoder>",
    "            <pattern>${FILE_PATTERN}</pattern>",
    "        </encoder>",
    "        <rollingPolicy class=\"ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy\">",
    "            <fileNamePattern>${LOG_PATH}/error.%d{yyyy-MM-dd}.%i.log</fileNamePattern>",
    "            <maxFileSize>10MB</maxFileSize>",
    "            <maxHistory>90</maxHistory>",
    "        </rollingPolicy>",
    "    </appender>",
    "",
    "    <!-- 패키지별 로거 설정 -->",
    "    <logger name=\"com.example.myapp\" level=\"DEBUG\" />",
    "    <logger name=\"org.springframework.web\" level=\"INFO\" />",
    "    <logger name=\"org.hibernate.SQL\" level=\"DEBUG\" />",
    "",
    "    <!-- Root 설정 -->",
    "    <root level=\"INFO\">",
    "        <appender-ref ref=\"CONSOLE\" />",
    "        <appender-ref ref=\"FILE\" />",
    "        <appender-ref ref=\"ERROR_FILE\" />",
    "    </root>",
    "",
    "</configuration>",
    "```",
    "",
    "### springProfile 태그로 프로파일별 설정",
    "",
    "```xml",
    "<configuration>",
    "",
    "    <!-- 개발 환경 -->",
    "    <springProfile name=\"local\">",
    "        <root level=\"DEBUG\">",
    "            <appender-ref ref=\"CONSOLE\" />",
    "        </root>",
    "    </springProfile>",
    "",
    "    <!-- 운영 환경 -->",
    "    <springProfile name=\"prod\">",
    "        <root level=\"INFO\">",
    "            <appender-ref ref=\"CONSOLE\" />",
    "            <appender-ref ref=\"FILE\" />",
    "            <appender-ref ref=\"ERROR_FILE\" />",
    "        </root>",
    "    </springProfile>",
    "",
    "</configuration>",
    "```",
    "",
    "| 프로파일 | 로그 레벨 | 출력 대상 | 용도 |",
    "|---------|----------|----------|------|",
    "| `local` | DEBUG | 콘솔만 | 개발 환경 |",
    "| `dev` | DEBUG | 콘솔 + 파일 | 개발 서버 |",
    "| `prod` | INFO | 콘솔 + 파일 + 에러 파일 | 운영 환경 |",
    "",
    "---",
    "",
    "## MDC (Mapped Diagnostic Context)",
    "",
    "**MDC**는 요청별 **고유 식별자(traceId)**를 로그에 자동으로 포함시키는 기능입니다. 분산 환경에서 하나의 요청 흐름을 추적할 때 필수적입니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant F as MDC Filter",
    "    participant Ctrl as Controller",
    "    participant Svc as Service",
    "    participant Log as 로그 파일",
    "",
    "    C->>F: HTTP 요청",
    "    F->>F: traceId 생성 (UUID)",
    "    F->>F: MDC.put(\"traceId\", uuid)",
    "    F->>Ctrl: 요청 전달",
    "    Ctrl->>Svc: 비즈니스 로직",
    "    Svc->>Log: log.info(\"처리 완료\")",
    "    Note over Log: [abc-123] 처리 완료",
    "    F->>F: MDC.clear()",
    "```",
    "",
    "### MDC Filter 구현",
    "",
    "```java",
    "import org.slf4j.MDC;",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import org.springframework.stereotype.Component;",
    "import java.io.IOException;",
    "import java.util.UUID;",
    "",
    "@Component",
    "public class MdcFilter implements Filter {",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request, ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "        try {",
    "            String traceId = UUID.randomUUID().toString().substring(0, 8);",
    "            MDC.put(\"traceId\", traceId);",
    "",
    "            HttpServletRequest httpRequest = (HttpServletRequest) request;",
    "            MDC.put(\"requestURI\", httpRequest.getRequestURI());",
    "            MDC.put(\"method\", httpRequest.getMethod());",
    "",
    "            chain.doFilter(request, response);",
    "        } finally {",
    "            MDC.clear();",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### 로그 패턴에 MDC 값 추가",
    "",
    "```xml",
    "<!-- logback-spring.xml 패턴에 %X{traceId} 추가 -->",
    "<property name=\"FILE_PATTERN\"",
    "          value=\"%d{HH:mm:ss.SSS} %-5level [%thread] [%X{traceId}] %logger{36} - %msg%n\" />",
    "```",
    "",
    "### 출력 결과",
    "",
    "```",
    "14:30:15.123 INFO  [http-nio-8080-exec-1] [a1b2c3d4] UserController - 사용자 조회 요청 - id: 1",
    "14:30:15.125 DEBUG [http-nio-8080-exec-1] [a1b2c3d4] UserService - DB 조회 시작",
    "14:30:15.200 INFO  [http-nio-8080-exec-1] [a1b2c3d4] UserService - 사용자 조회 완료",
    "14:30:15.130 INFO  [http-nio-8080-exec-2] [e5f6g7h8] OrderController - 주문 생성 요청",
    "```",
    "",
    "> 같은 `traceId`를 가진 로그를 필터링하면 **하나의 요청 흐름**을 추적할 수 있습니다.",
    "",
    "---",
    "",
    "## 비동기 로깅 (AsyncAppender)",
    "",
    "로그 출력은 I/O 작업이므로 **동기 방식**에서는 성능에 영향을 줄 수 있습니다. **AsyncAppender**를 사용하면 로그를 **큐에 저장**하고 별도 스레드에서 출력합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"애플리케이션 스레드\"] -->|\"log.info()\"| B[\"AsyncAppender<br/>(큐: BlockingQueue)\"]",
    "    B -->|\"별도 스레드\"| C[\"FileAppender<br/>(파일 I/O)\"]",
    "",
    "    style B fill:#FF9800,color:#fff",
    "```",
    "",
    "### AsyncAppender 설정",
    "",
    "```xml",
    "<configuration>",
    "",
    "    <!-- 기존 파일 Appender -->",
    "    <appender name=\"FILE\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">",
    "        <file>logs/application.log</file>",
    "        <encoder>",
    "            <pattern>%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n</pattern>",
    "        </encoder>",
    "        <rollingPolicy class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">",
    "            <fileNamePattern>logs/application.%d{yyyy-MM-dd}.log</fileNamePattern>",
    "            <maxHistory>30</maxHistory>",
    "        </rollingPolicy>",
    "    </appender>",
    "",
    "    <!-- 비동기 Appender -->",
    "    <appender name=\"ASYNC_FILE\" class=\"ch.qos.logback.classic.AsyncAppender\">",
    "        <queueSize>512</queueSize>",
    "        <discardingThreshold>0</discardingThreshold>",
    "        <includeCallerData>false</includeCallerData>",
    "        <neverBlock>true</neverBlock>",
    "        <appender-ref ref=\"FILE\" />",
    "    </appender>",
    "",
    "    <root level=\"INFO\">",
    "        <appender-ref ref=\"CONSOLE\" />",
    "        <appender-ref ref=\"ASYNC_FILE\" />",
    "    </root>",
    "",
    "</configuration>",
    "```",
    "",
    "| 설정 | 설명 | 기본값 |",
    "|------|------|-------|",
    "| `queueSize` | 큐 크기 (로그 메시지 버퍼) | 256 |",
    "| `discardingThreshold` | 큐가 이 비율 이하로 남으면 TRACE/DEBUG 폐기 | 20% |",
    "| `includeCallerData` | 호출자 정보 포함 (성능 저하) | false |",
    "| `neverBlock` | 큐 가득 차도 블로킹하지 않음 | false |",
    "",
    "### 동기 vs 비동기 성능 비교",
    "",
    "| 항목 | 동기 (FileAppender) | 비동기 (AsyncAppender) |",
    "|------|--------------------|-----------------------|",
    "| 로그 출력 | 즉시 파일 쓰기 | 큐에 저장 후 별도 스레드에서 쓰기 |",
    "| 응답 시간 영향 | 있음 (I/O 대기) | 거의 없음 |",
    "| 로그 유실 가능성 | 없음 | 큐 초과 시 가능 |",
    "| 적합한 환경 | 개발, 소규모 | 운영, 대규모 트래픽 |",
    "",
    "---",
    "",
    "## 로깅 패턴 커스텀",
    "",
    "### 패턴 구성 요소",
    "",
    "| 패턴 | 설명 | 출력 예시 |",
    "|------|------|---------|",
    "| `%d{패턴}` | 날짜/시간 | `2026-03-03 14:30:15.123` |",
    "| `%-5level` | 로그 레벨 (5자 좌측 정렬) | `INFO ` |",
    "| `%thread` | 스레드 이름 | `http-nio-8080-exec-1` |",
    "| `%logger{n}` | 로거 이름 (n글자 축약) | `c.e.m.UserController` |",
    "| `%msg` | 로그 메시지 | `사용자 조회 완료` |",
    "| `%n` | 줄바꿈 | - |",
    "| `%X{key}` | MDC 값 | `a1b2c3d4` |",
    "| `%highlight()` | 레벨별 색상 (콘솔) | - |",
    "| `%cyan()` | 청록색 (콘솔) | - |",
    "| `%-40.40logger{39}` | 로거명 40자 고정 | 좌측 정렬, 40자 초과 시 잘림 |",
    "",
    "### 실전 패턴 예시",
    "",
    "```xml",
    "<!-- 개발용 (컬러, 간결) -->",
    "<pattern>%d{HH:mm:ss} %highlight(%-5level) %cyan(%-30logger{29}) - %msg%n</pattern>",
    "",
    "<!-- 운영용 (날짜, traceId, 상세) -->",
    "<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%15thread] [%X{traceId}] %-40logger{39} - %msg%n</pattern>",
    "",
    "<!-- JSON 형식 (ELK 연동) -->",
    "<pattern>{\"timestamp\":\"%d{ISO8601}\",\"level\":\"%level\",\"thread\":\"%thread\",\"logger\":\"%logger\",\"traceId\":\"%X{traceId}\",\"message\":\"%msg\"}%n</pattern>",
    "```",
    "",
    "---",
    "",
    "## 실전 팁",
    "",
    "### 운영 로그 전략",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"로그 전략\"] --> B[\"레벨 분리\"]",
    "    A --> C[\"파일 분리\"]",
    "    A --> D[\"로그 수집\"]",
    "",
    "    B --> B1[\"local: DEBUG\"]",
    "    B --> B2[\"dev: DEBUG\"]",
    "    B --> B3[\"prod: INFO\"]",
    "",
    "    C --> C1[\"application.log<br/>(전체 로그)\"]",
    "    C --> C2[\"error.log<br/>(에러 전용)\"]",
    "    C --> C3[\"access.log<br/>(접근 로그)\"]",
    "",
    "    D --> D1[\"ELK Stack\"]",
    "    D --> D2[\"CloudWatch\"]",
    "    D --> D3[\"Datadog\"]",
    "```",
    "",
    "### 효과적인 로그 작성법",
    "",
    "```java",
    "// ✅ 좋은 로그 - 구체적인 컨텍스트 포함",
    "log.info(\"주문 생성 완료 - orderId: {}, userId: {}, amount: {}\", orderId, userId, amount);",
    "log.error(\"결제 실패 - orderId: {}, reason: {}\", orderId, e.getMessage(), e);",
    "",
    "// ❌ 나쁜 로그 - 정보가 부족",
    "log.info(\"완료\");",
    "log.error(\"에러 발생\");",
    "",
    "// ✅ 조건부 로그 (비용이 큰 로그)",
    "if (log.isDebugEnabled()) {",
    "    log.debug(\"상세 정보: {}\", expensiveToString());",
    "}",
    "```",
    "",
    "### 민감 정보 로깅 금지",
    "",
    "```java",
    "// ❌ 절대 금지 - 민감 정보 로깅",
    "log.info(\"로그인 - email: {}, password: {}\", email, password);",
    "log.info(\"결제 - cardNumber: {}\", cardNumber);",
    "",
    "// ✅ 마스킹 처리",
    "log.info(\"로그인 - email: {}\", maskEmail(email));",
    "log.info(\"결제 - cardNumber: ****-****-****-{}\", cardNumber.substring(12));",
    "```",
    "",
    "```java",
    "public class LogMaskUtil {",
    "    public static String maskEmail(String email) {",
    "        int atIndex = email.indexOf('@');",
    "        if (atIndex <= 2) return \"***\" + email.substring(atIndex);",
    "        return email.substring(0, 2) + \"***\" + email.substring(atIndex);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 로그 파일 관리",
    "",
    "| 관리 항목 | 권장 설정 | 이유 |",
    "|----------|----------|------|",
    "| 파일 크기 | 10~50MB | 너무 크면 열기/검색 어려움 |",
    "| 보관 기간 | 30~90일 | 디스크 용량 관리 |",
    "| 전체 용량 | 1~5GB | 디스크 부족 방지 |",
    "| 에러 로그 | 별도 파일 | 빠른 에러 확인 |",
    "| 압축 | gzip | 디스크 절약 (`fileNamePattern`에 `.gz` 추가) |",
    "",
    "### 압축 로그 파일 설정",
    "",
    "```xml",
    "<!-- .gz 확장자를 붙이면 자동 gzip 압축 -->",
    "<fileNamePattern>logs/application.%d{yyyy-MM-dd}.%i.log.gz</fileNamePattern>",
    "```",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "| 주의사항 | 설명 |",
    "|---------|------|",
    "| 문자열 연결 금지 | `log.debug(\"id: \" + id)` 대신 `log.debug(\"id: {}\", id)` 사용 |",
    "| 민감 정보 금지 | 비밀번호, 카드번호, 개인정보 로그에 남기지 않기 |",
    "| 과도한 로그 주의 | 루프 안에서 매번 로깅하면 성능 저하 |",
    "| 예외 전체 출력 | `log.error(\"msg\", e)` - 예외 객체를 마지막 인자로 전달 |",
    "| 운영 레벨 관리 | 운영 환경은 INFO 이상만 출력 |",
    "| MDC 정리 | Filter의 finally에서 반드시 `MDC.clear()` 호출 |",
    "| 비동기 주의 | AsyncAppender 사용 시 큐 크기와 유실 정책 설정 필수 |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| **SLF4J** | 로깅 인터페이스 (Facade 패턴) |",
    "| **Logback** | Spring Boot 기본 로깅 구현체 |",
    "| **로그 레벨** | TRACE < DEBUG < INFO < WARN < ERROR |",
    "| **@Slf4j** | Lombok 어노테이션, `log` 필드 자동 생성 |",
    "| **application.yml** | 간단한 레벨/파일/패턴 설정 |",
    "| **logback-spring.xml** | 세밀한 Appender/Logger/프로파일 설정 |",
    "| **MDC** | 요청별 traceId 추적 |",
    "| **AsyncAppender** | 비동기 로깅으로 성능 최적화 |",
    "| **패턴** | %d, %level, %thread, %logger, %msg, %X{key} |",
    "| **운영 팁** | 파일 분리, 압축, 민감 정보 마스킹, 적절한 레벨 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
