<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-libraries",
  title: "스프링부트 다양한 라이브러리 - Validation, ModelMapper, Gson 완전 정리",
  date: "2026-03-03",
  summary: "Spring Boot에서 자주 사용하는 라이브러리 3가지를 정리합니다. Bean Validation(입력 검증), ModelMapper(객체 변환), Gson(JSON 처리)의 개념, 설정, 실전 예제를 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","validation","modelmapper","gson","java","backend"],
  content: [
    "## 개요",
    "",
    "Spring Boot 프로젝트에서 자주 사용하는 실용 라이브러리 3가지를 정리합니다.",
    "",
    "| 라이브러리 | 역할 | 핵심 키워드 |",
    "|------------|------|-------------|",
    "| **Bean Validation** | 입력 데이터 검증 | `@NotBlank`, `@Email`, `@Valid` |",
    "| **ModelMapper** | 객체 간 필드 복사/변환 | Entity ↔ DTO 변환 |",
    "| **Gson** | JSON 직렬화/역직렬화 | Google JSON 라이브러리 |",
    "",
    "---",
    "",
    "# 1. Bean Validation (입력 검증)",
    "",
    "## Bean Validation이란?",
    "",
    "**Bean Validation**은 Java 객체의 필드 값이 올바른지 **어노테이션으로 검증**하는 표준(Jakarta Validation)입니다. Spring Boot에서는 `@Valid`와 함께 사용하여 Controller에 들어오는 요청 데이터를 자동으로 검증합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"클라이언트 요청<br/>{name: '', email: 'bad'}\"] --> B[\"@Valid 검증\"]",
    "    B -->|통과| C[\"Controller → Service\"]",
    "    B -->|실패| D[\"400 Bad Request<br/>+ 에러 메시지\"]",
    "```",
    "",
    "## 의존성",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-validation'",
    "}",
    "```",
    "",
    "---",
    "",
    "## 검증 어노테이션 총정리",
    "",
    "### 문자열 검증",
    "",
    "| 어노테이션 | 설명 | 예시 |",
    "|------------|------|------|",
    "| `@NotNull` | null 불가 (빈 문자열은 허용) | `@NotNull String name` |",
    "| `@NotEmpty` | null, 빈 문자열(`\"\"`) 불가 | `@NotEmpty String name` |",
    "| `@NotBlank` | null, 빈 문자열, 공백만(`\" \"`) 불가 | `@NotBlank String name` |",
    "| `@Size(min, max)` | 길이 범위 | `@Size(min=2, max=50)` |",
    "| `@Email` | 이메일 형식 | `@Email String email` |",
    "| `@Pattern(regexp)` | 정규표현식 매칭 | `@Pattern(regexp=\"^010-\\\\d{4}-\\\\d{4}$\")` |",
    "",
    "### 숫자 검증",
    "",
    "| 어노테이션 | 설명 | 예시 |",
    "|------------|------|------|",
    "| `@Min(value)` | 최솟값 | `@Min(0) int age` |",
    "| `@Max(value)` | 최댓값 | `@Max(150) int age` |",
    "| `@Positive` | 양수 | `@Positive int price` |",
    "| `@PositiveOrZero` | 0 또는 양수 | `@PositiveOrZero int stock` |",
    "| `@Negative` | 음수 | `@Negative int discount` |",
    "| `@Digits(integer, fraction)` | 정수·소수 자릿수 제한 | `@Digits(integer=10, fraction=2)` |",
    "| `@DecimalMin / @DecimalMax` | 문자열 숫자 범위 | `@DecimalMin(\"0.01\")` |",
    "",
    "### 날짜 검증",
    "",
    "| 어노테이션 | 설명 |",
    "|------------|------|",
    "| `@Past` | 과거 날짜만 |",
    "| `@PastOrPresent` | 과거 또는 현재 |",
    "| `@Future` | 미래 날짜만 |",
    "| `@FutureOrPresent` | 미래 또는 현재 |",
    "",
    "### 기타",
    "",
    "| 어노테이션 | 설명 |",
    "|------------|------|",
    "| `@AssertTrue` | true여야 함 (약관 동의 등) |",
    "| `@AssertFalse` | false여야 함 |",
    "",
    "---",
    "",
    "## 실전 예제: 회원가입 검증",
    "",
    "### DTO 작성",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import jakarta.validation.constraints.*;",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "",
    "@Getter @Setter",
    "public class SignupRequest {",
    "",
    "    @NotBlank(message = \"이름은 필수입니다\")",
    "    @Size(min = 2, max = 20, message = \"이름은 2~20자여야 합니다\")",
    "    private String name;",
    "",
    "    @NotBlank(message = \"이메일은 필수입니다\")",
    "    @Email(message = \"올바른 이메일 형식이 아닙니다\")",
    "    private String email;",
    "",
    "    @NotBlank(message = \"비밀번호는 필수입니다\")",
    "    @Size(min = 8, max = 100, message = \"비밀번호는 8자 이상이어야 합니다\")",
    "    @Pattern(",
    "        regexp = \"^(?=.*[A-Za-z])(?=.*\\\\d)(?=.*[@$!%*#?&]).{8,}$\",",
    "        message = \"비밀번호는 영문, 숫자, 특수문자를 포함해야 합니다\"",
    "    )",
    "    private String password;",
    "",
    "    @NotBlank(message = \"전화번호는 필수입니다\")",
    "    @Pattern(",
    "        regexp = \"^010-\\\\d{4}-\\\\d{4}$\",",
    "        message = \"전화번호 형식: 010-1234-5678\"",
    "    )",
    "    private String phone;",
    "",
    "    @Min(value = 14, message = \"만 14세 이상만 가입 가능합니다\")",
    "    @Max(value = 150, message = \"나이는 150 이하여야 합니다\")",
    "    private int age;",
    "",
    "    @AssertTrue(message = \"이용약관에 동의해야 합니다\")",
    "    private boolean agreeTerms;",
    "}",
    "```",
    "",
    "### Controller에서 @Valid 적용",
    "",
    "```java",
    "@RestController",
    "@RequestMapping(\"/api/auth\")",
    "@RequiredArgsConstructor",
    "public class AuthController {",
    "",
    "    private final UserService userService;",
    "",
    "    @PostMapping(\"/signup\")",
    "    public ResponseEntity<UserResponse> signup(",
    "            @Valid @RequestBody SignupRequest request) {",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(userService.signup(request));",
    "    }",
    "}",
    "```",
    "",
    "> `@Valid`를 붙이면 Spring이 자동으로 DTO의 검증 어노테이션을 실행합니다. 실패하면 `MethodArgumentNotValidException`이 발생합니다.",
    "",
    "### 에러 응답 처리 (@RestControllerAdvice)",
    "",
    "```java",
    "@RestControllerAdvice",
    "public class GlobalExceptionHandler {",
    "",
    "    @ExceptionHandler(MethodArgumentNotValidException.class)",
    "    public ResponseEntity<Map<String, Object>> handleValidation(",
    "            MethodArgumentNotValidException ex) {",
    "",
    "        Map<String, String> errors = new LinkedHashMap<>();",
    "        ex.getBindingResult().getFieldErrors().forEach(error ->",
    "            errors.put(error.getField(), error.getDefaultMessage())",
    "        );",
    "",
    "        Map<String, Object> body = new LinkedHashMap<>();",
    "        body.put(\"code\", \"VALIDATION_ERROR\");",
    "        body.put(\"message\", \"입력값이 올바르지 않습니다\");",
    "        body.put(\"errors\", errors);",
    "",
    "        return ResponseEntity.badRequest().body(body);",
    "    }",
    "}",
    "```",
    "",
    "### 에러 응답 예시",
    "",
    "```json",
    "{",
    "  \"code\": \"VALIDATION_ERROR\",",
    "  \"message\": \"입력값이 올바르지 않습니다\",",
    "  \"errors\": {",
    "    \"name\": \"이름은 필수입니다\",",
    "    \"email\": \"올바른 이메일 형식이 아닙니다\",",
    "    \"password\": \"비밀번호는 영문, 숫자, 특수문자를 포함해야 합니다\",",
    "    \"phone\": \"전화번호 형식: 010-1234-5678\",",
    "    \"agreeTerms\": \"이용약관에 동의해야 합니다\"",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 커스텀 검증 어노테이션 만들기",
    "",
    "기본 어노테이션으로 부족한 경우 **직접 검증 규칙**을 만들 수 있습니다.",
    "",
    "### 예제: 비속어 금지 어노테이션",
    "",
    "#### 1단계: 어노테이션 정의",
    "",
    "```java",
    "package com.example.demo.validation;",
    "",
    "import jakarta.validation.Constraint;",
    "import jakarta.validation.Payload;",
    "import java.lang.annotation.*;",
    "",
    "@Target({ElementType.FIELD})",
    "@Retention(RetentionPolicy.RUNTIME)",
    "@Constraint(validatedBy = NoProfanityValidator.class)",
    "public @interface NoProfanity {",
    "    String message() default \"부적절한 단어가 포함되어 있습니다\";",
    "    Class<?>[] groups() default {};",
    "    Class<? extends Payload>[] payload() default {};",
    "}",
    "```",
    "",
    "#### 2단계: 검증 로직 구현",
    "",
    "```java",
    "package com.example.demo.validation;",
    "",
    "import jakarta.validation.ConstraintValidator;",
    "import jakarta.validation.ConstraintValidatorContext;",
    "import java.util.Set;",
    "",
    "public class NoProfanityValidator",
    "        implements ConstraintValidator<NoProfanity, String> {",
    "",
    "    private static final Set<String> BLOCKED_WORDS = Set.of(",
    "            \"바보\", \"멍청이\"",
    "    );",
    "",
    "    @Override",
    "    public boolean isValid(String value, ConstraintValidatorContext context) {",
    "        if (value == null) return true;",
    "        return BLOCKED_WORDS.stream()",
    "                .noneMatch(word -> value.contains(word));",
    "    }",
    "}",
    "```",
    "",
    "#### 3단계: DTO에 적용",
    "",
    "```java",
    "@Getter @Setter",
    "public class CreatePostRequest {",
    "",
    "    @NotBlank",
    "    @NoProfanity",
    "    private String title;",
    "",
    "    @NotBlank",
    "    @NoProfanity",
    "    private String content;",
    "}",
    "```",
    "",
    "---",
    "",
    "## 중첩 객체 검증 (@Valid 중첩)",
    "",
    "DTO 안에 다른 DTO가 있을 때, 안쪽 객체에도 `@Valid`를 붙여야 검증이 동작합니다.",
    "",
    "```java",
    "@Getter @Setter",
    "public class OrderRequest {",
    "",
    "    @NotBlank",
    "    private String orderName;",
    "",
    "    @Valid",
    "    @NotNull(message = \"배송 정보는 필수입니다\")",
    "    private AddressRequest address;",
    "}",
    "",
    "@Getter @Setter",
    "public class AddressRequest {",
    "",
    "    @NotBlank(message = \"도시는 필수입니다\")",
    "    private String city;",
    "",
    "    @NotBlank(message = \"상세주소는 필수입니다\")",
    "    private String detail;",
    "",
    "    @Pattern(regexp = \"\\\\d{5}\", message = \"우편번호는 5자리 숫자입니다\")",
    "    private String zipCode;",
    "}",
    "```",
    "",
    "---",
    "",
    "# 2. ModelMapper (객체 변환)",
    "",
    "## ModelMapper란?",
    "",
    "**ModelMapper**는 Java 객체 간의 **필드를 자동으로 복사**해주는 라이브러리입니다. Entity ↔ DTO 변환에서 반복적인 getter/setter 코드를 줄여줍니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"User Entity<br/>{id, name, email, password, createdAt}\"] -->|ModelMapper| B[\"UserResponse DTO<br/>{id, name, email}\"]",
    "    C[\"CreateUserRequest DTO<br/>{name, email, age}\"] -->|ModelMapper| D[\"User Entity<br/>{name, email, age}\"]",
    "```",
    "",
    "## 의존성",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.modelmapper:modelmapper:3.2.0'",
    "}",
    "```",
    "",
    "## Bean 등록",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import org.modelmapper.ModelMapper;",
    "import org.modelmapper.convention.MatchingStrategies;",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "",
    "@Configuration",
    "public class AppConfig {",
    "",
    "    @Bean",
    "    public ModelMapper modelMapper() {",
    "        ModelMapper mapper = new ModelMapper();",
    "        mapper.getConfiguration()",
    "                .setMatchingStrategy(MatchingStrategies.STRICT)",
    "                .setFieldMatchingEnabled(true)",
    "                .setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel.PRIVATE);",
    "        return mapper;",
    "    }",
    "}",
    "```",
    "",
    "### 매칭 전략",
    "",
    "| 전략 | 설명 | 추천 |",
    "|------|------|------|",
    "| `STANDARD` | 기본값. 소스와 대상 필드명을 지능적으로 매칭 | 일반적인 경우 |",
    "| `STRICT` | 필드명이 정확히 일치해야 매핑 | **권장** (예상치 못한 매핑 방지) |",
    "| `LOOSE` | 가장 느슨한 매칭. 토큰 순서 무시 | 비추천 |",
    "",
    "---",
    "",
    "## 기본 사용법",
    "",
    "### Entity와 DTO",
    "",
    "```java",
    "// Entity",
    "@Getter @Setter",
    "public class User {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private String password;",
    "    private int age;",
    "    private LocalDateTime createdAt;",
    "}",
    "",
    "// 응답 DTO (password 제외)",
    "@Getter @Setter",
    "public class UserResponse {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private int age;",
    "}",
    "",
    "// 생성 DTO",
    "@Getter @Setter",
    "public class CreateUserRequest {",
    "    private String name;",
    "    private String email;",
    "    private String password;",
    "    private int age;",
    "}",
    "```",
    "",
    "### 변환 코드",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class UserService {",
    "",
    "    private final UserRepository userRepository;",
    "    private final ModelMapper modelMapper;",
    "",
    "    // DTO → Entity (생성)",
    "    public UserResponse create(CreateUserRequest request) {",
    "        User user = modelMapper.map(request, User.class);",
    "        user.setCreatedAt(LocalDateTime.now());",
    "        User saved = userRepository.save(user);",
    "        return modelMapper.map(saved, UserResponse.class);",
    "    }",
    "",
    "    // Entity → DTO (조회)",
    "    public UserResponse findById(Long id) {",
    "        User user = userRepository.findById(id)",
    "                .orElseThrow(() -> new RuntimeException(\"사용자 없음\"));",
    "        return modelMapper.map(user, UserResponse.class);",
    "    }",
    "",
    "    // 목록 조회 (List 변환)",
    "    public List<UserResponse> findAll() {",
    "        return userRepository.findAll().stream()",
    "                .map(user -> modelMapper.map(user, UserResponse.class))",
    "                .toList();",
    "    }",
    "}",
    "```",
    "",
    "### ModelMapper 없이 수동 변환 (비교)",
    "",
    "```java",
    "// ModelMapper 사용",
    "UserResponse dto = modelMapper.map(user, UserResponse.class);",
    "",
    "// 수동 변환 (필드가 많으면 코드가 길어짐)",
    "UserResponse dto = new UserResponse();",
    "dto.setId(user.getId());",
    "dto.setName(user.getName());",
    "dto.setEmail(user.getEmail());",
    "dto.setAge(user.getAge());",
    "```",
    "",
    "---",
    "",
    "## 고급 사용법",
    "",
    "### 필드명이 다른 경우 (커스텀 매핑)",
    "",
    "```java",
    "// Entity",
    "@Getter @Setter",
    "public class Order {",
    "    private Long id;",
    "    private String productName;",
    "    private int totalPrice;",
    "    private User buyer;",
    "}",
    "",
    "// DTO (필드명이 다름)",
    "@Getter @Setter",
    "public class OrderResponse {",
    "    private Long orderId;       // id → orderId",
    "    private String itemName;    // productName → itemName",
    "    private int price;          // totalPrice → price",
    "    private String buyerName;   // buyer.name → buyerName",
    "}",
    "```",
    "",
    "```java",
    "@Bean",
    "public ModelMapper modelMapper() {",
    "    ModelMapper mapper = new ModelMapper();",
    "",
    "    // Order → OrderResponse 커스텀 매핑 규칙",
    "    mapper.createTypeMap(Order.class, OrderResponse.class)",
    "            .addMapping(Order::getId, OrderResponse::setOrderId)",
    "            .addMapping(Order::getProductName, OrderResponse::setItemName)",
    "            .addMapping(Order::getTotalPrice, OrderResponse::setPrice)",
    "            .addMapping(",
    "                src -> src.getBuyer().getName(),",
    "                OrderResponse::setBuyerName",
    "            );",
    "",
    "    return mapper;",
    "}",
    "```",
    "",
    "### 특정 필드 제외 (skip)",
    "",
    "```java",
    "mapper.createTypeMap(User.class, UserResponse.class)",
    "        .addMappings(m -> m.skip(UserResponse::setEmail));",
    "```",
    "",
    "### 변환 후 추가 처리 (Converter)",
    "",
    "```java",
    "mapper.createTypeMap(User.class, UserResponse.class)",
    "        .setPostConverter(context -> {",
    "            UserResponse dest = context.getDestination();",
    "            // 이름을 마스킹",
    "            String name = dest.getName();",
    "            if (name != null && name.length() > 1) {",
    "                dest.setName(name.charAt(0) + \"*\".repeat(name.length() - 1));",
    "            }",
    "            return dest;",
    "        });",
    "```",
    "",
    "---",
    "",
    "## ModelMapper vs 수동 변환 vs MapStruct",
    "",
    "| 비교 | 수동 변환 | ModelMapper | MapStruct |",
    "|------|----------|-------------|-----------|",
    "| 설정 | 없음 | Bean 등록 | 인터페이스 정의 |",
    "| 성능 | 가장 빠름 | 런타임 리플렉션 (느림) | **컴파일타임 코드 생성 (빠름)** |",
    "| 타입 안전성 | O | X (런타임 에러) | O (컴파일 에러) |",
    "| 코드량 | 많음 | **적음** | 적음 |",
    "| 디버깅 | 쉬움 | 어려움 | 쉬움 |",
    "| 추천 | 필드 적을 때 | 빠른 프로토타이핑 | **실무 권장** |",
    "",
    "> 실무에서는 **성능과 타입 안전성**이 중요하므로 MapStruct를 더 많이 사용합니다. ModelMapper는 빠른 개발이나 프로토타이핑에 적합합니다.",
    "",
    "---",
    "",
    "# 3. Gson (JSON 처리)",
    "",
    "## Gson이란?",
    "",
    "**Gson**은 Google이 만든 **JSON ↔ Java 객체** 변환 라이브러리입니다. Spring Boot의 기본 JSON 라이브러리는 Jackson이지만, Gson은 더 **간결한 API**와 **가벼운 크기**가 장점입니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Java 객체\"] -->|\"gson.toJson()\"| B[\"JSON 문자열\"]",
    "    B -->|\"gson.fromJson()\"| A",
    "```",
    "",
    "## 의존성",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'com.google.code.gson:gson:2.11.0'",
    "}",
    "```",
    "",
    "## Bean 등록",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import com.google.gson.Gson;",
    "import com.google.gson.GsonBuilder;",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "",
    "@Configuration",
    "public class GsonConfig {",
    "",
    "    @Bean",
    "    public Gson gson() {",
    "        return new GsonBuilder()",
    "                .setPrettyPrinting()        // JSON 보기 좋게 포맷팅",
    "                .setDateFormat(\"yyyy-MM-dd HH:mm:ss\")",
    "                .serializeNulls()           // null 필드도 포함",
    "                .create();",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 기본 사용법",
    "",
    "### 객체 → JSON (직렬화)",
    "",
    "```java",
    "@Getter @Setter",
    "@AllArgsConstructor",
    "public class Product {",
    "    private Long id;",
    "    private String name;",
    "    private int price;",
    "    private boolean available;",
    "}",
    "```",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class ProductService {",
    "",
    "    private final Gson gson;",
    "",
    "    public void example() {",
    "        Product product = new Product(1L, \"노트북\", 1500000, true);",
    "",
    "        // 객체 → JSON 문자열",
    "        String json = gson.toJson(product);",
    "        System.out.println(json);",
    "    }",
    "}",
    "```",
    "",
    "**출력:**",
    "",
    "```json",
    "{",
    "  \"id\": 1,",
    "  \"name\": \"노트북\",",
    "  \"price\": 1500000,",
    "  \"available\": true",
    "}",
    "```",
    "",
    "### JSON → 객체 (역직렬화)",
    "",
    "```java",
    "String json = \"{\\\"id\\\":1,\\\"name\\\":\\\"노트북\\\",\\\"price\\\":1500000,\\\"available\\\":true}\";",
    "",
    "// JSON 문자열 → 객체",
    "Product product = gson.fromJson(json, Product.class);",
    "System.out.println(product.getName());  // 노트북",
    "System.out.println(product.getPrice()); // 1500000",
    "```",
    "",
    "### List ↔ JSON",
    "",
    "```java",
    "import com.google.gson.reflect.TypeToken;",
    "import java.lang.reflect.Type;",
    "",
    "// List → JSON",
    "List<Product> products = List.of(",
    "        new Product(1L, \"노트북\", 1500000, true),",
    "        new Product(2L, \"마우스\", 35000, true),",
    "        new Product(3L, \"키보드\", 89000, false)",
    ");",
    "String jsonArray = gson.toJson(products);",
    "",
    "// JSON → List",
    "Type listType = new TypeToken<List<Product>>(){}.getType();",
    "List<Product> restored = gson.fromJson(jsonArray, listType);",
    "System.out.println(restored.size()); // 3",
    "```",
    "",
    "> **`TypeToken`**은 Java의 제네릭 타입 소거(Type Erasure) 문제를 해결하기 위한 Gson의 유틸리티입니다. `List<Product>`같은 제네릭 타입을 런타임에서도 인식할 수 있게 해줍니다.",
    "",
    "### Map ↔ JSON",
    "",
    "```java",
    "// Map → JSON",
    "Map<String, Object> data = new LinkedHashMap<>();",
    "data.put(\"name\", \"홍길동\");",
    "data.put(\"age\", 28);",
    "data.put(\"scores\", List.of(90, 85, 95));",
    "String json = gson.toJson(data);",
    "",
    "// JSON → Map",
    "Type mapType = new TypeToken<Map<String, Object>>(){}.getType();",
    "Map<String, Object> restored = gson.fromJson(json, mapType);",
    "```",
    "",
    "---",
    "",
    "## 실전 활용: 외부 API 응답 파싱",
    "",
    "외부 API에서 받은 JSON 응답을 Java 객체로 변환하는 실전 예제입니다.",
    "",
    "```java",
    "// 외부 API의 JSON 응답 구조",
    "// {",
    "//   \"status\": \"success\",",
    "//   \"data\": {",
    "//     \"temperature\": 24.5,",
    "//     \"humidity\": 60,",
    "//     \"city\": \"Seoul\"",
    "//   }",
    "// }",
    "",
    "// 응답 매핑용 클래스",
    "@Getter @Setter",
    "public class WeatherApiResponse {",
    "    private String status;",
    "    private WeatherData data;",
    "}",
    "",
    "@Getter @Setter",
    "public class WeatherData {",
    "    private double temperature;",
    "    private int humidity;",
    "    private String city;",
    "}",
    "```",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class WeatherService {",
    "",
    "    private final Gson gson;",
    "    private final RestTemplate restTemplate;",
    "",
    "    public WeatherData getWeather(String city) {",
    "        String jsonResponse = restTemplate.getForObject(",
    "                \"https://api.example.com/weather?city=\" + city,",
    "                String.class",
    "        );",
    "",
    "        WeatherApiResponse response = gson.fromJson(jsonResponse, WeatherApiResponse.class);",
    "",
    "        if (\"success\".equals(response.getStatus())) {",
    "            return response.getData();",
    "        }",
    "        throw new RuntimeException(\"날씨 API 호출 실패\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 고급 사용법",
    "",
    "### 필드 이름 변경 (@SerializedName)",
    "",
    "JSON 키와 Java 필드명이 다를 때 사용합니다.",
    "",
    "```java",
    "@Getter @Setter",
    "public class GithubUser {",
    "",
    "    @SerializedName(\"login\")",
    "    private String username;",
    "",
    "    @SerializedName(\"avatar_url\")",
    "    private String avatarUrl;",
    "",
    "    @SerializedName(\"public_repos\")",
    "    private int publicRepoCount;",
    "}",
    "```",
    "",
    "```java",
    "String json = \"{\\\"login\\\":\\\"haru1813\\\",\\\"avatar_url\\\":\\\"https://...\\\",\\\"public_repos\\\":42}\";",
    "GithubUser user = gson.fromJson(json, GithubUser.class);",
    "System.out.println(user.getUsername()); // haru1813",
    "```",
    "",
    "### 특정 필드 제외 (@Expose + excludeFieldsWithoutExposeAnnotation)",
    "",
    "```java",
    "@Getter @Setter",
    "public class User {",
    "    @Expose private Long id;",
    "    @Expose private String name;",
    "    @Expose private String email;",
    "    private String password;  // @Expose 없음 → JSON에서 제외",
    "}",
    "```",
    "",
    "```java",
    "@Bean",
    "public Gson gson() {",
    "    return new GsonBuilder()",
    "            .excludeFieldsWithoutExposeAnnotation()  // @Expose 없는 필드 제외",
    "            .create();",
    "}",
    "```",
    "",
    "### transient 키워드로 제외",
    "",
    "```java",
    "@Getter @Setter",
    "public class User {",
    "    private Long id;",
    "    private String name;",
    "    private transient String password;  // JSON 변환에서 제외",
    "}",
    "```",
    "",
    "---",
    "",
    "## Gson vs Jackson 비교",
    "",
    "| 비교 | Gson | Jackson |",
    "|------|------|---------|",
    "| 개발사 | Google | FasterXML |",
    "| Spring Boot 기본 | X | **O** (자동 포함) |",
    "| API 스타일 | `toJson()` / `fromJson()` | `writeValueAsString()` / `readValue()` |",
    "| 설정 복잡도 | 단순 | 다양한 설정 가능 |",
    "| 성능 | 중간 | **빠름** (스트리밍 지원) |",
    "| 어노테이션 | `@SerializedName`, `@Expose` | `@JsonProperty`, `@JsonIgnore` |",
    "| 용량 | 가벼움 (약 250KB) | 상대적으로 큼 |",
    "| 추천 | 외부 JSON 파싱, 단순 변환 | Spring Boot 기본, REST API |",
    "",
    "### 같은 작업, 다른 코드",
    "",
    "```java",
    "// Gson",
    "Gson gson = new Gson();",
    "String json = gson.toJson(user);",
    "User user = gson.fromJson(json, User.class);",
    "",
    "// Jackson (Spring Boot 기본)",
    "ObjectMapper mapper = new ObjectMapper();",
    "String json = mapper.writeValueAsString(user);",
    "User user = mapper.readValue(json, User.class);",
    "```",
    "",
    "> Spring Boot의 REST API에서는 Jackson이 자동으로 동작하므로 별도 설정이 필요 없습니다. Gson은 **외부 API 응답 파싱**, **파일에서 JSON 읽기**, **Jackson이 없는 환경**에서 주로 사용합니다.",
    "",
    "---",
    "",
    "## 3가지 라이브러리 활용 흐름",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"클라이언트 요청<br/>(JSON)\"] -->|@Valid| B[\"Bean Validation<br/>입력 검증\"]",
    "    B -->|통과| C[\"Controller\"]",
    "    C --> D[\"Service\"]",
    "    D -->|ModelMapper| E[\"DTO → Entity 변환\"]",
    "    E --> F[\"Repository 저장\"]",
    "    F --> G[\"Entity 조회\"]",
    "    G -->|ModelMapper| H[\"Entity → DTO 변환\"]",
    "    H --> I[\"응답 반환 (JSON)\"]",
    "    D -->|Gson| J[\"외부 API 호출<br/>JSON 파싱\"]",
    "    J --> D",
    "    B -->|실패| K[\"400 에러 응답\"]",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 라이브러리 | 역할 | 핵심 코드 |",
    "|------------|------|-----------|",
    "| **Bean Validation** | 입력 검증 | `@NotBlank`, `@Email`, `@Valid` + `BindingResult` |",
    "| **ModelMapper** | 객체 변환 | `modelMapper.map(source, TargetClass.class)` |",
    "| **Gson** | JSON 처리 | `gson.toJson(obj)`, `gson.fromJson(json, Class)` |",
    "",
    "| 상황 | 추천 |",
    "|------|------|",
    "| API 입력 검증 | **Bean Validation** (Spring 표준) |",
    "| Entity ↔ DTO 변환 (빠른 개발) | **ModelMapper** |",
    "| Entity ↔ DTO 변환 (실무 성능) | MapStruct |",
    "| Spring Boot REST API의 JSON 변환 | Jackson (기본 내장) |",
    "| 외부 JSON 파싱, 단순 변환 | **Gson** |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
