<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-build-system",
  title: "IntelliJ vs Maven vs Gradle - Java 빌드 시스템 완벽 정리",
  date: "2026-03-09",
  summary: "IntelliJ 프로젝트 생성 시 선택하는 빌드 시스템 3가지(IntelliJ, Maven, Gradle)의 개념, 차이점, 설정 파일, 의존성 관리, 빌드 명령어, 그리고 언제 무엇을 선택해야 하는지 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","maven","gradle","intellij","build","java","groovy","kotlin","backend"],
  content: [
    "## 한 줄 요약",
    "**빌드 시스템**은 소스 코드를 컴파일하고, 라이브러리를 관리하고, 실행 가능한 파일(JAR/WAR)을 만들어주는 도구입니다. Java에서는 **Maven**과 **Gradle**이 업계 표준이며, **IntelliJ 빌드**는 IDE 내장 방식입니다.",
    "",
    "---",
    "",
    "## 빌드 시스템이란?",
    "",
    "소스 코드(`.java`)를 작성한 후, 이를 실행 가능한 프로그램으로 만들려면 여러 단계를 거쳐야 합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"소스 코드<br>.java\"] --> B[\"컴파일<br>.class\"]",
    "    B --> C[\"테스트 실행\"]",
    "    C --> D[\"패키징<br>.jar / .war\"]",
    "    D --> E[\"배포<br>서버 실행\"]",
    "    F[\"외부 라이브러리<br>다운로드·관리\"] --> B",
    "```",
    "",
    "빌드 시스템은 이 과정 전체를 **자동화**해줍니다.",
    "",
    "### 빌드 시스템이 하는 일",
    "",
    "| 역할 | 설명 |",
    "|------|------|",
    "| **의존성 관리** | 외부 라이브러리(Spring, JPA 등)를 자동으로 다운로드하고 버전 관리 |",
    "| **컴파일** | `.java` → `.class` 변환 |",
    "| **테스트** | JUnit 등 테스트 코드 자동 실행 |",
    "| **패키징** | 컴파일된 코드를 JAR/WAR 파일로 묶음 |",
    "| **배포** | 빌드된 결과물을 서버에 배포 |",
    "| **멀티 모듈** | 여러 프로젝트(모듈)를 하나로 관리 |",
    "",
    "---",
    "",
    "## IntelliJ 프로젝트 생성 시 빌드 시스템 선택",
    "",
    "IntelliJ IDEA에서 새 프로젝트를 만들 때, **시스템 빌드** 항목에 3가지 선택지가 나타납니다.",
    "",
    "| 선택지 | 정체 | 적합한 상황 |",
    "|--------|------|------------|",
    "| **IntelliJ** | IDE 내장 빌드 (별도 빌드 도구 없음) | 간단한 학습, 알고리즘 연습 |",
    "| **Maven** | XML 기반 빌드 도구 (pom.xml) | 엔터프라이즈 프로젝트, 레거시 |",
    "| **Gradle** | Groovy/Kotlin 기반 빌드 도구 (build.gradle) | Spring Boot, Android, 모던 프로젝트 |",
    "",
    "---",
    "",
    "## 1. IntelliJ 빌드 (IDE 내장)",
    "",
    "IntelliJ IDEA 자체의 빌드 시스템을 사용합니다. Maven이나 Gradle 같은 외부 빌드 도구 없이 IntelliJ가 직접 컴파일하고 실행합니다.",
    "",
    "### 특징",
    "",
    "- 별도의 설정 파일(`pom.xml`, `build.gradle`)이 **없음**",
    "- 라이브러리를 사용하려면 **JAR 파일을 직접 다운로드**하여 프로젝트에 추가해야 함",
    "- IntelliJ 없이는 빌드할 수 없음 (IDE에 종속)",
    "- 팀원 간 환경 공유가 어려움",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "my-project/",
    "├── src/",
    "│   └── Main.java",
    "├── out/              # 컴파일 결과 (IntelliJ가 생성)",
    "└── my-project.iml    # IntelliJ 프로젝트 설정 파일",
    "```",
    "",
    "### 언제 쓰나?",
    "",
    "- Java 문법 학습, 알고리즘 문제 풀이",
    "- 외부 라이브러리가 거의 필요 없는 간단한 프로젝트",
    "- 혼자서 빠르게 테스트할 때",
    "",
    "> **실무나 Spring Boot 프로젝트에서는 사용하지 않습니다.** 의존성 관리가 안 되고 재현 가능한 빌드가 불가능하기 때문입니다.",
    "",
    "---",
    "",
    "## 2. Maven",
    "",
    "**Apache Maven**은 2004년에 등장한 Java 빌드 도구로, **XML 기반의 설정 파일(`pom.xml`)**을 사용합니다. \"Convention over Configuration(설정보다 관례)\" 원칙을 도입하여 프로젝트 구조를 표준화했습니다.",
    "",
    "### pom.xml 예시",
    "",
    "```xml",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<project xmlns=\"http://maven.apache.org/POM/4.0.0\"",
    "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"",
    "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0",
    "         https://maven.apache.org/xsd/maven-4.0.0.xsd\">",
    "    <modelVersion>4.0.0</modelVersion>",
    "",
    "    <parent>",
    "        <groupId>org.springframework.boot</groupId>",
    "        <artifactId>spring-boot-starter-parent</artifactId>",
    "        <version>3.4.3</version>",
    "    </parent>",
    "",
    "    <groupId>com.example</groupId>",
    "    <artifactId>my-project</artifactId>",
    "    <version>0.0.1-SNAPSHOT</version>",
    "    <name>my-project</name>",
    "",
    "    <properties>",
    "        <java.version>21</java.version>",
    "    </properties>",
    "",
    "    <dependencies>",
    "        <dependency>",
    "            <groupId>org.springframework.boot</groupId>",
    "            <artifactId>spring-boot-starter-web</artifactId>",
    "        </dependency>",
    "        <dependency>",
    "            <groupId>org.springframework.boot</groupId>",
    "            <artifactId>spring-boot-starter-data-jpa</artifactId>",
    "        </dependency>",
    "        <dependency>",
    "            <groupId>mysql</groupId>",
    "            <artifactId>mysql-connector-j</artifactId>",
    "            <scope>runtime</scope>",
    "        </dependency>",
    "        <dependency>",
    "            <groupId>org.springframework.boot</groupId>",
    "            <artifactId>spring-boot-starter-test</artifactId>",
    "            <scope>test</scope>",
    "        </dependency>",
    "    </dependencies>",
    "",
    "    <build>",
    "        <plugins>",
    "            <plugin>",
    "                <groupId>org.springframework.boot</groupId>",
    "                <artifactId>spring-boot-maven-plugin</artifactId>",
    "            </plugin>",
    "        </plugins>",
    "    </build>",
    "</project>",
    "```",
    "",
    "### Maven 프로젝트 구조 (표준)",
    "",
    "```",
    "my-project/",
    "├── src/",
    "│   ├── main/",
    "│   │   ├── java/             # 소스 코드",
    "│   │   │   └── com/example/",
    "│   │   │       └── App.java",
    "│   │   └── resources/        # 설정 파일",
    "│   │       └── application.yml",
    "│   └── test/",
    "│       └── java/             # 테스트 코드",
    "├── target/                   # 빌드 결과물",
    "├── pom.xml                   # Maven 설정 파일",
    "└── mvnw / mvnw.cmd           # Maven Wrapper",
    "```",
    "",
    "### Maven 빌드 생명주기",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[validate] --> B[compile]",
    "    B --> C[test]",
    "    C --> D[package]",
    "    D --> E[verify]",
    "    E --> F[install]",
    "    F --> G[deploy]",
    "```",
    "",
    "| 단계 | 설명 |",
    "|------|------|",
    "| `validate` | 프로젝트 구조 검증 |",
    "| `compile` | 소스 코드 컴파일 |",
    "| `test` | 단위 테스트 실행 |",
    "| `package` | JAR/WAR 패키징 |",
    "| `verify` | 통합 테스트 검증 |",
    "| `install` | 로컬 저장소에 설치 |",
    "| `deploy` | 원격 저장소에 배포 |",
    "",
    "### 주요 명령어",
    "",
    "```bash",
    "# Maven Wrapper 사용 (프로젝트에 포함된 Maven)",
    "./mvnw clean compile       # 정리 후 컴파일",
    "./mvnw test                # 테스트 실행",
    "./mvnw package             # JAR/WAR 패키징",
    "./mvnw spring-boot:run     # Spring Boot 실행",
    "",
    "# 전역 Maven 사용",
    "mvn clean install          # 정리 → 컴파일 → 테스트 → 패키징 → 로컬 설치",
    "mvn dependency:tree        # 의존성 트리 확인",
    "```",
    "",
    "### Maven의 의존성 스코프",
    "",
    "| 스코프 | 설명 | 예시 |",
    "|--------|------|------|",
    "| `compile` (기본값) | 컴파일 + 실행 시 모두 포함 | spring-boot-starter-web |",
    "| `runtime` | 실행 시에만 포함 (컴파일에는 불필요) | mysql-connector-j |",
    "| `test` | 테스트 시에만 포함 | spring-boot-starter-test |",
    "| `provided` | 컴파일 시 사용, 실행 시 외부 제공 | servlet-api (Tomcat 제공) |",
    "",
    "### Maven 장단점",
    "",
    "| 장점 | 단점 |",
    "|------|------|",
    "| 안정적, 오랜 역사와 생태계 | XML이 장황하고 가독성 낮음 |",
    "| 표준화된 프로젝트 구조 | 빌드 속도가 Gradle보다 느림 |",
    "| 풍부한 플러그인 | 커스텀 빌드 로직 작성이 어려움 |",
    "| 대부분의 레거시 프로젝트가 Maven 사용 | 멀티 모듈 설정이 복잡함 |",
    "",
    "---",
    "",
    "## 3. Gradle",
    "",
    "**Gradle**은 2012년에 등장한 빌드 도구로, **Groovy** 또는 **Kotlin DSL**로 설정 파일을 작성합니다. Maven의 장점을 가져오면서 단점(XML 장황함, 느린 빌드)을 개선한 현대적인 빌드 시스템입니다.",
    "",
    "### Gradle DSL 선택: Groovy vs Kotlin",
    "",
    "IntelliJ에서 Gradle을 선택하면 **Gradle DSL** 항목에서 Kotlin 또는 Groovy를 선택할 수 있습니다.",
    "",
    "| DSL | 파일명 | 특징 |",
    "|-----|--------|------|",
    "| **Groovy** | `build.gradle` | 기존 방식, 자료가 풍부, 문법이 유연함 |",
    "| **Kotlin** | `build.gradle.kts` | 타입 안전, IDE 자동완성 우수, 최근 추세 |",
    "",
    "### build.gradle (Groovy DSL) 예시",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'",
    "    runtimeOnly 'com.mysql:mysql-connector-j'",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "### build.gradle.kts (Kotlin DSL) 예시",
    "",
    "```kotlin",
    "plugins {",
    "    java",
    "    id(\"org.springframework.boot\") version \"3.4.3\"",
    "    id(\"io.spring.dependency-management\") version \"1.1.7\"",
    "}",
    "",
    "group = \"com.example\"",
    "version = \"0.0.1-SNAPSHOT\"",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion.set(JavaLanguageVersion.of(21))",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation(\"org.springframework.boot:spring-boot-starter-web\")",
    "    implementation(\"org.springframework.boot:spring-boot-starter-data-jpa\")",
    "    runtimeOnly(\"com.mysql:mysql-connector-j\")",
    "    testImplementation(\"org.springframework.boot:spring-boot-starter-test\")",
    "}",
    "",
    "tasks.withType<Test> {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "### Gradle 프로젝트 구조",
    "",
    "```",
    "my-project/",
    "├── src/",
    "│   ├── main/",
    "│   │   ├── java/             # 소스 코드",
    "│   │   └── resources/        # 설정 파일",
    "│   └── test/",
    "│       └── java/             # 테스트 코드",
    "├── build/                    # 빌드 결과물 (Maven의 target/)",
    "├── build.gradle              # Gradle 설정 파일 (또는 .kts)",
    "├── settings.gradle           # 프로젝트 이름, 멀티 모듈 설정",
    "├── gradle/",
    "│   └── wrapper/",
    "│       └── gradle-wrapper.properties  # Gradle 버전 지정",
    "└── gradlew / gradlew.bat     # Gradle Wrapper",
    "```",
    "",
    "### 주요 명령어",
    "",
    "```bash",
    "# Gradle Wrapper 사용 (프로젝트에 포함된 Gradle)",
    "./gradlew build              # 컴파일 + 테스트 + 패키징",
    "./gradlew clean build        # 정리 후 빌드",
    "./gradlew test               # 테스트 실행",
    "./gradlew bootRun            # Spring Boot 실행",
    "./gradlew bootJar            # 실행 가능한 JAR 생성",
    "./gradlew dependencies       # 의존성 트리 확인",
    "",
    "# Windows에서는 gradlew.bat 사용",
    "gradlew.bat build",
    "```",
    "",
    "### Gradle의 의존성 구성 (Dependency Configuration)",
    "",
    "Gradle에서 의존성을 추가할 때 앞에 붙이는 키워드로, **이 라이브러리를 언제, 어디서 사용할지** 결정합니다.",
    "",
    "| 구성 | 컴파일 시 | 실행 시 | 테스트 시 | 최종 JAR 포함 | Maven 대응 |",
    "|------|-----------|---------|-----------|--------------|-----------|",
    "| `implementation` | ✅ | ✅ | ✅ | ✅ | `compile` |",
    "| `runtimeOnly` | ❌ | ✅ | ✅ | ✅ | `runtime` |",
    "| `compileOnly` | ✅ | ❌ | ❌ | ❌ | `provided` |",
    "| `testImplementation` | ❌ | ❌ | ✅ | ❌ | `test` |",
    "| `annotationProcessor` | ✅ (코드 생성) | ❌ | ❌ | ❌ | - |",
    "",
    "### 각 구성의 역할과 예시",
    "",
    "### `implementation` — 가장 기본, 대부분의 라이브러리",
    "",
    "코드를 **작성할 때도, 실행할 때도** 필요한 라이브러리입니다.",
    "",
    "```groovy",
    "implementation 'org.springframework.boot:spring-boot-starter-web'",
    "```",
    "",
    "코드에서 `import`도 하고 실행할 때도 필요하면 `implementation`을 씁니다. **대부분의 라이브러리가 여기에 해당**합니다.",
    "",
    "### `runtimeOnly` — 실행할 때만 필요",
    "",
    "코드에서 직접 `import`하지 않지만, **실행 시에 필요한** 라이브러리입니다.",
    "",
    "```groovy",
    "runtimeOnly 'com.mysql:mysql-connector-j'",
    "```",
    "",
    "대표적으로 **DB 드라이버**가 여기에 해당합니다. 코드에서는 JPA/JDBC라는 표준 인터페이스를 사용하고, 실제로 MySQL에 연결하는 건 드라이버가 실행 시점에 알아서 처리합니다.",
    "",
    "### `compileOnly` — 컴파일할 때만 필요",
    "",
    "코드를 **작성할 때는 필요하지만**, 실행할 때는 빠지는 라이브러리입니다.",
    "",
    "```groovy",
    "compileOnly 'org.projectlombok:lombok'",
    "```",
    "",
    "**Lombok**이 대표적입니다. `@Getter`, `@Setter` 같은 어노테이션은 컴파일 시점에 코드를 생성해주고, 실행 시에는 더 이상 필요 없습니다.",
    "",
    "### `testImplementation` — 테스트 코드에서만 사용",
    "",
    "`src/test/` 폴더의 **테스트 코드에서만** 사용하는 라이브러리입니다. 실제 앱(JAR)에는 포함되지 않습니다.",
    "",
    "```groovy",
    "testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "```",
    "",
    "JUnit, Mockito, AssertJ 같은 테스트 도구가 여기에 해당합니다.",
    "",
    "### `annotationProcessor` — 컴파일 시 코드 자동 생성",
    "",
    "컴파일할 때 어노테이션을 읽어서 **코드를 자동으로 만들어주는** 프로세서입니다.",
    "",
    "```groovy",
    "// Lombok은 compileOnly + annotationProcessor 둘 다 필요",
    "compileOnly 'org.projectlombok:lombok'",
    "annotationProcessor 'org.projectlombok:lombok'",
    "```",
    "",
    "- `compileOnly`: 어노테이션(`@Getter` 등) 자체를 인식하기 위해",
    "- `annotationProcessor`: 그 어노테이션을 보고 getter/setter 등의 **코드를 생성**하기 위해",
    "",
    "### 비유로 정리",
    "",
    "| 구성 | 비유 |",
    "|------|------|",
    "| `implementation` | 항상 가지고 다니는 도구 (망치) |",
    "| `runtimeOnly` | 현장에서만 쓰는 장비 (설계도에는 안 나옴) |",
    "| `compileOnly` | 설계할 때만 쓰는 자 (시공 때는 필요 없음) |",
    "| `testImplementation` | 검수할 때만 쓰는 측정기 (납품에 안 포함) |",
    "| `annotationProcessor` | 설계도를 자동으로 그려주는 AI (결과물만 남김) |",
    "",
    "### Gradle이 Maven보다 빠른 이유",
    "",
    "```mermaid",
    "flowchart TB",
    "    subgraph Gradle[\"Gradle의 빌드 최적화\"]",
    "        IC[\"증분 빌드<br>변경된 파일만 재컴파일\"]",
    "        BC[\"빌드 캐시<br>이전 빌드 결과 재사용\"]",
    "        DM[\"Gradle Daemon<br>백그라운드 프로세스 유지\"]",
    "        PL[\"병렬 실행<br>독립 태스크 동시 수행\"]",
    "    end",
    "    IC --> R[빌드 속도 향상]",
    "    BC --> R",
    "    DM --> R",
    "    PL --> R",
    "```",
    "",
    "| 최적화 기술 | 설명 |",
    "|------------|------|",
    "| **증분 빌드** | 변경된 파일만 다시 컴파일 (전체 재빌드 X) |",
    "| **빌드 캐시** | 이전 빌드 결과를 캐시하여 동일한 작업 건너뜀 |",
    "| **Gradle Daemon** | JVM을 백그라운드에 유지하여 시작 시간 단축 |",
    "| **병렬 실행** | 독립적인 태스크를 동시에 실행 |",
    "",
    "### Gradle 장단점",
    "",
    "| 장점 | 단점 |",
    "|------|------|",
    "| 빌드 속도 빠름 (캐시, 증분 빌드) | 학습 곡선이 Maven보다 높음 |",
    "| Groovy/Kotlin으로 가독성 좋음 | Groovy 문법이 낯설 수 있음 |",
    "| 커스텀 빌드 로직 작성 쉬움 | 버전별 문법 변경이 잦음 |",
    "| Spring Boot 공식 권장 | 디버깅이 어려울 수 있음 |",
    "",
    "---",
    "",
    "## Maven vs Gradle 비교",
    "",
    "### 같은 의존성, 다른 문법",
    "",
    "```xml",
    "<!-- Maven (pom.xml) - 7줄 -->",
    "<dependency>",
    "    <groupId>org.springframework.boot</groupId>",
    "    <artifactId>spring-boot-starter-web</artifactId>",
    "</dependency>",
    "```",
    "",
    "```groovy",
    "// Gradle (build.gradle) - 1줄",
    "implementation 'org.springframework.boot:spring-boot-starter-web'",
    "```",
    "",
    "### 전체 비교",
    "",
    "| 항목 | IntelliJ 빌드 | Maven | Gradle |",
    "|------|-------------|-------|--------|",
    "| 설정 파일 | .iml (IDE 전용) | pom.xml (XML) | build.gradle (Groovy/Kotlin) |",
    "| 의존성 관리 | 수동 (JAR 직접 추가) | 자동 (Maven Central) | 자동 (Maven Central) |",
    "| 빌드 속도 | - | 보통 | 빠름 (캐시, 증분 빌드) |",
    "| IDE 독립성 | ❌ IntelliJ 필수 | ✅ 어디서든 빌드 가능 | ✅ 어디서든 빌드 가능 |",
    "| 설정 가독성 | - | 낮음 (XML 장황) | 높음 (스크립트 기반) |",
    "| 커스텀 로직 | ❌ | 어려움 (플러그인 필요) | 쉬움 (스크립트로 작성) |",
    "| 생태계 | - | 풍부 (오래된 역사) | 빠르게 성장 중 |",
    "| Spring Boot 지원 | ❌ | ✅ | ✅ (공식 권장) |",
    "| Android 지원 | ❌ | ❌ | ✅ (공식 빌드 시스템) |",
    "| 학습 난이도 | 쉬움 | 보통 | 약간 높음 |",
    "",
    "### 명령어 비교",
    "",
    "| 동작 | Maven | Gradle |",
    "|------|-------|--------|",
    "| 정리 | `mvn clean` | `gradle clean` |",
    "| 컴파일 | `mvn compile` | `gradle compileJava` |",
    "| 테스트 | `mvn test` | `gradle test` |",
    "| 패키징 | `mvn package` | `gradle build` |",
    "| Spring Boot 실행 | `mvn spring-boot:run` | `gradle bootRun` |",
    "| 의존성 트리 | `mvn dependency:tree` | `gradle dependencies` |",
    "",
    "---",
    "",
    "## Wrapper란? (mvnw / gradlew)",
    "",
    "**Wrapper**는 프로젝트에 빌드 도구의 특정 버전을 포함시켜, 컴퓨터에 Maven/Gradle이 설치되어 있지 않아도 빌드할 수 있게 해줍니다.",
    "",
    "```bash",
    "# 팀원 A의 PC에 Gradle이 없어도",
    "# gradlew가 자동으로 지정된 버전의 Gradle을 다운로드하여 실행",
    "./gradlew build",
    "",
    "# Maven도 마찬가지",
    "./mvnw package",
    "```",
    "",
    "| 장점 | 설명 |",
    "|------|------|",
    "| 환경 통일 | 모든 팀원이 동일한 빌드 도구 버전 사용 |",
    "| 설치 불필요 | 빌드 도구가 없어도 프로젝트 빌드 가능 |",
    "| CI/CD 편리 | 서버에 별도 설치 없이 빌드 가능 |",
    "",
    "---",
    "",
    "## 의존성 저장소 (Repository)",
    "",
    "Maven과 Gradle 모두 **Maven Central**이라는 중앙 저장소에서 라이브러리를 다운로드합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"build.gradle<br>또는 pom.xml\"] -->|의존성 선언| B[\"빌드 도구<br>(Maven/Gradle)\"]",
    "    B -->|다운로드| C[\"Maven Central<br>(중앙 저장소)\"]",
    "    C -->|JAR 파일| D[\"로컬 캐시<br>(~/.m2 또는 ~/.gradle)\"]",
    "    D -->|참조| E[\"프로젝트 빌드\"]",
    "```",
    "",
    "| 저장소 | 설명 |",
    "|--------|------|",
    "| **Maven Central** | 가장 큰 공개 저장소 (search.maven.org) |",
    "| **로컬 캐시** | 한 번 다운로드하면 로컬에 캐싱 (`~/.m2/repository` 또는 `~/.gradle/caches`) |",
    "| **사설 저장소** | 회사 내부 라이브러리용 (Nexus, Artifactory) |",
    "",
    "---",
    "",
    "## 어떤 것을 선택해야 할까?",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q[\"프로젝트 용도?\"] -->|학습/알고리즘| A[\"IntelliJ 빌드\"]",
    "    Q -->|실무/Spring Boot| B{\"팀/회사 기준?\"}",
    "    B -->|기존 프로젝트가 Maven| C[\"Maven\"]",
    "    B -->|새 프로젝트| D[\"Gradle (권장)\"]",
    "    B -->|Android 개발| E[\"Gradle (필수)\"]",
    "    style A fill:#6c757d,color:#fff",
    "    style C fill:#e85d04,color:#fff",
    "    style D fill:#198754,color:#fff",
    "    style E fill:#198754,color:#fff",
    "```",
    "",
    "| 상황 | 추천 |",
    "|------|------|",
    "| Java 문법 학습, 간단한 코드 실행 | **IntelliJ 빌드** |",
    "| 기존 레거시 프로젝트 유지보수 | **Maven** (기존 것 유지) |",
    "| 새로운 Spring Boot 프로젝트 | **Gradle** (Spring Initializr 기본값) |",
    "| Android 앱 개발 | **Gradle** (필수) |",
    "| 팀에서 Maven을 쓰고 있다면 | **Maven** (굳이 바꿀 필요 없음) |",
    "",
    "> **Spring Initializr**(start.spring.io)에서 프로젝트를 생성하면 기본값이 **Gradle - Groovy**입니다. 새 Spring Boot 프로젝트라면 Gradle을 선택하는 것이 일반적입니다.",
    "",
    "---",
    "",
    "## 라이브러리 추가하는 방법",
    "",
    "npm에서 `npm install axios`처럼, Maven/Gradle에서도 설정 파일에 라이브러리를 한 줄 추가하면 자동으로 다운로드됩니다.",
    "",
    "### 1단계: 라이브러리 검색",
    "",
    "아래 사이트에서 원하는 라이브러리를 검색하면 Maven/Gradle 의존성 코드를 복사할 수 있습니다.",
    "",
    "| 사이트 | URL | 설명 |",
    "|--------|-----|------|",
    "| **Maven Central** | [search.maven.org](https://search.maven.org) | 공식 중앙 저장소 검색 (가장 정확) |",
    "| **MVN Repository** | [mvnrepository.com](https://mvnrepository.com) | 가장 인기 있는 검색 사이트 (사용량, 버전 정보 풍부) |",
    "| **Spring Initializr** | [start.spring.io](https://start.spring.io) | Spring Boot 프로젝트 생성 시 의존성을 UI로 선택 |",
    "| **Gradle Plugin Portal** | [plugins.gradle.org](https://plugins.gradle.org) | Gradle 플러그인 전용 검색 |",
    "",
    "> **추천**: [mvnrepository.com](https://mvnrepository.com)이 가장 사용하기 편합니다. 라이브러리를 검색하면 Maven, Gradle (Groovy/Kotlin) 코드를 탭으로 바로 복사할 수 있습니다.",
    "",
    "### 2단계: 의존성 코드 복사 & 붙여넣기",
    "",
    "예를 들어 **Lombok** 라이브러리를 추가한다고 가정하겠습니다.",
    "",
    "### Maven에 추가 (pom.xml)",
    "",
    "```xml",
    "<!-- pom.xml의 <dependencies> 안에 추가 -->",
    "<dependencies>",
    "    <!-- 기존 의존성들... -->",
    "",
    "    <!-- Lombok 추가 -->",
    "    <dependency>",
    "        <groupId>org.projectlombok</groupId>",
    "        <artifactId>lombok</artifactId>",
    "        <version>1.18.36</version>",
    "        <scope>provided</scope>",
    "    </dependency>",
    "</dependencies>",
    "```",
    "",
    "### Gradle에 추가 (build.gradle - Groovy)",
    "",
    "```groovy",
    "// build.gradle의 dependencies 블록 안에 추가",
    "dependencies {",
    "    // 기존 의존성들...",
    "",
    "    // Lombok 추가",
    "    compileOnly 'org.projectlombok:lombok:1.18.36'",
    "    annotationProcessor 'org.projectlombok:lombok:1.18.36'",
    "}",
    "```",
    "",
    "### Gradle에 추가 (build.gradle.kts - Kotlin)",
    "",
    "```kotlin",
    "// build.gradle.kts의 dependencies 블록 안에 추가",
    "dependencies {",
    "    // 기존 의존성들...",
    "",
    "    // Lombok 추가",
    "    compileOnly(\"org.projectlombok:lombok:1.18.36\")",
    "    annotationProcessor(\"org.projectlombok:lombok:1.18.36\")",
    "}",
    "```",
    "",
    "### 3단계: 의존성 동기화",
    "",
    "설정 파일을 수정한 후 라이브러리를 실제로 다운로드해야 합니다.",
    "",
    "| 방법 | 설명 |",
    "|------|------|",
    "| **IntelliJ 자동 감지** | 파일 수정 시 우상단에 나타나는 🔄 새로고침 아이콘 클릭 |",
    "| **Maven 명령어** | `./mvnw dependency:resolve` 또는 우클릭 → Maven → Reload Project |",
    "| **Gradle 명령어** | `./gradlew build --refresh-dependencies` 또는 우클릭 → Gradle → Reload |",
    "| **단축키 (IntelliJ)** | `Ctrl + Shift + O` (Maven/Gradle 프로젝트 동기화) |",
    "",
    "---",
    "",
    "## 자주 사용하는 라이브러리 예시",
    "",
    "### Spring Boot 관련",
    "",
    "| 라이브러리 | Gradle 의존성 | 용도 |",
    "|-----------|--------------|------|",
    "| Spring Web | `implementation 'org.springframework.boot:spring-boot-starter-web'` | REST API, 웹 MVC |",
    "| Spring Data JPA | `implementation 'org.springframework.boot:spring-boot-starter-data-jpa'` | DB 접근 (ORM) |",
    "| Spring Security | `implementation 'org.springframework.boot:spring-boot-starter-security'` | 인증/인가 |",
    "| Spring Validation | `implementation 'org.springframework.boot:spring-boot-starter-validation'` | 입력값 검증 |",
    "| Actuator | `implementation 'org.springframework.boot:spring-boot-starter-actuator'` | 모니터링 |",
    "",
    "### 데이터베이스 드라이버",
    "",
    "| 라이브러리 | Gradle 의존성 | 용도 |",
    "|-----------|--------------|------|",
    "| MySQL | `runtimeOnly 'com.mysql:mysql-connector-j'` | MySQL 연결 |",
    "| PostgreSQL | `runtimeOnly 'org.postgresql:postgresql'` | PostgreSQL 연결 |",
    "| H2 | `runtimeOnly 'com.h2database:h2'` | 인메모리 DB (테스트용) |",
    "| MariaDB | `runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'` | MariaDB 연결 |",
    "",
    "### 유틸리티",
    "",
    "| 라이브러리 | Gradle 의존성 | 용도 |",
    "|-----------|--------------|------|",
    "| Lombok | `compileOnly 'org.projectlombok:lombok'` | getter/setter 등 보일러플레이트 제거 |",
    "| MapStruct | `implementation 'org.mapstruct:mapstruct:1.6.3'` | DTO ↔ Entity 자동 매핑 |",
    "| Jackson | Spring Web에 포함 | JSON 직렬화/역직렬화 |",
    "| Querydsl | `implementation 'com.querydsl:querydsl-jpa'` | 타입 안전 동적 쿼리 |",
    "",
    "### 테스트",
    "",
    "| 라이브러리 | Gradle 의존성 | 용도 |",
    "|-----------|--------------|------|",
    "| Spring Test | `testImplementation 'org.springframework.boot:spring-boot-starter-test'` | JUnit 5 + Mockito + AssertJ |",
    "| Testcontainers | `testImplementation 'org.testcontainers:junit-jupiter'` | Docker 기반 통합 테스트 |",
    "",
    "---",
    "",
    "## npm과 비교 (JavaScript 개발자를 위한 정리)",
    "",
    "| npm (JavaScript) | Maven / Gradle (Java) |",
    "|------------------|-----------------------|",
    "| `npm install axios` | pom.xml 또는 build.gradle에 의존성 추가 |",
    "| `package.json` | `pom.xml` / `build.gradle` |",
    "| `node_modules/` | `~/.m2/repository/` / `~/.gradle/caches/` |",
    "| `npmjs.com`에서 검색 | `mvnrepository.com`에서 검색 |",
    "| `npm install` (전체 설치) | `mvn install` / `gradle build` |",
    "| `npm update` (업데이트) | 버전 번호를 직접 수정 후 동기화 |",
    "",
    "---",
    "",
    "### 요약",
    "IntelliJ의 **시스템 빌드**에서 선택하는 3가지는 프로젝트의 **의존성 관리, 컴파일, 패키징을 누가 담당하느냐**의 차이입니다. **IntelliJ 빌드**는 IDE에 종속되어 간단한 학습용에만 적합하고, **Maven**은 XML 기반의 안정적인 표준 빌드 도구, **Gradle**은 빠른 빌드 속도와 간결한 스크립트를 제공하는 현대적 빌드 도구입니다. 라이브러리를 추가하려면 [mvnrepository.com](https://mvnrepository.com)에서 검색한 뒤 `pom.xml` 또는 `build.gradle`에 의존성 코드를 붙여넣고 동기화하면 됩니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
