<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-h2",
  title: "Spring Boot H2 데이터베이스 완전 정리 - 설정, 콘솔, 테스트, 운영 전환까지",
  date: "2026-03-03",
  summary: "H2 데이터베이스의 개념, 인메모리/파일 모드 차이, Spring Boot 연동 설정, H2 Console 사용법, JPA와 함께 사용하기, 초기 데이터 로딩, 테스트 활용, MySQL/PostgreSQL로 전환하는 방법까지 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot", "h2", "database", "jpa", "test", "inmemory", "backend"],
  content: [
    "## H2 데이터베이스란?",
    "",
    "**H2**는 Java로 작성된 **경량 관계형 데이터베이스**입니다. 별도의 설치 없이 **의존성만 추가하면** 바로 사용할 수 있어, 개발과 테스트에 매우 유용합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph \"일반 DB (MySQL, PostgreSQL)\"",
    "        A1[\"별도 서버 설치\"] --> B1[\"서버 실행\"] --> C1[\"연결 설정\"]",
    "    end",
    "    subgraph \"H2\"",
    "        A2[\"의존성 추가만 하면 끝\"] --> B2[\"자동 실행\"]",
    "    end",
    "```",
    "",
    "### H2의 특징",
    "",
    "| 특징 | 설명 |",
    "|------|------|",
    "| **경량** | JAR 파일 하나 (~2MB)로 동작 |",
    "| **빠름** | 인메모리 모드에서 매우 빠른 읽기/쓰기 |",
    "| **설치 불필요** | Gradle/Maven 의존성만 추가하면 됨 |",
    "| **웹 콘솔** | 브라우저에서 SQL을 실행할 수 있는 **H2 Console** 내장 |",
    "| **호환성** | MySQL, PostgreSQL 등의 **호환 모드** 제공 |",
    "| **두 가지 모드** | 인메모리(RAM) / 파일(디스크) 모드 선택 가능 |",
    "",
    "### 언제 사용하나?",
    "",
    "| 상황 | 적합 여부 |",
    "|------|----------|",
    "| 개발 중 빠른 프로토타이핑 | **적합** |",
    "| 단위/통합 테스트 | **매우 적합** |",
    "| 학습, 튜토리얼 | **매우 적합** |",
    "| 운영(프로덕션) 서버 | **부적합** (MySQL, PostgreSQL 등 사용) |",
    "",
    "---",
    "",
    "## 인메모리 모드 vs 파일 모드",
    "",
    "| 항목 | 인메모리 모드 | 파일 모드 |",
    "|------|-------------|----------|",
    "| JDBC URL | `jdbc:h2:mem:testdb` | `jdbc:h2:file:./data/mydb` |",
    "| 데이터 저장 | **RAM** (메모리) | **디스크** (파일) |",
    "| 서버 종료 시 | **데이터 삭제됨** | **데이터 유지됨** |",
    "| 속도 | 매우 빠름 | 빠름 |",
    "| 용도 | 테스트, 개발 | 로컬 데이터 유지 필요 시 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q{\"서버 재시작 후에도\<br>데이터가 필요한가?\"}",
    "    Q -->|\"아니오\"| A[\"인메모리 모드\<br>jdbc:h2:mem:testdb\"]",
    "    Q -->|\"예\"| B[\"파일 모드\<br>jdbc:h2:file:./data/mydb\"]",
    "```",
    "",
    "---",
    "",
    "## 프로젝트 설정",
    "",
    "### 인텔리제이에서 프로젝트 만들기",
    "",
    "1. IntelliJ IDEA → `New Project` → **Spring Initializr** 선택",
    "2. 프로젝트 정보 입력:",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | `springboot_h2_example` |",
    "| **Language** | Java |",
    "| **Build System** | Gradle - Groovy |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "3. Dependencies 선택:",
    "",
    "| 카테고리 | 의존성 |",
    "|----------|--------|",
    "| Developer Tools | **Lombok** |",
    "| Web | **Spring Web** |",
    "| SQL | **Spring Data JPA** |",
    "| SQL | **H2 Database** |",
    "",
    "4. `Create` 클릭하여 프로젝트 생성",
    "",
    "### build.gradle",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '1.0-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'",
    "    implementation 'org.springframework.boot:spring-boot-starter-validation'",
    "",
    "    runtimeOnly 'com.h2database:h2'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "test {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "> `runtimeOnly`로 H2를 추가합니다. 컴파일 시에는 필요 없고 **실행 시**에만 사용되기 때문입니다.",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── DemoApplication.java",
    "├── entity/",
    "│   └── Member.java",
    "├── repository/",
    "│   └── MemberRepository.java",
    "├── service/",
    "│   └── MemberService.java",
    "├── controller/",
    "│   └── MemberController.java",
    "└── dto/",
    "    ├── CreateMemberRequest.java",
    "    └── MemberResponse.java",
    "",
    "src/main/resources/",
    "├── application.yml",
    "└── data.sql",
    "```",
    "",
    "### DemoApplication.java",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### Member.java (Entity)",
    "",
    "```java",
    "package com.example.demo.entity;",
    "",
    "import jakarta.persistence.*;",
    "import lombok.*;",
    "",
    "@Entity",
    "@Getter",
    "@NoArgsConstructor(access = AccessLevel.PROTECTED)",
    "@AllArgsConstructor",
    "@Builder",
    "public class Member {",
    "",
    "    @Id",
    "    @GeneratedValue(strategy = GenerationType.IDENTITY)",
    "    private Long id;",
    "",
    "    @Column(nullable = false)",
    "    private String name;",
    "",
    "    @Column(nullable = false, unique = true)",
    "    private String email;",
    "",
    "    @Column(nullable = false)",
    "    private int age;",
    "}",
    "```",
    "",
    "### MemberRepository.java",
    "",
    "```java",
    "package com.example.demo.repository;",
    "",
    "import com.example.demo.entity.Member;",
    "import org.springframework.data.jpa.repository.JpaRepository;",
    "",
    "public interface MemberRepository extends JpaRepository<Member, Long> {",
    "}",
    "```",
    "",
    "### MemberService.java",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import com.example.demo.dto.CreateMemberRequest;",
    "import com.example.demo.dto.MemberResponse;",
    "import com.example.demo.entity.Member;",
    "import com.example.demo.repository.MemberRepository;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.stereotype.Service;",
    "import org.springframework.transaction.annotation.Transactional;",
    "",
    "import java.util.List;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "@Transactional(readOnly = true)",
    "public class MemberService {",
    "",
    "    private final MemberRepository memberRepository;",
    "",
    "    @Transactional",
    "    public MemberResponse create(CreateMemberRequest request) {",
    "        Member member = Member.builder()",
    "                .name(request.getName())",
    "                .email(request.getEmail())",
    "                .age(request.getAge())",
    "                .build();",
    "        return MemberResponse.from(memberRepository.save(member));",
    "    }",
    "",
    "    public List<MemberResponse> findAll() {",
    "        return memberRepository.findAll().stream()",
    "                .map(MemberResponse::from)",
    "                .toList();",
    "    }",
    "",
    "    public MemberResponse findById(Long id) {",
    "        Member member = memberRepository.findById(id)",
    "                .orElseThrow(() -> new IllegalArgumentException(\"회원을 찾을 수 없습니다. id=\" + id));",
    "        return MemberResponse.from(member);",
    "    }",
    "",
    "    @Transactional",
    "    public void delete(Long id) {",
    "        memberRepository.deleteById(id);",
    "    }",
    "}",
    "```",
    "",
    "### MemberController.java",
    "",
    "```java",
    "package com.example.demo.controller;",
    "",
    "import com.example.demo.dto.CreateMemberRequest;",
    "import com.example.demo.dto.MemberResponse;",
    "import com.example.demo.service.MemberService;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "import java.util.List;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/members\")",
    "@RequiredArgsConstructor",
    "public class MemberController {",
    "",
    "    private final MemberService memberService;",
    "",
    "    @PostMapping",
    "    public ResponseEntity<MemberResponse> create(@RequestBody CreateMemberRequest request) {",
    "        return ResponseEntity.ok(memberService.create(request));",
    "    }",
    "",
    "    @GetMapping",
    "    public ResponseEntity<List<MemberResponse>> findAll() {",
    "        return ResponseEntity.ok(memberService.findAll());",
    "    }",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public ResponseEntity<MemberResponse> findById(@PathVariable Long id) {",
    "        return ResponseEntity.ok(memberService.findById(id));",
    "    }",
    "",
    "    @DeleteMapping(\"/{id}\")",
    "    public ResponseEntity<Void> delete(@PathVariable Long id) {",
    "        memberService.delete(id);",
    "        return ResponseEntity.noContent().build();",
    "    }",
    "}",
    "```",
    "",
    "### CreateMemberRequest.java (요청 DTO)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import lombok.Getter;",
    "import lombok.NoArgsConstructor;",
    "",
    "@Getter",
    "@NoArgsConstructor",
    "public class CreateMemberRequest {",
    "    private String name;",
    "    private String email;",
    "    private int age;",
    "}",
    "```",
    "",
    "### MemberResponse.java (응답 DTO)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import com.example.demo.entity.Member;",
    "import lombok.Builder;",
    "import lombok.Getter;",
    "",
    "@Getter",
    "@Builder",
    "public class MemberResponse {",
    "    private Long id;",
    "    private String name;",
    "    private String email;",
    "    private int age;",
    "",
    "    public static MemberResponse from(Member member) {",
    "        return MemberResponse.builder()",
    "                .id(member.getId())",
    "                .name(member.getName())",
    "                .email(member.getEmail())",
    "                .age(member.getAge())",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "### application.yml",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb",
    "    driver-class-name: org.h2.Driver",
    "    username: sa",
    "    password:",
    "  h2:",
    "    console:",
    "      enabled: true",
    "      path: /h2-console",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: create-drop",
    "    show-sql: true",
    "    properties:",
    "      hibernate:",
    "        format_sql: true",
    "    defer-datasource-initialization: true",
    "  sql:",
    "    init:",
    "      mode: always",
    "```",
    "",
    "### data.sql (초기 데이터)",
    "",
    "```sql",
    "-- src/main/resources/data.sql",
    "INSERT INTO member (name, email, age) VALUES ('홍길동', 'hong@example.com', 25);",
    "INSERT INTO member (name, email, age) VALUES ('김철수', 'kim@example.com', 30);",
    "INSERT INTO member (name, email, age) VALUES ('이영희', 'lee@example.com', 28);",
    "```",
    "",
    "### 테스트 (Postman)",
    "",
    "애플리케이션을 실행한 후 Postman으로 API를 테스트합니다.",
    "",
    "**1. 전체 회원 조회 (GET)**",
    "",
    "```",
    "GET http://localhost:8080/api/members",
    "```",
    "",
    "초기 데이터(`data.sql`)로 등록된 3명이 조회됩니다.",
    "",
    "**2. 회원 등록 (POST)**",
    "",
    "```",
    "POST http://localhost:8080/api/members",
    "Content-Type: application/json",
    "",
    "{",
    "    \"name\": \"박지민\",",
    "    \"email\": \"park@example.com\",",
    "    \"age\": 22",
    "}",
    "```",
    "",
    "**3. 단건 조회 (GET)**",
    "",
    "```",
    "GET http://localhost:8080/api/members/1",
    "```",
    "",
    "**4. 회원 삭제 (DELETE)**",
    "",
    "```",
    "DELETE http://localhost:8080/api/members/1",
    "```",
    "",
    "**5. H2 Console 접속**",
    "",
    "브라우저에서 `http://localhost:8080/h2-console` 접속 후 아래 정보로 로그인합니다.",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| JDBC URL | `jdbc:h2:mem:testdb` |",
    "| User Name | `sa` |",
    "| Password | (빈칸) |",
    "",
    "로그인 후 `SELECT * FROM MEMBER;` 쿼리로 데이터를 확인할 수 있습니다.",
    "",
    "---",
    "",
    "## 인메모리 모드 설정",
    "",
    "가장 기본적인 설정입니다. 서버를 재시작하면 데이터가 초기화됩니다.",
    "",
    "```yaml",
    "# application.yml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb",
    "    driver-class-name: org.h2.Driver",
    "    username: sa",
    "    password:",
    "  h2:",
    "    console:",
    "      enabled: true",
    "      path: /h2-console",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: create",
    "    show-sql: true",
    "    properties:",
    "      hibernate:",
    "        format_sql: true",
    "```",
    "",
    "| 설정 | 설명 |",
    "|------|------|",
    "| `url: jdbc:h2:mem:testdb` | 인메모리 모드, DB 이름은 `testdb` |",
    "| `username: sa` | 기본 사용자명 (`sa` = System Administrator) |",
    "| `password:` | 비밀번호 없음 (빈 문자열) |",
    "| `h2.console.enabled: true` | **H2 Console** 활성화 |",
    "| `h2.console.path: /h2-console` | 콘솔 접속 경로 |",
    "| `ddl-auto: create` | 시작 시 테이블 자동 생성 (기존 테이블 삭제 후 재생성) |",
    "| `show-sql: true` | 실행되는 SQL을 콘솔에 출력 |",
    "| `format_sql: true` | SQL을 보기 좋게 포맷팅 |",
    "",
    "---",
    "",
    "## 파일 모드 설정",
    "",
    "서버를 재시작해도 데이터가 **유지**됩니다.",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:file:./data/mydb",
    "    driver-class-name: org.h2.Driver",
    "    username: sa",
    "    password: mypassword",
    "  h2:",
    "    console:",
    "      enabled: true",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: update",
    "```",
    "",
    "> 프로젝트 루트에 `data/` 디렉토리가 생기고, `mydb.mv.db` 파일에 데이터가 저장됩니다. `ddl-auto: update`로 설정하면 기존 데이터를 유지하면서 스키마만 변경합니다.",
    "",
    "### ddl-auto 옵션",
    "",
    "| 값 | 동작 | 용도 |",
    "|---|------|------|",
    "| `create` | 시작 시 테이블 **삭제 후 재생성** | 개발 (인메모리) |",
    "| `create-drop` | 시작 시 생성, **종료 시 삭제** | 테스트 |",
    "| `update` | 변경된 부분만 **반영** (기존 데이터 유지) | 개발 (파일 모드) |",
    "| `validate` | 스키마만 **검증** (변경 안 함) | 운영 |",
    "| `none` | 아무것도 안 함 | 운영 (Flyway/Liquibase 사용) |",
    "",
    "---",
    "",
    "## H2 Console 사용하기",
    "",
    "H2 Console은 **브라우저에서 SQL을 실행**할 수 있는 웹 기반 관리 도구입니다.",
    "",
    "### 접속 방법",
    "",
    "1. 애플리케이션 실행",
    "2. 브라우저에서 `http://localhost:8080/h2-console` 접속",
    "3. 로그인 정보 입력",
    "",
    "| 항목 | 인메모리 모드 | 파일 모드 |",
    "|------|-------------|----------|",
    "| JDBC URL | `jdbc:h2:mem:testdb` | `jdbc:h2:file:./data/mydb` |",
    "| User Name | `sa` | `sa` |",
    "| Password | (빈칸) | `mypassword` |",
    "",
    "### H2 Console에서 할 수 있는 것",
    "",
    "```sql",
    "-- 테이블 목록 확인",
    "SHOW TABLES;",
    "",
    "-- 데이터 조회",
    "SELECT * FROM USERS;",
    "",
    "-- 데이터 삽입",
    "INSERT INTO USERS (NAME, EMAIL) VALUES ('테스트', 'test@test.com');",
    "",
    "-- 테이블 구조 확인",
    "SHOW COLUMNS FROM USERS;",
    "",
    "-- 데이터 삭제",
    "DELETE FROM USERS WHERE ID = 1;",
    "",
    "-- 전체 삭제",
    "TRUNCATE TABLE USERS;",
    "```",
    "",
    "### Spring Security 사용 시 H2 Console 접근 허용",
    "",
    "Spring Security를 사용하면 H2 Console이 차단될 수 있습니다.",
    "",
    "```java",
    "@Configuration",
    "@EnableWebSecurity",
    "public class SecurityConfig {",
    "",
    "    @Bean",
    "    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {",
    "        http",
    "            .csrf(csrf -> csrf.disable())",
    "            .headers(headers -> headers.frameOptions(",
    "                    frameOptions -> frameOptions.sameOrigin()))",
    "            .authorizeHttpRequests(auth -> auth",
    "                    .requestMatchers(\"/h2-console/**\").permitAll()",
    "                    .anyRequest().authenticated()",
    "            );",
    "        return http.build();",
    "    }",
    "}",
    "```",
    "",
    "> H2 Console은 `<iframe>`을 사용하므로 `frameOptions.sameOrigin()`이 필요합니다. CSRF도 비활성화해야 콘솔에서 SQL을 실행할 수 있습니다.",
    "",
    "---",
    "",
    "## JPA Entity + Repository 예제",
    "",
    "### Entity",
    "",
    "```java",
    "@Entity",
    "@Table(name = \"users\")",
    "@Getter",
    "@NoArgsConstructor(access = AccessLevel.PROTECTED)",
    "@Builder",
    "@AllArgsConstructor(access = AccessLevel.PRIVATE)",
    "public class User {",
    "",
    "    @Id",
    "    @GeneratedValue(strategy = GenerationType.IDENTITY)",
    "    private Long id;",
    "",
    "    @Column(nullable = false)",
    "    private String name;",
    "",
    "    @Column(nullable = false, unique = true)",
    "    private String email;",
    "",
    "    @Column(nullable = false)",
    "    private int age;",
    "}",
    "```",
    "",
    "### Repository",
    "",
    "```java",
    "public interface UserRepository extends JpaRepository<User, Long> {",
    "    Optional<User> findByEmail(String email);",
    "    List<User> findByAgeGreaterThanEqual(int age);",
    "    boolean existsByEmail(String email);",
    "}",
    "```",
    "",
    "### 실행 시 자동 생성되는 테이블",
    "",
    "```sql",
    "-- ddl-auto: create 설정 시 Hibernate가 자동 생성",
    "CREATE TABLE users (",
    "    id BIGINT GENERATED BY DEFAULT AS IDENTITY,",
    "    name VARCHAR(255) NOT NULL,",
    "    email VARCHAR(255) NOT NULL UNIQUE,",
    "    age INTEGER NOT NULL,",
    "    PRIMARY KEY (id)",
    ");",
    "```",
    "",
    "---",
    "",
    "## 초기 데이터 로딩",
    "",
    "### 방법 1: data.sql 파일",
    "",
    "`src/main/resources/data.sql` 파일에 SQL을 작성하면 **시작 시 자동 실행**됩니다.",
    "",
    "```sql",
    "-- src/main/resources/data.sql",
    "INSERT INTO users (name, email, age) VALUES ('홍길동', 'hong@example.com', 25);",
    "INSERT INTO users (name, email, age) VALUES ('김철수', 'kim@example.com', 30);",
    "INSERT INTO users (name, email, age) VALUES ('이영희', 'lee@example.com', 28);",
    "```",
    "",
    "```yaml",
    "# application.yml - data.sql 사용 시 필요한 설정",
    "spring:",
    "  jpa:",
    "    defer-datasource-initialization: true",
    "  sql:",
    "    init:",
    "      mode: always",
    "```",
    "",
    "> `defer-datasource-initialization: true`가 없으면 Hibernate가 테이블을 생성하기 **전에** `data.sql`이 실행되어 오류가 발생합니다.",
    "",
    "### 방법 2: schema.sql + data.sql",
    "",
    "```sql",
    "-- src/main/resources/schema.sql (테이블 직접 정의)",
    "CREATE TABLE IF NOT EXISTS users (",
    "    id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "    name VARCHAR(255) NOT NULL,",
    "    email VARCHAR(255) NOT NULL UNIQUE,",
    "    age INT NOT NULL",
    ");",
    "```",
    "",
    "```yaml",
    "spring:",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: none",
    "  sql:",
    "    init:",
    "      mode: always",
    "```",
    "",
    "> `ddl-auto: none`으로 하고 `schema.sql`로 직접 테이블을 만드는 방식입니다.",
    "",
    "### 방법 3: CommandLineRunner (Java 코드)",
    "",
    "```java",
    "@Component",
    "@RequiredArgsConstructor",
    "public class DataInitializer implements CommandLineRunner {",
    "",
    "    private final UserRepository userRepository;",
    "",
    "    @Override",
    "    public void run(String... args) {",
    "        userRepository.save(User.builder().name(\"홍길동\").email(\"hong@example.com\").age(25).build());",
    "        userRepository.save(User.builder().name(\"김철수\").email(\"kim@example.com\").age(30).build());",
    "        userRepository.save(User.builder().name(\"이영희\").email(\"lee@example.com\").age(28).build());",
    "",
    "        System.out.println(\"초기 데이터 \" + userRepository.count() + \"건 로딩 완료\");",
    "    }",
    "}",
    "```",
    "",
    "| 방법 | 장점 | 단점 |",
    "|------|------|------|",
    "| `data.sql` | SQL 파일로 관리, 간편 | JPA Entity와 불일치 가능 |",
    "| `schema.sql` + `data.sql` | 테이블 구조까지 직접 제어 | `ddl-auto: none` 필요 |",
    "| **CommandLineRunner** | **Java 코드로 유연, Entity 사용** | SQL 직접 제어는 불가 |",
    "",
    "---",
    "",
    "## 테스트에서 H2 사용하기",
    "",
    "Spring Boot 테스트에서 H2는 **독립적인 테스트 환경**을 제공합니다.",
    "",
    "### @DataJpaTest (기본적으로 H2 사용)",
    "",
    "```java",
    "@DataJpaTest",
    "@DisplayName(\"UserRepository 테스트\")",
    "class UserRepositoryTest {",
    "",
    "    @Autowired",
    "    private UserRepository userRepository;",
    "",
    "    @BeforeEach",
    "    void setUp() {",
    "        userRepository.save(User.builder().name(\"홍길동\").email(\"hong@test.com\").age(25).build());",
    "        userRepository.save(User.builder().name(\"김철수\").email(\"kim@test.com\").age(30).build());",
    "    }",
    "",
    "    @Test",
    "    @DisplayName(\"이메일로 사용자를 조회할 수 있다\")",
    "    void findByEmail() {",
    "        // given",
    "        String email = \"hong@test.com\";",
    "",
    "        // when",
    "        Optional<User> user = userRepository.findByEmail(email);",
    "",
    "        // then",
    "        assertThat(user).isPresent();",
    "        assertThat(user.get().getName()).isEqualTo(\"홍길동\");",
    "    }",
    "",
    "    @Test",
    "    @DisplayName(\"30세 이상 사용자를 조회할 수 있다\")",
    "    void findByAge() {",
    "        // when",
    "        List<User> users = userRepository.findByAgeGreaterThanEqual(30);",
    "",
    "        // then",
    "        assertThat(users).hasSize(1);",
    "        assertThat(users.get(0).getName()).isEqualTo(\"김철수\");",
    "    }",
    "}",
    "```",
    "",
    "> `@DataJpaTest`는 기본적으로 H2 인메모리 DB를 사용하고, 각 테스트 후 **자동 롤백**됩니다.",
    "",
    "### 테스트 전용 설정 파일",
    "",
    "`src/test/resources/application.yml`에 테스트 전용 설정을 두면 메인 설정과 분리됩니다.",
    "",
    "```yaml",
    "# src/test/resources/application.yml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb",
    "    driver-class-name: org.h2.Driver",
    "    username: sa",
    "    password:",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: create-drop",
    "    show-sql: true",
    "```",
    "",
    "---",
    "",
    "## H2 호환 모드",
    "",
    "운영에서 MySQL이나 PostgreSQL을 사용하지만, 개발/테스트에서는 H2를 쓰고 싶을 때 **호환 모드**를 사용합니다.",
    "",
    "```yaml",
    "# MySQL 호환 모드",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb;MODE=MySQL",
    "",
    "# PostgreSQL 호환 모드",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb;MODE=PostgreSQL",
    "```",
    "",
    "| 호환 모드 | JDBC URL 파라미터 |",
    "|----------|------------------|",
    "| MySQL | `MODE=MySQL` |",
    "| PostgreSQL | `MODE=PostgreSQL` |",
    "| Oracle | `MODE=Oracle` |",
    "| SQL Server | `MODE=MSSQLServer` |",
    "",
    "> 호환 모드는 기본적인 SQL 문법을 맞춰주지만, 100% 호환은 아닙니다. DB 고유 함수나 고급 기능은 동작하지 않을 수 있습니다.",
    "",
    "---",
    "",
    "## 프로파일별 DB 전환 (개발: H2 → 운영: MySQL)",
    "",
    "개발 환경에서는 H2, 운영 환경에서는 MySQL을 사용하는 가장 일반적인 패턴입니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"application.yml\<br>공통 설정\"]",
    "    A --> B[\"application-dev.yml\<br>H2 인메모리\"]",
    "    A --> C[\"application-prod.yml\<br>MySQL\"]",
    "```",
    "",
    "### application.yml (공통)",
    "",
    "```yaml",
    "spring:",
    "  profiles:",
    "    active: dev",
    "  jpa:",
    "    show-sql: true",
    "    properties:",
    "      hibernate:",
    "        format_sql: true",
    "```",
    "",
    "### application-dev.yml (개발: H2)",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:devdb",
    "    driver-class-name: org.h2.Driver",
    "    username: sa",
    "    password:",
    "  h2:",
    "    console:",
    "      enabled: true",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: create",
    "```",
    "",
    "### application-prod.yml (운영: MySQL)",
    "",
    "```yaml",
    "spring:",
    "  datasource:",
    "    url: jdbc:mysql://localhost:3306/myapp?useSSL=false&serverTimezone=Asia/Seoul",
    "    driver-class-name: com.mysql.cj.jdbc.Driver",
    "    username: ${DB_USERNAME}",
    "    password: ${DB_PASSWORD}",
    "  h2:",
    "    console:",
    "      enabled: false",
    "  jpa:",
    "    hibernate:",
    "      ddl-auto: validate",
    "    properties:",
    "      hibernate:",
    "        dialect: org.hibernate.dialect.MySQLDialect",
    "```",
    "",
    "### build.gradle 의존성",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'",
    "",
    "    // H2 - 개발/테스트에서만 사용",
    "    runtimeOnly 'com.h2database:h2'",
    "",
    "    // MySQL - 운영에서 사용",
    "    runtimeOnly 'com.mysql:mysql-connector-j'",
    "}",
    "```",
    "",
    "```bash",
    "# 개발 환경 실행",
    "java -jar app.jar --spring.profiles.active=dev",
    "",
    "# 운영 환경 실행",
    "java -jar app.jar --spring.profiles.active=prod",
    "```",
    "",
    "---",
    "",
    "## 자주 발생하는 문제와 해결",
    "",
    "### 1. H2 Console 접속 시 테이블이 안 보임",
    "",
    "```yaml",
    "# JDBC URL을 정확히 맞춰야 합니다",
    "# application.yml에 jdbc:h2:mem:testdb 라고 설정했으면",
    "# H2 Console에서도 동일하게 jdbc:h2:mem:testdb 를 입력해야 합니다",
    "spring:",
    "  datasource:",
    "    url: jdbc:h2:mem:testdb",
    "```",
    "",
    "> 콘솔에서 `jdbc:h2:~/test` (기본값)로 접속하면 다른 DB에 연결되어 테이블이 보이지 않습니다.",
    "",
    "### 2. data.sql 실행 시 테이블이 없다는 오류",
    "",
    "```yaml",
    "# defer-datasource-initialization을 true로 설정",
    "spring:",
    "  jpa:",
    "    defer-datasource-initialization: true",
    "```",
    "",
    "### 3. 서버 재시작 시 데이터가 사라짐",
    "",
    "인메모리 모드(`mem:`)를 사용하면 정상적인 동작입니다. 데이터를 유지하려면:",
    "- **파일 모드**로 변경: `jdbc:h2:file:./data/mydb`",
    "- 또는 **data.sql** / **CommandLineRunner**로 초기 데이터를 매번 로딩",
    "",
    "### 4. Spring Boot 3.x에서 H2 Console 접근 안 됨",
    "",
    "Spring Boot 3.x에서는 Spring Security가 있으면 기본적으로 모든 경로가 보호됩니다.",
    "",
    "```java",
    "// SecurityFilterChain에서 H2 Console 경로를 허용",
    ".requestMatchers(\"/h2-console/**\").permitAll()",
    "// frameOptions도 설정",
    ".headers(h -> h.frameOptions(f -> f.sameOrigin()))",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| **H2란** | Java 기반 경량 관계형 DB, 설치 불필요 |",
    "| **인메모리 모드** | `jdbc:h2:mem:testdb` (종료 시 삭제) |",
    "| **파일 모드** | `jdbc:h2:file:./data/mydb` (데이터 유지) |",
    "| **H2 Console** | `http://localhost:8080/h2-console` 에서 SQL 실행 |",
    "| **초기 데이터** | `data.sql`, `CommandLineRunner` 등 |",
    "| **테스트** | `@DataJpaTest`가 기본적으로 H2 사용 |",
    "| **호환 모드** | `MODE=MySQL` 등으로 운영 DB 문법 호환 |",
    "| **프로파일 전환** | `application-dev.yml` (H2) / `application-prod.yml` (MySQL) |",
    "",
    "| 의존성 | 설명 |",
    "|--------|------|",
    "| `runtimeOnly 'com.h2database:h2'` | H2 DB |",
    "| `spring-boot-starter-data-jpa` | JPA + Hibernate |",
    "| `spring.h2.console.enabled: true` | H2 Console 활성화 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
