<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-spring-cloud",
  title: "Spring Cloud와 MSA 완전 정리 - API Gateway, Service Discovery, Config Server까지",
  date: "2026-01-31",
  summary: "마이크로서비스 아키텍처(MSA)의 개념, 모놀리식과의 차이, Spring Cloud 핵심 컴포넌트(Eureka, API Gateway, Config Server, OpenFeign, Resilience4j)를 실전 예제로 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","spring-cloud","msa","eureka","gateway","config-server","feign","backend"],
  content: [
    "## MSA란?",
    "",
    "**MSA(Microservice Architecture)**는 하나의 애플리케이션을 **여러 개의 작은 독립적인 서비스**로 분리하여 개발·배포·운영하는 아키텍처 패턴입니다. 각 서비스는 **자체 DB**를 가지고, **API(HTTP/메시징)**로 통신합니다.",
    "",
    "### 모놀리식 vs MSA",
    "",
    "```mermaid",
    "flowchart TB",
    "    subgraph 모놀리식 Monolithic",
    "        A[\"하나의 애플리케이션\"] --> B[\"사용자 모듈\"]",
    "        A --> C[\"상품 모듈\"]",
    "        A --> D[\"주문 모듈\"]",
    "        A --> E[\"결제 모듈\"]",
    "        A --> F[\"하나의 DB\"]",
    "    end",
    "",
    "    subgraph MSA Microservice",
    "        G[\"API Gateway\"] --> H[\"사용자 서비스\"]",
    "        G --> I[\"상품 서비스\"]",
    "        G --> J[\"주문 서비스\"]",
    "        G --> K[\"결제 서비스\"]",
    "        H --> L[\"User DB\"]",
    "        I --> M[\"Product DB\"]",
    "        J --> N[\"Order DB\"]",
    "        K --> O[\"Payment DB\"]",
    "    end",
    "```",
    "",
    "### 모놀리식 vs MSA 비교",
    "",
    "| 비교 항목 | 모놀리식(Monolithic) | MSA(Microservice) |",
    "|-----------|--------------------|--------------------|",
    "| **구조** | 단일 애플리케이션 | 여러 독립 서비스 |",
    "| **배포** | 전체 재배포 | 서비스별 개별 배포 |",
    "| **DB** | 하나의 공유 DB | 서비스별 독립 DB |",
    "| **기술 스택** | 동일 기술 강제 | 서비스별 자유 선택 |",
    "| **확장성** | 전체 스케일링 | 서비스별 독립 스케일링 |",
    "| **장애 영향** | 전체 시스템 다운 | 해당 서비스만 영향 |",
    "| **통신** | 메서드 호출 (In-Process) | API 호출 (HTTP/gRPC/메시징) |",
    "| **개발 속도** | 초기 빠름, 규모 커지면 느림 | 초기 느림, 규모 커져도 유지 |",
    "| **운영 복잡도** | 낮음 | **높음** (모니터링, 로깅, 배포) |",
    "| **적합한 경우** | 소규모 팀, 초기 프로젝트 | 대규모 팀, 복잡한 도메인 |",
    "",
    "### MSA의 장단점",
    "",
    "| 구분 | 내용 |",
    "|------|------|",
    "| **장점** | 독립 배포, 기술 스택 자유, 장애 격리, 확장성, 팀 자율성 |",
    "| **단점** | 분산 시스템 복잡도, 네트워크 지연, 데이터 일관성, 디버깅 어려움, 운영 비용 |",
    "",
    "> **핵심**: MSA는 **은탄환이 아닙니다**. 팀 규모, 도메인 복잡도, 운영 역량을 고려하여 도입 여부를 결정해야 합니다. 대부분의 경우 **모놀리식으로 시작**하여 점진적으로 MSA로 전환하는 것이 바람직합니다.",
    "",
    "---",
    "",
    "## Spring Cloud 생태계",
    "",
    "**Spring Cloud**는 MSA를 구현하기 위한 **도구 모음(Tool Suite)**입니다. 분산 시스템에서 필요한 공통 패턴(서비스 디스커버리, 설정 관리, 로드 밸런싱, 서킷 브레이커 등)을 쉽게 구현할 수 있도록 도와줍니다.",
    "",
    "### 핵심 컴포넌트",
    "",
    "| 컴포넌트 | 역할 | 기술 |",
    "|---------|------|------|",
    "| **Service Discovery** | 서비스 등록/발견 | Spring Cloud Netflix Eureka |",
    "| **API Gateway** | 단일 진입점, 라우팅, 필터 | Spring Cloud Gateway |",
    "| **Config Server** | 중앙 설정 관리 | Spring Cloud Config |",
    "| **HTTP Client** | 선언적 REST 호출 | Spring Cloud OpenFeign |",
    "| **Circuit Breaker** | 장애 전파 방지 | Resilience4j |",
    "| **분산 추적** | 요청 추적, 로깅 | Micrometer Tracing + Zipkin |",
    "| **메시지 브로커** | 비동기 이벤트 통신 | Spring Cloud Stream (Kafka/RabbitMQ) |",
    "| **로드 밸런서** | 클라이언트 사이드 로드 밸런싱 | Spring Cloud LoadBalancer |",
    "",
    "---",
    "",
    "## 전체 아키텍처 다이어그램",
    "",
    "```mermaid",
    "flowchart TB",
    "    Client[\"Client\<br>(Browser/App)\"] --> GW[\"API Gateway\<br>:8080\"]",
    "",
    "    GW --> US[\"User Service\<br>:8081\"]",
    "    GW --> PS[\"Product Service\<br>:8082\"]",
    "    GW --> OS[\"Order Service\<br>:8083\"]",
    "    GW --> PAS[\"Payment Service\<br>:8084\"]",
    "",
    "    US --> UDB[(\"User DB\")]",
    "    PS --> PDB[(\"Product DB\")]",
    "    OS --> ODB[(\"Order DB\")]",
    "    PAS --> PADB[(\"Payment DB\")]",
    "",
    "    GW -.->|서비스 조회| EUR[\"Eureka Server\<br>:8761\"]",
    "    US -.->|등록| EUR",
    "    PS -.->|등록| EUR",
    "    OS -.->|등록| EUR",
    "    PAS -.->|등록| EUR",
    "",
    "    US -.->|설정 조회| CS[\"Config Server\<br>:8888\"]",
    "    PS -.->|설정 조회| CS",
    "    OS -.->|설정 조회| CS",
    "    PAS -.->|설정 조회| CS",
    "",
    "    CS -.->|설정 저장소| GIT[(\"Git Repository\")]",
    "",
    "    OS -->|Feign 호출| PS",
    "    OS -->|Feign 호출| PAS",
    "",
    "    style GW fill:#FF6B35,color:#fff",
    "    style EUR fill:#6DB33F,color:#fff",
    "    style CS fill:#4285F4,color:#fff",
    "    style GIT fill:#333,color:#fff",
    "```",
    "",
    "| 구성 요소 | 역할 |",
    "|----------|------|",
    "| **API Gateway** | 모든 요청의 단일 진입점. 라우팅, 인증, 로드 밸런싱 수행 |",
    "| **Eureka Server** | 서비스 레지스트리. 각 서비스의 위치(IP:Port)를 관리 |",
    "| **Config Server** | Git에 저장된 설정 파일을 중앙에서 관리·배포 |",
    "| **각 Service** | 독립된 비즈니스 로직과 DB를 가진 마이크로서비스 |",
    "",
    "---",
    "",
    "## 실습: 인텔리제이에서 MSA 프로젝트 만들기",
    "",
    "이론을 이해했으니, 이제 **직접 3개의 마이크로서비스**를 만들어 봅시다. 가장 핵심적인 Eureka Server + User Service + Order Service 구성으로, Order Service가 **OpenFeign**을 사용하여 User Service를 호출하는 구조입니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    EUR[\"Eureka Server\<br>:8761\"]",
    "    US[\"User Service\<br>:8081\"]",
    "    OS[\"Order Service\<br>:8082\"]",
    "",
    "    US -.->|등록| EUR",
    "    OS -.->|등록| EUR",
    "    OS -->|Feign 호출| US",
    "",
    "    style EUR fill:#6DB33F,color:#fff",
    "    style US fill:#4285F4,color:#fff",
    "    style OS fill:#FF6B35,color:#fff",
    "```",
    "",
    "### Step 1: 인텔리제이에서 프로젝트 생성",
    "",
    "**3개의 프로젝트**를 각각 생성합니다. IntelliJ에서 `File → New → Project → Spring Initializr`를 선택하고 아래 표대로 설정합니다.",
    "",
    "| 프로젝트 | Group | Artifact | Java | Build | Dependencies |",
    "|---------|-------|----------|------|-------|-------------|",
    "| **eureka-server** | com.example | eureka-server | 21 | Gradle - Groovy | Eureka Server |",
    "| **user-service** | com.example | user-service | 21 | Gradle - Groovy | Eureka Discovery Client, Spring Web |",
    "| **order-service** | com.example | order-service | 21 | Gradle - Groovy | Eureka Discovery Client, Spring Web, OpenFeign |",
    "",
    "> **Tip**: 여러 프로젝트를 하나의 IntelliJ 창에서 관리하려면, 상위 폴더를 열고 각 프로젝트를 `File → New → Module from Existing Sources`로 추가하면 편리합니다.",
    "",
    "```",
    "msa-practice/          ← 상위 폴더",
    "├── eureka-server/",
    "├── user-service/",
    "├── order-service/",
    "└── docker-compose.yml",
    "```",
    "",
    "### Step 2: eureka-server",
    "",
    "#### build.gradle",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.1'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "ext {",
    "    set('springCloudVersion', '2024.0.0')",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'",
    "}",
    "",
    "dependencyManagement {",
    "    imports {",
    "        mavenBom \"org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}\"",
    "    }",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "#### EurekaServerApplication.java",
    "",
    "```java",
    "package com.example.eurekaserver;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;",
    "",
    "@SpringBootApplication",
    "@EnableEurekaServer",
    "public class EurekaServerApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(EurekaServerApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "#### application.yml",
    "",
    "```yaml",
    "server:",
    "  port: 8761",
    "",
    "spring:",
    "  application:",
    "    name: eureka-server",
    "",
    "eureka:",
    "  client:",
    "    register-with-eureka: false",
    "    fetch-registry: false",
    "  server:",
    "    enable-self-preservation: false",
    "```",
    "",
    "### Step 3: user-service",
    "",
    "#### build.gradle",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.1'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "ext {",
    "    set('springCloudVersion', '2024.0.0')",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "}",
    "",
    "dependencyManagement {",
    "    imports {",
    "        mavenBom \"org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}\"",
    "    }",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "#### UserServiceApplication.java",
    "",
    "```java",
    "package com.example.userservice;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class UserServiceApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(UserServiceApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "#### UserController.java",
    "",
    "```java",
    "package com.example.userservice.controller;",
    "",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.PathVariable;",
    "import org.springframework.web.bind.annotation.RequestMapping;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "import java.util.Map;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/users\")",
    "public class UserController {",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public Map<String, Object> getUser(@PathVariable Long id) {",
    "        return Map.of(",
    "            \"id\", id,",
    "            \"name\", \"홍길동\",",
    "            \"email\", \"hong@example.com\"",
    "        );",
    "    }",
    "}",
    "```",
    "",
    "#### application.yml",
    "",
    "```yaml",
    "server:",
    "  port: 8081",
    "",
    "spring:",
    "  application:",
    "    name: user-service",
    "",
    "eureka:",
    "  client:",
    "    service-url:",
    "      defaultZone: http://localhost:8761/eureka/",
    "  instance:",
    "    prefer-ip-address: true",
    "```",
    "",
    "### Step 4: order-service",
    "",
    "#### build.gradle",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.1'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "ext {",
    "    set('springCloudVersion', '2024.0.0')",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'",
    "}",
    "",
    "dependencyManagement {",
    "    imports {",
    "        mavenBom \"org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}\"",
    "    }",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "#### OrderServiceApplication.java",
    "",
    "```java",
    "package com.example.orderservice;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "import org.springframework.cloud.openfeign.EnableFeignClients;",
    "",
    "@SpringBootApplication",
    "@EnableFeignClients",
    "public class OrderServiceApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(OrderServiceApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "#### UserClient.java (Feign Client)",
    "",
    "```java",
    "package com.example.orderservice.client;",
    "",
    "import org.springframework.cloud.openfeign.FeignClient;",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.PathVariable;",
    "",
    "import java.util.Map;",
    "",
    "@FeignClient(name = \"user-service\")",
    "public interface UserClient {",
    "",
    "    @GetMapping(\"/api/users/{id}\")",
    "    Map<String, Object> getUser(@PathVariable(\"id\") Long id);",
    "}",
    "```",
    "",
    "#### OrderController.java",
    "",
    "```java",
    "package com.example.orderservice.controller;",
    "",
    "import com.example.orderservice.client.UserClient;",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.PathVariable;",
    "import org.springframework.web.bind.annotation.RequestMapping;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "import java.util.Map;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/orders\")",
    "public class OrderController {",
    "",
    "    private final UserClient userClient;",
    "",
    "    public OrderController(UserClient userClient) {",
    "        this.userClient = userClient;",
    "    }",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public Map<String, Object> getOrder(@PathVariable Long id) {",
    "        Map<String, Object> user = userClient.getUser(id);",
    "        return Map.of(",
    "            \"orderId\", id,",
    "            \"product\", \"스프링 부트 교재\",",
    "            \"price\", 35000,",
    "            \"user\", user",
    "        );",
    "    }",
    "}",
    "```",
    "",
    "#### application.yml",
    "",
    "```yaml",
    "server:",
    "  port: 8082",
    "",
    "spring:",
    "  application:",
    "    name: order-service",
    "",
    "eureka:",
    "  client:",
    "    service-url:",
    "      defaultZone: http://localhost:8761/eureka/",
    "  instance:",
    "    prefer-ip-address: true",
    "```",
    "",
    "### Step 5: Docker Compose로 실행하기",
    "",
    "각 프로젝트 루트에 동일한 `Dockerfile`을 생성합니다.",
    "",
    "```dockerfile",
    "FROM eclipse-temurin:21-jre",
    "COPY build/libs/*.jar app.jar",
    "ENTRYPOINT [\"java\", \"-jar\", \"/app.jar\"]",
    "```",
    "",
    "상위 폴더(`msa-practice/`)에 `docker-compose.yml`을 생성합니다.",
    "",
    "```yaml",
    "version: '3.8'",
    "",
    "services:",
    "  eureka-server:",
    "    build: ./eureka-server",
    "    ports:",
    "      - \"8761:8761\"",
    "    healthcheck:",
    "      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:8761/actuator/health\"]",
    "      interval: 10s",
    "      retries: 5",
    "",
    "  user-service:",
    "    build: ./user-service",
    "    ports:",
    "      - \"8081:8081\"",
    "    depends_on:",
    "      eureka-server:",
    "        condition: service_healthy",
    "    environment:",
    "      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/",
    "",
    "  order-service:",
    "    build: ./order-service",
    "    ports:",
    "      - \"8082:8082\"",
    "    depends_on:",
    "      eureka-server:",
    "        condition: service_healthy",
    "      user-service:",
    "        condition: service_started",
    "    environment:",
    "      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/",
    "```",
    "",
    "```bash",
    "# 각 프로젝트에서 JAR 빌드 후 Docker Compose 실행",
    "cd eureka-server && ./gradlew bootJar && cd ..",
    "cd user-service && ./gradlew bootJar && cd ..",
    "cd order-service && ./gradlew bootJar && cd ..",
    "",
    "docker-compose up --build",
    "```",
    "",
    "### Step 6: 실행 순서 및 테스트",
    "",
    "Docker 없이 **로컬에서 직접 실행**하는 경우, 아래 순서를 반드시 지켜야 합니다.",
    "",
    "| 순서 | 서비스 | 실행 방법 | 포트 |",
    "|------|--------|----------|------|",
    "| 1 | Eureka Server | IntelliJ에서 `EurekaServerApplication` Run | :8761 |",
    "| 2 | User Service | IntelliJ에서 `UserServiceApplication` Run | :8081 |",
    "| 3 | Order Service | IntelliJ에서 `OrderServiceApplication` Run | :8082 |",
    "",
    "> **중요**: Eureka Server가 완전히 기동된 후(콘솔에 `Started EurekaServerApplication` 출력 확인) 나머지 서비스를 실행해야 합니다.",
    "",
    "#### 테스트",
    "",
    "```bash",
    "# 1. Eureka 대시보드 확인 - 브라우저에서 접속",
    "http://localhost:8761",
    "",
    "# 2. User Service 직접 호출",
    "curl http://localhost:8081/api/users/1",
    "# → {\"id\":1, \"name\":\"홍길동\", \"email\":\"hong@example.com\"}",
    "",
    "# 3. Order Service 호출 (내부적으로 Feign → User Service 호출)",
    "curl http://localhost:8082/api/orders/1",
    "# → {\"orderId\":1, \"product\":\"스프링 부트 교재\", \"price\":35000,",
    "#    \"user\":{\"id\":1, \"name\":\"홍길동\", \"email\":\"hong@example.com\"}}",
    "```",
    "",
    "Eureka 대시보드(`http://localhost:8761`)에 접속하면 **USER-SERVICE**와 **ORDER-SERVICE**가 등록된 것을 확인할 수 있습니다. Order Service의 `/api/orders/1` 응답에 User Service에서 가져온 사용자 정보가 포함되어 있으면 **Feign을 통한 서비스 간 통신이 성공**한 것입니다.",
    "",
    "---",
    "",
    "## Eureka (Service Discovery)",
    "",
    "**Eureka**는 Netflix에서 만든 **서비스 디스커버리** 도구입니다. 각 서비스가 자신의 위치(IP, Port)를 Eureka Server에 **등록**하고, 다른 서비스는 Eureka에서 **조회**하여 통신합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant ES as Eureka Server",
    "    participant S1 as Order Service",
    "    participant S2 as Product Service",
    "",
    "    S1->>ES: 1. 서비스 등록 (order-service, 192.168.0.10:8083)",
    "    S2->>ES: 2. 서비스 등록 (product-service, 192.168.0.11:8082)",
    "    S1->>ES: 3. product-service 위치 조회",
    "    ES->>S1: 4. 192.168.0.11:8082",
    "    S1->>S2: 5. HTTP 요청",
    "    Note over S1,ES: 30초마다 heartbeat 전송",
    "    Note over ES: 90초간 heartbeat 없으면 서비스 제거",
    "```",
    "",
    "### Eureka Server 설정",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'",
    "}",
    "```",
    "",
    "```java",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;",
    "",
    "@SpringBootApplication",
    "@EnableEurekaServer",
    "public class EurekaServerApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(EurekaServerApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "```yaml",
    "# eureka-server application.yml",
    "server:",
    "  port: 8761",
    "",
    "eureka:",
    "  client:",
    "    register-with-eureka: false   # 자기 자신은 등록하지 않음",
    "    fetch-registry: false         # 레지스트리 정보를 가져오지 않음",
    "  server:",
    "    enable-self-preservation: false  # 개발 환경에서는 비활성화",
    "```",
    "",
    "### Eureka Client (각 서비스) 설정",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'",
    "}",
    "```",
    "",
    "```yaml",
    "# order-service application.yml",
    "spring:",
    "  application:",
    "    name: order-service      # Eureka에 등록될 서비스 이름",
    "",
    "server:",
    "  port: 8083",
    "",
    "eureka:",
    "  client:",
    "    service-url:",
    "      defaultZone: http://localhost:8761/eureka/",
    "  instance:",
    "    prefer-ip-address: true  # 호스트명 대신 IP로 등록",
    "```",
    "",
    "### Eureka 동작 원리",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| **서비스 등록** | 애플리케이션 시작 시 Eureka Server에 자신의 정보(이름, IP, Port)를 등록합니다 |",
    "| **Heartbeat** | 30초마다 Eureka Server에 heartbeat를 전송하여 살아있음을 알립니다 |",
    "| **서비스 제거** | 90초간 heartbeat가 없으면 Eureka가 해당 서비스를 레지스트리에서 제거합니다 |",
    "| **서비스 조회** | 다른 서비스를 호출할 때 Eureka에서 서비스 이름으로 IP:Port를 조회합니다 |",
    "| **캐싱** | 클라이언트는 레지스트리 정보를 로컬에 캐싱하여 Eureka 장애 시에도 동작합니다 |",
    "",
    "> **Eureka Dashboard**: `http://localhost:8761`에 접속하면 등록된 서비스 목록을 확인할 수 있습니다.",
    "",
    "---",
    "",
    "## API Gateway (Spring Cloud Gateway)",
    "",
    "**API Gateway**는 모든 클라이언트 요청이 거치는 **단일 진입점**입니다. 라우팅, 인증/인가, 로드 밸런싱, 요청 변환, Rate Limiting 등의 **횡단 관심사(Cross-Cutting Concerns)**를 처리합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    C[\"Client\"] --> GW[\"API Gateway\<br>:8080\"]",
    "    GW -->|/api/users/**| US[\"User Service\"]",
    "    GW -->|/api/products/**| PS[\"Product Service\"]",
    "    GW -->|/api/orders/**| OS[\"Order Service\"]",
    "",
    "    style GW fill:#FF6B35,color:#fff",
    "```",
    "",
    "### 의존성",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'",
    "}",
    "```",
    "",
    "### YAML 방식 라우팅 설정",
    "",
    "```yaml",
    "# gateway application.yml",
    "server:",
    "  port: 8080",
    "",
    "spring:",
    "  application:",
    "    name: gateway-service",
    "  cloud:",
    "    gateway:",
    "      routes:",
    "        - id: user-service",
    "          uri: lb://user-service        # Eureka에서 조회 + 로드 밸런싱",
    "          predicates:",
    "            - Path=/api/users/**",
    "          filters:",
    "            - StripPrefix=1              # /api/users/** → /users/**",
    "",
    "        - id: product-service",
    "          uri: lb://product-service",
    "          predicates:",
    "            - Path=/api/products/**",
    "          filters:",
    "            - StripPrefix=1",
    "",
    "        - id: order-service",
    "          uri: lb://order-service",
    "          predicates:",
    "            - Path=/api/orders/**",
    "          filters:",
    "            - StripPrefix=1",
    "",
    "      default-filters:",
    "        - DedupeResponseHeader=Access-Control-Allow-Origin",
    "",
    "eureka:",
    "  client:",
    "    service-url:",
    "      defaultZone: http://localhost:8761/eureka/",
    "```",
    "",
    "### Java DSL 방식 라우팅 설정",
    "",
    "```java",
    "import org.springframework.cloud.gateway.route.RouteLocator;",
    "import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "",
    "@Configuration",
    "public class GatewayConfig {",
    "",
    "    @Bean",
    "    public RouteLocator customRouteLocator(",
    "            RouteLocatorBuilder builder) {",
    "        return builder.routes()",
    "                .route(\"user-service\", r -> r",
    "                        .path(\"/api/users/**\")",
    "                        .filters(f -> f.stripPrefix(1))",
    "                        .uri(\"lb://user-service\"))",
    "                .route(\"product-service\", r -> r",
    "                        .path(\"/api/products/**\")",
    "                        .filters(f -> f",
    "                                .stripPrefix(1)",
    "                                .addRequestHeader(\"X-Request-Source\", \"gateway\"))",
    "                        .uri(\"lb://product-service\"))",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "### Gateway 핵심 개념",
    "",
    "| 개념 | 설명 | 예시 |",
    "|------|------|------|",
    "| **Route** | 요청을 어디로 보낼지 정의 | `/api/users/**` → `user-service` |",
    "| **Predicate** | 요청 매칭 조건 | `Path`, `Method`, `Header`, `Host` |",
    "| **Filter** | 요청/응답 변환 | `StripPrefix`, `AddRequestHeader`, `CircuitBreaker` |",
    "| **lb://** | Eureka 연동 로드 밸런싱 | `lb://user-service` (여러 인스턴스 중 하나 선택) |",
    "",
    "### 커스텀 인증 필터 (Global Filter)",
    "",
    "```java",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.cloud.gateway.filter.GatewayFilterChain;",
    "import org.springframework.cloud.gateway.filter.GlobalFilter;",
    "import org.springframework.core.Ordered;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.stereotype.Component;",
    "import org.springframework.web.server.ServerWebExchange;",
    "import reactor.core.publisher.Mono;",
    "",
    "@Slf4j",
    "@Component",
    "public class AuthorizationFilter implements GlobalFilter, Ordered {",
    "",
    "    @Override",
    "    public Mono<Void> filter(",
    "            ServerWebExchange exchange,",
    "            GatewayFilterChain chain) {",
    "",
    "        String path = exchange.getRequest().getURI().getPath();",
    "",
    "        // 인증 불필요 경로",
    "        if (path.startsWith(\"/api/auth\") || path.equals(\"/api/health\")) {",
    "            return chain.filter(exchange);",
    "        }",
    "",
    "        // Authorization 헤더 확인",
    "        String authHeader = exchange.getRequest()",
    "                .getHeaders().getFirst(\"Authorization\");",
    "",
    "        if (authHeader == null || !authHeader.startsWith(\"Bearer \")) {",
    "            log.warn(\"인증 토큰이 없습니다: {}\", path);",
    "            exchange.getResponse().setStatusCode(HttpStatus.UNAUTHORIZED);",
    "            return exchange.getResponse().setComplete();",
    "        }",
    "",
    "        String token = authHeader.substring(7);",
    "        log.info(\"인증 토큰 확인: {}\", path);",
    "",
    "        // 토큰 검증 로직 (JWT 검증 등)",
    "        // ...",
    "",
    "        return chain.filter(exchange);",
    "    }",
    "",
    "    @Override",
    "    public int getOrder() {",
    "        return -1; // 가장 먼저 실행",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Config Server (중앙 설정 관리)",
    "",
    "**Config Server**는 모든 마이크로서비스의 설정을 **중앙에서 관리**합니다. Git 저장소에 설정 파일을 저장하고, 각 서비스가 Config Server를 통해 설정을 가져옵니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    GIT[(\"Git Repository\<br>config-repo\")] -->|설정 파일| CS[\"Config Server\<br>:8888\"]",
    "    CS -->|user-service.yml| US[\"User Service\"]",
    "    CS -->|order-service.yml| OS[\"Order Service\"]",
    "    CS -->|product-service.yml| PS[\"Product Service\"]",
    "",
    "    style CS fill:#4285F4,color:#fff",
    "```",
    "",
    "### Config Server 설정",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-config-server'",
    "}",
    "```",
    "",
    "```java",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "import org.springframework.cloud.config.server.EnableConfigServer;",
    "",
    "@SpringBootApplication",
    "@EnableConfigServer",
    "public class ConfigServerApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(ConfigServerApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "```yaml",
    "# config-server application.yml",
    "server:",
    "  port: 8888",
    "",
    "spring:",
    "  application:",
    "    name: config-server",
    "  cloud:",
    "    config:",
    "      server:",
    "        git:",
    "          uri: https://github.com/your-org/config-repo",
    "          default-label: main",
    "          search-paths: '{application}'  # 서비스 이름별 폴더",
    "```",
    "",
    "### Git 저장소 구조 (config-repo)",
    "",
    "```",
    "config-repo/",
    "├── application.yml           # 공통 설정 (모든 서비스 적용)",
    "├── user-service/",
    "│   ├── user-service.yml      # 기본 설정",
    "│   └── user-service-prod.yml # 프로필별 설정",
    "├── order-service/",
    "│   ├── order-service.yml",
    "│   └── order-service-prod.yml",
    "└── product-service/",
    "    ├── product-service.yml",
    "    └── product-service-prod.yml",
    "```",
    "",
    "### Config Client (각 서비스) 설정",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-config'",
    "}",
    "```",
    "",
    "```yaml",
    "# user-service application.yml",
    "spring:",
    "  application:",
    "    name: user-service",
    "  config:",
    "    import: optional:configserver:http://localhost:8888",
    "  profiles:",
    "    active: dev",
    "```",
    "",
    "### 설정 동적 갱신 (@RefreshScope)",
    "",
    "설정이 변경되었을 때 서비스를 **재시작하지 않고** 반영하려면 `@RefreshScope`와 Actuator를 사용합니다.",
    "",
    "```java",
    "// build.gradle에 추가",
    "// implementation 'org.springframework.boot:spring-boot-starter-actuator'",
    "",
    "import org.springframework.beans.factory.annotation.Value;",
    "import org.springframework.cloud.context.config.annotation.RefreshScope;",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "@RestController",
    "@RefreshScope",
    "public class ConfigTestController {",
    "",
    "    @Value(\"${app.message:기본 메시지}\")",
    "    private String message;",
    "",
    "    @GetMapping(\"/message\")",
    "    public String getMessage() {",
    "        return message;",
    "    }",
    "}",
    "```",
    "",
    "```yaml",
    "# actuator 엔드포인트 활성화",
    "management:",
    "  endpoints:",
    "    web:",
    "      exposure:",
    "        include: refresh, health, info",
    "```",
    "",
    "```",
    "# 설정 변경 후 갱신 요청",
    "POST http://localhost:8081/actuator/refresh",
    "```",
    "",
    "> **참고**: Spring Cloud Bus(Kafka/RabbitMQ)를 사용하면 모든 서비스에 **한 번에 갱신**을 전파할 수 있습니다.",
    "",
    "---",
    "",
    "## OpenFeign (선언적 HTTP 클라이언트)",
    "",
    "**OpenFeign**은 인터페이스와 어노테이션만으로 **REST API를 호출**할 수 있게 해주는 **선언적 HTTP 클라이언트**입니다. RestTemplate이나 WebClient를 직접 사용하는 것보다 훨씬 간결합니다.",
    "",
    "### 의존성 및 설정",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'",
    "}",
    "```",
    "",
    "```java",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "import org.springframework.cloud.openfeign.EnableFeignClients;",
    "",
    "@SpringBootApplication",
    "@EnableFeignClients",
    "public class OrderServiceApplication {",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(OrderServiceApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### FeignClient 사용",
    "",
    "```java",
    "import org.springframework.cloud.openfeign.FeignClient;",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.PathVariable;",
    "",
    "@FeignClient(name = \"product-service\",",
    "             fallbackFactory = ProductClientFallbackFactory.class)",
    "public interface ProductClient {",
    "",
    "    @GetMapping(\"/products/{id}\")",
    "    ProductResponse getProduct(@PathVariable(\"id\") Long id);",
    "",
    "    @GetMapping(\"/products\")",
    "    List<ProductResponse> getAllProducts();",
    "}",
    "```",
    "",
    "```java",
    "// 사용 예시 - OrderService",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "public class OrderService {",
    "",
    "    private final ProductClient productClient;",
    "",
    "    public OrderResponse createOrder(OrderRequest request) {",
    "        // Feign으로 product-service 호출 (Eureka에서 자동 조회)",
    "        ProductResponse product = productClient",
    "                .getProduct(request.getProductId());",
    "",
    "        // 주문 생성 로직",
    "        Order order = Order.builder()",
    "                .productId(product.getId())",
    "                .productName(product.getName())",
    "                .price(product.getPrice())",
    "                .quantity(request.getQuantity())",
    "                .build();",
    "",
    "        return OrderResponse.from(orderRepository.save(order));",
    "    }",
    "}",
    "```",
    "",
    "### FallbackFactory (에러 처리)",
    "",
    "```java",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.cloud.openfeign.FallbackFactory;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Slf4j",
    "@Component",
    "public class ProductClientFallbackFactory",
    "        implements FallbackFactory<ProductClient> {",
    "",
    "    @Override",
    "    public ProductClient create(Throwable cause) {",
    "        log.error(\"ProductClient 호출 실패: {}\", cause.getMessage());",
    "",
    "        return new ProductClient() {",
    "            @Override",
    "            public ProductResponse getProduct(Long id) {",
    "                return ProductResponse.builder()",
    "                        .id(id)",
    "                        .name(\"[서비스 일시 불가]\")",
    "                        .price(0)",
    "                        .build();",
    "            }",
    "",
    "            @Override",
    "            public List<ProductResponse> getAllProducts() {",
    "                return Collections.emptyList();",
    "            }",
    "        };",
    "    }",
    "}",
    "```",
    "",
    "### RestTemplate vs WebClient vs Feign 비교",
    "",
    "| 항목 | RestTemplate | WebClient | OpenFeign |",
    "|------|-------------|-----------|-----------|",
    "| 방식 | 명령형(Imperative) | 반응형(Reactive) | **선언적(Declarative)** |",
    "| 코드량 | 많음 | 보통 | **적음** |",
    "| Eureka 연동 | 수동 설정 | 수동 설정 | **자동** |",
    "| Circuit Breaker | 수동 적용 | 수동 적용 | **어노테이션으로 적용** |",
    "| 적합한 경우 | 레거시 | WebFlux | **MSA 서비스 간 통신** |",
    "",
    "---",
    "",
    "## Resilience4j (Circuit Breaker)",
    "",
    "**Resilience4j**는 MSA에서 **장애 전파를 방지**하기 위한 라이브러리입니다. 핵심 패턴은 **Circuit Breaker(서킷 브레이커)**로, 특정 서비스 호출이 반복 실패하면 **회로를 열어(Open)** 더 이상 요청을 보내지 않고 빠르게 실패(Fail-Fast)합니다.",
    "",
    "### Circuit Breaker 상태 전환",
    "",
    "```mermaid",
    "stateDiagram-v2",
    "    [*] --> CLOSED",
    "    CLOSED --> OPEN: 실패율 >= threshold\<br>(예: 50% 이상 실패)",
    "    OPEN --> HALF_OPEN: waitDurationInOpenState\<br>(예: 60초 후)",
    "    HALF_OPEN --> CLOSED: 시험 호출 성공",
    "    HALF_OPEN --> OPEN: 시험 호출 실패",
    "",
    "    CLOSED: 정상 상태\<br>모든 요청 통과",
    "    OPEN: 차단 상태\<br>fallback 즉시 반환",
    "    HALF_OPEN: 반열림 상태\<br>일부 요청만 통과하여 테스트",
    "```",
    "",
    "| 상태 | 설명 |",
    "|------|------|",
    "| **CLOSED** | 정상 상태. 모든 요청이 대상 서비스로 전달됩니다 |",
    "| **OPEN** | 차단 상태. 요청을 보내지 않고 즉시 fallback을 반환합니다 |",
    "| **HALF_OPEN** | 시험 상태. 일부 요청만 보내서 서비스 복구 여부를 확인합니다 |",
    "",
    "### 의존성 및 설정",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'",
    "}",
    "```",
    "",
    "```yaml",
    "# application.yml",
    "resilience4j:",
    "  circuitbreaker:",
    "    instances:",
    "      productService:",
    "        sliding-window-size: 10             # 최근 10개 호출 기준",
    "        failure-rate-threshold: 50           # 실패율 50% 이상이면 OPEN",
    "        wait-duration-in-open-state: 60s     # OPEN 상태 유지 시간",
    "        permitted-number-of-calls-in-half-open-state: 3  # HALF_OPEN 시 시험 호출 수",
    "        minimum-number-of-calls: 5           # 최소 5번 호출 후 판단",
    "",
    "  retry:",
    "    instances:",
    "      productService:",
    "        max-attempts: 3",
    "        wait-duration: 1s",
    "        retry-exceptions:",
    "          - java.io.IOException",
    "          - java.net.SocketTimeoutException",
    "",
    "  ratelimiter:",
    "    instances:",
    "      productService:",
    "        limit-for-period: 100               # 기간당 허용 요청 수",
    "        limit-refresh-period: 1s             # 기간",
    "        timeout-duration: 0s                 # 대기 시간 (0 = 즉시 거부)",
    "```",
    "",
    "### @CircuitBreaker 사용",
    "",
    "```java",
    "import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;",
    "import io.github.resilience4j.retry.annotation.Retry;",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Slf4j",
    "@Service",
    "@RequiredArgsConstructor",
    "public class OrderService {",
    "",
    "    private final ProductClient productClient;",
    "",
    "    @CircuitBreaker(name = \"productService\",",
    "                    fallbackMethod = \"getProductFallback\")",
    "    @Retry(name = \"productService\")",
    "    public ProductResponse getProduct(Long productId) {",
    "        return productClient.getProduct(productId);",
    "    }",
    "",
    "    // fallback 메서드 (파라미터 + Throwable)",
    "    private ProductResponse getProductFallback(",
    "            Long productId, Throwable t) {",
    "        log.warn(\"Product 서비스 호출 실패, fallback 실행: {}\",",
    "                 t.getMessage());",
    "        return ProductResponse.builder()",
    "                .id(productId)",
    "                .name(\"[상품 정보를 불러올 수 없습니다]\")",
    "                .price(0)",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "### Resilience4j 핵심 패턴 비교",
    "",
    "| 패턴 | 목적 | 설정 예시 |",
    "|------|------|----------|",
    "| **CircuitBreaker** | 연속 실패 시 요청 차단 | `failure-rate-threshold: 50` |",
    "| **Retry** | 일시적 장애 시 재시도 | `max-attempts: 3, wait-duration: 1s` |",
    "| **RateLimiter** | 초당 요청 수 제한 | `limit-for-period: 100` |",
    "| **Bulkhead** | 동시 요청 수 제한 | `max-concurrent-calls: 25` |",
    "| **TimeLimiter** | 타임아웃 설정 | `timeout-duration: 3s` |",
    "",
    "---",
    "",
    "## 서비스 간 통신 흐름 - 주문 → 상품 → 결제",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as Client",
    "    participant GW as API Gateway",
    "    participant OS as Order Service",
    "    participant PS as Product Service",
    "    participant PAS as Payment Service",
    "    participant EUR as Eureka",
    "",
    "    C->>GW: POST /api/orders",
    "    GW->>EUR: order-service 조회",
    "    EUR->>GW: 192.168.0.10:8083",
    "    GW->>OS: POST /orders (라우팅)",
    "",
    "    OS->>EUR: product-service 조회",
    "    EUR->>OS: 192.168.0.11:8082",
    "    OS->>PS: GET /products/1 (Feign)",
    "    PS->>OS: {id: 1, name: \"노트북\", price: 1500000}",
    "",
    "    OS->>EUR: payment-service 조회",
    "    EUR->>OS: 192.168.0.12:8084",
    "    OS->>PAS: POST /payments (Feign)",
    "    PAS->>PAS: 결제 처리",
    "    PAS->>OS: {paymentId: 100, status: \"SUCCESS\"}",
    "",
    "    OS->>OS: 주문 저장",
    "    OS->>GW: {orderId: 1, status: \"COMPLETED\"}",
    "    GW->>C: 201 Created",
    "```",
    "",
    "### 통신 방식 비교",
    "",
    "| 방식 | 특징 | 사용 시점 |",
    "|------|------|----------|",
    "| **동기(Sync)** | Feign/RestTemplate, 즉시 응답 대기 | 결과가 바로 필요한 경우 (주문 → 상품 조회) |",
    "| **비동기(Async)** | Kafka/RabbitMQ, 이벤트 발행 | 결과를 기다릴 필요 없는 경우 (알림, 로그) |",
    "",
    "---",
    "",
    "## MSA 도입 시 고려사항",
    "",
    "### 분산 트랜잭션 - Saga 패턴",
    "",
    "MSA에서는 각 서비스가 **독립적인 DB**를 사용하므로 기존의 **2-Phase Commit**이 어렵습니다. 대신 **Saga 패턴**을 사용합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant OS as Order Service",
    "    participant PS as Product Service",
    "    participant PAS as Payment Service",
    "",
    "    Note over OS,PAS: 정상 흐름 (Choreography Saga)",
    "    OS->>OS: 1. 주문 생성 (PENDING)",
    "    OS->>PS: 2. 재고 차감 이벤트",
    "    PS->>PS: 3. 재고 차감",
    "    PS->>PAS: 4. 결제 요청 이벤트",
    "    PAS->>PAS: 5. 결제 처리",
    "    PAS->>OS: 6. 결제 완료 이벤트",
    "    OS->>OS: 7. 주문 확정 (COMPLETED)",
    "",
    "    Note over OS,PAS: 실패 시 보상 트랜잭션",
    "    PAS->>PAS: 5. 결제 실패",
    "    PAS->>PS: 6. 결제 실패 이벤트",
    "    PS->>PS: 7. 재고 복원 (보상)",
    "    PS->>OS: 8. 재고 복원 이벤트",
    "    OS->>OS: 9. 주문 취소 (CANCELLED)",
    "```",
    "",
    "| Saga 방식 | 설명 |",
    "|-----------|------|",
    "| **Choreography** | 각 서비스가 이벤트를 발행/구독하여 자율적으로 처리 (간단하지만 복잡해질 수 있음) |",
    "| **Orchestration** | 중앙 오케스트레이터가 각 서비스에 명령을 내려 순서를 제어 (명확하지만 단일 장애점) |",
    "",
    "### 분산 추적 - Micrometer Tracing + Zipkin",
    "",
    "MSA에서는 하나의 요청이 **여러 서비스를 거치므로** 어디서 문제가 발생했는지 추적하기 어렵습니다. **Trace ID**를 사용하여 전체 요청 흐름을 추적합니다.",
    "",
    "```java",
    "// build.gradle",
    "dependencies {",
    "    implementation 'io.micrometer:micrometer-tracing-bridge-brave'",
    "    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'",
    "}",
    "```",
    "",
    "```yaml",
    "# application.yml",
    "management:",
    "  tracing:",
    "    sampling:",
    "      probability: 1.0    # 100% 요청 추적 (프로덕션에서는 0.1 권장)",
    "  zipkin:",
    "    tracing:",
    "      endpoint: http://localhost:9411/api/v2/spans",
    "",
    "logging:",
    "  pattern:",
    "    level: \"%5p [${spring.application.name},%X{traceId},%X{spanId}]\"",
    "```",
    "",
    "```",
    "# 로그 출력 예시 - 동일한 traceId로 서비스 간 요청 추적 가능",
    "INFO [order-service,abc123def456,span001] 주문 생성 요청",
    "INFO [product-service,abc123def456,span002] 상품 조회 요청",
    "INFO [payment-service,abc123def456,span003] 결제 처리 요청",
    "```",
    "",
    "### 데이터 일관성",
    "",
    "| 전략 | 설명 |",
    "|------|------|",
    "| **Eventual Consistency** | 최종적으로 일관성을 보장 (이벤트 기반) |",
    "| **CQRS** | 명령(Command)과 조회(Query) 분리 |",
    "| **Event Sourcing** | 상태 변경을 이벤트로 저장 |",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| **복잡도** | MSA는 모놀리식보다 훨씬 복잡합니다. 서비스 간 통신, 분산 트랜잭션, 데이터 일관성 등 새로운 문제가 발생합니다 |",
    "| **팀 규모** | 서비스당 전담 팀(2 Pizza Team)이 필요합니다. 소규모 팀에서는 오히려 생산성이 떨어집니다 |",
    "| **모놀리식부터 시작** | 처음부터 MSA로 시작하기보다 **모놀리식 → 모듈러 모놀리식 → MSA** 순으로 점진적 전환을 권장합니다 |",
    "| **인프라** | Docker, Kubernetes, CI/CD 파이프라인 등 **컨테이너·자동화 인프라**가 필수입니다 |",
    "| **모니터링** | 분산 시스템에서는 **중앙 집중식 로깅·모니터링**이 필수입니다 (ELK, Prometheus, Grafana) |",
    "| **네트워크** | 서비스 간 통신이 네트워크를 거치므로 **지연(Latency)**과 **장애**에 대비해야 합니다 |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| **MSA** | 독립적인 서비스로 분리, 개별 배포·확장 가능 |",
    "| **Spring Cloud** | MSA 구현을 위한 도구 모음 |",
    "| **Eureka** | 서비스 디스커버리 - 서비스 등록/발견 |",
    "| **API Gateway** | 단일 진입점 - 라우팅, 필터, 인증 |",
    "| **Config Server** | 중앙 설정 관리 - Git 기반 |",
    "| **OpenFeign** | 선언적 HTTP 클라이언트 - 인터페이스만으로 API 호출 |",
    "| **Resilience4j** | 장애 전파 방지 - CircuitBreaker, Retry, RateLimiter |",
    "| **Saga 패턴** | 분산 트랜잭션 처리 - Choreography / Orchestration |",
    "| **분산 추적** | Micrometer Tracing + Zipkin으로 서비스 간 요청 추적 |",
    "| **권장 전환** | 모놀리식 → 모듈러 모놀리식 → MSA (점진적 전환) |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
