<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-event",
  title: "스프링부트 이벤트 처리 완전 정리 - ApplicationEvent, @EventListener, 비동기 이벤트까지",
  date: "2026-02-21",
  summary: "Spring Boot의 이벤트 기반 아키텍처를 정리합니다. ApplicationEventPublisher로 이벤트 발행, @EventListener와 @TransactionalEventListener로 이벤트 수신, 커스텀 이벤트 클래스 설계, 비동기 이벤트 처리까지 실전 예제로 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","event","eventlistener","applicationevent","publisher","backend"],
  content: [
    "## 이벤트 기반 아키텍처가 필요한 이유",
    "",
    "회원가입 기능을 구현할 때 가입 처리 후 **이메일 발송**, **쿠폰 지급**, **알림 전송** 등 부가 작업이 추가됩니다. 이런 작업을 Service 안에 직접 넣으면 **강한 결합**이 생깁니다.",
    "",
    "```java",
    "// ❌ 강결합: MemberService가 모든 부가 서비스를 직접 의존",
    "@Service",
    "@RequiredArgsConstructor",
    "public class MemberService {",
    "",
    "    private final MemberRepository memberRepository;",
    "    private final EmailService emailService;",
    "    private final CouponService couponService;",
    "    private final NotificationService notificationService;",
    "    private final PointService pointService;",
    "",
    "    @Transactional",
    "    public Member signup(SignupRequest request) {",
    "        Member member = memberRepository.save(request.toEntity());",
    "",
    "        emailService.sendWelcomeEmail(member);         // 부가 로직 1",
    "        couponService.issueWelcomeCoupon(member);       // 부가 로직 2",
    "        notificationService.sendWelcome(member);        // 부가 로직 3",
    "        pointService.giveSignupPoint(member);           // 부가 로직 4",
    "",
    "        return member;",
    "    }",
    "}",
    "```",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph \"❌ 강결합\"",
    "        MS[\"MemberService\"] --> ES[\"EmailService\"]",
    "        MS --> CS[\"CouponService\"]",
    "        MS --> NS[\"NotificationService\"]",
    "        MS --> PS[\"PointService\"]",
    "    end",
    "```",
    "",
    "**문제점:**",
    "- 부가 기능이 추가될 때마다 `MemberService`를 수정해야 합니다",
    "- 이메일 발송이 실패하면 회원가입 전체가 롤백될 수 있습니다",
    "- `MemberService`가 회원가입과 무관한 서비스들에 의존합니다",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph \"✅ 이벤트 기반 (느슨한 결합)\"",
    "        MS2[\"MemberService\"] -->|이벤트 발행| EV[\"MemberSignedUpEvent\"]",
    "        EV --> ES2[\"EmailListener\"]",
    "        EV --> CS2[\"CouponListener\"]",
    "        EV --> NS2[\"NotificationListener\"]",
    "        EV --> PS2[\"PointListener\"]",
    "    end",
    "```",
    "",
    "> `MemberService`는 이벤트를 **발행**만 하고, 누가 처리하는지는 모릅니다. 부가 기능 추가/삭제 시 `MemberService`를 수정할 필요가 없습니다.",
    "",
    "---",
    "",
    "## Spring 이벤트 시스템 구조",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant S as Service (Publisher)",
    "    participant P as ApplicationEventPublisher",
    "    participant E as Event 객체",
    "    participant L1 as Listener 1",
    "    participant L2 as Listener 2",
    "    participant L3 as Listener 3",
    "",
    "    S->>P: publishEvent(event)",
    "    P->>E: 이벤트 생성/전달",
    "    P->>L1: @EventListener 호출",
    "    P->>L2: @EventListener 호출",
    "    P->>L3: @EventListener 호출",
    "```",
    "",
    "| 구성 요소 | 역할 | 비유 |",
    "|----------|------|------|",
    "| **Event** | 발생한 사건을 담는 객체 | 공지문 |",
    "| **Publisher** | 이벤트를 발행하는 주체 | 방송국 |",
    "| **Listener** | 이벤트를 수신하여 처리 | 라디오 수신기 |",
    "",
    "---",
    "",
    "## 프로젝트 설정 (IntelliJ 실습)",
    "",
    "### 1단계: 인텔리제이에서 프로젝트 만들기",
    "",
    "IntelliJ IDEA → **New Project** → **Spring Boot** (Spring Initializr) 선택 후 다음과 같이 설정합니다.",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | `springboot_event_example` |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "**Dependencies** 화면에서 다음 두 가지를 추가합니다:",
    "- **Spring Web** (`spring-boot-starter-web`)",
    "- **Lombok** (`lombok`)",
    "",
    "### 2단계: build.gradle 전체",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "> Spring 이벤트 시스템은 `spring-boot-starter`에 내장되어 있어 **별도 의존성이 필요 없습니다.** `spring-boot-starter-web`에 포함되어 있습니다.",
    "",
    "### 3단계: 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/springboot_event_example/",
    "├── SpringbootEventExampleApplication.java",
    "├── event/",
    "│   └── OrderCreatedEvent.java",
    "├── service/",
    "│   └── OrderService.java",
    "├── listener/",
    "│   ├── EmailNotificationListener.java",
    "│   └── InventoryListener.java",
    "└── controller/",
    "    └── OrderController.java",
    "",
    "src/main/resources/",
    "└── application.yml",
    "```",
    "",
    "### 4단계: 전체 코드 작성",
    "",
    "#### SpringbootEventExampleApplication.java",
    "",
    "```java",
    "package com.example.springboot_event_example;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class SpringbootEventExampleApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(SpringbootEventExampleApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "#### OrderCreatedEvent.java (커스텀 이벤트)",
    "",
    "```java",
    "package com.example.springboot_event_example.event;",
    "",
    "import lombok.AllArgsConstructor;",
    "import lombok.Getter;",
    "",
    "@Getter",
    "@AllArgsConstructor",
    "public class OrderCreatedEvent {",
    "    private final Long orderId;",
    "    private final String productName;",
    "    private final int quantity;",
    "}",
    "```",
    "",
    "> POJO 방식의 이벤트 클래스입니다. `ApplicationEvent`를 상속하지 않아도 됩니다. 주문 ID, 상품명, 수량 정보를 담습니다.",
    "",
    "#### OrderService.java (이벤트 발행)",
    "",
    "```java",
    "package com.example.springboot_event_example.service;",
    "",
    "import com.example.springboot_event_example.event.OrderCreatedEvent;",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.context.ApplicationEventPublisher;",
    "import org.springframework.stereotype.Service;",
    "",
    "import java.util.concurrent.atomic.AtomicLong;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class OrderService {",
    "",
    "    private final ApplicationEventPublisher eventPublisher;",
    "    private final AtomicLong orderIdGenerator = new AtomicLong(1);",
    "",
    "    public Long createOrder(String productName, int quantity) {",
    "        Long orderId = orderIdGenerator.getAndIncrement();",
    "        log.info(\"[OrderService] 주문 생성 완료 - orderId={}, product={}, qty={}\",",
    "                orderId, productName, quantity);",
    "",
    "        eventPublisher.publishEvent(",
    "                new OrderCreatedEvent(orderId, productName, quantity)",
    "        );",
    "",
    "        return orderId;",
    "    }",
    "}",
    "```",
    "",
    "> `ApplicationEventPublisher`를 주입받아 `publishEvent()`로 이벤트를 발행합니다. DB 없이 `AtomicLong`으로 주문 ID를 생성합니다.",
    "",
    "#### EmailNotificationListener.java (이메일 알림 리스너)",
    "",
    "```java",
    "package com.example.springboot_event_example.listener;",
    "",
    "import com.example.springboot_event_example.event.OrderCreatedEvent;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.context.event.EventListener;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Component",
    "@Slf4j",
    "public class EmailNotificationListener {",
    "",
    "    @EventListener",
    "    public void handleOrderCreated(OrderCreatedEvent event) {",
    "        log.info(\"[EmailListener] 주문 확인 메일 발송 - orderId={}, product={}, qty={}\",",
    "                event.getOrderId(), event.getProductName(), event.getQuantity());",
    "    }",
    "}",
    "```",
    "",
    "#### InventoryListener.java (재고 처리 리스너)",
    "",
    "```java",
    "package com.example.springboot_event_example.listener;",
    "",
    "import com.example.springboot_event_example.event.OrderCreatedEvent;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.context.event.EventListener;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Component",
    "@Slf4j",
    "public class InventoryListener {",
    "",
    "    @EventListener",
    "    public void handleOrderCreated(OrderCreatedEvent event) {",
    "        log.info(\"[InventoryListener] 재고 차감 처리 - product={}, qty={}\",",
    "                event.getProductName(), event.getQuantity());",
    "    }",
    "}",
    "```",
    "",
    "> 두 리스너 모두 `@EventListener`로 같은 `OrderCreatedEvent`를 수신합니다. `OrderService`는 리스너의 존재를 모릅니다.",
    "",
    "#### OrderController.java (REST API)",
    "",
    "```java",
    "package com.example.springboot_event_example.controller;",
    "",
    "import com.example.springboot_event_example.service.OrderService;",
    "import lombok.Getter;",
    "import lombok.NoArgsConstructor;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.web.bind.annotation.PostMapping;",
    "import org.springframework.web.bind.annotation.RequestBody;",
    "import org.springframework.web.bind.annotation.RequestMapping;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "import java.util.Map;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/orders\")",
    "@RequiredArgsConstructor",
    "public class OrderController {",
    "",
    "    private final OrderService orderService;",
    "",
    "    @PostMapping",
    "    public ResponseEntity<Map<String, Object>> createOrder(@RequestBody OrderRequest request) {",
    "        Long orderId = orderService.createOrder(request.getProductName(), request.getQuantity());",
    "        return ResponseEntity.ok(Map.of(",
    "                \"orderId\", orderId,",
    "                \"message\", \"주문이 생성되었습니다.\"",
    "        ));",
    "    }",
    "",
    "    @Getter",
    "    @NoArgsConstructor",
    "    static class OrderRequest {",
    "        private String productName;",
    "        private int quantity;",
    "    }",
    "}",
    "```",
    "",
    "#### application.yml",
    "",
    "```yaml",
    "server:",
    "  port: 8080",
    "```",
    "",
    "### 5단계: Postman으로 테스트",
    "",
    "애플리케이션을 실행한 뒤 Postman(또는 `curl`)으로 POST 요청을 보냅니다.",
    "",
    "```",
    "POST http://localhost:8080/api/orders",
    "Content-Type: application/json",
    "",
    "{",
    "    \"productName\": \"스프링부트 교재\",",
    "    \"quantity\": 2",
    "}",
    "```",
    "",
    "**응답 (JSON):**",
    "",
    "```json",
    "{",
    "    \"orderId\": 1,",
    "    \"message\": \"주문이 생성되었습니다.\"",
    "}",
    "```",
    "",
    "**콘솔 출력 (두 리스너 모두 실행됨):**",
    "",
    "```",
    "[OrderService] 주문 생성 완료 - orderId=1, product=스프링부트 교재, qty=2",
    "[EmailListener] 주문 확인 메일 발송 - orderId=1, product=스프링부트 교재, qty=2",
    "[InventoryListener] 재고 차감 처리 - product=스프링부트 교재, qty=2",
    "```",
    "",
    "> 하나의 이벤트를 발행했을 뿐인데, **두 개의 리스너가 각각 독립적으로 실행**되었습니다. `OrderService`는 이메일이나 재고 서비스를 직접 의존하지 않습니다. 새 리스너를 추가해도 `OrderService`를 수정할 필요가 없습니다.",
    "",
    "---",
    "",
    "# 1. 커스텀 이벤트 클래스",
    "",
    "## 방법 1: POJO (추천)",
    "",
    "Spring 4.2부터 `ApplicationEvent`를 상속하지 않아도 **일반 객체(POJO)**를 이벤트로 사용할 수 있습니다.",
    "",
    "```java",
    "package com.example.demo.event;",
    "",
    "import lombok.AllArgsConstructor;",
    "import lombok.Getter;",
    "",
    "import java.time.LocalDateTime;",
    "",
    "@Getter",
    "@AllArgsConstructor",
    "public class MemberSignedUpEvent {",
    "    private final Long memberId;",
    "    private final String email;",
    "    private final String name;",
    "    private final LocalDateTime signedUpAt;",
    "}",
    "```",
    "",
    "```java",
    "@Getter",
    "@AllArgsConstructor",
    "public class OrderCreatedEvent {",
    "    private final Long orderId;",
    "    private final Long memberId;",
    "    private final String productName;",
    "    private final int totalPrice;",
    "    private final LocalDateTime orderedAt;",
    "}",
    "```",
    "",
    "## 방법 2: ApplicationEvent 상속 (레거시)",
    "",
    "```java",
    "public class MemberSignedUpEvent extends ApplicationEvent {",
    "",
    "    private final Long memberId;",
    "    private final String email;",
    "",
    "    public MemberSignedUpEvent(Object source, Long memberId, String email) {",
    "        super(source);  // 이벤트 발행자 참조",
    "        this.memberId = memberId;",
    "        this.email = email;",
    "    }",
    "}",
    "```",
    "",
    "> `ApplicationEvent` 상속은 Spring에 종속되므로, **POJO 방식을 권장**합니다.",
    "",
    "## 공통 베이스 이벤트 (선택)",
    "",
    "여러 이벤트에 공통 정보(발생 시각, 이벤트 ID 등)를 담고 싶다면 베이스 클래스를 만들 수 있습니다.",
    "",
    "```java",
    "@Getter",
    "public abstract class BaseEvent {",
    "    private final String eventId;",
    "    private final LocalDateTime occurredAt;",
    "",
    "    protected BaseEvent() {",
    "        this.eventId = UUID.randomUUID().toString();",
    "        this.occurredAt = LocalDateTime.now();",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@Getter",
    "public class MemberSignedUpEvent extends BaseEvent {",
    "    private final Long memberId;",
    "    private final String email;",
    "    private final String name;",
    "",
    "    public MemberSignedUpEvent(Long memberId, String email, String name) {",
    "        super();",
    "        this.memberId = memberId;",
    "        this.email = email;",
    "        this.name = name;",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "# 2. ApplicationEventPublisher (이벤트 발행)",
    "",
    "## 기본 사용법",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import com.example.demo.event.MemberSignedUpEvent;",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.context.ApplicationEventPublisher;",
    "import org.springframework.stereotype.Service;",
    "import org.springframework.transaction.annotation.Transactional;",
    "",
    "import java.time.LocalDateTime;",
    "",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class MemberService {",
    "",
    "    private final MemberRepository memberRepository;",
    "    private final ApplicationEventPublisher eventPublisher;",
    "",
    "    @Transactional",
    "    public Member signup(SignupRequest request) {",
    "        // 핵심 로직: 회원 저장",
    "        Member member = memberRepository.save(request.toEntity());",
    "        log.info(\"회원가입 완료: {}\", member.getEmail());",
    "",
    "        // 이벤트 발행 (누가 처리하는지 모름)",
    "        eventPublisher.publishEvent(",
    "                new MemberSignedUpEvent(",
    "                        member.getId(),",
    "                        member.getEmail(),",
    "                        member.getName(),",
    "                        LocalDateTime.now()",
    "                )",
    "        );",
    "",
    "        return member;",
    "    }",
    "}",
    "```",
    "",
    "> `MemberService`는 `EmailService`, `CouponService` 등을 직접 의존하지 않습니다. 이벤트만 발행하면 됩니다.",
    "",
    "## 주문 서비스 예제",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class OrderService {",
    "",
    "    private final OrderRepository orderRepository;",
    "    private final ApplicationEventPublisher eventPublisher;",
    "",
    "    @Transactional",
    "    public Order createOrder(OrderRequest request) {",
    "        Order order = orderRepository.save(request.toEntity());",
    "        log.info(\"주문 생성: {}\", order.getId());",
    "",
    "        eventPublisher.publishEvent(",
    "                new OrderCreatedEvent(",
    "                        order.getId(),",
    "                        order.getMemberId(),",
    "                        order.getProductName(),",
    "                        order.getTotalPrice(),",
    "                        LocalDateTime.now()",
    "                )",
    "        );",
    "",
    "        return order;",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "# 3. @EventListener (이벤트 수신)",
    "",
    "## 기본 사용법",
    "",
    "```java",
    "package com.example.demo.listener;",
    "",
    "import com.example.demo.event.MemberSignedUpEvent;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.context.event.EventListener;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Component",
    "@Slf4j",
    "public class EmailEventListener {",
    "",
    "    @EventListener",
    "    public void handleMemberSignedUp(MemberSignedUpEvent event) {",
    "        log.info(\"[이메일] 환영 메일 발송: {} → {}\",",
    "                event.getName(), event.getEmail());",
    "        // 실제 이메일 발송 로직",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class CouponEventListener {",
    "",
    "    @EventListener",
    "    public void handleMemberSignedUp(MemberSignedUpEvent event) {",
    "        log.info(\"[쿠폰] 가입 축하 쿠폰 발급: memberId={}\", event.getMemberId());",
    "        // 쿠폰 발급 로직",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class NotificationEventListener {",
    "",
    "    @EventListener",
    "    public void handleMemberSignedUp(MemberSignedUpEvent event) {",
    "        log.info(\"[알림] 가입 환영 알림: {}\", event.getName());",
    "        // 푸시 알림 로직",
    "    }",
    "}",
    "```",
    "",
    "## 실행 결과 로그",
    "",
    "```",
    "회원가입 완료: user@example.com",
    "[이메일] 환영 메일 발송: 홍길동 → user@example.com",
    "[쿠폰] 가입 축하 쿠폰 발급: memberId=1",
    "[알림] 가입 환영 알림: 홍길동",
    "```",
    "",
    "> 새로운 부가 기능이 필요하면 **Listener만 추가**하면 됩니다. `MemberService`는 수정하지 않습니다.",
    "",
    "## 조건부 이벤트 처리 (condition)",
    "",
    "```java",
    "@EventListener(condition = \"#event.totalPrice >= 100000\")",
    "public void handleHighValueOrder(OrderCreatedEvent event) {",
    "    log.info(\"[VIP] 고액 주문 특별 처리: {}원\", event.getTotalPrice());",
    "}",
    "```",
    "",
    "> SpEL(Spring Expression Language)로 조건을 지정하여, **특정 조건의 이벤트만** 처리할 수 있습니다.",
    "",
    "## 이벤트 리턴으로 체이닝",
    "",
    "리스너가 **새 이벤트를 반환**하면, 그 이벤트도 자동으로 발행됩니다.",
    "",
    "```java",
    "@EventListener",
    "public CouponIssuedEvent handleMemberSignedUp(MemberSignedUpEvent event) {",
    "    log.info(\"쿠폰 발급: memberId={}\", event.getMemberId());",
    "",
    "    // 새 이벤트를 반환 → 자동 발행",
    "    return new CouponIssuedEvent(event.getMemberId(), \"WELCOME_10\");",
    "}",
    "",
    "@EventListener",
    "public void handleCouponIssued(CouponIssuedEvent event) {",
    "    log.info(\"쿠폰 발급 알림: {} → {}\", event.getMemberId(), event.getCouponCode());",
    "}",
    "```",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"MemberSignedUpEvent\"] --> B[\"CouponListener\"]",
    "    B -->|반환| C[\"CouponIssuedEvent\"]",
    "    C --> D[\"CouponNotificationListener\"]",
    "```",
    "",
    "## 실행 순서 제어 (@Order)",
    "",
    "```java",
    "@Component",
    "public class EventListeners {",
    "",
    "    @EventListener",
    "    @Order(1)",
    "    public void firstHandler(MemberSignedUpEvent event) {",
    "        log.info(\"1번째 실행: 데이터 검증\");",
    "    }",
    "",
    "    @EventListener",
    "    @Order(2)",
    "    public void secondHandler(MemberSignedUpEvent event) {",
    "        log.info(\"2번째 실행: 이메일 발송\");",
    "    }",
    "",
    "    @EventListener",
    "    @Order(3)",
    "    public void thirdHandler(MemberSignedUpEvent event) {",
    "        log.info(\"3번째 실행: 알림 전송\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "# 4. @TransactionalEventListener (트랜잭션 연동)",
    "",
    "## 문제 상황",
    "",
    "기본 `@EventListener`는 **이벤트 발행 즉시** 리스너가 실행됩니다. 만약 트랜잭션이 롤백되면, 이미 발송된 이메일은 취소할 수 없습니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant S as MemberService",
    "    participant DB as DB",
    "    participant L as EmailListener",
    "",
    "    Note over S,L: @EventListener (문제 발생)",
    "    S->>DB: 회원 저장",
    "    S->>L: 이벤트 발행 → 이메일 발송 ✅",
    "    S->>DB: 후속 로직에서 예외 발생!",
    "    S->>DB: 트랜잭션 롤백 ❌",
    "    Note over L: 이메일은 이미 발송됨 😱",
    "```",
    "",
    "## 해결: @TransactionalEventListener",
    "",
    "`@TransactionalEventListener`는 **트랜잭션이 커밋된 후**에 리스너를 실행합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant S as MemberService",
    "    participant DB as DB",
    "    participant L as EmailListener",
    "",
    "    Note over S,L: @TransactionalEventListener (안전)",
    "    S->>DB: 회원 저장",
    "    S->>S: 이벤트 발행 (대기 중...)",
    "    S->>DB: 트랜잭션 커밋 ✅",
    "    S->>L: 커밋 후 이메일 발송 ✅",
    "```",
    "",
    "```java",
    "package com.example.demo.listener;",
    "",
    "import com.example.demo.event.MemberSignedUpEvent;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.stereotype.Component;",
    "import org.springframework.transaction.event.TransactionalEventListener;",
    "import org.springframework.transaction.event.TransactionPhase;",
    "",
    "@Component",
    "@Slf4j",
    "public class EmailEventListener {",
    "",
    "    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)",
    "    public void handleMemberSignedUp(MemberSignedUpEvent event) {",
    "        log.info(\"[이메일] 트랜잭션 커밋 후 환영 메일 발송: {}\", event.getEmail());",
    "    }",
    "}",
    "```",
    "",
    "## TransactionPhase 옵션",
    "",
    "| Phase | 실행 시점 | 사용 예 |",
    "|-------|---------|--------|",
    "| `AFTER_COMMIT` (기본) | 트랜잭션 **커밋 후** | 이메일, 알림 (가장 많이 사용) |",
    "| `AFTER_ROLLBACK` | 트랜잭션 **롤백 후** | 실패 로깅, 보상 처리 |",
    "| `AFTER_COMPLETION` | 커밋 또는 롤백 **후** | 리소스 정리 |",
    "| `BEFORE_COMMIT` | 커밋 **직전** | 유효성 최종 검증 |",
    "",
    "```java",
    "// 트랜잭션 롤백 시 실행",
    "@TransactionalEventListener(phase = TransactionPhase.AFTER_ROLLBACK)",
    "public void handleSignupFailed(MemberSignedUpEvent event) {",
    "    log.error(\"[알림] 회원가입 롤백됨: {}\", event.getEmail());",
    "    // 관리자 알림, 보상 로직 등",
    "}",
    "```",
    "",
    "---",
    "",
    "# 5. 비동기 이벤트 처리 (@Async + @EventListener)",
    "",
    "## 문제: 동기 이벤트의 한계",
    "",
    "기본 `@EventListener`는 **동기적**으로 실행됩니다. 리스너가 오래 걸리면 발행자도 대기합니다.",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant S as MemberService",
    "    participant L1 as EmailListener (3초)",
    "    participant L2 as CouponListener (1초)",
    "    participant L3 as NotificationListener (2초)",
    "",
    "    Note over S,L3: 동기 이벤트 (총 6초 대기)",
    "    S->>L1: 이메일 발송 (3초)",
    "    L1-->>S: 완료",
    "    S->>L2: 쿠폰 발급 (1초)",
    "    L2-->>S: 완료",
    "    S->>L3: 알림 전송 (2초)",
    "    L3-->>S: 완료",
    "    S-->>S: 총 6초 후 응답",
    "```",
    "",
    "## 해결: @Async 비동기 이벤트",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant S as MemberService",
    "    participant L1 as EmailListener",
    "    participant L2 as CouponListener",
    "    participant L3 as NotificationListener",
    "",
    "    Note over S,L3: 비동기 이벤트 (즉시 반환)",
    "    S->>L1: 이메일 발송 (별도 스레드)",
    "    S->>L2: 쿠폰 발급 (별도 스레드)",
    "    S->>L3: 알림 전송 (별도 스레드)",
    "    S-->>S: 즉시 응답 ⚡",
    "```",
    "",
    "### @EnableAsync 설정",
    "",
    "```java",
    "@Configuration",
    "@EnableAsync",
    "public class AsyncConfig {",
    "",
    "    @Bean(name = \"eventExecutor\")",
    "    public Executor eventExecutor() {",
    "        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();",
    "        executor.setCorePoolSize(3);",
    "        executor.setMaxPoolSize(10);",
    "        executor.setQueueCapacity(50);",
    "        executor.setThreadNamePrefix(\"Event-\");",
    "        executor.initialize();",
    "        return executor;",
    "    }",
    "}",
    "```",
    "",
    "### 비동기 리스너",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class EmailEventListener {",
    "",
    "    @Async(\"eventExecutor\")",
    "    @EventListener",
    "    public void handleMemberSignedUp(MemberSignedUpEvent event) {",
    "        log.info(\"[{}] 이메일 발송 시작: {}\",",
    "                Thread.currentThread().getName(), event.getEmail());",
    "",
    "        // 3초 걸리는 이메일 발송",
    "        try { Thread.sleep(3000); } catch (InterruptedException e) { }",
    "",
    "        log.info(\"[{}] 이메일 발송 완료: {}\",",
    "                Thread.currentThread().getName(), event.getEmail());",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class CouponEventListener {",
    "",
    "    @Async(\"eventExecutor\")",
    "    @EventListener",
    "    public void handleMemberSignedUp(MemberSignedUpEvent event) {",
    "        log.info(\"[{}] 쿠폰 발급: memberId={}\",",
    "                Thread.currentThread().getName(), event.getMemberId());",
    "    }",
    "}",
    "```",
    "",
    "### 실행 결과 로그",
    "",
    "```",
    "[main] 회원가입 완료: user@example.com",
    "[Event-1] 이메일 발송 시작: user@example.com",
    "[Event-2] 쿠폰 발급: memberId=1",
    "[Event-3] 가입 환영 알림: 홍길동",
    "[main] 회원가입 응답 즉시 반환 ⚡",
    "[Event-1] 이메일 발송 완료: user@example.com",
    "```",
    "",
    "> 리스너들이 별도 스레드에서 실행되므로 **메인 스레드는 즉시 응답**합니다.",
    "",
    "### @Async + @TransactionalEventListener",
    "",
    "트랜잭션 커밋 후 비동기로 처리하는 가장 안전한 패턴입니다.",
    "",
    "```java",
    "@Async(\"eventExecutor\")",
    "@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)",
    "public void handleMemberSignedUp(MemberSignedUpEvent event) {",
    "    log.info(\"트랜잭션 커밋 후 + 비동기 이메일 발송: {}\", event.getEmail());",
    "}",
    "```",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"이벤트 발행\"] --> B{\"트랜잭션 커밋?\"}",
    "    B -->|성공| C[\"비동기 스레드에서 리스너 실행\"]",
    "    B -->|롤백| D[\"리스너 실행 안 함\"]",
    "```",
    "",
    "---",
    "",
    "# 6. 실전 예제: 주문 이벤트 시스템",
    "",
    "```mermaid",
    "flowchart TD",
    "    OC[\"OrderController\"] --> OS[\"OrderService\"]",
    "    OS -->|이벤트 발행| OE[\"OrderCreatedEvent\"]",
    "",
    "    OE --> L1[\"EmailListener<br/>주문 확인 메일\"]",
    "    OE --> L2[\"InventoryListener<br/>재고 차감\"]",
    "    OE --> L3[\"PointListener<br/>포인트 적립\"]",
    "    OE --> L4[\"AnalyticsListener<br/>통계 업데이트\"]",
    "```",
    "",
    "### 이벤트 클래스",
    "",
    "```java",
    "@Getter",
    "public class OrderCreatedEvent extends BaseEvent {",
    "    private final Long orderId;",
    "    private final Long memberId;",
    "    private final String memberEmail;",
    "    private final String productName;",
    "    private final int quantity;",
    "    private final int totalPrice;",
    "",
    "    @Builder",
    "    public OrderCreatedEvent(Long orderId, Long memberId, String memberEmail,",
    "                             String productName, int quantity, int totalPrice) {",
    "        super();",
    "        this.orderId = orderId;",
    "        this.memberId = memberId;",
    "        this.memberEmail = memberEmail;",
    "        this.productName = productName;",
    "        this.quantity = quantity;",
    "        this.totalPrice = totalPrice;",
    "    }",
    "}",
    "```",
    "",
    "### Service (이벤트 발행)",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "@Slf4j",
    "public class OrderService {",
    "",
    "    private final OrderRepository orderRepository;",
    "    private final ApplicationEventPublisher eventPublisher;",
    "",
    "    @Transactional",
    "    public OrderResponse createOrder(OrderRequest request) {",
    "        Order order = orderRepository.save(request.toEntity());",
    "",
    "        eventPublisher.publishEvent(",
    "                OrderCreatedEvent.builder()",
    "                        .orderId(order.getId())",
    "                        .memberId(request.getMemberId())",
    "                        .memberEmail(request.getEmail())",
    "                        .productName(order.getProductName())",
    "                        .quantity(order.getQuantity())",
    "                        .totalPrice(order.getTotalPrice())",
    "                        .build()",
    "        );",
    "",
    "        return OrderResponse.from(order);",
    "    }",
    "}",
    "```",
    "",
    "### Listeners (이벤트 처리)",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class OrderEventListeners {",
    "",
    "    @Async(\"eventExecutor\")",
    "    @TransactionalEventListener",
    "    public void sendOrderConfirmation(OrderCreatedEvent event) {",
    "        log.info(\"[이메일] 주문 확인: {} → {}\",",
    "                event.getOrderId(), event.getMemberEmail());",
    "    }",
    "",
    "    @TransactionalEventListener",
    "    public void deductInventory(OrderCreatedEvent event) {",
    "        log.info(\"[재고] {} x{}개 차감\",",
    "                event.getProductName(), event.getQuantity());",
    "    }",
    "",
    "    @Async(\"eventExecutor\")",
    "    @TransactionalEventListener",
    "    public void accumulatePoints(OrderCreatedEvent event) {",
    "        int points = (int) (event.getTotalPrice() * 0.01);",
    "        log.info(\"[포인트] {}P 적립: memberId={}\",",
    "                points, event.getMemberId());",
    "    }",
    "",
    "    @Async(\"eventExecutor\")",
    "    @TransactionalEventListener",
    "    @Order(99)",
    "    public void updateAnalytics(OrderCreatedEvent event) {",
    "        log.info(\"[분석] 주문 통계 업데이트: {}원\", event.getTotalPrice());",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "# 7. Spring 내장 이벤트",
    "",
    "Spring은 애플리케이션 라이프사이클 이벤트를 기본 제공합니다.",
    "",
    "| 이벤트 | 발생 시점 |",
    "|--------|---------|",
    "| `ContextRefreshedEvent` | ApplicationContext 초기화 또는 새로고침 |",
    "| `ContextStartedEvent` | ApplicationContext 시작 |",
    "| `ContextStoppedEvent` | ApplicationContext 정지 |",
    "| `ContextClosedEvent` | ApplicationContext 종료 |",
    "| `ApplicationReadyEvent` | **애플리케이션 완전 시작** (가장 많이 사용) |",
    "| `ApplicationStartedEvent` | 애플리케이션 시작 직후 |",
    "",
    "```java",
    "@Component",
    "@Slf4j",
    "public class ApplicationEventListeners {",
    "",
    "    @EventListener(ApplicationReadyEvent.class)",
    "    public void onApplicationReady() {",
    "        log.info(\"애플리케이션 시작 완료! 초기 데이터를 로드합니다.\");",
    "        // 캐시 워밍업, 초기 데이터 로드 등",
    "    }",
    "",
    "    @EventListener(ContextClosedEvent.class)",
    "    public void onShutdown() {",
    "        log.info(\"애플리케이션 종료 중... 리소스를 정리합니다.\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 이벤트 vs 메시징 비교",
    "",
    "| 비교 | Spring Event | RabbitMQ / Kafka |",
    "|------|-------------|-----------------|",
    "| 범위 | **같은 JVM 내부** | 서로 다른 애플리케이션 |",
    "| 브로커 | 불필요 | 외부 브로커 필요 |",
    "| 영속성 | 없음 (메모리) | 디스크 저장 가능 |",
    "| 재시도 | 직접 구현 | 브로커가 지원 |",
    "| 복잡도 | 낮음 | 높음 |",
    "| 적합 | 같은 앱 내 느슨한 결합 | 마이크로서비스 간 통신 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A{\"서비스 간 통신?\"} -->|같은 애플리케이션 내부| B[\"Spring Event\"]",
    "    A -->|서로 다른 서비스| C{\"메시지 보관 필요?\"}",
    "    C -->|아니오, 작업 큐| D[\"RabbitMQ\"]",
    "    C -->|예, 이벤트 스트림| E[\"Kafka\"]",
    "```",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "### 1. @EventListener는 기본 동기",
    "리스너가 예외를 던지면 발행자에게 전파됩니다. 부가 로직의 실패가 핵심 로직에 영향을 주지 않으려면 `@Async`를 사용하세요.",
    "",
    "### 2. @TransactionalEventListener는 트랜잭션 없으면 무시",
    "`publishEvent()`가 `@Transactional` 메서드 밖에서 호출되면 `@TransactionalEventListener`는 **실행되지 않습니다**.",
    "",
    "```java",
    "// ❌ 트랜잭션 없음 → @TransactionalEventListener 동작 안 함",
    "public void someMethod() {",
    "    eventPublisher.publishEvent(new SomeEvent());",
    "}",
    "",
    "// ✅ 트랜잭션 있음 → 정상 동작",
    "@Transactional",
    "public void someMethod() {",
    "    eventPublisher.publishEvent(new SomeEvent());",
    "}",
    "```",
    "",
    "> `fallbackExecution = true`를 설정하면 트랜잭션 없이도 실행됩니다.",
    "",
    "```java",
    "@TransactionalEventListener(fallbackExecution = true)",
    "public void handle(SomeEvent event) { ... }",
    "```",
    "",
    "### 3. 같은 클래스 내부 호출 주의",
    "`@Async`는 AOP 프록시 기반이므로 같은 클래스 내부 호출에서는 비동기가 적용되지 않습니다. 리스너는 별도 `@Component` 클래스로 분리하세요.",
    "",
    "### 4. 이벤트 리스너 예외 처리",
    "",
    "```java",
    "@Async(\"eventExecutor\")",
    "@EventListener",
    "public void handleEvent(MemberSignedUpEvent event) {",
    "    try {",
    "        sendEmail(event.getEmail());",
    "    } catch (Exception e) {",
    "        log.error(\"이메일 발송 실패: {}\", event.getEmail(), e);",
    "        // 재시도 큐에 넣기, 알림 등",
    "    }",
    "}",
    "```",
    "",
    "### 5. 이벤트 발행은 가벼워야 합니다",
    "이벤트 객체에 무거운 데이터(파일, 바이트 배열 등)를 담지 마세요. **ID만 전달**하고 리스너에서 필요한 데이터를 조회하는 것이 좋습니다.",
    "",
    "```java",
    "// ❌ 무거운 이벤트",
    "new FileUploadedEvent(fileBytes, fileName, ...);",
    "",
    "// ✅ 가벼운 이벤트 (ID만 전달)",
    "new FileUploadedEvent(fileId, fileName);",
    "```",
    "",
    "---",
    "",
    "## AOP vs 이벤트 비교",
    "",
    "AOP와 이벤트는 모두 **핵심 로직과 부가 로직을 분리**하는 데 사용되지만, 목적과 동작 방식이 다릅니다.",
    "",
    "### 핵심 차이",
    "",
    "```mermaid",
    "flowchart TD",
    "    subgraph \"AOP (Aspect Oriented Programming)\"",
    "        A1[\"Controller / Service\"] -->|메서드 호출| A2[\"Proxy가 가로챔\"]",
    "        A2 -->|Before| A3[\"부가 로직 실행\"]",
    "        A3 --> A4[\"원본 메서드 실행\"]",
    "        A4 -->|After| A5[\"부가 로직 실행\"]",
    "    end",
    "",
    "    subgraph \"Event (이벤트)\"",
    "        B1[\"Service\"] -->|publishEvent| B2[\"이벤트 객체\"]",
    "        B2 --> B3[\"Listener A\"]",
    "        B2 --> B4[\"Listener B\"]",
    "        B2 --> B5[\"Listener C\"]",
    "    end",
    "```",
    "",
    "| 비교 항목 | AOP | Event |",
    "|----------|-----|-------|",
    "| **목적** | 횡단 관심사를 메서드 실행 전후에 끼워넣기 | 발생한 사건을 여러 리스너에게 알리기 |",
    "| **결합도** | 대상 메서드를 **알고 있음** (Pointcut으로 지정) | 발행자는 리스너를 **모름** (완전 분리) |",
    "| **실행 시점** | 메서드 호출 전/후/예외 등 자동 실행 | `publishEvent()` 호출 시점에 실행 |",
    "| **적용 대상** | 패턴으로 여러 메서드에 일괄 적용 | 특정 이벤트 타입에 대한 1:N 처리 |",
    "| **코드 변경** | 대상 메서드 코드 변경 없음 | `publishEvent()` 호출 코드 추가 필요 |",
    "| **대표 사용처** | 로깅, 인증, 트랜잭션, 성능 측정 | 회원가입 후처리, 주문 후처리, 알림 |",
    "",
    "### 코드 비교: 같은 요구사항을 AOP와 이벤트로 구현",
    "",
    "**요구사항:** 회원가입 시 실행 시간을 로깅하고, 환영 이메일을 발송한다.",
    "",
    "#### AOP로 구현 - 실행 시간 로깅",
    "",
    "```java",
    "@Aspect",
    "@Component",
    "@Slf4j",
    "public class ExecutionTimeAspect {",
    "",
    "    @Around(\"execution(* com.example.demo.service.*Service.*(..))\")",
    "    public Object logExecutionTime(ProceedingJoinPoint joinPoint) throws Throwable {",
    "        long start = System.currentTimeMillis();",
    "        Object result = joinPoint.proceed();",
    "        long elapsed = System.currentTimeMillis() - start;",
    "",
    "        log.info(\"[AOP] {}.{} 실행 시간: {}ms\",",
    "                joinPoint.getTarget().getClass().getSimpleName(),",
    "                joinPoint.getSignature().getName(), elapsed);",
    "",
    "        return result;",
    "    }",
    "}",
    "```",
    "",
    "> AOP는 `MemberService`, `OrderService` 등 **모든 Service 메서드에 자동 적용**됩니다. 대상 메서드 코드를 수정할 필요가 없습니다.",
    "",
    "#### 이벤트로 구현 - 환영 이메일 발송",
    "",
    "```java",
    "// Service: 이벤트 발행",
    "@Service",
    "@RequiredArgsConstructor",
    "public class MemberService {",
    "    private final ApplicationEventPublisher eventPublisher;",
    "",
    "    @Transactional",
    "    public Member signup(SignupRequest request) {",
    "        Member member = memberRepository.save(request.toEntity());",
    "        eventPublisher.publishEvent(new MemberSignedUpEvent(member.getId(), member.getEmail()));",
    "        return member;",
    "    }",
    "}",
    "",
    "// Listener: 이메일 발송",
    "@Component",
    "@Slf4j",
    "public class WelcomeEmailListener {",
    "    @Async",
    "    @TransactionalEventListener",
    "    public void send(MemberSignedUpEvent event) {",
    "        log.info(\"환영 이메일 발송: {}\", event.getEmail());",
    "    }",
    "}",
    "```",
    "",
    "> 이벤트는 **회원가입이라는 특정 사건 발생 시** 후속 처리를 위해 사용합니다. 리스너를 추가/제거해도 `MemberService`는 변경되지 않습니다.",
    "",
    "### 왜 실행 시간 로깅에 이벤트를 쓰면 안 되는가?",
    "",
    "```java",
    "// ❌ 이벤트로 실행 시간 로깅? → 비효율적",
    "public Member signup(SignupRequest request) {",
    "    long start = System.currentTimeMillis();",
    "    Member member = memberRepository.save(request.toEntity());",
    "    long elapsed = System.currentTimeMillis() - start;",
    "",
    "    eventPublisher.publishEvent(new ExecutionTimeEvent(\"signup\", elapsed));",
    "    return member;",
    "}",
    "```",
    "",
    "모든 메서드에 시간 측정 코드를 직접 넣어야 하므로 **코드 중복**이 발생합니다. 이런 작업은 AOP가 적합합니다.",
    "",
    "### 왜 환영 이메일 발송에 AOP를 쓰면 안 되는가?",
    "",
    "```java",
    "// ❌ AOP로 회원가입 후 이메일 발송? → 부적절",
    "@AfterReturning(\"execution(* com.example..MemberService.signup(..))\") ",
    "public void sendWelcomeEmail(JoinPoint joinPoint) {",
    "    // 반환값에서 Member 정보를 꺼내기 어려움",
    "    // signup 메서드가 변경되면 AOP도 깨짐",
    "    // 다른 후처리(쿠폰, 알림)도 추가하면 Aspect가 비대해짐",
    "}",
    "```",
    "",
    "특정 **비즈니스 이벤트에 대한 1:N 후속 처리**는 이벤트 패턴이 적합합니다. AOP는 비즈니스 로직이 아닌 **기술적 관심사**에 사용합니다.",
    "",
    "### 선택 가이드",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q1{\"부가 로직의 성격은?\"}",
    "    Q1 -->|\"기술적 관심사<br/>(로깅, 보안, 트랜잭션, 성능)\"| AOP[\"✅ AOP 사용\"]",
    "    Q1 -->|\"비즈니스 후속 처리<br/>(이메일, 쿠폰, 알림, 적립)\"| Q2{\"처리 대상이 하나?\"}",
    "    Q2 -->|\"1개\"| DIRECT[\"직접 호출도 OK\"]",
    "    Q2 -->|\"여러 개 (1:N)\"| EVENT[\"✅ Event 사용\"]",
    "```",
    "",
    "| 상황 | 추천 | 이유 |",
    "|------|------|------|",
    "| 모든 Service 메서드 실행 시간 로깅 | **AOP** | 패턴으로 일괄 적용, 코드 변경 없음 |",
    "| API 인증/인가 체크 | **AOP** (또는 Filter/Interceptor) | 횡단 관심사, 모든 요청에 적용 |",
    "| 회원가입 후 이메일 + 쿠폰 + 알림 | **Event** | 1:N 비즈니스 후속 처리, 느슨한 결합 |",
    "| 주문 완료 후 재고 차감 + 포인트 적립 | **Event** | 핵심 로직과 부가 로직 분리 |",
    "| 메서드 파라미터 유효성 검증 | **AOP** | 여러 메서드에 공통 적용 |",
    "| 데이터 변경 시 캐시 무효화 | **Event** 또는 **AOP** | 상황에 따라 선택 |",
    "",
    "### 함께 사용하는 패턴",
    "",
    "AOP와 이벤트는 **상호 배타적이 아닙니다.** 실무에서는 함께 사용하는 경우가 많습니다.",
    "",
    "```java",
    "// AOP: 모든 Service 메서드에 로깅 + 성능 측정 (기술적 관심사)",
    "@Aspect",
    "@Component",
    "public class ServiceLoggingAspect {",
    "    @Around(\"execution(* com.example..service.*Service.*(..))\")",
    "    public Object log(ProceedingJoinPoint jp) throws Throwable {",
    "        log.info(\"[시작] {}\", jp.getSignature().getName());",
    "        Object result = jp.proceed();",
    "        log.info(\"[완료] {}\", jp.getSignature().getName());",
    "        return result;",
    "    }",
    "}",
    "",
    "// Event: 회원가입 후 비즈니스 후속 처리 (비즈니스 관심사)",
    "@Service",
    "public class MemberService {",
    "    @Transactional",
    "    public Member signup(SignupRequest request) {",
    "        Member member = memberRepository.save(request.toEntity());",
    "        eventPublisher.publishEvent(new MemberSignedUpEvent(...));",
    "        return member;  // AOP가 자동으로 로깅해줌",
    "    }",
    "}",
    "```",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as Controller",
    "    participant AOP as AOP Proxy",
    "    participant S as MemberService",
    "    participant EP as EventPublisher",
    "    participant L as EmailListener",
    "",
    "    C->>AOP: signup() 호출",
    "    AOP->>AOP: [Before] 로깅 시작",
    "    AOP->>S: 원본 메서드 실행",
    "    S->>EP: publishEvent()",
    "    EP->>L: 이메일 발송 (비동기)",
    "    S-->>AOP: 반환",
    "    AOP->>AOP: [After] 실행 시간 로깅",
    "    AOP-->>C: 응답",
    "```",
    "",
    "> **AOP**는 메서드 실행 전후에 자동으로 끼어드는 **기술적 인프라**이고, **이벤트**는 비즈니스 사건 발생 시 **명시적으로 발행하는 메시지**입니다. 용도가 다르므로 적절히 조합하여 사용하세요.",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 구성 | 역할 |",
    "|------|------|",
    "| 이벤트 클래스 (POJO) | 발생한 사건의 데이터를 담는 객체 |",
    "| `ApplicationEventPublisher` | `publishEvent()`로 이벤트 발행 |",
    "| `@EventListener` | 이벤트를 수신하여 처리 (동기, 즉시 실행) |",
    "| `@TransactionalEventListener` | 트랜잭션 커밋/롤백 후 실행 |",
    "| `@Async` + `@EventListener` | 별도 스레드에서 비동기 처리 |",
    "",
    "| 패턴 | 적합한 경우 |",
    "|------|-----------|",
    "| `@EventListener` | 단순 처리, 트랜잭션 불필요 |",
    "| `@TransactionalEventListener` | DB 커밋 후 안전하게 처리 |",
    "| `@Async` + `@EventListener` | 느린 부가 작업 (이메일, 알림) |",
    "| `@Async` + `@TransactionalEventListener` | **가장 안전한 패턴** (커밋 후 + 비동기) |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
