<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-roadmap",
  title: "Spring Boot 기술 총정리 - 각 기술이 해결하는 문제와 학습 로드맵",
  date: "2026-03-14",
  summary: "Spring Boot 생태계의 기술들을 '어떤 문제를 해결하는가' 관점에서 정리합니다. 기초부터 운영까지, 각 기술의 역할과 관계를 한눈에 파악할 수 있는 로드맵입니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot", "roadmap", "overview", "backend", "java"],
  content: [
    "## 이 글의 목적",
    "",
    "Spring Boot를 학습하다 보면 기술이 너무 많아서 **\"이걸 왜 쓰는 거지?\"**라는 의문이 생깁니다. 이 글은 각 기술이 **어떤 문제를 해결**하는지 한 문장으로 요약하고, 전체적인 그림을 잡을 수 있도록 정리한 글입니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Spring Boot 기초\"] --> B[\"웹 API 개발\"]",
    "    B --> C[\"데이터 접근\"]",
    "    C --> D[\"보안\"]",
    "    D --> E[\"성능 최적화\"]",
    "    E --> F[\"외부 연동\"]",
    "    F --> G[\"운영/배포\"]",
    "    style A fill:#4CAF50,color:#fff",
    "    style G fill:#F44336,color:#fff",
    "```",
    "",
    "---",
    "",
    "## 1. Spring Boot 기초 - \"프로젝트를 시작하려면?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**Spring Boot 개요**](/post/springboot-overview) | Spring은 설정이 너무 복잡하다 → **자동 설정**으로 최소한의 코드로 시작 |",
    "| [**핵심 어노테이션**](/post/springboot-annotations) | 수많은 어노테이션이 뭘 하는지 모르겠다 → **카테고리별로 정리** |",
    "| [**application.yml**](/post/springboot-application-properties) | 설정 파일을 어떻게 작성하는지 모르겠다 → **yml/properties 문법과 프로파일** |",
    "| [**빌드 시스템**](/post/springboot-build-system) | Maven? Gradle? 뭘 선택해야 하지? → **빌드 도구 비교와 설정** |",
    "| [**설정(Configuration)**](/post/springboot-configuration) | 환경별로 설정을 어떻게 분리하지? → **프로파일, 외부 설정, 우선순위** |",
    "| [**고유 기능**](/post/springboot-features) | Spring Boot만의 특별한 기능이 뭐가 있지? → **Auto Configuration, @ConditionalOn 등** |",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"build.gradle<br>의존성 관리\"] --> B[\"application.yml<br>설정\"]",
    "    B --> C[\"@SpringBootApplication<br>자동 설정\"]",
    "    C --> D[\"애플리케이션 실행\"]",
    "```",
    "",
    "---",
    "",
    "## 2. 웹 API 개발 - \"클라이언트 요청을 어떻게 처리하지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**REST API**](/post/springboot-rest-api) | 클라이언트와 서버가 데이터를 주고받는 표준이 필요하다 → **RESTful API 설계 원칙** |",
    "| [**요청·응답 처리**](/post/springboot-request-response) | 다양한 형태의 요청 데이터를 어떻게 받지? → **@RequestBody, @PathVariable, ResponseEntity 등** |",
    "| [**Filter**](/post/springboot-filter) | 모든 요청에 공통 작업(인코딩, CORS, 로깅)을 하고 싶다 → **Servlet Filter로 요청 전/후 처리** |",
    "| [**Interceptor**](/post/springboot-interceptor) | Controller 실행 전/후에 인증 확인이나 로깅을 하고 싶다 → **HandlerInterceptor** |",
    "| [**라이브러리**](/post/springboot-libraries) | 입력 검증, 객체 변환, JSON 처리를 간편하게 하고 싶다 → **Validation, ModelMapper, Gson** |",
    "| [**예외 처리**](/post/springboot-exception-handling) | 에러가 발생하면 일관된 형식으로 응답하고 싶다 → **@RestControllerAdvice, 커스텀 예외** |",
    "| [**파일 처리**](/post/springboot-file-handling) | 파일 업로드/다운로드를 구현해야 한다 → **MultipartFile, 저장 전략** |",
    "| [**국제화(i18n)**](/post/springboot-i18n) | 다국어를 지원해야 한다 → **MessageSource, LocaleResolver** |",
    "| [**Thymeleaf**](/post/thymeleaf-overview) | 서버에서 HTML 페이지를 렌더링해야 한다 → **템플릿 엔진으로 동적 HTML 생성** |",
    "| [**DTO 패턴**](/post/springboot-dto-pattern) | Entity를 직접 노출하면 보안, 성능 문제가 생긴다 → **Request/Response DTO 분리** |",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"HTTP 요청\"] --> B[\"Filter<br>공통 처리\"]",
    "    B --> C[\"Interceptor<br>인증/로깅\"]",
    "    C --> D[\"Controller<br>요청 매핑\"]",
    "    D --> E[\"Service<br>비즈니스 로직\"]",
    "    D -.->|에러| F[\"@RestControllerAdvice<br>예외 처리\"]",
    "```",
    "",
    "---",
    "",
    "## 3. 데이터 접근 - \"DB와 어떻게 통신하지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**H2 데이터베이스**](/post/springboot-h2) | 개발/테스트할 때 DB를 설치하기 번거롭다 → **의존성만 추가하면 되는 인메모리 DB** |",
    "| [**JPA/Hibernate**](/post/springboot-jpa-hibernate) | SQL을 직접 작성하기 번거롭다 → **객체로 DB를 다루는 ORM** |",
    "| [**JPA 심화**](/post/springboot-jpa-advanced) | N+1 문제, 동적 쿼리, 페이징이 어렵다 → **Fetch Join, QueryDSL, Specification** |",
    "| [**JdbcTemplate**](/post/springboot-jdbc-template) | JPA 없이 순수 SQL로 DB를 다루고 싶다 → **JdbcTemplate으로 SQL 직접 실행** |",
    "| [**MyBatis**](/post/springboot-mybatis) | 복잡한 SQL을 XML로 깔끔하게 관리하고 싶다 → **SQL Mapper** |",
    "| [**Elasticsearch**](/post/springboot-elasticsearch) | RDBMS로 전문 검색(Full-text Search)이 어렵다 → **검색 엔진 연동** |",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q{\"어떤 상황인가?\"}",
    "    Q -->|\"객체 중심, CRUD 위주\"| JPA[\"JPA/Hibernate\"]",
    "    Q -->|\"복잡한 SQL, 레거시\"| MB[\"MyBatis\"]",
    "    Q -->|\"간단한 SQL, 가벼운 프로젝트\"| JT[\"JdbcTemplate\"]",
    "    Q -->|\"전문 검색, 자동완성\"| ES[\"Elasticsearch\"]",
    "```",
    "",
    "---",
    "",
    "## 4. 보안 - \"인증과 인가를 어떻게 구현하지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**Security (세션)**](/post/springboot-security-session) | 로그인/로그아웃, 권한 관리가 필요하다 → **세션 기반 인증** |",
    "| [**Security + JWT**](/post/springboot-security-jwt) | 서버에 세션을 저장하고 싶지 않다 (Stateless) → **토큰 기반 인증** |",
    "| [**Security 필터**](/post/springboot-security-filters) | Security가 내부적으로 어떻게 동작하는지 모르겠다 → **15개 필터 체인 동작 원리** |",
    "| [**OAuth2 소셜 로그인**](/post/springboot-oauth2) | Google, Kakao, Naver 로그인을 구현해야 한다 → **OAuth2 소셜 로그인 연동** |",
    "",
    "```mermaid",
    "flowchart TD",
    "    Q{\"인증 방식 선택\"}",
    "    Q -->|\"서버 렌더링<br>(Thymeleaf 등)\"| A[\"세션 기반\"]",
    "    Q -->|\"REST API<br>(SPA, 모바일)\"| B[\"JWT 토큰 기반\"]",
    "    Q -->|\"소셜 로그인<br>(Google, Kakao)\"| C[\"OAuth2\"]",
    "    B --> D[\"Access Token +<br>Refresh Token\"]",
    "```",
    "",
    "---",
    "",
    "## 5. 횡단 관심사 - \"공통 로직을 어떻게 분리하지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**AOP**](/post/springboot-aop) | 로깅, 트랜잭션, 권한 체크 코드가 여기저기 중복된다 → **관점 지향으로 공통 관심사 분리** |",
    "| [**프록시**](/post/springboot-proxy) | @Transactional, @Async 등이 내부적으로 어떻게 동작하지? → **프록시 패턴으로 기능 부가** |",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"실행 시간 측정\"] --> D[\"AOP로 분리\"]",
    "    B[\"로깅\"] --> D",
    "    C[\"트랜잭션 관리\"] --> D",
    "    D --> E[\"비즈니스 로직은<br>깔끔하게 유지\"]",
    "```",
    "",
    "---",
    "",
    "## 6. 성능 최적화 - \"느린 응답을 어떻게 빠르게 하지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**캐싱 + Redis**](/post/springboot-caching) | 같은 DB 조회를 반복하면 느리다 → **캐시에 저장해서 빠르게 응답** |",
    "| [**비동기 처리**](/post/springboot-async) | 이메일 발송, 알림 등 오래 걸리는 작업이 응답을 지연시킨다 → **@Async로 별도 스레드에서 처리** |",
    "| [**배치 처리**](/post/springboot-batch) | 대량 데이터를 한꺼번에 처리해야 한다 (정산, 통계) → **Spring Batch로 대규모 데이터 일괄 처리** |",
    "| [**WebFlux**](/post/springboot-webflux) | 동시 접속이 많을 때 스레드가 부족하다 → **리액티브 논블로킹으로 적은 스레드로 고성능** |",
    "",
    "```mermaid",
    "flowchart TD",
    "    P{\"성능 문제가 뭔가?\"}",
    "    P -->|\"같은 데이터 반복 조회\"| A[\"캐싱<br>(@Cacheable, Redis)\"]",
    "    P -->|\"오래 걸리는 작업이<br>응답을 지연\"| B[\"비동기 처리<br>(@Async)\"]",
    "    P -->|\"대량 데이터<br>일괄 처리\"| C[\"배치 처리<br>(Spring Batch)\"]",
    "    P -->|\"동시 접속 수만 명\"| D[\"WebFlux<br>(논블로킹)\"]",
    "```",
    "",
    "---",
    "",
    "## 7. 이벤트/메시징 - \"서비스 간 결합도를 어떻게 낮추지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**이벤트**](/post/springboot-event) | 회원가입 시 이메일 발송, 포인트 적립 등 부가 로직이 Service에 직접 엮여 있다 → **이벤트로 느슨한 결합** |",
    "| [**메시징 (RabbitMQ, Kafka)**](/post/springboot-messaging) | 서비스 간 통신이 실시간으로 묶여 있으면 장애가 전파된다 → **메시지 큐로 비동기 통신** |",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph \"강한 결합 (Before)\"",
    "        A1[\"UserService\"] -->|직접 호출| B1[\"MailService\"]",
    "        A1 -->|직접 호출| C1[\"PointService\"]",
    "    end",
    "    subgraph \"느슨한 결합 (After)\"",
    "        A2[\"UserService\"] -->|이벤트 발행| E[\"EventListener\"]",
    "        E --> B2[\"MailService\"]",
    "        E --> C2[\"PointService\"]",
    "    end",
    "```",
    "",
    "---",
    "",
    "## 8. 외부 시스템 연동 - \"다른 서비스와 어떻게 통신하지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**Slack 연동**](/post/springboot-slack) | 에러 발생, 배포 완료 시 팀에 알림을 보내고 싶다 → **Webhook/Bot으로 Slack 메시지 발송** |",
    "| [**WebSocket**](/post/springboot-websocket) | 실시간 채팅, 알림을 구현해야 한다 → **양방향 실시간 통신** |",
    "| [**GraphQL**](/post/springboot-graphql) | REST로는 원하는 데이터만 골라 받기 어렵다 → **클라이언트가 필요한 데이터만 요청** |",
    "| [**gRPC**](/post/springboot-grpc) | 마이크로서비스 간 통신이 REST보다 빨라야 한다 → **Protocol Buffers 기반 고성능 RPC** |",
    "| [**Redis**](/post/springboot-redis) | 빈번하게 읽히는 데이터를 DB 대신 빠르게 저장/조회하고 싶다 → **인메모리 데이터 저장소** |",
    "| [**메일 발송**](/post/springboot-mail) | 회원가입 인증, 비밀번호 초기화 메일을 보내야 한다 → **JavaMailSender로 SMTP 이메일 발송** |",
    "",
    "---",
    "",
    "## 9. 테스트 - \"내 코드가 제대로 동작하는지 어떻게 검증하지?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**테스트 전략**](/post/springboot-test) | 어디까지 테스트해야 하는지 모르겠다 → **단위/슬라이스/통합 테스트 전략과 Given-When-Then 패턴** |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"단위 테스트<br>JUnit + Mockito\"] --> B[\"슬라이스 테스트<br>@WebMvcTest, @DataJpaTest\"]",
    "    B --> C[\"통합 테스트<br>@SpringBootTest\"]",
    "    style A fill:#4CAF50,color:#fff",
    "```",
    "",
    "| 테스트 종류 | 무엇을 검증? | 속도 |",
    "|-----------|-------------|------|",
    "| 단위 테스트 | Service 메서드 하나가 정상 동작하는가? | 매우 빠름 |",
    "| 슬라이스 테스트 | Controller의 URL 매핑, Repository 쿼리가 맞는가? | 빠름 |",
    "| 통합 테스트 | 요청 → 응답 전체 흐름이 정상인가? | 느림 |",
    "",
    "---",
    "",
    "## 10. 운영/배포 - \"서비스를 안정적으로 운영하려면?\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**로깅**](/post/springboot-logging) | 에러가 발생했는데 원인을 모르겠다 → **SLF4J + Logback으로 체계적 로그 관리** |",
    "| [**Swagger/OpenAPI**](/post/springboot-swagger) | API 문서를 수동으로 관리하기 힘들다 → **코드에서 API 문서 자동 생성** |",
    "| [**Actuator**](/post/springboot-actuator) | 서버 상태(헬스, 메모리, DB 연결)를 확인하고 싶다 → **모니터링 엔드포인트 제공** |",
    "| [**모니터링 (Prometheus + Grafana)**](/post/springboot-monitoring) | 메트릭을 시각화하고 이상 시 알림을 받고 싶다 → **대시보드와 알림 파이프라인** |",
    "| [**Docker**](/post/springboot-docker) | \"내 PC에서는 되는데...\" 환경 차이 문제를 없애고 싶다 → **컨테이너로 동일 환경 보장** |",
    "| [**CI/CD**](/post/springboot-cicd) | 배포를 수동으로 하면 실수가 생긴다 → **GitHub Actions로 자동 빌드/배포** |",
    "| [**Spring Cloud + MSA**](/post/springboot-spring-cloud) | 서비스가 커져서 모놀리식으로 한계가 온다 → **마이크로서비스 아키텍처** |",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"코드 Push\"] --> B[\"GitHub Actions<br>CI/CD\"]",
    "    B --> C[\"Docker 이미지<br>빌드\"]",
    "    C --> D[\"서버 배포\"]",
    "    D --> E[\"Actuator +<br>Prometheus\"]",
    "    E --> F[\"Grafana<br>대시보드\"]",
    "```",
    "",
    "---",
    "",
    "## 11. 고급 기능 - \"실무에서 자주 마주치는 것들\"",
    "",
    "| 기술 | 해결하는 문제 |",
    "|------|-------------|",
    "| [**@Transactional 고급, @Retryable, @Lock, WebClient**](/post/springboot-useful-features) | 트랜잭션 전파 레벨, 재시도, 동시성 제어, 비동기 HTTP 호출이 필요하다 |",
    "",
    "---",
    "",
    "## 전체 흐름 한눈에 보기",
    "",
    "하나의 HTTP 요청이 들어왔을 때, 어떤 기술이 어느 시점에서 동작하는지 보여줍니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    REQ[\"클라이언트 요청\"] --> FIL[\"Filter<br>(인코딩, CORS, 로깅)\"]",
    "    FIL --> SEC[\"Spring Security<br>(인증/인가)\"]",
    "    SEC --> INT[\"Interceptor<br>(로깅, 권한 체크)\"]",
    "    INT --> CON[\"Controller<br>(요청 매핑, Validation)\"]",
    "    CON --> AOP[\"AOP<br>(로깅, 실행 시간 측정)\"]",
    "    AOP --> SVC[\"Service<br>(비즈니스 로직)\"]",
    "    SVC --> TX[\"@Transactional<br>(트랜잭션 관리)\"]",
    "    TX --> CACHE{\"@Cacheable<br>캐시에 있나?\"}",
    "    CACHE -->|HIT| RES1[\"캐시에서 즉시 반환\"]",
    "    CACHE -->|MISS| REPO[\"Repository<br>(JPA/MyBatis/JdbcTemplate)\"]",
    "    REPO --> DB[(\"Database<br>(H2, MySQL, PostgreSQL)\")]",
    "    REPO --> RES2[\"응답 반환\"]",
    "    CON -.->|에러 발생| EXH[\"@RestControllerAdvice<br>전역 예외 처리\"]",
    "    SVC -.->|비동기 작업| ASYNC[\"@Async<br>(메일 발송, 알림)\"]",
    "    SVC -.->|이벤트| EVT[\"@EventListener<br>(포인트 적립 등)\"]",
    "```",
    "",
    "---",
    "",
    "## 학습 순서 추천",
    "",
    "### 일반적인 웹 서비스는 4단계면 충분하다",
    "",
    "회원가입, 로그인, 게시판 CRUD 같은 **일반적인 웹 애플리케이션**은 1~4단계만으로 충분히 동작합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"1단계: 기초<br>프로젝트 시작\"] --> B[\"2단계: 웹 API<br>요청/응답 처리\"]",
    "    B --> C[\"3단계: 데이터<br>DB CRUD\"]",
    "    C --> D[\"4단계: 보안<br>로그인, 권한\"]",
    "    D --> E{{\"여기까지면<br>웹 서비스 완성!\"}}",
    "    E -.->|서비스가 커지면| F[\"5~8단계: 심화\"]",
    "    style A fill:#4CAF50,color:#fff",
    "    style E fill:#FF9800,color:#fff",
    "    style F fill:#9E9E9E,color:#fff",
    "```",
    "",
    "5단계 이후는 서비스가 성장하면서 **필요할 때** 학습하면 됩니다.",
    "",
    "| 상황 | 필요한 기술 |",
    "|------|-----------|",
    "| 코드가 정상 동작하는지 검증하고 싶다 | **테스트** (JUnit, MockMvc) |",
    "| 같은 데이터를 반복 조회해서 느리다 | **캐싱** (Redis, @Cacheable) |",
    "| 이메일 발송이 응답을 지연시킨다 | **비동기** (@Async) |",
    "| 배포를 수동으로 하면 실수가 생긴다 | **CI/CD** (GitHub Actions, Docker) |",
    "| 장애 원인을 추적할 수 없다 | **로깅, 모니터링** (Logback, Prometheus) |",
    "| 서비스가 너무 커져서 한 프로젝트로 한계가 온다 | **MSA, 메시징** (Spring Cloud, Kafka) |",
    "",
    "### 전체 8단계 로드맵",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"1단계: 기초<br>Overview, 어노테이션, 설정\"] --> B[\"2단계: 웹 개발<br>REST API, Filter, 예외 처리\"]",
    "    B --> C[\"3단계: 데이터<br>JPA, H2, DTO 패턴\"]",
    "    C --> D[\"4단계: 보안<br>Security, JWT, OAuth2\"]",
    "    D --> E[\"5단계: 테스트<br>JUnit, MockMvc, 통합 테스트\"]",
    "    E --> F[\"6단계: 성능<br>캐싱, 비동기, AOP\"]",
    "    F --> G[\"7단계: 운영<br>로깅, Docker, CI/CD, 모니터링\"]",
    "    G --> H[\"8단계: 확장<br>메시징, MSA, WebFlux\"]",
    "    style A fill:#4CAF50,color:#fff",
    "    style D fill:#FF9800,color:#fff",
    "    style H fill:#2196F3,color:#fff",
    "```",
    "",
    "| 단계 | 주제 | 핵심 기술 | 필요 시점 |",
    "|------|------|----------|----------|",
    "| **1단계** | 기초 | Spring Boot 개요, 어노테이션, application.yml, 빌드 시스템 | **필수** |",
    "| **2단계** | 웹 개발 | REST API, 요청/응답, Filter, Interceptor, 예외 처리, Validation | **필수** |",
    "| **3단계** | 데이터 | H2, JPA/Hibernate, JPA 심화, DTO 패턴, JdbcTemplate, MyBatis | **필수** |",
    "| **4단계** | 보안 | Security(세션), JWT, 필터 체인, OAuth2 | **필수** |",
    "| **5단계** | 테스트 | JUnit 5, Mockito, MockMvc, @DataJpaTest, 통합 테스트 | 코드 품질 보장 시 |",
    "| **6단계** | 성능 | 캐싱(Redis), 비동기(@Async), AOP, 프록시 | 성능 이슈 발생 시 |",
    "| **7단계** | 운영 | 로깅, Swagger, Actuator, Docker, CI/CD, Prometheus+Grafana | 실서비스 배포 시 |",
    "| **8단계** | 확장 | 이벤트, 메시징(Kafka, RabbitMQ), Spring Cloud, WebFlux, Batch | 대규모 서비스 시 |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 분류 | 핵심 질문 | 대표 기술 |",
    "|------|----------|----------|",
    "| **기초** | 프로젝트를 어떻게 시작하지? | Spring Boot, Gradle, application.yml |",
    "| **웹 API** | 요청을 어떻게 받고 응답하지? | REST API, Filter, Interceptor, 예외 처리 |",
    "| **데이터** | DB와 어떻게 통신하지? | JPA, MyBatis, JdbcTemplate, H2 |",
    "| **보안** | 인증/인가를 어떻게 구현하지? | Security, JWT, OAuth2 |",
    "| **횡단 관심사** | 공통 로직을 어떻게 분리하지? | AOP, 프록시 |",
    "| **성능** | 느린 응답을 어떻게 빠르게 하지? | 캐싱, @Async, Batch, WebFlux |",
    "| **이벤트/메시징** | 서비스 간 결합도를 어떻게 낮추지? | Event, RabbitMQ, Kafka |",
    "| **외부 연동** | 다른 서비스와 어떻게 통신하지? | WebSocket, GraphQL, gRPC, Redis, Slack |",
    "| **테스트** | 코드가 제대로 동작하는지 어떻게 검증하지? | JUnit 5, Mockito, MockMvc |",
    "| **운영** | 서비스를 안정적으로 운영하려면? | 로깅, Docker, CI/CD, Prometheus |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
