<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-file-handling",
  title: "스프링부트 파일 처리 완전 정리 - 업로드, 다운로드, 저장 전략까지",
  date: "2026-03-01",
  summary: "Spring Boot에서 파일을 다루는 모든 것을 정리합니다. MultipartFile 업로드, 다중 파일, 파일 다운로드, 이미지 미리보기, 파일 검증, 저장 전략(로컬/UUID), REST API 파일 처리까지 실전 예제로 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","file","upload","download","multipartfile","java","backend"],
  content: [
    "## 파일 처리 개요",
    "",
    "웹 애플리케이션에서 파일 처리는 **프로필 이미지 업로드**, **문서 첨부**, **엑셀 내보내기** 등 다양한 곳에서 필요합니다. Spring Boot는 `MultipartFile` 인터페이스를 통해 파일 업로드를 쉽게 처리할 수 있습니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"클라이언트\"] -->|\"multipart/form-data\"| B[\"Controller<br/>MultipartFile\"]",
    "    B --> C[\"Service<br/>파일 검증 + 저장\"]",
    "    C --> D[\"저장소<br/>로컬/S3/DB\"]",
    "    D --> E[\"파일 경로/URL 반환\"]",
    "```",
    "",
    "---",
    "",
    "## 프로젝트 설정",
    "",
    "### 의존성 (build.gradle)",
    "",
    "```groovy",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-validation'",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "}",
    "```",
    "",
    "> 파일 업로드는 별도의 라이브러리 없이 `spring-boot-starter-web`만으로 가능합니다.",
    "",
    "### application.yml",
    "",
    "```yaml",
    "spring:",
    "  servlet:",
    "    multipart:",
    "      enabled: true",
    "      max-file-size: 10MB        # 단일 파일 최대 크기",
    "      max-request-size: 50MB     # 전체 요청 최대 크기",
    "      file-size-threshold: 2KB   # 이 크기 이상이면 디스크에 임시 저장",
    "",
    "file:",
    "  upload-dir: ./uploads         # 파일 저장 경로",
    "  allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xlsx",
    "  max-file-size: 10485760       # 10MB (바이트 단위, 코드에서 사용)",
    "```",
    "",
    "### 설정 상세 설명",
    "",
    "| 설정 | 기본값 | 설명 |",
    "|------|--------|------|",
    "| `max-file-size` | 1MB | 단일 파일 최대 크기 |",
    "| `max-request-size` | 10MB | 멀티파트 요청 전체 최대 크기 |",
    "| `file-size-threshold` | 0B | 이 크기 이상이면 메모리 대신 디스크에 임시 저장 |",
    "| `location` | (시스템 임시폴더) | 임시 파일 저장 위치 |",
    "| `enabled` | true | 멀티파트 업로드 활성화 |",
    "",
    "### 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── config/",
    "│   ├── FileConfig.java            // 파일 설정 + 정적 자원 매핑",
    "│   └── FileProperties.java        // 파일 설정 값 바인딩",
    "├── service/",
    "│   └── FileService.java           // 파일 저장/조회/삭제 로직",
    "├── controller/",
    "│   └── FileController.java        // 파일 업로드/다운로드 API",
    "├── dto/",
    "│   └── FileResponse.java          // 파일 응답 DTO",
    "├── exception/",
    "│   ├── FileException.java         // 파일 관련 예외",
    "│   └── GlobalExceptionHandler.java",
    "└── DemoApplication.java",
    "",
    "uploads/                            // 업로드된 파일 저장 폴더",
    "```",
    "",
    "---",
    "",
    "## 1단계: 설정 클래스",
    "",
    "### FileProperties (설정 값 바인딩)",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "import org.springframework.boot.context.properties.ConfigurationProperties;",
    "import org.springframework.stereotype.Component;",
    "",
    "import java.util.List;",
    "",
    "@Getter @Setter",
    "@Component",
    "@ConfigurationProperties(prefix = \"file\")",
    "public class FileProperties {",
    "",
    "    private String uploadDir = \"./uploads\";",
    "    private List<String> allowedExtensions = List.of(",
    "            \"jpg\", \"jpeg\", \"png\", \"gif\", \"pdf\", \"doc\", \"docx\", \"xlsx\"",
    "    );",
    "    private long maxFileSize = 10 * 1024 * 1024; // 10MB",
    "}",
    "```",
    "",
    "### FileConfig (정적 자원 매핑)",
    "",
    "업로드된 파일을 **URL로 접근**할 수 있게 정적 자원 핸들러를 등록합니다.",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.context.annotation.Configuration;",
    "import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;",
    "import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;",
    "",
    "import java.nio.file.Path;",
    "import java.nio.file.Paths;",
    "",
    "@Configuration",
    "@RequiredArgsConstructor",
    "public class FileConfig implements WebMvcConfigurer {",
    "",
    "    private final FileProperties fileProperties;",
    "",
    "    @Override",
    "    public void addResourceHandlers(ResourceHandlerRegistry registry) {",
    "        Path uploadPath = Paths.get(fileProperties.getUploadDir()).toAbsolutePath();",
    "",
    "        registry.addResourceHandler(\"/files/**\")",
    "                .addResourceLocations(\"file:\" + uploadPath + \"/\");",
    "    }",
    "}",
    "```",
    "",
    "> 이 설정으로 `http://localhost:8080/files/image.jpg`로 업로드된 파일에 접근할 수 있습니다.",
    "",
    "---",
    "",
    "## 2단계: FileService (파일 저장/조회/삭제)",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import com.example.demo.config.FileProperties;",
    "import com.example.demo.dto.FileResponse;",
    "import com.example.demo.exception.FileException;",
    "import jakarta.annotation.PostConstruct;",
    "import lombok.RequiredArgsConstructor;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.core.io.Resource;",
    "import org.springframework.core.io.UrlResource;",
    "import org.springframework.stereotype.Service;",
    "import org.springframework.util.StringUtils;",
    "import org.springframework.web.multipart.MultipartFile;",
    "",
    "import java.io.IOException;",
    "import java.net.MalformedURLException;",
    "import java.nio.file.*;",
    "import java.util.List;",
    "import java.util.UUID;",
    "",
    "@Slf4j",
    "@Service",
    "@RequiredArgsConstructor",
    "public class FileService {",
    "",
    "    private final FileProperties fileProperties;",
    "    private Path uploadPath;",
    "",
    "    @PostConstruct",
    "    public void init() {",
    "        uploadPath = Paths.get(fileProperties.getUploadDir()).toAbsolutePath().normalize();",
    "        try {",
    "            Files.createDirectories(uploadPath);",
    "            log.info(\"파일 업로드 디렉토리 생성: {}\", uploadPath);",
    "        } catch (IOException e) {",
    "            throw new FileException(\"업로드 디렉토리를 생성할 수 없습니다\", e);",
    "        }",
    "    }",
    "",
    "    /**",
    "     * 단일 파일 업로드",
    "     */",
    "    public FileResponse upload(MultipartFile file) {",
    "        validate(file);",
    "",
    "        String originalName = StringUtils.cleanPath(file.getOriginalFilename());",
    "        String extension = getExtension(originalName);",
    "        String storedName = UUID.randomUUID() + \".\" + extension;",
    "",
    "        try {",
    "            Path targetPath = uploadPath.resolve(storedName);",
    "            file.transferTo(targetPath);",
    "            log.info(\"파일 업로드 성공: {} → {}\", originalName, storedName);",
    "",
    "            return FileResponse.builder()",
    "                    .originalName(originalName)",
    "                    .storedName(storedName)",
    "                    .size(file.getSize())",
    "                    .contentType(file.getContentType())",
    "                    .url(\"/files/\" + storedName)",
    "                    .build();",
    "        } catch (IOException e) {",
    "            throw new FileException(\"파일 저장에 실패했습니다: \" + originalName, e);",
    "        }",
    "    }",
    "",
    "    /**",
    "     * 다중 파일 업로드",
    "     */",
    "    public List<FileResponse> uploadMultiple(List<MultipartFile> files) {",
    "        return files.stream()",
    "                .map(this::upload)",
    "                .toList();",
    "    }",
    "",
    "    /**",
    "     * 파일 다운로드용 Resource 조회",
    "     */",
    "    public Resource loadAsResource(String filename) {",
    "        try {",
    "            Path filePath = uploadPath.resolve(filename).normalize();",
    "            Resource resource = new UrlResource(filePath.toUri());",
    "",
    "            if (resource.exists() && resource.isReadable()) {",
    "                return resource;",
    "            }",
    "            throw new FileException(\"파일을 찾을 수 없습니다: \" + filename);",
    "        } catch (MalformedURLException e) {",
    "            throw new FileException(\"잘못된 파일 경로입니다: \" + filename, e);",
    "        }",
    "    }",
    "",
    "    /**",
    "     * 파일 삭제",
    "     */",
    "    public void delete(String filename) {",
    "        try {",
    "            Path filePath = uploadPath.resolve(filename).normalize();",
    "            boolean deleted = Files.deleteIfExists(filePath);",
    "            if (deleted) {",
    "                log.info(\"파일 삭제 완료: {}\", filename);",
    "            } else {",
    "                log.warn(\"삭제할 파일 없음: {}\", filename);",
    "            }",
    "        } catch (IOException e) {",
    "            throw new FileException(\"파일 삭제에 실패했습니다: \" + filename, e);",
    "        }",
    "    }",
    "",
    "    /**",
    "     * 파일 검증 (빈 파일, 크기, 확장자)",
    "     */",
    "    private void validate(MultipartFile file) {",
    "        if (file.isEmpty()) {",
    "            throw new FileException(\"빈 파일은 업로드할 수 없습니다\");",
    "        }",
    "",
    "        if (file.getSize() > fileProperties.getMaxFileSize()) {",
    "            throw new FileException(String.format(",
    "                    \"파일 크기가 최대 허용 크기(%dMB)를 초과했습니다\",",
    "                    fileProperties.getMaxFileSize() / (1024 * 1024)));",
    "        }",
    "",
    "        String extension = getExtension(file.getOriginalFilename());",
    "        if (!fileProperties.getAllowedExtensions().contains(extension.toLowerCase())) {",
    "            throw new FileException(String.format(",
    "                    \"허용되지 않는 파일 확장자입니다: .%s (허용: %s)\",",
    "                    extension, fileProperties.getAllowedExtensions()));",
    "        }",
    "    }",
    "",
    "    private String getExtension(String filename) {",
    "        if (filename == null || !filename.contains(\".\")) {",
    "            throw new FileException(\"파일 확장자를 확인할 수 없습니다\");",
    "        }",
    "        return filename.substring(filename.lastIndexOf(\".\") + 1);",
    "    }",
    "}",
    "```",
    "",
    "### 핵심 메서드 정리",
    "",
    "| 메서드 | 역할 |",
    "|--------|------|",
    "| `upload()` | 단일 파일 검증 + UUID 이름 변환 + 저장 |",
    "| `uploadMultiple()` | 다중 파일 업로드 (stream으로 반복) |",
    "| `loadAsResource()` | 파일을 `Resource`로 로드 (다운로드용) |",
    "| `delete()` | 파일 삭제 |",
    "| `validate()` | 빈 파일, 크기 초과, 확장자 검증 |",
    "",
    "### 왜 UUID로 파일명을 변경하는가?",
    "",
    "| 문제 | 설명 |",
    "|------|------|",
    "| 파일명 충돌 | 여러 사용자가 `image.jpg`를 업로드하면 덮어쓰기 발생 |",
    "| 보안 | 원본 파일명에 `../`같은 경로 조작 문자가 포함될 수 있음 |",
    "| 한글/특수문자 | 파일명에 한글이나 공백이 있으면 URL 인코딩 문제 발생 |",
    "",
    "```",
    "원본: 프로필 사진 (최종).jpg",
    "저장: 550e8400-e29b-41d4-a716-446655440000.jpg",
    "```",
    "",
    "---",
    "",
    "## 3단계: DTO와 예외",
    "",
    "### FileResponse",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import lombok.*;",
    "",
    "@Getter",
    "@Builder",
    "public class FileResponse {",
    "    private String originalName;",
    "    private String storedName;",
    "    private long size;",
    "    private String contentType;",
    "    private String url;",
    "}",
    "```",
    "",
    "### FileException",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "public class FileException extends RuntimeException {",
    "",
    "    public FileException(String message) {",
    "        super(message);",
    "    }",
    "",
    "    public FileException(String message, Throwable cause) {",
    "        super(message, cause);",
    "    }",
    "}",
    "```",
    "",
    "### 예외 처리 (GlobalExceptionHandler)",
    "",
    "```java",
    "@RestControllerAdvice",
    "public class GlobalExceptionHandler {",
    "",
    "    @ExceptionHandler(FileException.class)",
    "    public ResponseEntity<Map<String, String>> handleFileException(",
    "            FileException e) {",
    "        return ResponseEntity.badRequest()",
    "                .body(Map.of(",
    "                        \"code\", \"FILE_ERROR\",",
    "                        \"message\", e.getMessage()));",
    "    }",
    "",
    "    @ExceptionHandler(MaxUploadSizeExceededException.class)",
    "    public ResponseEntity<Map<String, String>> handleMaxSizeException(",
    "            MaxUploadSizeExceededException e) {",
    "        return ResponseEntity.status(HttpStatus.PAYLOAD_TOO_LARGE)",
    "                .body(Map.of(",
    "                        \"code\", \"FILE_TOO_LARGE\",",
    "                        \"message\", \"파일 크기가 허용 범위를 초과했습니다\"));",
    "    }",
    "}",
    "```",
    "",
    "> `MaxUploadSizeExceededException`은 `application.yml`의 `max-file-size`를 초과했을 때 Spring이 자동으로 던지는 예외입니다.",
    "",
    "---",
    "",
    "## 4단계: FileController",
    "",
    "### REST API 파일 업로드/다운로드",
    "",
    "```java",
    "package com.example.demo.controller;",
    "",
    "import com.example.demo.dto.FileResponse;",
    "import com.example.demo.service.FileService;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.core.io.Resource;",
    "import org.springframework.http.*;",
    "import org.springframework.web.bind.annotation.*;",
    "import org.springframework.web.multipart.MultipartFile;",
    "",
    "import java.net.URLEncoder;",
    "import java.nio.charset.StandardCharsets;",
    "import java.util.List;",
    "import java.util.Map;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/files\")",
    "@RequiredArgsConstructor",
    "public class FileController {",
    "",
    "    private final FileService fileService;",
    "",
    "    /**",
    "     * 단일 파일 업로드",
    "     */",
    "    @PostMapping(\"/upload\")",
    "    public ResponseEntity<FileResponse> upload(",
    "            @RequestParam(\"file\") MultipartFile file) {",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(fileService.upload(file));",
    "    }",
    "",
    "    /**",
    "     * 다중 파일 업로드",
    "     */",
    "    @PostMapping(\"/upload/multiple\")",
    "    public ResponseEntity<List<FileResponse>> uploadMultiple(",
    "            @RequestParam(\"files\") List<MultipartFile> files) {",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(fileService.uploadMultiple(files));",
    "    }",
    "",
    "    /**",
    "     * 파일과 데이터를 함께 업로드",
    "     */",
    "    @PostMapping(\"/upload/with-data\")",
    "    public ResponseEntity<Map<String, Object>> uploadWithData(",
    "            @RequestParam(\"file\") MultipartFile file,",
    "            @RequestParam(\"title\") String title,",
    "            @RequestParam(\"description\") String description) {",
    "",
    "        FileResponse fileResponse = fileService.upload(file);",
    "",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(Map.of(",
    "                        \"title\", title,",
    "                        \"description\", description,",
    "                        \"file\", fileResponse));",
    "    }",
    "",
    "    /**",
    "     * 파일 다운로드",
    "     */",
    "    @GetMapping(\"/download/{filename}\")",
    "    public ResponseEntity<Resource> download(",
    "            @PathVariable String filename) {",
    "",
    "        Resource resource = fileService.loadAsResource(filename);",
    "",
    "        String encodedName = URLEncoder.encode(",
    "                resource.getFilename(), StandardCharsets.UTF_8)",
    "                .replace(\"+\", \"%20\");",
    "",
    "        return ResponseEntity.ok()",
    "                .contentType(MediaType.APPLICATION_OCTET_STREAM)",
    "                .header(HttpHeaders.CONTENT_DISPOSITION,",
    "                        \"attachment; filename*=UTF-8''\" + encodedName)",
    "                .body(resource);",
    "    }",
    "",
    "    /**",
    "     * 파일 삭제",
    "     */",
    "    @DeleteMapping(\"/{filename}\")",
    "    public ResponseEntity<Map<String, String>> delete(",
    "            @PathVariable String filename) {",
    "        fileService.delete(filename);",
    "        return ResponseEntity.ok(Map.of(\"message\", \"파일이 삭제되었습니다\"));",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## API 요청·응답 예시",
    "",
    "### 단일 파일 업로드",
    "",
    "```",
    "POST /api/files/upload",
    "Content-Type: multipart/form-data",
    "",
    "file: (바이너리 파일 데이터)",
    "```",
    "",
    "**응답 (201 Created):**",
    "",
    "```json",
    "{",
    "  \"originalName\": \"프로필사진.jpg\",",
    "  \"storedName\": \"550e8400-e29b-41d4-a716-446655440000.jpg\",",
    "  \"size\": 245760,",
    "  \"contentType\": \"image/jpeg\",",
    "  \"url\": \"/files/550e8400-e29b-41d4-a716-446655440000.jpg\"",
    "}",
    "```",
    "",
    "### 다중 파일 업로드",
    "",
    "```",
    "POST /api/files/upload/multiple",
    "Content-Type: multipart/form-data",
    "",
    "files: (파일1)",
    "files: (파일2)",
    "files: (파일3)",
    "```",
    "",
    "**응답 (201 Created):**",
    "",
    "```json",
    "[",
    "  {",
    "    \"originalName\": \"photo1.jpg\",",
    "    \"storedName\": \"a1b2c3d4-...-001.jpg\",",
    "    \"size\": 245760,",
    "    \"contentType\": \"image/jpeg\",",
    "    \"url\": \"/files/a1b2c3d4-...-001.jpg\"",
    "  },",
    "  {",
    "    \"originalName\": \"document.pdf\",",
    "    \"storedName\": \"e5f6g7h8-...-002.pdf\",",
    "    \"size\": 1048576,",
    "    \"contentType\": \"application/pdf\",",
    "    \"url\": \"/files/e5f6g7h8-...-002.pdf\"",
    "  }",
    "]",
    "```",
    "",
    "### 파일 + 데이터 함께 업로드",
    "",
    "```",
    "POST /api/files/upload/with-data",
    "Content-Type: multipart/form-data",
    "",
    "file: (바이너리 파일 데이터)",
    "title: 제품 이미지",
    "description: 메인 배너용 이미지입니다",
    "```",
    "",
    "**응답 (201 Created):**",
    "",
    "```json",
    "{",
    "  \"title\": \"제품 이미지\",",
    "  \"description\": \"메인 배너용 이미지입니다\",",
    "  \"file\": {",
    "    \"originalName\": \"banner.png\",",
    "    \"storedName\": \"i9j0k1l2-...-003.png\",",
    "    \"size\": 512000,",
    "    \"contentType\": \"image/png\",",
    "    \"url\": \"/files/i9j0k1l2-...-003.png\"",
    "  }",
    "}",
    "```",
    "",
    "### 파일 다운로드",
    "",
    "```",
    "GET /api/files/download/550e8400-e29b-41d4-a716-446655440000.jpg",
    "```",
    "",
    "**응답:** 파일 바이너리 (브라우저에서 다운로드 대화상자 표시)",
    "",
    "### 에러 응답 예시",
    "",
    "```json",
    "{",
    "  \"code\": \"FILE_ERROR\",",
    "  \"message\": \"허용되지 않는 파일 확장자입니다: .exe (허용: [jpg, jpeg, png, gif, pdf, doc, docx, xlsx])\"",
    "}",
    "```",
    "",
    "---",
    "",
    "## MultipartFile 핵심 메서드",
    "",
    "| 메서드 | 반환 타입 | 설명 |",
    "|--------|----------|------|",
    "| `getOriginalFilename()` | `String` | 원본 파일명 (`photo.jpg`) |",
    "| `getContentType()` | `String` | MIME 타입 (`image/jpeg`) |",
    "| `getSize()` | `long` | 파일 크기 (바이트) |",
    "| `isEmpty()` | `boolean` | 빈 파일 여부 |",
    "| `getBytes()` | `byte[]` | 파일 내용을 바이트 배열로 |",
    "| `getInputStream()` | `InputStream` | 파일 입력 스트림 |",
    "| `transferTo(Path)` | `void` | 지정 경로에 파일 저장 |",
    "",
    "### 파일 저장 방법 비교",
    "",
    "```java",
    "// 방법 1: transferTo (권장 - 가장 간결하고 효율적)",
    "file.transferTo(targetPath);",
    "",
    "// 방법 2: Files.copy (InputStream 사용)",
    "try (InputStream inputStream = file.getInputStream()) {",
    "    Files.copy(inputStream, targetPath, StandardCopyOption.REPLACE_EXISTING);",
    "}",
    "",
    "// 방법 3: 바이트 배열 (소규모 파일만)",
    "byte[] bytes = file.getBytes();",
    "Files.write(targetPath, bytes);",
    "```",
    "",
    "---",
    "",
    "## Thymeleaf 파일 업로드 폼",
    "",
    "REST API 대신 서버 렌더링 방식으로 파일을 업로드하는 예제입니다.",
    "",
    "### Controller",
    "",
    "```java",
    "@Controller",
    "@RequestMapping(\"/upload\")",
    "@RequiredArgsConstructor",
    "public class UploadPageController {",
    "",
    "    private final FileService fileService;",
    "",
    "    @GetMapping",
    "    public String uploadForm() {",
    "        return \"upload\";",
    "    }",
    "",
    "    @PostMapping",
    "    public String handleUpload(",
    "            @RequestParam(\"file\") MultipartFile file,",
    "            RedirectAttributes redirectAttributes) {",
    "",
    "        FileResponse result = fileService.upload(file);",
    "        redirectAttributes.addFlashAttribute(\"message\",",
    "                \"업로드 성공: \" + result.getOriginalName());",
    "        redirectAttributes.addFlashAttribute(\"fileUrl\", result.getUrl());",
    "        return \"redirect:/upload\";",
    "    }",
    "}",
    "```",
    "",
    "### upload.html",
    "",
    "```html",
    "<!DOCTYPE html>",
    "<html xmlns:th=\"http://www.thymeleaf.org\">",
    "<head><title>파일 업로드</title></head>",
    "<body>",
    "    <h1>파일 업로드</h1>",
    "",
    "    <div th:if=\"${message}\" style=\"color: green;\"",
    "         th:text=\"${message}\"></div>",
    "",
    "    <!-- 업로드된 이미지 미리보기 -->",
    "    <div th:if=\"${fileUrl}\">",
    "        <img th:src=\"${fileUrl}\" style=\"max-width: 300px;\">",
    "    </div>",
    "",
    "    <!-- enctype 필수! -->",
    "    <form th:action=\"@{/upload}\" method=\"post\"",
    "          enctype=\"multipart/form-data\">",
    "        <input type=\"file\" name=\"file\" required>",
    "        <button type=\"submit\">업로드</button>",
    "    </form>",
    "",
    "    <!-- 다중 파일 업로드 -->",
    "    <h2>다중 파일 업로드</h2>",
    "    <form th:action=\"@{/upload/multiple}\" method=\"post\"",
    "          enctype=\"multipart/form-data\">",
    "        <input type=\"file\" name=\"files\" multiple>",
    "        <button type=\"submit\">업로드</button>",
    "    </form>",
    "</body>",
    "</html>",
    "```",
    "",
    "> **핵심**: `<form>`에 `enctype=\"multipart/form-data\"`를 반드시 추가해야 합니다. 이것이 없으면 파일이 전송되지 않습니다.",
    "",
    "---",
    "",
    "## 이미지 미리보기 (인라인 표시)",
    "",
    "다운로드가 아니라 **브라우저에서 바로 이미지를 표시**하려면 `Content-Disposition`을 `inline`으로 설정합니다.",
    "",
    "```java",
    "@GetMapping(\"/view/{filename}\")",
    "public ResponseEntity<Resource> viewImage(@PathVariable String filename) {",
    "    Resource resource = fileService.loadAsResource(filename);",
    "",
    "    String contentType = determineContentType(filename);",
    "",
    "    return ResponseEntity.ok()",
    "            .contentType(MediaType.parseMediaType(contentType))",
    "            .header(HttpHeaders.CONTENT_DISPOSITION,",
    "                    \"inline; filename=\\\"\" + filename + \"\\\"\")",
    "            .body(resource);",
    "}",
    "",
    "private String determineContentType(String filename) {",
    "    String ext = filename.substring(filename.lastIndexOf(\".\") + 1).toLowerCase();",
    "    return switch (ext) {",
    "        case \"jpg\", \"jpeg\" -> \"image/jpeg\";",
    "        case \"png\" -> \"image/png\";",
    "        case \"gif\" -> \"image/gif\";",
    "        case \"pdf\" -> \"application/pdf\";",
    "        default -> \"application/octet-stream\";",
    "    };",
    "}",
    "```",
    "",
    "### Content-Disposition 차이",
    "",
    "| 값 | 동작 | 용도 |",
    "|-----|------|------|",
    "| `attachment` | 다운로드 대화상자 표시 | 파일 다운로드 |",
    "| `inline` | 브라우저에서 바로 표시 | 이미지 미리보기, PDF 뷰어 |",
    "",
    "---",
    "",
    "## 날짜별 하위 폴더 저장",
    "",
    "파일이 많아지면 하나의 폴더에 모든 파일을 넣는 것은 비효율적입니다. **날짜별 하위 폴더**를 만들어 관리할 수 있습니다.",
    "",
    "```java",
    "public FileResponse upload(MultipartFile file) {",
    "    validate(file);",
    "",
    "    String originalName = StringUtils.cleanPath(file.getOriginalFilename());",
    "    String extension = getExtension(originalName);",
    "    String storedName = UUID.randomUUID() + \".\" + extension;",
    "",
    "    // 날짜별 하위 폴더 (예: 2026/03/01)",
    "    String dateFolder = LocalDate.now().format(",
    "            DateTimeFormatter.ofPattern(\"yyyy/MM/dd\"));",
    "    Path datePath = uploadPath.resolve(dateFolder);",
    "",
    "    try {",
    "        Files.createDirectories(datePath);",
    "        Path targetPath = datePath.resolve(storedName);",
    "        file.transferTo(targetPath);",
    "",
    "        return FileResponse.builder()",
    "                .originalName(originalName)",
    "                .storedName(dateFolder + \"/\" + storedName)",
    "                .size(file.getSize())",
    "                .contentType(file.getContentType())",
    "                .url(\"/files/\" + dateFolder + \"/\" + storedName)",
    "                .build();",
    "    } catch (IOException e) {",
    "        throw new FileException(\"파일 저장 실패: \" + originalName, e);",
    "    }",
    "}",
    "```",
    "",
    "```",
    "uploads/",
    "├── 2026/03/01/",
    "│   ├── 550e8400-...-001.jpg",
    "│   └── 662f9500-...-002.pdf",
    "├── 2026/03/02/",
    "│   └── 773g0600-...-003.png",
    "└── ...",
    "```",
    "",
    "---",
    "",
    "## 파일 저장 전략 비교",
    "",
    "| 전략 | 장점 | 단점 | 적합한 경우 |",
    "|------|------|------|-------------|",
    "| **로컬 디스크** | 구현 간단, 비용 없음 | 서버 확장 시 공유 어려움 | 개발/소규모 |",
    "| **NAS/공유 스토리지** | 여러 서버에서 접근 | 네트워크 속도 의존 | 중규모 |",
    "| **AWS S3** | 무제한 용량, CDN 연동, 고가용성 | 비용, 외부 의존성 | **실무 권장** |",
    "| **DB (BLOB)** | 트랜잭션과 함께 관리 | 성능 저하, DB 용량 증가 | 소규모 문서 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A{\"파일 저장 전략 선택\"} --> B[\"개발/학습\"]",
    "    A --> C[\"운영 소규모\"]",
    "    A --> D[\"운영 대규모\"]",
    "    B --> E[\"로컬 디스크\"]",
    "    C --> F[\"로컬 디스크 + 백업\"]",
    "    D --> G[\"AWS S3 + CloudFront(CDN)\"]",
    "```",
    "",
    "---",
    "",
    "## Postman으로 테스트하기",
    "",
    "### 단일 파일 업로드",
    "",
    "1. **Method**: `POST`",
    "2. **URL**: `http://localhost:8080/api/files/upload`",
    "3. **Body** 탭 → `form-data` 선택",
    "4. KEY에 `file` 입력, 타입을 **File**로 변경",
    "5. VALUE에서 파일 선택",
    "6. **Send**",
    "",
    "### 다중 파일 업로드",
    "",
    "1. **Body** 탭 → `form-data`",
    "2. KEY에 `files`, 타입 **File** → 파일 선택",
    "3. 같은 KEY `files`로 행 추가 → 다른 파일 선택",
    "4. **Send**",
    "",
    "### 파일 + 데이터 함께 업로드",
    "",
    "1. **Body** 탭 → `form-data`",
    "2. `file` (File 타입) → 파일 선택",
    "3. `title` (Text 타입) → `제품 이미지`",
    "4. `description` (Text 타입) → `메인 배너용`",
    "5. **Send**",
    "",
    "> **주의**: Postman에서 파일 업로드 시 Content-Type을 수동으로 설정하지 마세요. Postman이 `multipart/form-data`와 boundary를 자동으로 설정합니다.",
    "",
    "---",
    "",
    "## 전체 흐름 정리",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant CT as FileController",
    "    participant SV as FileService",
    "    participant FS as 파일 시스템",
    "",
    "    Note over C,FS: 업로드",
    "    C->>CT: POST /api/files/upload<br/>(multipart/form-data)",
    "    CT->>SV: upload(MultipartFile)",
    "    SV->>SV: validate() - 빈 파일/크기/확장자",
    "    SV->>SV: UUID 파일명 생성",
    "    SV->>FS: file.transferTo(path)",
    "    SV-->>CT: FileResponse",
    "    CT-->>C: 201 Created + FileResponse",
    "",
    "    Note over C,FS: 다운로드",
    "    C->>CT: GET /api/files/download/{filename}",
    "    CT->>SV: loadAsResource(filename)",
    "    SV->>FS: UrlResource(filePath)",
    "    SV-->>CT: Resource",
    "    CT-->>C: 200 OK + 파일 바이너리<br/>(Content-Disposition: attachment)",
    "",
    "    Note over C,FS: 정적 자원 접근",
    "    C->>FS: GET /files/{storedName}",
    "    FS-->>C: 파일 직접 반환 (이미지 표시 등)",
    "```",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "### 1. 경로 조작 공격 (Path Traversal) 방지",
    "",
    "```java",
    "// X: 사용자 입력을 그대로 경로에 사용",
    "Path path = uploadPath.resolve(userInput);  // userInput = \"../../etc/passwd\"",
    "",
    "// O: 정규화 후 업로드 경로 내인지 확인",
    "Path path = uploadPath.resolve(userInput).normalize();",
    "if (!path.startsWith(uploadPath)) {",
    "    throw new FileException(\"잘못된 파일 경로입니다\");",
    "}",
    "```",
    "",
    "### 2. MIME 타입 확장자 위조 주의",
    "",
    "```java",
    "// 확장자만 체크하면 위조 가능 (evil.exe → evil.jpg로 변경)",
    "// Content-Type도 함께 검증",
    "private void validate(MultipartFile file) {",
    "    String contentType = file.getContentType();",
    "    if (contentType != null && !contentType.startsWith(\"image/\")) {",
    "        throw new FileException(\"이미지 파일만 업로드 가능합니다\");",
    "    }",
    "}",
    "```",
    "",
    "### 3. 업로드 폴더는 웹 루트 밖에 위치",
    "",
    "```yaml",
    "# O: 프로젝트 외부 경로",
    "file:",
    "  upload-dir: /var/uploads",
    "",
    "# X: src/main/resources/static/ 내부 (빌드 시 삭제됨)",
    "```",
    "",
    "### 4. 대용량 파일은 스트리밍 처리",
    "",
    "```java",
    "// 작은 파일: getBytes() 가능",
    "byte[] bytes = file.getBytes();",
    "",
    "// 대용량 파일: 반드시 InputStream 또는 transferTo 사용",
    "file.transferTo(targetPath);  // 메모리에 전체를 올리지 않음",
    "```",
    "",
    "### 5. .gitignore에 업로드 폴더 추가",
    "",
    "```",
    "# .gitignore",
    "uploads/",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 구성 요소 | 역할 | 핵심 코드 |",
    "|-----------|------|-----------|",
    "| `application.yml` | 파일 크기 제한 설정 | `max-file-size: 10MB` |",
    "| `FileProperties` | 설정 값 바인딩 | `@ConfigurationProperties` |",
    "| `FileConfig` | 정적 자원 매핑 | `addResourceHandler(\"/files/**\")` |",
    "| `FileService` | 파일 저장/조회/삭제/검증 | `file.transferTo()`, `UrlResource` |",
    "| `FileController` | 업로드/다운로드 API | `@RequestParam MultipartFile` |",
    "| `FileException` | 파일 관련 예외 | `extends RuntimeException` |",
    "",
    "| 상황 | 처리 |",
    "|------|------|",
    "| 단일 파일 업로드 | `@RequestParam(\"file\") MultipartFile file` |",
    "| 다중 파일 업로드 | `@RequestParam(\"files\") List<MultipartFile> files` |",
    "| 파일 + 데이터 | `@RequestParam`으로 파일과 텍스트를 함께 수신 |",
    "| 파일 다운로드 | `Resource` + `Content-Disposition: attachment` |",
    "| 이미지 미리보기 | `Resource` + `Content-Disposition: inline` |",
    "| 파일명 충돌 방지 | UUID로 저장명 변경 |",
    "| 파일 검증 | 빈 파일, 크기, 확장자, MIME 타입 |",
    "| 날짜별 정리 | `yyyy/MM/dd` 하위 폴더 |",
    "| 운영 환경 | AWS S3 + CloudFront CDN 권장 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
