<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-aop",
  title: "Spring Boot AOP(관점 지향 프로그래밍) 완전 정리 - 개념부터 실전 예제까지",
  date: "2026-03-06",
  summary: "AOP의 개념, 핵심 용어(Aspect, Advice, Pointcut, JoinPoint), Spring AOP 동작 원리(프록시), 그리고 실행 시간 측정·로깅·권한 체크·커스텀 어노테이션 등 실전 예제를 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","aop","aspect","proxy","java","backend"],
  content: [
    "## AOP란?",
    "",
    "**AOP(Aspect-Oriented Programming, 관점 지향 프로그래밍)**는 여러 클래스에 걸쳐 반복되는 **공통 관심사(Cross-Cutting Concern)**를 비즈니스 로직에서 분리하여 모듈화하는 프로그래밍 기법입니다.",
    "",
    "### 왜 필요한가?",
    "",
    "아래처럼 모든 서비스 메서드에 로깅·시간 측정·트랜잭션 코드가 반복된다고 가정합니다.",
    "",
    "```java",
    "public class OrderService {",
    "    public void createOrder(OrderRequest req) {",
    "        long start = System.currentTimeMillis();     // 시간 측정",
    "        log.info(\"createOrder 시작\");                  // 로깅",
    "        // --- 핵심 비즈니스 로직 ---",
    "        Order order = new Order(req);",
    "        orderRepository.save(order);",
    "        // --- 핵심 비즈니스 로직 끝 ---",
    "        log.info(\"createOrder 끝\");                    // 로깅",
    "        long end = System.currentTimeMillis();",
    "        log.info(\"실행 시간: {}ms\", end - start);       // 시간 측정",
    "    }",
    "}",
    "```",
    "",
    "이런 **부가 기능**이 10개, 100개 메서드마다 반복되면 유지보수가 어렵습니다. AOP를 사용하면 이 부가 기능을 **한 곳에 모아서** 관리할 수 있습니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph \"AOP 없이\"",
    "        A1[\"OrderService<br/>로깅 + 시간측정 + 비즈니스\"]",
    "        A2[\"UserService<br/>로깅 + 시간측정 + 비즈니스\"]",
    "        A3[\"PaymentService<br/>로깅 + 시간측정 + 비즈니스\"]",
    "    end",
    "    subgraph \"AOP 적용\"",
    "        B0[\"LoggingAspect<br/>로깅 + 시간측정\"]",
    "        B1[\"OrderService<br/>비즈니스만\"]",
    "        B2[\"UserService<br/>비즈니스만\"]",
    "        B3[\"PaymentService<br/>비즈니스만\"]",
    "        B0 -.-> B1",
    "        B0 -.-> B2",
    "        B0 -.-> B3",
    "    end",
    "```",
    "",
    "---",
    "",
    "## 핵심 용어",
    "",
    "| 용어 | 영문 | 설명 | 비유 |",
    "|------|------|------|------|",
    "| **관점(Aspect)** | Aspect | 공통 관심사를 모듈화한 클래스 | \"감시 카메라\" 자체 |",
    "| **조인 포인트(JoinPoint)** | JoinPoint | Aspect가 적용될 수 있는 지점 (Spring에서는 메서드 실행) | \"카메라가 설치될 수 있는 위치\" |",
    "| **어드바이스(Advice)** | Advice | 실제로 실행되는 부가 로직 (언제 실행할지 포함) | \"카메라가 녹화하는 행위\" |",
    "| **포인트컷(Pointcut)** | Pointcut | 어드바이스를 적용할 대상을 선별하는 조건식 | \"어디에 카메라를 설치할지 규칙\" |",
    "| **위빙(Weaving)** | Weaving | Aspect를 대상 객체에 연결하는 과정 | \"카메라를 실제로 설치하는 작업\" |",
    "| **타깃(Target)** | Target | Aspect가 적용되는 대상 객체 | \"감시 대상 건물\" |",
    "",
    "### Advice 종류",
    "",
    "| 어노테이션 | 실행 시점 | 용도 |",
    "|------------|-----------|------|",
    "| `@Before` | 메서드 실행 **전** | 권한 체크, 파라미터 로깅 |",
    "| `@AfterReturning` | 메서드 **정상** 실행 후 | 결과 로깅, 후처리 |",
    "| `@AfterThrowing` | 메서드에서 **예외** 발생 시 | 에러 로깅, 알림 |",
    "| `@After` | 메서드 실행 후 (성공/실패 무관, finally) | 리소스 정리 |",
    "| `@Around` | 메서드 실행 **전후** 모두 | 시간 측정, 트랜잭션, 캐싱 |",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 호출자",
    "    participant P as Proxy (AOP)",
    "    participant T as Target 메서드",
    "    C->>P: 메서드 호출",
    "    Note over P: @Before 실행",
    "    P->>T: proceed() - 실제 메서드 실행",
    "    alt 정상 실행",
    "        T-->>P: 결과 반환",
    "        Note over P: @AfterReturning 실행",
    "    else 예외 발생",
    "        T-->>P: 예외 던짐",
    "        Note over P: @AfterThrowing 실행",
    "    end",
    "    Note over P: @After 실행 (finally)",
    "    P-->>C: 결과/예외 전달",
    "```",
    "",
    "---",
    "",
    "## 인텔리제이에서 프로젝트 만들기",
    "",
    "### 1단계: 새 프로젝트 생성",
    "",
    "1. IntelliJ IDEA 실행 → **File → New → Project**",
    "2. 왼쪽 목록에서 **Spring Initializr** 선택",
    "3. 아래와 같이 설정:",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | springboot_aop_example |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **Group** | com.example |",
    "| **Artifact** | demo |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "4. **Next** 클릭",
    "",
    "### 2단계: 의존성 선택",
    "",
    "| 카테고리 | 선택할 의존성 |",
    "|----------|-------------|",
    "| **Developer Tools** | Lombok |",
    "| **Web** | Spring Web |",
    "",
    "> `spring-boot-starter-aop`는 build.gradle에서 직접 추가합니다.",
    "",
    "5. **Create** 클릭 → 프로젝트 생성 완료",
    "",
    "### 3단계: build.gradle 설정",
    "",
    "생성된 `build.gradle`을 아래 내용으로 교체합니다.",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '1.0-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-aop'",
    "",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "test {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "| 의존성 | 역할 |",
    "|--------|------|",
    "| `spring-boot-starter-web` | REST API 개발 (Controller, JSON 응답) |",
    "| `spring-boot-starter-aop` | **Spring AOP + AspectJ** 라이브러리 (별도의 `@EnableAspectJAutoProxy` 없이 자동 활성화) |",
    "| `lombok` | `@Slf4j`, `@RequiredArgsConstructor` 등 보일러플레이트 제거 |",
    "",
    "> build.gradle을 수정한 후 IntelliJ 우측 상단에 뜨는 🐘 **코끼리 아이콘(Reload)** 을 클릭하거나, **Ctrl + Shift + O** 로 Gradle을 동기화하세요.",
    "",
    "### 프로젝트 구조",
    "",
    "아래 구조대로 패키지와 파일을 만들면 됩니다.",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── DemoApplication.java",
    "├── controller/",
    "│   └── OrderController.java",
    "├── service/",
    "│   └── OrderService.java",
    "├── dto/",
    "│   ├── OrderRequest.java",
    "│   └── ApiResponse.java",
    "└── aop/",
    "    ├── ExecutionTimeAspect.java       ← @Around: 실행 시간 측정",
    "    ├── LoggingAspect.java             ← @Before/@AfterReturning/@AfterThrowing: 로깅",
    "    ├── ExceptionAlertAspect.java      ← @AfterThrowing: 예외 알림",
    "    └── annotation/",
    "        └── TimeTrace.java             ← 커스텀 어노테이션",
    "```",
    "",
    "---",
    "",
    "## 실습 코드 (복사해서 바로 실행)",
    "",
    "아래 코드를 위 프로젝트 구조에 맞게 파일을 만들고 복사-붙여넣기 하세요.",
    "",
    "### DemoApplication.java (메인 클래스)",
    "",
    "```java",
    "package com.example.demo;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "### OrderRequest.java (DTO)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import lombok.Getter;",
    "import lombok.Setter;",
    "",
    "@Getter",
    "@Setter",
    "public class OrderRequest {",
    "    private String itemName;",
    "    private int quantity;",
    "    private int price;",
    "}",
    "```",
    "",
    "### ApiResponse.java (공통 응답 DTO)",
    "",
    "```java",
    "package com.example.demo.dto;",
    "",
    "import lombok.AllArgsConstructor;",
    "import lombok.Getter;",
    "",
    "@Getter",
    "@AllArgsConstructor",
    "public class ApiResponse<T> {",
    "    private boolean success;",
    "    private T data;",
    "    private String message;",
    "",
    "    public static <T> ApiResponse<T> ok(T data) {",
    "        return new ApiResponse<>(true, data, null);",
    "    }",
    "",
    "    public static <T> ApiResponse<T> error(String message) {",
    "        return new ApiResponse<>(false, null, message);",
    "    }",
    "}",
    "```",
    "",
    "### OrderService.java",
    "",
    "#### AtomicLong이란?",
    "",
    "`AtomicLong`은 **여러 스레드가 동시에 접근해도 안전한 long 값**입니다. 일반 `long`은 여러 스레드가 동시에 `++` 연산을 하면 값이 꼬일 수 있지만, `AtomicLong`은 내부적으로 **원자적(atomic) 연산**을 보장합니다.",
    "",
    "| 항목 | `long` | `AtomicLong` |",
    "|------|--------|-------------|",
    "| 스레드 안전 | X | **O** |",
    "| 사용 예 | 단일 스레드 카운터 | 멀티스레드 ID 생성기, 카운터 |",
    "| 주요 메서드 | `++`, `--` | `getAndIncrement()`, `incrementAndGet()`, `get()` |",
    "",
    "> 웹 서버에서 주문 ID를 순차적으로 생성할 때, 여러 사용자가 동시에 주문하면 같은 ID가 생길 수 있습니다. `AtomicLong`을 사용하면 **중복 없이 안전하게** ID를 발급할 수 있습니다.",
    "",
    "#### @TimeTrace란?",
    "",
    "이 예제에서 직접 만든 **커스텀 어노테이션**입니다. 이 어노테이션을 붙인 메서드만 AOP가 실행 시간을 측정합니다. 아래 `TimeTrace.java`에서 어노테이션을 정의하고, `TimeTraceAspect.java`에서 동작을 구현합니다. 자세한 설명은 아래 \"커스텀 어노테이션 + AOP\" 섹션에서 다룹니다.",
    "",
    "```java",
    "package com.example.demo.service;",
    "",
    "import com.example.demo.aop.annotation.TimeTrace;",
    "import com.example.demo.dto.OrderRequest;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.stereotype.Service;",
    "",
    "import java.util.Map;",
    "import java.util.concurrent.ConcurrentHashMap;",
    "import java.util.concurrent.atomic.AtomicLong;",
    "",
    "@Slf4j",
    "@Service",
    "public class OrderService {",
    "",
    "    private final Map<Long, Map<String, Object>> orders = new ConcurrentHashMap<>();",
    "    private final AtomicLong idGenerator = new AtomicLong(1);",
    "",
    "    @TimeTrace",
    "    public Map<String, Object> createOrder(OrderRequest request) {",
    "        log.info(\"주문 생성 로직 실행: {}\", request.getItemName());",
    "",
    "        // 시간이 걸리는 작업 시뮬레이션",
    "        try { Thread.sleep(150); } catch (InterruptedException ignored) {}",
    "",
    "        Long id = idGenerator.getAndIncrement();",
    "        Map<String, Object> order = Map.of(",
    "                \"id\", id,",
    "                \"itemName\", request.getItemName(),",
    "                \"quantity\", request.getQuantity(),",
    "                \"price\", request.getPrice(),",
    "                \"totalPrice\", request.getQuantity() * request.getPrice(),",
    "                \"status\", \"CREATED\"",
    "        );",
    "        orders.put(id, order);",
    "        return order;",
    "    }",
    "",
    "    public Map<String, Object> getOrder(Long orderId) {",
    "        log.info(\"주문 조회 로직 실행: {}\", orderId);",
    "",
    "        if (orderId <= 0) {",
    "            throw new IllegalArgumentException(\"유효하지 않은 주문 ID: \" + orderId);",
    "        }",
    "",
    "        Map<String, Object> order = orders.get(orderId);",
    "        if (order == null) {",
    "            throw new IllegalArgumentException(\"존재하지 않는 주문: \" + orderId);",
    "        }",
    "        return order;",
    "    }",
    "",
    "    public Map<String, Object> getAllOrders() {",
    "        log.info(\"전체 주문 조회 로직 실행\");",
    "        return Map.of(\"orders\", orders.values(), \"count\", orders.size());",
    "    }",
    "}",
    "```",
    "",
    "### OrderController.java",
    "",
    "```java",
    "package com.example.demo.controller;",
    "",
    "import com.example.demo.dto.ApiResponse;",
    "import com.example.demo.dto.OrderRequest;",
    "import com.example.demo.service.OrderService;",
    "import lombok.RequiredArgsConstructor;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "import java.util.Map;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/orders\")",
    "@RequiredArgsConstructor",
    "public class OrderController {",
    "",
    "    private final OrderService orderService;",
    "",
    "    @PostMapping",
    "    public ApiResponse<Map<String, Object>> create(@RequestBody OrderRequest request) {",
    "        return ApiResponse.ok(orderService.createOrder(request));",
    "    }",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public ApiResponse<Map<String, Object>> get(@PathVariable Long id) {",
    "        return ApiResponse.ok(orderService.getOrder(id));",
    "    }",
    "",
    "    @GetMapping",
    "    public ApiResponse<Map<String, Object>> getAll() {",
    "        return ApiResponse.ok(orderService.getAllOrders());",
    "    }",
    "}",
    "```",
    "",
    "### TimeTrace.java (커스텀 어노테이션)",
    "",
    "```java",
    "package com.example.demo.aop.annotation;",
    "",
    "import java.lang.annotation.ElementType;",
    "import java.lang.annotation.Retention;",
    "import java.lang.annotation.RetentionPolicy;",
    "import java.lang.annotation.Target;",
    "",
    "@Target(ElementType.METHOD)",
    "@Retention(RetentionPolicy.RUNTIME)",
    "public @interface TimeTrace {",
    "}",
    "```",
    "",
    "| 어노테이션 | 설명 |",
    "|------------|------|",
    "| `@Target(ElementType.METHOD)` | 메서드에만 붙일 수 있음 |",
    "| `@Retention(RetentionPolicy.RUNTIME)` | 런타임까지 어노테이션 정보 유지 (리플렉션으로 읽을 수 있음) |",
    "",
    "### ExecutionTimeAspect.java (@Around - 실행 시간 측정)",
    "",
    "```java",
    "package com.example.demo.aop;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.aspectj.lang.ProceedingJoinPoint;",
    "import org.aspectj.lang.annotation.Around;",
    "import org.aspectj.lang.annotation.Aspect;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Slf4j",
    "@Aspect",
    "@Component",
    "public class ExecutionTimeAspect {",
    "",
    "    @Around(\"execution(* com.example.demo.service..*(..))\")",
    "    public Object measureExecutionTime(ProceedingJoinPoint joinPoint) throws Throwable {",
    "",
    "        String methodName = joinPoint.getSignature().toShortString();",
    "        long start = System.currentTimeMillis();",
    "",
    "        try {",
    "            Object result = joinPoint.proceed();",
    "            return result;",
    "        } finally {",
    "            long elapsed = System.currentTimeMillis() - start;",
    "            log.info(\"[실행 시간] {} → {}ms\", methodName, elapsed);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "| 요소 | 설명 |",
    "|------|------|",
    "| `@Aspect` | 이 클래스가 Aspect임을 선언 |",
    "| `@Component` | Spring Bean으로 등록 (필수) |",
    "| `@Around` | 메서드 실행 전후를 감싸는 Advice |",
    "| `ProceedingJoinPoint` | 대상 메서드 정보를 담고 있는 객체 |",
    "| `joinPoint.proceed()` | **실제 메서드를 실행** (이걸 호출하지 않으면 원래 메서드가 실행되지 않음!) |",
    "| `execution(* com.example.demo.service..*(..))` | service 패키지의 모든 메서드에 적용 |",
    "",
    "### LoggingAspect.java (@Before, @AfterReturning, @AfterThrowing)",
    "",
    "```java",
    "package com.example.demo.aop;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.aspectj.lang.JoinPoint;",
    "import org.aspectj.lang.annotation.*;",
    "import org.springframework.stereotype.Component;",
    "",
    "import java.util.Arrays;",
    "",
    "@Slf4j",
    "@Aspect",
    "@Component",
    "public class LoggingAspect {",
    "",
    "    @Before(\"execution(* com.example.demo.controller..*(..))\")",
    "    public void logBefore(JoinPoint joinPoint) {",
    "        String method = joinPoint.getSignature().toShortString();",
    "        Object[] args = joinPoint.getArgs();",
    "        log.info(\"[호출] {} | 파라미터: {}\", method, Arrays.toString(args));",
    "    }",
    "",
    "    @AfterReturning(",
    "            pointcut = \"execution(* com.example.demo.controller..*(..))\"",
    "          , returning = \"result\"",
    "    )",
    "    public void logAfterReturning(JoinPoint joinPoint, Object result) {",
    "        String method = joinPoint.getSignature().toShortString();",
    "        log.info(\"[성공] {} | 결과: {}\", method, result);",
    "    }",
    "",
    "    @AfterThrowing(",
    "            pointcut = \"execution(* com.example.demo.controller..*(..))\"",
    "          , throwing = \"ex\"",
    "    )",
    "    public void logAfterThrowing(JoinPoint joinPoint, Exception ex) {",
    "        String method = joinPoint.getSignature().toShortString();",
    "        log.error(\"[예외] {} | {}: {}\", method, ex.getClass().getSimpleName(), ex.getMessage());",
    "    }",
    "}",
    "```",
    "",
    "### ExceptionAlertAspect.java (@AfterThrowing - 예외 알림)",
    "",
    "```java",
    "package com.example.demo.aop;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.aspectj.lang.JoinPoint;",
    "import org.aspectj.lang.annotation.AfterThrowing;",
    "import org.aspectj.lang.annotation.Aspect;",
    "import org.springframework.stereotype.Component;",
    "",
    "import java.util.Arrays;",
    "",
    "@Slf4j",
    "@Aspect",
    "@Component",
    "public class ExceptionAlertAspect {",
    "",
    "    @AfterThrowing(",
    "        pointcut = \"execution(* com.example.demo.service..*(..))\"",
    "      , throwing = \"ex\"",
    "    )",
    "    public void handleException(JoinPoint joinPoint, Exception ex) {",
    "        String method = joinPoint.getSignature().toShortString();",
    "        Object[] args = joinPoint.getArgs();",
    "",
    "        log.error(\"=======================================\");",
    "        log.error(\"[예외 발생] 메서드: {}\", method);",
    "        log.error(\"[예외 발생] 파라미터: {}\", Arrays.toString(args));",
    "        log.error(\"[예외 발생] 예외: {} - {}\", ex.getClass().getSimpleName(), ex.getMessage());",
    "        log.error(\"=======================================\");",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 실행 및 포스트맨으로 테스트",
    "",
    "### 애플리케이션 실행",
    "",
    "IntelliJ에서 `DemoApplication.java`를 열고 **▶ Run** 버튼을 클릭합니다. 콘솔에 아래가 나오면 성공입니다.",
    "",
    "```",
    "Started DemoApplication in 1.5 seconds",
    "```",
    "",
    "### 테스트 1: 주문 생성 (POST)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | POST |",
    "| **URL** | `http://localhost:8080/api/orders` |",
    "| **Headers** | Content-Type: application/json |",
    "| **Body (raw JSON)** | 아래 참고 |",
    "",
    "```json",
    "{",
    "    \"itemName\": \"노트북\",",
    "    \"quantity\": 2,",
    "    \"price\": 1500000",
    "}",
    "```",
    "",
    "**포스트맨 응답:**",
    "",
    "```json",
    "{",
    "    \"success\": true,",
    "    \"data\": {",
    "        \"id\": 1,",
    "        \"itemName\": \"노트북\",",
    "        \"quantity\": 2,",
    "        \"price\": 1500000,",
    "        \"totalPrice\": 3000000,",
    "        \"status\": \"CREATED\"",
    "    },",
    "    \"message\": null",
    "}",
    "```",
    "",
    "**IntelliJ 콘솔 로그 (AOP 동작 확인):**",
    "",
    "```",
    "INFO  [호출] OrderController.create(..) | 파라미터: [OrderRequest(itemName=노트북, quantity=2, price=1500000)]",
    "INFO  주문 생성 로직 실행: 노트북",
    "INFO  [실행 시간] OrderService.createOrder(..) → 152ms",
    "INFO  [성공] OrderController.create(..) | 결과: ApiResponse(success=true, data={...})",
    "```",
    "",
    "> `@Before` → Service 실행 → `@Around`(시간 측정) → `@AfterReturning` 순서로 AOP가 동작하는 것을 확인할 수 있습니다.",
    "",
    "### 테스트 2: 주문 조회 (GET - 정상)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/orders/1` |",
    "",
    "**포스트맨 응답:**",
    "",
    "```json",
    "{",
    "    \"success\": true,",
    "    \"data\": {",
    "        \"id\": 1,",
    "        \"itemName\": \"노트북\",",
    "        \"quantity\": 2,",
    "        \"price\": 1500000,",
    "        \"totalPrice\": 3000000,",
    "        \"status\": \"CREATED\"",
    "    },",
    "    \"message\": null",
    "}",
    "```",
    "",
    "### 테스트 3: 주문 조회 (GET - 예외 발생)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/orders/-1` |",
    "",
    "**IntelliJ 콘솔 로그 (ExceptionAlertAspect 동작):**",
    "",
    "```",
    "INFO  [호출] OrderController.get(..) | 파라미터: [-1]",
    "INFO  주문 조회 로직 실행: -1",
    "ERROR =======================================",
    "ERROR [예외 발생] 메서드: OrderService.getOrder(..)",
    "ERROR [예외 발생] 파라미터: [-1]",
    "ERROR [예외 발생] 예외: IllegalArgumentException - 유효하지 않은 주문 ID: -1",
    "ERROR =======================================",
    "ERROR [예외] OrderController.get(..) | IllegalArgumentException: 유효하지 않은 주문 ID: -1",
    "```",
    "",
    "> Service 코드에는 로깅·시간측정·예외알림 코드가 **하나도 없지만**, AOP가 자동으로 처리합니다.",
    "",
    "### 테스트 4: 전체 주문 조회 (GET)",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Method** | GET |",
    "| **URL** | `http://localhost:8080/api/orders` |",
    "",
    "### 포스트맨 테스트 요약",
    "",
    "| 테스트 | Method | URL | Body | 확인할 AOP |",
    "|--------|--------|-----|------|-----------|",
    "| 주문 생성 | POST | `/api/orders` | `{\"itemName\":\"노트북\",\"quantity\":2,\"price\":1500000}` | @Before, @Around(시간측정), @AfterReturning |",
    "| 정상 조회 | GET | `/api/orders/1` | 없음 | @Before, @Around, @AfterReturning |",
    "| 예외 조회 | GET | `/api/orders/-1` | 없음 | @Before, @Around, **@AfterThrowing**, ExceptionAlert |",
    "| 전체 조회 | GET | `/api/orders` | 없음 | @Before, @Around, @AfterReturning |",
    "",
    "---",
    "",
    "## 커스텀 어노테이션 + AOP (@TimeTrace)",
    "",
    "위 코드에서 `OrderService.createOrder()`에만 `@TimeTrace`를 붙였습니다. 이 어노테이션이 붙은 메서드만 **별도로** 시간을 추적하는 Aspect를 만들 수 있습니다.",
    "",
    "위에서 이미 `TimeTrace.java` 어노테이션을 만들었으므로, Aspect만 추가하면 됩니다.",
    "",
    "### TimeTraceAspect.java (aop/ 폴더에 추가)",
    "",
    "```java",
    "package com.example.demo.aop;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.aspectj.lang.ProceedingJoinPoint;",
    "import org.aspectj.lang.annotation.Around;",
    "import org.aspectj.lang.annotation.Aspect;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Slf4j",
    "@Aspect",
    "@Component",
    "public class TimeTraceAspect {",
    "",
    "    @Around(\"@annotation(com.example.demo.aop.annotation.TimeTrace)\")",
    "    public Object traceTime(ProceedingJoinPoint joinPoint) throws Throwable {",
    "        String method = joinPoint.getSignature().toShortString();",
    "        log.info(\"[TimeTrace 시작] {}\", method);",
    "",
    "        long start = System.nanoTime();",
    "        try {",
    "            return joinPoint.proceed();",
    "        } finally {",
    "            long elapsed = (System.nanoTime() - start) / 1_000_000;",
    "            log.info(\"[TimeTrace 종료] {} → {}ms\", method, elapsed);",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "> **패키지 전체 vs 어노테이션** 방식 비교:",
    "",
    "| 방식 | Pointcut 표현식 | 장점 | 단점 |",
    "|------|-----------------|------|------|",
    "| 패키지 전체 | `execution(* com.example..service..*(..))` | 일괄 적용, 누락 없음 | 불필요한 메서드에도 적용 |",
    "| 커스텀 어노테이션 | `@annotation(TimeTrace)` | 명시적, 선택적 적용 | 어노테이션 붙이는 걸 잊을 수 있음 |",
    "",
    "---",
    "",
    "## Pointcut 표현식 문법",
    "",
    "Pointcut은 **어떤 메서드에 Aspect를 적용할지** 결정하는 조건식입니다.",
    "",
    "### execution 표현식 구조",
    "",
    "```",
    "execution(접근제어자? 반환타입 패키지.클래스.메서드(파라미터))",
    "```",
    "",
    "### 자주 쓰는 패턴",
    "",
    "| 표현식 | 의미 |",
    "|--------|------|",
    "| `execution(* com.example.demo.service..*(..))` | service 패키지와 하위 패키지의 모든 메서드 |",
    "| `execution(* com.example.demo.service.OrderService.*(..))` | OrderService의 모든 메서드 |",
    "| `execution(public * *(..))` | 모든 public 메서드 |",
    "| `execution(* create*(..))` | create로 시작하는 모든 메서드 |",
    "| `execution(* *(String, ..))` | 첫 번째 파라미터가 String인 메서드 |",
    "| `execution(String *(..))` | 반환 타입이 String인 메서드 |",
    "",
    "### 와일드카드 의미",
    "",
    "| 기호 | 의미 |",
    "|------|------|",
    "| `*` | 아무 값 하나 (패키지·클래스·메서드·반환타입) |",
    "| `..` | 0개 이상 (패키지 → 하위 패키지 포함, 파라미터 → 아무 개수) |",
    "",
    "### 기타 Pointcut 지시자",
    "",
    "| 지시자 | 예시 | 설명 |",
    "|--------|------|------|",
    "| `@annotation` | `@annotation(TimeTrace)` | 특정 어노테이션이 붙은 메서드 |",
    "| `@within` | `@within(org.springframework.stereotype.Service)` | 특정 어노테이션이 붙은 **클래스**의 모든 메서드 |",
    "| `within` | `within(com.example.demo.service..*)` | 특정 패키지 내의 모든 메서드 |",
    "| `bean` | `bean(orderService)` | 특정 Bean 이름의 모든 메서드 (Spring 전용) |",
    "| `args` | `args(String, ..)` | 런타임 파라미터 타입으로 매칭 |",
    "",
    "### Pointcut 조합 (AND, OR, NOT)",
    "",
    "```java",
    "package com.example.demo.aop;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.aspectj.lang.JoinPoint;",
    "import org.aspectj.lang.annotation.Aspect;",
    "import org.aspectj.lang.annotation.Before;",
    "import org.aspectj.lang.annotation.Pointcut;",
    "import org.springframework.stereotype.Component;",
    "",
    "@Slf4j",
    "@Aspect",
    "@Component",
    "public class CombinedAspect {",
    "",
    "    @Pointcut(\"execution(* com.example.demo.service..*(..))\")",
    "    private void serviceLayer() {}",
    "",
    "    @Pointcut(\"execution(* com.example.demo.controller..*(..))\")",
    "    private void controllerLayer() {}",
    "",
    "    // Service OR Controller",
    "    @Before(\"serviceLayer() || controllerLayer()\")",
    "    public void logAll(JoinPoint joinPoint) {",
    "        log.info(\"[LOG] {}\", joinPoint.getSignature().toShortString());",
    "    }",
    "",
    "    // Service AND create로 시작하는 메서드",
    "    @Before(\"serviceLayer() && execution(* create*(..))\")",
    "    public void logCreate(JoinPoint joinPoint) {",
    "        log.info(\"[CREATE] {}\", joinPoint.getSignature().toShortString());",
    "    }",
    "",
    "    // NOT: Service 중에서 get으로 시작하지 않는 메서드",
    "    @Before(\"serviceLayer() && !execution(* get*(..))\")",
    "    public void logExceptGet(JoinPoint joinPoint) {",
    "        log.info(\"[NOT GET] {}\", joinPoint.getSignature().toShortString());",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Spring AOP 동작 원리 - 프록시(Proxy)",
    "",
    "Spring AOP는 **프록시 패턴**으로 동작합니다. 대상 객체를 직접 호출하는 것이 아니라, Spring이 만든 **프록시 객체**를 통해 호출합니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[Controller] -->|\"orderService.createOrder()\"| B[\"Proxy 객체<br/>(Spring이 자동 생성)\"]",
    "    B -->|\"@Before 실행\"| C[Advice 로직]",
    "    B -->|\"proceed()\"| D[\"실제 OrderService\"]",
    "    D -->|반환| B",
    "    B -->|\"@AfterReturning 실행\"| C",
    "    B -->|결과 전달| A",
    "```",
    "",
    "### 프록시 생성 방식",
    "",
    "Spring은 대상 객체가 인터페이스를 구현했는지 여부에 따라 **JDK 동적 프록시** 또는 **CGLIB 프록시**를 선택합니다. Spring Boot 2.0+부터는 기본적으로 CGLIB 프록시를 사용합니다.",
    "",
    "> 📌 JDK Dynamic Proxy와 CGLIB의 차이, ProxyFactory, 프록시 디버깅 등 상세한 내용은 'Spring Boot 프록시(Proxy) 완전 정리' 글을 참고하세요.",
    "",
    "### Spring AOP vs AspectJ",
    "",
    "| 비교 | Spring AOP | AspectJ |",
    "|------|-----------|---------|",
    "| 위빙 시점 | **런타임** (프록시) | 컴파일타임 / 로드타임 |",
    "| 적용 대상 | **Spring Bean의 메서드**만 | 모든 Java 객체 |",
    "| JoinPoint | 메서드 실행만 | 메서드, 생성자, 필드 접근 등 |",
    "| 성능 | 약간의 프록시 오버헤드 | 직접 바이트코드 수정 → 빠름 |",
    "| 설정 난이도 | 쉬움 (Spring 내장) | 복잡 (별도 컴파일러 필요) |",
    "| 실무 선택 | **대부분의 경우 충분** | 극도의 성능·세밀한 제어 필요 시 |",
    "",
    "---",
    "",
    "## 실무에서 AOP가 이미 적용된 곳",
    "",
    "우리가 Spring에서 자주 쓰는 기능 중 상당수가 **내부적으로 AOP로 동작**합니다.",
    "",
    "| 기능 | 어노테이션 | AOP로 하는 일 |",
    "|------|------------|---------------|",
    "| 트랜잭션 | `@Transactional` | 메서드 시작 시 트랜잭션 시작, 종료 시 커밋/롤백 |",
    "| 캐싱 | `@Cacheable` | 결과를 캐시에 저장, 다음 호출 시 캐시에서 반환 |",
    "| 비동기 | `@Async` | 메서드를 별도 스레드에서 실행 |",
    "| 보안 | `@PreAuthorize` | 메서드 실행 전 권한 체크 |",
    "| 재시도 | `@Retryable` | 예외 발생 시 자동 재시도 |",
    "",
    "### @Transactional이 AOP로 동작하는 원리",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as Controller",
    "    participant P as Proxy (트랜잭션 AOP)",
    "    participant S as 실제 Service",
    "    participant DB as Database",
    "    C->>P: createOrder() 호출",
    "    Note over P: 트랜잭션 시작 (BEGIN)",
    "    P->>S: createOrder() 실행",
    "    S->>DB: INSERT 쿼리",
    "    DB-->>S: 성공",
    "    S-->>P: 결과 반환",
    "    alt 예외 없음",
    "        Note over P: 트랜잭션 커밋 (COMMIT)",
    "    else 예외 발생",
    "        Note over P: 트랜잭션 롤백 (ROLLBACK)",
    "    end",
    "    P-->>C: 결과/예외 전달",
    "```",
    "",
    "---",
    "",
    "## AOP가 주로 쓰이는 실무 시나리오",
    "",
    "AOP는 **여러 클래스에 걸쳐 반복되는 기술적 관심사**를 분리할 때 사용합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    AOP[\"AOP 실무 활용\"]",
    "    AOP --> A[\"1. 로깅 / 모니터링\"]",
    "    AOP --> B[\"2. 성능 측정\"]",
    "    AOP --> C[\"3. 트랜잭션 관리\"]",
    "    AOP --> D[\"4. 보안 / 권한 체크\"]",
    "    AOP --> E[\"5. 캐싱\"]",
    "    AOP --> F[\"6. 예외 처리 / 재시도\"]",
    "    AOP --> G[\"7. 감사 로그 (Audit)\"]",
    "    AOP --> H[\"8. API 속도 제한\"]",
    "```",
    "",
    "### 시나리오별 요약",
    "",
    "| 시나리오 | Advice 타입 | 핵심 | 실무 중요도 |",
    "|----------|-----------|------|:---:|",
    "| API 요청/응답 로깅 | `@Around` | 파라미터, 결과, 시간 기록 | ★★★★★ |",
    "| 느린 API 감지 | `@Around` | 기준시간 초과 시 경고 | ★★★★☆ |",
    "| 트랜잭션 관리 | `@Around` (내부) | `@Transactional`이 AOP로 동작 | ★★★★★ |",
    "| 권한 체크 | `@Before` | 메서드 실행 전 인증/인가 확인 | ★★★★☆ |",
    "| 캐싱 | `@Around` (내부) | `@Cacheable`이 AOP로 동작 | ★★★★☆ |",
    "| 자동 재시도 | `@Around` (내부) | `@Retryable`이 AOP로 동작 | ★★★☆☆ |",
    "| 감사 로그 | `@AfterReturning` | 데이터 변경 이력 자동 저장 | ★★★★☆ |",
    "| API 속도 제한 | `@Before` | 과도한 요청 차단 | ★★★☆☆ |",
    "",
    "> 실무에서 **직접 AOP를 작성하는 경우**는 주로 로깅, 성능 측정, 감사 로그입니다. 트랜잭션, 캐싱, 재시도 등은 Spring이 제공하는 AOP 기반 어노테이션(`@Transactional`, `@Cacheable`, `@Retryable`)을 사용합니다.",
    "",
    "---",
    "",
    "## 주의사항 (반드시 알아야 할 것)",
    "",
    "### 1. 같은 클래스 내부에서 호출하면 AOP가 적용되지 않음",
    "",
    "Spring AOP는 **프록시를 통해** 동작하기 때문에, 같은 클래스 안에서 `this.method()`를 호출하면 프록시를 거치지 않아 AOP가 적용되지 않습니다. 해결 방법은 메서드를 **별도의 클래스**로 분리하는 것이 가장 깔끔합니다.",
    "",
    "> 📌 내부 호출 문제의 상세한 동작 원리와 다양한 해결 방법은 'Spring Boot 프록시(Proxy) 완전 정리' 글을 참고하세요.",
    "",
    "### 2. private 메서드에는 AOP 적용 불가",
    "",
    "CGLIB 프록시는 **상속**으로 동작하므로, `private` 메서드는 오버라이드할 수 없어 AOP가 적용되지 않습니다. AOP를 적용하려면 `public` 메서드를 사용해야 합니다.",
    "",
    "> 📌 프록시 기반의 제약사항(private, final, 내부 호출)에 대한 상세한 설명은 'Spring Boot 프록시(Proxy) 완전 정리' 글을 참고하세요.",
    "",
    "### 3. Aspect 실행 순서 제어 (@Order)",
    "",
    "여러 Aspect가 같은 메서드에 적용될 때 실행 순서를 `@Order`로 제어합니다.",
    "",
    "```java",
    "import org.springframework.core.annotation.Order;",
    "",
    "@Aspect @Component @Order(1)  // 숫자가 작을수록 먼저 실행",
    "public class SecurityAspect { ... }",
    "",
    "@Aspect @Component @Order(2)",
    "public class LoggingAspect { ... }",
    "",
    "@Aspect @Component @Order(3)",
    "public class ExecutionTimeAspect { ... }",
    "```",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[요청] --> B[\"SecurityAspect<br/>(@Order 1)\"]",
    "    B --> C[\"LoggingAspect<br/>(@Order 2)\"]",
    "    C --> D[\"ExecutionTimeAspect<br/>(@Order 3)\"]",
    "    D --> E[실제 메서드]",
    "    E --> D",
    "    D --> C",
    "    C --> B",
    "    B --> A",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| AOP란 | 공통 관심사(로깅, 트랜잭션 등)를 비즈니스 로직에서 분리하는 기법 |",
    "| 핵심 어노테이션 | `@Aspect`, `@Before`, `@After`, `@AfterReturning`, `@AfterThrowing`, `@Around` |",
    "| Pointcut | `execution(...)`, `@annotation(...)`, `within(...)`, `bean(...)` |",
    "| 동작 원리 | Spring이 **프록시 객체**를 생성하여 메서드 호출을 가로챔 |",
    "| 주의사항 | 내부 호출 시 AOP 미적용, private 메서드 불가, `@Order`로 순서 제어 |",
    "",
    "**AOP 활용 패턴:**",
    "",
    "| 용도 | Advice 타입 | 핵심 키워드 |",
    "|------|-------------|-------------|",
    "| 실행 시간 측정 | `@Around` | `System.currentTimeMillis()` + `proceed()` |",
    "| 로깅 | `@Before` / `@AfterReturning` | `joinPoint.getArgs()` / `returning` |",
    "| 예외 감지/알림 | `@AfterThrowing` | `throwing` + Slack/Email |",
    "| 권한 체크 | `@Before` | 파라미터 검증, 인증 확인 |",
    "| 응답 래핑 | `@Around` | `proceed()` 결과를 공통 포맷으로 변환 |",
    "| 트랜잭션 | `@Around` (내부) | `@Transactional`이 이 방식으로 동작 |",
    "",
    "Spring에서 이미 `@Transactional`, `@Cacheable`, `@Async` 등이 AOP로 동작하고 있으므로, AOP의 원리를 이해하면 이들의 동작 방식과 주의사항(내부 호출 문제 등)도 자연스럽게 이해할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
