<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-exception-handling",
  title: "스프링부트 예외 처리 완전 정리 - 개념부터 실전 패턴까지",
  date: "2026-03-02",
  summary: "Spring Boot의 예외 처리 전략을 정리합니다. @ExceptionHandler, @RestControllerAdvice, 커스텀 예외, ErrorResponse 패턴, Bean Validation 에러 처리, 예외 계층 구조 설계까지 실전 예제로 다룹니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","exception","error","restcontrolleradvice","java","backend"],
  content: [
    "## 왜 예외 처리가 중요한가?",
    "",
    "예외 처리를 제대로 하지 않으면 클라이언트에게 **서버 내부 정보가 노출**되거나, **일관성 없는 에러 응답**이 반환됩니다.",
    "",
    "### 예외 처리 안 했을 때",
    "",
    "```json",
    "{",
    "  \"timestamp\": \"2026-03-02T10:30:00.000+00:00\",",
    "  \"status\": 500,",
    "  \"error\": \"Internal Server Error\",",
    "  \"trace\": \"java.lang.NullPointerException\\n\\tat com.example.demo.service.UserService.findById(UserService.java:25)\\n\\tat com.example.demo.controller.UserController...\",",
    "  \"path\": \"/api/users/999\"",
    "}",
    "```",
    "",
    "> 스택 트레이스가 그대로 노출되어 **보안 취약점**이 됩니다.",
    "",
    "### 예외 처리 했을 때",
    "",
    "```json",
    "{",
    "  \"code\": \"USER_NOT_FOUND\",",
    "  \"message\": \"사용자를 찾을 수 없습니다\",",
    "  \"status\": 404",
    "}",
    "```",
    "",
    "> 클라이언트에게 **의미 있는 정보**만 전달하고, 내부 정보는 숨깁니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"예외 발생\"] --> B{\"예외 처리 여부\"}",
    "    B -->|처리 안 함| C[\"500 + 스택 트레이스 노출\"]",
    "    B -->|처리 함| D[\"적절한 상태 코드 +<br/>깔끔한 에러 응답\"]",
    "```",
    "",
    "---",
    "",
    "## Spring Boot 예외 처리 방법 3가지",
    "",
    "| 방법 | 범위 | 추천 |",
    "|------|------|------|",
    "| `try-catch` | 메서드 내부 | 특수한 경우만 |",
    "| `@ExceptionHandler` | 특정 Controller | 컨트롤러별 처리 |",
    "| **`@RestControllerAdvice`** | **전체 애플리케이션** | **권장** |",
    "",
    "---",
    "",
    "## 방법 1: try-catch (비추천)",
    "",
    "```java",
    "@GetMapping(\"/{id}\")",
    "public ResponseEntity<?> getUser(@PathVariable Long id) {",
    "    try {",
    "        UserResponse user = userService.findById(id);",
    "        return ResponseEntity.ok(user);",
    "    } catch (UserNotFoundException e) {",
    "        return ResponseEntity.status(HttpStatus.NOT_FOUND)",
    "                .body(Map.of(\"message\", e.getMessage()));",
    "    } catch (Exception e) {",
    "        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)",
    "                .body(Map.of(\"message\", \"서버 오류\"));",
    "    }",
    "}",
    "```",
    "",
    "### 문제점",
    "",
    "- 모든 Controller 메서드에 try-catch를 반복해야 함",
    "- 에러 응답 형식이 일관되지 않음",
    "- 비즈니스 로직과 에러 처리가 섞여서 가독성 저하",
    "",
    "---",
    "",
    "## 방법 2: @ExceptionHandler (Controller 단위)",
    "",
    "특정 Controller 안에서만 동작하는 예외 처리입니다.",
    "",
    "```java",
    "@RestController",
    "@RequestMapping(\"/api/users\")",
    "public class UserController {",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public UserResponse getUser(@PathVariable Long id) {",
    "        return userService.findById(id);",
    "    }",
    "",
    "    @ExceptionHandler(UserNotFoundException.class)",
    "    public ResponseEntity<Map<String, String>> handleUserNotFound(",
    "            UserNotFoundException e) {",
    "        return ResponseEntity.status(HttpStatus.NOT_FOUND)",
    "                .body(Map.of(\"message\", e.getMessage()));",
    "    }",
    "}",
    "```",
    "",
    "> 이 `@ExceptionHandler`는 `UserController` 안에서 발생한 `UserNotFoundException`만 처리합니다. 다른 Controller에서는 동작하지 않습니다.",
    "",
    "---",
    "",
    "## 방법 3: @RestControllerAdvice (전역 처리, 권장)",
    "",
    "**모든 Controller**에서 발생하는 예외를 **한 곳에서** 처리합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"UserController\"] -->|예외 발생| D[\"@RestControllerAdvice<br/>GlobalExceptionHandler\"]",
    "    B[\"OrderController\"] -->|예외 발생| D",
    "    C[\"ProductController\"] -->|예외 발생| D",
    "    D --> E[\"적절한 HTTP 상태 코드 +<br/>통일된 에러 응답 반환\"]",
    "```",
    "",
    "### @ControllerAdvice vs @RestControllerAdvice",
    "",
    "| 어노테이션 | 반환 방식 | 용도 |",
    "|------------|----------|------|",
    "| `@ControllerAdvice` | View (HTML) | Thymeleaf/JSP 프로젝트 |",
    "| `@RestControllerAdvice` | **JSON** | **REST API 프로젝트 (권장)** |",
    "",
    "> `@RestControllerAdvice` = `@ControllerAdvice` + `@ResponseBody`",
    "",
    "---",
    "",
    "## 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── controller/",
    "│   └── UserController.java",
    "├── service/",
    "│   └── UserService.java",
    "├── exception/",
    "│   ├── ErrorCode.java               // 에러 코드 Enum",
    "│   ├── ErrorResponse.java           // 통일된 에러 응답 DTO",
    "│   ├── BusinessException.java       // 비즈니스 예외 베이스 클래스",
    "│   ├── UserNotFoundException.java   // 사용자 없음 예외",
    "│   ├── DuplicateEmailException.java // 이메일 중복 예외",
    "│   └── GlobalExceptionHandler.java  // 전역 예외 처리기",
    "└── dto/",
    "    ├── CreateUserRequest.java",
    "    └── UserResponse.java",
    "```",
    "",
    "---",
    "",
    "## 1단계: 통일된 에러 응답 (ErrorResponse)",
    "",
    "모든 에러 응답을 **같은 형식**으로 반환해야 프론트엔드에서 일관되게 처리할 수 있습니다.",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "import com.fasterxml.jackson.annotation.JsonInclude;",
    "import lombok.*;",
    "import java.time.LocalDateTime;",
    "import java.util.Map;",
    "",
    "@Getter",
    "@Builder",
    "@JsonInclude(JsonInclude.Include.NON_NULL)",
    "public class ErrorResponse {",
    "",
    "    private final String code;",
    "    private final String message;",
    "    private final int status;",
    "    private final LocalDateTime timestamp;",
    "    private final Map<String, String> errors;",
    "",
    "    public static ErrorResponse of(ErrorCode errorCode) {",
    "        return ErrorResponse.builder()",
    "                .code(errorCode.getCode())",
    "                .message(errorCode.getMessage())",
    "                .status(errorCode.getStatus())",
    "                .timestamp(LocalDateTime.now())",
    "                .build();",
    "    }",
    "",
    "    public static ErrorResponse of(ErrorCode errorCode, String message) {",
    "        return ErrorResponse.builder()",
    "                .code(errorCode.getCode())",
    "                .message(message)",
    "                .status(errorCode.getStatus())",
    "                .timestamp(LocalDateTime.now())",
    "                .build();",
    "    }",
    "",
    "    public static ErrorResponse of(ErrorCode errorCode, Map<String, String> errors) {",
    "        return ErrorResponse.builder()",
    "                .code(errorCode.getCode())",
    "                .message(errorCode.getMessage())",
    "                .status(errorCode.getStatus())",
    "                .timestamp(LocalDateTime.now())",
    "                .errors(errors)",
    "                .build();",
    "    }",
    "}",
    "```",
    "",
    "> `@JsonInclude(NON_NULL)`: null인 필드는 JSON에서 제외됩니다. `errors`가 없으면 응답에 포함되지 않습니다.",
    "",
    "### 에러 응답 예시",
    "",
    "```json",
    "{",
    "  \"code\": \"USER_NOT_FOUND\",",
    "  \"message\": \"사용자를 찾을 수 없습니다\",",
    "  \"status\": 404,",
    "  \"timestamp\": \"2026-03-02T10:30:00\"",
    "}",
    "```",
    "",
    "```json",
    "{",
    "  \"code\": \"VALIDATION_ERROR\",",
    "  \"message\": \"입력값이 올바르지 않습니다\",",
    "  \"status\": 400,",
    "  \"timestamp\": \"2026-03-02T10:30:00\",",
    "  \"errors\": {",
    "    \"email\": \"올바른 이메일 형식이 아닙니다\",",
    "    \"name\": \"이름은 필수입니다\"",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## 2단계: 에러 코드 Enum (ErrorCode)",
    "",
    "에러 코드를 Enum으로 관리하면 **코드, 메시지, HTTP 상태**를 한 곳에서 관리할 수 있습니다.",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "import lombok.Getter;",
    "import lombok.RequiredArgsConstructor;",
    "",
    "@Getter",
    "@RequiredArgsConstructor",
    "public enum ErrorCode {",
    "",
    "    // 400 Bad Request",
    "    INVALID_INPUT(400, \"INVALID_INPUT\", \"입력값이 올바르지 않습니다\"),",
    "    VALIDATION_ERROR(400, \"VALIDATION_ERROR\", \"요청 데이터 검증에 실패했습니다\"),",
    "    DUPLICATE_EMAIL(400, \"DUPLICATE_EMAIL\", \"이미 사용 중인 이메일입니다\"),",
    "    DUPLICATE_USERNAME(400, \"DUPLICATE_USERNAME\", \"이미 사용 중인 아이디입니다\"),",
    "",
    "    // 401 Unauthorized",
    "    UNAUTHORIZED(401, \"UNAUTHORIZED\", \"인증이 필요합니다\"),",
    "    INVALID_TOKEN(401, \"INVALID_TOKEN\", \"유효하지 않은 토큰입니다\"),",
    "",
    "    // 403 Forbidden",
    "    ACCESS_DENIED(403, \"ACCESS_DENIED\", \"접근 권한이 없습니다\"),",
    "",
    "    // 404 Not Found",
    "    USER_NOT_FOUND(404, \"USER_NOT_FOUND\", \"사용자를 찾을 수 없습니다\"),",
    "    ORDER_NOT_FOUND(404, \"ORDER_NOT_FOUND\", \"주문을 찾을 수 없습니다\"),",
    "    RESOURCE_NOT_FOUND(404, \"RESOURCE_NOT_FOUND\", \"요청한 리소스를 찾을 수 없습니다\"),",
    "",
    "    // 409 Conflict",
    "    ALREADY_EXISTS(409, \"ALREADY_EXISTS\", \"이미 존재하는 리소스입니다\"),",
    "",
    "    // 500 Internal Server Error",
    "    INTERNAL_ERROR(500, \"INTERNAL_ERROR\", \"서버 내부 오류가 발생했습니다\");",
    "",
    "    private final int status;",
    "    private final String code;",
    "    private final String message;",
    "}",
    "```",
    "",
    "### 에러 코드 Enum의 장점",
    "",
    "| 장점 | 설명 |",
    "|------|------|",
    "| 중앙 관리 | 모든 에러 코드를 한 파일에서 관리 |",
    "| 일관성 | 같은 에러는 항상 같은 코드/메시지/상태 반환 |",
    "| 프론트엔드 연동 | `code` 필드로 프론트엔드에서 에러 분기 처리 가능 |",
    "| 문서화 | Enum 자체가 에러 목록 문서 역할 |",
    "",
    "---",
    "",
    "## 3단계: 커스텀 예외 클래스",
    "",
    "### 비즈니스 예외 베이스 클래스",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "import lombok.Getter;",
    "",
    "@Getter",
    "public class BusinessException extends RuntimeException {",
    "",
    "    private final ErrorCode errorCode;",
    "",
    "    public BusinessException(ErrorCode errorCode) {",
    "        super(errorCode.getMessage());",
    "        this.errorCode = errorCode;",
    "    }",
    "",
    "    public BusinessException(ErrorCode errorCode, String message) {",
    "        super(message);",
    "        this.errorCode = errorCode;",
    "    }",
    "}",
    "```",
    "",
    "### 구체적인 예외 클래스",
    "",
    "```java",
    "public class UserNotFoundException extends BusinessException {",
    "",
    "    public UserNotFoundException() {",
    "        super(ErrorCode.USER_NOT_FOUND);",
    "    }",
    "",
    "    public UserNotFoundException(Long id) {",
    "        super(ErrorCode.USER_NOT_FOUND, \"사용자를 찾을 수 없습니다 (ID: \" + id + \")\");",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "public class DuplicateEmailException extends BusinessException {",
    "",
    "    public DuplicateEmailException() {",
    "        super(ErrorCode.DUPLICATE_EMAIL);",
    "    }",
    "",
    "    public DuplicateEmailException(String email) {",
    "        super(ErrorCode.DUPLICATE_EMAIL, \"이미 사용 중인 이메일입니다: \" + email);",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "public class OrderNotFoundException extends BusinessException {",
    "",
    "    public OrderNotFoundException(Long id) {",
    "        super(ErrorCode.ORDER_NOT_FOUND, \"주문을 찾을 수 없습니다 (ID: \" + id + \")\");",
    "    }",
    "}",
    "```",
    "",
    "### 예외 계층 구조",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"RuntimeException\"] --> B[\"BusinessException\"]",
    "    B --> C[\"UserNotFoundException\"]",
    "    B --> D[\"DuplicateEmailException\"]",
    "    B --> E[\"OrderNotFoundException\"]",
    "    B --> F[\"AccessDeniedException\"]",
    "    B --> G[\"InvalidTokenException\"]",
    "```",
    "",
    "> `BusinessException`을 상속하면, `GlobalExceptionHandler`에서 **하나의 핸들러**로 모든 비즈니스 예외를 처리할 수 있습니다.",
    "",
    "---",
    "",
    "## 4단계: 전역 예외 처리기 (GlobalExceptionHandler)",
    "",
    "```java",
    "package com.example.demo.exception;",
    "",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.http.ResponseEntity;",
    "import org.springframework.http.converter.HttpMessageNotReadableException;",
    "import org.springframework.web.HttpRequestMethodNotSupportedException;",
    "import org.springframework.web.bind.MethodArgumentNotValidException;",
    "import org.springframework.web.bind.MissingServletRequestParameterException;",
    "import org.springframework.web.bind.annotation.ExceptionHandler;",
    "import org.springframework.web.bind.annotation.RestControllerAdvice;",
    "import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException;",
    "import org.springframework.web.servlet.resource.NoResourceFoundException;",
    "",
    "import java.util.LinkedHashMap;",
    "import java.util.Map;",
    "",
    "@Slf4j",
    "@RestControllerAdvice",
    "public class GlobalExceptionHandler {",
    "",
    "    /**",
    "     * 비즈니스 예외 (BusinessException 및 모든 하위 클래스)",
    "     */",
    "    @ExceptionHandler(BusinessException.class)",
    "    public ResponseEntity<ErrorResponse> handleBusinessException(",
    "            BusinessException e) {",
    "        log.warn(\"비즈니스 예외: [{}] {}\", e.getErrorCode().getCode(), e.getMessage());",
    "",
    "        ErrorResponse response = ErrorResponse.of(e.getErrorCode(), e.getMessage());",
    "        return ResponseEntity",
    "                .status(e.getErrorCode().getStatus())",
    "                .body(response);",
    "    }",
    "",
    "    /**",
    "     * Bean Validation 실패 (@Valid 검증 에러)",
    "     */",
    "    @ExceptionHandler(MethodArgumentNotValidException.class)",
    "    public ResponseEntity<ErrorResponse> handleValidation(",
    "            MethodArgumentNotValidException e) {",
    "",
    "        Map<String, String> errors = new LinkedHashMap<>();",
    "        e.getBindingResult().getFieldErrors().forEach(error ->",
    "                errors.put(error.getField(), error.getDefaultMessage()));",
    "",
    "        log.warn(\"검증 실패: {}\", errors);",
    "",
    "        ErrorResponse response = ErrorResponse.of(ErrorCode.VALIDATION_ERROR, errors);",
    "        return ResponseEntity.badRequest().body(response);",
    "    }",
    "",
    "    /**",
    "     * 요청 본문 파싱 실패 (잘못된 JSON 등)",
    "     */",
    "    @ExceptionHandler(HttpMessageNotReadableException.class)",
    "    public ResponseEntity<ErrorResponse> handleMessageNotReadable(",
    "            HttpMessageNotReadableException e) {",
    "        log.warn(\"요청 본문 파싱 실패: {}\", e.getMessage());",
    "",
    "        ErrorResponse response = ErrorResponse.of(",
    "                ErrorCode.INVALID_INPUT, \"요청 본문을 읽을 수 없습니다. JSON 형식을 확인해주세요.\");",
    "        return ResponseEntity.badRequest().body(response);",
    "    }",
    "",
    "    /**",
    "     * 파라미터 타입 불일치 (예: id에 문자열 전달)",
    "     */",
    "    @ExceptionHandler(MethodArgumentTypeMismatchException.class)",
    "    public ResponseEntity<ErrorResponse> handleTypeMismatch(",
    "            MethodArgumentTypeMismatchException e) {",
    "        String message = String.format(",
    "                \"'%s' 파라미터의 값 '%s'이(가) 올바르지 않습니다. %s 타입이어야 합니다.\",",
    "                e.getName(), e.getValue(),",
    "                e.getRequiredType() != null ? e.getRequiredType().getSimpleName() : \"\"",
    "        );",
    "        log.warn(\"타입 불일치: {}\", message);",
    "",
    "        ErrorResponse response = ErrorResponse.of(ErrorCode.INVALID_INPUT, message);",
    "        return ResponseEntity.badRequest().body(response);",
    "    }",
    "",
    "    /**",
    "     * 필수 파라미터 누락",
    "     */",
    "    @ExceptionHandler(MissingServletRequestParameterException.class)",
    "    public ResponseEntity<ErrorResponse> handleMissingParameter(",
    "            MissingServletRequestParameterException e) {",
    "        String message = String.format(\"필수 파라미터 '%s'이(가) 누락되었습니다.\", e.getParameterName());",
    "        log.warn(\"파라미터 누락: {}\", message);",
    "",
    "        ErrorResponse response = ErrorResponse.of(ErrorCode.INVALID_INPUT, message);",
    "        return ResponseEntity.badRequest().body(response);",
    "    }",
    "",
    "    /**",
    "     * 지원하지 않는 HTTP 메서드",
    "     */",
    "    @ExceptionHandler(HttpRequestMethodNotSupportedException.class)",
    "    public ResponseEntity<ErrorResponse> handleMethodNotSupported(",
    "            HttpRequestMethodNotSupportedException e) {",
    "        String message = String.format(",
    "                \"'%s' 메서드는 지원하지 않습니다. 지원 메서드: %s\",",
    "                e.getMethod(), e.getSupportedHttpMethods());",
    "        log.warn(\"메서드 미지원: {}\", message);",
    "",
    "        ErrorResponse response = ErrorResponse.of(ErrorCode.INVALID_INPUT, message);",
    "        return ResponseEntity.status(HttpStatus.METHOD_NOT_ALLOWED).body(response);",
    "    }",
    "",
    "    /**",
    "     * 존재하지 않는 URL 접근",
    "     */",
    "    @ExceptionHandler(NoResourceFoundException.class)",
    "    public ResponseEntity<ErrorResponse> handleNoResourceFound(",
    "            NoResourceFoundException e) {",
    "        log.warn(\"리소스 없음: {}\", e.getMessage());",
    "",
    "        ErrorResponse response = ErrorResponse.of(ErrorCode.RESOURCE_NOT_FOUND);",
    "        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(response);",
    "    }",
    "",
    "    /**",
    "     * 그 외 모든 예외 (최후의 안전망)",
    "     */",
    "    @ExceptionHandler(Exception.class)",
    "    public ResponseEntity<ErrorResponse> handleException(Exception e) {",
    "        log.error(\"예상치 못한 서버 오류\", e);",
    "",
    "        ErrorResponse response = ErrorResponse.of(ErrorCode.INTERNAL_ERROR);",
    "        return ResponseEntity",
    "                .status(HttpStatus.INTERNAL_SERVER_ERROR)",
    "                .body(response);",
    "    }",
    "}",
    "```",
    "",
    "### 핸들러 실행 순서",
    "",
    "Spring은 **가장 구체적인 예외 타입**부터 매칭합니다.",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"예외 발생\"] --> B{\"UserNotFoundException?\"}",
    "    B -->|예| C[\"handleBusinessException<br/>(BusinessException의 하위)\"]",
    "    B -->|아니오| D{\"MethodArgumentNotValidException?\"}",
    "    D -->|예| E[\"handleValidation\"]",
    "    D -->|아니오| F{\"HttpMessageNotReadableException?\"}",
    "    F -->|예| G[\"handleMessageNotReadable\"]",
    "    F -->|아니오| H{\"기타 예외?\"}",
    "    H -->|예| I[\"handleException<br/>(최후의 안전망)\"]",
    "```",
    "",
    "> `UserNotFoundException`은 `BusinessException`의 하위 클래스이므로 `handleBusinessException`이 처리합니다. 별도의 핸들러를 만들 필요가 없습니다.",
    "",
    "---",
    "",
    "## 5단계: Service에서 예외 던지기",
    "",
    "```java",
    "@Service",
    "@RequiredArgsConstructor",
    "public class UserService {",
    "",
    "    private final UserRepository userRepository;",
    "",
    "    public UserResponse findById(Long id) {",
    "        User user = userRepository.findById(id)",
    "                .orElseThrow(() -> new UserNotFoundException(id));",
    "        return UserResponse.from(user);",
    "    }",
    "",
    "    public UserResponse create(CreateUserRequest request) {",
    "        if (userRepository.existsByEmail(request.getEmail())) {",
    "            throw new DuplicateEmailException(request.getEmail());",
    "        }",
    "        User user = User.builder()",
    "                .name(request.getName())",
    "                .email(request.getEmail())",
    "                .build();",
    "        return UserResponse.from(userRepository.save(user));",
    "    }",
    "}",
    "```",
    "",
    "### Controller는 깔끔하게 유지",
    "",
    "```java",
    "@RestController",
    "@RequestMapping(\"/api/users\")",
    "@RequiredArgsConstructor",
    "public class UserController {",
    "",
    "    private final UserService userService;",
    "",
    "    @GetMapping(\"/{id}\")",
    "    public ResponseEntity<UserResponse> getUser(@PathVariable Long id) {",
    "        return ResponseEntity.ok(userService.findById(id));",
    "    }",
    "",
    "    @PostMapping",
    "    public ResponseEntity<UserResponse> createUser(",
    "            @Valid @RequestBody CreateUserRequest request) {",
    "        return ResponseEntity.status(HttpStatus.CREATED)",
    "                .body(userService.create(request));",
    "    }",
    "}",
    "```",
    "",
    "> Controller에 try-catch가 전혀 없습니다. 예외가 발생하면 `GlobalExceptionHandler`가 자동으로 처리합니다.",
    "",
    "---",
    "",
    "## 에러 응답 예시 모음",
    "",
    "### 사용자 없음 (404)",
    "",
    "```",
    "GET /api/users/999",
    "```",
    "",
    "```json",
    "{",
    "  \"code\": \"USER_NOT_FOUND\",",
    "  \"message\": \"사용자를 찾을 수 없습니다 (ID: 999)\",",
    "  \"status\": 404,",
    "  \"timestamp\": \"2026-03-02T10:30:00\"",
    "}",
    "```",
    "",
    "### 이메일 중복 (400)",
    "",
    "```",
    "POST /api/users",
    "{ \"name\": \"홍길동\", \"email\": \"hong@example.com\" }",
    "```",
    "",
    "```json",
    "{",
    "  \"code\": \"DUPLICATE_EMAIL\",",
    "  \"message\": \"이미 사용 중인 이메일입니다: hong@example.com\",",
    "  \"status\": 400,",
    "  \"timestamp\": \"2026-03-02T10:30:00\"",
    "}",
    "```",
    "",
    "### Validation 에러 (400)",
    "",
    "```",
    "POST /api/users",
    "{ \"name\": \"\", \"email\": \"not-email\" }",
    "```",
    "",
    "```json",
    "{",
    "  \"code\": \"VALIDATION_ERROR\",",
    "  \"message\": \"요청 데이터 검증에 실패했습니다\",",
    "  \"status\": 400,",
    "  \"timestamp\": \"2026-03-02T10:30:00\",",
    "  \"errors\": {",
    "    \"name\": \"이름은 필수입니다\",",
    "    \"email\": \"올바른 이메일 형식이 아닙니다\"",
    "  }",
    "}",
    "```",
    "",
    "### JSON 파싱 실패 (400)",
    "",
    "```",
    "POST /api/users",
    "Body: { invalid json }",
    "```",
    "",
    "```json",
    "{",
    "  \"code\": \"INVALID_INPUT\",",
    "  \"message\": \"요청 본문을 읽을 수 없습니다. JSON 형식을 확인해주세요.\",",
    "  \"status\": 400,",
    "  \"timestamp\": \"2026-03-02T10:30:00\"",
    "}",
    "```",
    "",
    "### 타입 불일치 (400)",
    "",
    "```",
    "GET /api/users/abc",
    "```",
    "",
    "```json",
    "{",
    "  \"code\": \"INVALID_INPUT\",",
    "  \"message\": \"'id' 파라미터의 값 'abc'이(가) 올바르지 않습니다. Long 타입이어야 합니다.\",",
    "  \"status\": 400,",
    "  \"timestamp\": \"2026-03-02T10:30:00\"",
    "}",
    "```",
    "",
    "### 서버 내부 오류 (500)",
    "",
    "```json",
    "{",
    "  \"code\": \"INTERNAL_ERROR\",",
    "  \"message\": \"서버 내부 오류가 발생했습니다\",",
    "  \"status\": 500,",
    "  \"timestamp\": \"2026-03-02T10:30:00\"",
    "}",
    "```",
    "",
    "> 500 에러는 내부 메시지를 노출하지 않고 고정 메시지를 반환합니다. 상세 정보는 **서버 로그**에만 기록합니다.",
    "",
    "---",
    "",
    "## HTTP 상태 코드와 예외 매핑",
    "",
    "| 상태 코드 | 의미 | 사용 예 |",
    "|-----------|------|---------|",
    "| **400** Bad Request | 잘못된 요청 | Validation 실패, 잘못된 JSON, 중복 데이터 |",
    "| **401** Unauthorized | 인증 필요 | 로그인 안 함, 토큰 만료 |",
    "| **403** Forbidden | 권한 없음 | 관리자 페이지에 일반 사용자 접근 |",
    "| **404** Not Found | 리소스 없음 | 존재하지 않는 ID로 조회 |",
    "| **405** Method Not Allowed | 메서드 미지원 | GET만 있는데 POST 요청 |",
    "| **409** Conflict | 충돌 | 이미 존재하는 리소스 생성 시도 |",
    "| **500** Internal Server Error | 서버 오류 | 예상치 못한 에러 |",
    "",
    "---",
    "",
    "## 고급: Checked vs Unchecked 예외",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Throwable\"] --> B[\"Error<br/>(시스템 오류, 복구 불가)\"]",
    "    A --> C[\"Exception\"]",
    "    C --> D[\"Checked Exception<br/>(IOException, SQLException)\"]",
    "    C --> E[\"RuntimeException<br/>(Unchecked Exception)\"]",
    "    E --> F[\"NullPointerException\"]",
    "    E --> G[\"IllegalArgumentException\"]",
    "    E --> H[\"BusinessException (커스텀)\"]",
    "```",
    "",
    "| 구분 | Checked Exception | Unchecked Exception |",
    "|------|-------------------|---------------------|",
    "| 상속 | `Exception` | `RuntimeException` |",
    "| 컴파일 체크 | O (throws 필수) | X |",
    "| 트랜잭션 롤백 | 기본 X | **기본 O** |",
    "| Spring 권장 | 비추천 | **권장** |",
    "",
    "> Spring에서는 **RuntimeException(Unchecked)**을 사용하는 것이 권장됩니다. `@Transactional`이 Unchecked 예외에서만 기본 롤백을 수행하기 때문입니다.",
    "",
    "---",
    "",
    "## 고급: 특정 패키지/Controller만 처리하기",
    "",
    "```java",
    "// 특정 패키지의 Controller만 처리",
    "@RestControllerAdvice(basePackages = \"com.example.demo.controller.api\")",
    "public class ApiExceptionHandler { ... }",
    "",
    "// 특정 Controller만 처리",
    "@RestControllerAdvice(assignableTypes = {UserController.class, OrderController.class})",
    "public class UserOrderExceptionHandler { ... }",
    "",
    "// 특정 어노테이션이 붙은 Controller만 처리",
    "@RestControllerAdvice(annotations = RestController.class)",
    "public class RestApiExceptionHandler { ... }",
    "```",
    "",
    "> 대규모 프로젝트에서는 API용과 View용 예외 처리기를 분리할 수 있습니다.",
    "",
    "---",
    "",
    "## 고급: @ResponseStatus 어노테이션",
    "",
    "간단한 예외는 `@ResponseStatus`로 상태 코드를 지정할 수 있습니다.",
    "",
    "```java",
    "@ResponseStatus(HttpStatus.NOT_FOUND)",
    "public class ResourceNotFoundException extends RuntimeException {",
    "    public ResourceNotFoundException(String message) {",
    "        super(message);",
    "    }",
    "}",
    "```",
    "",
    "> `@ResponseStatus`를 붙이면 해당 예외가 발생할 때 자동으로 지정한 상태 코드가 반환됩니다. 단, 응답 형식을 세밀하게 제어하기 어려워 `@RestControllerAdvice` 방식이 더 권장됩니다.",
    "",
    "---",
    "",
    "## 고급: Spring의 기본 에러 처리 (/error)",
    "",
    "Spring Boot는 기본적으로 `BasicErrorController`가 `/error` 경로에서 에러를 처리합니다.",
    "",
    "### application.yml 설정",
    "",
    "```yaml",
    "server:",
    "  error:",
    "    include-message: always        # 에러 메시지 포함",
    "    include-binding-errors: always  # 바인딩 에러 포함",
    "    include-stacktrace: never       # 스택 트레이스 절대 포함 안 함",
    "    include-exception: false        # 예외 클래스명 포함 안 함",
    "```",
    "",
    "> `@RestControllerAdvice`를 사용하면 `BasicErrorController`보다 **먼저** 예외를 가로채므로, 직접 구현한 핸들러가 우선 동작합니다.",
    "",
    "---",
    "",
    "## 실전 패턴 모음",
    "",
    "### 패턴 1: Service에서 예외를 던지고, Handler에서 처리",
    "",
    "```java",
    "// Service",
    "public Order getOrder(Long id) {",
    "    return orderRepository.findById(id)",
    "            .orElseThrow(() -> new OrderNotFoundException(id));",
    "}",
    "",
    "// Controller (try-catch 없이 깔끔)",
    "@GetMapping(\"/orders/{id}\")",
    "public ResponseEntity<OrderResponse> getOrder(@PathVariable Long id) {",
    "    return ResponseEntity.ok(orderService.getOrder(id));",
    "}",
    "```",
    "",
    "### 패턴 2: 조건부 예외 던지기",
    "",
    "```java",
    "public void updateOrder(Long id, UpdateOrderRequest request) {",
    "    Order order = orderRepository.findById(id)",
    "            .orElseThrow(() -> new OrderNotFoundException(id));",
    "",
    "    if (order.getStatus() == OrderStatus.COMPLETED) {",
    "        throw new BusinessException(",
    "                ErrorCode.INVALID_INPUT, \"완료된 주문은 수정할 수 없습니다\");",
    "    }",
    "",
    "    if (!order.getUserId().equals(request.getUserId())) {",
    "        throw new BusinessException(",
    "                ErrorCode.ACCESS_DENIED, \"본인의 주문만 수정할 수 있습니다\");",
    "    }",
    "",
    "    order.update(request);",
    "}",
    "```",
    "",
    "### 패턴 3: 외부 API 호출 예외 래핑",
    "",
    "```java",
    "public WeatherData getWeather(String city) {",
    "    try {",
    "        return restTemplate.getForObject(weatherApiUrl + city, WeatherData.class);",
    "    } catch (RestClientException e) {",
    "        log.error(\"날씨 API 호출 실패: {}\", e.getMessage());",
    "        throw new BusinessException(",
    "                ErrorCode.INTERNAL_ERROR, \"외부 서비스 호출에 실패했습니다\");",
    "    }",
    "}",
    "```",
    "",
    "> 외부 API의 예외를 그대로 노출하지 않고, **우리 시스템의 예외로 래핑**하여 일관된 에러 응답을 유지합니다.",
    "",
    "---",
    "",
    "## 전체 흐름 정리",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant CT as Controller",
    "    participant SV as Service",
    "    participant GH as GlobalExceptionHandler",
    "",
    "    Note over C,GH: 정상 흐름",
    "    C->>CT: GET /api/users/1",
    "    CT->>SV: findById(1)",
    "    SV-->>CT: UserResponse",
    "    CT-->>C: 200 OK + UserResponse",
    "",
    "    Note over C,GH: 예외 흐름",
    "    C->>CT: GET /api/users/999",
    "    CT->>SV: findById(999)",
    "    SV->>GH: throw UserNotFoundException(999)",
    "    GH-->>C: 404 + ErrorResponse",
    "",
    "    Note over C,GH: Validation 에러 흐름",
    "    C->>CT: POST /api/users {name:'', email:'bad'}",
    "    CT->>GH: MethodArgumentNotValidException",
    "    GH-->>C: 400 + ErrorResponse (errors 포함)",
    "```",
    "",
    "---",
    "",
    "## 주의사항",
    "",
    "### 1. 500 에러에 내부 정보 노출 금지",
    "",
    "```java",
    "// X: 내부 에러 메시지 노출",
    "@ExceptionHandler(Exception.class)",
    "public ResponseEntity<Map<String, String>> handle(Exception e) {",
    "    return ResponseEntity.status(500)",
    "            .body(Map.of(\"message\", e.getMessage())); // NullPointerException at line 42...",
    "}",
    "",
    "// O: 고정 메시지, 상세는 로그에만",
    "@ExceptionHandler(Exception.class)",
    "public ResponseEntity<ErrorResponse> handle(Exception e) {",
    "    log.error(\"예상치 못한 서버 오류\", e);",
    "    return ResponseEntity.status(500)",
    "            .body(ErrorResponse.of(ErrorCode.INTERNAL_ERROR));",
    "}",
    "```",
    "",
    "### 2. 로깅 레벨 구분",
    "",
    "```java",
    "// 비즈니스 예외 (예측 가능) → warn",
    "log.warn(\"비즈니스 예외: {}\", e.getMessage());",
    "",
    "// 서버 오류 (예측 불가) → error + 스택 트레이스",
    "log.error(\"예상치 못한 서버 오류\", e);",
    "```",
    "",
    "### 3. @Transactional과 예외",
    "",
    "```java",
    "// RuntimeException → 자동 롤백",
    "@Transactional",
    "public void process() {",
    "    userRepository.save(user);",
    "    throw new BusinessException(ErrorCode.INTERNAL_ERROR); // 롤백됨",
    "}",
    "",
    "// Checked Exception → 롤백 안 됨 (명시적 설정 필요)",
    "@Transactional(rollbackFor = IOException.class)",
    "public void process() throws IOException {",
    "    userRepository.save(user);",
    "    throw new IOException(\"파일 오류\"); // rollbackFor 덕분에 롤백됨",
    "}",
    "```",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 구성 요소 | 역할 | 핵심 코드 |",
    "|-----------|------|-----------|",
    "| `ErrorCode` (Enum) | 에러 코드/메시지/상태 중앙 관리 | `USER_NOT_FOUND(404, ...)` |",
    "| `ErrorResponse` (DTO) | 통일된 에러 응답 형식 | `code`, `message`, `status`, `errors` |",
    "| `BusinessException` | 비즈니스 예외 베이스 클래스 | `extends RuntimeException` |",
    "| 구체적 예외 클래스 | 개별 예외 | `extends BusinessException` |",
    "| `GlobalExceptionHandler` | 전역 예외 처리기 | `@RestControllerAdvice` |",
    "",
    "| 상황 | 처리 방법 |",
    "|------|----------|",
    "| 리소스 없음 (404) | 커스텀 예외 throw → `handleBusinessException` |",
    "| 입력 검증 실패 (400) | `@Valid` → `handleValidation` |",
    "| 중복 데이터 (400/409) | 커스텀 예외 throw |",
    "| JSON 파싱 실패 (400) | `handleMessageNotReadable` |",
    "| 파라미터 타입 오류 (400) | `handleTypeMismatch` |",
    "| 서버 내부 오류 (500) | `handleException` (안전망) |",
    "",
    "| 핵심 원칙 | 설명 |",
    "|-----------|------|",
    "| **Controller는 깔끔하게** | try-catch 없이, 예외는 throw로 |",
    "| **응답 형식 통일** | 모든 에러가 같은 `ErrorResponse` 구조 |",
    "| **에러 코드 중앙 관리** | `ErrorCode` Enum 사용 |",
    "| **상세 정보는 로그에만** | 500 에러는 클라이언트에 내부 정보 노출 금지 |",
    "| **RuntimeException 사용** | Checked Exception 대신 Unchecked 사용 |"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
