<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-monitoring",
  title: "Spring Boot 모니터링 심화 - Prometheus, Grafana, 알림 설정까지",
  date: "2026-02-02",
  summary: "Spring Boot Actuator + Micrometer + Prometheus + Grafana를 연동하여 애플리케이션 메트릭 수집, 대시보드 구축, 알림 설정까지 실전 모니터링 파이프라인을 구축하는 방법을 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","monitoring","prometheus","grafana","micrometer","actuator","devops","backend"],
  content: [
    "## 모니터링이란?",
    "",
    "**모니터링**은 애플리케이션의 **상태, 성능, 동작을 지속적으로 관찰하고 기록**하는 것입니다. 장애를 사전에 감지하고, 성능 병목을 파악하며, 서비스 품질을 유지하기 위한 필수 활동입니다.",
    "",
    "### 왜 모니터링이 필요한가?",
    "",
    "- **장애 감지**: 서버 다운, 메모리 부족, 응답 지연 등을 **즉시** 파악",
    "- **성능 최적화**: 느린 API, 높은 CPU 사용률 등 **병목 지점** 식별",
    "- **용량 계획**: 트래픽 추세를 분석하여 **서버 증설 시점** 판단",
    "- **SLA 관리**: 서비스 수준 협약(99.9% 가용성 등)의 **준수 여부** 확인",
    "- **사후 분석**: 장애 발생 시 **원인 분석**을 위한 데이터 확보",
    "",
    "### Observability 3 Pillars (관측 가능성의 3축)",
    "",
    "| 구분 | 메트릭 (Metrics) | 로그 (Logs) | 트레이싱 (Traces) |",
    "|------|-----------------|-------------|------------------|",
    "| 정의 | 수치 데이터 (숫자) | 이벤트 기록 (텍스트) | 요청 흐름 추적 |",
    "| 예시 | CPU 80%, 응답시간 200ms | \"주문 생성 성공\", 에러 스택트레이스 | A서비스 → B서비스 → DB 호출 경로 |",
    "| 도구 | Prometheus, Micrometer | ELK Stack, Loki | Zipkin, Jaeger |",
    "| 특징 | 집계/통계에 강함 | 상세 컨텍스트 제공 | 분산 시스템 디버깅 |",
    "| 저장 비용 | 낮음 | 높음 | 중간 |",
    "| 쿼리 속도 | 빠름 | 중간 | 중간 |",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"Observability<br/>(관측 가능성)\"] --> B[\"Metrics<br/>메트릭\"]",
    "    A --> C[\"Logs<br/>로그\"]",
    "    A --> D[\"Traces<br/>트레이싱\"]",
    "",
    "    B --> E[\"Prometheus<br/>Micrometer\"]",
    "    C --> F[\"ELK Stack<br/>Loki\"]",
    "    D --> G[\"Zipkin<br/>Jaeger\"]",
    "",
    "    E --> H[\"Grafana<br/>(시각화)\"]",
    "    F --> H",
    "    G --> H",
    "",
    "    style A fill:#9C27B0,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "    style C fill:#4CAF50,color:#fff",
    "    style D fill:#FF9800,color:#fff",
    "    style H fill:#E91E63,color:#fff",
    "```",
    "",
    "이 글에서는 **메트릭(Metrics)** 기반 모니터링에 집중하여 Prometheus + Grafana를 다룹니다.",
    "",
    "---",
    "",
    "## 전체 아키텍처",
    "",
    "Spring Boot 모니터링의 전체 데이터 흐름입니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Spring Boot<br/>애플리케이션\"] --> B[\"Actuator<br/>(엔드포인트 노출)\"]",
    "    B --> C[\"Micrometer<br/>(메트릭 수집/변환)\"]",
    "    C --> D[\"/actuator/prometheus<br/>(Prometheus 포맷)\"]",
    "    D -->|HTTP Pull| E[\"Prometheus<br/>(저장/쿼리)\"]",
    "    E -->|PromQL| F[\"Grafana<br/>(시각화/알림)\"]",
    "",
    "    F --> G[\"Slack 알림\"]",
    "    F --> H[\"Email 알림\"]",
    "    F --> I[\"Discord 알림\"]",
    "",
    "    style A fill:#4CAF50,color:#fff",
    "    style C fill:#2196F3,color:#fff",
    "    style E fill:#FF9800,color:#fff",
    "    style F fill:#E91E63,color:#fff",
    "```",
    "",
    "### 각 컴포넌트 역할",
    "",
    "| 컴포넌트 | 역할 | 비유 |",
    "|----------|------|------|",
    "| **Spring Boot Actuator** | 애플리케이션 내부 상태를 HTTP 엔드포인트로 노출 | 자동차 계기판 센서 |",
    "| **Micrometer** | 메트릭을 수집하고 다양한 포맷으로 변환 | 범용 어댑터 |",
    "| **Prometheus** | 메트릭을 주기적으로 수집(Pull)하고 시계열 DB에 저장 | 데이터 수집기 + 저장소 |",
    "| **Grafana** | 저장된 메트릭을 시각화하고 알림 규칙 설정 | 대시보드 + 경보 시스템 |",
    "",
    "---",
    "",
    "## 프로젝트 설정 (IntelliJ 실습)",
    "",
    "직접 따라 하면서 Spring Boot 모니터링 환경을 구축해 봅시다.",
    "",
    "### 1단계: 인텔리제이 프로젝트 만들기",
    "",
    "1. IntelliJ IDEA → **New Project** → **Spring Initializr** 선택",
    "2. 아래와 같이 설정:",
    "",
    "| 항목 | 값 |",
    "|------|-----|",
    "| **Name** | `springboot_monitoring_example` |",
    "| **Language** | Java |",
    "| **Type** | Gradle - Groovy |",
    "| **JDK** | 21 |",
    "| **Packaging** | Jar |",
    "",
    "3. Dependencies에서 다음을 추가:",
    "   - **Lombok**",
    "   - **Spring Web**",
    "   - **Spring Boot Actuator**",
    "4. **Create** 클릭",
    "",
    "### 2단계: build.gradle",
    "",
    "Spring Initializr가 생성한 `build.gradle`에 `micrometer-registry-prometheus` 의존성을 추가합니다.",
    "",
    "```groovy",
    "plugins {",
    "    id 'java'",
    "    id 'org.springframework.boot' version '3.4.3'",
    "    id 'io.spring.dependency-management' version '1.1.7'",
    "}",
    "",
    "group = 'com.example'",
    "version = '0.0.1-SNAPSHOT'",
    "",
    "java {",
    "    toolchain {",
    "        languageVersion = JavaLanguageVersion.of(21)",
    "    }",
    "}",
    "",
    "configurations {",
    "    compileOnly {",
    "        extendsFrom annotationProcessor",
    "    }",
    "}",
    "",
    "repositories {",
    "    mavenCentral()",
    "}",
    "",
    "dependencies {",
    "    implementation 'org.springframework.boot:spring-boot-starter-web'",
    "    implementation 'org.springframework.boot:spring-boot-starter-actuator'",
    "    implementation 'io.micrometer:micrometer-registry-prometheus'",
    "    compileOnly 'org.projectlombok:lombok'",
    "    annotationProcessor 'org.projectlombok:lombok'",
    "    testImplementation 'org.springframework.boot:spring-boot-starter-test'",
    "    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'",
    "}",
    "",
    "tasks.named('test') {",
    "    useJUnitPlatform()",
    "}",
    "```",
    "",
    "### 3단계: application.yml",
    "",
    "`src/main/resources/application.yml`을 작성합니다. (기존 `application.properties`는 삭제)",
    "",
    "```yaml",
    "spring:",
    "  application:",
    "    name: springboot-monitoring-example",
    "",
    "management:",
    "  endpoints:",
    "    web:",
    "      exposure:",
    "        include: health,info,prometheus",
    "  endpoint:",
    "    health:",
    "      show-details: always",
    "```",
    "",
    "- `management.endpoints.web.exposure.include`로 노출할 Actuator 엔드포인트를 지정합니다.",
    "- `micrometer-registry-prometheus` 의존성이 있으면 `/actuator/prometheus` 엔드포인트가 자동 생성됩니다.",
    "",
    "### 4단계: 애플리케이션 코드",
    "",
    "#### DemoApplication.java",
    "",
    "```java",
    "package com.example.springboot_monitoring_example;",
    "",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "",
    "@SpringBootApplication",
    "public class DemoApplication {",
    "",
    "    public static void main(String[] args) {",
    "        SpringApplication.run(DemoApplication.class, args);",
    "    }",
    "}",
    "```",
    "",
    "#### HelloController.java",
    "",
    "메트릭을 발생시킬 간단한 API를 만듭니다.",
    "",
    "```java",
    "package com.example.springboot_monitoring_example;",
    "",
    "import lombok.RequiredArgsConstructor;",
    "import io.micrometer.core.instrument.Counter;",
    "import io.micrometer.core.instrument.MeterRegistry;",
    "import jakarta.annotation.PostConstruct;",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.RestController;",
    "",
    "@RestController",
    "@RequiredArgsConstructor",
    "public class HelloController {",
    "",
    "    private final MeterRegistry meterRegistry;",
    "    private Counter helloCounter;",
    "",
    "    @PostConstruct",
    "    public void init() {",
    "        helloCounter = Counter.builder(\"hello.api.count\")",
    "                .description(\"Hello API 호출 횟수\")",
    "                .register(meterRegistry);",
    "    }",
    "",
    "    @GetMapping(\"/hello\")",
    "    public String hello() {",
    "        helloCounter.increment();",
    "        return \"Hello, Monitoring!\";",
    "    }",
    "}",
    "```",
    "",
    "- `/hello`를 호출할 때마다 `hello.api.count` 커스텀 메트릭이 1씩 증가합니다.",
    "- 이 메트릭은 `/actuator/prometheus`에서 확인할 수 있습니다.",
    "",
    "### 5단계: Docker Compose (Prometheus + Grafana)",
    "",
    "프로젝트 루트에 `docker-compose.yml`을 생성합니다.",
    "",
    "```yaml",
    "version: '3.8'",
    "services:",
    "  prometheus:",
    "    image: prom/prometheus",
    "    ports:",
    "      - \"9090:9090\"",
    "    volumes:",
    "      - ./prometheus.yml:/etc/prometheus/prometheus.yml",
    "  grafana:",
    "    image: grafana/grafana",
    "    ports:",
    "      - \"3000:3000\"",
    "    environment:",
    "      GF_SECURITY_ADMIN_PASSWORD: admin",
    "```",
    "",
    "같은 위치에 `prometheus.yml`도 생성합니다.",
    "",
    "```yaml",
    "global:",
    "  scrape_interval: 15s",
    "scrape_configs:",
    "  - job_name: 'spring-boot'",
    "    metrics_path: '/actuator/prometheus'",
    "    static_configs:",
    "      - targets: ['host.docker.internal:8080']",
    "```",
    "",
    "- `host.docker.internal`은 Docker 컨테이너에서 **호스트 PC의 localhost**에 접근하기 위한 주소입니다.",
    "- Spring Boot는 호스트에서 직접 실행하고, Prometheus/Grafana만 Docker로 띄우는 구조입니다.",
    "",
    "### 6단계: 실행 순서",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"1. Spring Boot<br/>실행\"] --> B[\"2. docker-compose<br/>up -d\"]",
    "    B --> C[\"3. Prometheus<br/>확인\"]",
    "    C --> D[\"4. Grafana<br/>접속\"]",
    "    D --> E[\"5. Data Source<br/>추가\"]",
    "    E --> F[\"6. Dashboard<br/>Import\"]",
    "",
    "    style A fill:#4CAF50,color:#fff",
    "    style B fill:#2196F3,color:#fff",
    "    style C fill:#FF9800,color:#fff",
    "    style D fill:#E91E63,color:#fff",
    "```",
    "",
    "**① Spring Boot 실행**",
    "",
    "IntelliJ에서 `DemoApplication`을 Run 합니다. http://localhost:8080/hello 로 정상 동작을 확인합니다.",
    "",
    "**② Docker Compose 실행**",
    "",
    "```bash",
    "docker-compose up -d",
    "```",
    "",
    "**③ Prometheus 확인**",
    "",
    "http://localhost:9090 에 접속 → **Status → Targets** 에서 `spring-boot` 타겟이 **UP** 상태인지 확인합니다.",
    "",
    "**④ Grafana 접속**",
    "",
    "http://localhost:3000 에 접속합니다. (ID: `admin` / PW: `admin`)",
    "",
    "**⑤ Prometheus Data Source 추가**",
    "",
    "1. 좌측 메뉴 → **Connections → Data Sources → Add data source**",
    "2. **Prometheus** 선택",
    "3. URL에 `http://prometheus:9090` 입력 (같은 Docker 네트워크이므로 서비스명 사용)",
    "4. **Save & Test** → \"Successfully queried\" 확인",
    "",
    "**⑥ Dashboard Import**",
    "",
    "1. 좌측 메뉴 → **Dashboards → Import**",
    "2. Dashboard ID: `4701` 입력 → **Load**",
    "3. Data Source: **Prometheus** 선택 → **Import**",
    "4. JVM 메트릭(CPU, 메모리, GC, 스레드 등)이 시각화된 대시보드를 확인합니다.",
    "",
    "> **Tip**: http://localhost:8080/hello 를 여러 번 호출한 뒤, Prometheus에서 `hello_api_count_total`을 검색하면 커스텀 메트릭이 수집되는 것을 확인할 수 있습니다.",
    "",
    "### 프로젝트 디렉토리 구조",
    "",
    "```",
    "springboot_monitoring_example/",
    "├── src/main/java/com/example/springboot_monitoring_example/",
    "│   ├── DemoApplication.java",
    "│   └── HelloController.java",
    "├── src/main/resources/",
    "│   └── application.yml",
    "├── build.gradle",
    "├── docker-compose.yml",
    "└── prometheus.yml",
    "```",
    "",
    "### 의존성 구조",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"spring-boot-starter-actuator\"] --> B[\"micrometer-core\"]",
    "    C[\"micrometer-registry-prometheus\"] --> B",
    "    C --> D[\"Prometheus 포맷<br/>변환 기능\"]",
    "",
    "    A --> E[\"/actuator/* 엔드포인트\"]",
    "    B --> F[\"Counter, Gauge,<br/>Timer 등 메트릭 API\"]",
    "",
    "    style A fill:#4CAF50,color:#fff",
    "    style C fill:#FF9800,color:#fff",
    "```",
    "",
    "- `spring-boot-starter-actuator`에 `micrometer-core`가 자동 포함",
    "- `micrometer-registry-prometheus`를 추가하면 `/actuator/prometheus` 엔드포인트가 자동 생성",
    "",
    "---",
    "",
    "## Actuator 엔드포인트",
    "",
    "### 주요 엔드포인트",
    "",
    "| 엔드포인트 | 경로 | 설명 |",
    "|-----------|------|------|",
    "| **health** | `/actuator/health` | 애플리케이션 상태 (UP/DOWN) |",
    "| **info** | `/actuator/info` | 애플리케이션 정보 |",
    "| **metrics** | `/actuator/metrics` | 사용 가능한 메트릭 목록 |",
    "| **prometheus** | `/actuator/prometheus` | Prometheus 수집용 메트릭 |",
    "| **env** | `/actuator/env` | 환경 변수 |",
    "| **loggers** | `/actuator/loggers` | 로거 설정 (런타임 변경 가능) |",
    "| **httptrace** | `/actuator/httptrace` | 최근 HTTP 요청 추적 |",
    "",
    "### /actuator/health 응답 예시",
    "",
    "```json",
    "{",
    "  \"status\": \"UP\",",
    "  \"components\": {",
    "    \"db\": {",
    "      \"status\": \"UP\",",
    "      \"details\": {",
    "        \"database\": \"MySQL\",",
    "        \"validationQuery\": \"isValid()\"",
    "      }",
    "    },",
    "    \"diskSpace\": {",
    "      \"status\": \"UP\",",
    "      \"details\": {",
    "        \"total\": 107374182400,",
    "        \"free\": 53687091200,",
    "        \"threshold\": 10485760",
    "      }",
    "    },",
    "    \"ping\": {",
    "      \"status\": \"UP\"",
    "    }",
    "  }",
    "}",
    "```",
    "",
    "### /actuator/prometheus 응답 예시",
    "",
    "```",
    "# HELP jvm_memory_used_bytes The amount of used memory",
    "# TYPE jvm_memory_used_bytes gauge",
    "jvm_memory_used_bytes{area=\"heap\",id=\"G1 Eden Space\"} 2.5165824E7",
    "jvm_memory_used_bytes{area=\"heap\",id=\"G1 Old Gen\"} 1.2582912E7",
    "jvm_memory_used_bytes{area=\"nonheap\",id=\"Metaspace\"} 6.291456E7",
    "",
    "# HELP http_server_requests_seconds",
    "# TYPE http_server_requests_seconds histogram",
    "http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/orders\",le=\"0.05\"} 150",
    "http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/orders\",le=\"0.1\"} 200",
    "http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/orders\",le=\"+Inf\"} 210",
    "http_server_requests_seconds_count{method=\"GET\",uri=\"/api/orders\"} 210",
    "http_server_requests_seconds_sum{method=\"GET\",uri=\"/api/orders\"} 8.45",
    "```",
    "",
    "이 텍스트 포맷을 Prometheus가 주기적으로 HTTP로 가져가서(Pull) 시계열 DB에 저장합니다.",
    "",
    "---",
    "",
    "## 커스텀 메트릭",
    "",
    "기본 제공 메트릭 외에 **비즈니스 메트릭**을 직접 정의할 수 있습니다.",
    "",
    "### 메트릭 타입",
    "",
    "| 타입 | 설명 | 예시 |",
    "|------|------|------|",
    "| **Counter** | 증가만 가능한 수치 | 주문 수, 에러 발생 횟수 |",
    "| **Gauge** | 증가/감소 가능한 현재 값 | 현재 접속자 수, 큐 크기 |",
    "| **Timer** | 시간 측정 (횟수 + 총 시간) | API 응답 시간, 처리 시간 |",
    "| **DistributionSummary** | 값의 분포 측정 | 요청 크기, 결제 금액 분포 |",
    "",
    "### Counter 예제 - 주문 수 카운팅",
    "",
    "```java",
    "import io.micrometer.core.instrument.Counter;",
    "import io.micrometer.core.instrument.MeterRegistry;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Service",
    "public class OrderService {",
    "",
    "    private final Counter orderCounter;",
    "    private final Counter orderFailCounter;",
    "",
    "    public OrderService(MeterRegistry registry) {",
    "        this.orderCounter = Counter.builder(\"orders.created\")",
    "                .description(\"생성된 주문 수\")",
    "                .tag(\"type\", \"total\")",
    "                .register(registry);",
    "",
    "        this.orderFailCounter = Counter.builder(\"orders.failed\")",
    "                .description(\"실패한 주문 수\")",
    "                .tag(\"type\", \"failed\")",
    "                .register(registry);",
    "    }",
    "",
    "    public Order createOrder(OrderRequest request) {",
    "        try {",
    "            Order order = processOrder(request);",
    "            orderCounter.increment();",
    "            return order;",
    "        } catch (Exception e) {",
    "            orderFailCounter.increment();",
    "            throw e;",
    "        }",
    "    }",
    "}",
    "```",
    "",
    "### Gauge 예제 - 현재 활성 사용자 수",
    "",
    "```java",
    "import io.micrometer.core.instrument.Gauge;",
    "import io.micrometer.core.instrument.MeterRegistry;",
    "import org.springframework.stereotype.Component;",
    "",
    "import java.util.concurrent.atomic.AtomicInteger;",
    "",
    "@Component",
    "public class ActiveUserTracker {",
    "",
    "    private final AtomicInteger activeUsers = new AtomicInteger(0);",
    "",
    "    public ActiveUserTracker(MeterRegistry registry) {",
    "        Gauge.builder(\"users.active\", activeUsers, AtomicInteger::get)",
    "                .description(\"현재 활성 사용자 수\")",
    "                .register(registry);",
    "    }",
    "",
    "    public void userConnected() {",
    "        activeUsers.incrementAndGet();",
    "    }",
    "",
    "    public void userDisconnected() {",
    "        activeUsers.decrementAndGet();",
    "    }",
    "}",
    "```",
    "",
    "### Timer 예제 - API 응답 시간 측정",
    "",
    "```java",
    "import io.micrometer.core.instrument.MeterRegistry;",
    "import io.micrometer.core.instrument.Timer;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Service",
    "public class PaymentService {",
    "",
    "    private final Timer paymentTimer;",
    "",
    "    public PaymentService(MeterRegistry registry) {",
    "        this.paymentTimer = Timer.builder(\"payment.process.time\")",
    "                .description(\"결제 처리 시간\")",
    "                .publishPercentiles(0.5, 0.95, 0.99)",
    "                .register(registry);",
    "    }",
    "",
    "    public PaymentResult processPayment(PaymentRequest request) {",
    "        return paymentTimer.record(() -> {",
    "            // 실제 결제 처리 로직",
    "            return callPaymentGateway(request);",
    "        });",
    "    }",
    "}",
    "```",
    "",
    "### DistributionSummary 예제 - 결제 금액 분포",
    "",
    "```java",
    "import io.micrometer.core.instrument.DistributionSummary;",
    "import io.micrometer.core.instrument.MeterRegistry;",
    "import org.springframework.stereotype.Service;",
    "",
    "@Service",
    "public class AnalyticsService {",
    "",
    "    private final DistributionSummary orderAmountSummary;",
    "",
    "    public AnalyticsService(MeterRegistry registry) {",
    "        this.orderAmountSummary = DistributionSummary",
    "                .builder(\"order.amount\")",
    "                .description(\"주문 금액 분포\")",
    "                .baseUnit(\"won\")",
    "                .publishPercentiles(0.5, 0.75, 0.95)",
    "                .register(registry);",
    "    }",
    "",
    "    public void recordOrderAmount(long amount) {",
    "        orderAmountSummary.record(amount);",
    "    }",
    "}",
    "```",
    "",
    "### @Timed 어노테이션 활용",
    "",
    "```java",
    "import io.micrometer.core.annotation.Timed;",
    "import org.springframework.web.bind.annotation.*;",
    "",
    "@RestController",
    "@RequestMapping(\"/api/orders\")",
    "public class OrderController {",
    "",
    "    @Timed(value = \"api.orders.list\", description = \"주문 목록 조회 시간\")",
    "    @GetMapping",
    "    public List<Order> getOrders() {",
    "        return orderService.findAll();",
    "    }",
    "",
    "    @Timed(value = \"api.orders.create\", description = \"주문 생성 시간\")",
    "    @PostMapping",
    "    public Order createOrder(@RequestBody OrderRequest request) {",
    "        return orderService.createOrder(request);",
    "    }",
    "}",
    "```",
    "",
    "> **참고**: `@Timed` 사용 시 `TimedAspect` Bean 등록이 필요합니다.",
    "",
    "```java",
    "import io.micrometer.core.aop.TimedAspect;",
    "import io.micrometer.core.instrument.MeterRegistry;",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "",
    "@Configuration",
    "public class MetricsConfig {",
    "",
    "    @Bean",
    "    public TimedAspect timedAspect(MeterRegistry registry) {",
    "        return new TimedAspect(registry);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Prometheus 설정",
    "",
    "### Docker로 Prometheus 실행",
    "",
    "```yaml",
    "# docker-compose-prometheus.yml",
    "version: '3.8'",
    "",
    "services:",
    "  prometheus:",
    "    image: prom/prometheus:latest",
    "    container_name: prometheus",
    "    ports:",
    "      - \"9090:9090\"",
    "    volumes:",
    "      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml",
    "      - prometheus_data:/prometheus",
    "    command:",
    "      - '--config.file=/etc/prometheus/prometheus.yml'",
    "      - '--storage.tsdb.retention.time=15d'",
    "      - '--web.enable-lifecycle'",
    "    restart: unless-stopped",
    "",
    "volumes:",
    "  prometheus_data:",
    "```",
    "",
    "### prometheus.yml 설정",
    "",
    "```yaml",
    "# prometheus/prometheus.yml",
    "global:",
    "  scrape_interval: 15s      # 메트릭 수집 주기",
    "  evaluation_interval: 15s  # 알림 규칙 평가 주기",
    "",
    "scrape_configs:",
    "  # Prometheus 자체 메트릭",
    "  - job_name: 'prometheus'",
    "    static_configs:",
    "      - targets: ['localhost:9090']",
    "",
    "  # Spring Boot 애플리케이션",
    "  - job_name: 'spring-boot-app'",
    "    metrics_path: '/actuator/prometheus'",
    "    scrape_interval: 10s",
    "    static_configs:",
    "      - targets: ['host.docker.internal:8080']  # Docker에서 호스트 접근",
    "        labels:",
    "          application: 'my-spring-app'",
    "          environment: 'local'",
    "",
    "  # 여러 인스턴스 모니터링",
    "  - job_name: 'spring-boot-prod'",
    "    metrics_path: '/actuator/prometheus'",
    "    scrape_interval: 10s",
    "    static_configs:",
    "      - targets:",
    "          - '192.168.1.10:8080'",
    "          - '192.168.1.11:8080'",
    "          - '192.168.1.12:8080'",
    "        labels:",
    "          application: 'my-spring-app'",
    "          environment: 'production'",
    "```",
    "",
    "### Prometheus 동작 방식",
    "",
    "```mermaid",
    "flowchart LR",
    "    subgraph TARGETS[\"수집 대상\"]",
    "        A[\"Spring Boot :8080\"]",
    "        B[\"Spring Boot :8081\"]",
    "        C[\"Spring Boot :8082\"]",
    "    end",
    "",
    "    D[\"Prometheus\"] -->|\"HTTP GET /actuator/prometheus<br/>매 15초\"| A",
    "    D -->|\"HTTP GET\"| B",
    "    D -->|\"HTTP GET\"| C",
    "",
    "    D --> E[\"시계열 DB<br/>(TSDB)\"]",
    "    E --> F[\"PromQL<br/>쿼리 엔진\"]",
    "",
    "    style D fill:#FF9800,color:#fff",
    "    style E fill:#795548,color:#fff",
    "```",
    "",
    "- **Pull 방식**: Prometheus가 타겟에 **주기적으로** HTTP 요청을 보내 메트릭을 수집",
    "- 수집된 메트릭은 **시계열 데이터베이스(TSDB)**에 저장",
    "- **PromQL**로 저장된 메트릭을 쿼리하여 분석",
    "",
    "---",
    "",
    "## PromQL 기본",
    "",
    "**PromQL**(Prometheus Query Language)은 시계열 데이터를 쿼리하는 언어입니다.",
    "",
    "### 기본 문법",
    "",
    "```",
    "# 특정 메트릭 조회",
    "http_server_requests_seconds_count",
    "",
    "# 레이블 필터링",
    "http_server_requests_seconds_count{method=\"GET\", uri=\"/api/orders\"}",
    "",
    "# 정규식 필터링",
    "http_server_requests_seconds_count{uri=~\"/api/.*\"}",
    "",
    "# 제외 필터",
    "http_server_requests_seconds_count{status!=\"200\"}",
    "```",
    "",
    "### 주요 함수",
    "",
    "| 함수 | 설명 | 예시 |",
    "|------|------|------|",
    "| `rate()` | 초당 평균 증가율 | `rate(http_server_requests_seconds_count[5m])` |",
    "| `increase()` | 지정 기간 동안 총 증가량 | `increase(orders_created_total[1h])` |",
    "| `sum()` | 합계 | `sum(rate(http_server_requests_seconds_count[5m]))` |",
    "| `avg()` | 평균 | `avg(jvm_memory_used_bytes)` |",
    "| `max()` / `min()` | 최대/최소 | `max(jvm_threads_live_threads)` |",
    "| `histogram_quantile()` | 히스토그램에서 퍼센타일 | `histogram_quantile(0.95, ...)` |",
    "| `topk()` | 상위 N개 | `topk(5, rate(http_server_requests_seconds_count[5m]))` |",
    "",
    "### 자주 쓰는 PromQL 쿼리",
    "",
    "| 목적 | PromQL |",
    "|------|--------|",
    "| 초당 요청 수 (RPS) | `sum(rate(http_server_requests_seconds_count[5m]))` |",
    "| 95번째 백분위 응답 시간 | `histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))` |",
    "| 에러율 (5xx) | `sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100` |",
    "| JVM 힙 메모리 사용률 | `jvm_memory_used_bytes{area=\"heap\"} / jvm_memory_max_bytes{area=\"heap\"} * 100` |",
    "| GC 횟수 (분당) | `rate(jvm_gc_pause_seconds_count[5m]) * 60` |",
    "| 활성 스레드 수 | `jvm_threads_live_threads` |",
    "| 1시간 동안 주문 수 | `increase(orders_created_total[1h])` |",
    "| CPU 사용률 | `system_cpu_usage * 100` |",
    "",
    "---",
    "",
    "## Grafana 설정",
    "",
    "### Docker로 Grafana 실행",
    "",
    "```yaml",
    "# docker-compose-grafana.yml",
    "version: '3.8'",
    "",
    "services:",
    "  grafana:",
    "    image: grafana/grafana:latest",
    "    container_name: grafana",
    "    ports:",
    "      - \"3000:3000\"",
    "    environment:",
    "      - GF_SECURITY_ADMIN_USER=admin",
    "      - GF_SECURITY_ADMIN_PASSWORD=admin123",
    "      - GF_USERS_ALLOW_SIGN_UP=false",
    "    volumes:",
    "      - grafana_data:/var/lib/grafana",
    "    restart: unless-stopped",
    "",
    "volumes:",
    "  grafana_data:",
    "```",
    "",
    "### 데이터 소스 추가 (Prometheus)",
    "",
    "1. Grafana 접속: `http://localhost:3000` (기본: admin/admin123)",
    "2. **Configuration → Data Sources → Add data source**",
    "3. **Prometheus** 선택",
    "4. URL: `http://prometheus:9090` (Docker 네트워크 사용 시) 또는 `http://host.docker.internal:9090`",
    "5. **Save & Test** 클릭",
    "",
    "### 대시보드 생성 방법",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"Grafana 접속\"] --> B[\"Data Source<br/>추가\"]",
    "    B --> C[\"대시보드<br/>생성/Import\"]",
    "    C --> D[\"패널 추가<br/>(PromQL 쿼리)\"]",
    "    D --> E[\"시각화 설정<br/>(그래프, 게이지 등)\"]",
    "    E --> F[\"알림 규칙<br/>설정\"]",
    "",
    "    style A fill:#E91E63,color:#fff",
    "```",
    "",
    "---",
    "",
    "## JVM 대시보드 (미리 만들어진 대시보드 Import)",
    "",
    "Grafana에서는 커뮤니티가 만든 **대시보드를 ID로 Import**할 수 있습니다.",
    "",
    "### Import 방법",
    "",
    "1. Grafana → **Dashboards → Import**",
    "2. **Dashboard ID 입력**: `4701` (JVM Micrometer 대시보드)",
    "3. **Load** 클릭",
    "4. Data Source로 **Prometheus** 선택",
    "5. **Import** 클릭",
    "",
    "### 추천 대시보드 ID",
    "",
    "| 대시보드 ID | 이름 | 내용 |",
    "|------------|------|------|",
    "| **4701** | JVM (Micrometer) | CPU, 메모리, GC, 스레드, 클래스 로더 |",
    "| **11378** | Spring Boot Statistics | HTTP 요청, 에러율, 응답 시간 |",
    "| **6756** | Spring Boot 2.1 | Actuator 전체 메트릭 |",
    "| **12900** | Spring Boot APM | 성능 모니터링 종합 |",
    "",
    "### 4701 대시보드 주요 패널",
    "",
    "| 패널 | 표시 내용 | PromQL 예시 |",
    "|------|----------|-------------|",
    "| CPU Usage | 프로세스/시스템 CPU | `system_cpu_usage`, `process_cpu_usage` |",
    "| JVM Memory | 힙/논힙 메모리 | `jvm_memory_used_bytes` |",
    "| GC Pause | GC 일시정지 시간 | `rate(jvm_gc_pause_seconds_sum[5m])` |",
    "| Threads | 라이브/데몬 스레드 | `jvm_threads_live_threads` |",
    "| Class Loading | 로드/언로드 클래스 수 | `jvm_classes_loaded_classes` |",
    "| Logback Events | 로그 레벨별 발생 수 | `logback_events_total` |",
    "",
    "---",
    "",
    "## 커스텀 대시보드",
    "",
    "비즈니스 메트릭을 시각화하는 **커스텀 대시보드**를 구성합니다.",
    "",
    "### 패널 1: 주문 수 (Counter)",
    "",
    "```",
    "# 분당 주문 수",
    "rate(orders_created_total[5m]) * 60",
    "",
    "# 시간대별 누적 주문 수",
    "increase(orders_created_total[1h])",
    "```",
    "",
    "- 시각화 타입: **Time Series** 또는 **Stat**",
    "- 단위: `orders/min`",
    "",
    "### 패널 2: API 응답 시간 (Timer)",
    "",
    "```",
    "# 95번째 백분위 응답 시간",
    "histogram_quantile(0.95,",
    "  sum(rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[5m])) by (le, uri)",
    ")",
    "",
    "# 평균 응답 시간",
    "rate(http_server_requests_seconds_sum{uri=~\"/api/.*\"}[5m])",
    "  / rate(http_server_requests_seconds_count{uri=~\"/api/.*\"}[5m])",
    "```",
    "",
    "- 시각화 타입: **Time Series** (다중 라인)",
    "- 단위: `seconds`",
    "",
    "### 패널 3: 에러율 (Gauge/Stat)",
    "",
    "```",
    "# 에러율 (%) - 5xx 응답 비율",
    "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
    "  / sum(rate(http_server_requests_seconds_count[5m])) * 100",
    "```",
    "",
    "- 시각화 타입: **Gauge** 또는 **Stat**",
    "- 임계값: 0~1% 녹색, 1~5% 노랑, 5%~ 빨강",
    "",
    "### 커스텀 대시보드 구성 예시",
    "",
    "| 행 | 패널 1 | 패널 2 | 패널 3 |",
    "|----|--------|--------|--------|",
    "| 1행 | 총 요청 수 (Stat) | 에러율 (Gauge) | 활성 사용자 (Stat) |",
    "| 2행 | 응답 시간 P95 (Time Series) | RPS (Time Series) | - |",
    "| 3행 | 주문 수 (Time Series) | 주문 실패 (Time Series) | 주문 금액 분포 (Histogram) |",
    "| 4행 | CPU 사용률 (Gauge) | 메모리 사용률 (Gauge) | GC 일시정지 (Time Series) |",
    "",
    "---",
    "",
    "## 알림 설정 (Grafana Alert)",
    "",
    "### Alert Rule 생성",
    "",
    "Grafana에서 특정 조건이 충족되면 **자동으로 알림**을 보낼 수 있습니다.",
    "",
    "#### 에러율 알림 예시",
    "",
    "1. 대시보드 패널 → **Edit → Alert 탭**",
    "2. **Create Alert Rule**:",
    "   - Name: `High Error Rate`",
    "   - Condition: `WHEN last() OF query(A) IS ABOVE 5`",
    "   - Evaluate: every `1m` for `5m` (5분 동안 지속 시 알림)",
    "3. **Notification** 설정",
    "",
    "### Notification Channel 설정",
    "",
    "#### Slack 알림",
    "",
    "```",
    "1. Grafana → Alerting → Notification channels → Add channel",
    "2. Type: Slack",
    "3. Webhook URL: https://hooks.slack.com/services/xxx/yyy/zzz",
    "4. Channel: #monitoring-alerts",
    "5. Send Test → Save",
    "```",
    "",
    "#### Email 알림",
    "",
    "```yaml",
    "# Grafana 환경 변수 (docker-compose에 추가)",
    "environment:",
    "  - GF_SMTP_ENABLED=true",
    "  - GF_SMTP_HOST=smtp.gmail.com:587",
    "  - GF_SMTP_USER=your-email@gmail.com",
    "  - GF_SMTP_PASSWORD=app-password",
    "  - GF_SMTP_FROM_ADDRESS=your-email@gmail.com",
    "```",
    "",
    "#### Discord 알림",
    "",
    "```",
    "1. Discord 서버 → 채널 설정 → 연동 → 웹훅 만들기",
    "2. 웹훅 URL 복사: https://discord.com/api/webhooks/xxx/yyy",
    "3. Grafana → Notification channels → Add channel",
    "4. Type: Discord",
    "5. Webhook URL 입력 → Save",
    "```",
    "",
    "### 권장 알림 규칙",
    "",
    "| 알림 이름 | 조건 | 지속 시간 | 심각도 |",
    "|----------|------|----------|--------|",
    "| 높은 에러율 | 에러율 > 5% | 5분 | Critical |",
    "| 느린 응답 | P95 > 3초 | 5분 | Warning |",
    "| 높은 CPU | CPU > 80% | 10분 | Warning |",
    "| 메모리 부족 | 힙 사용률 > 90% | 5분 | Critical |",
    "| 서비스 다운 | health != UP | 1분 | Critical |",
    "| GC 과다 | GC 시간 > 500ms | 5분 | Warning |",
    "",
    "---",
    "",
    "## Docker Compose 전체 구성",
    "",
    "Spring Boot + Prometheus + Grafana를 **한 번에** 실행하는 구성입니다.",
    "",
    "```yaml",
    "# docker-compose.yml",
    "version: '3.8'",
    "",
    "services:",
    "  # Spring Boot 애플리케이션",
    "  app:",
    "    build:",
    "      context: .",
    "      dockerfile: Dockerfile",
    "    container_name: spring-app",
    "    ports:",
    "      - \"8080:8080\"",
    "    environment:",
    "      - SPRING_PROFILES_ACTIVE=local",
    "    healthcheck:",
    "      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:8080/actuator/health\"]",
    "      interval: 30s",
    "      timeout: 10s",
    "      retries: 3",
    "    networks:",
    "      - monitoring",
    "",
    "  # Prometheus",
    "  prometheus:",
    "    image: prom/prometheus:latest",
    "    container_name: prometheus",
    "    ports:",
    "      - \"9090:9090\"",
    "    volumes:",
    "      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml",
    "      - prometheus_data:/prometheus",
    "    command:",
    "      - '--config.file=/etc/prometheus/prometheus.yml'",
    "      - '--storage.tsdb.retention.time=15d'",
    "      - '--web.enable-lifecycle'",
    "    depends_on:",
    "      app:",
    "        condition: service_healthy",
    "    networks:",
    "      - monitoring",
    "",
    "  # Grafana",
    "  grafana:",
    "    image: grafana/grafana:latest",
    "    container_name: grafana",
    "    ports:",
    "      - \"3000:3000\"",
    "    environment:",
    "      - GF_SECURITY_ADMIN_USER=admin",
    "      - GF_SECURITY_ADMIN_PASSWORD=admin123",
    "      - GF_USERS_ALLOW_SIGN_UP=false",
    "    volumes:",
    "      - grafana_data:/var/lib/grafana",
    "      - ./grafana/provisioning:/etc/grafana/provisioning",
    "    depends_on:",
    "      - prometheus",
    "    networks:",
    "      - monitoring",
    "",
    "networks:",
    "  monitoring:",
    "    driver: bridge",
    "",
    "volumes:",
    "  prometheus_data:",
    "  grafana_data:",
    "```",
    "",
    "### prometheus.yml (Docker Compose용)",
    "",
    "```yaml",
    "# prometheus/prometheus.yml",
    "global:",
    "  scrape_interval: 15s",
    "",
    "scrape_configs:",
    "  - job_name: 'prometheus'",
    "    static_configs:",
    "      - targets: ['localhost:9090']",
    "",
    "  - job_name: 'spring-boot-app'",
    "    metrics_path: '/actuator/prometheus'",
    "    scrape_interval: 10s",
    "    static_configs:",
    "      - targets: ['app:8080']  # Docker 서비스 이름으로 접근",
    "        labels:",
    "          application: 'my-spring-app'",
    "```",
    "",
    "### Grafana 자동 프로비저닝 (선택사항)",
    "",
    "```yaml",
    "# grafana/provisioning/datasources/prometheus.yml",
    "apiVersion: 1",
    "",
    "datasources:",
    "  - name: Prometheus",
    "    type: prometheus",
    "    access: proxy",
    "    url: http://prometheus:9090",
    "    isDefault: true",
    "    editable: true",
    "```",
    "",
    "### 실행 및 확인",
    "",
    "```bash",
    "# 전체 서비스 시작",
    "docker-compose up -d",
    "",
    "# 상태 확인",
    "docker-compose ps",
    "",
    "# 각 서비스 접속 확인",
    "# Spring Boot: http://localhost:8080/actuator/health",
    "# Prometheus:  http://localhost:9090/targets",
    "# Grafana:     http://localhost:3000 (admin/admin123)",
    "",
    "# 로그 확인",
    "docker-compose logs -f app",
    "",
    "# 종료",
    "docker-compose down",
    "```",
    "",
    "### 전체 디렉토리 구조",
    "",
    "```",
    "프로젝트 루트/",
    "├── src/",
    "│   └── main/",
    "│       ├── java/",
    "│       └── resources/",
    "│           └── application.yml",
    "├── prometheus/",
    "│   └── prometheus.yml",
    "├── grafana/",
    "│   └── provisioning/",
    "│       └── datasources/",
    "│           └── prometheus.yml",
    "├── Dockerfile",
    "├── docker-compose.yml",
    "└── build.gradle",
    "```",
    "",
    "---",
    "",
    "## 주의사항 및 베스트 프랙티스",
    "",
    "### 메트릭 과다 수집 방지",
    "",
    "- **필요한 메트릭만** 노출: `management.endpoints.web.exposure.include`로 제한",
    "- **scrape_interval** 적절히 설정: 너무 짧으면 부하 증가 (권장: 10~30초)",
    "- 불필요한 엔드포인트 비활성화:",
    "",
    "```yaml",
    "management:",
    "  endpoints:",
    "    web:",
    "      exposure:",
    "        include: health,prometheus  # 필요한 것만",
    "        exclude: env,beans,conditions  # 불필요한 것 제외",
    "```",
    "",
    "### 카디널리티(Cardinality) 관리",
    "",
    "- **카디널리티**: 메트릭의 고유한 레이블 조합 수",
    "- 높은 카디널리티는 Prometheus의 **메모리와 스토리지를 급격히 증가**시킴",
    "",
    "| 레이블 | 카디널리티 | 주의 |",
    "|--------|-----------|------|",
    "| `method` (GET/POST) | 낮음 ✅ | 안전 |",
    "| `status` (200/404/500) | 낮음 ✅ | 안전 |",
    "| `uri` (/api/users) | 중간 ⚠️ | 경로 변수 주의 |",
    "| `userId` (사용자 ID) | 높음 ❌ | 절대 사용 금지 |",
    "| `orderId` (주문 ID) | 높음 ❌ | 절대 사용 금지 |",
    "",
    "```java",
    "// ❌ 나쁜 예 - 카디널리티 폭발",
    "Counter.builder(\"api.calls\")",
    "    .tag(\"userId\", userId)  // 사용자 수만큼 시계열 생성!",
    "    .register(registry);",
    "",
    "// ✅ 좋은 예 - 낮은 카디널리티",
    "Counter.builder(\"api.calls\")",
    "    .tag(\"endpoint\", \"/api/orders\")",
    "    .tag(\"method\", \"GET\")",
    "    .register(registry);",
    "```",
    "",
    "### 보안 설정",
    "",
    "운영 환경에서는 Actuator 엔드포인트를 **반드시 보호**해야 합니다.",
    "",
    "```java",
    "// SecurityConfig.java",
    "@Configuration",
    "@EnableWebSecurity",
    "public class SecurityConfig {",
    "",
    "    @Bean",
    "    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {",
    "        return http",
    "            .authorizeHttpRequests(auth -> auth",
    "                .requestMatchers(\"/actuator/health\").permitAll()",
    "                .requestMatchers(\"/actuator/**\").hasRole(\"ADMIN\")",
    "                .anyRequest().authenticated()",
    "            )",
    "            .build();",
    "    }",
    "}",
    "```",
    "",
    "또는 **별도 포트**로 Actuator를 분리:",
    "",
    "```yaml",
    "# application-prod.yml",
    "management:",
    "  server:",
    "    port: 9090  # Actuator 전용 포트 (내부 네트워크에서만 접근 가능)",
    "```",
    "",
    "### 정리 표",
    "",
    "| 항목 | 도구 | 핵심 설정 | 주의점 |",
    "|------|------|----------|--------|",
    "| 메트릭 노출 | Actuator | `management.endpoints.web.exposure` | 운영 환경 보안 |",
    "| 메트릭 수집 | Micrometer | Counter, Gauge, Timer | 카디널리티 관리 |",
    "| 메트릭 저장 | Prometheus | `prometheus.yml` scrape 설정 | 리텐션, 스토리지 |",
    "| 시각화 | Grafana | 대시보드 + PromQL | 패널 수 적절히 |",
    "| 알림 | Grafana Alert | 조건 + Notification Channel | 알림 피로 방지 |",
    "| JVM 대시보드 | Grafana Import | ID: 4701 | Micrometer 버전 호환 |",
    "| 커스텀 메트릭 | MeterRegistry | 비즈니스 메트릭 정의 | 과다 수집 주의 |",
    "| 보안 | Spring Security | Actuator 접근 제한 | 내부 포트 분리 |",
    "",
    "---",
    "",
    "## 마무리",
    "",
    "모니터링은 **배포 후 시작**이 아니라 **개발 초기부터 함께** 구축해야 합니다. 아래 단계로 점진적으로 도입하세요.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[\"1단계<br/>Actuator 설정\"] --> B[\"2단계<br/>Prometheus 연동\"]",
    "    B --> C[\"3단계<br/>Grafana 대시보드\"]",
    "    C --> D[\"4단계<br/>커스텀 메트릭\"]",
    "    D --> E[\"5단계<br/>알림 설정\"]",
    "    E --> F[\"6단계<br/>로그/트레이싱<br/>통합\"]",
    "",
    "    style A fill:#C8E6C9",
    "    style B fill:#FFE0B2",
    "    style C fill:#BBDEFB",
    "    style D fill:#FFF9C4",
    "    style E fill:#FFCDD2",
    "    style F fill:#D1C4E9",
    "```",
    "",
    "- **1단계**: Actuator + Micrometer 의존성 추가, 기본 엔드포인트 노출",
    "- **2단계**: Prometheus Docker 실행, scrape 설정으로 메트릭 수집 시작",
    "- **3단계**: Grafana Docker 실행, JVM 대시보드(4701) Import",
    "- **4단계**: Counter, Timer 등으로 비즈니스 메트릭 정의",
    "- **5단계**: 에러율, CPU, 메모리 등 핵심 지표에 알림 규칙 설정",
    "- **6단계**: ELK/Loki(로그), Zipkin/Jaeger(트레이싱)로 Observability 완성"
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
