<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "springboot-filter",
  title: "Spring Boot Filter 완전 정리 - 개념부터 실전 예제까지",
  date: "2026-03-04",
  summary: "Servlet Filter의 개념, Interceptor와의 차이, Filter 등록 방법 3가지, 인코딩·CORS·로깅·보안 실전 예제, Filter Chain 실행 순서, OncePerRequestFilter까지 정리합니다.",
  category: "Technology/SpringBoot",
  tags: ["springboot","filter","servlet","cors","java","backend"],
  content: [
    "## Filter란?",
    "",
    "**Filter(필터)**는 HTTP 요청이 **DispatcherServlet에 도달하기 전**과 **응답이 클라이언트로 나가기 전**에 공통 처리를 수행하는 **Servlet API** 기능입니다.",
    "",
    "Interceptor보다 **더 바깥쪽**에서 동작하며, Spring에 종속되지 않는 Java EE(Jakarta EE) 표준 기술입니다.",
    "",
    "```mermaid",
    "flowchart LR",
    "    A[클라이언트] --> B[\"Filter 1\"]",
    "    B --> C[\"Filter 2\"]",
    "    C --> D[\"Filter 3\"]",
    "    D --> E[\"DispatcherServlet\"]",
    "    E --> F[\"Interceptor\"]",
    "    F --> G[\"Controller\"]",
    "    G --> F",
    "    F --> E",
    "    E --> D",
    "    D --> C",
    "    C --> B",
    "    B --> A",
    "    style B fill:#e67e22,color:#fff",
    "    style C fill:#e67e22,color:#fff",
    "    style D fill:#e67e22,color:#fff",
    "    style F fill:#3498db,color:#fff",
    "```",
    "",
    "> Filter는 요청이 들어올 때와 응답이 나갈 때 **양방향으로** 동작합니다. 여러 Filter가 체인처럼 연결됩니다.",
    "",
    "---",
    "",
    "## Filter vs Interceptor 핵심 차이",
    "",
    "| 비교 | Filter | Interceptor |",
    "|------|--------|-------------|",
    "| 표준 | Servlet API (Jakarta EE) | Spring MVC |",
    "| 동작 위치 | DispatcherServlet **밖** | DispatcherServlet **안** |",
    "| 적용 대상 | **모든 요청** (정적 리소스 포함) | Controller로 향하는 요청만 |",
    "| 인터페이스 | `jakarta.servlet.Filter` | `HandlerInterceptor` |",
    "| 요청/응답 조작 | `ServletRequest/Response` 교체 가능 | 읽기만 가능 |",
    "| Spring Bean 접근 | Spring Boot에서 가능 | 자유롭게 가능 |",
    "| 주요 용도 | 인코딩, CORS, 보안, 요청 래핑 | 로그인 체크, 로깅, 권한 |",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant F as Filter",
    "    participant DS as DispatcherServlet",
    "    participant I as Interceptor",
    "    participant CT as Controller",
    "    rect rgb(230, 126, 34)",
    "        Note over F: Filter 영역 (Servlet 레벨)",
    "        C->>F: HTTP 요청",
    "        F->>DS: doFilter() → chain.doFilter()",
    "    end",
    "    rect rgb(52, 152, 219)",
    "        Note over I: Interceptor 영역 (Spring MVC 레벨)",
    "        DS->>I: preHandle()",
    "        I->>CT: Controller 실행",
    "        CT-->>I: postHandle()",
    "    end",
    "    I-->>DS: 응답",
    "    DS-->>F: 응답",
    "    F-->>C: 최종 응답",
    "```",
    "",
    "### 언제 Filter를 쓸까?",
    "",
    "| 상황 | 추천 이유 |",
    "|------|-----------|",
    "| 문자 인코딩 설정 | 모든 요청에 공통 적용, Spring 이전에 처리 필요 |",
    "| CORS 헤더 설정 | 모든 응답에 헤더 추가 |",
    "| 요청/응답 본문 로깅 | `HttpServletRequest`를 래핑해야 함 |",
    "| XSS·SQL Injection 방지 | 파라미터를 필터링/치환 |",
    "| 압축/암호화 | 응답 스트림을 래핑 |",
    "| 인증 토큰 검증 (Spring Security) | Security Filter Chain |",
    "",
    "---",
    "",
    "## Filter 인터페이스",
    "",
    "```java",
    "public interface Filter {",
    "",
    "    // 필터 초기화 (서버 시작 시 1회)",
    "    default void init(FilterConfig filterConfig) throws ServletException {}",
    "",
    "    // 요청/응답 처리 (매 요청마다)",
    "    void doFilter(ServletRequest request,",
    "                  ServletResponse response,",
    "                  FilterChain chain) throws IOException, ServletException;",
    "",
    "    // 필터 소멸 (서버 종료 시 1회)",
    "    default void destroy() {}",
    "}",
    "```",
    "",
    "| 메서드 | 호출 시점 | 역할 |",
    "|--------|-----------|------|",
    "| `init()` | 서버 시작 시 1회 | 초기화 작업 |",
    "| `doFilter()` | 매 요청마다 | 핵심 로직 + `chain.doFilter()`로 다음 필터 호출 |",
    "| `destroy()` | 서버 종료 시 1회 | 리소스 정리 |",
    "",
    "### doFilter()의 핵심 구조",
    "",
    "```java",
    "@Override",
    "public void doFilter(ServletRequest request,",
    "                     ServletResponse response,",
    "                     FilterChain chain) throws IOException, ServletException {",
    "",
    "    // ① 요청 전 처리 (Controller 실행 전)",
    "    // ... 전처리 로직 ...",
    "",
    "    chain.doFilter(request, response);  // ② 다음 필터 또는 Servlet으로 전달",
    "",
    "    // ③ 응답 후 처리 (Controller 실행 후)",
    "    // ... 후처리 로직 ...",
    "}",
    "```",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"① 전처리 (요청 로깅, 인코딩 등)\"] --> B[\"② chain.doFilter()\"]",
    "    B --> C[\"다음 Filter → ... → Controller → 응답\"]",
    "    C --> D[\"③ 후처리 (응답 로깅, 헤더 추가 등)\"]",
    "```",
    "",
    "> **`chain.doFilter()`를 호출하지 않으면** 요청이 다음 단계로 전달되지 않아 Controller가 실행되지 않습니다. Interceptor의 `return false`와 비슷한 효과입니다.",
    "",
    "---",
    "",
    "## 프로젝트 구조",
    "",
    "```",
    "src/main/java/com/example/demo/",
    "├── DemoApplication.java",
    "├── config/",
    "│   └── FilterConfig.java               // Filter 등록 (방법 2)",
    "├── filter/",
    "│   ├── EncodingFilter.java              // 인코딩 설정",
    "│   ├── CorsFilter.java                  // CORS 처리",
    "│   ├── RequestLoggingFilter.java        // 요청 로깅",
    "│   ├── XssFilter.java                   // XSS 방지",
    "│   └── AuthenticationFilter.java        // 토큰 인증",
    "├── controller/",
    "│   └── UserController.java",
    "└── service/",
    "    └── UserService.java",
    "```",
    "",
    "---",
    "",
    "## Filter 등록 방법 3가지",
    "",
    "### 방법 1: @Component (간단하지만 순서 제어 어려움)",
    "",
    "```java",
    "@Component",
    "@Order(1)",
    "public class MyFilter implements Filter {",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "        // 로직",
    "        chain.doFilter(request, response);",
    "    }",
    "}",
    "```",
    "",
    "### 방법 2: FilterRegistrationBean (권장 - 순서·URL 패턴 제어 가능)",
    "",
    "```java",
    "package com.example.demo.config;",
    "",
    "import com.example.demo.filter.*;",
    "import org.springframework.boot.web.servlet.FilterRegistrationBean;",
    "import org.springframework.context.annotation.Bean;",
    "import org.springframework.context.annotation.Configuration;",
    "",
    "@Configuration",
    "public class FilterConfig {",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<RequestLoggingFilter> loggingFilter() {",
    "        FilterRegistrationBean<RequestLoggingFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new RequestLoggingFilter());",
    "        bean.addUrlPatterns(\"/*\");",
    "        bean.setOrder(1);",
    "        bean.setName(\"requestLoggingFilter\");",
    "        return bean;",
    "    }",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<AuthenticationFilter> authFilter() {",
    "        FilterRegistrationBean<AuthenticationFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new AuthenticationFilter());",
    "        bean.addUrlPatterns(\"/api/*\");",
    "        bean.setOrder(2);",
    "        bean.setName(\"authenticationFilter\");",
    "        return bean;",
    "    }",
    "}",
    "```",
    "",
    "### 방법 3: @WebFilter + @ServletComponentScan",
    "",
    "```java",
    "@WebFilter(urlPatterns = \"/api/*\", filterName = \"myFilter\")",
    "public class MyFilter implements Filter {",
    "    @Override",
    "    public void doFilter(ServletRequest request, ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "        chain.doFilter(request, response);",
    "    }",
    "}",
    "```",
    "",
    "```java",
    "@SpringBootApplication",
    "@ServletComponentScan",
    "public class DemoApplication { ... }",
    "```",
    "",
    "### 등록 방법 비교",
    "",
    "| 방법 | 순서 제어 | URL 패턴 | Spring Bean 주입 | 추천도 |",
    "|------|-----------|----------|------------------|--------|",
    "| `@Component` + `@Order` | `@Order` | 불가 (전체 적용) | O | 간단한 경우 |",
    "| `FilterRegistrationBean` | `setOrder()` | `addUrlPatterns()` | O | **권장** |",
    "| `@WebFilter` | 보장 안 됨 | `urlPatterns` | X | 비추천 |",
    "",
    "---",
    "",
    "## 실전 예제 1: 요청·응답 로깅 Filter",
    "",
    "모든 HTTP 요청의 메서드, URI, 실행 시간, 응답 상태를 기록합니다.",
    "",
    "### RequestLoggingFilter.java",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "",
    "import java.io.IOException;",
    "",
    "@Slf4j",
    "public class RequestLoggingFilter implements Filter {",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "",
    "        HttpServletRequest httpReq = (HttpServletRequest) request;",
    "        HttpServletResponse httpRes = (HttpServletResponse) response;",
    "",
    "        String method = httpReq.getMethod();",
    "        String uri = httpReq.getRequestURI();",
    "        long start = System.currentTimeMillis();",
    "",
    "        log.info(\"[Filter 요청] {} {}\", method, uri);",
    "",
    "        chain.doFilter(request, response);",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        int status = httpRes.getStatus();",
    "        log.info(\"[Filter 응답] {} {} → {} ({}ms)\", method, uri, status, elapsed);",
    "    }",
    "}",
    "```",
    "",
    "### 실행 결과",
    "",
    "```",
    "INFO  [Filter 요청] GET /api/users",
    "INFO  [Filter 응답] GET /api/users → 200 (23ms)",
    "INFO  [Filter 요청] POST /api/users",
    "INFO  [Filter 응답] POST /api/users → 201 (41ms)",
    "INFO  [Filter 요청] GET /api/users/999",
    "INFO  [Filter 응답] GET /api/users/999 → 404 (5ms)",
    "```",
    "",
    "---",
    "",
    "## 실전 예제 2: CORS Filter",
    "",
    "브라우저의 **Cross-Origin 요청**을 허용하는 헤더를 모든 응답에 추가합니다.",
    "",
    "### CorsFilter.java",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "",
    "import java.io.IOException;",
    "",
    "@Slf4j",
    "public class CorsFilter implements Filter {",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "",
    "        HttpServletRequest httpReq = (HttpServletRequest) request;",
    "        HttpServletResponse httpRes = (HttpServletResponse) response;",
    "",
    "        httpRes.setHeader(\"Access-Control-Allow-Origin\", \"*\");",
    "        httpRes.setHeader(\"Access-Control-Allow-Methods\", \"GET, POST, PUT, DELETE, OPTIONS\");",
    "        httpRes.setHeader(\"Access-Control-Allow-Headers\", \"Authorization, Content-Type\");",
    "        httpRes.setHeader(\"Access-Control-Max-Age\", \"3600\");",
    "",
    "        // OPTIONS preflight 요청은 바로 응답",
    "        if (\"OPTIONS\".equalsIgnoreCase(httpReq.getMethod())) {",
    "            httpRes.setStatus(HttpServletResponse.SC_OK);",
    "            return;",
    "        }",
    "",
    "        chain.doFilter(request, response);",
    "    }",
    "}",
    "```",
    "",
    "### CORS 헤더 설명",
    "",
    "| 헤더 | 역할 |",
    "|------|------|",
    "| `Access-Control-Allow-Origin` | 허용할 출처 (`*` = 모든 출처) |",
    "| `Access-Control-Allow-Methods` | 허용할 HTTP 메서드 |",
    "| `Access-Control-Allow-Headers` | 허용할 요청 헤더 |",
    "| `Access-Control-Max-Age` | Preflight 결과 캐시 시간(초) |",
    "",
    "> Spring Boot에서는 `WebMvcConfigurer.addCorsMappings()`이나 `@CrossOrigin`으로 CORS를 더 간단하게 설정할 수도 있습니다. Filter는 Spring 외부에서도 동작해야 하거나, 세밀한 제어가 필요할 때 사용합니다.",
    "",
    "---",
    "",
    "## 실전 예제 3: 인증 토큰 검증 Filter",
    "",
    "API 요청의 `Authorization` 헤더에서 토큰을 검증합니다.",
    "",
    "### AuthenticationFilter.java",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "",
    "import java.io.IOException;",
    "import java.util.Set;",
    "",
    "@Slf4j",
    "public class AuthenticationFilter implements Filter {",
    "",
    "    // 인증 없이 접근 가능한 경로",
    "    private static final Set<String> WHITELIST = Set.of(",
    "            \"/api/auth/login\",",
    "            \"/api/auth/signup\",",
    "            \"/api/health\"",
    "    );",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "",
    "        HttpServletRequest httpReq = (HttpServletRequest) request;",
    "        HttpServletResponse httpRes = (HttpServletResponse) response;",
    "",
    "        String uri = httpReq.getRequestURI();",
    "",
    "        // 화이트리스트 경로는 통과",
    "        if (WHITELIST.contains(uri)) {",
    "            chain.doFilter(request, response);",
    "            return;",
    "        }",
    "",
    "        // OPTIONS 요청 통과 (CORS preflight)",
    "        if (\"OPTIONS\".equalsIgnoreCase(httpReq.getMethod())) {",
    "            chain.doFilter(request, response);",
    "            return;",
    "        }",
    "",
    "        // Authorization 헤더 확인",
    "        String authHeader = httpReq.getHeader(\"Authorization\");",
    "",
    "        if (authHeader == null || !authHeader.startsWith(\"Bearer \")) {",
    "            log.warn(\"[인증 실패] 토큰 없음: {} {}\", httpReq.getMethod(), uri);",
    "            httpRes.setStatus(HttpServletResponse.SC_UNAUTHORIZED);",
    "            httpRes.setContentType(\"application/json;charset=UTF-8\");",
    "            httpRes.getWriter().write(",
    "                    \"{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"토큰이 필요합니다\\\"}\"",
    "            );",
    "            return;  // chain.doFilter()를 호출하지 않아 요청 차단",
    "        }",
    "",
    "        String token = authHeader.substring(7);",
    "",
    "        if (!isValidToken(token)) {",
    "            log.warn(\"[인증 실패] 유효하지 않은 토큰: {} {}\", httpReq.getMethod(), uri);",
    "            httpRes.setStatus(HttpServletResponse.SC_FORBIDDEN);",
    "            httpRes.setContentType(\"application/json;charset=UTF-8\");",
    "            httpRes.getWriter().write(",
    "                    \"{\\\"code\\\":\\\"FORBIDDEN\\\",\\\"message\\\":\\\"유효하지 않은 토큰입니다\\\"}\"",
    "            );",
    "            return;",
    "        }",
    "",
    "        log.info(\"[인증 성공] {} {}\", httpReq.getMethod(), uri);",
    "        chain.doFilter(request, response);",
    "    }",
    "",
    "    private boolean isValidToken(String token) {",
    "        // 실무에서는 JWT 파싱, 서명 검증, 만료 시간 확인",
    "        return token != null && token.length() > 10;",
    "    }",
    "}",
    "```",
    "",
    "**요청 차단 방법:**",
    "",
    "| Interceptor | Filter |",
    "|-------------|--------|",
    "| `return false;` | `chain.doFilter()`를 **호출하지 않고 return** |",
    "",
    "---",
    "",
    "## 실전 예제 4: XSS 방지 Filter",
    "",
    "요청 파라미터에서 `<script>` 같은 위험한 HTML 태그를 제거합니다.",
    "",
    "### XssFilter.java",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.*;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletRequestWrapper;",
    "",
    "import java.io.IOException;",
    "",
    "public class XssFilter implements Filter {",
    "",
    "    @Override",
    "    public void doFilter(ServletRequest request,",
    "                         ServletResponse response,",
    "                         FilterChain chain) throws IOException, ServletException {",
    "        chain.doFilter(new XssRequestWrapper((HttpServletRequest) request), response);",
    "    }",
    "}",
    "```",
    "",
    "### XssRequestWrapper.java",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletRequestWrapper;",
    "",
    "public class XssRequestWrapper extends HttpServletRequestWrapper {",
    "",
    "    public XssRequestWrapper(HttpServletRequest request) {",
    "        super(request);",
    "    }",
    "",
    "    @Override",
    "    public String getParameter(String name) {",
    "        String value = super.getParameter(name);",
    "        return sanitize(value);",
    "    }",
    "",
    "    @Override",
    "    public String[] getParameterValues(String name) {",
    "        String[] values = super.getParameterValues(name);",
    "        if (values == null) return null;",
    "        String[] sanitized = new String[values.length];",
    "        for (int i = 0; i < values.length; i++) {",
    "            sanitized[i] = sanitize(values[i]);",
    "        }",
    "        return sanitized;",
    "    }",
    "",
    "    @Override",
    "    public String getHeader(String name) {",
    "        String value = super.getHeader(name);",
    "        return sanitize(value);",
    "    }",
    "",
    "    private String sanitize(String value) {",
    "        if (value == null) return null;",
    "        return value",
    "                .replaceAll(\"<\", \"&lt;\")",
    "                .replaceAll(\">\", \"&gt;\")",
    "                .replaceAll(\"\\\\(\", \"&#40;\")",
    "                .replaceAll(\"\\\\)\", \"&#41;\")",
    "                .replaceAll(\"'\", \"&#39;\")",
    "                .replaceAll(\"eval\\\\(\", \"\")",
    "                .replaceAll(\"javascript:\", \"\");",
    "    }",
    "}",
    "```",
    "",
    "> **핵심:** `HttpServletRequestWrapper`를 상속하여 요청 객체 자체를 **교체**합니다. 이렇게 하면 Controller가 `request.getParameter()`를 호출해도 이미 치환된 안전한 값을 받습니다. 이것이 Filter에서만 가능하고 Interceptor에서는 불가능한 기능입니다.",
    "",
    "---",
    "",
    "## OncePerRequestFilter (Spring 제공)",
    "",
    "Spring은 `jakarta.servlet.Filter` 대신 **`OncePerRequestFilter`** 추상 클래스를 제공합니다. 요청당 **1회만** 실행되는 것을 보장합니다.",
    "",
    "### 왜 필요한가?",
    "",
    "서블릿 스펙에서는 `forward`나 `include`로 내부 이동이 발생하면 같은 요청에서 Filter가 **여러 번** 호출될 수 있습니다. `OncePerRequestFilter`는 이를 방지합니다.",
    "",
    "### 예제: OncePerRequestFilter 기반 로깅",
    "",
    "```java",
    "package com.example.demo.filter;",
    "",
    "import jakarta.servlet.FilterChain;",
    "import jakarta.servlet.ServletException;",
    "import jakarta.servlet.http.HttpServletRequest;",
    "import jakarta.servlet.http.HttpServletResponse;",
    "import lombok.extern.slf4j.Slf4j;",
    "import org.springframework.stereotype.Component;",
    "import org.springframework.web.filter.OncePerRequestFilter;",
    "",
    "import java.io.IOException;",
    "",
    "@Slf4j",
    "@Component",
    "public class ApiLoggingFilter extends OncePerRequestFilter {",
    "",
    "    @Override",
    "    protected void doFilterInternal(HttpServletRequest request,",
    "                                    HttpServletResponse response,",
    "                                    FilterChain filterChain)",
    "            throws ServletException, IOException {",
    "",
    "        long start = System.currentTimeMillis();",
    "        String method = request.getMethod();",
    "        String uri = request.getRequestURI();",
    "",
    "        log.info(\"[API] {} {} 시작\", method, uri);",
    "",
    "        filterChain.doFilter(request, response);",
    "",
    "        long elapsed = System.currentTimeMillis() - start;",
    "        log.info(\"[API] {} {} → {} ({}ms)\", method, uri, response.getStatus(), elapsed);",
    "    }",
    "",
    "    @Override",
    "    protected boolean shouldNotFilter(HttpServletRequest request) {",
    "        String uri = request.getRequestURI();",
    "        // 정적 리소스와 health check는 제외",
    "        return uri.startsWith(\"/css\")",
    "                || uri.startsWith(\"/js\")",
    "                || uri.startsWith(\"/images\")",
    "                || uri.equals(\"/api/health\");",
    "    }",
    "}",
    "```",
    "",
    "### Filter vs OncePerRequestFilter 비교",
    "",
    "| 비교 | `Filter` | `OncePerRequestFilter` |",
    "|------|----------|------------------------|",
    "| 패키지 | `jakarta.servlet` | `org.springframework.web.filter` |",
    "| 요청당 실행 | 여러 번 가능 (forward/include 시) | **1회 보장** |",
    "| 구현 메서드 | `doFilter()` | `doFilterInternal()` |",
    "| 제외 조건 | 직접 구현 | `shouldNotFilter()` 오버라이드 |",
    "| 파라미터 타입 | `ServletRequest` | **`HttpServletRequest`** (캐스팅 불필요) |",
    "",
    "> 실무에서는 대부분 **`OncePerRequestFilter`를 사용하는 것이 권장**됩니다.",
    "",
    "---",
    "",
    "## Filter Chain 실행 순서",
    "",
    "여러 Filter가 등록된 경우, `order` 값이 **작을수록 먼저** 실행됩니다.",
    "",
    "```java",
    "@Configuration",
    "public class FilterConfig {",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<CorsFilter> corsFilter() {",
    "        FilterRegistrationBean<CorsFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new CorsFilter());",
    "        bean.setOrder(1);  // 가장 먼저",
    "        bean.addUrlPatterns(\"/*\");",
    "        return bean;",
    "    }",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<XssFilter> xssFilter() {",
    "        FilterRegistrationBean<XssFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new XssFilter());",
    "        bean.setOrder(2);",
    "        bean.addUrlPatterns(\"/*\");",
    "        return bean;",
    "    }",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<RequestLoggingFilter> loggingFilter() {",
    "        FilterRegistrationBean<RequestLoggingFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new RequestLoggingFilter());",
    "        bean.setOrder(3);",
    "        bean.addUrlPatterns(\"/*\");",
    "        return bean;",
    "    }",
    "",
    "    @Bean",
    "    public FilterRegistrationBean<AuthenticationFilter> authFilter() {",
    "        FilterRegistrationBean<AuthenticationFilter> bean = new FilterRegistrationBean<>();",
    "        bean.setFilter(new AuthenticationFilter());",
    "        bean.setOrder(4);",
    "        bean.addUrlPatterns(\"/api/*\");",
    "        return bean;",
    "    }",
    "}",
    "```",
    "",
    "```mermaid",
    "sequenceDiagram",
    "    participant C as 클라이언트",
    "    participant F1 as CorsFilter (order=1)",
    "    participant F2 as XssFilter (order=2)",
    "    participant F3 as LoggingFilter (order=3)",
    "    participant F4 as AuthFilter (order=4)",
    "    participant S as DispatcherServlet → Controller",
    "    C->>F1: 요청",
    "    F1->>F2: chain.doFilter()",
    "    F2->>F3: chain.doFilter()",
    "    F3->>F4: chain.doFilter()",
    "    F4->>S: chain.doFilter()",
    "    S-->>F4: 응답",
    "    F4-->>F3: 응답",
    "    F3-->>F2: 응답",
    "    F2-->>F1: 응답",
    "    F1-->>C: 최종 응답",
    "```",
    "",
    "### 권장 순서",
    "",
    "| 순서 | Filter | 이유 |",
    "|------|--------|------|",
    "| 1 | CORS | 모든 응답에 CORS 헤더가 포함되어야 함 |",
    "| 2 | XSS 방지 | 인증 전에 입력값을 먼저 정리 |",
    "| 3 | 로깅 | 요청 전체 흐름을 기록 |",
    "| 4 | 인증 | 보호된 리소스 접근 전 최종 검증 |",
    "",
    "---",
    "",
    "## Spring Boot 내장 Filter",
    "",
    "Spring Boot는 자동으로 등록하는 기본 Filter들이 있습니다.",
    "",
    "| Filter | 역할 | 자동 등록 |",
    "|--------|------|-----------|",
    "| `CharacterEncodingFilter` | 요청/응답 인코딩 (UTF-8) | O (기본 활성화) |",
    "| `HiddenHttpMethodFilter` | HTML form에서 PUT/DELETE 사용 (`_method` 파라미터) | O |",
    "| `FormContentFilter` | PUT/PATCH의 `application/x-www-form-urlencoded` 파싱 | O |",
    "| `RequestContextFilter` | `RequestContextHolder`에 요청 정보 저장 | O |",
    "",
    "### application.yml로 인코딩 설정",
    "",
    "```yaml",
    "server:",
    "  servlet:",
    "    encoding:",
    "      charset: UTF-8",
    "      enabled: true",
    "      force: true",
    "```",
    "",
    "> Spring Boot는 `CharacterEncodingFilter`가 기본 등록되어 있으므로, 별도로 인코딩 Filter를 만들 필요가 없습니다.",
    "",
    "---",
    "",
    "## 전체 흐름 정리: Filter → Interceptor → AOP → Controller",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[\"클라이언트 요청\"] --> B[\"Filter Chain<br/>(CORS → XSS → 로깅 → 인증)\"]",
    "    B --> C[\"DispatcherServlet\"]",
    "    C --> D[\"Interceptor<br/>preHandle()\"]",
    "    D --> E[\"AOP<br/>@Before / @Around\"]",
    "    E --> F[\"Controller\"]",
    "    F --> G[\"Service\"]",
    "    G --> F",
    "    F --> E",
    "    E --> D",
    "    D --> H[\"Interceptor<br/>postHandle() → afterCompletion()\"]",
    "    H --> C",
    "    C --> B",
    "    B --> I[\"클라이언트 응답\"]",
    "    style B fill:#e67e22,color:#fff",
    "    style D fill:#3498db,color:#fff",
    "    style H fill:#3498db,color:#fff",
    "    style E fill:#27ae60,color:#fff",
    "```",
    "",
    "| 계층 | 기술 | 주요 용도 |",
    "|------|------|-----------|",
    "| **가장 바깥** | Filter | 인코딩, CORS, XSS, 요청 래핑 |",
    "| **중간** | Interceptor | 로그인 체크, API 로깅, 권한 |",
    "| **가장 안쪽** | AOP | 트랜잭션, 메서드 실행 시간, 캐싱 |",
    "",
    "---",
    "",
    "## 정리",
    "",
    "| 항목 | 내용 |",
    "|------|------|",
    "| Filter란 | DispatcherServlet 밖에서 동작하는 Servlet 레벨 공통 처리 기능 |",
    "| 인터페이스 | `jakarta.servlet.Filter` 또는 `OncePerRequestFilter` (권장) |",
    "| 등록 방법 | `FilterRegistrationBean` (권장) > `@Component` > `@WebFilter` |",
    "| 순서 제어 | `setOrder(n)` — 작을수록 먼저 실행 |",
    "| 요청 차단 | `chain.doFilter()`를 호출하지 않으면 다음 단계로 전달되지 않음 |",
    "",
    "**Filter 활용 패턴:**",
    "",
    "| 용도 | 핵심 코드 |",
    "|------|-----------|",
    "| 로깅 | `chain.doFilter()` 전후에 시간 측정·로그 출력 |",
    "| CORS | `response.setHeader(\"Access-Control-Allow-Origin\", \"*\")` |",
    "| 인증 | `Authorization` 헤더 확인 → 실패 시 `return` (chain 미호출) |",
    "| XSS 방지 | `HttpServletRequestWrapper`로 요청 객체 교체 |",
    "| 제외 조건 | `OncePerRequestFilter.shouldNotFilter()` 오버라이드 |",
    "",
    "실무에서는 **인코딩·CORS·XSS는 Filter**, **로그인 체크·API 로깅은 Interceptor**, **트랜잭션·서비스 로직은 AOP**로 역할을 분리하는 것이 일반적입니다. 세 기술의 동작 위치를 이해하면 어디에 어떤 로직을 넣어야 하는지 자연스럽게 판단할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
