<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "ts-class-module",
  title: "TypeScript 클래스와 모듈",
  date: "2026-02-24",
  summary: "TypeScript의 클래스(접근 제한자, 추상 클래스, implements), 모듈(import/export), 네임스페이스, 데코레이터, 그리고 선언 파일(.d.ts)을 예제와 함께 정리합니다.",
  category: "Coding/JavaScript",
  tags: ["typescript","class","module","abstract","decorator","namespace","import","export","basics"],
  content: [
    "## 한 줄 요약",
    "TypeScript의 클래스는 **접근 제한자**(public/private/protected)와 **추상 클래스**, **interface implements**를 지원하며, 모듈 시스템은 ES Module(`import`/`export`)을 기반으로 합니다.",
    "",
    "---",
    "",
    "## 1. 클래스 (Class)",
    "",
    "### 기본 문법",
    "```typescript",
    "class User {",
    "    name: string;",
    "    age: number;",
    "",
    "    constructor(name: string, age: number) {",
    "        this.name = name;",
    "        this.age = age;",
    "    }",
    "",
    "    greet(): string {",
    "        return `Hi, I'm ${this.name}`;",
    "    }",
    "}",
    "",
    "const user = new User('haru', 25);",
    "console.log(user.greet()); // \"Hi, I'm haru\"",
    "```",
    "",
    "### 접근 제한자 (Access Modifiers)",
    "",
    "| 제한자 | 클래스 내부 | 하위 클래스 | 외부 |",
    "|--------|-----------|-----------|------|",
    "| `public` (기본값) | ✅ | ✅ | ✅ |",
    "| `protected` | ✅ | ✅ | ❌ |",
    "| `private` | ✅ | ❌ | ❌ |",
    "",
    "```typescript",
    "class Account {",
    "    public owner: string;",
    "    protected balance: number;",
    "    private pin: number;",
    "",
    "    constructor(owner: string, balance: number, pin: number) {",
    "        this.owner = owner;",
    "        this.balance = balance;",
    "        this.pin = pin;",
    "    }",
    "",
    "    public getBalance(): number {",
    "        return this.balance;",
    "    }",
    "",
    "    private validatePin(pin: number): boolean {",
    "        return this.pin === pin;",
    "    }",
    "}",
    "",
    "const acc = new Account('haru', 1000, 1234);",
    "console.log(acc.owner);       // OK (public)",
    "// console.log(acc.balance);  // ❌ (protected)",
    "// console.log(acc.pin);      // ❌ (private)",
    "console.log(acc.getBalance()); // OK",
    "```",
    "",
    "### 매개변수 프로퍼티 (Parameter Properties)",
    "생성자 매개변수에 접근 제한자를 붙이면 **선언과 할당을 동시에** 할 수 있습니다.",
    "",
    "```typescript",
    "// Before",
    "class User {",
    "    name: string;",
    "    age: number;",
    "    constructor(name: string, age: number) {",
    "        this.name = name;",
    "        this.age = age;",
    "    }",
    "}",
    "",
    "// After (동일한 결과, 코드 간결)",
    "class User {",
    "    constructor(",
    "        public name: string,",
    "        public age: number",
    "    ) {}",
    "}",
    "```",
    "",
    "### readonly 프로퍼티",
    "```typescript",
    "class Config {",
    "    constructor(",
    "        public readonly host: string,",
    "        public readonly port: number",
    "    ) {}",
    "}",
    "",
    "const config = new Config('localhost', 3000);",
    "// config.host = '127.0.0.1'; // ❌ 읽기 전용",
    "```",
    "",
    "### 상속 (extends)",
    "```typescript",
    "class Animal {",
    "    constructor(public name: string) {}",
    "",
    "    move(distance: number): void {",
    "        console.log(`${this.name} moved ${distance}m`);",
    "    }",
    "}",
    "",
    "class Dog extends Animal {",
    "    constructor(name: string, public breed: string) {",
    "        super(name); // 부모 생성자 호출 필수",
    "    }",
    "",
    "    bark(): string {",
    "        return 'Woof!';",
    "    }",
    "",
    "    // 오버라이드",
    "    move(distance: number): void {",
    "        console.log('Running...');",
    "        super.move(distance);",
    "    }",
    "}",
    "",
    "const dog = new Dog('Max', 'Golden');",
    "dog.bark();    // 'Woof!'",
    "dog.move(10);  // 'Running...' → 'Max moved 10m'",
    "```",
    "",
    "### 추상 클래스 (Abstract Class)",
    "직접 인스턴스를 만들 수 없고, **하위 클래스에서 반드시 구현**해야 하는 메서드를 정의합니다.",
    "",
    "```typescript",
    "abstract class Shape {",
    "    constructor(public color: string) {}",
    "",
    "    abstract area(): number;        // 하위 클래스에서 구현 필수",
    "    abstract perimeter(): number;   // 하위 클래스에서 구현 필수",
    "",
    "    describe(): string {",
    "        return `${this.color} shape, area: ${this.area()}`;",
    "    }",
    "}",
    "",
    "class Circle extends Shape {",
    "    constructor(color: string, public radius: number) {",
    "        super(color);",
    "    }",
    "",
    "    area(): number {",
    "        return Math.PI * this.radius ** 2;",
    "    }",
    "",
    "    perimeter(): number {",
    "        return 2 * Math.PI * this.radius;",
    "    }",
    "}",
    "",
    "class Rectangle extends Shape {",
    "    constructor(color: string, public width: number, public height: number) {",
    "        super(color);",
    "    }",
    "",
    "    area(): number { return this.width * this.height; }",
    "    perimeter(): number { return 2 * (this.width + this.height); }",
    "}",
    "",
    "// const shape = new Shape('red'); // ❌ 추상 클래스는 인스턴스화 불가",
    "const circle = new Circle('red', 5);",
    "console.log(circle.describe()); // 'red shape, area: 78.53...'",
    "```",
    "",
    "### 인터페이스 구현 (implements)",
    "```typescript",
    "interface Printable {",
    "    print(): void;",
    "}",
    "",
    "interface Loggable {",
    "    log(message: string): void;",
    "}",
    "",
    "class Report implements Printable, Loggable {",
    "    constructor(public title: string) {}",
    "",
    "    print(): void {",
    "        console.log(`Printing: ${this.title}`);",
    "    }",
    "",
    "    log(message: string): void {",
    "        console.log(`[${this.title}] ${message}`);",
    "    }",
    "}",
    "```",
    "",
    "### getter / setter",
    "```typescript",
    "class Temperature {",
    "    private _celsius: number;",
    "",
    "    constructor(celsius: number) {",
    "        this._celsius = celsius;",
    "    }",
    "",
    "    get fahrenheit(): number {",
    "        return this._celsius * 9 / 5 + 32;",
    "    }",
    "",
    "    set fahrenheit(value: number) {",
    "        this._celsius = (value - 32) * 5 / 9;",
    "    }",
    "",
    "    get celsius(): number {",
    "        return this._celsius;",
    "    }",
    "}",
    "",
    "const temp = new Temperature(100);",
    "console.log(temp.fahrenheit); // 212",
    "temp.fahrenheit = 32;",
    "console.log(temp.celsius);    // 0",
    "```",
    "",
    "### static 멤버",
    "```typescript",
    "class MathUtils {",
    "    static PI = 3.14159;",
    "",
    "    static circleArea(radius: number): number {",
    "        return MathUtils.PI * radius ** 2;",
    "    }",
    "}",
    "",
    "console.log(MathUtils.PI);              // 3.14159",
    "console.log(MathUtils.circleArea(5));    // 78.53...",
    "// 인스턴스 없이 클래스 이름으로 직접 접근",
    "```",
    "",
    "---",
    "",
    "## 2. 모듈 (Module)",
    "",
    "TypeScript는 **ES Module** (`import`/`export`) 문법을 사용합니다.",
    "",
    "### Named Export / Import",
    "```typescript",
    "// utils.ts",
    "export function add(a: number, b: number): number {",
    "    return a + b;",
    "}",
    "",
    "export const PI = 3.14159;",
    "",
    "export interface User {",
    "    name: string;",
    "    age: number;",
    "}",
    "```",
    "",
    "```typescript",
    "// main.ts",
    "import { add, PI, User } from './utils';",
    "",
    "console.log(add(1, 2)); // 3",
    "console.log(PI);        // 3.14159",
    "",
    "const user: User = { name: 'haru', age: 25 };",
    "```",
    "",
    "### Default Export / Import",
    "```typescript",
    "// logger.ts",
    "export default class Logger {",
    "    log(message: string): void {",
    "        console.log(`[LOG] ${message}`);",
    "    }",
    "}",
    "```",
    "",
    "```typescript",
    "// main.ts",
    "import Logger from './logger';",
    "",
    "const logger = new Logger();",
    "logger.log('Hello');",
    "```",
    "",
    "### 별칭 (as)",
    "```typescript",
    "import { add as sum } from './utils';",
    "import * as Utils from './utils';",
    "",
    "sum(1, 2);",
    "Utils.add(1, 2);",
    "Utils.PI;",
    "```",
    "",
    "### 타입만 가져오기 (import type)",
    "```typescript",
    "import type { User } from './utils';",
    "",
    "const user: User = { name: 'haru', age: 25 };",
    "```",
    "",
    "런타임에서 타입 정보를 제거하여 **번들 크기를 줄입니다**.",
    "",
    "### Re-export",
    "```typescript",
    "// index.ts (배럴 파일)",
    "export { add, PI } from './utils';",
    "export { default as Logger } from './logger';",
    "export type { User } from './utils';",
    "```",
    "",
    "---",
    "",
    "## 3. 네임스페이스 (Namespace)",
    "",
    "관련된 코드를 **논리적으로 그룹화**합니다. 모듈 시스템 등장 전의 방식이며, 현재는 **모듈 사용이 권장**됩니다.",
    "",
    "```typescript",
    "namespace Validation {",
    "    export function isEmail(value: string): boolean {",
    "        return /^[^@]+@[^@]+$/.test(value);",
    "    }",
    "",
    "    export function isPhone(value: string): boolean {",
    "        return /^\\d{3}-\\d{4}-\\d{4}$/.test(value);",
    "    }",
    "}",
    "",
    "Validation.isEmail('haru@email.com'); // true",
    "Validation.isPhone('010-1234-5678');  // true",
    "```",
    "",
    "---",
    "",
    "## 4. 데코레이터 (Decorator)",
    "",
    "클래스, 메서드, 프로퍼티에 **메타데이터를 추가**하거나 동작을 변경합니다. `tsconfig.json`에서 `experimentalDecorators: true` 설정이 필요합니다.",
    "",
    "### 클래스 데코레이터",
    "```typescript",
    "function Logger(constructor: Function) {",
    "    console.log(`Class created: ${constructor.name}`);",
    "}",
    "",
    "@Logger",
    "class User {",
    "    constructor(public name: string) {}",
    "}",
    "",
    "// 출력: 'Class created: User'",
    "```",
    "",
    "### 데코레이터 팩토리",
    "```typescript",
    "function Logger(prefix: string) {",
    "    return function (constructor: Function) {",
    "        console.log(`${prefix}: ${constructor.name}`);",
    "    };",
    "}",
    "",
    "@Logger('APP')",
    "class User {",
    "    constructor(public name: string) {}",
    "}",
    "// 출력: 'APP: User'",
    "```",
    "",
    "### 메서드 데코레이터",
    "```typescript",
    "function Log(",
    "    target: any,",
    "    propertyKey: string,",
    "    descriptor: PropertyDescriptor",
    ") {",
    "    const original = descriptor.value;",
    "    descriptor.value = function (...args: any[]) {",
    "        console.log(`Calling ${propertyKey} with`, args);",
    "        const result = original.apply(this, args);",
    "        console.log(`Result:`, result);",
    "        return result;",
    "    };",
    "}",
    "",
    "class Calculator {",
    "    @Log",
    "    add(a: number, b: number): number {",
    "        return a + b;",
    "    }",
    "}",
    "",
    "new Calculator().add(1, 2);",
    "// 'Calling add with [1, 2]'",
    "// 'Result: 3'",
    "```",
    "",
    "---",
    "",
    "## 5. 선언 파일 (.d.ts)",
    "",
    "JavaScript 라이브러리에 **타입 정보를 제공**하는 파일입니다.",
    "",
    "### DefinitelyTyped (@types)",
    "```bash",
    "# JavaScript 라이브러리의 타입 설치",
    "npm install --save-dev @types/lodash",
    "npm install --save-dev @types/express",
    "npm install --save-dev @types/node",
    "```",
    "",
    "### 직접 선언 파일 작성",
    "```typescript",
    "// types/my-lib.d.ts",
    "declare module 'my-lib' {",
    "    export function greet(name: string): string;",
    "    export const version: string;",
    "}",
    "```",
    "",
    "### declare를 사용한 전역 선언",
    "```typescript",
    "// global.d.ts",
    "declare const API_URL: string;",
    "declare function log(message: string): void;",
    "",
    "declare interface Window {",
    "    myApp: {",
    "        version: string;",
    "    };",
    "}",
    "```",
    "",
    "---",
    "### 요약",
    "TypeScript 클래스는 **접근 제한자**(public/private/protected), **추상 클래스**, **implements**로 OOP를 강화합니다. 모듈은 **ES Module**(`import`/`export`)을 기본으로 사용하며, `import type`으로 타입만 가져올 수 있습니다. 데코레이터는 클래스/메서드에 메타 기능을 추가하고, `.d.ts` 선언 파일은 JS 라이브러리에 타입 정보를 제공합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
