<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "ts-interface-type-alias",
  title: "TypeScript 인터페이스와 타입 별칭",
  date: "2026-02-24",
  summary: "TypeScript에서 객체 구조를 정의하는 interface와 type의 문법, 확장(extends/&), 선택적·읽기전용 프로퍼티, 인덱스 시그니처, 함수 타입 정의, 그리고 interface vs type 차이를 정리합니다.",
  category: "Coding/JavaScript",
  tags: ["typescript","interface","type","extends","intersection","readonly","basics"],
  content: [
    "## 한 줄 요약",
    "**interface**와 **type alias**는 모두 객체의 구조(Shape)를 정의하지만, interface는 **선언 병합과 extends**에 강하고, type은 **유니언·교차·매핑** 등 유연한 타입 조합에 강합니다.",
    "",
    "---",
    "",
    "## 1. interface (인터페이스)",
    "",
    "객체가 어떤 프로퍼티와 메서드를 가져야 하는지 **계약(Contract)**을 정의합니다.",
    "",
    "### 기본 문법",
    "```typescript",
    "interface User {",
    "    name: string;",
    "    age: number;",
    "    email: string;",
    "}",
    "",
    "const user: User = {",
    "    name: 'haru',",
    "    age: 25,",
    "    email: 'haru@email.com'",
    "};",
    "",
    "// 프로퍼티 누락 → 에러",
    "// const bad: User = { name: 'haru' }; // ❌ age, email 누락",
    "",
    "// 없는 프로퍼티 추가 → 에러",
    "// const bad2: User = { name: 'haru', age: 25, email: 'a', phone: '010' }; // ❌",
    "```",
    "",
    "### 선택적 프로퍼티 (?)",
    "```typescript",
    "interface User {",
    "    name: string;",
    "    age: number;",
    "    email?: string;   // 있어도 되고 없어도 됨",
    "}",
    "",
    "const user1: User = { name: 'haru', age: 25 };                // OK",
    "const user2: User = { name: 'haru', age: 25, email: 'a@b' };  // OK",
    "```",
    "",
    "### 읽기 전용 프로퍼티 (readonly)",
    "```typescript",
    "interface Config {",
    "    readonly apiKey: string;",
    "    readonly baseUrl: string;",
    "    timeout: number;",
    "}",
    "",
    "const config: Config = {",
    "    apiKey: 'abc123',",
    "    baseUrl: 'https://api.example.com',",
    "    timeout: 5000",
    "};",
    "",
    "config.timeout = 3000;  // OK",
    "// config.apiKey = 'xyz'; // ❌ 읽기 전용",
    "```",
    "",
    "### 함수 타입 정의",
    "```typescript",
    "interface MathFunc {",
    "    (a: number, b: number): number;",
    "}",
    "",
    "const add: MathFunc = (a, b) => a + b;",
    "const multiply: MathFunc = (a, b) => a * b;",
    "```",
    "",
    "### 메서드 정의",
    "```typescript",
    "interface User {",
    "    name: string;",
    "    greet(): string;",
    "    setName(name: string): void;",
    "}",
    "",
    "const user: User = {",
    "    name: 'haru',",
    "    greet() { return `Hi, I'm ${this.name}`; },",
    "    setName(name) { this.name = name; }",
    "};",
    "```",
    "",
    "### 인덱스 시그니처 (Index Signature)",
    "프로퍼티 이름을 미리 알 수 없을 때 사용합니다.",
    "",
    "```typescript",
    "interface StringMap {",
    "    [key: string]: string;",
    "}",
    "",
    "const headers: StringMap = {",
    "    'Content-Type': 'application/json',",
    "    'Authorization': 'Bearer token123',",
    "    'X-Custom': 'value'",
    "};",
    "",
    "interface NumberMap {",
    "    [index: number]: string;",
    "}",
    "",
    "const colors: NumberMap = {",
    "    0: 'red',",
    "    1: 'green',",
    "    2: 'blue'",
    "};",
    "```",
    "",
    "### 인터페이스 확장 (extends)",
    "```typescript",
    "interface Animal {",
    "    name: string;",
    "    age: number;",
    "}",
    "",
    "interface Dog extends Animal {",
    "    breed: string;",
    "}",
    "",
    "const myDog: Dog = {",
    "    name: 'Max',",
    "    age: 3,",
    "    breed: 'Golden Retriever'",
    "};",
    "",
    "// 다중 확장",
    "interface Pet extends Animal {",
    "    owner: string;",
    "}",
    "",
    "interface ServiceDog extends Dog, Pet {",
    "    role: string;",
    "}",
    "```",
    "",
    "### 선언 병합 (Declaration Merging)",
    "같은 이름의 interface를 여러 번 선언하면 **자동으로 병합**됩니다.",
    "",
    "```typescript",
    "interface User {",
    "    name: string;",
    "}",
    "",
    "interface User {",
    "    age: number;",
    "}",
    "",
    "// User = { name: string; age: number; }",
    "const user: User = { name: 'haru', age: 25 }; // 둘 다 필요",
    "```",
    "",
    "---",
    "",
    "## 2. type alias (타입 별칭)",
    "",
    "타입에 **이름을 붙이는** 기능입니다. 객체뿐 아니라 **모든 타입 표현식**에 사용할 수 있습니다.",
    "",
    "### 기본 문법",
    "```typescript",
    "type User = {",
    "    name: string;",
    "    age: number;",
    "    email?: string;",
    "};",
    "",
    "const user: User = { name: 'haru', age: 25 };",
    "```",
    "",
    "### 유니언 타입에 이름 붙이기",
    "```typescript",
    "type ID = string | number;",
    "type Status = 'active' | 'inactive' | 'pending';",
    "type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';",
    "",
    "let userId: ID = 'abc';",
    "userId = 123; // OK",
    "",
    "let status: Status = 'active';",
    "// status = 'deleted'; // ❌",
    "```",
    "",
    "### 교차 타입 (Intersection Type) - &",
    "`extends` 대신 `&`로 타입을 합칩니다.",
    "",
    "```typescript",
    "type Animal = {",
    "    name: string;",
    "    age: number;",
    "};",
    "",
    "type DogTraits = {",
    "    breed: string;",
    "};",
    "",
    "type Dog = Animal & DogTraits;",
    "",
    "const myDog: Dog = {",
    "    name: 'Max',",
    "    age: 3,",
    "    breed: 'Golden Retriever'",
    "};",
    "```",
    "",
    "### 함수 타입",
    "```typescript",
    "type MathFunc = (a: number, b: number) => number;",
    "",
    "const add: MathFunc = (a, b) => a + b;",
    "```",
    "",
    "### 튜플 타입",
    "```typescript",
    "type Coordinate = [number, number];",
    "type RGB = [number, number, number];",
    "",
    "const point: Coordinate = [10, 20];",
    "const red: RGB = [255, 0, 0];",
    "```",
    "",
    "### 조건부 타입 (Conditional Type)",
    "```typescript",
    "type IsString<T> = T extends string ? 'yes' : 'no';",
    "",
    "type A = IsString<string>;  // 'yes'",
    "type B = IsString<number>;  // 'no'",
    "```",
    "",
    "---",
    "",
    "## 3. interface vs type 비교",
    "",
    "| 기능 | interface | type |",
    "|------|-----------|------|",
    "| 객체 구조 정의 | ✅ | ✅ |",
    "| 확장 | `extends` | `&` (교차 타입) |",
    "| 유니언 타입 | ❌ | ✅ `string \\| number` |",
    "| 리터럴 타입 | ❌ | ✅ `'a' \\| 'b'` |",
    "| 튜플 타입 | ❌ | ✅ `[string, number]` |",
    "| 선언 병합 | ✅ (자동 병합) | ❌ (중복 선언 에러) |",
    "| 조건부 타입 | ❌ | ✅ |",
    "| 매핑 타입 | ❌ | ✅ |",
    "| implements | ✅ (클래스 구현) | ✅ (객체 타입만) |",
    "",
    "### 언제 무엇을 사용하나?",
    "",
    "| 상황 | 추천 |",
    "|------|------|",
    "| 객체 구조 정의 | **interface** (확장성·선언 병합) |",
    "| 유니언/리터럴 타입 | **type** |",
    "| 함수 타입 | 둘 다 가능 (type이 간결) |",
    "| 라이브러리 API 정의 | **interface** (선언 병합으로 확장 가능) |",
    "| 복잡한 타입 조합 | **type** (조건부·매핑 타입) |",
    "",
    "---",
    "",
    "## 4. 실전 예제",
    "",
    "### API 응답 타입 정의",
    "```typescript",
    "interface ApiResponse<T> {",
    "    status: number;",
    "    message: string;",
    "    data: T;",
    "    timestamp: string;",
    "}",
    "",
    "interface UserData {",
    "    id: number;",
    "    name: string;",
    "    email: string;",
    "}",
    "",
    "type UserResponse = ApiResponse<UserData>;",
    "type UserListResponse = ApiResponse<UserData[]>;",
    "",
    "// 사용",
    "function fetchUser(id: number): Promise<UserResponse> {",
    "    return fetch(`/api/users/${id}`).then(res => res.json());",
    "}",
    "```",
    "",
    "### 이벤트 핸들러 타입",
    "```typescript",
    "type EventHandler = (event: Event) => void;",
    "type ClickHandler = (event: MouseEvent) => void;",
    "",
    "interface ButtonProps {",
    "    label: string;",
    "    onClick: ClickHandler;",
    "    disabled?: boolean;",
    "}",
    "```",
    "",
    "---",
    "### 요약",
    "**interface**는 객체 구조 정의·확장(`extends`)·선언 병합에 적합하고, **type alias**는 유니언·교차·리터럴·조건부 타입 등 **유연한 타입 조합**에 적합합니다. 실무에서는 객체 구조에 `interface`, 나머지에 `type`을 사용하는 것이 일반적입니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
