<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unity-coroutine",
  title: "Coroutine(코루틴)이란?",
  date: "2026-02-17",
  summary: "Coroutine은 실행을 잠시 멈추었다가 다음 프레임이나 조건이 충족되면 이어서 실행하는 함수입니다. 딜레이, 순차 연출, 비동기 대기 등에 사용됩니다.",
  category: "Technology/Unity",
  tags: ["unity","coroutine","ienumerator","yield","async","basics"],
  content: [
    "## 한 줄 요약",
    "**Coroutine(코루틴)**은 `yield return`으로 실행을 **잠시 멈추었다가** 나중에 다시 이어서 실행하는 함수입니다. 일반 함수는 한 번 호출되면 끝까지 실행되지만, 코루틴은 중간에 대기할 수 있습니다.",
    "",
    "## 기본 구조",
    "`IEnumerator`를 반환하고, `yield return`으로 실행을 일시 정지합니다.",
    "",
    "```csharp",
    "using UnityEngine;",
    "using System.Collections;",
    "",
    "public class CoroutineExample : MonoBehaviour",
    "{",
    "    void Start()",
    "    {",
    "        StartCoroutine(MyCoroutine());",
    "    }",
    "",
    "    IEnumerator MyCoroutine()",
    "    {",
    "        Debug.Log(\"시작\");",
    "        yield return null;  // 다음 프레임까지 대기",
    "        Debug.Log(\"1프레임 후\");",
    "        yield return new WaitForSeconds(2f);  // 2초 대기",
    "        Debug.Log(\"2초 후\");",
    "    }",
    "}",
    "```",
    "",
    "## StartCoroutine / StopCoroutine",
    "",
    "| 메서드 | 설명 |",
    "|--------|------|",
    "| StartCoroutine(IEnumerator) | 코루틴 시작, Coroutine 객체 반환 |",
    "| StopCoroutine(Coroutine) | 해당 코루틴 정지 |",
    "| StopAllCoroutines() | 이 오브젝트의 모든 코루틴 정지 |",
    "",
    "```csharp",
    "Coroutine co = StartCoroutine(MyCoroutine());",
    "// ...",
    "StopCoroutine(co);",
    "```",
    "",
    "## yield return 종류",
    "",
    "| 표현 | 대기 조건 |",
    "|------|-----------|",
    "| yield return null | 다음 프레임까지 |",
    "| yield return new WaitForSeconds(초) | 지정한 초만큼 |",
    "| yield return new WaitForSecondsRealtime(초) | Time.scale 영향 없이 실제 시간 |",
    "| yield return new WaitForEndOfFrame() | 프레임 렌더링 끝까지 |",
    "| yield return new WaitForFixedUpdate() | 다음 FixedUpdate까지 |",
    "| yield return new WaitUntil(() => 조건) | 조건이 true 될 때까지 |",
    "| yield return new WaitWhile(() => 조건) | 조건이 false 될 때까지 |",
    "| yield return StartCoroutine(다른코루틴) | 다른 코루틴이 끝날 때까지 |",
    "",
    "## 예제 1: 딜레이 후 실행",
    "",
    "```csharp",
    "IEnumerator DelayedAction()",
    "{",
    "    yield return new WaitForSeconds(3f);",
    "    Debug.Log(\"3초 경과\");",
    "    DoSomething();",
    "}",
    "",
    "void Start()",
    "{",
    "    StartCoroutine(DelayedAction());",
    "}",
    "```",
    "",
    "## 예제 2: 순차 연출 (여러 단계)",
    "",
    "```csharp",
    "IEnumerator Sequence()",
    "{",
    "    ShowText(\"준비\");",
    "    yield return new WaitForSeconds(1f);",
    "    ShowText(\"시작!\");",
    "    yield return new WaitForSeconds(2f);",
    "    StartGame();",
    "}",
    "```",
    "",
    "## 예제 3: 조건 만족할 때까지 대기",
    "",
    "```csharp",
    "IEnumerator WaitForPlayerReady()",
    "{",
    "    yield return new WaitUntil(() => playerIsReady);",
    "    StartCountdown();",
    "}",
    "```",
    "",
    "## 예제 4: 코루틴 안에서 다른 코루틴 대기",
    "",
    "```csharp",
    "IEnumerator MainFlow()",
    "{",
    "    yield return StartCoroutine(FadeIn());",
    "    yield return new WaitForSeconds(1f);",
    "    yield return StartCoroutine(FadeOut());",
    "}",
    "```",
    "",
    "## 예제 5: 매 프레임 체크 (Update 대신)",
    "",
    "```csharp",
    "IEnumerator CheckEveryFrame()",
    "{",
    "    while (true)",
    "    {",
    "        if (Input.GetKeyDown(KeyCode.Space))",
    "            break;",
    "        yield return null;",
    "    }",
    "    Debug.Log(\"스페이스 눌림\");",
    "}",
    "```",
    "",
    "## 주의사항",
    "",
    "### 1) GameObject가 비활성화되면 코루틴 중단",
    "`SetActive(false)` 하면 해당 오브젝트의 코루틴이 모두 멈춥니다.",
    "",
    "### 2) Time.scale과 WaitForSeconds",
    "`WaitForSeconds`는 `Time.timeScale` 영향을 받습니다. 게임이 일시정지(Time.timeScale = 0)면 대기 시간도 멈춥니다. 실제 시간 기준이 필요하면 `WaitForSecondsRealtime`을 사용합니다.",
    "",
    "### 3) StartCoroutine은 MonoBehaviour에서만",
    "`StartCoroutine`을 호출하려면 해당 스크립트가 `MonoBehaviour`를 상속한 **활성화된** 오브젝트에 붙어 있어야 합니다.",
    "",
    "### 4) 매개변수 전달",
    "```csharp",
    "StartCoroutine(MyCoroutine(5f));",
    "IEnumerator MyCoroutine(float delay)",
    "{",
    "    yield return new WaitForSeconds(delay);",
    "    // ...",
    "}",
    "```",
    "",
    "## Coroutine vs Invoke / InvokeRepeating",
    "| 방식 | 특징 |",
    "|------|------|",
    "| Coroutine | 조건 대기, 순차 연출, 유연함 |",
    "| Invoke(\"메서드명\", delay) | 단순 딜레이 1회, 문자열로 메서드 지정 |",
    "| InvokeRepeating | 반복 호출, 취소는 CancelInvoke |",
    "",
    "복잡한 흐름은 코루틴이 적합합니다.",
    "",
    "## Coroutine vs async/await (C#)",
    "Unity 2023+ 에서는 `async/await`와 `UniTask` 등으로 비동기를 처리할 수도 있습니다. 기존 프로젝트와 호환성을 위해 코루틴은 여전히 많이 쓰입니다.",
    "",
    "---",
    "### 요약",
    "Coroutine은 `IEnumerator`와 `yield return`으로 실행을 잠시 멈추고 다시 이어갈 수 있는 함수입니다. `WaitForSeconds`, `WaitUntil` 등으로 딜레이·조건 대기·순차 연출을 구현할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
