<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unity-animator-animation-clip",
  title: "Animator와 Animation Clip이란?",
  date: "2026-02-18",
  summary: "Animation Clip은 키프레임 기반 애니메이션 데이터이고, Animator는 Animator Controller를 통해 클립을 재생·전환합니다. 관계, 설정, 스크립트 제어를 정리합니다.",
  category: "Technology/Unity",
  tags: ["unity","animator","animation","animation-clip","animator-controller","basics"],
  content: [
    "## 한 줄 요약",
    "**Animation Clip**은 시간에 따른 Transform·프로퍼티 변화를 담은 에셋이고, **Animator**는 Animator Controller에 따라 클립을 재생·전환하는 컴포넌트입니다.",
    "",
    "## 관계 정리",
    "",
    "| 개념 | 역할 |",
    "|------|------|",
    "| Animation Clip | 키프레임·커브로 정의된 애니메이션 데이터 (재생 단위) |",
    "| Animator Controller | 여러 클립과 전환 조건을 담은 상태 머신 (.controller) |",
    "| Animator | Animator Controller를 실행해 클립을 재생하는 컴포넌트 |",
    "",
    "Animator에 Animator Controller를 할당하고, 그 안의 각 State가 Animation Clip을 참조합니다.",
    "",
    "## Animation Clip",
    "",
    "Animation Clip은 **키프레임**과 **애니메이션 커브**로 구성됩니다.",
    "",
    "| 내용 | 설명 |",
    "|------|------|",
    "| 키프레임 | 시간별로 Transform(위치·회전·스케일)·프로퍼티 값 |",
    "| 커브 | 키프레임 사이를 보간한 곡선 (선형·베지어 등) |",
    "| 길이 | 클립 재생 시간 (프레임 또는 초) |",
    "",
    "### 생성 방법",
    "- **Animation 창** (Window → Animation): 키프레임 직접 추가",
    "- **외부 모델** (FBX 등) import 시 포함된 클립 사용",
    "- **스크립트**: `AnimationClip.SetCurve`로 런타임 생성",
    "",
    "### Import Settings",
    "FBX·모델에서 가져온 클립은 Rig 설정(R humanoid/Generic/Legacy)과 맞아야 합니다.",
    "",
    "## Animator Controller",
    "",
    "Animator Controller는 **상태 머신(State Machine)**입니다.",
    "",
    "| 요소 | 설명 |",
    "|------|------|",
    "| State | 애니메이션 상태, 각각 하나의 Clip 연결 |",
    "| Transition | 상태 간 전환 조건 (파라미터·시간 등) |",
    "| Parameter | Bool, Int, Float, Trigger 등 전환 트리거 |",
    "| Any State | 어떤 상태에서든 전환 가능한 특수 상태 |",
    "",
    "### 레이어(Layer)",
    "여러 레이어로 상체·하체·표정을 따로 제어할 수 있습니다. Avatar Mask로 적용 부위를 제한합니다.",
    "",
    "## Animator 컴포넌트",
    "",
    "| 프로퍼티 | 설명 |",
    "|----------|------|",
    "| Controller | 연결할 Animator Controller |",
    "| Avatar | Humanoid 리깅 시 사용하는 Avatar |",
    "| Apply Root Motion | 캐릭터 루트를 애니메이션으로 이동시킬지 |",
    "| Update Mode | Normal, Animate Physics, Unscaled Time |",
    "| Culling Mode | Always Animate, Cull Update Transforms, Cull Completely |",
    "",
    "### Animator vs Animation (Legacy)",
    "| 컴포넌트 | 특징 |",
    "|----------|------|",
    "| Animator | Mecanim, 상태 머신, 블렌드 트리, 레이어 |",
    "| Animation (Legacy) | 구형, 단일 클립 재생·교차 페이드 |",
    "",
    "새 프로젝트는 Animator(Mecanim)를 사용합니다.",
    "",
    "## 스크립트에서 제어",
    "",
    "### 파라미터 설정",
    "```csharp",
    "using UnityEngine;",
    "",
    "public class AnimControl : MonoBehaviour",
    "{",
    "    Animator anim;",
    "",
    "    void Start() { anim = GetComponent<Animator>(); }",
    "",
    "    void Update()",
    "    {",
    "        anim.SetFloat(\"Speed\", moveSpeed);",
    "        anim.SetBool(\"IsGrounded\", isGrounded);",
    "        anim.SetInteger(\"State\", stateIndex);",
    "",
    "        if (Input.GetButtonDown(\"Fire1\"))",
    "            anim.SetTrigger(\"Attack\");",
    "    }",
    "}",
    "```",
    "",
    "### 주요 메서드",
    "| 메서드 | 설명 |",
    "|--------|------|",
    "| SetFloat(name, value) | Float 파라미터 설정 |",
    "| SetBool(name, value) | Bool 파라미터 설정 |",
    "| SetInteger(name, value) | Int 파라미터 설정 |",
    "| SetTrigger(name) | Trigger 파라미터 발동 (한 번만) |",
    "| ResetTrigger(name) | Trigger 초기화 |",
    "| Play(stateName) | 특정 상태로 즉시 전환 |",
    "| GetCurrentAnimatorStateInfo(layer) | 현재 재생 중인 상태 정보 |",
    "",
    "### 현재 재생 상태 확인",
    "```csharp",
    "AnimatorStateInfo info = anim.GetCurrentAnimatorStateInfo(0);",
    "if (info.IsName(\"Attack\") && info.normalizedTime >= 1f)",
    "{",
    "    // 공격 애니메이션 종료 시 처리",
    "}",
    "```",
    "",
    "### 클립 교체 (런타임)",
    "Animator Controller 안의 State가 참조하는 Clip을 바꾸려면 Runtime Animator Controller를 스크립트로 생성하거나, AnimatorOverrideController를 사용합니다.",
    "",
    "```csharp",
    "AnimatorOverrideController over = new AnimatorOverrideController(anim.runtimeAnimatorController);",
    "over[\"IdleClip\"] = myCustomIdleClip;",
    "anim.runtimeAnimatorController = over;",
    "```",
    "",
    "## Root Motion",
    "",
    "Apply Root Motion이 켜져 있으면, 애니메이션 클립에 기록된 **루트 노드 이동**이 캐릭터 Transform에 적용됩니다. 꺼두면 스크립트로 직접 이동해야 합니다.",
    "",
    "## 주의사항",
    "",
    "### 1) Animator와 물리",
    "Rigidbody가 있는 캐릭터에서 Root Motion을 쓸 때는 Animator의 Update Mode를 **Animate Physics**로 두면 물리와 동기화됩니다.",
    "",
    "### 2) Trigger 중복",
    "Trigger는 전환 후 자동 초기화됩니다. 같은 프레임에 여러 번 SetTrigger를 호출하면 한 번만 반영될 수 있습니다.",
    "",
    "### 3) Transition Duration",
    "Transition Time이 0이면 즉시 전환되고, 0보다 크면 블렌딩됩니다.",
    "",
    "---",
    "### 요약",
    "Animation Clip은 애니메이션 데이터, Animator Controller는 상태 머신, Animator는 이를 실행하는 컴포넌트입니다. SetFloat·SetBool·SetTrigger로 파라미터를 조정해 전환을 제어합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
