<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unity-world-local-coordinates",
  title: "월드 좌표와 로컬(상대) 좌표",
  date: "2026-02-17",
  summary: "Unity에서 월드 스페이스는 씬 전체의 기준 좌표계이고, 로컬 스페이스는 부모 Transform 기준의 상대 좌표계입니다. position과 localPosition, Translate/Rotate의 Space 옵션을 이해하는 기초입니다.",
  category: "Technology/Unity",
  tags: ["unity","coordinate","world","local","transform","basics"],
  content: [
    "## 한 줄 요약",
    "- **월드 좌표(World Space)**: 씬 전체가 공유하는 하나의 기준 좌표계",
    "- **로컬 좌표(Local Space)**: 부모 Transform 기준의 상대 좌표계",
    "",
    "## 왜 두 종류가 있나",
    "오브젝트가 부모 아래 있으면, 두 가지 \"위치\"를 동시에 가집니다.",
    "",
    "- **월드 위치**: 씬의 원점(0, 0, 0)에서 봤을 때의 좌표",
    "- **로컬 위치**: 부모의 pivot에서 봤을 때의 상대 좌표",
    "",
    "부모가 움직이거나 회전하면 자식의 **월드 위치**는 바뀌지만, **로컬 위치**는 그대로일 수 있습니다. (자식이 부모를 따라가기 때문)",
    "",
    "## 좌표계 비교",
    "",
    "| 구분 | 월드 스페이스(World) | 로컬 스페이스(Local) |",
    "|------|----------------------|----------------------|",
    "| 기준점 | 씬 원점 (0, 0, 0) | 부모 Transform의 pivot |",
    "| X/Y/Z 방향 | 씬에 고정 (오른손법칙) | 부모 회전에 따라 변함 |",
    "| 부모 없는 경우 | 로컬 = 월드 | 로컬 = 월드 |",
    "",
    "## Transform 프로퍼티 매핑",
    "",
    "| 목적 | 월드 | 로컬 |",
    "|------|------|------|",
    "| 위치 | position | localPosition |",
    "| 회전 | rotation | localRotation |",
    "| 각도(Euler) | (rotation → Euler) | localEulerAngles |",
    "| 크기 | lossyScale (읽기전용) | localScale |",
    "",
    "`lossyScale`은 부모 스케일이 반영된 최종 크기이며, 수정할 수 없습니다. 크기 변경은 `localScale`로 합니다.",
    "",
    "## 메서드의 Space 옵션",
    "`Translate()`, `Rotate()` 등은 `Space` 인자로 기준을 선택합니다.",
    "",
    "```csharp",
    "// Space.Self: 자신의 앞/오른쪽/위 방향 기준",
    "transform.Translate(Vector3.forward * 1f, Space.Self);",
    "",
    "// Space.World: 씬의 X/Y/Z 방향 기준",
    "transform.Translate(Vector3.up * 1f, Space.World);",
    "```",
    "",
    "| Space | 축·방향 기준 |",
    "|-------|-------------|",
    "| Space.Self | 오브젝트 자신의 로컬 축 (forward, right, up) |",
    "| Space.World | 씬의 고정 축 (World X, Y, Z) |",
    "",
    "## 좌표 변환",
    "월드 ↔ 로컬 변환이 필요할 때 사용합니다.",
    "",
    "```csharp",
    "// 로컬 좌표 → 월드 좌표",
    "Vector3 worldPos = transform.TransformPoint(localPos);",
    "Vector3 worldDir = transform.TransformDirection(localDir);",
    "",
    "// 월드 좌표 → 로컬 좌표",
    "Vector3 localPos = transform.InverseTransformPoint(worldPos);",
    "Vector3 localDir = transform.InverseTransformDirection(worldDir);",
    "```",
    "",
    "| 메서드 | 용도 |",
    "|--------|------|",
    "| TransformPoint | 점(position) 변환 |",
    "| InverseTransformPoint | 점 역변환 |",
    "| TransformDirection | 방향 벡터 변환 (길이 무시) |",
    "| InverseTransformDirection | 방향 역변환 |",
    "",
    "## 예제: 자식 오브젝트의 월드 위치 구하기",
    "",
    "```csharp",
    "using UnityEngine;",
    "",
    "public class CoordinateExample : MonoBehaviour",
    "{",
    "    void Start()",
    "    {",
    "        // 부모 기준 상대 위치 (Inspector 값과 동일)",
    "        Vector3 local = transform.localPosition;",
    "        Debug.Log(\"Local: \" + local);",
    "",
    "        // 씬 기준 절대 위치",
    "        Vector3 world = transform.position;",
    "        Debug.Log(\"World: \" + world);",
    "",
    "        // 로컬 (1, 0, 0)이 월드에서 어디인지",
    "        Vector3 worldOfLocalRight = transform.TransformPoint(Vector3.right);",
    "        Debug.Log(\"World of local (1,0,0): \" + worldOfLocalRight);",
    "    }",
    "}",
    "```",
    "",
    "## 예제: 부모 회전과 Translate Space",
    "",
    "```csharp",
    "void Update()",
    "{",
    "    // Space.Self: 앞쪽 = 오브젝트가 바라보는 방향",
    "    transform.Translate(Vector3.forward * 2f * Time.deltaTime, Space.Self);",
    "",
    "    // Space.World: 앞쪽 = 씬의 Z+ 방향 (회전과 무관)",
    "    transform.Translate(Vector3.forward * 2f * Time.deltaTime, Space.World);",
    "}",
    "```",
    "",
    "오브젝트가 Y축 기준 90° 회전해 있다면:",
    "- `Space.Self` → 실제로는 씬의 X+ 방향으로 이동",
    "- `Space.World` → 씬의 Z+ 방향으로 이동",
    "",
    "## 언제 사용할까",
    "",
    "| 상황 | 추천 |",
    "|------|------|",
    "| 캐릭터가 바라보는 방향으로 이동 | Translate(..., Space.Self) |",
    "| 점프, 중력 등 항상 위/아래 | Translate(..., Space.World) |",
    "| UI, 물리 충돌 등 씬 절대 좌표 | position, worldPosition |",
    "| 부모 안에서 상대 배치 | localPosition |",
    "",
    "---",
    "### 요약",
    "월드 좌표는 씬 기준, 로컬 좌표는 부모 기준입니다. `position`/`localPosition`, `Translate`/`Rotate`의 Space 옵션, `TransformPoint`/`InverseTransformPoint`로 서로 변환할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
