<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unity-texture-shader-material",
  title: "텍스처, 셰이더, 머터리얼이란?",
  date: "2026-02-18",
  summary: "텍스처는 2D 이미지 데이터, 셰이더는 GPU가 픽셀을 그리는 방법, 머터리얼은 그 둘을 조합해 오브젝트 표면을 정의합니다. Unity 렌더링의 핵심 개념을 정리합니다.",
  category: "Technology/Unity",
  tags: ["unity","texture","shader","material","rendering","graphics","basics"],
  content: [
    "## 한 줄 요약",
    "**텍스처**는 2D 이미지(색상·높이 등) 데이터이고, **셰이더**는 GPU가 화면에 픽셀을 그리는 **방법**이며, **머터리얼**은 셰이더와 텍스처·색·옵션을 묶어 **표면 표현을 정의**하는 에셋입니다.",
    "",
    "## 관계 정리",
    "",
    "| 개념 | 역할 | 비유 |\n|------|------|------|\n| 텍스처 | 이미지 데이터 (알베도, 노멀, 이펙트용 등) | 도료의 원료 |\n| 셰이더 | 픽셀을 어떻게 계산할지 정한 코드 | 도료를 바르는 방법/공식 |\n| 머터리얼 | 셰이더 + 텍스처 + 설정값을 묶은 에셋 | 완성된 도료(색·질감 포함) |",
    "",
    "머터리얼을 Mesh Renderer 등에 할당하면 오브젝트가 그 형태로 렌더링됩니다.",
    "",
    "## 텍스처(Texture)",
    "",
    "텍스처는 **2D 이미지**입니다. 보통 다음과 같이 쓰입니다.",
    "",
    "| 용도 | 설명 |\n|------|------|\n| Albedo/Diffuse | 표면 기본 색 (메인 텍스처) |\n| Normal Map | 법선 맵, 요철·굴곡 표현 (조명 반응) |\n| Metallic/Roughness | 금속성·거칠기 (PBR) |\n| Emission | 빛나는 부분 |\n| Height/Displacement | 표면 높이 |\n| Mask/AO | 그림자·오클루전 등 |",
    "",
    "### Import Settings",
    "Project에서 텍스처 선택 후 Inspector에서 설정합니다.",
    "",
    "| 설정 | 설명 |\n|------|------|\n| Texture Type | Default, Normal map, Sprite 등 |\n| Max Size | 해상도 상한 (512, 1024, 2048 등) |\n| Generate Mip Maps | 거리에 따라 작은 버전 생성 (성능·거리 흐릿함) |\n| sRGB | 색상 텍스처에 체크, 노멀맵은 해제 |\n| Wrap Mode | Repeat(타일), Clamp(끝 고정) |",
    "",
    "## 셰이더(Shader)",
    "",
    "셰이더는 **GPU가 꼭짓점·픽셀을 어떻게 계산할지** 적어둔 프로그램입니다.",
    "",
    "### Shader 파이프라인 (간단)",
    "1. **Vertex Shader**: 정점 위치·UV 변환",
    "2. **Fragment/Pixel Shader**: 각 픽셀의 최종 색상 계산",
    "",
    "### Unity Built-in vs URP/HDRP",
    "| 종류 | 특징 |\n|------|------|\n| Built-in | 레거시, 다양한 내장 셰이더 |\n| URP (Universal RP) | 경량·모바일·일반 게임에 적합 |\n| HDRP | 고품질, PC·콘솔 등 |",
    "",
    "프로젝트에 따라 사용 가능한 셰이더가 달라집니다.",
    "",
    "### Shader Graph (URP)",
    "코드 대신 **노드 그래프**로 셰이더를 만듭니다. HLSL 없이도 커스텀 효과를 만들 수 있습니다.",
    "",
    "## 머터리얼(Material)",
    "",
    "머터리얼은 **셰이더 + 프로퍼티 값**을 저장한 에셋입니다.",
    "",
    "### 프로퍼티 예시",
    "- `_MainTex` (Albedo): 메인 텍스처",
    "- `_Color`: 메인 색 (텍스처에 곱함)",
    "- `_Metallic`, `_Glossiness` / `_Smoothness`: PBR 재질 값",
    "- `_BumpMap`: 노멀 맵",
    "- `_EmissionColor`: 발광색",
    "",
    "### 머터리얼 생성·할당",
    "1. Project 창 우클릭 → **Create → Material**",
    "2. Inspector에서 **Shader** 선택, 텍스처·색 등 설정",
    "3. 머터리얼을 **Mesh Renderer**의 Material 슬롯에 드래그",
    "",
    "## 스크립트에서 다루기",
    "",
    "```csharp",
    "using UnityEngine;",
    "",
    "public class MaterialExample : MonoBehaviour",
    "{",
    "    [SerializeField] Material mat;",
    "    [SerializeField] Texture newTexture;",
    "",
    "    void Start()",
    "    {",
    "        // 머터리얼 프로퍼티 변경",
    "        mat.SetTexture(\"_MainTex\", newTexture);",
    "        mat.SetColor(\"_Color\", Color.red);",
    "        mat.SetFloat(\"_Metallic\", 0.5f);",
    "    }",
    "}",
    "```",
    "",
    "### 런타임에 머터리얼 복제",
    "원본 에셋을 바꾸지 않으려면 인스턴스를 만들어 사용합니다.",
    "",
    "```csharp",
    "Renderer renderer = GetComponent<Renderer>();",
    "renderer.material.SetColor(\"_Color\", Color.blue);  // 인스턴스 생성 (메모리 주의)",
    "// 영구 수정이 아니라면 sharedMaterial로 참조만",
    "```",
    "",
    "`renderer.material`은 자동으로 **인스턴스**를 만들고, `renderer.sharedMaterial`은 프로젝트 에셋을 직접 참조합니다.",
    "",
    "## 텍스처 vs 스프라이트",
    "| 타입 | 용도 |\n|------|------|\n| Texture | 3D 오브젝트, 셰이더에 사용 |\n| Sprite | 2D UI, 2D 게임 스프라이트 |",
    "",
    "이미지를 **Sprite**로 쓰려면 Texture Type을 Sprite(2D and UI)로 바꿉니다.",
    "",
    "## 주의사항",
    "",
    "### 1) 메모리",
    "텍스처 해상도가 클수록 메모리를 많이 씁니다. Max Size, Mip Map, 압축 형식을 잘 맞춥니다.",
    "",
    "### 2) Draw Call",
    "머터리얼이 다르면 보통 **배칭이 깨져** Draw Call이 늘어납니다. 같은 머터리얼·셰이더를 쓰는 오브젝트가 많을수록 배칭에 유리합니다.",
    "",
    "### 3) Material Instancing",
    "`renderer.material`을 반복 호출하면 매번 새 인스턴스가 생깁니다. 필요한 곳에서 한 번 캐시해서 재사용합니다.",
    "",
    "---",
    "### 요약",
    "텍스처는 이미지 데이터, 셰이더는 렌더링 규칙, 머터리얼은 그 조합으로 표면을 정의합니다. 이 세 가지를 이해하면 Unity 렌더링과 비주얼 작업의 기반을 잡을 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
