<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unity-quaternion",
  title: "Quaternion(쿼터니언)이란?",
  date: "2026-02-17",
  summary: "Quaternion은 3D 회전을 나타내는 4D 수입니다. Unity에서 Transform의 rotation은 내부적으로 쿼터니언을 사용하며, 짐벌락을 피하고 부드러운 회전 보간(Slerp)에 유리합니다.",
  category: "Technology/Unity",
  tags: ["unity","quaternion","rotation","3d","math","basics"],
  content: [
    "## 한 줄 요약",
    "**Quaternion(쿼터니언)**은 3D 공간에서의 회전을 나타내는 4개의 실수(x, y, z, w)로 구성된 수입니다. Unity의 `transform.rotation`은 내부적으로 쿼터니언을 사용합니다.",
    "",
    "## 왜 Euler 각 대신 쿼터니언을 쓰나",
    "Euler 각(X, Y, Z)은 직관적이지만 몇 가지 문제가 있습니다.",
    "",
    "| Euler 각 | 쿼터니언 |",
    "|-----------|----------|",
    "| 짐벌락(Gimbal Lock): 90°에서 한 축 손실 | 짐벌락 없음 |",
    "| 보간 시 궤적이 불규칙 | Slerp로 부드러운 보간 |",
    "| 각도 순서(XYZ vs ZYX 등)에 따라 결과 다름 | 일관된 표현 |",
    "| 직관적 (Inspector 표시용) | 직접 해석 어려움 |",
    "",
    "Unity는 Inspector에는 Euler 각으로 보여주고, 내부 연산은 쿼터니언으로 처리합니다.",
    "",
    "## Quaternion 구조",
    "```csharp",
    "Quaternion q;  // (x, y, z, w) 4개 성분",
    "// q.x, q.y, q.z, q.w 로 접근",
    "```",
    "",
    "직접 (x, y, z, w)를 다루기보다는 **정적 메서드**로 생성하는 경우가 대부분입니다.",
    "",
    "## 자주 쓰는 정적 메서드",
    "",
    "### Quaternion.Euler",
    "Euler 각(도 단위)을 쿼터니언으로 변환합니다.",
    "",
    "```csharp",
    "Quaternion q = Quaternion.Euler(0f, 45f, 0f);  // Y축 45°",
    "transform.rotation = q;",
    "```",
    "",
    "### Quaternion.LookRotation",
    "특정 방향을 **바라보는** 회전을 만듭니다. `Transform.LookAt`과 비슷하지만, 회전값만 반환합니다.",
    "",
    "```csharp",
    "Vector3 dir = target.position - transform.position;",
    "Quaternion look = Quaternion.LookRotation(dir);",
    "transform.rotation = look;",
    "```",
    "",
    "`worldUp`을 지정할 수 있습니다 (기본값: Vector3.up).",
    "",
    "### Quaternion.Identity",
    "회전이 없는 상태 (0°). 초기값이나 리셋할 때 사용합니다.",
    "",
    "```csharp",
    "transform.rotation = Quaternion.identity;",
    "```",
    "",
    "### Quaternion.Slerp (구면 선형 보간)",
    "두 회전 사이를 **부드럽게** 보간합니다. 캐릭터가 천천히 턴할 때 유용합니다.",
    "",
    "```csharp",
    "Quaternion from = transform.rotation;",
    "Quaternion to = Quaternion.Euler(0f, 90f, 0f);",
    "transform.rotation = Quaternion.Slerp(from, to, t);  // t: 0~1",
    "```",
    "",
    "### Quaternion.Lerp",
    "Slerp보다 빠르지만, 각도가 클 때 약간 불규칙할 수 있습니다. 대부분은 Lerp로도 충분합니다.",
    "",
    "```csharp",
    "transform.rotation = Quaternion.Lerp(from, to, t);",
    "```",
    "",
    "## 프로퍼티 및 연산",
    "",
    "| 항목 | 설명 |",
    "|------|------|",
    "| Quaternion * Quaternion | 회전 합성 (순서 중요) |",
    "| Quaternion * Vector3 | 벡터를 해당 회전만큼 변환 |",
    "| Quaternion.Inverse(q) | 역회전 |",
    "| Quaternion.Angle(a, b) | 두 회전 사이 각도(도) |",
    "",
    "```csharp",
    "// A 회전 후 B 회전 적용",
    "Quaternion combined = qB * qA;",
    "",
    "// 벡터를 회전시키기",
    "Vector3 rotated = q * Vector3.forward;",
    "```",
    "",
    "## 예제: 부드러운 회전 추적",
    "",
    "```csharp",
    "using UnityEngine;",
    "",
    "public class QuaternionExample : MonoBehaviour",
    "{",
    "    [SerializeField] Transform target;",
    "    [SerializeField] float turnSpeed = 5f;",
    "",
    "    void Update()",
    "    {",
    "        if (target == null) return;",
    "",
    "        Vector3 dir = target.position - transform.position;",
    "        dir.y = 0f;  // 수평 회전만",
    "        if (dir.sqrMagnitude < 0.01f) return;",
    "",
    "        Quaternion targetRot = Quaternion.LookRotation(dir);",
    "        transform.rotation = Quaternion.Slerp(",
    "            transform.rotation,",
    "            targetRot,",
    "            turnSpeed * Time.deltaTime",
    "        );",
    "    }",
    "}",
    "```",
    "",
    "## 예제: Euler ↔ Quaternion 변환",
    "",
    "```csharp",
    "// Euler → Quaternion",
    "Vector3 euler = new Vector3(10f, 45f, 0f);",
    "Quaternion q = Quaternion.Euler(euler);",
    "",
    "// Quaternion → Euler (Transform 통해)",
    "Vector3 eulerAngles = transform.eulerAngles;",
    "// 또는",
    "Vector3 e = q.eulerAngles;",
    "```",
    "",
    "## Euler vs Quaternion 선택 가이드",
    "",
    "| 상황 | 추천 |",
    "|------|------|",
    "| Inspector에서 수동 배치 | Euler (직관적) |",
    "| 스크립트로 절대 회전 설정 | Quaternion.Euler() |",
    "| 부드러운 회전 보간 | Quaternion.Slerp / Lerp |",
    "| 방향 벡터로 회전 만들기 | Quaternion.LookRotation |",
    "| 회전 합성, 벡터 변환 | Quaternion 연산 |",
    "",
    "---",
    "### 요약",
    "Quaternion은 Unity에서 3D 회전의 내부 표현입니다. 짐벌락을 피하고 부드러운 보간에 유리합니다. `Quaternion.Euler`, `LookRotation`, `Slerp`, `identity`를 익히면 대부분의 회전 작업을 처리할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
