<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unity-ui-toolkit",
  title: "UI Toolkit이란?",
  date: "2026-02-24",
  summary: "UI Toolkit은 Unity의 차세대 UI 시스템으로, 웹(HTML/CSS)과 유사한 UXML·USS 기반 선언적 UI를 제공합니다. 에디터 확장과 런타임 UI 모두에 사용할 수 있습니다.",
  category: "Technology/Unity",
  tags: ["unity","ui-toolkit","uxml","uss","visual-element","runtime-ui","basics"],
  content: [
    "## 한 줄 요약",
    "**UI Toolkit**은 UXML(구조)과 USS(스타일)로 UI를 선언적으로 구성하는 Unity의 차세대 UI 프레임워크입니다. 에디터 확장뿐 아니라 런타임 게임 UI에도 사용할 수 있습니다.",
    "",
    "## Unity UI 시스템 비교",
    "",
    "| 시스템 | 등장 시기 | 특징 | 적합 용도 |",
    "|--------|----------|------|-----------|",
    "| IMGUI | 초기 | 코드 기반 즉시 모드, 매 프레임 그리기 | 에디터 디버그 UI |",
    "| uGUI (Canvas) | Unity 4.6 | GameObject + RectTransform 기반 | 기존 게임 런타임 UI |",
    "| UI Toolkit | Unity 2019+ | UXML/USS 선언적, Retained Mode | 에디터 확장 + 런타임 UI |",
    "",
    "UI Toolkit은 웹의 HTML/CSS 모델과 유사하게 구조(UXML)와 스타일(USS)을 분리합니다.",
    "",
    "## 핵심 개념",
    "",
    "### VisualElement",
    "UI Toolkit의 **모든 요소의 기본 클래스**입니다. 웹의 `<div>`에 해당하며, 트리 구조로 중첩됩니다.",
    "",
    "```csharp",
    "var root = new VisualElement();",
    "var label = new Label(\"Hello UI Toolkit\");",
    "root.Add(label);",
    "```",
    "",
    "### UXML (구조)",
    "UI의 계층 구조를 XML로 정의합니다. 웹의 HTML에 해당합니다.",
    "",
    "```xml",
    "<ui:UXML xmlns:ui=\"UnityEngine.UIElements\">",
    "    <ui:VisualElement class=\"container\">",
    "        <ui:Label text=\"제목\" class=\"title\" />",
    "        <ui:Button text=\"클릭\" name=\"my-button\" />",
    "        <ui:TextField label=\"이름\" name=\"name-field\" />",
    "    </ui:VisualElement>",
    "</ui:UXML>",
    "```",
    "",
    "### USS (스타일)",
    "UI의 시각적 스타일을 정의합니다. 웹의 CSS에 해당합니다.",
    "",
    "```css",
    ".container {",
    "    padding: 10px;",
    "    background-color: rgb(40, 40, 40);",
    "    flex-direction: column;",
    "}",
    "",
    ".title {",
    "    font-size: 24px;",
    "    color: white;",
    "    -unity-font-style: bold;",
    "    margin-bottom: 8px;",
    "}",
    "",
    "Button {",
    "    width: 200px;",
    "    height: 40px;",
    "}",
    "```",
    "",
    "### USS 선택자",
    "| 선택자 | 문법 | 설명 |",
    "|--------|------|------|",
    "| 타입 | `Button` | 특정 요소 타입 전체 |",
    "| 클래스 | `.title` | class 속성이 일치하는 요소 |",
    "| 이름 | `#my-button` | name 속성이 일치하는 요소 |",
    "| 자식 | `.container > Label` | 직계 자식만 |",
    "| 후손 | `.container Label` | 모든 하위 Label |",
    "| 가상 클래스 | `Button:hover` | 상태 기반 (hover, active, focus 등) |",
    "",
    "## Flexbox 레이아웃",
    "",
    "UI Toolkit은 **Flexbox**로 레이아웃을 배치합니다. 웹 CSS의 Flexbox와 거의 동일합니다.",
    "",
    "| USS 프로퍼티 | 설명 | 기본값 |",
    "|-------------|------|--------|",
    "| flex-direction | 자식 배치 방향 (row, column) | column |",
    "| justify-content | 주축 정렬 (flex-start, center, flex-end, space-between) | flex-start |",
    "| align-items | 교차축 정렬 (stretch, center, flex-start, flex-end) | stretch |",
    "| flex-grow | 남은 공간 차지 비율 | 0 |",
    "| flex-shrink | 축소 비율 | 1 |",
    "",
    "```css",
    ".horizontal-row {",
    "    flex-direction: row;",
    "    justify-content: space-between;",
    "    align-items: center;",
    "}",
    "```",
    "",
    "## 기본 컨트롤",
    "",
    "| 컨트롤 | 설명 |",
    "|--------|------|",
    "| Label | 텍스트 표시 |",
    "| Button | 클릭 버튼 |",
    "| TextField | 텍스트 입력 |",
    "| Toggle | 체크박스(on/off) |",
    "| Slider / SliderInt | 슬라이더 |",
    "| DropdownField | 드롭다운 선택 |",
    "| Foldout | 접기/펼치기 영역 |",
    "| ListView | 가상화된 리스트(대량 항목에 적합) |",
    "| ScrollView | 스크롤 가능한 영역 |",
    "| ProgressBar | 진행률 표시 |",
    "| RadioButton / RadioButtonGroup | 라디오 선택 |",
    "",
    "## 런타임 UI 구성",
    "",
    "### UIDocument 컴포넌트",
    "런타임에서 UI Toolkit을 사용하려면 **UIDocument** 컴포넌트를 GameObject에 추가합니다.",
    "",
    "| 프로퍼티 | 설명 |",
    "|----------|------|",
    "| Source Asset | 연결할 UXML 파일 |",
    "| Panel Settings | 렌더링 설정 (해상도, 스케일 모드 등) |",
    "| Sort Order | 여러 UIDocument 간 렌더링 순서 |",
    "",
    "### Panel Settings",
    "Panel Settings 에셋은 UI가 화면에 어떻게 렌더링될지를 결정합니다.",
    "",
    "| 설정 | 설명 |",
    "|------|------|",
    "| Scale Mode | Constant Pixel Size, Scale With Screen Size, Constant Physical Size |",
    "| Reference Resolution | 기준 해상도 (Scale With Screen Size일 때) |",
    "| Theme Style Sheet | 전역 테마 USS |",
    "",
    "## 스크립트에서 제어",
    "",
    "### 요소 검색",
    "```csharp",
    "using UnityEngine;",
    "using UnityEngine.UIElements;",
    "",
    "public class UIController : MonoBehaviour",
    "{",
    "    void OnEnable()",
    "    {",
    "        var root = GetComponent<UIDocument>().rootVisualElement;",
    "",
    "        var button = root.Q<Button>(\"my-button\");",
    "        var nameField = root.Q<TextField>(\"name-field\");",
    "        var title = root.Q<Label>(className: \"title\");",
    "    }",
    "}",
    "```",
    "",
    "### 검색 메서드",
    "| 메서드 | 설명 |",
    "|--------|------|",
    "| Q<T>(name) | 이름으로 첫 번째 일치 요소 반환 |",
    "| Q<T>(className: \"cls\") | 클래스로 검색 |",
    "| Q(name) | 타입 무관하게 이름으로 검색 |",
    "| Query<T>() | 조건에 맞는 모든 요소 (IEnumerable) |",
    "",
    "### 이벤트 등록",
    "```csharp",
    "button.clicked += () => Debug.Log(\"버튼 클릭!\");",
    "",
    "button.RegisterCallback<ClickEvent>(evt => {",
    "    Debug.Log(\"ClickEvent 발생\");",
    "});",
    "",
    "nameField.RegisterValueChangedCallback(evt => {",
    "    Debug.Log($\"입력값: {evt.newValue}\");",
    "});",
    "```",
    "",
    "### 주요 이벤트",
    "| 이벤트 | 설명 |",
    "|--------|------|",
    "| ClickEvent | 클릭 |",
    "| ChangeEvent<T> | 값 변경 (TextField, Toggle 등) |",
    "| MouseEnterEvent / MouseLeaveEvent | 마우스 진입/이탈 |",
    "| FocusEvent / BlurEvent | 포커스 획득/해제 |",
    "| PointerDownEvent / PointerUpEvent | 포인터(터치/마우스) 누름/뗌 |",
    "| KeyDownEvent | 키보드 입력 |",
    "",
    "### 스타일 동적 변경",
    "```csharp",
    "var box = root.Q<VisualElement>(\"box\");",
    "box.style.backgroundColor = Color.red;",
    "box.style.width = 200;",
    "box.style.display = DisplayStyle.None;",
    "",
    "box.AddToClassList(\"highlight\");",
    "box.RemoveFromClassList(\"highlight\");",
    "box.ToggleInClassList(\"highlight\");",
    "```",
    "",
    "## 에디터 확장에서 사용",
    "",
    "### EditorWindow 예시",
    "```csharp",
    "using UnityEditor;",
    "using UnityEngine.UIElements;",
    "",
    "public class MyEditorWindow : EditorWindow",
    "{",
    "    [MenuItem(\"Window/My Tool\")]",
    "    public static void ShowWindow()",
    "    {",
    "        GetWindow<MyEditorWindow>(\"My Tool\");",
    "    }",
    "",
    "    public void CreateGUI()",
    "    {",
    "        var root = rootVisualElement;",
    "",
    "        var label = new Label(\"에디터 UI Toolkit\");",
    "        var btn = new Button(() => Debug.Log(\"클릭\")) { text = \"실행\" };",
    "",
    "        root.Add(label);",
    "        root.Add(btn);",
    "",
    "        // USS 적용",
    "        var styleSheet = AssetDatabase.LoadAssetAtPath<StyleSheet>(\"Assets/Editor/MyStyle.uss\");",
    "        root.styleSheets.Add(styleSheet);",
    "    }",
    "}",
    "```",
    "",
    "### Custom Inspector",
    "```csharp",
    "using UnityEditor;",
    "using UnityEngine.UIElements;",
    "",
    "[CustomEditor(typeof(MyComponent))]",
    "public class MyComponentEditor : Editor",
    "{",
    "    public override VisualElement CreateInspectorGUI()",
    "    {",
    "        var root = new VisualElement();",
    "        // UXML 로드 또는 코드로 구성",
    "        InspectorElement.FillDefaultInspector(root, serializedObject, this);",
    "        return root;",
    "    }",
    "}",
    "```",
    "",
    "## 데이터 바인딩",
    "",
    "UI Toolkit은 SerializedProperty와의 **데이터 바인딩**을 지원합니다.",
    "",
    "```xml",
    "<ui:FloatField label=\"속도\" binding-path=\"speed\" />",
    "<ui:Toggle label=\"활성화\" binding-path=\"isActive\" />",
    "```",
    "",
    "`binding-path`에 SerializedProperty 이름을 지정하면, 값이 자동으로 동기화됩니다. 에디터 Inspector에서 특히 유용합니다.",
    "",
    "## UI Builder",
    "",
    "**UI Builder**는 UI Toolkit용 비주얼 에디터입니다 (Window → UI Toolkit → UI Builder).",
    "",
    "| 기능 | 설명 |",
    "|------|------|",
    "| Hierarchy | 요소 트리 구조 편집 |",
    "| Viewport | 실시간 미리보기 |",
    "| Inspector | 선택 요소의 속성·스타일 편집 |",
    "| StyleSheets | USS 클래스 관리 |",
    "| Library | 드래그 앤 드롭으로 컨트롤 추가 |",
    "",
    "코드 없이 UXML·USS를 시각적으로 만들 수 있어, uGUI의 Canvas 편집과 비슷한 경험을 제공합니다.",
    "",
    "## uGUI vs UI Toolkit 선택 기준",
    "",
    "| 기준 | uGUI (Canvas) | UI Toolkit |",
    "|------|---------------|------------|",
    "| 월드 스페이스 UI | 지원 (World Space Canvas) | 제한적 (Screen Space 중심) |",
    "| 에디터 확장 | 불가 | 권장 |",
    "| 3D 오브젝트 위 UI | 적합 | 제한적 |",
    "| 대량 목록 (수백~수천 항목) | ScrollRect + 직접 풀링 | ListView 가상화 내장 |",
    "| 스타일 재사용 | 프리팹 기반 | USS 클래스 기반 |",
    "| 레이아웃 시스템 | Anchor + Layout Group | Flexbox |",
    "| 학습 곡선 | Unity 기존 사용자에게 익숙 | 웹 개발 경험자에게 익숙 |",
    "",
    "Unity는 UI Toolkit을 장기적 표준으로 밀고 있지만, 월드 스페이스 UI 등 uGUI가 여전히 강한 영역이 있습니다.",
    "",
    "## 주의사항",
    "",
    "### 1) 런타임 지원 범위",
    "UI Toolkit의 런타임 기능은 Unity 버전에 따라 지원 범위가 다릅니다. 최신 LTS에서 대부분의 런타임 기능이 안정화되었습니다.",
    "",
    "### 2) USS는 CSS의 서브셋",
    "웹 CSS의 모든 기능이 지원되지는 않습니다. 지원되는 프로퍼티는 Unity 문서에서 확인해야 합니다. Unity 전용 프로퍼티는 `-unity-` 접두사를 사용합니다.",
    "",
    "### 3) 성능",
    "UI Toolkit은 Retained Mode(보존 모드)로 동작해 매 프레임 다시 그리지 않습니다. 변경이 있을 때만 다시 렌더링하므로, 많은 요소가 있을 때 IMGUI보다 효율적입니다.",
    "",
    "---",
    "### 요약",
    "UI Toolkit은 UXML(구조) + USS(스타일)로 선언적 UI를 구성하는 Unity 차세대 UI 시스템입니다. Flexbox 레이아웃, VisualElement 트리, 이벤트 시스템, 데이터 바인딩을 제공하며, 에디터 확장과 런타임 UI 모두에 사용할 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
