<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unity-attributes",
  title: "Unity 어트리뷰트(Attribute) 정리",
  date: "2026-02-17",
  summary: "[System.Serializable], [SerializeField], [Range], [Header], [Tooltip] 등 Unity와 C#에서 Inspector 표시·직렬화·검증을 위한 자주 쓰는 어트리뷰트를 정리합니다.",
  category: "Technology/Unity",
  tags: ["unity","attribute","serializable","inspector","csharp","basics"],
  content: [
    "## 한 줄 요약",
    "어트리뷰트(Attribute)는 클래스·필드·메서드에 붙어 **Inspector 표시**, **직렬화**, **검증** 등을 제어하는 메타데이터입니다.",
    "",
    "## [System.Serializable]",
    "클래스나 구조체를 **Inspector에 노출**시키려면 이 어트리뷰트가 필요합니다.",
    "",
    "```csharp",
    "using UnityEngine;",
    "",
    "[System.Serializable]",
    "public class ItemData",
    "{",
    "    public string name;",
    "    public int count;",
    "}",
    "",
    "public class Inventory : MonoBehaviour",
    "{",
    "    public ItemData[] items;  // Inspector에서 직렬화·편집 가능",
    "}",
    "```",
    "",
    "`[System.Serializable]`가 없으면 `ItemData` 배열이 Inspector에 제대로 표시되지 않습니다.",
    "",
    "### 주의사항",
    "- `MonoBehaviour`를 상속한 클래스는 이미 직렬화 가능하므로 붙일 필요 없음",
    "- `ScriptableObject`도 마찬가지",
    "- 일반 `class`, `struct`를 public 필드로 쓰는 경우에 필요",
    "",
    "## [SerializeField]",
    "`private` 또는 `protected` 필드를 **Inspector에 보이게** 합니다. 값은 유지되지만, 다른 스크립트에서 직접 접근하지 못하게 할 수 있습니다.",
    "",
    "```csharp",
    "[SerializeField]",
    "private float speed = 5f;",
    "",
    "[SerializeField]",
    "private GameObject targetPrefab;",
    "```",
    "",
    "`public` 필드는 기본적으로 Inspector에 보이므로 `[SerializeField]`가 필요 없습니다.",
    "",
    "## [HideInInspector]",
    "`public` 필드를 Inspector에서 **숨깁니다**. 코드에서만 접근하고, 에디터에는 노출하지 않을 때 사용합니다.",
    "",
    "```csharp",
    "[HideInInspector]",
    "public int internalCounter;  // Inspector에 안 보임",
    "```",
    "",
    "## Inspector 표시 개선용",
    "",
    "### [Header(\"제목\")]",
    "Inspector에서 구간 구분용 제목을 표시합니다.",
    "",
    "```csharp",
    "[Header(\"이동 설정\")]",
    "public float moveSpeed = 5f;",
    "public float jumpForce = 10f;",
    "",
    "[Header(\"공격 설정\")]",
    "public int damage = 10;",
    "```",
    "",
    "### [Space(높이)]",
    "필드 사이에 빈 공간을 넣습니다. 높이를 생략하면 기본 간격입니다.",
    "",
    "```csharp",
    "public float a;",
    "[Space(10)]",
    "public float b;",
    "[Space]",
    "public float c;",
    "```",
    "",
    "### [Tooltip(\"설명\")]",
    "마우스를 올렸을 때 툴팁으로 설명을 표시합니다.",
    "",
    "```csharp",
    "[Tooltip(\"캐릭터의 이동 속도 (m/s)\")]",
    "public float speed = 5f;",
    "```",
    "",
    "### [TextArea(최소줄, 최대줄)]",
    "`string` 필드를 여러 줄 입력 가능한 텍스트 영역으로 표시합니다.",
    "",
    "```csharp",
    "[TextArea(2, 5)]",
    "public string description;",
    "```",
    "",
    "### [Multiline(줄수)]",
    "`TextArea`보다 단순한 형태. 줄 수만 지정합니다. (구버전, `[TextArea]` 권장)",
    "",
    "## 값 제한·검증용",
    "",
    "### [Range(최소, 최대)]",
    "슬라이더로 최소~최대 범위 내 값만 입력할 수 있게 합니다.",
    "",
    "```csharp",
    "[Range(0f, 100f)]",
    "public float health = 100f;",
    "",
    "[Range(1, 10)]",
    "public int level = 1;",
    "```",
    "",
    "### [Min(최소값)]",
    "Unity 2020+ 에서 사용. 최소값 이상만 허용합니다.",
    "",
    "```csharp",
    "[Min(0f)]",
    "public float speed = 5f;",
    "```",
    "",
    "## 실행·콜백 제어용",
    "",
    "### [ContextMenu(\"메뉴 이름\")]",
    "Inspector에서 해당 컴포넌트 우클릭 시 커스텀 메뉴를 추가합니다.",
    "",
    "```csharp",
    "[ContextMenu(\"초기화\")]",
    "void ResetData()",
    "{",
    "    count = 0;",
    "}",
    "```",
    "",
    "### [ContextMenuItem(\"표시이름\", \"메서드명\")]",
    "특정 필드 우클릭 시 메뉴가 나타납니다.",
    "",
    "```csharp",
    "[ContextMenuItem(\"랜덤 값\", \"SetRandom\")]",
    "public int value;",
    "",
    "void SetRandom() { value = Random.Range(0, 100); }",
    "```",
    "",
    "## 정리 표",
    "",
    "| 어트리뷰트 | 용도 |",
    "|------------|------|",
    "| [System.Serializable] | class/struct 직렬화 (Inspector 노출) |",
    "| [SerializeField] | private 필드 Inspector 노출 |",
    "| [HideInInspector] | public 필드 Inspector 숨김 |",
    "| [Header] | 섹션 제목 |",
    "| [Space] | 여백 |",
    "| [Tooltip] | 툴팁 설명 |",
    "| [Range] | 슬라이더로 범위 제한 |",
    "| [Min] | 최소값 제한 |",
    "| [TextArea] | 여러 줄 문자열 |",
    "| [ContextMenu] | 우클릭 메뉴 추가 |",
    "| [ContextMenuItem] | 필드별 우클릭 메뉴 |",
    "",
    "## 예제: 한 스크립트에 여러 어트리뷰트 적용",
    "",
    "```csharp",
    "using UnityEngine;",
    "",
    "[System.Serializable]",
    "public class Stat",
    "{",
    "    [Tooltip(\"캐릭터 레벨\")]",
    "    [Range(1, 99)]",
    "    public int level = 1;",
    "",
    "    [Tooltip(\"체력 (0~100)\")]",
    "    [Range(0f, 100f)]",
    "    public float health = 100f;",
    "}",
    "",
    "public class PlayerController : MonoBehaviour",
    "{",
    "    [Header(\"이동\")]",
    "    [SerializeField]",
    "    [Tooltip(\"이동 속도\")]",
    "    [Range(0f, 20f)]",
    "    private float moveSpeed = 5f;",
    "",
    "    [Space(5)]",
    "    [Header(\"스탯\")]",
    "    public Stat stat;",
    "}",
    "```",
    "",
    "---",
    "### 요약",
    "`[System.Serializable]`은 일반 class/struct를 Inspector에 넣을 때 필수입니다. `[SerializeField]`, `[Header]`, `[Range]`, `[Tooltip]` 등으로 가독성과 유효성 검사가 쉬워집니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
