<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unreal-engine-install",
  title: "Unreal Engine 설치 방법",
  date: "2026-02-17",
  summary: "Unreal Engine은 Epic Games Launcher를 통해 설치합니다. 계정 생성, Launcher 설치, 엔진 버전 선택 및 설치 과정을 단계별로 정리합니다.",
  category: "Technology/Unreal",
  tags: ["unreal","unreal-engine","epic-games","install","basics"],
  content: [
    "## 한 줄 요약",
    "Unreal Engine은 **Epic Games Launcher**를 통해 설치합니다. [unrealengine.com](https://www.unrealengine.com)에서 Launcher를 받고, Launcher 안에서 원하는 엔진 버전을 설치합니다.",
    "",
    "## 사전 요구사항",
    "",
    "| 항목 | 권장 사양 |",
    "|------|-----------|",
    "| OS | Windows 10/11 64비트, 또는 최신 macOS |",
    "| CPU | 쿼드코어 이상, 2.5 GHz 이상 |",
    "| RAM | 16 GB 이상 (대형 프로젝트는 32 GB 권장) |",
    "| GPU | DirectX 11/12 호환 (Windows), 최신 Apple GPU (macOS) |",
    "| 저장 공간 | SSD 50 GB 이상 여유 공간 |",
    "",
    "또한 **Epic Games 계정**이 필요합니다. (무료 가입 가능)",
    "",
    "## 설치 단계",
    "",
    "### 1) Epic Games Launcher 다운로드",
    "1. [unrealengine.com](https://www.unrealengine.com) 접속",
    "2. **Get Started** 또는 **다운로드** 버튼 클릭",
    "3. Epic Games Launcher 설치 파일 다운로드 (Windows: MSI, macOS: DMG)",
    "",
    "### 2) Launcher 설치",
    "1. 다운로드한 설치 파일 실행",
    "2. Epic Games 계정으로 로그인 (없으면 회원가입)",
    "3. 설치 경로 선택 후 설치 완료",
    "",
    "### 3) Unreal Engine 설치",
    "1. Epic Games Launcher 실행",
    "2. 왼쪽 메뉴에서 **Unreal Engine** 선택",
    "3. **라이브러리(Library)** 탭으로 이동",
    "4. **엔진 버전(Engine Versions)** 옆 **+** 버튼 클릭",
    "5. 설치할 버전 선택 (예: 5.4, 5.3, 5.2 등)",
    "6. **설치(Install)** 클릭",
    "",
    "### 4) 설치 옵션",
    "설치 창에서 다음을 설정할 수 있습니다.",
    "",
    "| 옵션 | 설명 |",
    "|------|------|",
    "| 설치 경로 | 엔진이 설치될 폴더 (50 GB 이상 여유 필요) |",
    "| Editor symbols for debugging | 디버깅용 기호 (용량 증가) |",
    "| 대상 플랫폼 | Windows, Android, iOS 등 추가 플랫폼 |",
    "",
    "설정 후 설치를 시작하면 다운로드 및 설치가 진행됩니다. (용량이 커서 시간이 걸릴 수 있습니다)",
    "",
    "## 첫 프로젝트 만들기",
    "설치가 끝나면 **실행(Launch)** 버튼이 나타납니다.",
    "",
    "1. **실행** 클릭",
    "2. **프로젝트 브라우저** 창이 열림",
    "3. **게임**, **영상** 등 카테고리에서 템플릿 선택",
    "4. **First Person**, **Third Person**, **Blank** 등 원하는 템플릿 선택",
    "5. 프로젝트 이름, 저장 경로, **Blueprint / C++** 선택",
    "6. **생성(Create)** 클릭",
    "",
    "## 버전 선택 가이드",
    "| 상황 | 추천 |",
    "|------|------|",
    "| 학습·새 프로젝트 | 최신 안정 버전 (예: 5.4) |",
    "| 기존 프로젝트 유지 | 프로젝트에 맞는 버전 |",
    "| 특정 플러그인 호환 | 플러그인 요구 버전 확인 |",
    "",
    "여러 버전을 동시에 설치해 두고, 프로젝트별로 다른 버전을 쓸 수 있습니다.",
    "",
    "## Epic Games Launcher 없이 설치 (고급)",
    "Epic Games Launcher 대신 **커맨드라인**이나 **GitHub**에서 소스 빌드하는 방법도 있으나, 일반 사용자는 Launcher 방식이 가장 간단합니다.",
    "",
    "## 문제 해결",
    "",
    "| 현상 | 확인 사항 |",
    "|------|-----------|",
    "| Launcher 설치 실패 | 관리자 권한, 방화벽, 백신 예외 |",
    "| 엔진 다운로드 느림 | 네트워크 상태, Epic 서버 상태 |",
    "| 디스크 공간 부족 | 50 GB 이상 여유 공간 확보 |",
    "| 실행 시 크래시 | GPU 드라이버 최신화, DirectX 설치 |",
    "",
    "---",
    "### 요약",
    "Unreal Engine은 Epic Games Launcher를 설치한 뒤, Launcher의 Unreal Engine → 라이브러리에서 원하는 버전을 추가·설치합니다. Epic Games 계정과 충분한 저장 공간(50 GB 이상)을 준비하면 됩니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
