<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "unreal-character-movement",
  title: "캐릭터 이동과 입력",
  date: "2026-02-17",
  summary: "Unreal Engine에서 Character Movement 컴포넌트와 입력 바인딩으로 WASD 이동·점프를 구현하는 방법을 정리합니다. Input Action, Add Movement Input, Jump를 다룹니다.",
  category: "Technology/Unreal",
  tags: ["unreal","character","movement","input","wasd","jump","basics"],
  content: [
    "## 한 줄 요약",
    "Character Blueprint에서 **Input Action** 이벤트에 **Add Movement Input**, **Jump** 노드를 연결하면 WASD 이동과 점프가 구현됩니다. Third Person 템플릿에는 이미 설정되어 있습니다.",
    "",
    "## 입력 설정 (Input Mapping)",
    "프로젝트 설정에서 키/마우스/패드를 **Input Action** 또는 **Input Axis**에 연결합니다.",
    "",
    "### 설정 경로",
    "Edit → Project Settings → **Input** (또는 Engine - Input)",
    "",
    "### Input Action (단발 입력)",
    "점프, 공격, 상호작용 등 한 번 누를 때 한 번 반응하는 입력입니다.",
    "",
    "| Action 이름 | 키 예시 |",
    "|-------------|---------|",
    "| Jump | Space |",
    "| Fire | Left Mouse Button |",
    "",
    "### Input Axis (연속 입력)",
    "이동처럼 누르고 있는 동안 계속 반응하는 입력입니다.",
    "",
    "| Axis 이름 | 키 예시 |",
    "|------------|---------|",
    "| MoveForward | W (+1), S (-1) |",
    "| MoveRight | D (+1), A (-1) |",
    "",
    "## Character Blueprint에서 사용",
    "Character Blueprint를 열고, **Event Graph**에서 입력 이벤트를 찾습니다.",
    "",
    "### 점프 (Input Action Jump)",
    "```",
    "InputAction Jump (Pressed) → Jump (Character Movement 컴포넌트) |",
    "```",
    "",
    "Jump 노드는 Character Movement 컴포넌트의 Jump()를 호출합니다.",
    "",
    "### 이동 (Input Axis MoveForward / MoveRight)",
    "```",
    "InputAxis MoveForward → Add Movement Input (World Direction = Forward Vector * Axis Value) |",
    "InputAxis MoveRight   → Add Movement Input (World Direction = Right Vector * Axis Value) |",
    "```",
    "",
    "**Add Movement Input**은 이동 방향과 강도(보통 -1 ~ 1)를 받아 Character Movement가 처리합니다.",
    "",
    "## Add Movement Input 노드",
    "| 입력 | 설명 |",
    "|------|------|",
    "| World Direction | 이동할 방향 (벡터, 정규화 권장) |",
    "| Scale Value | 이동 강도 (-1 ~ 1, 축 값 그대로 사용) |",
    "",
    "Get Forward Vector, Get Right Vector로 앞/오른쪽 방향을 구해, Axis Value를 곱해 넣습니다.",
    "",
    "## Character Movement 프로퍼티",
    "Details 패널에서 Character Movement 컴포넌트를 선택하면 다음을 조절할 수 있습니다.",
    "",
    "| 프로퍼티 | 설명 |",
    "|----------|------|",
    "| Max Walk Speed | 걷기 최대 속도 |",
    "| Jump Z Velocity | 점프 초기 속도 (위로) |",
    "| Gravity Scale | 중력 배율 |",
    "| Air Control | 공중에서 방향 전환 가능 비율 |",
    "",
    "## 마우스로 시점 회전",
    "마우스 입력(Mouse X, Mouse Y)으로 **Add Controller Yaw Input**, **Add Controller Pitch Input**을 호출하면 1인칭/3인칭 시점 회전이 됩니다. Third Person 템플릿에도 이미 연결되어 있습니다.",
    "",
    "## 예제: Third Person 템플릿 확인",
    "1. Content Browser → ThirdPersonBP → Blueprints → ThirdPersonCharacter 열기",
    "2. Event Graph에서 InputAxis MoveForward, MoveRight, InputAction Jump 노드 찾기",
    "3. 각각 Add Movement Input, Jump와 어떻게 연결되는지 확인",
    "",
    "---",
    "### 요약",
    "Input Action/ Axis를 프로젝트 설정에 등록하고, Character Blueprint의 입력 이벤트에 Add Movement Input·Jump를 연결하면 이동과 점프가 구현됩니다. Third Person 템플릿을 분석하면 기본 구조를 빠르게 익힐 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
