<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "vue-template-directives",
  title: "Vue.js 템플릿 문법과 디렉티브",
  date: "2026-03-03",
  summary: "Vue의 템플릿 문법(보간법, 바인딩)과 핵심 디렉티브(v-bind, v-on, v-if, v-for, v-model, v-show, v-slot)의 사용법을 TypeScript 예제로 정리합니다.",
  category: "Technology/Vue.js",
  tags: ["vue","template","directive","v-bind","v-on","v-if","v-for","v-model","v-show"],
  content: [
    "## 한 줄 요약",
    "Vue의 템플릿은 **머스태시 보간법**(`{{ }}`)으로 데이터를 출력하고, **디렉티브**(`v-` 접두사)로 DOM을 선언적으로 조작합니다.",
    "",
    "---",
    "",
    "## 1. 텍스트 보간법",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "const message = ref('안녕하세요')",
    "const count = ref(42)",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <p>{{ message }}</p>",
    "  <p>{{ count * 2 }}</p>",
    "  <p>{{ message.split('').reverse().join('') }}</p>",
    "  <p>{{ count > 10 ? '크다' : '작다' }}</p>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 2. v-bind — 속성 바인딩",
    "",
    "HTML 속성에 동적 값을 바인딩합니다. 단축 문법은 `:`입니다.",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "const imgUrl = ref('https://example.com/img.jpg')",
    "const isDisabled = ref(true)",
    "const dynamicClass = ref('active')",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <!-- 전체 문법 -->",
    "  <img v-bind:src=\"imgUrl\" />",
    "",
    "  <!-- 단축 문법 (권장) -->",
    "  <img :src=\"imgUrl\" />",
    "  <button :disabled=\"isDisabled\">버튼</button>",
    "  <div :class=\"dynamicClass\">동적 클래스</div>",
    "\x3c/template>",
    "```",
    "",
    "### 클래스 바인딩",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "const isActive = ref(true)",
    "const hasError = ref(false)",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <!-- 객체 문법 -->",
    "  <div :class=\"{ active: isActive, error: hasError }\">객체</div>",
    "",
    "  <!-- 배열 문법 -->",
    "  <div :class=\"[isActive ? 'active' : '', 'base']\">배열</div>",
    "\x3c/template>",
    "```",
    "",
    "### 스타일 바인딩",
    "",
    "```vue",
    "\x3ctemplate>",
    "  <div :style=\"{ color: 'red', fontSize: '16px' }\">인라인</div>",
    "  <div :style=\"[baseStyle, overrideStyle]\">배열</div>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 3. v-on — 이벤트 핸들링",
    "",
    "DOM 이벤트를 처리합니다. 단축 문법은 `@`입니다.",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "const count = ref(0)",
    "",
    "const handleClick = (event: MouseEvent): void => {",
    "  console.log('클릭!', event.target)",
    "}",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <!-- 전체 문법 -->",
    "  <button v-on:click=\"count++\">{{ count }}</button>",
    "",
    "  <!-- 단축 문법 (권장) -->",
    "  <button @click=\"count++\">인라인</button>",
    "  <button @click=\"handleClick\">메서드</button>",
    "  <button @click=\"() => count = 0\">초기화</button>",
    "\x3c/template>",
    "```",
    "",
    "### 이벤트 수식어",
    "",
    "| 수식어 | 설명 | 예시 |",
    "|--------|------|------|",
    "| `.prevent` | `e.preventDefault()` | `@submit.prevent` |",
    "| `.stop` | `e.stopPropagation()` | `@click.stop` |",
    "| `.once` | 한 번만 실행 | `@click.once` |",
    "| `.self` | 자기 자신에서만 | `@click.self` |",
    "| `.enter` | Enter 키 | `@keydown.enter` |",
    "| `.ctrl` | Ctrl 키 조합 | `@click.ctrl` |",
    "",
    "```vue",
    "\x3ctemplate>",
    "  <form @submit.prevent=\"onSubmit\">...</form>",
    "  <input @keydown.enter=\"search\" />",
    "  <div @click.self=\"closeModal\">...</div>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 4. v-if / v-else-if / v-else — 조건부 렌더링",
    "",
    "조건에 따라 DOM을 **생성/제거**합니다.",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "type Status = 'loading' | 'success' | 'error'",
    "const status = ref<Status>('loading')",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <p v-if=\"status === 'loading'\">로딩 중...</p>",
    "  <p v-else-if=\"status === 'error'\">에러 발생!</p>",
    "  <p v-else>데이터 로드 완료</p>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 5. v-show — 표시/숨기기",
    "",
    "`display: none`으로 토글합니다. DOM은 항상 존재합니다.",
    "",
    "```vue",
    "\x3ctemplate>",
    "  <p v-show=\"isVisible\">보였다 안 보였다</p>",
    "\x3c/template>",
    "```",
    "",
    "| 비교 | v-if | v-show |",
    "|------|------|--------|",
    "| DOM 처리 | 생성/제거 | display 토글 |",
    "| 초기 비용 | 낮음 (false면 미생성) | 높음 (항상 생성) |",
    "| 토글 비용 | 높음 (재생성) | 낮음 (CSS만 변경) |",
    "| 적합한 경우 | 거의 안 바뀌는 조건 | 자주 토글하는 경우 |",
    "",
    "---",
    "",
    "## 6. v-for — 리스트 렌더링",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "interface Todo {",
    "  id: number",
    "  text: string",
    "  done: boolean",
    "}",
    "",
    "const todos = ref<Todo[]>([",
    "  { id: 1, text: '공부하기', done: false },",
    "  { id: 2, text: '운동하기', done: true },",
    "  { id: 3, text: '책 읽기', done: false },",
    "])",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <!-- 배열 -->",
    "  <ul>",
    "    <li v-for=\"todo in todos\" :key=\"todo.id\">",
    "      {{ todo.done ? '✅' : '⬜' }} {{ todo.text }}",
    "    </li>",
    "  </ul>",
    "",
    "  <!-- 인덱스 포함 -->",
    "  <li v-for=\"(todo, index) in todos\" :key=\"todo.id\">",
    "    {{ index + 1 }}. {{ todo.text }}",
    "  </li>",
    "",
    "  <!-- 객체 -->",
    "  <div v-for=\"(value, key) in { name: '홍길동', age: 25 }\" :key=\"key\">",
    "    {{ key }}: {{ value }}",
    "  </div>",
    "",
    "  <!-- 숫자 범위 -->",
    "  <span v-for=\"n in 5\" :key=\"n\">{{ n }} </span>",
    "\x3c/template>",
    "```",
    "",
    "> `:key`는 **필수**입니다. 고유한 ID를 사용하세요 (인덱스 사용은 권장하지 않음).",
    "",
    "---",
    "",
    "## 7. v-model — 양방향 바인딩",
    "",
    "폼 입력과 데이터를 자동 동기화합니다.",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "const name = ref('')",
    "const agreed = ref(false)",
    "const selected = ref('')",
    "const skills = ref<string[]>([])",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <!-- 텍스트 -->",
    "  <input v-model=\"name\" placeholder=\"이름\" />",
    "  <p>입력: {{ name }}</p>",
    "",
    "  <!-- 체크박스 -->",
    "  <label><input type=\"checkbox\" v-model=\"agreed\" /> 동의</label>",
    "",
    "  <!-- 다중 체크박스 -->",
    "  <label><input type=\"checkbox\" v-model=\"skills\" value=\"js\" /> JS</label>",
    "  <label><input type=\"checkbox\" v-model=\"skills\" value=\"ts\" /> TS</label>",
    "  <p>선택: {{ skills }}</p>",
    "",
    "  <!-- 셀렉트 -->",
    "  <select v-model=\"selected\">",
    "    <option value=\"\">선택하세요</option>",
    "    <option value=\"vue\">Vue</option>",
    "    <option value=\"react\">React</option>",
    "  </select>",
    "\x3c/template>",
    "```",
    "",
    "### v-model 수식어",
    "",
    "| 수식어 | 설명 |",
    "|--------|------|",
    "| `.lazy` | input 대신 change 이벤트에서 업데이트 |",
    "| `.number` | 숫자로 자동 변환 |",
    "| `.trim` | 앞뒤 공백 제거 |",
    "",
    "```vue",
    "<input v-model.lazy=\"message\" />",
    "<input v-model.number=\"age\" type=\"number\" />",
    "<input v-model.trim=\"name\" />",
    "```",
    "",
    "---",
    "",
    "## 디렉티브 요약",
    "",
    "| 디렉티브 | 단축 | 역할 |",
    "|----------|------|------|",
    "| `v-bind` | `:` | 속성 바인딩 |",
    "| `v-on` | `@` | 이벤트 핸들링 |",
    "| `v-if` | - | 조건부 렌더링 (DOM 생성/제거) |",
    "| `v-show` | - | 조건부 표시 (display 토글) |",
    "| `v-for` | - | 리스트 렌더링 |",
    "| `v-model` | - | 양방향 바인딩 |",
    "| `v-slot` | `#` | 슬롯 콘텐츠 전달 |",
    "| `v-html` | - | HTML 삽입 (XSS 주의) |",
    "",
    "---",
    "",
    "### 요약",
    "Vue 템플릿은 **머스태시 보간법**으로 데이터를 출력하고, `:` (v-bind)로 속성, `@` (v-on)으로 이벤트, `v-if`/`v-for`로 조건/반복, `v-model`로 양방향 바인딩을 처리합니다. 이벤트 수식어(`.prevent`, `.stop`, `.enter`)로 보일러플레이트를 줄일 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
