<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "vue-advanced",
  title: "Vue.js 고급 패턴: Teleport, Suspense, 커스텀 디렉티브, 플러그인",
  date: "2026-03-03",
  summary: "Vue 3의 고급 기능인 Teleport, Suspense, KeepAlive, Transition, 커스텀 디렉티브, 플러그인 작성, 성능 최적화 패턴을 TypeScript 예제로 정리합니다.",
  category: "Technology/Vue.js",
  tags: ["vue","teleport","suspense","keep-alive","transition","directive","plugin","performance","typescript"],
  content: [
    "## 한 줄 요약",
    "Vue 3의 고급 기능인 **Teleport**(DOM 이동), **Suspense**(비동기 로딩), **KeepAlive**(캐싱), **Transition**(애니메이션), 커스텀 디렉티브, 플러그인으로 복잡한 UI 패턴을 구현합니다.",
    "",
    "---",
    "",
    "## 1. Teleport — DOM 위치 이동",
    "",
    "컴포넌트의 렌더링 출력을 DOM의 다른 위치로 텔레포트합니다. 모달, 툴팁 등에 유용합니다.",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "const showModal = ref(false)",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <button @click=\"showModal = true\">모달 열기</button>",
    "",
    "  <Teleport to=\"body\">",
    "    <div v-if=\"showModal\" class=\"modal-overlay\" @click.self=\"showModal = false\">",
    "      <div class=\"modal\">",
    "        <h2>모달 제목</h2>",
    "        <p>이 내용은 body에 렌더링됩니다.</p>",
    "        <button @click=\"showModal = false\">닫기</button>",
    "      </div>",
    "    </div>",
    "  </Teleport>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 2. Suspense — 비동기 컴포넌트 로딩",
    "",
    "비동기 `setup`이 있는 컴포넌트의 로딩 상태를 선언적으로 처리합니다.",
    "",
    "```vue",
    "<!-- AsyncData.vue — 비동기 컴포넌트 -->",
    "\x3cscript setup lang=\"ts\">",
    "interface User {",
    "  id: number",
    "  name: string",
    "}",
    "",
    "const res = await fetch('/api/users')",
    "const users: User[] = await res.json()",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <ul>",
    "    <li v-for=\"u in users\" :key=\"u.id\">{{ u.name }}</li>",
    "  </ul>",
    "\x3c/template>",
    "```",
    "",
    "```vue",
    "<!-- 부모 -->",
    "\x3ctemplate>",
    "  <Suspense>",
    "    \x3ctemplate #default>",
    "      <AsyncData />",
    "    \x3c/template>",
    "    \x3ctemplate #fallback>",
    "      <p>로딩 중...</p>",
    "    \x3c/template>",
    "  </Suspense>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 3. KeepAlive — 컴포넌트 캐싱",
    "",
    "탭 전환 시 컴포넌트 상태를 유지합니다.",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref, shallowRef } from 'vue'",
    "import TabA from './TabA.vue'",
    "import TabB from './TabB.vue'",
    "",
    "const currentTab = shallowRef(TabA)",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <button @click=\"currentTab = TabA\">탭 A</button>",
    "  <button @click=\"currentTab = TabB\">탭 B</button>",
    "",
    "  <KeepAlive>",
    "    <component :is=\"currentTab\" />",
    "  </KeepAlive>",
    "\x3c/template>",
    "```",
    "",
    "| 속성 | 설명 |",
    "|------|------|",
    "| `include` | 캐싱할 컴포넌트 이름 |",
    "| `exclude` | 캐싱 제외할 컴포넌트 이름 |",
    "| `max` | 최대 캐싱 수 |",
    "",
    "---",
    "",
    "## 4. Transition — 애니메이션",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "const show = ref(true)",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <button @click=\"show = !show\">토글</button>",
    "",
    "  <Transition name=\"fade\">",
    "    <p v-if=\"show\">나타났다 사라졌다</p>",
    "  </Transition>",
    "\x3c/template>",
    "",
    "\x3cstyle scoped>",
    ".fade-enter-active,",
    ".fade-leave-active {",
    "  transition: opacity 0.3s ease;",
    "}",
    ".fade-enter-from,",
    ".fade-leave-to {",
    "  opacity: 0;",
    "}",
    "\x3c/style>",
    "```",
    "",
    "### TransitionGroup — 리스트 애니메이션",
    "",
    "```vue",
    "\x3ctemplate>",
    "  <TransitionGroup name=\"list\" tag=\"ul\">",
    "    <li v-for=\"item in items\" :key=\"item.id\">{{ item.text }}</li>",
    "  </TransitionGroup>",
    "\x3c/template>",
    "",
    "\x3cstyle scoped>",
    ".list-enter-active, .list-leave-active {",
    "  transition: all 0.3s ease;",
    "}",
    ".list-enter-from, .list-leave-to {",
    "  opacity: 0;",
    "  transform: translateX(30px);",
    "}",
    ".list-move {",
    "  transition: transform 0.3s ease;",
    "}",
    "\x3c/style>",
    "```",
    "",
    "---",
    "",
    "## 5. 커스텀 디렉티브",
    "",
    "```ts",
    "// directives/vFocus.ts",
    "import type { Directive } from 'vue'",
    "",
    "export const vFocus: Directive<HTMLInputElement> = {",
    "  mounted(el) {",
    "    el.focus()",
    "  },",
    "}",
    "```",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { vFocus } from '@/directives/vFocus'",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <input v-focus placeholder=\"자동 포커스\" />",
    "\x3c/template>",
    "```",
    "",
    "### 클릭 외부 감지 디렉티브",
    "",
    "```ts",
    "// directives/vClickOutside.ts",
    "import type { Directive } from 'vue'",
    "",
    "export const vClickOutside: Directive<HTMLElement, () => void> = {",
    "  mounted(el, binding) {",
    "    (el as any).__clickOutsideHandler = (event: Event) => {",
    "      if (!el.contains(event.target as Node)) {",
    "        binding.value()",
    "      }",
    "    }",
    "    document.addEventListener('click', (el as any).__clickOutsideHandler)",
    "  },",
    "  unmounted(el) {",
    "    document.removeEventListener('click', (el as any).__clickOutsideHandler)",
    "  },",
    "}",
    "```",
    "",
    "```vue",
    "\x3ctemplate>",
    "  <div v-click-outside=\"closeDropdown\" class=\"dropdown\">...</div>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 6. 플러그인 작성",
    "",
    "```ts",
    "// plugins/toast.ts",
    "import type { App, Plugin } from 'vue'",
    "import { ref } from 'vue'",
    "",
    "const message = ref('')",
    "const visible = ref(false)",
    "",
    "export const toast = {",
    "  show(msg: string, duration = 3000) {",
    "    message.value = msg",
    "    visible.value = true",
    "    setTimeout(() => { visible.value = false }, duration)",
    "  },",
    "  message,",
    "  visible,",
    "}",
    "",
    "export const ToastPlugin: Plugin = {",
    "  install(app: App) {",
    "    app.provide('toast', toast)",
    "    app.config.globalProperties.$toast = toast",
    "  },",
    "}",
    "```",
    "",
    "```ts",
    "// main.ts",
    "import { ToastPlugin } from './plugins/toast'",
    "app.use(ToastPlugin)",
    "```",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { inject } from 'vue'",
    "const toast = inject<typeof import('@/plugins/toast').toast>('toast')!",
    "",
    "const notify = () => toast.show('저장 완료!')",
    "\x3c/script>",
    "```",
    "",
    "---",
    "",
    "## 7. 성능 최적화 팁",
    "",
    "| 기법 | 설명 |",
    "|------|------|",
    "| `v-once` | 한 번만 렌더링 (정적 콘텐츠) |",
    "| `v-memo` | 조건이 변경될 때만 리렌더링 |",
    "| `shallowRef` | 깊은 반응성 불필요 시 |",
    "| `KeepAlive` | 탭 전환 시 컴포넌트 캐싱 |",
    "| 동적 import | 라우트 레이지 로딩 |",
    "| `computed` | 불필요한 재계산 방지 (캐싱) |",
    "",
    "```vue",
    "\x3ctemplate>",
    "  <!-- v-once: 최초 1회만 렌더링 -->",
    "  <h1 v-once>{{ title }}</h1>",
    "",
    "  <!-- v-memo: deps가 바뀔 때만 리렌더링 -->",
    "  <div v-for=\"item in list\" :key=\"item.id\" v-memo=\"[item.selected]\">",
    "    {{ item.name }}",
    "  </div>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "**Teleport**로 모달을 body에 렌더링하고, **Suspense**로 비동기 컴포넌트 로딩 UI를, **KeepAlive**로 탭 캐싱을, **Transition**으로 애니메이션을 선언적으로 처리합니다. **커스텀 디렉티브**와 **플러그인**으로 재사용 가능한 기능을 확장하고, `v-once`/`v-memo`/`shallowRef`로 성능을 최적화합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
