<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "vue-lifecycle-composables",
  title: "Vue.js 생명주기와 Composables",
  date: "2026-03-03",
  summary: "Vue 컴포넌트의 생명주기 훅(onMounted, onUpdated, onUnmounted 등)과 로직 재사용을 위한 Composables 패턴을 TypeScript 예제로 정리합니다.",
  category: "Technology/Vue.js",
  tags: ["vue","lifecycle","onMounted","onUnmounted","composables","custom-hook","typescript"],
  content: [
    "## 한 줄 요약",
    "Vue의 **생명주기 훅**은 컴포넌트의 생성·업데이트·제거 시점에 코드를 실행하고, **Composables**는 반응성 로직을 재사용 가능한 함수로 추출합니다.",
    "",
    "---",
    "",
    "## 1. 생명주기 훅",
    "",
    "| 훅 | 시점 | 주요 용도 |",
    "|-----|------|----------|",
    "| `onBeforeMount` | DOM 마운트 직전 | - |",
    "| `onMounted` | DOM 마운트 완료 | API 호출, DOM 접근, 타이머 |",
    "| `onBeforeUpdate` | 리렌더링 직전 | - |",
    "| `onUpdated` | 리렌더링 완료 | DOM 변경 후 작업 |",
    "| `onBeforeUnmount` | 언마운트 직전 | 클린업 준비 |",
    "| `onUnmounted` | 언마운트 완료 | 타이머 해제, 이벤트 제거 |",
    "| `onErrorCaptured` | 하위 에러 캡처 | 에러 로깅 |",
    "",
    "### 기본 사용법",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref, onMounted, onUnmounted } from 'vue'",
    "",
    "const data = ref<string[]>([])",
    "let timer: ReturnType<typeof setInterval>",
    "",
    "onMounted(async () => {",
    "  // DOM 접근 가능, API 호출",
    "  const res = await fetch('/api/data')",
    "  data.value = await res.json()",
    "",
    "  // 타이머 설정",
    "  timer = setInterval(() => {",
    "    console.log('tick')",
    "  }, 1000)",
    "})",
    "",
    "onUnmounted(() => {",
    "  // 클린업",
    "  clearInterval(timer)",
    "})",
    "\x3c/script>",
    "```",
    "",
    "---",
    "",
    "## 2. Composables (커스텀 훅)",
    "",
    "Composables는 `use` 접두사를 가진 함수로, **반응성 상태 + 로직**을 캡슐화하여 여러 컴포넌트에서 재사용합니다. React의 커스텀 훅과 유사합니다.",
    "",
    "### useFetch",
    "",
    "```ts",
    "// composables/useFetch.ts",
    "import { ref, watchEffect, type Ref } from 'vue'",
    "",
    "interface UseFetchReturn<T> {",
    "  data: Ref<T | null>",
    "  loading: Ref<boolean>",
    "  error: Ref<string | null>",
    "}",
    "",
    "export function useFetch<T>(url: Ref<string> | string): UseFetchReturn<T> {",
    "  const data = ref<T | null>(null) as Ref<T | null>",
    "  const loading = ref(true)",
    "  const error = ref<string | null>(null)",
    "",
    "  watchEffect(async (onCleanup) => {",
    "    const controller = new AbortController()",
    "    onCleanup(() => controller.abort())",
    "",
    "    loading.value = true",
    "    error.value = null",
    "",
    "    try {",
    "      const urlValue = typeof url === 'string' ? url : url.value",
    "      const res = await fetch(urlValue, { signal: controller.signal })",
    "      if (!res.ok) throw new Error(`HTTP ${res.status}`)",
    "      data.value = await res.json()",
    "    } catch (err) {",
    "      if ((err as Error).name !== 'AbortError') {",
    "        error.value = (err as Error).message",
    "      }",
    "    } finally {",
    "      loading.value = false",
    "    }",
    "  })",
    "",
    "  return { data, loading, error }",
    "}",
    "```",
    "",
    "```vue",
    "<!-- 컴포넌트에서 사용 -->",
    "\x3cscript setup lang=\"ts\">",
    "import { useFetch } from '@/composables/useFetch'",
    "",
    "interface User { id: number; name: string }",
    "const { data: users, loading, error } = useFetch<User[]>('/api/users')",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <p v-if=\"loading\">로딩 중...</p>",
    "  <p v-else-if=\"error\">에러: {{ error }}</p>",
    "  <ul v-else>",
    "    <li v-for=\"u in users\" :key=\"u.id\">{{ u.name }}</li>",
    "  </ul>",
    "\x3c/template>",
    "```",
    "",
    "### useToggle",
    "",
    "```ts",
    "// composables/useToggle.ts",
    "import { ref } from 'vue'",
    "",
    "export function useToggle(initial = false) {",
    "  const value = ref(initial)",
    "  const toggle = () => { value.value = !value.value }",
    "  const setTrue = () => { value.value = true }",
    "  const setFalse = () => { value.value = false }",
    "  return { value, toggle, setTrue, setFalse }",
    "}",
    "```",
    "",
    "### useLocalStorage",
    "",
    "```ts",
    "// composables/useLocalStorage.ts",
    "import { ref, watch, type Ref } from 'vue'",
    "",
    "export function useLocalStorage<T>(key: string, defaultValue: T): Ref<T> {",
    "  const stored = localStorage.getItem(key)",
    "  const data = ref<T>(stored ? JSON.parse(stored) : defaultValue) as Ref<T>",
    "",
    "  watch(data, (val) => {",
    "    localStorage.setItem(key, JSON.stringify(val))",
    "  }, { deep: true })",
    "",
    "  return data",
    "}",
    "",
    "// 사용",
    "const theme = useLocalStorage<'light' | 'dark'>('theme', 'light')",
    "```",
    "",
    "### useMousePosition",
    "",
    "```ts",
    "// composables/useMousePosition.ts",
    "import { ref, onMounted, onUnmounted } from 'vue'",
    "",
    "export function useMousePosition() {",
    "  const x = ref(0)",
    "  const y = ref(0)",
    "",
    "  const update = (e: MouseEvent) => {",
    "    x.value = e.clientX",
    "    y.value = e.clientY",
    "  }",
    "",
    "  onMounted(() => window.addEventListener('mousemove', update))",
    "  onUnmounted(() => window.removeEventListener('mousemove', update))",
    "",
    "  return { x, y }",
    "}",
    "```",
    "",
    "---",
    "",
    "## VueUse — Composables 라이브러리",
    "",
    "직접 만들지 않아도 **VueUse** 라이브러리에 200개 이상의 Composables가 있습니다.",
    "",
    "```bash",
    "npm install @vueuse/core",
    "```",
    "",
    "```ts",
    "import { useMouse, useLocalStorage, useDark, useToggle } from '@vueuse/core'",
    "",
    "const { x, y } = useMouse()",
    "const isDark = useDark()",
    "const toggleDark = useToggle(isDark)",
    "const token = useLocalStorage('token', '')",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "**생명주기 훅**은 `onMounted`(API 호출, DOM 접근)와 `onUnmounted`(클린업)가 가장 자주 사용됩니다. **Composables**는 `use` 접두사 함수로 반응성 로직을 캡슐화하여 재사용하며, **VueUse** 라이브러리로 200개 이상의 범용 Composables를 바로 쓸 수 있습니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
