<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "vue-router",
  title: "Vue Router 완벽 가이드",
  date: "2026-03-03",
  summary: "Vue Router 4의 설치, 기본 라우팅, 동적 경로, 중첩 라우트, 네비게이션 가드, 라우트 메타, 레이지 로딩까지 TypeScript 예제로 정리합니다.",
  category: "Technology/Vue.js",
  tags: ["vue","vue-router","routing","navigation-guard","lazy-loading","typescript"],
  content: [
    "## 한 줄 요약",
    "**Vue Router**는 Vue.js의 공식 라우팅 라이브러리로, SPA에서 URL 기반 페이지 전환, 네비게이션 가드, 동적 경로를 관리합니다.",
    "",
    "---",
    "",
    "## 설치 및 기본 설정",
    "",
    "```bash",
    "npm install vue-router@4",
    "```",
    "",
    "```ts",
    "// router/index.ts",
    "import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'",
    "",
    "const routes: RouteRecordRaw[] = [",
    "  {",
    "    path: '/',",
    "    name: 'Home',",
    "    component: () => import('@/views/Home.vue'),",
    "  },",
    "  {",
    "    path: '/about',",
    "    name: 'About',",
    "    component: () => import('@/views/About.vue'),",
    "  },",
    "  {",
    "    path: '/:pathMatch(.*)*',",
    "    name: 'NotFound',",
    "    component: () => import('@/views/NotFound.vue'),",
    "  },",
    "]",
    "",
    "const router = createRouter({",
    "  history: createWebHistory(import.meta.env.BASE_URL),",
    "  routes,",
    "})",
    "",
    "export default router",
    "```",
    "",
    "```ts",
    "// main.ts",
    "import { createApp } from 'vue'",
    "import App from './App.vue'",
    "import router from './router'",
    "",
    "createApp(App).use(router).mount('#app')",
    "```",
    "",
    "---",
    "",
    "## 네비게이션",
    "",
    "### 템플릿에서",
    "",
    "```vue",
    "\x3ctemplate>",
    "  <nav>",
    "    <RouterLink to=\"/\">홈</RouterLink>",
    "    <RouterLink to=\"/about\">소개</RouterLink>",
    "    <RouterLink :to=\"{ name: 'About' }\">소개 (name)</RouterLink>",
    "  </nav>",
    "",
    "  <RouterView />",
    "\x3c/template>",
    "```",
    "",
    "| 컴포넌트 | 역할 |",
    "|----------|------|",
    "| `<RouterLink>` | 링크 (a 태그 대체, active 클래스 자동) |",
    "| `<RouterView>` | 현재 라우트의 컴포넌트를 렌더링 |",
    "",
    "### 프로그래매틱 네비게이션",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { useRouter, useRoute } from 'vue-router'",
    "",
    "const router = useRouter()",
    "const route = useRoute()",
    "",
    "// 이동",
    "router.push('/about')",
    "router.push({ name: 'About' })",
    "router.push({ path: '/search', query: { q: 'vue' } })",
    "",
    "// 현재 경로 정보",
    "console.log(route.path)       // '/about'",
    "console.log(route.params)     // { id: '123' }",
    "console.log(route.query)      // { q: 'vue' }",
    "",
    "// 히스토리 조작",
    "router.replace('/login')     // 히스토리에 쌓지 않음",
    "router.go(-1)                // 뒤로",
    "\x3c/script>",
    "```",
    "",
    "---",
    "",
    "## 동적 경로 매개변수",
    "",
    "```ts",
    "// router/index.ts",
    "{",
    "  path: '/user/:id',",
    "  name: 'UserDetail',",
    "  component: () => import('@/views/UserDetail.vue'),",
    "  props: true,  // params를 props로 전달",
    "}",
    "```",
    "",
    "```vue",
    "<!-- views/UserDetail.vue -->",
    "\x3cscript setup lang=\"ts\">",
    "import { useRoute } from 'vue-router'",
    "",
    "// 방법 1: useRoute",
    "const route = useRoute()",
    "const userId = route.params.id as string",
    "",
    "// 방법 2: props (props: true 설정 시)",
    "const props = defineProps<{ id: string }>()",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <h1>사용자 #{{ id }}</h1>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 중첩 라우트 (Nested Routes)",
    "",
    "```ts",
    "{",
    "  path: '/dashboard',",
    "  component: () => import('@/views/Dashboard.vue'),",
    "  children: [",
    "    { path: '', component: () => import('@/views/DashboardHome.vue') },",
    "    { path: 'profile', component: () => import('@/views/DashboardProfile.vue') },",
    "    { path: 'settings', component: () => import('@/views/DashboardSettings.vue') },",
    "  ],",
    "}",
    "```",
    "",
    "```vue",
    "<!-- views/Dashboard.vue -->",
    "\x3ctemplate>",
    "  <div>",
    "    <nav>",
    "      <RouterLink to=\"/dashboard\">홈</RouterLink>",
    "      <RouterLink to=\"/dashboard/profile\">프로필</RouterLink>",
    "      <RouterLink to=\"/dashboard/settings\">설정</RouterLink>",
    "    </nav>",
    "    <RouterView />  <!-- 자식 라우트가 여기에 렌더링 -->",
    "  </div>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 네비게이션 가드",
    "",
    "### 전역 가드",
    "",
    "```ts",
    "// router/index.ts",
    "router.beforeEach((to, from) => {",
    "  const isAuthenticated = !!localStorage.getItem('token')",
    "",
    "  if (to.meta.requiresAuth && !isAuthenticated) {",
    "    return { name: 'Login', query: { redirect: to.fullPath } }",
    "  }",
    "})",
    "```",
    "",
    "### 라우트별 가드",
    "",
    "```ts",
    "{",
    "  path: '/admin',",
    "  component: () => import('@/views/Admin.vue'),",
    "  meta: { requiresAuth: true, roles: ['admin'] },",
    "  beforeEnter: (to) => {",
    "    const userRole = getUserRole()",
    "    if (!to.meta.roles?.includes(userRole)) {",
    "      return { name: 'Forbidden' }",
    "    }",
    "  },",
    "}",
    "```",
    "",
    "### 컴포넌트 내 가드",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { onBeforeRouteLeave } from 'vue-router'",
    "",
    "const hasUnsavedChanges = ref(false)",
    "",
    "onBeforeRouteLeave(() => {",
    "  if (hasUnsavedChanges.value) {",
    "    return confirm('저장하지 않은 변경사항이 있습니다. 나가시겠습니까?')",
    "  }",
    "})",
    "\x3c/script>",
    "```",
    "",
    "---",
    "",
    "## 라우트 메타 (TypeScript)",
    "",
    "```ts",
    "// router/index.ts",
    "declare module 'vue-router' {",
    "  interface RouteMeta {",
    "    requiresAuth?: boolean",
    "    roles?: string[]",
    "    title?: string",
    "  }",
    "}",
    "",
    "// 라우트 정의 시 타입 안전한 meta 사용",
    "{",
    "  path: '/admin',",
    "  meta: { requiresAuth: true, roles: ['admin'], title: '관리자' },",
    "}",
    "```",
    "",
    "---",
    "",
    "## 레이지 로딩 (코드 분할)",
    "",
    "```ts",
    "// ✅ 동적 import — 각 라우트를 별도 청크로 분리",
    "const routes: RouteRecordRaw[] = [",
    "  {",
    "    path: '/dashboard',",
    "    component: () => import('@/views/Dashboard.vue'),",
    "  },",
    "]",
    "```",
    "",
    "---",
    "",
    "## 스크롤 동작",
    "",
    "```ts",
    "const router = createRouter({",
    "  history: createWebHistory(),",
    "  routes,",
    "  scrollBehavior(to, from, savedPosition) {",
    "    if (savedPosition) return savedPosition     // 뒤로가기 시 위치 복원",
    "    if (to.hash) return { el: to.hash }          // 앵커로 스크롤",
    "    return { top: 0 }                            // 맨 위로",
    "  },",
    "})",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "`createRouter`로 라우터를 생성하고, `<RouterLink>` / `<RouterView>`로 네비게이션과 렌더링을 처리합니다. **동적 경로**(`:id`), **중첩 라우트**(`children`), **네비게이션 가드**(`beforeEach`, `beforeEnter`)로 인증·권한 제어를 구현하며, 동적 `import()`로 코드 분할을 적용합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
