<script setup>
import ArticleHeader from '@/components/ArticleHeader.vue'
import ArticleBody from '@/components/ArticleBody.vue'

const post = {
  id: "vue-form-validation",
  title: "Vue.js 폼 관리와 유효성 검사",
  date: "2026-03-03",
  summary: "Vue의 v-model을 활용한 폼 관리, VeeValidate + Zod를 이용한 스키마 기반 유효성 검사, 실전 회원가입 폼 구현을 TypeScript 예제로 정리합니다.",
  category: "Technology/Vue.js",
  tags: ["vue","form","v-model","vee-validate","zod","validation","typescript"],
  content: [
    "## 한 줄 요약",
    "Vue에서는 `v-model`로 양방향 바인딩 폼을 만들고, **VeeValidate** + **Zod**로 타입 안전한 유효성 검사를 구현합니다.",
    "",
    "---",
    "",
    "## 1. 기본 폼 — v-model 활용",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { reactive, ref } from 'vue'",
    "",
    "interface FormData {",
    "  name: string",
    "  email: string",
    "  password: string",
    "  age: number | null",
    "  agreed: boolean",
    "}",
    "",
    "const form = reactive<FormData>({",
    "  name: '',",
    "  email: '',",
    "  password: '',",
    "  age: null,",
    "  agreed: false,",
    "})",
    "",
    "const errors = reactive<Record<string, string>>({})",
    "",
    "const validate = (): boolean => {",
    "  Object.keys(errors).forEach((k) => delete errors[k])",
    "",
    "  if (!form.name.trim()) errors.name = '이름을 입력하세요'",
    "  if (!/^\\S+@\\S+\\.\\S+$/.test(form.email)) errors.email = '유효한 이메일을 입력하세요'",
    "  if (form.password.length < 8) errors.password = '비밀번호는 8자 이상이어야 합니다'",
    "  if (!form.agreed) errors.agreed = '약관에 동의해주세요'",
    "",
    "  return Object.keys(errors).length === 0",
    "}",
    "",
    "const handleSubmit = () => {",
    "  if (validate()) {",
    "    console.log('제출:', form)",
    "  }",
    "}",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <form @submit.prevent=\"handleSubmit\">",
    "    <div>",
    "      <label>이름</label>",
    "      <input v-model=\"form.name\" />",
    "      <span v-if=\"errors.name\" class=\"error\">{{ errors.name }}</span>",
    "    </div>",
    "    <div>",
    "      <label>이메일</label>",
    "      <input v-model=\"form.email\" type=\"email\" />",
    "      <span v-if=\"errors.email\" class=\"error\">{{ errors.email }}</span>",
    "    </div>",
    "    <div>",
    "      <label>비밀번호</label>",
    "      <input v-model=\"form.password\" type=\"password\" />",
    "      <span v-if=\"errors.password\" class=\"error\">{{ errors.password }}</span>",
    "    </div>",
    "    <div>",
    "      <label>나이</label>",
    "      <input v-model.number=\"form.age\" type=\"number\" />",
    "    </div>",
    "    <div>",
    "      <label><input type=\"checkbox\" v-model=\"form.agreed\" /> 약관 동의</label>",
    "      <span v-if=\"errors.agreed\" class=\"error\">{{ errors.agreed }}</span>",
    "    </div>",
    "    <button type=\"submit\">회원가입</button>",
    "  </form>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 2. VeeValidate + Zod — 스키마 기반 검증",
    "",
    "```bash",
    "npm install vee-validate @vee-validate/zod zod",
    "```",
    "",
    "### 스키마 정의",
    "",
    "```ts",
    "// schemas/signup.ts",
    "import { z } from 'zod'",
    "",
    "export const signupSchema = z.object({",
    "  name: z.string().min(2, '이름은 2자 이상').max(20, '이름은 20자 이하'),",
    "  email: z.string().email('유효한 이메일을 입력하세요'),",
    "  password: z",
    "    .string()",
    "    .min(8, '8자 이상')",
    "    .regex(/[A-Z]/, '대문자 포함')",
    "    .regex(/[0-9]/, '숫자 포함'),",
    "  passwordConfirm: z.string(),",
    "  age: z.number({ invalid_type_error: '숫자를 입력하세요' }).min(14, '14세 이상').optional(),",
    "  agreed: z.literal(true, { errorMap: () => ({ message: '약관에 동의해주세요' }) }),",
    "}).refine((data) => data.password === data.passwordConfirm, {",
    "  message: '비밀번호가 일치하지 않습니다',",
    "  path: ['passwordConfirm'],",
    "})",
    "",
    "export type SignupForm = z.infer<typeof signupSchema>",
    "```",
    "",
    "### 폼 컴포넌트",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { useForm, useField } from 'vee-validate'",
    "import { toTypedSchema } from '@vee-validate/zod'",
    "import { signupSchema, type SignupForm } from '@/schemas/signup'",
    "",
    "const { handleSubmit, errors, isSubmitting } = useForm<SignupForm>({",
    "  validationSchema: toTypedSchema(signupSchema),",
    "})",
    "",
    "const { value: name } = useField<string>('name')",
    "const { value: email } = useField<string>('email')",
    "const { value: password } = useField<string>('password')",
    "const { value: passwordConfirm } = useField<string>('passwordConfirm')",
    "const { value: age } = useField<number>('age')",
    "const { value: agreed } = useField<boolean>('agreed')",
    "",
    "const onSubmit = handleSubmit(async (values) => {",
    "  console.log('검증 통과:', values)",
    "  // API 호출",
    "})",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <form @submit=\"onSubmit\">",
    "    <div>",
    "      <label>이름</label>",
    "      <input v-model=\"name\" />",
    "      <span v-if=\"errors.name\" class=\"error\">{{ errors.name }}</span>",
    "    </div>",
    "    <div>",
    "      <label>이메일</label>",
    "      <input v-model=\"email\" type=\"email\" />",
    "      <span v-if=\"errors.email\" class=\"error\">{{ errors.email }}</span>",
    "    </div>",
    "    <div>",
    "      <label>비밀번호</label>",
    "      <input v-model=\"password\" type=\"password\" />",
    "      <span v-if=\"errors.password\" class=\"error\">{{ errors.password }}</span>",
    "    </div>",
    "    <div>",
    "      <label>비밀번호 확인</label>",
    "      <input v-model=\"passwordConfirm\" type=\"password\" />",
    "      <span v-if=\"errors.passwordConfirm\" class=\"error\">{{ errors.passwordConfirm }}</span>",
    "    </div>",
    "    <div>",
    "      <label>나이</label>",
    "      <input v-model.number=\"age\" type=\"number\" />",
    "      <span v-if=\"errors.age\" class=\"error\">{{ errors.age }}</span>",
    "    </div>",
    "    <div>",
    "      <label><input type=\"checkbox\" v-model=\"agreed\" /> 약관 동의</label>",
    "      <span v-if=\"errors.agreed\" class=\"error\">{{ errors.agreed }}</span>",
    "    </div>",
    "    <button type=\"submit\" :disabled=\"isSubmitting\">회원가입</button>",
    "  </form>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "## 3. 동적 폼 필드",
    "",
    "```vue",
    "\x3cscript setup lang=\"ts\">",
    "import { ref } from 'vue'",
    "",
    "interface FormField {",
    "  id: number",
    "  label: string",
    "  value: string",
    "}",
    "",
    "const fields = ref<FormField[]>([",
    "  { id: 1, label: '기술 1', value: '' },",
    "])",
    "",
    "let nextId = 2",
    "",
    "const addField = () => {",
    "  fields.value.push({ id: nextId++, label: `기술 ${fields.value.length + 1}`, value: '' })",
    "}",
    "",
    "const removeField = (id: number) => {",
    "  fields.value = fields.value.filter((f) => f.id !== id)",
    "}",
    "\x3c/script>",
    "",
    "\x3ctemplate>",
    "  <div v-for=\"field in fields\" :key=\"field.id\">",
    "    <input v-model=\"field.value\" :placeholder=\"field.label\" />",
    "    <button @click=\"removeField(field.id)\">삭제</button>",
    "  </div>",
    "  <button @click=\"addField\">필드 추가</button>",
    "\x3c/template>",
    "```",
    "",
    "---",
    "",
    "### 요약",
    "기본 폼은 `v-model` + `reactive`로 관리하고, 복잡한 유효성 검사는 **VeeValidate** + **Zod** 조합으로 타입 안전하게 구현합니다. `.refine()`으로 교차 필드 검증(비밀번호 확인 등), `useField`로 개별 필드의 반응성 상태와 에러를 관리합니다."
  ]
}
</script>

<template>
  <ArticleHeader :post="post" />
  <ArticleBody :content="post.content" />
</template>
